### ISSUE TITLE
Support for raw aggregation

### ISSUE THREAD

**Issue by bittusarkar** [elastic/elasticsearch-net#1016]
I have developed a custom plugin for Elasticsearch suited for my requirements. It has an implementation of custom query. Till now I was able to use Nest as it supported raw queries. Recently, I've implemented a custom aggregation. But I could not find a way to pass a raw aggregation to the `Search<T>` API. Is there a way I can achieve this without having to pass the entire search string (query, filters, aggregations, fields, etc) in raw format?

**Comment by bittusarkar** [comment]
@Mpdreamz I just saw that Nest 2.0.0-alpha1 is out. Does it have support for raw aggregations yet? Also tentatively when do you plan to release Nest 2.0?

**Comment by Mpdreamz** [comment]
bumping this 2.1 until #1729 is implemented

**Comment by Mpdreamz** [comment]
This is something we wont be able to add support for until 5.0

There is a bug in Elasticsearch 2.x that does not return metadata for pipeline aggregations, @gmarz fixed this though as per https://github.com/elastic/elasticsearch/issues/16484

Using the _metadata greatly simplifies our deserialization so definitely this is still on our radar

https://github.com/elastic/elasticsearch-net/pull/1806

**Comment by bittusarkar** [comment]
Thanks for the update @Mpdreamz. We don't use pipeline aggregations. Will it work for metric aggregations today?

**Comment by gmarz** [comment]
@bittusarkar unfortunately, we can't only support metric aggregations- the deserializer needs to be generalized for all aggregation types.  Even though this is fixed now on the ES end, there are still 2.x versions of ES where it isn't, that we need to maintain support for.  That's why this is now aimed at 5.0.

**Comment by harsimranb** [comment]
Any update on this?  I am also looking to use Raw JSON for aggregators and other DSL properties, instead of c# objects.

**Comment by russcam** [comment]
No further effort has been put into this @harsimranb. For now, you can still use the lowlevel client exposed on the high level client to send raw JSON strings/bytes or anonymous objects for a request, and a return either a low level or high level response.  [See the NOTE in the Getting Started section.](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/nest-getting-started.html#_searching_2)

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Please let us know if this issue is still a relevant priority for your usage?
