### ISSUE TITLE
Mapping validation

### ISSUE THREAD

**Issue by mausch** [elastic/elasticsearch-net#1065]
I'm currently getting this error from Elasticsearch:

```
org.elasticsearch.index.mapper.MapperParsingException: object mapping for [Foo] tried to parse as object, but got EOF, has a concrete value been provided to it?
```

while indexing, which means that the document I'm trying to index doesn't match the mapping.

Firstly, Elasticsearch.net / NEST doesn't seem to show any information about the error in `response.ServerError`.

Secondly, it would be nice to have a mapping validation feature in NEST. As explained in https://github.com/elasticsearch/elasticsearch/issues/2354 , Elasticsearch doesn't really say much about *where* the problem is exactly, it just dumps the offending document with that exception, but it doesn't say which field has the problem.
I tried using https://github.com/atott/es-mapping-validator but that only checks documents that are already in the index, not documents about to get indexed.

**Comment by Mpdreamz** [comment]
Closing this because elasticsearch will now start to output structured json error messages moving (1.6, 2.0?) forward that we can map and expose.
