### ISSUE TITLE
Debugging code containing NEST methods prompts Visual Studio to save the related .cs file

### ISSUE THREAD

**Issue by Ellesedil** [elastic/elasticsearch-net#1067]
When debugging my code that contains NEST methods, Visual Studio will pop up a save dialog box prompting me to save whatever related NEST .cs file is associated with the method in use. Canceling the save request makes debugging, particularly anything involving loops or repeated calls, extremely difficult.

Is there a reason for this and a way to avoid this from happening going forward? I just want to step through my code and seeing that NEST is simply a reference library for my project, I don't particularly care what the NEST method I'm stepping over looks like.

Is this an issue with Copy Local set to true (by default it appears)? I'm on VS 2013. Thanks.

**Comment by luppheim** [comment]
I'm also having this problem. I understand your solution, but I think it's a solution to a different problem. As @Ellesedil says I don't want to step into the NEST source, I just want to have the call treated as a call to Entity Framework or JSON or whatever and not be prompted to delve into a third party source code.
