### ISSUE TITLE
GetMapping should support Indices() and Types()

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch-net#1074]
#1066 made it possible to retrieve mappings for multiple indices and types, but you have to specify them on `GetMappingDescriptor` like so:

    client.GetMapping<Foo>(g => g
        .Index("index1,index2")
        .Type("type1,type2")
    );

This was done for backwards compatibility.

For `2.0`, we should change the base class of `GetMappingDescriptor` to one of the optional type/index path descriptors such as `IIndicesOptionalTypesNamePath` so that the following can be done instead:

    client.GetMapping<Foo>(g => g
        .Indices(new [] { "index1", "index2" })
        .Types(new [] { "type1", "type2"})
    );

**Comment by Mpdreamz** [comment]
No longer relevant and implemented in 2.0
