### ISSUE TITLE
Support inner_hits

### ISSUE THREAD

**Issue by a-lustin-parc** [elastic/elasticsearch-net#1092]
https://github.com/elasticsearch/elasticsearch/blob/d7e224da040c4690052c7b353e84468f39b5a91e/docs/reference/search/request/inner-hits.asciidoc
http://www.elasticsearch.org/guide/en/elasticsearch/reference/1.x/search-request-inner-hits.html

**Comment by a-lustin-parc** [comment]
elastic 1.5 released! @Mpdreamz now it's your turn! :)

**Comment by benbenwilde** [comment]
+1

**Comment by benbenwilde** [comment]
+1

**Comment by benbenwilde** [comment]
Right now I am using NEST to serialize my query, and then manually editing it to add the `inner_hits` section to the JSON. Then I'm making a raw request and using a updated object based on NESTs `SearchResponse<T>` to deserialize the response to something useful. I could potentially PR the updated response object but its not of much use unless we had an updated `SearchDescriptor` too.

**Comment by Mpdreamz** [comment]
Just submitted a PR for this here: https://github.com/elastic/elasticsearch-net/pull/1369

**Comment by benbenwilde** [comment]
Awesome!!

**Comment by gmarz** [comment]
Closed via #1369

**Comment by a-lustin-parc** [comment]
thank you!
