### ISSUE TITLE
Consider using ServiceStack.Text for JSON serialisation

### ISSUE THREAD

**Issue by cocowalla** [elastic/elasticsearch-net#111]
In all benchmarks I have seen on the web, ServiceStack.Text beats Newtonsoft.Json for serialisation performance.

In my own tests, replacing Newtonsoft.Json with ServiceStack.Text in `ElasticClient.GenerateBulkCommand` improved throughout by 25%.

So this line:
`string jsonCommand = ServiceStack.Text.JsonSerializer.SerializeToString<T>(@object);`

Simply became:
`string jsonCommand = JsonConvert.SerializeObject(@object, Formatting.None, IndexSerializationSettings);`

I didn't try using ServiceStack.Text anywhere else, I just wanted to see how much different it would make in the 'serialisation-heavy' part.

**Comment by Mpdreamz** [comment]
closing this issue since moving to SS.TEXT is now less viable, for `2.0` we really would like to prebake as much of the serialization as we can and rely less on JSON.NET. 

No guarantees or hard commitments as of yet but we'll open a new design tickets when we have an attack plan.
