### ISSUE TITLE
How to get group by sum in Elastic search (Nest Client C#)

### ISSUE THREAD

**Issue by sindhusingh** [elastic/elasticsearch-net#1142]
Hi, Can any one please help me to get Group by SUM in elastic search. I am using NEST Client for a dot net(C#) based application.

It will be very helpful for me if a got a working example for it.

**Comment by ShamefulPast** [comment]
Solve the problem?How to deal with the group by multiple fields?

**Comment by russcam** [comment]
@sindhusingh, @ShamefulPast : the best place to ask these questions would be on [discuss](https://discuss.elastic.co/c/elasticsearch). We try to keep issues for bugs, features and issues with the clients. Thanks!
