### ISSUE TITLE
Create a Nest.Contrib library for supporting third-party plugins

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch-net#1144]
https://github.com/elasticsearch/elasticsearch-net/issues/1028
https://github.com/elasticsearch/elasticsearch-net/pull/538

**Comment by niemyjski** [comment]
I'm against having a Nest.Contrib library. I think each plugin should have a library so I don't accidentally use a plugin I don't have installed (discovery). Also, it can be aligned with the specific plugin version you are using.

**Comment by gmarz** [comment]
Fair points.  Although, I'd be more concerned with the versioning issue you bring up rather than the accidental usage a plugin.  I think proper namespacing would do a pretty good job in preventing that.

We are definitely not sold on the idea of a Nest.Contrib either, just toying with the idea and haven't really given it much thought yet.

I think the idea was that it could provide a clear and concise way to extend the client, and we would be able to provide the minimum boiler plate code required in order to "hook" into the client properly.  It also gives us some control over the plugins- enforce conventions (like namespacing mentioned above), run unit tests with our builds, etc...

**Comment by Mpdreamz** [comment]
closing this because general concensus is a single contrib library is not the way to go
