### ISSUE TITLE
Normalize all places that take an expression to represent a path

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#1183]
To take `Expression<Func<T, TReturn>>` over `Expression<Func<T, object>>` this helps to prevent having to do this in F#:

```fsharp
    a.Field(fun p -> p.x :> Object)
```

Which works but is ugly, we should consistently use `TReturn` over `object` everywhere. 

We should also choose between either `OnField` or `Field` everywhere.

**Comment by gmarz** [comment]
+1

Also in favor of using `Field` everywhere as opposed to `OnField`.

**Comment by Mpdreamz** [comment]
Implemented in 2.0
