### ISSUE TITLE
Update doesn't take stringified JSON where Index does

### ISSUE THREAD

**Issue by hisuwh** [elastic/elasticsearch-net#1200]
I had implemented an Elasticsearch solution where a string containing Json was indexed using the Index method.  I was trying to then implement update functionality and was struggling with a problem for a while until I noticed an old issue that mentioned string not working in Index and this subsequently being fixed.

After some investigation this was indeed my problem.  I have got around this for now by parsing to a JObject but it might be worth modifying the Update method so it behaves in the same way as Index.

Thanks everyone though for the great library.

**Comment by Mpdreamz** [comment]
Hi @hisuwh can you share a bit more on the actual calls that you are doing?

Is this using NEST or elasticsearch.net?

**Comment by hisuwh** [comment]
This is using Nest.

**Comment by Mpdreamz** [comment]
Hi @hisuwh I'm afraid I need some more context :)

Can you link me to the issue that you mentioned where it was fixed? 

Also if you can paste the code you are using now using a JObject I might be able to to drill down faster. 

The reason I ask is that NEST does not allow you to pass a string for indexing either see this Stackoverflow answer:

http://stackoverflow.com/questions/23107760/cannot-index-document

So I'm afraid without some code we might not be talking about the same issue here.

**Comment by hisuwh** [comment]
Unfortanely I have been unable to find that issue again since I initially saw it. It might have been in Elasticsearch.Net rather than Nest.

"NEST does not allow you to pass a string for indexing" - this isn't true though because I am passing a string for indexing using Nest, it is treating it as already serialised and it is indexing it
