### ISSUE TITLE
RangeFilter should not force to string

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#1215]
https://github.com/elasticsearch/elasticsearch-net/blob/develop/src/Nest/DSL/Filter/RangeFilterDescriptor.cs#L180

We should simply store From And To as object and let the serializer deal with it. 

Especially with dates having to manually specify the format is not discoverable and not including time zone by default is a bug as well. 

As reported by @mastoj [on twitter] (https://twitter.com/TomasJansson/status/558598011459485696)

**Comment by mastoj** [comment]
I think it might be broken for indexing as well. If the `DateTime` object has a kind specified it doesn't use the kind specified `DateTimeZoneHandling`. For example, if you index a document with a `DateTime` where kind is set to `Local` and then you have `DateTimeZoneHandling` set to `Utc`, it's still serialized as local. But maybe that is how it is supposed to be?

**Comment by Mpdreamz** [comment]
In 2.0 there are dedicated Numeric/DateRange Queries that no longer rely on ToString().
