### ISSUE TITLE
Implement transaction request

### ISSUE THREAD

**Issue by TheHunter** [elastic/elasticsearch-net#1272]
Hi all,
I want to know if It's possible to integrate transactions on ElasticSearch?
Using ElasticClient I don't see any feature for making transactional request on indexes.

Anyone could help me?

**Comment by TheHunter** [comment]
Anyone could help me ???
I hope that is possible, otherwise It couldn't use it for my client ...

**Comment by Mpdreamz** [comment]
We currently do not support `TransactionScope` or anything similar like unit of work.

Elasticsearch itself does not support transactions either so any abstraction we would introduce to mimic transactions would **always** be a bad one.
