### ISSUE TITLE
Why does OnFieldsWithBoost automatically converts capitalized fields into lowercased?

### ISSUE THREAD

**Issue by foresightyj** [elastic/elasticsearch-net#1273]
![image](https://cloud.githubusercontent.com/assets/1296736/6611764/cdda65e2-c8ab-11e4-8232-805f7f8b46f4.png)

`OnFieldsWithBoost` converts all capitalized fields into lowercased, which causes search hits to be zero all the time.

**Comment by gmarz** [comment]
Hey @foresightyj this is by design, and the default behavior of NEST.  Check out this SO question: http://stackoverflow.com/questions/27282865/how-to-disable-camel-casing-elasticsearch-field-names-in-nest/27296871#27296871.

**Comment by foresightyj** [comment]
You are a life saver! Thanks
