### ISSUE TITLE
Nest.MetadataIndexState missing Aliases

### ISSUE THREAD

**Issue by Minx-SigEp** [elastic/elasticsearch-net#1275]
When querying the cluster's state the alias information is missing form the MetadataIndexState object. It is possible to get this information by calling GetAlias or GetAliasAsync, but this then requires an additional request to the cluster. 

```c#
IElasticClient client = _clientProvider.Fetch();
IClusterStateResponse response = await client.ClusterStateAsync();

List<IndexInfo> data = new List<IndexInfo>();
foreach (KeyValuePair<string, MetadataIndexState> index in response.Metadata.Indices)
{
        index.Value.Aliases <= Missing
}
```

**Comment by gmarz** [comment]
Fixed.  Thanks for the report @Minx-SigEp
