### ISSUE TITLE
Ignore property using fluent mapping

### ISSUE THREAD

**Issue by markwalsh-liverpool** [elastic/elasticsearch-net#1278]
Doesn't seem to be the ability in the fluent mapping when creating an index to explicity ignore a field

            var result = client.CreateIndex(indexName, c => c
                .Settings(s => s //just as an example
                    .Add("analysis.analyzer.folding.tokenizer", "standard")
                    .Add("analysis.analyzer.folding.filter.0", "lowercase")
                    .Add("analysis.analyzer.folding.filter.1", "asciifolding")
                )
                .AddMapping<ElasticVideo>(m => m
                    .Type("video")
                    .Properties(props => props
                        .String(s => s
                            .Name("Title")
                            .Index(FieldIndexOption.NotAnalyzed)
                        ))));

**Comment by gmarz** [comment]
Hey @markwalsh-liverpool you don't need to explicitly ignore properties.  By not specifying the field in the mapping call, it simply will not be mapped.  Is that not the case for you?

The only time properties aren't ignored when left out is when `MapFromAttributes()` is used.  However, we introduced https://github.com/elastic/elasticsearch-net/pull/1072 in 1.3 to side step that behavior.

**Comment by markwalsh-liverpool** [comment]
It still maps over for me.  My class (ElasticVideo) has a base class however, do you want me to post my actual code?

**Comment by markwalsh-liverpool** [comment]
*The property which is being mapped over is defined in the base class

**Comment by markwalsh-liverpool** [comment]
Here's all of my code so its, reproducible for any readers

    public class ElasticSearchBaseEntity
    {
        public string ObjectId { get; set; }
    }

    public class ElasticVideo : ElasticSearchBaseEntity
    {
        public string CountryOfOrigin { get; set; }
        public string LanguageOfOrigin { get; set; }
        public string Title { get; set; }
        public string TitleEnglish { get; set; }
        public string Description { get; set; }
        public string DescriptionEnglish { get; set; }
        public string VideoImage { get; set; }
        public int ViewCount { get; set; }
        public int LikesCount { get; set; }
        public int DislikesCount { get; set; }
        public DateTime? Published { get; set; }
        public DateTime? CreatedDate { get; set; }
        public List<string> WatchLater { get; set; }
        public List<string> Favourite { get; set; }
        public VideoStatus Status { get; set; }
        public TranscriptionStatus TranscriptionStatus { get; set; }
        public UploadSource UploadSource { get; set; }
        public bool IsSearchable { get; set; }
        public bool FromProject { get; set; }
        public string NativeTranscription { get; set; }
        public string EnglishTranscription { get; set; }
        public List<string> Tags { get; set; }
        public List<string> Comments { get; set; }
        public List<string> Attributes { get; set; }
        public List<string> Recommendations { get; set; }
        public string ClientId { get; set; }

        public ElasticVideo()
        {
            Tags = new List<string>();
            WatchLater = new List<string>();
            Favourite = new List<string>();
            Comments = new List<string>();
            Attributes = new List<string>();
        }
    }
     public static class ElasticSearchIndexCreator
    {
        public static string Create(string indexName, string languageAnalyzer)
        {
            var connectionSettings = new ConnectionSettings(new Uri("http://localhost:9200"));
            var client = new ElasticClient(connectionSettings);

            var result = client.CreateIndex(indexName, c => c
                .Settings(s => s 
                    .Add("analysis.analyzer.folding.tokenizer", "standard")
                    .Add("analysis.analyzer.folding.filter.0", "lowercase")
                    .Add("analysis.analyzer.folding.filter.1", "asciifolding")
                )
                .AddMapping<ElasticVideo>(m => m
                    .Type("video")
                    .Properties(props => props
                        .String(s => s
                            .Name("CountryOfOrigin")
                            .Index(FieldIndexOption.NotAnalyzed)
                        )
                        .String(s => s
                            .Name("LanguageOfOrigin")
                            .Index(FieldIndexOption.NotAnalyzed)
                        )
                        .MultiField(s => s
                            .Name("Title")
                            .Fields(fs => fs
                                .String(x => x.Name("Title").Analyzer(languageAnalyzer))
                                .String(y => y.Name(t => t.Title.Suffix("folded")).Analyzer("folding"))
                                .String(y => y.Name(t => t.Title.Suffix("raw")).Index(FieldIndexOption.NotAnalyzed)))
                        )
                        .MultiField(s => s
                            .Name("TitleEnglish")
                            .Fields(fs => fs
                                .String(x => x.Name("TitleEnglish").Analyzer("english"))
                                .String(y => y.Name(t => t.TitleEnglish.Suffix("folded")).Analyzer("folding")))

                        )
                        .MultiField(s => s
                            .Name("Description")
                            .Fields(fs => fs
                                .String(x => x.Name("Description").Analyzer(languageAnalyzer))
                                .String(y => y.Name(t => t.Description.Suffix("folded")).Analyzer("folding")))

                        )

                        .MultiField(s => s
                            .Name("DescriptionEnglish")
                            .Fields(fs => fs
                                .String(x => x.Name("DescriptionEnglish").Analyzer("english"))
                                .String(y => y.Name(t => t.DescriptionEnglish.Suffix("folded")).Analyzer("folding")))

                        )
                        .String(s => s
                            .Name("VideoImage")
                            .Index(FieldIndexOption.No)
                        )
                        .String(s => s
                            .Name("ClientId")
                            .Index(FieldIndexOption.NotAnalyzed)
                        )
                        .Number(s => s
                            .Name("ViewCount")
                            .Index(NonStringIndexOption.NotAnalyzed)
                        )
                        .Number(s => s
                            .Name("LikesCount")
                            .Index(NonStringIndexOption.NotAnalyzed)
                        )
                        .Number(s => s
                            .Name("DislikesCount")
                            .Index(NonStringIndexOption.NotAnalyzed)
                        )
                        .Date(s => s
                            .Name("Published")
                            .Index(NonStringIndexOption.NotAnalyzed)
                        )
                        .Date(s => s
                            .Name("CreatedDate")
                            .Index(NonStringIndexOption.NotAnalyzed)
                        )
                        .String(s => s
                            .Name("WatchLater")
                            .Index(FieldIndexOption.NotAnalyzed)
                        )
                        .String(s => s
                            .Name("Favourite")
                            .Index(FieldIndexOption.NotAnalyzed)
                        )
                        .String(s => s
                            .Name("Recommendations")
                            .Index(FieldIndexOption.NotAnalyzed)
                        )
                        .Number(s => s
                            .Name("TranscriptionStatus")
                            .Index(NonStringIndexOption.NotAnalyzed)
                        )
                        .Number(s => s
                            .Name("UploadSource")
                            .Index(NonStringIndexOption.NotAnalyzed)
                        )
                        .Boolean(s => s
                            .Name("FromProject")
                            .Index(NonStringIndexOption.NotAnalyzed)
                        )
                        .Boolean(s => s
                            .Name("IsSearchable")
                            .Index(NonStringIndexOption.NotAnalyzed)
                        )
                        .MultiField(s => s
                            .Name("NativeTranscription")
                            .Fields(fs => fs
                                .String(x => x.Name("NativeTranscription").Analyzer(languageAnalyzer))
                                .String(
                                    y => y.Name(t => t.NativeTranscription.Suffix("folded")).Analyzer("folding")))

                        )
                        .MultiField(s => s
                            .Name("EnglishTranscription")
                            .Fields(fs => fs
                                .String(x => x.Name("EnglishTranscription").Analyzer("english"))
                                .String(
                                    y => y.Name(t => t.EnglishTranscription.Suffix("folded")).Analyzer("folding")))

                        )
                        .MultiField(s => s
                            .Name("Tags")
                            .Fields(fs => fs
                                .String(x => x.Name("Tags").Analyzer(languageAnalyzer))
                                .String(y => y.Name(t => t.Tags.Suffix("folded")).Analyzer("folding")))

                        )
                        .MultiField(s => s
                            .Name("Comments")
                            .Fields(fs => fs
                                .String(x => x.Name("Comments").Analyzer(languageAnalyzer))
                                .String(y => y.Name(t => t.Comments.Suffix("folded")).Analyzer("folding")))

                        )
                        .String(s => s
                            .Name("ClientId")
                            .Index(FieldIndexOption.NotAnalyzed)
                        )
                    )));

            return string.Format(result.RequestInformation.Success ? "Index: {0} created" : "Error: {0} NOT created", indexName);
        }
    }

**Comment by markwalsh-liverpool** [comment]
Could be because the field being mapped (ObjectId) is in a base class

**Comment by gmarz** [comment]
@markwalsh-liverpool mind sharing which properties exactly aren't being ignored?  Also, version of NEST and ES?

**Comment by markwalsh-liverpool** [comment]
Its ObjectId in the ElasticSearchBaseEntity class.
Version of NEST is 1.4.2 and EL 1.4.4.  I haven't tried moving the property into the subclass yet, which I will try tomorrow to see if its still mapped.

**Comment by markwalsh-liverpool** [comment]
Apologies.  I should of posted my full code from the start.

**Comment by gmarz** [comment]
@markwalsh-liverpool I'm not able to reproduce this.  Could you take a look at this [test](https://github.com/elastic/elasticsearch-net/blob/6ba96e91190cfd0cb66145e354de8c7ce16b9b5c/src/Tests/Nest.Tests.Integration/Reproduce/Reproduce1278Tests.cs) and see if you can make it fail?

**Comment by gmarz** [comment]
Hey @markwalsh-liverpool

Thinking about this some more, I realized that your issue is probably `ObjectId` appearing when you index documents.  This is due to the [dynamic mapping](http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-dynamic-mapping.html) behavior of ES when it detects new fields.  You can turn this behavior off by setting `dynamic: false` or `ignore` in your mapping:

```csharp
client.Map<ElasticVideo>(m => m
	.Dynamic(DynamicMappingOption.Ignore)
	...
);
```

```csharp
client.Map<ElasticVideo>(m => m
	.Dynamic(false)
	...
);
```

Keep in mind though, the property will still be present in `_source`.

Alternatively, you can use the fluent ignore property API mentioned above, which will exclude the property entirely from the mapping and `_source` since doing so will cause it to not undergo serialization:

```csharp
var settings = new ConnectionSettings()
	.MapPropertiesFor<ElasticVideo>(m => m
		.Ignore(v => v.ObjectId)
	);

var client = new ElasticClient(settings);
```

or less ideal, just stick Json.NET's `[JsonIgnore]` attribute on the `ObjectId` property.

Hope that helps.  Feel free to re-open this issue if you still run into problems.

**Comment by markwalsh-liverpool** [comment]
Apologies, been AFK.  Yes you are correct, issue resolved.
