### ISSUE TITLE
Add IElasticClient.TemplateExists string overload

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#1280]
I noticed today that I was getting an error when I tried to [delete a template](https://github.com/exceptionless/Exceptionless/blob/master/Source/Core/Repositories/ElasticSearchConfiguration.cs#L43-L44)

So I went and tried wrapping it in an if block and call TemplateExists(string). However, there isn't an overload that just takes a string. GetTemplate, PutTemplate and DeleteTemplate have a string overload.

**Comment by gmarz** [comment]
Added.  Good catch @niemyjski :+1:

**Comment by niemyjski** [comment]
Thanks :), Do you want me to close this issue?

**Comment by gmarz** [comment]
No problem.  It'll be closed once the PR is merged.
