### ISSUE TITLE
EnableHttpCompression() not working with 1.4.2 ES

### ISSUE THREAD

**Issue by lamchakchan** [elastic/elasticsearch-net#1285]
I'm getting an error from ES when compression my request over the wire for PUT/POST request where compressed body is involved.

![capture](https://cloud.githubusercontent.com/assets/1277096/6763749/b196adce-cf58-11e4-930c-209ae404558f.JPG)

![capture](https://cloud.githubusercontent.com/assets/1277096/6763744/819458f6-cf58-11e4-9c0b-703b3f1bdf1c.JPG)

**Comment by gmarz** [comment]
Hi @lamchakchan have you enabled compression on the server?

```
http.compression: true
```

http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-http.html

**Comment by gmarz** [comment]
@lamchakchan I'm going to close this and assume it's resolved.  Feel free to re-open if this is still an issue.
