### ISSUE TITLE
Extracting the request content from Nest client

### ISSUE THREAD

**Issue by redserpent7** [elastic/elasticsearch-net#1288]
Hi,

I was wondering if there is a way to extract the json body of the web request so I can save it in a file? I cannot find a way to instruct the ElasticClient to give me the raw body of the Http request.

**Comment by gmarz** [comment]
You can get the raw request from the `ConnectionStatus.Request` property on the response.

For instance:

```csharp
var result = client.Search<Foo>(s => s.MatchAll());

result.ConnectionStatus.Request <-- raw request
```

The `ConnectionStatusHandler` method on `ConnectionSettings` is a handy way to automatically do something with the `ConnectionStatus` (i.e. log the raw request to a file) for every request:

```csharp
var settings = new ConnectionSettings(...)
    .ConnectionStatusHandler(status => Logger.Log(status.Request));
var client = new ElasticClient(settings);
```
