### ISSUE TITLE
No @timestamp on raw index

### ISSUE THREAD

**Issue by btecu** [elastic/elasticsearch-net#1294]
I'm trying to index some raw objects but no matter one, the `@timestamp` is never set:
`Client.Raw.IndexAsync(myIndex, "fluentd", data)`

I also tried this way without success:
http://stackoverflow.com/questions/26744742/index-a-dynamic-object-using-nest

Note that the index is created by `fluentd` which inserts most of the records and all of them have `@timestamp`.

Any idea?

**Comment by gmarz** [comment]
@btecu can you share your mapping here?  You need to enable `timestamp` as it's disabled by default.  See the docs: http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-timestamp-field.html

**Comment by btecu** [comment]
```
{
  "logstash-2015.04.01": {
  "aliases": {},
  "mappings": {
    "fluentd": {
      "properties": {
        ...,
        "@timestamp": {
          "type": "date",
          "format": "dateOptionalTime"
        },
        ...
      }
   }
}
```

**Comment by gmarz** [comment]
Hey @btecu sorry I misread the issue initially and thought you were referring to the `_timestamp` field, not `@timestamp`.

IIRC, I think I remember running into a similar issue like this in the past and the problem was that `@` is a reserved C# token.  Maybe that's the issue here as well?

Any chance you could post the actual request that's being sent (i.e. the contents of `ConnectionStatus.Request`)?

**Comment by btecu** [comment]
That is correct, `@` is reserved for naming variables with keywords. However, I'm not currently setting `@timestamp`... I just expect Elasticsearch to set it for me. Should I be setting it, somehow?

**Comment by gmarz** [comment]
I think maybe you're confusing the logstash `@timestamp` field and [_timestamp](http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-timestamp-field.html) in Elasticsearch?

You can enable `_timestamp` in which Elasticsearch will indeed set automatically- but not `@timestamp`.

**Comment by btecu** [comment]
I was... On the same index I had `fluentd` indexing records which does sets `@timestamp` and I can use it in `Kibana`. Since my `data` was a json, I ended up adding a field with the timestamp (`JObject`) and now I have a `@timestamp`.
