### ISSUE TITLE
Include support to parse ElasticSearch time units

### ISSUE THREAD

**Issue by aochsner** [elastic/elasticsearch-net#1300]
This is a pretty small start but the goal is to parse http://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#time-units into a TimeSpan.  

I started down this path when I realized that if I set Timeout("20m") on a request (/_cluster/health for example) that I also have to set the RequestConfiguration.RequestTimeout(<millis>).  Longer term, might be nice to do that be default, but not sure the right place to put that.  

Not sure the right place for this but for my tests to work better, it ended up in Elasticsearch.Net instead of NEST.

Also not quite sure what to do about things bigger than a week.  They start to become dependent on DateTime.Now (months aren't always 31 days, years aren't always 365 days).  Even days are a bit incorrect wrt timezones.  But it's a start...

**Comment by gmarz** [comment]
@aochsner thanks for opening this!  You raise a very a good point, it makes sense that `RequesTimeout` always be the same as `Timeout()`.

Before sending the request, we could probably look for a `timeout` query param and set `RequesTimeout` if it's present.

As far as parsing the time values, might make sense to mimic the logic in Elasticsearch: https://github.com/elastic/elasticsearch/blob/master/src/main/java/org/elasticsearch/common/unit/TimeValue.java#L228

**Comment by aochsner** [comment]
Yeah I had seen the `TimeValue` code.  Wasn't completely sure if that's what's used so stuck w/ the time-units doc from above.  But I can easily change that logic and add the additional units. Is it OK to just return null or do you want to have the signature look the same?

Also, any pointer on where to do that inspection for `timeout` query param just before it goes out?

**Comment by gmarz** [comment]
I think returning null is fine if the value passed in is null/empty.  But if parsing fails then I think it's more appropriate to throw the exception.

> Also, any pointer on where to do that inspection for timeout query param just before it goes out?

I think the best place is in [HttpConnection.GetRequestTimeout()](https://github.com/elastic/elasticsearch-net/blob/develop/src/Elasticsearch.Net/Connection/HttpConnection.cs#L420).  You'll just need to add the request URL as another parameter.

Also, thinking about this a bit more, I think it makes more sense to only set the request timeout to the timeout query param if it's > the current request timeout.

@Mpdreamz thoughts?
