### ISSUE TITLE
Can't deserialise And

### ISSUE THREAD

**Issue by abibell** [elastic/elasticsearch-net#1304]
The following elasticsearch JSON query has trouble during deserialisation. However, it works on Elastic server as it is valid syntax. It is similar to https://github.com/elastic/elasticsearch-net/issues/1187. You can use the similar source code to test by changing JSON string input

```javascript
{
   "size": 5,
   "from": 0,
   "query": {
      "filtered": {
         "query": {
            "query_string": {
               "query": "*"
            }
         },
         "filter": {
            "and": [
               {
                  "range": {
                     "Year": {
                        "gte": "2000-10-10T00:00:00",
                        "lte": "2010-10-10T00:00:00"
                     }
                  }
               },
               {
                  "exists": {
                     "field": "identifier"
                  }
               },
               {
                  "exists": {
                     "field": "dateLastModified"
                  }
               },
               {
                  "exists": {
                     "field": "Year"
                  }
               }
            ]
         }
      }
   }
}
```

**Comment by gmarz** [comment]
@abibell What do you mean exactly trouble during deserialization?  I tried reproducing this with an almost identical query and it seems fine.  Also tested serialize => deserialize => serialize and that also passes.

See the above test: https://github.com/elastic/elasticsearch-net/blob/develop/src/Tests/Nest.Tests.Integration/Reproduce/Reproduce1304Tests.cs

**Comment by abibell** [comment]
Hi @gmarz ,

Thanks for quick response.

I found the difference in your test's produced jsonString to reported. In my query there is no **filters array** within **and**. I think that is the issue. Is there an ElasticSearch query grammar documentation somewhere so we can make sure our Serialization matches ES?

**Comment by gmarz** [comment]
Hi @abibell sorry for the delayed response.

Yea, that looks like the issue.  Both forms are valid, but NEST favors the filters array form since it's required in order to make use of the [_cache](http://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-and-filter.html#_caching) param.

Hope that clears things up.
