### ISSUE TITLE
SearchParseException throwed whenever there are documents with $type property

### ISSUE THREAD

**Issue by TheHunter** [elastic/elasticsearch-net#1309]
Hi All,
nowadays, I found a problem whenever My documents located in the same index structure have the $type property.
The $type property surely serve for right deserialization whenever documents are read from consumers, and the reason behind of this behavior is because I could have different types which derive from a base class.
But, this behavior is different whenever I try to load document using the Get method, this works fine, so in the case of trying to use a derived class, that document is deserialized correctly.

Surely, for deserializing documents, I use a custom binder... that this one maps type names with the right Type class.

these are the documents on my index.
{
  "took": 1,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 2,
    "max_score": 1.0,
    "hits": [
      {
        "_index": "polystudent",
        "_type": "student",
        "_id": "1",
        "_score": 1.0,
        "_source": {
          "$type": "Student",
          "id": 1,
          "name": "Name1",
          "size": 1,
          "dataEncoded": "dlskfndlksfnkldsnfkl=",
          "version": 1
        }
      },
      {
        "_index": "polystudent",
        "_type": "student",
        "_id": "2",
        "_score": 1.0,
        "_source": {
          "$type": "StudentDev",
          "university": "home",
          "id": 2,
          "name": "Name2",
          "size": 2,
          "dataEncoded": "dlskfndlksfnkldsnfkl=",
          "version": 1
        }
      }
    ]
  }
}

---------------------------------------
So, when I do the search of this all documents from this index (polystudent) using this code, I get the error from server:

            var client = MakeElasticClient("polystudent");
            var response = client.Search<Student>(descriptor => descriptor
                .From(0)
                .Size(2)
                );

Instead, If I use this code, everything is alright:

            var res0 = client.Get<Student>(1);
            Assert.True(res0.Found);
            var res1 = client.Get<Student>(2);
            Assert.True(res1.Found);

Anyone could help me for this error???

Thanks in advance.

**Comment by TheHunter** [comment]
It seems that the error comes from request reference (calling (HttpWebResponse)request.GetResponse())., this last instruction throws an exception (bad request).

Could anyone understand this error???

**Comment by gmarz** [comment]
Hi @TheHunter can you share the contents of `MakeElasticClient()`?

**Comment by TheHunter** [comment]
Hi @gmarz :
surely..

        private static ElasticClient MakeElasticClient(string defaultIndex)
        {
            var settings = MakeSettings(defaultIndex)
                .ExposeRawResponse()
                .UsePrettyResponses()
                ;

            settings.SetJsonSerializerSettingsModifier(
                delegate(JsonSerializerSettings zz)
                {
                    zz.NullValueHandling = NullValueHandling.Ignore;
                    zz.MissingMemberHandling = MissingMemberHandling.Ignore;
                    zz.TypeNameHandling = TypeNameHandling.Objects;
                    zz.Binder = new CustomBinder(
                        new List<KeyValuePair<string, Type>>
                        {
                            new KeyValuePair<string, Type>("Student", typeof(Student)),
                            new KeyValuePair<string, Type>("StudentDev", typeof(StudentDev)),
                            new KeyValuePair<string, Type>("StudentNew", typeof(StudentDev))
                        });
                    zz.ConstructorHandling = ConstructorHandling.AllowNonPublicDefaultConstructor;
                    zz.ContractResolver = new DynamicContractResolver(settings);
                });
            return new ElasticClient(settings);
        }

        private static ConnectionSettings MakeSettings(string defaultIndex)
        {
            var uri = new Uri("http://localhost:9200");
            var settings = new ConnectionSettings(uri, defaultIndex);
            return settings;
        }

**Comment by TheHunter** [comment]
There are a couple of class that I use ( DynamicContractResolver, CustomBinder )

    public class DynamicContractResolver
        : ElasticContractResolver
    {
        private static readonly Type DynamicType;
        private readonly List<MemberInfo> members;

        static DynamicContractResolver()
        {
            DynamicType = typeof(IDynamicMetaObjectProvider);
        }

        public DynamicContractResolver(IConnectionSettingsValues connectionSettings)
            : base(connectionSettings)
        {
            this.members = new List<MemberInfo>();
        }

        protected override JsonContract CreateContract(Type objectType)
        {
            var contract = base.CreateContract(objectType);

            if (!DynamicType.IsAssignableFrom(objectType))
                return contract;

            /*
            NOTA:
                 * qui faccio una forzatura (alla proprietà che serve per la serializzazione)
                 * per tutti i membri dell'istanza dinamica,
                 * altrimenti i membri non etichettati non verrebbero serializzati.
            */
            dynamic ctr = contract;
            foreach (var prop in ctr.Properties)
            {
                prop.HasMemberAttribute = true;
            }
            return contract;
        }

        protected override List<MemberInfo> GetSerializableMembers(Type objectType)
        {
            var origMembers = base.GetSerializableMembers(objectType);
            this.members.AddRange(origMembers);
            return origMembers;
        }

        protected override string ResolvePropertyName(string propertyName)
        {
            if (propertyName.Equals("$type"))
                Console.WriteLine("ciao");

            try
            {
                if (this.members.Any(info => info.Name.Equals(propertyName)))
                    return base.ResolvePropertyName(propertyName);

                return propertyName;
            }
            catch (Exception ex)
            {
                throw new Exception("ex", ex);
            }
        }

        protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
        {
            var property = base.CreateProperty(member, memberSerialization);
            if (!(member is PropertyInfo))
                return property;

            if (member.Name == "$type")
            {
                Console.WriteLine("ciao...");
                Console.WriteLine(member.Name);
            }

            dynamic prp = member;
            property.Writable = prp.GetSetMethod(true) != null;
            property.Readable = prp.GetGetMethod(true) != null;

            return property;
        }
    }

**Comment by TheHunter** [comment]
The DynamicContractResolver class is used for deserialize dynamic properties, instead CustomBinder class is used for type name handling, so for encode / decode $type value for deserializing the instance.

Thanks in advance!

**Comment by TheHunter** [comment]
@gmarz 
I hope the code is clear for u.

**Comment by TheHunter** [comment]
@gmarz :
have you understood the problem ?
For us, It's important to understand if It's possible to take advantage of polymorphism when our documents are stored into the same collector structure.
I notice that the problem is generated when It's gotten the response from httprequest  (404 error).

Please, tell me if It's possible to find a workaround to this problem.

**Comment by TheHunter** [comment]
Anyone could give me a feedback about this issue ??

theHunter

**Comment by TheHunter** [comment]
Could anybody help for this problem?

Thanks in advance.

**Comment by robertlyson** [comment]
So with this search
```var response = client.Search<Student>(descriptor => descriptor
            .From(0)
            .Size(2));```
you would like to get ```Student```, ```StudentDev```, ```StudentNew``` etc types?

**Comment by TheHunter** [comment]
Yes, surely.
I found a solution to this problem, but I'm curious to know if there is another solution, maybe yours.

**Comment by Mpdreamz** [comment]
@TheHunter, sorry for not being too responsive both me and gmarz just finished a tour through the states and are currently ramping back up to speed, will have a look when I can. 

What would help us tremendously is if you can create a unit test (or separate repository) so we can dive in more quickly without trying to recreate your scenario. Would also be great for us to verify/understand your solution. 

Much appreciated!

**Comment by TheHunter** [comment]
No problem @Mpdreamz 
ok, in a few words whenever you enable $type on Json settings, the instance SearchDescriptor (body of web request for POST verb (I think so)) includes properly the $type (because I've configured like this), but the windows service when receives the request, this one finds $type property, that is not recognize by the deserializer (on service side I intend), so this one throws an exception.
THE SOLUTION... easy... the class NestSerializer is the key of solution.

In my branch (see below) I've commited a new test file (named SearchWithPolymorphismDocs.cs) which contains the test including all classes involved in this test.

Please, I would like to receive a feedback for this solution... maybe There's another smarter solution 
than mine..

https://github.com/TheHunter/elasticsearch-net/commit/940671ebe0fa57cf748e0323786f849aad3a23e1

**Comment by Mpdreamz** [comment]
Ok typically when you set ` zz.TypeNameHandling = TypeNameHandling.Objects;` 

You end up breaking our serialization as well since we might now inject `$type` in our requests as well. 

NEST has a different way to handle covariant results out of the box:

If you index your different students under different elasticsearch search types e.g

```
client.Index<StudentDev>(studentDev);
client.Index<StudentNew>(studentDev);
client.Index<Student>(studentDev);
```

If you then do a search using 

```
client.Search<IStudent>(s=>s
    .Types(typeof(Student), typeof(StudentDev), typeof(StudentNew))
```

Not only will we search across all three types `student,studentdev,studentnew` we will use the `_type` meta data to deserialize each hit in the correct as an actual instance of each subclass. So something like this:

```
result.Documents.OfType<StudentDev>()
```

Will actually work. 

If you have a custom property in your document you can use to differentiate hits actual types you can also introspect the source and return a CLR type to deserialize to.

```
client.Search<IStudent>(s=>s
    .ConcreteTypeSelector((source, hit ) => source.somefield == "mytype" ? typeof(StudentDev) : typeof(StudentNew))
```

Hope this explains it well.

**Comment by TheHunter** [comment]
Hi @Mpdreamz :+1: 
good suggestion, but if you think in detail, your suggestion couldn't be a complete solution, for this case surely (student, studentdev ecc.).
One case could be if a document contains a property which is an interface | not concrete (abstract class) reference, in this situation you need necessarily the $type for deserializing correctly those properties, for example, consider this situation:


    public class MyDocument
    {
        public string MyLoalprop { get; set; }
        public IMyCustomProperty MyInterfaceproperty { get; set; }
    }

    public interface IMyCustomProperty
    {
        string Name { get; set; }
    }

    public class MyCustomProp1 : IMyCustomProperty
    {
        public string Name { get; set; }
    }

    public class MyCustomProp2 : IMyCustomProperty
    {
        public string Name { get; set; }
        public int Code { get; set; }
    }

In order to deserialize correctly the MyInterfaceproperty property from MyDocument instances, IIt's mandatory to have something which instructs to serializer for deserialize correctly that property at runtime, because that property can be any kind of reference which its type implements the IMyCustomProperty interface.

Can you confirm this mine assertion?

I think that It's mandatory to use the $type for this last case.

**Comment by Mpdreamz** [comment]
This is true!

You need to find a way to isolate that `$type` behaviour to that interface/property alone:

sadly I do not think this works

```csharp
[JsonObject(ItemTypeNameHandling = TypeNameHandling.Objects)]
public interface IMyCustomProperty
{
	string Name { get; set; }
}
```

It would be nice if `Json.NET` support `TypeNameHandling` declared on interfaces/classes beyond `ItemTypeNameHandling` which only deals with collection properties. Would be a good feature request there :) 

Applying it at a root level on our serializer is like applying a bazooka that will affect too many other serialization routines.

In the future we hope to prebake all our serialization so that it can be completely isolated from your domain serialization.

**Comment by TheHunter** [comment]
I'm agree with the last paragraph, so documents serialization context must be different with internal serialization context, so in this case the engine of ElasticSearch must use own custom serialization settings.

But maybe there's nothing to do for resolving the original problem, so if you change the settings like this: zz.TypeNameHandling = TypeNameHandling.Auto; the problem is resolved.

Thanks a lot...  @Mpdreamz
