### ISSUE TITLE
Normalize Sort in 2.0

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#1311]
`Sort()` on `SearchDescriptor` works in an unexpected way: you can call it multiple times and mutate `SearchDescriptor`'s state. Where everywhere else chaining the same method twice will override the previous value in a descriptors state. 

Proposal change from: 

```csharp
client.Search<T>(s=>s
    .Sort()
    .SortScript()
)
```

to

```csharp
client.Search<T>(s=>s
    .Sort(sort=>sort
          .Ascending()
          .Descending()
          .ScriptDescending()
         ....
    )
```

**Comment by gmarz** [comment]
Closed via #1646
