### ISSUE TITLE
Unit Test SearchDescriptor

### ISSUE THREAD

**Issue by matt-lethargic** [elastic/elasticsearch-net#1314]
Due to lack of documentation I cannot unit test my SearchDescriptor.
Simple :-)

**Comment by robertlyson** [comment]
[This](http://stackoverflow.com/questions/29239831/accessing-searchdescriptor-properties-for-testing/29240793#29240793) should help you for now.

**Comment by matt-lethargic** [comment]
Cool thanks. Woked a treat. Is there anything different planned for the future??

For future ref:
var query = ((ISearchRequest) searchDescriptor).Query.Match.Query;

**Comment by Mpdreamz** [comment]
No :)

Being able to cast to interfaces is the way to go if you want to unit test your descriptors
