### ISSUE TITLE
How to Implement Starts-With Phrase Search via NEST Client

### ISSUE THREAD

**Issue by sindhusingh** [elastic/elasticsearch-net#1315]
Suppose my Column(On which i am doing Search) have values like below

Assume Record 1 Is----> "TOMMY STICKER THLDEUR 03-IN" 
Assume Record 2 Is----> "STICKER TOMMY TH-00814-IN" 
Assume Record 3 Is----> "STICKER TOMMY - THLDEUR O03-IN" 
Assume Record 4 Is----> "TOMMY JELLY BEANS (20G X 12 UNITS X 12 BOXES)" 
Assume Record 5 Is----> "STICKER TOMMY - TH-00003-IN"

So if i searched "TOMMY" it should only show record 1 and 4 as only they are starting from "TOMMY".

Also i don't want to change(recreate) my indexes as they are very large.

**Comment by gmarz** [comment]
Hi @sindhusingh 

Take a look at the [prefix query](http://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-prefix-query.html) or [prefix filter](http://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-prefix-filter.html).  Keep in mind though that they require your field to not be analyzed to work properly- so you may have to reindex.

A better option would be (however would also require reindexing) to use an analyzer with the [shingle](http://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-shingle-tokenfilter.html) or [edge ngram](http://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-edgengram-tokenfilter.html) token filter applied on your field.  This will increase the size of your index, but in turn will give you better performance than using the prefix query/filter.

Hope that helps.
