### ISSUE TITLE
Offer the ability to disable Pretty Printed JSON over the wire

### ISSUE THREAD

**Issue by pickypg** [elastic/elasticsearch-net#1316]
Currently, NEST will pretty print the HTTP. For those concerned with reducing network traffic, the best option is to use `EnableHttpCompression()`, which exists today on `ConnectionSettings`.

It would be nice to also add the ability to disable pretty printing at the same level, either as an opt-in option (`EnablePrettyPrint()`, thereby changing the current behavior) or as an opt-out feature (`DisablePrettyPrint()`, thereby maintaining the same behavior).

**Comment by klimchuk** [comment]
Actually I'm the one who is interested in this feature. Overhead is pretty big for complex queries.
