### ISSUE TITLE
BulkInsert and document Id.

### ISSUE THREAD

**Issue by HaggeMan** [elastic/elasticsearch-net#1320]
Hi,
-I'm trying to bulk insert documents with the following code...
When I controll the descriptor it returns the correct Id of my id field, but once the document is saved I get the id generated by Elasticsearch. Am I doing it wrong or is there a bug? -I'm using version: 1.4.3

Etc: _id: AUzb-6EX1gWJV-Yxroxu instead of _id: 1

I have also defined... [ElasticType( IdProperty = "Id")] on my ProductES class but didn't help.

```cs
public async Task<bool> Index(List<ProductES> products)
        {

            var descriptor = new BulkDescriptor();
            descriptor.FixedPath("products", "product");
            foreach (var item in products)
            {
                descriptor.Index<ProductES>(op => op
                    .Id(item.Id)
                    .Document(item)
                    .Index("products")
                    .Type("product")
                );
            }
            
            var result = this._client.Bulk(d => descriptor);

            return result.IsValid;

        }
```

Thx for a great component!

**Comment by gmarz** [comment]
Hi @HaggeMan I can't quite reproduce this.

Is the correct id inferred if you do the following on one of your items?

```csharp
var id = this._client.Infer.Id(item);
```

Also, mind sharing your connection settings and `ProductES` POCO?

**Comment by HaggeMan** [comment]
Hi @gmarz,
My ProductES look like this...

[ElasticType( IdProperty = "Id")]
    public class ProductES
    {
        /// <summary>
        /// Constructor
        /// </summary>
        public ProductES()
        {
            ProductTag = 1;
            
            
            Categories = new List<CategoryES>();
            Texts = new List<TextES>();

            Attributes = new List<AttributeES>();
            CustomFields = new List<CustomFieldES>();
            Documents = new List<DocumentES>();
            Relations = new List<RelatedProductES>();

            Created = DateTime.UtcNow;
            Modified = DateTime.UtcNow;
            Origin = "*";
        }

        /// <summary>
        /// The unique product id, will be assigned by the database
        /// </summary>
        public long Id { get; set; }

        /// <summary>
        /// If the product was importned from an external system this is the ID to map against
        /// </summary>
        public string ExternalId { get; set; }

        /// <summary>
        /// The categories the product is connected to
        /// </summary>
        public IEnumerable<CategoryES> Categories { get; set; }

        /// <summary>
        /// The origin (owner of the object)...
        /// * = global
        /// <![CDATA[<instance> - Instance record]]>
        /// <![CDATA[<instance>_<site> - Site record]]>
        /// <![CDATA[<instance>_<site>_<customerGroupNo> - Customer group record]]>
        /// <![CDATA[<instance>_<site>_<customerGroupNo>_<customerNo> - Customer record]]>
        /// </summary>
        public string Origin { get; set; }

        /// <summary>
        /// Unique URI name, to browse to the product
        /// </summary>
        public string URIName { get; set; }

        /// <summary>
        /// The name of the product, etc Apple iPhone 6, Samsung Galaxy 4S
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// The brand: Apple, Samsung
        /// </summary>
        public string Brand { get; set; }

        //public ProductType ProductType { get; set; }
        public int ProductTag { get; set; }

        /// <summary>
        /// If active we'll export the record to the web shops
        /// </summary>
        public bool Active { get; set; }

        /// <summary>
        ///     Defines the image attached to the product, can be inhiert from parent
        /// </summary>
        public string Image { get; set; }

        /// <summary>
        ///     Gets / sets all attributes connected to the product or parent product.
        /// </summary>
        public IList<AttributeES> Attributes { get; set; }

        /// <summary>
        /// The categories the product is connected to
        /// </summary>
        public IEnumerable<TextES> Texts { get; set; }

        public IList<CustomFieldES> CustomFields { get; set; }

        public IList<DocumentES> Documents { get; set; }

        public IList<RelatedProductES> Relations { get; set; }
        
        /// <summary>
        /// The UTC date when the record was created
        /// </summary>
        public System.DateTime Created { get; set; }

        /// <summary>
        /// The UTC date when the record was modified
        /// </summary>
        public System.DateTime Modified { get; set; }
    }

If I run the below code...

public async Task<bool> Index(List<ProductES> products)
        {

            var descriptor = new BulkDescriptor();
            descriptor.FixedPath("products", "product");

            foreach (var item in products)
                 _client.Index(item, i=>i
                    .Index("products")
                    .Type("product")
                    .Id(item.Id)
                );

            return true;
        }

...It works great, the elastic _id gets set to my db integer and assigned to the index: products and type: product. But when indexing approx 5 million documents it won't be the best approch so I really want to bulk insert the records.

My connection wrapper look like this...

public class ElasticClientWrapper : ElasticClient
    {
        
        private static Uri[] nodes = new Uri[]
        {
            new Uri("http://localhost:9200")
        };

        private static StaticConnectionPool pool = new StaticConnectionPool(nodes);

        private static ConnectionSettings _settings = new ConnectionSettings(pool)
                .SetDefaultIndex("products")
                .UsePrettyResponses()
                .SniffOnConnectionFault()
                .SniffOnStartup()
                .SniffLifeSpan(TimeSpan.FromMinutes(1))
                .SetMaximumAsyncConnections(20)
                .MaximumRetries(5)
                .SetJsonSerializerSettingsModifier(x =>
                {
                    x.ContractResolver = new CamelCasePropertyNamesContractResolver();
                    x.DateTimeZoneHandling = DateTimeZoneHandling.Utc;
                    x.PreserveReferencesHandling = PreserveReferencesHandling.All;
                    x.NullValueHandling = NullValueHandling.Ignore;
                    x.Formatting = Formatting.None;
                    x.PreserveReferencesHandling = Newtonsoft.Json.PreserveReferencesHandling.Objects;
                    x.ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Serialize;
                });




        public ElasticClientWrapper() : base(_settings)
        {
            
        }
    }

I added the following code to my foreach...
string id = this._client.Infer.Id<ProductES>(item)

and it returns the id of my document etc id: 1

Thanks for taking time to help me out @gmarz!

**Comment by Mpdreamz** [comment]
You should not have to infer your id since we fallback on that internally already:

https://github.com/elastic/elasticsearch-net/blob/develop/src/Nest/DSL/Bulk/BulkIndexDescriptor.cs#L58-L61

And a quick test using your POCO confirms that it does so correctly:

https://github.com/elastic/elasticsearch-net/blob/ded58687b84a8f1854ca6c73a9c88d437ad6e981/src/Tests/Nest.Tests.Unit/Reproduce/Reproduce1320Tests.cs#L19-L38

So we are missing a piece of the puzzle here :)

Some sidenotes:

We typically do not recommend setting your own ContractResolver and if you do make sure it inherits from `ElasticContractResolver` this is where much of our contracts are configured.

```
.SniffOnConnectionFault()
.SniffOnStartup()
.SniffLifeSpan(TimeSpan.FromMinutes(1))
```

The `StaticConnectionPool` won't do any sniffing so i you want sniffing of your cluster please use the `SniffingConnectionPool`

**Comment by HaggeMan** [comment]
Thanks!
I changed my connection string; removed the ContractResolver and it works. I didn't see that was the cause. I'll close it not a bug!

Once again thx for a nice component around elastic!
