### ISSUE TITLE
Is GetMany convenient?

### ISSUE THREAD

**Issue by vorou** [elastic/elasticsearch-net#1326]
So, I was going to write code to retrieve multiple documents by id. I found that I could do it like this:

```
elasticClient.GetMany<TDocument>(ids)
```

I was happy and felt that I really accomplished everything I could today, so I went to eat some cookies. However, when I came back, I realized that the day wouldn't be as easy as I expected. I found out that:

1. The method returns not documents, but some weird `MultiHits`.
2. The method returns a hit for every id, regardless of whether it found something for that id.

Of course, it wasn't too hard to overcome these hurdles. I wrote an extensions method:

```
public static IEnumerable<TDocument> GetMultiple<TDocument>(this IElasticClient client, IEnumerable<string> ids) where TDocument : class
{
    var hits = client.GetMany<TDocument>(ids);
    var documents = hits.Where(d => d.Found).Select(d => d.Source);
    return documents;
}
```

So, why there isn't such thing in NEST? I think it's what most people would expect from the method based on its signature — it should return *documents* which were *found*. And instead I have some semi-raw elasticsearch output, only strongly-typed.

Just to clarify: I don't want to say that it's a stupid design decision, I want to know the reasoning behind it.

**Comment by Mpdreamz** [comment]
`GetMany` translates into gettting the hits out of the elasticsearch multi get API 
http://www.elastic.co/guide/en/elasticsearch/reference/1.4/docs-multi-get.html 

and internally also simply calls to `client.MultiGet()`:

This API returns the documents wrapped in metadata (_version, _timestamp etcetera) which is often metadata you could be interested in. 

If your are only interested in the `_source` simply call `client.SourceMany()` which translates to your extension method already :)
