### ISSUE TITLE
PropertiesDescriptor<T>.Remove() usage

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#1327]
On `PropertiesDescriptor<T>`, there is a `Remove(string name)` method. From my understanding, this is intended to be used to opt out a property from being included in the mapping for a type i.e. the fluent mapping version of `[ElasticProperty(OptOut = true)]`. 

This appears to work fine when the property is at the top of the object graph (root object) and the property name is camel-cased, but it doesn't seem to work for properties of `object` or `nested` properties, using a camel-cased property name (**not** a string of the path to the property name from the root object).

Looking through the source, the nearest I can get to `[ElasticProperty(OptOut = true)]` using fluent mappings is to cast my `ConnectionSettings` to `IConnectionSettingsValue` and add the `MemberInfo` for each type to the `PropertyMappings` collection with `Ignore` set to true, similar to

``` c#
var propertyInfos = typeof(Model).GetProperties().Where(p => PropertiesToIgnore.Contains(p.Name));
var propertyMapping = new PropertyMapping { Ignore = true };

foreach (var propertyInfo in propertyInfos)
{
      ((IConnectionSettingsValues)connection).PropertyMappings.Add(propertyInfo, propertyMapping);
}
```

I guess what I'm asking is two-fold:

1. Is my understanding of what  `Remove()` is supposed to do correct? If it is, how do I go about using it for nested/object property properties?
2. Could we have an expression based way to ignore properties when using fluent-mappings?

**Comment by Mpdreamz** [comment]
The `Remove` is a bit of an ugly duckling, its there to remove a property that `MapFromAttributes()` would find but that you do not want mapped. 

This is old, wrong and will be marked for removal!

If you want `OptOut` behaviour in code use:

```csharp
new ConnectionSettings()
    .MapPropertiesFor<T>(m=>m
         .Ignore(p=>p.PropertyOnT)
    );
```

Now not only `MapFromAttributes()` ignores it but also it will be ignored when indexing (serialization in general).

Hope this explains it!

**Comment by russcam** [comment]
Thanks! I did see the `MapPropertiesFor<T>` - if I were to use it to ignore some properties, I take it the rest of an object's properties would adhere to the `MapFromAttributes()` and `Properties()` set up?

Any thoughts about exposing `Ignore` on the `PropertyDescriptor<T>`?
