### ISSUE TITLE
More control over AutoMap

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#1328]
For 2.0 it be nice if you could control the default mapping for reflected properties that we map automatically using `MapFromAttributes()`

```
.MapFromAttributes(a=>a
    .String(m => /* set up default string mapping here for reflected properties */ )
    .Match(typeof(MyEnum), m=> ... )
```

`m` would hold information on the current property being reflected. 

Also controversial, should we rename `.MapFromAttributes()` to `.ReflectAllProperties()` in 2.0 ?

**Comment by gmarz** [comment]
`.MapFromAttributes()` has been renamed to `AutoMap()`.

I think this is still a great feature we should implement, but shouldn't block the 2.0 release.

**Comment by Mpdreamz** [comment]
You can now accomplish this by passing a visitor to `AutoMap()`
