### ISSUE TITLE
Inner hits feature

### ISSUE THREAD

**Issue by benbenwilde** [elastic/elasticsearch-net#1330]
Any plans for inner hits feature as is implemented in elasticsearch?

https://github.com/elastic/elasticsearch/pull/8153

**Comment by a-lustin-parc** [comment]
@benbenwilde https://github.com/elastic/elasticsearch-net/issues/1092 just only plans

**Comment by benbenwilde** [comment]
mmm ok I'll have to start +1-ing your issue

**Comment by benbenwilde** [comment]
Closed in favor of #1092
