### ISSUE TITLE
Pass Aggregation using QueryRaw

### ISSUE THREAD

**Issue by neeldeep** [elastic/elasticsearch-net#1337]
I am not able to pass aggregation using QueryRaw. Result returned doesn't contain any "hits" & aggregation

Request JSON:

{
    "query": {
        "filtered": {
            "query": {
                "multi_match": {
                    "query": "main",
                    "type": "cross_fields",
                    "fields": [
                        "field1^5",
                        "field2"
                    ],
                    "operator": "and"
                }
            }
        }
    },
    "aggregations": {
        "multiselectTerms": {
            "terms": {
                "field": "field1.raw",
                "order": {
                    "_count": "desc"
                }
            }
        }
    }
}
```
C# Code:

        [HttpPost]
        public HttpResponseMessage Property(JToken inputRequest) 
        {
            JObject reqObj = JObject.Parse(inputRequest.ToString());
            var uri = new Uri(ConfigurationManager.AppSettings["ELASTICSEARCH_SERVER"]);
            var settings = new ConnectionSettings(uri, defaultIndex: ConfigurationManager.AppSettings["DEFAULT_INDEX"]);
            var client = new ElasticClient(settings);
            
            var resp=client.Search<dynamic>(q =>
                q.Type("mappingType").QueryRaw(reqObj["query"].ToString()).From(Convert.ToInt32(((JValue)reqObj["from"]))).Size(Convert.ToInt32(((JValue)reqObj["size"])))
                );
            
            return Request.CreateResponse(HttpStatusCode.OK, new { total = resp.Total, hits = resp.Hits,aggregations=resp.Aggregations });
        }
```

**Comment by Mpdreamz** [comment]
Won't be able to help you without knowing what `reqObj["query"].ToString()` actually contains.

Since you are enabling TRACE please paste the trace output as well.

**Comment by Mpdreamz** [comment]
Looks like user input so you are sending a query like this:

```
"query" : "value"
```

Which is not a valid elasticsearch query. 

Try .QueryString() for now and see if that returns hits.

**Comment by neeldeep** [comment]
I have updated the Post with JSON Object & C# code.

**Comment by Mpdreamz** [comment]
`.QueryRaw` allows to pass in raw json for the `query` property itself. You can not pass in the whole search request there.
