### ISSUE TITLE
Using a version when It's indexed a new document.

### ISSUE THREAD

**Issue by TheHunter** [elastic/elasticsearch-net#1338]
Hi all,
I would like to know about the usage of __versioning__ whenever I index a new document, for example: 

    var client = MakeElasticClient("myindex");
    var responseIndex = client.Index(myDocument, descriptor => descriptor.Version(1));

in fact I don't really understand Why there's the method __.Version(myversion)__ defined into __IndexDescriptor<T>__ and __IndexRequest<T>__ class.
Maybe because of Index method is used for saving and updating instances ??

Thanks a lot.

**Comment by Mpdreamz** [comment]
This blog post will explain it better then I could ever do :smile: 

https://www.elastic.co/blog/elasticsearch-versioning-support
