### ISSUE TITLE
Support for dist/pre/post options on SpanNotQuery

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch-net#1361]
https://github.com/elastic/elasticsearch/pull/4452

**Comment by robertlyson** [comment]
Looks like it's already [implemented]([https://github.com/elastic/elasticsearch-net/blob/c1fefa18a981ae09232f4345d0a367d5619b2e5f/src/Nest/DSL/Query/SpanNotQueryDescriptor.cs#L105-121).

**Comment by gmarz** [comment]
Indeed, thanks @robertlyson
