### ISSUE TITLE
Mapping of interface types for search

### ISSUE THREAD

**Issue by ddisalvo** [elastic/elasticsearch-net#1371]
I'm not sure I am following the configuration needed to allow searching via interface types.

I want separation of concerns between domain and data models, thus I have an IProduct interface defined and Product implementation with various ES attributes.

ElasticClient is created and I am using:
```
MapDefaultTypeIndices(m => m.Add(typeof(IProduct), "product")
```

This gets me the correct index in the request url, but not the correct ES type when searching via: 
```
client.Search<IProduct>
```
Request url: POST product/iproduct/_search

I see we have MapDefaultTypeNames, and when I add
```
MapDefaultTypeNames(m => m.Add(typeof(IProduct), "product"))
```
I get the Json.Net error:
```
Could not create an instance of type IProduct. Type is an interface or abstract class and cannot be instantiated. Path 'hits.hits[0]._source.type'
```
However the request url looks to be correctly formed with ES type: POST product/product/_search.

Is the expectation that all concrete types be added to Search methods via:
```
ConcreteTypeSelector((o,h) => typeof(Product))
```
This seems like a basic use case and I'm not understanding how to wire up the mappings.

**Comment by Mpdreamz** [comment]
@ddisalvo free day here today, will reply with in detail tomorrow of what kinda tactics you can take here.

**Comment by Mpdreamz** [comment]
the built-in way to handle interfaces is to simply index into multiple elasticsearch types. 

e.g:

```
client.Index<Book>();
client.Index<Dvd>();
client.Index<Couch>();
client.Index<Sandwich>();
client.Index<Lager>();
```

Each of them implementing `IProduct`. 

Then when you do a search use: 

```
var search = client.Search<IProduct>(s=>s
    .Types(typeof(Book), typeof(Dvd), ... ) 
```

Note: `Types()` also takes an `IEnumerable<Type>`

which will do a search on `/products/book,dvd,.../_search` nest can then deserialize all hits to actual instances taking advantage of C# covariant enumerable. e.g `search.Documents.OfType<Book>()` will work here.

If you wish to use a single ES type you can use 

```
ConcreteTypeSelector((o,h) => typeof(Product))
```

But even better would be to register a custom json converter for `IProduct` and making it part of the cached json contract:

```
var settings = new ConnectionSettings(new Uri("http://localhost:9200"))
	.AddContractJsonConverters(
		t => typeof(IProduct).IsAssignableFrom(t) ? new ProductJsonConverter() : null
	);
```

We use a similar (more generalized) pattern internally for reading interfaces using [ReadAsTypeConverter](https://github.com/elastic/elasticsearch-net/blob/develop/src/Nest/Resolvers/Converters/ReadAsTypeConverter.cs#L35) as attributes on the interface itself.

```csharp
[JsonConverter(typeof(ReadAsTypeConverter<MaxAggregator>))]
public interface IMaxAggregator : IMetricAggregator
```

This converter can only read, relying on the default json writer. If we need a specialized writer we use [CompositeJsonConverter](https://github.com/elastic/elasticsearch-net/blob/682bc5293379b1c94b2e94d832fe3c7c5022e9b5/src/Nest/Resolvers/Converters/CompositeJsonConverter.cs)


```csharp
[JsonConverter(typeof(CompositeJsonConverter<ReadAsTypeConverter<QueryContainer>, CustomJsonConverter>))]
IQueryContainer Query { get; set; }
```
