### ISSUE TITLE
Decouple IMultiGetOperation from MLT query

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch-net#1378]
Currently, the MLT query relies on [IMultiGetOperation](https://github.com/elastic/elasticsearch-net/blob/develop/src/Nest/DSL/MultiGet/IMultiGetOperation.cs) to specify documents.  This made sense up until #1377, where MLT specific options have been added (artificial documents and per field analyzer), which are no longer relevant to a get operation.

We should remove `IMultiGetOperation` from the MLT query and introduce a new object for specifying documents.

**Comment by Mpdreamz** [comment]
This has been implemented in 2.0 already.
