### ISSUE TITLE
TypeMappingWriter should default Guid's to string

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#1381]
https://github.com/elastic/elasticsearch-net/blob/develop/src/Nest/Resolvers/Writers/TypeMappingWriter.cs#L260

https://github.com/elastic/elasticsearch-net/issues/322

https://twitter.com/chrismckee/status/595944958135250944

**Comment by ChrisMcKee** [comment]
Don't get rid of attribute mapping.
