### ISSUE TITLE
OrderDescending and OrderAscending cannot be chained for multi-criteria ordering

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch-net#1396]
TermsAggregationDescriptor<T> OrderDescending and OrderAscending blindly create a new Dictionary for each call rather than adding to the Dictionary if it already exists.  This prevents multi-criteria ordering using Fluent syntax.

**Comment by tdoman** [comment]
One more thing I've discovered.  I've noticed that the field `Order` in `ITermsAggregator` is typed as an `IDictionary<string,string>`.  Simply allowing addition of more than one key to a single dictionary will produce something like:
`"order": {
   "avg_rank": "desc",
   "avg_score": "desc"
}`
However, this will cause ES to evaluate only the last ordering specified.
What ES requires is a list, something like:
`"order": [
   {"avg_rank": "desc"},
   {"avg_score": "desc"}
]`
which means `Order` can only be an `IDictionary<string,string>` until a second (or more) ordering criteria is added in which case it must be an `IList<IDictionary<string,string>>`.  I have verified the behavior of both of the JSON examples above.  ES will correctly sub-order the aggregation with the second example.

**Comment by Mpdreamz** [comment]
Hi @tdoman,

Prior to elasticsearch 1.5 you could only have one sort key, this was indeed changed to also accept an array `[]` 

Support for this not make it into our 1.5 though, the ticket we track it under is: https://github.com/elastic/elasticsearch-net/issues/1348 

I started on it but I couldn't implement without introducing breaking changes which for us requires a major version bump for us (due to strongnaming our assemblies we need strict binary assembly compatibility). 

Since we are doing a 2.0 after this we decided to leave this ticket open until NEST 2.0 where we can do a proper remap of terms aggregation order.

**Comment by tdoman** [comment]
Thanks for the reply Martijn.  As a general rule, can we assume that the NEST version supports the features of the like-versioned ES?  If so, I guess this is an example of an exception to the general rule and that's OK.  Mostly I'm curious since you referred NEST 2.0 and I'm wondering if I'd have to wait for ES 2.0 to release in order to get NEST 2.0 and thus, this fix.  If not, what is the current estimate for the release of NEST 2.0?

If so, since you can't do a breaking change w/o a major version bump, might you be able to:
a.) provide a more raw approach in a 1.5 build using a new temporary API to add the order criteria w/ perhaps a type check in the serialization path (IDictionary vs. IList) to properly serialize?
b.) perhaps considering this same type of scenario in the future, provide an API that:
   i.) allows raw JSON string injection or
   ii.) allows objects to be added with a custom serialization callback
   at any point should the need arise?

Some of that sounds pretty drastic but I'd hate to think that being tied to NEST means I can't keep up with the latest versions of ES if NEST lags (or even has a serialization bug) which is totally understandable.  At any rate, for our software, multi-criteria ordering in aggregations is extremely important.  What would be your best guess on availability of NEST 2.0?

**Comment by Mpdreamz** [comment]
Hey Tom,

First off all, knowing that this is something extremely importance we will be damn sure to get it in a `1.5.1` release, shouting at us helps in this case and is very much appreciated :+1: 

The like versioned nature of our current releases are a convenient accident :smile: We typically bump our minor when we introduce a big(ish) new feature which with the last couple releases coincided with feature parity releases. The one guarantee we give off is that when a NEST 1.x release goes out the door we ran our integration tests with all the elasticsearch 1.x version released at that time. 

You totally caught us being lazy to be honest, we found [all the new features we had to support for 1.5](https://github.com/elastic/elasticsearch-net/issues?q=is%3Aissue+label%3Av1.5.0+is%3Aclosed) and this one issue proved to be a possible blocker for 1.5 last friday, so we opted to `"do it later"`. We are going full steam on NEST 2.0 now but that does not mean we won't do bugfix releases on `1.x` even if `2.0` gets out (although we won't support 1.x after 2.0 indefinitely **TBD**).


With NEST 1.0 we moved everything off actual implementations to interfaces even if said interface has only one implementation. Usually i'm totally against this but we did this with extensibility in mind. 

I attached a unit test with a patched `TermsAggregator` that supports multiple sort orders but for future googles let me explain here more explicitly :smile: 

```csharp
public class MyTermsAggregationFix : TermsAggregator
{
	[JsonProperty("order")]
	public new List<TermOrder> TermsOrder { get; set; }
}
```

Where TermOrder is:

```csharp
[JsonConverter(typeof(CustomJsonConverter))]
public class TermOrder : ICustomJson
{
	public string Key { get; set; }
	public SortOrder Order { get; set; }
	public object GetCustomJson()
	{
		return new Dictionary<string, SortOrder> {{this.Key, this.Order}};
	}
}
```

To use `MyTermsAggregationFix` simply use it like so:

```csharp
var order = new List<TermOrder>()
{
	new TermOrder { Key = "x", Order = SortOrder.Ascending},
	new TermOrder { Key = "y", Order = SortOrder.Descending}
};
var agg = new MyTermsAggregationFix
{
	Field = "x",
	TermsOrder = order
};
var search = new SearchRequest
{
	Aggregations = new Dictionary<string, IAggregationContainer>
	{
		{
			"my_terms_agg", new AggregationContainer
			{
				Terms = agg
			}
		}
	}
};
```

This allows you to patch the DSL, without giving up completely on types and go the string json route even though in some place we allow you to inject raw json e.g using [.QueryRaw](https://github.com/elastic/elasticsearch-net/blob/develop/src/Tests/Nest.Tests.Unit/Search/Facets/DateHistogramFacetJson.cs#L15) on search descriptor. 

We need to do a better job at documenting this and we will with 2.0 where we can combine unit testing and writing documentation in a much saner way. See [this example on connecting if you are interested](https://github.com/elastic/elasticsearch-net/blob/spike/literate-tests/src/Tests/Nest.Tests.Literate/ElasticsearchNet/Connecting.cs).

In fact I'll probably use this reply as a unit test later :laughing:

**Comment by tdoman** [comment]
Hey Martijn, awesome!  Thanks for being so responsive, I really appreciate it!  I've been looking at your workaround to see if I could bridge it to the fluent style since all of our code is written that way.  I'm about as new to C# as I am ES (a few months).  I learned how to bridge last week by casting my `TermsAggregationDescriptor` to an `ITermsAggregator` to get access to the `Order` property so I could initialize the dictionary outside `OrderDescending` (which approach, as I commented above, I subsequently discovered wouldn't work ... but I digress).
Would I be able to extend `TermsAggregationDescriptor` just as you did `TermsAggregator` with no other changes?  If not, would you mind showing how I would add custom JSON using the Fluent implementation?

**Comment by tdoman** [comment]
Hey Martijn, not possible? ^^^

**Comment by tdoman** [comment]
Hey guys, I was hoping for a fluent workaround as I said above or some other news.  We're going live with our next round of changes next week and I really need this functionality if I can get it.

**Comment by Mpdreamz** [comment]
@tdoman I will respond this weekend! Friday night here now and had one to many to do commits on master :)

**Comment by tdoman** [comment]
Awesome, thanks a lot Martijn, I really appreciate it!

**Comment by Mpdreamz** [comment]
Attached an updated unit test that showcase how to extend the fluent interface


```csharp
public class MyTermsAggregationsFluentFix<T> : TermsAggregationDescriptor<T>
	where T : class
{
	[JsonProperty("order")]
	internal List<TermOrder> TermsOrder { get; set; }

	public MyTermsAggregationsFluentFix<T> PatchedOrder(List<TermOrder> order)
	{
		this.TermsOrder = order;
		return this;
	}
}
```

then to us it:

```csharp
.Aggregations(aggs=>aggs
	.Terms("my_terms_agg", t=> new MyTermsAggregationsFluentFix<ElasticsearchProject>()
		.PatchedOrder(order)
		.Field("x")
	)
)
```

Its important to call `PatchedOrder()` first because the other fluent methods return an instance of `TermsAggregationDescriptor`.

Hope this helps!

**Comment by tdoman** [comment]
Hi Matijn, tried it, works great!  Thanks again for all your support, it is much appreciated!

**Comment by Mpdreamz** [comment]
I'm closing this in favor of introducing this feature in 2.0 now that we have a "documented" workaround in the `1.x` range.
