### ISSUE TITLE
RawFilters are not written to request when used on filtered aliases

### ISSUE THREAD

**Issue by PaulEpitomy** [elastic/elasticsearch-net#1409]
I believe that cause of this is that the AliasAddOperation.FilterDescriptor property is not decorated with [JsonConverter(typeof(CompositeJsonConverter<ReadAsTypeConverter<FilterContainer>, CustomJsonConverter>))] whereas SearchDescriptor is.

**Comment by gmarz** [comment]
@PaulEpitomy Indeed this is a bug, thanks for reporting!  There may be some other places where this is also an issue, so we'll incorporate this in a larger fix.

**Comment by gmarz** [comment]
Closed via #1422
