### ISSUE TITLE
Bulk is timing out for more than 50000 Request

### ISSUE THREAD

**Issue by maheshbabu7** [elastic/elasticsearch-net#1411]
Hi, 
  I am trying to load more than six millions documents in Elastic. I am using NEST bulk method to insert the records. If my batch size (number of documents per request) is greater than 50K, i am http time out exception.  I am using four core processor and using "parallel.for" to load four batch at a given time. Here is the code for bulk insert:

BulkInsertSymbol:

 protected bool BulkInsertSymbol(List<Symbol> symList)
        {
            bool valid = false;
            try
            {
                ElasticClient client = GetClient();
                if (client != null)
                {
                    IBulkRequest request = new BulkRequest()
                    {
                        Refresh = true,
                        Consistency = Consistency.One

                    };
                    request.Operations = new List<IBulkOperation>();
                    foreach (Symbol symObj in symList)
                    {
                        IBulkCreateOperation<Symbol> symRequest = new BulkCreateOperation<Symbol>(symObj);
                        request.Operations.Add(symRequest);
                    }

                    IBulkResponse response = client.Bulk(request);

                    valid = response.IsValid;
                }

            }
            catch (Exception ex)
            {
                _logger.Error("Exception occured in BulkInsertSymbol method.",ex);
               
            }
            return valid;
        }

Right now, to load six million documents it would take close to 10 minutes, I would like to improve the performance. Please suggest ways to improve performance.

Mahesh Babu

**Comment by gmarz** [comment]
@maheshbabu7 you can try increasing the request timeout via `ConnectionSettings`:

```csharp
new ConnectionSettings().SetTimeout(60000);
```

In terms of performance, check out: https://www.elastic.co/guide/en/elasticsearch/guide/master/indexing-performance.html

Hope that helps.

**Comment by clintongormley** [comment]
Honestly, I think a better solution to this is to decrease the number of documents in each bulk request. It'll be friendlier to memory too.

**Comment by maheshbabu7** [comment]
its working for 50000 as batch. I would like to improve performance, it there any other way to load huge data in Elastic Search.

**Comment by nasreekar** [comment]
@maheshbabu7 Hi Mahesh.. Even I'm doing something like this. But i have to get data from SQL db and index them. I tried doing using IndexMany which is working for 30000 documents as of now. I dont know how it behaves when I try to index 6million documents.  I tried using Bulk also..but not sure if im using the right approach of code or not. 

```
                        List<Class1> feedlist = new List<Class1>();
                        while (reader.Read())
                        {
                            client.Bulk(b => b.Index<Class1>(i => i
                            .Document(new Class1
                            {
                                Id = Int32.Parse(reader[0].ToString()),
                                Title = reader[1].ToString(),
                                BodyContent = reader[2].ToString(),
                                ModifiedDt = Convert.ToDateTime(reader[3].ToString()),
                            }
                            )));
                            //feedlist.Add(fd);
                            count++;
                        }
```

Now I'm trying to index using json file. But not sure how to do it using NEST. I serialized the feedlist to JSON object and i have to index it. All i can find is using curl. But nothing related to NEST. 

Can you please help me solving this using BULK method which you have mentioned above. 

TIA
