### ISSUE TITLE
Using Script for deleting a document field

### ISSUE THREAD

**Issue by TheHunter** [elastic/elasticsearch-net#1414]
Hi everyone,
I would ask you information about how I can delete a document field whenever I need to update a particular document.

I notice that in some cases the below code works well:

            var res2 = client.Update<dynamic>(descriptor => descriptor
                .Id(33)
                .Type<Student>()
                .Script("ctx._source.remove(\"_idsession\")")
                );

In this case, I can delete the field "_idSession", but I had to modify the original name of that field ("$idsession"), and It seems that the "$" char is not accepted when I try to delete it.

Could you please tell me if there's a way in order to delete that field considering the original case (so using "$idsession") ?

Thanks.

**Comment by Mpdreamz** [comment]
You are hitting groovy's string interpolation:

http://docs.groovy-lang.org/latest/html/documentation/index.html#_string_interpolation

It tries to eval `idsession` which does not exist, you need to escape like :` \$idsession`

**Comment by TheHunter** [comment]
Hi @Mpdreamz 
It works perfectly :+1: 

Thanks a lot.
