### ISSUE TITLE
Lets design & provide source code generator for elastic search queries

### ISSUE THREAD

**Issue by abibell** [elastic/elasticsearch-net#1420]
As a follow up to https://github.com/elastic/elasticsearch-net/pull/1416.
# Background

Every time ElasticSearch query syntax changes we need to manually write source code and test it. This is a significant effort. This is probably done over several ElasticSearch client libraries (.net, Ruby and ...). Despite best efforts we miss things and bugs are reported.
# Challenge

Figure out a way where we can just maintain the query schema manually and the source code for query descriptors is generated automatically. Use existing source code as a basis. We have tried using JSON schema and we faced limitations. Ensure serialization/deserialization is builtin.
# Acceptance Criteria
- Changing elasticsearch query syntax and performing an operation should produce latest query source code.
- Provide instructions on **process of converting the query syntax to source code**
- Generated source code must support all available serialization/deserialization NEST abilities at a minimum.
- [Optional] Produce automated unit tests or shell as a framework so we could use.
# Warning

This will take quite a bit of time to develop, right now we are targeting this for version 3.0

**Comment by KodrAus** [comment]
Possibly a candidate for some kind of [interpreter](https://en.m.wikipedia.org/wiki/Interpreter_pattern) implementation? It would be cool to be able to target multiple languages, like C#/F#. It looks like an intense but thoroughly interesting undertaking.

T4 can do a nice job of code generation, but unfortunately I've found the tooling makes it a nuisance for anything but fairly simple tasks. And cross platform is an issue. 

Excuse my ignorance, but how is the query schema maintained? Is it something standard that's generated out of the Elasticsearch project? Is it C# or something else?

**Comment by codebrain** [comment]
This proposition relies on the Elasticsearch REST specification containing definitions for the HTTP request and response bodies. At the moment they do not, so the C# types that model the requests and responses are maintained by hand, by us.

This is an issue that is best raised on the Elasticsearch repository, here:https://github.com/elastic/elasticsearch/issues/25152

We also have a specification generator, which is very much in beta, here: https://github.com/elastic/elastic-client-generator

**Comment by russcam** [comment]
> beta

_alpha_ 😃
