### ISSUE TITLE
RangeFilter is not serialized to JSON

### ISSUE THREAD

**Issue by prychel** [elastic/elasticsearch-net#1424]
Hi, 

I'm using Nest and ElasticSearch.NET and I'm facing problems with Ranges. When I'm searching using created request I'm receiving error "Failed to parse source" because "range" is always null. I'm using NEST.1.5.0 and Elasticsearch.Net.1.5.0

Here is my code:
ISearchRequest request = new SearchRequest();
IQueryContainer query = new QueryContainer();
request.Query = query;
query.Filtered = new FilteredQuery();

if (!String.IsNullOrEmpty(options.SearchTerm))
{
    query.Filtered.Query = new QueryContainer();
    query.Filtered.Query.QueryString = new QueryStringQuery { Query = options.SearchTerm };
}
query.Filtered.Filter = new FilterContainer();
query.Filtered.Filter.Range = new RangeFilter();
query.Filtered.Filter.Range.FilterName = "priceAmount";
query.Filtered.Filter.Range.GreaterThanOrEqualTo = "10";
query.Filtered.Filter.Range.LowerThan = "50";

Here is a json request:
{
  "from": 0,
  "size": 10,
  "query": {
    "filtered": {
      "filter": {
        "range": null
        }
      }
    }
  }

**Comment by gmarz** [comment]
Hey @prychel 

The problem is that you aren't specifying the field to filter on, which is required, so what's happining is the [conditionless construct](https://github.com/elastic/elasticsearch-net/issues/414) is kicking in and returning null.

You need to specify a field:

```csharp
query.Filtered.Filter.Range.Field = "foo";
```
