### ISSUE TITLE
overloads for ElasticsearchClient ctor

### ISSUE THREAD

**Issue by swimtver** [elastic/elasticsearch-net#1425]
I use Structuremap for DI.
When I try to inject ElasticsearchClient with

    For<IElasticsearchClient>()
             .Use(() => new ElasticsearchClient (new ConnectionConfiguration(uri));

I have a problem: first parameter's type is expression, and i get a error from comppller:
_error CS0854: An expression tree may not contain a call or invocation that uses optional arguments_

The way to fix it is create overloads for ctor.

Could you answer me, is it necessary?
I can make this small changes for this library.

this is a old post written by Jimmy Bogard about it.
https://lostechies.com/jimmybogard/2010/05/18/caveats-of-c-4-0-optional-parameters/

**Comment by Mpdreamz** [comment]
@swimtver thanks for the suggestion, I rather not introduce N overloads of all the combinations or require users to pass null for options they do not want. 

An alternative might be to create a subclass of `ElasticsearchClient` ?
