### ISSUE TITLE
ElasticsearchClient should filter index names for invalid characters

### ISSUE THREAD

**Issue by aateeque** [elastic/elasticsearch-net#1426]
I have come across Elasticsearch issues when using ElasticsearchClient to publish to an index. The method I am using is:
`Elasticsearch.Net.IElasticsearchClient.Index(string index, string type, object body, Func<IndexRequestParameters, IndexRequestParameters> requestParameters = null);`

The exception on Elasticsearch server is:
`org.elasticsearch.indices.InvalidIndexNameException: [a name with a space] Invalid index name [a name with a space], must not contain the following characters [\, /, *, ?, ", <, >, |,  , ,]
at org.elasticsearch.cluster.metadata.MetaDataCreateIndexService.validateIndexName(MetaDataCreateIndexService.java:173`

In this case I would ElasticsearchClient to throw an exception because of the unescaped invalid characters before it causes problems on the server.

**Comment by gmarz** [comment]
Hi @aateeque this has been brought up before, and we decided against doing any client side validation like this.  See https://github.com/elastic/elasticsearch-net/issues/1017 for details.

**Comment by aateeque** [comment]
Thanks @gmarz
