### ISSUE TITLE
Query(q=>q.Raw("<json>") Not actually taking in the JSON Query

### ISSUE THREAD

**Issue by Draekane** [elastic/elasticsearch-net#1427]
I have seen this question asked at least one other place with no good answer yet....  When trying to create a Query from a JSON string (in my case, I am trying to create an Object-Agnostic Percolator Proxy microservice and I need to be able to pass everything in as JSON strings), using the Raw function inside the query doesn't actually populate the query.

The code I am trying to run is this:
    var percolateResponse = client.RegisterPercolator<dynamic>(query
        .Name, p=>p
            .Index(index.ActualName)
            .Query(q=>q.Raw(query.Context)));

and the JSON that I have tried using for this is:

    {"query":
        {"term":
            {"banana":
                {"value": "green"}
            }
        }
    }

and 

    {"term":
        {"banana":
            {"value": "green"}
        }
    }

and 

    {"banana":
        {"value": "green"}
    }

And nothing seems to actually populate the Query of the `RegisterPercolatorRequest` and this  then wipes out whatever query I had indexed already.  I have seen another question where someone just had problems in a general query using this as well.  It did the same thing as mine, the query JSON was empty instead of using the raw JSON string to populate the query like we would expect it would.

Are we just doing this wrong, or does that functionality actually not work like that?  And if that is the case, how do we do something like pass a Query into the `RegisterPercolator` via a JSON query if not the above?

Just for reference, the specific error I am getting is this:

    [<indexName>] failed to parse query [<queryName>]]; 
    nested: QueryParsingException[[<indexName>] [_na] query malformed, no field after start_object

**Comment by Draekane** [comment]
I think I have actually found the solution to my problem.  The problem was that I wanted to pass in a JSON query and have it registered in Percolator, but couldn't get Percolator to take a query as above.  Through trial and error though, I found that this worked:

    var percolateResponse = client.RegisterPercolator<dynamic>(query
        .Name, p => p
            .Index(index.ActualName)
            .Query(q => q
                .SimpleQueryString(sqs=>sqs
                    .Query(query.Context))));

This registers my query as I expected it would, and then it properly percolates  and returns the query when I run a document that should match the query across it.

**Comment by gmarz** [comment]
Hey @Draekane thanks for reporting; this is definitely a bug.  Working on a fix- but glad you found a workaround in the mean time.

**Comment by Draekane** [comment]
The workaround doesn't actually work like expected either.  I had to drop down to the Elasticsearch.net client for the final solution....  It is as follows:

    // This is the JSON formatted Query, parsed to a JObject to clean up any \' or \"
    var queryJson = JObject.Parse(query.Context); 
    var percolateResponse = client.Raw.
        IndexPut<dynamic>(
            index.ActualName, 
            ".percolator", 
            query.Name,
             queryJson.ToString(Formatting.None));

**Comment by Mpdreamz** [comment]
This is now fixed for `1.x` in 2.0 raw queries are a full class citizen rather then the hack they are in `1.x`

Thanks for reporting this @Draekane :+1: sorry this took forever to fix.
