### ISSUE TITLE
Missing doc_values property in DateMapping

### ISSUE THREAD

**Issue by Crassirostris** [elastic/elasticsearch-net#1429]
https://www.elastic.co/guide/en/elasticsearch/guide/master/doc-values.html says that doc_values parameter is enabled for date fields, but there is not such property in DateMapping. Could you please help me figure it out? Thanks a lot!

**Comment by gmarz** [comment]
Thanks for reporting @Crassirostris.  Looks like this is also missing for the boolean and geo point field mapping types.
