### ISSUE TITLE
NEST API does not have the possibility to add an array of values to the Include/exclude parameters in a TermsAggregation

### ISSUE THREAD

**Issue by Beckero** [elastic/elasticsearch-net#1430]
When filtering on values in a TermsAggregation, ElasticSearch has added the possibility to enter arrays of exact values in the Include/Exclude parameters from version 1.5.0.
This is not yet available in the NEST API

**Comment by bertvan** [comment]
+1

**Comment by gmarz** [comment]
@Beckero thanks for reporting :+1: , this is now implemented.
