### ISSUE TITLE
Raw JSON response for search queries

### ISSUE THREAD

**Issue by redserpent7** [elastic/elasticsearch-net#1432]
Hi,

I am trying to get the raw JSON response for a search query. 

The query succeeds and returns results yet ```searchResult.ConnectionStatus.ResponseRaw``` is always null. 

P.S. I am using Nest version: 1.5.1

**Comment by gmarz** [comment]
Hi @redserpent7 we read off the stream and don't keep a copy of the raw bytes around by default.  You need to call `ExposeRawResponse()` on `ConnectionSettings` to enable the behavior:

```csharp
new ConnectionSettings().ExposeRawResponse()
```
