### ISSUE TITLE
Need some help returning top_hit values/items

### ISSUE THREAD

**Issue by bobwiller** [elastic/elasticsearch-net#1436]
I have a query that returns the following snippet:

   "aggregations": {
      "sport": {
         "doc_count_error_upper_bound": 0,
         "sum_other_doc_count": 0,
         "buckets": [
            {
               "key": "rugby",
               "doc_count": 16,
               "uniforms": {
                  "doc_count_error_upper_bound": 0,
                  "sum_other_doc_count": 0,
                  "buckets": [
                     {
                        "key": "1",
                        "doc_count": 3,
                        "last_sale": {
                           "hits": {
                              "total": 3,
                              "max_score": null,
                              "hits": [
                                 {
                                    "_index": "sportindex",
                                    "_type": "myobject",
                                    "_id": "15165231",
                                    "_score": null,
                                    "_source": {
                                       "currentPrice": 359,
                                       "endTime": "2011-12-01T21:10:04"
                                    },
                                    "sort": [
                                       1322773804000
                                    ]
                                 }
                              ]
                           }
                        }
                     }
....... additional items removed .....

In my code, I get the Nest.ISearchResponse<MyObject> and I can drill down into the returned aggregations.  However, when I get down to the last_sale item, Nest only seems to return to me a Nest.TopHitsMetric item, (which shows a Total (3) and MaxScore (null)) but the "hits" do not appear to be serialized - which is really what I am after.

My Nest query looks like this:

   var sales = client.Search<MyObject>(s =>
                s.Size(0)
                .QueryRaw(body));

The aggregation portion of my query looks something like this:

                                "aggs": {
                                    "sport": {
                                        "terms": { "field": "sport" },
                                        "aggs": {
                                            "uniform": {
                                                "terms": {
                                                    "field": "sku", "order": { "_term": "asc" }
                                                },
                                    "aggs": {
                                      "last_sale": {
                                            "top_hits" : {
                                                "sort": [{ "endTime": { "order": "desc"}}],
                                                "_source": { "include": [ "endTime", "currentPrice" ]},
                                                "size": 1
                                            }
                                        }
                                    }

Can anyone provide any insight?
Thank you,
Bob

**Comment by gmarz** [comment]
Hi @bobwiller 

How are you pulling the hits from the response?  Can you share your code?

The top hits aggregation response is "lazily deserialized", meaning it's up to the user to specify which types to deserialize to on the response, since they can't be known at the time of the request.

It exposes two methods: `Hits<T>()` to return a collection of `Nest.Hit<T>`s, and `Documents<T>()` which throws out all of the hits meta data and simply returns a collection of `T`s.

For example:

```csharp
var lastSale = result.Aggs.TopHits("last_sale");
var products = lastSale.Hits<Product>().ToList();
```

Hope that makes sense?  If not, post some of your code if possible so we can get a better idea.

**Comment by bobwiller** [comment]
Thanks, the second line is the key - didn't realize they were lazily loaded.  My hits sit a few levels of aggregations down, so it took some work to get to them, but I have it working now.
Much Appreciated,
Bob
