### ISSUE TITLE
ConfigurationManager.AppSettings Context issue

### ISSUE THREAD

**Issue by JasonStein** [elastic/elasticsearch-net#1437]
Here is the issue I'm having right now:

var someValueA = ConfigurationManager.AppSettings["Key"];
var elasticClient = new ElasticClient(...);
var someValueB = ConfigurationManager.AppSettings["Key"];

someValueA is the exact value from my web.config/app.config that I am expecting but someValueB is null, which is wired. Any idea?

**Comment by gmarz** [comment]
Hey @JasonStein 

Weird indeed, but hard to say what's going on here without more info/context, as I'm not able to reproduce this.  Any chance you could put together a simple console app with the bare minimum that repros this?

**Comment by JasonStein** [comment]
Sorry, I'm also not able to reproduce this issue. I have tried both console app and web app. Maybe it is related to other stuff that I am using. However, this issue still happens within my project. Cannot share the original code with you since it's confidential :( If I find out the reason, will let you know. Thanks btw.

**Comment by Mpdreamz** [comment]
NEST does not touch `ConfigurationManager` at all so I'm not convinced this is a bug on our part. Please reopen this if you feel differently @JasonStein :+1:
