### ISSUE TITLE
No GeoPrecision for GeoPoints / GeoPointMappingDescriptors

### ISSUE THREAD

**Issue by jbattermann** [elastic/elasticsearch-net#1438]
I wanted to see if ES's memory usage would improve following the guidlines outlined [here](https://www.elastic.co/guide/en/elasticsearch/guide/current/geo-memory.html) and while GeoShape apparently has an Nest integrated/mapped way of settingthe GeoPrecision, GeoPoint seems to have not.. or I haven't found it yet :)

Is there a way to set the '*precision*' value as shown on the ["Reducing Memory Usage"](https://www.elastic.co/guide/en/elasticsearch/guide/current/geo-memory.html)" article via Nest when creating / updating a mapping for a GeoPoint / location?

Cheers and thanks,
-J

**Comment by gmarz** [comment]
@jbattermann thanks for reporting!  This has been added: https://github.com/elastic/elasticsearch-net/blob/develop/src/Tests/Nest.Tests.Unit/Core/Map/GeoPoint/GeoPointMappingTests.cs#L22
