### ISSUE TITLE
Add Support for murmur3 Field Type

### ISSUE THREAD

**Issue by J-Griffin** [elastic/elasticsearch-net#1441]
The new, "experimental" Cardinality Aggregation talks about a murmur3 field type which allows precomputed hashes to speed up high cardinality fields:

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html#_pre_computed_hashes

Can this be added to the FieldType enum? Is there some backdoor way to specify a field type by string?

**Comment by gmarz** [comment]
@J-Griffin thanks for reporting.  I just opened the above PR to add support for this, but I'm not sure I love the implementation- although there isn't really any other way to go about it without introducing a breaking change.
