### ISSUE TITLE
CountDescriptor.Query IQueryContainer support

### ISSUE THREAD

**Issue by JamieDixon** [elastic/elasticsearch-net#1454]
Presently, `SearchDescriptor.Query` has an overload that takes an `IQueryContainer`.

It would be useful if `CountDescriptor.Query` also had an overload accepting an `IQueryContainer`.

This would allow us to pass the same incoming parameters to either method as required without the need to handle `CountDescriptor.Query` as a special case.

**Comment by gmarz** [comment]
Agreed, this would be useful.  Just thinking that if we did this, we'd have to be consistent and do the same for everywhere we have a `Query()`...

**Comment by Mpdreamz** [comment]
Taking this on board because it was super easy to add, on our `2.0` branch we are making an effort in normalizing this across all descriptors.
