### ISSUE TITLE
Question: Sorting results based on an arbitrary collection

### ISSUE THREAD

**Issue by JamieDixon** [elastic/elasticsearch-net#1455]
I'm searching for products and I need them to be ordered based on Ids in another collection.

Our code looks something like this: https://gist.github.com/JamieDixon/7648e3d52c7ba7b9527b

How would I go about building up this kind of  sort so that we can apply `Skip` and `Take` on the sorted collection without eagerly retrieving all of the items?

Any help greatly appreciated, thanks :)

**Comment by gmarz** [comment]
Not totally sure I understand what you mean by "based on Ids in another collection"?

From your gist:
```
p => bookmarkedProductIds.IndexOf(p.Id)
```
returns an index.  [Sort](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_sort_order) is expecting a field to sort by...

Are you simply trying to sort by the `Id` field?  If that's the case, then what you want is:

```
var result  = client.Search<Product>(s => s
    .Skip(request.Skip)
    .Take(request.Take)
    .SortAscending(p => p.Id)
    .Query(request.Query));
```

Or maybe I'm totally missing something here.

**Comment by JamieDixon** [comment]
Hi Greg,

I don't want to sort by a field I want to sort based on the sort order of another collection.

In the gist, we're retrieving a collecting of product IDs that the user has bookmarked and they're ordered by the date the bookmark was set.

Now I want to get the products that relate to those IDs and I also need them sorted by the date that the bookmark was set. That date isn't available on the product since it's user specific.

As you said based on the gist, doing a standard `OrderBy(p => bookmarkedProductIds.IndexOf(p.Id))` returns a index and `OrderBy` can use this as a way of sorting the items. i.e. The items with the lowest index in the `bookmarkedProductIds` collection ends up higher in the result produced by `OrderBy`.

Let me know how much sense I'm making.

**Comment by gmarz** [comment]
Ah okay, gotcha.  No, that makes total sense...for some reason it was hard to grasp without the context.

Since you'd need to full result set when performing the lookup, this would have be done in ES.  One solution would be using a [script](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html#_script_based_sorting) and passing the collection you want to sort by as a parameter.

Something like:

```csharp
var result  = client.Search<Product>(s => s
    .Skip(request.Skip)
    .Take(request.Take)
    .SortScript(sort => sort
    	.Script("bookmarked_ids.indexOf(doc['id'].value)")
    	.Params(p => p
    		.Add("bookmarked_ids", bookmarkedProductIds)
    	)
    )
    .Query(request.Query)
);

```

**Comment by JamieDixon** [comment]
Thanks Greg. That works a treat. Note, `sort.Type("number")` must be passed along with the Script and Params. Thanks again, we've just saved the lives of a few bits.
