### ISSUE TITLE
Script_File support for NEST

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch-net#1456]
_From @vineet85 on June 14, 2015 20:15_

Hi,

ElasticSearch supports referencing a script which is stored in a file. Eg:-
GET /_search
{
    "script_fields": {
        "my_field": {
            "script_file": "my_script",
            "params": {
              "my_var": 2
            }
        }
    }
}

However the .NET NEST client does not have any support for this yet. Is this going to be added soon?

https://github.com/elastic/elasticsearch-net/blob/4fcecae93dcf16a4ff7e110135da81eed409dda5/src/Nest/DSL/Filter/ScriptFilterDescriptor.cs#L36

Thanks,
Vineet

_Copied from original issue: elastic/elasticsearch#11652_

**Comment by isabel12** [comment]
This would be great - it is best practice to use stored scripts over anything else isn't it?  (https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html)

It would be nice to be able to use scripts safely and disable dynamic scripting.

**Comment by gmarz** [comment]
Just added.  Thanks for reporting @vineet85

**Comment by vineet85** [comment]
*Thanks for the addition. Will this work with the BulkUpdateDescriptor as
well?*

*Eg:-*
*BulkDescriptor childBulkDescriptor = new BulkDescriptor();*

*for (int i = 0; i < searchResponse.Hits.Count(); i++)*
*{*
*childBulkDescriptor.Update<NestedDocument, object>(u => u*
* .Type("document")*
* .Id(searchResponse.Hits.ElementAt(i).Id) // document id*
* .ScriptFile("my_script")*
* .Params(x => x.Add("field_id", fieldIdToUpdate).Add("field_value",
fieldValue))*
* .RetriesOnConflict(4)*
* );*
* }*

*Thanks,*
*Vineet*

On Sun, Jun 14, 2015 at 10:16 PM, Greg Marzouka <notifications@github.com>
wrote:

> Just added. Thanks for reporting @vineet85 <https://github.com/vineet85>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch-net/issues/1456#issuecomment-111909065>
> .
>



-- 
--
Vineet Saju
