### ISSUE TITLE
Best way to create a new alias with existing indexes.

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#1458]
I have migration code that needs to run and create a new alias and add all the existing indexes to said alias (based on a pattern).

I haven't tested this code but I was hoping there was a much better way to do this but didn't see it via the api. I was hoping to see a string[] param where I could past it a list of string indexes. 

```csharp
var indices = client.IndicesStats().Indices.Where(kvp => kvp.Key.StartsWith(index.VersionedName)).Select(kvp => kvp.Key).ToList();
foreach (string name in indices)
    response = client.Alias(a => a.Add(add => add.Index(name).Alias(index.Name)));
```

On a side note, I wish I could create an empty alias that doesn't have any indices, then I could assume it always exists and that I could add to it on insert.

**Comment by gmarz** [comment]
@niemyjski That is indeed the correct way to go about it.  NEST follows the actual _alias API quite strictly in this regard.

That said, I think this is a pretty common use case, so I can see an extension method here being pretty useful.  Perhaps something like `AddMany(string alias, IEnumerable<string> indices)`.  A PR for this would be great. :)

> On a side note, I wish I could create an empty alias that doesn't have any indices, then I could assume it always exists and that I could add to it on insert.

Unfortunately, I don't think this is possible.  An index has aliases, not the other way around...so you always need to associate an index when creating an alias.

**Comment by niemyjski** [comment]
Thanks! If I create an extension method for this. I'll do a pull request.

**Comment by gmarz** [comment]
Great, thanks @niemyjski.  Going to close this issue, but please do feel free to open a PR.
