### ISSUE TITLE
ScriptFile parameter for NEST UpdateDescriptor

### ISSUE THREAD

**Issue by vineet85** [elastic/elasticsearch-net#1459]
Re: https://github.com/elastic/elasticsearch-net/issues/1456

Can this be added to the BulkUpdateDescriptor as well?

https://github.com/elastic/elasticsearch-net/blob/4fcecae93dcf16a4ff7e110135da81eed409dda5/src/Nest/DSL/Bulk/BulkUpdateDescriptor.cs

Eg:-
*BulkDescriptor childBulkDescriptor = new BulkDescriptor();

for (int i = 0; i < searchResponse.Hits.Count(); i++)
{
childBulkDescriptor.Update<NestedDocument, object>(u => u
 .Type("document")
 .Id(searchResponse.Hits.ElementAt(i).Id) // document id
 .ScriptFile("my_script")
 .Params(x => x.Add("field_id", fieldIdToUpdate).Add("field_value",
fieldValue))
.RetriesOnConflict(4)
);
}

Thanks,
Vineet

**Comment by gmarz** [comment]
Added!  Nice catch @vineet85 and thanks again for reporing.

**Comment by vineet85** [comment]
Thanks @gmarz - Any idea when v1.5.2 will be publicly available?

**Comment by gmarz** [comment]
Very soon...debating whether to release 1.5.2 or go straight to 1.6 (pending #1453).

**Comment by CezarCretu** [comment]
This doesn't seem to be working for me using the newly-released 1.6.
I've checked the original request body and the value set for ```ScritpFile``` doesn't get serialized.

Should ```ScriptFile``` and ```ScriptId``` not be added in [BulkUpdateBody](https://github.com/elastic/elasticsearch-net/blob/4fcecae93dcf16a4ff7e110135da81eed409dda5/src/Nest/Domain/Bulk/BulkUpdateBody.cs) and be set [here](https://github.com/elastic/elasticsearch-net/blob/699696fc0c4c7f0b4e75d6b63d98f9427f940282/src/Nest/DSL/Bulk/BulkUpdateDescriptor.cs#L80-L85) or am I just missing something?

**Comment by gmarz** [comment]
Argh, yes, you're right @CezarCretu.  This is my bad...we'll fix and release a 1.6.1 asap.

**Comment by gmarz** [comment]
FYI I opened #1463 for this.
