### ISSUE TITLE
Global aggregation not working

### ISSUE THREAD

**Issue by redserpent7** [elastic/elasticsearch-net#1466]
Hi,

I am trying to follow the example provided in [the documentation](http://nest.azurewebsites.net/nest/aggregations/global.html) to create a global aggregate. However, ES keeps giving me this error: ``Parse Failure [Missing definition for aggregation [global_bucket]]];``

Any idea why I am getting this, I copy/paste the code in the example as is, only changed the field name to match the name of the field in my index.

**Comment by gmarz** [comment]
Hey @redserpent7 this is an error in the docs, it should be:

```csharp
var request = new SearchRequest
{
    Query = new QueryContainer(new MatchQuery
    {
        Field = "country",
        Query = "Malaysia"
    }
    ),
    Aggregations = new Dictionary<string, IAggregationContainer>
    {
        { "global_bucket", new AggregationContainer
            {
                Global = new GlobalAggregator(),
                Aggregations = new Dictionary<string, IAggregationContainer>
                {
                    { "bool_count", new AggregationContainer
                        {
                            Terms = new TermsAggregator
                            {
                                Field = "boolValue"
                            }
                        }
                    }
                }
            }
        }
    }
};
```

We'll correct this ASAP.  Thanks for reporting!
