### ISSUE TITLE
Nest: Filter on enum property doesn't seem to work

### ISSUE THREAD

**Issue by zidad** [elastic/elasticsearch-net#1470]
Hi,

I'm trying to filter an index by a enum property, using a NOT, but I can't get it to work. 

This is how I wrote the code:
```csharp
[Test]
public async Task FilterByEnum()
{
        var response = await client.SearchAsync<TaskInstance>(s => s
             .Index("unit-test")
             .Query(q =>
             {
                  return !q.Term(task => task.Status, TaskStatus.Removed.ToString());
             }));

            var tasks = response.Documents.ToList();
            Assert.AreEqual(0, tasks.Count, "Should not return removed results");
}
```
Note: the 'Status' property has this attribute on it to make it more readable in ES (which is why I pass the enum value as a string):

        [JsonConverter(typeof(StringEnumConverter))]

This data is in ES:
```
_index: unit-test
_type: taskinstance
_id: Test
_score: 1
_source: {
id: Test
status: Removed
progress: 98
log: [ { level: 1 message: Finished } ]
timeStampUtc: 2015-06-25T16:27:24.8092654Z
retryCount: 0
}
```

The resulting query is this: 

```
{
  "query": {
    "bool": {
      "must_not": [
        {
          "term": {
            "status": {
              "value": "Removed"
            }
          }
        }
      ]
    }
  }
}

```

However, it keeps returning that record, while I expect zero results.

Or am I doing something completely wrong? :) 

Thanks!

**Comment by Mpdreamz** [comment]
@zidad what kind of mapping do you have in place for the `status` field?

If you do not have any elasticsearch will split on word boundaries, lowercase the resulting terms and remove stopwords by default. So your `Removed` will actually be stored in the inverted index as `removed`. A term query is not analyzed so it will look for the `Removed` term which does not exist in the inverted index.

Try mapping `status` using `index: not_analyzed` this will use the provided value as a single verbatim token. `Removed` in your case.

**Comment by zidad** [comment]
Oh all right, sorry I'm obviously missing some basic concepts here...  I'm using it too much like RavenDB. Thanks a lot!
