### ISSUE TITLE
FieldIndexOption.NotAnalyzed gives mapping of Analyzed

### ISSUE THREAD

**Issue by sewarts** [elastic/elasticsearch-net#1476]
when creating mapping and setting a fields index to not_analysed, FieldIndexOption.NotAnalyzed sets the mapping of the field in elastic search as analysed. I do understand from here https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping-intro.html that "The other simple types (such as long, double, date etc) also accept the index parameter, but the only relevant values are no and not_analyzed, as their values are never analyzed."

**Comment by gmarz** [comment]
@sewarts can you share your code?

**Comment by sewarts** [comment]
Sure, though I now realise I can just leave it out as it's the default... it's here below for the accounted field.


            client.CreateIndex(Index, Function(c) c.Analysis(Function(descriptor) descriptor.Tokenizers(Function(bases) bases.Add("patterntoke", patterntoke)).TokenFilters(Function(bases) bases.Add("filter_stop", fstop).Add("filter_shingle", fshingle).Add("kill_filters", fkillfilters)).Analyzers(Function(bases) bases.Add("shingles_analyzer", shingles_analyzer).Add("tags_analyzer", tags_analyzer))).AddMapping(Of Ticket)(Function(m) m.Properties(Function(o) o.String(Function(i) i.Name(Function(x) x.description).IndexAnalyzer("shingles_analyzer"))).Properties(Function(o) o.Number(Function(i) i.Name(Function(x) x.accountid).Index(NonStringIndexOption.NotAnalyzed)))))

**Comment by Mpdreamz** [comment]
@sewarts the attached commit verifies that `.Index()` works as expected on number mappings. Closing this issue as a result.
