### ISSUE TITLE
StemExclusionList on LanguageAnalyzer does not work

### ISSUE THREAD

**Issue by monsieur-d** [elastic/elasticsearch-net#1478]
When using the `LanguageAnalyzer` class for registering an Analyzer and using it's property `StemExclusionList`, this list isn't recognized by elastic search because there is a space in the generated Json which doesn't belong there:
```C#
    [JsonProperty("stem_exclusion ")]
    public IEnumerable<string> StemExclusionList { get; set; }
```
This is the relevant snippet from the elastic search source. You can see it on the property parameter after "stem_exclusion".
I hope this helps.

**Comment by gmarz** [comment]
Yikes, nice catch @monsieur-d and thanks for reporting.  This will be fixed in the next release.
