### ISSUE TITLE
Literate Tests that we need to write for 2.0

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#1481]
In `2.0` we are redoing our test architecture so that we can we wrtite our unit/integration tests in one go  while they also serve as compilable documentation thanks to some roslyn magic.  We're dubbing this literate testing.

The new tests (and also much of the client) are layout to mimic the official elasticsearch documentation. 

This lists all the literate tests that we need to write for `2.0` based of the elasticsearch documentation. We have more that deal with client concepts (inferring, failover, connectionsettings) that are outside the scope of this issue.

- [ ] ├── aggregations
- [ ] │   ├── bucket
- [x] │   │   ├── children-aggregation.asciidoc
- [x] │   │   ├── datehistogram-aggregation.asciidoc
- [x] │   │   ├── daterange-aggregation.asciidoc
- [x] │   │   ├── filter-aggregation.asciidoc
- [x] │   │   ├── filters-aggregation.asciidoc
- [ ] │   │   ├── geodistance-aggregation.asciidoc
- [ ] │   │   ├── geohashgrid-aggregation.asciidoc
- [ ] │   │   ├── global-aggregation.asciidoc
- [ ] │   │   ├── histogram-aggregation.asciidoc
- [ ] │   │   ├── iprange-aggregation.asciidoc
- [ ] │   │   ├── missing-aggregation.asciidoc
- [ ] │   │   ├── nested-aggregation.asciidoc
- [ ] │   │   ├── range-aggregation.asciidoc
- [ ] │   │   ├── reverse-nested-aggregation.asciidoc
- [ ] │   │   ├── sampler-aggregation.asciidoc
- [ ] │   │   ├── significantterms-aggregation.asciidoc
- [ ] │   │   └── terms-aggregation.asciidoc
- [ ] │   ├── bucket.asciidoc
- [ ] │   ├── metrics
- [ ] │   │   ├── avg-aggregation.asciidoc
- [ ] │   │   ├── cardinality-aggregation.asciidoc
- [ ] │   │   ├── extendedstats-aggregation.asciidoc
- [ ] │   │   ├── geobounds-aggregation.asciidoc
- [ ] │   │   ├── max-aggregation.asciidoc
- [ ] │   │   ├── min-aggregation.asciidoc
- [ ] │   │   ├── percentile-aggregation.asciidoc
- [ ] │   │   ├── percentile-rank-aggregation.asciidoc
- [ ] │   │   ├── scripted-metric-aggregation.asciidoc
- [ ] │   │   ├── stats-aggregation.asciidoc
- [ ] │   │   ├── sum-aggregation.asciidoc
- [ ] │   │   ├── tophits-aggregation.asciidoc
- [ ] │   │   └── valuecount-aggregation.asciidoc
- [ ] │   ├── metrics.asciidoc
- [ ] │   ├── misc.asciidoc
- [ ] │   ├── pipeline
- [ ] │   │   ├── avg-bucket-aggregation.asciidoc
- [ ] │   │   ├── bucket-script-aggregation.asciidoc
- [ ] │   │   ├── bucket-selector-aggregation.asciidoc
- [ ] │   │   ├── cumulative-sum-aggregation.asciidoc
- [ ] │   │   ├── derivative-aggregation.asciidoc
- [ ] │   │   ├── max-bucket-aggregation.asciidoc
- [ ] │   │   ├── min-bucket-aggregation.asciidoc
- [ ] │   │   ├── movavg-aggregation.asciidoc
- [ ] │   │   └── sum-bucket-aggregation.asciidoc
- [ ] │   └── pipeline.asciidoc
- [ ] ├── aggregations.asciidoc
- [ ] ├── analysis
- [ ] │   ├── analyzers
- [ ] │   │   ├── custom-analyzer.asciidoc
- [ ] │   │   ├── keyword-analyzer.asciidoc
- [ ] │   │   ├── lang-analyzer.asciidoc
- [ ] │   │   ├── pattern-analyzer.asciidoc
- [ ] │   │   ├── simple-analyzer.asciidoc
- [ ] │   │   ├── snowball-analyzer.asciidoc
- [ ] │   │   ├── standard-analyzer.asciidoc
- [ ] │   │   ├── stop-analyzer.asciidoc
- [ ] │   │   └── whitespace-analyzer.asciidoc
- [ ] │   ├── analyzers.asciidoc
- [ ] │   ├── charfilters
- [ ] │   │   ├── htmlstrip-charfilter.asciidoc
- [ ] │   │   ├── mapping-charfilter.asciidoc
- [ ] │   │   └── pattern-replace-charfilter.asciidoc
- [ ] │   ├── charfilters.asciidoc
- [ ] │   ├── icu-plugin.asciidoc
- [ ] │   ├── tokenfilters
- [ ] │   │   ├── apostrophe-tokenfilter.asciidoc
- [ ] │   │   ├── asciifolding-tokenfilter.asciidoc
- [ ] │   │   ├── cjk-bigram-tokenfilter.asciidoc
- [ ] │   │   ├── cjk-width-tokenfilter.asciidoc
- [ ] │   │   ├── classic-tokenfilter.asciidoc
- [ ] │   │   ├── common-grams-tokenfilter.asciidoc
- [ ] │   │   ├── compound-word-tokenfilter.asciidoc
- [ ] │   │   ├── delimited-payload-tokenfilter.asciidoc
- [ ] │   │   ├── edgengram-tokenfilter.asciidoc
- [ ] │   │   ├── elision-tokenfilter.asciidoc
- [ ] │   │   ├── hunspell-tokenfilter.asciidoc
- [ ] │   │   ├── keep-types-tokenfilter.asciidoc
- [ ] │   │   ├── keep-words-tokenfilter.asciidoc
- [ ] │   │   ├── keyword-marker-tokenfilter.asciidoc
- [ ] │   │   ├── keyword-repeat-tokenfilter.asciidoc
- [ ] │   │   ├── kstem-tokenfilter.asciidoc
- [ ] │   │   ├── length-tokenfilter.asciidoc
- [ ] │   │   ├── limit-token-count-tokenfilter.asciidoc
- [ ] │   │   ├── lowercase-tokenfilter.asciidoc
- [ ] │   │   ├── ngram-tokenfilter.asciidoc
- [ ] │   │   ├── normalization-tokenfilter.asciidoc
- [ ] │   │   ├── pattern-capture-tokenfilter.asciidoc
- [ ] │   │   ├── pattern_replace-tokenfilter.asciidoc
- [ ] │   │   ├── phonetic-tokenfilter.asciidoc
- [ ] │   │   ├── porterstem-tokenfilter.asciidoc
- [ ] │   │   ├── reverse-tokenfilter.asciidoc
- [ ] │   │   ├── shingle-tokenfilter.asciidoc
- [ ] │   │   ├── snowball-tokenfilter.asciidoc
- [ ] │   │   ├── standard-tokenfilter.asciidoc
- [ ] │   │   ├── stemmer-override-tokenfilter.asciidoc
- [ ] │   │   ├── stemmer-tokenfilter.asciidoc
- [ ] │   │   ├── stop-tokenfilter.asciidoc
- [ ] │   │   ├── synonym-tokenfilter.asciidoc
- [ ] │   │   ├── trim-tokenfilter.asciidoc
- [ ] │   │   ├── truncate-tokenfilter.asciidoc
- [ ] │   │   ├── unique-tokenfilter.asciidoc
- [ ] │   │   ├── uppercase-tokenfilter.asciidoc
- [ ] │   │   └── word-delimiter-tokenfilter.asciidoc
- [ ] │   ├── tokenfilters.asciidoc
- [ ] │   ├── tokenizers
- [ ] │   │   ├── classic-tokenizer.asciidoc
- [ ] │   │   ├── edgengram-tokenizer.asciidoc
- [ ] │   │   ├── keyword-tokenizer.asciidoc
- [ ] │   │   ├── letter-tokenizer.asciidoc
- [ ] │   │   ├── lowercase-tokenizer.asciidoc
- [ ] │   │   ├── ngram-tokenizer.asciidoc
- [ ] │   │   ├── pathhierarchy-tokenizer.asciidoc
- [ ] │   │   ├── pattern-tokenizer.asciidoc
- [ ] │   │   ├── standard-tokenizer.asciidoc
- [ ] │   │   ├── thai-tokenizer.asciidoc
- [ ] │   │   ├── uaxurlemail-tokenizer.asciidoc
- [ ] │   │   └── whitespace-tokenizer.asciidoc
- [ ] │   └── tokenizers.asciidoc
- [ ] ├── analysis.asciidoc
- [ ] ├── api-conventions.asciidoc
- [ ] ├── cat
- [ ] │   ├── alias.asciidoc
- [ ] │   ├── allocation.asciidoc
- [ ] │   ├── count.asciidoc
- [ ] │   ├── fielddata.asciidoc
- [ ] │   ├── health.asciidoc
- [ ] │   ├── indices.asciidoc
- [ ] │   ├── master.asciidoc
- [ ] │   ├── nodes.asciidoc
- [ ] │   ├── pending_tasks.asciidoc
- [ ] │   ├── plugins.asciidoc
- [ ] │   ├── recovery.asciidoc
- [ ] │   ├── segments.asciidoc
- [ ] │   ├── shards.asciidoc
- [ ] │   └── thread_pool.asciidoc
- [ ] ├── cat.asciidoc
- [ ] ├── cluster
- [ ] │   ├── health.asciidoc
- [ ] │   ├── nodes-hot-threads.asciidoc
- [ ] │   ├── nodes-info.asciidoc
- [ ] │   ├── nodes-stats.asciidoc
- [ ] │   ├── pending.asciidoc
- [ ] │   ├── reroute.asciidoc
- [ ] │   ├── state.asciidoc
- [ ] │   ├── stats.asciidoc
- [ ] │   └── update-settings.asciidoc
- [ ] ├── cluster.asciidoc
- [ ] ├── docs
- [ ] │   ├── bulk.asciidoc
- [ ] │   ├── delete-by-query.asciidoc
- [ ] │   ├── delete.asciidoc
- [ ] │   ├── get.asciidoc
- [x] │   ├── index_.asciidoc
- [ ] │   ├── multi-get.asciidoc
- [ ] │   ├── multi-termvectors.asciidoc
- [ ] │   ├── termvectors.asciidoc
- [ ] │   └── update.asciidoc
- [ ] ├── docs.asciidoc
- [ ] ├── getting-started.asciidoc
- [ ] ├── glossary.asciidoc
- [ ] ├── index-modules
- [ ] │   ├── allocation
- [ ] │   │   ├── delayed.asciidoc
- [ ] │   │   ├── filtering.asciidoc
- [ ] │   │   └── total_shards.asciidoc
- [ ] │   ├── allocation.asciidoc
- [ ] │   ├── analysis.asciidoc
- [ ] │   ├── mapper.asciidoc
- [ ] │   ├── merge.asciidoc
- [ ] │   ├── similarity.asciidoc
- [ ] │   ├── slowlog.asciidoc
- [ ] │   ├── store.asciidoc
- [ ] │   └── translog.asciidoc
- [ ] ├── index-modules.asciidoc
- [ ] ├── index.asciidoc
- [ ] ├── indices
- [ ] │   ├── aliases.asciidoc
- [ ] │   ├── analyze.asciidoc
- [ ] │   ├── clearcache.asciidoc
- [ ] │   ├── create-index.asciidoc
- [ ] │   ├── delete-index.asciidoc
- [ ] │   ├── flush.asciidoc
- [ ] │   ├── get-field-mapping.asciidoc
- [ ] │   ├── get-index.asciidoc
- [ ] │   ├── get-mapping.asciidoc
- [ ] │   ├── get-settings.asciidoc
- [ ] │   ├── indices-exists.asciidoc
- [ ] │   ├── open-close.asciidoc
- [ ] │   ├── optimize.asciidoc
- [ ] │   ├── put-mapping.asciidoc
- [ ] │   ├── recovery.asciidoc
- [ ] │   ├── refresh.asciidoc
- [ ] │   ├── segments.asciidoc
- [ ] │   ├── shadow-replicas.asciidoc
- [ ] │   ├── stats.asciidoc
- [ ] │   ├── templates.asciidoc
- [ ] │   ├── types-exists.asciidoc
- [ ] │   ├── update-settings.asciidoc
- [ ] │   ├── upgrade.asciidoc
- [ ] │   └── warmers.asciidoc
- [ ] ├── indices.asciidoc
- [ ] ├── mapping
- [ ] │   ├── date-format.asciidoc
- [ ] │   ├── dynamic-mapping.asciidoc
- [ ] │   ├── fielddata_formats.asciidoc
- [ ] │   ├── fields
- [ ] │   │   ├── all-field.asciidoc
- [ ] │   │   ├── field-names-field.asciidoc
- [ ] │   │   ├── id-field.asciidoc
- [ ] │   │   ├── index-field.asciidoc
- [ ] │   │   ├── parent-field.asciidoc
- [ ] │   │   ├── routing-field.asciidoc
- [ ] │   │   ├── size-field.asciidoc
- [ ] │   │   ├── source-field.asciidoc
- [ ] │   │   ├── timestamp-field.asciidoc
- [ ] │   │   ├── ttl-field.asciidoc
- [ ] │   │   ├── type-field.asciidoc
- [ ] │   │   └── uid-field.asciidoc
- [ ] │   ├── fields.asciidoc
- [ ] │   ├── meta.asciidoc
- [ ] │   ├── transform.asciidoc
- [ ] │   ├── types
- [ ] │   │   ├── array-type.asciidoc
- [ ] │   │   ├── attachment-type.asciidoc
- [ ] │   │   ├── core-types.asciidoc
- [ ] │   │   ├── geo-point-type.asciidoc
- [ ] │   │   ├── geo-shape-type.asciidoc
- [ ] │   │   ├── ip-type.asciidoc
- [ ] │   │   ├── nested-type.asciidoc
- [ ] │   │   ├── object-type.asciidoc
- [ ] │   │   └── root-object-type.asciidoc
- [ ] │   └── types.asciidoc
- [ ] ├── mapping.asciidoc
- [ ] ├── migration
- [ ] │   ├── index.asciidoc
- [ ] │   ├── migrate_1_0.asciidoc
- [ ] │   ├── migrate_1_4.asciidoc
- [ ] │   ├── migrate_1_6.asciidoc
- [ ] │   └── migrate_2_0.asciidoc
- [ ] ├── modules
- [ ] │   ├── advanced-scripting.asciidoc
- [ ] │   ├── cluster
- [ ] │   │   ├── allocation_awareness.asciidoc
- [ ] │   │   ├── allocation_filtering.asciidoc
- [ ] │   │   ├── disk_allocator.asciidoc
- [ ] │   │   ├── misc.asciidoc
- [ ] │   │   └── shards_allocation.asciidoc
- [ ] │   ├── cluster.asciidoc
- [ ] │   ├── discovery
- [ ] │   │   ├── azure.asciidoc
- [ ] │   │   ├── ec2.asciidoc
- [ ] │   │   ├── gce.asciidoc
- [ ] │   │   └── zen.asciidoc
- [ ] │   ├── discovery.asciidoc
- [ ] │   ├── gateway.asciidoc
- [ ] │   ├── http.asciidoc
- [ ] │   ├── indices
- [ ] │   │   ├── circuit_breaker.asciidoc
- [ ] │   │   ├── fielddata.asciidoc
- [ ] │   │   ├── indexing_buffer.asciidoc
- [ ] │   │   ├── query_cache.asciidoc
- [ ] │   │   ├── recovery.asciidoc
- [ ] │   │   ├── request_cache.asciidoc
- [ ] │   │   └── ttl_interval.asciidoc
- [ ] │   ├── indices.asciidoc
- [ ] │   ├── memcached.asciidoc
- [ ] │   ├── network.asciidoc
- [ ] │   ├── node.asciidoc
- [ ] │   ├── plugins.asciidoc
- [ ] │   ├── scripting.asciidoc
- [ ] │   ├── snapshots.asciidoc
- [ ] │   ├── threadpool.asciidoc
- [ ] │   ├── thrift.asciidoc
- [ ] │   ├── transport.asciidoc
- [ ] │   └── tribe.asciidoc
- [ ] ├── modules.asciidoc
- [ ] ├── query-dsl
- [ ] │   ├── and-query.asciidoc
- [ ] │   ├── bool-query.asciidoc
- [ ] │   ├── boosting-query.asciidoc
- [ ] │   ├── common-terms-query.asciidoc
- [ ] │   ├── compound-queries.asciidoc
- [ ] │   ├── constant-score-query.asciidoc
- [ ] │   ├── dis-max-query.asciidoc
- [ ] │   ├── exists-query.asciidoc
- [ ] │   ├── filtered-query.asciidoc
- [ ] │   ├── full-text-queries.asciidoc
- [ ] │   ├── function-score-query.asciidoc
- [ ] │   ├── fuzzy-query.asciidoc
- [ ] │   ├── geo-bounding-box-query.asciidoc
- [ ] │   ├── geo-distance-query.asciidoc
- [ ] │   ├── geo-distance-range-query.asciidoc
- [ ] │   ├── geo-polygon-query.asciidoc
- [ ] │   ├── geo-queries.asciidoc
- [ ] │   ├── geo-shape-query.asciidoc
- [ ] │   ├── geohash-cell-query.asciidoc
- [ ] │   ├── has-child-query.asciidoc
- [ ] │   ├── has-parent-query.asciidoc
- [ ] │   ├── ids-query.asciidoc
- [ ] │   ├── indices-query.asciidoc
- [ ] │   ├── joining-queries.asciidoc
- [ ] │   ├── limit-query.asciidoc
- [ ] │   ├── match-all-query.asciidoc
- [ ] │   ├── match-query.asciidoc
- [ ] │   ├── minimum-should-match.asciidoc
- [ ] │   ├── missing-query.asciidoc
- [ ] │   ├── mlt-query.asciidoc
- [ ] │   ├── multi-match-query.asciidoc
- [ ] │   ├── multi-term-rewrite.asciidoc
- [ ] │   ├── nested-query.asciidoc
- [ ] │   ├── not-query.asciidoc
- [ ] │   ├── or-query.asciidoc
- [ ] │   ├── prefix-query.asciidoc
- [ ] │   ├── query-string-query.asciidoc
- [ ] │   ├── query-string-syntax.asciidoc
- [ ] │   ├── query_filter_context.asciidoc
- [ ] │   ├── range-query.asciidoc
- [ ] │   ├── regexp-query.asciidoc
- [ ] │   ├── regexp-syntax.asciidoc
- [ ] │   ├── script-query.asciidoc
- [ ] │   ├── simple-query-string-query.asciidoc
- [ ] │   ├── span-containing-query.asciidoc
- [ ] │   ├── span-first-query.asciidoc
- [ ] │   ├── span-multi-term-query.asciidoc
- [ ] │   ├── span-near-query.asciidoc
- [ ] │   ├── span-not-query.asciidoc
- [ ] │   ├── span-or-query.asciidoc
- [ ] │   ├── span-queries.asciidoc
- [ ] │   ├── span-term-query.asciidoc
- [ ] │   ├── span-within-query.asciidoc
- [ ] │   ├── special-queries.asciidoc
- [ ] │   ├── template-query.asciidoc
- [ ] │   ├── term-level-queries.asciidoc
- [ ] │   ├── term-query.asciidoc
- [ ] │   ├── terms-query.asciidoc
- [ ] │   ├── type-query.asciidoc
- [ ] │   └── wildcard-query.asciidoc
- [ ] ├── query-dsl.asciidoc
- [ ] ├── redirects.asciidoc
- [ ] ├── search
- [ ] │   ├── count.asciidoc
- [ ] │   ├── exists.asciidoc
- [ ] │   ├── explain.asciidoc
- [ ] │   ├── field-stats.asciidoc
- [ ] │   ├── multi-search.asciidoc
- [ ] │   ├── percolate.asciidoc
- [ ] │   ├── request
- [ ] │   │   ├── explain.asciidoc
- [ ] │   │   ├── fielddata-fields.asciidoc
- [ ] │   │   ├── fields.asciidoc
- [ ] │   │   ├── from-size.asciidoc
- [ ] │   │   ├── highlighting.asciidoc
- [ ] │   │   ├── index-boost.asciidoc
- [ ] │   │   ├── inner-hits.asciidoc
- [ ] │   │   ├── min-score.asciidoc
- [ ] │   │   ├── named-queries-and-filters.asciidoc
- [ ] │   │   ├── post-filter.asciidoc
- [ ] │   │   ├── preference.asciidoc
- [ ] │   │   ├── query.asciidoc
- [ ] │   │   ├── rescore.asciidoc
- [ ] │   │   ├── script-fields.asciidoc
- [ ] │   │   ├── scroll.asciidoc
- [ ] │   │   ├── search-type.asciidoc
- [ ] │   │   ├── sort.asciidoc
- [ ] │   │   ├── source-filtering.asciidoc
- [ ] │   │   └── version.asciidoc
- [ ] │   ├── request-body.asciidoc
- [ ] │   ├── search-shards.asciidoc
- [ ] │   ├── search-template.asciidoc
- [ ] │   ├── search.asciidoc
- [ ] │   ├── suggesters
- [ ] │   │   ├── completion-suggest.asciidoc
- [ ] │   │   ├── context-suggest.asciidoc
- [ ] │   │   ├── phrase-suggest.asciidoc
- [ ] │   │   └── term-suggest.asciidoc
- [ ] │   ├── suggesters.asciidoc
- [ ] │   ├── uri-request.asciidoc
- [ ] │   └── validate.asciidoc
- [ ] ├── search.asciidoc

**Comment by robertlyson** [comment]
Concept looks great guys!

Happy to help. May you point a sample test? So it would be easier to follow.
Also, are you going to create some kind of todo list, so we can attache PRs?

**Comment by tkirill** [comment]
This sounds incredible!  It would be really interesting to see the result!

**Comment by Mpdreamz** [comment]
Hey @robertlyson and @tkirill  

Currently we are working in the `logical-grouping` branch but we are merging that into `2.0` today, There are about [120 refactoring commits](https://github.com/elastic/elasticsearch-net/compare/2.0...feature/logical-grouping) in there. I'll open another checkbox ticket tomorrow that tries to list all the (breaking) changes that are going into 2.0. 

The idea behind the testing is that we now only have 1 test project (instead of the 5 we had previously) simply called [Tests](https://github.com/elastic/elasticsearch-net/tree/feature/logical-grouping/src/Tests)

If we look at an example [FromAndSize.cs](https://github.com/elastic/elasticsearch-net/blob/feature/logical-grouping/src/Tests/Search/Request/FromAndSize.cs)

You can see it [uses comments](https://github.com/elastic/elasticsearch-net/blob/feature/logical-grouping/src/Tests/Search/Request/FromAndSize.cs) that [becomes part of the documentation](https://github.com/elastic/elasticsearch-net/blob/feature/logical-grouping/docs/contents/new/Search/Request/FromAndSize.asciidoc). The idea is that we automatically take the [Initializer](https://github.com/elastic/elasticsearch-net/blob/feature/logical-grouping/src/Tests/Search/Request/FromAndSize.cs#L23) and [Fluent](https://github.com/elastic/elasticsearch-net/blob/feature/logical-grouping/src/Tests/Search/Request/FromAndSize.cs#L30) and use it as the documentation. The calls they go into are specified in to [ClientUsage()](https://github.com/elastic/elasticsearch-net/blob/feature/logical-grouping/src/Tests/Search/SearchUsageBase.cs#L21) method each `UsageTest` must implement. 

Not only do those two drive documentation they are also both used for [(de)serialization tests when running in unit test mode](https://github.com/elastic/elasticsearch-net/blob/feature/logical-grouping/src/Tests/Framework/EndpointUsageBase.cs#L105-L109). In integration mode by default we do some testing on [status codes and expected isvalid](https://github.com/elastic/elasticsearch-net/blob/feature/logical-grouping/src/Tests/Framework/EndpointUsageBase.cs#L96-L100) but we always assert on all 4 endpoints (fluent/initializer sync/async). Implementations can [implement more integration tests](https://github.com/elastic/elasticsearch-net/blob/feature/logical-grouping/src/Tests/Search/Request/Explain.cs#L30-L31). Methods marked with `[I]` are picked up when we run the tests [in integration mode](https://github.com/elastic/elasticsearch-net/blob/feature/logical-grouping/src/Tests/Framework/TestClient.cs#L18), and `[U]` when running in unit test mode. 

We also allow you to write more story driven tests such as [Connecting.cs](https://github.com/elastic/elasticsearch-net/blob/feature/logical-grouping/src/Tests/ClientConcepts/LowLevel/Connecting.cs) which [takes comments into the extreme](https://github.com/elastic/elasticsearch-net/blob/feature/logical-grouping/src/Tests/ClientConcepts/LowLevel/Connecting.cs#L120-L141) that [all make it into the documentation!](https://github.com/elastic/elasticsearch-net/blob/feature/logical-grouping/docs/contents/new/ClientConcepts/LowLevel/Connecting.asciidoc). All the code in the documentation is real code that has to compile :)

At the heart of the documentation is our [Litterateur](https://github.com/elastic/elasticsearch-net/tree/feature/logical-grouping/src/CodeGeneration/Nest.Litterateur) where we use [roslyn to visit the csharp syntax of our tests](https://github.com/elastic/elasticsearch-net/blob/feature/logical-grouping/src/CodeGeneration/Nest.Litterateur/Walkers/CodeWithDocumentationWalker.cs).

From the command line you can run `build quicktest` this will do an incremental build and runs `Tests.dll` in unit test mode. To run integration tests run `build integrate [versionnumber]` this will download and run elasticsearch `versionnumber` automatically. We start with a random node/cluster name and try to clean up afterwards. Obviously 2.0 is not released so right now it involves manually extracting to the right location in `%APPDATA%\NEST` but that should sort it self out when Elasticsearch 2.0 hits GA :+1: 

They are regular xUnit 2.0 tests that can be run from your favorite visual studio test runner though (NCrunch, Resharper etc).

Both the command line tooling, documentation generation still need that last 10% polishing.

Any feedback in form of comments (or PR's :smile: ) are very much appreciated!

**Comment by robertlyson** [comment]
@Mpdreamz any idea what I'm missing that I can't run tests from command line?
![image](https://cloud.githubusercontent.com/assets/2392583/9980553/64980fe6-5f9e-11e5-827d-9285e2443ddf.png)

**Comment by KodrAus** [comment]
Is there a plan on how the writing of this nice big list of tests is going to be done to prevent colliding PRs? I wouldn't mind taking a look at doing some of the `mapping/fields` tests to get started.

**Comment by robertlyson** [comment]
Just in case someone will be struggling with the same issue - I've managed to fix this by reinstalling dependencies.

**Comment by Mpdreamz** [comment]
Closing this, will open a new issue to track documentation.
