### ISSUE TITLE
Unify ExplainGet<T> and GetFromUpdate

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#1490]
Should be generic, and in order to do that in 2.0 `UpdateResponse` has to be generic as well.

relates to: https://github.com/elastic/elasticsearch-net/pull/1489

**Comment by robertlyson** [comment]
I really would love to help with this one, but one qustion pop up. Is it still to be done?

Looks like `IUpdateResponse` changed a bit between 1.x and 2.0

2.0
```
public interface IUpdateResponse : IResponse
{
	ShardsMetaData ShardsHit { get; }
	string Index { get; }
	string Type { get; }
	string Id { get; }
	long Version { get; }
}
```

1.x
```
public interface IUpdateResponse : IResponse
{
	ShardsMetaData ShardsHit { get; }
	string Index { get; }
	string Type { get; }
	string Id { get; }
	string Version { get; }
	GetFromUpdate Get { get;  }

	T Source<T>() where T : class;
	FieldSelection<T> Fields<T>() where T : class;
}
```

**Comment by Mpdreamz** [comment]
Yeah the added properties and methods were introduced in the linked issue:

https://github.com/elastic/elasticsearch-net/pull/1489/files

They were introduced as methods because making the response object generic would be a breaking change :(

**Comment by robertlyson** [comment]
Thank you @Mpdreamz, now I understand :)
I'll do my best to handle this.

Also I'll try to write tests #1481 way :)

**Comment by Mpdreamz** [comment]
@gmarz @russcam would love to see this in alpha1

See: https://github.com/elastic/elasticsearch-net/issues/1296

**Comment by robertlyson** [comment]
@Mpdreamz thanks for handling :+1:. :-1:  for @me.
