### ISSUE TITLE
Path to elasticsearch rewritten on requests

### ISSUE THREAD

**Issue by hisuwh** [elastic/elasticsearch-net#1502]
I am developing and testing an Elasticsearch solution where my application has to communicate with Elasticsearch through a proxy. E.g. at url `https://localhost/proxypath`

But when I make a request using NEST the path gets rewritten with the index and type names (rather than appending them) E.g my url becomses `https://localhost/index/type/_search`

This is going to cause me issues on live as I'm using `http://proxyserver.com/es/` to route to Elasticsearch (so I can use `http//proxyserver.com/kibana/` to route to kibana)

Please let me know if there is way I can resolve this, or if this is indeed a bug.

**Comment by Mpdreamz** [comment]
We rely on `Uri(Uri uri, string path)` to combine these two together:

https://github.com/elastic/elasticsearch-net/blob/4fcecae93dcf16a4ff7e110135da81eed409dda5/src/Elasticsearch.Net/Connection/RequestState/TransportRequestState.cs#L161

For that to properly resolve you have to register your prefix paths **with** a trailing `/` e.g

```csharp
new Uri(new Uri("http://localhost/proxypath"), "index/type/_search")
```

resolves to `http://localhost/index/type/_search`, whereas

```csharp
new Uri(new Uri("http://localhost/proxypath/"), "index/type/_search")
```

resolves to `http://localhost/proxypath/index/type/_search` 

If this still fails please report back! :+1:

**Comment by hisuwh** [comment]
I yes that fixed it.  I thought I had it working at some point.
Thanks for your answer and sorry for wasting your time.

**Comment by Mpdreamz** [comment]
Not at all feel free to ask questions on github :+1: 

We are working hard on new docs for NEST 2.0, feedback like this is great.
