### ISSUE TITLE
Sorting parents on property of inner hits

### ISSUE THREAD

**Issue by MichelBrinckman** [elastic/elasticsearch-net#1504]
We have an index with two types, companies and persons. Now we have a haschild query on companies, to be able to find companies that contain names of specific persons. For example, give me all company types that have a child with the name 'Jansen'.

Now I want to sort those results (which consists of the parents of type company) on the firstnames of the persons working for that company.

The following query does not sort my companies, based on the inner_hits:

```json
{
  "query": {
    "has_child": {
      "type": "employee",
	  "inner_hits" : {},
      "query": {
        "term" : {"firstname" : "jan"}
      }
    }
  },
  "sort": [{"employee.firstname" : "desc"}]
}
```

Sorting INSIDE the inner hits works fine:

```json
{
  "query": {
    "has_child": {
      "type": "employee",
	  "inner_hits" : {  "sort": [{"lastname" : "asc"}]},
      "query": {
        "term" : {"firstname" : "jan"}
      }
    }
  }
}
```

and:

```json
{
  "query": {
    "has_child": {
      "type": "employee",
	  "inner_hits" : {},
      "query": {
        "term" : {"firstname" : "jan"}
      }
    }
  },
  "sort": [{"revenue" : "desc"}]
}
```

sorts the companies based on revenue just fine. I understand the last one is a property of the parent , but how do I sort the parents based on a property of the child?

**Comment by Mpdreamz** [comment]
As far as I know this is still an open feature request in elasticsearch itself:

https://github.com/elastic/elasticsearch/issues/2917

And the only workaround for now is to duplicate the data you want to sort on on the company object, although I can imagine this is not always possible.
