### ISSUE TITLE
Sticky round-robin connection pool

### ISSUE THREAD

**Issue by tstojecki** [elastic/elasticsearch-net#1507]
Hi,
Is there or are there any plans to develop an IConnectionPool implementation that has a notion of a sticky session? We have used SniffingConnectionPool so far, but the latency in replicating the updates across all the nodes is causing some issues for us. Ideally, we would like something that can hand out the same node ip for as long as the node stays alive for a duration of a session. 

Php's ES library has a notion of that, but it appears to be fairly simplistic, no notion of a session or load balancing:
https://github.com/elastic/elasticsearch-php/blob/de7c2694a9d63a8f21cdda5a286aacc901fb42f9/src/Elasticsearch/ConnectionPool/Selectors/StickyRoundRobinSelector.php

**Comment by Mpdreamz** [comment]
We do not have any immediate plans, I am however in the process of refactoring the internals a tad here for `NEST 2.0` and will take this use case on board to test how (not) easy it is to write.

**Comment by tstojecki** [comment]
Thanks!
I am likely oversimplifying, but my thinking was to derive from SniffingConnectionPool to leverage its initialization logic and select the first available up node (random or not). We would then need some sort of SessionIdProvider dependency to control the lifetime of a session.

**Comment by Mpdreamz** [comment]
@tstojecki I am going to bump this for now, I have no immediate plans to implement this nor in the imediate future but would love a PR :smile:
