### ISSUE TITLE
Success == false but OriginalException == null

### ISSUE THREAD

**Issue by mausch** [elastic/elasticsearch-net#1508]
I ran into a case where Success == false but OriginalException == null for a IElasticsearchResponse. This contradicts the documentation at https://github.com/elastic/elasticsearch-net/blob/develop/src/Elasticsearch.Net/Domain/Response/IElasticsearchResponse.cs#L20-L24 . 

From a brief static analysis, this could be happening from a null Exception being passed into [this constructor](https://github.com/elastic/elasticsearch-net/blob/develop/src/Elasticsearch.Net/Domain/Response/ElasticsearchResponse.cs#L123) but more likely this is coming from [this constructor](https://github.com/elastic/elasticsearch-net/blob/develop/src/Elasticsearch.Net/Domain/Response/ElasticsearchResponse.cs#L130) with a 400 statusCode (which was my particular case).

So the options are: either remove that assertion from the documentation or change the code to make it comply to this assertion...

**Comment by mausch** [comment]
BTW I realise it would be breaking change but it would be great if this was modeled as an algebraic data type. See [Sasa's Result](http://sourceforge.net/p/sasa/code/ci/default/tree/Sasa/Result.cs) for reference. With an ADT this cannot happen.

**Comment by Mpdreamz** [comment]
Thanks @mausch 

In 1.x there is a code path where a bad response (400) does not actually result in an exception but still triggers an invalid response.  Will update the documentation to explicitly mention this. 

For 2.0 we are actually in the process of formalising our request pipeline, what kind of exceptions it throws and how the user should handle it more sanely then in `1.x`.

![clientpipeline6](https://cloud.githubusercontent.com/assets/245275/9058763/1e612f86-3aa4-11e5-887d-152c523fa131.png)

The idea is that you can configure the client to **always** throw hard exceptions on any of the immediate exit points or **always** return a soft error response with a guaranteed exception attached to it akin more to how `1.x`. In `1.x` exception behaviour is also coupled to wheter you have retries enabled and/or are using the SingleNodeConnectionPool, this is bad and we are looking to rectify this mistake in 2.0.

There are definitive up-sights to `Result<>`, folks who want hard exceptions simply use `.Value` to rethrow the original exception. Folks who want soft error responses can use `.HasValue` or a `.Match(v=>value, error=>value_on_error)` to always handle both permutations.

I need to let that idea bake in my head and also weigh its benefits against breaking 100% of the calls when folks update to `NEST 2.0`. `NEST 2.0` is all about daring to break things where needed for the next 5 years of the client but for this one I need to regroup :+1:

**Comment by jonyadamit** [comment]
Currently, when a bad response occurs, you can no longer see the actual error returned from Elasticsearch. The OriginalException is simply a `WebException` with a status of `ProtocolError`.
Is this planned to be changed?

**Comment by gmarz** [comment]
Hey @jonyadamit assuming you're talking about 2.0?  Yes, this is planned and currently being worked on in this branch https://github.com/elastic/elasticsearch-net/tree/spike/2.0-exceptions.

**Comment by jonyadamit** [comment]
:+1: :+1: That's great :-)

**Comment by Mpdreamz** [comment]
Closing this as non actionable, `2.0` has a much saner exception/soft error policy. 

Modelling result as algebraic data type is definitely something we'll revisit when c# natively supports them (like any sane language should (roll on c# 7)).
