### ISSUE TITLE
bulk index sometimes fails to write successfully

### ISSUE THREAD

**Issue by penance316** [elastic/elasticsearch-net#1509]
I have code as follows to create a bulk index of a document type to elasticsearch.
```
public void Create(List<ST> smartTypes) {
			elasticClient.Bulk(bulk => {
				foreach (var thing in smartTypes) {
					var smartType = thing;
					PrepareForCreate(smartType);
					bulk.Index<ST>(i => i.Index(smartType.ElasticIndex).Id(smartType.Id).Document(smartType));
				}
				bulk.Refresh();
				return bulk;
			});
		}
```

In my code this call is suppose to add 14 documents into elasticsearch however when running say 200 tests about 40-60% of the time only 10-12 documents are successfully written. 

I then changed the code to do a foreach around the next method and this worked fine 100% of the time.
```
		public ST Create(ST smartType) {
			PrepareForCreate(smartType);
			elasticClient.Index(smartType, i => i.Index(smartType.ElasticIndex).Id(smartType.Id).Refresh());
			return smartType;
		}
```

I understand this is probably not a bug as it does seem to work sometimes however i would like to know if anyone else has had a similar issue with bulk updates?

**Comment by Mpdreamz** [comment]
How are you validating the documents that get written? What does `.ItemsWithErrors` report on the bulk response when you see these failures?

**Comment by penance316** [comment]
firstly thanks for the reply.I had no idea that command even existed in the API. I am getting this error back. (i have removed the IP and machine name)

Failed to index document 
d9d43044bb93485a8a2838505f4e2f33: 
RemoteTransportException[[COMPUTERNAME][inet[/X.X.X.X]][indices:data/write/bulk
[s]]]; nested: EsRejectedExecutionException[rejected execution (queue capacity 50) on org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$PrimaryPhase$1@1ce41d09];

**Comment by penance316** [comment]
after some digging it seems i need to update the bulk operations queue_size from 50 to something greater. I will give this a go asap.

**Comment by penance316** [comment]
that has indeed fixed my issue. thanks for you help in this matter.
