### ISSUE TITLE
Completion field should be under multifield type

### ISSUE THREAD

**Issue by clintongormley** [elastic/elasticsearch-net#1512]
_From @robertnadar on August 5, 2015 15:26_

i believe the the completion field should be defined under CorePropertiesDescriptor.cs class since we should be able to define the completion type under multi-field type

e.g.
```json
 "properties" : {
          "audience" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "author" : {
            "type" : "string",
            "fields" : {
              "raw" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "suggestive" : {
                "type" : "completion",
                "analyzer" : "simple",
                "payloads" : true,
                "preserve_separators" : true,
                "preserve_position_increments" : true,
                "max_input_length" : 50
              }
            }
          },
```

_Copied from original issue: elastic/elasticsearch#12672_

**Comment by gmarz** [comment]
Hey @robertnadar, yea this is an unfortunate and known issue (see #1408 for details and a *potential* workaround).

We are rewriting the mapping API as part of [NEST 2.0](https://github.com/elastic/elasticsearch-net/tree/fix/2.0-mappings), and have already fixed this in that branch.  We've done away with the idea of separating core properties from other properties, and now only have a single `PropertiesDescriptor`.  The result is a much cleaner and intuitive API.

We might be able to back port some of this to a `1.8` release, but right now we'd rather not continue to hack on `CorePropertiesDescriptor` as there's still a distinction between `IElasticType`s and `IElasticCoreType`s in `1.x`.
