### ISSUE TITLE
 Unexpected token when deserializing object: Integer. Path 'aggregations.names.doc_count_error_upper_bound', line 1629, position 62.

### ISSUE THREAD

**Issue by ksujeet** [elastic/elasticsearch-net#1513]
I am trying to write a NEST query for the aggregations and this error always pops up but the same query works in ES.
I tried with the code samples on NEST websites and it still gives me this error in NEST

NEST version=1.7.0
Newtonsoft.Json version=7.0.1

**Comment by gmarz** [comment]
Hey @ksujeet mind sharing the query?  Also, what version of Elasticsearch?

**Comment by ksujeet** [comment]
sure, 

ES version 1.6 and here is the query

    var ags = esclient.Search<Artifact>(s => s.Aggregations(fa => fa.Filter("filtered", f => f.Filter(fd => fd)
                .Aggregations(ta => ta.Terms("type", st => st.Field("objectCategory"))))).SearchType(SearchType.Count));

**Comment by ksujeet** [comment]
This is the query which works, 
var agg = esclient.Search<Artifact>(s => s.Aggregations(ag => ag
                        .Filter("refine_search", fi => fi.Filter(fl => fl.Bool(b => b
                            .Should(sh => sh.Terms("multimediaReferenceList.mimeType", input.Filters.Media)
                                && sh.Terms("physicalLocations.level1", input.Filters.Location)
                                && sh.Terms("objectCategory", input.Filters.Type)
                                && sh.Range(r => r.GreaterOrEquals(input.Years[0]).OnField(of => of.MinYear)) 
                                && sh.Range(ra => ra.LowerOrEquals(input.Years[1]).OnField(od => od.MaxYear))))))).SearchType(SearchType.Count));

**Comment by gmarz** [comment]
@ksujeet can you post the full query that causes the exception?

**Comment by ksujeet** [comment]
@gmarz , please see the NEST code below, 

the query doesnt fail. I was just sending the aggs query for reference

esclient.Search<Artifact>(s => s.Aggregations(ag => ag
                        .Filter("refine_search", fi => fi.Filter(fl => fl.Bool(b => b
                            .Should(sh => sh.Terms("multimediaReferenceList.mimeType", input.Filters.Media)
                                && sh.Terms("physicalLocations.level1", input.Filters.Location)
                                && sh.Terms("objectCategory", input.Filters.Type)
                                && (sh.Range(r => r.GreaterOrEquals(input.Years[0]).OnField(of => of.MinYear)) ||
                                sh.Range(ra => ra.LowerOrEquals(input.Years[1]).OnField(od => od.MaxYear)))))).Aggregations(aa => aa
               .Terms("type", att => att.Field("objectCategory"))
               .Terms("media", att => att.Field("multimediaReferenceList.mimeType"))
               .Terms("location", att => att.Field("physicalLocations.level1")))))

**Comment by gmarz** [comment]
Closing in favor of duplicate issue #1515.
