### ISSUE TITLE
HasParentFilterDescriptor doesn't have Filter ability

### ISSUE THREAD

**Issue by ejsmith** [elastic/elasticsearch-net#1514]
According to the documentation, I should be able to do a filter with the has_parent operation, but only Query is available on the HasParentFilterDescriptor.

https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-has-parent-filter.html

**Comment by gmarz** [comment]
@ejsmith you're absolutely right, thanks for reporting :+1:.  We'll fix this for the next release.

**Comment by ejsmith** [comment]
Also, there isn't a HasParent on Filter<T>.  Shouldn't it be there as well?
