### ISSUE TITLE
Throw if no such index/mapping

### ISSUE THREAD

**Issue by vorou** [elastic/elasticsearch-net#1517]
Is there a way to make `ElasticClient` blow up on `Index()` if there is no such index/mapping? We don't use dynamic mapping, so if anything is trying to index a doc into non-existent index it's always a sign that something is broken.

Here's example:

```
const string defaultIndex = "must-throw";
var connectionSettings = new ConnectionSettings(new Uri("http://localhost:9200"), defaultIndex);
var elastic = new ElasticClient(connectionSettings);
if (elastic.IndexExists(defaultIndex).Exists)
    elastic.DeleteIndex(defaultIndex);

// must throw something here
elastic.Index(new {name = "Panda"});
```

**Comment by Mpdreamz** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/1.6/mapping-dynamic-mapping.html

You can set `dynamic: false` to silently ignore unmapped fields or `dynamic: strict` to make elasticsearch return an exception. If you configure the client with `.AlwaysThrowOnElasticsearchServerExceptions()` the client will also throw a hard exceptions.

The cool thing is that you can make it strict for the root object but reenable dynamic mapping in sub objects in the json grap e.g an explicit metadata field. 

in Nest call

`.Dynamic(DynamicMappingOption.Strict)`

**Comment by vorou** [comment]
Thanks for your response!

Just for the record, I put these two lines into `elasticsearch.yml`:
```
action.auto_create_index: false
index.mapper.dynamic: false
```

And made NEST client throw on server errors:
```
var connectionSettings = new ConnectionSettings(new Uri("http://localhost:9200"), defaultIndex).ThrowOnElasticsearchServerExceptions();
```

And hooray, I have the exception. Exceptions are great. So much love for exceptions when it's third time in a row you debug a problem only to find out it was caused by somebody dropped the mapping and the app silenty recreated it (wrong).
