### ISSUE TITLE
Scroll ends with 404 "Could not parse server error" when ThrowOnElasticsearchServerExceptions is set

### ISSUE THREAD

**Issue by vorou** [elastic/elasticsearch-net#1518]
I'm using scroll search like this:

```
var scanResult = elasticClient.Search<OrganizationSuggestionDocument>(s => s.MatchAll().SearchType(SearchType.Scan).Scroll("1h").Size(100));
var scrollResult = elasticClient.Scroll<OrganizationSuggestionDocument>("1h", scanResult.ScrollId);
while (scrollResult.Documents.Any())
{
    foreach (var doc in scrollResult.Documents)
        yield return new OrganizationSuggestion {Name = doc.Name, Inn = doc.Inn};
    scrollResult = elasticClient.Scroll<OrganizationSuggestionDocument>("1h", scanResult.ScrollId);
}
```

It used to work OK, but now after I turned on `ThrowOnElasticsearchServerExceptions` the last call to scroll results into exception.

Is it the expected behavior? How could I avoid that exception? I was looking for anything like `.IsFinal` flag on scroll result, but didn't find any.

**Comment by Mpdreamz** [comment]
`ThrowOn` will turn any response that would otherwise be invalid into an exception. 

You can however force 404 to be an OK response on a per request basis:

```
.Scroll<Project>(s => s
    .Scroll("5m")
    .ScrollId(id)
    .RequestConfiguration(r => r.AllowedStatusCodes(404))
);
```

Hope this helps!

**Comment by vorou** [comment]
Thanks! Worked for me.
