### ISSUE TITLE
NEST Bool Query not generating expected request

### ISSUE THREAD

**Issue by samlbest** [elastic/elasticsearch-net#1519]
I'm attempting to create an Elasticsearch query in NEST which uses the Bool query, but everything I put inside the Bool method seems to get ignored.

This is the code I've tried:

    var query = "my query";
    var fileType = "Poster";
    var searchResults = _client.Search<Doc>(s => 
            s.Query(q =>
                q.Bool(
                    b => b.Must(
                        m =>  m.MatchPhrase(mp =>
                            mp.Query(query).Fuzziness(2))
                        ).Must(m => m.Match(
                            mp => mp.Query(fileType))))
                ).Highlight(x =>
                        x.OnFields(y =>
                            y.OnField(f => f.File)
                             .PreTags("<strong>")
                             .PostTags("</strong>"))
                ).Fields("fileType", "title"));

Here is the JSON request NEST is generating from that code. Notice that it's missing the entire query property:

    {
      "highlight": {
        "fields": {
          "file": {
            "pre_tags": [
              "<strong>"
            ],
            "post_tags": [
              "</strong>"
            ]
          }
        }
      },
      "fields": [
        "fileType",
        "title"
      ]
    }

I tried taking out the extra highlighting and field selection, in case that was causing a problem, just leaving the Query and the Bool:

    var searchResults = _client.Search<Doc>(s => 
            s.Query(q =>
                q.Bool(
                    b => b.Must(
                        m =>  m.MatchPhrase(mp =>
                            mp.Query(query).Fuzziness(2))
                        )
                    .Must(m => m.Match(mp => mp.Query(fileType))))
                ));

This code generates an empty JSON object.

I couldn't find mention of the Bool and Must methods in the NEST documentation and I haven't been able to figure it out with trial and error.

What am I doing wrong?

----------

Notes
-----

I have used NEST's Query method with a simple QueryString. It generated the expected JSON request, so I'm pretty sure the way I have things configured is correct.

This is the JSON query that I'm attempting to recreate with NEST:

    {
      "fields": [
        "title",
        "fileType"
      ],
      "query": {
        "bool": {
          "must": [
            {
              "match": {
                "fileType": {
                  "query": "Poster"
                }
              }
            },
            {
              "match_phrase": {
                "file": {
                  "query": "my query",
                  "fuzziness": 2
                }
              }
            }
          ]
        }
      },
      "highlight": {
        "fields": {
          "file": {}
        }
      }
    }

Also posted this here: https://stackoverflow.com/questions/31993248/elasticsearch-net-nest-bool-query-not-generating-expected-request

**Comment by gmarz** [comment]
You aren't specifying a field in your match queries and thus the `Conditionless()` construct is kicking in nullifying them.  NEST doesn't infer the field name from the variable passed into `Query()`, you need to explicitly specify the field using `OnField()`.

Try this instead:

```csharp
var query = "my query";
var fileType = "Poster";
var searchResults = _client.Search<Doc>(s => 
        s.Query(q =>
            q.Bool(
                b => b.Must(
                    m =>  m.MatchPhrase(mp =>
                        mp.OnField("file").Query(query).Fuzziness(2))
                    ).Must(m => m.Match(
                        mp => mp.OnField("fieldType").Query("Poster"))))
            ).Highlight(x =>
                    x.OnFields(y =>
                        y.OnField(f => f.File)
                         .PreTags("<strong>")
                         .PostTags("</strong>"))
            ).Fields("fileType", "title"));
```

Hope that makes sense.

**Comment by samlbest** [comment]
Thank you. That makes sense. Match is working now, but I'm still having trouble with MatchPhrase, even when I use it by itself as in this example:

```
 _client.Search<Doc>(s => 
                    s.Query(q =>
                        q.Bool(
                            b => b.Must(m =>  m.MatchPhrase(mp =>
                                    mp.OnField(f => f.File).Query(query).Fuzziness(2))
                                ))
                        ).Fields("fileType", "title"));
```

**Comment by gmarz** [comment]
Hmm, by any chance is `query` null or empty?  That would also cause the conditionless to kick in.

Can you post the generated JSON?

**Comment by samlbest** [comment]
You're absolutely right. I was so focused on the syntax of the query that I forgot I had changed the variable name. Thanks for the help.
