### ISSUE TITLE
SnapshortBytesPerSecondMaximum Typo in FileSystemRepositoryDescriptor.cs

### ISSUE THREAD

**Issue by J-Griffin** [elastic/elasticsearch-net#1522]
Is:
SnapshortBytesPerSecondMaximum
Should Be:
SnapshotBytesPerSecondMaximum

**Comment by gmarz** [comment]
It's already been marked [obsolete](https://github.com/elastic/elasticsearch-net/blob/develop/src/Nest/DSL/Repository/FileSystemRepositoryDescriptor.cs#L75) and will be removed in 2.0.  Use the [corrected](https://github.com/elastic/elasticsearch-net/blob/develop/src/Nest/DSL/Repository/FileSystemRepositoryDescriptor.cs#L86) method instead.
