### ISSUE TITLE
about MatchQuery

### ISSUE THREAD

**Issue by starckgates** [elastic/elasticsearch-net#1523]
你好，大神，我想使用MatchQuery来进行查询，但是无法查出结果。
I use MatchQuery to Search,but return " match:null"

QueryContainer matchQuery = new MatchQuery() { Query = keyword};
var searchResults = client.Search<NewsBase>(s => s
                .Index(indexname)
                .Type(typename)
                .Query(matchQuery)
                .From(0)
                .Size(10)
            );

--------------------

{StatusCode: 400, 
	Method: POST, 
	Url: http://localhost:9200/sci_news/newsbase/_search, 
	Request: {
  "from": 0,
  "size": 10,
  "query": {
    "match": null
  }
}, 
	Response: <Response stream not captured or already read to completion by serializer, set ExposeRawResponse() on connectionsettings to force it to be set on>
	ExceptionMessage: Failed to execute phase [query], all shards failed; shardFailures {[MkMQGFYIS06-aluuBDKMSw][sci_news][0]: SearchParseException[[sci_news][0]: from[0],size[10]: Parse Failure [Failed to parse source [{
  "from": 0,
  "size": 10,
  "query": {
    "match": null
  }
}]]]; nested: QueryParsingException[[sci_news] [_na] query malformed, no field after start_object]; }{[MkMQGFYIS06-aluuBDKMSw][sci_news][1]: SearchParseException[[sci_news][1]: from[0],size[10]: Parse Failure [Failed to parse source [{
  "from": 0,
  "size": 10,
  "query": {
    "match": null
  }
}]]]; nested: QueryParsingException[[sci_news] [_na] query malformed, no field after start_object]; }{[MkMQGFYIS06-aluuBDKMSw][sci_news][2]: SearchParseException[[sci_news][2]: from[0],size[10]: Parse Failure [Failed to parse source [{
  "from": 0,
  "size": 10,
  "query": {
    "match": null
  }
}]]]; nested: QueryParsingException[[sci_news] [_na] query malformed, no field after start_object]; }{[MkMQGFYIS06-aluuBDKMSw][sci_news][3]: SearchParseException[[sci_news][3]: from[0],size[10]: Parse Failure [Failed to parse source [{
  "from": 0,
  "size": 10,
  "query": {
    "match": null
  }
}]]]; nested: QueryParsingException[[sci_news] [_na] query malformed, no field after start_object]; }{[MkMQGFYIS06-aluuBDKMSw][sci_news][4]: SearchParseException[[sci_news][4]: from[0],size[10]: Parse Failure [Failed to parse source [{
  "from": 0,
  "size": 10,
  "query": {
    "match": null
  }
}]]]; nested: QueryParsingException[[sci_news] [_na] query malformed, no field after start_object]; }
	 StackTrace: }

-------------------

**Comment by Mpdreamz** [comment]
You have to specify a `Field = ` when using the match query otherwise conditionless feature will kick in. 

http://nest.azurewebsites.net/nest/writing-queries.html

There is a bug here though when you mix and match fluent and object initializer syntax like you do, that query should have been rewritten to:

```
 {
"from": 0,
"size": 10
}
```
