### ISSUE TITLE
WebSocket

### ISSUE THREAD

**Issue by mathrb** [elastic/elasticsearch-net#1524]
Hello,

Do you plan to support websocket connection with elastic search, like these projects :
https://github.com/jprante/elasticsearch-client-websocket
https://github.com/jprante/elasticsearch-transport-websocket

Thanks

**Comment by Mpdreamz** [comment]
We have no plans to support these @mathrb, if you want to have a stab at implementing it then you could look into creating your own `IConnection` implementation that you can inject into the client. 

In NEST 2.0 the contract for `IConnection` has changed significantly and should be easier to implement.
