### ISSUE TITLE
Date Histogram aggregation missing "Offset" option

### ISSUE THREAD

**Issue by tagg7** [elastic/elasticsearch-net#1525]
As can be seen in the latest documentation, the Date Histogram aggregation has a new property called "Offset" that effectively replaces the "pre_offset" and "post_offset" options.
https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-aggregations-bucket-datehistogram-aggregation.html#_offset

This new offset option needs to be added to ElasticSearch.NET.

**Comment by gmarz** [comment]
Nice catch, thank you!  We'll add this for the next release.
