### ISSUE TITLE
Do we have any plan to fit .Net Core 5 ?

### ISSUE THREAD

**Issue by SuperShowwei** [elastic/elasticsearch-net#1526]
I test NEST Api on ASP.NET MVC 6 yesterday.
I got a message that there is not compatiable NEST version for .Net Core 5.

Do we have any plan to fit .Net Core 5 ?

**Comment by Mpdreamz** [comment]
.NET Core support is a blocking requirement for NEST 2.0, we won't release without support for it. 

I've been tracking .NET core [as far back as october 2014](https://github.com/elastic/elasticsearch-net/pull/1043), and opened another PR again [a couple of months ago](https://github.com/elastic/elasticsearch-net/pull/1397). We are doing quite a bit of groundwork in our 2.0 branch that will make it easier to move over but that means those PR's are now stale and closed though.

That said, we might still push an alpha version of NEST 2.0 without support first.

**Comment by SuperShowwei** [comment]
Thank you for respnse.

NEST is a great Elasticsearch API.

**Comment by Jetski5822** [comment]
Would love to see a CoreCLR version! :+1:

**Comment by tugberkugurlu** [comment]
any news on this?
