### ISSUE TITLE
Next release of NEST to include issue with min/max_children

### ISSUE THREAD

**Issue by vineet85** [elastic/elasticsearch-net#1527]
https://github.com/elastic/elasticsearch-net/issues/1505

Can you tell me when the next release of NEST will be which will include a fix to the above issue.

Thanks,
Vineet

**Comment by Mpdreamz** [comment]
Hi @vineet85, 

We have no concrete plans to release NEST 1.7.1 yet, working hard to get an alpha/bete release of NEST 2.0 out of the door first.

**Comment by gmarz** [comment]
We are aiming for 1.7.1 release this week.
