### ISSUE TITLE
Multi Field (Nested Properties)

### ISSUE THREAD

**Issue by shoushouleb** [elastic/elasticsearch-net#1531]
Hi,
I need to use multi fields, that is I have a property that has sub-properties, what should I do in order of:
- Property creation
-mapping
-indexing
-searching

After that I need to create a query that search the path ( I already created path tokenizer) thanks to 
@Mpdreamz 
@KodrAus
along with the properties I have in my class, which are normal properties and nested properties.
Thanks,

**Comment by Mpdreamz** [comment]
A quick example can be found [here](https://github.com/elastic/elasticsearch-net/blob/develop/src/Tests/Nest.Tests.Integration/IntegrationSetup.cs#L97-L106)

This `.Fields()` method is available for all property types e.g inside `String()` `Number()` etcetera and allows you to introduce multi-fields. 

In the linked example we create a NotAnalyzed multi-field called `sort` that we can use the sort on the name as it was passed in.

**Comment by shoushouleb** [comment]
Thank you for your example, I have read it but  I wonder how the value of "sort" can be set while indexing, so we can search for it later , also how the classes design of the Parent-child look like?
Thank you very much

**Comment by Mpdreamz** [comment]
The multified takes it value from its parent

e.g 

```csharp
public MyClass {
    public string Name { get; set; }
}
```

We can create N multifield mappings for `Name` but we only ever have to supply it once during indexing.

**Comment by KodrAus** [comment]
I think the point of the [Multi field type](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-core-types.html#_multi_fields_3) is that the data that goes in is the same, but what changes is the analyzer and type, so you can index / query over the same data in different way.

In the example Elastic gives, you have this property:

```
"name" : {
  "type" : "string",
    "index" : "analyzed",
      "fields" : {
        "raw" : {"type" : "string", "index" : "not_analyzed"}
    }
}
```

Which could look like this when indexed with the value `"My property value"`:

```
"name" : [ "my", "property", "value" ]
"name.raw" : "My property value"
```

So you can use `name.raw` for exact matching. You could perhaps also use it to do something like this:

```
"isbn" : {
  "type" : "number",
    "index" : "not_analyzed",
      "fields" : {
        "autocomplete" : {"type" : "string", "index" : "my_ngram_autocompleter"}
    }
}
```

Which, if you pass in `9781234567890` could give you:

```
"isbn": 9781234567890
"isbn.autocomplete": ["978", "9781", "97812", "978123", "9781234", "97812345", "978123456", "9781234567", "97812345678", "978123456789", "9781234567890"]
```

I'm not certain if that's how the casting works though.

So if you want fields with different values, you can just use a plain old C# object, and NEST's mapping will automagically figure it out for you.
