### ISSUE TITLE
NEST is missing the ability to specify the store property to the _timestamp field

### ISSUE THREAD

**Issue by ben-guri** [elastic/elasticsearch-net#1533]
There isn't a way to specify the store property on the _timestamp field when programmatically creating a new mapping with NEST. TimestampFieldMappingDescriptor misses a property for store.

so that enabling _timestamp field for a mapping would store turned on would be:
ts.Enabled(true).Store(true);
(where ts is TimestampFieldMappingDescriptor)

**Comment by Mpdreamz** [comment]
Thanks for reporting, will take this on board for the next release :+1:

**Comment by ben-guri** [comment]
for when is it scheduled ?
thanks

**Comment by KodrAus** [comment]
I've made a pull request for this, but am not ninja enough to attach it to the issue https://github.com/elastic/elasticsearch-net/pull/1537

**Comment by gmarz** [comment]
@KodrAus FYI - it's just a matter of referencing the issue # in the PR summary or commit message and GitHub will automatically associate them.

**Comment by gmarz** [comment]
Closed via #1537
