### ISSUE TITLE
complex query

### ISSUE THREAD

**Issue by shoushouleb** [elastic/elasticsearch-net#1534]
Hi,
I have a class and a child class ( the parent class has a list of type ChildClass)
How can I construct a query to search for each field in the parent ( I may need  to search for one field,2 fields, etc...) and/or the children in the list ( again I may need to search for one field in the child or many fields).

Thanks

**Comment by Mpdreamz** [comment]
Hi @shoushouleb 

Have a look at http://nest.azurewebsites.net/nest/writing-queries.html you can either use boolean queries, or use the multi match to run a query against multiple fields. 

Glad to help with questions but its generally more helpful to us if you post your attempted solution with as much code and mappings you can dig up for us. Your question depends a lot on the type of relation you have in place for instance.
