### ISSUE TITLE
Datetime Range search

### ISSUE THREAD

**Issue by shoushouleb** [elastic/elasticsearch-net#1538]
Hi 
I am trying to search for datetime ( from -> to) in boolean query, 
for testing now,I am trying just to get the greater than
and this is my query:
<code>

    lstDoc = elastic.Search<Document>(s => s
                     .From(From)
                     .Size(Size)
                     .Query(q => q
                         .Bool(a => a.Must(b =>
                             b.Term("Document.lstChildren.AttributeValueID",1)
    && q.Range(n => n.GreaterOrEquals(Convert.ToDateTime( input),"dd/MM/yyyy").OnField( f=> f.Modified))
                                 )// MUST
                      )// bool
                        
                        ));

</code>

the input is 25/08/2015 and I do have this value set to all my docs ( 9 docs) but the search always return no results.

**Comment by gmarz** [comment]
What format was specified for the `Modified` field mapping?  Can you share the entire mapping for your `Document` type?

Does the query return results with the range query removed (i.e. only the term query)?

**Comment by shoushouleb** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Nest;

namespace ElasticEngineLibrary
{

    [ElasticType(IdProperty = "Id", Name = "Document")]
    public class Document1
    {
        [ElasticProperty(Name = "_id", Index = FieldIndexOption.NotAnalyzed, Type = FieldType.String)]
        public int ID { get; set; }
    }
    [ElasticType(IdProperty = "Id", Name = "Document")]
    public class Document
    {
        [ElasticProperty(Name = "_id",  Index = FieldIndexOption.NotAnalyzed, Type = FieldType.String)]
        public int ID { get; set; }

        [ElasticProperty(Name = "name", Index = FieldIndexOption.Analyzed, Type = FieldType.String)]
        public string Name { get; set; }
        
        [ElasticProperty(Name = "content", TermVector =TermVectorOption.WithPositionsOffsets, Index = FieldIndexOption.Analyzed,  Type = FieldType.Attachment)]
        public string Content { get; set; }
       
        [ElasticProperty(Name = "originalNodeID", Index = FieldIndexOption.NotAnalyzed, Type = FieldType.Integer)]
        public int OriginalNodeID { get; set; }
       
        [ElasticProperty(Name = "versionNo", Index = FieldIndexOption.NotAnalyzed, Type = FieldType.Integer)]
        public int VersionNo { get; set; }
       
        //[ElasticProperty(Name = "isLatest", Index = FieldIndexOption.NotAnalyzed, Type = FieldType.Boolean)]
        //public bool IsLatest { get; set; }

        [ElasticProperty(Name = "path", Index = FieldIndexOption.Analyzed, Type = FieldType.String)]
        public string FilePath { get; set; }

        [ElasticProperty(Name = "fullFilePath", Index = FieldIndexOption.Analyzed, Type = FieldType.String)]
        public string FullFilePath { get; set; }

       [ElasticProperty(Name = "extension", Index = FieldIndexOption.NotAnalyzed, Type = FieldType.String)]
        public string Extenstion { get; set; }

       [ElasticProperty(Name = "created", Index = FieldIndexOption.NotAnalyzed, Type = FieldType.Date)]
       public DateTime Created { get; set; }


       [ElasticProperty(Name = "modified", Index = FieldIndexOption.NotAnalyzed, Type = FieldType.Date)]
       public DateTime Modified { get; set; }



       public List<Attributes> LstChildren { get; set; }
    }

    public class Attributes
    {
         [ElasticProperty(Name = "AttributeValueID")]
        public int AttributeValueID { get; set; }

         [ElasticProperty(Name = "NodeID")]
         public int NodeID { get; set; }

         [ElasticProperty(Name = "AttributeID")]
         public int AttributeID { get; set; }

         [ElasticProperty(Name = "TextValue")]
         public string TextValue { get; set; }

         [ElasticProperty(Name = "TextTrimmedValue")]
         public string TextTrimmedValue { get; set; }

         [ElasticProperty(Name = "DateValue")]
         public DateTime DateValue { get; set; }

         [ElasticProperty(Name = "IntValue")]
         public int IntValue { get; set; }

         [ElasticProperty(Name = "BoolValue")]
         public bool BoolValue { get; set; }

         [ElasticProperty(Name = "LookUpID")]
         public int LookUpID { get; set; }
    }
}

**Comment by gmarz** [comment]
@shoushouleb what date format was used when indexing the documents?  Does the query return results without the range query and only the term?

**Comment by shoushouleb** [comment]
When I add the range query the result is 0
I did not do anything in the indexing, I left it as is.
Thanks

**Comment by gmarz** [comment]
I suspect that `Convert.ToDateTime()` isn't returning the date you're expecting.  I think you need to sanitize your input.  `25/08/2015` is not a valid format for `Convert.ToDateTime()`- it should be `08/25/2015`.

Try `.Range(n => n.GreaterOrEquals(Convert.ToDateTime("08/25/2015")`, leaving out the format, and see if that fixes your problem.

**Comment by shoushouleb** [comment]
@gmarz 
It throws not a valid datetime error.

**Comment by shoushouleb** [comment]
I have realized that the mess is due to date format becauase if I search using "015-08-25T00:00:00+03:00" ( which is the format stored in the index) , the results are OK.
so the question now how i can tell elasticsearch to set the datetime to be of format "dd/MM/yyyy"

**Comment by shoushouleb** [comment]
I have added the propert DateFormat to the mapping of my class, but the index still saving the datetime using the default format

**Comment by gmarz** [comment]
Closing in favor of #1542.

**Comment by shoushouleb** [comment]
SOLVED:
Remove the mapping from the index creation.
Add mapping to the propert as = dd/MM/yyyy
The index will index the fields as 2015-01-01T00:00:00 so I pass the date value in the form of 2015-01-01

Thanks for your help
