### ISSUE TITLE
Initializing query objects

### ISSUE THREAD

**Issue by shoushouleb** [elastic/elasticsearch-net#1540]
hi,
I was able to initialize a querystring like this:

<code>
QueryContainer qry1 =new QueryStringQuery
                {
                    DefaultField = "content",
                    Query  = @"b"
                };
</code>

but i am unable to do it with FilteredQuery or range query \
thank you

**Comment by gmarz** [comment]
You would initialize them in the same manner...

```csharp
QueryContainer filtered = new FilteredQuery
{
	Query = new QueryContainer(new MatchQuery(...)),
	Filter = new FilterContainer(...)
};
```

```csharp
QueryContainer range = new RangeQuery
{
	GreaterThan = ...
};
```

Hopefully that clears things up?

**Comment by gmarz** [comment]
@shoushouleb closing this for now.  Feel free to re-open you still need help.

**Comment by shoushouleb** [comment]
Thank you, It worked.
