### ISSUE TITLE
about use Range problem, the DateTime

### ISSUE THREAD

**Issue by starckgates** [elastic/elasticsearch-net#1541]
In my Project，I want use range 

.FacetRange<DateTime>(t=>t
                    .OnField(f=>f.Createon)
                    .Ranges(
                        r=>r.From(new DateTime(2014,1,1).ToLocalTime())
                    )
                )

-----------------
 running, I get this

"facets": {
    "createon": {
      "range": {
        "field": "createon",
        "ranges": [
          {
            "from": "2014-01-01T08:00:00+08:00"
          }
        ]
      }
    }
  },

----------------------------------
2014-01-01T08:00:00+08:00
2014-07-24T16:45:17.163+08:00

but, ES  -->  "createon": "2014-07-24T16:45:17.163+08:00"

so,the DateTime Format is Mismatch.

how to use range to  Filter time？

**Comment by KodrAus** [comment]
By default, if you're using a DateTime, Elasticsearch will index your dates using the `basic_date_time` format, see details [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html).

`date_time_no_millis` is a better match for the C# date you're getting from Nest. It will output results that look like this:

`2014-01-01T10:00:00+10:00`

Now take the following example:

```
using System;
using System.Collections.Generic;
using System.Linq;
using Nest;

namespace Test
{
	public class TestWithDate
	{
		public DateTime CreateOn { get; set; }
	}

	public class Program
	{
		static void Main(string[] args)
		{
			var client = new ElasticClient(new ConnectionSettings(new Uri("http://localhost:9200")));

			var doc = new TestWithDate
			{
				CreateOn = new DateTime(2014,1,1).ToLocalTime()
			};

			//Set the mapping for the TestWithDate to explicitely use date_time_no_millis
			client.Map<TestWithDate>(m => m
				.Index("test_index_for_date")
				.DynamicDateFormats(new[] { "date_time_no_millis" })
				.MapFromAttributes()
			);

			client.Index<TestWithDate>(doc, idx => idx.Index("test_index_for_date"));

			var results = client.Search<TestWithDate>(body => body
				.MatchAll()
			    .FacetRange<DateTime>(t => t
			        .OnField(f => f.CreateOn)
			        .Ranges(
			            r=>r.From(new DateTime(2014,1,1).ToLocalTime())
			        )
			    )
			);

			Console.WriteLine(results.Documents.Count() + " query results");

			var facets = results.FacetItems<FacetItem>(p=>p.CreateOn);

			Console.WriteLine(facets.Count() + " facet buckets");

			foreach (DateRange facet in facets)
			{
				Console.WriteLine(facet.From);
				Console.WriteLine(facet.Count + " document in facet");
			}
		}
	}
}
```

Which will return something like this:

```
3 query results
1 facet buckets
1/01/2014 10:00:00 AM
3 document in facet
```

**Comment by starckgates** [comment]
@KodrAus  OK,I will Try.
Thanks a Lot!

**Comment by KodrAus** [comment]
I'm fairly sure you can set the date format using NEST's property attributes... But I don't have Intellisense so I can't check :)

**Comment by gmarz** [comment]
That's correct.  `ElasticProperty` contains a [DateFormat](https://github.com/elastic/elasticsearch-net/blob/develop/src/Nest/Domain/Mapping/Attributes/ElasticPropertyAttribute.cs#L45) field which is used for setting the format.  Also, FYI the default date format is [date_optional_time](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html#mapping-date-format).

Thanks for the thorough answer @KodrAus !

Closing this for now, feel free to re-open if necessary @starckgates.
