### ISSUE TITLE
Map Many fields

### ISSUE THREAD

**Issue by shoushouleb** [elastic/elasticsearch-net#1542]
Hi i am trying to map two fields : (please see ERROR HERE)

 elastic.CreateIndex("test1", i => i
                    .Analysis(an => an
                        .Tokenizers(tokenizers => tokenizers
                            .Add(PathTokenizerName, PathTokenizer)
                        )
                        .Analyzers(analyzer => analyzer
                            .Add(PathAnalyzerName, PathAnalyzer)
                        )
                    )
                    .AddMapping<Document>(t => t
                        .MapFromAttributes()
                        .Properties(props => props
                            //Partial path matching
                           .String(myPathProperty => myPathProperty
                                .Name(_t => _t.FullFilePath)
                                .IndexAnalyzer(PathAnalyzerName)
                            )
//////////////////////////ERROR HERE ///////////
// if I add this statement the index wlill not index documents any more, if removed all ok
// if I check the mappings using the browser, the format of the field will be :dd/MM/yyyy
                            .Date( df=> df.Name( _tdf => _tdf.Modified ).Format("dd/MM/yyyy"))
                        )
                    )
                );

**Comment by KodrAus** [comment]
Your example doesn't have a generic argument for the mapping. What type are you trying to map? A couple of things to try:

- change your first line to something like `var indexResult = elastic.CreateIndex("test1", i => i` and then inspect `indexResult.ConnectionStatus` to see if there are any errors in there

- If you're pointing at a local Elasticsearch instance you've spun up with `elasticsearch.bat`, have a look through the console window it's running in and see if there are any exceptions printed there

- try removing just the `.Format ()` line and see what happens

- call your Elasticsearch instance in the browser at `test1/_mapping?pretty` and see what's in there

- find out if you actually really need a custom date format or not. You may be giving yourself more work than you need to

**Comment by shoushouleb** [comment]
I am trying to map Date field:

<code>
     [ElasticProperty(Name = "modified", Index = FieldIndexOption.NotAnalyzed, Type =FieldType.Date ,DateFormat ="dd/MM/yyyy")]
       public DateTime Modified { get; set; }
</code>

-removing .format() will do the job, but all the dates will be inserted as :0001/01/01
- the result of the connection status is :200
- calling test1/_mapping?pretty will show that the format of the field is the custom format ( before removing .format)

**Comment by gmarz** [comment]
@shoushouleb have you re-created your index with the new mappings and indexed your data again?

**Comment by shoushouleb** [comment]
@gmarz  Yes I have re-created the index.

**Comment by KodrAus** [comment]
@shoushouleb are you saying that your date pattern `dd/MM/yyyy` is indexing as `0001/01/01`?

**Comment by shoushouleb** [comment]
yes exactly as : 0001-01-01T00:00:00

**Comment by KodrAus** [comment]
Ah, so with the default ES date format then? Can you post the results of `test1/_mapping?pretty`

**Comment by shoushouleb** [comment]
{
  "test1" : {
    "mappings" : {
      "Document" : {
        "properties" : {
          "content" : {
            "type" : "attachment",
            "path" : "full",
            "fields" : {
              "content" : {
                "type" : "string"
              },
              "author" : {
                "type" : "string"
              },
              "title" : {
                "type" : "string"
              },
              "name" : {
                "type" : "string"
              },
              "date" : {
                "type" : "date",
                "format" : "dateOptionalTime"
              },
              "keywords" : {
                "type" : "string"
              },
              "content_type" : {
                "type" : "string"
              },
              "content_length" : {
                "type" : "integer"
              },
              "language" : {
                "type" : "string"
              }
            }
          },
          "created" : {
            "type" : "date",
            "format" : "dateOptionalTime"
          },
          "extension" : {
            "type" : "string",
            "index" : "not_analyzed"
          },
          "fullFilePath" : {
            "type" : "string",
            "index_analyzer" : "path"
          },
          "lstChildren" : {
            "properties" : {
              "AttributeID" : {
                "type" : "integer"
              },
              "AttributeValueID" : {
                "type" : "integer"
              },
              "BoolValue" : {
                "type" : "boolean"
              },
              "DateValue" : {
                "type" : "date",
                "format" : "dateOptionalTime"
              },
              "IntValue" : {
                "type" : "integer"
              },
              "LookUpID" : {
                "type" : "integer"
              },
              "NodeID" : {
                "type" : "integer"
              },
              "TextTrimmedValue" : {
                "type" : "string"
              },
              "TextValue" : {
                "type" : "string"
              }
            }
          },
          "modified" : {
            "type" : "date",
            "format" : "dd/MM/yyyy"
          },
          "name" : {
            "type" : "string"
          },
          "originalNodeID" : {
            "type" : "integer"
          },
          "path" : {
            "type" : "string"
          },
          "versionNo" : {
            "type" : "integer"
          }
        }
      }
    }
  }
}

**Comment by KodrAus** [comment]
If I run the following manually in Elasticsearch it works fine:

```
POST test_index_for_date

PUT test_index_for_date/doc/_mapping
{
    "properties": {
      "modified": {
        "type": "date",
        "format": "dd/MM/yyyy"
      },
      "modified_standard": {
        "type": "date",
        "format": "basic_date"
      }
    }
}

PUT test_index_for_date/doc/1
{
  "modified": "01/03/2014",
  "modified_standard": "20140301"
}

GET test_index_for_date/doc/_search
{
  "query": {
    "filtered": {
      "query": {
        "match_all": {}
      },
      "filter": {
        "range": {
          "modified": {
            "gt": "01/01/2014",
            "format": "dd/MM/yyyy"
          }
        }
      }
    }
  }
}

GET test_index_for_date/doc/_search
{
  "query": {
    "filtered": {
      "query": {
        "match_all": {}
      },
      "filter": {
        "range": {
          "modified": {
            "gt": "20140101"
          }
        }
      }
    }
  }
}

RESPONSE
{
   "took": 1,
   "timed_out": false,
   "_shards": {
      "total": 5,
      "successful": 5,
      "failed": 0
   },
   "hits": {
      "total": 1,
      "max_score": 1,
      "hits": [
         {
            "_index": "test_index_for_date",
            "_type": "doc",
            "_id": "1",
            "_score": 1,
            "_source": {
               "modified": "01/03/2014",
               "modified_standard": "20140301"
            }
         }
      ]
   }
}
```

On the response object for your `elastic.Index` line, look in `ConnectionStatus` for the original request object, with a json body, and post that so we can see what's actually being passed to Elasticsearch.

**Comment by gmarz** [comment]
Closing for now.  Feel free to reopen if you're still having issues @shoushouleb.
