### ISSUE TITLE
Initializing Phrase Query

### ISSUE THREAD

**Issue by shoushouleb** [elastic/elasticsearch-net#1543]
hi,
we can use this to initialize stringquery:

 QueryContainer qry1 =new QueryStringQuery { DefaultField = "content", Query = @"b" }; 

How to initialize Pa query for MatchPhrase() ?
Thanks

**Comment by gmarz** [comment]
It's simply a `match query` of type `phrase`, so you would initialize it as:

```csharp
new MatchQuery
{
    Type = "phrase",
    ...
};
```

A little counter-intuitive though, we should probably have a `MatchPhraseQuery` that sets the type for you.  We'll think about adding this in the next release, or perhaps in 2.0.

**Comment by shoushouleb** [comment]
thank you,
