### ISSUE TITLE
Improvements to Documentation

### ISSUE THREAD

**Issue by KodrAus** [elastic/elasticsearch-net#1544]
It's been raised before #1528 that the docs are falling a bit behind what's current. I understand you're looking at auto generating documentation out of the code. I'd like to put my hand up to help out with any manual writing that could embellish the auto generated docs. Is there anything needed in this space?

**Comment by Mpdreamz** [comment]
in our `2.0` branch we have come up with a concept we like to call literate testing. We combine writing our unit and integration tests into one and use roslyn to turn the code and its comments to documentation. 

I wrote extensively about this process on this comment: https://github.com/elastic/elasticsearch-net/issues/1481#issuecomment-120107806

The links are out of date though on that comment but the principal still holds up. 

Here are a couple of example tests:

https://github.com/elastic/elasticsearch-net/blob/2.0/src/Tests/Aggregations/Bucket/ChildrenAggregation.cs

https://github.com/elastic/elasticsearch-net/blob/2.0/src/Tests/Aggregations/WritingAggregations.cs

And here is an example of the output:  

https://github.com/elastic/elasticsearch-net/blob/2.0/docs/contents/new/Aggregations/WritingAggregations.asciidoc

Whats really needed is for these tests to be written :) We are still in refactoring mode on 2.0 before we can start ramping up on those tests though.

**Comment by KodrAus** [comment]
Cool, I'll start taking a look around :)

**Comment by gmarz** [comment]
Closing.  Lets use #1481 to track progress on the new literate testing/documentation.
