### ISSUE TITLE
RandomScore only supports int seed

### ISSUE THREAD

**Issue by jakobt** [elastic/elasticsearch-net#1548]
As i understand you can easily use a string based seed in elasticsearch but the IRandomScoreFunction only supports an integer seed. Using a sessionid or similar rarely produces an int so is there anything wrong in making IRandomScore be string based instead?

**Comment by KodrAus** [comment]
See #1359 it looks like this is lined up for 2.0

**Comment by jakobt** [comment]
So much for trying to search before opening issue, will close this one
