### ISSUE TITLE
Datetime Parse Error

### ISSUE THREAD

**Issue by shoushouleb** [elastic/elasticsearch-net#1550]
Hi when I try to index files I got this:
+		res.ConnectionStatus.OriginalException	{"failed to parse [modified]]; nested: MapperParsingException[failed to parse date field [2015-07-24T14:26:28.7], tried both date format [dd/MM/yyyy], and timestamp number with locale []]; nested: IllegalArgumentException[Invalid format: \"2015-07-24T14:26:28.7\" is malformed at \"15-07-24T14:26:28.7\""}	System.Exception {Elasticsearch.Net.ElasticsearchServerException}

this is the mapping :

<code>
 [ElasticProperty(Name = "modified", Index = FieldIndexOption.NotAnalyzed, Type = FieldType.Date, DateFormat = "dd/MM/yyyy")]
        public DateTime Modified { get; set; }
</code>
Thank you

**Comment by KodrAus** [comment]
The issue here is that you're providing a custom date format for mapping, but it's not being used to serialize your objects.

The culprit seems to be the `NestSerializer.JsonSerializerSettings.DateFormatString` which has a default format that corresponds to the `date_optional_time` format.

The odd thing is though, even if I set the `JsonSerializerSettings.DateFormatString`, it still doesn't use that format when serializing the object.

```
using Nest;
using System;
using System.Linq;
using System.Text;

namespace NestTestDateFormatIndexing
{
    class Program
    {
        [ElasticType]
        class TestClass
        {
            [ElasticProperty(Name = "modified", Index = FieldIndexOption.NotAnalyzed, Type = FieldType.Date, DateFormat = "dd/MM/yyyy")]
            public DateTime Modified { get; set; }
        }

        static void Main(string[] args)
        {
            //Use custom dateformatstring settings
            var settings = new ConnectionSettings();
            settings.SetJsonSerializerSettingsModifier(s => s.DateFormatString = "dd/MM/yyyy");

            var client = new ElasticClient(settings);

            if (!client.IndexExists("test_custom_date").Exists)
            {
                client.CreateIndex("test_custom_date");
                var mapResult = client.Map<TestClass>(m => m
                    .Index("test_custom_date")
                    .MapFromAttributes()
                );
            }

            var indexResult = client.Index(new TestClass { Modified = DateTime.Now }, idx => idx.Index("test_custom_date"));

            var rawRequest = Encoding.Default.GetString(indexResult.ConnectionStatus.Request);

            Console.WriteLine(rawRequest);

            var searchResult = client.Search<TestClass>(body => body
                .Index("test_custom_date")
                .MatchAll()
            );

            Console.WriteLine(searchResult.Documents.First().Modified);
        }
    }
}
```

If I manually , then everything works as expected:

```
[ElasticType]
class TestClass
{
    [ElasticProperty(Name = "modified", Index = FieldIndexOption.NotAnalyzed, Type = FieldType.Date, DateFormat = "dd/MM/yyyy")]
    public string _Modified { get; set; }

    [JsonIgnore]
    public DateTime Modified
    {
        get
        {
            return DateTime.ParseExact(_Modified, "dd/MM/yyyy", CultureInfo.InvariantCulture);
        }
        set
        {
            _Modified = value.ToString("dd/MM/yyyy");
        }
    }
}
```

I'm not sure what to make of the serializer's apparent refusal to use the format you provide it though, but the benefit of this approach is that you can support different formats on the same type in the same request.

**Comment by shoushouleb** [comment]
HI, Thank you I will try and come back to you.

**Comment by shoushouleb** [comment]
@KodrAus 
Worked as sharm !

Thank you a lot, just saved my day :100:

**Comment by KodrAus** [comment]
Awesome :) glad to hear it helped

**Comment by gmarz** [comment]
Thanks @KodrAus
