### ISSUE TITLE
about Fields

### ISSUE THREAD

**Issue by starckgates** [elastic/elasticsearch-net#1551]
in NSET, the doc said:
---------------------------
.Fields(p=>p.Id, p=>p.Name, p=>p.Followers.First().Name, ...)
---------------------------
but in my project
it will use
----------------
.FielddataFields(f=>f.Id)
----------------
so ,i think that's a Issues

**Comment by starckgates** [comment]
Fields 无法进行字段选择

**Comment by gmarz** [comment]
@starckgates sorry, need more context here.  What API is this?  Can you post a full example?

**Comment by gmarz** [comment]
No reply, closing for now.  Feel free to re-open @starckgates if you can provide more context.
