### ISSUE TITLE
Condense and optimize on MergeMustFilters

### ISSUE THREAD

**Issue by mjohnst** [elastic/elasticsearch-net#1554]
When getting filters from an OData query passed into our application:
`$filter=CreatedAt lt 2015-08-31 and CreatedAt gt 2015-08-16`

We have logic to parse either side and merge the `Nest.FilterContainers`:
`return binaryOperatorNode.Left.Accept(this) && binaryOperatorNode.Right.Accept(this);`

However, this results in a ES query like this:
```
  "query": {
    "filtered": {
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "CreatedAt": {
                  "lt": "Mon Aug 31 00:00:00 +00:00 2015"
                }
              }
            },
            {
              "range": {
                "CreatedAt": {
                  "gt": "Sun Aug 16 00:00:00 +00:00 2015"
                }
              }
            }
          ]
        }
      }
    }
  }
```

It would be better if it could result in a query like this:
```
  "query": {
    "filtered": {
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "CreatedAt": {
                  "lt": "Mon Aug 31 00:00:00 +00:00 2015",
                  "gt": "Sun Aug 16 00:00:00 +00:00 2015"
                }
              }
            }
          ]
        }
      }
    }
  }
```

Is there any way we can currently accomplish this, or does there need to be a change made to `BoolIFilterExtensions.MergeMustFilters` to perform this condensation/optimization.

This could be a large performance gain if the first filter performed is more expensive or returns more data than the other filters.

**Comment by Mpdreamz** [comment]
I have no immediate plans to support this, while NEST does rewrite bool dsl (`&&, ||, !, +`) somewhat its mainly meant to flatten the graph where possible (prevent combinatory explosion). I feel optimizations like these should go into elasticsearch itself.
