### ISSUE TITLE
Support for elasticsearch _bulk/index api

### ISSUE THREAD

**Issue by vineet85** [elastic/elasticsearch-net#1556]
Hi,

Can you tell me if there is a way to call the elasticsearch /_bulk/{indexname} api using NEST?
https://www.elastic.co/guide/en/elasticsearch/guide/current/bulk.html#_don_8217_t_repeat_yourself

I am able to find support for POST /_bulk:
Eg:-
var descriptor = new BulkDescriptor();    
foreach (var auditEntity in auditEntities)
   {					  
    descriptor.Index<TAuditEntity>(
		    op => op
		    .Index(indexPatternName)
		    .Document(auditEntity));
    }
var result = this.client.Bulk(descriptor);

Does NEST also support the following two:-
POST
•	/{index}/_bulk 
•	/{index}/{type}/_bulk

Thanks,
Vineet

**Comment by Mpdreamz** [comment]
There is you can call `.FixedPath()` to fixate the the index and/or type for the bulk operation.

**Comment by vineet85** [comment]
Thank you! This worked
