### ISSUE TITLE
Aggregation Filter does not accept raw 

### ISSUE THREAD

**Issue by Nican** [elastic/elasticsearch-net#1566]
Hello! I have hit a bug with using FilterAggregator inside of a AggregationContainer. When applying a raw FilterDescription, the resulting json does not appear inside of the request. 

I have the following code: 
```C#
            var searchRequest = new SearchRequest()
            {
                Aggregations = new Dictionary<string, IAggregationContainer>(),
            };

            var filterContainer = new AggregationContainer()
            {
                Filter = new FilterAggregator
                {
                    Filter = new FilterDescriptor<dynamic>().Raw(@"{""test"":""test""")
                },
                Aggregations = new Dictionary<string, IAggregationContainer>()
            };

            searchRequest.Aggregations["base_filter"] = filterContainer;
            var response = esClient.Search<dynamic>(searchRequest);
```

And this is the request generated by NEST:
```JSON
{
  "aggs": {
    "base_filter": {
      "filter": {},
      "aggs": {}
    }
  }
}
```

As you can see, the {"test":"test"} from the FilterDescriptor does not appear inside of the request. Is there something that I am missing? 

I am using Elasticsearch.Net 1.7.1

**Comment by Mpdreamz** [comment]
Hi Nican,

We found that not all properties that take a Filter/QueryContainer were decorated with something we are working on rectifying in 2.0 with a unit tests to assert all QueryContainer properties have the same jsonconverters set. This is something we have to backport to `1.x`

e.g:
https://github.com/elastic/elasticsearch-net/blob/develop/src/Nest/DSL/Aggregations/FilterAggregationDescriptor.cs#L11

has no dedicated `[JsonConverter]` attribute whereas:

https://github.com/elastic/elasticsearch-net/blob/develop/src/Nest/DSL/SearchDescriptor.cs#L86-L87

does.

**Comment by Nican** [comment]
Any suggestions for a quick workaround while the issue is not fixed?

**Comment by Mpdreamz** [comment]
Hi Nican,

This is now fixed on the `1.x` branch as well and should make it into the next release. Sorry for taking some time to resolve this one.
