### ISSUE TITLE
Update a document without increasing the version.

### ISSUE THREAD

**Issue by TheHunter** [elastic/elasticsearch-net#1567]
Hi everyone,
I would like to know if It's possible to update a document without changing the document version?.
The reason is because my document needs to remove a property, in my case I use a script for do it, so look at this example:

                    var respo = this.Client.Update<object>(descriptor => descriptor
                        .Id(myId)
                        .Type(myDocType)
                        .Index(myIndex)
                        .Script(string.Format("ctx._source.remove(\"{0}\")", "\\" + SessionFieldName))
                        );

I need to remove the given property, but document state is the same, so for this reason I would like to avoid that document version is modified.

Thanks in advance.

**Comment by gmarz** [comment]
You can set `version_type` to `force`, but you would need to know the current version of the document ahead of time:

```csharp
var respo = this.Client.Update<object>(descriptor => descriptor
    .Id(myId)
    .Type(myDocType)
    .Index(myIndex)
    .Version(currentVersion)
    .VersionType(VersionType.Force)
    .Script(string.Format("ctx._source.remove(\"{0}\")", "\\" + SessionFieldName))
);
```

See the [versioning](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html#index-versioning) section of the elasticsearch docs for more info.
