### ISSUE TITLE
Getting value of a node info setting to know if a node is a data node

### ISSUE THREAD

**Issue by TheFireCookie** [elastic/elasticsearch-net#1573]
Hello,

I'm having some troubles on the proper way to get settings of a node with NEST.

The ElasticSearch info I need is here:

http://localhost:9200/_nodes/machineName/settings

Then in "node/data".

What i've found with NEST is this:

```csharp
      dynamic nodeSetting = null;
      esNodeInfos.Settings.TryGetValue("node", out nodeSetting);
      ElasticsearchDynamicValue elasticsearchDynamicValue = nodeSetting;
      var jObject = (JObject)elasticsearchDynamicValue.Value;
      var jProperty = jObject.Property("data");
      if (jProperty == null)
      {
        return false;
      }
```

The real info I need is beeing able to know is that node is a data node or just a master node.

What's the good practise to do this?

Why do we use dynamics to do that?

Thanks!

**Comment by robertlyson** [comment]
I think this one should work for you:

```
var masterNode = (bool)nodeInfoResponse.Nodes["nodeId"].Settings["node"]["master"];
var dataNode = (bool)nodeInfoResponse.Nodes["nodeId"].Settings["node"]["data"];
```

or if you are calling `.NodesInfo(..)` with `FlatSettings()`

```
var masterNode = (bool)nodeInfoResponse.Nodes["nodeId"].Settings["node.master"];
var dataNode = (bool)nodeInfoResponse.Nodes["nodeId"].Settings["node.data"];
```

Hope it helps.

**Comment by TheFireCookie** [comment]
It helps a lot, thanks, its much more beautiful in my code now! :+1:
