### ISSUE TITLE
Memory leak on response

### ISSUE THREAD

**Issue by hantleman** [elastic/elasticsearch-net#1575]
Response does not close correctly. It should be dispose instead of close:
https://github.com/elastic/elasticsearch-net/blob/aa126d672c12e1c7aadeff1abb900127b50b1d68/src/Elasticsearch.Net/Connection/RequestHandlers/RequestHandlerBase.cs#L192

**Comment by Mpdreamz** [comment]
[.Close() calls dispose()](http://referencesource.microsoft.com/#mscorlib/system/io/stream.cs,240)

So this shouldn't leak. We also have a tests in place to make sure streams are closed or disposed: 

https://github.com/elastic/elasticsearch-net/blob/develop/src/Tests/Elasticsearch.Net.Tests.Unit/Memory/ResponseCodePathsMemoryTestsBase.cs#L20

That said I would love to hear if you are experiencing a memory leak!
