### ISSUE TITLE
No overload for method 'Map' takes 0 arguments

### ISSUE THREAD

**Issue by gnudle** [elastic/elasticsearch-net#1580]
According to the NEST documentation,  you can persist attribute based mapping like this:
```
var response = this.ConnectedClient.Map<ElasticSearchProject>();
```
(see: http://nest.azurewebsites.net/nest/indices/put-mapping.html)

However, I'm getting an error saying: No overload for method 'Map' takes 0 arguments

**Comment by TheFireCookie** [comment]
I just think the documentation needs to be updated.

**Comment by Mpdreamz** [comment]
++ Several documentation pages are horribly lacking behind. We are working on a solution for 2.0 where all our code examples are actual code that has to compile or the build will fail.
