### ISSUE TITLE
Cannot reindex all types in 1.7.1

### ISSUE THREAD

**Issue by ashkandaie** [elastic/elasticsearch-net#1583]
After upgrading to v1.7.1 reindex functionality is broken. When reindexing the type System.Object the system no longer reindexes all types. It actually tries to reindex type "object" as seen in this url http://localhost:9200/myindex/object/_search?search_type=scan&scroll=2m&pretty=true.

Looking at the version history for ReindexObservable.cs

In 1.6.x and < it did the following:

```c#
if (typeof(T).Name.Equals(typeof(object).Name))
{
    searchDescriptor = s => searchDescriptor(s).AllTypes();
}
```
SHA: d1f0f4208131ba4cbb3540fc599bb9e313c24eff

This check is no longer being done.

In 1.7.1 and dev branch it simply reads the allTypes internal property from ReindexDescriptor and calls AllTypes on searchDescriptor if true.
 
```c#
var allTypes = this._reindexDescriptor._allTypes;

.....

if (allTypes)
   searchDescriptor.AllTypes();
else
   searchDescriptor.Type<T>();
```
In fact, the internal type allTypes in ReindexDescriptor is never set and cannot be set by the client SDK. 

Wouldn't it be cleaner if NEST supported a non-generic ReindexDescriptor to index all types? 

Should AllTypes be exposed on the fluent API?

Think that at a minimum ReindexDesciptor\<object\> should reindex all types for backward compatibility with 1.6.x and \<.

Happy to submit a PR once confirmed a bug.

**Comment by Mpdreamz** [comment]
Thanks for this @ashkandaie we introduced a non generic [Reindex()](https://github.com/elastic/elasticsearch-net/pull/1440/files#diff-7ebc04cffd1a44c3e7d4b9bef1e19333R19) method on the client itself to cover this use case. The special behaviour of `<object>` was treated as a bug.

See also: https://github.com/elastic/elasticsearch-net/issues/1433

Sorry this bit you ;(

**Comment by ashkandaie** [comment]
Perfect!!

Thank you.
