### ISSUE TITLE
[NEST] Type or namespace name 'ElasticsearchProject' could not be found

### ISSUE THREAD

**Issue by eladnava** [elastic/elasticsearch-net#1585]
Hi,
I feel kind of stupid for writing this, but I can't seem to get any of the example code to compile because of a missing declaration of `ElasticsearchProject`.

          var request = new SearchRequest
            {
                From = 0,
                Size = 10,
                Query = new QueryContainer(new TermQuery
                {
                    Field = "name",
                    Value = "NEST"
                }
                )
            };

            var results = client.Search<ElasticsearchProject>(request);

`Error	1	The type or namespace name 'ElasticsearchProject' could not be found (are you missing a using directive or an assembly reference?)`

I tried searching and I seem to be the only one on the entire planet experiencing this. I'm on VS 2012 Express, if that helps.

Nuget package dependency:
`<package id="NEST" version="1.7.1" targetFramework="net45" />`

What am I missing?

Thanks,
Elad

**Comment by gmarz** [comment]
`ElasticsearchProject` is part of the `Nest.Tests.MockData` assembly and is not part of NEST itself.  It's just a POCO we use for testing and isn't required to use NEST.

If you want to copy the doc examples verbatim then you can copy over `ElasticsearchProject` into your project, but you'll also have to copy over other classes that it depends on: https://github.com/elastic/elasticsearch-net/tree/develop/src/Tests/Nest.Tests.MockData/Domain.

**Comment by eladnava** [comment]
I see. How am I supposed to run the examples without referencing the `Nest.Tests.MockData` assembly?

I think the documentation should be changed as this is very confusing to a NEST newcomer, especially since the Nuget `Install-Package` command doesn't include that assembly and so the example code just doesn't compile.

**Comment by gmarz** [comment]
The purpose of the documentation is to demonstrate how to us the NEST API, and not really meant to be copied and ran verbatim.  You should be substituting `ElasticsearchProject` with a real POCO from your project.

That said, if you want to run the examples verbatim, then you can copy the MockData POCOs into your project as explained above, or you can clone the GH repo and reference `Nest.Tests.MockData`.
