### ISSUE TITLE
End of a request is not traced with async methods

### ISSUE THREAD

**Issue by fedotovalex** [elastic/elasticsearch-net#1589]
When request tracing is enabled and async request methods are used, only the beginning of the request is traced, not the result. This is probably caused by the premature disposal of the TransportRequestState object [here](https://github.com/elastic/elasticsearch-net/blob/develop/src/Elasticsearch.Net/Connection/Transport.cs#L349).

**Comment by Mpdreamz** [comment]
Doh, you are absolutely right @fedotovalex this should be fixed asap.

**Comment by Mpdreamz** [comment]
Took some time but we finally got around to fixing this, should make it in the next release. Thanks again for reporting @fedotovalex :+1:
