### ISSUE TITLE
CatAliases API

### ISSUE THREAD

**Issue by DivyaMalini** [elastic/elasticsearch-net#1591]
Hi
I am using CatAliases API to get the list of all aliases .
My request is something like 
ICatAliasesRequest catAliasesRequest = new CatAliasesRequest();
            return m_elasticClient.CatAliases(catAliasesRequest);

and i am trying to read every record received from response(IEnumerable<CatAliasesRecord>). I am observing that the records returned only have alias and index information and returns null for Search and Index routing .

Could anyone please confirm if this is a known issue or point me if i am doing something wrong ?

Thanks in advance !!

**Comment by robertlyson** [comment]
Hi @DivyaMalini,

Did you set routing value during alias creation? Have a look into [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-aliases.html#aliases-routing).

This is how you can do this with the NEST:
- Object initializer
```
var putAliasResponse = client.PutAlias(new PutAliasRequest("name")
{
    Routing = "routing"
});
```
- Fluent
```
var putAliasResponse = client.PutAlias(a => a
	.Index(indexName)
	.Name("name")
	.Routing("routing"));
```
Hope it helps.

**Comment by DivyaMalini** [comment]
Hi @robertlyson ,

Yes i had set the routing value during alias creation. Even when i directly run the command through sense plugin (GET _cat/aliases), the results displayed has SearchRouting values set. It is when I used the API in my c# code , i found the results whose routing values are null .

**Comment by robertlyson** [comment]
@DivyaMalini may you share more information about your alias?

**Comment by DivyaMalini** [comment]
@robertlyson ,

My PutAlias call is defined like this 

public IPutAliasResponse PutAlias(string indexName, string aliasName)
        {
            var request = new PutAliasRequest(aliasName)
            {
                Index = new IndexNameMarker()
                {
                    Name = indexName
                },
                Routing = Gid.NewGuid()
            };         
            return elasticClient.PutAlias(request);
        }


The _cat/Aliases call through sense plugin gives aliasName, indexName, Filter, Search and Index routing.

But when executed via code 
public ICatResponse<CatAliasesRecord> CatAliases(ICatAliasesRequest request)
{
         CatAliasesRequest req = new CatAliasesRequest();
         client.CatAliases(req);
}

in the catAliasesRecord obtained all the aliases routing(index and search) are returned null

FYI , i use Nest 1.6.0

**Comment by robertlyson** [comment]
@DivyaMalini looks like a bug, so I've created https://github.com/elastic/elasticsearch-net/pull/1593 to address this issue.

**Comment by DivyaMalini** [comment]
@robertlyson , Great !!! Thanks a lot ...
