### ISSUE TITLE
Missing support for naming filters in aggregations

### ISSUE THREAD

**Issue by omeaart** [elastic/elasticsearch-net#1592]
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-filters-aggregation.html

I'm trying to build an aggregation query of the following form:
```
"aggs": {
      "agg-name": {
         "filters": {
            "filters": {
               "filter1-name": {
                  "terms": {
                     "field1": [
                        "val1"
                     ]
                  }
               },
               "filter2-name": {
                  "match_all": {}
               }
            }
         },
         "aggs": {
            ...
         }
    }
}
```

But I can't figure out how to pass the filter names (filter1-name,filter2-name) in the NEST methods. Is this supported?

**Comment by Mpdreamz** [comment]
This should be available, we support both the named and anonymous filter syntax see this integration test:

https://github.com/elastic/elasticsearch-net/blob/develop/src/Tests/Nest.Tests.Integration/Aggregations/FIltersAggregationTests.cs#L15
