### ISSUE TITLE
SuggestOption is missing Highlighted field.

### ISSUE THREAD

**Issue by Beanow** [elastic/elasticsearch-net#1595]
While highlighting is supported using the fluent API, the result is discarded because SuggestOption is missing this property. See [SuggestOption.cs](https://github.com/elastic/elasticsearch-net/blob/develop/src/Nest/Domain/Suggest/SuggestOption.cs).

**Comment by gmarz** [comment]
Thanks for reporting @Beanow, we'll fix this for the next release.
