### ISSUE TITLE
Nested Attribute not working with ElasticSearch 2.0

### ISSUE THREAD

**Issue by TheKahuna** [elastic/elasticsearch-net#1601]
When indexing my data to elastic search 2.0, a property with the [ElasticProperty(Type = FieldType.Nested)] attribute is not mapped has a nested property on Elastic Search (it is working wiht ES v1.7.3)

NEST Library v1.0

**Comment by Mpdreamz** [comment]
@TheKahuna we are working hard on NEST 2.0. NEST 1.x is not completely compatible with ES 2.0

**Comment by TheKahuna** [comment]
Agrrr... Sorry, maybe next time I should read the docs ;)
Any idea on the release date?

**Comment by Mpdreamz** [comment]
We are still a couple weeks out to releasing sadly

**Comment by TheKahuna** [comment]
Ok, I'll on the lookout! Closing has its not a issue.
Just a sugestion, you could update the description of the project saying that is not compatible with ES v2.0
