### ISSUE TITLE
Question: After upgrading to ES 2.0, Should I use NEST 1.7.1, or compile myself a version from the 2.0 branch until it's officially released?

### ISSUE THREAD

**Issue by jonyadamit** [elastic/elasticsearch-net#1604]
(For development purposes)
To be more specific, will the Query DSL changes have big impact on the NEST API?

**Comment by Mpdreamz** [comment]
Hey @jonyadamit,

Yes they will. Eventhough a lot of the query refactoring on ES is backwards compatible NEST 2.x will reflect the new state of afairs this means that for instance we removed all our `*Filter` classes

You could use 1.7.1 but please keep in mind the [breaking changes in Elasticsearch 2.x](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking-changes-2.0.html) that might not have been reflected in 2.0. We do not have a full write up of things we expect to break when using NEST 1.x against Elasticsearch 2.x just yet.

As soon as we have our query/aggregations resynced with 2.0 (including the new pipeline aggregations) and we got rid of most of our todo list we will release an alpha of NEST 2.0.

We hope to release an alpha that end of next week.

**Comment by jonyadamit** [comment]
@Mpdreamz thank you very much for the quick response.
I never had the chance to contribute to a github repository and am thinking to try and help with yours :-) 
I just want to see I understand things correctly:
When you mention that todo list, are you referring to the open issues?
I see for example, that the `BoolQuery` does not contain a *filter* `QueryContainer`, which is a must if we want to sync with 2.0 - yet I do not see an open issue regarding this. 
Is this something an issue needs to be opened for? Or is that todo list somewhere else?

**Comment by Mpdreamz** [comment]
No problem! We are currently in beastmode getting things done and our administration is lacking a tad.

Our two master issues for 2.0 are:

https://github.com/elastic/elasticsearch-net/issues/1481

and

https://github.com/elastic/elasticsearch-net/issues/1586

But we need to update them to reflect the current state of the 2.0 branch. The query dsl / aggregations right now are hotspots and we hope to get them done asap.

I would love to help you get your first Github contribution after our alpha goes out the door, hit me up on Skype!
