### ISSUE TITLE
NEST.SearchDescriptor<T>: Fields() methods signature incompatible with C# 6 

### ISSUE THREAD

**Issue by AKlaus** [elastic/elasticsearch-net#1605]
There are 2 methods Fields() with optional collection of parameters:
```
public SearchDescriptor<T> Fields(params Expression<Func<T, object>>[] expressions);
public SearchDescriptor<T> Fields(params string[] fields);
```
It's possible to call `Fields()` without parametersfor C# 5 and below (does it get resolved to the first method?). But in C# 6 they changed [the rules](http://stackoverflow.com/q/31877169/968003) and error "`CS0121 The call is ambiguous`" is reaised.

**Comment by Mpdreamz** [comment]
Thanks for the heads up! 

Already on top of this one :+1: 

Our upcoming 2.0 release is C# 6 throughout and Fields() has [been remodelled](https://github.com/elastic/elasticsearch-net/blob/2.0/src/Tests/ClientConcepts/HighLevel/Inferrence/FieldNames/FieldInference.doc.cs)

**Comment by dotcom9** [comment]
Broken link above
