### ISSUE TITLE
Parent-Child mapping in ES 2.0

### ISSUE THREAD

**Issue by samjudson** [elastic/elasticsearch-net#1608]
Hi

I'm trying to create a parent-child relationship in ES 2.0. We have this up and running in ES 1.73 fine, but the new restriction in 2.0 that the parent type cannot already exist means I need to send both mappings to ES at the same time.

However using the Nest 1.7.* code I can't see a way to do this. The Map<T>() method only takes one type (and the none-generic version looks to do the same).

Is this possible, or do we need to move to a beta version of Nest 2.0.

If this isn't possible I think I'll have to try to work around it with a template or something.

Sam

**Comment by samjudson** [comment]
Just realised I can do this on index creation - however would still be useful to know if it can be done any other way. Cheers.

**Comment by gmarz** [comment]
@samjudson setting this up at index creation is the right approach.  The put mapping API doesn't work on multiple types in the same request- so it wouldn't make sense to extend Map() to allow for multiple types either.

**Comment by samjudson** [comment]
Sorry, you are right, thanks.
