### ISSUE TITLE
AutoMap with NoopPropertyVisitor does not process attribute values. 2.0

### ISSUE THREAD

**Issue by zabykrinich** [elastic/elasticsearch-net#1610]
Sorry if I create the issue too early and feature is under development.
I tried to create MapFromAttribute mapping using AutoMap.
There is following type: 
```[ElasticsearchType(IdProperty = "Id", Name = "FooType")]```
```public class FooType```
{
     ```[Number(Name = "Id", Type = NumberType.Integer, DocValues = true)]```
     ```public int Id { get; set; }```
}

I use: ```client.Map<FooType>(m => m.Index("FooIndex").AutoMap());``` Mapping created for the FooType does not contain attribute values. Only mapping from type.

I did some debugging with code from 2.0 branch and found following: function GetProperty(PropertyInfo propertyInfo, ElasticsearchPropertyAttribute attribute) in src/Nest/Mapping/Visitor/PropertyWalker.cs; 

// Takes property from attribute
   ``` if (attribute != null)```
           ```property = attribute.ToProperty();```

// Reset property to values taken from type
   ``` property = InferProperty(propertyInfo.PropertyType);```

May be this is the reason, or it can be my wrong understanding of the function. Should it be updated  in custom visitor? Should AutoMap generate mapping from attributes?

**Comment by gmarz** [comment]
Hey @zabykrinich this is definitely wrong.  Your understanding is correct in that AutoMap() should treat attributes with a higher precedence, and only infer when there is no attribute, or when a mapping is defined explicitly in the mapping call.

It is indeed still under development, and we have plans to revisit and test the new mappings heavily before releasing 2.0 alpha, so we'll be sure this gets fixed.

Thanks for raising this issue!

**Comment by zabykrinich** [comment]
Hello, 
After https://github.com/elastic/elasticsearch-net/commit/ce7b412cd96e3803c8c4dbcef1b92d64f3e648b6
I see one more problem:
It produces mapping json with some fields with default values even if I don't set them in the attributes. 
For example: 
[Number(Name = "Id", Type = NumberType.Integer, DocValues = true)]
gives 
"Id": {"boost": 0.0, "null_value": 0.0, "include_in_all": false, "precision_step": 0, "ignore_malformed": false, "type": "integer", "doc_values": true, "store": false}
and I expect
"Id": { "type": "integer", "doc_values": true}
It seems the problem is in NumberAttribute. Its fields can't be nullable and memberInfo.GetCustomAttributes produces Attribute with fields set.
Hope it will help in testing :-)

**Comment by gmarz** [comment]
This is all fixed now.  Thanks for raising these issues @zabykrinich !
