### ISSUE TITLE
Unify NEST and Elastic names for Greater/Less/Lower ranges

### ISSUE THREAD

**Issue by asd-and-Rizzo** [elastic/elasticsearch-net#1611]
1. Elastic has
```	
Greater-than
Less-than
```
[1]

2. In NEST code I type in our project:
```
f => f.Range(range => range.Greater(lowerDate.ToString(DateFormat, CultureInfo.InvariantCulture)).Lower(greaterDate.ToString(DateFormat, CultureInfo.InvariantCulture))
```

Greater = GreaterThan = lowerDate in our REST API
Lower= LessThan = greaterDate in our REST API

Not very easy to grasp.

This happened partially because NEST API is kind of misleading.

Expected:
0. Unification of NEST names with Elastic to simplifying query build and understanding, to maintain same languages of users of NEST and HEAD.

1. `Lower` should be obsolete and replaces with `Less`:
```
f => f.Range(range => range.Greater(lowerDate.ToString(DateFormat, CultureInfo.InvariantCulture)).Less(greaterDate.ToString(DateFormat, CultureInfo.InvariantCulture))
```

Better `Greater` and `Lower` obsolete and replaced with:
```
f => f.Range(range => range.GreaterThan(lowerDate.ToString(DateFormat, CultureInfo.InvariantCulture)).LessThan(greaterDate.ToString(DateFormat, CultureInfo.InvariantCulture))
```

so we can improve language of our project and REST API either to simplify things (and use custom reporting directly against Elastic with same language against our NEST code):
```
f => f.Range(range => range.GreaterThan(greaterThanDate.ToString(DateFormat, CultureInfo.InvariantCulture)).LessThan(lessThanDate.ToString(DateFormat, CultureInfo.InvariantCulture))
```

[1] : https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html

**Comment by Mpdreamz** [comment]
huge +1 :+1: 

We'll take this on board for 2.0 

Also our GeoDistanceRangeQuery mapping still uses `from/to/include_lower/include_upper` instead of `gt/etc. `from/to` still works in Elasticsearch 2.0 but is deprecated and undocumented
