### ISSUE TITLE
Filter<T>.Term vs Filter<T>.Terms parameter types

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#1612]
The api is inconsistent in between Term and Terms.

For example I can do this 

```csharp
Filter<T>.Term("age", 21);
```

but not 

```csharp
Filter<T>.Terms("age", new int[] { 21, 22 });
```

Please note that this is an example of the inconsistencies...

**Comment by gmarz** [comment]
Agreed, it should be `Terms<K>`

We have a few other inconsistencies (https://github.com/elastic/elasticsearch-net/issues/1549) that we're aware of- this is something we're definitely going to address for 2.0 alpha.

Thanks for raising this.

**Comment by Mpdreamz** [comment]
See last attached commit
