### ISSUE TITLE
Incorrect properties for a Completion type

### ISSUE THREAD

**Issue by AIsaac08** [elastic/elasticsearch-net#1617]
When I'm declaring my mapping, in the Completion Type is missing the analyzer properties, instead you have IndexAnalyzer.

Example:
```c#
.AddMapping<MyModel>(m => m
    .Properties(p => p
        .Completion(c => c.Name(n => n.MyProperty).IndexAnalyzer("custom_analyzer").Payloads(true))
    )
)
```
when it should be:
```c#
.AddMapping<MyModel>(m => m
    .Properties(p => p
        .Completion(c => c.Name(n => n.MyProperty).Analyzer("custom_analyzer").Payloads(true))
    )
)
```

Reference: https://www.elastic.co/guide/en/elasticsearch/guide/current/_controlling_analysis.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html#completion-suggester-mapping

**Comment by AIsaac08** [comment]
Sorry guys, I think I just made a mistake here :/

**Comment by michaelbudnik** [comment]
This is right for 1.7. See https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-suggesters-completion.html

**Comment by gmarz** [comment]
Thanks @michaelbudnik

**Comment by AIsaac08** [comment]
Excuse me, but, when we will see this on NuGet Gallery?
