### ISSUE TITLE
IndexExistsAsync response IsValid is false when index doesn't exist

### ISSUE THREAD

**Issue by michaelbudnik** [elastic/elasticsearch-net#1621]
2.0 branch.
I would expect the same behavior as in 1.7.x.
IsValid should be true if we get a correct (expected) response from ES? 404 is ok I guess.
My code I've used to use:

    public async Task<bool> DoesIndexExist(string indexName)
        {
            var response = await UnderlyingClient.IndexExistsAsync(indexName);
            if (response.IsValid)
            {
                return response.Exists;
            }
            else
            {
                throw new ElasticSearchErrorException(string.Format("Error while checking existence of index: {0}", indexName)
                    , response.ServerError);
            }
        }

**Comment by gmarz** [comment]
Yea, you're correct- a 404 is a valid response.  We'll fix this,  Thanks for reporting :+1:

**Comment by russcam** [comment]
The behaviour in 2.0 branch now matches 1.7.x as verified by the following

```c#
[U]
public async Task Test()
{
    var client = new ElasticClient();

    var nonExistentIndex = "foobar";
    var response = await client.IndexExistsAsync(nonExistentIndex );

    response.IsValid.Should().BeTrue();
    response.Exists.Should().BeFalse();
    response.ApiCall.HttpStatusCode.Should().Be(404);
}
```
