### ISSUE TITLE
How to set dynamic=strict in mapping for nested object?

### ISSUE THREAD

**Issue by hmanner** [elastic/elasticsearch-net#1622]
I am using MapFromAttributes() together with the following to create a mapping for a nested object:

[ElasticProperty(Type = FieldType.Nested, ...]
public MyNestedType MyNestedObject { get; set; }

In addition to this I want to set the dynamic property to strict on the nested object, as described here:

https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html#nested-params

I have already set the dynamic property to strict on the root object, and verified that this works (introducing new fields dynamically on top level in the root object is not possible). But the setting is not inherited to the nested object as far as I can see. The Elasticsearch documentation is a bit unclear on this, it does state that the setting is inherited to inner objects but does not mention nested objects:

https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic.html

I realize that the above is more suited for an Elasticsearch forum. The question for this issue is: How do I set dynamic = strict on nested objects using NEST and MapFromAttributes? Or is there another way?

**Comment by gmarz** [comment]
This isn't possible in NEST 1.x using attributes, as they don't expose all the possible options for a given type.  You have to use the fluent API instead within either the `CreateIndex()` or `Map()` calls.  See  [this test](https://github.com/elastic/elasticsearch-net/blob/develop/src/Tests/Nest.Tests.Unit/Core/Map/Properties/PropertiesTests.cs#L179) for an example.

This however will be possible in NEST 2.0 with the new attribute mapping API: https://github.com/elastic/elasticsearch-net/pull/1520
