### ISSUE TITLE
Aggregation, suggestion in ElasticSearch (Nest, Elasticsearch.net) get complete object

### ISSUE THREAD

**Issue by shreemada** [elastic/elasticsearch-net#1623]
I'm quite new to elasticsearch, I am using NEST to query to elastic following is my code snippet.

      var searchResults =
            elasticClient.Client.Search<T>(
            s => s
                    .Size(20)
                    .Fields(core)
                    .QueryString(String.Format("*{0}*", query)).MinScore(1).QueryString(String.Format("*{0}*", query.Replace(" ", "")))
                    .Highlight(h => h
                    .PreTags("<b>")
                    .PostTags("</b>")
                    .OnFields(f => f
                        .PreTags("<em>")
                        .PostTags("</em>")
                    )
                )
            );

    var suggestResults = elasticClient.Client.Suggest<T>(s => s
                                        .Term("suggest", m => m
                                            .SuggestMode(SuggestMode.Always)
                                            .Text(query)
                                            .Size(10)
                                            .OnField(core)
                                        ));

    var aggregation = elasticClient.Client.Search<T>(s => s
            .Aggregations(a => a
                .Terms("term_items", gh=>gh
                    .Field(p=>p.Town)
                    .Aggregations(gha=>gha
                        .SignificantTerms("bucket_agg", m => m
                            .Field(p => p.Town)
                            .Size(2)
                            .Aggregations(ma => ma.Terms("Town", t => t.Field(p => p.Town)))
                        )
                    )
                )
            )
       );

  

I do get list of documents (list of my specified domain object) , but in case of suggest and aggregation it doesn't return domain object ?

I apologize in advanced and I hope you can point me to the correct direction.

I am looking for a way to implement in NEST.

**Comment by michaelbudnik** [comment]
Suggestions are designed like this.
https://www.elastic.co/guide/en/elasticsearch/reference/1.7/search-suggesters.html

Don't remember about aggregations but you can try top hits aggregations.
Those are Elasticsearch related questions, not related to Nest.
Please read Elasticsearch documentation

**Comment by shreemada** [comment]
thank you @michaelbudnik for reply.
looking at the documentation it seems that , it just returns the text not the document object.

**Comment by gmarz** [comment]
Thanks @michaelbudnik 

@shreemada correct, the significant terms aggregation only returns the terms and not the documents which contains them.  You can however add [top hits](https://www.elastic.co/guide/en/elasticsearch/reference/1.4/search-aggregations-metrics-top-hits-aggregation.html) as a sub-aggregation to retrieve the N most relevant documents containing those terms, which may get you close to what you're trying to achieve.

**Comment by shreemada** [comment]
@gmarz  Thank you
