### ISSUE TITLE
HistogramItem's Date property has unspecified DateTime Kind

### ISSUE THREAD

**Issue by rokeller** [elastic/elasticsearch-net#1626]
Despite the fact that ElasticSearch's response includes time zone information, the parsed value in the Date property of HistogramItem instances has the Kind property set to 'Unspecified', which is just wrong. I.e. the following Assert would fail:

```
HistogramItem histogramItem = // ... get from ElasticSearch
Assert.AreNotEqual(DateTimeKind.Unspecified, histogramItem.Date.Kind, "The DateTime Kind must not be Unspecified");
```

Since the timezone information is present, it should be parsed with that and then accordingly the DateTimeKind should be set on the parsed value.

This is for 1.7.1

**Comment by Mpdreamz** [comment]
Sorry for the late reply, elasticsearch stores and returns dates in utc so we should specify DateTimeKind.Utc.

This also needs forward porting to `2.x` 

Thanks for reporting this issue :+1:
