### ISSUE TITLE
Meta fields mapping changes ( _id, _routing ... ) [2.0]

### ISSUE THREAD

**Issue by michaelbudnik** [elastic/elasticsearch-net#1630]
This is for 2.0 branch.

In ES 2.0 your not allowed to configure _id field anymore which makes IdField class obsolete.
Some other meta field classes are also not updated yet.

See https://www.elastic.co/blog/great-mapping-refactoring#meta-fields and https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#migration-meta-fields.

```
{
  "error" : {
    "root_cause" : [ {
      "type" : "mapper_parsing_exception",
      "reason" : "_id is not configurable"
    } ],
    "type" : "mapper_parsing_exception",
    "reason" : "_id is not configurable"
  },
  "status" : 400
}
```

**Comment by gmarz** [comment]
Thanks @michaelbudnik, this has long been on our TODO list and now fixed via https://github.com/elastic/elasticsearch-net/commit/5b982abcadfa7102c58398419d48bf2b800bdce6
