### ISSUE TITLE
2.0 much worse serialization performance compared to 1.x

### ISSUE THREAD

**Issue by michaelbudnik** [elastic/elasticsearch-net#1631]
Sorry guys about that, but I may be reporting more stuff, because I'm evaluating upgrade to 2.0.
May help you with some stuff if I have time.
If you feel that's 2.0 branch is not in a state to report issues related to it just let me know and I'll stop =]

Testing with bulk index request (IndexMany).
2000 objects in a bulk (30 short fields on average per object).

**Used to take less than a second** with ES being the bottleneck but **now it takes about 20-25 seconds** where almost all the time the code is executing is on the client server serializing the request.
Comparing 2.0 (ES & Nest) vs 1.7 (ES & Nest)

Made some performance analysis with VS and it seems CPU hot paths mostly include
Newtonsoft.Json and **ElasticContractResolver**.

Tried with release build but no improvements.

**Comment by Mpdreamz** [comment]
@michaelbudnik, much much love for this please don't apologize for opening tickets against our 2.0 branch, that's awesome. We still have to do profiling deep dives and this particular one was already on our horizon :+1: 

I have some comments on the implementation but I'll switch those over to the PR :)
