### ISSUE TITLE
SetJsonSerializerSettingsModifier method in ConnectionSettings class not working.

### ISSUE THREAD

**Issue by michaelbudnik** [elastic/elasticsearch-net#1636]
Branch 2.0.

The problem occurs when you don't provide your own `IElasticsearchSerializer` instance to `ConnectionSettings` constructor (which I never do).
The default serializer is getting created at base class (`ConnectionConfiguration`) [here](https://github.com/elastic/elasticsearch-net/blob/dd5e964a3b2663ddb77908560234ee629e9971d8/src/Elasticsearch.Net/Configuration/ConnectionConfiguration.cs#L162) which creates `new NestSerializer(this)` [here](https://github.com/elastic/elasticsearch-net/blob/dd5e964a3b2663ddb77908560234ee629e9971d8/src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettings.cs#L92)
After this point there is no way of changing json settings because they are used in `NestSerializer`constructor only (which was already called).

Hope it will make sense to someone :smile:

**Comment by michaelbudnik** [comment]
It's almost like a circular dependency.
`NestSerializer` depends on settings (constructor requires it).
`ConnectionSettings` contains serializer (injected trough constructor or creates default `new NestSerializer(this)`).

Can't change the serializer after creating settings. 
Can't change settings after creating serializer, because they are used only in constructor.

**Comment by gmarz** [comment]
Closed via https://github.com/elastic/elasticsearch-net/pull/1703
