### ISSUE TITLE
Disable caching for Terms Filter (Nest 1.7.1)

### ISSUE THREAD

**Issue by MrHypnos** [elastic/elasticsearch-net#1637]
Hi there,

According to https://www.elastic.co/guide/en/elasticsearch/reference/1.7/query-dsl-terms-filter.html, you can disable caching for Terms filter query.

I am right assuming that they are not cache control at the moment with Nest fluent interfaces on "Term" and "Terms" filter queries?

Here is my terms filter: 
filterDescriptor.Terms("documentId", documentIds.Select(x => x.ToString()), TermsExecution.Plain)

Thanks,

**Comment by Mpdreamz** [comment]
The FilterDescriptor does not expose a `.Terms(f=>f)` where f is a `Func<TermsFilterDescriptor, ITermsFilter>`. It only has short version overloads.

See also:

https://github.com/elastic/elasticsearch-net/blob/develop/src/Nest/DSL/Filter/FilterDescriptor.cs#L767

The QueryDescriptor does have this:

https://github.com/elastic/elasticsearch-net/blob/develop/src/Nest/DSL/Query/QueryDescriptor.cs#L156

In 2.0 this all normalized. But we should definitely expose this in the first 1.7.x NEST bug fix release.

**Comment by Mpdreamz** [comment]
Ok on second inspection it seems i was confused back in November. 

You can use `f=>f.Cache(false).Terms()` in `1.x` 

Sorry we left this ticket open for so long
