### ISSUE TITLE
Unit is missing when using ConnectionSettings() in conjunction with SniffOnConnectionFault() and SniffOnStartup()

### ISSUE THREAD

**Issue by lgaill02** [elastic/elasticsearch-net#1639]
After upgrading from Elasticsearch 1.4.1 to Elasticsearch v2.0, I can no longer connect using NEST.

This used to work in v1.4.1:

    http://localhost:9200/_nodes/_all/clear?timeout=50

Unfortunately, it no longer works with Elasticsearch 2.0, as I now get an ElasticsearchParseException ("Failed to parse setting [NodesInfoRequest.timeout] with value [50] as a time value: unit is missing or unrecognized").

This works (note the "ms" at the end):
 
    http://localhost:9200/_nodes/_all/clear?timeout=50ms

We use Nest to connect to Elasticsearch using a ConnectionSettings object with SniffOnConnectionFault and SniffOnStartup functions, and it generates that obsolete URL (without the unit).

We're stumped... can't upgrade to Elasticsearch 2.0!

**Comment by jonyadamit** [comment]
@lgaill02, Please note Nest 2.0 hasn't been released yet.
A possible fix is in #1657, but it hasn't been reviewed yet.

**Comment by Mpdreamz** [comment]
This is fixed on the master (2.0) branch now, thanks for reporting @lgaill02 :+1:
