### ISSUE TITLE
C# to Java type mapping

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#1643]
I have a dictionary that I do [dynamic mapping on in our app](https://github.com/exceptionless/Exceptionless/blob/master/Source/Core/Pipeline/035_CopySimpleDataToIdxAction.cs). I append a type suffix to the field name so I can share mappings (multi tenant). Currently I'm only handling decimal and double mappings in .net and this leads to some insert errors when I detect it incorrectly (obviously a bug on our part).. I think the solutions for us going forward is to have a typed field mapping based on the suffix that maps to the largest numeric type (sucks because you use more memory) or parse out the specific type (and use more processing time).

I wanted to look through your code to see if I could find a method where I could pass a type/instance or string (do a parse of the type for me) and return the name it would be mapped to (E.G., `number`). I came across [this](https://github.com/elastic/elasticsearch-net/blob/5b1ada2a9fc9d2f2d9e4168ece7ae8e7d7b01724/src/Nest/Resolvers/Writers/TypeMappingWriter.cs#L278-L309) and [this in master](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Resolvers/Writers/TypeMappingWriter.cs#L258). To my knowledge, correct me if I'm wrong.. seem to incorrectly handle some data types incorrectly or not at all. For example it doesn't seem like some data types are handled like `DateTimeOffset` and possibly some numeric types. Secondly the [java types](http://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html) as defined here don't match up with your [.NET data type mappings](https://msdn.microsoft.com/en-us/library/ms228360(v=vs.90).aspx). Example:

Java `byte` is -128 to 127 which is the same as a .NET SByte. In the code I saw you had it mapped to a .NET `Byte` as well which is 0-255. Which I believe the methods would return the incorrect mapping if the value is >127.

Would it be possible to expose some helper methods that make it easier to get the mapped types as well as update these mappings?

**Comment by russcam** [comment]
@niemyjski thanks for reporting this. I'm looking at this in the 2.0 branch, with the following C# to Elasticsearch data type mappings:

| .NET Type | Elasticsearch Type |
| --------- | ------------------ |
| `System.Byte`      | [`short`](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/number.html) |
| `System.Int16`     | [`short`](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/number.html) |
| `System.Int32`     | [`integer`](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/number.html) |
| `System.Int64`     | [`long`](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/number.html) |
| `System.Single`    | [`float`](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/number.html) |
| `System.Double`    | [`double`](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/number.html) |
| `System.Decimal`   | [`double`](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/number.html) |
| `System.SByte`     | [`byte`](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/number.html) |
| `System.UInt16`    | [`integer`](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/number.html) |
| `System.UInt32`    | [`long`](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/number.html) |
| `System.UInt64`    | [`double`](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/number.html) |
| `System.Boolean`   | [`boolean`](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/boolean.html) |
| `System.Char`      | [`string`](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/string.html) |
| `System.String`    | [`string`](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/string.html) |
| `System.Guid` | [`string`](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/string.html) |
| `System.DateTime`      | [`date`](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/date.html) |
| `System.DateTimeOffset` | [`date`](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/date.html) |

/cc @gmarz @Mpdreamz, I think we should consider also handling `System.TimeSpan` by default, storing it as a [`double`](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/number.html) representing the TotalMilliseconds of the TimeSpan. Storing it as a string makes less sense to me as you may want to query on the field and this would be unituitive on a string field. 

Within the 2.0 branch, you can use the [`PropertyWalker`](https://github.com/elastic/elasticsearch-net/blob/2.0/src/Nest/Mapping/Visitor/PropertyWalker.cs) to get the mapped properties for a given type.

**Comment by Mpdreamz** [comment]
Closing this as we are doing the correct thing in 2.0 (unless i'm going crosseyed @niemyjski @russcam please reopen!)

**Comment by russcam** [comment]
@Mpdreamz We adhere to the above mappings in 2.0 (and also have been backported to the next release of 1.x). 

The only remaining consideration is handling `TimeSpan` by default - this would require a custom `JsonConverter` to handle serialization/deserialization to and from a `double`. I'll open as a separate issue for consideration.

**Comment by niemyjski** [comment]
@russcam was this back ported to 1.8?

**Comment by russcam** [comment]
@niemyjski yes, it went into 1.7.2 in aa8c9931fad056affacf16b234f87d88f4ca938f
