### ISSUE TITLE
Serialization performance once again

### ISSUE THREAD

**Issue by michaelbudnik** [elastic/elasticsearch-net#1644]
Branch 2.0

A query with about 10 leaf filters/queries (which results in about 3KB JSON) takes more time to serialize than deserializaiton of almost 1MB response.

Did some performance sampling to find this out.

I wouldn't expect Newtonsoft.Json to be such slow. There are many calls to Reserialize converter along the serialization call tree.

![nest-serialization](https://cloud.githubusercontent.com/assets/10867000/11499657/937b0ade-981f-11e5-85cc-6f026d45ac92.PNG)

And here you can compare the total server time vs time spent on elasticsearch (about 10/1 ratio).
Over 250ms total response time when the search takes 30ms cannot be acceptable.

![server time vs elasticsearch time](https://cloud.githubusercontent.com/assets/10867000/11499666/9b3e9182-981f-11e5-9ad7-dca2f09886cd.PNG)

The same query with almost empty response (no hits) takes at minimum 150ms to complete.

**Comment by Mpdreamz** [comment]
@michaelbudnik started working on this yesterday as part of a bigger clean up our json.net contract.

Thanks for reporting :+1:

**Comment by michaelbudnik** [comment]
Just updated my project with recent Nest (master) and it seems this problem is still valid.

**Comment by gmarz** [comment]
@michaelbudnik going to try and reproduce this.  In the mean time, any chance you can post your query here?

**Comment by michaelbudnik** [comment]
I might have problem finding it, but it was bool query with several filters and also compound query part.
You don't need to actually have any data in elasticsearch to test it. You can execute a query against empty elasticsearch and you can observ that serializing the query takes an order of magnitude more time time than deserializing the error response about missing index.

**Comment by gmarz** [comment]
Right, no worries- I thought it might make things easier initially, but I'm able to see the issue with just a single match query.

The bottleneck definitely lies within ReserializeJsonConverter, as you already mentioned.  Particularly in `Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object)`.

**Comment by gmarz** [comment]
@michaelbudnik I think I found and fixed the culprit: https://github.com/elastic/elasticsearch-net/commit/8b50bfbfde55e9512f1610cad3e0e33cb5209b05

We were looking up properties in the cache, but not adding to it!  Silly mistake.

Would you mind building the latest master and running your tests again?

**Comment by gmarz** [comment]
Removed the blocks 2.0-alpha label, but will leave this open until @michaelbudnik confirms on his end.

Huuuge :+1: @michaelbudnik for reporting this!

**Comment by michaelbudnik** [comment]
It is 2-3 times faster now :+1: which makes it ok for production for me.
My queries went down from ~300ms to ~120ms (everything on localhost).
The serialization still takes a lot more time compared to deserialization.
If I have some free time (not till end of Jan) I might consider spending some time on this.
I didn't make any comparison to 1.7.x branch.

I will leave the decision to you to close this issue because performance optimization is a never ending story :)

Thanks for the fix

**Comment by michaelbudnik** [comment]
Hey guys,

So I spent a little bit of time investigating what's the problem.
I was looking at caching capabilities of Newtonsoft.Json vs what you do.
I was thinking about the cache's lifetime.

So I registered IElasticClient implementation (ElasticClient) as a singleton (as opposed to instance per request) in my ASP.NET IoC configuration. I was comparing my queries with Size=0 so response was pretty much empty.

Here are the results **before** the change:
![before](https://cloud.githubusercontent.com/assets/10867000/12980469/73afc012-d0d4-11e5-868f-0b85d532f9de.PNG)

And here are the results **after**:
![after](https://cloud.githubusercontent.com/assets/10867000/12980487/83ab9f4a-d0d4-11e5-898a-60f2b7d35ed6.PNG)

Calls to localhost:52xxx are calls to ASP.NET app and they measure total time.
Each of the call is then followed by 2 calls to Elasticsearch from within ASP.NET (using Nest).
Time spent in the app is total time of the request minus time of requests to ES.

In the first set of measurements you can see that it's about 70-80ms.
After the change it's about 10-15ms. Huge performance gain.

My question is: Is ElasticClient safe to be used as a singleton? Is it thread-safe?

Maybe it's worth to try to cache (static?) ElasticContractResolver?

**Comment by Mpdreamz** [comment]
Hey @michaelbudnik 

This is something that we should have said from the get go, sorry for dropping the ball here!

Yeah `ConnectionSettings` is very much intended to keep alive for as long as possible, as all the caches are per ConnectionSettings. This is intended because two clients with two different settings should not bleed into eachother. 

`IElasticClient` can be instantiated (using a singleton ConnectionSettings) everytime or also be kept around as singleton as its thread safe. Most of our components are unless explicitly specified (MemberInfoVisitor/PropertyNameVisitor come to mind)

Very glad this is now resolved on your end! :tada: :balloon: :fireworks: :cake:
