### ISSUE TITLE
Building the 2.0 branch [2.0]

### ISSUE THREAD

**Issue by mtolman** [elastic/elasticsearch-net#1648]
Hi! I'm starting on a new project that should take a month or two to finish and I thought I would start using the 2.0 version of elasticsearch-net -- even though it isn't quite released yet.

Q1: Is this a bad idea to use un-released code for development purposes?
Q2: Do I need to build it manually? I tried running build.bat, but ran into some errors.
Q3: Is the 2.0 branch going to be compatible with the 4.0 framework?

Thanks!

**Comment by michaelbudnik** [comment]
Try using Visual Studio 2015 to build it. 2.0 branch uses some c# 6.0 features which older versions of visual studio don't support.

**Comment by cdonnellytx** [comment]
Do you have a rough ETA for the 2.0 release?  Days, weeks, months, ... ?

We were using the 1.x client with Elasticsearch 2.x until we hit the problem that 2.0 changed the response "error" property from a String to an Object, which made us go back to 1.7.3, since we are nearly code complete with our project and will be releasing it soon.

I am also concerned with whether the 2.x client would be interoperable with 1.x servers with this regard, but understand that that might not be possible.

Thanks,
\# Chris

**Comment by gmarz** [comment]
@cdonnellytx we're aiming for 1-2 weeks.  No, unfortunately the 2.x client will not be backwards compatible with 1.x versions of ES.  You would need to use a 1.x version of the client.  You may be able to get away with some things, but it will likely cause more problems than it's worth.

@mtolman What errors were you getting?  We have some failing unit tests (on purpose) which is likely the issue.  For now, you can build it manually within VS2015.

**Comment by mtolman** [comment]
@gmarz Thanks for the reply. Here are the errors I was getting:
- PdbStr is not found on the computer, please install 'Debugging Tools for Windows'
- Tests.QueryDsl.Compound.FunctionScore.FunctionScoreQueryUsageTests.SerializesFluent [FAIL]
- Tests.QueryDsl.Compound.FunctionScore.FunctionScoreQueryUsageTests.SerializesInitializer [FAIL]

I was able to build in VS2015, as you suggested. The older version of the client targeted both .net40 and .net45. Is that not the case with the 2.0 client?

**Comment by russcam** [comment]
@mtolman 
> PdbStr is not found on the computer, please install 'Debugging Tools for Windows'

what OS are you building on? PdbStr is used by SourceLink to link to source code on Github and [by default it looks in the following locations](https://github.com/ctaggart/SourceLink/blob/master/SourceLink/Pdbstr.fs)

> C:\ProgramData\chocolatey\bin\pdbstr.exe
> C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\srcsrv\pdbstr.exe 
> C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\srcsrv\pdbstr.exe 
> C:\Program Files (x86)\Windows Kits\8.1\Debuggers\x64\srcsrv\pdbstr.exe
> C:\Program Files\Microsoft Team Foundation Server 12.0\Tools\pdbstr.exe
> C:\Program Files (x86)\Windows Kits\8.0\Debuggers\x64\srcsrv\pdbstr.exe
> C:\Program Files\Microsoft Team Foundation Server 11.0\Tools\pdbstr.exe
> C:\Program Files\Debugging Tools for Windows (x64)\srcsrv\pdbstr.exe

Probably the easiest way to install pdbstr.exe is with [chocolatey](https://chocolatey.org/) and install the sourcelink package with `choco install sourcelink`.

There are likely to be failing tests in flux on the `2.0` branch - if you get latest, they're all passing, right now :)

**Comment by gmarz** [comment]
@mtolman sorry for the delayed reply.  NEST 2.0 will not support Framework 4.0, which will be EOL in January.  We'll also have a weak story around DNX, but will be jumping on that once we get the alpha release out.
