### ISSUE TITLE
Does branch develop support the newest Elasticsearch 2.1.0 ?

### ISSUE THREAD

**Issue by jasonmon** [elastic/elasticsearch-net#1650]
the branch develop support Elasticsearch 2.1.0? if yes, can we use it in product? and how to build it?
the branche 2.0 is corresponding to Elasticsearch 2.0?

**Comment by russcam** [comment]
The 2.0 branch should work with Elasticsearch 2.1.0 - our priority is getting it to a point to release it, hopefully in the next 1-2 weeks. It's getting there but would say that it's use at your own risk in production right now.

The client can be built by building the solution within Visual Studio, or by running the build script in the root.
