### ISSUE TITLE
Typed API Call?

### ISSUE THREAD

**Issue by aureole82** [elastic/elasticsearch-net#1653]
Hi

I read the documentation http://nest.azurewebsites.net/elasticsearch-net/handling-responses.html and stumbled upon your suggestion:
```csharp
var result = client.Search<MyType>()
```
(By the way the `Search` method needs at least the `body` parameter!!!)

But that will never do the job! Except my `MyType` looks like this:
```csharp
    public class MyType
    {
        public int took { get; set; }
        public MyHits hits { get; set; }
    }

    public class MyHits
    {
        public int total { get; set; }
        public double max_score { get; set; }
        public MyHit[] hits { get; set; }
    }

    public class MyHit
    {
        public string _index { get; set; }
        public string _type { get; set; }
        public string _id { get; set; }
        public double _score { get; set; }
        public dynamic _source { get; set; }
        public Dictionary<string, string[]> highlight { get; set; }
    }
```
Ok, let's assume I use this workaround. The next obstacle is I will never get my concrete Type hidden in `MyHit._source` except with a hack like this:
```csharp
var realResult = JsonConvert.DeserializeObject<MyRealType>(
    JsonConvert.SerializeObject(
        result.Response.hits.hits[0]._source
    )
);
```
But that's ridiculous! So I did some refactoring to allow my POCO `MyRealType` to be passed as a generic argument:
```csharp
    public class MyType<T> where T : new()
    {
        public int took { get; set; }
        public MyHits<T> hits { get; set; }
    }

    public class MyHits<T> where T : new()
    {
        public int total { get; set; }
        public double max_score { get; set; }
        public MyHit<T>[] hits { get; set; }
    }

    public class MyHit<T> where T : new()
    {
        public string _index { get; set; }
        public string _type { get; set; }
        public string _id { get; set; }
        public double _score { get; set; }
        public T _source { get; set; }
        public Dictionary<string, string[]> highlight { get; set; }
    }
```
But calling 
```csharp
var result = client.Search<MyType<MyRealType>>("myindex",  @"{query:{match:{""Title"":""Elasticsearch""}}}");
```
leads to a `System.InvalidCastException`.

So currently there's only one decent way:
```csharp
var result = client.Search<string>("myindex");
var results = JsonConvert.DeserializeObject<MyType<MyRealType>>(result.Response);
```
But sending strings as an HTTP request and handling strings from an HTTP response is too low level even for Elasticsearch.net!!!

**Please provide a decent result type with a generic argument for the peoples' POCOs!**

**Comment by russcam** [comment]
There are two .NET clients for Elasticsearch - Elasticsearch.NET which is a very low level, dependency free, client that has no opinions about how you build and represent your requests and responses, and NEST, a high level client that has the advantage of having mapped all the request and response objects and is probably the first starting point for interacting with Elasticsearch.

Based on the links that you've supplied, you're using the Elasticsearch.NET client but I think what you're really after is the [NEST client](http://nest.azurewebsites.net/nest/search/basics.html). With NEST, all you would need to do is define the type that maps to the document mapping that you have in Elasticsearch, and the serializer used by NEST will take care of deserializing the search response and your types. For example,

```c#
void Main()
{
	var settings = new ConnectionSettings();
	var connection = new InMemoryConnection(settings);
	var client = new ElasticClient(connection: connection);

	var response = client.Search<MyType>(s => s
		.Query(q => q
			.Term(p => p.Property, "value")
		)
	);

	// do something with results, which will be an IEnumerable<MyType>
	var results = response.Documents;
}

public class MyType
{
	public string Property { get; set; }
}
```

**Comment by aureole82** [comment]
Thanks for the code snippet! There wasn't one in the NEST documentation.

But nevertheless: Don't provide `client.Search<MyType>()` anymore. It's simply confusing and won't help anyone who wants get type-safe documents from the Elasticsearch response.

**Comment by gmarz** [comment]
_search doesn't require a body.

```
client.Search<MyType>()
```

will result in a `GET /myType/_search` with no body, which is the equivalent to performing a `match_all` query on `myType`.

**Comment by aureole82** [comment]
https://raw.githubusercontent.com/elastic/elasticsearch-net/master/src/Elasticsearch.Net/ElasticsearchClient.Generated.cs:
```csharp
ElasticsearchResponse<T> Search<T>(object body, Func<SearchRequestParameters, SearchRequestParameters> requestParameters = null)
ElasticsearchResponse<T> Search<T>(string index, object body, Func<SearchRequestParameters, SearchRequestParameters> requestParameters = null)
ElasticsearchResponse<T> Search<T>(string index, string type, object body, Func<SearchRequestParameters, SearchRequestParameters> requestParameters = null)
```

**Comment by russcam** [comment]
@aureole82 You're looking at the wrong client there - take a look at [the search methods in the master branch](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/ElasticClient-Search.cs)

In the current 1.x NEST client, a `match_all` query can be performed with

```c#
client.Search<MyType>(s => s)
``` 

In the client in the [2.0 branch (that we're currently working on)](https://github.com/elastic/elasticsearch-net/blob/2.0/src/Nest/Search/Search/ElasticClient-Search.cs), the Func delegate is nullable as @gmarz mentioned, so it's simply

```c#
client.Search<MyType>()
```
