### ISSUE TITLE
MatchQueryDescriptor<T>.OnField(Expression<Func<T, object>>) describes lowercase property names

### ISSUE THREAD

**Issue by aureole82** [elastic/elasticsearch-net#1654]
Hi

Calling `MatchQueryDescriptor<T>.OnField(Expression<Func<T, object>>)` leads to lowercase field names. And that leads to an empty result set.

1) Using `MatchQueryDescriptor<T>.OnField(Expression<Func<T, object>>)`
```csharp
var result = client.Search<MyBlog>(
    desc => desc
        .Index("myindex")
        .Type("mypoco")
        .Query(q => q.Match(m => m.OnField(poco=>poco.Title).Query("Elasticsearch")))
    );
Console.WriteLine("{0}:", result.RequestInformation.RequestUrl);
var requestString = Encoding.UTF8.GetString(result.RequestInformation.Request);
Console.WriteLine(requestString);
Console.WriteLine("{0} result(s).", result.Documents.Count());
```

Output:
```
http://localhost:9200/myindex/mypoco/_search:
{
  "query": {
    "match": {
      "title": {
        "query": "Elasticsearch"
      }
    }
  }
}
0 result(s).
```
2) Passing the property's name explicitly with `MatchQueryDescriptor<T>.OnField(string)`
```csharp
.Query(q => q.Match(m => m.OnField("Title").Query("Elasticsearch")))
```

Output:
```
http://localhost:9200/myindex/mypoco/_search:
{
  "query": {
    "match": {
      "Title": {
        "query": "Elasticsearch"
      }
    }
  }
}
10 result(s).
```

**Comment by gmarz** [comment]
Property names are camelCased by default.  You can override this behavior by supplying your own property name inferrer:

```csharp
settings.SetDefaultPropertyNameInferrer(p=>p);
```

See the [Inference](http://nest.azurewebsites.net/nest/index-type-inference.html) section of the docs, and also this [SO answer](http://stackoverflow.com/questions/27282865/how-to-disable-camel-casing-elasticsearch-field-names-in-nest/27296871#27296871) for more details:

**Comment by aureole82** [comment]
Yeah, that's it.

Personally, I would do it the other way round (leave it as is; enable camelCased if requested). That would increase interoperability.

**Comment by gmarz** [comment]
Yea, we've discussed this before, but it would be a real PITA for people to upgrade if we switched it on them.  More pain than it's worth.  For justification, camelCasing is somewhat of a JSON convention...which was the motivation by making it the default initially.

**Comment by EmilAlipiev** [comment]
is this settings.SetDefaultPropertyNameInferrer(p=>p); replaced with settings.DefaultFieldNameInferrer(p => p);   ?
