### ISSUE TITLE
PercolateDescriptor Sort is serialized as 'score'

### ISSUE THREAD

**Issue by mikelazell** [elastic/elasticsearch-net#1656]
When serializing the PercolateDescriptor, the sort property was incorrectly being serialized as 'score' and not 'sort'. 

I have submitted a possible fix in https://github.com/elastic/elasticsearch-net/pull/1655

**Comment by russcam** [comment]
Hey @mikelazell, thanks for this! We're focused on getting the 2.0 client out the door so will take a look at this after.

Thanks again for submitting :+1:

**Comment by russcam** [comment]
This has now been fixed as part of PR https://github.com/elastic/elasticsearch-net/pull/1655.

The fix should be in the [latest 1.x package on MyGet](https://www.myget.org/gallery/elasticsearch-net-legacy) and will make its way into a bug fix release of 1.x at some point in the future.
