### ISSUE TITLE
Index concrete types and search them by common base type easily

### ISSUE THREAD

**Issue by aureole82** [elastic/elasticsearch-net#1658]
I know, this is a demanding feature request. Who dares wins ;-)

 Assume the following models...
```csharp
abstract class MediaPoco { public int Id { get; set; } }
class ImagePoco : MediaPoco { ... }
class DocumentPoco : MediaPoco { ... }
```
Now, I'd like to get all images and documents:
```csharp
var settings = new ConnectionSettings(uri, "all_media");
settings.MapDefaultTypeNames(desc => desc
    .Add(typeof (ImagePoco), "image")
    .Add(typeof (DocumentPoco), "document")
    );
var client = new ElasticClient(settings);
var allMedia = client.Search<MediaPoco>(desc => desc.AllTypes());
```
Of course I get a `JsonSerializationException: Could not create an instance of type MediaPoco. Type is an interface or abstract class and cannot be instantiated.`

The obvious approach is providing a `ConcreteTypeSelector` for every search request:
```csharp
var allMedia = client.Search<MediaPoco>(desc => desc
    .AllTypes()
    .ConcreteTypeSelector((o, hit) => hit.Type == "image" ? typeof (ImagePoco) : typeof (DocumentPoco)));
```

My kind request would be:
**Since you know the concrete type mapping from beginning either by `MapDefaultTypeNames(..)` or `ElasticTypeAttribute` could you deserialize with that types and not with the `T` in `client.Search<T>(..)`?**

**Comment by Mpdreamz** [comment]
If you use `.Types(typeof(ImagePoco), typeof(DocumentPoco))` we'll build the concrete type selector for you. Does that work for you?

**Comment by aureole82** [comment]
That's more helpful! Thanks

But finally I'm looking something like that
```csharp
var allMedia = client.Search<MediaPoco>(desc => desc
    .Types(typeof (MediaPoco).Assembly
        .GetTypes()
        .Where(type => type.IsSubclassOf(typeof (MediaPoco)))
        .ToArray())
    );
```
Yeah, that will work. Just in case I would like a `VideoPoco`.

**Comment by Mpdreamz** [comment]
Cool! Just to be clear that behaviour on `Types()` already exist now so closing this issue :+1: 

The covariance section on our search basics docs covers this as well. http://nest.azurewebsites.net/nest/search/basics.html
