### ISSUE TITLE
2.0 Namespace cleanup

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#1661]
Within Client projects (NEST and Elasticsearch.NET), all types should be in the root namespace.

NEST directory structure follows the structure of the Elasticsearch documentation

**Comment by russcam** [comment]
Updated the namespaces for all the types in Elasticsearch.Net and Nest to the root namespace of each assembly, respectively.

@Mpdreamz and @gmarz is there anything currently to check the directory structure in Nest matches the  Elasticsearch documentation? I had a look through the Tests assembly but couldn't see anything.

**Comment by gmarz** [comment]
@russcam No, there isn't.  We could add a code standards test for this, but I think it serves better as a general guideline and not something we should enforce.  Open to other ideas though.

**Comment by russcam** [comment]
@gmarz No worries. We OK to close this issue as done then?

**Comment by gmarz** [comment]
:+1: OK with me
