### ISSUE TITLE
2.0 MovingAverageAggregation* UsageTests pass on one machine but fail on another

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#1662]
I have two machines, one running Windows 7 64Bit, the other, Windows 10 64Bit. When running `build.bat` on the Windows7 machine, all unit tests pass. When running the same commit on the Windows10 machine, the usage tests for moving average pipeline aggregations usage tests fails with:

```
System.InvalidCastException : Object must implement IConvertible
```

Stepping through, it is related to the implicit conversion from a `string` to `SingleBucketsPath` within [`MovingAverageAggregationJsonConverter`](https://github.com/elastic/elasticsearch-net/blob/2.0/src/Nest/Aggregations/Pipeline/MovingAverage/MovingAverageAggregationJsonConverter.cs#L77)

```c#
private T GetOrDefault<T>(string key, Dictionary<string, JToken> properties)
{
	if (!properties.ContainsKey(key)) return default(T);
    // fails on line below
	return (T)Convert.ChangeType(properties[key], typeof(T));
}
```

The Windows 7 machine uses Microsoft (R) Build Engine version 14.0.23107.0
The Windows 10 machine uses Microsoft (R) Build Engine version 14.0.24720.0

**Comment by gmarz** [comment]
Hmm, interesting.  I'm running MSBuild 14.0.24720.0 as well and the tests pass for me.

**Comment by russcam** [comment]
Figured it out. Somehow, a reference to the portable library / dnxcore compatible Newtonsoft.Json assembly had made its way into the solution on the Windows 10 machine - I think I went to update packages using paket and messed it up somehow.

Clearing out the packages directory and running `paket install` has fixed the issue.

**Comment by gmarz** [comment]
Ah, ok cool :+1:
