### ISSUE TITLE
Support for IAggregationVisitor

### ISSUE THREAD

**Issue by jonyadamit** [elastic/elasticsearch-net#1669]
I want to make sure I'm not missing anything here:
We have `IQueryVisitor`. The `IQueryContainer` is built pretty much the same way as `IAggregationContainer`.
Is there any special reason the visitor pattern is implemented for query, but not for aggregation?

If there's nothing I miss here, I plan to write one.
Should I implement it for Nest, or there is no such need?

**Comment by Mpdreamz** [comment]
There is no reason other then its something currently on our wishlist. 

Would absolutely love a PR for one :+1:

**Comment by jonyadamit** [comment]
Here you go #1670 .  Hope this is enough - for me it is.

**Comment by Mpdreamz** [comment]
Awesome! Will review tomorrow
