### ISSUE TITLE
Cannot use SniffingConnectionPool in branch 2.0

### ISSUE THREAD

**Issue by jonyadamit** [elastic/elasticsearch-net#1673]
I added a relevant PR #1657 which I'm not certain is the way to go, but this must be a `blocks 2.0-alpha` bug.

**Comment by Mpdreamz** [comment]
Your absolutely right, I'm not certain your PR is the way to go either just yet hence why its not pulled in already.

**Comment by jonyadamit** [comment]
:+1:  Wanted to make sure it's noticed.
I feel that if the low level client needs to use time units, the `TimeUnitExpression` class belongs there.

**Comment by jonyadamit** [comment]
I also don't know why the setting values changed to `string`, which caused another bug down this path.

**Comment by Mpdreamz** [comment]
It was, but I appreciate the nudge! I used to pat myself on the back for responding to PR's within a day, these past two months that reputation has gone down the drain :smile:

I rather not move `Time` down to the low client, I have some thoughts on how to avoid that but will need to evaluate that first. The jump to string on the settings is what really needs further investigating on my end, how was it introduced and do we need to somehow support both forms now? Not sure (yet).

**Comment by jonyadamit** [comment]
:+1:  Thanks for the explanation. Trust me I can relate to your tight schedule situation :wink:

**Comment by Mpdreamz** [comment]
Closing this, just pushed a slightly different approach to #1657 to make sure timespans's are written as timeunits. 

Thanks again for opening the issue and the PR @jonyadamit
