### ISSUE TITLE
SearchDescriptor.Query(q=>q.Ids()) results in empty JSON object on serialization

### ISSUE THREAD

**Issue by danielweisss** [elastic/elasticsearch-net#1674]
```c#
SearchDescriptor<NestRelease> searchDescriptor = new SearchDescriptor<NestRelease>();
searchDescriptor.Query(q => q.Ids(i => i.Values(id)));
ISearchResponse<NestRelease> searchResponse = this.elasticContext.Search<NestRelease>(searchDescriptor);
```
returns too many documents, because the searchDescriptor is an empty json object after serialization. 

Proofed here:
```c#
FileStream fileStream = new FileStream("D:\\searchDescriptor .json", FileMode.Create);
this.elasticContext.Serializer.Serialize(searchDescriptor, fileStream);
```

I can't get one document by it's id because i use an alias for many indices. Now i do a search via term as a workaround. Any other ideas?
```c#
searchDescriptor.Query(q => q.Term(t => t.Field("_id").Value(id)));
```
best regards

**Comment by russcam** [comment]
Which version of NEST are you using / branch are you building?

I couldn't replicate generating an empty json object with the following

```c#
void Main()
{
	var client = new ElasticClient(connection: new InMemoryConnection());
	var id = new long[] { 1, 2 };

	SearchDescriptor<NestRelease> searchDescriptor = new SearchDescriptor<NestRelease>();
	searchDescriptor.Query(q => q.Ids(i => i.Values(id)));

	var result = client.Search<NestRelease>(searchDescriptor);
	Console.WriteLine(Encoding.UTF8.GetString(result.RequestInformation.Request));
}

public class NestRelease
{
}
```

This generates the following query DSL

```javascript
{
  "query": {
    "ids": {
      "values": [
        "1",
        "2"
      ]
    }
  }
}
```

Is `id` an empty `IEnumerable<long>`? Did you also see [multi-get](https://nest.azurewebsites.net/nest/core/multi-get.html)?

**Comment by danielweisss** [comment]
I'm using branch 2.0 with latest changes. I forgot to say. 

My id is just one value, but i've tried. It makes no difference. 

Multi-get is another workaround. I do it via term instead of Ids. 
searchDescriptor.Query(q => q.Term(t => t.Field("_id").Value(id)))

Is a multi-get the better way?

**Comment by russcam** [comment]
Would you be able to show what `id` is in your first code example please?

**Comment by danielweisss** [comment]
Sure. 

```c#
SearchDescriptor<NestRelease> searchDescriptor = new SearchDescriptor<NestRelease>();
searchDescriptor.Query(q => q.Ids(i => i.Values("e0efccfb8c2d2461eed18529535b9f194723b109")));
ISearchResponse<NestRelease> searchResponse = this.elasticContext.Search<NestRelease>(searchDescriptor);
```

**Comment by gmarz** [comment]
`IsConditionless` was taking into account types, but they are optional. This is fixed with the above commit.  Thanks for reporting @danielweisss!
