### ISSUE TITLE
ElasticSearch.NET is not compatible with UAP

### ISSUE THREAD

**Issue by wbsimms** [elastic/elasticsearch-net#1676]
ES.NET and NEST need compilations which target UWP. I'm creating a UWP app and get the following when using the nuget packages:

Installing Newtonsoft.Json 7.0.1.
Installing NEST 1.7.1.
Installing Elasticsearch.Net 1.7.1.
NEST 1.7.1 is not compatible with UAP,Version=v10.0.
Elasticsearch.Net 1.7.1 is not compatible with UAP,Version=v10.0.
Some packages are not compatible with UAP,Version=v10.0.
NEST 1.7.1 is not compatible with UAP,Version=v10.0 (win10-arm).
Elasticsearch.Net 1.7.1 is not compatible with UAP,Version=v10.0 (win10-arm).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
NEST 1.7.1 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Elasticsearch.Net 1.7.1 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
NEST 1.7.1 is not compatible with UAP,Version=v10.0 (win10-x86).
Elasticsearch.Net 1.7.1 is not compatible with UAP,Version=v10.0 (win10-x86).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
NEST 1.7.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Elasticsearch.Net 1.7.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
NEST 1.7.1 is not compatible with UAP,Version=v10.0 (win10-x64).
Elasticsearch.Net 1.7.1 is not compatible with UAP,Version=v10.0 (win10-x64).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
NEST 1.7.1 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
Elasticsearch.Net 1.7.1 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).
Package restore failed for 'ElasticTransfer.Lib'.
Package restore failed. Rolling back package changes for 'ElasticTransfer.Lib'.

**Comment by Mpdreamz** [comment]
Thanks @wbsimms we'll be releasing 2.0.0 as alpha first. The main reason its an alpha is because we need to tackle multi platform targetting sanely and we do not want to block the alpha on that.

**Comment by russcam** [comment]
It looks like in order to support this, we will also need to target `uap10` in addition to `dotnet5.1` and `net45` according to [documentation on the standard platform](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md).

**Comment by Mpdreamz** [comment]
We now publish a `netstandard 1.3` TFM moniker on nuget which should allow you to use the clients with UAP according to: https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms

@wbsimms please let us know if you still face issues on UAP!
