### ISSUE TITLE
Missing Real Word Error Likelihood action in PhraseSuggester method

### ISSUE THREAD

**Issue by AIsaac08** [elastic/elasticsearch-net#1678]
# API Example

The `phrase` request is defined along side the query part in the json request:

```JSON
curl -s -XPOST 'localhost:9200/_search' -d {
  "suggest" : {
    "text" : "Xor the Got-Jewel",
    "simple_phrase" : {
      "phrase" : {
        "analyzer" : "body",
        "field" : "bigram",
        "size" : 1,
        "real_word_error_likelihood" : 0.95,
        "max_errors" : 0.5,
        "gram_size" : 2,
        "direct_generator" : [ {
          "field" : "body",
          "suggest_mode" : "always",
          "min_word_len" : 1
        } ]
      }
    }
  }
}
```

There's one property that I'm not finding in NEST implementation, `real_word_error_likelihood`.
I saw the property in the `PhraseSuggestDescriptor.cs`, but when coding the request, there's no `RealWordErrorLikelihood` action.

**Comment by russcam** [comment]
You're right, thanks for reporting this! Will fix shortly :smile:
