### ISSUE TITLE
PropertyWalker does not respect JsonProperty attributes on property type

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#1679]
It looks like `PropertyWalker` does not respect `JsonPropertyAttribute` applied to properties of a type to be indexed. For example, `GeoLocation` is a type with `Latitude` and `Longitude` properties that have a `JsonPropertyAttribute`s applied of `lat` and `lon`, respectively.

When creating the mapping, the `PropertyWalker` constructs an `object` type mapping with `latitude` and `longitude` fields. When indexing a `GeoLocation` however, the properties on the json object are `lat` and `lon`, respecting the `JsonProperty` attributes.

**Comment by russcam** [comment]
It looks like `TypeMappingWriter` in master does the same thing; mapping does not respect `JsonPropertyAttribute` to infer the property name but indexing a new document does.

Question is then, should mapping have knowledge of the conventions of the serializer used by NEST (currently Json.Net) or should it remain agnostic, and how to handle this is well documented?

**Comment by gmarz** [comment]
Nice catch.  

IMO, I'd rather not introduce `PropertyWalker` to any Json.Net constructs, but at the same time I can also see how it may be surprising.  With atttribute based mappings though, one can pretty much achieve anything that `JsonProperty` provides.

In the case of `GeoLocation`, we should probably modify `PropertyWalker` to infer it as a `geo_point`.  Similarly we should also map [CompletionField](https://github.com/elastic/elasticsearch-net/blob/2.0/src/Nest/Search/Suggesters/CompletionSuggester/CompletionField.cs) to the `completion` type.

**Comment by russcam** [comment]
Tying `PropertyWalker` to knowledge of the serializer does look like a smell, particularly because you can change the `IElasticsearchSerializer` implementation

> With atttribute based mappings though, one can pretty much achieve anything that JsonProperty provides.

True, definitely feel this should be documented in line with above comment i.e. if you have type with a `JsonPropertyAttribute` and a `PropertyName` property set to something else and are using the default serializer, then you will also need to apply the `ElasticsearchPropertyAttribute` and set the `Name` property to the same value.

:+1: to infer `GeoLocation` and `CompletionField` as `geo_point` and `completion`, respectively.

**Comment by russcam** [comment]
Noticed that we have `GeoLocation` and `GeoCoordinate` [here](https://github.com/elastic/elasticsearch-net/blob/2.0/src/Nest/QueryDsl/Geo/GeoLocation.cs). Looks like we could either drop `GeoCoordinate` and let the `GeoCoordinateJsonConverter` handle `GeoLocation` types

**Comment by Mpdreamz** [comment]
GeoLocation serializes to object and GeoCoordinate to array of doubles, used in the query dsl (the various geoshape queries).

**Comment by russcam** [comment]
That makes sense; `GeoLocation` needs to represent an object with `lat` and `lon` properties when used against the `geo_point` type and queries that take a `lat` and `lon`, and `GeoCoordinate` needs to represent `lat` and `lon` as an array when used in geo shape queries.

**Comment by gmarz** [comment]
This is now fixed via #1692.

PropertyWalker will now pull in JsonProperty, but ElasticPropertyAttribute takes precedence.
