### ISSUE TITLE
Raw queries joined with NEST QueryContainer do not serialize.

### ISSUE THREAD

**Issue by JefStat** [elastic/elasticsearch-net#1680]
Combining multiple queries into a single boolean query but the query generated is empty for the queries that are created from a raw string.

With this method call

```
ConvertQueryToESD("{\"term\":\"fieldname\":\"value\"}"
                  ,null
                  ,a range filter)
    .From(0)
    .Take(50)
    .SortMulti(a sort)
````
````
 internal SearchDescriptor<T> ConvertQueryToESD<T>(string queryString, string filterId, List<QueryContainer> filters) where T : class
    {
        var filterQueryString = GetFilter(filterId);
        if (!string.IsNullOrWhiteSpace(filterQueryString))
        {
            var qd = new QueryDescriptor<T>();
            filters.Add(qd.Raw(filterQueryString));
        }
        if (!string.IsNullOrWhiteSpace(queryString))
        {
            var qd = new QueryDescriptor<T>();
            filters.Add(qd.Raw(queryString));
        }
        var sd = new SearchDescriptor<T>();
        sd.Query(q => q.Bool(b => b.Must(filters.ToArray())));
        return sd;
    }
````
Resulting query is 
````
{
  "from": 0,
  "size": 50,
  "sort": [
    {
      "startTimeLocal": {
        "order": "desc"
      }
    }
  ],
  "query": {
    "bool": {
      "must": [
        {
          "range": {
            "startTimeLocal": {
              "gte": "0001-01-01T00:00:00",
              "lte": "2015-12-22T16:28:22"
            }
          }
        },
        {}
      ]
    }
  }
}
````
The `{}` is where I would expect to see the raw term query. Inspecting the SearchDescriptor before the search is ran shows all the expected fields are populated with the correct values. I have also tested only adding the raw string term query without the range filter and the search descriptor serializes as expected

**Comment by Mpdreamz** [comment]
Thanks for reporting this, the query.raw() is not well tested as a composable piece in 1.x and even in 2.x for now.

**Comment by Mpdreamz** [comment]
I just spend some cycles this works in the upcoming 2.0 release (see https://github.com/elastic/elasticsearch-net/blob/9beac06934cf64cced512aca3ecde5cba1a55219/src/Tests/QueryDsl/NestSpecific/Raw/RawCombineUsageTests.cs). 

The raw query now looks and behaves like any other `IQuery` albeit that's its the only one not supporting deserialization. Because of this I'm not planning to backport this to 1.x. 

`Raw()` should be documented as a last ditch effort that does not combine well though in the 1.x branch though.

**Comment by JefStat** [comment]
Thanks, waiting anxiously for the 2.0 release, guess we will test with a custom nuget pkg.

**Comment by Mpdreamz** [comment]
Closing this because we will phase out the `1.x` documentation and in `2.x` this is no longer a problem.

**Comment by JefStat** [comment]
Not a problem for me we have been running with 2.x about a month combining raw queries with the fluent syntax. Thanks for the 2.x implementation.
