### ISSUE TITLE
Building/running Nest with Elastic 2.x

### ISSUE THREAD

**Issue by SeanFarrow** [elastic/elasticsearch-net#1687]
Hi,

What are the steps to run Elastic.net and Nest with Elastic 2.x.
gWhich branch should I be building from as packages do not seem to exist on MyGet.
Any help appreciated.
Kind regards
Sean.

**Comment by russcam** [comment]
Hey @SeanFarrow, the [2.x client is up on MyGet](https://www.myget.org/feed/elasticsearch-net/package/nuget/Elasticsearch.Net) now. Note that this is currently _pre-alpha_ :smiley:  We're working on getting an alpha out very shortly.

If you want to build from source, you can build the `master` branch using the build script in the root of the repository.
