### ISSUE TITLE
Resolve Newtonsoft requirements in 1.7+

### ISSUE THREAD

**Issue by sallgeud** [elastic/elasticsearch-net#1693]
When upgrading to 1.7.1 from 1.6.0, NEST requires a downgrade of Newtonsoft.Json. This prevents an upgrade to 1.7.1 for us.

**Comment by gmarz** [comment]
I'm assuming you're on Newtonsoft.Json 8.0.1 which was just released?

**Comment by sallgeud** [comment]
Yes. It looks like line 5 of the packet.lock being changed to < 9 would do it. 1.6.0 works well with 8.0.1 in our tests (which are not even remotely a complete test).

**Comment by gmarz** [comment]
We haven't added support for Json.Net 8 just yet (i.e. need to run our test suite against it).  We'll make this a priority for the upcoming 1.7.2 and 2.0.0-alpha releases.  For now you'll have to downgrade, but that won't be for long :).

**Comment by gmarz** [comment]
Closing in favor of https://github.com/elastic/elasticsearch-net/issues/1694.  Thanks for raising this @sallgeud.
