### ISSUE TITLE
Add support for Newtonsoft.Json 8

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch-net#1694]
Released a few days ago https://github.com/JamesNK/Newtonsoft.Json/releases/tag/8.0.1

**Comment by Mpdreamz** [comment]
I propose we release 1.7.2 as is against `json.net 7` then do a `NEST1.8` release next week. It be nice if we figure out a way to support both 7 & 8 sanely in both the `1.x` and `master` branches. 

Vote to bump to 1.8 :+1: /cc @gmarz @russcam

**Comment by Mpdreamz** [comment]
Another option (perhaps the most sane one) is to internalize our JSON.NET dependency. This might have some implications with peoples custom converters though,

**Comment by alinia** [comment]
Please bump to 1.8 :+1:

**Comment by markwalsh-liverpool** [comment]
Latest release is now 8.0.2

https://github.com/JamesNK/Newtonsoft.Json/releases/tag/8.0.2

**Comment by gmarz** [comment]
We now support both versions 7 and 8.

Closed via a7090a81799f1617885b3532fcb7d613eaaa9dde
