### ISSUE TITLE
AutoMap/Infer TimeSpan properties by default

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#1705]
Reference to https://github.com/elastic/elasticsearch-net/issues/1643

I think we should consider handling/inferring `System.TimeSpan` properties by default, storing it as a `double` representing the TotalMilliseconds of the TimeSpan. Storing it as a string makes less sense as  you may want to query on the field and this would be unituitive on a string field.

Doing this would require a custom `JsonConverter` for `TimeSpan`.

What are your thoughts, @Mpdreamz, @gmarz?

**Comment by RobinRieger** [comment]
:+1: 

Manually adding attribute for 'double' here atm, because string mapping doesn't make any sense....
