### ISSUE TITLE
Multifield: MapperParsingException when using dot 

### ISSUE THREAD

**Issue by tomasfalt** [elastic/elasticsearch-net#1707]
When I map a Multifield called Name I get the following error:

 `MapperParsingException[Field name [name.raw] which is a multi field of [name] cannot contain '.']`

I know that field name with dots is not longer allowed in ES 2.0 but I can't see a solution to this then using Multifields.

**Comment by russcam** [comment]
@tomasfalt Can you provide the relevant mapping please? In addition, what version of NEST and Elasticsearch are you using?

**Comment by tomasfalt** [comment]
@russcam I'm using NEST 2.0.0-alpha1 and ES 2.1.1. 

The mapping: 
```c#
var mapping = propertiesDescriptor.String(
                    s1 =>
                        s1.Name(p => p.Name)
                            .Analyzer("standard")
                            .Fields(fs => fs.String(s2 => s2.Name(p2 => p2.Name.Suffix("raw")).Index(FieldIndexOption.NotAnalyzed))))
```

I found this: https://discuss.elastic.co/t/elasticsearch-2-mapping/34366. It sounds like the same problem?

**Comment by tomasfalt** [comment]
Sorry... Wrong button

**Comment by gmarz** [comment]
@tomasfalt yea, that's correct.  You don't need to supply the suffix explicitly anymore, since it's a multi-field, ES will create this for you automatically.

Just try:

```csharp
 .Fields(fs => fs.String(s2 => s2.Name(p2 => p2.Name("raw").Index(FieldIndexOption.NotAnalyzed))))
```

**Comment by gmarz** [comment]
@tomasfalt while my above comment will fix the issue, after some internal discussion we should change `PropertyName` to always resolve to the last token.  I've opened #1708 for this.

**Comment by tomasfalt** [comment]
Ok, great. Thanks!
