### ISSUE TITLE
Callback registered with ConnectionStatusHandler is never invoked

### ISSUE THREAD

**Issue by joelse** [elastic/elasticsearch-net#1712]
ConnectionConfiguration<T>.ConnectionStatusHandler allows you to register a callback that should be invoked on every request. Using 2.0.0-alpha1, however, the registered callback is never invoked. (The equivalent functionality worked fine with 1.7.1.)

The ConnectionStatusHandler method is a nice and simple way to handle logging needs. Is there an alternative method that could/should be used from version 2.0.0?

**Comment by gmarz** [comment]
Thanks for reporting this.  I think this was unintentionally removed during the transport refactoring and should definitely be added back.

I'd also propose that we rename it to something like `OnRequestCompleted()`.

**Comment by russcam** [comment]
++ to the name change

**Comment by joelse** [comment]
Thanks for dealing with the issue so quickly! Any thoughts/guesses as to when the next release (whether another alpha, or a beta) is coming?
