### ISSUE TITLE
Difference in request url when use scroll

### ISSUE THREAD

**Issue by zabykrinich** [elastic/elasticsearch-net#1713]
I have ES 2.1 and builded nest from Master branch (as far as I understand alpha is located there). When I try to make search I see following problem:
Code 
``` var resultScan = m_client.Search<T>(s => s ```
```                                                                     .From(0) ```
```                                                                     .Size(1) ```
```                                                                     .Index(index) ```
```                                                                    .Query(q => q.MatchAll()) ```
```                                                                    .SearchType(Elasticsearch.Net.SearchType.Scan) ```
```                                                                     .Scroll(TimeSpan.FromSeconds(2))); ```

Gives following url : .../_search?search_type=scan&scroll=2s

``` SearchRequest<T> reqScan = new SearchRequest<T>(index) ```
``` { ```
``` From = 0, ```
``` Size = 1, ```
``` Query = new MatchAllQuery(), ```
``` SearchType = Elasticsearch.Net.SearchType.Scan, ```
``` Scroll = TimeSpan.FromSeconds(2) ```
``` }; ```

``` var resultScan = m_client.Search<T>(reqScan); ```

Gives following url : ...//_search?search_type=scan&scroll=00:00:02

In last case I get BadRequest(400) from server. 

May be the problem is fixed on 2.0 branch, but unfortunately I can't make tests there.

**Comment by russcam** [comment]
Thanks for reporting :+1: 

This is a bug - the `Scroll` property should not be a `TimeSpan` but a [`Time`](https://github.com/elastic/elasticsearch-net/blob/82c938893b2ff4ddca03a8e977ad14a16da712ba/src/Nest/CommonOptions/TimeUnit/Time.cs) type
