### ISSUE TITLE
How to delete mapping in NEST 2.0?

### ISSUE THREAD

**Issue by tomasfalt** [elastic/elasticsearch-net#1716]
The DeleteMapping method seems to be removed in NEST 2.0 and I can't figure if there is a new way to do it?

**Comment by Mpdreamz** [comment]
This API has been deleted in Elasticsearch 2.0 because it can introduce subtle bugs:

https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_types_may_no_longer_be_deleted

Therefore we also deleted our mapping for this API in NEST 2.x
