### ISSUE TITLE
How to use ContractJsonConverters in NEST 2.0

### ISSUE THREAD

**Issue by zabykrinich** [elastic/elasticsearch-net#1717]
There was method ``` ConnectionSettings.AddContractJsonConverters ``` in NEST 1.x.
NEST 2.0 has no. I tried to use ``` [ContractJsonConverter(typeof(JsonCreationConverter))] ``` attribute for type, but it seems it is ignored. Could you describe how to use it now please?
Thank you in advance!

**Comment by Mpdreamz** [comment]
Its a little bit more involved in 2.0 see:

https://github.com/elastic/elasticsearch-net/pull/1703

You have to create a subclass of JsonNetSerializer and provide an implementation for 

``csharp
protected override IList<Func<Type, JsonConverter>> ContractConverters => null;
```
Our long term plan (3.0) is to internalize json.net and this is the first step in that direction.

**Comment by zabykrinich** [comment]
Thank you a lot for your help, it seems method is working, but still it is not working how it was in 1.x.
I use ContractConverter to process BaseClass - ChildClass relations: 
I have
``` public class BaseClass ```
``` { ```
``` } ```

``` public class ChildClass1 ```
``` { ```
``` public prop1 ```
``` } ```

``` public class ChildClass2 ```
``` { ```
``` public prop2 ```
``` } ```

I defined 
``` public class MyJsonNetSerializer : JsonNetSerializer ```
```	{ ```
```public MyJsonNetSerializer(IConnectionSettingsValues settings) : base(settings) { } ```


``` private IList<Func<Type, JsonConverter>> m_ContractConverters = ```
```			new List<Func<Type, JsonConverter>>() { t => t.IsAssignableFrom(typeof(BaseClass)) ? new MyJsonConverter() : null };```

``` protected override void ModifyJsonSerializerSettings(JsonSerializerSettings settings) { }```
``` protected override IList<Func<Type, JsonConverter>> ContractConverters ```
``` { ```
``` get ```
``` { ```
``` return m_ContractConverters; ```
``` } ```
``` } ```
``` } ```

I have overrided the ContractConverters with list defined:
```Func<Type, JsonConverter> ```
```  t => t.IsAssignableFrom(typeof(BaseClass)) ? new MyJsonConverter() : null ```

When I define that way,  search returns me elements of BaseClass not the Child, and MyJsonConverter methods are not called. If I define ContractConverter as 
```  t =>  new MyJsonConverter() ``` it starts enter it but for all types. 
Could you say what I do wrong please? 
Thanks in advance!

**Comment by zabykrinich** [comment]
I did some debugging and found that code in src\Nest\CommonAbstractions\SerializationBehavior\ElasticContractResolver.cs

		 protected override JsonContract CreateContract(Type objectType)
		{
			JsonContract contract = base.CreateContract(objectType);

			// this will only be called once and then cached

			if (typeof(IDictionary).IsAssignableFrom(objectType) && !typeof(IIsADictionary).IsAssignableFrom(objectType))
				contract.Converter = new VerbatimDictionaryKeysJsonConverter();
			else if (objectType == typeof(ServerError))
				contract.Converter = new ServerErrorJsonConverter();
			else if (objectType == typeof(DateTime) || objectType == typeof(DateTime?))
				contract.Converter = new IsoDateTimeConverter();
			else if (!objectType.FullName.StartsWith("Nest.", StringComparison.OrdinalIgnoreCase)) return contract;

			else if (ApplyExactContractJsonAttribute(objectType, contract)) return contract;
			else if (ApplyContractJsonAttribute(objectType, contract)) return contract;

			if (this._contractConverters.HasAny())
			{
				foreach (var c in this._contractConverters)
				{
					var converter = c(objectType);
					if (converter == null)
						continue;
					contract.Converter = converter;
					break;
				}
			}
			return contract;
		}

Since my type name does not start from "Nest." it exits from function in case ``` else if (!objectType.FullName.StartsWith("Nest.", StringComparison.OrdinalIgnoreCase)) return contract; ``` . It does not check _contractConverters and uses the default one.

Can it be the bug?
Thank you a lot in advance!
