### ISSUE TITLE
Elasticsearch .NET - Framework 4.0

### ISSUE THREAD

**Issue by Romanx** [elastic/elasticsearch-net#1719]
The current 2.0.0-alpha on nuget seems to have removed the v4.0 build of this although NEST still seems to have this.

Is there a reason it was removed as I'm using nest with [Quartz](https://github.com/quartznet/quartznet) which only has a 4.0 build and we'd like to get ready for 2.0

**Comment by cstlaurent** [comment]
From microsoft announcement: https://support.microsoft.com/en-us/gp/framework_faq/en-us?wa=wsignin1.0, .NET 4.x, 4.5, 4.5.1 are deprecated since January 12, 2016. I don't think the elasticsearch.net team will use their precious time to support it any longer. You should probably ask the Quartz team to create a build for 4.5.2 - 4.6.x or .NET core instead...

**Comment by Romanx** [comment]
I did see that that was the case and all of our other software supports it. I agree with not necessarily supporting it actively but if you can still build against the target without issue then why take away the option, especially as NEST still has a 4.0 option but it can't be used at all without a 4.0 version of Elasticsearch.NET

**Comment by Mpdreamz** [comment]
Hi @Romanx 

We already use features and api's that are a pain to backport to NET4.0. Not impossible but not worth the added complexity. 

I rather put that effort in getting pcl/uap/corefx support out and that for us takes priority over .NET 4.0 which has EOL'ed.

I agree with @cstlaurent, thanks for chiming in btw!, the onus probably lies with Quartz to get .NET 4.5+ builds out there. We have to move forward as a .NET community :smile:

**Comment by Romanx** [comment]
Thanks for the response, I've opened an issue with Quartz to help get them into the future with the rest of us.
