### ISSUE TITLE
Migrated to the alpha 

### ISSUE THREAD

**Issue by carstenmuellercas** [elastic/elasticsearch-net#1724]
Hi,

we created to the aplha verson to validate our project with elastic 2.1.
It 1 minutes till that IndexExists request comes back, is there anything we ar doing wrong?

         var connectionPool = new SniffingConnectionPool(_Configuration._URLs);
            
                var settings = new ConnectionSettings(
                    connectionPool
                );
                settings.DefaultIndex(_elasticIndexName);
                if (_Configuration.Authentication) settings.BasicAuthentication(_Configuration.Username, _Configuration.Password);

                _client = new ElasticClient(settings);
               // settings.PingTimeout(new TimeSpan(0, 0, 0, 1));  // Set ping timeout to 1 second

              
                //Create elastic search index if not existing
                var request = new IndexExistsRequest(_elasticIndexName);
                var indexRespone = _client.IndexExists(request);

**Comment by Mpdreamz** [comment]
Hi @carstenmuellercas is this issue resolved? That call should not take 1 minute unless the cluster is unresponsive.

**Comment by carstenmuellercas** [comment]
Yes, I had gto change the code to that one using the StaticConnectionPool.

                var connectionPool = new SniffingConnectionPool(_Configuration.Nodes());          
       
                var pool = new StaticConnectionPool(_Configuration.Nodes());

                var settings = new ConnectionSettings(pool);


The other code didn't even raise a catchable exeption.
