### ISSUE TITLE
IcuCollation Token Filter

### ISSUE THREAD

**Issue by MimiTator** [elastic/elasticsearch-net#1725]
After installing the analysis icu plugin I tried to add a icu collation token filter in the index settings via NEST. Unfortunately there is no way I see to set custom filter. It is possible to add this class?
Something like this should work:

```
public class IcuCollationTokenFilter : TokenFilterBase
{
    public IcuCollationTokenFilter()
        : base("icu_collation")
    {
    }

    [JsonProperty("language")]
    public string Language { get; set; }

    [JsonProperty("country")]
    public string Country { get; set; }
}
```

**Comment by Mpdreamz** [comment]
[ITokenFilters](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Analysis/TokenFilters/TokenFilters.cs#L9) is basically a dict of string `ITokenFilter` if you are are using the fuent API you can use [UserDefined](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Analysis/TokenFilters/TokenFilters.cs#L26) to set it.

That said in the future we will ship with support for the ICU plugin out of the box
