### ISSUE TITLE
Modifier for custom json Serialization NEST 2.0+

### ISSUE THREAD

**Issue by kneeclass** [elastic/elasticsearch-net#1727]
Hi

I'm currenty developing a EPiServer integration to elasticsearch that uses NEST for querying and indexing items/content.
It's currently build using elasticsearch-1.7.4 and NEST 1.7.1

But of course i want to upgrade it to elasticsearch 2.0+.

I know the current version of NEST that supports 2.0 is only i alpha release but i ask anyway.
In my current version have to do a lot of custom serialization because of how EPiServer works :-1: 

Basicly want i want to do it this:
```csharp
            connectionSettings.SetJsonSerializerSettingsModifier(x => {
                x.Converters = new JsonConverter[] {
                    new IContentJsonConverter(),
                    new ContentReferenceJsonConverter(), 
                    new PropertyDataCollectionJsonConverter(),
                    new LinkItemConverter(),
                    new AccessControlListJsonConverter(),
                    new XHtmlStringConverter(),
                    new ContentMixinJsonConverter()
                };
                x.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
            });
```

I haven't dug to deep in the 2.0 version yet but i couldn't find a way to modify the json without using reflection to modify private fields.

Is there a "official" way to do this kind of modifications or is that coming in the none alpha version ?

**Comment by Mpdreamz** [comment]
Its still possible but it became a little bit more involved see the source of our new docs here:

https://github.com/elastic/elasticsearch-net/blob/master/src/Tests/ClientConcepts/LowLevel/Connecting.doc.cs#L212

The main reason we are alpha is docs and coreclr but both are getting there :)

Are you making this EPiServer integration public?

**Comment by kneeclass** [comment]
Thanks for the answer. That's a much more elegant solution!
The idea is to make it public as soon as possible.

**Comment by Mpdreamz** [comment]
Cool! Ping me when you do would love to help making some noise :smile:
