### ISSUE TITLE
Due date for 2.0.0-alpha2?

### ISSUE THREAD

**Issue by joelse** [elastic/elasticsearch-net#1732]
Apologies in advance if this is an inappropriate forum for this type of question, but is there a targeted due date for 2.0.0-alpha? Checking the milestones, it says february 1st for 2.0.0, but nothing for the next alpha.

**Comment by russcam** [comment]
Hey @joelse, this is totally the right place to ask :smile: 

We are working hard to get a 2.0.0-alpha2 out in the next few days.

**Comment by joelse** [comment]
Sounds great, thanks for the answer.
