### ISSUE TITLE
Search Suggestion

### ISSUE THREAD

**Issue by sindhusingh** [elastic/elasticsearch-net#1733]
We are facing below problems, please guide us for it.

Question 1.
While doing search "DI METHYL SULFIDE" Don't work while "DIMETHYL SULFIDE" works because in our indexes we don't have such word like "DI METHYL SULFIDE"

Question 2.
We need "Auto Suggestion with Spell correcter" for "Product Description" field. What should we do, Also do we need to change our mappings to work it correctly?

We are searching on "productDesciption" field. Please have a look in attached links having mappings and sample data.

According to documentation Phrase Suggesters is what we are looking for but unable to use it, may be mapping having issue. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-phrase.html

Can you provide sample code for both my problems and correct mappings if required.

[SampleData.txt](https://github.com/elastic/elasticsearch-net/files/94447/SampleData.txt)

[Mappings.txt](https://github.com/elastic/elasticsearch-net/files/94425/Mappings.txt)

**Comment by gmarz** [comment]
@sindhusingh questions like this are better suited for [Discourse](https://discuss.elastic.co/c/elasticsearch) or [StackOverflow](http://stackoverflow.com/questions/tagged/nest).  We try to keep GitHub issues for bug reporting and feature requests.

That said, for question 1 - there are multiple ways of solving this.  I would suggest reading the [Mapping and Analysis](https://www.elastic.co/guide/en/elasticsearch/guide/current/mapping-analysis.html) section of the [Definitive Guide](https://www.elastic.co/guide/en/elasticsearch/guide/current/index.html) as a starting point.

Question 2 - you'd have to elaborate more on why it's not working for you.  But again, asking on Discourse or StackOverflow will yield better results.

Hope that helps!
