### ISSUE TITLE
Build Instructions for DnxCore branches

### ISSUE THREAD

**Issue by grantgoodart** [elastic/elasticsearch-net#1739]
Could you please provide build instructions for the DnxCore branches?  I pulled them down and was unable to F5 build or use the batch file to build the project. 

We are wanting to evaluate how far that project is progressing. We have a dependency on NEST and need to be able to run on .NET Core. Any instructions would be greatly appreciated.

**Comment by grantgoodart** [comment]
We were able to get this to work.

**Comment by russcam** [comment]
Glad you were able to get this to work @grantgoodart :+1:  

FYI, [the dnx branch has been merged into master](https://github.com/elastic/elasticsearch-net/commit/8632fc197c01e5f8a7b89a0e9b2cc357e9163903) and the `build.bat` file in the root of the repo uses DNX tooling for _nearly_ all targets

**Comment by grantgoodart** [comment]
Is it on the nuget or myget feed yet @russcam?

**Comment by russcam** [comment]
[The latest packages on the MyGet feed have CI builds that target](https://www.myget.org/feed/elasticsearch-net/package/nuget/Nest)

- .NETFramework,Version=v4.6
- .NETFramework,Version=v4.5
- .NETPlatform,Version=v5.1

We're working on a getting core clr support in a nuget release :smile:

**Comment by shakdoesgithub** [comment]
Hi @russcam are there any updates to getting this into a nuget release?

**Comment by russcam** [comment]
@shakdoesgithub, there's a Core CLR version of NEST and Elasticsearch.NET on nuget since version [2.0.0-rc1](https://www.nuget.org/packages/NEST/2.0.0-rc1) and it's in all 2.x releases since. It's targeting `dotnet5.1`
