### ISSUE TITLE
Multiple AggregationContainers in top level aggregations (NEST 2.0.0)

### ISSUE THREAD

**Issue by andersosthus** [elastic/elasticsearch-net#1740]
Hi,

I'm having a bit of a struggle understanding the Aggregation fluent API and combining aggregations.

What I want to achieve is this:
```
"aggs": {
  "termAgg": {
    "terms": {
      "field": "termField",
      "include": [
        "term1"
      ]
    }
  },
  "avgAgg": {
    "avg": {
      "field": "anotherField"
    }
  }
}
```

What I have (simplified case):
```
var descriptor = new SearchDescriptor<T>();

var aggregationFuncs = new List<Func<AggregationContainerDescriptor<T>, IAggregationContainer>>
{
    a => a.Terms("termAgg", t => t.Field("termField").Include(new [] {"term1"})),
    a => a.Average("avgAgg", avg => avg.Field("anotherField"))
};

descriptor.Aggregations(aggDescriptor =>
{
    aggregationFuncs.ForEach(agg => agg(aggDescriptor));
    return aggDescriptor;
});
```

My question is about the last part, the ```descriptor.Aggregations(...```.
Right now, we iterate over each of the functions, evaluating them with the descriptor, but this seems like a weird thing to do.

A lot of the Query DSL has a signature like ```params Func<TIn, TOut>[]```, and those are a joy to work with because we can just pass in an array of funcs and it's all good :)
So, is there a reason that Aggregations doesn't have this signature/API?
Is there a "better" way of passing in multiple aggregation functions when using the Fluent API?

Our usecase is generating aggregations based on different user input, so we generate inside-out for each of the top-level aggregations and then combine them in the end.

Btw, great job on NEST 2.0.0 so far. Things feels more aligned :)

**Comment by Mpdreamz** [comment]
> Btw, great job on NEST 2.0.0 so far. Things feels more aligned :)

Thanks! part of this alignment is that the only fluent methods taking params of Func's are ones that map to an array in elasticsearch e.g the Must clause on the BoolQuery.

The aggregations map to a dictionary and there for have a dedicated AggregationContainerDescriptor. I'm a bit on the fence on adding params Func as sugar back here since it can be achieved with an extension method reasonably easy.

 

```csharp
public static SearchDescriptor<T> Aggregations<T>(
	this SearchDescriptor<T> d,
	params Func<AggregationContainerDescriptor<T>, IAggregationContainer>[] aggs) 
	where T : class =>
	d.Aggregations(a =>
	{
		foreach (var agg in aggs)agg(a);
		return a;
	});

```

Trying to cut down convenience overloads in the client and add them back in as needed.

@gmarz @russcam thoughts?

**Comment by gmarz** [comment]
I agree, we should keep sugar like this out of the descriptors.  Otherwise things get unwieldy fast, and we end up in a state like our 1.x branch where there is a lot of inconsistency across methods.

That said, I'm +1 for adding it as an extension method.

**Comment by russcam** [comment]
It sounds like it might be a common use case so an extension method looks like a good fit :+1:

**Comment by andersosthus** [comment]
I agree with not adding it in as sugar directly, if that aligns with the standards/policies you've set :)

If it's added as a extension or not, I'm fine with either or, since they're pretty easy to make, but for use cases like this it might be good to have them by default.

I might have formulated it a bit badly, but my main question was really if the whole:
```
d.Aggregations(a =>
    {
        foreach (var agg in aggs)agg(a);
        return a;
    });
```
 is a) a valid way of doing it, b) should I be doing it in some other way, and c) it should probably be added to the docs as an advanced example of some kind ?

**Comment by russcam** [comment]
will add a piece of documentation for this
