### ISSUE TITLE
Sniffing Connection Pool does not work

### ISSUE THREAD

**Issue by rabx88** [elastic/elasticsearch-net#1743]
The following results in an Aggregate exception after a minute.
`var pool = new SniffingConnectionPool(new[] {new Uri("http://localhost:9200")});`
`mClient = new ElasticsearchClient(new ConnectionConfiguration(pool));`
`mClient.IndicesExists("foo");`

**Comment by russcam** [comment]
What version of Elasticsearch are you running? And what version of NEST/Elasticsearch.Net?

**Comment by rabx88** [comment]
Sorry for the terse submission. Elasticsearch 2.1.1. I tried both alpha releases of Elasticsearch.Net for 2.x and both have the same issue. I currently am stuck using 1.7.1 with essentially my own client to handle the changes to error parsing and request formatting.

**Comment by russcam** [comment]
Hmmm, I'm not seeing any issues; running against Elasticsearch 2.1.1 on local machine with 2.0.0-alpha2 release from nuget

```c#
void Main()
{
	var pool = new SniffingConnectionPool(new[] { new Uri("http://localhost:9200") });
	var lowLevelClient = new ElasticsearchClient(new ConnectionConfiguration(pool));
	var lowLevelResponse = lowLevelClient.IndicesExists<dynamic>("foo");
	
	Console.WriteLine("success:{0}, status code:{1}", lowLevelResponse.Success, lowLevelResponse.HttpStatusCode);

	var highLevelclient = new ElasticClient(new ConnectionSettings(pool));
	var highLevelResponse = highLevelclient.IndexExists("foo");	
	Console.WriteLine("valid:{0}, exists:{1}", highLevelResponse.IsValid, highLevelResponse.Exists);
}
```

I get

```
success:True, status code:404
valid:True, exists:False
```

The benchmarking project in master uses the SniffingConnectionPool too.

Sounds like the issue could be elsewhere in your code?

**Comment by rabx88** [comment]
```
using System;
using System.IO;
using Elasticsearch.Net;

namespace ConsoleApplication4
{
    class Program
    {
        static void Main(string[] args)
        {
            var pool = new SniffingConnectionPool(new[] {new Uri("http://localhost:9200")});
            var client = new ElasticsearchClient(new ConnectionConfiguration(pool));
            var resp = client.IndicesExists<Stream>("foo");
            Console.WriteLine(resp.HttpStatusCode);
            if (resp.OriginalException != null)
            {
                Console.WriteLine(resp.OriginalException);
            }
        }
    }
 }
```
Elasticsearch.Net.ElasticsearchClientException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> Elasticsearch.Net.PipelineException: Failed sniffing cluster state. ---> System.AggregateException: One or more errors occurred. ---> Elasticsearch.Net.PipelineException: An error occurred trying to establish a connection with the specified node.
   at Elasticsearch.Net.RequestPipeline.Sniff() in C:\Users\russ\source\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 322
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.RequestPipeline.Sniff() in C:\Users\russ\source\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 337
   at Elasticsearch.Net.RequestPipeline.SniffOnConnectionFailure() in C:\Users\russ\source\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 297
   at Elasticsearch.Net.Transport`1.Ping(IRequestPipeline pipeline, Node node, List`1 seenExceptions) in C:\Users\russ\source\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 178
   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\Users\russ\source\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 67
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---

**Comment by russcam** [comment]
> Elasticsearch.Net.PipelineException: An error occurred trying to establish a connection with the specified node.

This looks like it could be the issue - are you sure that you're running Elasticsearch locally on port 9200 and can connect to it? Can check this easily by opening a browser and navigating to `http://localhost:9200`.

I can replicate the exception with the same stack trace _but only_ after I have stopped Elasticsearch from running; a `PipelineException`  is expected here, with a reason of `SniffFailure` and message "Failed sniffing cluster state.". The exception is thrown after 2 seconds.

**Comment by rabx88** [comment]
Yes it is running, I can connect to the same cluster using the same code with the latest stable version of Elasticsearch.Net. Perhaps it is a race condition of some kind, I have not dug into your code. I can tell you that the sample above takes about a minute to throw the exception provided and does not vary.

**Comment by Mpdreamz** [comment]
Is there anything in the inner exception that could tip us off?

The `ElasticsearchClientException` also has Request/Response/AuditTrail properties what do they say? they might be able to clue us in whats going on.

**Comment by rabx88** [comment]
It appears to be assuming that the node is reachable by IP, which may not be the case:

![image](https://cloud.githubusercontent.com/assets/12072726/12491419/cce1cf0a-c02f-11e5-8769-0b66b0837b1b.png)

For reference my settings:
```
threadpool.search.queue_size: 30000
threadpool.bulk.queue_size: 300
cluster.name: rab
node.name: RAB-WIN10
bootstrap.mlockall: true
action.auto_create_index: false
network.host: 0.0.0.0
```

**Comment by Mpdreamz** [comment]
aye so is that IP is not reachable? 0.0.0.0 binds it to all IP addresses you might have to be more explicit see also: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html for all the different options here.

what does `GET http://localhost:9200/_nodes/_all/settings?flat_settings` return?

**Comment by rabx88** [comment]
{"cluster_name":"rab","nodes":{"1c-rrTdvSFWjuknN8uft8g":{"name":"RAB-WIN10","transport_address":"10.60.130.39:9300","host":"10.60.130.39","ip":"10.60.130.39","version":"2.1.1","build":"40e2c53","http_address":"10.60.130.39:9200","settings":{"action.auto_create_index":"false","bootstrap.mlockall":"true","client.type":"node","cluster.name":"rab","config.ignore_system_properties":"true","name":"RAB-WIN10","network.host":"0.0.0.0","node.name":"RAB-WIN10","path.conf":"C:\\Elasticsearch\\config","path.data":"C:\\Elasticsearch\\data","path.home":"C:\\Elasticsearch\\","path.logs":"C:/Elasticsearch/logs","threadpool.bulk.queue_size":"300","threadpool.search.queue_size":"30000"}}}}

**Comment by Mpdreamz** [comment]
right so if `10.60.130.39` is not accessible `0.0.0.0` is not the right setting to use for `network.host` changing that to `_local_` should do the trick.

**Comment by rabx88** [comment]
So why does the old version of the code work? I guess I fail to see why the setting is invalid. That IP certainly responds to ping but it seems elasticsearch is not bound there. The documentation in this area seems incomplete.

**Comment by gmarz** [comment]
@rabx88 this was a change made in ES 2.0: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_network_changes.html

**Comment by Mpdreamz** [comment]
The defaults have changed in `NEST 1.x` you had to explicitly enable `SniffOnStartup/ConnectionFailure/LifeSpan` as well as pass a `SniffingConnectionPool`. So in `NEST 1.x` its not actually doing a sniff on start using the code you pasted. 

In `NEST 2.x` the defaults are `true` for all and passing a `SniffingConnectionPool` is enough to optin.

On top of that if you are running the `NEST 1.x` against an `Elasticsearch 2.0` server the output of the sniff call changed in Elasticsearch slightly but completely incompatible with how `NEST 1.x` deals with the response. So a sniff from `NEST 1.x` can never succeed on a `Elasticsearch 2.x` node.

Hope this clarifies whats going on :)

**Comment by rabx88** [comment]
Ok so what benefit is the sniffing pool if it doesn't handle this scenario? I just tried the StaticConnectionPool and it works fine. Does it have the same failure detection/load balancing semantics?

**Comment by Mpdreamz** [comment]
Yes it does! The difference is that you can use the sniffing connection pool to seed using a limited ammount of nodes (e.g only the master eligable nodes in a 10+ cluster) and it can find the rest of the nodes on startup. It can also find out about more node failures ahead of time e.g when 10 nodes drop of a 100 node cluster. 

>  That IP certainly responds to ping but it seems elasticsearch is not bound there.

Something does not feel right there though, even manually http://10.60.130.39:9200 is not available? If you explicitly set `_local_` or `_non_loopback_` on network.host do you have better luck?

**Comment by rabx88** [comment]
When set to _local_
- http://10.60.130.39:9200/ fails
- http://rab-win10:9200/ fails
- http://localhost:9200/ succeeds

When set to _non_loopback_
- http://10.60.130.39:9200/ fails
- http://rab-win10:9200/ succeeds
- http://localhost:9200/ fails

When set to 0.0.0.0
- http://10.60.130.39:9200/ fails
- http://rab-win10:9200/ succeeds
- http://localhost:9200/ succeeds

**Comment by Mpdreamz** [comment]
Out of interest: what does `/_nodes/_all/settings?flat_settings` return in each setting on an endpoint that succeeds?

**Comment by rabx88** [comment]
When the setting is 0.0.0.0 there is no difference in the output (I checked with a tool): {"cluster_name":"rab","nodes":{"BPfhKb5nTviGWShHHfZbHA":{"name":"RAB-WIN10","transport_address":"[2001:0:9d38:6abd:3812:680:9ebe:9105]:9300","host":"2001:0:9d38:6abd:3812:680:9ebe:9105","ip":"2001:0:9d38:6abd:3812:680:9ebe:9105","version":"2.1.1","build":"40e2c53","http_address":"[2001:0:9d38:6abd:3812:680:9ebe:9105]:9200","settings":{"action.auto_create_index":"false","bootstrap.mlockall":"true","client.type":"node","cluster.name":"rab","config.ignore_system_properties":"true","name":"RAB-WIN10","network.host":"0.0.0.0","node.name":"RAB-WIN10","path.conf":"C:\\Elasticsearch\\config","path.data":"C:\\Elasticsearch\\data","path.home":"C:\\Elasticsearch\\","path.logs":"C:/Elasticsearch/logs","threadpool.bulk.queue_size":"300","threadpool.search.queue_size":"30000"}}}}
