### ISSUE TITLE
Nest - TokenCountProperty missing Analyzer

### ISSUE THREAD

**Issue by attilalaszlo** [elastic/elasticsearch-net#1744]
In the ITokenCountProperty interface, the JsonProperty is missing from the Analyzer property.

before:
<code>
public interface ITokenCountProperty : INumberProperty{
        string Analyzer { get; set; }
	}
</code>

fix:
<code>
public interface ITokenCountProperty : INumberProperty
	{
        [JsonProperty("analyzer")]
        string Analyzer { get; set; }
	}
</code>

**Comment by russcam** [comment]
Thanks for reporting @attilalaszlo, :+1: !
