### ISSUE TITLE
Index Level templates missing in NEST 1.x

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#1746]
It seems that index-level templates i.e. [default mappings](https://www.elastic.co/guide/en/elasticsearch/guide/1.x/default-mapping.html) are missing in NEST 1.x. 

There is only  `ElasticClient.Map<T>()`  and `CreateIndexDescriptor.AddMapping<T>()` methods, but no non-generic version.

This can currently be worked around by taking advantage of `Type` to type name inferrence

```c#
public class _default_ { }

void Main()
{
    var settings = new ConnectionSettings();
	var connection = new InMemoryConnection(settings);
	var client = new ElasticClient(connection : connection);

	var mr = client.Map<_default_>(map => map
		.DynamicTemplates(dt => dt
			.Add(t => t
				.Name("idx_reference")
				.Match("@ref:*")
				.Mapping(m => m
					.String(f => f
						.Index(FieldIndexOption.NotAnalyzed)
					)
				)
			)
		)
	);

	Console.WriteLine(Encoding.UTF8.GetString(mr.RequestInformation.Request));
}
```

which yields

```javascript
{
  "_default_": {
    "dynamic_templates": [
      {
        "idx_reference": {
          "match": "@ref:*",
          "mapping": {
            "index": "not_analyzed",
            "type": "string"
          }
        }
      }
    ]
  }
}
```

but I think it would be clearer to have a _less hacky_ way to add default mappings

**Comment by Mpdreamz** [comment]
Closing this because another way would be to use `.Map<object>(m=>m.Type("_default_"));`
