### ISSUE TITLE
Indexed document as string try as object

### ISSUE THREAD

**Issue by AColmant** [elastic/elasticsearch-net#1747]
Hello,

I try to push some json data as in this exemple :
```C#
string data = "{ \"source\":\"my_source\", \"country\":\"my_country\", \"company\":\"my_company\" }";

_client.Index(data, s => s
    .Index("my_index")
    .Type("my_type")
    .Id(Guid.NewGuid().ToString()));
}
```
Currently (with the master branch 2.0), this does not work for me.
When running, I could notice that the constructor `Elasticsearch.Net.PostData(T item)` is called instead of (in my humble opinion) `Elasticsearch.Net.PostData(string item)`. So the execution try to serialize a `string`...

I found a unit test only related with a document as `object` but not with `byte[]`, **`string`**, `IEnumerable<string> item`, `IEnumerable<object> item` to confirm this.

NB : Without `s.id()` the request sent is not `POST` (and is therefore considered as false by ElasticSearch) but perhaps this is result of the unexpected execution described above.

**Comment by Mpdreamz** [comment]
Are you on the latest alpha2 the Id bug should have been fixed as per: https://github.com/elastic/elasticsearch-net/issues/1736

I suspect _client is a `NestClient` which does not support posting `strings` directly. You need to use the LowLevel client which you can get to using `.Raw`

```
_client.Raw.Index<IndexResponse>("index", "type", "{}");
```

**Comment by AColmant** [comment]
Oh! Yes, I tried `Id` in `alpha1` and I haven't try again in `alpha2`. My mistake, thank you.

Ok, I just test your advice, they seem to work. I'm just sorry for not having found documentation related to this. But it's really good job, thank you guys for all.

**Comment by Mpdreamz** [comment]
No worries thanks for taking the alpha for a spin, feel free to open more tickets! :+1:
