### ISSUE TITLE
Filter an aggregation with an empty QueryContainer array result in null

### ISSUE THREAD

**Issue by tomasfalt** [elastic/elasticsearch-net#1749]
In NEST 1.7.1 it was possible to do this:
``` c#
 var aggDescriptor = new AggregationDescriptor<Person>().Filter("filter", f1 => f1.Filter(f2 => f2.And(new FilterContainer[0])));
```
And it returned this
``` json
{
  "aggs": {
    "filter": {
      "filter": {}
    }
  }
}
```
But then I try to do the same in NEST 2.0 like this
``` c#
 var aggDescriptor = new AggregationContainerDescriptor<Person>().Filter("filter", f1 => f1.Filter(f2 => f2.Bool(b1 => b1.Filter(new QueryContainer[0]))));
```
or with the obsolete method
``` c#
var aggDescriptor = new AggregationContainerDescriptor<Person>().Filter("filter", f1 => f1.Filter(f2 => f2.And(a => a.Filters(new QueryContainer[0]))));
```
I get null
``` json
{
  "aggs": {
    "filter": {
      "filter": null
    }
  }
}
```

Is there another way to do a Filter with an empty QueryContainer array?

**Comment by russcam** [comment]
Hey @tomasfalt, you can achieve similar output in NEST 2.x with

```c#
var r = client.Search<Person>(s => s
	.Aggregations(a => a
		.Filter("filter", f1 => f1
			.Filter(f2 => f2
				.Raw("{}")
			)
		)
	)
);
```

which yields the same output as desired

```javascript
{
  "aggs": {
    "filter": {
      "filter": {}
    }
  }
}
```

I suspect however your real usage includes the `bool` filter, in which case the following will also work

```c#
var r = client.Search<Person>(s => s
	.Aggregations(a => a
		.Filter("filter", f1 => f1
			.Filter(f2 => f2
				.Bool(b1 => b1
					.Filter(new RawQuery("{}"))
				)
			)
		)
	)
);
```

which yields

```javascript
{
  "aggs": {
    "filter": {
      "filter": {
        "bool": {
          "filter": [
            {}
          ]
        }
      }
    }
  }
}
```

Note that the `bool` filter is a collection of filters. 

Let me know if that helps :smile:

**Comment by tomasfalt** [comment]
Thank you for the response. The thing is that I create an array of filters from a set of query parameters and if none of the query parameters is chosen the array is empty.

I can solve this by adding an array with a MatchAll-filter if the array is empty (the solution I use now) or your suggestion with the Raw query.

I added this issue mostly because it worked differently before (i.e. better for me...) but it can be closed if you feel it's a minor issue or if it actually should behave like this.

**Comment by russcam** [comment]
I dug into this further as this behaviour was not desirable and just pushed a change that would yield

```javascript
{
  "aggs": {
    "filter": {
      "filter": {}
    }
  }
}
```
for an empty `QueryContainer`. 

Thanks again for reporting :+1: !
