### ISSUE TITLE
ConnectionSettings throws TypeLoadException

### ISSUE THREAD

**Issue by tomasfalt** [elastic/elasticsearch-net#1750]
When I upgrade from 2.0.0-alpha1 to 2.0.0-alpha2 I get ```TypeLoadException``` in ```ConnectionSettings``` with the exception message: ```"Method 'Dispose' in type 'Nest.ConnectionSettings' from assembly 'Nest, Version=2.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d' does not have an implementation." ```

Has it something to do with this: https://github.com/elastic/elasticsearch-net/pull/1720?

**Comment by Mpdreamz** [comment]
Can you do a clean and rebuild? also make sure all the projects reference alpha-2 so you do not end up with alpha1 in bin somehow?

**Comment by tomasfalt** [comment]
Sorry, yes it was something left from the previous version in one of the project. Thank you for the swift response.
