### ISSUE TITLE
Interface level attributes ignored

### ISSUE THREAD

**Issue by RobinRieger** [elastic/elasticsearch-net#1753]
Interface level attributes seem to be ignored.

```
public interface IDocumentStructure
    {
        [String(Index = FieldIndexOption.NotAnalyzed)]
        string SomeField { get; set; }
    }

public class Foo: IDocumentStructure
    {
        string SomeField { get; set; }
    }
```

But when I put the mapping it only puts:

```
"someField ": {
    "type": "string",
},
```

Is there a way to use the interface level attributes?

**Comment by russcam** [comment]
Hey @RobinRieger, What version of NEST are you using? Also can you show how you are mapping `Foo` with the client please?

**Comment by RobinRieger** [comment]
Currently using the latest, so 2.0.0 aplha-2

This is the code I am using to insert/create the mapping:
```
var createMapping = ElasticClient.Map<Foo>
                    (m => m.Index(Indices.Index("testindex"))
                           .DateDetection(false)
                           .Dynamic(false)
                           .AutoMap());
```

**Comment by russcam** [comment]
You need to re-declare the attributes applied to the interface type to any type that implements that interface - this is a CLR rule and [has come up frequently in ASP.NET MVC where attributes are frequently used for validation](http://bradwilson.typepad.com/blog/2011/08/interface-attributes-class-attributes.html).

If you only want to use the interface attributes for mapping, the following would work

```c#
// use the interface type for the generic type parameter passed to Map<T>()
// but infer the type name from typeof(Foo)
var createMapping = client.Map<IDocumentStructure>(m => m
	.Type(typeof(Foo))
	.Index("testindex")
	.DateDetection(false)
	.Dynamic(false)
	.AutoMap());
```

**Comment by RobinRieger** [comment]
Yeah, you're totally right. My bad. Was confusing the base class and interfaces. As soon as I saw the link with the `required` attribute example I realized the problem with this thinking. 

Given that I used the same interface but for all classes I store in ES, and not wanting to repeat the same attributes everywhere, I am will just change the mapping call to:

```
var createMapping = ElasticClient.Map<Foo>
                    (m => m.Index(Indices.Index("testindex"))
                           .DateDetection(false)
                           .Dynamic(false)
                           .AutoMap()
                           .Properties
                              (ps => ps.String
                                         (s => s.Name(c => c.SomeField )
                                                .Index(FieldIndexOption.NotAnalyzed))));
```

which allows me to map the rest of the properties in 'Foo' with attributes, but allow me to set the interface properties in one single place (without having to waste time changing the interface to base class etc etc)

Thanks for your help.

**Comment by russcam** [comment]
No worries :+1:

**Comment by RobinRieger** [comment]
Sorry to be a pain but I have an issue with the date format of one of the properties. 

If I have the following model ( Note: think of this as a generic class or 'object' -- mapped as an 'object')

````
public class GenericDateModel
    {
        [Date(Format = "yyyy-MM-dd'T'HH:mm:ss")]
        public DateTime PointInTime {get; set;}
    }
````

and interface

````
public interface ITest {
    GenericDateModel InsertedTime { get; set; }
}
````

and then use these in my 'main' model

````
public class Foo : ITest 
{
    public GenericDateModel InsertedTime { get; set; }

    public GenericDateModel AnotherPropertySpecificToThisClass { get; set; }
}

````

When I call the 'index' method for nest to index the `Foo` class, the `DateTime` for the `AnotherPropertySpecificToThisClass` proeprty gets passed by nest in the correct format to ES, however, the `InsertedTime` (the interface property) is in the wrong format (it sends the milliseconds which ES then rejects saying the value provided is wrong as it does not match the mapping -- the mapping being as in `GenericDateModel` above. ). 

Whilst I can easily re-apply the attributes to a e.g. `string` as you suggested above, how am I meant to reapply the attribute to an 'object' which has its own properties?

**Note**
I found [this](https://github.com/elastic/elasticsearch-net/issues/1550) whilst trying to work around the problem. -- It does not mention it but I think this was using the old 1.x version  :confused: .....

If I change the `GenericDateModel` to 

````
private string _originalValue;

public DateTime PointInTime
        {
            get
            {
                return DateTime.ParseExact(_originalValue, "yyyy-MM-dd'T'HH:mm:ss", CultureInfo.InvariantCulture);
            }
            set
            {
                _originalValue = value.ToString("yyyy-MM-dd'T'HH:mm:ss");
            }
        }
````

then it sends both values correctly to ES in the correct format. 

I guess I am trying to figure out if this is a mistake on my part regarding re applying attributes to interface objects or whether there is something odd in the serialize process with Nest.
