### ISSUE TITLE
JsonIgnore to ignore field

### ISSUE THREAD

**Issue by RobinRieger** [elastic/elasticsearch-net#1754]
During the mapping process, the `AutoMap` will use the `JsonProperty` to get the name of the property, but it will not follow a `JsonIgnore` attribute to ignore the field from the mapping. Currently I am just putting `[Object(Ignore = true)]` everywhere that I have a `JsonIgnore` attribute. 

E.g. (just a random example)
````
public string CultureInfoID { get; set; }

[JsonIgnore]
[Object(Ignore = true)]
public CultureInfo CultureInfo
{
        get
        {
                return new CultureInfo(CultureInfoID, false);
        }
}
````

I am not sure if this is correct. Should it not follow the `JsonIgnore` attribute and not map the field? Kind of feels inconsistent, or is this the expected behavior?

**Comment by russcam** [comment]
Thanks for reporting @RobinRieger :+1:  I thought that we had this covered off but will look into. I take it this is NEST 2.x?

**Comment by RobinRieger** [comment]
Yep the alpha 2 on nuget.

**Comment by russcam** [comment]
There are a couple of ways for ignoring properties

- Using the `Ignore` property on a derived `ElasticsearchPropertyAttribute` type applied to the property that should be ignored on the POCO
- Using the `.InferMappingFor<TDocument>(Func<ClrTypeMappingDescriptor<TDocument>, IClrTypeMapping<TDocument>> selector)` on the connection settings

```c#
[ElasticsearchType(Name = "company")]
public class CompanyWithAttributesAndPropertiesToIgnore
{
	public string Name { get; set; }

    // one way
	[String(Ignore = true)]
	public string PropertyToIgnore { get; set; }

	public string AnotherPropertyToIgnore { get; set; }
}

var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));	
var connectionSettings = new ConnectionSettings(pool)
    .InferMappingFor<CompanyWithAttributesAndPropertiesToIgnore>(i => i
        // another way
        .Ignore(p => p.AnotherPropertyToIgnore)
    );
```

**Comment by RobinRieger** [comment]
Yeah, I saw the `ElasticsearchPropertyAttribute` and tried to apply it directly to, as in the example above the `CultureInfo`, but the attribute itself is `protected`, so I ended up just using the `object` attribute. Seemed to fit most closely, i.e. it's not a `string`.... I can confirm that it does actually ignore the property then in the mapping, i.e. this does 'work'.

Have not tried the second way, so can't comment on that.

**Comment by Mpdreamz** [comment]
We adhere to `[JsonProperty(Name=)` when doing calling `AutoMap()` by virtue of `PropertyName` supporting it. I think the principle of least surprise here is that we also ignore properties marked with `JsonIgnore` when calling `AutoMap()` as at index time they will never be indexed anyway.

Will push a fix shortly

**Comment by rwb196884** [comment]
`[JsonIgnore]` is still being ignored. This has taken some time to track down.

**Comment by russcam** [comment]
If you're using NEST 6.x and above @rwb196884, `JsonIgnore` will not work without hooking up [`JsonNetSerializer`](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html#_jsonnetserializer). What version are you using?

**Comment by rwb196884** [comment]
NEST 6.6.0 and
``` 
ConnectionSettings cs = new ConnectionSettings(
  connectionPool: connectionPool,
  sourceSerializer: (builtin, settings) => new JsonNetSerializer(builtin, settings)
);
```
