### ISSUE TITLE
FormattableString generates a warning in alpha2

### ISSUE THREAD

**Issue by jonyadamit** [elastic/elasticsearch-net#1755]
> The predefined type 'FormattableString' is defined in multiple assemblies in the global alias; using definition from 'Elasticsearch.Net, Version=2.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'

**Comment by russcam** [comment]
Thanks for raising @jonyadamit :+1:

**Comment by russcam** [comment]
@jonyadamit what target framework(s) are you targeting in the project that is referencing Elasticsearch.Net?

**Comment by jonyadamit** [comment]
@russcam - .NET Framework 4.6

**Comment by russcam** [comment]
Thought that might be the case; Elasticsearch.Net targets .NET 4.5 that does not have `FormattableString` so there are types defined in the assembly to _bridge_ the gap and allow the use of  string interpolation.

Have added target framework `net46` in https://github.com/elastic/elasticsearch-net/commit/92abb15e3aac49b5d9b553f25702957575df868a and only include `FormattableString` and `FormattableStringFactory` only when targeting `net45`.
