### ISSUE TITLE
TtlField.cs 'Default' property - string vs time 

### ISSUE THREAD

**Issue by RobinRieger** [elastic/elasticsearch-net#1756]
In 2.0 alpha 2 I had to change the index call on a document re the `Ttl` field to pass in a `Time` object.

So, 
````
elasticClient.Index
    (objectToStore,
        x => x.Index("index")
        .Type<TestModel>()
        .Id("1234")
        .Ttl(new Time(new TimeSpan(30,0,0,0,0)))))
````

as opposed to what I had which was e.g.

`        .Ttl("30d")`

But when I make a mapping, the [TtlField.cs](https://github.com/elastic/elasticsearch-net/blob/82c938893b2ff4ddca03a8e977ad14a16da712ba/src/Nest/Mapping/MetaFields/Ttl/TtlField.cs) requires a 'string' for the `Default` property. 

Should this be changed to also be a `Time`? :confused:

**Comment by russcam** [comment]
[There are implicit operators to convert from `string`, `TimeSpan` and `double` to `Time`](https://github.com/elastic/elasticsearch-net/blob/4a987c4d7688d285f3ff81f1794398b1318a1243/docs/asciidoc/CommonOptions/TimeUnit/TimeUnits.doc.asciidoc), so using `"30d"` will convert to an instance of `Time` representing 30 days.

The `Default` property on `TtlField` should also be of type `Time` - thanks for reporting :+1:
