### ISSUE TITLE
Aggregations aren't being serialized when filtered

### ISSUE THREAD

**Issue by Romanx** [elastic/elasticsearch-net#1757]
When trying to serialize a search response using IElasticsearchSerializer, no aggregations are being returned just an empty object in the outputted json.

The aggregations return correctly to the code and are serialized into the class correctly but not out. It serializes correctly when not using a filter aggregation.

Small example

```json
{
  "query": {
    "match_all": {}
  },
  "aggs": {
    "results": {
      "filters": {
        "filters": {
          "filtered": {
            "terms": {
              "my_filter": [
                1
              ]
            }
          }
        }
      },
      "aggs": {
        "distilleries": {
          "terms": {
            "field": "some_field",
            "size": 5
          }
        }
      }
    }
  }
}
```

Results
```json
{
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  },
  "hits": {
    "total": 37130,
    "max_score": 1,
    "hits": [ "... removed for brevity ..." ]
  },
  "aggregations": {
    "results": {}
  },
  "took": 4,
  "timed_out": false,
  "terminated_early": false,
  "highlights": {}
}
```

**Comment by gmarz** [comment]
@Romanx using a filtered query in the filters aggregation isn't necessary, and doesn't really make sense.  In your case, you can just use a terms filter directly.

Also, the filtered query has been deprecated in 2.0 and can be replaced with a bool query (with a `must` and `filter` clause).

That said, I can't quite reproduce this...are you getting results if you run the raw JSON directly against ES (not using NEST)?.

**Comment by gmarz** [comment]
Closing.  Feel free to re-open if this is still an issue @Romanx.
