### ISSUE TITLE
DeleteByQuery don't set the generic as the type

### ISSUE THREAD

**Issue by tomasfalt** [elastic/elasticsearch-net#1758]
I noticed another difference between NEST 1.7.1 and NEST 2.0 namely that DeleteByQuery don't set the generic as the type. So this query will delete all documents of every type in the index PersonData:
``` c#
client.DeleteByQuery<Person>("PersonData", dq => dq.MatchAll());
```
but if I add Type it works like it did before, i.e. only deletes all documents of the Person type:
``` c#
client.DeleteByQuery<Person>("PersonData",
                   dq => dq.Type(Types.Type(typeof(Person))).MatchAll());
```

**Comment by Mpdreamz** [comment]
Thanks @tomasfalt the deletebyquery in 2.x now takes an explicit `Types` argument so this becomes less ambiguous. e.g `"mytype, mytype2"` or `Types.All` or `Type<Project>()` if you statically import `Nest.Infer`
