### ISSUE TITLE
Need .NET Core support

### ISSUE THREAD

**Issue by taschmidt** [elastic/elasticsearch-net#1760]
Really need this!  Are the plans to do it?

**Comment by gmarz** [comment]
Yes, we've already added support for CoreCLR and it's currently in master.  It'll be available in the next release, but marked "experimental" until the things are more stable.  Right now it works fine with [DNX](https://github.com/aspnet/dnx) tooling, but there are some issues using the [dotnet cli](https://github.com/dotnet/cli) (not yet released).

Also see #1697 and #1739
