### ISSUE TITLE
Bring back metrics and trace

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch-net#1762]
Two features from 1.x that have been removed in master due to refactoring are `MetricsEnabled()` and `TraceEnabled()`.  We should add them back, and I think trace can leverage the new `AuditTrail` bits?

**Comment by Mpdreamz** [comment]
I'm fine with leaving Trace out, i rather introduce LibLog and log `.DebugInformation` on `INFO`.

Our audit trail already gives timings for each individual step in the pipeline but not per step what the time to first byte / attempted serialization/deserialization time was. 

This would be awesome to bring back through metrics, however if we can do it **always** in a low allocation fashion that'd be awesome++.

**Comment by maeserichar** [comment]
So in case we want to log the API requests, what should be the way in the 2.x version?

**Comment by Mpdreamz** [comment]
Specifiy a handler on ConnectionSettings for `OnRequestCompleted()`

**Comment by maeserichar** [comment]
Great, thanks!

**Comment by Mpdreamz** [comment]
Closing this as the path forward is `DiagnosticSource` for tracing and `EventCounter` for metrics. Both of which have landed in the client and we'll look to augment, stabalize and document for the 8.0.0 release. 

cc @russcam @codebrain
