### ISSUE TITLE
Request Response Fields is null

### ISSUE THREAD

**Issue by RobinRieger** [elastic/elasticsearch-net#1767]
I have the follow simple query

```
var test = elasticClient.Search<ProductDoc>
    (s => s.AllTypes()
        .Take(100)
        .Skip(0)
        .Fields(fils => fils.Fields(f => f.ProductID, f => f.ProductName)));
```

Is the `Fields` in the response meant to be null? Am I mean to loop each `hit` to get the field values? 

![missing fields](https://cloud.githubusercontent.com/assets/16716449/12639078/a2296110-c5ed-11e5-9ed2-e1ddbb376579.jpg)

![fields in hits](https://cloud.githubusercontent.com/assets/16716449/12639080/a5c6ba52-c5ed-11e5-8ef5-88cf764b871b.jpg)

**Comment by russcam** [comment]
Thanks for reporting, @RobinRieger :+1:

**Comment by Mpdreamz** [comment]
Thanks @RobinRieger we had an integration test for this but that was sorely lacking some needed assertions.
