### ISSUE TITLE
Ids not URL-encoded in 2.0.0-alpha2

### ISSUE THREAD

**Issue by joelse** [elastic/elasticsearch-net#1768]
In the 1.7.1 release an id like, for example, 'my/id' would be URL-encoded in the HTTP request, but this no longer happens in 2.0.0-alpha2.

**Comment by Mpdreamz** [comment]
Thanks for reporting this @joelse huge oversight! Its why we co-created PUrify in the first place so that `/` are always properly escaped :smile:

Thanks for catching this before we did our first 2.0 release!
