### ISSUE TITLE
nuspec should depend on base major version of NewtonSoft.Json

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#1772]
This happens due the new packaging mechanism.

**Comment by russcam** [comment]
project.json supports version ranges for dependencies of the form `[8,9)` [using VersionUtility](https://github.com/NuGet/NuGet2/blob/2.11/src/Core/Utility/VersionUtility.cs#L419) but it appears to resolve to the lowest version that satisifies the range. In the case of Newtonsoft.Json, this is 8.0.1 for range `[8, 9)`

**Comment by Mpdreamz** [comment]
True but only because `8.0.0` does not exist :smile: https://www.nuget.org/packages/Newtonsoft.Json

**Comment by russcam** [comment]
@Mpdreamz this means that the project will pull in and compile against 8.0.1 rather than latest 8.* version. 

Would _fixing_ the nuspec dependency (similar to what we are doing for the Nest package id) be a better option for the moment?

**Comment by Mpdreamz** [comment]
++ that's the better fix :)

**Comment by russcam** [comment]
Cool, I'll put this in now :+1:
