### ISSUE TITLE
Can't use [ElasticsearchProperty] on 2.0

### ISSUE THREAD

**Issue by RTodorov** [elastic/elasticsearch-net#1775]
Hi guys,

I'm having trouble trying to map a simple document on 2.0.0-alpha2:

using Nest;

    [ElasticsearchType(Name = "document")]
    public class MyDocument
    {
        [ElasticsearchProperty(
            Name = "_id",
            Store = true
        )]
        public string Id { get; set; }
    }

Error:

```DNX,Version=v4.5.1 error CS0653: Cannot apply attribute class 'ElasticsearchPropertyAttribute' because it is abstract```

Do you have any clues? I know the documentation on the website is not updated to v2 but I'm following this:

https://nest.azurewebsites.net/nest/indices/put-mapping.html

BTW, do we already have alpha docs for v2?

Thanks a lot! Please let me know if I can help with something.

**Comment by gmarz** [comment]
Hey @RTodorov that's the old NEST 1.x syntax.  Sorry the documentation is out of date, [but we're working on new ones here](https://github.com/elastic/elasticsearch-net/tree/master/docs/contents/new).

Try this instead

```
[ElasticsearchType(Name = "document")]
public class MyDocument
{
    [String(Name = "_id", Store = true)]
    public string Id { get; set; }
}
```

Also see https://github.com/elastic/elasticsearch-net/pull/1520 for details.

**Comment by RTodorov** [comment]
Hi @gmarz , thank you very much for the prompt response!

I assume this page hasn't been updated yet:

https://github.com/elastic/elasticsearch-net/blob/2.0.0-alpha2/docs/contents/nest/indices/create-indices.markdown

Right?

Apparently the CreateIndexDescriptor doesn't accept the method AddMapping anymore, so I'm wondering what's the right way of setting the mapping during the creation of the index?

Thanks again and sorry for bothering you with all those questions.

**Comment by russcam** [comment]
Hey @RTodorov, _those aren't docs you're looking for (waves hand in jedi mind trick fashion)_ . 

[Take a look at the 2.x docs for `AutoMap()`](https://github.com/elastic/elasticsearch-net/blob/2.0.0-alpha2/docs/asciidoc/ClientConcepts/HighLevel/Mapping/AutoMap.doc.asciidoc)

The indentation has gone a bit funny on that doc, but essentially it's this

```c#
var createIndexResponse = client.CreateIndex("myindex", c => c
	.Mappings(ms => ms
		.Map<Company>(m => m.AutoMap())
		.Map<Employee>(m => m.AutoMap())
	)
);
```

**Comment by RTodorov** [comment]
You're the best @russcam ! Working perfectly now!

BTW, do you happen to know if it's possible to set Fielddata options (or format and precision) via attribute on a GeoPoint field, so I can avoid this:

            var createResponse = client.CreateIndex(indexName, c => c
                .InitializeUsing(indexState)
                .Mappings(ms => ms
                    .Map<VenueMapping>(m => m
                        .AutoMap()
                        .Properties(p => p
                            .Nested<AddressMapping>(n => n
                                .Name(pn => pn.Address)
                                .Properties(pp => pp
                                    .GeoPoint(g => g
                                        .Name(gf => gf.Location)
                                        .Fielddata(fd => fd
                                            .Format(GeoPointFielddataFormat.Compressed)
                                            .Precision(Distance.Meters(3))
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            );

Thanks again, I swear I won't bother you guys anymore! I'm just so excited about Nest 2.0 that I won't wait the final version to play with it!

**Comment by gmarz** [comment]
@RTodorov that's awesome to hear!

Unfortunately no, you can't use attributes to map fielddata options.  Aside from multi fields, the other limitation of using attributes is that they only support scalar values, not objects (limitation of C#).  Your current approach is the right one.

**Comment by babadofar** [comment]
+1 on the excitement for 2.0, looking forwards to the new and correct documentation :)
