### ISSUE TITLE
Uncomment and fix unit tests

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#1776]
Uncomment and fix unit tests for Naming Conventions https://github.com/elastic/elasticsearch-net/blob/8632fc197c01e5f8a7b89a0e9b2cc357e9163903/src/Tests/CodeStandards/NamingConventions.doc.cs

**Comment by russcam** [comment]
Added a PR #1779 for this as it's quite a sweeping set of changes :smile:

**Comment by Mpdreamz** [comment]
#1779 is pulled in, thanks @russcam :+1:
