### ISSUE TITLE
Delete by Query - Usage Question

### ISSUE THREAD

**Issue by RobinRieger** [elastic/elasticsearch-net#1777]
I had this query, 

```
// Note: yes, this is meant to be an 'object' as I do not know 
// the 'type' of the document in this use case. I merely know that
// the document inherits from an interface 'iTest'. I just used 'object'
// until now and this worked....
esClient.DeleteByQuery<object>
                (Indices.Index("indexName"),
                 x => x.AllTypes()
                       .Query(q => q.MatchAll()));
```

which seems not to want to work anymore in 2.0

I looked at the folder [here](https://github.com/elastic/elasticsearch-net/tree/master/src/Nest/Document/Multiple/DeleteByQuery) re the delete by query stuff and if I look at the `ElasticClient-DeleteByQuery.cs` file it refers to a link to the ES documentation 'http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/docs-delete-by-query.html' which 404s.... which according to [here](https://www.elastic.co/guide/en/elasticsearch/reference/1.6/docs-delete-by-query.html) is correct becaue the delete by query is removed it was a 'break change' of the 2.0 [here](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_removed_features.html).

Anyways, is the `DeleteByQuery` still meant to work? If so my question is how can I delete all documents from a particular index which match a particular query (for simplicity, let's just say 'all documents' in an index). Should I be using a `scan` and `scroll` approach?

Ps: I notice [here](https://github.com/elastic/elasticsearch-net/issues/1758) that the delete by query is still being worked on as recently as two days ago, so I am probably just not understanding the usage of it.... :confused:

**Comment by tomasfalt** [comment]
@RobinRieger have add the DeleteByQuery plugin https://www.elastic.co/guide/en/elasticsearch/plugins/2.0/plugins-delete-by-query.html? After that your query should be working. See also my question about the types and @Mpdreamz response here https://github.com/elastic/elasticsearch-net/issues/1758.

**Comment by RobinRieger** [comment]
Thanks for that. Yeah I saw the plugin but had not realized that nest uses the plugin for this. I thought nest was only for the 'core' elasticsearch 'stuff'. Is there a list of all the plugins ES nest uses? I.e. ones that I need / should install to be able to use all the methods?

**Comment by russcam** [comment]
@RobinRieger For the integration tests, [two plugins are installed](https://github.com/elastic/elasticsearch-net/blob/92fdb2f0aeed098743c4d24ed1cf05229794cc32/src/Tests/Framework/Integration/Process/ElasticsearchNode.cs#L25):

1. [Delete by query plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/current/delete-by-query-plugin-reason.html#_new_delete_by_query_implementation)
2. [Azure cloud plugin ](https://github.com/elastic/elasticsearch-cloud-azure)

The first is required for delete by query to work and [the second is to ensure snapshot and restore works against an Azure repository](https://github.com/elastic/elasticsearch-net/blob/master/src/Tests/Modules/SnapshotAndRestore/Repositories/CreateRepository/CreateRepositoryApiTests.cs#L11).

If you need delete by query functionality, you should install the plugin.
