### ISSUE TITLE
Align naming of request/response for IValidateQueryRequest and IValidateResponse

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#1778]
The [`ElasticClient.Validate()`](https://github.com/elastic/elasticsearch-net/blob/82c938893b2ff4ddca03a8e977ad14a16da712ba/src/Nest/Search/Validate/ElasticClient-Validate.cs#L32) methods take a request type of `IValidateQueryRequest` but return a response type of `IValidateResponse`. The naming is not consistent  with the general request/response naming convention (where there is a one-to-one mapping of request type to response type).

@Mpdreamz, @gmarz - should  `IValidateQueryRequest` be renamed to `IValidateRequest`?

**Comment by Mpdreamz** [comment]
I'm +1 on renaming to `client.ValidateQuery()` and `ValidateQueryResponse`

**Comment by russcam** [comment]
:+1:

**Comment by gmarz** [comment]
+1
