### ISSUE TITLE
1.7.1 - limit on Newtonsoft.Json version

### ISSUE THREAD

**Issue by megakid** [elastic/elasticsearch-net#1781]
I am wondering what the reason behind adding a hard stop on the nuget `Newtonsoft.Json` dependency e.g. `[7,8)`

From what I can tell, there are some minor breaking changes between the versions but NEST does not use these and continues to work with v8 with an assembly redirect.  The upper limit is causing a number of issues when updating nuget packages (We are using 1 of the new v8 features - `ArrayPool` support).

Can this `nuspec` dependency version specification be diluted to perhaps `[7,9)` - assuming I haven't missed any broken functionality in NEST that v8 has caused?

**Comment by russcam** [comment]
Hey @megakid, we're currently working on getting NEST 2.x GA release out (_nearly there_) before working on issues related to the 1.x branch.

The concern that we have we doing this with our current setup is that we only build against the latest stable release within the version range specified in the nuspec file; in the case of 1.x, this is Newtonsoft.Json 7.0.1. Whilst it is very likely that NEST 1.x will work against 8.x versions of Json.Net, we would want to be confident about advertising that we support this by compiling and running tests against that version.

It's something that we've discussed and would like to do :+1:

**Comment by kbilsted** [comment]
@russcam  I can understand the need for testing, but I'd vote for giving v.1.7.1 some love ;-)

**Comment by niemyjski** [comment]
We really need this as well.. Can we get a 1.7.2 out with this please.

**Comment by ejsmith** [comment]
Yes, there have been other things fixed too. Would be really good to get a maintenance release out.

**Comment by Mpdreamz** [comment]
Hi Guys,

Sorry for leaving this issue open for so long, I just bumped the upper limit to 9 for Json.NET and we will get a `1.x` release out asap.

**Comment by niemyjski** [comment]
Thanks

**Comment by niemyjski** [comment]
Wondering if the dependency should be 8-9, so then we don't have to do binding redirects

**Comment by gmarz** [comment]
Just released 1.7.2 :)  The upper limit on Json.Net has been bumped per @Mpdreamz's commit above, so you'll be able to upgrade in your application.

We're going to upgrade our dependency to Json.Net 8 and release that as 1.8 shortly.
