### ISSUE TITLE
JsonReaderException on bulk response (NEST 1.7.1)

### ISSUE THREAD

**Issue by poulfoged** [elastic/elasticsearch-net#1783]
When a bulk request has errors deserialization seems to fail.

To reproduce simply index same document twice:
```
await client.BulkAsync(i => i.CreateMany(new[] { new { id = "test-id" } }, (m, p) => m.Index("test-index")));
await client.BulkAsync(i => i.CreateMany(new[] { new { id = "test-id" } }, (m, p) => m.Index("test-index")));
```

Results in exception from second request:

Newtonsoft.Json.JsonReaderException : Error reading string. Unexpected token: StartObject. Path 'items[0].create.error', line 1, position 136.

**Comment by gmarz** [comment]
Hi @poulfoged what version of Elasticsearch?

**Comment by poulfoged** [comment]
Hi, version 2.1.1 - maybe thats not supported?

**Comment by russcam** [comment]
@poulfoged Nest 1.x (1.7.1 in this case) is not compatible with 2.x of Elasticsearch - it _may_ work for the most part but there are some real differences in Elasticsearch 2.x that will result in exceptions in the NEST client. The format of errors returned from Elasticsearch is one of those differences :smile: 

[We released an RC release of Nest yesterday to Nuget](https://www.nuget.org/packages/NEST/2.0.0-rc1) if you'd like to give that one a try.

**Comment by poulfoged** [comment]
Ok, I will - sorry for the confusion. Thanks.

**Comment by russcam** [comment]
:+1:
