### ISSUE TITLE
Percentiles agg missing options

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#1785]
`compression`: https://www.elastic.co/guide/en/elasticsearch/reference/2.1/search-aggregations-metrics-percentile-aggregation.html#search-aggregations-metrics-percentile-aggregation-compression

`number_of_significant_value_digits`: https://www.elastic.co/guide/en/elasticsearch/reference/2.1/search-aggregations-metrics-percentile-aggregation.html#_hdr_histogram

`missing`: https://www.elastic.co/guide/en/elasticsearch/reference/2.1/search-aggregations-metrics-percentile-aggregation.html#_missing_value_6

**Comment by gmarz** [comment]
`missing` isn't missing :) It's implemented on the [MetricAggregationBase](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Aggregations/Metric/MetricAggregation.cs#L31).

**Comment by gmarz** [comment]
Oh yea, I remember this now. `compression` and `number_of_significant_value_digits` are implemented per the selected [TDigest method](https://github.com/elastic/elasticsearch-net/tree/master/src/Nest/Aggregations/Metric/Percentiles/Methods).  See https://github.com/elastic/elasticsearch/issues/14691
