### ISSUE TITLE
Rename IElasticsearchClient to ILowLevelElasticClient

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#1788]
To offset it against `IElasticClient` from NEST even harder.

cc @gmarz @russcam

**Comment by gmarz** [comment]
+1 to renaming, but only 90% convinced on `ILowLevelElasticClient`.  Need to let it bake.

While on the topic, what about `ConnectionSettings` and `ConnectionConfiguration`?  We discussed renaming these as well since they don't pertain to the connection only.

**Comment by russcam** [comment]
`ILowLevelElasticClient` or `IElasticLowLevelClient`? With the property on `IElasticClient` renamed from `.Raw` to `.LowLevelClient` (or `.LowLevel`)?

I'm also +1 for renaming, so long as we can come up with a good name :smile:
