### ISSUE TITLE
AggregationDictionary (IsADictionary) cast back to dictionary

### ISSUE THREAD

**Issue by Romanx** [elastic/elasticsearch-net#1790]
AggregationDictionary implements the interface `IsADictionary<string, IAggregationContainer>` and has implicit operators to cast Dictionaries to `AggregationDictionary` however it is not possible to do it the other way around.

`IsADictionary` has a `BackingDictionary` field which is protected, could we have a way of accessing this?

**Comment by russcam** [comment]
Hey @Romanx, `AggregationDictionary` implements `IDictionary<string, IAggregationContainer>` so you can cast it to this to access `IDictionary<string, IAggregationContainer>` methods that are implemented explicitly on `AggregationDictionary`.

Is there some reason that you explicitly wanted the `BackingDictionary` (`Dictionary<string, IAggregationContainer>`)?

**Comment by Romanx** [comment]
Seems i was trying to cast it to `Dictionary<string, IAggregationContainer>` which was causing me an error. Consider this closed :)
