### ISSUE TITLE
BucketAggregateData is internal so data can't be accessed

### ISSUE THREAD

**Issue by Romanx** [elastic/elasticsearch-net#1792]
As [this](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Aggregations/Bucket/BucketAggregate.cs#L33) class is internal and it is used as the return from a `SingleBucketAggregate` and I want to access the result. My code like this
```c#
var aggs = aggregations
    .Aggregations
    .Select(a => a.Value as SingleBucketAggregate)
    .Select(a =>
    {
        var first = a.Aggregations.First();
        return first.Value; // BucketAggregateData
    });
```

I can't access any data from the aggregations as the type `BucketAggregateData` is internal and `IAggregate` only has Meta on it.

**Comment by michaelbudnik** [comment]
Try using response.Aggs (not Aggregates) helpers like response.Aggs.GeoHash("key").
Seems strange to me to have Aggs and Aggregations anyway...

**Comment by gmarz** [comment]
@Romanx the reason `BucketAggregateData` is internal is because it's essentially a DTO object only used by our deserializer, and we don't really want to expose it to users as it isn't strongly typed to a particular bucket type.  We also might get rid of it entirely eventually and refactor the way [AggregateJsonConverter]() works.

As @michaelbudnik mentioned, you can use `Aggs` instead which will do the cast from `BucketAggregateData` -> `ActualBucketType` (could be `SingleBucketAggregate`,  `MultiBucketAggregate`, `TermsAggregate`, `FiltersAggregate`, etc...).  But you'll need to know the type of aggregation on the response (e.g. it's a filters aggregation then `Aggs.Filters("my_filters_agg")`).

That said, you can totally still use the `Aggregations` dictionary like you are above, and that's exactly why we still expose it.  However, you need to cast the `IAggregate`s to their actual aggregate type manually.

For instance, using your example above:

```csharp
var singleBucket = aggs.First() as SingleBucketAggregate;
```

Or if you know they are all of a certain type:

```csharp
var aggs = aggregations
    .Aggregations
    .Select(a => a.Value as SingleBucketAggregate)
    .Select(a =>
    {
        var first = a.Aggregations.First();
        return first.Value; // BucketAggregateData
    })
   .Cast<SingleBucketAggregate>();
```

Hope that makes sense?

@michaelbudnik yea it can be confusing to have both `Aggs` and `Aggregations` on the response, but they both serve their purposes.  We'll put some thought into how/if we can make this better for the GA release.  Would love you and @Romanx feedback on this.

**Comment by Romanx** [comment]
@gmarz I attempted the cast method as you suggested but the type of my aggregation internally is `BucketAggregateData` I can't cast it to any other type to get at the values, not sure what i'm doing wrong.

As @michaelbudnik noted i could access directly using the name however i'd rather not hardcode all my filters as i'm transforming the results into a more consumable format for my output.

**Comment by gmarz** [comment]
@Romanx Can you share the aggregation portion of your request here?

**Comment by michaelbudnik** [comment]
@gmarz
Here comes the feedback: 
IDictionary<string, IAggregate> Aggregations is available in both ISearchResponse and AggregationsHelper. I'm not sure if it is because of the backward compatibility.

**Comment by Romanx** [comment]
```json

"aggs": {
    "field_a": {
      "filter": {
        "and": {
          "filters": [
            {
              "terms": {
                "field_b_id": [
                  1781
                ]
              }
            }
          ]
        }
      },
      "aggs": {
        "field_a": {
          "terms": {
            "field": "field_a_agg",
            "size": 20
          }
        }
      }
    },
    "field_b": {
      "filter": {
        "and": {
          "filters": [
            {
              "terms": {
                "field_a_id": [
                  1760,
                  1759
                ]
              }            }
          ]
        }
      },
      "aggs": {
        "field_b": {
          "terms": {
            "field": "field_b_agg",
            "size": 20
          }
        }
      }
    },
    "field_c": {
      "filter": {
        "and": {
          "filters": [
            {
              "terms": {
                "field_a_id": [
                  1760,
                  1759
                ]
              }
            },
            {
              "terms": {
                "field_b_id": [
                  1781
                ]
              }
            }
          ]
        }
      },
      "aggs": {
        "field_c": {
          "terms": {
            "field": "field_c_agg",
            "size": 20
          }
        }
      }
    },
    "field_d": {
      "filter": {
        "and": {
          "filters": [
            {
              "terms": {
                "field_a_id": [
                  1760,
                  1759
                ]
              }
            },
            {
              "terms": {
                "field_b_id": [
                  1781
                ]
              }
            }
          ]
        }
      },
      "aggs": {
        "field_d": {
          "terms": {
            "field": "field_d_agg",
            "size": 20
          }
        }
      }
    },
    "field_e": {
      "filter": {
        "and": {
          "filters": [
            {
              "terms": {
                "field_a_id": [
                  1760,
                  1759
                ]
              }
            },
            {
              "terms": {
                "field_b_id": [
                  1781
                ]
              }
            }
          ]
        }
      },
      "aggs": {
        "field_e": {
          "terms": {
            "field": "field_e_agg",
            "size": 20
          }
        }
      }
    },
    "field_f": {
      "filter": {
        "and": {
          "filters": [
            {
              "terms": {
                "field_a_id": [
                  1760,
                  1759
                ]
              }
            },
            {
              "terms": {
                "field_b_id": [
                  1781
                ]
              }
            }
          ]
        }
      },
      "aggs": {
        "field_f": {
          "terms": {
            "field": "field_f",
            "size": 2
          }
        }
      }
    },
    "field_g": {
      "filter": {
        "and": {
          "filters": [
            {
              "terms": {
                "field_a_id": [
                  1760,
                  1759
                ]
              }
            },
            {
              "terms": {
                "field_b_id": [
                  1781
                ]
              }
            }
          ]
        }
      },
      "aggs": {
        "field_g": {
          "terms": {
            "field": "field_g",
            "size": 2
          }
        }
      }
    },
    "field_h": {
      "filter": {
        "and": {
          "filters": [
            {
              "terms": {
                "field_a_id": [
                  1760,
                  1759
                ]
              }
            },
            {
              "terms": {
                "field_b_id": [
                  1781
                ]
              }
            }
          ]
        }
      },
      "aggs": {
        "field_h": {
          "terms": {
            "field": "field_h",
            "size": 2
          }
        }
      }
    },
    "field_i": {
      "filter": {
        "and": {
          "filters": [
            {
              "terms": {
                "field_a_id": [
                  1760,
                  1759
                ]
              }
            },
            {
              "terms": {
                "field_b_id": [
                  1781
                ]
              }
            }
          ]
        }
      },
      "aggs": {
        "field_i": {
          "terms": {
            "field": "field_i",
            "size": 2
          }
        }
      }
    }
  }
```

Here you are. It's a little convoluted but essentially we're filtering each aggregate by every other field apart from itself hence the strange splitting. If there's a neater way i'd love to hear it.

Also to agree with @michaelbudnik having the aggregations dictionary available on both can be very confusing.

**Comment by gmarz** [comment]
> IDictionary<string, IAggregate> Aggregations is available in both ISearchResponse and AggregationsHelper. I'm not sure if it is because of the backward compatibility.

The reason it's on both is so that you can access the aggregation dictionary on a sub-aggregation just as you can on the outer most aggregation on the response itself.

**Comment by Romanx** [comment]
That makes sense but on the top level ISearchResponse is `IDictionary Aggregations` needed when it can be retrieved by doing `response.Aggs.Aggregations` which may be a little clearer if more code.

@gmarz Any thoughts on how I can access the results from my aggregation, at the moment I've got an awful hack of using reflection to get at the Items list in the BucketAggregateData. Again if there's a neater way of doing this i would love to hear it as it's a very convoluted and confusing approach but i can't find a better one.

**Comment by gmarz** [comment]
@Romanx I'm working on a fix for this.  The problem stems from the fact that there's no way of determining the response type (`IAggregate`) at the time of deserialization due to the way `AggregateJsonConverter` works.

We might have to make `BucketAggregateData` public again, but trying to avoid that.  I'm currently spiking an alternative deserialization implementation that uses [aggregation metadata](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/agg-metadata.html) that would solve this.

**Comment by Romanx** [comment]
@gmarz Thanks for the update, i'll look forward to seeing what you come up with and provide feedback :+1:

**Comment by gmarz** [comment]
@Romanx Unfortunately using metadata will have to wait for NEST 3.0 as there's a bug in elasticsearch that prevents us from targeting the 2.0 release.  See #1806 for details.

For now, I've made `BucketAggregateData` public again, but renamed to `BucketAggregate`.  You should be able to revert back to the original way of retrieving aggregations with the next release.

Feel free to re-open this if you run into any other issues.
