### ISSUE TITLE
Simplify response error handling

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch-net#1794]
A follow up from #1793 

This issue is two parts:

1) Design a way to encapsulate and simply error handling

2) Add `DebugInformation` to response that pretty prints error information for debugging and issue reporting

**Comment by Mpdreamz** [comment]
2) is implemented and is immensely useful
1) We are going to stick to our "progression over perfection" mantra for now. The error/exception handling is already greatly simplified from `1.x`. 

cc @russcam
