### ISSUE TITLE
Document ID is not escaped in URI

### ISSUE THREAD

**Issue by godefroi** [elastic/elasticsearch-net#1799]
When I call ElasticsearchClient.Index<T>() with an id of "x.x.x.3/001", the URI that is called is this:

http://1.1.1.1:9200/myindexname/mydocumenttype/x.x.x.3/001

This did not seem to be an issue with the previous (1.7.x) version.

**Comment by Mpdreamz** [comment]
Are you using rc1?

**Comment by godefroi** [comment]
Yes, 2.0.0-rc1.

**Comment by Mpdreamz** [comment]
Thanks a ton for opening this issue, I whole fully inadequately implemented and tested this only for NEST not the lowlevel client :cry:  

This is now fixed!
