### ISSUE TITLE
.ConfigureAwait(false) all async/await methods

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#1801]
Since none of our async methods need to callback on the context, [we should configure all async calls not to capture it](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx).

**Comment by niemyjski** [comment]
I took a look at the source code and it looks like you are missing them in quite a few spots: Here is one of them: https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs#L111 and pretty much every call to await Task.Delay(x). You may want to do a search for `await ` the project and then in the find window search for configureawait and if you don't see one on every result line... You may be missing a spot.
