### ISSUE TITLE
Filter clause missing in posted Json

### ISSUE THREAD

**Issue by ma-hag** [elastic/elasticsearch-net#1807]
NEST 2.0.0-rc1.
In the automapped class Person (DynamicMapping.Strict) there's a nested field 'CustomProperties' attributed with [Nested(Dynamic = DynamicMapping.Allow)].

Here's a query that fails finding documents where the nested property 'CustomProperties' is missing the field 'customProperties.oddPersonality'.
```
query = Query<Person>
	.Nested(n => n
		.Path(np => np.CustomProperties)
		.Query(nq => nq
			.Bool(nqb => nqb
				.Must(m => m.MatchAll())
				.Filter(f => f.Missing(m => m.Name("customProperties.oddPersonality"))))));
```

Generated json (according to hits.ApiCall.RequestBodyInBytes):
`{"query":{"nested":{"query":{"bool":{"must":[{"match_all":{}}]}},"path":"customProperties"}}}`

Note the absence of 'filter' in the json above.

Simply replacing the fluent '.Filter(...)' row with the raw json will make the query work: 
`.Filter(f => f.Raw(@"{""missing"": {""field"": ""customProperties.oddPersonality"" } }")))));`

Generated json (according to hits.ApiCall.RequestBodyInBytes):
`
{"query":{"nested":{"query":{"bool":{"must":[{"match_all":{}}],"filter":[{"missing": {"field": "customProperties.oddPersonality"}}]}},"path":"customProperties"}}}
`
Here the filter clause is included, as expected.

Any thoughts on how I can get the fluent code working?

**Comment by russcam** [comment]
Hey @ma-hag, There's a small mistake in your fluent query - it should be `m.Field("customProperties.oddPersonality")`. So it will look like

```c#
query = Query<Person>
    .Nested(n => n
        .Path(np => np.CustomProperties)
        .Query(nq => nq
            .Bool(nqb => nqb
                .Must(m => m.MatchAll())
                .Filter(f => f.Missing(m => m.Field("customProperties.oddPersonality"))))));
```

`.Name()` is for [named queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-named-queries-and-filters.html)

**Comment by ma-hag** [comment]
Thanks, @russcam!
