### ISSUE TITLE
Using publish_host with host/domain name instead of IP address does not work with connection pools

### ISSUE THREAD

**Issue by joelse** [elastic/elasticsearch-net#1808]
Elasticsearch: 2.1.1
Elasticsearch.NET/NEST: 2.0.0-rc1

Configuring the cluster to use a host/domain name for the http.publish_host setting (useful for reverse proxies) does not work with connection pools. It seems that Elasticsearch itself tries to resolve the value of the setting into an IP address and stores both the name and the address as a publish_address. Querying a cluster set up like this with, e.g., /_nodes, shows that the http_address field has a value like this, for example:

```
<FQDN>/<IP>:<port>
```

When using a sniffing connection pool, and once a sniff has been completed, the pool will be reseeded with nodes using the above as the base URL. This means that subsequent calls have the following form:

```
<http(s)>://<FQDN>/<IP>:<port>/rest/of/url/in/request (with port 80 used implicitly for HTTP requests)
```

Before trying this, I would have expected the following:

```
<http(s)>://<FQDN>:<port>/rest/of/url/in/request
````

Where FQDN would be the value configured for http.publish_host and port the value configured for http.publish_port.

**Comment by Mpdreamz** [comment]
@joelse can you paste the output of a manual GET to: 

`_nodes/_all/settings?flat_setting`

**Comment by joelse** [comment]
curl -XGET 'joelse:9200/_nodes/_all/settings?flat_setting'

{"cluster_name":"joelse-cluster","nodes":{"6nVf-X4qQwqAksLkerKPzQ":{"name":"Rachel Grey","transport_address":"127.0.0.1:9300","host":"127.0.0.1","ip":"127.0.0.1","version":"2.1.1","build":"40e2c53","http_address":"joelse/172.17.67.51:9200","settings":{"name":"Rachel Grey","client":{"type":"node"},"cluster":{"name":"joelse-cluster"},"http":{"publish_port":"9200","bind_host":"localhost","port":"9201","publish_host":"joelse"},"path":{"logs":"C:/Development/elasticsearch-2.1.1/logs","home":"C:\\Development\\elasticsearch-2.1.1"},"config":{"ignore_system_properties":"true"}}}}}

**Comment by joelse** [comment]
Instead of http_address contains the combined host/address:port value, but the values I've configured are settings.http.publish_host and settings.http.publish_port.

**Comment by Mpdreamz** [comment]
Thanks for opening this one @joelse :+1: Pushed a fix we now prefer the configured host name as the host for the nodes.
