### ISSUE TITLE
ConnectionPool with primary and fallback

### ISSUE THREAD

**Issue by Romanx** [elastic/elasticsearch-net#1810]
Hi,

We have a cluster with two nodes that have the data replicated between them. Each of our servers want to talk to the closest node, is there any way we can prioritize one node other another for a request? Is there some kind of connection pool for this or would i have to roll my own?

Thanks,

**Comment by Mpdreamz** [comment]
This does not exists, the interface to implement is here: https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/ConnectionPool/IConnectionPool.cs 

If you fancy a challenge, we will definitely accept a "sticky" connection pool implementation, this would also work for your use case e.g

* `Machine A` initializes with `Node 1, Node 2`
* `Machine B` initializes with `Node 2, Node 1`

This sticky connection pool's CreateView() always returns node in that order 

This has been requested before: #1507

**Comment by Romanx** [comment]
@Mpdreamz I'll take a look at implementing something. Any requirements on your end for what a sticky connection pool should be like? Also are there any other documentation on the life-cycle of a connection pool?

**Comment by gmarz** [comment]
Closed via #1831
