### ISSUE TITLE
2.0.0 has problems with parsing http_adress with only IP and port

### ISSUE THREAD

**Issue by joelse** [elastic/elasticsearch-net#1811]
You guys quickly fixed issue [#1808](https://github.com/elastic/elasticsearch-net/issues/1808), but now there's a problem when a host/domain name is not there. It's not immediately clear to me why, but if the input to SniffResponse.ParseToUri is something like `192.168.17.42:9200`, `fqdn` becomes `192.168.17.4` and `ip` becomes `2`, so the resulting URI becomes `http://192.168.17.4:9200`.

The following seems to work:
```c#
new Regex(@"^((?<fqdn>[^/]+)/)?(?<ip>[^:]+):(?<port>\d+)$")
```

We either have a part that ends with `/` and then `fqdn` is everything but that last character, or we don't have such a part and then we don't care about `/` at all.

**Comment by Mpdreamz** [comment]
Argh, not cool on a GA release :-1: to us. I just updated our packages to 2.0.1

https://github.com/elastic/elasticsearch-net/releases/tag/2.0.1

Should appear on nuget once they get indexed

Thanks every so much @joelse
