### ISSUE TITLE
SearchRequest override Index

### ISSUE THREAD

**Issue by Romanx** [elastic/elasticsearch-net#1812]
Hey,

Firstly sorry for opening so many tickets, thanks for the great job you're doing here and congratulations on the GA release.

I'm generating a query in parts and building it using SearchRequest which means I can't use the fluent interface to define my query at compile time. However using the fluent interface is the only way I can find to set the type and index you want a query to be run on, I can't seem to find these on SearchRequest.

Is there a way to do this? If not then could it please be a feature request?

**Comment by Mpdreamz** [comment]
You can pas these on the constructor:

https://github.com/elastic/elasticsearch-net/blob/82c938893b2ff4ddca03a8e977ad14a16da712ba/docs/contents/new/Search/Search/SearchUrlTests.asciidoc

Thanks for opening so many tickets :smile: !

**Comment by Romanx** [comment]
Is there no way to override them after a request has been created? I literally just spotted the constructor method after posting! =D

**Comment by Mpdreamz** [comment]
No there is no way, if a part is optional you can use `Types.All` or `Indices.All` to fallback on

**Comment by Romanx** [comment]
@Mpdreamz Okay then, thank you :+1:
