### ISSUE TITLE
Undesirable serialization of conditionless queries when using object initializer syntax

### ISSUE THREAD

**Issue by tuespetre** [elastic/elasticsearch-net#1817]
When using the object initializer syntax, any property that accepts `IEnumerable<QueryContainer>` (for example, `BoolQuery.Must`) is serialized with a `null` value per conditionless query.

Excerpt of an example query:

```
var request = new SearchRequest
{
    Query = new BoolQuery
    {
        Must = new List<QueryContainer>
        {
            new QueryStringQuery
            {
                Query = someNotNullNotEmptyString
            },
            new QueryStringQuery
            {
                Query = someNullString
            },
            new QueryStringQuery
            {
                Query = someEmptyString
            },
        }
    }
};
```

Excerpt of the example response:

`{"must":[{"query_string":{"query":"some search terms"}},null,null]}`

Expected:

`{"must":[{"query_string":{"query":"some search terms"}}]}`

**Comment by tuespetre** [comment]
See: https://github.com/elastic/elasticsearch-net/blob/2.0.1/src/Nest/QueryDsl/Abstractions/Query/QueryBase.cs#L72

**Comment by russcam** [comment]
Thanks for reporting @tuespetre :+1:

**Comment by russcam** [comment]
Just pushed a commit for this so that when serializing a collection of queries, a query will only be serialized if it's not null, strict or not conditionless.
