### ISSUE TITLE
MultiMatch OnFieldsWithBoost in NEST 2.x

### ISSUE THREAD

**Issue by Reonekot** [elastic/elasticsearch-net#1819]
I used to use the OnFieldsWithBoost construct on MultiMatch in NEST 1.7 for query time boosts, but I can't figure out how to get the same result with MultiMatch in NEST 2. What have I missed? :)

Right now my query without boost looks like:
```
.MultiMatch(m => m
    .Fields(fd => fd.Fields(
        ff => ff.HeadLine,
        ff => ff.LabelAdvice,
        ff => ff.MandatoryText,
        ff => ff.Note,
        ff => ff.Teaser))
    .Type(queryType)
    .Query(searchText)
    .Fuzziness(fuzziness)
```

**Comment by gmarz** [comment]
Hey @Reonekot it looks like this now:

```csharp
.MultiMatch(m => m
	.Fields(fields => fields
		.Field(p => p.Fizz, 1.5)
		.Field(p => p.Buzz 1.2)
		.Field(p => p.FizzBuzz, 0.8)
	)
)
```

**Comment by Reonekot** [comment]
Sorry for the late reply, but I have tested this I can't seem to get it to work with NEST 2.0.2. It doesn't produce the expected DSL query as far as I can tell?

My NEST query:
`            var searchResponse = await client.SearchAsync<Product>(s =>
            {
                s.From(0)
                 .Size(5)
                 .Query(q => q
                    .MultiMatch(m => m
                        .Fields(fields => fields
                            .Field(p => p.HeadLine, 1.5)
                            .Field(p => p.LabelAdvice, 1.2)
                            .Field(p => p.MandatoryText, 0.8)
                        )
                        .Query(searchText)
                    ));

                return s;
`
Produces:
`{
  "from": 0,
  "size": 5,
  "query": {
    "multi_match": {
      "query": "my query text",
      "fields": [
        "headLine",
        "labelAdvice",
        "mandatoryText"
      ]
    }
  }
}`
Where I'd expected some ^ to boost in there...

**Comment by gmarz** [comment]
Hmm, seems like a bug then.  Re-opening this.

**Comment by EmilAlipiev** [comment]
Is there any news on this? If this doesn't work, should we stick with 1.7 version until it is fixed?

**Comment by Mpdreamz** [comment]
Just pushed a fix for this we will release a patch release soon! Or you can switch to our bleeding edge myget feed which should have this fix in 20minutes or so.

**Comment by Reonekot** [comment]
Thanks for fixing this ! :)
