### ISSUE TITLE
AutoMap maxRecursion is ignored

### ISSUE THREAD

**Issue by MikeHarnetty** [elastic/elasticsearch-net#1821]
Hello

I'm using attributes to map properties, and since one of the types I want to map contains itself I'm calling AutoMap with the maxRecursion parameter set to a depth I'd like to recurse to:

`client.Map<T>(m => m.Index("index_name").AutoMap(maxRecursion))`

However this doesn't seem to have any effect.

I dug into AutoMap a little and it appears that parameter is never actually used here when creating the PropertyWalker:

```
public PutMappingDescriptor<T> AutoMap(IPropertyVisitor visitor = null, int maxRecursion = 0) => Assign(a =>
		{
			a.Properties = a.Properties ?? new Properties();
			var autoProperties = new PropertyWalker(typeof(T), visitor).GetProperties();
			foreach (var autoProperty in autoProperties)
				a.Properties[autoProperty.Key] = autoProperty.Value;
		});

```
Cheers
Mike

**Comment by gmarz** [comment]
Thanks for reporting this @MikeHarnetty :+1: Fixed in the attached commit.

Our tests didn't catch this because they only test AutoMap on CreateIndex and not PutMapping.
