### ISSUE TITLE
client.Update question

### ISSUE THREAD

**Issue by CocaColaBear** [elastic/elasticsearch-net#1824]
In 1.x version, my update looks like:

```
var model = ....
...
client.Update<Model>(
                u => u.Index("indexName")
                    .IdFrom(model)
                    .Doc(model));
```
But now, in 2.0, i replaced it to:

```
client.Update(new DocumentPath<Model>(model), s => s
                .Index(new IndexName { Name = "indexName" })
                .Doc(model)
                //.IdFrom(model) !!! What about Id?
            );
```

Im righjt or no? And what about IdFrom ?

**Comment by Mpdreamz** [comment]
When you call 

```csharp
client.Update(new DocumentPath<Model>(model), s => s
      .Index(new IndexName { Name = "indexName" })
      .Doc(model)
);
```

DocumentPath will already infer the index, typename for `Model` and get the Id from `model` 

So you only need to specify `.Index()` if it differs from the inferred index name. 

`model` will implicitly convert to a DocumentPath so

```csharp
client.Update<Model>(model, s => s
      .Index(new IndexName { Name = "indexName" })
      .Doc(model)
);
```

is equivalent.

It looks however like your are updateing the entire document again. You can simply call 

```csharp
client.Index(model);
````

If you are doing a full bodies update.
