### ISSUE TITLE
Issue with "_content" mapping on the  [Attachment]

### ISSUE THREAD

**Issue by kyakhta** [elastic/elasticsearch-net#1828]
Let's declare the object

```c#
 public class Document
    {
        public string Id { get; set; }

        [Attachment]
        public Data Data { get; set; }
    }
```
where Data type is

```c#
 public class Data
 {
        [String(Name = "_content", Store = true, TermVector = TermVectorOption.WithPositionsOffsets)]
        public string Content { get; set; }
}
```

After index created _content attribute will be resolved into  data.content field.

Then, when searching with Document type on the Data.Content field, actual Json, that will be sent to the ES, will looks like as 
```javascript
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "data._content": {
              "value": "tika"
            } }}]}}}
```
So, _content will have underscore and search will fail. When underscore is removed directly in  HEAD plugin query or by modifying    [String(Name = "_content" attribute to the    [String(Name = "content" then search will succeed. Looks like  on the search call _content field not getting properly resolved and caused search to fail. I did not tested this issue with rest of the Tika fields (_name, _content_type, etc)

**Comment by russcam** [comment]
I've added #2085 to make it easier to work with the mapper attachment plugin

**Comment by russcam** [comment]
@kyakhta Please take a look at the new `Attachment` type in NEST 2.3.3 and let me know if it helps here
