### ISSUE TITLE
Building fails if space in UserProfile path

### ISSUE THREAD

**Issue by Romanx** [elastic/elasticsearch-net#1829]
When trying to build the repository it failed to find DNX and DNVM as i had a space in my UserProfilePath

Relevant Lines 
- [1](https://github.com/elastic/elasticsearch-net/blob/master/build/scripts/Paths.fsx#L209)
- [2](https://github.com/elastic/elasticsearch-net/blob/master/build/scripts/Paths.fsx#L220)

**Comment by gmarz** [comment]
Closed via #1830
