### ISSUE TITLE
DeleteIndexAsync throws a Object reference not set to an instance of an object Error

### ISSUE THREAD

**Issue by jsangari-ssat** [elastic/elasticsearch-net#1834]
ES Version: 1.7.1
NEST/Elasticsearch.Net Version: 2.0.2

If the index does not exists and i try to delete it using the async api
``
var indexName = new IndexName();
indexName.Name = "foos";
var response = await client.DeleteIndexAsync(indexName); 
``
same thing with the low level api:
``
            var response = await _esClient.IndicesDeleteAsync<MemoryStream>(indexName);
``
Please note there is no problem with the Sync (DeleteIndex) API

**Comment by Mpdreamz** [comment]
`NEST 2.x` only works with `Elasticsearch 2.x` and up, are you also seeing this behaviour using `Elasticsearch 2.x` ?

Our integration tests for [DeleteIndex](https://github.com/elastic/elasticsearch-net/blob/master/src/Tests/Indices/IndexManagement/DeleteIndex/DeleteIndexApiTests.cs) only test the happy flow, so we should definitely update this.

**Comment by jsangari-ssat** [comment]
Hi Martijn,

Thanks for the quick reply . No I am not seeing this behavior with ES 2.X .

So NEST 1.x only works with 1.x and NEST 2.x only works with ES 2.X ?

**Comment by Mpdreamz** [comment]
> So NEST 1.x only works with ES 1.x and NEST 2.x only works with ES 2.X ?

That is correct.

**Comment by jsangari-ssat** [comment]
Thanks for clarifying, It just becomes a chicken and an egg problem when we think of upgrading...

**Comment by Mpdreamz** [comment]
@jsangari-ssat sorry to hear this puts you in a bit of a bind, please let us know if you get stuck and could use a hand!
