### ISSUE TITLE
Attachment field not mapped correctly in Nest 2

### ISSUE THREAD

**Issue by gerosalesc** [elastic/elasticsearch-net#1837]
Trying to map an attachment attribute like this:

    client.Map<Case>(m => m.UpdateAllTypes());

With this classes and mapping definitions:

    [ElasticsearchType(Name = "cases")]
	public class Case
	{
		public string Author { get; set; }
		public string CaseName { get; set; }
		[Attachment(Store = true)]
		public Attachment File { get; set; }
	}

	public class Attachment
	{
		[String(Name = "_content")]
		public string Content { get; set; }

		[String(Name = "_content_type")]
		public string ContentType { get; set; }

		[String(Name = "_name")]
		public string Name { get; set; }

	}

Here is the generated mapping

    "mappings": {
      "cases": {
        "properties": {
          "author": {
            "type": "string"
          },
          "case_name": {
            "type": "string"
          },
          "file": {
            "properties": {
              "_content": {
                "type": "string"
              },
              "_content_type": {
                "type": "string"
              },
              "_name": {
                "type": "string"
              }
            }
          }
        }
      }

Yep, there is `"type": "attachment"` missing down the file property definition.

Using Elasticsearch 2.2, Nest 2.0.2, Mono / .Net 4.5

As seen in [SO](http://stackoverflow.com/questions/35412657/attachment-field-not-mapped-correctly-in-nest-2)

**Comment by Mpdreamz** [comment]
Thanks for reporting @gerosalesc we are all travelling and attending [elasticon](https://www.elastic.co/elasticon/conf/2016/sf) the coming days so we might take a little longer to investigate. Thanks for submitting an issue, always much appreciated :+1:

**Comment by russcam** [comment]
I've been making some changes in this area in https://github.com/elastic/elasticsearch-net/commit/8ad3032def4cfe6ecfff5d21887e3feb1ccb6dc5 and PR https://github.com/elastic/elasticsearch-net/pull/1827. I feel it would be a good idea to install both the mapper attachment and murmur3 plugins as part of spinning up an Elasticsearch node for integration tests, since we support both out of the box

**Comment by Mpdreamz** [comment]
++ agreed

**Comment by gerosalesc** [comment]
@russcam @Mpdreamz  Thanks for your answers despite the elasticon. I have a couple of questions regarding this: is the decorator mapping working for the attachment type? If it's not, How would I map my Attachment attribute manually? I have seen the unit test but I would better understand if you have an example please :), pls.

**Comment by gerosalesc** [comment]
@russcam according to the [unit test](https://github.com/elastic/elasticsearch-net/commit/8ad3032def4cfe6ecfff5d21887e3feb1ccb6dc5) something [like this](http://stackoverflow.com/questions/35608490/mapping-attachment-type-manually-elasticsearch-2-and-nest2) should be working but is giving me a horrible null reference at runtime, do you know why? maybe I am doing something wrong.

**Comment by russcam** [comment]
@gerosalesc it's probably the same issue as #1826. I'm working on a fix for this including examples, that will go into the next release.

**Comment by gerosalesc** [comment]
@russcam Thanks for the reply. I tried your branch fix/mappings and the original decorator mapping and it's generating the mappings properly (or at least it seems), I will validate more carefully tomorrow. Good job buddy!

**Comment by gmarz** [comment]
Closed via #1827
