### ISSUE TITLE
UpdateIndexSettings example

### ISSUE THREAD

**Issue by zissop** [elastic/elasticsearch-net#1838]
Due to out of date documentation for Nest v2, is it possible to post a full working example of UpdateIndexSettings?

I tried the following but don't know what to pass on the last commented line.

var index = "products";
            Nest.Indices indices = index;

            client.GetIndexSettings(new GetIndexSettingsRequest(indices));

            IndexSettings a = new IndexSettings
            {
                Analysis = new Analysis
                {
                    Analyzers = new Analyzers
                    {
                        { "greek_fg", new CustomAnalyzer()
                            {
                                Filter = new [] { "greek_lowercase", "greek_lowercase2", "greek_stop"},
                                Tokenizer = "icu_tokenizer"
                            }
                        },
                         { "greek_fg2", new CustomAnalyzer()
                            {
                                Filter = new [] { "greek_lowercase2"},
                                Tokenizer = "keyword"
                            }
                        },
                          { "greek_fg3", new CustomAnalyzer()
                            {
                                Filter = new [] { "greek_lowercase", "greek_stemmer", "greek_stop"},
                                Tokenizer = "icu_tokenizer"
                            }
                        }
                    },

                }
            };

            a.Analysis.TokenFilters = new TokenFilters();
            a.Analysis.TokenFilters.Add("greek_stop", new StopTokenFilter() { StopWords = new StopWords("_greek_") });
            a.Analysis.TokenFilters.Add("greek_lowercase2", new LowercaseTokenFilter() { Language = "greek" });
            a.Analysis.TokenFilters.Add("greek_stemmer", new StemmerTokenFilter() { Language = "greek" });
            a.Analysis.TokenFilters.Add("greek_lowercase", new IcuTokenFilter() { Language = "greek" });

            //client.UpdateIndexSettings(indices);

**Comment by Mpdreamz** [comment]
https://github.com/elastic/elasticsearch-net/blob/master/src/Tests/Indices/IndexSettings/UpdateIndicesSettings/UpdateIndexSettingsApiTests.cs#L33

You have to instantiate a:

```csharp
new UpdateIndexSettingsRequest(indices) 
{
    IndexSettings = a
}
```

and pass that to `UpdateIndexSettings()`

**Comment by zissop** [comment]
Thanks very much!

**Comment by hyankov** [comment]
As mentioned in another ticket this doesn't work for me.

I am trying to clear the refresh_interval on an index. The documentation says that setting it to NULL should return it to the default.

`client.UpdateIndexSettings(new UpdateIndexSettingsRequest("some_index_name") { IndexSettings = new IndexSettings() { RefreshInterval = null } });`

generates PUT request with empty body:
`https://cluster/some_index_name/_settings?pretty=true`

This gets rejected with:
```
{
  "error" : {
    "root_cause" : [ {
      "type" : "action_request_validation_exception",
      "reason" : "Validation Failed: 1: no settings to update;"
    } ],
    "type" : "action_request_validation_exception",
    "reason" : "Validation Failed: 1: no settings to update;"
  },
  "status" : 400
}
```

What am I doing wrong?
