### ISSUE TITLE
Can't use connector.GetClient().Raw.Bulk()

### ISSUE THREAD

**Issue by imranazad** [elastic/elasticsearch-net#1840]
I've been previously using connector.GetClient().Raw.Bulk() to post raw json to Elastic to index documents, I've recently upgraded to 2.0.2 and the .Raw method on the low level client doesn't seem to be available anymore. Can you please advise?

**Comment by Mpdreamz** [comment]
`.Raw` is now `.LowLevel` hope that helps! :smile:

**Comment by imranazad** [comment]
@Mpdreamz Lool! Thank you so much!
