### ISSUE TITLE
SniffResponse can not parse http_address with inet[]

### ISSUE THREAD

**Issue by sergfed** [elastic/elasticsearch-net#1842]
I've got exception in SniffResponse.ParseToUri - "Can not parse http_address" - with value inet[/11.11.11.11:9200] returned elastic v1.7.3
Regex AddressRe `^((?<fqdn>[^/]+)/)?(?<ip>[^:]+):(?<port>\d+)$`
can't match this address because after port there is square bracket, but not end of line.

**Comment by Mpdreamz** [comment]
`inet[/11.11.11.11:9200]` is the old format returned in `Elasticsearch 1.x`.

NEST 2.x (and it sniffer) only works with  `Elasticsearch 2.x` and up
