### ISSUE TITLE
Mapping interface

### ISSUE THREAD

**Issue by CocaColaBear** [elastic/elasticsearch-net#1843]
Hi all!
Newtonsoft.JSON has attribute 
`[JsonConverter(typeof(ConcreteTypeConverter<Model>))]`
there is an equivalent Elasticsearch.NET?).
Like this:
```
public interface IFoo
{
  ....
}

public class Foo : IFoo
{
    ....
}

public class Bar
{
    [[JsonConverter(typeof(ConcreteTypeConverter<Foo>))]]
    // Equal in Elasticsearch.net??? For type conversion
    IFoo Foo { get; set; }
}
```

**Comment by russcam** [comment]
If you're using NEST with the default serializer then it will be using Newtonsoft.Json (Json.Net) and so a custom json converter specified by `JsonConverterAttribute` should work. Although NEST currently uses Json.Net, we try to keep the external API serializer agnostic.
