### ISSUE TITLE
ElasticSearchClientException returns insufficient information

### ISSUE THREAD

**Issue by jonyadamit** [elastic/elasticsearch-net#1845]
The real information that could help solve issues is not given in some circumstances.
For instance, look at the following response from ES:

![elastic1](https://cloud.githubusercontent.com/assets/796507/13102170/8d5912dc-d554-11e5-9a66-e32b1f18cb7f.png)

The most important piece of information resides under the *caused_by* element.

`ElasticSearchClientException` on the other hand returns the following information:

![elastic2](https://cloud.githubusercontent.com/assets/796507/13102273/5a9f989c-d555-11e5-8883-d4f365e3900a.png)

So solving issues becomes very hard this way.
Note that this information doesn't exist anywhere in the exception: not under `DebugInformation` and not anywhere else.

**Comment by jonyadamit** [comment]
@russcam @gmarz @Mpdreamz Any thoughts on this? Not sure about the correct way to include this information.

**Comment by russcam** [comment]
@jonyadamit We'll look to include this when parsing a `ServerError` from the response; We've all been at Elasticon this week but will look at this shortly. Thanks again for reporting :+1:

**Comment by jonyadamit** [comment]
:+1: great :smile:
