### ISSUE TITLE
Migration query from v1 to v2

### ISSUE THREAD

**Issue by SeanFarrow** [elastic/elasticsearch-net#1847]
Hi,

I'm migrating an application from v1 to v2 of nest.
I have the following poco class:

```csharp
    public class Post
    {
        public int UserId { get; set; }
        public DateTime PostDate { get; set; }
        public string PostText { get; set; }
    }
```

I'm trying to use the CreateIndexDescriptor to create the index and map the type.
I've got the following code currently:

```csharp
            CreateIndexDescriptor cid = new CreateIndexDescriptor("my_blog");
            cid.Mappings(
                x =>
                    {
                        x.Map < Post(x =>x.AutoMap()); 
                        //Problem1;
                    });
                        cid.Settings(
                            x =>
                                {
                                    x.NumberOfReplicas(1);
                                    x.NumberOfShards(1);
                                //Problem2;
                                });
```

My first issue is how to I return a IPromise<IMappings>> from the lambda that allows me to control the mappings? Secondly, how do I return an IPromise<IIndexSettings>>  from the lambda that lets me control the index settings.

Finally, is ther a migration guide covering this sort of this?

Any help appreciated.
Kind regards
Sean.

**Comment by Mpdreamz** [comment]
Sorry for the late reply @SeanFarrow 

If you are using a multiline lambda you simply `return` the parameter of the lambda. 

So both your problems can be solved by simply:

```csharp
return x;
```

If you use a single line lambda the return is implicit.

The closest thing we have to a migration guide is our breaking changes documentation:

https://github.com/elastic/elasticsearch-net/tree/master/docs/2.0-breaking-changes

Hope this helps.
