### ISSUE TITLE
Default property names ignore case of the first letter of the property name

### ISSUE THREAD

**Issue by shonaw** [elastic/elasticsearch-net#1848]
If I have classes with properties who's first letter is a capital (common in .Net programming) and when I put that into elastic search the property names are adjusted to start with a small case letter.  

I know I can add [ElasticProperty(Name ="MyProperty) however I'd prefer not to do that because it covers alot of properties and it means having Elastic references deep in my code which I want to keep data store agnostic.

I also tried adding [JsonProperty("MyProperty")] which is better because it isn't data store specific and that works for insert but when I build queries with that property it reverts back to "myProperty".

Is there any way to get NEST/Elastic search to honour the case of my properties?  Maybe a configuration setting or something?

I could also just bend to requirement that the first letter must be lower case, I'm just hoping for another solution.

**Comment by russcam** [comment]
Hey @shonaw, the default convention in NEST is to camel case field/property names to align with the general naming convention in JavaScript/json. 

This can be changed though by passing a `Func<string, string>` to `DefaultFieldNameInferrer` to modify how field names should be inferred

```c#
var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
var connectionSettings = new ConnectionSettings(pool)
    // delegate passed determines how field names are inferred
	.DefaultFieldNameInferrer(f => f);

```

The [field inference documentation](https://github.com/elastic/elasticsearch-net/blob/master/docs/asciidoc/ClientConcepts/HighLevel/Inferrence/FieldNames/FieldInference.doc.asciidoc) has more examples of the control you have over how POCO property names are inferred for queries and mappings

**Comment by shonaw** [comment]
Hi Russ,

Thank you, that’s very helpful!  I’ll try it out.

Shona
