### ISSUE TITLE
Could not load type 'Nest.Time' from assembly 'Nest' on Mono

### ISSUE THREAD

**Issue by maeserichar** [elastic/elasticsearch-net#1850]
Running mono 4.0.4.1 on Centos 7 and Nest 2.0.2. I´m having the following error when creating a Scroll query:

`Could not load type 'Nest.Time' from assembly 'Nest, Version=2.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'.`

Same code runs ok on Windows and with previous versions of Nest.

**Comment by maeserichar** [comment]
It turns to be an "rogue" copy of the old dll in our environment, so it looks like there is no problem...

Sorry guys!

**Comment by Mpdreamz** [comment]
No problem, thanks for reporting back!
