### ISSUE TITLE
Suggestion API

### ISSUE THREAD

**Issue by zissop** [elastic/elasticsearch-net#1854]
Hello

Again due to lack of documentation i would like to know more for the suggestion API. For example I have the following code:

```csharp
var suggestRequest = new SuggestRequest
            {
                Suggest = new SuggestContainer
                {
                    { "my-completion-suggest", new SuggestBucket
                    {
                        Text = "text1",
                        Completion = new CompletionSuggester
                        {
                            Context = new Dictionary<string, object> { { "color", "text2" } },
                            Fuzzy = new FuzzySuggester
                            {
                                Fuzziness = Fuzziness.Auto,
                                MinLength = 1,
                                PrefixLength = 2,
                                Transpositions = true,
                                UnicodeAware = false
                            },
                            Analyzer = "simple",
                            Field = "products.suggester2",
                            ShardSize = 7,
                            Size = 8
                        }
                    } },
                }
            };
```

1. What is the meaning of text1, text2 values? Text is the string we have to pass? Context is mandatory?
2. How we perform a Suggest request? What is the syntax on the above example?

Best regards
John

**Comment by andersosthus** [comment]
Hi,

That looks like a Context Suggester (https://www.elastic.co/guide/en/elasticsearch/reference/2.0/suggester-context.html)

```Context``` is the value you want to limit the suggest on.
```Text``` is the input value for suggest, i.e. the value you are wanting suggest for.

For doing a suggest, I belive the above would be something like this (note, I prefer the fluent syntax):
```
var descriptor = new SearchDescriptor<T>()
    .Suggest(s => s
        .Completion("my-completion-suggest", c => c
            .Text("text1")
            .Context(con => con.Add("color", "text2"))
            .Fuzzy(f => f
                .Fuzziness(Fuzziness.Auto)
                .MinLength(1)
                .PrefixLength(2)
                .Transpositions(true)
                .UnicodeAware(false))
            .Analyzer("simple")
            .Field("products.suggester2")
            .ShardSize(7)
            .Size(8)));

var result = client.Search<T>(descriptor);
```

**Comment by zissop** [comment]
Thanks very much. After digging around i found a working solution, i put it here for reference for anyone have the same concern and do not want to use the fluent syntax:

var suggestRequest = new SuggestRequest
            {
                Suggest = new SuggestContainer
                {
                    { "my-completion-suggest", new SuggestBucket
                    {
                        Text = "test string",
                        Completion = new CompletionSuggester
                        {
                            Fuzzy = new FuzzySuggester
                            {
                                Fuzziness = Fuzziness.Auto,
                                MinLength = 1,
                                PrefixLength = 2,
                                Transpositions = true,
                                UnicodeAware = false
                            },
                            Analyzer = "greek_fg",
                            Field = "suggester2",
                            Size = 10
                        }
                    } },
                }
            };

            var suggestResults = client.Suggest(suggestRequest);
