### ISSUE TITLE
Issue when calling DeleteByQuery

### ISSUE THREAD

**Issue by TonyWoo** [elastic/elasticsearch-net#1855]
I'm using the Nest 2.0.2.  When I run below code. It shows:"Invalid NEST response built from a unsuccesful low level call on DELETE:". Is this query correct? Thanks in advance.

```
client.DeleteByQuery<Document>(
                Indices.Index("documentindex"),
                Types.Type("document" ),
                q => q               
                .Query(rq => rq
                    .Term(f => f.DocumentType, 1)
                )
            );
```

**Comment by russcam** [comment]
Hey @TonyWoo, what version of Elasticsearch are you running NEST 2.0.2 against? Have you installed the [Delete by query plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/2.0/plugins-delete-by-query.html)? It's needed for delete by query functionality for Elasticsearch 2.x

**Comment by TonyWoo** [comment]
Hi @russcam, thank you very much. After we instaled the delete by query plugin, it works. Thanks again.

**Comment by swaroopgudipalli** [comment]
i cant find delete_by_query plugin in http://localhost:9200/_nodes/_all/plugins
tried restarting elasticsearch service
