### ISSUE TITLE
Limit NEST 1.7.1 dependency to Elasticsearch.Net < 2.0.0

### ISSUE THREAD

**Issue by hoonzis** [elastic/elasticsearch-net#1861]
It seems that the 1.7.1 NEST package which is the last stable one depends on Elasticsearch.Net (>= 1.7.1).

I am not sure about nuget itself, but when using paket, any time you update you will get the highest available release that satisfies the criteria - so it will be > 2.0.0 which will break the build.

I believe this should be limited.

**Comment by niemyjski** [comment]
@Mpdreamz Any idea on the timeframe for 1.7.2?

**Comment by Mpdreamz** [comment]
@niemyjski this week, finally :smile:
