### ISSUE TITLE
SniffingConnectionPool IP address resolved from domain name

### ISSUE THREAD

**Issue by grbinho** [elastic/elasticsearch-net#1865]
Hi,

I noticed that if `SniffingConnectionPool` is used with a URI that is a domain name that can point to a NATed IP address or NLB, requests will always result in a timeout. As far as I was able to see, `SniffingConnectionPool` will use addresses retrieved from cluster settings, which obviously don't have to match the one DNS resolves.

I'm guessing that that's the intended behavior and that in this case we should use `SingleNodeConnectionPool`.

What I wanted to know is if it makes sense, that instead of waiting for a timeout client throws an exception when it sees that IP address resolved from domain name does not match addresses returned from cluster settings.

Ivan

**Comment by Mpdreamz** [comment]
You can configure elasticsearch to use a separate `http.publish_host` for external reachable hosts, this will then be reported as the hostname in the cluster call we use for sniffing.

If you are not able to set this you can use the `StaticConnectionPool` instead to still have failover and round robin from your client application.
