### ISSUE TITLE
How can I retrieve the document Id from IMultiTermVectorsResponse?

### ISSUE THREAD

**Issue by crjackso** [elastic/elasticsearch-net#1866]
Hi,

  I'm having trouble determining how I can retrieve the corresponding document ids in a IMultiTermVectorsResponse instance.  This issue is similar to the one listed in issue #1484.  A solution was added for this issue, but it looks like the solution may have been removed as part of a set of breaking changes due to many version updates since then.  

  I'm using NEST version 2.02.  

    ` var termVectorResponse = ElasticClient.MultiTermVectors(new MultiTermVectorsRequest(IndexName, Type)
            {          
                Documents = documentIds.Select(id => new MultiTermVectorOperation<Document>(id)
                {
                   ...
                })
            });
            termVectorResponse.Documents.Select(termVectorsResponse =>
            {
                // how do I get the document Id
                termVectorsResponse.DocId = ???
            }); `

**Comment by russcam** [comment]
Hey @crjackso, thanks for reporting. This looks like it's been missed and will make it into the next release  :+1:

**Comment by crjackso** [comment]
Thanks! Looks good.
