### ISSUE TITLE
How can I filter terms in a term vector request?

### ISSUE THREAD

**Issue by crjackso** [elastic/elasticsearch-net#1868]
Given the code listed below, how can I filter the terms returned from a term vector request as a means of ensuring no words with a frequency greater than x are returned?  The ElasticSearch (ES) feature I'm trying to play around with is documented on the [ES website](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/docs-termvectors.html#docs-termvectors-terms-filtering).  
Here's the code snippet:
    
     var termVectorResponse = ElasticClient.MultiTermVectors(new MultiTermVectorsRequest(IndexName, Type)
            {                          
                Documents = documentIds.Select(id => new MultiTermVectorOperation<Document>(id)
                {
                    FieldStatistics = true,
                    Payloads = true,
                    TermStatistics = true,
                    Positions = true,
                    Offsets = true,
                    Type = Type,
                    Index = IndexName           
                })      
            });

How can I alter this code to specify term filters like _max_num_terms_ and _min_term_freq_?  I'm using ES version 2.02.  Thanks for the help!

**Comment by gmarz** [comment]
Looks like we're missing the filter option.  We'll add this for the next release.  Thanks for reporting!
