### ISSUE TITLE
Normalization Token Filter

### ISSUE THREAD

**Issue by Reonekot** [elastic/elasticsearch-net#1873]
I can't find a way to add the a Normalization Token Filter:
https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-normalization-tokenfilter.html

Am I missing how to add this (.Settings.Analysis.TokenFilters) or is this missing? If it's missing, I hope you'll consider adding it adding it in the future.

**Comment by gmarz** [comment]
It's not missing, it's just that the built in normalization token filters don't have any options to configure.

You can just add them to your list of token filters when building your custom analyzer.

For instance:

```csharp
.Analyzers(analyzers => analyzers
	.Custom("myCustom", a => a
		.Filters("arabic_normalization")
		.Tokenizer("whitespace")
	)
)
```
