### ISSUE TITLE
Custom sorting

### ISSUE THREAD

**Issue by CocaColaBear** [elastic/elasticsearch-net#1879]
Hi all!
Can you help me about add custom sorting to SortDescriotor? For example with implementing interface IComparer<T> ?

**Comment by CocaColaBear** [comment]
Or can you help me, how make order by multiple fields and set one of fields to top (primary sort).
Equalent to OrderBy and ThenBy in LINQ

**Comment by gmarz** [comment]
@CocaColaBear have a look at the [SortUsageTests](https://github.com/elastic/elasticsearch-net/blob/master/src/Tests/Search/Request/SortUsageTests.cs#L72).  There's an example of sorting on multiple fields using both the fluent (`SortDescriptor`) and object initializer API.

Also refer to the Elasticsearch documentation on [sorting](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/search-request-sort.html).
