### ISSUE TITLE
Aggregations default field value

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#1882]
I'm trying to generically build up aggregation queries and one thing I need to do is specify a default value of 0 for missing fields on my min,max and average aggregates. In 1.7.1, I don't see the missing property and when I specify a script I can't seem to set the value properly.

```
string defaultValueScript = $"_value != null ? _value : 0";
switch (field.Type) {
  case FieldAggregationType.Average:
    aggregation.Average(field.Key, a => a.Field(field.Field).Script(defaultValueScript));
```

Any ideas on how to accomplish this while still working once we migrate to 2.x

**Comment by gmarz** [comment]
`_value` will be of type double, so I don't think you can null check on it.  I'm guessing that's why your script isn't working.

Omit the field from the aggregation and try this:

```csharp
string defaultValueScript = $"doc['{field.Field}'].empty ? 0 : doc['{field.Field}'].value";
switch (field.Type) {
  case FieldAggregationType.Average:
    aggregation.Average(field.Key, a => a.Script(defaultValueScript));
```

Let me know if that works?

**Comment by niemyjski** [comment]
Thanks!! I'll try this out. What would you recommend doing for date fields on min and max ? Looking for something generic that works for numbers and dates for some aggregations. Like maybe leave null if it's not a numeric type

**Comment by niemyjski** [comment]
@gmarz, Also I was thinking more about this and my field is sometimes the index name. Will this still work as a doc indexer?

**Comment by gmarz** [comment]
Sorry for the delayed response.  @niemyjski did this work for you?

**Comment by niemyjski** [comment]
I haven't dug deep into it or saw if this works. Right now all my code paths limit it to a field I know where the index name matches the field name.

**Comment by Mpdreamz** [comment]
`doc[]` allows you to reference metadata fields such as `_index` too. closing this because there is nothing actionable.

**Comment by niemyjski** [comment]
But what if you don't know if it's a field name or index? In our case it's user supplied.

**Comment by niemyjski** [comment]
bump
