### ISSUE TITLE
Problem with NEST + ASP.NET5

### ISSUE THREAD

**Issue by senj** [elastic/elasticsearch-net#1885]
If I try to use NLog XML Configuration, I get this error: InnerException = {"Could not load type 'Elasticsearch.Net.Serialization.IElasticsearchSerializer' from assembly 'Elasticsearch.Net, Version=2.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'.":"Elasticsearch.Net.Serialization.IElasticsearchSerializer"}

I updated to 2.0.4 and now even .AddMVC() doesn't work anymore!

This seems to crash with the ElasticSearch NLog target.
Both use Elasticsearch.Net

**Comment by gmarz** [comment]
What version were up upgrading from?

Can you try clearing out your bin folders in case there's an old reference hanging around?

**Comment by gmarz** [comment]
No response; closing for now.  Please re-open @senj if this is still an issue.
