### ISSUE TITLE
ArgumentExceptions in FieldResolver bubble out as UnexpectedElasticsearchClientExceptions

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch-net#1889]
The underlying exception is an [ArgumentException](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/CommonAbstractions/Infer/Field/FieldResolver.cs#L56) and it should bubble out as an `ElasticsearchClientException`.  The problem lies in the fact that `.Resolve()` is called later in the pipeline.

**Comment by russcam** [comment]
As per discussion earlier, we will defer the field naming conventions to Elasticsearch; this way, if Elasticsearch's naming conventions change we do not also need to reflect these changes in the client, duplicating effort.

I will add tests to assert that the server error returned indicates the cause of the error.

**Comment by russcam** [comment]
We still potentially have a problem with [`ArgumentException` being thrown here](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/CommonAbstractions/Infer/Field/FieldResolver.cs#L77)

**Comment by gmarz** [comment]
Hmm...yea.  Maybe throwing a `ResolveException` is the better choice then.  

/cc @Mpdreamz

**Comment by gmarz** [comment]
Going to bump this for now and release 2.0.5 without it.  It's low priority anyway.

**Comment by Mpdreamz** [comment]
I kinda like `ResolveException` allows us to keep the door open to introduce client side validation of indexnames and fieldnames when these crystalize more in elasticsearch itself. 

I would like still throw one for `IndexName`'s with uppercase in them since its such a common mistake.

**Comment by russcam** [comment]
Reopening as `ResolveException` has been reverted from 2.1.0

**Comment by gmarz** [comment]
Bumped this again.

**Comment by gmarz** [comment]
Closing, as I don't think there's anything actionable here.  We can revisit again for 6.x if necessary.
