### ISSUE TITLE
SuggestOption and Payload

### ISSUE THREAD

**Issue by senj** [elastic/elasticsearch-net#1891]
Hello,

I have a question about the payload of a SuggestOption.
I'm using the Term suggestion and get some Suggest in my result.

The .Text property is filled with the corrected value, but Payload is null.
I expect the payload to be the data of the corrected object?
How/where can I get/define this payload?

**Comment by gmarz** [comment]
Hey @senj , payloads only apply when using the completion suggester, and they do not correspond to any document in your index.  Instead, they are a way of associating arbitrary data with a completion suggestion and must be supplied at indexing time when you're building your suggestions.

See the elasticsearch docs on the [completion suggester](https://www.elastic.co/guide/en/elasticsearch/reference/2.2/search-suggesters-completion.html) for more info.

As a side note, the completion suggester has gone through some major improvements for the next major release of Elasticsearch.  Payloads are going away and you'll be able to correlate actual documents in your index with completion suggestions.
