### ISSUE TITLE
NEST 2.x documentation?

### ISSUE THREAD

**Issue by andrewrimmer** [elastic/elasticsearch-net#1893]
What is the plan with updating the documentation for version 2.x?

Is it available already, and will it replace the existing content or do you plan to have documentation for each major version?

**Comment by Mpdreamz** [comment]
Our new documentation is part of the Tests project, we use roslyn to generate asciidoc and these will be exported here: https://github.com/elastic/elasticsearch-net/tree/master/docs/asciidoc

That folder will then serve as the source of our documentation on elastic.co. The azurewebsites will either redirect or stay up with a big banner. 

We will keep a version on elastic.co for each major version we support (-1 typically) starting from version 2.0. 

We hope to have the new docs up within 2 weeks.

Hope this explains where we are at :smile:

**Comment by andrewrimmer** [comment]
Brilliant, just what I was after!
