### ISSUE TITLE
Documents not found with a MultiGet  

### ISSUE THREAD

**Issue by EricKeij** [elastic/elasticsearch-net#1895]
I create a request like this:

```
var request = new MultiGetRequest()
{
 Documents = new List<IMultiGetOperation>()
 {
   new MultiGetOperation<MyType>("existing-id") { Index = "my-index" },
   new MultiGetOperation<MyType>("non-existing-id") { Index = "my-index" }
 }
}

var response = ElasticClient.MultiGet(request);
```
This results in two Documents both having the .Found property false and an empty .Source. 

To ensure the request is builded correctly I pasted the generated JSON request into Sense and I do get the expected result (first document found, second not). Is this a bug or am I missing something here?

**Comment by russcam** [comment]
@EricKeij, what version of NEST and what version of Elasticsearch are you using?

**Comment by EricKeij** [comment]
@russcam, I'm using NEST 2.0.4 with ES 2.2

**Comment by EricKeij** [comment]
Nevermind... I have multiple instances of ES running and was connecting to the wrong instance.

**Comment by russcam** [comment]
@EricKeij cool, glad you found the issue :smile:
