### ISSUE TITLE
IsVerbatim not working with multiple queries

### ISSUE THREAD

**Issue by EricKeij** [elastic/elasticsearch-net#1898]
Following up on #1872. 

IsVerbatim works fine on a single TermQuery but i can't seem to get it to work when combining mutiple queries. 

```
var container = new QueryContainer(new TermQuery
{
 Field = "surname",
 Value = ""
});

container &= new TermQuery
{
 Field = "age",
 Value = "10"
}

((IQueryContainer)container).IsVerbatim = true;
ElasticClient.Search<MyType>(new SearchRequest { Query = container });
```

This results in
```
POST /<index>/<type>/_search
{
   "query": {
      "term": {
         "age": {
            "value": "10"
          }
       }
    }
}
```

While I expect
```
POST /<index>/<type>/_search
{
   "query": {
      "bool": {
         "must": [
         {
            "term": {
               "surname": {
                "value": ""
             }
           }
         },
         {
            "term": {
                "age": {
                "value": "10"
                 }
             }
          }
       ]
    }
  }
}
```

**Comment by gmarz** [comment]
Thanks @EricKeij 

This also looks to be an issue using the fluent API as well.  I'm working on a fix for #1876 in [this branch](https://github.com/elastic/elasticsearch-net/tree/fix/verbatim-queries) and will make sure this gets covered as well.

**Comment by gmarz** [comment]
Pushing this to 2.2.

**Comment by gmarz** [comment]
It's not possible to cascade `IsVerbatim` and `IsStrict` from the container level (see the discussion in #2021), so this isn't going to work as expected in your initial example @EricKeij.  

However, #2021 now makes it possible to set `IsVerbatim` and `IsStrict` at the individual query level for both the OIS and fluent APIs...which is the only way to achieve this behavior:

```
var container = new QueryContainer(new TermQuery
{
 IsVerbatim = true,
 Field = "surname",
 Value = ""
});

container &= new TermQuery
{
 IsVerbatim = true,
 Field = "age",
 Value = "10"
}
```

**Comment by EricKeij** [comment]
Thanks @gmarz 

This solution works fine for us.
