### ISSUE TITLE
Incorrect method xmldoc comments for Nest.FilterDescriptor<T>.HasParent<K>

### ISSUE THREAD

**Issue by v-karbovnichiy-parc** [elastic/elasticsearch-net#1905]
Method doc summary is a copy-paste from summary of `HasChild<K>` (selected lines are incorrect):

![image](https://cloud.githubusercontent.com/assets/16113971/13698890/66fb94ea-e790-11e5-99d3-7b4c1dbe460d.png)

**Comment by russcam** [comment]
@v-karbovnichiy-parc, Which version of NEST are you using?

**Comment by v-karbovnichiy-parc** [comment]
NEST 1.7.1

**Comment by russcam** [comment]
Thanks; this is fixed in NEST 2.x but [looks like it's still there in the 1.x branch](https://github.com/elastic/elasticsearch-net/blob/1.x/src/Nest/DSL/Query/QueryDescriptor.cs#L455). I'll fix this now for the next release of 1.x.

Thanks again for reporting :+1:

**Comment by v-karbovnichiy-parc** [comment]
Originally I reported about [this code](https://github.com/elastic/elasticsearch-net/blob/1.x/src/Nest/DSL/Filter/FilterDescriptor.cs#L575).

**Comment by russcam** [comment]
Thanks, fixed that too :smile:
