### ISSUE TITLE
NEST Allow Range queries on DateTime / DateTimeOffset fields

### ISSUE THREAD

**Issue by guillaume86** [elastic/elasticsearch-net#1907]
Since updating NEST to 2.x, the api only support double as a parameter for range queries, would that be possible to add back support for DateTime?

At the moment I use a QueryString range as a workaround.

**Comment by russcam** [comment]
@guillaume86, Take a look at the [`DateRange` methods](https://github.com/elastic/elasticsearch-net/blob/2424248c0a0b402fb716fa27bd3b7a30c117ff83/src/Nest/QueryDsl/Abstractions/Container/QueryContainerDescriptor.cs#L156); They take a [`DateMath`](https://github.com/elastic/elasticsearch-net/blob/master/docs/asciidoc/CommonOptions/DateMath/DateMathExpressions.doc.asciidoc) type that has conversions from `DateTime`, `string` as well as other date math that the [`range` query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html#ranges-on-dates) supports

**Comment by guillaume86** [comment]
Ha thanks a lot I missed that.

**Comment by russcam** [comment]
No worries :thumbsup:
