### ISSUE TITLE
Can't connect to a server using Elasticsearch.Net

### ISSUE THREAD

**Issue by fandrei** [elastic/elasticsearch-net#1910]
I'm using this code:

```
			var settings = new ConnectionConfiguration(new Uri("http://SomeHost/"));
			settings.DisableDirectStreaming();

			var client = new ElasticLowLevelClient(settings);

			var query = File.ReadAllText("query_all.txt");
			var response = client.Search<object>(query);
```

And getting:

```
# OriginalException: System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in c:\code\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 138
# Request:
{
    "query" : {
        "match_all" : {}
    },
    "size":0
}

# Response:
<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
```

Elasticsearch.Net: 2.0.4
Elasticsearch server: 2.2.0

**Comment by russcam** [comment]
It looks like it's attempting to connect as you're getting a 400 Bad Response back. Have you tried running a web debugging proxy such as [Fiddler](https://www.telerik.com/download/fiddler) to see what the request and response look like?

**Comment by fandrei** [comment]
@russcam, why can't I just get these data from the library?
It's strange that it says "Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>", but I actually do call this method.

**Comment by gmarz** [comment]
@fandrei unfortunately there was a bug that caused us to discard the stream on bad responses, even if `DisableDirectStreaming` was set.  It's already fixed for the next release.  See https://github.com/elastic/elasticsearch-net/issues/1856 for details.

**Comment by fandrei** [comment]
This was a server side problem.

**Comment by Mpdreamz** [comment]
Appreciate the update @fandrei :+1:

**Comment by mitesh-diligencevault** [comment]
I'm still getting the same issue. I'm using 2.3.1 version. Could you please assist? @fandrei
