### ISSUE TITLE
Bool Must Terms always is Should (v2.0.4)

### ISSUE THREAD

**Issue by johnreaume** [elastic/elasticsearch-net#1915]
Example...

```c#
.MultiSearch(ms => ms
	.Search<PersonDocument>("people", s => s
		.Aggregations(agg => agg
			.Terms("skills.raw", term => term.Field(f => f.Skills.Suffix("raw")))
		)
		.Query(q => q
			.MultiMatch(qs => qs
				.Type(TextQueryType.MostFields)
				.Fields(f => f.Fields(options.Fields ?? _default))
				.Operator(Operator.Or)
				.Query(options.QueryString)) &&
			q.Bool(bl => bl
				.Must(m => 
					m.Terms(term => term
						.Field(field => field.Skills.Suffix("raw"))
						.Terms(options.Skills)
					)
				)
			)
		)
	)
)
```

Hover over m.Terms and it states

>     A query that match on any (configurable) of the provided terms. This is a
>     simpler syntax query for using a bool query with several term queries in
>     the should clauses.

In the previous version, we had a TermsExecution that allowed switching to Or/And
My only option is to loop thru all options.Skills (List<string>) and use Term
Just flagging this as a bug as when Bool Must is used it should run as Must and not Should

**Comment by russcam** [comment]
@johnreaume, this is not a bug; [**the `execution` option was deprecated in Elasticsearch 2.0**](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_query_dsl_changes.html#_literal_terms_literal_query_and_filter) so NEST 2.x simply reflects this change.

It should be relatively straightforward though to write a method that takes an IEnumerable of skills and returns an `IEnumerable<Func<QueryContainerDescriptor<T>, QueryContainer>>`. Something like this would do it

```c#
private IEnumerable<Func<QueryContainerDescriptor<PersonDocument>, QueryContainer>> Term(IEnumerable<string> skills)
{
	foreach (var skill in skills)
	{
		yield return m => 
			m.Term(term => term
				.Field(field => field.Skills.Suffix("raw"))
				.Value(skill)
			);
    }
}
```

And to use

```c#
	var options = new Options()
	{
		QueryString = "foo",
		Skills = new[] { "bar", "baz", "qux" }
	};
	var _default = new[] { "_default" };

	client.MultiSearch(ms => ms
		.Search<PersonDocument>("people", s => s
			.Aggregations(agg => agg
				.Terms("skills.raw", term => term.Field(f => f.Skills.Suffix("raw")))
			)
			.Query(q => q
				.MultiMatch(qs => qs
					.Type(TextQueryType.MostFields)
					.Fields(f => f.Fields(options.Fields ?? _default))
					.Operator(Operator.Or)
					.Query(options.QueryString)) &&
				q.Bool(bl => bl
					.Must(Term(options.Skills))
				)
			)
		)
	);
```

yields

```javascript
POST http://localhost:9200/_msearch?pretty=true 
{"index":"","type":"persondocument"}
{"aggs":{"skills.raw":{"terms":{"field":"skills.raw"}}},"query":{"bool":{"must":[{"multi_match":{"type":"most_fields","query":"foo","operator":"or","fields":["_default"]}},{"term":{"skills.raw":{"value":"bar"}}},{"term":{"skills.raw":{"value":"baz"}}},{"term":{"skills.raw":{"value":"qux"}}}]}}}
```

**Comment by johnreaume** [comment]
I understand the removal of TermsExecution as it was deprecated.
But was not expecting Terms to be only using Bool Should. 
What would occur if I ran Terms (with Must) in native Elastic Search?

Just my opinion that this should follow the same rules as the other calls

For anyone else...
Below is what I did to resolve as I have 8 additional Tags in my code
q.Bool(bl => {
	var filters = new List<Func<QueryContainerDescriptor<PersonDocument>, QueryContainer>>();
	// Can't use Terms in v2 as it's using Should
	if (options.Skills != null) {
		foreach (var skill in options.Skills) {
			filters.Add(f => f
				.Term(term => term.Field(field => field.Skills.Suffix("raw"))
				.Value(skill))
			);
		}
	}
	// Additional Terms (removed for this example)
	return bl.Must(filters);
})
