### ISSUE TITLE
question: elasticClient.Index(object) with inheritance uses super class as _type

### ISSUE THREAD

**Issue by rdehuyss** [elastic/elasticsearch-net#1916]
I am assuming I'm doing something wrong... I'm trying to Index some objects which inherits from a super class. For some reason, when I browse ES, the _type is the parent class and not the actually instantiated class.

What am I doing wrong? I tried the following mapping (which did not help):

```c#
_elasticClient.Map<DmfAWorkerDeclaration>(m => m
    .AutoMap()
    .Type(typeof(DmfAWorkerDeclaration)));

_elasticClient.Map<DmfAStudentDeclaration>(m => m
    .AutoMap()
    .Type(typeof(DmfAStudentDeclaration)));
```

This is how I want to index but does not work:
```c#
var indexResponse = await _elasticClient.IndexManyAsync(dmfADeclarations);
```

This works however, but is not optimal as I want to do a IndexMany:
```c#
foreach (var dmfADeclaration in dmfADeclarations)
{
      _elasticClient.Index(dmfADeclaration, idx => idx.Type(dmfADeclaration.GetType()));
}
```

What am I doing wrong? Google nor stackoverflow helped me :-)

**Comment by russcam** [comment]
@rdehuyss Is `dmfADeclarations` a collection of the base type of `DmfAWorkerDeclaration` and `DmfAStudentDeclaration`?

**Comment by rdehuyss** [comment]
@russcam that is correct. However, all instances in the collections are either a DmfAWorkerDeclaration or a DmfAStudentDeclaration. I'll need to double check  (not at work for the moment) but I even think that the base type is abstract.

**Comment by Mpdreamz** [comment]
This is expected behaviour. `IndexMany<T>(IEnumerable<T> documents)` is syntactic sugar for 

```csharp
.Bulk<T>(b=>b.IndexMany<T>(documents))
```

which is syntactic sugar over  

```csharp
.Bulk<T>(b=>documents.Foreach<T>(document=>b.Add(document))
```

Which means that `T` dictates the index and type name

If you want a somewhat shorter solution

```
client.Bulk(b=>b.IndexMany(dmfADeclarations, (bd, d) => bd.Type(d.GetType)));
```

The second parameter lambda gets called foreach `d` in `dmfADeclarations`
