### ISSUE TITLE
Bug in FieldStats indices request when LessThanOrEqualTo comparison is used on an IndexConstraint

### ISSUE THREAD

**Issue by cigma29** [elastic/elasticsearch-net#1917]
Using the LessThanOrEqualTo comparison filter on an IndexContraint of a FieldStats indices request will create a low-level API request with a GreaterThanOrEqualTo comparison instead.

You can see this at line 79 of Nest/Search/FieldStats/IndexConstraint.cs

`public IndexConstraintComparisonDescriptor LessThanOrEqualTo(string lte) => Assign(a => a.GreaterThanOrEqualTo = lte);`

**Comment by gmarz** [comment]
Thanks for reporting this @cigma29 :+1:
