### ISSUE TITLE
MaxRecursion when indexing data

### ISSUE THREAD

**Issue by tveyes** [elastic/elasticsearch-net#1918]
I'm trying to index some objects which have about 4 levels of depth. I've set up a mapping for the type like so:
```
           //Create the mapping for these objects
            var descriptor = new CreateIndexDescriptor("matches")
                .Mappings(ms => ms
                    .Map<CrompAudioMediaDetectionOrderMatch>(m => m
                        .AutoMap(10)
                    )
                );
            esClient.CreateIndex(descriptor);
```

I then index the content:
`             esClient.Index<CrompAudioMediaDetectionOrderMatch>(match, i=>i.Refresh());`

When I examine the _mapping data on the server I can see that the mappings have been correctly created to the desired depth, but when I try to return documents either by searching with NEST or by browsing to http://localhost:9200/matches/_search I find that the object is only stored 2 layers deep.

I saw that there _were_ some bugs surrounding the MaxDepth parameter of AutoMap, but since the server-side map seems correct I can't figure out what I'm doing wrong.

Do I need to do something at index time to store content to this depth? 

Many Thanks!

-D

**Comment by gmarz** [comment]
Hey @tveyes can you post the generated JSON here from the index call?  Is it missing data?

**Comment by tveyes** [comment]
Hello @gmarz,

I've been digging into this issue a bit, and I've been unable to recreate the issue using example POCOs. I therefore think it has something to do with the structure of the objects I'm trying to store. I'm pretty sure its an issue on my end. 

Thanks for your quick followup!

-D
