### ISSUE TITLE
Bug in TermsQueryDescriptor when passing to Terms IEnumerable<TValue>

### ISSUE THREAD

**Issue by alekole** [elastic/elasticsearch-net#1930]
if i have some descriptor like
`var descr = new QueryContainerDescriptor<SearchProductCard>().Terms(t => t.Field("field").Terms(new List<int> {1,2}));`

it will transfer in 
```
"terms": {
     "field": [
        [
             "1",
             "2"
         ]
      ]
   }
```
This causes an error in elastic
```
"reason": {
               "type": "number_format_exception",
               "reason": "For input string: \"[\""
            }
```

I have noticed that before commit [e1e467e2](https://github.com/elastic/elasticsearch-net/commit/e1e467e2bc91b1752b48048f71f4c08b8333c787) there was an explicit conversion to array
```
public TermsQueryDescriptor<T, K> Terms(IEnumerable<K> terms) => Assign(a =>  
    {
    if (terms.HasAny())
    terms = terms.Where(t => t != null).ToArray();
    a.Terms = terms.Cast<object>();
});
```
and missed later
```
public TermsQueryDescriptor<T, TValue> Terms(IEnumerable<TValue> terms) => Assign(a => a.Terms = terms.Cast<object>());
```

**Comment by tormodu** [comment]
I am also experiencing this using Elasticsearch 2.2.|

**Comment by russcam** [comment]
@alekole, Thanks for reporting. The `TermsQueryDescriptor<T>` looks like the following

```c#
	public class TermsQueryDescriptor<T> 
		: FieldNameQueryDescriptorBase<TermsQueryDescriptor<T>, ITermsQuery, T>
		, ITermsQuery where T : class
	{
		protected override bool Conditionless => TermsQuery.IsConditionless(this);
		MinimumShouldMatch ITermsQuery.MinimumShouldMatch { get; set; }
		bool? ITermsQuery.DisableCoord { get; set; }
		IEnumerable<object> ITermsQuery.Terms { get; set; }
		IFieldLookup ITermsQuery.TermsLookup { get; set; }

		public TermsQueryDescriptor<T> TermsLookup<TOther>(Func<FieldLookupDescriptor<TOther>, IFieldLookup> selector)
			where TOther : class => Assign(a => a.TermsLookup = selector(new FieldLookupDescriptor<TOther>()));

		public TermsQueryDescriptor<T> MinimumShouldMatch(MinimumShouldMatch minMatch) => Assign(a => a.MinimumShouldMatch = minMatch);

		public TermsQueryDescriptor<T> DisableCoord(bool? disable = true) => Assign(a => a.DisableCoord = disable);

		public TermsQueryDescriptor<T> Terms<TValue>(IEnumerable<TValue> terms) => Assign(a => a.Terms = terms?.Cast<object>());

		public TermsQueryDescriptor<T> Terms<TValue>(params TValue[] terms) => Assign(a => a.Terms = terms?.Cast<object>());

	}
```

The problem that you are experiencing here is that the compiler is preferring the `params TValue[]` overload of `Terms<TValue>()`, **incorrectly** inferring the type of `TValue` to be `List<int>` instead of correctly inferring it to be `int`. Specifying the type of `TValue` explicitly will rectify this

```c#
var descr = new QueryContainerDescriptor<SearchProductCard>().Terms(t => t
    .Field("field")
    // specify generic parameter type to be int
    .Terms<int>(new List<int> {1,2})
);
```

The `Terms<TValue>(IEnumerable<TValue> terms)` overload will now be called instead.

/cc @Mpdreamz, @gmarz

**Comment by Mpdreamz** [comment]
Thanks for reporting this one @tormodu :+1: whilst what we did was technically correct, it is very much unexpected behaviour from a users perspective

I just opened https://github.com/elastic/elasticsearch-net/pull/1948 to try an manually unwrap these cases to "the right thing".
