### ISSUE TITLE
Bug in filter aggregation with script

### ISSUE THREAD

**Issue by tormodu** [elastic/elasticsearch-net#1931]
When using filter aggregation with an inline script as filter nest generates an incorrect query to elasticsearch.
 
The following code: 
` .Filter("NAME", htw => htw.Filter(htwFlt => htwFlt.Script(hwScrpt => hwScrpt.Inline("SCRIPT "))))`

generates the following query:

` "NAME": {
      "filter": {
        "script": {
          "inline": "SCRIPT"
        }
      },`

Elasticsearch responds with **[script] query does not support [inline]**
Changing the query to:

` "NAME": {
      "filter": {
        "script": {
          "script": "SCRIPT"
        }
      },`

produces the correct result.

**Comment by Mpdreamz** [comment]
Which version of Elasticsearch are you using?

**Comment by tormodu** [comment]
Version 2.2.1

**Comment by Mpdreamz** [comment]
Definitely a bug on our end i just pushed a fix for this 

https://github.com/elastic/elasticsearch-net/pull/1944

Thanks a ton for raising the issue :+1:

**Comment by gmarz** [comment]
Closed via #1944
