### ISSUE TITLE
Firstly this is not an issue, but I am unable to get a proper documentation on CreateIndex in NEST 2.0.4

### ISSUE THREAD

**Issue by cmrhemalatha** [elastic/elasticsearch-net#1932]
Team,

Please do help me out, My world was simpler when I had  a json with my full index inside it.
I had to read the file , check if the index exists , if existed, delete it and create a new one in C# and I had uses NEST 1.7.1.
```
string jsonfile= System.IO.File.ReadAllText(jsonfilepath);
ESClient.Raw.IndicesCreatePost("myindex, filetext);
```
Post installing NEST 2.0.4, with my limited documentation available, could you please let me know, how do I just create an index.

I know it sounds like a trivial thing for you, but I just dont seem to get any concrete examples.

**Comment by russcam** [comment]
Hey @cmrhemalatha 

Accessing the low level client on `ElasticClient` now happens via the `.LowLevel` property on `ElasticClient` in 2.x

```c#
var client = new ElasticClient();

string jsonfile= System.IO.File.ReadAllText(@"C:\path_to_json");

// the generic parameter for the method is for the type of T in ElasticsearchResponse<T> so
// if you don't need to deserialize, you might want to use byte[] or string
var createIndex = client.LowLevel.IndicesCreatePost<string>("myindex", jsonfile);
```

Here are [details around what has changed in 2.x](https://www.elastic.co/blog/ga-release-of-nest-2-0-our-dot-net-client-for-elasticsearch) and a list of breaking changes for [Elasticsearch.Net](https://github.com/elastic/elasticsearch-net/blob/master/docs/2.0-breaking-changes/elasticsearch-net-breaking-changes.md) and [NEST](https://github.com/elastic/elasticsearch-net/blob/master/docs/2.0-breaking-changes/nest-breaking-changes.md) (programmatically generated so __most__ of the changes should be there)

**Comment by cmrhemalatha** [comment]
Thanks a ton :)
