### ISSUE TITLE
Deserialization into DateTimeOffset modifies the timezone offset.

### ISSUE THREAD

**Issue by JefStat** [elastic/elasticsearch-net#1937]
I index the following value with timezone info
`{"startTimeLocal": "2016-03-21T09:45:20-02:00"}`
When I query the document in elasticsearch I get back the correct timezone
`{ "startTimeLocal": "2016-03-21T09:45:20-02:00" }`
When the response is deserialized into the POCO mapping object using the `IGetResponse<T> Get<T>(DocumentPath<T> document, Func<GetDescriptor<T>, IGetRequest> selector = null)` method I get back the system timezone instead of the store timezone value for the `DateTimeOffset?` properties.

Sample class:
`public class SampleObject  {  [Nest.Date(DocValues = true, Name = "startTimeLocal")] public DateTimeOffset? StartTimeLocal {get; set;} }`
Result `StartTimeLocal = 2016-03-21T11:45:20-04:00`

**Comment by JefStat** [comment]
Traced the issue into Json.net. 
https://github.com/JamesNK/Newtonsoft.Json/issues/744

I could use some documentation how to modify the JSON.net serializer settings.

**Comment by JefStat** [comment]
Got it. 
```
    public class CustomJsonNetSerializer : JsonNetSerializer
    {
        public CustomJsonNetSerializer(IConnectionSettingsValues settings) : base(settings)
        {
        }

        #region Overrides of JsonNetSerializer

        protected override void ModifyJsonSerializerSettings(JsonSerializerSettings settings)
        {
            settings.DateParseHandling = DateParseHandling.DateTimeOffset;
            settings.DateFormatHandling = DateFormatHandling.IsoDateFormat;
            settings.DateTimeZoneHandling = DateTimeZoneHandling.RoundtripKind;
        }

        #endregion
    }
```

**Comment by Mpdreamz** [comment]
Appreciate the ping back, was gonna look at this in the morning. :+1:

We might want these settings to be the default that we ship witg
