### ISSUE TITLE
Request dispatching errors

### ISSUE THREAD

**Issue by Crassirostris** [elastic/elasticsearch-net#1940]
Hey

Recently I decided to update NEST to the latest version (2.0.5, from 1.6.1), but several cases of strange behavior occurred. For example, when I need to delete all indices, I issue this call:

```
await elasticClient.DeleteIndexAsync(Indices.All);
```

After that I get this exception:

```
System.ArgumentException : Dispatching IndicesDelete() from NEST into to Elasticsearch.NET failed
Received a request marked as DELETE
This endpoint accepts DELETE
The request might not have enough information provided to make any of these endpoints:
  - /{index=_all}

   at Nest.LowLevelDispatch.IndicesDeleteDispatchAsync[T](IRequest`1 p) in c:\code\elasticsearch-net\src\Nest\_Generated\_LowLevelDispatch.generated.cs:line 1137
   at Nest.ElasticClient.<Nest-IHighLevelToLowLevelDispatcher-DispatchAsync>d__24`4.MoveNext() in c:\code\elasticsearch-net\src\Nest\ElasticClient.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
```

Please, help, how can I perform some operations on all indices? I get the same result with IndicesGet, and I don't know indices list on the application side.

**Comment by Mpdreamz** [comment]
This is definitely a bug in our dispatch which has a special collapsing logic for `_all`, you can use `"*"` in the meantime. Thanks for reporting this will fix ASAP

**Comment by Crassirostris** [comment]
OK, thanks! Looking forward to the patch then.

**Comment by Mpdreamz** [comment]
Thanks for reporting this one added better tests for these cases and we'll release a new version later today/tomorrow :+1:
