### ISSUE TITLE
Filter terms crashes with NumberFormatException[For input string: "["];

### ISSUE THREAD

**Issue by SLavrynenko** [elastic/elasticsearch-net#1941]
I've the following C# code:

 ```
     var result2 = client.Search<Contact>(
        s => s.Query(
          q =>
          {
            return
              q.Bool(
                b => b.Must(
                  m =>
                  {
                    var query = m.MatchAll();
                    return query;
                  })
                  .Filter(f =>
                  {
                    var filter = f.Terms(p => p.Field(sf => sf.Tags).Terms(searchFilter.Tags));
                    return filter;
                  }));
          }));
```

and it returns that response doesn't have any errors:
`		DebugInformation	"Valid NEST response built from a succesful low level call on POST: /_search\r\n# Audit trail of this API call:\r\n - HealthyResponse: Node: http://192.168.1.110:9200/ Took: 00:00:00.3432729\r\n# Request:\r\n<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>\r\n# Response:\r\n<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>\r\n"	string`

But I see that there is error in ElasticSearch logs:
```
RemoteTransportException[[James Jaspers][192.168.1.110:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"match_all":{}}],"filter":[{"terms":{"tags":[[3765,8622,3766]]}}]}}}]]; nested: NumberFormatException[For input string: "["];
Caused by: SearchParseException[failed to parse search source [{"query":{"bool":{"must":[{"match_all":{}}],"filter":[{"terms":{"tags":[[3765,8622,3766]]}}]}}}]]; nested: NumberFormatException[For input string: "["];
```

The reason as I see is in the following: {"tags":[[3765,8622,3766]] - why it wrap values in double square brackets?

**Comment by gmarz** [comment]
This looks like the same issue as https://github.com/elastic/elasticsearch-net/issues/1930.

**Comment by SLavrynenko** [comment]
Yes it looks the same in the part how query is generated, but here we have additional part - NEST returns result that says that there were no errors. So it seems there is additional bug with result parsing from the ElasticSearch.

**Comment by Mpdreamz** [comment]
Are you using Elasticsearch 2.0? NEST 2.x does not work against Elasticsearch 2.x

I wrote an integration test for this to make sure we do the right thing against Elasticsearch 2.x here:

https://github.com/elastic/elasticsearch-net/blob/fix/support-list-of-terms-natively/src/Tests/QueryDsl/TermLevel/Terms/TermsListQueryUsageTests.cs#L125

The response is invalid on a number format exception inside a terms query.

I just submitted a PR that tries to the right thing when calling `.Terms(List<T> x)`

https://github.com/elastic/elasticsearch-net/pull/1948

**Comment by SLavrynenko** [comment]
My version of ElasticSearch:

  "version" : {
    "number" : "2.1.1",

**Comment by Mpdreamz** [comment]
Can you set DisableDirectStreaming on ConnectionSettings and paste the full
DebugInformation on the response?

**Comment by SLavrynenko** [comment]
DebugInformation	"Valid NEST response built from a succesful low level call on POST: /_search\r\n# Audit trail of this API call:\r\n - HealthyResponse: Node: http://192.168.1.110:9200/ Took: 00:00:00.3514100\r\n# Request:\r\n{\"query\":{\"bool\":{\"must\":[{\"match_all\":{}}],\"filter\":[{\"terms\":{\"tags\":[[3765,8622,3766]]}}]}}}\r\n# Response:\r\n{\"took\":17,\"timed_out\":false,\"_shards\":{\"total\":10,\"successful\":5,\"failed\":5,\"failures\":[{\"shard\":0,\"index\":\"smash_fly_1\",\"node\":\"3cg5G0JRQVKMhWv5VWYFGA\",\"reason\":{\"type\":\"number_format_exception\",\"reason\":\"For input string: \\\"[\\\"\"}}]},\"hits\":{\"total\":0,\"max_score\":null,\"hits\":[]}}\r\n"	string

**Comment by Mpdreamz** [comment]
So the response truely is valid in the sense that that response is a 200, but some of the shards failed and some succeeded resulting in a partially valid response.

**Comment by SLavrynenko** [comment]
But when Im trying to run the same query via Sense, I didn't see 200 response:

```
{
   "error": {
      "root_cause": [
         {
            "type": "number_format_exception",
            "reason": "For input string: \"[\""
         }
      ],
      "type": "search_phase_execution_exception",
      "reason": "all shards failed",
      "phase": "query",
      "grouped": true,
      "failed_shards": [
         {
            "shard": 0,
            "index": "index_1",
            "node": "3cg5G0JRQVKMhWv5VWYFGA",
            "reason": {
               "type": "number_format_exception",
               "reason": "For input string: \"[\""
            }
         }
      ]
   },
   "status": 400
}
```

**Comment by Mpdreamz** [comment]
in NEST your search goes through all the indices (`/_search`) are you doing the same in sense?

**Comment by SLavrynenko** [comment]
I've got what do you mean, yes - if I'm trying to make the same request to all the indices it returns 200 response, but if I try to send it to my index - it returns 400
