### ISSUE TITLE
How to create delegate Func that return ISearchRequest from SearchDescriptor input params

### ISSUE THREAD

**Issue by issam-chouchane** [elastic/elasticsearch-net#1943]
In thes 1.x version my delegate accepts SerchDescriptor and return the same type to build a clean query to searh entries in Elastic. How about the version 2.0 which accepts SerchDescriptor and return ISearchRequest.

**Comment by Mpdreamz** [comment]
Hi @issam-chouchane did you figure out how to do it?

**Comment by issam-chouchane** [comment]
Hi @Mpdreamz 

we rewrite 

`u.Query(q => q.Terms(tf => tf.Field(new Field() { Name = request.SearchField })) && q.Terms(tt => tt.Terms(request.SearchTerms)));`

to

`u.Query(q => q.Bool(bq => bq.Must(m => m.Terms(tf => tf.Field(new Field() { Name = request.SearchField }).Terms(request.SearchTerms)))));`

and cast the return result to ISearchRequest

`return u as ISearchRequest;`
