### ISSUE TITLE
ScriptQuery mapping

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#1945]
See: https://github.com/elastic/elasticsearch-net/pull/1944

We currently map script query as a single unit but we need to move the `inline`, `file` and `id` properties under another `script` property of type `ScriptBlock`. 

This `ScriptBlock` should be used under `ScriptScoreFunction` rather then the whole `ScriptQuery`

**Comment by gmarz** [comment]
We have [IScript](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/CommonOptions/Scripting/ScriptBase.cs) which we use everywhere a script can be specified.  Can we use that instead?

**Comment by Mpdreamz** [comment]
:+1: good call, absolutely

```diff
-ScriptBlock
+IScript
```
