### ISSUE TITLE
how to use custom similarity

### ISSUE THREAD

**Issue by smile-sunsshine** [elastic/elasticsearch-net#1946]
Hi,
    I have my own custom similarity es plugin,i want to use my own custom similarity in my index,but i have not found any info on how to use or set it.Could anybody please give me a complete demo about it?
    my elasticsearch.net is v2.0.0.0,and my Nest is v2.0.0.0 .

**Comment by Mpdreamz** [comment]
Create a C# type that implements `ISimilarity` and make sure it maps all the options of your custom elasticsearch similarity.

Take a look at https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/IndexModules/Similarity/IB/IBSimilarity.cs as a reference

Then you can register it as followed:

```csharp
client.CreateIndex(new CreateIndexRequest("newindex")
{
    Similarities = new Similarities
    {
           { "name-of-similarity", new MyCustomSimilarity() }
     }
});
```
