### ISSUE TITLE
[Discuss] How breaking should NEST 5.0 be?

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#1951]
`NEST 2.x` was a pretty heavy breaking major release, with 5.0.0 alpha's around the corner we should decide beforehand how backwards compatible we want to be for our next major release. 

e.g the `TermsQuery` no longer supports `MinimumShouldMatch` and `DisableCoord`, do we simply remove these from our client or mark them as obsolete?

That is a pretty easy to support backward compatible change but what do we do for more complex cases?

I'm +1 on removing these and starting from 5.0 maintain a stricter [Obsolete] observance of deprecated properties in Elasticsearch

**Comment by gmarz** [comment]
> I'm +1 on removing these

+1 as well.  I think we should [break where ES breaks](https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking-changes-5.0.html), and try to introduce as little client/refactoring breaking changes as possible from 2.x -> 5.x.

This also simplifies our compatibility matrix and makes it very straight forward as to which versions of ES the client supports.  Having a 2.x client and also maintaining bwc in 5.x would add maintenance complexity that I don't think is worth it considering we have a new shiny 2.x client where we refactored all the ugly bits.

> starting from 5.0 maintain a stricter [Obsolete] observance of deprecated properties in Elasticsearch

Definitely.  We can also go back and mark things in 2.0 as obsolete to give a heads up for 5.x which hopefully results in an easier upgrade path to 5.0.

**Comment by russcam** [comment]
I'm in agreement with @gmarz - we can (and _should_) break where ES breaks. There should be no surprises in a 5.x client being compatible with ES 5.x

**Comment by Mpdreamz** [comment]
We all agree then, awesome :smile:

**Comment by djnelson9715** [comment]
Perhaps this is a different issue, but would it be possible to have the
release of Nest 5.0 closer to the release of Elastic 5.0.  For our shop,
the lag between the 2.x elastic and 2.0 Nest really handcuffed us being
able to update our clusters.   It would really be helpful in allowing us to
stay more current with elastic releases.  I know that a lot of work went
into the Nest 2.0 and the end product is awesome, but hopefully this
release will be closer to the elastic release schedule.

On Wed, Mar 23, 2016 at 7:16 AM, Martijn Laarman <notifications@github.com>
wrote:

> NEST 2.x was a pretty heavy breaking major release, with 5.0.0 alpha's
> around the corner we should decide beforehand how backwards compatible we
> want to be for our next major release.
>
> e.g the TermsQuery no longer supports MinimumShouldMatch and DisableCoord,
> do we simply remove these from our client or mark them as obsolete?
>
> That is a pretty easy to support backward compatible change but what do we
> do for more complex cases?
>
> I'm +1 on removing these and starting from 5.0 maintain a stricter
> [Obsolete] observance of deprecated properties in Elasticsearch
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/elastic/elasticsearch-net/issues/1951>
>



-- 
Doug Nelson

**Comment by Mpdreamz** [comment]
Absolutely!, our master branch is already tracking master and we're doing our best to make sure the integration tests pass ASAP.
 
Thanks for voicing your concern @djnelson9715 it helps us gauge urgency!

**Comment by niemyjski** [comment]
We should remove these and mark those features and all other deprecated features as deprecated now and release a 2.1.1
