### ISSUE TITLE
Search for words with spaces

### ISSUE THREAD

**Issue by senj** [elastic/elasticsearch-net#1953]
Hello maybe someone can help me,

I'm using Search Query and Term Suggester to build a search and it's working pretty good.
The only thing that doesn't work is e.g.

MexicoCity
when the correct entry is: Mexico City.

Is this kind of search correction possible with ES?
Would be great if I don't have to modify my data definition in the database.

What can fuzzy search do for me?

**Comment by gmarz** [comment]
Hi @senj please ask this question on https://discuss.elastic.co/c/elasticsearch

GitHub issues are reserved for bug/feature requests, or questions about the .NET client itself.
