### ISSUE TITLE
where is the release notes ? 

### ISSUE THREAD

**Issue by devheroo** [elastic/elasticsearch-net#1955]
I just noticed there is an update for NEST 2.0.5, is there a release note available to read so that I can know what fixes are included in this update ? I am new to github and I couldn't find a way to trace issues that were closed in this update ?

any help is appreciated.

**Comment by gmarz** [comment]
All of our releases our published here https://github.com/elastic/elasticsearch-net/releases

We also label issues and PRs according the version they are targeted for, so you can always filter by the appropriate label: https://github.com/elastic/elasticsearch-net/issues?q=is%3Aissue+label%3Av2.0.5+is%3Aclosed

**Comment by devheroo** [comment]
Perfect, Thanks so much.
