### ISSUE TITLE
Issue with SniffingConnectionPool and non-http nodes

### ISSUE THREAD

**Issue by EricKeij** [elastic/elasticsearch-net#1957]
We ran into an issue when using the SniffingConnectionPool and having a node in the cluster with http disabled. This gives an exception saying "Failed sniffing cluster state". Looking at the inner exception it turns out that the actual error occurs in `ParseToUri() ` in `SniffResponse` which executes a regex getting an empty httpAddress passed in. 

The issue does not occur when stopping non-http nodes or when using the StaticConnectionPool and explicitly specify the nodes. 

We are using NEST 2.0.4 and ES 2.2.0.

**Comment by Mpdreamz** [comment]
Argh, yeah none of our unit tests test this scenario. Thanks for opening this issue :+1:

**Comment by Mpdreamz** [comment]
Hi @EricKeij finally got around to fixing this as per: https://github.com/elastic/elasticsearch-net/pull/2078

Should make it in `Nest 2.4` which should be out either end of this week or next week.
