### ISSUE TITLE
I'm confused, where is the 2.0 documentation

### ISSUE THREAD

**Issue by Sohojoe** [elastic/elasticsearch-net#1960]
specifically i'm looking for the 2.0 documentation for Attributes; as mentioned in this blog post, the attributes changed in 2.0 https://www.elastic.co/blog/ga-release-of-nest-2-0-our-dot-net-client-for-elasticsearch i.e.
 `[ElasticProperty(Type = FieldType.String, Analyzer = "myanalyzer", TermVector = TermVectorOption.WithOffsets)]` 
is now
 `[ElasticProperty(Type = FieldType.String, Analyzer = "myanalyzer", TermVector = TermVectorOption.WithOffsets)]`

[the wiki](https://github.com/elastic/elasticsearch-net/wiki) sends me to [azurewebsites.net](http://nest.azurewebsites.net/) - has the [documentation for v1.x](http://nest.azurewebsites.net/breaking-changes.html)

**Comment by russcam** [comment]
Hey @Sohojoe, I've just [merged](https://github.com/elastic/elasticsearch-net/pull/1962) the [updated docs (in asciidoc format) for NEST 2.x into the 2.x branch](https://github.com/elastic/elasticsearch-net/blob/2.x/docs/asciidoc/index.asciidoc). These will shortly be up on the [**Elastic clients documentation**](https://www.elastic.co/guide/en/elasticsearch/client/index.html).

http://nest.azurewebsites.net/ has documentation for an **_old_** version of 1.x and will be deprecated (with redirects) to point to the Elastic clients documentation pages. I'll also update the wiki to point to the right location.

Apologies for the confusion at this intermediate stage; [here are the 2.x docs for Attribute based mapping](https://github.com/elastic/elasticsearch-net/blob/2.x/docs/asciidoc/client-concepts/high-level/mapping/auto-map.asciidoc) to take a look at whilst you're waiting for them up to get up on the Elastic site :smile:

**Comment by russcam** [comment]
New docs are now up on the [elastic.co client documentation site](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/index.html). 

Documentation is generated from the [Tests project](https://github.com/elastic/elasticsearch-net/tree/master/src/Tests) using [Roslyn](https://github.com/dotnet/roslyn); multi-line comments serve as the main bodies of text, intermixed with code samples that test the documented components. The intention is to reduce the likelihood of documentation becoming outdated as the source changes. 

Text within multi-line comments conforms to [asciidoc](http://asciidoc.org/), a lightweight markdown style text format well suited to technical documentation. To generate the asciidoc files from the tests, you need to run [Nest.Litterateur](https://github.com/elastic/elasticsearch-net/tree/master/src/CodeGeneration/Nest.Litterateur) console application which will output the documentation files in the docs/asciidoc output directory. To verify that the generated asciidoc files can generate the documentation for the website, you would need to [clone the elastic docs repo](https://github.com/elastic/docs) and follow the instructions there for building documentation locally.

[Pull Requests](https://github.com/elastic/elasticsearch-net/pulls) are most welcome for areas of documentation that you feel may need improving :smile: Right now, we have the Query DSL and Aggregation usage pages up, but the plan is to also add usage examples for other endpoints too.

**Comment by chrisklepeis** [comment]
I'm having trouble determining how to add an anylizer, tokenizer to an index, as well as how to use CopyTo since the signature changed.

Might need some documentation on these as well.
