### ISSUE TITLE
Align default string mapping in AutoMap() with 5.0 defaults

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#1966]
The default inferred mapping for string fields is of type `text` with a `keyword` multi field of type `keyword`

https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_mapping_changes.html#_default_string_mappings

We already have support for the new `text` and `keyword` types in master as per https://github.com/elastic/elasticsearch-net/commit/be14c871be5462102116349fe8930a3bbc84a35d

Should we extend AutoMap() to default to the same default Elasticsearch has? 

I vote :+1:

**Comment by gmarz** [comment]
:+1:
