### ISSUE TITLE
Serialization / Deserialization performance problems on .Index operation

### ISSUE THREAD

**Issue by amelmusic** [elastic/elasticsearch-net#1969]
I've downloaded "elasticsearch-net-example-master" and when I run NuSearch.Indexer project every insert runs more than 500ms, but if I execute same request from postman it runs around 20ms.

I've run performance analysis on var result = Client.Index(package); method and from what I see, 90% of time is taken by serialization / deserialization. 
Can this be improved?

Please find in the attachment performance report.

[NuSearch.Indexer160331.zip](https://github.com/elastic/elasticsearch-net/files/197636/NuSearch.Indexer160331.zip)

**Comment by Mpdreamz** [comment]
If you profile its hard to distinguish between first request and subsequent requests, its true that the very first call carries a significant overhead, JSON.NET (and to be fair certain bits of NEST too) rely heavily on cached reflection which need to be warmed once per app domain.

If I hack nusearch from [elasticsearch-net-example](https://github.com/elastic/elasticsearch-net-example)

by adding this class:

```csharp
public class Timings
{
	public TimeSpan CLientTime { get; set; }
	public TimeSpan SerializationTime { get; set; }

	public override string ToString() => $"{(long)(CLientTime.TotalMilliseconds)}ms => {(long)(SerializationTime.TotalMilliseconds)}ms";
}
```

Setting `CallMetrics()` on `ConnectionSettings` and adding some stopwatches around the call:


```
var sw = new Stopwatch();
foreach (var package in packages)
{
	sw.Restart();
	var result = Client.Index(package);
	sw.Stop();
	var metrics = result.ConnectionStatus.Metrics;
	var serializationTime = TimeSpan.FromMilliseconds(metrics.SerializationTime + metrics.DeserializationTime);
	var timing = new Timings { CLientTime = sw.Elapsed, SerializationTime = serializationTime };
	Console.WriteLine(timing);
```

I'm seeing the following pattern:

```
239ms => 130ms
9ms => 0ms
6ms => 0ms
8ms => 0ms
6ms => 0ms
7ms => 0ms
6ms => 0ms
6ms => 0ms
6ms => 0ms
6ms => 0ms
6ms => 0ms
6ms => 0ms
7ms => 0ms
9ms => 0ms
6ms => 0ms
6ms => 0ms
7ms => 0ms
6ms => 0ms
6ms => 0ms
7ms => 0ms
...etc....
```

Which I think are acceptable numbers. Here its 240ms but i've seen them in the range `500ms-1s` depending on the machine.

Long term we are working on generating the (de)serialization of known bits of the API to minimize allocations and squeeze more performance and hopefully keep that first hit to a minimum,

**Comment by amelmusic** [comment]
That's totally acceptable.
Maybe, this is because of configuration or something else.
This is what I get:
714 --first request
511
512
511
510
511
511
501
510
501
511
511
511
511
507
510
510
510
511
etc

**Comment by Mpdreamz** [comment]
Mind sharing your code and connectionsettings? If you run nusearch with fiddler open, its configured to automatically route requests through fiddler, does that surface anything?

**Comment by amelmusic** [comment]
This is the connection:	
public static class NuSearchConfiguration
	{
		private static readonly ConnectionSettings _connectionSettings;

		public static string LiveIndexAlias { get { return "nusearch"; } }
		public static string OldIndexAlias { get { return "nusearch-old"; } }

		public static Uri CreateUri(int port)
		{
			var host = "localhost";
			if (Process.GetProcessesByName("fiddler").Any())
				host = "ipv4.fiddler";

			return new Uri("http://" + host + ":" + port);
		}

		static NuSearchConfiguration()
		{
			_connectionSettings = new ConnectionSettings(CreateUri(9200)).SetDefaultIndex("nusearch");
		}

		public static ElasticClient GetClient()
		{
			return new ElasticClient(_connectionSettings);
		}

		public static string CreateIndexName()
		{
			return string.Format("{0}-{1:dd-MM-yyyy-HH-mm-ss}", LiveIndexAlias, DateTime.UtcNow);
		}
	}

Rest is same as in example.

**Comment by amelmusic** [comment]
I've tried this on another server. Everything works OK. Same code.

**Comment by Mpdreamz** [comment]
Try specifying `DisableAutomaticProxyDetection` on `ConnectionSettings` on the server thats misbehaving. 

Thanks for reporting back!

**Comment by amelmusic** [comment]
Thnx. Great
