### ISSUE TITLE
Dynamic properties for mapping/indexing and queries

### ISSUE THREAD

**Issue by falsecrypt** [elastic/elasticsearch-net#1970]
Hello,

i would like to add more properties to the mapping at runtime. So for example i have defined a base `POCO ` with default properties and want to insert some user-configured properties, i could store them in a `Dictionary<string,string> ` structure, where key is a property name. Later i would like to use them in some queries. Maybe i could use `Template Query` for that. I can already create a dynamic mapping using `Properties` and `PutMappingRequest`. Is this the only possible solution?
But how can i index my `POCO` and serialize the object correctly? I don't want to have the dictionary in my mapping, only the properties, it contains.
I saw, that i can somehow provide my own `JsonNetSerializer` and a `JsonConverter`. Can somebody help me with this task or point me in the right direction? :-) 
Small example:

POCO:
```
    public class Product {
        [String]
        public string Title { get; set; }

        [String]
        public string Description { get; set; }

        public Dictionary<string, string> AdditionalFields { get; set; }
    }
```
Instance:
```
            var article = new Product () {
                Title = "Product title",
                Description = "some descr",
                AdditionalFields = new Dictionary<string, string> {
                    ["title_en"] = "some english title",
                    ["title_es"] = "some spanish title"
                }
            };
```
should be indexed as:

```
  "mappings": {
    "article": {
      "properties": {
        "title": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "title_en": {
          "type": "string",
          "analyzer": "english"
        },
        "title_es": {
          "type": "string",
          "analyzer": "spanish"
        }
      }
    }
  }
```

**Comment by Mpdreamz** [comment]
The `Json.NET` feature you are looking for is: `[JsonExtensionData]` see these release notes for an example usage: http://james.newtonking.com/archive/2013/10/14/json-net-5-0-release-7-immutable-collections

You can define `Properties` as part of the `CreateIndex()` call too. 

You should not need to use `Template Query` just use the string `"title_en"` as field name.

Let me know if this is not enough information to unblock you :)
