### ISSUE TITLE
Using QueryStrings (directly as string) in Nest Possible?

### ISSUE THREAD

**Issue by chrisklepeis** [elastic/elasticsearch-net#1972]
I'm not sure if this is a feature request or if I'm just missing something, but I want to get the results from a URL like this: http://127.0.0.1:9200/customersearch/_search?q=averageMonthlySales:>20000

The users of our application will be typing in the querystring - "averageMonthlySales:>20000"  (despite my disagreement).

I do get results in the browser when going to that URL, but when I try to call it with this I get no results:

```
var response = client.Search<DtoTypes.Customer.SearchResult>(s =>
    s.From(0)
    .Take(Constants.ElasticSearch.MaxResults)
    .Query(q => 
        q.QueryString(qs => qs.Query("averageMonthlySales:>20000"))));
```

I want to avoid having to parse what they type in... at least as much as I can. If this isn't possible with nest, could I just deserialize the results from the URL to a ISearchResponse object?

**Comment by chrisklepeis** [comment]
Odd... it just started working with the above code. I don't know what changed. I just set DisableDirectStreaming to true to get the DebugInformation, and since then it worked, even after I took that code out.

**Comment by russcam** [comment]
@chrisklepeis, Can you use something like [Fiddler](http://www.telerik.com/fiddler) to see what the response json is when not setting `.DisableDirectStreaming()`? If running against `localhost`, change `localhost` to `ipv4.fiddler` to run through fiddler.

**Comment by chrisklepeis** [comment]
Thankfully, I'm having trouble getting the issue again, so closing this issue for now. Will comment again if I see the issue again.

**Comment by russcam** [comment]
@chrisklepeis Cool. Feel free to reopen if you see it again :+1:
