### ISSUE TITLE
Indices.All vs Indices.AllIndicies

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#1973]
There's no docs on this that I can see. Any reason why there is both?
```csharp

    public static Indices All { get; } = new Indices(new Indices.AllIndicesMarker());

    public static Indices AllIndices { get; } = new Indices(new Indices.AllIndicesMarker());
```

**Comment by Mpdreamz** [comment]
Sharp eye :)

It's for when you statically import Indices and Types and `All` becomes ambiguous.

```csharp
using static Nest.Indices;
```

The preferred static import target though is

```csharp
using static Nest.Infer;
```

for everything (Fields, Type(s), Index, Indices and Id<T>(T))

We'll be more conservative how we expose this in 5.0 and write proper documentation around this (beyond the inferrence pages we already have https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/field-inference.html#nest-infer)

**Comment by niemyjski** [comment]
Thanks :). Could we use an import alias?

**Comment by niemyjski** [comment]
I just hit this again when trying to upgrade from 1.x to 5.x

**Comment by niemyjski** [comment]
There are no docs on this.

**Comment by russcam** [comment]
Did you see [the indices paths documentation?](https://www.elastic.co/guide/en/elasticsearch/client/net-api/5.x/indices-paths.html#_specifying_all_indices)

We're going to spend some time to go over the documentation to include elements that are not covered currently and to arrange the content in a more coherent fashion.

**Comment by niemyjski** [comment]
I did not, I always use up-to-date source as my docs most of the time. With this said I have a correction to my statement: There are no xml docs for this :)

Why not remove All and have AllIndicies then it would remove all confusion?
