### ISSUE TITLE
Timestamp field should be removed from fluent mappings

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#1977]
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-timestamp-field.html it's no longer supported. It actually throws an error when you try to run a mapping with it.

```csharp
.TimestampField(ts => ts.Enabled().Path(u => u.UpdatedUtc).IgnoreMissing(false))
````

**Comment by niemyjski** [comment]
The same goes for IncludeInAll

**Comment by gmarz** [comment]
Another one we''ll have to mark obsolete and remove in 5.x.  Although, it should only be deprecated in ES 2.x...

**Comment by niemyjski** [comment]
I think there are more that we are missing. Might want to go through all the docs and ensure we are deprecated everywhere.. This has made upgrading a pain point.

**Comment by gmarz** [comment]
Closing in favor of #1988
