### ISSUE TITLE
Can't have both Name and IndexName

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#1978]
This should throw a compile time error or at least warning. Maybe a roslyn analyzer would be good for this?

```csharp
.String(f => f.Name(e => e.Id).IndexName("id"))
```

**Comment by gmarz** [comment]
Actually, `IndexName` has been removed in 2.x in favor of `copy_to`, so it shouldn't even be there.  We'll have to mark it obsolete and remove in our 5.x branch.  

Thanks for the heads up @niemyjski.

**Comment by niemyjski** [comment]
No problem. I'm running into this kind of stuff left and right. Could use some assistance.

**Comment by gmarz** [comment]
Closing in favor of #1988
