### ISSUE TITLE
Sigma should be a double? on ExtendedStatsBucketAggregation

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#1982]
**NEST/Elasticsearch.Net version**: 2.1.0

**Elasticsearch version**: 2.3.0

**Description of the problem including expected versus actual behavior**:

[`Sigma` is specified as an `int?` on `ExtendedStatsBucketAggregation`](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Nest/Aggregations/Pipeline/ExtendedStatsBucket/ExtendedStatsBucketAggregation.cs#L11) but it [_should_ be a `double?` (based on the docs of Extended Stats Aggregation)](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-extendedstats-aggregation.html#CO49-1).

Sending a number without decimal places throws a parse exception on Elasticsearch 2.3.0:

Request:

```javascript
{
  "size": 0,
  "aggs": {
    "projects_started_per_month": {
      "date_histogram": {
        "field": "startedOn",
        "interval": "month"
      },
      "aggs": {
        "commits": {
          "sum": {
            "field": "numberOfCommits"
          }
        }
      }
    },
    "extended_stats_commits_per_month": {
      "extended_stats_bucket": {
        "buckets_path": "projects_started_per_month>commits",
        "sigma": 2
      }
    }
  }
}
```

Response:

```javascript
  "error" : {
    "root_cause" : [ {
      "type" : "parse_exception",
      "reason" : "Parameter [sigma] must be a Double, type `Integer` provided instead"
    } ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [ {
      "shard" : 0,
      "index" : "project",
      "node" : "afZfSF7hQoqmZQip5n3-LQ",
      "reason" : {
        "type" : "parse_exception",
        "reason" : "Parameter [sigma] must be a Double, type `Integer` provided instead"
      }
    } ]
  },
  "status" : 500
}
```
 
**Steps to reproduce**:
 1. Run the [ExtendedStatsBucketAggregationUsageTests](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Tests/Aggregations/Pipeline/ExtendedStatsBucket/ExtendedStatsBucketAggregationUsageTests.cs).
 2. Changing `Sigma` to `double?` fixes the problem. This would be a binary break for NEST 2.x however :disappointed: 

See also https://github.com/elastic/elasticsearch/issues/17499 - I filed an issue as I think Elasticsearch should also accept an integer value for `sigma` (and deserialize to double on the server side).

**Comment by jonyadamit** [comment]
@russcam How would this be a breaking change, when `ExtendedStatsBucketAggregation

**Comment by russcam** [comment]
@jonyadamit My bad, I thought it'd gone into 2.1.0 but I was looking at `ExtendedStatsAggregation` - will close this issue and change it to `double?` :+1:

**Comment by gmarz** [comment]
:+1: I had actually made this change in master (https://github.com/elastic/elasticsearch-net/commit/7273f55aa8a0ca821574a83561769234a146e440) but never cherry picked it to 2.x.
