### ISSUE TITLE
Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by shonaw** [elastic/elasticsearch-net#1984]
**NEST/Elasticsearch.Net version**:2.1.0

**Elasticsearch version**:2.2.0

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Intensively insert into an index using client.BulkAsync().  Here's my code:

```c#
             try
            {
                if (updates.Count() > 0)
                {
                    var bulkRequest = new BulkRequest("runtime");
                    var indexOps = updates
                        .Select(o => new BulkIndexOperation<object>(o.Value.Value)
                        {
                            Id = o.Key,
                            Type = o.Value.Key
                        })
                        .Cast<IBulkOperation>()
                        .ToList();
                    bulkRequest.Operations = indexOps;

                    var result = await _client.BulkAsync(bulkRequest);

                    }
                }
            }
            catch (Exception e)
            {
                // Caught the exception detailed below here.
            }
```

**Provide `DebugInformation` (if relevant)**:
Caught the following exception from ES:

```
 e	{"Collection was modified; enumeration operation may not execute."}	System.Exception {Elasticsearch.Net.UnexpectedElasticsearchClientException}
		StackTrace	"   at Elasticsearch.Net.Transport`1.<RequestAsync>d__15`1.MoveNext() in C:\\users\\russ\\source\\elasticsearch-net\\src\\Elasticsearch.Net\\Transport\\Transport.cs:line 148\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Nest.ElasticClient.<Nest-IHighLevelToLowLevelDispatcher-DispatchAsync>d__24`4.MoveNext() in C:\\users\\russ\\source\\elasticsearch-net\\src\\Nest\\ElasticClient.cs:line 0\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Acaveo.Sis.DataAccess.ElasticSearch.EsOrleansDataProvider.<BulkUpdateOfPending>d__23.MoveNext() in C:\\dev\\git\\banjo\\DataAccess\\Acaveo.Sis.DataAccess.ElasticSearch\\EsOrleansDataProvider.cs:line 153"	string

**with InnerException:**
+		InnerException	{"Collection was modified; enumeration operation may not execute."}	System.Exception {System.InvalidOperationException}

   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Nest.VerbatimDictionaryKeysJsonConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer) in C:\users\russ\source\elasticsearch-net\src\Nest\CommonAbstractions\SerializationBehavior\GenericJsonConverters\VerbatimDictionaryKeysConverter.cs:line 35
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Nest.JsonNetSerializer.Serialize(Object data, Stream writableStream, SerializationFormatting formatting) in C:\users\russ\source\elasticsearch-net\src\Nest\CommonAbstractions\SerializationBehavior\JsonNetSerializer.cs:line 59
   at Elasticsearch.Net.ElasticsearchSerializerExtensions.SerializeToBytes(IElasticsearchSerializer serializer, Object data, SerializationFormatting formatting) in C:\users\russ\source\elasticsearch-net\src\Elasticsearch.Net\Serialization\IElasticsearchSerializer.cs:line 25
   at Nest.BulkRequestJsonConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer) in C:\users\russ\source\elasticsearch-net\src\Nest\Document\Multiple\Bulk\BulkRequestJsonConverter.cs:line 33
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Nest.JsonNetSerializer.Serialize(Object data, Stream writableStream, SerializationFormatting formatting) in C:\users\russ\source\elasticsearch-net\src\Nest\CommonAbstractions\SerializationBehavior\JsonNetSerializer.cs:line 59
   at Elasticsearch.Net.PostData`1.<WriteAsync>d__17.MoveNext() in C:\users\russ\source\elasticsearch-net\src\Elasticsearch.Net\Transport\PostData.cs:line 149
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Elasticsearch.Net.HttpConnection.<RequestAsync>d__7`1.MoveNext() in C:\users\russ\source\elasticsearch-net\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Elasticsearch.Net.RequestPipeline.<CallElasticsearchAsync>d__66`1.MoveNext() in C:\users\russ\source\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 421
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Elasticsearch.Net.Transport`1.<RequestAsync>d__15`1.MoveNext() in C:\users\russ\source\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 128
```

**Comment by Mpdreamz** [comment]
What does your `updates` class look like?

**Comment by shonaw** [comment]
Hi Martijn,

Sorry for the delay, thank you for looking into this!

This is the declaration of “updates”:
var updates = new Dictionary<string, KeyValuePair<string, GrainState>>();

The string key of the dictionary is the id of the object, the string key in the key value pair is a string containing the type and GrainState is on MS Orleans class containing the data I want to be the document in elastic search

If it helps here is the full method where I build “updates” from a concurrent dictionary of the same shape called  _pendingUpdates which I do to make sure to not be affected by concurrent access to _pendingUpdates while I do my bulk insert.  Here is the full function:

            // pull the data out of the concurrent dictionary safely and then do the updates against that
            var updates = new Dictionary<string, KeyValuePair<string, GrainState>>();

            var keys = _pendingUpdates.Keys.ToList();
            foreach (var key in keys)
            {
                KeyValuePair<string, GrainState> pair;
                if (_pendingUpdates.TryRemove(key, out pair))
                {
                    updates.Add(key, pair);
                }
            }

            try
            {
                if (updates.Count() > 0)
                {
                                                                                var bulkRequest = new BulkRequest(“runtime”);
                                                                                var indexOps = updates
                                                                                                .Select(o => new BulkIndexOperation<object>(o.Value.Value)
                                                                                                {
                                                                                                                Id = o.Key,
                                                                                                                Type = o.Value.Key
                                                                                                })
                                                                                                .Cast<IBulkOperation>()
                                                                                                .ToList();
                                                                                bulkRequest.Operations = indexOps;

                                                                                var result = await _client.BulkAsync(bulkRequest);

                                                                                if (!result.IsValid)
                                                                                {
                                                                                                if (result.CallDetails.HttpStatusCode.HasValue && (int)result.CallDetails.HttpStatusCode == 429)
                                                                                                {
                                                                                                                // We are pushing too hard, delay and ask again
                                                                                                                for (int i = 0; i < NumRetries; i++)
                                                                                                                {
                                                                                                                                await Task.Delay(TimeBetweenRetry);
                                                                                                                                result = await _client.BulkAsync(bulkRequest);
                                                                                                                                if (result.IsValid)
                                                                                                                                                return;
                                                                                                                }
                                                                                                }

                                                                                                throw new EsResultInvalidException(result.ServerError.Error, result.CallDetails.RequestBodyInBytes);
                                                                                }

                }
            }
            catch (Elasticsearch.Net.UnexpectedElasticsearchClientException e)
            {
                // Caught Elastic search exception here
            }


Thank you,
Shona

**Comment by shonaw** [comment]
Hi,

I just wanted to follow-up on this issue.  It is becoming a bigger issue for us as we are pumping more data in through a bulk insert.

Do you have any suggestions on what we could do to mitigate the problem?

Thank you,
Shona


From: Shona Weldon
Sent: April 5, 2016 3:24 PM
To: 'elastic/elasticsearch-net' <reply@reply.github.com>
Subject: RE: [elastic/elasticsearch-net] Collection was modified; enumeration operation may not execute. (#1984)

Hi Martijn,

Sorry for the delay, thank you for looking into this!

This is the declaration of “updates”:
var updates = new Dictionary<string, KeyValuePair<string, GrainState>>();

The string key of the dictionary is the id of the object, the string key in the key value pair is a string containing the type and GrainState is on MS Orleans class containing the data I want to be the document in elastic search

If it helps here is the full method where I build “updates” from a concurrent dictionary of the same shape called  _pendingUpdates which I do to make sure to not be affected by concurrent access to _pendingUpdates while I do my bulk insert.  Here is the full function:

            // pull the data out of the concurrent dictionary safely and then do the updates against that
            var updates = new Dictionary<string, KeyValuePair<string, GrainState>>();

            var keys = _pendingUpdates.Keys.ToList();
            foreach (var key in keys)
            {
                KeyValuePair<string, GrainState> pair;
                if (_pendingUpdates.TryRemove(key, out pair))
                {
                    updates.Add(key, pair);
                }
            }

            try
            {
                if (updates.Count() > 0)
                {
                                                                                var bulkRequest = new BulkRequest(“runtime”);
                                                                                var indexOps = updates
                                                                                                .Select(o => new BulkIndexOperation<object>(o.Value.Value)
                                                                                                {
                                                                                                                Id = o.Key,
                                                                                                                Type = o.Value.Key
                                                                                                })
                                                                                                .Cast<IBulkOperation>()
                                                                                                .ToList();
                                                                                bulkRequest.Operations = indexOps;

                                                                                var result = await _client.BulkAsync(bulkRequest);

                                                                                if (!result.IsValid)
                                                                                {
                                                                                                if (result.CallDetails.HttpStatusCode.HasValue && (int)result.CallDetails.HttpStatusCode == 429)
                                                                                                {
                                                                                                                // We are pushing too hard, delay and ask again
                                                                                                                for (int i = 0; i < NumRetries; i++)
                                                                                                                {
                                                                                                                                await Task.Delay(TimeBetweenRetry);
                                                                                                                                result = await _client.BulkAsync(bulkRequest);
                                                                                                                                if (result.IsValid)
                                                                                                                                                return;
                                                                                                                }
                                                                                                }

                                                                                                throw new EsResultInvalidException(result.ServerError.Error, result.CallDetails.RequestBodyInBytes);
                                                                                }

                }
            }
            catch (Elasticsearch.Net.UnexpectedElasticsearchClientException e)
            {
                // Caught Elastic search exception here
            }


Thank you,
Shona

**Comment by russcam** [comment]
@shonaw What does `Acaveo.Sis.DataAccess.ElasticSearch.EsOrleansDataProvider.<BulkUpdateOfPending>d__23.MoveNext()` do in `EsOrleansDataProvider.cs`, line 153?

Based on the stack trace, a collection is being modified whilst it is being enumerated. The enumerating looks to be happening at the point of serializing the collection of bulk operations, which contain, amongst other types, an Orleans [`GrainState`](https://github.com/dotnet/orleans/blob/cc90465640710d82b2fc40bc9749af992faf41cf/src/Orleans/CodeGeneration/GrainState.cs#L12). 

It looks like the `GrainState` state gets serialized as a `Dictionary<string, object>`, which Nest uses the [`VerbatimDictionaryKeysJsonConverter`](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Nest/CommonAbstractions/SerializationBehavior/GenericJsonConverters/VerbatimDictionaryKeysConverter.cs) to serialize, enumerating the `DictionaryEntry`s in the dictionary in the process, but the `GrainState` is changed whilst the collection is being enumerated, hence the exception.

A couple of suggestions:

1. Take a deep copy/clone the `GrainState` before indexing and index the copies
2. Write a custom `JsonConverter` to serialize `GrainState` that accommodates the fact that their state may be constantly changing.

**Comment by shonaw** [comment]
Thank you for your suggestions!  

In the mean time we had re-implemented that code using calls that went straight to ES through an httpclient and numerous other changes.  In doing so we must have changed the code sufficiently such that the grainstate is no longer being modified.  It's working for us now with the httpclient.

Thank you for your support.
