### ISSUE TITLE
Obsolete parameters and APIs that are removed in Elasticsearch 5.0

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#1988]
`_timestamp`
`_ttl`

...etc

**Comment by gmarz** [comment]
I've linked a few issues here for the major stuff we need to mark obsolete, but we can also use the [breaking + v5.0.0 label](label:Breaking label:v5.0.0 ).

**Comment by niemyjski** [comment]
Can you also mark all these obsolete in 1.x client as well as anything obsoleted in 2.x This will make upgrading much much easier.

**Comment by Mpdreamz** [comment]
Should not forget Script(string) removal

https://github.com/elastic/elasticsearch-net/blob/2.x/src/Nest/Document/Single/Update/UpdateRequest.cs#L84

**Comment by russcam** [comment]
I'm going to close this now; I think we have covered off the main ones
