### ISSUE TITLE
error code: 400

### ISSUE THREAD

**Issue by neverlose** [elastic/elasticsearch-net#1993]
**Version information:**
*Request:*
http://5.9.16.112:9200/
*Response:*
{
  "name" : "maps",
  "cluster_name" : "vv",
  "version" : {
    "number" : "2.1.1",
    "build_hash" : "40e2c53a6b6c2972b3d13846e450e66f4375bd71",
    "build_timestamp" : "2015-12-15T13:05:55Z",
    "build_snapshot" : false,
    "lucene_version" : "5.3.1"
  },
  "tagline" : "You Know, for Search"
}

**Error information:**
*Request:*
http://5.9.16.112:9200/user_1422512278/mail/59151?fields=to_id
*Response:*
{"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[maps][5.9.16.112:9300][indices:data/read/get[s]]"}],"type":"number_format_exception","reason":"For input string: \"\""},"status":400}
*Expected:*
Document information with fields parameter, containing *to_id* field (which presents in document)

**Document information:**
*Request:*
http://5.9.16.112:9200/user_1422512278/mail/59151
*Response:*
http://pastebin.com/E7EqXA09

**Comment by russcam** [comment]
@neverlose, Would you be able to provide clearer and more specific details here please - it's difficult to decipher what the problem you're seeing is. 

It looks like it's related to the response containing a value of `""` for the `to_id` field, a field that is expected to be a `number` type of some description, and hence is throwing a parse exception in Elasticsearch (sounds like your mappings for the `mail` type in index `user_1422512278` may be incorrect).

**Comment by neverlose** [comment]
to_id field type is number (in mapping)
