### ISSUE TITLE
Remove deprecated queries

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch-net#1996]
https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_search_changes.html#_deprecated_queries_removed

We should also make sure we mark them as obsolete in 2.x (per #1988).

**Comment by russcam** [comment]
Marked as obsolete in 2.x in https://github.com/elastic/elasticsearch-net/commit/b4a7cd445eb2229eddf002380f5703bf9fcdf3ec
