### ISSUE TITLE
Graph/reindex support

### ISSUE THREAD

**Issue by SeanFarrow** [elastic/elasticsearch-net#2015]
**NEST/Elasticsearch.Net version**:

**Elasticsearch version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide `DebugInformation` (if relevant)**:

**Describe the feature**:
Hi,

What is the timeframe for supporting the graph/reindex functionality?
Kind regards
Sean.

**Comment by Mpdreamz** [comment]
I just opened a PR for `reindex` `update by query` `tasks list` and `task cancel` api support in #2017 

we will release this under `NEST 2,2` either friday or beginning next week. 

Tomorrow i'm tackling the Graph API, depending on how fast that goes it'll make it into `NEST 2.2` or we will have to do a separate `NEST 2.3` release at the end of next week
