### ISSUE TITLE
DeleteMapping is still referenced in the docs even though it's no longer supported.

### ISSUE THREAD

**Issue by JoshMcCullough** [elastic/elasticsearch-net#2020]
E.g. https://github.com/elastic/elasticsearch-net/search?utf8=%E2%9C%93&q=deletemapping

**Comment by gmarz** [comment]
Hey @JoshMcCullough those are the old docs.  The new docs are at https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/index.html

@russcam can we kill the old docs directory now?

**Comment by JoshMcCullough** [comment]
Ah, thanks.

**Comment by russcam** [comment]
@gmarz I'll look at cleaning up the docs directory today. 

@Mpdreamz, can the azure site files e.g. Jade templates, Markdown files, etc. be removed too?

**Comment by russcam** [comment]
I've deleted the old docs from `1.x` now; will simplify the directory structure for documentation as part of https://github.com/elastic/elasticsearch-net/issues/1961
