### ISSUE TITLE
ToTimeUnit() in Elasticsearch.Net converts to years

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#2022]
Should `ToTimeUnit()` still convert `TotalMilliseconds` to years? 

It currently doesn't convert to months and It seems we should also not convert to years, converting to weeks as the largest time unit.

**Comment by gmarz** [comment]
:+1: It should match the logic in [Time.Reduce()[(https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/CommonOptions/TimeUnit/Time.cs#L155).
