### ISSUE TITLE
How to pass raw query to elastic search.

### ISSUE THREAD

**Issue by nasreekar** [elastic/elasticsearch-net#2023]
NEST version: NEST.2.1.1
Elastic Search Version : Elasticsearch 2.3.1

I have a query like below.

```
{
        "size" : 10,    
        "query" : {
            "match" : {
                "bodyContent" : "singapore" 
            }
        }
 }
```

I converted it into a string.
```
string query = @{
        ""size"" : 10,    
        ""query"" : {
            ""match"" : {
                ""bodyContent"" : ""singapore"" 
            }
        }
    };

```
then im sending this as a parameter.

```
 var result = client.Search<Class1>(s => s
                         .From(0)
                         .Size(10)
                         .QueryRaw(query)
                     );
```
But the compiler says it Class1 doesnt contain QueryRaw.

Class1.

```
 public class Class1
    {
        [JsonProperty("key")]
        public string key { get; set; }

        [JsonProperty("doc_count")]
        public int doc_count { get; set; }
    }

```
Can you please help me in solving this

**Comment by russcam** [comment]
There is no `QueryRaw` in NEST 2.x (_as the compiler indicates_ :smile: ). You can use `.Raw()` on `QueryContainerDescriptor<T>`

```c#
client.Search<Class1>(s => s
	.Size(10)
	.Query(q => q
		.Raw(@"{ 
			""match"" : {
            	""bodyContent"" : ""singapore"" 
        	} 
		}")
	)
);
```

**Note** that this is only the query element of the query, so `.From()` and `.Size()` etc need to be set outside.

We try to reserve github issues for bugs and issues with the client; the best place to ask these kinds of questions is probably [our discuss forum](https://discuss.elastic.co/).

**Comment by nasreekar** [comment]
thanks for the reply.. will try that...
