### ISSUE TITLE
position_offset_gap renamed to position_increment_gap

### ISSUE THREAD

**Issue by stromblom** [elastic/elasticsearch-net#2027]
Elastic version: 2.2.0
Nest version: 2.1.0

When setting position_offset_gap on the StringAttribute Elastic will generate an error on the PUT:

"Mapping definition for [names] has unsupported parameters:  [position_offset_gap : 100]"

Seems it has been renamed to: position_increment_gap

https://www.elastic.co/guide/en/elasticsearch/reference/2.2/release-notes-2.0.0-beta2.html#breaking-2.0.0-beta2

**Comment by gmarz** [comment]
Thanks for the heads up @stromblom, we'll fix this asap.

**Comment by gmarz** [comment]
Closed via https://github.com/elastic/elasticsearch-net/commit/48a22004b99a4dd81f76063fc83a9c64ee7066ac and https://github.com/elastic/elasticsearch-net/commit/20903693f82b3fa1a3b7468b689b5568a9162627
