### ISSUE TITLE
rc2 Compatability

### ISSUE THREAD

**Issue by levia7han** [elastic/elasticsearch-net#2032]
Is there a time frame on ASPNet Core or rc2 compatibility? I see you are using rc1, but several of the packages I use have migrated to rc2 which forced me to upgrade.

**Comment by Mpdreamz** [comment]
We definitely will but rc2 itself is in a state of flux at the moment, see: https://github.com/aspnet/Home/wiki/Roadmap

We will open a branch to move to rc2 and probably start publishing prereleases to a temporary myget feed once we tackle it. Currrently getting ready for the 5.0.0-alpha1 from Elasticsearch and supporting all the x-pack features in 2.3 has our highest priority.

**Comment by levia7han** [comment]
Awesome, Thanks.
