### ISSUE TITLE
OmitNorms and Type Attribute mapping missing in Nest >= 2.0

### ISSUE THREAD

**Issue by yaskamal** [elastic/elasticsearch-net#2033]
Hi,

I cant see the `OmitNorms` and Type attribute anymore while mapping the property in a class.
I have a generic method that creates elastic search index and I  pass different types to create Index.

Not having `OmitNorms` as an attribute means I need to manually map as following:

```c#
Map<Employee>(m => m
            // infer mappings based on POCO property types and take into
            // account attribute mappings
            .AutoMap()
            // override certain inferred or attribute based mappings
            // from Automapping
            .Properties(ps => ps
                .String(s => s
                    .Name(c => c.Name) 
                    // omit norms equivalent in Elasticsearch >= 2.0 
                    .Norms(n => n
                        .Enabled(true)
                    )
                )
            )
```
Also I have double field how should I map double now, I used to use earlier Nest version <  2 :
[ElasticProperty(Type = FieldType.Double, DocValues = true)]
public double value { get; set; }

Is there a generic way where i can set `OmitNorms` and Field Type for all types passed as `<T>`.

It would be really nice to have the `OmitNorms` and Type attribute mapping in new NEST version as well.

**Comment by russcam** [comment]
Yes, there is, using an implementation of [`IPropertyVisitor`](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/auto-map.html#applying-conventions-through-the-visitor-pattern)

```c#
public class OmitNormsPropertyVisitor : NoopPropertyVisitor
{
	public override void Visit(
		IStringProperty type,
		PropertyInfo propertyInfo,
		ElasticsearchPropertyAttributeBase attribute)
	{
		type.Norms = new Norms { Enabled = false };
	}
}
```

then

```c#
.Map<Employee>(m => m
    .AutoMap(new OmitNormsPropertyVisitor())
)
```

you could also [apply the convention through an index template](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-templates.html)

```c#
var putTemplateResult = this.Client.PutIndexTemplate("raw_fields", p => p
	.Template("*") //match on all created indices
	.Settings(s => s
		.NumberOfReplicas(0)
		.NumberOfShards(2)
	)
	.Mappings(pm => pm
		.Map("_default_", m => m
			.DynamicTemplates(dt => dt
				.DynamicTemplate("omit_norms", dtt => dtt
					.Match("*") //matches all fields
					.MatchMappingType("string") //that are a string
					.Mapping(tm => tm
						.String(s => s
							.Norms(n => n
								.Enabled(true)
							)
						)
					)
				)
			)
		)
	)
);
```

**Comment by yaskamal** [comment]
@russcam thanks a ton mate...this is what i was looking.
New NEST is really killing me but I appreciate the good work going with new version.

**Comment by russcam** [comment]
I'm afraid I don't understand your point - `client.CreateIndex()` and `client.Map<T>` _*are*_ generic ways to create indexes and mappings. 

You can also apply settings and mappings for any type `T` with index templates e.g.

```c#
this.Client.PutIndexTemplate("project_template", p => p
	//match on all created indices
	.Template("*") 
	.Settings(s => s
		.NumberOfReplicas(0)
		.NumberOfShards(2)
	)
	// map project type
	.Mappings(pm => pm
		.Map<Project>(m => m.AutoMap())
	)
);
```
