### ISSUE TITLE
Bulk index flexible data structure (dictionary) with specified ID 

### ISSUE THREAD

**Issue by avoxm** [elastic/elasticsearch-net#2037]
I am bulk indexing flexible data structure through utilization of Dictionary. I load data from data store into dictionary and one of the dictionary items is the id. How can I specify that id to be the index id.

Here is the sample code 
                    Dictionary<string, string> data = new Dictionary<string,string>();

                    data.Add("Id", "10");
                    data.Add("Age", "25");
                    data.Add("Name", "Joe");

                    var list = new List<Dictionary<string, string>>();
                    list.Add(data);

                    var result = client.IndexMany<Dictionary<string, string>>(list, "test", "test_type");

Is there a way to specify the id field or may be another workaround ?

**Comment by gmarz** [comment]
Not using the `IndexMany()` shortcut.  You'll have to use `Bulk()` directly:

```csharp
client.Bulk(b =>
{
	foreach(var doc in list)
		b.Index<Dictionary<string, string>>(i => i.Document(doc).Id(doc["Id"]).Index("test").Type("test_type"));
	return b;
});

```

**Comment by gmarz** [comment]
Closing.  Feel free to re-open @avoxm if the above doesn't work for you.
