### ISSUE TITLE
Reindex API

### ISSUE THREAD

**Issue by kbentz** [elastic/elasticsearch-net#2039]
Elasticsearch released their new [Reindex API](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/docs-reindex.html) in Elasticsearch 2.3.0, does the latest version of NEST (2.2.0) make use of this API yet? If not, are there any plans to do so? 
I am aware that the current client has a reindex method, but it forces you to create the new index at the time of reindexing. For my use case, the index already exists, so it's not very useful..

**Comment by Mpdreamz** [comment]
We already have the reindex API mapped as per #2017 which also lands the other new API's from Elasticsearch 2.3. 

We're still adding the XPack related API's around graph, license and shield which I hope will land in `2.x` branch early next week and in `NEST 2.3` end of next week :)

The new reindex API will be mapped as `ReindexOnServer()` as our Reindex() is still very useful.

Our Reindex() should expose a way that assumes the index exists already, that's a great feature request :+1:

**Comment by wjonesy** [comment]
@Mpdreamz Did this function get implemented? 'Our Reindex() should expose a way that assumes the index exists already'

**Comment by Mpdreamz** [comment]
It did not. Created a new ticket for it: https://github.com/elastic/elasticsearch-net/issues/2164

PR's are welcome if you fancy a challenge :+1:
