### ISSUE TITLE
CancellationToken Parameter for Async Methods

### ISSUE THREAD

**Issue by alanprot** [elastic/elasticsearch-net#2042]
**Describe the feature**:
Why don't add a CancellationToken Parameter (overload) to the async methods like:

`Task<ISearchResponse<T>> SearchAsync<T>(Func<SearchDescriptor<T>, ISearchRequest> selector = null) where T : class;`

**Comment by Mpdreamz** [comment]
You can add a cancellation token on the request configuration per request. For 5.0 we might add it as a third optional parameter to make it more discoverable. 

@gmarz @forloop thoughts?

**Comment by gmarz** [comment]
+1

**Comment by russcam** [comment]
+1 We should add it to async methods to make it more discoverable e.g.

```c#
Task<ISearchResponse<T>> SearchAsync<T>(
    Func<SearchDescriptor<T>, ISearchRequest> selector = null,
    CancellationToken cancellationToken = default(CancellationToken)) where T : class;
```
