### ISSUE TITLE
Memory leak in FieldResolver

### ISSUE THREAD

**Issue by alwag85** [elastic/elasticsearch-net#2048]
**NEST 2.0+**:

If `Nest.Field` was created by `LambdaExpression` then `MemberExpression.GetHashcode()` used as Hashcode for dictionary `FieldResolver.Fields`, but method `GetHashcode` has not overridden in `MemberExpression` and used `Object.GetHashcode()`.

**Comment by rasmus** [comment]
+1

**Comment by tabro** [comment]
Aggreed - this one is sucking up alot of memory on our webservers.

**Comment by krjensen** [comment]
+1, eating up gigs of memory

**Comment by Mpdreamz** [comment]
:-1: us first for missing the issue when initially reported and second for introducing this in the first place :cry: 

We will get this fixed today and put an update out on nuget.org

**Comment by russcam** [comment]
Just pushed new versions of [Elasticsearch.Net](https://www.nuget.org/packages/Elasticsearch.Net/) and [NEST](https://www.nuget.org/packages/NEST/2.3.1) to nuget with a fix for this.

Thanks again for reporting :+1:
