### ISSUE TITLE
Verbatim() not working

### ISSUE THREAD

**Issue by mamasselin** [elastic/elasticsearch-net#2049]
**NEST/Elasticsearch.Net version**: 2.2.0

**Elasticsearch version**: 2.2.0

**Description of the problem including expected versus actual behavior**:

Using a MustNot bool query, i'm trying to filter out records where a string field (not analyzed) exists, but is empty ("").

```
.Bool(b => b.MustNot(mn  => mn.Verbatim().Term(t => t.Field(x => x.MyField).Value(""))))
```

This erases the whole boolean query from the JSON sent to ElasticSearch, event though I have Verbatim specified.

When putting any value other than empty string, it shows up in the JSON

EDIT:
As a workaround, I use Raw() and it does work:
```
.Bool(b =>b.MustNot(mn => mn.Raw("{\"query\": {\"term\": {\"myField\": {\"value\": \"\"}}}}")))
```

**Comment by gmarz** [comment]
Hi @mamasselin I currently have https://github.com/elastic/elasticsearch-net/pull/2021 open which aims to fix this, but it still needs some work.  It will most likely make it into the 2.4 release.

Closing in favor of #1898 and #1876
