### ISSUE TITLE
Cannot create Index with HunspellTokenFilter in Nest c# Elastic

### ISSUE THREAD

**Issue by shoibmohamad** [elastic/elasticsearch-net#2056]
I am having trouble in creating index if I use HunspellTokenFilter 
I have tried with different ways given in test.txt file. can somebody describe how to add HunspellTokenFilter 

please use notepad++ to view these files.

My actual need was to create a Multi Field property with Hunspell filter like in attached StructureOfIndex file

[StructureOfIndex.txt](https://github.com/elastic/elasticsearch-net/files/230180/StructureOfIndex.txt)
[Test.txt](https://github.com/elastic/elasticsearch-net/files/230165/Test.txt)

**Comment by Mpdreamz** [comment]
You were very close in your `test.txt`

add the token filter:

```csharp
.Add("Stemmer", new HunspellTokenFilter
{
	 Dedup = true,
	 Locale = "en_US"
})
```

add the analyzer: 

```csharp
.Add("key", new CustomAnalyzer
{
	Tokenizer = "standard",
	Filter = new List<string> { "lowercase", "english_stop", "TokenSingle", "keyword_repeat", "Stemmer", "unique", "ThreeChar" }
})
```

Then apply the analyzer but instead of add a multifield like this:

```charp
.String(ps => ps.Name(pn => pn.ProductDescription.Suffix("keyword")).Analyzer("key"))
```

use `.Fields()`

```csharp
.String(ps => ps
	.Name(pn => pn.ProductDescription)
	.Fields(f=>f
		.String(s => s
			.Name("raw")
		.	Analyzer("key")
		)
	)
)
```

Hope this helps! and appologies for leaving this ticket open for so long!
