### ISSUE TITLE
Add a Query method that accepts a QueryContainer

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch-net#2057]
**Describe the feature**:

https://github.com/elastic/elasticsearch-net/blob/8f08e086f234f8ceeeb1742b215cd6e18e0007e7/src/Nest/Search/Search/SearchRequest.cs#L393-L394

The query method expects a func, while in previous versions one was able to just pass a descriptor as well:

```
		public SearchDescriptor<T> Query(Func<QueryContainerDescriptor<T>, QueryContainer> query) =>
			Assign(a => a.Query = query?.InvokeQuery(new QueryContainerDescriptor<T>()));
```

We should add a method that accepts a `QueryContainer`.

**Comment by russcam** [comment]
It's possible to ignore the descriptor and return an already constructed `QueryContainer`

```c#
var client = new ElasticClient();
var termsQuery = Query<Project>.Terms(t => t.Field(p => p.Name).Terms("name1", "name2"));

client.Search<Project>(s => s.Query(_ => termsQuery));
```

An overload might be a little cleaner though /cc @Mpdreamz, @gmarz

**Comment by gmarz** [comment]
-1 otherwise it becomes inconsistent with all of the other methods which take funcs.  It can easily be achieved with the above example from @russcam, and added as an extension method.

**Comment by Mpdreamz** [comment]
Agreed, it is possible and otherwise we let the OIS and fluent syntax styles bleed too much into one another
