### ISSUE TITLE
How do i use DateMath type in DateRange?

### ISSUE THREAD

**Issue by hodgezappa** [elastic/elasticsearch-net#2058]
Nest version 2.1.1, Elasticsearch.Net version 2.1.1
Elasticsearch version 2.3.0

How do I convert a DateTime variable or even a string to a DateMath type, so I can then pass this type to the DateRange aggregation?  Can someone give me an example?

**Comment by Mpdreamz** [comment]
See our documentation on [DateMath](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/date-math-expressions.html)

Both of them implicitly convert to DateMath:

https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/CommonOptions/DateMath/DateMath.cs#L38-L39

**Comment by hodgezappa** [comment]
Ah maybe i'm getting the wrong end of the stick then, i'm passing my DateTime variables (example value is 31/03/2016 00:00:00)  in to DateRange like this:
` q.DateRange(r => r.Field("MyFieldEventDateTime").GreaterThan(startDate).LessThan(endDate))`
but I get this exception:
`\"parse_exception\",\"reason\":\"failed to parse date field [2015-04-01T00:00:00] with format [yyyy-MM-dd HH:mm:ss||yyyy-MM-dd]\",\"caused_by\":{\"type\":\"illegal_argument_exception\",\"reason\":\"Invalid format: \\\"2015-04-01T00:00:00\\\" is malformed at \\\"T00:00:00\\\"\"}}}]},\"status\":400}\r\n"`
