### ISSUE TITLE
Re-evaluate Property Type Hierarchy

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#2059]
`text` fields do not support docvalues just as [analyzed string fields](https://github.com/elastic/elasticsearch/issues/10061) did not in `2.x` but now that we have an explicit split of string to `text` and `keyword` this leaves `DocValues()` exposed on our `keyword` mapping.

**Comment by gmarz** [comment]
>  this leaves DocValues() exposed on our `keyword` mapping

I think you mean `text` mapping?

**Comment by Mpdreamz** [comment]
Doh! yeah

**Comment by russcam** [comment]
Started moving `IProperty` properties around to accommodate the `percolator` type in https://github.com/elastic/elasticsearch-net/pull/2063. Be a good opportunity to refactor this further

**Comment by Mpdreamz** [comment]
Comment from @gmarz on PR #2063 

>Few minor nitpicks but overall LGTM :+1: . I'm +1 on ICoreProperty, but I think there are a few instances where it exposes properties that aren't valid for a type (e.g. TextProperty.DocValues). There could be other instances as well. We should re-evaluate all of our types as part of #2059, but I'm cool with this for alpha1.

We should do a full sweep on our mapping API to be make sure its not introducing bad abstract base classes.

**Comment by gmarz** [comment]
Closed via #2337
