### ISSUE TITLE
Add 504 to default retry status codes

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#2061]
We only retry by default on 502 and 503.

https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Responses/ElasticsearchResponse.cs#L75

Elasticsearch PY only retries on 503. 504

https://github.com/elastic/elasticsearch-py/blob/6e94bf76adbbbb2fe5b927a3933ed535cd738387/elasticsearch/transport.py#L70

perl only on 503. 

I think it makes sense to also add 504 to the list

**Comment by Mpdreamz** [comment]
The reason we don't simply retry on `>=500` is because `500` can be used to signal valid bad states that should not be retried:

https://github.com/elastic/elasticsearch/search?p=1&q=INTERNAL_SERVER_ERROR&utf8=%E2%9C%93

Which I think is the correct status code, @elastic/es-clients do you see different HTTP status codes Elasticsearch could be returning in the previous cases, clearing the 500 range? Do we all want/need to settle on `502, 503, 504` collectively?

**Comment by clintongormley** [comment]
> Do we all want/need to settle on 502, 503, 504 collectively?

+1

**Comment by HonzaKral** [comment]
+1, will add it to python, do we also want to document it in ES itself for ES devs and other client authors? Where would be a good place?
