### ISSUE TITLE
Certificate validation on Core CLR

### ISSUE THREAD

**Issue by yorkie-m** [elastic/elasticsearch-net#2062]
Is there a way of intercepting certificate validation when using the NEST Client (2.1.1) and .NET Core (dnxcore50) to query an ElasticSearch server using a self-signed certificate?

The documentation states that ServicePointManager cannot be used and asks for an issue to be raised if support is required:

https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/connecting.html

Thanks in advance
Mark.

**Comment by russcam** [comment]
Hey @yorkie-m, there's currently no way to do this for the core clr build; core clr uses `System.Net.Http.HttpClient` that doesn't by itself expose a way to accept invalid certificates but it is [possible with an `IHttpFilter`](https://github.com/onovotny/WinRtHttpClientHandler) from ` Windows.Web.Http`.

What's your use case?

**Comment by yorkie-m** [comment]
Ok thanks. I've solved the immediate problem by using a valid certificate in our Dev environment. We want to target non Windows platforms so I guess that rules out IHttpFilter.  Thanks for coming back to me.

**Comment by russcam** [comment]
You could implement your own [`IConnection`](https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Connection/IConnection.cs) if the need arises, then pass that to the constructor of `ConnectionSettings` e.g.

```c#
public class MyConnection : IConnection
{
    Task<ElasticsearchResponse<TReturn>> RequestAsync<TReturn>(RequestData requestData)
			where TReturn : class
    {
        // implementation...
    }

    ElasticsearchResponse<TReturn> Request<TReturn>(RequestData requestData)
			where TReturn : class
    {
        // implementation...
    }
}


var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
var connectionSettings = new ConnectionSettings(pool, new MyConnection());
var client = new ElasticClient(connectionSettings);
```
