### ISSUE TITLE
Attribute-based geo_point mapping does not work

### ISSUE THREAD

**Issue by benchaikin** [elastic/elasticsearch-net#2067]
**NEST/Elasticsearch.Net version**: 2.3.0

**Elasticsearch version**: 1.5.2 (AWS elasticsearch)

**Description of the problem including expected versus actual behavior**:
Attribute-based mapping of a geo_point using the GeoLocation type does not produce a correct mapping. Behavior is the same with or without an explicit attribute. Setting the property as a GeoPoint via the fluent mapping API works as expected.

**Steps to reproduce**:
 1. Add a GeoLocation property to class to be indexed
 2. Optionally add the [GeoPoint] attribute (looking at the code this should be inferred for a GeoLocation anyway)
 3. Add instances of the domain object to the index
 4. Perform a search / GeoDistance sort against the index using the GeoLocation field. 

**Provide `DebugInformation` (if relevant)**:
Domain class:

`public class Product
    {
        [GeoPoint]
        public GeoLocation SomePoint { get; set; }
        public double Price { get; set; }
    }`
    
Generated mapping (incorrect):
`Mapping: 
price: double
somePoint {
   lat: double
   lon: double }
`

Query:
`[  
   {  
      "sort":[  
         {  
            "_geo_distance":{  
               "somePoint":[  
                  {  
                     "lat":40.7,
                     "lon":-74.0
                  }
               ]
            }
         }
      ],
      "query":{  
         "bool":{  
            "must":[  
               {  
                  "range":{  
                     "price":{  
                        "gt":1.0
                     }
                  }
               }
            ]
         }
      }
   }
]`

Exception: : ElasticsearchIllegalArgumentException[failed to find mapper for [somePoint] for geo distance based sort

**Comment by russcam** [comment]
Hey @benchaikin, [NEST and Elasticsearch.Net 2.x (including 2.3.0) are not compatible with Elasticsearch 1.x (including 1.5.2)](https://github.com/elastic/elasticsearch-net#compatibility-matrix).

For Elasticsearch 1.5.2, take a look at [NEST 1.8.0](https://www.nuget.org/packages/NEST/1.8.0), the latest 1.x compatible client.

**Comment by russcam** [comment]
@benchaikin, have you tried the `geo_point` mapping using NEST 1.8.0?

**Comment by russcam** [comment]
Closing. Feel free to re-open @benchaikin  if this is still an issue.
