### ISSUE TITLE
Expose TypeName in IGetMappingResponse

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#2072]
[The current implementation of `IGetMappingResponse`](https://github.com/elastic/elasticsearch-net/blob/9cab2174dd988fb8cf6b440fdd24d32517eab5b0/src/Nest/Indices/MappingManagement/GetMapping/GetMappingResponse.cs#L12) returns a dictionary of index string name and list of `TypeMapping` for the index, but does not expose the `TypeName` to which the `TypeMapping` relates to; so if the request asks for multiple types within a given index, there is no way of correlating the `TypeMapping` back to the type name.

We should expose the `TypeName` along with the `TypeMapping`. Changing the `Mappings` property in 2.x would be a breaking change so we should include another property for this. Maybe

```c#
public interface IGetMappingResponse : IResponse
{
    // .... other properties

    Dictionary<IndexName, IDictionary<TypeName, TypeMapping>> IndexTypeMappings { get; }
}
```

[This came up on stackoverflow](http://stackoverflow.com/questions/36991184/get-elasticsearch-type-mapping-names-with-nest-client#36991184)

**Comment by gmarz** [comment]
@russcam a little confused on the status of this.  #2074 was merged into 2.x and made it into 2.3.1, but #2074 which is targeted at master is still open and in limbo.

Is the change complete for the 2.x branch?  I'm going to remove the 2.3.2 label for now because either the change is done and this should be labeled 2.3.1, or it needs more commits and in that case let's target 2.3.3.

**Comment by russcam** [comment]
#2074 was merged into `2.x` [after the release of 2.3.1](https://github.com/elastic/elasticsearch-net/commits/2.x) so that change will have gone into 2.3.2. The change is complete for 2.x.

Where the `master` change in #2073 is slightly different is that it would be great to return `IndexName` instead of the string for the index name and similarly, `TypeName` instead of a string for the type name. There are a few ways I'd like to explore to see if this would work so have kept #2073 open :smile:
