### ISSUE TITLE
documentation with sample project

### ISSUE THREAD

**Issue by EmilAlipiev** [elastic/elasticsearch-net#2075]
Hi,

There was a nice walk through project here in wiki. If I remember correctly, It was called package finder or something like that. Where is this project? It was really helpful.
was it removed?

thanks,

**Comment by gmarz** [comment]
I'm guessing that you're referring to NuSearch? The repo is here https://github.com/elastic/elasticsearch-net-example

**Comment by EmilAlipiev** [comment]
oh yes, thanks a lot. I have been searching for it all over.
