### ISSUE TITLE
Cat related calls fail when run against Elastic Cloud

### ISSUE THREAD

**Issue by jacobkktan** [elastic/elasticsearch-net#2076]
**NEST/Elasticsearch.Net version**: 2.3.0

**Elasticsearch version**: 2.3.1

From reading codes, I believe the issue is, trying to deserialize plain text to Object. Without diving too much in the code, my biggest suspect is, the wrong serializer used.

-- codes that deserialize the response (for CatAliases) -> NEST/Cat/ElasticClient-Cat.cs line-15. 

**Steps to reproduce**:
1. Connect to elasticsearch that has basic auth (test cases shows most of the time, issue arises when there is basic auth) 
2. Call CatAliases or CatIndices

**DebugInformation**:
[DebugInfo.txt](https://github.com/elastic/elasticsearch-net/files/248018/DebugInfo.txt)

**Comment by russcam** [comment]
Hey @jacobkktan, I tried this locally with [Basic Auth set up with Shield](https://www.elastic.co/guide/en/shield/current/enable-basic-auth.html) against Elasticsearch 2.3.1 and NEST 2.3.0 and can't replicate the issue.

What are you using for basic auth? The `Content-Type` and `Accept` headers are set to `application/json` so the response should be in json. Could you check with something like [Fiddler](http://www.telerik.com/fiddler) to see if this is the case?

**Comment by jacobkktan** [comment]
Hi @russcam 

That's a good point from tracing,

Accept = "application/json"
Content-type="text/plain"

Hope this helps

**Comment by russcam** [comment]
Hmm, looking in the [Cat dispatch in 2.3.0](https://github.com/elastic/elasticsearch-net/blob/7ffbc4f01ea1dfaadc8311d8e78398ced483ae95/src/Nest/Cat/ElasticClient-Cat.cs#L27), the content-type header is set to `application/json`, and this value is [used to set both `Content-Type` and `Accept` headers on the request in `HttpConnection`](https://github.com/elastic/elasticsearch-net/blob/7ffbc4f01ea1dfaadc8311d8e78398ced483ae95/src/Elasticsearch.Net/Connection/HttpConnection.cs#L39-L40) and [`HttpConnecition` for CoreCLR](https://github.com/elastic/elasticsearch-net/blob/7ffbc4f01ea1dfaadc8311d8e78398ced483ae95/src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs#L130).

Are those the headers from the _request_?

**Comment by Oustad** [comment]
Hi, I'm getting the same issue as @jacobkktan callingl CatIndices().
I'm using a hosted elastic cloud instance withbasic auth.
Using the latest 2.*.* version from Nuget.

```
An unhandled exception of type 'Elasticsearch.Net.UnexpectedElasticsearchClientException' occurred in Elasticsearch.Net.dll

Additional information: Unexpected character encountered while parsing value: y. Path '', line 0, position 0. 
```

Calling the same endpoint in postman works fine, but it looks like ` /_cat/indices ` returns a different format than JSON, trying to convert to json inside postman yields a similar error `Unexpected 'y'`
Both Content-Type and Accept headers are set to application/json

**Comment by gmarz** [comment]
@Oustad would you mind posting the raw JSON response here?  Hopefully that may help us repro.

**Comment by Oustad** [comment]
@gmarz This is the raw response I get https://gist.github.com/Oustad/51041b71a1b67233f807247fdd30e9b5#file-response

**Comment by russcam** [comment]
@Oustad This appears to be an issue with Cloud returning a `text/plain` response when a response in `application/json` is requested. I've opened an issue with Cloud to look into.

**Comment by Oustad** [comment]
I see, that makes sense, thanks for looking into it.

**Comment by emmekappa** [comment]
@russcam same issue here. did you solved it?

**Comment by gmarz** [comment]
This is still an open issue with Elastic Cloud.  See https://discuss.elastic.co/t/ielasticclient-cathealth-works-ok-locally-but-fails-in-json-parsing-when-talking-to-elastic-cloud-instance/55431/3 for details and a work around using the low-level client.

We'll keep this issue open in the mean-time to provide updates on the status of the Cloud issue.

**Comment by russcam** [comment]
@jacobkktan, @Oustad, @emmekappa, this issue should now be fixed in Elastic Cloud.

I'm going to close the issue but feel free to reopen if the problem persists.
