### ISSUE TITLE
Elasticsearch Connect Custom Headers in Request

### ISSUE THREAD

**Issue by ChrisFeldmeier** [elastic/elasticsearch-net#2077]
Hi,

ist it possible to add a custom header like "X-ABCD" to every elasticsearch request? 
I could'nt find any option or property to do that.

Can anyone implement this?

Thanks
regards
Chris

**Comment by Mpdreamz** [comment]
This is already possible :smile: Call `GlobalHeaders()` on `ConnectionSettings` to send additional HTTP headers per request.
