### ISSUE TITLE
2.3.1 nuget issues?

### ISSUE THREAD

**Issue by chrisklepeis** [elastic/elasticsearch-net#2079]
I'm using .Net framework 4.6.1 in a WPF application.

When I try to update to the 2.3.1 nuget version I get this error (specifically with the Elasticsearch.Net package):

> Unable to find a version of 'Microsoft.CSharp' that is compatible with 'Elasticsearch.Net 2.3.1 constraint: Microsoft.CSharp (>= 4.0.1-beta-23225)

Looks like either the dependencies of this production package requires beta dependencies? Perhaps this should be a pre-release or the dependencies need to be updated?

**Comment by tomasfalt** [comment]
I got the same error but after I tried update a few times everything start to work suddenly.

**Comment by chrisklepeis** [comment]
I tried it about 10 times. At second glance, I'm not sure whats causing it to get stuck, since the beta dependencies are for .NetPlatform 5.1 (which I believe is .Net Core?) and I believe shouldn't apply to me.

![capture](https://cloud.githubusercontent.com/assets/16291940/15014220/bf1a565e-11d2-11e6-9a9c-6cb50b054972.PNG)

![capture1](https://cloud.githubusercontent.com/assets/16291940/15014235/da5dd076-11d2-11e6-994f-a2ae513c0425.PNG)

**Comment by Mpdreamz** [comment]
We didn't have any dependency changes between 2.3.0 and 2.3.1

https://github.com/elastic/elasticsearch-net/compare/2.3.0...2.3.1

Is this a temporary nuget glitch ?

I just tried it myself succesfully having only `nuget.org` and `Microsoft and .NET` as available package sources.

>
Attempting to gather dependencies information for package 'NEST.2.3.1' with respect to project 'WpfApplication2', targeting '.NETFramework,Version=v4.6.1'
Attempting to resolve dependencies for package 'NEST.2.3.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'NEST.2.3.1'
Resolved actions to install package 'NEST.2.3.1'
Adding package 'Elasticsearch.Net.2.3.1' to folder 'c:\users\mpdreamz\documents\visual studio 2015\Projects\WpfApplication2\packages'
Added package 'Elasticsearch.Net.2.3.1' to folder 'c:\users\mpdreamz\documents\visual studio 2015\Projects\WpfApplication2\packages'
Added package 'Elasticsearch.Net.2.3.1' to 'packages.config'
Successfully installed 'Elasticsearch.Net 2.3.1' to WpfApplication2
Adding package 'Newtonsoft.Json.8.0.1' to folder 'c:\users\mpdreamz\documents\visual studio 2015\Projects\WpfApplication2\packages'
Added package 'Newtonsoft.Json.8.0.1' to folder 'c:\users\mpdreamz\documents\visual studio 2015\Projects\WpfApplication2\packages'
Added package 'Newtonsoft.Json.8.0.1' to 'packages.config'
Executing script file 'c:\users\mpdreamz\documents\visual studio 2015\Projects\WpfApplication2\packages\Newtonsoft.Json.8.0.1\tools\install.ps1'...
Successfully installed 'Newtonsoft.Json 8.0.1' to WpfApplication2
Adding package 'NEST.2.3.1' to folder 'c:\users\mpdreamz\documents\visual studio 2015\Projects\WpfApplication2\packages'
Added package 'NEST.2.3.1' to folder 'c:\users\mpdreamz\documents\visual studio 2015\Projects\WpfApplication2\packages'
Added package 'NEST.2.3.1' to 'packages.config'
Successfully installed 'NEST 2.3.1' to WpfApplication2
========== Finished ==========

Are you using visual studio 2015 update2 ? (im still on update1 although I hope that should not make a difference)

**Comment by chrisklepeis** [comment]
Yes, I'm on visual studio 2015 update 2. Going to try blowing out temporary nuget data and try again.

**Comment by chrisklepeis** [comment]
I deleted the packages folder, didn't work. I also uninstalled Nest and Elasticsearch.Net packages and during my attempt to install 2.3.1 it has the same error, except on one of my projects which is a console application.

I have 5 projects that use it.

The project that I can successfully install it on has these nuget packages:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AWSSDK.Core" version="3.1.5.3" targetFramework="net461" />
  <package id="AWSSDK.DynamoDBv2" version="3.1.3.0" targetFramework="net461" />
  <package id="AWSSDK.S3" version="3.1.5.0" targetFramework="net461" />
  <package id="AWSSDK.SQS" version="3.1.0.6" targetFramework="net461" />
  <package id="Elasticsearch.Net" version="2.3.1" targetFramework="net461" />
  <package id="Microsoft.SqlServer.Types" version="11.0.2" targetFramework="net461" />
  <package id="NEST" version="2.3.1" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="8.0.3" targetFramework="net461" />
  <package id="ServiceStack" version="4.0.56" targetFramework="net461" />
  <package id="ServiceStack.Aws" version="4.0.56" targetFramework="net461" />
  <package id="ServiceStack.Client" version="4.0.56" targetFramework="net461" />
  <package id="ServiceStack.Common" version="4.0.56" targetFramework="net461" />
  <package id="ServiceStack.Interfaces" version="4.0.56" targetFramework="net461" />
  <package id="ServiceStack.OrmLite" version="4.0.56" targetFramework="net461" />
  <package id="ServiceStack.OrmLite.SqlServer" version="4.0.56" targetFramework="net461" />
  <package id="ServiceStack.OrmLite.SqlServer.Converters" version="4.0.56" targetFramework="net461" />
  <package id="ServiceStack.Razor" version="4.0.56" targetFramework="net461" />
  <package id="ServiceStack.Redis" version="4.0.56" targetFramework="net461" />
  <package id="ServiceStack.Server" version="4.0.56" targetFramework="net461" />
  <package id="ServiceStack.Text" version="4.0.56" targetFramework="net461" />
  <package id="SlowCheetah" version="2.5.15" targetFramework="net461" />
</packages>
```


It receives the error from my first post in a class library that has these:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="AWSSDK.Core" version="3.1.5.3" targetFramework="net461" />
  <package id="AWSSDK.DynamoDBv2" version="3.1.3.0" targetFramework="net461" />
  <package id="AWSSDK.S3" version="3.1.5.0" targetFramework="net461" />
  <package id="AWSSDK.SQS" version="3.1.0.6" targetFramework="net461" />
  <package id="Dapper" version="1.42" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="8.0.3" targetFramework="net461" />
  <package id="ServiceStack" version="4.0.56" targetFramework="net461" />
  <package id="ServiceStack.Aws" version="4.0.56" targetFramework="net461" />
  <package id="ServiceStack.Client" version="4.0.56" targetFramework="net461" />
  <package id="ServiceStack.Common" version="4.0.56" targetFramework="net461" />
  <package id="ServiceStack.Interfaces" version="4.0.56" targetFramework="net461" />
  <package id="ServiceStack.OrmLite" version="4.0.56" targetFramework="net461" />
  <package id="ServiceStack.Text" version="4.0.56" targetFramework="net461" />
</packages>
```

I just created a clean class library with the above packages, and receive the same error.

I also tried deleting all nuget cache from %LOCALAPPDATA%\NuGet\Cache\

**Comment by gmarz** [comment]
I'm able to reproduce this.  I've tried from both a class library and wpf application on framework 4.5 and 4.6- both produce the error.  VS 2015 update1, but I don't think that matters.

I'm inclined to think this is a nuget issue.  As @Mpdreamz mentioned, we haven't changed any dependencies from 2.3.0 to 2.3.1.  What's more, if I download the `nupkg` files from nuget.org and install them from a local feed, it works fine.

**Comment by chrisklepeis** [comment]
Too many nuget issues this year. Going to give paket a try.

**Comment by gmarz** [comment]
@chrisklepeis can you make sure you're using [v3 of the nuget.org feed](https://api.nuget.org/v3/index.json)? 

See the comments in the issue linked above.

**Comment by chrisklepeis** [comment]
I was indeed on v2. Updating to the V3 feed worked. Thanks.
