### ISSUE TITLE
Field Descriptor Prefix Function

### ISSUE THREAD

**Issue by Molenx** [elastic/elasticsearch-net#2080]
**NEST/Elasticsearch.Net version**: 2.3.0

**Elasticsearch version**: 2.3.1

**Description of the problem including expected versus actual behavior**:
I am using the couchbase transport plugin to index documents into Elasticsearch, by default it indexes all the fields under doc.*. 

Now that we can not use short filed names in ES, how can we use strongly typed field names in NEST queries and have a prefix setup per field or per type or for all types?

Currently there is a Suffix function to append to field names, but there is no Prefix.

In other words how in NEST now I can get it to prefix all field names with "doc." when using a field descriptor, I can just specify a string filed name in my queries but that is not ideal. 

Here is my NEST query

```
var termQuery = Query<Park>.Term(p => p.IsPublic, true);
ISearchResponse<T> searchResponse = this.client.Search<T>(s => s.Index("parkindex-local-01")
                     .Take(size)
                     .Source(false)
                     .Query(q => termQuery));
```

That would not get results because this will parse field name as "isPublic" but ES needs "doc.isPublic". 

```
{
  "size": 10,
  "_source": {
    "exclude": [
      "*"
    ]
  },
  "query": {
    "term": {
      "isPublic": {
        "value": "true"
      }
    }
  }
}
```

My POCO doesn't really have doc object, IsPublic is a direct property of the Park type, the couchbase plugin created the fields under the "doc" I don't think I can control that either. 

That all used to work in ES 1.x because ES allowed using short field names. 

I think the field inference should do the trick but I can't find any complete example that shows what I need. 

My original question is here
http://stackoverflow.com/questions/36994062/elasticsearch-nest-2-x-field-names

**Comment by russcam** [comment]
Hey @Molenx, the easiest way to address this would be to change your  `Park` type to introduce a `doc` property with a `Doc` type that has the values written to Elasticsearch by the Couchbase plugin i.e. 

```c#
public class Park
{
    public Doc Doc { get; set;}
}

public class Doc
{
    public bool IsPublic { get; set;}
}
```

Another way would be to write your own [`JsonConverter`](http://www.newtonsoft.com/json/help/html/SerializationGuide.htm#JsonConverter) to serialize and deserialize the `Park` type to expand and flatten the `isPublic` property to a property on a `doc` property object of the json but this would be much more effort than introducing the `Doc` property on the type.

You might be inclined to just attribute the `isPublic` property with a [`JsonPropertyAttribute`](http://www.newtonsoft.com/json/help/html/SerializationAttributes.htm) with the property name `"doc.isPublic"`

```c#
public class Park
{
	[JsonProperty("doc.isPublic")]
	public bool IsPublic { get; set; }
}
```

whilst this will work for **serialization**, it will **not work for deserialization**

```c#
var searchResponse = client.Search<Park>(s => s
		.Index("parkindex-local-01")
		.Take(1)
		.Source(false)
		.Query(q => termQuery));
```

```javascript
POST http://localhost:9200/parkindex-local-01/park/_search?pretty=true 
{
  "size": 1,
  "_source": {
    "exclude": [
      "*"
    ]
  },
  "query": {
    "term": {
      "doc.isPublic": {
        "value": true
      }
    }
  }
}
```

serialization looks good, but

```c#
var json = "{ \"doc\": { \"isPublic\": true } }";

using (var stream = new MemoryStream(Encoding.UTF8.GetBytes(json)))
{
    var park = client.Serializer.Deserialize<Park>(stream);
}
```

deserialization does not work as expected and `park.IsPublic` is `false`.

**Comment by Molenx** [comment]
@russcam thanks for your reply, if I changed my POCO, the property will be like this in ES "doc.doc.isPublic".
The couchbase transport plugin wraps all properties under doc, i don't control this part.

Also in principal this reason should not warrant changing my POCO.

The simple working around I am using now is not using the strongly types field descriptors and just using strings to specify my fields.

```
var termQuery = Query<Park>.Term("doc.isPublic", true);
ISearchResponse<T> searchResponse = this.client.Search<T>(s => s.Index("parkindex-local-01")
                     .Take(size)
                     .Source(false)
                     .Query(q => termQuery));
```
Please note that I get only the Ids from ES, then I get the doc contents from couchbase, changing the serialization would work at all and would break things.

**Comment by russcam** [comment]
Does Couchbase uses the CLR poco for serialization into ES? You could always define a different type for reading from ES if need be.
