### ISSUE TITLE
Can't Find SearchDescriptor<T> .Types(IEnumerable<Type> types) method on NEST Nuget package 2.3.1

### ISSUE THREAD

**Issue by remtek** [elastic/elasticsearch-net#2082]
I'm trying to use this method of ( .Types(params Type[] types ), intellisense was not finding either of them.

I looked at the decompiled sources for the SearchDescriptor class (using R#) but the source but the methods aren't there. Can't find the, in the SearchDescriptor<T> class defined in SearchRequest.cs of the official repository either.

Most of the other methods appear to be there

**Comment by Reonekot** [comment]
Not sure where you found  theabove repo, but the official repo is at https://github.com/elastic/elasticsearch-net

**Comment by remtek** [comment]
I googled for that method

I'm trying to do what's described here

https://github.com/elastic/elasticsearch-net/issues/243

**Comment by remtek** [comment]
.Search<object>(s=>s
      **.Types(typeof(Product),typeof(Category),typeof(Manufacturer))**
      .Query(...)
 );

**Comment by remtek** [comment]
@Mpdreamz can you please advise?

**Comment by russcam** [comment]
@remtek To specify multiple types, you would use `.Type(Types.Type(typeof(T)))`, for example

```c#
var response = client.Search<Person>(s => s
    .Type(Types.Type(typeof(Teacher), typeof(Firefighter)))
    .MatchAll()
);
```

If you're looking at returning covariant results, take a look at the [covariant search results documentation](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/covariant-search-results.html) and also [this example](https://github.com/elastic/elasticsearch-net/issues/1959).
