### ISSUE TITLE
Introduce derived NumberAttribute types

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#2084]
I think it would be useful to introduce derived number types for attributed based mapping.

At the moment, We have `NumberAttribute` but there doesn't look  to be a way to set the `NumberType` when used as an attribute because the `IProperty.Type` property is not exposed directly.

The derived types would inherit from `NumberAttribute` and simply set pass the appropriate `NumberType` to the base constructor.

**Comment by gmarz** [comment]
Removed labels as this isn't an issue.  `NumberType` can be passed via the attribute constructor.
