### ISSUE TITLE
Source Types vs Document Types

### ISSUE THREAD

**Issue by aarongundel** [elastic/elasticsearch-net#2098]
I'm using NEST/ES.net 2.3.1 on ES 2.1.1

The trouble I'm having is that the GetAsync method can't seem to infer my type vs SearchAsync which does seem to be able to infer it.  

`var results = await esClient.SearchAsync<dynamic>(s => s.Type(Types.Type(typeof(MyType)));`

Checking the results.Documents, I see an enumerable of MyType

However, when I do the following...

```
var docPath = new DocumentPath<dynamic>(id).Type(Types.Type(typeof(MyType)));
var myObject = await esClient.GetAsync(docPath);
```

When I look into myObject.Source.GetType(), all I see is the raw JObject from JSON.NET.  

This behavior doesn't seem to be consistent.  Am I looking at this the wrong way?

**Comment by russcam** [comment]
Hey @aarongundel, search (along with some other search requests such as scroll) implements [`ICovariantSearchRequest`](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Nest/Search/CovariantSearch.cs#L37) that can handle covariant search results. 

In the case of your first example with `.SearchAsync<T>()`, the type passed to `Types.Type()` is used as part of [`CloseOverAutomagicCovariantResultSelector`](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Nest/Search/CovariantSearch.cs#L15) to know what type to deserialize a hit into based on the `_type` string in the hit response mapping to a `System.Type`.

`Get` and `GetAsync` don't handle covariance.

**Comment by aarongundel** [comment]
Thanks @russcam!  That's how I've got things implemented right now -- so that everything is using searchasync.  Do you know if there is any plan for Get and GetAsync to handle covariance someday?

**Comment by Mpdreamz** [comment]
@aargundel retreiving a single document should always be done using `Get()` its less resource intensive and in Elasticsearch a GET of a single document is real time where as a search retrieving one is near real time. 

We discussed this today but we'll only support covariance on API's that can return multiple different shapes in a collection. `Search` `Scroll` `MultiSearch` and so forth. 

is there a reason why:

```csharp
await esClient.GetAsync<MyType>(id);
```

is not sufficient for your use case? Depending on what you are trying to achieve there are routes you can take today without `Get()` needing to be covariant.

**Comment by aarongundel** [comment]
@Mpdreamz I have many different types within my index.  I am writing an API that uses ES as a data source for select functions.  If `Get` is not covariant, I have to create a separate concrete call for each distinct type -- there are many, and as a result I create a lot of duplicate code.  I understand why it would be less resource intensive to do a `Get` than a search (and would certainly prefer to be using it), but if it doesn't support covariance, the search is going to be easier for me to maintain in the long run.  The covariant search method allows me to have a single controller that I can initialize dynamically to return many different CLR types.

**Comment by Mpdreamz** [comment]
Your usecase still doesn't quite click with me, bare with me :smile:

You store in a single index several unrelated CLR types? Is this a fixed list or unbounded? How do you dynamically initialize your controller? 

Not seeing why your service can't be generic too (even if instantiated dynamically). 

As i said not trying to shoot your idea down just trying to grasp it fully before recommending an alternative approach.

One such suggestion would be:

```csharp
var response = esClient.GetAsync<ILazyDocument>(id);
//use response.Type to determine this dynamically
return response.Source.As<MyType>();
```

ILazyDocument is a special construct in NEST you can use to defer deserialization
