### ISSUE TITLE
Query always overwrites

### ISSUE THREAD

**Issue by beruic** [elastic/elasticsearch-net#2102]
**NEST/Elasticsearch.Net version**: 2.3.1

**Elasticsearch version**: 2.3.2

**Description of the problem including expected versus actual behavior**:
If you are building a `SearchDescriptor` and call `.Query([query lambda])` on it, it overwrites the current query. This is inconsistent with the behaviour experiences when building a `MultiSearchDescriptor` where `.Search([name], [search lambda])` adds another search.

I know it's not completely the same, but often you just want to add to a query. Personally I expected the argument of the lambda method in `.Query([query lambda])` to be the current query, and not a completely new one every time.
(I also expected that every call to a method on some descriptor to be side effect free, but I got smarter and now see the value of the current approach, despite the lack of documentation)

For now I use an extension method to build my default query, and let this extension method take an optional argument of an additional query. It would be nice if the query method could take an additional boolean argument to tell it whether to merge this query or overwrite.

**Comment by russcam** [comment]
@beruic, did you see [the operator overloading documentation for building `bool` queries](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/bool-queries.html#_operator_overloading)? You can combine multiple queries using a `bool` query

```c#
client.Search<Document>(s => s
    .Query(q => q
        .Bool(b => b
            .Should(sh => sh
                .Match(c => c
                    .Field(p => p.Field1)
                    .Query("query 1")
                ),
                    sh => sh
                .Match(c => c
                    .Field(p => p.Field2)
                    .Query("query 2")
                )
            )
        )
    )
);
```

which, with operator overloading, can be shortened to 

```c#
client.Search<Document>(s => s
    .Query(q => q
        .Match(c => c
            .Field(p => p.Field1)
            .Query("query 1")
        )
        || q.Match(c => c
            .Field(p => p.Field2)
            .Query("query 2")
        )
    )
);
```

**Comment by beruic** [comment]
Well, this issue is more concerned with you having an instance of a `SearchDescriptor<T>`, and you want to add something to the current query. For example if you use a method to apply some standard filter to your search descriptor, as well as adding some extra stuff. My current solution is combining my queries by doing `searchDescriptor.Query(q => standardQueriesContainer && additionalQueries)`.

**Comment by gmarz** [comment]
@beruic that's the correct way to go about it, using the bool operators.

I think `.Query()` being additive, or merging with the existing query would not be intuitive at all.

Closing this, but feel free to re-open if you still think otherwise.

**Comment by beruic** [comment]
@gmarz I agree completely, as my comment from 20 may also indicates :)
