### ISSUE TITLE
Unable to combine multiple aggregations

### ISSUE THREAD

**Issue by beruic** [elastic/elasticsearch-net#2105]
**NEST/Elasticsearch.Net version**: 2.3.1

**Elasticsearch version**: 2.3.2

**Description of the problem including expected versus actual behavior**:
I have written some methods that create and return `AggregationContainerDescriptor<MyType>`s. Now I need to combine multiple of these in a single search, but there is no obvious way to do this.

It would be cool if I could just use the `+` operator to join them together or have an overload to take `params Func<AggregationContainerDescriptor<T>, IAggregationContainer> aggregationsSelectors` like with `BoolQueryDescriptor<T>.Filter`.

**Comment by gmarz** [comment]
Hey @beruic checkout the [docs on aggregating over a collection of aggregations](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/writing-aggregations.html#_aggregating_over_a_collection_of_aggregations) which explains how to use the built in `Aggregate()` LINQ method to combine multiple aggregation descriptors.

FWIW we also support the `&&` operator for combining aggregations as part of the [object initializer syntax](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/writing-aggregations.html#_object_initializer_syntax).  It might make sense for your methods to just return these objects rather than descriptors.

**Comment by beruic** [comment]
That example in the first link seems very unintuitive. Can't you make an example where a list of aggregations are added instead of a list of child aggregations? Or have I misunderstood something? It would be nice to compare the example to an equivalent piece of code where the aggregations are made normally.

BTW, the way I have fixed it for now is by returning the specific aggregation descriptors. E.g. `TermsAggregationDescriptor<MyType>`, and then I apply it with `.Terms([name], tad => [MygeneratorFunctionCall]`.
I still, however, really miss an overload for `params Func<AggregationContainerDescriptor<T>, IAggregationContainer>[] aggregationsSelectors` or `params IAggregationContainer[] aggregationsContainerDescriptors` (or perhaps `params AggregationContainerDescriptor<T>[] aggregationsContainerDescriptors` - I'm not sure what is best).

The object initializer syntax seems promissing, I'm just not really familiar with it yet. I'll give it a try now.

**Comment by gmarz** [comment]
Hey @beruic apologies for the slow response.

I agree the example is not very intuitive and feels like a leaky abstraction.  I think it's a good idea to add a `params` or `IEnumerable` overload that essentially does the `.Aggregate` accumulation in its implementation.

Thoughts @Mpdreamz  @russcam ?

**Comment by Mpdreamz** [comment]
>That example in the first link seems very unintuitive. Can't you make an example where a list of aggregations are added instead of a list of child aggregations?

The example just indicates how you can do it any level, the same should hold up at the root. 

> I agree the example is not very intuitive and feels like a leaky abstraction. 

I dissagree, our fluent composibilty is built on functions taking a thing and returning that thing. Allowing multiple functions to be composed to build pipelines. `Aggregate()` is a very natural extension to that if you have a list of functions you need to apply.

Adding an `IEnumerable<>` overload would add cognitive load on user for a pattern we do not actively promot, and adding params would not version well with what we released in 2.x.

That said:

I've added the ability for `AggregationContainerDescriptor<T>` to be bitwise `&&` together (just like the OIS syntax) though so hopefully this allows for even more combinating patterns to be utilized.
