### ISSUE TITLE
Filtering with Lookups

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch-net#2106]
NEST version: 1.7.2
ES version: 1.7.2

As I detailed here ([Elasticsearch and NEST: Filtering with Lookups](http://stackoverflow.com/questions/37402414/elasticsearch-and-nest-filtering-with-lookups)), I can't see any way to create a filter w/ lookups using NEST.  We're committed to using NEST and since the functionality is available in ES 1.7, we're hoping there's a way to pull this off.  Any thoughts and guidance appreciated.

Thanks,
Tom Doman

**Comment by gmarz** [comment]
It's mapped as `TermsLookup()` or `TermsLookupFilter` in `1.x`.  Check out [the unit tests](https://github.com/elastic/elasticsearch-net/blob/1.x/src/Tests/Nest.Tests.Unit/Search/Filter/Singles/TermsLookupFilterJson.cs) for some examples.

```csharp
client.Search<Paper>(s => s
    .Query(q => q
       .Filtered(fq => qf
           .Filter(f => f
               .CacheKey("experiment_1234")
               .TermsLookup(t => t
                   .Lookup<Protein>(p => p.UnregulatedProteins, "experiment1234", "microarrays", "experiment") 
               )
           )
       )
    )
);
```

In `2.x` it's a little more aligned with the [ES query DSL](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Tests/QueryDsl/TermLevel/Terms/TermsLookupQueryUsageTests.cs#L47).

**Comment by tdoman** [comment]
Fantastic, thanks Greg, I appreciate the quick response!
