### ISSUE TITLE
Allow some means to modify the request message when running on .NET core

### ISSUE THREAD

**Issue by jessegavin** [elastic/elasticsearch-net#2108]
**Describe the feature**:

We are using [ElasticSearch on AWS](https://aws.amazon.com/elasticsearch-service/). In our situation we need to be able to sign each request to ElasticSearch by adding an [Authorization header](http://docs.aws.amazon.com/general/latest/gr/sigv4_signing.html).

The HttpConnection class provides a `protected virtual` method named [CreateWebRequest](https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Connection/HttpConnection.cs#L35). I can extend HttpConnection and override this method to add the Authorization header. This works great. In fact there's a [Nuget package](https://www.nuget.org/packages/Elasticsearch.Net.Aws/) which does exactly this. See their [AwsHttpConnection implementation](https://github.com/bcuff/elasticsearch-net-aws/blob/c2d59f060f5169e6fe1a303ecf1810cd86c82cf6/src/Elasticsearch.Net.Aws/Elasticsearch.Net.Aws/AwsHttpConnection.cs#L70-L92).

However, ElasticSearch.Net has a [different implementation of HttpConnection](https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs#L116) for .NET Core which does not provide this same "hook".  The CreateHttpRequestMessage method is `private static`. I can't figure out a way to add the Authorization header required to use NEST to for ES on AWS.

Is this something that could be added?

**Comment by gmarz** [comment]
> I can extend HttpConnection and override this method to add the Authorization header. This works great.

This is also the recommended approach :+1: 

I don't know why `CreateHttpRequestMessage` is `private static`...probably oversight on our part (@Mpdreamz @russcam any ideas?).  I think we can and should change it to `protected virtual`.  I also think we can break out the basic auth header section into it's own method so a user doesn't have to re-implement that when overriding.

**Comment by russcam** [comment]
This looks like an oversight on my part.

++ on making this `protected virtual` and splitting out the auth header; it would be nice to revisit this further to allow passing own `HttpClientHandler` implementation to allow customisation of request/response pipeline.
