### ISSUE TITLE
How to get group by sum in Elastic search (Nest Client C#) with Where Condition

### ISSUE THREAD

**Issue by imdineshk80** [elastic/elasticsearch-net#2113]
Have a nice day!

The following query needs to be translated into equivalent NEST query, please help 
`{
  "size": 0,
   "query" : {
      "constant_score" : { 
         "filter" : {
            "bool" : {
              "must" : [
                 {"term" : {"Cycle" : "477"}},
                 {"term" : {"year" : 2016}},
                 {"term" : {"Code" : "20"}}
              ],
              "should" : [
                {"terms" : {"type" : ["Q1", "Q2", "Q3", "Q4"] }}   
              ]
           }
         }
      }
   },
  "aggs": {
    "group_by_clientId": {
      "terms": {
        "field": "clientId",
        "size": 100        
      },
      "aggs": {
        "sum_amount": {
          "sum": {
            "field": "amount"
          }
        }
      }
    }
  }
}

**Comment by russcam** [comment]
This question is best asked [in the discussion forums](https://discuss.elastic.co/c/elasticsearch) or [stackoverflow](http://stackoverflow.com/questions); Github issues are intended for issues and bugs with the client :smiley:
