### ISSUE TITLE
Per field custom similarity in fluent PUT mapping

### ISSUE THREAD

**Issue by lncramer** [elastic/elasticsearch-net#2119]
Nest version: 2.1.1

The current fluent syntax for creating a PUT mapping forces you to use a built in `SimilarityOption` (either `Default` or `BM25`) when specifying a per field similarity (https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Mapping/Types/CorePropertyDescriptorBase.cs), but I would like to use a custom similarity specified in the create index request instead. As far as I can tell this is currently only possible in Nest using `AllFieldDescriptor.Similarity`, but I don't want to apply the custom similarity to the `_all` field. According to the [Elastic docs](https://www.elastic.co/guide/en/elasticsearch/guide/current/changing-similarities.html) a per field custom similarity should be valid.

**Comment by gmarz** [comment]
Thanks for reporting @lncramer.  Sadly, fixing this in our 2.x branch would be a breaking change.  Targeting 5.x for now unless we can think of a clever work around.

**Comment by Mpdreamz** [comment]
@lncramer I opened some PR's for this so provided @gmarz and/or @russcam agrees it will be fixed in the next `2.x` release as well.
