### ISSUE TITLE
CompletionAttribute does not seem to set type  "completion" (Nest 2.3.2, Elastic 2.3.2)

### ISSUE THREAD

**Issue by HarveyWilliams** [elastic/elasticsearch-net#2123]
I'm trying to run a completion suggest on my index: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-suggesters-completion.html

There seems to be a lack of documentation on setting up an index using a POCO. I know how to do the query as it is documented here: https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/suggest-usage.html

I'm trying to put a Product into my index:

```
// My Product POCO
public class Product
{
    [String()]
    public string ProductType { get; set; }

    [Completion()]
    public CompletionField<object> ProductTypeSuggest { get; set; }
}

// Method I use to insert my Product into my Elastic database.
public IIndexResponse InsertProduct(string id)
{
    var product = new Product()
    {
        ProductType = "Foo",
        ProductTypeSuggest = new CompletionField<object>()
        { 
            Input = new[] { "Foo" }
        };
    };

    var index = ElasticClient.Index(new ElasticModels.Product(product));

    return index;
}
```

However, when I run: GET /index/product/_mappings

```
{
  "index": {
    "mappings": {
      "product": {
        "properties": {
          "productType": {
            "type": "string"
          },
          "productTypeSuggest": {
            "properties": {
              "input": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  }
}
```

If I then try to query the ProductTypeSuggest, I get the error: `Field [productTypeSuggest] is not a completion suggest field`

I tried to follow the test example which can be found here: https://github.com/elastic/elasticsearch-net/blob/2.x/src/Tests/Mapping/Types/Specialized/Completion/CompletionMappingTests.cs

But I'm not really sure how this test works. I have set up my model in the same way, but I'm not doing anything found on line 50. Is this necessary? Isn't the type of of the property decided from the attribute?

Any help would be much appreciated.

**Comment by russcam** [comment]
Hey @HarveyWilliams, did you see [the documentation on Automapping](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/auto-map.html)? There are examples of using a POCO to define mapping using [attributes](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/auto-map.html#attribute-mapping), [fluent mapping](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/auto-map.html#auto-mapping-with-overrides), [conventions using a visitor pattern](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/auto-map.html#applying-conventions-through-the-visitor-pattern), and a combination of all. 

The test that you've linked to tests that

- [inferred mapping](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Tests/Mapping/Types/Specialized/Completion/CompletionMappingTests.cs#L20)
- [simple attribute mapping](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Tests/Mapping/Types/Specialized/Completion/CompletionMappingTests.cs#L18)
- [complex attribute mapping](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Tests/Mapping/Types/Specialized/Completion/CompletionMappingTests.cs#L8)
- [fluent mapping](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Tests/Mapping/Types/Specialized/Completion/CompletionMappingTests.cs#L50)

all serialize to the expected json when mapping the `CompletionTest` POCO.

Here's a complete example to get you going

```c#
void Main()
{
	var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
	var productsIndex = "products";
	var connectionSettings = new ConnectionSettings(pool)
			.DefaultIndex(productsIndex);
				
	var client = new ElasticClient(connectionSettings);

    if (!client.IndexExists(productsIndex).Exists)
    {
        var createIndexResponse = client.CreateIndex(productsIndex, c => c
            .Mappings(m => m
                .Map<Product>(mm => mm
                    .AutoMap()
                )
            )
        );
        
        if (!createIndexResponse.IsValid)
            Console.WriteLine(createIndexResponse.DebugInformation);
    }

    var product = new Product()
    {
        ProductType = "Foo",
        ProductTypeSuggest = new CompletionField<object>()
        {
            Input = new[] { "Foo" }
        }
    };

    var indexResponse = client.Index(product);
    
    var mappingResponse = client.GetMapping<Product>();
}

public class Product
{
    [String()]
    public string ProductType { get; set; }

    [Completion()]
    public CompletionField<object> ProductTypeSuggest { get; set; }
}
```

You will need to create a new index with this mapping applied. The `mappingResponse` returns

```javascript
{
  "products" : {
    "mappings" : {
      "product" : {
        "properties" : {
          "productType" : {
            "type" : "string"
          },
          "productTypeSuggest" : {
            "type" : "completion",
            "analyzer" : "simple",
            "payloads" : false,
            "preserve_separators" : true,
            "preserve_position_increments" : true,
            "max_input_length" : 50
          }
        }
      }
    }
  }
}
```

**Comment by HarveyWilliams** [comment]
Hi @russcam, that's great. I just gave this a test and it's working as expected. I guess the important bit here was that the index needs setting up and mapped using AutoMap, otherwise the mappings won't be properly automapped when then the products are inserted.

Thanks again.

**Comment by russcam** [comment]
Yes, you need to map types with automapping to have a POCO mapped via inference, attributes or fluent mapping; if you don't specify mapping explicitly then [dynamic mapping in Elasticsearch will infer the mapping](https://www.elastic.co/guide/en/elasticsearch/guide/current/dynamic-mapping.html).

Happy it helped :+1:
