### ISSUE TITLE
Factor property should be removed from DateHistogramAggregation

### ISSUE THREAD

**Issue by jonyadamit** [elastic/elasticsearch-net#2124]
[Factor property](https://github.com/elastic/elasticsearch-net/blob/be0f2a70933c41c81235e057e7076dd2b33feb39/src/Nest/Aggregations/Bucket/DateHistogram/DateHistogramAggregation.cs#L33-L34) should be removed from `DateHistogramAggregation`. It is not supported since 2014: elastic/elasticsearch#6490 :sweat_smile:

**Comment by gmarz** [comment]
Thanks @jonyadamit :)
