### ISSUE TITLE
Allow to use a custom Highlighter

### ISSUE THREAD

**Issue by gwenzek** [elastic/elasticsearch-net#2125]
In Nest 2.3.2 the `HighlightField` uses an enum `HighlighterType` as `Type`.

This prevents to use a custom highlighter instead of one of the 3 embedded within ElasticSearch.

This is a regression from Nest 1.7 where the same field was a String, therefore allowing to put the name of an highlighter provided by a plugin.

I think having a string as Type field and a few const string inside a static `HighlighterType` class would give the best of both world.

**Comment by gmarz** [comment]
Similar to #2119.  Labeling for 5.0 as this would be a breaking change.  Thanks for reporting @gwenzek !

**Comment by Mpdreamz** [comment]
Hi @gwenzek we found a way to include support for this in 2.x without introducing a breaking change so a fix for this should go into the next release of `2.x`
