### ISSUE TITLE
NTLM Authentification with elasticsearch server

### ISSUE THREAD

**Issue by jsgervais** [elastic/elasticsearch-net#2128]
Can you add support for NTLM authentification in ConnectionConfiguration class?

**Comment by gmarz** [comment]
I don't think this is something we would want to support out of the box, but you can easily subclass [HttpConnection](https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Connection/HttpConnection.cs) and override [CreateHttpWebRequest](https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Connection/HttpConnection.cs#L26) and/or [CreateWebRequest](https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Connection/HttpConnection.cs#L35).  We try and keep this class as extensible as possible for reasons such as this.

For a good example, check out [AwsHttpConnection](https://github.com/bcuff/elasticsearch-net-aws/blob/master/src/Elasticsearch.Net.Aws/Elasticsearch.Net.Aws/AwsHttpConnection.cs) implementation in the elasticsearch-net-aws project.

**Comment by jsgervais** [comment]
Well, I was hoping for a cleaner, out of the box solution than this.  

In case this helps anyone else facing the same problem, here's the overriden class 

`
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Runtime.Serialization;
using System.Web;
using Elasticsearch.Net;

namespace Web.Areas.Api.Models.ElasticSearch.Extents
{
    public class NtlmHttpConnection : HttpConnection
    {

        /// <summary>
        /// Override de la méthode pour supporter les connexions HTTP avec authentification NTLM
        /// </summary>
        /// <param name="requestData"></param>
        /// <returns></returns>
        protected override HttpWebRequest CreateHttpWebRequest(RequestData requestData)
        {
            HttpWebRequest webRequest = this.CreateWebRequest(requestData);

            webRequest.Credentials = new NetworkCredential("user", "password", "DOMAIN");

            this.SetBasicAuthenticationIfNeeded(webRequest, requestData);
            this.SetProxyIfNeeded(webRequest, requestData);
            this.AlterServicePoint(webRequest.ServicePoint, requestData);
            return webRequest;
        }

        /// <summary>
        /// Override de la méthode pour supporter les connexions HTTP avec authentification NTLM
        /// </summary>
        /// <param name="requestData"></param>
        /// <returns></returns>
        protected override HttpWebRequest CreateWebRequest(RequestData requestData)
        {
            HttpWebRequest httpWebRequest = (HttpWebRequest)WebRequest.Create(requestData.Uri);


            httpWebRequest.Credentials = new NetworkCredential("user", "password", "DOMAIN");

            httpWebRequest.Accept = requestData.ContentType;
            httpWebRequest.ContentType = requestData.ContentType;
            httpWebRequest.MaximumResponseHeadersLength = -1;
            httpWebRequest.Pipelined = requestData.Pipelined;
            if (requestData.HttpCompression)
            {
                httpWebRequest.AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate;
                httpWebRequest.Headers.Add("Accept-Encoding", "gzip,deflate");
                httpWebRequest.Headers.Add("Content-Encoding", "gzip");
            }
            if (!Extensions.IsNullOrEmpty(requestData.RunAs))
                httpWebRequest.Headers.Add("es-shield-runas-user", requestData.RunAs);
            if (requestData.Headers != null && requestData.Headers.HasKeys())
                httpWebRequest.Headers.Add(requestData.Headers);
            int num = (int)requestData.RequestTimeout.TotalMilliseconds;
            httpWebRequest.Timeout = num;
            httpWebRequest.ReadWriteTimeout = num;
            string stringValue = Extensions.GetStringValue((Enum)requestData.Method);
            httpWebRequest.Method = stringValue;
            if (stringValue != "head" && stringValue != "get" && requestData.PostData == null)
                httpWebRequest.ContentLength = 0L;
            return httpWebRequest;
        }
         
    }



    internal static class Extensions
    {
        internal static string GetStringValue(this Enum enumValue)
        {
            string str = KnownEnums.Resolve(enumValue);
            if (str != KnownEnums.UnknownEnum)
                return str;
            EnumMemberAttribute[] enumMemberAttributeArray =
                (EnumMemberAttribute[])
                    enumValue.GetType()
                        .GetField(enumValue.ToString())
                        .GetCustomAttributes(typeof(EnumMemberAttribute), false);
            if (enumMemberAttributeArray.Length == 0)
                return Enum.GetName(enumValue.GetType(), (object)enumValue);
            return enumMemberAttributeArray[0].Value;
        }

        internal static bool IsNullOrEmpty(this string value)
        {
            return string.IsNullOrEmpty(value);
        }
    }
}
` 

and how to initialize it : 

`
            var uri = new Uri("https://elasticsearch.mydomain.ca");
            var conn = new ConnectionSettings(new SingleNodeConnectionPool(uri),new NtlmHttpConnection());
            var client = new ElasticClient(conn);

            var searchResults =  client.Search<mytype>( ...) 
`
