### ISSUE TITLE
When migrating to 2.33, some types are not valid

### ISSUE THREAD

**Issue by serefbilge** [elastic/elasticsearch-net#2129]
I don't want to ask this question here, but documentation for migration from 1.7.1 to 2.3.3 is insufficient. So, I need your help. Thanks for taking your time.

I have a method like below working on nest 1.7.1 and I have to migrate to nest 2.3.3. I tried but couldn't proceed any path. 

1- Firstly, Nest 2.3.3 doesn't know KeyItem type; what is the new way of getting items?
2- Nest 2.3.3 can not cast "agg.Value" as Bucket type at the method below. How can I cast to Bucket type?
3- How can I reach DocCount value from aggregationList which is in type of IDictionary<string, IAggregation> ?

```
 private void GetChildNodes(IDictionary<string, IAggregation> aggregationList, List<string> nodeTextList, KeyItem rootItem)
        {
            if (aggregationList != null && aggregationList.Count > 0)
            {
                foreach (var agg in aggregationList)
                {
                    var bucket = agg.Value as Bucket;
                    if (bucket != null && bucket.Items.Count() > 0)
                    {
                        foreach (KeyItem item in bucket.Items)
                        {
                            nodeTextList.Add(agg.Key + "=" + item.Key ?? string.Empty);

                            if (item.Aggregations != null && item.Aggregations.Count > 0)
                            {
                                GetChildNodes(item.Aggregations, nodeTextList, item);
                            }
                            else
                            {
                                nodeTextList.Add("Count=" + item.DocCount.ToString());
                            }
                        }
                    }
                }
            }
        }

```

**Comment by gmarz** [comment]
Hey @serefbilge questions like these are welcome here...we know upgrading from 1.x to 2.x can be quite the pain.

`Bucket` => `BucketAggregate`
`KeyedItem` => `KeyedBucket`
`IAggregation` => `IAggregate`

```csharp
private void GetChildNodes(IDictionary<string, IAggregate> aggregationList, List<string> nodeTextList, KeyedBucket rootItem)
{
	if (aggregationList != null && aggregationList.Count > 0)
	{
		foreach (var agg in aggregationList)
		{
			var bucket = agg.Value as BucketAggregate;
			if (bucket != null && bucket.Items.Count() > 0)
			{
				foreach (KeyedBucket item in bucket.Items)
				{
					nodeTextList.Add(agg.Key + "=" + item.Key ?? string.Empty);

					if (item.Aggregations != null && item.Aggregations.Count > 0)
					{
						GetChildNodes(item.Aggregations, nodeTextList, item);
					}
					else
					{
						nodeTextList.Add("Count=" + item.DocCount.ToString());
					}
				}
			}
		}
	}
}
```

Hope that helps.

**Comment by serefbilge** [comment]
Thanks, it was helpful. It could be better if you havewritten these details into documentation. By the way another thing I couldn't found is Nest.ValueMetric. What is the new version of it ?

**Comment by serefbilge** [comment]
Another thing is, in the script below 'Index' is wrong anymore. What is the right way of it ? Thanks in advance.

ElasticSearchEngine.GetClient().Update<dynamic, object>(u => u
                     .Index(TrendLastSamplesIndex.IndexName)
                     .Type(TrendLastSamplesIndex.TypeName)
                     .Id(trendStatistic.LastSampleDocId)
                     .Doc(docc)
                     .RetryOnConflict(3)
                     .Refresh());

**Comment by russcam** [comment]
In NEST 2.x, an update would be 

```c#
// replace Document generic type parameter with type of docc
client.Update<Document>(trendStatistic.LastSampleDocId, u => u
    .Index("index")
    .Type("type")
    .Doc(docc)
    .RetryOnConflict(3)
    .Refresh()
);
```

The first parameter to `.Update<T>()` is a [`DocumentPath`](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/document-paths.html)

**Comment by serefbilge** [comment]
Thanks, I'll try it. I asked another one in two post earlier not answered yet; what is the new usage of Nest.ValueMetric?
