### ISSUE TITLE
TasksList detailed info

### ISSUE THREAD

**Issue by EricKeij** [elastic/elasticsearch-net#2133]
Would it be possible to get the detailed info of a tasklist into the response object? 

So when doing

`var response = ElasticClient.TasksList(d => d.TaskId(myTaskId).Detailed())`

having the detailed info such as total/updated/created items into the response. AFAIK there is currently no way of getting this data other then parsing it from the raw response. Which requires DisableDirectStreaming() to be set.

**Comment by Mpdreamz** [comment]
Thanks for reporting this @EricKeij will be sure to support it soon!
