### ISSUE TITLE
GetIndexSettings response properties not filled correctly

### ISSUE THREAD

**Issue by EricKeij** [elastic/elasticsearch-net#2136]
**NEST/Elasticsearch.Net version**: 2.3.1

**Elasticsearch version**: 2.3.1

**Description of the problem including expected versus actual behavior**:
When doing GetIndexSettings() I expect the NumberOfReplicas and NumberOfShards properties to be set. Instead they will always be null. 

**Steps to reproduce**:
 1. Do a GetIndexSettings()

`var response = ElasticClient.GetIndexSettings(d => d.Index("myindex"))`

 2. Check value of NumberOfReplicas and NumberOfShards which will always be null.

`var numberOfReplicas = response.Indices.Single(i => i == "myindex").Value.Settings.NumberOfReplicas;`

 A workaround is the get the value directly from the dictionary using:

`var numberOfReplicas = response.Indices.Single(i => i == "myindex").Value.Settings.Single( x => x.Key == "index.NumberOfReplicas").Value`

**Comment by Mpdreamz** [comment]
Hi @EricKeij tried to reproduce this locally but could not reproduce. 

The correct elasticsearch setting is `number_of_replicas` which is what we serialize to and deserialize from. 

https://github.com/elastic/elasticsearch-net/commit/937019bc989839cbf7b3097645225d541368b908

I did notice in our `5.x` beta branch we had a bug where `number_of_replicas` got overwritten to `null` at serialization time. This is not the case in the stable `2.x` brranches. 

I do wonder how `index.NumberOfReplicas` got serialized into the index's settiings. Can you share the code that puts it there in the first place?

**Comment by EricKeij** [comment]
Hi @Mpdreamz 

I think index.NumberOfReplicas is serialized because that's the way it's returned from the _settings call. 
Looking at the raw response from _settings it's something like

`
"myindex {
 "settings": {
  "index": {
   "numberOfReplicas": "1",
   "numberOfReplicas": "5"
   ....
  } 
}
}"
`

Whilst an update is called with "index.number_of_replicas".

**Comment by EricKeij** [comment]
It turned out we use numberOfShards and numberOfReplicas in our templates instead of number_of_shards and number_of_replicas. Both seems to be valid (at least both work). I changed our templates to number_of_shards and number_of_replicas which solves our problem.

**Comment by Mpdreamz** [comment]
Aye that will explain the origin of the camelCasing :)

camelCase support is deprecated in 2.x and scheduled for removal in 5.x

https://github.com/elastic/elasticsearch/pull/17933

That said we should make an effort supporting camelCase settings at read time in our `2.x` branch.

**Comment by Mpdreamz** [comment]
We now also read camelCase versions of known values such as `index.numberOfShards` in 2.x as per 65bb0abd9b53b9523fe3b61414aab7bd0fb2f662

@EricKeij `index.NumberOfShards` in PascalCase is **not** supported in Elasticsearch 2.x. Your second comment is in camelCase but first in PascalCase.  

Just want to stress that sending `"index.NumberOfShards" : 2` won't actually create 2 shards in Elasticsearch `2.x`.  `"index.numberOfShards" : 2` will work but is deprecated.
