### ISSUE TITLE
Completion fields

### ISSUE THREAD

**Issue by zissop** [elastic/elasticsearch-net#2137]
Hello

I have a completion field defined as follows:

[Completion(Analyzer = "greek_fg", PreserveSeparators = true, PreservePositionIncrements = true, MaxInputLength = 20)]
public CompletionField suggester2 { get; set; }

public class CompletionField
{
            public List<string> Input { get; set; }
            public Payload Payload { get; set; }
}

public class Payload
{
     public long Id { get; set; }
}

This is automapped as follows:

"suggester" : {
            "type" : "completion",
            "analyzer" : "greek_fg",
            "payloads" : false,
            "preserve_separators" : true,
            "preserve_position_increments" : true,
            "max_input_length" : 20
}

What is required in order to get "payloads" : true? 

There is no help around and this is happening on the last version, I am pretty sure previous versions mapped it to "payloads" : true by default.

Regards
John

**Comment by gmarz** [comment]
@zissop you need to sey `Payloads=true` in your attribute as well, the default is `false`.

```csharp
[Completion(Analyzer = "greek_fg", PreserveSeparators = true, PreservePositionIncrements = true, MaxInputLength = 20, Payloads = true)]
```

**Comment by zissop** [comment]
There is not Payloads attribute there, are you sure you can add this? Code completion does not show this, that why i asked from the first place. Adding it manually does not help, can't compile.

**Comment by gmarz** [comment]
What version are you on?

**Comment by zissop** [comment]
5.0.0-alpha2

**Comment by zissop** [comment]
Ok i downloaded 2.3.3 and Payloads attribute exists. It will be removed from future versions? How the same functionality will be achieved?

**Comment by gmarz** [comment]
Sorry, I assumed you were on a 2.x version.

The completion suggester in ES 5.0 has changed quite a bit and no longer requires enabling `payload` in the mapping.  NEST 5.x reflects these changes. Checkout the [docs for 5.0](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-suggesters-completion.html).

Also, FYI if you're running a 2.x version of ES then you should be using a 2.x version of NEST, and 5.x version of NEST if you're running ES 5.x.
