### ISSUE TITLE
Support for .NET Core 1.0 and Json.NET 9

### ISSUE THREAD

**Issue by crohkohl** [elastic/elasticsearch-net#2138]
I am working with the new release of .NET Core 1.0.
It has a dependency on Newtonsoft.Json >= 9.0.

The current Nuget packages require a version < 9.0 and are incompatible with that version.

Is there a way to resolve that in a new release?

Thanks,
Christopher

**Comment by gmarz** [comment]
Hey @crohkohl we're working on releasing 2.4 of the client this week, which will support .NET Core 1.0 and Json.Net 9.

**Comment by crohkohl** [comment]
That are good news. Thanks for your feedback!

**Comment by Mpdreamz** [comment]
Reopening so others will see this ticket too without searching :smile

**Comment by jlandersen** [comment]
Will there be an update to the 1.x client as well to support at least JSON.NET 9?

**Comment by jessegavin** [comment]
Is there any chance this will get released today? Totally ok if it isn't, but will effect a decision about a project that I need to make today.

**Comment by gmarz** [comment]
@jlandersen yes, we will :)

@jessegavin No, probably looking at sometime next week.  We're almost there but there are a few things we need to change in our build that's blocking us from releasing.

**Comment by RTodorov** [comment]
Hey guys, sorry to bother you, any plans to release 2.4.0 this week? I really need to move my project from dnx-rc2 to core... thanks!

**Comment by gmarz** [comment]
FYI we just released [1.9.0](https://github.com/elastic/elasticsearch-net/releases/tag/1.9.0) with support for Json.NET 9.0.1 /cc @jlandersen
