### ISSUE TITLE
Combining Multiple Exclusive Should query

### ISSUE THREAD

**Issue by pavang6** [elastic/elasticsearch-net#2139]
When combining three different bool queries with only Should clause , seeing the first two bool query grouped under the must clause ignoring the third bool.

Below is the code sample and output.

```csharp
var searchResult = elasticClient.Search<AvailableTrucks>(query => query
   .Index(IndexConstants.AvailableTrucksIndex).Size(10000).From(0)
   .Query(q => q
   		.Bool(b => b
		.Must(m => m.MatchAll())
		.Filter(f => 
			(f.Bool(n => n.Must(mustfc.ToArray()))) 
			&& ((
			    f.Bool(n => n.Should(shouldQueryListFirst.ToArray()).Name("firstshould")) 
				&& f.Bool(n => n.Should(ShouldQueryListSecond.ToArray()).Name("secondshould")) 
				&& f.Bool(n => n.Should(ShouldQueryListThird.ToArray()).Name("thirdshould")))
				)
			)
		)
	)
);
```

**Json Output**
```
{  
   "from":0,
   "size":10000,
   "query":{  
      "bool":{  
         "must":[  
            {  
               "match_all":{  

               }
            }
         ],
         "filter":[  
            {  
               "bool":{  
                  "must":[  
                     {  
                        "term":{  
                           "EntityType":{  
                              "value":"LiveTrucks"
                           }
                        }
                     },
                     {  
                        "term":{  
                           "IsKilled":{  
                              "value":false
                           }
                        }
                     },
                     {  
                        "bool":{  
                           "must":[  
                              {  
                                 "bool":{  
                                    "_name":"firstshould",
                                    "should":[  
                                       {  
                                          "term":{  
                                             "IsDaily":{  
                                                "value":true
                                             }
                                          }
                                       },
                                       {  
                                          "range":{  
                                             "AvailableDate":{  
                                                "gte":"42547"
                                             }
                                          }
                                       }
                                    ]
                                 }
                              },
                              {  
                                 "bool":{  
                                    "_name":"secondshould",
                                    "should":[  
                                       {  
                                          "geo_distance":{  
                                             "distance":"100.0mi",
                                             "distance_type":"sloppy_arc",
                                             "OriginCoordinate":{  
                                                "lat":47.3068,
                                                "lon":-122.260607
                                             }
                                          }
                                       }
                                    ]
                                 }
                              }
                           ]
                        }
                     },
                     {  
                        "bool":{  
                           "_name":"thirdshould",
                           "should":[  
                              {  
                                 "term":{  
                                    "IsDestinationBoundaryNull":{  
                                       "value":true
                                    }
                                 }
                              },
                              {  
                                 "match":{  
                                    "DisplayDestinations":{  
                                       "query":"NY"
                                    }
                                 }
                              }
                           ]
                        }
                     }
                  ]
               }
            }
         ]
      }
   }
}
```

**Comment by Mpdreamz** [comment]
The operator overloading wont join two bool queries if they have a `_name` as merging them would alter their meaning. 

This is  one reason why `firstshould` does not move its must clauses to its parent. Then we inspect the `&&` of `firstshould` and `secondshould` both have a `_name` so they get wrapped into another bool with two must clauses. 

We then try to `&&` that wrapped bool query with our `thirdshould` which only has a should clause. Which we can not join into because when a bool has a must clause it has a different default `minimum_should_match` (0) then a bool query **only** should clauses (`min_should_match` being `1` in that case) so these two bool queries can not be joined.

This query rewriting is only combinatorial, if we did multple ipasses we could probably hoist the bool that holds `firsthould` and `secondshould` as must clauses to its parent, but we don't do that mainly because it would be too costly to do multi pass query rewrites.

We do support (and test) the case of doing multiple `q.Bool(b=>.Should())` && q.Bool(b=>.Should())` &&  ` only resulting in to a **single** bool query but the `_name` here changes the semantics where doing that would be wrong. 

Eventhough the query is not rewritten in the most optimal way its still semantically equivalent.

**Comment by pavang6** [comment]
Thanks. 
Here **_name** was introduced consciously to have the locks as suggested here
https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/bool-queries.html.

From the reply which states 

> Then we inspect the && of firstshould and secondshould both have a _name so they get wrapped into another bool with two must clauses.

> We then try to && that wrapped bool query with our thirdshould which only has a should clause. Which we can not join into because when a bool has a must clause it has a different default minimum_should_match (0) then a bool query only should clauses (min_should_match being 1 in that case) so these two bool queries can not be joined.

Worry was with grouping of firstshould and secondshould in Must clause.
Even the **secondshould** only has a should clause but its part of(wrapped in) the must clause. 

Having firstshould , secondshould , thirdshould in a separate bool query in should clause without wrapping them in must clause would still yield the same result? or eqivalent to the above query wrapped in must?

Thanks again for the reply.
