### ISSUE TITLE
NEST DeleteByQueryAsync doesn't delete in 2.3.3

### ISSUE THREAD

**Issue by rasmus** [elastic/elasticsearch-net#2144]
**NEST/Elasticsearch.Net version**: NEST 2.3.3

**Elasticsearch version**: 2.3.3

**Description of the problem including expected versus actual behavior**:
Delete by query (`DeleteByQueryAsync`) in NEST doesn't seem to work correctly or produces an invalid request.

**Steps to reproduce**:
Invoke `DeleteByQueryAsync` by calling it like this

```
_elasticClient.DeleteByQueryAsync<TReadModel>(
    "test-379e05e8-b7a1-40ff-845c-211043b11a6e",
    Types.Type<TReadModel>(), 
    d => d
        .RequestConfiguration(c => c
            .CancellationToken(cancellationToken))
        .Query(q => q.QueryString(qs => qs.Query("*"))));
```

which produces a request similar to this

```DELETE http://127.0.0.1:23531/test-379e05e8-b7a1-40ff-845c-211043b11a6e/thingy/_query```

with the body

```json
{
  "query": {
    "query_string": {
      "query": "*"
    }
  }
}
```

**Provide `DebugInformation` (if relevant)**:
The Elasticsearch server returns the following JSON, in which it has put `_query` in the `_id` field and hasn't deleted anything.

```json
{
  "found": false,
  "_index": "test-379e05e8-b7a1-40ff-845c-211043b11a6e",
  "_type": "thingy",
  "_id": "_query",
  "_version": 1,
  "_shards": {
    "total": 1,
    "successful": 1,
    "failed": 0
  }
}
```

**Comment by gmarz** [comment]
@rasmus I don't think you have the delete-by-query plugin installed.  [It was removed from core in 2.x](https://www.elastic.co/blog/core-delete-by-query-is-a-plugin).

Without the plugin, ES is interpreting this as a delete by id, where `_query` is the doc id.

**Comment by rasmus** [comment]
@gmarz That makes sense, thanks for the information
