### ISSUE TITLE
Missing Batch Size property in ReindexSource while performing Reindexing by ReindexOnServer API

### ISSUE THREAD

**Issue by sumithub** [elastic/elasticsearch-net#2145]
NEST : 2.3.1
ElasticSerach Version: 2.3.1
Elasticsearch 2.3 reindex API allows the users to increase the batch size of reindex  by adding Size within the source request as described in the below document abstract.

https://www.elastic.co/guide/en/elasticsearch/reference/2.3/docs-reindex.html
By default _reindex uses scroll batches of 100. You can change the batch size with the size field in the source element:

POST /_reindex
{
  "source": {
    "index": "source",
    **"size": 1500**
  },
  "dest": {
    "index": "dest"
  }
}

ReindexSource is missing Size property in NEST 2.3.1. Any plans to include missing property in 2.3 branch?

**Comment by russcam** [comment]
Thanks @sumithub, it should be in the `ReIndexOnServer()` API `IReIndexSource` interface and implementations.

A PR for it would be most welcome, if you'd like to contribute one :+1:

**Comment by russcam** [comment]
Thanks for the PR @sumithub, much appreciated! Will fold it into `master` (this is tracking Elasticsearch 5) and port to the `2.x` branch. :+1:

**Comment by russcam** [comment]
This will go into the next `2.x` release (currently scheduled to be 2.4.0) and the next `master` release (5.0.0-alpha4)

**Comment by sumithub** [comment]
Thanks for the update @russcam.
