### ISSUE TITLE
NEST - elasticsearch .net with SIREn

### ISSUE THREAD

**Issue by banony** [elastic/elasticsearch-net#2148]
Hi,

I use Elasticsearch version 2.1.1, with NEST version 2.2.

I found plugin called SIREn which is implement the ability to make join in elasticsearch.
(http://siren.solutions/searchplugins/join).

this plugin has a special syntax which NEST not been supported in.

does NEST intent to develop the ability to use SIREn?
does you work on implement a new objects that support SIREn syntax?

thanks.

**Comment by Mpdreamz** [comment]
We have no direct plans to support the third party plugin `SIREn`. 

NEST is very extensible so if you want to venture into writing a community package with support for SIREn in NEST let me know and i'll gladly help you get started!
