### ISSUE TITLE
Handle recursive error details

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#2152]
[An error in Elasticsearch can have multiple recursive details for the cause of the error](https://github.com/elastic/elasticsearch/blob/master/core/src/main/java/org/elasticsearch/ElasticsearchException.java#L306-L323) e.g.

```javascript    
{
    	"update": {
    		"_index": "testindex",
    		"_type": "docmodel",
    		"_id": "xyz",
    		"status": 400,
    		"error": {
    			"type": "illegal_argument_exception",
    			"reason": "failed to execute script",
    			"caused_by": {
    				"type": "script_exception",
    				"reason": "failed to run inline script [use(java.lang.Exception) {throw new Exception(\"Custermized Exception\")}] using lang [groovy]",
    				"caused_by": {
    					"type": "privileged_action_exception",
    					"reason": null,
    					"caused_by": {
    						"type": "exception",
    						"reason": "Custom Exception"
    					}
    				}
    			}
    		}
    	}
}
```

Currently, the client parses only the top level `type`, `reason` and `caused_by`, but should handle nested `caused_by` objects

**Comment by gmarz** [comment]
This is now in 2.4.2, but leaving this open until it's ported to master.  /cc @russcam

**Comment by russcam** [comment]
Thanks @gmarz, ported to master in cef52d8fa689986d9034f79230a1d5ea532be334
