### ISSUE TITLE
Drop dotnetcore support down netstandard1.1

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#2157]
Since #2149 we built against `netstandard1.3` for maximum platform coverage we should consider dropping down to `netstandard1.1`. Our old DNX based dotnet core beta build against `dotnet5.1` which should be equivalent to `netstandard 1.1`. 

A huge benefit of netstandard is that its self documenting and we do not need to get into the PCL framework matrix mess (https://github.com/elastic/elasticsearch-net/issues/671)

**Comment by gmarz** [comment]
Will add that we're currently blocked from dropping lower than `netstandard1.3` by the following dependencies

 - `System.Collections.Specialized`
 - `System.Reflection.TypeExtensions`

**Comment by Mpdreamz** [comment]
Closing until we see customer requests for this.
