### ISSUE TITLE
asp.net core  ElasticClient  DI scope

### ISSUE THREAD

**Issue by ngonzalezromero** [elastic/elasticsearch-net#2158]
I have this repository class

     public sealed class ProcessDataApiKeyRepository : IProcessDataApiKeyRepository
      {
        private readonly ElasticClient client;
        private static readonly string index = nameof(ProcessDataApiKey).ToLower();
        private readonly AppSettings _appSetting;

        public ProcessDataApiKeyRepository(IOptions<AppSettings> appSetting)
        {
            _appSetting = appSetting.Value;
            
            var node = new Uri(_appSetting.DbConnection.Elastic.Url);
            var settings = new ConnectionSettings(node);
            settings.DefaultIndex(index);
            client = new ElasticClient(settings);
            

        }

        public async Task<bool> SaveApiKeyAsync(ProcessDataApiKey apiKey)
        {
            var response = await client.IndexAsync(apiKey);
            return response.Created;
        }

and inject this class in asp.net core default Di container

         services.AddSingleton<IProcessDataApiKeyRepository, ProcessDataApiKeyRepository>();

Reading the Nest Documentation, the best way to manage the Nest client lifetimes
(https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/lifetimes.html)
 is through the singleton instance.

But, I don't know if this way is the best, because I think that I should be just managing the Nest client class as singleton and then inject in any repository

I made some test using asp.net core scope lifetime

             services.AddScoped<IProcessDataApiKeyRepository, ProcessDataApiKeyRepository>();

and the memory usage for each request was around  50 mg !!!!

with the singleton scope the memory usage peer request was around 2 mg

**Comment by Mpdreamz** [comment]
ConnectionSettings needs to be a singleton its what all the caches are leaning on.

ElasticClient may or may not be registered as a singleton, its thread safe so using a single instance is just fine.

I'd definitely make `IElasticClient` a constructor dependency that gets injected into `ProcessDataApiKeyRepository`

**Comment by gmarz** [comment]
+1 to what @Mpdreamz said.

To elaborate a bit further, your current implementation of 

```
services.AddSingleton<IProcessDataApiKeyRepository, ProcessDataApiKeyRepository>();
```

will cause each repository to have their own `ConnectionSettings` caches, which is definitely better than `AddScoped` which will create a new `ConnectionSetting`s every time, basically defeating the purpose caching (hence the 50ms vs 2ms difference you observed).

But injecting a singleton instance of `ConnectionSettings` as Martijn suggested into each repository will cause all your repositories to share the same caches which will result in overall better performance.

**Comment by ngonzalezromero** [comment]
@gmarz  Thank you

**Comment by aakesh001** [comment]
Can anyone show me how to create a singleton object of Elasticclient in .net?  for .net core it is straight forward.

**Comment by MarounMaroun** [comment]
@Mpdreamz @gmarz so combining your suggestions I came up with the following. Would be glad to hear if it's a good approach:

Connector:

```c#
public class ElasticsearchConnector
{
    public ElasticClient Client { get; }

    public ElasticsearchConnector()
    {
        var endpoint = Environment.GetEnvironmentVariable("ELASTIC_ENDPOINT");
        var apiKey = Environment.GetEnvironmentVariable("ELASTIC_API_KEY");
        if (endpoint is null || apiKey is null)
        {
            Logger.Error("ElasticsearchConnector: Missing environment variables");
            throw new Exception("missing Elasticsearch environment variables");
        }
        var settings = new ConnectionSettings(new Uri(endpoint))
            .ApiKeyAuthentication(new ApiKeyAuthenticationCredentials(apiKey))
            .DefaultMappingFor<Document>(m => m.IndexName("<mapping>"))
            .EnableApiVersioningHeader();

        Client = new ElasticClient(settings);
        var healthy = Client.Cluster.Health().IsValid;
        Logger.Information("Elasticsearch connection healthy: {Healthy}", healthy);
        if (!healthy)
        {
            Logger.Warning("Elasticsearch is not healthy");
        }
    }
}
```

Above connector lifetime scope is a singleton.


Repository:

```c#
public class MyRepository : AutoIndexedElasticsearchRepository<Document>, IMyRepository
{
    public MyRepository (ElasticsearchConnector connector) : base(connector, "myindex")
    {
    }
}
```

`AutoIndexedElasticsearchRepository`:

```c#
public class AutoIndexedElasticsearchRepository<T> : IAutoIndexedElasticsearchRepository<T> where T : class
{
    private readonly IElasticClient _client;

    public AutoIndexedElasticsearchRepository(ElasticsearchConnector connector, string indexName)
    {
        _client = connector.Client;

        // create index if not exists (auto-map fields)
        if (!_client.Indices.Exists(indexName).Exists)
        {
            Logger.Information("{Index} doesn't exist, creating it", indexName);
            _client.Indices.Create(indexName,
                c => c.Map<T>(m => m.AutoMap<T>()));
            Logger.Information("successfully created {Index} with auto-mapping", indexName);
        }
    }

    public async Task<T> GetByIdAsync(string id)
    {
        var response = await _client.GetAsync<T>(id);
        return response.Source;
    }

    public async Task<IEnumerable<T>> GetAllAsync()
    {
        var searchResponse = await _client.SearchAsync<T>(s => s.MatchAll());
        return searchResponse.Documents;
    }

    public async Task AddAsync(T document)
    {
        await _client.IndexDocumentAsync(document);
    }

    public async Task UpdateAsync(string id, T document)
    {
        await _client.UpdateAsync<T, T>(id, u => u.Doc(document));
    }

    public async Task DeleteAsync(string id)
    {
        await _client.DeleteAsync<T>(id);
    }
}
```

**Comment by stevejgordon** [comment]
@MarounMaroun Seems reasonable since it ensures that the client instance is reused as a singleton to reuse connections etc.
