### ISSUE TITLE
Analyze operation legacy request

### ISSUE THREAD

**Issue by macebalp** [elastic/elasticsearch-net#2169]
**Describe the feature**:

When an analyze operation is performed, the request generated to ES contains the text to analyze as the body of the request and the rest of parameters in the query string. This is maintained by ES for backward compatibility and has limitations (text cannot start by '{') as described here: https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-analyze.html. I have looked in your code base and seen this is done in: ElasticClient (https://github.com/elastic/elasticsearch-net/blob/2.x/src/Nest/Indices/Analyze/ElasticClient-Analyze.cs).

I would suggest to pass all the parameters in the body of the request as json as described in the above ES documentation link.

**Comment by russcam** [comment]
Thanks for opening this @macebalp; I agree that it would be better to use the json payload to call `_analyze`, since it handles starting `{` in the text.
