### ISSUE TITLE
NodesInfo: Could not convert string to integer

### ISSUE THREAD

**Issue by gigi81** [elastic/elasticsearch-net#2172]
When Invoking the Nest.ElasticClient.NodesInfo() method on my elasticsearch cluster I get the following exception:

Could not convert string to integer: 1k. Path 'nodes.3lJFeKYpRaWqY3Flam9omg.thread_pool.percolate.queue_size'

   at Elasticsearch.Net.Transport`1.Request[TReturn](HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters)
   at Elasticsearch.Net.ElasticLowLevelClient.NodesInfoForAll[T](Func`2 requestParameters)
   at Nest.LowLevelDispatch.NodesInfoDispatch[T](IRequest`1 p)
   at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch)

I'm using Elasticsearch v1.7.1 and the latest version of the library released in nuget.

**Comment by gmarz** [comment]
Hi @gigi81 the latest version of NEST (currently 2.4.1) is not compatible with Elasticsearch 1.7.1.

Check out the [compatibility matrix](https://github.com/elastic/elasticsearch-net#compatibility-matrix) on our readme.  Basically, the client and ES are compatible on major versions only.  So any 2.x version of NEST is compatible with any 2.x version of ES, NEST 1.x with any verison of ES 1.x, etc...

You'll have to downgrade to NEST 1.9.0 (latest release off the 1.x branch).  Can you try that and let us know if the problem still persists?

**Comment by gigi81** [comment]
Hi @gmarz 
I confirm it works with elasticserch 2.3.3 so I guess you can close the issue.
Anyway, my requirement is to support both versions and eventually 5.x
So what would be your suggested approach in supporting both versions? Can both assemblies be loaded at the same time?
Thanks
Luigi

**Comment by gmarz** [comment]
> Can both assemblies be loaded at the same time?

No.  I would recommend separate applications.
