### ISSUE TITLE
.NET Core 1.0 Support

### ISSUE THREAD

**Issue by edikep2000** [elastic/elasticsearch-net#2184]
I did like to know if either or both of these libraries have been ported to the new .NET Core 1.0 Framework.

**Comment by Mpdreamz** [comment]
We support netstandard 1.3 and thus .NET core.

**Comment by javadbat** [comment]
how about .net core 2 ? anyone know doc we can use elastic in .netcore 2

**Comment by Mpdreamz** [comment]
1.3 should be forward compatible with 2.0 as 2.0 is a superset of 2.0.
