### ISSUE TITLE
HTTPS Cert Validation Callback in .Net Core

### ISSUE THREAD

**Issue by hermanho** [elastic/elasticsearch-net#2198]
In the .net framework version, it is allowed to check the HTTPS cert with method overriding.
```csharp
 public class HttpsConnection : HttpConnection
    {
        protected override HttpWebRequest CreateHttpWebRequest(RequestData requestData)
        {
            var request = base.CreateHttpWebRequest(requestData);
            request.ServerCertificateValidationCallback = (sender, cert, chain, error) =>
            {
 /// perform the checking on the self-signed cert
                return true;
            };
            return request;
        }
    }
```
The .Net team has changed the code now. It is handled in HttpClientHandler. Is it possible do the similar way in .Net Core version? It seems this is the only way to check cert chain manually when we do not have permission to install the cert in the server.

Ref:
https://github.com/dotnet/corefx/issues/4476
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClientHandler.Windows.cs#L167
https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.cs#L1511

**Comment by gmarz** [comment]
Not currently, as we don' expose the [HttpClientHandler](https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs#L43).  We'll look into a good way to support this.
