### ISSUE TITLE
QueryContainer |= operator returns null 

### ISSUE THREAD

**Issue by JensVanhooydonck** [elastic/elasticsearch-net#2206]
**NEST/Elasticsearch.Net version**: 2.4.3

`QueryContainer should = new QueryContainer();`
`should |= new TermsQuery() { Field = "theme_theme.Id" };`

or

`QueryContainer should = new QueryContainer();`
`should |= new QueryContainer(new TermsQuery() { Field = "theme_theme.Id" });`

![image](https://cloud.githubusercontent.com/assets/5812950/17619552/4b878d80-6086-11e6-9f8b-ff0d4f9c25da.png)

Both return null instead of the combined QueryContainer.
 It has worked but suddenly stopt working.

**Comment by russcam** [comment]
['TermsQuery' is considered conditionless](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Nest/QueryDsl/TermLevel/Terms/TermsQuery.cs#L32-L49) if 
- `Field` is considered conditionless (basically doesn't resolve to a value), 
or 
- there are no terms or all terms are null or in the case of strings, empty strings
or
- terms lookup is null or missing a value needed for the lookup.

In this case, the Terms query neither has terms nor a terms lookup. Adding terms works

```c#
QueryContainer should = new QueryContainer();
should |= new TermsQuery() { Field = "theme_theme.Id", Terms = new[] { "a" } };

client.Search<object>(s => s.Query(q => should));
```

yields

```json
{
  "query": {
    "terms": {
      "theme_theme.Id": [
        "a"
      ]
    }
  }
}
```
