### ISSUE TITLE
StackOverflowException when combining many bool queries

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch-net#2209]
Repro here https://github.com/elastic/elasticsearch-net/commit/fe4a52ea075eb7a58eea06911996c280f1f52ede

Starts to happen after ~1000 iterations.  We should be able to support `max_clause_count`.

**Comment by gmoskovicz** [comment]
@gmarz it would be great to support max_clause_count, but since it's a setting in Elasticsearch maybe the best approach is to set it to 2 times the limit by default, which is 1024? Or are we planning to read the setting dynamically ?

**Comment by gmarz** [comment]
We just need to support the max value that `max_clause_count` can be set to.  No need to actually read the setting.

**Comment by gmoskovicz** [comment]
@gmarz max_clause_count max size is `Integer.MaxInt`.
