### ISSUE TITLE
ITermVectorFilter missing filters

### ISSUE THREAD

**Issue by attilalaszlo** [elastic/elasticsearch-net#2210]
https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Document/Single/TermVectors/TermVectorFilter.cs

only implements three types of filters:
- max_num_terms
- min_term_freq
- min_doc_freq

But the Elasticsearch support more TermVector Filter:
- max_term_freq
- max_doc_freq
- min_word_length
- max_word_length

Can we have all the filters in the TermVectorFilter? (maybe in the next 2.X release?)

Thanks!

**Comment by gmarz** [comment]
Thanks for reporting @attilalaszlo, we'll add these for the next release.
