### ISSUE TITLE
Failed to serialize the response body for content type 'application/json' for ISearchResponse<T>

### ISSUE THREAD

**Issue by rentianhua** [elastic/elasticsearch-net#2216]
I have founded a MVC5 webapi project, and set a http api to get request from ES using NEST then return response. like below

![Uploading image.png…]()

Event though, i attempt to return `response.Highlights` , it is still failed to serialize.

Do you have any way to handle the serialize problem?

**Comment by rentianhua** [comment]
[RoutePrefix("api/webapi")]
    public class WebAPIController : ApiController
    {
        [HttpPost]
        [Route("PatentSearch")]
        public object PatentSearch(IPCriteria criteria)
        {
            IEsService service = new EsService();
            var response = service.SearchIPEntities(criteria);

            return response;
        }
    }

**Comment by mcboman** [comment]
Had a serialization problem my self. One where a value could be either a string[] or a string. The way I resolved it was by create 2 props. One as a string and another as a string[]. You could try to set the exception field as type of Object instead of the current type.

**Comment by russcam** [comment]
@rentianhua, do you have 

1. The POCO structure that you are using and the query (in NEST) that you are doing
2. a sample json response from Elasticsearch for the query

Without these things, it's difficult to investigate. If you could provide these things, I may be able to help further.

**Comment by russcam** [comment]
@rentianhua Is this the same issue as #2168? Returning documents with highlights where documents may have the same id?

**Comment by rentianhua** [comment]
i think they may same. Now i use low_type api to workaround.

**Comment by russcam** [comment]
@rentianhua Thanks for reporting back. Because `.Highlights` is just a helpful extension (although not helpful in this case :smile: ) for getting all highlights from all hits, you can do enumerate over to get all the highlights without needing to use the low level API. Something like

```c#
var response = client.Search<Page>(s => s.MatchAll());

foreach (var hit in response.HitsMetaData.Hits)
{
    var highlights = hit.Highlights;
    // do something with highlights
}
```

I'm going to close this issue as it's related to #2168; feel free to reopen if that's not the case

**Comment by rentianhua** [comment]
Thanks. i will try later 😄
