### ISSUE TITLE
Missing "conflicts" on ReindexOnServer api

### ISSUE THREAD

**Issue by emmekappa** [elastic/elasticsearch-net#2219]
Reading Elastic documentation at https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html: 

> By default version conflicts abort the _reindex process but you can just count them by settings "conflicts": "proceed" in the request body

But I don't see any way to specify this options within ReindexOnServer API

**Comment by russcam** [comment]
Thanks for opening an issue @emmekappa, I'll add this now for the next release which we're looking to push out this week :+1:
