### ISSUE TITLE
Expose Descriptor mappings 

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2222]
Would it be possible to expose mapping descriptors in 1.x and 2.x. In our case I want to extend the fluent mappings to add support for aliases (local alias map) but also get access to analyzer info so we can pass a map to our query builder to optimize (term vs query string builders). Right now all of this is internal.

**Comment by gmarz** [comment]
Can you provide an example?  I'm all for opening the client up for extension where possible but need to get a better understanding of what you're proposing here.

**Comment by niemyjski** [comment]
I want to do something like this `.String(f => f.Name(e => e.Name).IndexName(Fields.Name).Index(FieldIndexOption.Analyzed).AddAlias("Blah", _alias))`

Which takes a look at the index name and allows me to create an alias map. Alternatively if I could get access to the raw mapping, I could create a visitor and create these much easier. I'd also like to create a map of all the analyzed fields.

**Comment by niemyjski** [comment]
Was thinking it would be cool if you could get access to the mapping and also have like a bag on the mapping itself (that wasn't sent to elastic, but allowed me to add meta data to the mapping and I could then view it later (via a visitor). Then I could just do `.String(f => f.Name(e => e.Name).IndexName(Fields.Name).Index(FieldIndexOption.Analyzed).AddAlias("custom_name").AlwaysUseMatchQuery())`.

**Comment by ejsmith** [comment]
@gmarz exposing the mapping configuration is useful in a lot of ways. Probably the biggest way would be to allow someone to build a proper LINQ provider without having to duplicate the mapping configuration like this project had to do: https://github.com/CenturyLinkCloud/ElasticLINQ

**Comment by Mpdreamz** [comment]
Discussed in slack with @ejsmith and @niemyjski our `MappingVisitor` especially in its `2.x` incarnation suffices here.
