### ISSUE TITLE
GetAlias does not return list of indices

### ISSUE THREAD

**Issue by babadofar** [elastic/elasticsearch-net#2230]
**NEST/Elasticsearch.Net version**:
NEST-5.0.0-alpha3
**Elasticsearch version**:
5.0.0-alpha5
**Description of the problem including expected versus actual behavior**:
The GetAlias function does not return list of indices an alias points to 

**Steps to reproduce**:
 1. 
Create indices and an alias pointing to these indices 
```
PUT /fisk_1/fisk/1
{"fisk": 1}
PUT /fisk/fisk/1
{"fisk": 1}

PUT /fisk_21/fisk/1
{"fisk": 1}

PUT /fisk/_alias/ocean
PUT /fisk_1/_alias/ocean
PUT /fisk_21/_alias/ocean
```

 2.  Execute GetAlias on a Nest Client
``` 
var settings = new ConnectionSettings()
				.DisableDirectStreaming(true);
ElasticClient client = new ElasticClient(settings);
var aliases = client.GetAlias(a => a.Name("ocean"));
var indices = aliases.Indices.Keys;
``` 
 3.  Results in indices being empty

The exact same code works for Elasticsearch versjon 2.3.5 and NEST 2.4.4

**Comment by babadofar** [comment]
Additionally the `GetIndicesPointingToAlias` method has disappeared in 5.0

**Comment by russcam** [comment]
Thanks @babadofar; I fixed the issue with this in https://github.com/elastic/elasticsearch-net/commit/35b41b3c648431dacbe91c3d8d3fc5ea68b759d0 and also added back the helper methods.

We're working on getting a `5.x` release compatible with Elasticsearch 5.0.0-alpha5 now and will release shortly. The above fix will be included in that next release.

**Comment by russcam** [comment]
@babadofar, we publish CI builds of NEST onto MyGet so feel free to [use the latest on there that contains the fix](https://www.myget.org/feed/elasticsearch-net-next/package/nuget/NEST/5.1.0-ci20160829014515), until the nuget package is released.

**Comment by babadofar** [comment]
Great! I actually tried to search the repo to see if this had been fixed. My github-fu must be low. Thank you:)
