### ISSUE TITLE
Nested attribute on List<string> generating unwanted properties

### ISSUE THREAD

**Issue by shakdoesgithub** [elastic/elasticsearch-net#2232]
**NEST/Elasticsearch.Net version**: 2.3.3

**Elasticsearch version**: 2.3.2

**Description of the problem including expected versus actual behavior**:

I have a mapping for a list<string> set with the Nested attribute and it's creating unwanted properties on the ES mapping. 

```
[Nested(IncludeInParent=true)]
public List<String> raw_amenities { get; set; }
```

yields

```
raw_amenities": {
     "type": "nested",
     "include_in_parent": true,
     "properties": {
          "chars": {
               "type": "string"
           },
           "length": {
               "type": "integer"
            }
      }
}
```

**Comment by gmarz** [comment]
Hey @shakdoesgithub the `nested` type is for objects and doesn't make any sense for strings.  What's happening here is a side effect of the client expecting an object when the `Nested` attribute is applied, treating string as an object and mapping its properties.

@russcam @Mpdreamz Perhaps, we should thrown an exception in this case instead of naively inferring the CLR properties?

**Comment by shakdoesgithub** [comment]
hey @gmarz,

So I'm a little big confused, since https://www.elastic.co/guide/en/elasticsearch/reference/2.3/nested.html says that 

"The nested type is a specialised version of the object datatype that allows arrays of objects to be indexed and queried independently of each other." 

My use case is to store the list of strings into this mapping. How would I go on about doing that, if not using a nested type?

**Comment by gmarz** [comment]
> arrays of objects

:)  Under the hood, everything is flattened in Lucene.  There is no actual array type.  So an array of any core type (string, integer, etc...) is really just its underlying type.  Check out the [docs on array datatypes](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/array.html).

In this case you would just map `raw_amenities` as a string.

Hope that makes sense?

**Comment by russcam** [comment]
Just to follow up on what @gmarz has said, you would want to map it as a string type

**Comment by russcam** [comment]
@gmarz I'm in two minds about whether we should throw an exception here; the example mapping may be perfectly valid for some use case. 

Were you thinking throw for certain types and not for others?

**Comment by shakdoesgithub** [comment]
@russcam thanks for that explanation.  I know I'v been down that path before getting mixed up between nested and object types, but your example helped me understand it.

**Comment by shakdoesgithub** [comment]
Reopening because of ongoing discussion between @russcam  and @gmarz

**Comment by gmarz** [comment]
> Were you thinking throw for certain types and not for others?

@russcam I'm thinking that we shouldn't allow `Nested` or `Object` on types that aren't actual objects (i.e. non-reference types).

I can't think of any use cases where this would be valid otherwise...?

**Comment by Mpdreamz** [comment]
Closing this before we attempt something to clever :smile: we'd have to unpack `PropertyType` see if its `IEnumerable<T>` then check if T is a reference type all for a small gain.
