### ISSUE TITLE
GreaterOrEquals, LowerOrEquals breaking changes are missing on 2.0 breaking changes doc

### ISSUE THREAD

**Issue by tugberkugurlu** [elastic/elasticsearch-net#2237]
This is on `NumericRangeQueryDescriptor`. I would add it and PR this but I am not sure where to add it. I assume equivalents are `GreaterThanOrEquals` and `LessThanOrEquals`.

**Comment by russcam** [comment]
Thanks @tugberkugurlu. [Are you looking at this breaking changes documentation?](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/nest-breaking-changes.html)

Your assumption is correct; the names were changed to better align with the abbreviated operator names (`gt`, `gte`, etc.)

**Comment by tugberkugurlu** [comment]
@russcam yep, I was looking at that doc. I was not sure where to add that breaking change inside the doc. Hence the issue instead of a PR 😄

**Comment by russcam** [comment]
I've added this to the breaking changes docs
