### ISSUE TITLE
Unexpected behaviour on PropertiesDescriptor fluent mapping

### ISSUE THREAD

**Issue by esukirno** [elastic/elasticsearch-net#2238]
**NEST/Elasticsearch.Net version**: 2.4.3

**Elasticsearch version**: 2.3.4

**Description of the problem including expected versus actual behavior**:

 public class DummyObject
        {
            public int Id { get; set; }
            public string Name { get; set; }
            public string Suburb { get; set; }
        }

`
   
     private static TypeMappingDescriptor<DummyObject> MapMe(TypeMappingDescriptor<DummyObject> map) => map

            .AutoMap()

            .Properties(ps => ps

                .String(s => s

                    .Name(n => n.Name).Fields(fs => fs.String(ss => ss.Name("sort").NotAnalyzed()))

                    .Name(n => n.Suburb).Fields(fs => fs.String(ss => ss.Name("sort").NotAnalyzed())))
            );
`

NEST fluent mapping allows me to specify multiple Name Descriptor inside a String Property Descriptor. But instead of adding Sort Field (as per sample above) to Name and Suburb Field, NEST would only add Sort Field to Suburb Field (I presume because it is the last Name Descriptor in the declaration).

I soon realize that I am not supposed to put multiple Name Descriptor inside String Property Descriptor. Should NEST allow this behavior on the first place?

**Steps to reproduce**:
 1.
 2.
 3.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by gmarz** [comment]
> I soon realize that I am not supposed to put multiple Name Descriptor inside String Property Descriptor

That's correct.  For the record, the propery syntax is

```csharp
 .Properties(ps => ps
    .String(s => s
        .Name(n => n.Name)
        .Fields(fs => fs.String(ss => ss.Name("sort").NotAnalyzed()))
    )
    .String(s => s
        .Name(n => n.Suburb)
        .Fields(fs => fs.String(ss => ss.Name("sort").NotAnalyzed()))
    )
```

> Should NEST allow this behavior on the first place?

Yes.  There are valid uses cases for being able to override existing values.

Closing this one @esukirno.  Feel free to re-open though if you feel strongly about this.
