### ISSUE TITLE
Document async options

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch-net#2239]
We support async methods for all the sync ones, but we don't talk about this at all in the docs.

Can we get something adding so people are aware of it?

**Comment by Mpdreamz** [comment]
Our long term plan here is to generate all our `ApiTests` and `CrudTests` to docs under

https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/index.html

in an API section e.g

https://github.com/elastic/elasticsearch-net/blob/master/src/Tests/Document/Single/Get/GetApiTests.cs

Would live under `api/document/single/get.html`

We will pick one of the 4 ways (sync/async and inititalizer/fluent) through consistent hashing to fully describe the endpoint and its body and response handling. 

Right now we only generate our `UsageTests` and we still have to work out how to nest the current docs better before we inject more pages all under the same banner :) e.g there is no subdivision under Query DSL and Aggregations in the docs but we would like it to reflect our folder structure (which mimics the es core docs).

**Comment by Mpdreamz** [comment]
closing this in favor of new tracking issue: #2248
