### ISSUE TITLE
Add Compatibility Matrix from README to docs

### ISSUE THREAD

**Issue by joshuar** [elastic/elasticsearch-net#2243]
Hey team,

Would we be able to add the compatibility matrix from here:

https://github.com/elastic/elasticsearch-net#compatibility-matrix

In the docs?  Potentially before the Breaking Changes or on the intro page?

**Comment by russcam** [comment]
Good idea @joshuar; I'll need to implement table parsing in our asciidoc parser for this :smile:

**Comment by Mpdreamz** [comment]
closing this in favor of new tracking issue: #2248
