### ISSUE TITLE
Hang when combining Bulk with Update

### ISSUE THREAD

**Issue by rongchaua** [elastic/elasticsearch-net#2244]
**NEST/Elasticsearch.Net version**: 2.4.5

**Elasticsearch version**: 2.3.3

**Steps to reproduce**:

When I execute the code listing below. The client.Update() can be executed without any problem. The BulkAsync with Update() simply hangs and doesn't throw any exception. I'm not sure where my code is wrong or it's error of nest.
I run this code in a unit test.

```
dynamic blogUpdate = new ExpandoObject();
blogUpdate.Title = "My updated blog post";
client.Update<Blog, dynamic>(new DocumentPath<Blog>(123), u => u.Doc(blogUpdate));

Result = await client.BulkAsync(b =>		
		b.Update<Blog, dynamic>(u => u.Id(123).Doc(blogUpdate)));
```

**Comment by gmarz** [comment]
@rongchaua Are you checking the response on `Result`?  It might be failing silently unless you enable exceptions by calling `.ThrowExceptions()` on your `ConnectionSettings` instance.

Can you try using something like Fiddler to inspect the whether a request is actually being sent, and what the response is from ES?

**Comment by rongchaua** [comment]
@gmarz : There is no request sending to ES server. It just hangs after "u.Id(123).Doc(blogUpdate)" and nothing happens then. No request, no response. UnitTest hangs.

**Comment by Mpdreamz** [comment]
I think you are getting bit by this issue: https://github.com/elastic/elasticsearch-net/issues/732

On phone now but will reply later if that issue is not enough information

**Comment by rongchaua** [comment]
@Mpdreamz : #732 is almost as same as my issue. However my problem is on the contrary. My normal Update works and Bulk+Update doesn't. 
Can you reproduce my issue? Do you need more information?

**Comment by Mpdreamz** [comment]
@rongchaua I think the root cause for both is the same and related too:

http://stackoverflow.com/questions/27011810/mystery-with-dynamic-type-double-dispatch

An immediate fix is:

```csharp
var result = await client.BulkAsync(b => b.Update<Blog, dynamic>(u => u.Id(123).Doc((object)blogUpdate)));
```

Note the explicit `(object)` cast to avoid the dispatch problem. There is not much we can do to mitigate the need for this explicit cast.
