### ISSUE TITLE
Safe Way to Issue Parametrized Search with Raw JSON Body

### ISSUE THREAD

**Issue by tugberkugurlu** [elastic/elasticsearch-net#2245]
This is more of a question than an issue. 

Let's assume that I want to run the below query through the .NET client:

```
GET movie-app/movies/_search
{
  "query": {
    "term": {
      "name": {
        "value": "star"
      }
    }
  }
}
```

I can see that I am able to do this through the fluent search syntax or object initializer syntax in C# but what I actually want to do is to write the query in a JSON{ish} way and parametrize the values. I think I am currently able to do this (with [NEST version `2.4.5`](https://www.nuget.org/packages/NEST/2.4.5)) in a dangerous way; very open to some sort of injection attacks 😄, which I cannot anticipate what those would be (but would also be good to know what they are if it's available handy somewhere). Here is my dangerous attempt:

`aggs-query.json` file:

```
{
  "query": {
    "term": {
      "name": {
        "value": @lookupTerm
      }
    }
  }
}
```

Code to issue the query:

```
var loopupTerm = "star";
var client = new ElasticLowLevelClient();
var aggsQueryFilePath = Path.Combine(PlatformServices.Default.Application.ApplicationBasePath, "aggs-query.json");
var queryTemplate = ReadToEnd(aggsQueryFilePath);
var queryToIssue = queryTemplate.Replace("@lookupTerm", $"\"{loopupTerm}\"");
var result = client.Search<string>(queryToIssue);
```

So, I am wondering whether there is a safe way to do this in NEST. My aim here is to not write unmaintainable C# code to craft queries. In my sample, it's small. So, it doesn't matter that much but for big queries, it gets really scary 😞

**Comment by russcam** [comment]
In what scenario would you want to build dynamic queries with string replacement as opposed to building the query with the fluent API, object initializer syntax or an anonymous type? Would like to understand your use case better.

**Comment by tugberkugurlu** [comment]
> In what scenario would you want to build dynamic queries with string replacement

@russcam any query I want to issue to Elasticsearch, I want to send the query as a raw JSON string. So, the short answer is in every scenario if possible.

**Comment by tugberkugurlu** [comment]
As stated above, my aim here is to not write unmaintainable C# code to craft queries. In my sample, it's small. So, it doesn't matter that much but for big queries, it gets really scary.

**Comment by tugberkugurlu** [comment]
This is the code for my poor attempt on this: https://github.com/tugberkugurlu/ElasticsearchSamples/tree/6ff600c001bfaf3f0f50d681ae30ac708177a967/elastic-2-sample

**Comment by russcam** [comment]
> > In what scenario would you want to build dynamic queries with string replacement

> @russcam any query I want to issue to Elasticsearch, I want to send the query as a raw JSON string. So, the short answer is in every scenario if possible.

Let me clarify: in what scenario would you want to build dynamic queries with strings **over** using strong types?

**Comment by tugberkugurlu** [comment]
I am sorry, I don't know what you mean by "scenario" here.

**Comment by russcam** [comment]
I'm trying to understand the underlying motivation for doing string replacement over working with strong types; unlike for example, SQL statements, where there are mechanisms for safely parameterizing a string of SQL, I'm not aware of any mechanisms to do this with JSON strings. 

You could potentially deserialize the json into some type e.g. `JObject` may be sufficient, and perform the replacement there but I'm trying to understand what this might buy you over creating the request with the fluent API or object initializer syntax.

**Comment by Mpdreamz** [comment]
@tugberkugurlu closing this as this seems out of scope for the client. 

Either you read to string and using a general purpose json library to replace safely (e.g json.net's linq support). 

Or you deserialize into one of NEST's classes e.g `SearchRequest` and modify the graph from there. 

Let me know if you feel strongly this should be part of the client!
