### ISSUE TITLE
Documentation: Clarify how a Connection Pool works

### ISSUE THREAD

**Issue by caleblloyd** [elastic/elasticsearch-net#2260]
**Documentation: Clarify how a Connection Pool works**

Most databases connectors make use of the term "ConnectionPool" to describe a pool of connections that are held open to the database that should be locked for use, used for a set of operations, and then unlocked and returned to the pool.

In Elasticsearch.NET / NEST however, a "ConnectionPool" is a pool of upstreams that can be reached.

As a newcomer to the library, I immediately looked to implement Connection Pooling to increase throughput.  I landed on the [ConnectionPooling](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/connection-pooling.html) page, but was left with quite a few questions:

- Where is the Connection Pool Size option?
- Does an ElasticClient generated from a Connection Pool serialize requests?
- If so, will implementing my own pool of ElasticClients increase throughput?

I finally stumbled upon this [StackOverflow](http://stackoverflow.com/questions/11334717/connection-pooling-with-nest-elasticsearch-library/11335211#11335211) answer by @Mpdreamz that cleared things up.

I think that the [ConnectionPooling](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/connection-pooling.html) page should highlight the following takeaways:

1. A Single ElasticClient per ConnectionPool should be used throughout an Application
2. "The default IConnection uses WebRequest.Create which already pools TCP connections."
3. "Reusing ElasticClient won't offer any performance gains since each call already gets its own HttpWebRequest."

(2,3 are direct quotes from @Mpdreamz on his [StackOverflow](http://stackoverflow.com/questions/11334717/connection-pooling-with-nest-elasticsearch-library/11335211#11335211) answer)

**Comment by Mpdreamz** [comment]
Hey @caleblloyd thanks for the feedback!

I thought our [connection pooling](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/connection-pooling.html) page did a good job explaining that but will expand on it more with your points! 

That StackOverflow answer is a bit outdated although many of the general best practices still apply. In any case its important to share the same `ConnectionSettings` instance across any elastic client you instantiate. ElasticClient can be a singleton or not as long as each instance shares the same `ConnectionSettings`instance. 

All of our caches are per `ConnectionSettings`, this includes serialization caches.

Also a single `ConnectionSettings` holds a single `IConnectionPool` and `IConnection` something you definitely want to reuse across requests.

Our [lifetimes](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/lifetimes.html) goes into this as well.

If you run on the [desktop CLR each request instantiates its own webrequest](https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Connection/HttpConnection.cs#L122) if you are on .NET core a single [HttpConnection uses a single `HttpClient`](https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs#L34) on which its safe to call multiple request concurrently. No serialization of requests will occur using a single ElasticClient instnace.

The actual TCP connection pooling in .NET is handled by ServicePointManager, [this article](https://blogs.msdn.microsoft.com/adarshk/2005/01/02/understanding-system-net-connection-management-and-servicepointmanager/) does a good job explaining the various stages.

If you need more control here [subclass our HttpConnection and override `AlterServicePoint`](https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Connection/HttpConnection.cs#L74)

Closing this and amending #2248 with this feedback. 

Let me if the above pointers were helpful

**Comment by caleblloyd** [comment]
@Mpdreamz thanks for the clarification!  The [lifetimes](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/lifetimes.html) page is very helpful, but the additional detail you have provided here clears up questions about how the actual TCP Connections are pooled.

I think that these pointers would be a great addition to the Connection Pooling docs!
