### ISSUE TITLE
FieldLookup should include "routing" property

### ISSUE THREAD

**Issue by seanwm** [elastic/elasticsearch-net#2261]
**Describe the feature**:

As documented here:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html

the Terms Query lookup supports a "routing" option, necessary when referencing a document in an index that uses custom routing. I need to use this, but NEST doesn't currently support that routing option with the FieldLookup class. Any chance we could see that added?

**Comment by seanwm** [comment]
Workaround for anyone else running into this:

    public class RoutableFieldLookup : IFieldLookup
    {
        public Id Id { get; set; }
        public IndexName Index { get; set; }
        public Field Path { get; set; }
        public TypeName Type { get; set; }
        [JsonProperty("routing")]
        public string CustomRouting { get; set; }
    }

That plain ol' string property isn't going to do anything to make sure your routing value makes any sense, so caveat coder.

**Comment by Mpdreamz** [comment]
Thanks @seanwm we'll add it to our next releases :+1: 

Side note: I'm super happy you were able to hack what you needed through implementing our interface with your own class. This is exactly why we made such a push for interface everywhere! :smile:

**Comment by seanwm** [comment]
Thanks. And yeah, I was really pleasantly surprised that I could just drop in my simple replacement class, kudos!
