### ISSUE TITLE
script file is not working

### ISSUE THREAD

**Issue by hiteshbhatt** [elastic/elasticsearch-net#2273]
```c#
ISearchResponse<Tenant> response = elasticContext.Client.Search<Tenant>(s=>s
    .Query(q=>q
        .Bool(b=>b
            .Filter(f=>f
                .Script(sc=>sc
                    .Name("query")
                    .Params(p=>p
                        .Add("lat",lat)
                        .Add("log",log)
                    )
                    .File("TenantByLocation")
                )
            )
        )
    )
);
```

```json
"query":{
 "bool": {
  "filter": {
   "script": {
     "script": {
      "file": "TenantByLocation"
     }, 
     "params": {
      "lat":28.412679,
      "log":77.043943
     }
   }
 }
}
``` 

but it should produce json this way:

```json
"query":{
 "bool": {
  "filter": {
   "script": {
    "script": {
     "file": "TenantByLocation" , 
     "params": {
      "lat":28.412679,
      "log":77.043943
     } 
    }
   }
  }
 } 
}
```

Get thing error ueryParsingException[script params must be specified inside script object in a [script] filter];
I am writhing this query it is producing json like this:

**NEST/Elasticsearch.Net version**:

**Elasticsearch version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Describe the feature**:

**Comment by russcam** [comment]
Hey @hiteshbhatt , it would really help if you could highlight the code using code blocks ( \`\`\` **before and after code**, with an optional language after the opening \`\`\` ) and also indent json; it took me a little while to see where the difference was in your examples, which is much easier to see now it's indented.

You haven't answered what version of NEST you're using, what Elasticsearch version you're targeting or any of the questions in the issue template. That makes it difficult to address with what you've provided.

I've just tried this with NEST 2.4.5 and get the expected result:

```json
{
  "query": {
    "bool": {
      "filter": [
        {
          "script": {
            "_name": "query",
            "script": {
              "file": "TenantByLocation",
              "params": {
                "lat": 28.412679,
                "log": 77.043943
              }
            }
          }
        }
      ]
    }
  }
}
```

If you're targeting Elasticsearch 2.x, I would recommend upgrading the client to this version.

**Comment by hiteshbhatt** [comment]
Hey,
I am using NEST 2.4.5
Elastic Version = 2.3.3
Nest is not returning Result .When I am Reading Groovy Script saved to disk.

But When I am trying with Kibana With This query Work
`{
  "query": {"bool": {"filter": {"script": {
    "script": {"file": "TenantByLocation","params": {"lat":0,"log":0}}
  }}}}
}`

This my code for Reading Script from File
`elasticContext.Client.Search<Tenant>(s=>s
    .Query(q=>q
        .Bool(b=>b
            .Filter(f=>f
                .Script(sc=>sc
                    .Name("query")
                    .Params(p=>p
                        .Add("lat",lat)
                        .Add("log",log)
                    )
                    .File("TenantByLocation")
                )
            )
        )
    )
);

`
