### ISSUE TITLE
5.x CallDetails vs ApiCall

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2286]
There are a lot of missing xml docs and it's hard to tell what the difference is between these two.

**Comment by Mpdreamz** [comment]
Thanks for opening this @niemyjski one of those things I wanted to come back to and never did and might not have for 5.0 either.

Opened: https://github.com/elastic/elasticsearch-net/pull/2381

At this rate i am not sure how many :beer:'s I owe you at elasticon :smile:
