### ISSUE TITLE
IMultiGetHit<T>.Version is a long IHit<out T>.Version is a long?

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2287]
One is nullable and one isn't this is inconsistent. Is there any reason that both of these are not nullable?

**Comment by niemyjski** [comment]
This also affects `IGetResponse<T>`

**Comment by Mpdreamz** [comment]
Version is only returned on search when `version: true` is send in the request. 

Other api's always return the version

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-version.html

**Comment by niemyjski** [comment]
Yes, but some of them are nullable and some are not. It's very inconsistent. In 1.x they all were nullable.
