### ISSUE TITLE
CountDescriptor.Index should take IEnumerable overload

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2289]
Existing api let us do something like this:

``` cs
            var response = await _client.CountAsync<T>(c => c.Query(q => q.MatchAll()).Indices(GetIndexesByQuery(null)).Type(ElasticType.Name)).AnyContext();
```

and pass it an array of indexes. Now it expects a comma delimited list of indexes. There should be an implicit conversion or overload that takes an array / ienumerable of strings to make this easier to use...

``` cs
///<summary>A comma-separated list of indices to restrict the results</summary>
public CountDescriptor<T> Index(Indices index) => Assign(a=>a.RouteValues.Optional("index", index));
```

**Comment by Mpdreamz** [comment]
You can cast `string` to `IndexName` and `IndexName[]` to `Indices`

**Comment by niemyjski** [comment]
but you can't use it if you are using an IEnumerable<string> or string[]

**Comment by Mpdreamz** [comment]
You can but I agree the experience can be nicer so attached a PR, should be backported to 2.x as well.

**Comment by niemyjski** [comment]
Thanks!

**Comment by russcam** [comment]
Closing as this has been added to 2.x, 5.x and master.
