### ISSUE TITLE
5.x Add Overload for AliasExistsAsync and GetAlias that takes a string name

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2290]
This seems like it would be a very common thing and it would save me from doing: `AliasExistsAsync(a => a.Name(alias))`

**Comment by Mpdreamz** [comment]
The defaults for these reflect the most open form of the urls itself. Only in some destructive endpoints (ClearCache, Delete*) did we opt to make `Indices`/`Names` etc explicit by default. 

We won't add these back in.

**Comment by niemyjski** [comment]
Fair enough. but I'm betting that if you looked at most oss projects that are using this, a good portion of them are only passing in the name.
