### ISSUE TITLE
5.x Explicit Interfaces on QueryContainer don't always return the correct value

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2291]
We were using `QueryContainer.IsConditionless` and noticed it was made internal :\. However when I was looking I noticed what I think could be a bug:

https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Dsl.cs#L13-L25

If you look at the explicit interface implementations they all return something else or nothing? Shouldn't they be returning the internal value?

**Comment by Mpdreamz** [comment]
The `Self` [loops back to this](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Assignments.cs#L60)

If you want this properties you have to get them from `IQueryContainer`, this is because we need to hide these on the fluent API.

**Comment by niemyjski** [comment]
THat's fine but this isn't returning the self value:

1. https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Dsl.cs#L13
2. https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Dsl.cs#L16
3. https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/QueryDsl/Abstractions/Container/QueryContainer-Dsl.cs#L22

Isn't that a bug?
