### ISSUE TITLE
Please deprecate / remove IndexName

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2293]
```
    public override TypeMappingDescriptor<Identity> BuildMapping(TypeMappingDescriptor<Identity> map) {
            return map
                .Dynamic(false)
                .Properties(p => p
                    .Keyword(f => f.Name(e => e.Id).IndexName(Fields.Id))
                );
        }
```
Compiles perfectly fine but throws bad request when I try to create the mapping. I thought this was supposed to be removed / deprecated in 1.3 

https://github.com/elastic/elasticsearch/issues/6677

**Comment by gmarz** [comment]
Good catch.  We'll deprecate it in 2.x and remove in 5.x/master.

**Comment by niemyjski** [comment]
Thanks!
