### ISSUE TITLE
5.x Invalid bulk operation causes BulkAsync() to return null.

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2296]
Using 5.0.0-beta client, I found out this issue trying to track down an issue with https://github.com/elastic/elasticsearch/issues/20702

Anyways to reproduce you need to create a bulk index request with an invalid version:

```
var bulkRequest = new BulkRequest();
var list = objects.Select(o => {
    var doc = new BulkIndexOperation<T>(o) { Type = type };
    doc.Index = "test";
    doc.Version = 0; // Invalid
    return doc;
}).Cast<IBulkOperation>().ToList();
bulkRequest.Operations = list;

var response = await client.BulkAsync(bulkRequest);
```

![screen shot 2016-09-29 at 3 42 07 pm](https://cloud.githubusercontent.com/assets/1020579/18972272/19fffda8-865e-11e6-85f5-5791a673c19e.png)

The expected result should return the bulk items with the BulkItem.Error property populated :).

**Comment by niemyjski** [comment]
If I get time, I'll try and create a unit test.. I was unable to debug past the client's dispatch call via vs source debugging

**Comment by ejsmith** [comment]
I ran into this with the 1.x client today as well

**Comment by Mpdreamz** [comment]
It'd be useful to get the request and response. I've attached a test that mimics your setup the best i could replicate it and it appears we are doing the correct thing:

Bulk indexing a valid and invalid version
 
```json
{"index":{"_type":"project","_id":"Homenick and Sons"}}
...doc...
{"index":{"_type":"project","_id":"Homenick and Sons","_version":0}}
...doc...
```

The whole response is will be marked with a 400

```
HTTP/1.1 400 Bad Request
content-type: application/json; charset=UTF-8
content-length: 384

{
  "error" : {
    "root_cause" : [
      {
        "type" : "action_request_validation_exception",
        "reason" : "Validation Failed: 1: illegal version value [0] for version type [INTERNAL];"
      }
    ],
    "type" : "action_request_validation_exception",
    "reason" : "Validation Failed: 1: illegal version value [0] for version type [INTERNAL];"
  },
  "status" : 400
}
```

Which our tests show as well. `response.Items` would be null in that case. I do expect elasticsearch to only fail that individual item so i'm going to chase that one

**Comment by niemyjski** [comment]
I guess I can pull down the test and take a look, it's failing every time over here.

**Comment by niemyjski** [comment]
![screen shot 2016-09-30 at 11 00 16 am](https://cloud.githubusercontent.com/assets/1020579/18998179/1b23ec40-86fd-11e6-99b3-3d03248d03d5.png)

I can't even build the 5.x branch. But if you pull down: https://github.com/exceptionless/Foundatio.Repositories/tree/feature/elastic5 and you remove this version > 0 check: https://github.com/exceptionless/Foundatio.Repositories/blob/feature/elastic5/src/Foundatio.Repositories.Elasticsearch/Extensions/ElasticIndexExtensions.cs#L112

And then basically any of the tests  you will get a null reference exception

**Comment by gmarz** [comment]
@niemyjski can you paste the json request and response from ES here?

**Comment by niemyjski** [comment]
https://github.com/elastic/elasticsearch-net/commit/d2491a48372242b8a436539c6892240a75fbb83a

**Comment by niemyjski** [comment]
I added a comment there :) The test needs to be updated so both bulk items specify a version:

```cs
protected override object ExpectJson { get; } = new object[]
		{
			new Dictionary<string, object>{ { "index", new { _type="project", _id = Project.Instance.Name, _version = 0 } } },
			Project.InstanceAnonymous,
			new Dictionary<string, object>{ { "index", new { _type="project", _id = Project.Instance.Name, _version = 0 } } },
			Project.InstanceAnonymous,
		};
```

**Comment by niemyjski** [comment]
I didn't get a chance to capture the response yet.

**Comment by Mpdreamz** [comment]
^ changing that only changes the json we expect to sent. You also need to update the fluent and initializer examples in the same file.

That said changing those does not change the response nor make response `null` in our tests. (response.Items is but there is #2299 to discuss that :))

If you can capture and share the response you get that'd be helpful

**Comment by niemyjski** [comment]
Here is the post

```
POST http://127.0.0.1:9200/_bulk HTTP/1.1
Accept: application/json
Content-Type: application/json
Host: 127.0.0.1:9200
Content-Length: 653

{"index":{"_index":"employees","_type":"employee","_id":"57f26c98f8a1032c98efa604","_version":0}}
{"createdUtc":"2016-10-03T14:35:04.2337412Z","id":"57f26c98f8a1032c98efa604","companyId":"57f26c98f8a1032c98efa602","companyName":"Exceptionless","name":"Blake","age":29,"yearsEmployed":9,"updatedUtc":"2016-10-03T14:35:04.2337412Z","isDeleted":false}
{"index":{"_index":"employees","_type":"employee","_id":"57f26c98f8a1032c98efa605","_version":0}}
{"createdUtc":"2016-10-03T14:35:04.2337412Z","id":"57f26c98f8a1032c98efa605","companyId":"57f26c98f8a1032c98efa603","age":52,"yearsEmployed":0,"updatedUtc":"2016-10-03T14:35:04.2337412Z","isDeleted":false}
```

Here is the response:
```
HTTP/1.1 400 Bad Request
content-type: application/json; charset=UTF-8
content-length: 421

{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: illegal version value [0] for version type [INTERNAL];2: illegal version value [0] for version type [INTERNAL];"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: illegal version value [0] for version type [INTERNAL];2: illegal version value [0] for version type [INTERNAL];"},"status":400}
```

If you want to see it for yourself (happens every time) you can clone our repo, comment out this line: https://github.com/exceptionless/Foundatio.Repositories/blob/feature/elastic5/src/Foundatio.Repositories.Elasticsearch/Extensions/ElasticIndexExtensions.cs#L112

and run this test: https://github.com/exceptionless/Foundatio.Repositories/blob/feature/elastic5/tests/Foundatio.Repositories.Elasticsearch.Tests/VersionedTests.cs#L106

I really need to spend some time and create a test for your repo and debug it, just tons of things going on right now

**Comment by russcam** [comment]
@niemyjski just checking in on this. I think I mentioned it on the call a couple of weeks ago, but if you have the 1.x source already and want to get the 2.x or 5.x source, you should `git clean -xfd` after checking out a different branch, or clone the repo for 2.x or 5.x branches. Then, building 2.x or 5.x should just be a case of calling `build.bat` in the root.

**Comment by niemyjski** [comment]
I'll try and get some time to create a test for this (so much going on).
