### ISSUE TITLE
5.0.0-beta:  Delete Response (404) result is incorrect

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2306]
I have a test where I'm deleting the a document that doesn't exist and checking the behaviors and I noticed that the result in the response is `not_found` but the returned model Result value is `Created`
<img width="1574" alt="screen shot 2016-10-03 at 2 49 55 pm" src="https://cloud.githubusercontent.com/assets/1020579/19051493/dbcf5740-8978-11e6-9022-08d06359f2ba.png">

**Comment by niemyjski** [comment]
Also looks like the Index, Version and type isn't populated

**Comment by russcam** [comment]
404 responses on Get and Delete requests are now accepted responses i.e. `.IsValid` is `true` and the json response will be deserialized such that `Index`, `Type`, `Id`, etc. will be populated.

This will make it into 5.0.0 and the next 2.x release. Thanks for reporting @niemyjski 👍
