### ISSUE TITLE
Ability to specify a string range query

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2307]
We use sequential ids and I am needing to do a range query on it (I don't care about perf, this is for resuming reindexing). The api allows to do a range query on this but it's not possible with nest (only allow for date or numeric ranges). 

```
GET /employees-v1/_search
{
 "query": {
   "range": {
     "id": {
       "gte": "57f688a3f8a103072c1f1000"
     }
   }
 },
 "sort": [
   {
     "id": {
       "order": "asc"
     }
   }
 ]
}
```

This should affect all nest versions.

https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-id-field.html
http://elasticsearch-users.115913.n3.nabble.com/Range-for-id-td4025670.html

**Comment by niemyjski** [comment]
Right now I worked around this by using a querystring filter 🗡 

```
GET /employees-v1/_search
{
  "query": {
    "query_string": {
      "query": ">=57f690a2f8a10310d060c073",
      "default_field": "id"
    }
  },
  "sort": [
    {
      "id": {
        "order": "asc"
      }
    }
  ]
}
```

**Comment by russcam** [comment]
I think you're looking for `.TermRange()` in NEST 2.x+

```c#
var searchResponse = client.Search<Employee>(s => s
	.Index("employees-v1")
	.Query(q => q
		.TermRange(tr => tr
			.Field(f => f.Id)
			.GreaterThanOrEquals("57f688a3f8a103072c1f1000")
		)
	)
	.Sort(so => so
		.Ascending(f => f.Id)
	)
);
```

Numeric, Date and Term ranges can all be specified against `.Range()` in NEST 1.x

```c#
var searchResponse = client.Search<Employee>(s => s
    .Index("employees-v1")
    .Query(q => q
        .Range(tr => tr
            .OnField(f => f.Id)
            .GreaterOrEquals("57f688a3f8a103072c1f1000")
        )
    )
    .SortAscending(f => f.Id)
);
```

**Comment by niemyjski** [comment]
Thanks! I'm curious is there any reason we couldn't have overloads on Range again that would return the proper interface based on the overload?

**Comment by russcam** [comment]
Properties such as `.TimeZone` and `.Format` are only valid for date ranges so it makes sense to split a range query on dates out separately. In doing this, it also makes sense to split out range queries on numeric fields and string fields too. 

In 1.x, values for each of the comparison operators were always sent as `string` but are now sent as the _more_ correct type in each case (`string` or `number`), which is much easier to do now they are now separate queries.
