### ISSUE TITLE
Error deserializing "took" value on TermVector request.

### ISSUE THREAD

**Issue by maeserichar** [elastic/elasticsearch-net#2308]
**NEST/Elasticsearch.Net version**: 2.4.6

**Elasticsearch version**: 2.3.3

**Description of the problem including expected versus actual behavior**: 
When asking for the TermVector, if the took field in the response is bigger than max value for an int, it gives a serialization exception.

I have noticed that depending of the response type, some has the Took field as a long and some others (like the received with the term vector request) as an integer. I would be glad to submit a PR unifying this types to long, but first I wanted to assure that this is not on purpose.

**Comment by gmarz** [comment]
Closed via https://github.com/elastic/elasticsearch-net/pull/2324 and we have https://github.com/elastic/elasticsearch-net/pull/2325 as a potential fix for the next 2.x release.
