### ISSUE TITLE
Is there documentation for navigating a terms aggregation within another terms aggregation

### ISSUE THREAD

**Issue by JRRan64** [elastic/elasticsearch-net#2315]
**NEST/Elasticsearch.Net version**:  2.0 

**Elasticsearch version**: 2.3.4

**Description of the problem including expected versus actual behavior**:
Cannot navigate 2+deep aggregations and zero documentation found re how to do this.
Queries are working in Sense and in Nest but cannot translate the Visual Studio watch variable navigation to accessible items in code.

**Steps to reproduce**:
 1.  Terms Aggregation within another Terms Aggregation (10 x 10)
 2.  Open to suggestions / other methods of creating pivot tables from Aggregations
 3.

**Provide `ConnectionSettings` (if relevant)**:  not relevant

**Provide `DebugInformation` (if relevant)**: not relevant

**Describe the feature**:

**Comment by russcam** [comment]
[Did you see the documentation on Aggregations?](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/writing-aggregations.html)

Here's an example of a sub aggregation, a [Stats Aggregation](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/stats-aggregation-usage.html), inside of a [Terms Aggregation](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/terms-aggregation-usage.html) and a LINQ expression for projecting the results. The principle is the same for N levels of sub aggregations

```c#
var client = new ElasticClient();

var response = client.Search<Question>(s => s
  	.Size(0)
  	.Aggregations(a => a
		.Terms("top_tags", m => m
	  		.Field(f => f.Tags)
	  		.Size(5)
	  		.ShardSize(20)
			.Aggregations(sa => sa
				.Stats("score_stats", st => st
					.Field(f => f.Score)
				)
			)
		)
  	)
);

var results = 
	from term in response.Aggs.Terms("top_tags").Buckets
	let stats = term.Stats("score_stats")
	select new
	{
		Tag = term.Key,
		Count = stats.Count,
		Min = stats.Min,
		Max = stats.Max,
		Average = stats.Average,
		Sum = stats.Sum
	};
```

**Comment by JRRan64** [comment]
Any chance you can show this in a non LINQ expression way.  DB guy loving Elasticsearch.

**Comment by JRRan64** [comment]
Also, even in LINQ, how do I access the different items in my sub aggregation.  It is a top 10 x top 10 query.  I manage to get the top 10 but still cant get to the items below it.

**Comment by russcam** [comment]
Here's how you access each bucket in a terms aggregation and how you access the sub terms aggegration in each bucket

```c#
var client = new ElasticClient();

var response = client.Search<Question>(s => s
  	.Size(0)
  	.Aggregations(a => a
		.Terms("top_tags", m => m
	  		.Field(f => f.Tags)
	  		.Size(10)
			.Aggregations(sa => sa
				.Terms("top_tags_per_top_tag", st => st
					.Field(f => f.Tags)
                    .Size(10)
				)
			)
		)
  	)
);

foreach (var topTermBucket in response.Aggs.Terms("top_tags").Buckets)
{
    Console.WriteLine(
        $"Key: {topTermBucket.Key}," +
        $"Doc Count: {topTermBucket.DocCount}");
        
    foreach (var subTermBucket in topTermBucket.Terms("top_tags_per_top_tag").Buckets)
    {
        Console.WriteLine(
            $"Top Key: {topTermBucket.Key}," + 
            $"Sub Key: {subTermBucket.Key}," + 
            $"Doc Count: {subTermBucket.DocCount}");
    }
}
```

**Comment by JRRan64** [comment]
Awesome! Worked first time.  Thank you so much.
