### ISSUE TITLE
UnregisterPercolator does not work

### ISSUE THREAD

**Issue by lonevvolf** [elastic/elasticsearch-net#2318]
NEST: 1.7.1
ElasticSearch.Net: 1.7.1

ElasticSearch 2.1.0

When making the the following type of call to unregister a percolator:
`elastic.UnregisterPercolator<MyIndexType>(GetPercolatorId(fieldUpdate.FieldId));`

a DELETE request is sent to the server at:
`http://<servername>:<port>/_all/.percolator/<percolatorId>`
which results in a code 400 and failure.  Rather, a DELETE request must be sent to:
`http://<servername>:<port>/<indexName>/.percolator/<percolatorId>`

as specified in the docs at:
[Indexing Percolator Queries](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/search-percolate.html#_indexing_percolator_queries)

**Comment by russcam** [comment]
@lonevvolf I see you're using NEST 1.7.1 with Elasticsearch 2.1.0; [1.x is not compatible (or supported) with Elasticsearch 2.x. ](https://github.com/elastic/elasticsearch-net#compatibility-matrix).

[In the 2.x client, the index name will inferred from `T`](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Nest/Search/Percolator/UnregisterPercolator/UnregisterPercolatorRequest.cs#L18).

**Comment by gmarz** [comment]
Closing this.  Feel free to re-open @lonevvolf if there's still an issue after aligning versions.
