### ISSUE TITLE
Infer the mapping for strings as text types only in 5.x

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#2329]
in 5.x+, [we're inferring the mapping of a string property as a `text` type with a `keyword` sub-fields mapping](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Mapping/Visitor/PropertyWalker.cs#L89-L96). This feels
-  very overbearing as the default 
- may not play too nicely with large input strings to map them as `keyword`
- goes beyond what we do in 1.x and 2.x

Is there a reason that this is done? I feel like the default should be to map as a `text` type only, to align with similar behaviour in 1.x and 2.x.

**Comment by gmarz** [comment]
The reason for this was to align with the ES defaults [as explained here](https://www.elastic.co/guide/en/elasticsearch/reference/5.x/breaking_50_mapping_changes.html#_default_string_mappings).  For instance,

```
PUT /foo/foo/1
{
    "foo","foo"
}
```

will result in

```
GET /foo/_mapping
{
  "foo" : {
    "mappings" : {
      "foo" : {
        "properties" : {
          "foo" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by russcam** [comment]
Thanks @gmarz, I thought I might be missing something 😄 I'll open a PR to add `ignore_above` to the `keyword` mapping as well 👍
