### ISSUE TITLE
Index and Type inference

### ISSUE THREAD

**Issue by sterchelen** [elastic/elasticsearch-net#2330]
Hi,

Like the elasticsearch documentation says, don't repeat yourself ! 
Actually, you can't remove the inference of the index name and the type name for bulk operations even if you pass the index and the type name into FixedPath.

Am I wrong ? If no, it will be a good enhancement.

Have a nice day.

**Comment by gmarz** [comment]
Hi @sterchelen can you elaborate a bit more on what you mean?

**Comment by gmarz** [comment]
This is already possibly by setting `Index` and/or `Type` on `IBulkRequest`:

For instance

```csharp
client.Bulk(b => {
    b.Index("foo");
    b.Type("bar");
    foreach (var doc in docs)
        b.Index<Foo>(i => i.Document(doc));
    return b;
});
```

Let me know if that helps.  Closing this for now as it's not an issue, but feel free to follow up here with any questions.

**Comment by sterchelen** [comment]
Well, I'm facing this problem on two apis (still using the v1 of NEST):

MultiGet and Bulk :

--> MultiGet:
Code:
`var response = _client.MultiGet( m => m.FixedPath( indexName, "customerClip" ).GetMany<CustomerClip>( customerClipIds, ( a, b ) => a.Index( indexName ) ).SourceInclude( "clipSelections" ) );
`
Data send (thanks Fiddler):
Raw url ==> .clips-201609/customerClip/_mget?_source_include=clipSelections

Raw data:
```
{
  "docs": [
    {
      "_index": ".clips-201609",
      "_type": "customerClip",
      "_id": "FR268070_326113083"
    },
    {
      "_index": ".clips-201609",
      "_type": "customerClip",
      "_id": "FR89605_325643921"
    }
  ]
}

```

As you can see, even if I set the indexName and the type on the MultiGet api, NEST set the _index and _type variables... Whereas in the elastic documentation on the mget api we can read this :

> 
> The mget endpoint can also be used against an index (in which case it is not required in the body):
> ```
> 
> curl 'localhost:9200/test/_mget' -d '{
>     "docs" : [
>         {
>             "_type" : "type",
>             "_id" : "1"
>         },
>         {
>             "_type" : "type",
>             "_id" : "2"
>         }
>     ]
> }'
> ```
> 
> And type:
> ```
> 
> curl 'localhost:9200/test/type/_mget' -d '{
>     "docs" : [
>         {
>             "_id" : "1"
>         },
>         {
>             "_id" : "2"
>         }
>     ]
> }'
> ```
> 
> In which case, the ids element can directly be used to simplify the request:
> ```
> 
> curl 'localhost:9200/test/type/_mget' -d '{
>     "ids" : ["1", "2"]
> }'
> ```

[Link to the doc](https://www.elastic.co/guide/en/elasticsearch/reference/0.90/docs-multi-get.html)
My goal is to have an output like the last request, just by setting the index and the type.





--> Bulk:
Code:
```
var bulkRequest = new BulkRequest()
			{
				Index = indexName,
				Type = "customerClip",

				Operations = new List<IBulkOperation>()
			};
			bulkRequest.Operations = new List<IBulkOperation>();

			foreach( var item in objs )
			{
				var bulkUpdateOperation = new BulkUpdateOperation<CustomerClip, object>( item._id );
				bulkUpdateOperation.Doc = item;
				bulkUpdateOperation.RetriesOnConflict = 5;
				bulkRequest.Operations.Add( bulkUpdateOperation );
			}

			var response = _client.BulkAsync( bulkRequest );
```

Data send:
Raw url ==> .clips-201609/customerClip/_bulk

Raw data: 
```

{ "update" :  {"_type":"customerClip","_id":"FR268070_326113083","_retry_on_conflict":5} }
{"doc":{"clipSelections":[{"id":"140741","name":"- AAAA"},{"id":"3041","name":"- ECOLOGIE"}],"_id":"FR268070_326113083"}}
{ "update" :  {"_type":"customerClip","_id":"FR89605_325643921","_retry_on_conflict":5} }
{"doc":{"clipSelections":[{"id":"140741","name":"- AAAA"},{"id":"3041","name":"- ECOLOGIE"},{"id":"3043","name":"- MER"},{"id":"3042","name":"- TRANSPORTS"},{"id":"2996","name":"Energie"}],"_id":"FR89605_325643921"}}
```

For the bulk operation, just the _type field remains. I suspect the type inference on this "problem". I hope my explanation is clear. 

Thank you for your time.
