### ISSUE TITLE
Add Script and DotExpander Pipeline Processors

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2334]
- `GeoIp` isn't specified in the elastic docs, if these are plugins, they should mention it in the xml docs
- `Attachment` isn't specified in the elastic docs, if these are plugins, they should mention it in the xml docs

Support for `Script` and `Dot Expander` processors are missing.

**Comment by russcam** [comment]
Merged into `5.x` and `master` from https://github.com/elastic/elasticsearch-net/pull/2361

**Comment by niemyjski** [comment]
Thanks @russcam!
