### ISSUE TITLE
Suggest<T> doesn't infer index name from T (#1310 regression)

### ISSUE THREAD

**Issue by seanwm** [elastic/elasticsearch-net#2335]
Is it possible that #1310 is back in 2.4.x? I've got a query that looks like this:

```
ISuggestResponse response = esClient.Suggest<SuggestionDictionaryEntry>(x => x
   .Completion("suggestions", c => c
      < snip >
   .Size(10)));
```

Type/index mappings are added when creating the client settings, like this:

```
private static ConnectionSettings settings = new ConnectionSettings(connectionPool)
        .MapDefaultTypeIndices(d => d.Add(typeof(SuggestionDictionaryEntry), "myIndexName"));
```

And, just as with this issue, these suggestion queries are being sent to _all. Adding the explicit index declaration (as described in the original issue report) fixes that behavior.

**NEST/Elasticsearch.Net version**:
2.4.6 (also seen in 2.4.1)

**Elasticsearch version**:
2.4.1

**Comment by russcam** [comment]
@seanwm The linked issue relates to NEST 1.x and the PR brought in the behaviour to infer the index from `T`.

In NEST 2.x+, the generic type parameter `T` is not used to infer the index name but I think it should; this would make the behaviour consistent with 1.x and also `Search<T>(s => s)`.

I think introducing a `SuggestRequest<T>` type would also make sense where the parameterless constructor defaults to inferring the index from `T`.

**Comment by russcam** [comment]
In 2.x, The index will now be inferred from `T` on the fluent API `Suggest<T>()` method. A new type, `SuggestRequest<T>` has been introduced to allow index inference from `T` on the `.Suggest(ISuggestRequest)` method. This will be in the next release of NEST 2.x.

In 5.x,  The index will now be inferred from `T` on `Suggest<T>()` method (`.Suggest()` method was removed, so  `SuggestRequest<T>` would be passed to `.Suggest<T>(ISuggestRequest)`).

Thanks for reporting @seanwm 👍
