### ISSUE TITLE
The key of an aggregation bucket is always read as a string

### ISSUE THREAD

**Issue by JulianRooze** [elastic/elasticsearch-net#2336]
We're currently running into a situation where we need to have the key of a `terms` aggregation (which is a double in Elasticsearch) available as a double in our code, but the value of `Key` in a `KeyedBucket` is always a string, so we now have to parse many doubles from strings to accomplish this. But when I look at the response from Elasticsearch, the key does come back as a number there, it's the following code in Nest that always reads the key as a string:

https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Aggregations/AggregateJsonConverter.cs#L538

``` csharp
var key = reader.ReadAsString();
reader.Read();
var property = reader.Value as string;
if (property == "from" || property == "to")
    return GetRangeBucket(reader, serializer, key);

var keyItem = new KeyedBucket {Key = key};
```

My proposal would be to add a `KeyAsObject` property to `KeyedBucket` that simply gets the `reader.Value` assigned to it. And to avoid an unnecessary string allocation, the `Key` property should delegate to `KeyAsObject` and only create a string when you use the `Key` property.

``` csharp
private string _key = null;

public string Key 
{
    get
    {
        if(_key == null && KeyAsObject != null)
        {
            _key = KeyAsObject.ToString();
        }
    }
    set
    {
        _key = value;
    }
}
```

Please let me know your thoughts on this!

**Comment by Mpdreamz** [comment]
This sounds very reasonable to me although we should not call ToString() on `KeyAsObject`. 

@gmarz thoughts?

**Comment by JulianRooze** [comment]
@Mpdreamz thanks for looking into this! What is the objection to calling `ToString` on `KeyAsObject` here? That it may be null? Or that `KeyAsObject.ToString()` results in a different string than `reader.ReadAsString()`? That might be the case, considering the `ToString()` would use the .NET logic of converting an int or double or whatever to a string whereas `ReadAsString` returns the JSON token value as a string. So if the token contains the value "10.0" and .NET decides to serialize the double `10` to the string value "10" instead of "10.0" then that could be a breaking change to whomever relies on that exact value. 

However, I'm not sure how else to do it, because as far as I know, `ReadAsString` and `Read` both *consume* the token so you can't do both. You can't both have `Key` and `KeyAsObject`. So that would require making this a setting in NEST that would do one or the other I guess. Would that be an option?

**Comment by gmarz** [comment]
@JulianRooze you can do this:
```c#
response.Aggs.Terms<int>("my_terms");
```

which will return the keys as `int`s.

There are also no extra casts going on here, as it's read as an `object` now instead of `string` by the deserializer.
