### ISSUE TITLE
Elasticsearch.Net.Audit shows negative time taken

### ISSUE THREAD

**Issue by fedotovalex** [elastic/elasticsearch-net#2340]
Minor issue: the [ToString()](https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Auditing/Audit.cs#L22) method in Elasticsearch.Net.Audit shows negative time taken. You want to swap it to read `var took = Ended - Started;`

**Comment by gmarz** [comment]
Nice catch @fedotovalex and thanks for reporting 👍
