### ISSUE TITLE
5.0: UpdateRequest contains Lang and Language

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2342]
![screen shot 2016-10-25 at 4 54 50 pm](https://cloud.githubusercontent.com/assets/1020579/19705788/18d7d074-9ad4-11e6-9a80-368e2ae3298b.png)
![screen shot 2016-10-25 at 4 54 27 pm](https://cloud.githubusercontent.com/assets/1020579/19705789/18e9f330-9ad4-11e6-8715-922ff4c767ed.png)

The comment also says groovy, which I believe the new default is `painless`. Should one of these be removed? I only found this after I got the following error: `53:09.14195 E:StackRepository - Error occurred incrementing total event occurrences on stack "1ecd0826e447a44e78877ab1". Error: Type: illegal_argument_exception Reason: "request [/test-stacks/stacks/1ecd0826e447a44e78877ab1/_update] contains unrecognized parameter: [lang]"`

**Comment by niemyjski** [comment]
Regardless, it is very confusing to have both :D, which is why I logged this.

**Comment by gmarz** [comment]
Good catch, `Lang` comes from the REST spec and is set as a query string parameter, while `Language` was used previously to set on the body.  We'll standardize on `Lang`.
