### ISSUE TITLE
Mark removed properties from #2337 as obsolete

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch-net#2346]
The following properties were removed as part of #2337 that we should mark obsolete in `2.x`:

**ObjectProperty**
- `Path`

**DateProperty**
- `PrecisionStep`
- `NumericResolution`

**KeywordProperty**
- `SearchAnalyzer`

**NumberProperty**
- `PrecisionStep`

**GeoPointProperty**
- `LatLon`
- `GeoHash`
- `GeoHashPrecision`
- `GeoHashPrefix`
- `Validate`
- `ValidateLatitude`
- `ValidateLongitude`
- `Normalize`
- `NormalizeLatitude`
- `NormalizeLongitude`
- `PrecisionStep`
- `Fielddata`

**IpProperty**
- `PrecisionStep`

**TokenCountProperty**
- No longer derives from NumberProperty

**Comment by russcam** [comment]
Closed per #2360
