### ISSUE TITLE
Field Data is disabled on text fields by default but annotation is present 

### ISSUE THREAD

**Issue by lonewolfass** [elastic/elasticsearch-net#2352]
Hi, i have annotation on field present like so 
[Nest.Text(Store = true, IndexOptions = IndexOptions.Positions, Fielddata = true)]
but i am getting always an error on mapping "Fielddata is disabled on text fields by default. Set fielddata=true" when trying to do aggregation
Yes i know i will have performance problems but i realy want to get this working. 
Is Fielddata = true ignored in nest ?

**Comment by russcam** [comment]
@lonewolfass What version of NEST are you using? And what version of Elasticsearch are you targeting?

**Comment by lonewolfass** [comment]
NEST 5.0.0-rc-1 Elastic 5.0, From 5.0 Fielddata is disabled is disabled by default , so we need to enable it by setting a parameter , unfortunetly annotation doesnt work. Is there another way to do this ? Test by using another mechanism ?

**Comment by Mpdreamz** [comment]
It should not be ignored as per this test: https://github.com/elastic/elasticsearch-net/blob/master/src/Tests/Mapping/Types/Core/Text/TextAttributeTests.cs#L42

Are you trying to update the mapping of an existing index? You have to create a new index with the correct index settings.

**Comment by lonewolfass** [comment]
I am creating an index. I have found something else : 
I have tried manually change fieldata property according to this https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html
and for type text i have a fallowing error : 
"type":"mapper_parsing_exception","reason":"Mapping definition for ["field"] has unsupported parameters:  [fieldata : true]"}], so maybe it is not supported by elastic itself ?

**Comment by lonewolfass** [comment]
I had a typo on fielddata , manulally changing an fielddata to true by fallowing https://www.elastic.co/guide/en/elasticsearch/reference/current/fielddata.html works , so only annotation isn't working

**Comment by russcam** [comment]
@lonewolfass Could you post a small example that reproduces this? Something that can be run in Linqpad   for example would be awesome.

Here's a Linqpad example to demonstrate it working using NEST-5.0.0-rc1 against Elasticsearch 5.0

```c#
void Main()
{
    var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
    var defaultIndex = "default-index";
    var connectionSettings = new ConnectionSettings(pool)
            .DefaultIndex(defaultIndex)
            .PrettyJson()
            .DisableDirectStreaming()
            .OnRequestCompleted(response =>
                {
                    // log out the request
                    if (response.RequestBodyInBytes != null)
                    {
                        Console.WriteLine(
                            $"{response.HttpMethod} {response.Uri} \n" +
                            $"{Encoding.UTF8.GetString(response.RequestBodyInBytes)}");
                    }
                    else
                    {
                        Console.WriteLine($"{response.HttpMethod} {response.Uri}");
                    }

                    Console.WriteLine();

                    // log out the response
                    if (response.ResponseBodyInBytes != null)
                    {
                        Console.WriteLine($"Status: {response.HttpStatusCode}\n" +
                                 $"{Encoding.UTF8.GetString(response.ResponseBodyInBytes)}\n" +
                                 $"{new string('-', 30)}\n");
                    }
                    else
                    {
                        Console.WriteLine($"Status: {response.HttpStatusCode}\n" +
                                 $"{new string('-', 30)}\n");
                    }
                });


    var client = new ElasticClient(connectionSettings);
    
    client.CreateIndex("examples", c => c
        .Mappings(m => m
            .Map<Document>(mm => mm
                .AutoMap()
            )
        )
    );
    
    client.GetMapping<Document>(m => m.Index("examples"));
}

public class Document
{
    [Nest.Text(Store = true, IndexOptions = IndexOptions.Positions, Fielddata = true)]
    public string Field { get; set; }
}
```

which produces the output

```json
PUT http://localhost:9200/examples?pretty=true 
{
  "mappings": {
    "document": {
      "properties": {
        "field": {
          "type": "text",
          "store": true,
          "fielddata": true,
          "index_options": "positions"
        }
      }
    }
  }
}

Status: 200
{
  "acknowledged" : true,
  "shards_acknowledged" : true
}

------------------------------

GET http://localhost:9200/examples/_mapping/document?pretty=true

Status: 200
{
  "examples" : {
    "mappings" : {
      "document" : {
        "properties" : {
          "field" : {
            "type" : "text",
            "store" : true,
            "fielddata" : true
          }
        }
      }
    }
  }
}

------------------------------
```

**Comment by lonewolfass** [comment]
Yes , this sample really works, so there must be a problem between computer and the seat ;) Sorry for wasting your time, if that works there is nothing to fix.
