### ISSUE TITLE
Sort by cardinality of a field with a script file using NEST 1.7.2

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch-net#2354]
NEST 1.7.2
ES 1.7.2

I have a scenario in which I need to sort documents by the cardinality of a field (not the values within that field).  From what I've read, it looks like the way to do this is via a script where I can specify `doc['my_field'].values.size()` as the sort value.  Since we have including script in a request disabled, we need to specify the script as a file (which we do already in several other cases).
However, with NEST 1.7.2 I cannot see a way to specify the script file (any script actually) to use when building my query using the `SortFieldDescriptor`.  Is there a way to work around this?  We use the fluent syntax.
In addition to sorting on the cardinality, I'd also like to sub-sort on the values of a second field.

**Comment by russcam** [comment]
@tdoman Using scripts to sort sounds like the way to do this. Take a look at `.SortScript()` on `SearchDescriptor<T>`. Here's an example

```c#
var response = client.Search<Document>(x => x
	.Query(q => q
		.MatchAll()
	)
    .SortScript(ss => ss
        .File("filename.groovy")
        .Descending()
    )
);
```
You can specify multiple sort conditions too (the order of conditions matters), by calling `Sort*` methods multiple times

```c#
var response = client.Search<Document>(x => x
	.Query(q => q
		.MatchAll()
	)   
    .SortScript(ss => ss
        .File("filename.groovy")
        .Descending()
    )
    .SortDescending("_score")
);
```

Note that the API for this in 2.x aligns better to the Elasticsearch API, nesting multiple sort conditions under the top level `.Sort()` and not calling multiple `Sort*` methods (calling the same method multiple times in NEST is a bit of an oddity, as usually the last call overrides any previous). 

The last example for 2.x would be

```c#
client.Search<Document>(s => s
    .Query(q => q
        .MatchAll()
    )
    .Sort(so => so         
        .Script(sc => sc
            .Script(sd => sd
                .File("filename.groovy")
            )
            .Descending()
        )
        .Descending("_score")
    )
);
```

**Comment by tdoman** [comment]
@russcam Thank you very much!  As always, you guys gave me a nice prompt response.  I'm looking forward to getting the chance to move to 2.x but I should have remembered my experience w/ TermsLookup to have discovered SortScript.  Anyway, again, thank you that's exactly what I needed.  FWIW, here's how I did it (Type is required):
`var response = client.Search<Document>(x => x.Query(q => q.MatchAll()).SortScript(ss => ss.Script("filename").Language("groovy").Type("number").Descending()).Sort(s => s.OnField("name.raw").Ascending())`

**Comment by russcam** [comment]
Awesome @tdoman, glad you got it working 😄
