### ISSUE TITLE
Should mark the String property as deprecated in 5.0.0 in NEST 2.x?

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#2359]
String property is replaced by Text property (for analyzed strings) and Keyword property (for not_analyzed strings).

Should we mark the String property and associated mappings and attributes with

```c#
[Obsolete("Deprecated in 5.0.0. Use Text properties for analyzed strings and Keyword property for not analyzed strings")]
```

We mark other types that are deprecated in 5.0 with `ObsoleteAttribute`, my initial thought is that we ought to do the same here. However, considering string usage is pretty ubiquitous, I am concerned about the gravity of such as change for users that may compile with warnings as errors or need to suppress warnings with pragma directives in their mappings.

Thoughts @elastic/microsoft?

**Comment by Mpdreamz** [comment]
I vote holding off until Elasticsearch 6.0 gets into view and we know for sure if `string` will be removed or not.
