### ISSUE TITLE
5.0-rc Bring back CreateIndexDescriptor.AddMapping

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2363]
Previously we had (return idx.AddMapping<T>(BuildMapping)) and we had a index type class that built up the mappings and added to the index descriptor. In 5.x this is no longer possible and it made it infinitely harder to generically build up mappings.

```cs
public virtual CreateIndexDescriptor Configure(CreateIndexDescriptor idx) {
  return idx.AddMapping<T>(BuildMapping);	
}

public virtual PutMappingDescriptor<T> BuildMapping(PutMappingDescriptor<T> map) {
   return map.Type(Name).Properties(p => p.SetupDefaults());
}
```

Now, it's a pita to have a configure index method and apply mappings. As I now have to have a dedicated method to building these up and apply the mappings in a single spot, but there are a lot of what-ifs that make this approach fall apart quickly

**Comment by gmarz** [comment]
Are you looking for `idx.Mappings(m => m.Map<T>)` perhaps?

Also see https://github.com/elastic/elasticsearch-net/issues/2196

**Comment by niemyjski** [comment]
Yes that's what I have now but I can add more than one mapping... calling that twice will cause it to only contain the last added mapping!

**Comment by gmarz** [comment]
call `.Map<T>()` twice, not `Mappings()`?

**Comment by gmarz** [comment]
For instance

```csharp
.Mappings(ms => ms
    .Map<Foo>(...)
    .Map<Bar>(...)
)
```

**Comment by niemyjski** [comment]
Yeah, I'm looking at refactoring it but it's a lot less useful than it was before.... I'd just like to add to the existing mappings!

**Comment by niemyjski** [comment]
Now I have to have all my index types be somewhat aware of each other instead of having each one isolated. This is a pita

**Comment by gmarz** [comment]
I'm missing how it's any different? `Map()` is the same thing as the old `AddMapping()`...it's just down a level to align more with the Elasticsearch JSON API:

```
.Settings(...)
.Mappings(...)
```

```
{
    "settings" : {},
    "mappings": {}
}
```

**Comment by niemyjski** [comment]
Previously I had createindexdescriptor.AddMapping<T> which would add to the mappings collection. Now I just have Mappings() and it's a one time call, calling it twice will override the previously added mapping

**Comment by gmarz** [comment]
As I explained above, you shouldn't call `Mappings()` twice.  Whatever code you had before needs to now build up a `MappingsDescriptor` or `IMappings` instead, and return it to `Mappings()`.

Sorry, I know it was a breaking change, but it was made to improve our APIs and make them more consistent, and it's been this way since 2.x.  I'm happy to take this offline via slack or something and help you change your code, but I'm going to close this as I don't see us changing it.
