### ISSUE TITLE
Executing scripts

### ISSUE THREAD

**Issue by justusth** [elastic/elasticsearch-net#2382]
**NEST/Elasticsearch.Net version**:
5.0-rc

**Elasticsearch version**:
5.0.0

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.             upsert2.ScriptFile("incrementNumber").Params(objects => objects.Add("newItem", new TestAnotherNested() {Count = 2, DateSale = updatetime, Id = updatetime.ToShortDateString()})).Upsert(new IndexedTestIdData() { TestId = 1002 }).Doc(new IndexedTestIdData() { TestId = 1002 });
            bulk.Operations.Add(upsert2);
            var response = ElasticHandler.Instance.TestIndex().client.Bulk(bulk);
            response.IsValid.Should().BeTrue();

Server compiles
[2016-11-09T15:48:12,107][INFO ][o.e.s.ScriptService      ] [kraftwerk] compiling script file [C:\Dev\elasticsearch-5.0.0\config\scripts\incrementNumber.groovy]

Having problems, when running queries or update data with script I dont get any error, Valid request from elastic server but! nothing happens. I cant even add a 1 to a field after update from 2.4.1 to 5.0.0. That I didnt get any errors fooled me.

So basicly when trying to run scripts stored at server, nothing happens and valid response without errors returns.

**Comment by justusth** [comment]
Could be related, will look some more.
https://github.com/elastic/elasticsearch-net/commit/02083c5b358920b81d5bdffa581738f4266ad5bf

**Comment by justusth** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_scripting.html
Probably related.
I will test some more tomorrow. I had the same problem running an painless script.

**Comment by russcam** [comment]
@justusth This sounds like the issue fixed in #2374. Looking to put another release of 5.x out very soon (hoping this week), but in the meantime, you can [grab the CI nuget package with that change in.](https://myget.org/feed/elasticsearch-net-next/package/nuget/NEST)

**Comment by justusth** [comment]
Oh that be lovely news! I will try it out in the morning.

**Comment by justusth** [comment]
Works like a charm. Ty for the help.

**Comment by russcam** [comment]
Awesome, glad it's fixed :+1:
