### ISSUE TITLE
Unable to create a new type inherited from GeoShapeQueryBase

### ISSUE THREAD

**Issue by JianpingLiu0225** [elastic/elasticsearch-net#2386]
**NEST/Elasticsearch.Net version**: 2.4.6

**Describe the feature**:

I am trying to write a Query class for GeometryCollection which is not included in NEST 2.4.6. But I've got some wierd issue. 

    'GeoShapeGeometryCollectionQuery.InternalWrapInContainer(IQueryContainer)': no suitable method found to override
    'GeoShapeGeometryCollectionQuery' does not implement inherited abstract member 'QueryBase.InternalWrapInContainer(IQueryContainer)'

So it asks me to override *InternalWrapInContainer* and at the same time it tells me it cannot find suitable method to override.

    public class GeoShapeGeometryCollectionQuery : GeoShapeQueryBase, IGeoShapeGeometryCollectionQuery, IGeoShapeQuery, IFieldNameQuery, IQuery
    {
        public GeoShapeGeometryCollectionQuery() { }

        public IGeometryCollectionGeoShape Shape { get; set; }
        protected override bool Conditionless { get; }

        internal override void InternalWrapInContainer(IQueryContainer container)
        {
            throw new NotImplementedException();
        }
    }

Anyone has idea of why this happens? I have spent a lot of time searching on web but have no luck finding any solution.

Thanks in advance.

**Comment by gmarz** [comment]
Are you adding this from an assembly other than NEST?  It's an internal method, and so it won't be accessible from outside assemblies.

It needs to be added within the NEST code base itself.  That said, it's definitely missing so I opened https://github.com/elastic/elasticsearch-net/issues/2387.  We'll add this for the next release...or feel free to tackle it yourself -- a PR would be much appreciated :).
