### ISSUE TITLE
Add UpdateMany for BulkOperation

### ISSUE THREAD

**Issue by dimmasik** [elastic/elasticsearch-net#2389]
**NEST/Elasticsearch.Net version**: 5.0

**Elasticsearch version**: 5.0

**Describe the feature**: Add UpdateMany to NEST like IndexMany, CreateMany and DeleteMany

**Comment by russcam** [comment]
@dimmasik fancy submitting a PR for this?

**Comment by dimmasik** [comment]
yes, i can

**Comment by russcam** [comment]
Awesome @dimmasik! Take a look at the [contributing guide](https://github.com/elastic/elasticsearch-net/blob/master/contributing.md). Let me know if you need any guidance in getting the solution up and running or have any problems with it. For Elasticsearch 5.0, if you make the PR against the 5.x branch, I can pull it into the others
