### ISSUE TITLE
5.x Nest - uax_url_email description

### ISSUE THREAD

**Issue by whittssg** [elastic/elasticsearch-net#2390]
Hello, i just upgraded to the new 5x version RC1 and cannot get an index created if i have the following descriptions on any of my properties:

 [Text(Analyzer = "uax_url_email")]

I used to use this in prior releases:

  [String(Analyzer = "uax_url_email")]

Thanks

**Comment by gmarz** [comment]
@whittssg what's the error returned from ES?

[uax_url_email](https://www.elastic.co/guide/en/elasticsearch/reference/5.0/analysis-uaxurlemail-tokenizer.html) is a tokenizer, not an analyzer.  You would create a custom analyzer with the `uax_url_email` tokenizer, then assign that analyzer to your properties.  

Can you share the response from `GET /<your-index-name>` here so we can see what if any custom analyzers you have?

**Comment by whittssg** [comment]
Hi @gmarz 

This is the repsonse : 
{Type: mapper_parsing_exception Reason: "Failed to parse mapping [users]: analyzer [uax_url_email] not found for field [email1]" CausedBy: "Type: mapper_parsing_exception Reason: "analyzer [uax_url_email] not found for field [email1]""}

I guess what you mean is that even though this wasn't giving an error in 2.x it wouldnt have been working ?
[String(Analyzer = "uax_url_email")]?

Thanks,

**Comment by gmarz** [comment]
@whittssg no, it should have given you an error in 2.x as well.  

This error indicates that there isn't an analyzer named `uax_url_email` in the index you're creating.  My guess is you had an analyzer also named `uax_url_email` in the 2.x index, and you're not carrying it over to the new index in 5.x.

In your create index call, you should add a custom analyzer and add the `uax_url_email` tokenizer to it.  Then add it to the field in your mapping.

```csharp
client.CreateIndex("myindex", c => c
	.Settings(s => s
		.Analysis(a => a
			.Analyzers(az => az
				.Custom("my_uax_url_email", ca => ca
					.Tokenizer("uax_url_email")
				)
			)
		)
	)
	.Mappings(m => m
		// snip 
	)
);
```

You would then assign `my_uax_url_email` as the analyzer on your POCO property, via attributes or the fluent API.

Also, the `string` type is [deprecated in 5.x and won't be allowed for a newly created index.](https://www.elastic.co/guide/en/elasticsearch/reference/5.x/string.html#string)  You need to use `text` or `keyword`.

Hope that makes sense?

**Comment by whittssg** [comment]
@gmarz It makes perfect sense, thanks for all your help.
