### ISSUE TITLE
Use FAKE's DotNetCli helper

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#2395]
[Use the DotNetCli helper that is now part of FAKE](http://fsharp.github.io/FAKE/apidocs/fake-dotnetcli.html)

**Comment by Mpdreamz** [comment]
👍 I'd wait though until the tooling itself RTM's in which case we can take the plunge fully and jump on the `new new csproj` files with VS2017 only support and a single `sln` file.

**Comment by Mpdreamz** [comment]
Implemented as per #2523
