### ISSUE TITLE
Requests and Responses should use DateTimeOffset instead of DateTime

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#2398]

**Comment by Mpdreamz** [comment]
:+1:

**Comment by russcam** [comment]
We discussed this change for 5.0. Whilst the change is straightforward, we would want to fully understand the ramifications of making it. It makes sense to target this at the next major version, 6.0.

**Comment by kcd83** [comment]
Was this effectively the case in v1.x because everything _seemed_ to be `DateTimeKind.Utc`?

#2773

**Comment by stevejgordon** [comment]
This looks to have been largely implemented in the current `7.x` client and will continue to be the case in `8.x` through code gen.
