### ISSUE TITLE
Generated Enum specific Resolve() methods for known enums

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#2400]
[`KnownEnums.Resolve(Enum e)`](https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Domain/Enums.Generated.cs#L391) can be used to get a string value for an enum value. We should generate enum specific `Resolve()` extension methods to avoid the type check and casting.

**Comment by Mpdreamz** [comment]
👍
