### ISSUE TITLE
Consistent Func<TDescriptor, TInterface>selector invocation

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#2406]
Going through 

- [`Analyzers`](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Analysis/Analyzers/Analyzers.cs)
- [`Tokenizers`](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Analysis/Tokenizers/Tokenizers.cs)
- [`CharFilters`](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Analysis/CharFilters/CharFilters.cs)
- [`TokenFilters`](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Analysis/TokenFilters/TokenFilters.cs) 

I noticed that the selector delegates are invoked in different ways, some using `selector.InvokeOfDefault()` and others doing `selector?.Invoke()`.

Added as an issue here to go through and sanitise/make consistent usage.

**Comment by Mpdreamz** [comment]
The rule is if the selector is nullable we call `selector.InvokeOrDefault()`otherwise we call `selector?.Invoke()` possibly assigning null if the user passes an explicit `null` as selector.

**Comment by russcam** [comment]
Agreed 😄 Was wondering if we could write some verification tests for this? 

With the examples of analysis components above, some of the selectors are nullable optional parameters and some of them are not; thinking it would be good to go through these to validate/verify these before 5.0.0 GA

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Please let us know if this issue is still a relevant priority for your usage?
