### ISSUE TITLE
Top hits aggregation - support multitype type hits

### ISSUE THREAD

**Issue by llRandom** [elastic/elasticsearch-net#2408]
**Describe the feature**:
Current version doesn't allow to get deserialized documents from `TopHitsAggregate` aggregation object if they have different types. An attempt to use an `object` as a generic type leads to an exception. The only workaround I've found is to use `Newtonsoft.Json.Linq.JObject` type for getting hits and then cast hits using `ToObject(targetType)` method:

    var doss = topHitsAgg.Hits<Newtonsoft.Json.Linq.JObject>()
        .Select(hit =>
        {
            var type = GetType(hit.Type);
            return hit.Source.ToObject(type);
        });

**Comment by Mpdreamz** [comment]
We have a special `ILazyDocument` type that you can use to defer the deserialization of your document type.

Then you can call `.As<MyObject>()` on these to materialize them.

**Comment by llRandom** [comment]
Thank you, that might work as a workaround instead of `Newtonsoft.Json.Linq.JObject` type but this interface doesn't allow to specify cast type at runtime (I can't pass required deserialization type as an argument). Besides, it looks odd to me that approaches for root hits and hits from top aggregation are so different.

**Comment by Mpdreamz** [comment]
@llRandom while I agree this would be a super handy feature, in NEST 5.x it would be incredibly hard to introduce without backwards compatible breaking changes. Closing this as `Elasticsearch 6.x` no longer supports multiple types this should be ideally handled by the serializer itself. 

In NEST 6.x and up it will be possible to configure a serializer **just** for `_source`'s and field values so the responsibility will shift.
