### ISSUE TITLE
5.0-RC3 Scalar mapping issues and feedback

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2415]
@Mpdreamz I came across two issues this morning with the new Scalar mapping.

1.  It doesn't work with enums (number backed). This one might be tricky as you may need to figure out the base type of the enum to pick the lowest data type.
2. selector parameter should be nullable. I have a very simple mapping where I'm just defining it like so: `.Scalar(f => f.BillingPrice, f => f)`. It would be really nice to just do `.Scalar(f => f.BillingPrice)`

**Comment by Mpdreamz** [comment]
Thanks for reporting this @niemyjski 

1. I don't think `Scalar` should support enums as any assumptions it will make will be wrong. A simple enum you might want to store as string or number in elasticsearch there is no wrong or right here. 
2. I'm on the fence about, even in those cases calling `AutoMap` is preferred. Then you only need to remap the exceptions with `.Scalar()` 

thoughts? cc @elastic/microsoft

**Comment by niemyjski** [comment]
1. All enums are integer backed, I can't think of any system I've worked with where the string representation was used.
2. I think it makes the api easier to use, especially when you have explicit mappings like we have.

**Comment by Mpdreamz** [comment]
With ES it can be quite normal to store the enum's string value as a not analyzed field that the application layer presents as a filter.

**Comment by gmarz** [comment]
1. I think `Scalar` behaving the same way as `AutoMap` is the most intuitive thing to do.  That means [mapping enums as integers](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Mapping/Visitor/PropertyWalker.cs#L103).

> I don't think Scalar should support enums as any assumptions it will make will be wrong. A simple enum you might want to store as string or number in elasticsearch there is no wrong or right here.

The same argument can be made against `AutoMap`.

2. I'm also on the fence, but I think there's nothing to gain by not allowing a nullable selector.  There are instances where someone may not be calling `AutoMap`, and thus would benefit from `Scalar` inferring the correct CLR type as `AutoMap` would.  Again, this aligns with the idea that `Scalar` and `AutoMap` should behave the same.
