### ISSUE TITLE
5.0-RC3 Ambiguity with IProperties.Count

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2416]
I came across an issue trying to see if an object property had any children this morning. This may be happening in other places as well.

```cs
var objectProperty = property as IObjectProperty;
if (objectProperty?.Properties?.Count > 0) {
}
```

Results in the following compiler error:

```
CS0229	Ambiguity between 'ICollection.Count' and 'ICollection<KeyValuePair<PropertyName, IProperty>>.Count'
```

Also, should Properties property be nullable?

**Comment by niemyjski** [comment]
![screen shot 2016-11-26 at 11 14 07 am](https://cloud.githubusercontent.com/assets/1020579/20641990/7a961740-b3c9-11e6-92c5-6e8e990bc413.png)

Looks like there are a few dupes in there.. I'm not even sure how that's possible LOL

**Comment by Mpdreamz** [comment]
Prior to #2399 our `IIsADictionary<>` implemented both `IDictionary<>` and `IDictionary` so in turn both `ICollection<>` and `ICollection`

However in RC3 you should not see that message anymore. With warning level set to 4 I am not getting `CS0229`.

According to the metadata browser in Vanilla VS this is IProperties expanded interface implementations:

```csharp
[JsonConverter(typeof(PropertiesJsonConverter))]
public interface IProperties : IIsADictionary<PropertyName, IProperty>
    , IDictionary<PropertyName, IProperty>
    , ICollection<KeyValuePair<PropertyName, IProperty>>
    , IEnumerable<KeyValuePair<PropertyName, IProperty>>
   , IEnumerable
   , IIsADictionary
{
}
```

None of which in turn implement the non generic `ICollection`. 

Are you sure the dll that ends up in `bin` is `rc3` ?

**Comment by niemyjski** [comment]
I'm closing this, I just tried it again after doing a `git clean -fxd` and it worked. I'm not sure what was there but maybe the bin folder wasn't properly updated. I had only rc3 references via nuget at the time.
