### ISSUE TITLE
Not able to find APIs to Create IndexTemplate and Dynamic Template

### ISSUE THREAD

**Issue by sreefubs** [elastic/elasticsearch-net#2423]
Hi All,

I'm using ElasticSearch 2.3.4 and NEST sdk for my .Net Application. I'm trying to define below Index Template and Dynamic Template using Nest Client but not able to identify appropriate APIs for the same,

{ 
"template": "*", 
"settings":{
"index":{
"analysis":{
"analyzer":{
"analyzer_keyword":{
"tokenizer":"keyword",
"filter":"lowercase"
}
}
}
},
"number_of_shards" : 5,
"number_of_replicas" : 0
},
"mappings": {
"default": {
"numeric_detection": true,
"dynamic_templates": [
{
"string_analyzer": {
"match_mapping_type": "string",
"match": "*",
"mapping": {
"type": "string",
"analyzer":"analyzer_keyword"
}
}
}
]
}
}
}

Any help is appreciated.

Thanks,
Sreeram

**Comment by Mpdreamz** [comment]
You can use `client.PutIndexTemplate()`, let me know if you need more details going forward.

**Comment by russcam** [comment]
@sreefubs This kind of question would be best asked on [discuss](https://discuss.elastic.co/c/elasticsearch) or [stackoverflow](http://stackoverflow.com/); we try to reserve github issues for bugs and issues related to the client.

**Comment by sreefubs** [comment]
@Mpdreamz Thanks for your quick response. Since I've to load template from a json file I did it as below,
            StreamReader r = new StreamReader(Environment.CurrentDirectory + @"\TemplateCreator\_template.json");
            string json = r.ReadToEnd();
            var response = EsClient.LowLevel.IndicesPutTemplateForAll<string>("custom_template", json);
