### ISSUE TITLE
Deprecated field [include] used

### ISSUE THREAD

**Issue by asp-sterling** [elastic/elasticsearch-net#2424]
The code using NEST:

```
var response = Client
    .Search<Party>(s => s
        .Source(src => src
            .IncludeAll())
        .Query(q => q
            .Match(m => m
            .Query("some string")
                .Operator(Operator.Or))));
```
The response contains a ServerError:

- Type: `illegal_argument_exception`
- Reason: `Deprecated field [include] used, expected [includes] instead`

... and the following query works fine in Kibana:

```
GET /_search
{
    "query": {
        "match" : {
            "name" : {
                "query" : "some string",
                "operator": "or"
            }
        }
    }
}
```
Did I come accross a bug?

**Comment by Mpdreamz** [comment]
What version of NEST and what version of Elasticsearch are you using?

**Comment by asp-sterling** [comment]
Elasticsearch 5.0.0 & NEST 2.4.7 (latest stable version available from NuGet)

Yeah, now I realized that the compatibility matrix clearly states I should be using NEST 5.0.0 as well even though it is a beta release. Thanks.

**Comment by russcam** [comment]
@asp-sterling It's a release candidate, with a GA release to be released very soon,
