### ISSUE TITLE
5.0 RC3 - Friendlier debugging experience with debugger display attributes

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2425]
It would be super useful if IProperty, PropertyName and many other types had debugger display attributes. For example, I'm trying to look into our mappings and this is what I see:
![screen shot 2016-11-29 at 2 56 32 pm](https://cloud.githubusercontent.com/assets/1020579/20728642/4c1a689e-b644-11e6-8692-770d1fd07b62.png)

**Comment by Mpdreamz** [comment]
👍 seems like a no brainer, we have some already but it'd be good to have a passover before 5.0 GA's
