### ISSUE TITLE
Elasticsearch.Net Doesn't Time Out Async Calls (HttpWebRequest Usage Bug)

### ISSUE THREAD

**Issue by WarrenAlpert** [elastic/elasticsearch-net#2438]
**NEST/Elasticsearch.Net version**: 2.4.7

**Elasticsearch version**: All Versions
**Description of the problem including expected versus actual behavior**:
  Async requests don't respect RequestTimeout set in ConnectionSettings (including the 60 second default). My team recently ran into network issues, meaning these requests to the cluster weren't completing, and this bug in ES.Net exacerbated the issue by pooling up an ever growing number of connections until we couldn't handle any more.

I located the bug here:
https://github.com/elastic/elasticsearch-net/blob/1de5538efda53dac24b024ce18c1b0c5012973ce/src/Elasticsearch.Net/Connection/HttpConnection.cs#L183

As you can see on MSDN, [HttpWebRequest.Timeout is NOT respected on async requests](https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.timeout(v=vs.110).aspx). Not sure the best solution, but one is to use HttpClient, which doesn't have this issue.

**Steps to reproduce**:
 1. Network issues or slow cluster response that causes a request to take longer than RequestTimeout in ConnectionSettings.
 2. The request does not time out.

**Comment by Mpdreamz** [comment]
Thank you for reporting this one @WarrenAlpert and apologies this blew up on your machines

I've opened a PR with a fix and some more backstory: https://github.com/elastic/elasticsearch-net/pull/2440

We'll do a 2.5 release very soon.

**Comment by Mpdreamz** [comment]
@WarrenAlpert we pushed NEST 2.5 with a fix for this to nuget today.
