### ISSUE TITLE
Timing issue causes no hits

### ISSUE THREAD

**Issue by Reyhn3** [elastic/elasticsearch-net#2442]
[ESTimingIssue.txt](https://github.com/elastic/elasticsearch-net/files/626988/ESTimingIssue.txt)
**Note**: For some reason, GitHub wouldn't accept the zip-file with a .zip-extension. Rename "ESTimingIssue.txt" to "ESTimingIssue.zip" and extract the project. Sorry for the inconvenience!

**NEST/Elasticsearch.Net version**: 5.0.0-rc4 as well as rc3

**Elasticsearch version**: 5.0.2 as well as 5.0.1

**Tested on**: Windows 7 SP1 64-bit, Intel Xeon E3-1246 v3 @ 3.50GHz with 32GB RAM

**Description of the problem including expected versus actual behavior**:
I'm afraid I don't fully understand the nature of this problem, so I'll provide a code example in hope someone with more insight in ES/NEST can make something out of it.

It seems that there is some kind of timing issue that prevents NEST from receiving the result from ES. If the code executes **too fast**, no hits are materialized. If a delay is injected, the same query produces the correct result. Hence, I believe the problem to reside in NEST, not ES.

In the `OnRequestCompleted` callback, when a `Thread.Sleep` is added, or simply a breakpoint in debug-mode is hit, the documents are materialized. If none of these are present, no hits are (incorrectly) reported back.

From the debug prints, the raw DSL query is printed, and when using the Sense-extension for Chrome, the very same query produces the expected result.

**Steps to reproduce**:
 1. Start ElasticSearch locally.
 2. Compile and run the attached example project. The output should state that no results were found.
 3. Uncomment the Thread.Sleep-line and run again. The output should state that results were found.

**Provide `DebugInformation` (if relevant)**:
Note that the "pause" required to make it work seems to depend on the complexity of the code being executed and the hardware. In a more complex index+query, the pause could be reduced to 75ms on my machine.

Output **without** delay:
```json
ElasticSearch request: Method: POST, Uri: http://localhost:9200/inventory/product/_search?pretty=true, Raw DSL: {
  "query": {
    "term": {
      "productId": {
        "value": "09916a80-47e7-490a-b356-79b98794293f"
      }
    }
  }
}
ElasticSearch response: Raw JSON: {
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}

No documents found! ):
```

Output **with** delay:

```json
ElasticSearch request: Method: POST, Uri: http://localhost:9200/inventory/product/_search?pretty=true, Raw DSL: {
  "query": {
    "term": {
      "productId": {
        "value": "146814a7-98fd-4db7-a11e-64c849f67db9"
      }
    }
  }
}
ElasticSearch response: Raw JSON: {
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 1,
    "max_score" : 0.2876821,
    "hits" : [
      {
        "_index" : "inventory",
        "_type" : "product",
        "_id" : "146814a7-98fd-4db7-a11e-64c849f67db9",
        "_score" : 0.2876821,
        "_source" : {
          "productId" : "146814a7-98fd-4db7-a11e-64c849f67db9",
          "manufacturerId" : "2b9524fe-986d-4033-b2ef-86710a905ed7",
          "name" : "Product A"
        }
      }
    ]
  }
}

Found Product A (146814a7-98fd-4db7-a11e-64c849f67db9).
```

**Comment by Mpdreamz** [comment]
What you are hitting is the near real time nature of elasticsearch:

From your code in the zip:

```csharp
client.Index(product, i => i.Index(indexName));
// Perform a search.
var result = client.Search<Product>(s => s
```

It might take up to a second (by default) for elasticsearch to refresh and create lucene segments that can be searched for your data. 

Our getting started guide has an excellent section on this:

https://www.elastic.co/guide/en/elasticsearch/guide/current/near-real-time.html

Single document operations (index/update/delete/get) are real time, _search is not.

**Comment by Reyhn3** [comment]
> This can be confusing for new users: they index a document and try to search for it, and it just isn’t there. 

D'oh!
Thank you for pointing me in the right direction! (:
