### ISSUE TITLE
5.0 RC4: DateHistogramBucket Date kind issue

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2452]
you can create a DateHistogram aggregation that has an offset. If you do this, each bucket will be returned with an offset time (off of utc). The Date Autoproperty you have specifys the offset type as utc from epoch

but that is an incorrect assumption the second the data is not stored as utc or you specify an offset.

**Comment by niemyjski** [comment]
Thinking of this more, I think utc is right just because if you create it as unspecified, it will be translated to the server / local time before being returned from the API. However, if you create a date histogram with a timezone offset, we should be creating the buckets with utc+ right offset so we know that it's the correct time by looking at it.

**Comment by codebrain** [comment]
Hi @niemyjski - I've been curating the old issues in this repository and came across this open issue from some years ago.

From reading the description you left it sounds as though this may be covered in the documentation?

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-datehistogram-aggregation.html#_timezone

I will close this issue, if you have any further queries please raise another, thanks.
