### ISSUE TITLE
5.0 RC4: Add warnings to aggregations that may be removed in a future release

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2453]
I'm not sure if this is possible but was looking at https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-max-bucket-aggregation.html and basically there are a lot of features that say caution it may be removed. Can we mark these as a compile time warning so at least you check out the docs, so you don't adopt a feature without at least the warning that it may be removed.

I'm not sure an obsolete attribute is right, but also potentially using something that could be removed does not set up end users for success (we like idiots, used every deprecated feature in the 1.x client and it has bitten us hard 👎  )..

**Comment by russcam** [comment]
I don't feel there's a better way of doing this, beyond them being documented as experimental on the Elastic site; they could be changed or removed in a future release but equally, they could not 😄 

Whether a feature marked as Experimental will prevent someone from taking advantage of it in knowledge of the warning, I feel, is a call for the individual. We always try to give as much forewarning and notice to features that will be removed, usually by first deprecating them in the next major version and then removing in the subsequent major version.
