### ISSUE TITLE
&= operator issue

### ISSUE THREAD

**Issue by EricKeij** [elastic/elasticsearch-net#2461]
NEST Version 2.5.0 

Consider the following code:

`QueryContainer q1 = new TermQuery {Field = "a", Value = "a" };`
`q1 &= new TermQuery {Field = "b", Value = "b" };`

Everything as expected. q1 contains the 2 must clauses

`QueryContainer result = q1 && new TermQuery {Field = "c", Value = "c" };`

After this statement q1 is changed and contains 3 must clauses instead of the original 2. Why is q1 changed in this scenario? 

If q1 is not using the &= operator but constructed with && it is working as expected.

**Comment by EricKeij** [comment]
I just found out NEST 2.3.1 is not having this issue. 
Also tested with NEST 2.4.6 and seeing the same behaviour as 2.5.0

**Comment by Mpdreamz** [comment]
Thanks for reporting @EricKeij and @russcam for bootstrapping the test :smile:

I've opened https://github.com/elastic/elasticsearch-net/pull/2467 to fix this and explained what happened there as well.
