### ISSUE TITLE
ValueAggregations missing value_as_string

### ISSUE THREAD

**Issue by ejsmith** [elastic/elasticsearch-net#2479]
**NEST/Elasticsearch.Net version**: NEST 5.0 RC4
**Elasticsearch version**: Elasticsearch 5.1.1 

**Description of the problem including expected versus actual behavior**:
If I do a min aggregation on a date field ES will return a value that is numeric plus a value_as_string that is the formatted date. NEST deserializes the response into a ValueAggregate model but loses the value_as_string field.

**Comment by russcam** [comment]
Thanks for reporting @ejsmith 👍
