### ISSUE TITLE
5.0 RC4 - Friendly overloads for Term Includes and Excludes

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2490]
We were using term includes and excludes and for string properties you have to use include / exclude patterns but for booleans and numbers etc you need to use values. Additionally elastic search allows you to pass integers, true, false or strings through, where all current nest api's only allow you to pass a string (no biggy as elastic will handle it, but I think nest should improve this api surface as it currently results in a runtime exception due to no compile time checks)

**Comment by russcam** [comment]
Will see if we can support this in 5.x.

> (no biggy as elastic will handle it, but I think nest should improve this api surface as it currently results in a runtime exception due to no compile time checks)

could you elaborate on this? When do you get a runtime exception?

**Comment by niemyjski** [comment]
It's been a while but if I remember correctly try to do term exclude and includes on a boolean/numeric field and try specifying `true`, `false`, `0`, `1` as the term value It's converted to a string and you get either a runtime exception or error from elasticsearch (don't remember).

**Comment by Mpdreamz** [comment]
Elasticsearch will except something like:

```json
POST project/_search
{
  "size" : 0,
  "aggs" : {
    "terms" : {
      "terms": {
        "field": "duration",
        "size": 10,
        "exclude": [4500000000]
      }
    }
  }
}
```

but internally each value is stored as a bytes ref and then fed as utf8 string.

```json
POST project/_search
{
  "size" : 0,
  "aggs" : {
    "terms" : {
      "terms": {
        "field": "duration",
        "size": 10,
        "exclude": ["4500000000"]
      }
    }
  }
}
```

Works just as well.
