### ISSUE TITLE
5.0: Add constants for known date formatters

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2493]
I think it would be helpful to provide some known constant values for things like date formatters: https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html#built-in-date-formats

What are your thoughts on this? Also, should a default one be sent in elastic 5 (dateOptionalTime was sent in 1.x).

**Comment by russcam** [comment]
Known date formats seems like a good idea 👍

**Comment by gmarz** [comment]
+1 on adding a `DateFormat` enum.  This means adding an overload everywhere we take a string though.

**Comment by Mpdreamz** [comment]
We now have constants on `DateFormat.*` thanks for the suggestion @niemyjski 👍
