### ISSUE TITLE
bulk index string

### ISSUE THREAD

**Issue by shakdoesgithub** [elastic/elasticsearch-net#2494]
Hi,

How would go about bulk indexing a collection of string that are already serialized in json? 

the following doesn't work because the doc gets serialized and escapes double quotes with backslash.
So something like this {"name": "jack"} becomes {"\name\":\"jack\"}

item.doc is a json string
```

BulkDescriptor descriptor = new BulkDescriptor();

                foreach (var item in items)
                {
                    descriptor.Index<object>(i => i
                        .Index("myIndex")
                        .Type(item.type)
                        .Id(item.docId)
                        .VersionType(VersionType.External)
                        .Version(item.processId)


                        .Document(item.doc));
                }

var response = await client.BulkAsync(descriptor);
```

**Comment by Mpdreamz** [comment]
The bulk needs json the json for the documents in a single line. `item.doc` needs to take care of that. 

The lowlevel client (`client.LowLevel.Bulk`) takes a `PostData<object>` which implicitly converts from `IEnumerable<string>`

So you can use that to send your json strings directly however you need to manually interweave each operations header manually in this case.

https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html

https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/post-data.html
