### ISSUE TITLE
5.0: Time needs to properly support different time units

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#2497]
There needs to be some solid unit tests for time parsing and it should handle all these cases (same ones supported by elastic server side:

https://github.com/exceptionless/Exceptionless.DateTimeExtensions/blob/master/tests/Exceptionless.DateTimeExtensions.Tests/TimeUnitTests.cs

I bring this up because I did `new Time("-3h").ToTimeSpan()` and it returned a timespan of `-3ms` which is completely wrong, it should be `-3 hours`.

**Comment by niemyjski** [comment]
@Mpdreamz Looks like there are many more use cases we are not thinking about I'm trying to pass `month`, `day` to a date histogram interval and it's blowing up.

   at Nest.Time..ctor(String timeUnit) in C:\Users\russ\source\elasticsearch-net-5.x\src\Nest\CommonOptions\TimeUnit\Time.cs:line 53

Could we look through all the test cases that elastic has and add them to the time parser? Also, any ideas on the next release date? We have customers asking for date range histograms by month :D

**Comment by russcam** [comment]
@niemyjski DateHistogram Aggregation takes a `Union<DateInterval, Time>` so can be passed either; For passing "month", "day", etc. use the respective `DateInterval` enum field value.

**Comment by niemyjski** [comment]
Well why is it being parsed when I set the interval as a string on the date histogram object? It should just allow it to be sent to elasticsearch and fail.

**Comment by russcam** [comment]
Can you show an example?

**Comment by niemyjski** [comment]
```cs
 return new DateHistogramAggregation(originalField) {
                Field = field,
                Interval = new Union<DateInterval, Time>("month"),
                Format = "date_optional_time"
            };
```

**Comment by niemyjski** [comment]
I'm guessing month is implicit conversion to time which can't be parsed it probably should be `DateInterval | Time | string` or Time shouldn't blow up if it can't be parsed. Elasticsearch might add a new time range that you don't support...

**Comment by niemyjski** [comment]
@russcam I can't use the enum.... This is coming straight from our parser https://github.com/exceptionless/Foundatio.Parsers/blob/master/src/Foundatio.Parsers.ElasticQueries/Extensions/DefaultAggregationNodeExtensions.cs#L38

a string is a valid overload and what es takes, you shouldn't blow up if you can't parse it and `month` and `day` are valid time/date intervals.

**Comment by niemyjski** [comment]
Maybe the solution is to have Time(string) return a nullable timespan or timespan.zero and have the two string (or how ever your populating the query) return the raw value if you don't know how to handle it. That would allow us to pass it anything.

**Comment by russcam** [comment]
> a string is a valid overload and what es takes

Currently, there is no implicit conversion from `string` to `DateInterval` so it's not currently a valid overload for setting an interval in NEST. 

It's important to keep the responsibilities of `Time` and `DateInterval` types separate, hence why the interval on date histogram take a union of those two types. There are other places within the API surface that accept `Time`, so allowing a conversion from `"month"` or any other interval string to an instance of `Time` doesn't seem like the best thing to do.

**Comment by niemyjski** [comment]
Can you create something that detects if it's a time unit or date interval and does the right thing? It's not user friendly from an api consumer and something not a lot of people are going to know. I don't want to have to know about DateInterval or time unit. I just want it to work by passing a string.....

**Comment by niemyjski** [comment]
I’m not going to parse the passed in string to figure what it is only for you to parse it a second time a “month” string is a valid value and you blow up when I pass in a valid string value so I gotta do a new Time() in a try catch and then try casting it to an enum just to use an interval generically?

The first thing someones going to do is go to the date histogram docs and the first example shows off “month” and “day” and they are going to put it into nest and then have it blow up, not a great onboarding experience.

What about if you created a new Interval type that with a base type of Union<DateInterval, Time> had an implicit conversion that checked for known interval values and returned the correct instance... win, win and it's semi future proof :)

**Comment by niemyjski** [comment]
Here is the code I added to get this (this is specific to my use case)

```cs
        private static Union<DateInterval, Time> GetInterval(string proximity, DateTime? start, DateTime? end) {
            if (String.IsNullOrEmpty(proximity))
                return new Union<DateInterval, Time>(GetInterval(start, end));

            switch (proximity.ToLower().Trim()) {
                case "second":
                    return DateInterval.Second;
                case "minute":
                    return DateInterval.Minute;
                case "hour":
                    return DateInterval.Hour;
                case "day":
                    return DateInterval.Day;
                case "week":
                    return DateInterval.Week;
                case "month":
                    return DateInterval.Month;
                case "quarter":
                    return DateInterval.Quarter;
                case "year":
                    return DateInterval.Year;
                default:
                    return new Union<DateInterval, Time>(proximity);
            }
        }
```
