### ISSUE TITLE
Cannot make any requests on CentOS 7

### ISSUE THREAD

**Issue by bling** [elastic/elasticsearch-net#2500]
**NEST/Elasticsearch.Net version**: 5.0.0

**Elasticsearch version**: 5.0.0

**Description of the problem including expected versus actual behavior**:
due to [this](https://github.com/elastic/elasticsearch-net/blob/9612fb0a35163dfef1757da54190e7e23d04a4ab/src/Elasticsearch.Net/Connection/HttpConnection-CoreFx.cs#L112) line of code, a `PlatformNotSupportedException` is thrown when trying to make any outgoing request.  i've filed a corresponding upstream bug at https://github.com/dotnet/corefx/issues/14614.

this only happens on Centos.  it's fine on Ubuntu.

**Steps to reproduce**:
```
var client = new System.Net.Http.HttpClientHandler();
client.MaxConnectionsPerServer = 8; // any value >= 1
```

**Comment by gmarz** [comment]
Thanks for reporting this @bling 👍 

FYI as a temporary workaround, you can override `CreateHttpClientHandler` in a custom `HttpConnection` implementation which doesn't set `MaxConnectionsPerServer`.

**Comment by Mpdreamz** [comment]
Closing this since the linked thread mentions this can be fixed by updating libcurl on the CentOS box itself. 

Thanks again for making us aware of this @bling much appreciated 👍

**Comment by ErikSchierboom** [comment]
For those struggling with this or unable to update their curl version, setting the `ConnectionLimit` value to `0` also fixes this issue, as then the `MaxConnectionsPerServer` property isn't set anymore.
