### ISSUE TITLE
Invalid format: "2016 - 12 - 18T10: 53:13.945Z" is malformed at " - 12 - 18T10: 53:13.945Z"

### ISSUE THREAD

**Issue by betimer** [elastic/elasticsearch-net#2501]
when init a PostData,  extra space is applied on datetime: "serverTimeStamp":"2016 - 12 - 18T10: 53:13:301Z"

Full log is below:
Unsuccessful low level call on POST: /webrtc-stats/pc-stats
# Audit trail of this API call:
 - [1] BadResponse: Node: https://search-dev-logs-fofbcvpfniwjxuhte55nn3u4ga.ap-southeast-2.es.amazonaws.com/ Took: 00:00:00.0912391
# ServerError: ServerError: 400Type: mapper_parsing_exception Reason: "failed to parse [clientTimestamp]" CausedBy: "Type: illegal_argument_exception Reason: "Invalid format: "2016 - 12 - 18T10: 53:13.945Z" is malformed at " - 12 - 18T10: 53:13.945Z"""
# OriginalException: System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 143
# Request:
{"audio":{"sent":{"codecName":"opus","inputLevel":"3","packetsLost":"0","rtt":"2","packetsSent":"13531","jitterReceived":"3","bytesSent":"382523"},"recd":{"jitterReceived":"2","jitterBufferMs":"28","packetsLost":"0","packetsReceived":"13531","bytesReceived":"408122","codecName":"opus"}},"video":{"sent":{"rtt":"1","packetsLost":"0","packetsSent":"60872","frameRateSent":"30","frameHeightSent":"480","frameWidthSent":"640","encodeUsagePercent":"29","cpuLimitedResolution":"false","viewLimitedResolution":"false","bandwidthLimitedResolution":"false","codecName":"VP8","bytesSent":"66714017"},"recd":{"packetsLost":"0","packetRecd":"61037","frameRateRecd":"29","frameHeightRecd":"480","frameWidthRecd":"640","bytesRecd":"66940004","jitterBufferMs":"26","codecName":"VP8"},"bandwidth":{"actualEncBitrate":"2072081","availableSendBandwidth":"2048000","availableReceiveBandwidth":"0","retransmitBitrate":"0","targetEncBitrate":"2048000","bucketDelay":"3","transmitBitrate":"2094592"}},"isOfferer":"true","encryption":"sha - 256","connectionType":{"local":{"candidateType":"local","ipAddress":"10.0.0.8","localCandidateId":"Cand - 02s2AoeL","localCandidateType":"local","networkType":"wlan"},"remote":{"candidateType":"local","ipAddress":"10.0.0.8","remoteCandidateId":"Cand - RVNLk / Im","remoteCandidateType":"local"},"transport":"udp","bytesSent":"67773522","bytesReceived":"68023343","packetsSent":"81472","requestsSent":"112","responsesSent":"112","requestsReceived":"112","responsesReceived":"112"},"clientTimestamp":"2016 - 12 - 18T10: 53:13.945Z","senderSocketId":"ciwuj525c00023d6xwgj22w1z","receivedKbps":0,"fromSocketId":"ciwuj4wlr00023d6smu6nefg7","conferenceId":"c7e589b4 - a9c1 - 4c14 - 99d3 - 2e95cc2264a8","videoCallQualityProfile":{"Name":"Standard","MediaCaptureParam":"camera min:640x480 max:640x480 min:15fps max:30fps","ConstrainBandwidth":2048},"roomId":6661,"networkId":3337,"networkType":5,"orgNetworkId":3334,"isFullStatsEnabled":true,"serverTimeStamp":"2016 - 12 - 18T10: 53:13:301Z","senderPersonId":15992,"receiverPersonId":44267}

**NEST/Elasticsearch.Net version**:
5.0

**Comment by russcam** [comment]
Can you provide a small reproducible example, @betimer? How are you making the request and constructing `PostData`?

**Comment by betimer** [comment]
looks like the server only accept this format DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ss.fffZ").
OK then I will close this issue, as it turns out to be my problem

**Comment by russcam** [comment]
@betimer ok, glad you got it sorted 👍
