### ISSUE TITLE
Order of query and aggregation elements should not be important when declared at same level

### ISSUE THREAD

**Issue by bloritsch** [elastic/elasticsearch-net#2507]
**NEST/Elasticsearch.Net version**: 2.4.6 (using Advanced Rest Client directly to verify)

**Elasticsearch version**: 2.4.1

**Description of the problem including expected versus actual behavior**:

Constructed a query where I wanted to restrict results and get aggregations on those results (faceted search interface).  I started with the aggregations defined first (as NEST produced it) and the query portion was completely ignored.

I changed the order of elements, and then I got the expected results.

**Steps to reproduce**:
 1. Produce a query with aggregations defined first.  Example:

```
    {
        "aggs": {
           "teachers": {
              "terms": { "field": "teachings.teacher.id", "size": 500 }
            }
        },
        "query": {
            "constant_score": {
                "filter": {
                    "bool": {
                       "must": [
                       {
                           "term": { "releasableTo": "Member" }
                       },
                  ]
             }
          }
        }
      }
    }
```

 2. Look at results and see examples that violate the query terms

 3. Swap query and aggregations sections

```
    {
        "query": {
            "constant_score": {
                "filter": {
                    "bool": {
                       "must": [
                       {
                           "term": { "releasableTo": "Member" }
                       },
                  ]
             }
          }
        }
      },
        "aggs": {
           "teachers": {
              "terms": { "field": "teachings.teacher.id", "size": 500 }
            }
        }
    }
```

4. Observe that the results are restricted as expected and the buckets reflect just the restricted set

It was my impression that the query string was declarative, i.e. evaluated as a whole and not in order.  When I am not directly in control of the query creation, it's rather important that the generated query has the effect I expected.

**Comment by Mpdreamz** [comment]
The order **has no bearing** on the execution:

Take this sense session and observe both search's output.

```json
DELETE my-index

PUT my-index
{
  "settings": {
    "number_of_shards": 1 
  }, 
  "mappings": {
    "type" : {
      "properties": {
        "name" : {
          "type": "string"
          , "index" : "not_analyzed"
        }
      }
    }
  }
}

POST my-index/type/1
{
  "name" : "New York",
  "description": "The big apple"
}
POST my-index/type/2
{
  "name" : "Chicago",
  "description": "The windy city"
}

POST my-index/type/_search
{
  "query" : {
    "query_string": {
      "query": "windy"
    }
  },
  "aggs": {
    "cities": {
      "terms": {
        "field": "name"
      }
    }
  }
}

POST my-index/type/_search
{
  "aggs": {
    "cities": {
      "terms": {
        "field": "name"
      }
    }
  },
  "query" : {
    "query_string": {
      "query": "windy"
    }
  }
}
````


Both your JSON examples are not valid, would love to help you diagnose further but would need some more information and complete examples.
