### ISSUE TITLE
MatchPhrasePrefix is deprecated

### ISSUE THREAD

**Issue by babadofar** [elastic/elasticsearch-net#2509]
**NEST/Elasticsearch.Net version**: 5.0

**Elasticsearch version**: 5.1.1

**Description of the problem including expected versus actual behavior**:
Using Elasticsearch 5.1.1 with the MatchPhrasePrefix operator, I get deprecation warnings

`Deprecated field [type] used, replaced by [match_phrase and match_phrase_prefix query]`

**Steps to reproduce**:
 1. Create a query using the MatchPhrasePrefix operator

**Provide `DebugInformation` (if relevant)**:

Examining the generated query, it looks like this 
`     "match": {
                            "navn": {
                              "type": "phrase_prefix",
                              "query": "Rasta"                        }                          }`
The new and improved syntax should be
`  "match_phrase_prefix": {    "navn": {                         
                              "query": "Rasta"
                            }
                          }`

**Comment by gmarz** [comment]
Nice catch @babadofar looks like we missed this :\

I've opened #2515 which will fix this in master, but debating whether we should back port it to 5.x since it will have to be done in backwards compatible manner leaving irrelevant and obsoleted properties on MatchQuery.
