### ISSUE TITLE
Whitespace analyzer seems to not work as expected

### ISSUE THREAD

**Issue by daluas** [elastic/elasticsearch-net#2512]
Hello,

I'm using a class like this:

public class UserSearchEntity
{
public string Id { get; set; }

    [Text(Analyzer = "whitespace", SearchAnalyzer = "whitespace")]
    public string Name { get; set; }

    [GeoPoint]
    public GeoLocation Location { get; set; }

    public string LocationAddress { get; set; }
}
but the SearchAnalyzer seems to not work.

The mappings looks like:

{
  "users" : {
    "mappings" : {
      "usersearchentity" : {
        "properties" : {
          "id" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "location" : {
            "type" : "geo_point"
          },
          "locationAddress" : {
            "type" : "text",
            "fields" : {
              "keyword" : {
                "type" : "keyword",
                "ignore_above" : 256
              }
            }
          },
          "name" : {
            "type" : "text",
            "analyzer" : "whitespace"
          }
        }
      }
    }
  }
}

I have several users: 

- Alina Damian
- Alina-Cristina Ghiba

but searching by Alina-Cristina returns also a user Alina Damian (you can see my users here http://178.22.68.157:9200/users/_search?pretty ), which should not be returned if the analyzer is whitespace.

My search method looks like:

public void Search(string textBox1Text)
        {
            var result = elasticClient.Search<UserSearchEntity>(s => s
                .Index(usersIndex)                
                .Query(q => q.QueryString(qs => qs.Query(textBox1Text + "*").Analyzer("whitespace"))).Size(100)
                .Sort(sort => sort.GeoDistance(g => g
                        .Field(p => p.Location)
                        .Unit(DistanceUnit.Kilometers)
                        .Mode(SortMode.Min)
                        .PinTo(new GeoLocation(0, 0))))
                );

            foreach (var user in result.Documents)
            {
                Console.WriteLine(user.Name);
            }
        }

I also tried without specifying the Analyzer field.

Any thoughts about this?

**NEST/Elasticsearch.Net version**:
2.0

**Elasticsearch version**:

{
  "name" : "P4yO8Bl",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "DC_aY2jlSaK1MVmpGpKINw",
  "version" : {
    "number" : "5.1.1",
    "build_hash" : "5395e21",
    "build_date" : "2016-12-06T12:36:15.409Z",
    "build_snapshot" : false,
    "lucene_version" : "6.3.0"
  },
  "tagline" : "You Know, for Search"
}

**Comment by babadofar** [comment]
This is not a bug with NEST. Since you are not specifying a field to search on, you are actually searching the "all" field, which uses the default analyzer, and can be configured separately. You can set a list of fields to search for in the querystring parameter. 

https://www.elastic.co/guide/en/elasticsearch/reference/5.1/mapping-all-field.html

**Comment by daluas** [comment]
OK. Thanks a lot. It was not clear that I have to specify the fields.

Thanks again.
Please close the issue.

Regards,

Dan Aluas

**Comment by gmarz** [comment]
Thanks @babadofar !
