### ISSUE TITLE
5.X Is TermVector intentionally not exposed on Nest.TextAttribute?

### ISSUE THREAD

**Issue by awelburn** [elastic/elasticsearch-net#2513]
Seems like it's missing the public property to allow us to set it:

```c#
[Text(TermVector = TermVectorOption.WithPositionsOffsets)] 
```

If it just needs adding, I'll submit a PR to add a public property that wraps the explicit interface property - just like the others do!

**Comment by gmarz** [comment]
It was indeed missing @awelburn thanks for reporting this 👍 I opened #2513 - sorry, the time it took to check was the same as just adding it, so I went ahead and did it :)

**Comment by awelburn** [comment]
Even better! thanks @gmarz

**Comment by yoav2** [comment]
Hi 
When the fix will be available? Can I get it Updating my NuGet?
I was just moving to elastic 5 and this is critical for my project... 
Thanks :)

**Comment by russcam** [comment]
@yoav2 Looking to release a new version of NEST 5.x this week

**Comment by yoav2** [comment]
Thanks russcam :+1:
