### ISSUE TITLE
cant use existing index with uppercase letters alias using NEST 5.0

### ISSUE THREAD

**Issue by ran729** [elastic/elasticsearch-net#2516]
i just migrated from NEST 1 to NEST 5 (along with elasticsearch 1.7 to 5.1.1) and stambled upon an annoying bug

**NEST/Elasticsearch.Net version**: 5.0.0

**Elasticsearch version**:5.1.1

**Description of the problem including expected versus actual behavior**:
cant use existing index with uppercase letters alias using NEST 5.0

**Steps to reproduce**:
 1.create an index 
 2.add alias with uppercase letters
 3. get the index using NEST with the alias name - ERROR (validating alias name as if it was index name) 
          error is - Index names cannot contain uppercase characters

DebugInformation:
"System.ArgumentException: Index names cannot contain uppercase characters: UpperCaseAliasName .\r\n   at Nest.IndexNameResolver.ValidateIndexName(String indexName) in C:\\Users\\russ\\source\\elasticsearch-net-5.x\\src\\Nest\\CommonAbstractions\\Infer\\IndexName\\IndexNameResolver.cs:line 49\r\n   at Nest.IndexNameResolver.Resolve(IndexName i) in C:\\Users\\russ\\source\\elasticsearch-net-5.x\\src\\Nest\\CommonAbstractions\\Infer\\IndexName\\IndexNameResolver.cs:line 20\r\n   at Nest.IndexName.GetString(IConnectionConfigurationValues settings) in C:\\Users\\russ\\source\\elasticsearch-net-5.x\\src\\Nest\\CommonAbstractions\\Infer\\IndexName\\IndexName.cs:line 76\r\n   at Nest.RouteValues.Resolve(IConnectionSettingsValues settings) in C:\\Users\\russ\\source\\elasticsearch-net-5.x\\src\\Nest\\CommonAbstractions\\Request\\RouteValues.cs:line 60\r\n   at Nest.ElasticClient.<Nest-IHighLevelToLowLevelDispatcher-DispatchAsync>d__253`4.MoveNext() in C:\\Users\\russ\\source\\elasticsearch-net-5.x\\src\\Nest\\ElasticClient.cs:line 75\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Hoard.ElasticSearch.Wrapper.Implementations.RepositoryImplementation.<SetRepositoryDetailsAsync>d__11.MoveNext() in D:\\Projects\\Hoard\\src\\HOARD.ElasticSearchWrapper\\Implementations\\RepositoryImplementation.cs:line 120\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Hoard.ElasticSearch.Wrapper.Implementations.RepositoryImplementation.<OpenRepositoryAsync>d__9.MoveNext() in D:\\Projects\\Hoard\\src\\HOARD.ElasticSearchWrapper\\Implementations\\RepositoryImplementation.cs:line 90\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Hoard.Web.Controllers.HoardController.<AddHoard>d__3.MoveNext() in D:\\Projects\\Hoard\\src\\HOARD.Web\\Controllers\\HoardController.cs:line 42\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()"
}

**Comment by Mpdreamz** [comment]
Can confirm as per:

https://github.com/nik9000/elasticsearch/commit/d23b8a64c8c148b7b79796facce96fe7624a76a7

Indexnames and alias names **are** validated the same way **except** for uppercase names.

Will try to create a workaround for an `5.0.1` release.

Are you using UPPERCASE as a way to differentiate between index names and their aliases?

**Comment by ran729** [comment]
I am using the alias as an easy and accessible name to hide the long and unique index name which is much more complicated.
Our old indexes uses uppercase letters in their alias names, which is why we want to make the upgrade easier not having to change all of the alias names to lower case,
Especially because ElasticSearch does not require it, only the NEST 5 name validation.

we will be very happy to find a fix in release 5.0.1, thanks!

**Comment by gmarz** [comment]
Closed via #2520

**Comment by ran729** [comment]
so its going to be fixed in release 5.0.1? when is it by the way?
