### ISSUE TITLE
MultiGetAsync with routing 5.0.0-alpha3

### ISSUE THREAD

**Issue by checkhavoc** [elastic/elasticsearch-net#2519]
NEST: 5.0.0-alpha3
ES: 2.3.2
.NETCore

Can functionality be added for MultiGetAsync to include .Routing()?

client.MultiGetAsync(m => m.GetMany<T>(ids).Index(index).Type(type).**Routing(ROUTING_NAME)**);

Using the above versions, I am not able to include routing with MultiGet or MultiGetAsync. If this does exist, can someone provide information? Are there any work arounds for this at the moment?

Thank you,
Jayr

**Comment by Mpdreamz** [comment]
```csharp
 client.MultiGetAsync(m => m.GetMany<object>(ids, (d, i) => d.Routing("")).Index("index").Type("type"));
```

`Index` and `Type` describe the default index and type for the whole multi get call. We can describe each get operation using a second parameter to `GetMany(list, descriptor_per_op)`

**Comment by Mpdreamz** [comment]
Also take note that `5.0.0` has been released on the stable channel!

**Comment by checkhavoc** [comment]
Got it! Thank you for the swift reply @Mpdreamz :)
