### ISSUE TITLE
Error when serializing GeoShapeBase

### ISSUE THREAD

**Issue by MattHartz** [elastic/elasticsearch-net#2524]
Hi,

I am receiving the error "Type 'Nest.GeoShapeBase' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute. If the type is a collection, consider marking it with the CollectionDataContractAttribute. See the Microsoft .NET Framework documentation for other supported types."

I have tried using the DataContract and DataMember attributes and still does not help.

Thanks!

Nest version 2.4.6

**Comment by gmarz** [comment]
Hey @MattHartz would you mind sharing some more info (C# snippets help) on how you're using it and where you're getting the error?

**Comment by MattHartz** [comment]
[ElasticsearchType(Name = "connection")]
    public class CorporateOfficeConnection
    {
        [Nest.String(Name = "id")]
        public string Id { get; set; }

        [Nest.Number(Name = "connectedofficeid")]
        public int ConnectedOfficeId { get; set; }

        [Nest.String(Name = "connectedofficename", Index = FieldIndexOption.Analyzed)]
        public string ConnectedOfficeName { get; set; }

        [Nest.Number(Name = "connectionid")]
        public int ConnectionId { get; set; }

        [Nest.Number(Name = "corporateofficeid")]
        public int CorporateOfficeId { get; set; }

        [Nest.String(Name = "corporateofficename")]
        public string CorporateOfficeName { get; set; }

        [Nest.GeoShape(Name = "servicelocations")]
        public List<Nest.CircleGeoShape> ServiceLocations { get; set; }

        public ConnectionProgram Program { get; set; }

        [ElasticsearchType(Name = "program")]
        public class ConnectionProgram
        {
            [Nest.Number(Name = "id")]
            public int Id { get; set; }

            [Nest.String(Name = "name", Index = FieldIndexOption.NotAnalyzed)]
            public string Name { get; set; }

            [Nest.Number(Name = "relationshiptype")]
            public ConnectionType RelationshipType { get; set; }

            [Nest.Boolean(Name = "standing")]
            public bool Standing { get; set; }
        }

        [ElasticsearchType(Name = "servicelocation")]
        public class ServiceLocation
        {
            [Nest.String(Name = "radius")]
            public string Radius { get; set; }

            [Nest.String(Name = "type")]
            public string Type { get; set; }

            [Nest.Number(Name = "relationshiptype")]
            public double[] Coordinates { get; set; }
        }



        public enum ConnectionType
        {
            Parent = 1,
            Child = 2
        }

        /*
        public class CustomNestGeoShapeConverter : CustomCreationConverter<Nest.CircleGeoShape>
        {
            public override Nest.CircleGeoShape Create(Type objectType)
            {
                return null;
            }

            public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
            {
                var token = JToken.Load(reader);
                if (token == null) return null;

                var shapes = new List<GeoShapeBase>();

                
                foreach (var shape in token) {
                    var type = shape.Value<string>("type");

                    switch (type)
                    {
                        case "circle":
                        {
                            var coords = new List<double>();
                            coords.Add(Double.Parse(shape["coordinates"][0].ToString()));
                            coords.Add(Double.Parse(shape["coordinates"][1].ToString()));
                            return new Nest.CircleGeoShape()
                            {
                                Coordinates = new GeoCoordinate(coords[0], coords[1])
                            };
                        }
                    }
                }

                return shapes;
            }

            public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
            {
                throw new NotImplementedException();
            }
        }*/
    }

**Comment by MattHartz** [comment]
Hi @gmarz ,

Here is the class. I redacted some of the code for clarity.
```C#
[ElasticsearchType(Name = "connection")]
public class Connection
{
    [Nest.String(Name = "id")]
    public string Id { get; set; }

    [Nest.GeoShape(Name = "servicelocations")]
    public List<Nest.CircleGeoShape> ServiceLocations { get; set; }
}
```

This is the class I am using to add the data into elasticsearch.  When adding this value, i am able to successfully search within a locations radius.  Where this fails, is returning this object via a service.  Apparently it is not serializable.  Does that make sense?

Thanks!

**Comment by gmarz** [comment]
@MattHartz sorry for the delayed response.  Yes, that makes sense.  However, the `GeoShape` types are really only meant to be used within NEST's query DSL.  We can't simply mark them `Serializable` or use the `DataContract` attribute either, because these constructs aren't supported by netstandard1.3.

Best practice would be to create your own domain objects to reflect the geo shapes, and only use the built-in NEST classes for querying.

Hope that makes sense?

**Comment by MattHartz** [comment]
@gmarz No worries.

Yeah that what we are doing.  We are just hoping to minimize the amount of domain objects we map to. :) 

Thanks
