### ISSUE TITLE
German Snowball analyzer fails due to misspelling

### ISSUE THREAD

**Issue by ZNS** [elastic/elasticsearch-net#2525]
**NEST/Elasticsearch.Net version**: 2.3.3

**Elasticsearch version**:  2.3.3

**Description of the problem including expected versus actual behavior**: When using SnowballAnalyzer with language set to "German" the language in the index becomes "Ferman" due to a spelling error. This causes indexing to fail. It seems to still exist:  elasticsearch-net/src/Nest/Analysis/Languages/SnowballLanguage.cs 

**Steps to reproduce**:
 1. Add a Snowball analyzer with language set to "German".

**Comment by Mpdreamz** [comment]
Nice catch! thank you for opening  a ticket @ZNS much appreciated. 

Opened a PR to fix this in the next release.

**Comment by russcam** [comment]
This will be in the next release. Thanks again for submitting @ZNS 👍
