### ISSUE TITLE
Cannot override AutoMap() in the ElasticClients Map<T> method

### ISSUE THREAD

**Issue by tomasfalt** [elastic/elasticsearch-net#2528]
**NEST/Elasticsearch.Net version**:
5.0.0

**Elasticsearch version**:
5.1.1

**Description of the problem including expected versus actual behavior**:
In version 2.x of Nest/ES you could override the AutoMap() method in the ElasticClient.Map method like this

```c#
client.Map<Person>(
                p =>
                    p.AllField(af => af.Enabled(false)).AutoMap()
                        .Properties(
                            PersonIndexMapping.PersonPropertiesDescriptor));
```
Now it seems that it only execute the AutoMap() method without the overridden properties.

Is this correct behavior or is there something I'm missing?

**Comment by gmarz** [comment]
[No, this should work as you're expecting.](https://www.elastic.co/guide/en/elasticsearch/client/net-api/5.x/auto-map.html#auto-mapping-with-overrides)  Need some more info though to see why it's not for you.

Are you getting an error, or are the overrides just not being mapped?

Can you share the raw request and response if possible (by setting `.DisableDirectStreaming()` and `.PrettyJson()` on your `ConnectionSettings`)?

Also, can you post the code for `PersonIndexMapping.PersonPropertiesDescriptor`?

**Comment by tomasfalt** [comment]
My bad. I was missing a UpdateAllTypes() which was not needed before.

I'm sorry I wasted your time.
