### ISSUE TITLE
Setting up ScrollId in NEST

### ISSUE THREAD

**Issue by ran729** [elastic/elasticsearch-net#2534]
**NEST/Elasticsearch.Net version**: 5.0.0

**Elasticsearch version**: 5.1.1

**Description of the problem including expected versus actual behavior**:
trying to set scroll_id to a slice scroll, and it asks for an int datatype instead of a string!
in the elasticsearch api the scroll_id is a string and also in the SearchResponse object.

**Steps to reproduce**:
 1. ElasticClient.SearchAsync<ExpandoObject>(s => s.Scroll("1m").Slice(o => o.Id("scroll_id_test")));
 2.build error because id accepts int and not string!

the scroll api is not usable right now because i cant use the scroll_id property, please fix.

**Comment by gmarz** [comment]
> ElasticClient.SearchAsync(s => s.Scroll("1m").Slice(o => o.Id("scroll_id_test")));

`Id` here is the id of the slice, not the scroll, which is an integer.

See https://www.elastic.co/guide/en/elasticsearch/reference/5.1/search-request-scroll.html

**Comment by ran729** [comment]
So how can i set the scroll_id then ?

**Comment by lostllama** [comment]
@ran729 lovely that @gmarz closed this and never replied to you. I now have the same question.

**Comment by lostllama** [comment]
@gmarz And how do we pass the scroll_id into NEST then?

**Comment by lostllama** [comment]
@gmarz 
For those coming to this, like me, trying to work out how to use ScrollId in `.Search()`, it seems that there is a separate method `.Scroll()`.

Unfortunately this issue is one of the highest ranking results on Google when searching for scroll_id and NEST.
