### ISSUE TITLE
Shower thought: Debug mode?

### ISSUE THREAD

**Issue by gmarz** [elastic/elasticsearch-net#2535]
Often when we're helping someone troubleshoot an issue we ask them to set `DisableDirectStreaming()` and also `PrettyJson()`.  This can sometimes be verbose and not very intuitive.

Thoughts on adding something more intuitive like `.DebugMode()` or `.EnableDebugging()` which encapsulates both of these, and any potential future features we add that aid in debugging (like https://github.com/elastic/elasticsearch-net/issues/1762 for instance)?

**Comment by russcam** [comment]
Sounds like a good idea - maybe `.EnableDebugMode()`?

**Comment by Mpdreamz** [comment]
++ just had to walk @LucaWintergerst through enabling all this and its too many steps.

```csharp
.EnableDebugMode(Func onRequestCompleted = null);
```
?
