### ISSUE TITLE
Error converting value 0 to type 'Nest.Retries'. Path 'retries', line 1, position 105.

### ISSUE THREAD

**Issue by NicolaDipierro** [elastic/elasticsearch-net#2539]
Hi guys,
I'm trying to execute an update by query operation. This is my code:

```
var response = elasticClient.UpdateByQuery<QualifiedLead>(u => u
					 .Script(s => s.Inline($"ctx._source.userId = userId").Params(p => p.Add("userId", userId))).Conflicts(Elasticsearch.Net.Conflicts.Proceed)
					 .Query(q => q.Term(t => t.Field(f => f.MultiRequestId).Value(requestGuid)))
					);
```
and I have this beautifull exception:

> Error converting value 0 to type 'Nest.Retries'. Path 'retries', line 1, position 105.

I'm using a 5.0.1 Nest version and 2.4.0 Elastic Version

Thank you.

**Comment by Mpdreamz** [comment]
`NEST 5.x` is only tested and supported against `Elasticsearch 5.x` while it might work for the most part there are several edge cases like this that you might hit.

The shape in which retries is returned is now an object in 5.x indicating whether the search or the update was retried and in 2.x it was an overall numeric.
