### ISSUE TITLE
Count with no body sends POST, but could send GET

### ISSUE THREAD

**Issue by asd-and-Rizzo** [elastic/elasticsearch-net#2540]
I use NEST 2.4.6 to get count:
```csharp
var count = this.elasticClient.Count<T>(x => x.Index("myindex").Type<T>()).Count;
```
It sends POST with
```json
{}
```

I believe it could send GET in this case. This may be fruitful if my credentials prevent POST, but I still need some overall count for application side optimizations/estimates and I do not want to go low level and POST adds slightly more performance overhead above GET and I want to copy/paste NEST debug output my browser. I believe it is possible to infer that it may be GET, not POST.

**Comment by Mpdreamz** [comment]
Makes sense, i opened https://github.com/elastic/elasticsearch-net/pull/2543. 

Thanks for raising this 👍 

We'll release a new 2.x either this week or next week. If you need it right now you can also subclass `CountRequest` and override `HttpMethod`.
