### ISSUE TITLE
Reindex from Remote option is missing

### ISSUE THREAD

**Issue by sumithub** [elastic/elasticsearch-net#2546]
**NEST/Elasticsearch.Net version**: 5.0.1

**Elasticsearch version**: 5.1.1

**Description of the problem including expected versus actual behavior**: Elasticsearch 5.0 brings the ability to reindex from remote cluster which seems to be missing in NEST 5.0.1. Just wondering any plans to include in forthcoming release? 

**Steps to reproduce**:
 1. Not able to run below in NEST 5.0.1
POST _reindex
{
  "source": {
    "remote": {
      "host": "http://otherhost:9200",
      "username": "user",
      "password": "pass"
    },
    "index": "source",
    "query": {
      "match": {
        "test": "data"
      }
    }
  },
  "dest": {
    "index": "dest"
  }
}
 2.
 3.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Describe the feature**:

**Comment by russcam** [comment]
Thanks for raising @sumithub; we'll add this into the next release 👍

**Comment by Mpdreamz** [comment]
Opened a PR for this: https://github.com/elastic/elasticsearch-net/pull/2549
