### ISSUE TITLE
Active Directory Authentication

### ISSUE THREAD

**Issue by CharlesBunders** [elastic/elasticsearch-net#2547]
Have an Elasticsearch cluster we can query fine with no authentication. When enabling a user:pass we can simply add that to the URL. However, we have now enabled Active Directory authentication on the Elasticsearch cluster. We can connect via cURL with user:pass from the command line. However, using Elasticsearch.net we can't see how we would pass a Windows security token in through the interface. Anyone get this working or tried it?

**Comment by Mpdreamz** [comment]
tracking this over on discuss: https://discuss.elastic.co/t/client-example-elasticsearch-with-active-directory-security-enabled/72337/2
