### ISSUE TITLE
Bulk Api - Dynamic Id Field

### ISSUE THREAD

**Issue by cheng93** [elastic/elasticsearch-net#2552]
**NEST/Elasticsearch.Net version**: 5.0.1

**Elasticsearch version**: 5.0.0

**Description of the problem including expected versus actual behavior**:

When using the bulk API, it is dynamically creating an `Id` field.
Tried different ways of setting Id property of our document.
Our mapping has `dynamic: strict`, so this throws an exception - this is fine for us.

Question is, why is it creating an `Id` field when it should be mapping it to `_Id` ?

**Steps to reproduce**:
 1. Simple POCO - let say we don't have access to edit it.
``` 
public class Product 
{
    public Product (Guid id)
    {
        Id = id;
    }
    public Guid Id { get; }

    public string Name {get; set;}
} 
```

There are more fields, but I left them out for simplicity.

 2.

```
var descriptor = new BulkDescriptor();
descriptor.IndexMany(products, (bd, q) => bd.Index("products").Type("product"));
client.Bulk(descriptor)
```

also used 

`descriptor.IndexMany(products, (bd, q) => bd.Id(q.Id.ToString()).Index("products").Type("product"));`

as a way of identifying the Id.

**Provide `ConnectionSettings` (if relevant)**:
```
new ConnectionSettings(connectionPool)
                .DefaultFieldNameInferrer(i => i)
```
as well as combinations of:
(a)
```
.InferMappingFor<Product>(i => i
     .IdProperty(p => p.Id)
)
```
(b)
```
.InferMappingFor<Product>(i => i
    .IdProperty(p => p.Id)
    .Ignore(p => p.Id)
)
```
(c)
```
.MapIdPropertyFor<Product>(p => p.Id);
```

When using (b), bulk api worked, however when retrieving the documents from ElasticSearch, the Id are not mapped, (ignored)

**Provide `DebugInformation` (if relevant)**:
`{Type: strict_dynamic_mapping_exception Reason: "mapping set to strict, dynamic introduction of [Id] within [product] is not allowed"}`

**Describe the feature**:

**Comment by cheng93** [comment]
```{
  "index" : {
    "_index" : "products",
    "_type" : "product",
    "_id" : "4efb4592-1271-4a22-ac8e-0024e631a39a"
  }
}
{
  "Id" : "4efb4592-1271-4a22-ac8e-0024e631a39a"
}
```

Gets producted when using `response.ApiCall.RequestBodyInBytes`. (.DisableDirectSteaming()` is on `ConnectionSettings`)

**Comment by Mpdreamz** [comment]
@cheng93 you are correct  in your conclusion: Id inference is only one way so this actually behaves as expected.

Id inference is strictly about url inference. 

So with option b) Id won't get stored in the actual `_source`. We do not mutate hits (by design) meaning the the `_id` on hit wont be hoisted to `_source` automagically. 

Hope this makes sense!
