### ISSUE TITLE
.Missing() for Term-aggregation of int-field

### ISSUE THREAD

**Issue by Grastveit** [elastic/elasticsearch-net#2561]
**NEST/Elasticsearch.Net version**: 5.0.1

**Elasticsearch version**: 5.1.2

**Description of the problem including expected versus actual behavior**:

When specifying `.Missing()` for Term-aggregation of integer-fields elastic reponds with a confusing error. 
It appears elastic 5 is stricter on types for missing-values in aggregations. `"missing":-1` works, but not `"missing":"-1"`.

**Steps to reproduce**:

```c
void Main()
{
	var client = new ElasticClient(new Uri("http://localhost:9200"));
	
	client.CreateIndex("fooindex", c => c.Settings(s => s.NumberOfShards(1).NumberOfReplicas(0))
		.Mappings(ms => ms.Map<Foo>(m => m.AutoMap()))
	);
	
	var resp = client.Search<Foo>(s => s
		.Index("fooindex")
		.Aggregations(a => a
			.Terms("a", t => t.Field(b => b.SomeInt)
				.Missing("-1") // need overload that takes int?
			)
		)
	);
	
	// writes: Field [someInt] of type [integer] does not support custom time zones
	Console.WriteLine(resp.ServerError.Error.RootCause.First().Reason); 
}

public class Foo
{
	public int Id { get; set; }
	public int SomeInt { get; set; }
}
```

**Comment by gmarz** [comment]
Hey @Grastveit thanks for raising this.  I've opened #2585 to fix this but unfortunately it can't be backported to 5.x in a backwards-compatible way.

As a workaround, try this:

```csharp
public class TermsAggregationHack : TermsAggregation
{
    public new int Missing { get; set; }
}
```
```csharp
.Aggregations(a => a
    .Terms("a", t => new TermsAggregationHack { Missing = -1 })
);
```
