### ISSUE TITLE
Add parent by default when indexing a document

### ISSUE THREAD

**Issue by gmoskovicz** [elastic/elasticsearch-net#2563]
Currently there is no way to define the parent property as an Attribute in a class. We could have a string field in a class, or an object that we could use one of his properties to map the parent.

I was thinking something like the following:

```
[Parent("Person.name")]
public Person person{}
```

or

```
[Parent]
public string person_name
```

**Comment by Mpdreamz** [comment]
Closing this since `parent` is no longer a param in `6.x`
