### ISSUE TITLE
Add XML documentation

### ISSUE THREAD

**Issue by StephenCleary** [elastic/elasticsearch-net#2564]
Add XML docs in the code, generate the XML files during build, and include them in the NuGet packages.

**Comment by Mpdreamz** [comment]
We definitely need to write more xmldocs overall, its been a long standing issue and something we can hopefully block a week or two soon for. 

We do not currently include documentation file for the `netstandard1.3` artifacts in our nuget package, we'll remedy this ASAP.

`net45` and `net46` do already include sourcelink enabled XML files in the published nuget packages.
