### ISSUE TITLE
Setting TypeNameHandling to Auto in the SerializerFactory produces unwanted side effects in queries

### ISSUE THREAD

**Issue by anellomancante** [elastic/elasticsearch-net#2565]
**NEST/Elasticsearch.Net version**: 5.0.1

**Elasticsearch version**: 5.1.2

**Description of the problem including expected versus actual behavior**:

Setting TypeNameHandling to Auto in the SerializerFactory produces unwanted side effects in some queries. In my case the Ids query produces this Json (the array was reduced to one element just for the sake of this example):
```json
"query":{"ids":{"values":{"$type":"System.Linq.Enumerable+WhereSelectArrayIterator`2[[System.String, mscorlib],[Nest.Id, Nest]], System.Core","$values":["Opportunities/17b51da1-0b69-49ae-849e-352bc7f84a48"]}}}
```
**Steps to reproduce**:
 1. Set TypeNameHandling to Auto in the SerializerFactory
 2. Create a request with an Ids query and pass it to the NEST Search<T> method.
 3. You will get an invalid Response telling you that the Ids query cannot contain an object.

**Provide `ConnectionSettings` (if relevant)**:
```csharp
var connectionPool = new SingleNodeConnectionPool(new Uri(config.Connection.Url));

var settings = new ConnectionSettings(connectionPool, new HttpConnection(), new SerializerFactory((json, nest) => {
json.Converters.Add(new StringEnumConverter());
json.TypeNameHandling = TypeNameHandling.Auto;
}));
```
**Provide `DebugInformation` (if relevant)**:

(Some data was removed for privacy reasons)

Invalid NEST response built from a unsuccessful low level call on POST: /<xxx>/<yyy>/_search?scroll=2m
# Audit trail of this API call:
 - [1] BadResponse: Node: https://<removed>:<removed>/ Took: 00:00:00.3380140
# ServerError: ServerError: 400Type: parsing_exception Reason: "[ids] values doesn't support values of type: START_OBJECT" CausedBy: "Type: illegal_argument_exception Reason: "[ids] values doesn't support values of type: START_OBJECT""
# OriginalException: System.Net.WebException: Errore del server remoto: (400) Richiesta non valida.
   in System.Net.HttpWebRequest.GetResponse()
   in Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Connection\HttpConnection.cs:riga 143

**Comment by Mpdreamz** [comment]
Enabling TypeNameHandling.Auto like this will break our own serializing. mark your POCO's manually with `[JsonObject(TypeNameHandling)]` attributes.

See also: https://github.com/elastic/elasticsearch-net/issues/1155
