### ISSUE TITLE
How do I use the new "normalizer" feature from ES 5.2 today?

### ISSUE THREAD

**Issue by rosrosros** [elastic/elasticsearch-net#2567]
I see that there is a release/5.2 branch, but it does not contain the new normalizer feature https://www.elastic.co/guide/en/elasticsearch/reference/5.2/normalizer.html

What are my options if I want to use this feature from C#?

**Comment by russcam** [comment]
@rosrosros We plan to include normalizer in the next 5.x release /cc @elastic/microsoft .

In the meantime, you can use the low level client (exposed via `.LowLevel` on `IElasticClient`) to create a mapping with a normalizer;

**Comment by rosrosros** [comment]
@russcam  Thanks for quick feedback. That just works!

Do you have an estimated release date for the 5.x release?

**Comment by russcam** [comment]
We're aiming to release a new version this week or next.

**Comment by rosrosros** [comment]
Thanks mate!
