### ISSUE TITLE
A possible bug: Http line is larger than 4096

### ISSUE THREAD

**Issue by mu-soliman** [elastic/elasticsearch-net#257]
When trying to analyze an Arabic string using the following code:

`AnalyzeParams parameters  = new AnalyzeParams();
  parameters.Analyzer = "arabic";
  var result = _Client.Analyze(parameters, Article);`

ElasticSearch crashes with the following output:
org.elasticsearch.common.netty.handler.codec.frame.TooLongFrameException: An HTTP line is larger than 4096 bytes.

This is the a sample text that causes this exception:
"قال حزب مصر القوية، إن قصف سوريا من قبل الاحتلال الإسرائيلي ما هو إلا امتداد لسلسلة من الأعمال الحقيرة التي ترعاها وتدافع عنها الإدارة الأمريكية.

وأضاف الحزب، في بيان له على صفحته الرسمية على موقع التواصل الاجتماعي «الفيس بوك»، اليوم الاثنين، أن الكيان الصهيوني الذي يضع نفسه فوق كل القوانين والأعراف اعتاد على إجرامه.
وأشار إلى أن سوريا بالنسبة لنا هي الشعب السوري، ولا نتألم إلا لتألم هذا الشعب الشقيق واستباحة أراضيه وقصف مقدراته، مؤكدًا أن الإدانة الواضحة للتعدي السافر على الأراضي السورية من الكيان الصهيوني لا يجب أن تنسينا عذابات هذا الشعب السوري الذي يقدم كل يوم أرواح مئات من شهدائه الأبرار، في مواجهة نظام مجرم لم يطلق رصاصة واحدة نحو عدو صهيوني، يحتل أراضي سورية عزيزة منذ عشرات السنين.

وطالب الجامعة العربية بالتحرك السريع والتدخل الفاعل، وأن تقوم مصر بدورها العربي المنتظر بالتأثير على المشهد السوري بما تحمله من ثقل عربي وإسلامي، و أﻻ تكتفي ببيانات الشجب واﻹدانة،  لحقن دماء السوريين وحماية مقدراتهم وأراضيهم من اﻻستباحة الصهيونية."

**Comment by yasenblky** [comment]
ماذا عن قصف النظام وقال مايزيد عن مليون إنسان اليسوا هؤلاء من الشعب السوري
