### ISSUE TITLE
Successive calls to Must, Should, MustNot and Filter are not additive

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#2570]
Consider

```c#
var predicate = true;
var b = new BoolQueryDescriptor<Document>();

b.Must(m => m.Term(f => f.Field1, "value1"));

if (predicate)
{
    b.Must(m => m.Term(f => f.Field2, "value2"));
}

client.Search<Document>(s => s
    .Query(q => q
        .Bool(_ => b)
    )
);
```

this results in the following query

```json
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "field2": {
              "value": "value2"
            }
          }
        }
      ]
    }
  }
}
```

The last call to `.Must()` overrides any previously passed queries. I know there are other ways to write this query to combine the two must clauses, for example

```c#
var predicate = true;

client.Search<Document>(s => s
    .Query(q => q
        .Bool(b => b
            .Must(
                m => m.Term(f => f.Field1, "value1"),
                m =>
                {
                    // intentional use of method group vs. expression
                    if (predicate)
                        return m.Term(f => f.Field2, "value2");
        
                    return m;
                }
            )
        )
    )
);
```
but the behaviour seems surprising for the simple usage case.

I propose to make the calls to `.Must()`, etc. be additive such that it would produce the following query

```json
{
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "field1": {
              "value": "value1"
            }
          }
        },
        {
          "term": {
            "field2": {
              "value": "value2"
            }
          }
        }
      ]
    }
  }
}
```

Thoughts? /cc @elastic/microsoft

**Comment by Mpdreamz** [comment]
Big :-1: from me 😄 

All `.Fluent()` assignments override just as `Must =` would. I'd hate to reintroduce exceptions to this rule like we had with `Sort()` in `1.x`.

The first example as given to me reads: `if (predicate) { do this must array instead }`

You can rely quite easily on the bitwise operators to generate more dynamic queries.

 `.Bool(b=> q.Term() && q.Term())` with a multiline lambda to introduce branching or rely on condition less queries e.g `.Bool(b=>q.Term && q.Term(field, predicate ? value : null)`

Another mechanism in the client is `q.Conditionless(query, fallbackQuery)` construct that can be used to introduce branching.

Then you can mix and match OIS and Fluent queries where you build your mustclauses as a list dynamically and inject it in the fluent version. 

`.Must(MethodThatDynamicallyYieldsQueries.ToArray())`

Loads of options here already IMO.

**Comment by ronnyek** [comment]
I can see argument in both directions to be honest. (This was probably spurred on by conversation between @russcam and myself on slack if I had to guess)

I can see the argument for some alignment with elastic APIs, but at the same time, seems like some of this doesn't appear to support "building" the way people are expecting to be able to use fluent builders. (or at least that's the case for me, compared to how I'd use a fluent builder in most other frameworks).

I've found the fluent and lambda stuff in nest to be fairly un-intuitive, even though I know roughly what to expect a query needing to look like, output wise from nest.

@Russcam gave me ideas about how to get around this for now, just thought I'd put in my .02c.

**Comment by Mpdreamz** [comment]
Appreciate the feedback @ronnyek , closing this out as we wont be changing the way the API's work.

I get your point though but for e.g simpler properties it will become rather ambiguous

```csharp
.Field()
.Field()
```

The `"proper"` fluent builder interfaces would protect against this by having the first return a new instance of a closed builder that does not allow field to be set again. This would be super impractical for the amount of request classes we need for all the Elasticsearch APIs.

`NEST` was never designed to be a `"proper"` fluent DSL, rather a way to fluently assign. In that model the overwriting makes total sense IMO.
