### ISSUE TITLE
Reduce GeoDistance Insanity

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#2593]
https://github.com/elastic/elasticsearch/pull/19846

GeoDistance query, sort, and scripts make use of a crazy GeoDistance enum for handling 4 different ways of computing geo distance: SLOPPY_ARC, ARC, FACTOR, and PLANE. Only two of these are useful: ARC, PLANE.

**Comment by gmarz** [comment]
I think this is covered by #2612  which completely removes `GeoDistanceType`?

**Comment by Mpdreamz** [comment]
Yep 👍  and in `5.x` the old enum values will be rewritten by ES.
