### ISSUE TITLE
Remove DFS_QUERY_AND_FETCH as a search type

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#2597]
https://github.com/elastic/elasticsearch/pull/22787

**Comment by gmarz** [comment]
Pending my comment on elastic/elasticsearch#22787

**Comment by s1monw** [comment]
you can't use this search type since 2.0 via rest. I think you can just trash it

**Comment by gmarz** [comment]
@s1monw thank, we got this confused with `dfs_query_THEN_fetch`.  We've already removed it in our 5.x branch.
