### ISSUE TITLE
Fix parsing for `max_determinized_states`

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#2609]
https://github.com/elastic/elasticsearch/pull/22749

This looks like a breaking change for us since its not bwc in Elasticsearch (at first very quick glance)

**Comment by gmarz** [comment]
Looks like we're already using the correct spelling (which was wrong?) 

https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/QueryDsl/FullText/QueryString/QueryStringQuery.cs#L53

**Comment by Mpdreamz** [comment]
yup! we future proofed our code *cough* *cough*
