### ISSUE TITLE
Error Getting Response Stream

### ISSUE THREAD

**Issue by saintpaul1984** [elastic/elasticsearch-net#2615]
**NEST/Elasticsearch.Net version**: 5.2.0

**Elasticsearch version**: 2.3

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Setup elasticclient with base settings (and connectionlimit to -1)
 2. Call a search to index in elastic.co ES cluster
 3. Error!

**Provide `ConnectionSettings` (if relevant)**: 

var settings = new ConnectionSettings(uri);
settings.ConnectionLimit(-1);

q1 = (Nest.QueryContainerDescriptor<xxxxxxxx>)q1.Term("xxxxx", yyyyyy);
var result = client.Search<xxxxxxxxxx>(s => s.
														 Index(index).
														 Type(type).
														 From(0).
														 Size(50).
														 Query(q => q1)
														);

**Provide `DebugInformation` (if relevant)**:
{Elasticsearch.Net.UnexpectedElasticsearchClientException: Error getting response stream (ReadDone2):…}	Elasticsearch.Net.UnexpectedElasticsearchClientException

DebugInformation	"# FailureReason: Unrecoverable/Unexpected BadRequest while attempting POST http://xxxx:yyyyy@7e292f6f852bef41d3ed924a76209786.us-east-1.aws.found.io:9200/provider_login/prov_login/_search\n - [1] BadRequest: Node: http://xxxxxxx:yyyyyyyyy@7e292f6f852bef41d3ed924a76209786.us-east-1.aws.found.io:9200/

**Comment by gmarz** [comment]
NEST 5.2 isn't compatible with ES 2.3.   See the [compatibility matrix](https://github.com/elastic/elasticsearch-net#compatibility-matrix).

Try either upgrading to ES 5.x if possible, or downgrade the client to 2.x.

Feel free to re-open if the issue still persists after that.
