### ISSUE TITLE
Boost in field name bug

### ISSUE THREAD

**Issue by stdray** [elastic/elasticsearch-net#2626]
Class FieldNameQueryDescriptorBase has method

  ```public TDescriptor Field(Field field);```

There is a problem in the use of this method with combinator term-level (like .Term, .Wildcard, .MatchPhrase, etc).
When i created Field I used Boost (as in example)

  ```
FieldsDescriptor<PurchasesDocument> GetTextFields(FieldsDescriptor<PurchasesDocument> fd)
        {
            return fd.
                Field(ff => ff.Identity, Constants.HighBoost).// key
                Field(ff => ff.ParentIdentity, Constants.HighBoost).// key
                ...
```

And when i serialized NEST request in json, I got elements
  ```
{
          "term": {
            "purchases.Identity^10": {
              "value": "xxxx"
            }
          }
        },
        {
          "term": {
            "purchases.ParentIdentity^10": {
              "value": "xxxx"
            }
          }
        },
```

Because of the presence word Boost in the title (kind of ^10) the search didn't get any results. But when i skip word Boost (purchases.Identity^10 => purchases.Identity) the search was successful.

It's worth noting, that all works correctly for MultiMatchQuery, but for TermQuery, WildcardQuery, MatchPhraseQuery and probably other term-level queries it doesn't work.

NEST: 5.2.0
Elastic: "version": {
    "number": "5.2.0",
    "build_hash": "24e05b9",
    "build_date": "2017-01-24T19:52:35.800Z",
    "build_snapshot": false,
    "lucene_version": "6.4.0"
},

**Comment by russcam** [comment]
@stdray Thanks for reporting. I can replicate with 

```c#
public class Test
{
	public string Message { get; set; }
}

Field field = Infer.Field<Test>(f => f.Message, 10);
	
client.Search<Test>(s => s
	.Query(q => q
		.Term(tq => tq
			.Field(field)
			.Value("value")
		)
	)
);
```

which produces 

```json
{
  "query": {
    "term": {
      "message^10": {
        "value": "value"
      }
    }
  }
}
```

Is that similar to what you're doing?

**Comment by stdray** [comment]
@russcam 
yes,  this behavior causes the problem. Also I use the prefix (like `purchases`.Parentidentity). but I'm not sure that it matters.

**Comment by Mpdreamz** [comment]
Field syntax boosting is only supported by some queries e.g the `match` query family.

Other queries take the boost as part of their options.
