### ISSUE TITLE
BulkAll vs. Exceptions

### ISSUE THREAD

**Issue by rosrosros** [elastic/elasticsearch-net#2634]
Using NEST 5.2 with this index code;
```

 var waitHandle2 = new CountdownEvent(1);

            var bulkAll = elasticClient.BulkAll(docs, b => b
                .MaxDegreeOfParallelism(8)
                .BackOffTime(TimeSpan.FromSeconds(10))
                .BackOffRetries(2)
                .Size(1000)
                .RefreshOnCompleted() 
                .Index(indexName)
            );

            bulkAll.Subscribe(new BulkAllObserver(
                onNext: (b) => { Console.Write("."); },
                onError: (e) => { throw e; },
                onCompleted: () => waitHandle2.Signal()
            ));

            waitHandle2.Wait();

            return;
```

If an exception is thrown the `onError` is hit, but the code never reaches the `return` statement 

Please advise

**Comment by rosrosros** [comment]
Ended up using this solution:


var waitHandle2 = new ManualResetEvent(false);

	var docs = new[] {new Product(),new Product()};
	var bulkAll = client.BulkAll(docs, b => b
		.MaxDegreeOfParallelism(8)
		.BackOffTime(TimeSpan.FromSeconds(1))
		.BackOffRetries(1)
		.Size(1000)
		.RefreshOnCompleted()
		.Index(indexName)
	);

	//we set up an observer
	Exception ex = null;
	var bulkObserver = new BulkAllObserver(
		onError: (e) =>
		{
			ex = e;
			waitHandle2.Set();
			throw e;
		} ,
		onCompleted: () => waitHandle2.Set(),
		onNext: (b) =>  Console.Write("on next")
	);
	
	bulkAll.Subscribe(bulkObserver);
	waitHandle2.WaitOne();
	
	if (ex != null )
		throw ex;

**Comment by Mpdreamz** [comment]
In the first example noone signals `waitHandle2` in RX only `onError` or `onCompleted` are called at most once.

If you include a reference to the full RX framework you'll gain handy operators like [Finally() and others](http://www.introtorx.com/Content/v1.0.10621.0/11_AdvancedErrorHandling.html) to deal with this in a more composable way.

It should not be necessary to rethrow in the onError but reviewing our current code i do think i spotted a bug where we need to throw here:

https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs#L89-L94

and rely on this guy to call OnError once: 

https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs#L57

**Comment by rosrosros** [comment]
Thanks mate - and keep up the good work!

**Comment by Mpdreamz** [comment]
Instead of calling `.Subscribe()` you can now also call `.Wait(TimeSpan, Action onNext)` which will block and throw exceptions more naturally if blocking is the desired behavior.

**Comment by rosrosros** [comment]
Thank @Mpdreamz,

Does `BulkAllObservable<T>` have a `.Wait` method? - can't seem to find it
