### ISSUE TITLE
fvh is not working correctly with match_phrase query with slop.

### ISSUE THREAD

**Issue by cesar2** [elastic/elasticsearch-net#2637]
**NEST/Elasticsearch.Net version**: 5.0.0

**Elasticsearch version**: 5.0.0

**Description of the problem including expected versus actual behavior**:  I am trying to highlight some match_phrase queries with slop. With the plain highlight is working fine, but with fvh does not and I don't know why.

**Steps to reproduce**:
 1. Index some documents.
 2. Do a match_phrase query with slop and using **fvh**, like this: 

```
 var resultado2 = client.Search<dynamic>(s => s
         .Size(100)
         .Type(Types.Type("text"))
         .Query(q => q.MatchPhrase( mf => mf.Field("textContent").Query(TextToSearch).Slop(8))
             )
         .Highlight(h => h
                .PreTags("<strong style=\"color:#FF4000;\">")
                .PostTags("</strong>")
                .Fields(fs => fs
                    .Field("textContent")
                    .Order("score")
                    .Type(HighlighterType.Fvh)
                    .FragmentSize(150)
                    .NumberOfFragments(3)
                    .NoMatchSize(150)
                    .ForceSource()
                ))


                 )

                 ;
```
 3. When I see the results, the words are not highlighted.

**Provide `ConnectionSettings` (if relevant)**:
```
 client.CreateIndex("documents", c => c
                       .Settings(s => s
                           .NumberOfShards(1)
                           .NumberOfReplicas(1)
                           .Analysis(analysis => analysis
                                .TokenFilters(tf => tf.Stop("stop_es",st => st.StopWords("_spanish_")))
                                .Analyzers(bases => bases
                                    //.Snowball("es_std", es => es.Language(SnowballLanguage.Spanish))
                                    .Custom("analizador_prueba", ca => ca
                                    .Tokenizer("standard")
                                    .Filters("lowercase","stop_es","asciifolding")
                                    
                                    )
                                )
                            )
                       )
                      .Map<texto>(d => d
                           .Properties(p => p
                                   .Text(st => st
                                        .Name(na => na.textContent)
                                        .TermVector(TermVectorOption.WithPositionsOffsets)
                                        .Analyzer("analizador_prueba")
                                   )
                            )
                 )
```
**Provide `DebugInformation` (if relevant)**:

**Describe the feature**:
Is there any problems with the **fvh** with match_phrase queries with slop?

**Comment by russcam** [comment]
[The Fast Vector Highlighter needs `term_vector` set to `with_positions_offsets` in the field mapping to work](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html#fast-vector-highlighter); I can see you have it in the creat index mapping, but what does the mapping look like for `textContent` in Elasticsearch if you retrieve it?

**Comment by cesar2** [comment]
I don't understand your question. What do yo mean?

**Comment by russcam** [comment]
I mean, if you call

```
GET documents/_mapping 
```

what does it return?

**Comment by cesar2** [comment]
Here I show my setting of the whole Index (documentos500 is the name):

{
  "documentos500": {
    "mappings": {
      "hipertext": {
        "_parent": {
          "type": "contenidosweb"
        },
        "_routing": {
          "required": true
        },
        "properties": {
          "id": {
            "type": "long"
          },
          "textoContenido": {
            "type": "text",
            "term_vector": "with_positions_offsets",
            "analyzer": "my_analyzer"
          },
          "tituloHiperTexto": {
            "type": "text",
            "term_vector": "with_positions_offsets",
            "analyzer": "my_analyzer"
          }
        }
      },
      "imagenes": {
        "_parent": {
          "type": "contenidosweb"
        },
        "_routing": {
          "required": true
        },
        "properties": {
          "etiquetas": {
            "type": "text",
            "analyzer": "my_analyzer"
          },
          "id": {
            "type": "long"
          },
          "pixelesAltura": {
            "type": "long"
          },
          "pixelesAnchura": {
            "type": "long"
          }
        }
      },
      "texto": {
        "_parent": {
          "type": "contenidosweb"
        },
        "_routing": {
          "required": true
        },
        "properties": {
          "id": {
            "type": "long"
          },
          "textoContenido": {
            "type": "text",
            "term_vector": "with_positions_offsets",
            "analyzer": "my_analyzer"
          }
        }
      },
      "contenidosweb": {
        "properties": {
          "autorArchivo": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "fechaCreacionArchivo": {
            "type": "date"
          "formato": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "id": {
            "type": "long"
          },
          "nombreArchivo": {
            "type": "text",
            "term_vector": "with_positions_offsets",
            "analyzer": "my_analyzer"
          },
          "tamanoArchivo": {
            "type": "float"
          },
          "urlProtocolo": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "urlPuerto": {
            "type": "long"
          },
          "urlRuta": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          }
        }
      },
      "audio": {
        "_parent": {
          "type": "contenidosweb"
        },
        "_routing": {
          "required": true
        },
        "properties": {
          "duracion": {
            "type": "long"
          },
          "etiquetas": {
            "type": "text",
            "analyzer": "my_analyzer"
          },
          "id": {
            "type": "long"
          }
        }
      },
      "video": {
        "_parent": {
          "type": "contenidosweb"
        },
        "_routing": {
          "required": true
        },
        "properties": {
          "calidad": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "duracion": {
            "type": "long"
          },
          "etiquetas": {
            "type": "text",
            "analyzer": "my_analyzer"
          },
          "id": {
            "type": "long"
          }
        }
      }
    }
  }
}


Thanks! :)

**Comment by Mpdreamz** [comment]
Late reply but you are searching on `.Field("textContent")` which is not mapped in your mapping. Did you mean `.Field(p=>p.textContent)` which'll get translated to `textoContenido` ?
