### ISSUE TITLE
_cat/aliases/multiple,aliases - not returning any records - But api for NEST is provided for such a request.

### ISSUE THREAD

**Issue by Cnordbo** [elastic/elasticsearch-net#2638]
**NEST/Elasticsearch.Net version**: 5.2

**Elasticsearch version**: 5.2

**Description of the problem including expected versus actual behavior**:
When using _client.CatAliases(Names names) to get info about a set of aliases, it doesn't return anything. 

**Steps to reproduce**:
 1. Create multiple Aliases `a_1`, `a_2`
 2. Confirm that they are created using `GET _cat/aliases`
 2. GET `/_cat/aliases/a_1,a_2` or by using nest (`_client.CatAliases("a_1,a_2")`)

**Expected behavior:** 
Return a list of records containing information about the given aliases. 

**Actual:** 
Returns valid request, with blank \ no information (Records count = 0)
 
[Official 5.2 documentation does not say that this should be possible, but the Nest client provides an api for it which again indicates it should. ](https://www.elastic.co/guide/en/elasticsearch/reference/current/cat-alias.html)

**Comment by Mpdreamz** [comment]
That url only takes a **single** alias so it sees `a_1,a_2` as a single entity.

I've opened an issue fixing this in the rest specification in Elasticsearch itself which we use to generate methods.

https://github.com/elastic/elasticsearch/issues/23661

Thanks for reporting!

**Comment by Mpdreamz** [comment]
This is now fixed in `elasticsearch` itself.
