### ISSUE TITLE
Position of query property in request changes aggs results.

### ISSUE THREAD

**Issue by markttech** [elastic/elasticsearch-net#2639]
Nest 5.2.0
ElasticSearch 5.2.1

I am getting different results for aggs when the query property is before or after a term aggs that is using include property with a pattern and reading from an alias that points to two indexes with similar data.

The issue is that the results appear to change depending on where the query property is in the request. This is an issue for me at the moment as I encountered the issue using Nest and haven't found a way to place the query before the aggs property and currently results in doubling the doc counts.

```
put aggstest 
{
    "mappings" : {
        "entity" : {
            "properties" : {
                "genre" : { "type" : "keyword" },
				"group" : {"type": "integer"}
            }
        }
    }
}

put aggstest2
{
    "mappings" : {
        "entity" : {
            "properties" : {
                "genre" : { "type" : "keyword" },
				"group" : {"type": "integer"}
            }
        }
    }
}

post aggstest/entity
{
    "genre":"nonfiction",
	"group":100
}

post aggstest/entity
{
    "genre":"documentary",
	"group":100
}

post aggstest2/entity
{
    "genre":"nonfiction",
	"group":200
}

post aggstest2/entity
{
    "genre":"documentary",
	"group":200
}

post _aliases
{
    "actions" : [
        { "add" : { "index" : "aggstest", "alias" : "aggstestalias" } },
		{ "add" : { "index" : "aggstest2", "alias" : "aggstestalias" } }
    ]
}

post aggstestalias/entity/_search
{
  "size": 0,
  "from": 0,
  "query": {
    "term": {
      "group": "100"
    }
  },
  "aggs": {
    "genres": {
      "terms": {
        "field": "genre",
        "include": {
          "pattern": ".*nonfiction.*"
        }
      }
    }
  }
}
This returns doc_count 1 for nonfiction.

post aggstestalias/entity/_search
{
  "size": 0,
  "from": 0,
  "aggs": {
    "genres": {
      "terms": {
        "field": "genre",
        "include": {
          "pattern": ".*nonfiction.*"
        }
      }
    }
  },
  "query": {
    "term": {
      "group": "100"
    }
  }
}
This returns doc_count 2 for nonfiction.
```

**Comment by gmoskovicz** [comment]
Hi @markttech ,

The order of the parameters or the way that you write the Json cannot change the result, as internally we just parse the Json into objects. We do not care if first comes the aggs or the query. Now, i am not completely sure that this has any type of relationship with NEST itself. Can you please confirm that you observe this without using NEST at all? If so, we might need to close this issue and you can open a new issue in the Elasticsearch main repo.

Thanks!
--Gabriel

**Comment by markttech** [comment]
This can be recreated without using Nest. The provided API commands can recreate the issue.

Thank you for that clarification, I was also under the assumption that the order of the parameters shouldn't matter but I couldn't find evidence of that to be 100% sure.

**Comment by gmoskovicz** [comment]
@markttech Marked as a non-issue as it's not a NEST issue!

Thank you.
