### ISSUE TITLE
Looks like transport port is needed for sniffing. [needs more information]

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#2642]
[From discuss](https://discuss.elastic.co/t/elasticsearch-net-sniffingconnectionpool-requires-open-transport-port/75727/2)

I'm seeing connection failures using Sniffing ConnectionPool1 , where parts of the elasticsearch cluster is only available on the http port, that is - the transport port is closed for these nodes. When limiting the set of cluster nodes to only those with open transport ports, no failed sniffing cluster state errors occur. 
So it seems that there is a requirement for the transport ports to be open, alternatively to set a publish port (which should be open to the client). If this is correct, you might want to add this to the documentation.

```
Elasticsearch.Net.PipelineException: Failed sniffing cluster state. ---> System.AggregateException: One or more errors occurred. ---> Elasticsearch.Net.PipelineException: An error occurred trying to read the response from the specified node.
at Elasticsearch.Net.RequestPipeline.Sniff() in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 340
```

and similar issue:

My cluster is running on https://cloud.elastic.co/ and when I try to connect using the SniffingConnectionPool, I see the following exception:

```
[PipelineException: An error occurred trying to read the response from the specified node.]
Elasticsearch.Net.RequestPipeline.Sniff() in C:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:342

[AggregateException: One or more errors occurred.]

[PipelineException: Failed sniffing cluster state.]
Elasticsearch.Net.RequestPipeline.Sniff() in C:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:357
Elasticsearch.Net.RequestPipeline.SniffOnConnectionFailure() in C:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:317
Elasticsearch.Net.Transport1.Ping(IRequestPipeline pipeline, Node node) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:177
Elasticsearch.Net.Transport1.Request(HttpMethod method, String path, PostData`1 data, IRequestParameters requestParameters) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:69
```

I'm using an Elastic 5.2 cluster and tested with both Nest client 5.0 and 5.2.

**Comment by thollowell** [comment]
Also hitting this. ES 5.2 and Nest client 5.2.
Client will run fine for about an hour, its a cached singleton, then will not work until restart of service.
If i set the cache litfetime down to a few minutes then the new generated clients seem to work.

Exception:

`Elasticsearch.Net.ElasticsearchClientException: Maximum number of retries reached. ---> System.AggregateException: One or more errors occurred. ---> Elasticsearch.Net.PipelineException: Failed sniffing cluster state. ---> System.AggregateException: One or more errors occurred. ---> Elasticsearch.Net.PipelineException: An error occurred trying to read the response from the specified node.
   at Elasticsearch.Net.RequestPipeline.Sniff() in C:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 342
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.RequestPipeline.Sniff() in C:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 357
   at Elasticsearch.Net.RequestPipeline.SniffOnConnectionFailure() in C:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Pipeline\RequestPipeline.cs:line 317
   at Elasticsearch.Net.Transport1.Ping(IRequestPipeline pipeline, Node node) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 176
   at Elasticsearch.Net.Transport1.Request[TReturn](HttpMethod method, String path, PostData1 data, IRequestParameters requestParameters) in C:\code\elasticsearch-net\src\Elasticsearch.Net\Transport\Transport.cs:line 68
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---`

**Comment by Mpdreamz** [comment]
@thollowell your exception is not the same as the original reported issue(s), would you mind opening a new ticket explaining your topology and setup? Are you running against cloud.co? Whats the response/exception `DebugInformation` return, etcetera.

**Comment by Mpdreamz** [comment]
Closing this as can not reproduce, the client will never call the transport ports. @Babadofar if you are able to capture the sniff response that introduces unreachable nodes please let us know 👍

**Comment by srgclr** [comment]
Hi @Mpdreamz 

I'm seeing something that might be related to this?

If I run the following with either elastic down or simulated connection failures (using Fiddler to auto respond with 502) I'll get a PipelineException on the first GetMany. If I start with a working cluster, which succeeds on the first call, and then close the connection or kill elastic before the second call,  it will not throw an exception but return empty list instead.

If I use the low level client I do get an unsuccessful response in the second case which is good but the inconsistency in throwing was causing us to miss exceptions if the access to the cluster becomes unstable.

Do you think this can be improved? 

Thanks

    var serverLocation = "localhost:9200";
    var uri = new Uri("http://" + serverLocation);
    var sniffingConnectionPool = new SniffingConnectionPool(new List<Uri>() { uri });
    var connectionSettings = new ConnectionSettings(sniffingConnectionPool);

    connectionSettings
                    .DisableDirectStreaming()
                    .SniffOnConnectionFault()
                    .SniffLifeSpan(TimeSpan.FromSeconds(300));

    var client = new ElasticClient(connectionSettings);
    var ids = new List<string> { "123" };
    var postData = new Dictionary<string, IEnumerable<string>> { { "ids", ids } };

    var index = "index";
    var type = "type";

    var response1 = client.GetMany<object>(ids, index, type);

    // stop elastic 
    Thread.Sleep(5_000);

    var response2 = client.GetMany<object>(ids, index, type);
