### ISSUE TITLE
Nest default sort order

### ISSUE THREAD

**Issue by rm2k** [elastic/elasticsearch-net#2649]
**NEST/Elasticsearch.Net version**: 5.2.0

**Elasticsearch version**: 5.2.0

**Description of the problem including expected versus actual behavior**:

Does NEST define a default sort order?

I'm sending the same request and after certain number of requests I get a randomized order. The documents have the same `_score = 1` and i didn't specify any sort. This got me worried as i'd like perform to paging on my results.

**Steps to reproduce**:

I had a simple query for test
 
    new BoolQuery {
         Must = new QueryContainer[] { new MatchAllQuery() 
    }

if I run the search for consecutive number of times, I get randomized order.

**Comment by russcam** [comment]
[The default sort order for Elasticsearch is `_score` descending](https://www.elastic.co/guide/en/elasticsearch/guide/current/_sorting.html) which means that documents with equal score may appear in different order on subsequent requests. You can add additional sorting with the client

```c#
client.Search<MyDocument>(s => s
    .Query(q => q
        .MatchAll()
    )
    .Sort(so => so
        .Descending("_score")
        .Ascending("name")
    )
);
```
