### ISSUE TITLE
Refresh property needs to be update to enum

### ISSUE THREAD

**Issue by ejsmith** [elastic/elasticsearch-net#2650]
I've noticed that the following 2 classes have a boolean Refresh property instead of using the Refresh enum:

DeleteByQueryRequest
UpdateByQueryRequest

**Comment by russcam** [comment]
thanks for reporting @ejsmith. They're both `bool` in the rest specs

- [Update by query](https://github.com/elastic/elasticsearch/blob/5.x/rest-api-spec/src/main/resources/rest-api-spec/api/update_by_query.json#L137-L140)
-[Delete by query](https://github.com/elastic/elasticsearch/blob/5.x/rest-api-spec/src/main/resources/rest-api-spec/api/delete_by_query.json#L129-L132)

checking if these should be updated.

**Comment by Mpdreamz** [comment]
https://github.com/elastic/elasticsearch/blob/master/modules/reindex/src/main/java/org/elasticsearch/index/reindex/AbstractBaseReindexRestHandler.java#L94

The spec is correct here, thanks for reporting though @ejsmith 👍

**Comment by ejsmith** [comment]
Ok, thanks for checking and sorry for the trouble.

"Sending the refresh will update all shards in the index being updated when the request completes. This is different than the Index API’s refresh parameter which causes just the shard that received the new data to be indexed."
