### ISSUE TITLE
Deserializing a list

### ISSUE THREAD

**Issue by GaryTurpin** [elastic/elasticsearch-net#2652]
**NEST/Elasticsearch.Net version**:
2.5.2
**Elasticsearch version**:
2.4.4
**Description of the problem including expected versus actual behavior**:
I am having a problem upgrading to the latest version of ES 2.X from ES 1.7 when deserializing my data.  The problem only existing when trying to pull in a List<>.  I know in 1.X I have it setup like the following issue https://github.com/elastic/elasticsearch-net/issues/227 but it doesnt seem to work correctly for me in ES 2.X.  Is there something I am missing?

ESDocument
```
[JsonConverter(typeof(JsonToListConverter<string>))]
public List<string> Foo { get; set; }
```

Getting stuff out of an IHit
```
public ESHit(IHit<ESDocument> hit)
{
    var ListOfFoo = hit.Fields.ValueOf<ESDocument, List<string>>(p => p.Foo);
}
```

> Could not cast or convert from System.String to System.Collections.Generic.List`1[System.String].

**Comment by russcam** [comment]
@GaryTurpin Is the `Foo` field stored separately i.e. `store:true` on the field mapping, or are you wishing to deserialize it from `_source`?

**Comment by GaryTurpin** [comment]
@russcam The field is stored separately.  I found a workaround using:

```
public ESHit(IHit<ESDocument> hit)
{
    var ListOfFoo = hit.Fields.ValuesOf<string>("Foo").ToList();
}
```

If I uses this with lamba notation: 
```
public ESHit(IHit<ESDocument> hit)
{
    var ListOfFoo = hit.Fields.Values<ESDocument, List<string>>(p => p.Foo);
}
```

it will return a List<List<string>> opposed to List<string>.

**Comment by russcam** [comment]
Glad you found the methods that return an array of values 👍 With `.Fields.Values<TDocument, TValue>`, it returns `TValue[]`, so the following should also work

```c#
var ListOfFoo = hit.Fields.Values<ESDocument, string>(p => p.Foo).ToList();
```

I'm going to close this issue.
