### ISSUE TITLE
IndicesCreatePost not working with JSON string

### ISSUE THREAD

**Issue by GaryTurpin** [elastic/elasticsearch-net#2656]
**NEST/Elasticsearch.Net version**:
2.5.2

**Elasticsearch version**:
2.4.4

**Description of the problem including expected versus actual behavior**:
I am upgrading from ES 1.X to ES 2.X and I am having a problem creating an index with mappings/settings from JSON.

In ES 1.X Nest, I would do the following and everything would work perfectly.
```
public bool CreateIndex(string json)
{
  var client = new Nest.ElasticClient(new ConnectionSettings(this.ESIndex.ClusterUri));
  var resp = client.Raw.IndicesCreatePost(this.ESIndex.SyncIndex, json);
  return resp.Success;
}
```

In ES 2.X Nest, I do the following and the mappings/settings never get added to the blank index.
```
public bool CreateIndex<T>(string json) where T : class
{
  var client = new Nest.ElasticClient(this.ESIndex.ClusterUri);
  var body = new PostData<string>(json);
  var resp = client.LowLevel.IndicesCreatePost<T>(this.ESIndex.SyncIndex, body);
  return resp.Success;
}
```

If I look at fiddler, it looks like the only thing in the body of the request is
`{"type":1}`

But, I expect to have the JSON that have for my mappings/settings.  Any idea what I am doing incorrectly so I can make this work?

**Comment by Mpdreamz** [comment]
This is a little confusing but its because of `PostData<string>`

```csharp
  var body = new PostData<object>(json);
var resp = client.LowLevel.IndicesCreatePost<string>("someindex5", body);
```

Will work or just sending json directly as the second argument. 

It happens because that `PostData<string>` gets passed internally to argument taking `PostData<object>` and the implicit operator for `T` kicks in wrapping it.
