### ISSUE TITLE
Sniffing connection pool with attribute awareness

### ISSUE THREAD

**Issue by srgclr** [elastic/elasticsearch-net#2657]
Hi,

We typically setup multiple VMs each with one instance of our .NET API server, one data node and one coordinating node. Then we replicate this on another server on a separate rack.

The existing sniffing connection pool is interesting but instead of round robin, we would like to always use a preferred node (coordinator) and if this fails switch to the next best and so on.

The failover node will be the one that shares the most attributes with the preferred one.

For example say we configure the nodes with attributes like '_server_', '_rack_id_' and '_room_'.

If the preferred node dies, it will select one on the same host, then one on the same server, then rack, then room and so on.

We will implement something like this but wanted to check if this feature would be desired by the community and if that's the case we will fork the project and do it here rather that in our project.

Any thoughts?

Thanks

**Comment by Mpdreamz** [comment]
Hi @srgclr 

We have two things that you could use right now to do this:

[StickyConnectionPool](https://github.com/elastic/elasticsearch-net/pull/1831)

And:

[NodeSelector](https://github.com/elastic/elasticsearch-net/pull/2619) on ConnectionSettings. Look at [this test](https://github.com/elastic/elasticsearch-net/blob/2a4ac8b214df2f109074e983473a4f29fde1c80c/src/Tests/ClientConcepts/ConnectionPooling/Sniffing/RoleDetection.doc.cs#L173) for an example taking node attributes into account.

However the `StickyConnectionPool` does not support reseeding and `NodeSelector` and `Sniff` only runs on `IConnectionPools` that [supports reseeding](https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/ConnectionPool/IConnectionPool.cs#L24).

So we'd need a `StickySniffingConnectionPool`, happy to take a PR for that! We're currently at elasticon so limitted keyboard time is available. If not I can start looking at adding that in in two weeks.

**Comment by Mpdreamz** [comment]
I guess the `stickyness` decider needs to be pluggable too so `CreateView()` returns node in the order you want.

**Comment by srgclr** [comment]
Thanks @Mpdreamz,

We can start soonish but can't promise it will be ready in less than two weeks.

Will keep in touch in case you get to it first.

Cheers

**Comment by srgclr** [comment]
Hi @Mpdreamz,

We've started working on this. Should have something to review soon.

Thanks

**Comment by srgclr** [comment]
We're happy with #2789 
Thanks

**Comment by Mpdreamz** [comment]
Ty for taking the time to report back @srgclr!
