### ISSUE TITLE
Reindex with index creation not working.

### ISSUE THREAD

**Issue by Vdm88** [elastic/elasticsearch-net#2660]
**NEST/Elasticsearch.Net version**: 5.2.0

**Elasticsearch version**: 5.2.2

**Description of the problem including expected versus actual behavior**:
I m trying to reindex from old index to new index with index creation but nothing happens.

```
var reindex = _Instance.Reindex<ILazyDocument>(r => r
                .BackPressureFactor(10)
                .ScrollAll("1m", 2, s => s
                    .Search(ss => ss
                        .Index("OldIndex")
                        .AllTypes()
                    )
                    .MaxDegreeOfParallelism(4)
                )
                .CreateIndex(c => GetIndexDescription(c).Index("NewIndex"))
                .BulkAll(b => b
                    .Index("NewIndex")
                    .Size(100)
                    .MaxDegreeOfParallelism(2)
                    .RefreshOnCompleted()
                )
            );
```

The index description is good, i have created the index using `_Instance.CreateIndex(indexName, c => GetIndexDescription(c));` and the index is generated correctly.

Maybe i m doing something wrong ... 

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by Mpdreamz** [comment]
`Reindex()` returns a cold `IObservable` on which you have to call `.Subscribe()` to kick off everything. 

Can you confirm you do and if so let me know what `OnError` callback gets passed.

**Comment by Vdm88** [comment]
ok so it seems that if i subscribe to `reindex` it's working.
so i have added this to my code

```
var o = new ReindexObserver(onError: (e) => { ex = e; observableWait.Signal(); }, onCompleted: () => observableWait.Signal());
reindex.Subscribe(o);
```
