### ISSUE TITLE
AutoMap() is traversing every property by default

### ISSUE THREAD

**Issue by Cnordbo** [elastic/elasticsearch-net#2661]
**NEST/Elasticsearch.Net version**: 5.2

**Elasticsearch version**: 5.2

**Description of the problem including expected versus actual behavior**:

**Action:** 
Add a simple mapping as per [docs](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/auto-map.html)
```
.Mappings(m => m
                    .Map<mySimpleObject>(map => map
                    .AutoMap()
))
```

**Expected Behavior**
Maps variables to appropriate types with values in index. 

**Actual Behavior**
Goes full-depth on every single object, (strings, ints, anything) mapping properties and their values. 

This causes ES to throw an exception that the type already has the maximum allowed fields (default: 1000)

** Workaround **
use `.AutoMap(0)`
I still needed to explicitly tell it that CultureInfo was of type `Text`, same with a custom object. 

**Steps to reproduce**:

1. Add a simple mapping as per [docs](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/auto-map.html)
```
PutIndexTemplate("MyTemplate", t => t
.Mappings(m => m
                    .Map<mySimpleObject>(map => map
                    .AutoMap()
))
```
 2. Run it towards your ES instance
 3. do a simple _search in Kibana to see results

**Comment by Mpdreamz** [comment]
I think the problem here is that `CultureInfo`expends to a lot of fields.

You can use visitors to make all your `CultureInfo` properties text in Elasticsearch;

```csharp
void Main()
{
	var x = new CreateIndexDescriptor("MyTemplate")
		.Mappings(m => m
		.Map<SimpleObject>(map => map
			.AutoMap(new MyVisitor())
		));
		
	new ElasticClient().Serializer.SerializeToString(x).Dump();
		
}

public class SimpleObject
{
	public double Z { get; set; }
	public CultureInfo X { get; set; }
}


public class MyVisitor : NoopPropertyVisitor
{
	public override IProperty Visit(PropertyInfo propertyInfo, ElasticsearchPropertyAttributeBase attribute)
	{
		if (propertyInfo.PropertyType == typeof(CultureInfo)) return new TextProperty();
		return base.Visit(propertyInfo, attribute);
    }
}
```

yields:

```json
{
  "mappings": {
    "simpleobject": {
      "properties": {
        "z": {
          "type": "double"
        },
        "x": {
          "type": "text"
        }
      }
    }
  }
}
```
