### ISSUE TITLE
BulkUpdateDescriptor<TDocument, TPartialDocument> does not have support for "scripted_upsert"

### ISSUE THREAD

**Issue by bittusarkar** [elastic/elasticsearch-net#2662]
**NEST/Elasticsearch.Net version**: 1.8.0

**Elasticsearch version**: 1.7.4

**Description of the problem including expected versus actual behavior**: While `UpdateDescriptor<TDocument, TPartialDocument>` has support for [`"scripted_upsert"`](https://www.elastic.co/guide/en/elasticsearch/reference/1.7/docs-update.html#_literal_scripted_upsert_literal), `BulkUpdateDescriptor<TDocument, TPartialDocument>` does not or at least I could not figure out a way to use `"scripted_upsert"` in a bulk update request. Looks like it is also missing from the latest version of Nest. I understand that you may not want to fix Nest 1.x but I wanted to confirm the lack/miss of support for `"scripted_upsert"` in Nest 1.8.0 before I go updating Nest code itself to suit for my use.

**Provide `ConnectionSettings` (if relevant)**: n/a

**Provide `DebugInformation` (if relevant)**: n/a

**Comment by Mpdreamz** [comment]
Good catch!
