### ISSUE TITLE
NEST produces minimum_should_match parameter even when there is no should clauses

### ISSUE THREAD

**Issue by rseniuta** [elastic/elasticsearch-net#2663]
**NEST/Elasticsearch.Net version**: 5.2.2

**Elasticsearch version**: 5.2.2

**NEST produces minimum_should_match parameter even when there is no should clauses**:

**Steps to reproduce**:
My code:
```
SearchDescriptor<Product> searchDescriptor =
                this.BuildSearchDescriptor()
                    .Query(q => q
                        .Bool(b => b
                            .Should(
                                this.GetFirstQuery(query.A),
                                this.GetSecondQuery(query.B),
                                this.GetThirdQuery(query.C))
                            .MinimumShouldMatch(MinimumShouldMatch.Fixed(1))
                            .Filter(this.GetFilters(query.D))
                        ));
```
And when query.A, B, and C are null then JSON output looks like this:

```
POST test/test/_search
{
   "query": {
      "bool": {
         "minimum_should_match": 1,
         "filter": [
            {
               "term": {
                  "isDeleted": false
               }
            }
         ]
      }
   }
}
```
Which does not return any documents because of "minimum_should_match": 1.
(This behaviour changed because it worked is Elasticsearch 2.3.3)

NEST should not output "minimum_should_match" parameter when no should clauses exist.

**Comment by Mpdreamz** [comment]
2.x behaved the same way:

```csharp
SearchDescriptor<dynamic> searchDescriptor = new SearchDescriptor<dynamic>()
	.Query(q => q
	      .Bool(b => b
			.MinimumShouldMatch(MinimumShouldMatch.Fixed(1))
			.Filter(m => m.MatchAll())
	));

new ElasticClient().Serializer.SerializeToString(searchDescriptor).Dump();
```

yields 

```json
{
  "query": {
    "bool": {
      "filter": [
        {
          "match_all": {}
        }
      ],
      "minimum_should_match": 1
    }
  }
}
```

A `"query"` is only conditionless if it does not have any clauses or only clauses which themselves are ALL conditionless. 

We won't support optionally sending `minimum_should_match`, you set it we send it.

**Comment by rseniuta** [comment]
Hi, I know it behaved the same in NEST but it changed its behaviour in Elasticsearch 5.
