### ISSUE TITLE
Test Method: Invalid setup on a non-virtual

### ISSUE THREAD

**Issue by carloscosta08** [elastic/elasticsearch-net#2667]
I'm trying to mock the property `InnerHits `from `Hit<T>` class.

`InnerHits `is defined by: `IDictionary<string, InnerHitsResult>` 

Now, the problem is that `InnerHitsResult` does not implement any interface, neither its property `InnerHitsMetaData.Hits`.

And none of this properties have public setters and `Document<T>` is non-virtual in both.

Does InnerHitsResult or InnerHitsMetaData classes should implement interfaces?

If you have an example how to mock those objects it would be great.

**Comment by russcam** [comment]
@carloscosta08 A few questions for you:

1. What version of NEST are you using?
2 .Why do you need to mock `Hit<T>`?

There may be a better way to achieve what you want to do if you can provide more details.

**Comment by carloscosta08** [comment]
Hi, @russcam 

1. Nest, Version=2.4.6
2. I'm trying to develop a unit test and i have to set the object of type:

`IHit<Book> hit`

and then access

`hit.InnerHits["names"].Documents<Name>` property

**Comment by russcam** [comment]
You can provide your own implementation of `IHit<T>` for testing purposes if you need to, but I would question the value of what it is that you are testing within the method i.e. what is the system under test?

Do you want to stub out what `IElasticClient` returns in a given scenario? Something like the following with [Moq](https://github.com/moq/moq)

```c#
void Main()
{
    var people = new List<Person>
    {
        new Person { Id = 1 },
        new Person { Id = 2 },
    };

    var hits = new List<IHit<Person>>
    {
        new Mock<IHit<Person>>().Object
    };

    var mockSearchResponse = new Mock<ISearchResponse<Person>>();
    mockSearchResponse.Setup(x => x.Documents).Returns(people);
    mockSearchResponse.Setup(x => x.Hits).Returns(hits);

    var mockElasticClient = new Mock<IElasticClient>();
    
    mockElasticClient.Setup(x => x
        .Search(It.IsAny<Func<SearchDescriptor<Person>, ISearchRequest>>()))
        .Returns(mockSearchResponse.Object);

    var result = mockElasticClient.Object.Search<Person>(s => s);

    Assert.AreEqual(2, result.Documents.Count());
    Assert.AreEqual(1, result.Hits.Count());
}

public class Person
{
    public int Id { get; set; }
}
```

**Comment by Mpdreamz** [comment]
I strongly believe you should **not** be mocking the response objects of the client. 

You typically have service/repositories/models wrapping the call(s) to elasticsearch. These make for strong mocking candidates in your unit tests.

If you are reusing our types in the return types of these services (which is a very valid usecase) you might run into cases where you can not mock everything.

Closing this but feel free to reply if you feel strongly we should change this.

**Comment by carloscosta08** [comment]
I ran into this solution, by loading a json file during the test initialization:

```
[TestInitialize]
        public void Setup()
        {
            var client = new ElasticClient();
            var jsonContent = Resources.ElasticResponse_FakeHitsList;
            using (Stream stream = new MemoryStream(jsonContent))
            {
                ElasticResponseFakeHitsList = client.Serializer.Deserialize<List<IHit<Product>>>(stream);
            }
        }
```

But in matter of future cases you can think about change those class structures ;)

Thanks
