### ISSUE TITLE
Allow ITransport interface to support custom IPostData

### ISSUE THREAD

**Issue by vikasmestry** [elastic/elasticsearch-net#2668]
**Describe the feature**:

Currently the ITransport interface implementation contains the following method

`public ElasticsearchResponse<TReturn> Request<TReturn>(HttpMethod method, string path, PostData<object> data = null, IRequestParameters requestParameters = null)
			where TReturn : class`

the above method expects an object of PostData, since this PostData is an implementation of IPostData<T> interface, I would like to provide my own implementation for the Write method of this interface & pass my custom PostData implementation for method invocation.

Following is the scenario wherein i would like to customize the PostData implementation

1. I would like to index file (attachment type) which are of size > 1 GB
2. The PostData constructor accepts a parameter of type byte[]
3. The current implementation creates a document in the index with the field name as "WrittenBytes" & the value provided in the byte[] is supplied as the value for this field

I would like to create a document like the following 
```

{
 "myfield" : "someValue",
 "myAttachmentField" : "base64String" --> this would be the byte[] supplied in the PostData constructor
}
```

Please let me know if you require any further information on this.

**Comment by Mpdreamz** [comment]
Pardon the delayed response, we were all travelling back from elasticon these days.


You should not be seeing `WrittenBytes` which makes me think you instantiated an `PostData<byte[]>` the `PostData` data type should really only be used to instantiate `PostData<object>(byte[])` or rely on the implicit conversion of `byte[]`. 

In those cases we'll write the `byte[]` array verbatim to elasticsearch which should do what you want already.

Please let me know if this does not work for you!
