### ISSUE TITLE
PascalCase part of document

### ISSUE THREAD

**Issue by EricKeij** [elastic/elasticsearch-net#2669]
**NEST/Elasticsearch.Net version**: 5.2.0

**Elasticsearch version**: 5.2.0

I need to index a document of which a part needs to be PascalCased. Assume the following:

```
public class MyObject
{
 public int Id {get;set;} 

 [Nested(Name="Child")] 
 public object Child {get;set;}
}
```

Child can contain any kind of data. Child itself is properly pascal cased because of the attribute but I need all sub properties (recursively) pascal cased as well. How can this be done?

**Comment by gmarz** [comment]
You can use [DefaultFieldNameIInferrer on ConnectionSettings](https://github.com/elastic/elasticsearch-net/blob/9710ca5117302220f074e9a5fe7eb1028bbbb9ee/src/Tests/ClientConcepts/HighLevel/Inference/FieldInference.doc.cs#L160) to pass in a lambda that will apply some transformation to all of your fields.

To leave all of the properties as-is, then just do `DefaultFieldNameInferrer(p => p)`.

This however will be applied to all of your types/documents unconditionally.  The only way to apply different property names to multiple types, or partially to a document is to define them using attributes as you are now, or [InferMappingFor<T> and .Rename() on ConnectionSettings](https://github.com/elastic/elasticsearch-net/blob/9710ca5117302220f074e9a5fe7eb1028bbbb9ee/src/Tests/ClientConcepts/HighLevel/Inference/FieldInference.doc.cs#L438), both of which would require you to explicitly map each property manually.

**Comment by EricKeij** [comment]
I tried your suggestions but as said it's not working for me because it's a single type requiring pascal casing and I can't explicitly map the properties because I don't know what object is passed in. I was hoping some customization in json writing could be applied. 

Anyway we'll look for another solution. Thanks for your help.

**Comment by gmarz** [comment]
@EricKeij you might also try using your own visitor with `AutoMap()`.  See [the docs here](https://www.elastic.co/guide/en/elasticsearch/client/net-api/5.x/auto-map.html#applying-conventions-through-the-visitor-pattern).

**Comment by Mpdreamz** [comment]
There are not toggles for this in the client itself, were it a dictionary you could have a peek at reusing our [`VerbatimDictionaryKeysJsonConverter`](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/CommonAbstractions/SerializationBehavior/GenericJsonConverters/VerbatimDictionaryKeysConverter.cs).

You would need to write your own custom json serializer here. Let us know if you hit any walls!

**Comment by EricKeij** [comment]
Thanks for the suggestion. We ended up reindexing our data to get rid of the pascal cased legacy :)

**Comment by Mpdreamz** [comment]
Haha awesome, even better! 👍
