### ISSUE TITLE
Update a document field

### ISSUE THREAD

**Issue by cesar2** [elastic/elasticsearch-net#2677]
**NEST/Elasticsearch.Net version**: 5.0

**Elasticsearch version**: 5.0

**Description of the problem including expected versus actual behavior**:

I am trying to modify a document field in ES.

**Steps to reproduce**:
 1. I get a document that I want to change.
 2. I do a Update operation with a inline script.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Describe the feature**: That is my code to try to update the document "tempRegistrado" of type **temp**. I want to change the field "evaluado". I want set it to 100: 

```
client.Update<temp>(tempRegistrado,u => u
            .Type("temp")
            .Script(cs => cs.Inline("ctx._source.evaluado = evaluado").Params(p => p.Add("evaluado", 100)))
            .RetryOnConflict(3)
            .Refresh(Refresh.True)
        );
```

And I get an error saying that evaluado variable is not defined:

`# ServerError: ServerError: 400Type: illegal_argument_exception Reason: "failed to execute script" CausedBy: "Type: script_exception Reason: "compile error" CausedBy: "Type: illegal_argument_exception Reason: "Variable [evaluado] is not defined."""`

And, in the mapping, you can see that this field exists, in the **documentos0** index:

```
{
  "documentos0": {
    "mappings": {
      "temp": {
        "properties": {
          "$id": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "bloqueado": {
            "type": "long"
          },
          "evaluado": {
            "type": "long"
          },
          "id": {
            "type": "long"
          },
          "idHiperTextoOrigen": {
            "type": "long"
          },
          "idServidor": {
            "type": "long"
          },
          "timeout": {
            "type": "long"
          },
          "url": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "urlProtocolo": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "urlPuerto": {
            "type": "long"
          },
          "urlRuta": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          }
        }
      }
    }
  }
}
```

Any idea of how update a field of a document? Thanks.

**Comment by cesar2** [comment]
I used this page to solve my problem: 

http://stackoverflow.com/questions/35630189/how-to-update-an-elasticsearch-document-in-nest2

My solution it was: 

```
var updateResponse = client.Update<temp, temp2>((int)tempRegistrado.id, descriptor => descriptor
        .Doc(new temp2
        {
            evaluado = 100
        }));
```

**Comment by russcam** [comment]
Glad you found an answer 👍 

The default scripting language is [Painless](https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting-painless.html) is 5.x so an inline update looks like

```c#
client.Update<temp>(tempRegistrado,u => u
            .Type("temp")
            .Script(cs => cs
                .Inline("ctx._source.evaluado = params.evaluado") // prefix with params
                .Params(p => p.Add("evaluado", 100)))
            .RetryOnConflict(3)
            .Refresh(Refresh.True)
        );
```

You can also send in a partial document as you have done; you can use an anonymous type to represent the partial document too.
