### ISSUE TITLE
Sort on multiple fields doesn't work

### ISSUE THREAD

**Issue by SLavrynenko** [elastic/elasticsearch-net#2686]
"version" : {
"number" : "2.4.4",
"build_hash" : "fcbb46dfd45562a9cf00c604b30849a6dec6b017",
"build_timestamp" : "2017-01-03T11:33:16Z",
"build_snapshot" : false,
"lucene_version" : "5.5.2"
},

NEST version 2.4.6

I've the following code:

response = client.Search(
s => s.Query(
q => GetQueryContainer(q))
.Index(Settings.IndexName)
.Source(sfd => SourceSelector(sfd))
.From(fromRow)
.Size(pageSize)
.Sort(s1 => s1.Field("Firstname", SortOrder.Descending))
.Sort(s1 => s1.Field("Lastname", SortOrder.Descending))
);

and as I see in the logs I have sort on the field that is used in the last Sort method. If I add the new Sort method in a chain I will get sorting on that field and not on all of them:

Request that code above is provided:
{"from":0,"size":20,"sort":[{"Lastname":{"order":"desc"}}],"_source":{"include":["Firstname","Lastname"],"exclude":[]},"query":{...}}

At debugger in MS Visual Studio I see that internal Sort collection has only 1 item after each call of Sort method. So it doesnt add anything to a collection - just rewrite the only 1 item every time.

**Comment by SLavrynenko** [comment]
From the source code I see following:

///<summary>
		///A comma-separated list of fields to return as the field data representation of a field for each hit
		///</summary>
		public SearchDescriptor<T> Sort(Func<SortDescriptor<T>, IPromise<IList<ISort>>> selector) => Assign(a => a.Sort = selector?.Invoke(new SortDescriptor<T>())?.Value);

so, a.Sort = selector?.Invoke(..) and not a.Sort.Add(...) - is it ok?

**Comment by russcam** [comment]
It's correct @SLavrynenko; To sort on multiple fields in NEST 2.x+ is

```c#
var searchResponse = client.Search<object>(s => s
    .Query(q => q
        .MatchAll()
    )
    .Sort(s1 => s1
        .Field("Firstname", Nest.SortOrder.Descending)
        .Field("Lastname", Nest.SortOrder.Descending)
    )
);
```

All sort expressions should be inside the one `.Sort(Func<SortDescriptor<T>, IPromise<IList<ISort>>> selector)`; the NEST structure was [changed in 2.x to better represent the structure in the Elasticsearch query DSL](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/nest-breaking-changes.html#_isolated_descriptors).

**Comment by whittssg** [comment]
@russcam Is there a way to provide a list to .Sort? a bit like you can for Filter? I have checked everywhere and I cant seem to find anyway to do it apart from if i use Object Initalizer.

I thought something like this would work:

```
var testSort = new List<ISort>();
foreach (var option in mySortList)
{
testSort.Add(new FieldSort { Field = option.Key, Order = option.SortOrder == "ASC" ? SortOrder.Ascending : SortOrder.Descending });
} 
.Sort(testSort)
```

Thanks
