### ISSUE TITLE
Error when trying to set MaxThreadCount on the merge scheduler 

### ISSUE THREAD

**Issue by whittssg** [elastic/elasticsearch-net#2690]
**NEST/Elasticsearch.Net version**: 5.2.0

**Elasticsearch version**: 5.2.0

**Description of the problem including expected versus actual behavior**:

I am trying to set the the max thread count on one of my indexes via c#. I use the following code:

```
 client.CreateIndex(indexInfo.Value, c => c
                        .Settings(st => st
                            .Merge(mr => mr
                                .Scheduler(sc => sc.MaxThreadCount(1)))));
```

But i get this error: 
An unhandled exception of type 'Elasticsearch.Net.UnexpectedElasticsearchClientException' occurred in Elasticsearch.Net.dll
Additional information: Object reference not set to an instance of an object.

The index is created fine if i remove the merge setting. I am setting this since i found out that it is recommended when running elastic on spinning disks.

Thanks,

**Comment by whittssg** [comment]
Adding an empty policy setting fixes it. Is this normal?
```
.Merge(mr => mr
 .Scheduler(sc => sc
    .MaxThreadCount(1))
 .Policy(po => po))
```

**Comment by gmarz** [comment]
> Is this normal?

Nope, definitely looks like a bug.  We'll have this fixed for the next release.  Thanks for reporting!
