### ISSUE TITLE
How do I search multiple nodes by searching for keywords 

### ISSUE THREAD

**Issue by sjllef** [elastic/elasticsearch-net#2698]
**I can set the search node by**
//Request multiple nodes
`var manyStrings = Nest.Indices.Index("db_studnet", "db_other_student");
var manyTypes = Nest.Indices.Index<Student>().And<OtherStudent>();`

**But I can only retrieve a type operation**
`var result = client.Search<Student>(s => s.Index("db_test"));`
**This example can only be achieved on the "Student" query** 

How do I achieve the same as the following post request to get multi node multi type search
`POST /db_egov/_search
{
   "query": {
      "query_string": {
         "query": "jack"
      }
   }
}`

**How to achieve through API, thank you!**

**Comment by russcam** [comment]
hey @sjllef, GitHub is reserved for bug reports and feature requests. 

The best place to ask a general question is at the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch
