### ISSUE TITLE
Substring function with Inline Script

### ISSUE THREAD

**Issue by cesar2** [elastic/elasticsearch-net#2703]
**NEST/Elasticsearch.Net version**: 5.0.0

**Elasticsearch version**: 5.0.0

**Description of the problem including expected versus actual behavior**:

I am trying to get a **subtring of a document field** and compare it with a string. I am doing this with URLs, so, for example, I wanna check if the server part of a document url field is equal to a specific aplication on my intranet.

For example, if my document has the url field "/ExampleofAplication/folder1/document1.doc"

`length = ("/ExampleofAplication").Length();`

I wanna get it if:    doc['url'].value.substring(1, length) == ExampleofAplication

**Steps to reproduce**:
 1. I have tried on Kibana but it does not work:

```
GET myIndex/MyType/_search
{
  "script_fields": {
    "example": {
      "script": {
        "lang":   "expression",
        "inline": "doc['url'].value.substring(1,20) == ExampleofAplication"
      }
    }
  }
}
```

I have tried also with doc['url'].substrin(1,20)...

And both get me this error:
Unrecognized function call (doc['urlRuta'].substring

**Provide `ConnectionSettings` (if relevant)**:
url is keyword:
```
.Keyword(st => st
         .Name(na => na.url)
          .IgnoreAbove(1024)
 )

```

**Provide `DebugInformation` (if relevant)**:

**Describe the feature**:

**Comment by KodrAus** [comment]
Is this something you could use a [Path Hierarchy Tokenizer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-pathhierarchy-tokenizer.html) for rather than manually slicing the field with a script?

**Comment by Mpdreamz** [comment]
Hi Cesar,

Please open questions that are not directly related to the .NET client on https://discuss.elastic.co/. 

I think you need to access `doc['url.keyword'].value` or setup `url` as not analyzed to access to original string this way. See also: https://www.elastic.co/guide/en/elasticsearch/reference/master/modules-scripting-fields.html

@KodrAus suggestion of the Path Hierarchy Tokenizer is going to yield the fastest solution so definitely explore that option!
