### ISSUE TITLE
Change from IndicesGetAliasesForAll to IndicesGetAliasForAll is not documented

### ISSUE THREAD

**Issue by seang-es** [elastic/elasticsearch-net#2704]
We had some confusion when IndicesGetAliasesForAll was removed from the code.  The removal was included as a breaking change, but no reference is made to using IndicesGetAliasForAll in its place.

**Comment by Mpdreamz** [comment]
This got removed as per: https://github.com/elastic/elasticsearch/pull/13906

Its a breaking change in 5.0 but long deprecated since 1.0.

**Comment by Mpdreamz** [comment]
Closing this since the highlevel client method change is documented and is part of a greater documented breaking change in Elasticsearch.
