### ISSUE TITLE
Performance degredation with v2.5.2 and JSON serialization after upgrade from 1.6

### ISSUE THREAD

**Issue by aaron-horst** [elastic/elasticsearch-net#2705]
**NEST/Elasticsearch.Net version**: 2.5.2

**Elasticsearch version**: 2.4.4

**Description of the problem including expected versus actual behavior**:

After upgrading from 1.6 we are seeing significant performance degradation with the JSON serialization logic. It appears as though the client serializer may have been static in version 1 however it is not now perhaps. Timings around serialization are up from about 3ms on average with v1.x to about 300ms with v2.x.

I have seen a few issues around this but none have called out a solution that I could discern. Note that establishing a lazy singleton for connection settings appears to correct this with only the initializer incurring the larger performance hit but wanted to see if (1) this is the correct solution and (2) if a shared connection setting object (example below) may be considered thread safe.

Example of shared connection setting:
private static Lazy<ConnectionSettings> connectionSettings = new Lazy<ConnectionSettings>(() =>
        {
            var uri = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
            var esSettings = new ConnectionSettings(uri).DefaultIndex("myIndexName"); 
            return esSettings;
        }); 

**Steps to reproduce**:
 1. Nest query containing aggs, filters, etc.
 2. Call to search or client.Serializer.SerializeToBytes (settings below)
 3. Review of timings around calls to NEST in comparison with response time from ES

**Provide `ConnectionSettings` (if relevant)**:

var settings = new Nest.ConnectionSettings();
            if (forceLowercasePropertyNames)
            {
                settings.DefaultFieldNameInferrer(x => x.ToLower());                
            }
            var client = new Nest.ElasticClient(settings);
            return client.Serializer.SerializeToBytes(o);

![2017-04-06_20-21-31](https://cloud.githubusercontent.com/assets/5679562/24810664/1b493c6a-1b91-11e7-9589-d228664bcf3e.png)

**Comment by Mpdreamz** [comment]
Hi!

All of our AND json.net caches are per `ConnectionSettings` and your absolutely encouraged to share a single instance of it over multiple clients and that should be totally thread safe to do so.

The first call will typically incur overhead while these caches are built.

Our [Lifetimes documentation](https://www.elastic.co/guide/en/elasticsearch/client/net-api/2.x/lifetimes.html) goes into this as well.

Let me know if this answers your question or if I missed anything and closed this too soon!
