### ISSUE TITLE
ReindexOnServerAsync error still returns true for IsValid

### ISSUE THREAD

**Issue by ejsmith** [elastic/elasticsearch-net#2719]
**NEST/Elasticsearch.Net version**: 5.3.0

**Elasticsearch version**: 5.3.0

**Description of the problem including expected versus actual behavior**:

When calling ReindexOnServerAsync the IsValid on response still returns true when the server returned a 500 http status code.

**Steps to reproduce**:
 1. Call ReindexOnServerAsync with an invalid painless script.

**Comment by Mpdreamz** [comment]
Thanks for reporting this @ejsmith! 

I opened https://github.com/elastic/elasticsearch-net/pull/2735 to fix this and explain why this mistake creeped into the client there as well.

**Comment by Mpdreamz** [comment]
closed by https://github.com/elastic/elasticsearch-net/pull/2735
