### ISSUE TITLE
A possible bug: marking a property as not analyzed doesn't work

### ISSUE THREAD

**Issue by mu-soliman** [elastic/elasticsearch-net#272]
I create mapping using attributes. I mark a property as not analyzed by adding the following attribute:
[ElasticProperty (Index = FieldIndexOption.not_analyzed)]

All term queries that search for exact phrase against the given property return zero result. 

I suspected that the mapping doesn't work, so I looked at the mapping by sending an http request to elasticsearch. I found that the returned mapping doesn't mention the property as not_analyzed.

**Comment by skshandilya** [comment]
Hello I have a small question with regards to this
I changed the dynamic template from analyzed to not_analyzed
I realized that this was a mistake and changed back to analyzed.
but the new data is still being indexed as not_analyzed why?
I have at least 5 to 6 types in the data after deleting a type the behaviour was correct but the next day (the first level of indexing happens by date)
Here is a snippet of default template
  "template" : "logstash-*",
  "settings" : {
    "index.refresh_interval" : "5s"
  },
  "mappings" : {
    "_default_" : {
       "_all" : {"enabled" : true},
       "dynamic_templates" : [ {
         "string_fields" : {
           "match" : "*",
           "match_mapping_type" : "string",
           "mapping" : {
             "type" : "string", "index" : "analyzed", "omit_norms" : true,
               "fields" : {
                 "raw" : {"type": "string", "index" : "not_analyzed", "ignore_above" : 256}
               }
           }
         }
       } ],
should I just go ahead and remove the "index": "analyzed" or it does not matter if it is there?
