### ISSUE TITLE
Legacy `string` field's `fielddata` attribute parsing issue

### ISSUE THREAD

**Issue by astefan** [elastic/elasticsearch-net#2721]
**NEST/Elasticsearch.Net version**: 5.x

**Elasticsearch version**: 5.x

**Description of the problem including expected versus actual behavior**:

Upon 2.x to 5.x upgrade, Elasticsearch will also upgrade the existent indices mappings. One change is to add `"fielddata": false` to any `not_analyzed` `string` fields. And these new mappings seem to break the mappings serialization:
```
Unexpected initial token 'Boolean' when populating object. Expected JSON object or array. Path 'fielddata', line 1, position 368.
```

**Comment by russcam** [comment]
Thanks for submitting @astefan; I've opened PR #2728 with a fix

**Comment by russcam** [comment]
Merged in PR; this'll be in the next release on Nuget 👍
