### ISSUE TITLE
Nest 5.x performance issue.

### ISSUE THREAD

**Issue by Vdm88** [elastic/elasticsearch-net#2723]
**NEST/Elasticsearch.Net version**: 5.3.1

**Elasticsearch version**: 5.2.2

**Description of the problem including expected versus actual behavior**:
So we have built one APi with .net and NEST. We have ~ 2 mil queries per day. After we updated to es5.x from 1.7.2 we had some issues with performance. So i have added timers that i log to check what is taking most of the time when we do a search. It looks like the 

**Steps to reproduce**:
 ```
           var watch = Stopwatch.StartNew();
            var result = _EsClient.Search<Residential>(q => q
                .Index(_residentialIndex + countryCode.ToLower())
                .Type("residential")
                .ExecuteOnLocalShard()
                .Query(qq =>
                {
                    QueryContainer phoneContainer = null;

                    QueryContainer publicationFlagQuery = qq.Bool(b => b.MustNot(
                                            n => n.Term(t => t.Field("publicationFlag").Value("0")),
                                            n => n.Term(t => t.Field("infobelWebPublicationFlag").Value("0"))
                                            ));

                    phoneContainer = qq.Term(t => t.SourceDisplayPhone, phone);

                    return publicationFlagQuery && phoneContainer;
                })
                 .Sort(sort => sort.Descending(SortSpecialField.Score))
                 .Take(1)
                );
            watch.Stop();
```
So i measure the time to execute the search + i check the result.Took time ( guess this is the time ElasticSearch needs to respond )

So i execute same query multiple times and i get something like this

Total time = 103 -> result.Took = 2. So each time i do a search i waste more than 100 ms just to serialize/deserialize.
Is this normal ?

**Provide `ConnectionSettings` (if relevant)**:
We have ElasticClient as Singletone so we don't create one instance for each search. 
APi and elastic server are on the same location

**Comment by Vdm88** [comment]
I have updated the query and added a filter query for the flags, but speed seems the same.
`var phoneResult = _EsClient.Search<Residential>(q => q
                .Index(index)
                .Type(residentialType)
                .ExecuteOnLocalShard()
                .Query(qq => qq
                    .Bool(b => b
                        .Must(s => s.Term(n => n.SourceDisplayPhone, phone))
                        .Filter(f => f.Bool(bb => bb
                                    .MustNot(
                                        n => n.Term(t => t.Field("publicationFlag").Value("0")),
                                        n => n.Term(t => t.Field("infobelWebPublicationFlag").Value("0")))
                                  ))
                        ))))
                 .Take(1)
                );`

**Comment by GaryTurpin** [comment]
I just went through this last week.  They changed their approach in nest 2.0.  You will need to use singletons and just reuse the client.  [https://www.elastic.co/guide/en/elasticsearch/client/net-api/5.x/lifetimes.html](https://www.elastic.co/guide/en/elasticsearch/client/net-api/5.x/lifetimes.html)

**Comment by Vdm88** [comment]
thx for the answer  but i already did that. The _EsClient is a singletone. I wrote this from the begining. We had big issues with RAM before we implemented the singletone.
```
        private static ElasticClient _EsClient;
        #region Singleton
        private static readonly object __lock = new object();
        private static volatile ElasticSearchManager _instance;
        public static ElasticSearchManager Instance
        {
            get
            {
                if (_instance == null)
                {
                    lock (__lock)
                    {
                        if (_instance == null)
                        {
                            _instance = new ElasticSearchManager();
                        }
                    }
                }

                return _instance;
            }
        }

        private ElasticSearchManager()
        {
            var elasticSearchURI = ConfigurationManager.AppSettings["elasticSearchURI"];

            var connectionPool = new SingleNodeConnectionPool(new Uri(elasticSearchURI));
            var config = new ConnectionSettings(connectionPool)
                                    .SniffOnConnectionFault(false)
                                    .SniffOnStartup(false)
                                    .RequestTimeout(TimeSpan.FromMilliseconds(60000))
                                    .MaximumRetries(3)
                                    .DisablePing();

            _EsClient = new ElasticClient(config);
        }
```
We have 4 nodes 64 gb ram, and a LB in front.

**Comment by Vdm88** [comment]
Even worst, we have logged times bigger than 20 seconds, and the result.Took from the response is only 4 ms.

**Comment by stumpyfr** [comment]
Question: are you on linux?
It's look like we have the same performance problem when the code is running directly on the linux server who host the ES node.
But when we run the same code from a windows machine who connects to the ES node, no problem at all.

**Comment by Vdm88** [comment]
No, the application is .net hosted in iis. 2 machines with load balancer in front.

**Comment by Vdm88** [comment]
We upgraded the Es to 5.3. Nothing new ...

**Comment by Mpdreamz** [comment]
@Vdm88 I'm currently on vacation so pardon the late reply. There is definitely a serialization overhead but should not be that high (100+ ms).

`.Took` does not take network into account either although that typically does not run into the 10s of ms either.

The `20s` seems insanely high which makes me think it might be a networking issue. With a `SingleNodeConnection` the client [will never retry](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/retries.html).

Are you able to run with `EnableDebugMode()` and capture the request/response and share your `Residence` class with us? (privately also possible by emailing `microsoft AT elastic.co`. This would be the quickest way for us to dive in.

@stumpyfr mind opening a new issue with your findings? We run our unit tests on linux continuously but not our integration tests.

**Comment by Vdm88** [comment]
So the `Residential` class is this. It's small

```
public class Residential
    {
        public string SourceDisplayName { get; set; }
        public string FullAddress { get; set; }
        public string FirstName1 { get; set; }
        public string CityName { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string SourceDisplayPhone { get; set; }
    }
```

And debug info 
```
237-147-->Valid NEST response built from a successful low level call on POST: /wpuniversalcallerid_fr/residentialcallerid/_search?preference=_local
# Audit trail of this API call:
 - [1] HealthyResponse: Node: http://10.200.11.43:9200/ Took: 00:00:00.2379859
# Request:
{
  "size": 1,
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "sourceDisplayPhone": {
              "value": "0134477540"
            }
          }
        }
      ],
      "filter": [
        {
          "bool": {
            "must_not": [
              {
                "term": {
                  "publicationFlag": {
                    "value": "0"
                  }
                }
              },
              {
                "term": {
                  "infobelWebPublicationFlag": {
                    "value": "0"
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}
# Response:
{"took":147,"timed_out":false,"_shards":{"total":10,"successful":10,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}
```
Where 147 is resp took and 237 is time to execute the search method.

**Comment by Vdm88** [comment]
Creation for this index :

```
EsClient.CreateIndex(indexName, c => c
                            .Settings(s => s
                                .NumberOfReplicas(0)
                                .NumberOfShards(shardsNr)
                                .RefreshInterval(-1)
                                .Setting("index.search.slowlog.threshold.query.warn", "15s")
                                .Setting("index.search.slowlog.threshold.fetch.warn", "15s")
                                .Analysis(descriptor => descriptor
                                    .Analyzers(bases => bases
                                        .Custom("trimmed_number", cus => cus
                                            .CharFilters(new List<string> { "drop_chars" })
                                            .Filters(new List<string>() { "lowercase" })
                                            .Tokenizer("standard")
                                        )
                                    )      
                                    .CharFilters(ch => ch
                                        .PatternReplace("drop_chars", p => p
                                            .Pattern(@"[^0-9]")
                                            .Replacement("")
                                        )
                                    )
                                )
                            )
                            .Mappings(mp => mp
                                .Map<Residential>(m => m
                                    .Properties(props => props
                                        .Keyword(s => s.Name(t => t.PublicationFlag))
                                        .Keyword(s => s.Name(t => t.InfobelWebPublicationFlag))
                                        .Text(s => s.Name(t => t.SourceDisplayPhone).Analyzer("trimmed_number"))
                                        .Keyword(s => s.Name(t => t.PhoneRange))
                                    )
                                )
                    ));
```

**Comment by russcam** [comment]
@Vdm88 as @Mpdreamz said, 20 seconds seems like an unusually large amount of time. 

Isolating NEST from the timing of Elasticsearch and the network would be good to see. For example,

1. [What does fiddler show](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/logging-with-fiddler.html) for the request in regards to timings?
2. Issuing a request from the same machine using something like [Fiddler's](http://www.telerik.com/fiddler) composer, do you see the same latency?
3. Does [Network tracing](https://msdn.microsoft.com/en-us/library/ty48b824.aspx) provide any further insight?
4. Building a [benchmarking test harness with BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) that uses `InMemoryConnection` in conjunction with a stubbed response, how does NEST 5.3.1 compare to 1.7.2? [I've built a similar comparison before comparing NEST 1.8.2 to NEST 2.5.0](https://github.com/elastic/elasticsearch-net/issues/1899#issuecomment-264395183), so if you wanted to email the response JSON to the address @Mpdreamz's mentioned above, I can run the comparison for you.

**Comment by Vdm88** [comment]
@russcam the problem is not per 1 issue the thing is that from time to time we have very bad responses. Before we changed to es 5.x we had no issue and we know that because we log every search made on the APi + response time. The environment is the same.  
I generated one console app and executed just the search method, to isolate it from the APi. I logged the time to execute the search and the time response.took. From time to time they are bad ( over 300 ms ). The index is not refreshed by any other process (update, insert, delete).

1. The fiddler shows same bad speed. Simple search like the one above from time to time resp.Took is bigger than 300 ms even 1000 ms.
2. Tried with the composer, same stuff happening.
3. What to capture from here ?
4. I can not test anymore the difference between the NEST 1.8.2 and 5.3.1 because we don't have the old server anymore.

**Comment by russcam** [comment]
@Vdm88 do you have any kind of monitoring on the cluster that you can correlate with the point at which you get slow requests?

**Comment by Vdm88** [comment]
@russcam  the cluster is not stressed. I can monitor somehow with Cerebro. In general the cpu usage on each node is under 10% and load  is max 4. Don't really know how correct are the values from Cerebro.

**Comment by russcam** [comment]
I'm not familiar with Cerebro; suspect it's getting data from Elasticsearch APIs.

Do you have metrics on search thread pool, heap size, etc? What you've described doesn't sound like a NEST/client issue, but perhaps an issue with the cluster.

What are you running Elasticsearch on (OS, JDK)? Did you upgrade cluster from a previous version? Did you restore indices from a previous version?

**Comment by Vdm88** [comment]
I don't handle the Es server. From what i know it is JDK and when we updated from 1.7.2 to 5.2.0 we did a clean install. So we re-indexed all.
We have 4 nodes like with: 64GB RAM, Xeon E5-4640 x4 sockets
The heap betweend 50-70%


Ubuntu 14.04LTS
JVM 1.8.0.121 
ES 5.3.0

**Comment by Mpdreamz** [comment]
I've added a reproduce test for this issue here: https://github.com/elastic/elasticsearch-net/commit/abcf24ec439e0c1de4e1a7daa912e8f20ebde9b8#diff-e907d746734356566298f4568d690736

To rule out serialization alone taking 10s of milliseconds. The median (and max) serialization is well below `3ms`.

Not discarding your issue but with the same thing happening in Fiddler's `composer` it definitely looks to be a network latency issue rather than a client issue.

Fiddler also has a Statistics tab which could present more clues in the delay e.g


```
Request Count:   1
Bytes Sent:      617		(headers:617; body:0)
Bytes Received:  415		(headers:382; body:33)

ACTUAL PERFORMANCE
--------------
ClientConnected:	14:06:16.969
ClientBeginRequest:	14:06:16.970
GotRequestHeaders:	14:06:16.970
ClientDoneRequest:	14:06:16.970
Determine Gateway:	0ms
DNS Lookup: 		6ms
TCP/IP Connect:	2ms
HTTPS Handshake:	0ms
ServerConnected:	14:06:16.979
FiddlerBeginRequest:	14:06:16.979
ServerGotRequest:	14:06:16.979
ServerBeginResponse:	14:06:16.981
GotResponseHeaders:	14:06:16.981
ServerDoneResponse:	14:06:16.981
ClientBeginResponse:	14:06:16.981
ClientDoneResponse:	14:06:16.981

	Overall Elapsed:	0:00:00.011
```

Closing this issue but please keep us posted, we're not disengaging 👍

**Comment by labsilva** [comment]
I've had the same (or a very similar problem) while running an ASP.NET Core application on Kubernetes while using `aspnetcore:2.0.4` image.

Most of the times my ES requests would be fast (less than 100ms), but periodically a few requests would take much more time (more than 800ms); information from ES said that it took a few millis, but result from audit trail indicated a much higher timing.

After three weeks researching (trial and error mostly...), I've been able to solve this problem by switching to the `aspnetcore:2.0.4-jessie` image and publishing specifically for `debian 8 jessie` runtime:
`dotnet publish --self-contained -r debian.8-x64`.

Posting this here in case it helps anyone having the same problem.
