### ISSUE TITLE
Could not load data using ElasticClient after installing x-pack

### ISSUE THREAD

**Issue by chulicaoli** [elastic/elasticsearch-net#2724]
**NEST/Elasticsearch.Net version**:2.0.0.0

**Elasticsearch version**:5.3.0

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Could not load data using ElasticClient after installing x-pack

**Provide `ConnectionSettings` (if relevant)**:
var settings = new ConnectionSettings(new Uri(ESServer)).DefaultIndex("formattest");

**Provide `DebugInformation` (if relevant)**: No error information.

**Describe the feature**:Could not load data using ElasticClient after installing x-pack
before installing x-pack, I could use the ConnectionSettings to load data into ES.
I think it may duo to authentication issue, could you please provide sample to show how to walk-around?

**Comment by Mpdreamz** [comment]
"Could not load data" seems very vague thing to report. If you can not connect let us know the exception or `response.DebugInformation` so we have something to go from 😄 

if you use x-pack security you could not be able to connect for a variety of reasons:

* Basic auth might need to be set on `ConnectionSettings` https://www.elastic.co/guide/en/elasticsearch/client/net-api/5.x/configuration-options.html

* `EsServer` might need to be `https` ?

* Using PKI authentication? there are some docs for that! https://www.elastic.co/guide/en/elasticsearch/client/net-api/5.x/working-with-certificates.html#_client_certificates

Hope the above gets you unblocked.
