### ISSUE TITLE
DeleteByQueryResponse.IsValid is true when request failed

### ISSUE THREAD

**Issue by blachniet** [elastic/elasticsearch-net#2725]
**NEST/Elasticsearch.Net version**: 5.3.1

**Elasticsearch version**: 5.2.2

**Description of the problem including expected versus actual behavior**:

`DeleteByQueryResponse.IsValid` is `true` when the request fails. For example, if you create the ElasticClient with URLs to in-existent nodes, `DeleteByQueryResponse.OriginalException` will be something like "Maximum number of retries reached." or "Unable to connect to remote server". However, `DeleteByQueryResponse.IsValid` is `true`. In this situation, I expect `DeleteByQueryResponse.IsValid` to be `false`

**Steps to reproduce**:
 1. Create an ElasticClient with URLs to nonexistent nodes.
 2. Perform a delete by query request.

Expect: `DeleteByQueryResponse.IsValid = false`
Actual: `DeleteByQueryResponse.IsValid = true`

**Comment by Mpdreamz** [comment]
Thanks for reporting this @blachniet! 

I opened https://github.com/elastic/elasticsearch-net/pull/2735 to fix this and explain why this mistake creeped into the client there as well.

**Comment by Mpdreamz** [comment]
closed by https://github.com/elastic/elasticsearch-net/pull/2735

Thanks again @blachniet 👍
