### ISSUE TITLE
NEST cproj cannot open

### ISSUE THREAD

**Issue by DeepSeaWolf** [elastic/elasticsearch-net#2726]
Hi, 
I am new to NEST. I downloaded the ealsticsearch-net-master.rar file and unzipped it. But when I tried to open the Elasticsearch.sln with VS 2015, several projects cannot open. Error is related to project file format. Something like 'The default XML namespace of the project must be MSbuild XML namespace..'. Should I open it with newer VS?

Thanks

**NEST/Elasticsearch.Net version**:

**Elasticsearch version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Describe the feature**:

**Comment by russcam** [comment]
Hi @DeepSeaWolf, the project has been ported over to the new csproj format. Consequently, it cannot be opened in Visual Studio 2015 but will work in Visual Studio 2017.
