### ISSUE TITLE
Document Search Template API usage

### ISSUE THREAD

**Issue by joshuar** [elastic/elasticsearch-net#2729]
Currently NEST has support for the Search Template API (see tests [here](https://github.com/elastic/elasticsearch-net/tree/master/src/Tests/Search/SearchTemplate) but doesn't have any documentation for them.  Would be useful to document this API given the the current deprecation of the Template Query in Elasticsearch (the spiritual predecessor of Search Template).

**Comment by Mpdreamz** [comment]
@joshuar agreed! we have an open ticket to automatically generate documentation from all `*ApiTests.cs` and `*CrudTests.cs` files. Everything is in place for it we just need to manually verify the output before adding 100+ new documentation pages 😄 

Closing this in favour of the other ticket #2248

**Comment by russcam** [comment]
Added a check box to #2248 for this one; I think it's a good candidate for a more detailed page demonstrating serializing request and adding as template

**Comment by Mpdreamz** [comment]
Agreed although the `CrudTest` should/would provide such a walkthrough.
