### ISSUE TITLE
Warning: Deprecated field [pattern] used, replaced by [Put patterns directly under the [include] or [exclude]]

### ISSUE THREAD

**Issue by giocaputo** [elastic/elasticsearch-net#2732]
**NEST/Elasticsearch.Net version**:5.2.0

**Elasticsearch version**:5.2.0

**Steps to reproduce**:
Using TermsAggregationDescriptor<T> Include(string includePattern, null)
I have this warning
Deprecated field [pattern] used, replaced by [Put patterns directly under the [include] or [exclude]]

**Comment by Mpdreamz** [comment]
Thank you for reporting this its one of the breaking changes in 6.0 (our `master` branch)

We still have to apply at some point: https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_60_aggregations_changes.html
