### ISSUE TITLE
Indexing (or in fact anything) *without* deserialising response.

### ISSUE THREAD

**Issue by Jestar342** [elastic/elasticsearch-net#2737]
I need to be able to index/create/delete/etc without the need to deserialise the response. The deserialisation is hurting performance. Naturally I'd rather not have to resort to HttpClient for this.

v1.x supported this, but v5.x doesn't. (Unsure of v2.x, didn't use it)

**Comment by Mpdreamz** [comment]
The lowlevel client supports this by using `VoidResponse` as `TResponse`.

**Comment by Jestar342** [comment]
So it does, thanks!
