### ISSUE TITLE
Bulk Streaming 

### ISSUE THREAD

**Issue by aslamy** [elastic/elasticsearch-net#2739]
Hi !
Is it possible to stream a  bulk into elasticsearch?

**Comment by KodrAus** [comment]
Do you mind explaining your use-case a bit more?

By 'stream' bulk do you mean use a `Stream` of json bytes as the body for the bulk request? Or observing a stream `IBulkOperation`s and sending those asynchronously?

**Comment by Mpdreamz** [comment]
### observing a stream of objects  and send tthem in bulk
```csharp
var size = 1000;
var pages = 100;
var seenPages = 0;
var numberOfDocuments = size * pages;
var documents = this.CreateLazyStreamOfDocuments(numberOfDocuments);
We can then set up our BulkAll() call as follows:

var observableBulkAll = client.BulkAll(documents, f => f
    .MaxDegreeOfParallelism(8)
    .BackOff(TimeSpan.FromSeconds(10))
    .NumberOfBackOffRetries(2)
    .Size(size)
    .RefreshOnCompleted()
    .Index(IndexName)
);
and then register an observer

var bulkAllObserver = new PartitionedBulkObserver(
    onError: (e) => { throw e; },
    onCompleted: () => doSomething(),
    onNext: (b) => Interlocked.Increment(ref seenPages)
);
observableBulkAll.Subscribe(bulkAllObserver);
```

### Get access to write stream

this is not possible in the low level API although you can get direct access to the response stream

The lowlevel API only allows you to send `byte[]` 

https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/post-data.html
