### ISSUE TITLE
ShowTermDocumentCountError in 5.x?

### ISSUE THREAD

**Issue by MaJaHa95** [elastic/elasticsearch-net#2740]
Hey everyone,

I'm not sure whether this is a bug, or if it's a feature request, but please bear with me.

I'm running Elasticsearch 5.3.0, and have NEST and Elasticsearch-Net 5.3.0 as well.

I'm using the terms aggregation, and I just came across the `show_term_doc_count_error` setting.

The only reference I can find in this repo to this setting is in the list of 5.0 breaking changes, where it's listed as removed (specifically, in its C# form, `ShowTermDocumentCountError`). Here's that document: https://github.com/elastic/elasticsearch-net/blob/781430ec6793153a87f8e38ae93448b9db9fe6e6/docs/5.0-breaking-changes/nest-breaking-changes.asciidoc

However, I'm able to use it in queries against my cluster, again running >5.0, and I don't see anything in the Elasticsearch-side documentation that hints at this being deprecated. I see the giant warning that it's experimental and *may* be removed, but nothing to say it has been already.

Is there something I'm missing here? Was this setting properly removed from the SDK?

Thanks,
Matthew

**Comment by Mpdreamz** [comment]
wow thanks for catching this one @MaJaHa95, this property should **not** have been removed.

**Comment by Mpdreamz** [comment]
Opened https://github.com/elastic/elasticsearch-net/pull/2752 to fix this, Should make it into the next version. Thanks again @MaJaHa95 👍

**Comment by Mpdreamz** [comment]
PR merged to `5.x` and `master`
