### ISSUE TITLE
Generic Missing descriptor on Terms aggregation missing in NEST version 5.3.1

### ISSUE THREAD

**Issue by rbluethl** [elastic/elasticsearch-net#2755]
**NEST/Elasticsearch.Net version**:
5.3.1

**Elasticsearch version**:
5.1

**Description of the problem including expected versus actual behavior**:

Hello,
I would like to use the `Missing` property on a Terms aggregation for a `long` field, but unfortunately I am receiving the same error as described [here](https://github.com/elastic/elasticsearch-net/issues/2561). Since it seems like the issue was already fixed by providing a generic version of the missing descriptor, I wanted to ask in which version the issue will be fixed. We are using the latest version of NEST (5.3.1), where it's not yet possible to provide a type.

Thank you in advance.

**Comment by Mpdreamz** [comment]
Sadly the fix for it could not be backported without breaking compatibility so it only landed in `master (NEST 6.0). 

For now you can workaround it through the hack described here: https://github.com/elastic/elasticsearch-net/issues/2561#issuecomment-279528222

Hope this is enough to get you unstuck!

**Comment by rbluethl** [comment]
Thank you for the quick response.
I found the hack earlier and instantly tried it before opening this issue.
However, it didn't work for me.

The missing descriptor was ignored.
Also, the provided hack didn't compile with my NEST version.

Can you provide a working Missing with the latest NEST version?

Thank you and best regards

**Comment by rbluethl** [comment]
Hello again,

since this issue is kind of blocking for us, I wanted to ask if there are any updates regarding to it.

Thanks and best regards
Ronald

**Comment by Mpdreamz** [comment]
Sorry @rbluethl your reply to a closed entered the void, entirely our fault!

Will see if I can post a work around tomorrow

**Comment by rbluethl** [comment]
That would be awesome!

Thanks,
Ronald

**Comment by Mpdreamz** [comment]
```csharp
void Main()
{
	var memory = new InMemoryConnection();
	var connectionSettings = new ConnectionSettings(new SingleNodeConnectionPool(new Uri("http://localhost:9200")), memory)
		.EnableDebugMode();
	var client = new ElasticClient(connectionSettings);

	client.CreateIndex("fooindex", c => c.Settings(s => s.NumberOfShards(1).NumberOfReplicas(0))
		.Mappings(ms => ms.Map<Foo>(m => m.AutoMap()))
	);

	var resp = client.Search<Foo>(s => s
		.Index("fooindex")
		.Aggregations(a => a
			.Terms("a", t => new TermsAggregationHack("a") { Field = Infer.Field<Foo>(b => b.SomeInt), Missing = -1 }
			)
		)
	);

	resp.DebugInformation.Dump();

}

public class Foo
{
	public int Id { get; set; }
	public int SomeInt { get; set; }
}

public class TermsAggregationHack : TermsAggregation
{
	public TermsAggregationHack(string name) : base(name) {}
	[JsonProperty("missing")]
	public new int Missing { get; set; }
}
```

Will send the following request to elasticsearch

```json
{
  "aggs": {
    "a": {
      "terms": {
        "missing": -1,
        "field": "someInt"
      }
    }
  }
}
```

Hope this unblocks you @rbluethl !

**Comment by rbluethl** [comment]
Sorry for the late response.
The hack works perfectly fine - thanks a ton @Mpdreamz 👍
