### ISSUE TITLE
does NEST support geohash grid aggregation?

### ISSUE THREAD

**Issue by CurryHan** [elastic/elasticsearch-net#2762]
i'm sorry,i'm new to Nest.
i just ask :does NEST support geohash grid aggregation?
i can't find any method about it.

**Comment by russcam** [comment]
Hey @CurryHan, yes it does. [Check out the example usage documentation](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/geo-hash-grid-aggregation-usage.html)

**Comment by CurryHan** [comment]
I found it.Thank you!
