### ISSUE TITLE
NEST Index API Parent expects string instead of Id

### ISSUE THREAD

**Issue by dstockhammer** [elastic/elasticsearch-net#2765]
**NEST/Elasticsearch.Net version**: 5.4.0

**Description of the problem including expected versus actual behavior**:

`IndexDescriptor<TDocument>.Parent(string parent)` expects the parent id to be a string, whereas other APIs support the `Id` type when ids are expected. Examples:
* `IndexDescriptor<TDocument>.Id(Id id)`
* `BulkOperationDescriptorBase<TDescriptor, TInterface>.Parent(Id parent)`

So it seems that it would make sense to change this method to also take an `Id` as argument instead of `string`.

**Comment by russcam** [comment]
Thanks for reporting @dstockhammer. I think it'd be worth making this change in `master` for 6.x, if you'd like to look at submitting a PR for it?

**Comment by Mpdreamz** [comment]
Closing this as `Parent` is deprecated and removed in 6.x
