### ISSUE TITLE
How to use Nest to deduplicate suggestions

### ISSUE THREAD

**Issue by aslamy** [elastic/elasticsearch-net#2766]
Im running elasticsearch version 5.4.0. In the last release elasticsearch completion suggester learns to deduplicate suggestions. But how can I implement this in Nest  ?

**Comment by russcam** [comment]
Hi @aslamy, GitHub is reserved for bug reports and feature requests.

The best place to ask a general question is at the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch

Thanks!
