### ISSUE TITLE
Extract the code that runs ElasticSearch from the test assembly

### ISSUE THREAD

**Issue by SeanFarrow** [elastic/elasticsearch-net#2767]
I am writing a persistence plugin for Akka.net and it would be nice if something existed akin to Mongo2Go for MongoDB, allowing the running and teardown of either a node or a cluster.

I believe all the code is already there in the tests assembly. How feasible would it be to extract the relevant bits to a separate assembly/NuGet package?
I'm happy to do this, if it's something that's warranted.
Kind regards
Sean.

**Comment by Mpdreamz** [comment]
It should be very feasible and we have plans for doing so but none in the immediate future, if you fancy doing a PR for it to get things rolling that'd be awesome!

Feel free to open a work in progress PR as soon as you do! 👍 

I think it will need to be two packages `Elasticsearch.Managed` (all the `ElasticsearchNode` and `Observable` stuff) and `Elasticsearch.Net.XUnit` with all the `XUnit` bits allowing you to create integration tests against Elasticsearch more easily.

We can focus on `Elasticsearch.Managed` first though.

**Comment by SeanFarrow** [comment]
Ok, forking as we speak!
Will the tests need to depend on both packages—I’m assuming so!

**Comment by SeanFarrow** [comment]
Also, is there an issue for this and do I need to sign a CLA?

**Comment by Mpdreamz** [comment]
Once you've started open a PR (even if its nowhere near done) I'll mark it `WIP` and you can ping us whenever you need some input or we'll provide unsolicited feedback on commits while scanning through :)

That can act as 'the' ticket. 

Our CLA is up over at: https://www.elastic.co/contributor-agreement

**Comment by SeanFarrow** [comment]
What branch should we be basing this off 5.x or master/develop?
Also, where is the best place to start looking at the usage of the code that manages ES?

**Comment by Mpdreamz** [comment]
I would go for `5.x` since it also still has `2.x` specific edge case handling.

**Comment by SeanFarrow** [comment]
Ok, what’s the best place to start looking at the usage?

**Comment by Mpdreamz** [comment]
It all starts from `ClusterBase` which holds an `ElasticsearchNode` which in turn holds an `ObservableProcess`.

**Comment by SeanFarrow** [comment]
Ok, thanks, where do the integration tests live?
I’ll extract everything off cluster base in to a package then.

**Comment by russcam** [comment]
Integration tests live in the [Tests project](https://github.com/elastic/elasticsearch-net/tree/5.x/src/Tests), with most of the components to extract in the [Framework](https://github.com/elastic/elasticsearch-net/tree/5.x/src/Tests/Framework), specifically [Framework/ManagedElasticsearch](https://github.com/elastic/elasticsearch-net/tree/5.x/src/Tests/Framework/ManagedElasticsearch) directories. 

As @Mpdreamz said, there may be some unpicking to do, to decouple it from NEST's test infrastructure.

**Comment by SeanFarrow** [comment]
Ok, should be able to start this tomorrow, what version of vs are we using/wht project type?
Also, how do I add NuGet packages using packet to a project? I was looking at the paket.dependencies and XUnit doesn’t seem to be referenced there.
Finally should we upgrade our NuGet packages? I’ll raise another issue for this!
Kind regards
Sean.

**Comment by SeanFarrow** [comment]
Ok, I'm able to look at this over the weekend, what sort of project should I create in vs2017?

**Comment by SeanFarrow** [comment]
Whilst looking at this, it seems that ElasticSearchVersion is tightly coupled to TestClient, see the RootUrl field as an example. How do we get round this?

**Comment by russcam** [comment]
> Ok, I'm able to look at this over the weekend, what sort of project should I create in vs2017?

I'd recommend using the new csproj format with a C# library, that seems most fitting here.

> Whilst looking at this, it seems that ElasticSearchVersion is tightly coupled to TestClient, see the RootUrl field as an example. How do we get round this?

I think the configuration of `TestClient` would need to be pulled out of it; `ITestConfiguration` is used to determine the version of Elasticsearch that should be started and some other test specific behaviours e.g. test against already running cluster, whether to reseed with test data. I think this should be instantiated separately and passed to `TestClient`

**Comment by nphmuller** [comment]
Sorry to hijack this issue, but I have a quick question about the same subject matter.

Currently everything test related starts with the `Tests.` namespace. I guess everything related to ManagedElasticsearch would need to be refactored from `Tests.Framework.ManagedElasticsearch` to `Elasticsearch.Managed`, right?

**Comment by Mpdreamz** [comment]
@nphmuller @SeanFarrow 

I have started work on this myself last week to abstract several new nuget packages out of this. I hope to have this done by the end of the week.

**Comment by SeanFarrow** [comment]
@nphmuller<https://github.com/nphmuller>
Yes, that was the plan.
What new NuGet packages are you looking to create for my reference?

**Comment by nphmuller** [comment]
@SeanFarrow 
@Mpdreamz is already creating a couple of official NuGet packages. So currently I don't plan to create anything. :)

**Comment by SeanFarrow** [comment]
@mpdreamz What NuGet packages are you creating?

**Comment by nphmuller** [comment]
@Mpdreamz Any update on the new NuGet packages?

**Comment by HarelM** [comment]
Any updates on this?
I'm looking for a NuGet package that only contains the the binaries.

**Comment by HarelM** [comment]
Here's what I got so far, pretty sure this is not the approach that is described above but it is what I basically need and I think it can help others.
The following is the nuspec file I created:
```xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
    <metadata>
        <id>Elasticsearch</id>
        <version>5.6.3</version>
        <authors>elasticsearch</authors>
        <owners>elasticsearch</owners>
        <licenseUrl>https://github.com/elastic/elasticsearch/blob/master/LICENSE.txt</licenseUrl>
        <projectUrl>https://github.com/elastic/elasticsearch/</projectUrl>
        <iconUrl>https://raw.githubusercontent.com/elastic/elasticsearch-net/master/build/nuget-icon.png</iconUrl>
        <requireLicenseAcceptance>true</requireLicenseAcceptance>
        <releaseNotes></releaseNotes>
        <description>Elasticsearch is a distributed, RESTful search and analytics engine capable of solving a growing number of use cases. As the heart of the Elastic Stack, it centrally stores your data so you can discover the expected and uncover the unexpected. </description>
        <copyright>© 2017. All Rights Reserved - Elasticsearch</copyright>
        <tags>elasticsearch,elastic,search,lucene</tags>
        <dependencies>
        </dependencies>
    </metadata>
    <files>
        <file src="Elasticsearch\Elasticsearch.targets" target="build\" />
        <file src="Elasticsearch\lib\*.*" target="content\Elasticsearch\lib\" />
        <file src="Elasticsearch\config\*.*" target="content\Elasticsearch\config\" />
        <file src="Elasticsearch\bin\*.*" target="content\Elasticsearch\bin\" />
        <file src="Elasticsearch\modules\*.*" target="content\Elasticsearch\modules\" />
        <file src="Elasticsearch\plugins\*.*" target="content\Elasticsearch\plugins\" />
    </files>
</package>
```
Then in order to link the relevant files to be copied to the output folder I added this `Elasticsearch.targets` file (It must have the same name as the package):
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <NativeLibs Include="$(MSBuildThisFileDirectory)..\content\**\*.*" />
    <None Include="@(NativeLibs)">
      <Link>%(RecursiveDir)%(FileName)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
```
And that's it.
I have locally tested it to work.
Thoughts are welcome. 
I can publish it under a different name with my user if you think this is not the right way to go.

**Comment by Mpdreamz** [comment]
NuGet is not for binaries IMO. You can get Elasticsearch from chocolatey for instance. Our managed elasticsearch is for running Elasticsearch from code. It will bootstrap aquiring es in ÷APPDATA÷

**Comment by HarelM** [comment]
>NuGet is not for binaries IMO

This is a strange opinion - most of what's in NuGet is binary files. Most of them are .Net managed DLLs and I agree that it will be strange to place java binaries there, but I can compare these Java binaries to C++ DLLs that are also stored in NuGet for libraries that need those native DLLs. My server and my development environment needs Elasticsearch and so to me it feels like the right place to put it.

My goal is to simplify the setup of development environment so adding a step to install elasticsearch is going to the opposite direction, this is for my use case anyway...

**Comment by russcam** [comment]
I agree with @mpdreamz, I don't think a Nuget package is the best way to distribute Elasticsearch, in much the same way you wouldn't use it to distribute SQL Server. Chocolatey is a better fit for this

**Comment by russcam** [comment]
@SeanFarrow I'm going to close this issue now as @Mpdreamz has decoupled the components that we use to spin up Elasticsearch within the NEST integrations tests into their separate projects:

https://github.com/elastic/elasticsearch-net-abstractions

These are available as packages on a MyGet feed currently:

https://www.myget.org/F/elasticsearch-net-abstractions-temp/api/v3/index.json

With plans to make them more _official_ once they've had time to bake. You can see how they are wired up within the Tests projects in 6.x and master branches.

Feedback on them would be very welcome!
