### ISSUE TITLE
result

### ISSUE THREAD

**Issue by 25julia** [elastic/elasticsearch-net#2769]
**NEST/Elasticsearch.Net version**:

**Elasticsearch version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Describe the feature**:

**Comment by russcam** [comment]
Closing this; no bug/issue supplied.
