### ISSUE TITLE
Reindex hangs when calling Subscribe

### ISSUE THREAD

**Issue by mortenbock** [elastic/elasticsearch-net#2771]
**NEST/Elasticsearch.Net version**: NEST 5.4

**Elasticsearch version**: 5.0.2

I'm trying to use the Reindex to take all products from one index, enrich them, and reindex them in a separate index.

The code I'm using is the following:

    var reindexObservable = elasticClient.Reindex<ProductDocument, ProductDocument>(pd =>
    {
        pd.DisplayName = "Foobar";
        return pd;
    },
    descriptor => descriptor
                    .ScrollAll(new Time(TimeSpan.FromMinutes(1)), 4,
                        scrollAllDescriptor => scrollAllDescriptor
                        .MaxDegreeOfParallelism(2)
                            .Search(searchDescriptor => searchDescriptor
                                .Index("currentcatalog")
                                .Type<ProductDocument>()
                                .MatchAll()
                                .Size(250)))
                    .BulkAll(bulkAllDescriptor => bulkAllDescriptor
                        .MaxDegreeOfParallelism(1)
                        .RefreshOnCompleted()
                        .Index("updatedcatalog")
                        .Type<ProductDocument>())
                    .OmitIndexCreation()
    );
    
    var obs = new ReindexObserver(
        onNext: br => Console.WriteLine($"Next: {br.Page}"),
        onError: ex =>
        {
            Console.WriteLine($"Error: {ex.Message}");
            throw ex;
        },
        onCompleted: () =>
        {
            Console.WriteLine("Completed");
        });
    
    reindexObservable.Subscribe(obs);

When the `reindexObservable.Subscribe(obs);` is called, the program never seems to move any further, and none of the onNext/Error/Complete are called.

Am I misconfiguring the Scroll/Bulk or is this a bug?

The index contains around 120k documents.

**Comment by Mpdreamz** [comment]
Subscribe should be non blocking so seeing it hang does not seem right. 

In what context do you call this? How do you experience the hang? If you debug and pause and inspect the threads what line is it blocking on?

**Comment by mortenbock** [comment]
@Mpdreamz I'm running this from LinqPad right now. So I'm just creating my client and calling the code above.

Looking at the actual requests made to ES, this is what is posted to ES, and then it stops sending anything:

    POST http://127.0.0.1:9200/currentcatalog/productdocument/_search?pretty=true&scroll=1m 
    {
      "size": 250,
      "sort": [
        {
          "_doc": {}
        }
      ],
      "slice": {
        "id": 0,
        "max": 4
      },
      "query": {
        "match_all": {}
      }
    } 
    
    
    POST http://127.0.0.1:9200/currentcatalog/productdocument/_search?pretty=true&scroll=1m 
    {
      "size": 250,
      "sort": [
        {
          "_doc": {}
        }
      ],
      "slice": {
        "id": 1,
        "max": 4
      },
      "query": {
        "match_all": {}
      }
    } 
    
    POST http://127.0.0.1:9200/_search/scroll?pretty=true 
    {
      "scroll": "1m",
      "scroll_id": "DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAgRFkFvcUk2S0F5VERTbEoxX29MVkdQX1EAAAAAAAAIEBZBb3FJNktBeVREU2xKMV9vTFZHUF9RAAAAAAAACA8WQW9xSTZLQXlURFNsSjFfb0xWR1BfUQAAAAAAAAgTFkFvcUk2S0F5VERTbEoxX29MVkdQX1EAAAAAAAAIEhZBb3FJNktBeVREU2xKMV9vTFZHUF9R"
    } 
    
    POST http://127.0.0.1:9200/_search/scroll?pretty=true 
    {
      "scroll": "1m",
      "scroll_id": "DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAgWFkFvcUk2S0F5VERTbEoxX29MVkdQX1EAAAAAAAAIFBZBb3FJNktBeVREU2xKMV9vTFZHUF9RAAAAAAAACBUWQW9xSTZLQXlURFNsSjFfb0xWR1BfUQAAAAAAAAgYFkFvcUk2S0F5VERTbEoxX29MVkdQX1EAAAAAAAAIFxZBb3FJNktBeVREU2xKMV9vTFZHUF9R"
    } 
    
    POST http://127.0.0.1:9200/_search/scroll?pretty=true 
    {
      "scroll": "1m",
      "scroll_id": "DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAgRFkFvcUk2S0F5VERTbEoxX29MVkdQX1EAAAAAAAAIEBZBb3FJNktBeVREU2xKMV9vTFZHUF9RAAAAAAAACA8WQW9xSTZLQXlURFNsSjFfb0xWR1BfUQAAAAAAAAgTFkFvcUk2S0F5VERTbEoxX29MVkdQX1EAAAAAAAAIEhZBb3FJNktBeVREU2xKMV9vTFZHUF9R"
    } 
    
    POST http://127.0.0.1:9200/_search/scroll?pretty=true 
    {
      "scroll": "1m",
      "scroll_id": "DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAgWFkFvcUk2S0F5VERTbEoxX29MVkdQX1EAAAAAAAAIFBZBb3FJNktBeVREU2xKMV9vTFZHUF9RAAAAAAAACBUWQW9xSTZLQXlURFNsSjFfb0xWR1BfUQAAAAAAAAgYFkFvcUk2S0F5VERTbEoxX29MVkdQX1EAAAAAAAAIFxZBb3FJNktBeVREU2xKMV9vTFZHUF9R"
    } 

The word "hang" might not be the right one, because the process does not freeze, but I can see in LinqPad, that the debugger never moves past the last line.

**Comment by Mpdreamz** [comment]
Can you try explicitly blocking on the subscribe?

E.g reindexObservable.Wait(TimeSpan.FromMinutes(10)) instead of the subscribe. 

That wait method is an extension method we ship with. 

Do you see it run to completion? I wonder if this is some LinqPad magic in the way it executes. 

If you do the same from a vanilla console app do you see the same?

**Comment by Mpdreamz** [comment]
Not able to get to a keyboard today so excuse my remote debugging though you here :)

**Comment by mortenbock** [comment]
@Mpdreamz No worries, I'm happy to try stuff out.

If I do `reindexObservable.Wait(TimeSpan.FromSeconds(10), r => {r.Dump();});` then the program "hangs" at that line. Even after the 10 seconds have gone.

So it seems to give the same experience.

I will try to move this code to a console app, and see if VS debugging can give me more info.

**Comment by mortenbock** [comment]
I tried putting the code in a console app, and I was not able to see any exceptions or anything from any background threads.

Just no more requests being made to ES.

**Comment by ThomasSkyldahl** [comment]
try setting .MaxDegreeOfParallelism(1) to .MaxDegreeOfParallelism(2)

I can not spot why it works but it does the job at least for me.

Sources: 
https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Document/Multiple/Reindex/ReindexObservable.cs#L122

and the ProducerConsumer used in the background

https://github.com/elastic/elasticsearch-net/blob/3e58310d6c29a35d5568923480f86856bfb9675b/src/Nest/CommonAbstractions/Reactive/ProducerConsumerBackPressure.cs

**Comment by mortenbock** [comment]
@ThomasSkyldahl That actually did the trick!

So there needs to be some degree of parallelism for this to work.

@Mpdreamz Maybe it would make sense to have the Reindex method throw that as en exception if this is indeed intended behaviour? In the same way it does if the funnel is too small?

https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Document/Multiple/Reindex/ReindexObservable.cs#L128

**Comment by Mpdreamz** [comment]
Thanks for opening this @mortenbock, opened #2781 to also throw an exception when the producer only has enough concurrency to satisfy a single consumer. We need atleast `+1` slot available to call `MoveNext()` on.
