### ISSUE TITLE
When using ScrollingSearch => After Scroll Size is reached exception due to PiggyBackState = null

### ISSUE THREAD

**Issue by rdehuyss** [elastic/elasticsearch-net#2790]
**NEST/Elasticsearch.Net version**: 2.5.4

**Elasticsearch version**: 2.3.1

**Description of the problem including expected versus actual behavior**:
We are using Elastic for a scrolling search and pass an enumerable of typenames in the Type part of the query descriptor. When we hit the size provided in the query descriptor, we notice that we receive another JsonNetSerializer with a ContractResolver where the PiggyBackState is null whereas before the provided size was hit, we receive a JsonNetSerializer with a ContractResolver where the PiggyBackState is not null.

When the PiggyBackState is null, we receive an exception as one of our types is Abstract

**Where does it go wrong?**
Before the scroll size is hit, realConverter != null, so a concreteTypeConverter is used. After the scroll size is hit, realConverter == null thus throwing an exception when using an abstract  class as T

	public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
	{
		var realConverter = serializer.GetStatefulConverter<ConcreteTypeConverter<T>>();
		if (realConverter != null)
			return ConcreteTypeConverter.GetUsingConcreteTypeConverter<T>(reader, serializer, realConverter);

		var instance = (Hit<T>)(typeof(Hit<T>).CreateInstance());
		serializer.Populate(reader, instance);
		instance.Fields = new FieldValues(serializer.GetConnectionSettings().Inferrer, instance.Fields);
		return instance;
	}

**Steps to reproduce**:
See code below...

	using Nest;
	using System;
	using System.Collections.Generic;
	using System.IO;
	using System.Linq;

	namespace ConsoleApplication1
	{
		class Program
		{
			static void Main(string[] args)
			{
				var elasticClient = new ElasticClient(new ConnectionSettings(new Uri("http://localhost:9200")).ThrowExceptions(true).DefaultIndex("test"));

				if(elasticClient.IndexExists("test").Exists)
					elasticClient.DeleteIndex("test");
				File.Delete(@"c:\test-es.txt");

				const int documentCountPerType = 60;

				var testDocuments = Enumerable.Range(0, documentCountPerType).Select(n => new TestModels.TestDocumentThatExtends { Id = $"IdTD-{n}", Value = $"Value-{n}" });
				var testDocumentsAThatExtend = Enumerable.Range(0, documentCountPerType).Select(n => new TestModels.TestDocumentAThatExtends { Id = $"IdTDA-{n}", Value = $"Value-{n}", Bar = $"Bar-{n}" });
				var testDocumentsBThatExtend = Enumerable.Range(0, documentCountPerType).Select(n => new TestModels.TestDocumentBThatExtends { Id = $"IdTDB-{n}", Value = $"Value-{n}", Foo = $"Foo-{n}" });

				elasticClient.IndexMany(testDocuments);
				elasticClient.IndexMany(testDocumentsAThatExtend);
				elasticClient.IndexMany(testDocumentsBThatExtend);

				int batchSizeThatWorks = 200; //(scroll is not hit)
				int batchSizeThatFails = 3; //(scroll is hit)

				elasticClient
					.SubclassScrollingSearch<TestModels.TestDocument>(q => q.MatchAll(), scrollTimeoutInSeconds: 900, batchSize: batchSizeThatFails)
					.ForEach(testDoc => WriteToFile(testDoc));

				if (File.ReadAllLines(@"c:\test-es.txt").Length != 180)
				{
					throw new InvalidOperationException("Not all types are in the file...");
				}
			}

			private static void WriteToFile(TestModels.TestDocument testDoc)
			{
				var toWrite = testDoc.Id;
				if (testDoc is TestModels.TestDocumentAThatExtends)
				{
					var testDocumentAThatExtends = ((TestModels.TestDocumentAThatExtends) testDoc);
					toWrite += $"; {testDocumentAThatExtends.Bar}";
				}
				if (testDoc is TestModels.TestDocumentBThatExtends)
				{
					var testDocumentAThatExtends = ((TestModels.TestDocumentBThatExtends)testDoc);
					toWrite += $"; {testDocumentAThatExtends.Foo}";
				}
				File.AppendAllText(@"c:\test-es.txt", testDoc.Id + Environment.NewLine);
			}
		}

		public static class ElasticClientExtension
		{
			public static IEnumerable<T> SubclassScrollingSearch<T>(this IElasticClient client, Func<SearchDescriptor<T>, ISearchRequest> selector, int scrollTimeoutInSeconds = 30, int batchSize = 5000)
				where T : class
			{
				var subclasses = SubClassesForType<T>();
				var typeNames = subclasses.Select(type => new TypeName { Name = type.Name.ToLowerInvariant(), Type = type });

				var scrollTimeout = new Time(TimeSpan.FromSeconds(scrollTimeoutInSeconds));

				var response = client.Search<T>(descriptor => selector(descriptor
					.Version()
					.Type(Types.Type(typeNames))
					.Scroll(scrollTimeout)
					.Size(batchSize)));

				if (!response.Documents.Any())
					yield break;

				do
				{
					foreach (var document in response.Documents)
					{
						yield return document;
					}

					var scrollId = response.ScrollId;
					response = client.Scroll<T>(scrollTimeout, scrollId);
				} while (response.Documents.Any());
			}

			public static void ForEach<T>(this IEnumerable<T> enumeration, Action<T> action)
			{
				foreach (T item in enumeration)
				{
					action(item);
				}
			}

			private static IEnumerable<Type> SubClassesForType<T>() where T : class
			{
				var subclasses = typeof(T).Assembly.GetTypes().Where(type => type.IsSubclassOf(typeof(T))).ToList();
				subclasses.Add(typeof(T));
				return subclasses;
			}
		}

		class TestModels
		{
			public abstract class TestDocument
			{
				public string Id { get; set; }

			}

			public class TestDocumentThatExtends : TestDocument
			{
				public string Value { get; set; }
			}

			public class TestDocumentAThatExtends : TestDocumentThatExtends
			{
				public string Bar { get; set; }
			}

			public class TestDocumentBThatExtends : TestDocumentThatExtends
			{
				public string Foo { get; set; }
			}
		}
	}

**Comment by rdehuyss** [comment]
Never mind, RTF at https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/covariant-search-results.html

**Comment by russcam** [comment]
Glad you got it sorted @rdehuyss. For the benefit of others that may find this in future, would you be able to summarize the solution?

**Comment by rdehuyss** [comment]
Well, the problem was that the `client.Scroll<T>(scrollTimeout, scrollId);` didn't have a ConcreteTypeSelector. The issue was solved by doing it as follows:

	public static IEnumerable<T> SubclassScrollingSearch<T>(this IElasticClient client, Func<SearchDescriptor<T>, ISearchRequest> selector, int scrollTimeoutInSeconds = 30, int batchSize = 5000)
            where T : class
	{
		var subclasses = SubClassesForType<T>();
		var typeNames = subclasses.Select(type => new TypeName { Name = type.Name.ToLowerInvariant(), Type = type });

		var scrollTimeout = new Time(TimeSpan.FromSeconds(scrollTimeoutInSeconds));

		var response = client.Search<T>(descriptor => selector(descriptor
			.Version()
			.Type(Types.Type(typeNames))
			.Scroll(scrollTimeout)
			.Size(batchSize)));

		if (!response.Documents.Any())
			yield break;

		do
		{
			
			foreach (var document in response.Documents)
			{
				yield return document;
			}

			var scrollId = response.ScrollId;
			response = client.Scroll<T>(scrollTimeout, scrollId, sd => sd.ConcreteTypeSelector((d, hit) => typeNames.Single(typeName => typeName.Name == hit.Type).Type));
		} while (response.Documents.Any());
	}

In the `client.Scroll()` method we now pass a ConcreteTypeSelector which makes sure Newtonsoft gets the right type to deserialize.

**Comment by russcam** [comment]
Thank you @rdehuyss, that'll definitely help future googlers 😃
