### ISSUE TITLE
Missing parameters on SimpleQueryStringQuery

### ISSUE THREAD

**Issue by chronolinq** [elastic/elasticsearch-net#2792]
**NEST/Elasticsearch.Net version**: 5.4.0

**Elasticsearch version**: 5.4.2

**Description of the problem including expected versus actual behavior**: It appears that the "quote_field_suffix" parameter is missing from the SimpleQueryStringQuery class.  It is, however, present on the QueryStringQuery class.

Reference to the parameters for the SimpleQueryStringQuery are listed here: **https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html**

Will these parameters be exposed in a future version?

**Comment by russcam** [comment]
Thanks for opening this @wwcrelate. Yes, it'll be added in the next release.

**Comment by wwcrelate** [comment]
Awesome! Thanks @russcam for the response.
