### ISSUE TITLE
How to get highlights for nested field from the InnerHits in the NEST?

### ISSUE THREAD

**Issue by tstar** [elastic/elasticsearch-net#2798]
**NEST/Elasticsearch.Net version**: 5.4.0

**Elasticsearch version**: 5.4.3

**Description of the problem**:

I'm trying to get highlights for nested fields. I can see them in the ES result in the inner_hits, but I can not get them via NEST. I see that the InnerHits property has the property Highlights but it not returns highlights beside it has infinity nested Highlights properties.

I did not found any solution for this issue. Am I doing something wrong?

Thanks.

**Comment by Mpdreamz** [comment]
Hi @tstar, 

You might have stumbled over a bug here, we'll look into reproducing and possibly fixing this for the next version.

Thanks for reporting 👍

**Comment by Mpdreamz** [comment]
Finally got around to try and reproduce this issue but to no avail, see #2940.

Closing this as can not reproduce, thanks again for reporting and appologies that it took forever to come back around to this.
