### ISSUE TITLE
怎么设置索引默认分词器

### ISSUE THREAD

**Issue by YangTianb** [elastic/elasticsearch-net#2801]
**NEST/Elasticsearch.Net version**:5.0

**Elasticsearch version**:5.4.1

ES 安装了 ik 中文分词器。

NEST 中怎么使用这个分词器？

**Comment by medcl** [comment]
hi，在创建索引的时候指定该索引的字段的分词为对应的 ik 就可以的。
可以参照文档：https://www.elastic.co/guide/en/elasticsearch/client/net-api/5.x/writing-analyzers.html

**Comment by Mpdreamz** [comment]
thanks @medcl 👍
