### ISSUE TITLE
BulkAll() retry configuration

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#2804]
[BulkAll currently tries to retry all invalid responses where there are a number of backOff retries configured](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs#L117-L128).

Should some responses not be retried e.g. a 401 response when authentication credentials have not been specified?

**Comment by Mpdreamz** [comment]
It only retries `429`'d bulk items by default, but making it pluggable would be a nice feature!
