### ISSUE TITLE
Ambigous call on QueryContainerDescriptor<T>.Wildcard(field, value)

### ISSUE THREAD

**Issue by TSSchoof** [elastic/elasticsearch-net#2805]
**NEST/Elasticsearch.Net version**: 5.4

**Elasticsearch version**: 5.5

**Description of the problem including expected versus actual behavior**: After upgrading to NEST 5.4 (from 5.2.2) I get an exception on QueryContainerDescriptor<T>.Wildcard(field, value).

`The call is ambiguous between the following methods or properties: 'QueryContainerDescriptor<T>.Wildcard(Expression<Func<T, object>>, string, double?, RewriteMultiTerm?, string)' and 'QueryContainerDescriptor<T>.Wildcard(Expression<Func<T, object>>, string, double?, MultiTermQueryRewrite, string)'`

I use this feature to do Wildcard searches, because the alternative Term does not work like a 'like' search.
```
var query = value.Contains("*") ? (Func<QueryContainerDescriptor<T>, QueryContainer>)
                            (bs => bs.Wildcard(propConfig.KeySelector, value)) : // wildcard search
                            (bs => bs.Term(propConfig.KeySelector, value)); // default term search
```

**Steps to reproduce**:
 1. call .Wildcard on a QueryContainerDescriptor<T> with 2 parameters: field, value

**Misc**:
I also noticed that .Wildcard is new deprecated. What is the recommended method to replace this? I can't find this in any release notes.

**Comment by russcam** [comment]
Hey @TSSchoof, that particular method call for `WildCard()` was deprecated in [NEST 5.3.0](https://github.com/elastic/elasticsearch-net/releases/tag/5.3.0) because of #2688. With the deprecated warning, do you see the message "Use overload that accepts MultiTermQueryRewrite"?

Looks like we didn't have a test to catch the method call ambiguity 😢  It's easily resolved by specifying `rewrite` though

```c#
(bs => bs.Wildcard(propConfig.KeySelector, value, rewrite:(MultiTermQueryRewrite)null))
```
The deprecated methods will be removed in the next major release.

**Comment by TSSchoof** [comment]
Thanks! I don't see that message though. It's probably a setting in Visual Studio somewhere.

![wildcard](https://user-images.githubusercontent.com/2319986/28207665-db8787ac-688a-11e7-9d1e-b1383ec29cba.png)

**Comment by russcam** [comment]
That's no good! Do you see it in the build output?

**Comment by TSSchoof** [comment]
Well when I'm not using the rewrite the build fails and I just get the exception.

![output](https://user-images.githubusercontent.com/2319986/28208013-ffd64ade-688b-11e7-999e-aca358d5638f.PNG)

The override is not deprecated so that does not show any warnings.

**Comment by russcam** [comment]
No worries, thanks for looking. I'm sure Visual Studio used to show the Obsolete message within the intellisense bubble 😕

**Comment by TSSchoof** [comment]
No problem! I would have assumed so too. Not sure if it's something with my Visual Studio (2017) or just in general.
