### ISSUE TITLE
Serialization / deserialization issue

### ISSUE THREAD

**Issue by risogolo** [elastic/elasticsearch-net#2809]
**NEST/Elasticsearch.Net version 5.4.0**:

**Elasticsearch version 5.5.0**:

**I need to store nested property of type `List<Entity>` which is a property of some parent object, type Entity uses polymorphism**
`
public class Entity
{
some properties
}

public class Something : Entity
{
some properties
}
`

**Steps to reproduce**:
 1. I created the connection as it is described here (in first [table)](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/modifying-default-serializer.html#_modifying_settings_using_serializerfactory), basically It when storing data it creates also the field which contains $type: for specific type (Entity), then the deserializer should know how to deserialize (to which specific specific type). I expected that this would work out of the box, but it is not.
 2. Then I added a record to the elastic search, this seems to be OK
 3. When I'm getting the record from elasticsearch, I'm getting "ServerError: 400Type: illegal_argument_exception Reason: "[max] unknown field [$type], parser not found"

**Comment by Mpdreamz** [comment]
Enabling TypeNameHandling.Auto like this will break our own serializing. mark your POCO's manually with [JsonObject(TypeNameHandling)] attributes.

See also: #1155

**Comment by risogolo** [comment]
I saw it, but this attribute with this constructor does not exist anymore

**Comment by Mpdreamz** [comment]
Sorry to hear, my thoughts on this haven't changed though since:

https://github.com/elastic/elasticsearch-net/issues/1155#issuecomment-70147904

JSON.NET needs a less intrusive opt in way to enable this feature, so this would make a great feature request on that project.

**Comment by risogolo** [comment]
Still not sure what I need to achieve, what this attibute sets [JsonObject(TypeNameHandling)] Is it Auto or Object, do I need to also specify the jsonserializer settings via SerializerFactory
