### ISSUE TITLE
Writing to ElasticSearch version 1.7.5 

### ISSUE THREAD

**Issue by aateeque** [elastic/elasticsearch-net#2811]
I am in the usual situation where I have two different versions of ElasticSearch clusters - the latest one and version 1.7.5. I wonder if I can use the latest ElasticSearch.Net to write to version 1.7.5 of ElasticSearch?

**Comment by aateeque** [comment]
This seems to be fine; no problems encountered so far; not sure about edge cases

**Comment by russcam** [comment]
@aateeque We don't support (or test) major versions against previous major versions. Whilst it might work for the most part, there are known breaking API changes between 1.x -> 2.x -> 5.x that are reflected in breaking changes in the client. An example that comes to mind is the format of error responses returned changed in 2.x from 1.x.

If you can, you should consider updating the 1.7.5 cluster to latest major version (ideally 5.5.0). The [reindex API with reindex from remote](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#reindex-from-remote) can help here in reindexing your data across or you can go through the [upgrade process](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html).

If you want to load both NEST 1.x and 5.x assemblies side by side, it should be possible using [`extern alias`](https://blogs.msdn.microsoft.com/abhinaba/2005/11/30/c-2-0-using-different-versions-of-the-same-dll-in-one-application/). NuGet prevents you from adding two different package versions with the same ID, but it's possible to download manually and reference.
