### ISSUE TITLE
Verbatim Terms query with Empty Terms gives invalid search json

### ISSUE THREAD

**Issue by Koenyn** [elastic/elasticsearch-net#2812]
**NEST/Elasticsearch.Net version**:
5.4.0

**Elasticsearch version**:
5.5

**Description of the problem including expected versus actual behavior**:
Verbatim Terms query with an empty array of terms is producing an invalid search request

`SearchDescriptor<Test> searchDescriptor = new SearchDescriptor<Test>()
		.Index("test")
		.Type("type")
		.Size(5)
		.Query(q => q.Terms(t => t.Verbatim().Field(f => f.Things).Terms(new string[] { })));`

results in

`{
  "size": 5,
  "query": {
    "terms": {}
  }
}`

I expected
`{
  "query": {
    "terms": {
      "things": [
      ]
    }
  },
  "size": 5
}`

**Comment by Mpdreamz** [comment]
Hmm I can see this being unexpected, the fix for this could be a tad tricky. Could you explain your usecase for this?

**Comment by Koenyn** [comment]
Each document has an array of companyIDs that can access it. Should a user not belong to a company then they should not have access to any documents. V1.7x verbatim worked fine, we're now upgrading to  v5.5

I have a workaround by adding an invalid companyID to my query array, but it's not ideal.

**Comment by zioseri** [comment]
Hi guys,
any news on this ?
Thanks a lot

**Comment by Mpdreamz** [comment]
@Koenyn @zioseri took forever but I finally had the opportunity to dig into this as per https://github.com/elastic/elasticsearch-net/pull/2941

Should be fixed in the next 2.x 5.x and 6.x releases.
