### ISSUE TITLE
Special Chart Search 

### ISSUE THREAD

**Issue by mojinxun** [elastic/elasticsearch-net#2814]
Such as @, #, %

How Can I search it

**Comment by russcam** [comment]
Hi @mojinxun , 

GitHub is reserved for bug reports and feature requests.

The best place to ask a general question like this is at the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. What you're looking for here is [using a custom analyzer](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/writing-analyzers.html) that tokenizes those special characters within the terms produced by it, making them available for search.

Thanks!
