### ISSUE TITLE
Setting `{dynamic_type}` as part of the mapping

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#2817]
Reported on stackoverflow:  https://stackoverflow.com/questions/44933356/create-a-dynamic-type-mapping-in-elasticsearch-with-nest

The user is not able to generate the following using our `.Generic` construct that can map dynamic mappings like these.

```json
"mapping": {
    "type": "{dynamic_type}",
    "index": "not_analyzed",
    "doc_values": true
}
```

**Comment by lakario** [comment]
Thanks for creating a Github issue to track this.
