### ISSUE TITLE
When Use A Dynamic Type in Query, Got StackOverFlow Exception

### ISSUE THREAD

**Issue by moonheart** [elastic/elasticsearch-net#2825]
**NEST/Elasticsearch.Net version**: 5.5.0

**Elasticsearch version**: 5.3

Visual Studio 2017, .NET Framework 4.5.2
**Steps to reproduce**:
1. Use the following code, I got a StackOverFlow exception.
```csharp
dynamic queryString = "example query string";
var res = esClient.Search<article>(s => s
      .Size(5)
      .Query(q => q
           .Bool(b => b
                  .Must(
                        m => m.QueryString(qs => qs.DefaultField("title").Query(queryString )),
                        m => m.QueryString(qs => qs.DefaultField("content").Query(queryString ))
                  )
            )
     ));
```
2. Change **`dynamic queryString`** to **`string queryString`**, it works without any problem.

**Comment by russcam** [comment]
I think this is the [same _potential_ bug in the DLR in dynamic type resolution](https://github.com/dotnet/corefx/issues/7527); the StackOverflowException is from 

```
System.RuntimeTypeHandle.GetInstantiation(type, types, fAsRuntimeTypeArray)
(Unmanaged code)
System.RuntimeType.GetGenericArguments()
Microsoft.CSharp.RuntimeBinder.SymbolTable.GetConstructedType(type, agg)
Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(originalType)
Microsoft.CSharp.RuntimeBinder.SymbolTable.GetConstructedType(type, agg)
Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(originalType)
// ... etc
```

Since the resolution here is not to use `dynamic`, I'm going to close this issue.

**Comment by Mpdreamz** [comment]
Inserting dynamic in expressions is known to misbehave in odd ways:

https://github.com/elastic/elasticsearch-net/issues/732#issuecomment-49157199

https://github.com/elastic/elasticsearch-net/issues/2244#issuecomment-246611226

https://github.com/elastic/elasticsearch-net/issues/937

Thread with care 🙂
