### ISSUE TITLE
ServerError while passing long parameter to range query on timestamp field

### ISSUE THREAD

**Issue by jkhanpara** [elastic/elasticsearch-net#2832]
NEST: 5.2.0 
Elasticsearch.Net: 5.5.0
Elasticsearch version: 5.3.2

Description: Error while using the range query on timestamp field.
We recently upgraded our elastic cluster from 1.7.2 to 5.3.2 and started getting below error

> {Type: illegal_argument_exception Reason: "Parse failure at index [1] of [1.5027552E12]"}
> failed to parse date field [1.5027552E12] with format [strict_date_optional_time||epoch_millis]

While executing the below code:

```
var results = await client.SearchAsync<EventData>(s =>
            {
                var query = s
                    .Size(0)
                    .Query(
                        q => q.Bool(
                            b => b.Must(
                                m => m.Range(r => r
                                    .Field("timestamp")
                                    .GreaterThanOrEquals(from)
                                    .LessThanOrEquals(to)))))
                    .Aggregations(a => a
                        .Terms("type_agg", h => h
                        .Field("type")
                        .Size(10)
                        .MinimumDocumentCount(0)));
                return query;
            });
```

Raw query generated by above code:
```
{
  "size": 0,
  "aggs": {
    "type_agg": {
      "terms": {
        "field": "type",
        "size": 10,
        "min_doc_count": 0
      }
    }
  },
  "query": {
    "bool": {
      "must": [
        {
          "range": {
            "timestamp": {
              "gte": 1502755200000.0,
              "lte": 1502841599000.0
            }
          }
        }
      ]
    }
  }
}
```

Executing the above raw query directly into ES head also throws exception on 5.x version but works fine on older version. After removing the decimal part (".0") from above query works perfectly fine on both versions.

Looks like issue is with GreaterThanOrEquals (and similar methods like LessThanOrEquals) which accepts nullable double and append decimal part to passed in value. In my case it is of type long. I found similar issue addressed on elasticsearch https://github.com/elastic/elasticsearch/issues/14641 

Is there any workaround to address this issue?

**Comment by freeaxes** [comment]
Looks like if you use the DateRange query descriptor instead of Range, you can just pass in the strings that you want the json to contain?

So this:
```
.DateRange(r => r
    .Field(field => field.Time)
    .GreaterThanOrEquals($"{myParams.StartTime.ToUnixTimestamp() * 1000}")
    .LessThanOrEquals($"{myParams.EndTime.ToUnixTimestamp() * 1000}")
    .Format("epoch_millis"))
```

Is producing JSON like this:
```
"range": {
    "Time": {
        "gte": "1503279000000",
        "lte": "1503281400000",
        "format": "epoch_millis"
    }
}
```

Which then executes cleanly as near as I can tell.

**Comment by jkhanpara** [comment]
Thanks @freeaxes, it worked.
