### ISSUE TITLE
[Docs] InitializeUsing vs Settings

### ISSUE THREAD

**Issue by btecu** [elastic/elasticsearch-net#2833]
**NEST/Elasticsearch.Net version**: 5.x

**Elasticsearch version**: 5.x

**Description of the problem including expected versus actual behavior**:
Currently in the process of migrating from version 1 to 5, I'm not able to find any documentation about `InitializeUsing` when creating an index. It's now possible to pass the settings via `Settings`, however I don't know if there are other implications or which one should be used.
The documentation probably needs to be updated.

**Comment by Mpdreamz** [comment]
Hi apologies for leaving this issue open for such a long time.

`InitializeUsing()` is used to take the result from a `GetIndex()` call and feed that directly into a `CreateIndex()` call, you can then override settings using `Settings()`
