### ISSUE TITLE
install NEST in vs2017

### ISSUE THREAD

**Issue by yanwei2508** [elastic/elasticsearch-net#2841]
I try to install nest in the Package manager console in vs 2017,like:
PM> Install-Package NEST -Version 5.5.0

but always Say:
Install-Package : Sequence contains more than one matching element
At line:1 char:1
+ Install-Package NEST -Version 5.5.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

I don't know the reason and can't find any solution about this

**Comment by russcam** [comment]
Hey @yanwei2508, this is an issue with NuGet - I'd recommend filing an issue at https://github.com/NuGet/NuGet.Client for this, which contains the PowerShell cmdlets.

Closing this as not a NEST issue.
