### ISSUE TITLE
shard_min_doc_count parameter for Significant Terms Aggregation is not supported by NEST client

### ISSUE THREAD

**Issue by anatoly21** [elastic/elasticsearch-net#2847]
Nest Version 5.0.0.0
Elasticsearch version: 5.5.2

I cannot find how to specify shard_min_doc_count  with NEST. Am I missing something ?

**Comment by russcam** [comment]
Hey @anatoly21, apologies for not responding to this issue sooner. This is indeed missing from the Significant Terms aggregation in NEST, currently. I'll open a PR shortly to address 👍

**Comment by russcam** [comment]
I've opened #2958

**Comment by anatoly21** [comment]
Thanks
