### ISSUE TITLE
NEST - No mechanism to override index.mappings.nested_fields.limit

### ISSUE THREAD

**Issue by lakario** [elastic/elasticsearch-net#2848]
Testing against elasticsearch-net 5.5 and NEST, I cannot seem to find a mechanism which will allow me to put index settings for `index.mappings.nested_fields.limit`. It appears as though the only option is to execute a low-level JSON PUT. Am I missing something?

**Comment by mwolfhoffman** [comment]
This worked for me to update the settings when creating a index. 

settings["index.mapping.total_fields.limit"]: 1000000 // (or however much)

other examples
https://www.elastic.co/guide/en/elasticsearch/client/net-api/1.x/update-settings.html
