### ISSUE TITLE
Add phrase_limit for FVH highlighting

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#2851]
[from stackoverflow](https://stackoverflow.com/questions/46162384/specifying-phrase-limit-for-elasticsearch-using-nest-client)

Fast Vector Highlighter should have [`phrase_limit`](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html#phrase-limit)

**Comment by bkowald** [comment]
Hi Russ, so does this mean that this is added in Elastic version 5.5.5?

**Comment by russcam** [comment]
@bkowald This hasn't been addressed yet. Looking at now. Apologies that it has taken so long to look at this

**Comment by russcam** [comment]
I've opened https://github.com/elastic/elasticsearch-net/pull/2959 to address
