### ISSUE TITLE
Wildcard exception

### ISSUE THREAD

**Issue by aslamy** [elastic/elasticsearch-net#2853]
I have a query like:

```
.Query(q => q
    .Bool(b => b
       .Should(s => s.Wildcard(w=>w
                     .Field(f=>f.Title)
                     .Value("boo*")
                    )
             )
       )
)
```

When I run this query I get this exception:
Self referencing loop detected with type 'Nest.QueryContainerDescriptor
Why I can't have a Wildcard inside Should query?

**Comment by Mpdreamz** [comment]
Happy to see the issue resolved for you @aslamy, mind posting why you closed the issue for future googlers? :+1:
