### ISSUE TITLE
How to Prepare ElasticSearch(NEST) Query  to perform search operation On an Index throughout all Types for a specific field ?

### ISSUE THREAD

**Issue by susilkumarpadhi** [elastic/elasticsearch-net#2860]
Hello, I need a Nest Query.

Here I am Providing the Sense Query.

**GET 52.214.134.87:9200/ic/_search
{  
   "query": {
     "match_phrase": {
        "recordType": "WealthEvent"
     }
   }
}**

**Comment by russcam** [comment]
Hi @susilkumarpadhi 

GitHub is reserved for bug reports and feature requests.

The best place to ask a general question like this in the future is at the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch

Thanks!

Take a look at the documentation of [MatchPhrase query](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/match-phrase-usage.html)

something like

```c#
public class MyDocument
{
    public string RecordType { get; set; }
}

var client = new ElasticClient();

client.Search<MyDocument>(s => s
    .Index("ic")
    .AllTypes()
    .Query(q => q
        .MatchPhrase(mp => mp
            .Field(f => f.RecordType)
            .Query("WealthEvent")
        )
    )
);
```
