### ISSUE TITLE
Move empty field to bottom

### ISSUE THREAD

**Issue by kaviyarasanaspire** [elastic/elasticsearch-net#2863]
Hi,

We are using ElasticSearch 1.5, we are in a requirement to sort the content by ascending and show the empty string at the last position. 

Can anyone help me to achieve the solution.

**Comment by russcam** [comment]
Hi @kaviyarasanaspire , 

GitHub is reserved for bug reports and feature requests.

The best place to ask a general question like this is at the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch

Thanks!
