### ISSUE TITLE
Make BulkResponseItemBase easier to mock

### ISSUE THREAD

**Issue by awelburn** [elastic/elasticsearch-net#2867]
Attempting to use BulkResponseItemBase in unit testing is a bit painful at the moment as all its setters are internal.

I propose creating an interface (IBulkResponseItem?) from the public properties of BulkResponseItemBase and then changing usages of BulkResponseItemBase to use this interface e.g. Items/ItemsWithErrors properties on IBulkResponse.

Should I submit a PR for this, or am I just writing tests in the wrong way?

**Comment by russcam** [comment]
@awelburn Could you provide an example of how you're typically testing/mocking this? 

Very generally speaking, I've tended to not mock/stub responses in the past, preferring to assert the serialized form of queries in unit tests and to run integration tests for actual responses. We're in the process of pulling out the components in the Tests project that would allow spinning up a cluster (single node currently) as part of your integration tests, so this may be useful for you in the future. No ETA on when that will be finished as we're focusing on 6.0 client and Windows Installer readiness.

That aside, what you're proposing seems like a reasonable change but it wouldn't be possible to change this in the 5.x client as it would be a binary breaking change. This change could however be made against `master`, for the 6.x client. Would you like to open a PR for this?

**Comment by Mackiovello** [comment]
This problem was introduced again in https://github.com/elastic/elasticsearch-net/pull/3670. It's really hard to test classes that return `BulkResponse` now.

**Comment by simonauner** [comment]
@russcam Sorry for bringing an old thread back to life, but I wanted to provide you with an example of when I would like to mock this in a test. We do indexing with optimistic index creation, while at the same time not allowing auto-creation of indices. 

This means that we try to index documents, and if we get 404s back, then we create the index.

```csharp
// send update or delete indexing requests
var response = await _client.BulkAsync(new BulkRequest
            {
                Refresh = Refresh.True,
                Operations = operations
            }, cancellationToken);

            if (response.Items.Any(i => i.Status == 404))
            {
                indexExists = false;
            }
``` 

and if `indexExists == false`:

```csharp
var indexExistsResponse =
                await _client.Indices.ExistsAsync(new IndexExistsRequest(indexName), cancellationToken);
            if (indexExistsResponse.Exists)
                return indexName;

            var createIndexResponse = await _client.Indices.CreateAsync(indexName,
                GetIndexDescriptor(language), cancellationToken);
```

Here it would be helpful to be able to mock the response of the indexing `BulkAsync` request, since we have logic that does different things depending on what the response is.
