### ISSUE TITLE
Count api of elastic search does not support list of routing paths while Search api does.

### ISSUE THREAD

**Issue by amver7** [elastic/elasticsearch-net#2869]
**NEST/Elasticsearch.Net version**: 2.3.3

**Elasticsearch version**: 2.x

**Description of the problem including expected versus actual behavior**:
I want to use _count api to get the count of results. My current query generation logic uses _search api of ES. The thing is SearchDescriptor for _search api has component ROUTING which is list of strings (and I do need multiple routing strings for my application), while the analogous ROUTING component of CountDescriptor takes string parameter only (you can't pass a list). 
The question is : do we have a way to pass multiple routing strings to CountDescriptor by appending all the string using certain separator or any other way to handle it?

**Comment by russcam** [comment]
@amver7 The `routing` parameter method has been generated from the [Rest API spec](https://github.com/elastic/elasticsearch/blob/5.5/rest-api-spec/src/main/resources/rest-api-spec/api/count.json#L41-L44) for the endpoint. I've opened https://github.com/elastic/elasticsearch/pull/26958 to address.

You should be able to specify multiple values with a comma separated string.

**Comment by russcam** [comment]
Closing this issue as the workaround is to specify multiple values, comma separated.
