### ISSUE TITLE
Elasticsearch NEST tutorial times out after long processing

### ISSUE THREAD

**Issue by sramalingam24** [elastic/elasticsearch-net#2876]
Following along the tutorial here
https://github.com/elastic/elasticsearch-net-example/tree/5.x with elasticsearch 5.6 and changing the code as below i get response timed out exception on windows 7. All the settings are default and cluster is running on localhost:9200

```
static void IndexDumps()
{
 	   var packages = DumpReader.Dumps.Select(s=>s.NugetPackages);

            var result = Client.IndexMany(packages);

            if (!result.IsValid)
            {
                Console.WriteLine(result.OriginalException.ToString());
            }            

            Console.WriteLine("Done.");
}
```

**Comment by russcam** [comment]
@sramalingam24 Could you post on issue on https://github.com/elastic/elasticsearch-net-example/issues for this please.

**Comment by sramalingam24** [comment]
@russcam I have entered an issue, thanks.
