### ISSUE TITLE
Request for Settings as part of RolloverIndexRequest

### ISSUE THREAD

**Issue by coelacanth16** [elastic/elasticsearch-net#2879]
Feature request:

The RolloverIndexRequest class includes **Conditions**, but the rollover API allows additional **Settings** that might override any index-templates that could be inherited by the new index. For example, I would like to add search aliases to the new index in one call to .RolloverIndex instead of a second call to .Alias. Or, I want to override the shard count for the new index, because if its being rolled over at all, it must be busy.

**Comment by russcam** [comment]
Thanks for opening @coelacanth16, I've opened PR #2969 to address
