### ISSUE TITLE
Feature Request: Version in PutIndexTemplateDescriptor

### ISSUE THREAD

**Issue by coelacanth16** [elastic/elasticsearch-net#2880]
The Index-Template API supports **version** which greatly helps with configuration management. This request is to add and implement Version to the PutIndexTemplateDescriptor in the ElasticClient.PutIndexTemplate methods.

**Comment by codebrain** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-templates.html#versioning-templates

@Mpdreamz - I can add the version parameter to the descriptor quite easily, interestingly the JSON spec makes no mention of the version parameter. Shall I mention in the core team?

**Comment by codebrain** [comment]
Reference: https://github.com/elastic/elasticsearch/pull/27135
