### ISSUE TITLE
PastePreProcess is not working in IOS 11

### ISSUE THREAD

**Issue by kaviyarasanaspire** [elastic/elasticsearch-net#2885]
Hi,

We are facing an issue with the IPad after upgraded into Ios 11, 
We have some code to strip of the html code from the pasted content in the "paste_preprocess" event. But the "paste_preprocess" is not calling in IOS 11.

Can anyone suggest me the solution.

**Comment by russcam** [comment]
Hey @kaviyarasanaspire, this issue is not related to the Elasticsearch .NET clients, which this repository is related to, so I'm closing it. Please open an issue on the github repository to which your issue is related.

Thanks!
