### ISSUE TITLE
Deserializing a Common Grams Token Filter that uses a predefined word list fails

### ISSUE THREAD

**Issue by awelburn** [elastic/elasticsearch-net#2886]
**NEST/Elasticsearch.Net version**: 5.x
**Elasticsearch version**: 5.x

**Description of the problem including expected versus actual behavior**:
Following the examples here: https://www.elastic.co/guide/en/elasticsearch/guide/master/common-grams.html (I know this was written against v2, but I haven't found anything to suggest this filter has changed since?)

**Steps to reproduce**:
 1. Create a new index as per the examples in the url above, using "\_english\_" as the value for "common_words"
 2.  Create a nest client and call a method that retrieves index settings, GetIndexAsync() for example.
 3. Exception thrown!

**Provide `DebugInformation` (if relevant)**: 
 Elasticsearch.Net.UnexpectedElasticsearchClientException: Error converting value "_english_" to type 'System.Collections.Generic.IEnumerable`1[System.String]'. Path 'common_words'. ---> Newtonsoft.Json.JsonSerializationException: Error converting value "_english_" to type 'System.Collections.Generic.IEnumerable`1[System.String]'. Path 'common_words'. ---> System.ArgumentException: Could not cast or convert from System.String to System.Collections.Generic.IEnumerable`1[System.String].

**Comment by awelburn** [comment]
I'm not sure if this is the right attribute to use, but I've fixed the issue locally by adding `[JsonConverter(typeof(ReadSingleOrEnumerableJsonConverter<string>))]`

to the CommonWords property in ICommonGramsTokenFilter

**Comment by russcam** [comment]
Thanks for reporting @awelburn. This is a case where NEST only supports an array of values for `common_words`, so an index created outside of NEST using a single value will cause an exception as seen.

Applying `[JsonConverter(typeof(ReadSingleOrEnumerableJsonConverter<string>))]` will rectify this. Mind submitting a PR against `master` with this change?

**Comment by russcam** [comment]
Closing this. Will be in the next release. Thanks for opening @awelburn 👍
