### ISSUE TITLE
warning NU1603: NEST 5.5.0 depend on Newtonsoft.Json (>= 10.0.0 && < 11.0.0)，but not found Newtonsoft.Json 10.0.0

### ISSUE THREAD

**Issue by iissy** [elastic/elasticsearch-net#2887]
**NEST/Elasticsearch.Net version**:5.5.0

**Elasticsearch version**:5.5.2

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. get NEST 5.5.0 via nuget on vs 2017 update 4, .net core 2.0.2 project
 2. build
 3. found a warning like title

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Describe the feature**:

**Comment by russcam** [comment]
This has been fixed in https://github.com/elastic/elasticsearch-net/pull/2865 and will be in the next 5.x release.
