### ISSUE TITLE
Include Classic similarity in index settings

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#2890]
`CreateIndex()` allows a similarity to be set

```c#
client.CreateIndex("index", c => c
	.Similarity(s => s
		.BM25("default", ds => ds)
	)
);
```

but there appear to be two issues with this

1. No way to set the [Classic Similarity](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-similarity.html#classic-similarity) (looks like it is still referred to as Default in source)
2. Similarity settings should be under `settings.index` e.g.

```json
PUT /my_index
{
  "settings": {
    "index": {
      "similarity": {
        "default": {
          "type": "classic"
        }
      }
    }
  }
}
```

but NEST currently produces

```json
PUT http://localhost:9200/messages?pretty=true 
{
  "similarity": {
    "default": {
      "type": "BM25"
    }
  }
}
```

**Comment by Mpdreamz** [comment]
Still an issue on 5.x and 2.x

**Comment by Mpdreamz** [comment]
Backported by @russcam 👍
