### ISSUE TITLE
Create Index with Coordinates

### ISSUE THREAD

**Issue by yanwei2508** [elastic/elasticsearch-net#2895]
**NEST/Elasticsearch.Net version**:5.5

**Elasticsearch version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.  I want to Create index with model like below:
     public class company
    {

        public long id { get; set; }

        public string name { get; set; }

        public string address { get; set; }

        public long areaCode { get; set; }

        public string city { get; set; }

        public string state { get; set; }

        public string latestActivityTimestamp { get; set; }
        public location location { get; set; }
    }
    public class location
    {
        [JsonProperty(PropertyName = "lat")]
        public double latitude { get; set; }

        [JsonProperty(PropertyName = "lon")]
        public double longitude { get; set; }
    }

 2. I want to Create index it and mapping the location as GeoPoint ,I find some example like : 
internal class Location
{
    [JsonProperty(PropertyName = "lat")]
    public double Latitude { get; set; }

    [JsonProperty(PropertyName = "lon")]
    public double Longitude { get; set; }

}
and then mapping it with:
.MapFromAttributes()
    .Properties(p =>
        p.GeoPoint(s =>
            s.Name(n => n.Location).IndexGeoHash().IndexLatLon().GeoHashPrecision(12)
            )
        )

The Problem is I can not find MapFromAttributes(), IndexGeoHash() ,I don't know how to deal with my problem.

**Comment by russcam** [comment]
Hi @yanwei2508 , 

GitHub issues are reserved for bug reports and feature requests.

The best place to ask a general question is at the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Feel free to link to your question there by editing this issue.

Thanks!
