### ISSUE TITLE
Invalid query build for null or empty value

### ISSUE THREAD

**Issue by dimmasik** [elastic/elasticsearch-net#2898]
**NEST/Elasticsearch.Net version**:
5.5.0, 6.0-alpha1

**Elasticsearch version**:
5.1.2

I need to filter query by field with empty string.
My code is:
`
searchRequest.Query = new BoolQuery
{
	Should = new List<QueryContainer>
	{
		new TermQuery()
		{
			Field = "parentId",
			Value = "2"
		}
	},
	Filter = new List<QueryContainer>
	{
		new BoolQuery
		{
			MustNot = new List<QueryContainer>
			{
				new TermQuery
				{
					Field = "accessoryProductImage",
					Value = ""
				}
			}
		}
	}
};
`
So it is converted to `{"query":{"bool":{"should":[{"term":{"parentId":{"value":"2"}}}]}}}`
But if set value to MustNot for example 
`
new TermQuery
{
	Field = "accessoryProductImage",
	Value = "s"
}
`

All are ok: `{"query":{"bool":{"should":[{"term":{"parentId":{"value":"2"}}}],"filter":[{"bool":{"must_not":[{"term":{"accessoryProductImage":{"value":"d"}}}]}}]}}}`

Bug is for all query (TermQuery, MutchQuery), where value or query (keyword) is null or empty. It's not only for filter.

**Comment by russcam** [comment]
This is a feature known as [conditionless queries](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/verbatim-and-strict-query-usage.html). You can use `IsVerbatim = true` to circumvent conditionless logic

```c#
searchRequest.Query = new BoolQuery 
{ 
    Should = new List<QueryContainer> 
    { 
        new TermQuery() 
        { 
            Field = "parentId", 
            Value = "2" 
        } 
    }, 
    Filter = new List<QueryContainer> 
    { 
        new BoolQuery 
        { 
            MustNot = new List<QueryContainer> 
            { 
                new TermQuery 
                { 
                    Field = "accessoryProductImage", 
                    Value = "",
                    IsVerbatim = true // ensure this query is serialized, even though it's considered "conditionless"
                } 
            } 
        } 
    } 
};
```

**Comment by dimmasik** [comment]
Thank you.

**Comment by russcam** [comment]
No problem, thanks for raising @dimmasik 👍
