### ISSUE TITLE
ScrollAll Continues Before Retrieving All Matching Documents

### ISSUE THREAD

**Issue by SpencerLN** [elastic/elasticsearch-net#2904]
**NEST/Elasticsearch.Net version**: 5.5.0

**Elasticsearch version**: 5.6.1

**Description of the problem including expected versus actual behavior**:
ScrollAll<T> not waiting for final slice, no matter how long the maximumRunTime is set for. Instead it continues past the Wait and then requests the final slice of documents from ES.

**Steps to reproduce**:
 1. Populate index with ~3,500 documents across 3 shards.
 2. Perform ScrollAll request
```
var docList = new List<docType>();
var scrollObserver = nestClient.ScrollAll<docType>("10s", 3,
                                s => s.Search(se => se.Query(q =>
                                    +q.Term(t => t.Field(f => f.TheField).Value(true))
                                ).Size(10000)).MaxDegreeOfParallelism(1))
                            .Wait(TimeSpan.FromSeconds(15),
                                r =>
                                {
                                    docList.AddRange(r.SearchResponse.Documents.ToList());
                                });
								
return docList;
```
 3. The first two scroll requests complete almost immediately (requests# 2605 and 2610 in the screenshot). The third request to retrieve the last documents doesn't occur until after the wait period has elapsed, no matter how long the wait time is (request# 2800). 

**Provide `ConnectionSettings` (if relevant)**:
```
var nestConfig = new ConnectionSettings(connectionPool)
                .RequestTimeout(TimeSpan.FromSeconds(120))
                .DefaultIndex("index").MapDefaultTypeIndices(m => m.Add(typeof(docType), "index"));
```

![untitled](https://user-images.githubusercontent.com/6659148/32907236-f711b92e-cac4-11e7-91d4-e3d773ba26ba.png)

**Comment by Mpdreamz** [comment]
Does changing the `MaxDegreeOfParallelism(1)` to something higher than `1` have any affect?

We have integration tests to make sure `ScrollAll()` sees all the documents but I wonder if setting max degree of parallelism `1` have a bug.

**Comment by SpencerLN** [comment]
I have tried setting MaxDegreeOfParallelism to 2 and it did not resolve the issue.

In my testing each request is going to a different node of the cluster, but I don’t think that should impact anything.

**Comment by russcam** [comment]
#2930 merged into 5.x. Will be in the next release
