### ISSUE TITLE
Terminate_after parameter is not available for count api of elasticsearch

### ISSUE THREAD

**Issue by amver7** [elastic/elasticsearch-net#2905]
**NEST/Elasticsearch.Net version**: 2.3.3

**Elasticsearch version**: 5.x

**Describe the feature**:
I am using _count api of elasticsearch via nest client and I want to use the Terminate_after parameter in the countQueryDescriptor, but looks like it is not there in the descriptor class (a similar terminate_after parameter is available for SearchQueryDescriptor of _search api).
Am I missing the parameter name here or is the terminate_after parameter has been left out?
If you do not plan to support terminate_after for _count api in near future, is there a workaround for this?

**Comment by russcam** [comment]
hey @amver7, if you are using Elasticsearch 5.x, then you should upgrade NEST to 5.x (latest); [NEST 2.x is not supported or tested against Elasticsearch 5.x](https://github.com/elastic/elasticsearch-net#compatibility-matrix). 

It looks like `terminate_after` was [added to the REST API specs in Elasticsearch 5.6.4](https://github.com/elastic/elasticsearch/commit/377a43c88ced91c7f60f4fcc9c0c34f113c9f84c); we'll update the specs before releasing the next 5.x client version to include the parameter.

**Comment by amver7** [comment]
Is there a work around to use the terminate_after in nest client 2.3.3? Upgrading to Nest client 5.x is less likely to happen from our side and i do need to use the terminate after parameter.

**Comment by russcam** [comment]
This will be in the next 5.x release.

@amver7 You can workaround this in 2.x for the moment with something like

```c#
client.Count<Document>(c => 
{
    // set anything else on CountDescriptor c that you need to.    

    Nest.IRequest<Elasticsearch.Net.CountRequestParameters> r = c;
    r.RequestParameters.AddQueryString("terminate_after", 100);		
    return c;
});
```

I've opened https://github.com/elastic/elasticsearch/pull/27886 to add it to the 2.4 REST API spec.

**Comment by russcam** [comment]
Closing this as #2964 has been merged for next release.

**Comment by amver7** [comment]
It worked.
Thanks :)
