### ISSUE TITLE
Allow to specify type for `Automap` as `Type` argument

### ISSUE THREAD

**Issue by llRandom** [elastic/elasticsearch-net#2907]
**Describe the feature**:
Allow to specify type for `Automap` as `Type` argument. Currently it's only possible as a generic parameter:

    client.Map<MyType>(map => map.AutoMap());
It would be great to support something like this:

    client.Map<object>(map => map.AutoMap(typeof(MyType)));

**Comment by russcam** [comment]
@llRandom what's the use case here? How do you see this being used?

**Comment by llRandom** [comment]
I often need to define an array of types supported by index, for example, for `ConcreteTypeSelector`, or list of types for search. But I can't iterate through it do define mapping, so I have to duplicate it for `Automap` calls.
