### ISSUE TITLE
Calling Search() or Index() throws ProtocolViolationException Exception

### ISSUE THREAD

**Issue by kbandrew** [elastic/elasticsearch-net#2908]
Preview
NEST/Elasticsearch.Net version: 6.1.x

Elasticsearch version: 6.0

Description of the problem including expected versus actual behavior: Any index or search operations made using NEST result in the following error:-

ProtocolViolationException: When performing a write operation with AllowWriteStreamBuffering set to false, you must either set ContentLength to a non-negative number or set SendChunked to true.

Steps to reproduce:

Create a new ElasticClient
Call Search() or Index()
Provide ConnectionSettings (if relevant):
var settings = new ConnectionSettings(new Uri("http://localhost:9200")).BasicAuthentication("elastic", "password");

**Comment by russcam** [comment]
@kbandrew looking at this now, running the readonly cluster tests (522 integration tests) on `master`, I'm not seeing this issue. The tests can be run with
```
build.bat integrate 6.0.0 ReadOnly
```

I'll look at seeing if I can replicate with a small example, but could you provide one that reproduces it for you, including the package you're using from MyGet and the target framework?

**Comment by russcam** [comment]
OK, I can reproduce with MyGet packages 6.1.0-ci1116113135 with a small example in LINQPad. Strange that the integration tests aren't failing...

**Comment by russcam** [comment]
Integration tests were running against the netstandard1.3 version, which uses `HttpClient` and does not expose `AllowWriteStreamBuffering`. Reproduced now against Desktop CLR and will open a PR shortly

**Comment by russcam** [comment]
I've opened https://github.com/elastic/elasticsearch-net/pull/2909

**Comment by russcam** [comment]
I'm closing this issue for now as the change to `AllowWriteStreamBuffering=false` has been reverted and included in #2909.

@kbandrew the latest canary package on MyGet has the reverted change 👍
