### ISSUE TITLE
Table added inside TinyMCE always uses default font family and size even if it is changed

### ISSUE THREAD

**Issue by kaviyarasanaspire** [elastic/elasticsearch-net#2914]
Table added inside TinyMCE always uses default font family and size even if it is changed

Can anyone provide the solution for this.

**Comment by awelburn** [comment]
@kaviyarasanaspire wrong project? - looks like you need to post in https://github.com/tinymce/tinymce/issues

**Comment by russcam** [comment]
@awelburn agreed.

@kaviyarasanaspire please take a look at filing an issue on the project linked to by @awelburn .
