### ISSUE TITLE
Question: how to enable timeout for the client when connecting or sending request to server which is down

### ISSUE THREAD

**Issue by risogolo** [elastic/elasticsearch-net#2918]
**NEST/Elasticsearch.Net version**: 5.5.0

**Elasticsearch version**: 5.6.4 

**Steps to reproduce**:
 1. Send request to non existing elastticsearch
 2. You immediately have response
 
I'm expecting that the client will use some timeout properties and will use retrying mechanism. 
I have these settings on NEST side configured, but I'm getting the response immediately:

.MaxDeadTimeout(TimeSpan.FromSeconds(60))
.DeadTimeout(TimeSpan.FromSeconds(60))
.MaximumRetries(10)
.RequestTimeout(TimeSpan.FromSeconds(60)) // default 60
.MaxRetryTimeout(TimeSpan.FromSeconds(60)) // default 60

**Comment by Mpdreamz** [comment]
Are you using a single server? The client is build to fail fast not to retry indefinitely until maxretries is hit.

If you have 100 node cluster maxretries of 10 will limit how many servers a retried. If you have a 3 node cluster maxRetries of 10 will affectively be 3.

**Comment by risogolo** [comment]
Yes, I need that behavior on one instance, I'd like to retry and wait for the elastic search to to become available, not fail fast. Is it possible?

**Comment by Mpdreamz** [comment]
Hi @risogolo this is not possible and will also not be part of the client. 

Maybe a more generic retry library like: http://www.thepollyproject.org/ can help out here?
