### ISSUE TITLE
6.0 Breaking changes check

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#2923]
# [Breaking Changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking-changes-6.0.html)

## [Aggregations changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_aggregations_changes.html)

- [x] Deprecated pattern element of include/exclude for terms aggregations has been removed
- [x] Numeric to and from parameters in date_range aggregation are interpreted according to format now

## [Cat API changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_cat_changes.html)

- [x] Unbounded queue size in cat thread pool

## [Clients changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_clients_changes.html)

- [x] Java High Level REST Client

## [Cluster changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_cluster_changes.html)

- [x] Cluster name no longer allowed in path.data

## [Document API changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_docs_changes.html)

- [x] `version` type force remove - **Deleted enum value**
- [x] Upserts no longer support versions
- [x] `created` field removed in the Index API
- [x] `found` field removed in the Delete API - **Deleted property**

## [Indices changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_indices_changes.html)

- [x] Index templates use `index_patterns` instead of `template`
- [x] Shadow Replicas have been removed
- [x] Open/Close index API allows wildcard expressions that match no indices by default
- [x] Delete a document
- [x] Indices aliases api resolves indices expressions only against indices
- [x] Delete index api resolves indices expressions only against indices
- [x] Support for + has been removed in index expressions
- [x] Translog retention

## [Ingest changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_ingest_changes.html)

- [x] Timestamp meta-data field type has changed
- [x] The format of the string-formatted ingest.timestamp field has changed

## [Java API changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_java_changes.html)

- [x] `setSource` methods require XContentType
- [x] `DeleteByQueryRequest` requires an explicitly set query
- [x] `InternalStats` and `Stats` getCountAsString() method removed
- [x] `ActionRequestBuilder#execute` returns `ActionFuture` rather than `ListenableActionFuture`
- [x] `Terms.Order` and `Histogram.Order` classes replace by `BucketOrder`
- [x] `getTookInMillis()` removed in `BulkResponse`, `SearchResponse` and `TermVectorsResponse`
- [x] `GetField` and `SearchHitField` replaced by `DocumentField`
- [x] Some Aggregation classes have moved packages
- [x] Constructor for `PercentileRanksAggregationBuilder` has changed

## [Mapping changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_mappings_changes.html)

- [x] Coercion of boolean fields
- [x] The `_all` meta field is now disabled by default
- [x] The `include_in_all` mapping parameter is now disallowed - **Deleted all `IncludeInAll` and `include_in_all` references**
- [x] Unrecognized `match_mapping_type` options not silently ignored
- [x] Validation of `locale` on date fields

## [Packaging changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_packaging_changes.html)

- [x] Configuring custom user and group for package is no longer allowed
- [x] `path.conf` is no longer a configurable setting
- [x] `CONF_DIR` is no longer supported
- [x] Default path settings are removed
- [x] 32-bit is no longer maintained
- [x] `ES_JVM_OPTIONS` is no longer supported
- [x] `ES_INCLUDE` is no longer supported
- [x] Heap dump path default

## [Percolator changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_percolator_changes.html)

- [x] Deprecated percolator and mpercolate apis have been removed
- [x] The `percolator.map_unmapped_fields_as_string` setting has been deprecated

## [Plugins changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_plugins_changes.html)

- [x] Mapper attachments plugin
- [x] S3 Repository plugin
- [x] Azure Repository plugin
- [x] GCS Repository plugin
- [x] EC2 Discovery plugin
- [x] Ignoring hidden folders
- [x] ICU Analysis plugin
- [x] Plugins should not construct `Environment` instances from `Settings`

## [Reindex changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_reindex_changes.html)

- [x] `size` parameter

## [REST changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_rest_changes.html)

- [x] Unquoted JSON
- [x] Duplicate Keys in JSON, CBOR, Yaml and Smile
- [x] Content-Type Auto-detection
- [x] Boolean API parameters
- [x] Analyze API changes
- [x] Support custom normalizer in Analyze API
- [x] Indices exists API - **REST API Spec still contains paramters - https://github.com/elastic/elasticsearch/blob/6.x/rest-api-spec/src/main/resources/rest-api-spec/api/indices.exists.json. Have asked for clarification on https://github.com/elastic/elasticsearch/issues/27681.**
- [x] `timestamp` and `ttl` in index requests
- [x] Refresh requests with one or more shard failures return HTTP 500 response instead of 200
- [x] Delete by Query API requires an explicit query
- [x] DELETE document calls now implicitly create the type
- [x] Indices information APIs
- [x] Requests to existing endpoints with incorrect HTTP verb now return 405 responses
- [x] Disallow using `_cache` and `_cache_key`
- [x] IndexClosedException to return 400 status code

## [Scripting changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_scripting_changes.html)

- [x] Groovy, JavaScript, and Python languages removed
- [x] Native scripts removed
- [x] File scripts removed
- [x] Date fields now return dates
- [x] Removed access to index internal via the `_index` variable
- [x] Script Settings
- [x] `lang` can no longer be specified when using a stored script as part of a request - https://github.com/elastic/elasticsearch-net/issues/2935
- [x] `lang` can no longer be used when putting, getting, or deleting a stored script
- [x] Stored search template apis removed

## [Search and Query DSL changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_search_changes.html)

- Changes to queries:
    - [x] The collect_payloads parameter of the span_near query has been removed. Payloads will be loaded when needed.
    - [x] Queries on boolean fields now strictly parse boolean-like values. This means only the strings "true" and "false" will be parsed into their boolean counterparts. Other strings will cause an error to be thrown.
    - [x] The in query (a synonym for the terms query) has been removed
    - [x] The geo_bbox query (a synonym for the geo_bounding_box query) has been removed
    - [x] The mlt query (a synonym for the more_like_this query) has been removed.
    - [x] The deprecated like_text, ids and docs parameters (all synonyms for like) of the more_like_this query have been removed. Also the deprecated min_word_len (a synonym for min_word_length) and max_word_len (a synonym for max_word_length) have been removed.
    - [x] The fuzzy_match and match_fuzzy query (synonyma for the match query) have been removed
    - [x] The terms query now always returns scores equal to 1 and is not subject to indices.query.bool.max_clause_count anymore.
    - [x] The deprecated indices query has been removed.
    - [x] Support for empty query objects ({ }) has been removed from the query DSL. An error is thrown whenever an empty query object is provided.
    - [x] The deprecated minimum_number_should_match parameter in the bool query has been removed, use minimum_should_match instead.
    - [x] The query_string query now correctly parses the maximum number of states allowed when "determinizing" a regex as max_determinized_states instead of the typo max_determined_states.
    - [x] The query_string query no longer accepts enable_position_increment, use enable_position_increments instead.
    - [x] For geo_distance queries, sorting, and aggregations the sloppy_arc option has been removed from the distance_type parameter. **Deleted enum value**
    - [x] The geo_distance_range query, which was deprecated in 5.0, has been removed.
    - [x] The optimize_bbox parameter has been removed from geo_distance queries.
    - [x] The ignore_malformed and coerce parameters have been removed from geo_bounding_box, geo_polygon, and geo_distance queries.
    - [x] The disable_coord parameter of the bool and common_terms queries has been removed. If provided, it will be ignored and issue a deprecation warning.
    - [x] The template query has been removed. This query was deprecated since 5.0
    - [x] The percolate query’s document_type has been deprecated. From 6.0 and later it is no longer required to specify the document_type parameter.
    - [x] The split_on_whitespace parameter for the query_string query has been removed. If provided, it will be ignored and issue a deprecation warning. The query_string query now splits on operator only.
    - [x] The use_dismax parameter for the query_string query has been removed. If provided, it will be ignored and issue a deprecation warning. The tie_breaker parameter must be used instead.
    - [x] The auto_generate_phrase_queries parameter for the query_string query has been removed, use an explicit quoted query instead. If provided, it will be ignored and issue a deprecation warning.
    - [x] The all_fields parameter for the query_string has been removed. Set default_field to *` instead. If provided, default_field will be automatically set to *
    - [x] The index parameter in the terms filter, used to look up terms in a dedicated index is now mandatory. Previously, the index defaulted to the index the query was executed on. Now this index must be explicitly set in the request.
    - [x] The deprecated type and slop parameter for the match query have been removed. Instead of setting the type, the match_phrase or match_phrase_prefix should be used. The slop removed from the match query but is supported for match_phrase and match_phrase_prefix.
    - [x] The deprecated phrase_slop parameter (a synonym for the slop parameter) of the match_phrase query has been removed.
    - [x] The deprecated query parameter (a synonym for the filter parameter) of the constant_score query has been removed.
    - [x] The deprecated phrase_slop parameter (a synonym for the slop parameter) of the multi_match query has been removed.
    - [x] The deprecated prefix parameter (a synonym for the value parameter) of the prefix query has been removed.
    - [x] The deprecated le (a synonym for lte) and ge (a synonym for gte) parameter of the range query have been removed.
    - [x] The deprecated multi term rewrite parameters constant_score_auto, constant_score_filter (synonyms for constant_score) have been removed.
- [x] Search shards API
- [x] Changes to the Profile API
- [x] Scoring changes
- [x] Fielddata on `_uid`
- [x] Highlighters
- [x] `fielddata_fields`
- [x] `docvalue_fields`
- [x] `script_fields`
- [x] Inner hits
- [x] Scroll
- [x] Limit on from/size in top hits and inner hits
- [x] Scroll queries that use the request_cache are deprecated

## [Settings changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_settings_changes.html)

- [x] Remove support for elasticsearch.json and elasticsearch.yaml configuration file
- [x] Duplicate keys in configuration file
- [x] Coercion of boolean settings
- [x] Snapshot settings
- [x] Store throttling settings
- [x] Store settings
- [x] Network settings
- [x] Similarity settings
- [x] Script Settings
- [x] Discovery Settings

## [Stats and info changes](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_stats_changes.html)

- [x] Removal of `throttle_time` in the `store` stats
- [x] FS stats no longer reports if the disk spins

**Comment by codebrain** [comment]
**timestamp and ttl in index requests**
timestamp and ttl are not accepted anymore as parameters of index/update requests.

---

Really? So delete the parameters?

**Comment by codebrain** [comment]
**Refresh requests with one or more shard failures return HTTP 500 response instead of 200**
Refresh requests that are broadcast to multiple shards that can have one or more shards fail during the request now return a 500 response instead of a 200 response in the event there is at least one failure.

---

Presumably this is already handled?

**Comment by codebrain** [comment]
**Indices information APIs**
Previously it was possible to execute GET /_aliases,_mappings or GET /myindex/_settings,_alias by separating mulitple types of requests with commas in order to retrieve multiple types of information about one or more indices. This comma-separation for retrieving multiple pieces of information has been removed.. GET /_all can be used to retrieve all aliases, settings, and mappings for all indices. In order to retrieve only the mappings for an index, GET /myindex/_mappings (or _aliases, or _settings).

---

Does the client concat indices information requests together?

**Comment by codebrain** [comment]
**Requests to existing endpoints with incorrect HTTP verb now return 405 responses**
Issuing a request to an endpoint that exists, but with an incorrect HTTP verb (such as a POST request to /myindex/_settings) now returns an HTTP 405 response instead of a 404. An Allow header is added to the 405 responses containing the allowed verbs.

---

Given that a 405 is not a success code, the client should behave as expected and fail the request. But it might be nice to inspect the HTTP headers on a 405 and provide this information to the user.

**Comment by codebrain** [comment]
**IndexClosedException to return 400 status code**
An IndexClosedException is returned whenever an api that doesn’t support closed indices (e.g. search) is called passing closed indices as parameters and ignore_unavailable is set to false. The response status code returned in such case changed from 403 to 400.

---

A previous breaking change indicates that `ignore_unavailable` has been removed, and it should now internally use the default value (false). Therefore is it safe to assume the client will behave with the 400 status code?

**Comment by tdoman** [comment]
@codebrain Where did `ConnectionSettings.MapDefaultTypeIndices` go?  I see `InferMappingFor<T>` is there but that requires me to do something at compile time that I was previously able to do at run time from another list I'm already required to create to keep track of other things per index (ie. search fields and aggregations I use, etc.).

**Comment by codebrain** [comment]
**Search and Query DSL changes**
The deprecated type and slop parameter for the match query have been removed. Instead of setting the type, the match_phrase or match_phrase_prefix should be used. The slop removed from the match query but is supported for match_phrase and match_phrase_prefix.

---

Should it be removed from `IMultiMatchQuery`?

**Comment by codebrain** [comment]
**fielddata_fields**
The deprecated fielddata_fields have now been removed. docvalue_fields should be used instead.

---

Still present on _NodesStats_ and _IndicesStats_ - is this correct?

**Comment by Mpdreamz** [comment]
@codebrain 

**timestamp and ttl in index requests**, yes these should be removed. deprecated in 2.x they were kept around in 5.x for 2.x indices that moved over.

**Refresh requests with one or more shard failures return HTTP 500 response instead of 200** 
**IndexClosedException to return 400 status code**
These should both be handled with the new response deserialization handling in `master`.

**Requests to existing endpoints with incorrect HTTP verb now return 405 responses**
These should be covered by the low level client autobaking the correct verbs. None of our integration tests unearthed this either.

**fielddata_fields**

Yes these should still be returned by the stats API, you can no longer select them to be returned as part of the search but they can still be used to drive aggregations

**Comment by codebrain** [comment]
@Mpdreamz - Have asked about `ttl` parameters (and timestamp) as they still seem to be present in the REST specs: https://github.com/elastic/elasticsearch/search?utf8=%E2%9C%93&q=Expiration+time+for+the+document

**Comment by russcam** [comment]
@codebrain They should have been removed from the REST API spec. Would you like to open a PR to remove them (against elasticsearch master)? Typical flow would be to

1. fork elasticsearch to your own account
2. [set up elastic/elasticsearch as upstream for the fork](https://help.github.com/articles/configuring-a-remote-for-a-fork/)
3. branch from fork master
4. Make REST API changes.
5. Open PR from fork to upstream/master.

**Comment by codebrain** [comment]
Removed TTL and Timestamp from requests: https://github.com/elastic/elasticsearch/pull/27888

Will need to pull & re-gen REST specs when I backport to 6.x branches.

**Comment by codebrain** [comment]
Merged ttl & timestamp removal into elasticsearch:master and backported to elasticsearch:6.x, 6.0 and 6.1

**Comment by codebrain** [comment]
The _all meta field is now disabled by default

---

Since this can be re-enabled I have left it in the codebase.

**Comment by Mpdreamz** [comment]
> Deprecated percolator and mpercolate apis have been removed

Already removed as part of https://github.com/elastic/elasticsearch-net/pull/2680

**Comment by Mpdreamz** [comment]
> Stored search template apis removed

https://github.com/elastic/elasticsearch-net/pull/2951 covers this, the crud api's have been removed but render search template API still exists.

https://www.elastic.co/guide/en/elasticsearch/reference/6.x/search-template.html

**Comment by Mpdreamz** [comment]
> The index parameter in the terms filter, used to look up terms in a dedicated index is now mandatory. Previously, the index defaulted to the index the query was executed on. Now this index must be explicitly set in the request.

No action required on our end, fall back to server validation here.

**Comment by Mpdreamz** [comment]
> The deprecated type and slop parameter for the match query have been removed. Instead of setting the type, the match_phrase or match_phrase_prefix should be used. The slop removed from the match query but is supported for match_phrase and match_phrase_prefix.

In 5.x we rely on `type` but in 6.x we have already moved to explicitly named  `match_*` queries into separate entities and removing deprecated properties as per https://github.com/elastic/elasticsearch-net/pull/2515

**Comment by Mpdreamz** [comment]
> Fielddata on _uid

No client action needed here.

**Comment by Mpdreamz** [comment]
@codebrain guess we can close this :cake: 🚢 :it:

**Comment by piaste** [comment]
Sorry to spoil the party, but the Serilog sink (which relies on elasticsearch.net) encounters a breaking change moving from 5.x to 6.0:

https://github.com/serilog/serilog-sinks-elasticsearch/issues/147
