### ISSUE TITLE
ConnectionSettings.MapDefaultTypeIndices in NEST 6.x

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch-net#2926]
Hello all, I'm trying out the bleeding edge here and testing NEST 6.x w/ ES 6.  I'm using NEST 6.1.0-ci1205045848.

Where did ConnectionSettings.MapDefaultTypeIndices go?  I see `InferMappingFor<T>` is there but that would require me to do something at compile time that I was previously able to do at run time from another list that I'm already required to create to keep track of for other per index things (ie. search fields and aggregations I use, the `Type`, index name, etc.).  For example, "IndexTypes" is that list, so I can do the following:
`IndexTypes.ForEach(x => settings.MapDefaultTypeIndices(d => d.Add(x.Type, x.Index)));`
What's the 6.0 way?

**Comment by russcam** [comment]
Hey @tdoman, it looks like we should look at exposing a non-generic `InferMappingFor()` method that allows `Type` to be passed.

In the meantime, connection settings can be cast to `IConnectionSettingsValues` interface to add the mappings directly

```c#
    var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
    var connectionSettings = new ConnectionSettings(pool);

    IConnectionSettingsValues settings = connectionSettings;   
    settings.DefaultIndices.Add(typeof(Message), "foobar");

    var client = new ElasticClient(connectionSettings);
```

**Comment by tdoman** [comment]
@russcam Ok, thanks Russ I'll do that until there's a non-generic `InferMappingFor()`.  BTW, I assume that even after types go away in 7.0, we'll still need a way to specify which POCO to use for each index via NEST no?
On a separate note, as far as I can tell, https://github.com/elastic/elasticsearch-net/issues/2927 is my only blocker from having all the functionality that we use working in an ES 6.0 system.  Once I get past that I may discover something else but we're close.

**Comment by Mpdreamz** [comment]
Thanks for opening this @tdoman, opened https://github.com/elastic/elasticsearch-net/pull/2934 to address this.
