### ISSUE TITLE
Script "File" should be gone, "Id" available in latest NEST 6.0 build

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch-net#2927]
Hello all, I'm trying out the bleeding edge here and testing NEST 6.x w/ ES 6. I'm using NEST 6.1.0-ci1205045848.

Based upon this list: https://github.com/elastic/elasticsearch-net/issues/2923, I was expecting that with the latest build something like the following would not build and that I'd have to switch to stored scripts.  However, it builds and "Id" is not available.
`            var response = await client.UpdateAsync<T, object>(id, u => u.Index("my_index").Type("my_type").Lang("painless").Script(s => s.File(scriptFile).Params(parms)).RetryOnConflict(5));`

**Comment by tdoman** [comment]
@russcam Here's another example:
`searchDescriptor = searchDescriptor
                        .Sort(s => s
                            .Script(ss => ss
                                .Script(sd => sd
                                    .File("mysort")
                                    .Lang("painless"))
                                    .Type("number")
                                    .Order((SortOrder)SortDirection)))
                        .Sort(s => s.Field(f => f.Field("name.keyword").Ascending()));`

**Comment by Mpdreamz** [comment]
`Indexed` is the descriptor method to use to refer to an indexed script, in retrospect `Id()` is better and there for I obsoleted `Indexed` and added `Id()`. 

Removed all script file related properties/methods as per https://github.com/elastic/elasticsearch-net/pull/2933

Thanks for reporting these while you upgrade, super super helpful 👍

**Comment by tdoman** [comment]
@Mpdreamz Thanks Martijn, I appreciate you taking care of the issues I'm discovering.  I grabbed today's build but looks like it's not there yet but I'm staying on the bleeding edge.  We're excited to get to 6.0, we're coming all the way from 1.7.5 in one leap.

**Comment by russcam** [comment]
Merged #2933 into master
