### ISSUE TITLE
.Lang() not allowed to be specified as parameter in 6.0 on update request.

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch-net#2935]
NEST 6.1.0-ci1208153011

The NEST library allows it to be specified but ES 6.0 responds with:
"request [/myindex/mytype/1/_update] contains unrecognized parameter: [lang]"

`var response = await client.UpdateAsync<T, object>(id, u => u.Index(index).Type(type).Lang("painless").Script(s => s.Indexed(scriptFile).Params(parms)).RetryOnConflict(5));`

**Comment by tdoman** [comment]
I'm seeing this in some other contexts in my code as well where the .Lang() function is being exposed in script contexts where it shouldn't.  [lang can no longer be specified...](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_scripting_changes.html#_literal_lang_literal_can_no_longer_be_specified_when_using_a_stored_script_as_part_of_a_request)

**Comment by russcam** [comment]
Hey @tdoman, `Lang()` is allowed in the body, but not as a query string parameter.
Merged 6.x script changes in #2951 and #2933.

Thanks for reporting this 👍

**Comment by russcam** [comment]
Apologies @tdoman, my last comment was incorrect. `Lang()` is not allowed in places that reference a script. It is allowed in the Put Script API

**Comment by tdoman** [comment]
@russcam Yep, NEST had been allowing me to specify `.Lang()` but ES 6.0 was rejecting it as a query string parameter.  Thanks for fixing all these, are they in the 12/14 build?  If so, I can try 'em all out.  I believe this will also represent 100% coverage on all our current usages, woot!

**Comment by tdoman** [comment]
@russcam I grabbed the 12/14 build, looks great!  Just more thorough testing to do, thanks for all the work, looking forward to the official ship of NEST 6.0!

**Comment by russcam** [comment]
@tdoman [NEST-6.0.0-beta1 is up on Nuget](https://www.nuget.org/packages/NEST/6.0.0-beta1) if you're like to take that for a spin; it's very near to what we expect to be in the GA release and we have released it to nuget in order to garner wider feedback.

**Comment by tdoman** [comment]
Sweet, I will pull that from Nuget and give it a spin, thanks Russ!
