### ISSUE TITLE
Upsert support in Bulk Update 0.11.0.0

### ISSUE THREAD

**Issue by nariman-haghighi** [elastic/elasticsearch-net#294]
Hi Martin;

It looks like your latest release now supports bulk partial updates w/ upsert?

I had a look at the basic example here:

http://nest.azurewebsites.net/core/update.html

But am not able to reproduce the upsert query shown in this example:

http://elasticsearchserverbook.com/elasticsearch-0-90-1-updates-in-bulk-api/

```
{ "update": {"_index": "library", "_type": "book", "_id": "5"}}
{ "script" : "ctx._source.available = param1", "params" : {"param1" : false}, "upsert": {"title": "Mastering ElasticSearch", "available": false}}
```

Does NEST support the query above at the moment? Any thoughts around performance differences between this approach and a standard .IndexMany()?

Regards,
N.

**Comment by chopki01** [comment]
I'm actually running into this same issue, how did you end up performing this type of update in bulk? Single updates work for me, but the bulk processing with this or IndexMany both don't work for me.
