### ISSUE TITLE
Ignore base class properties during auto mapping in ElasticSearch using NEST

### ISSUE THREAD

**Issue by nkdev89** [elastic/elasticsearch-net#2945]
I'm working on Elastic Search 5.4 and using NEST to create index in C#, When i do a automap for a class which in Inheriting from SortedDictionary, The base class properites like Count,Comparer,Items are added to the Mapping, Can some one please help me how to avoid this.

Thanks

```
 public class Document : SortedDictionary<string, dynamic>
 {
    public int Id { get; set; }
 }
```
The actual mapping I'm getting is

```
{"DocumentMapping": {
"mappings": {
  "Document": {
    "dynamic": "strict",
    "_all": {
      "enabled": false
    },
    "properties": null,
    "Documents": {
      "properties": {
        "Comparer": {
          "type": "object"
        },
        "Count": {
          "type": "integer"
        },
        "Item": {
          "type": "object",
          "include_in_all": false
        },
        "ID": {
          "type": "int "
        }
      }
    }
  }
}}}
```
What i need is

```
{"DocumentMapping": {
"mappings": {
  "Document": {
    "dynamic": "strict",
    "_all": {
      "enabled": false
    },
    "properties": null,
    "Documents": {
      "properties": 
        "ID": {
          "type": "int "
        }
      }
    }
  }
}}}
```
How do i ignore the the Comparer,Count and Item from my mapping JSON.

**Comment by Mpdreamz** [comment]
I initially started a reply saying you can totally do this using [the `visitor` that you can supply to `AutoMap()`](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/visitor-pattern-mapping.html) then proceeding to draft an example I was shocked. "no you can't!"

I've opened #3001 which will make this possible in the next `5.x` and `6.x` releases.
