### ISSUE TITLE
paste_preprocess is not working in IOS 11

### ISSUE THREAD

**Issue by kaviyarasanaspire** [elastic/elasticsearch-net#2952]
Hi,
paste_preprocess is not working in IOS 11, is there any issue or did we changed the logic to handle in some other way.

Paste image itself is not working in IOS 11, but I handled that by having the code "var clipboardContent = getClipboardContent(Env.iOS ? e.originalEvent : e);" in editor.on('paste', function (e)  event.

Can anyone give me the solution for this.

**Comment by Mpdreamz** [comment]
wrong repository my friend.
