### ISSUE TITLE
Failed to compile inline script [ctx._source.LastModified='2017-12-13T09:45:37.547+02:00'] using lang [painless]

### ISSUE THREAD

**Issue by rm2k** [elastic/elasticsearch-net#2961]
**NEST/Elasticsearch.Net version**: 6.0.0-alpha1

**Elasticsearch version**: 5.6.3

**Description of the problem including expected versus actual behavior**:

  I seldom get this error message:

    Failed to compile inline script [ctx._source.LastModified='2017-12-13T09:45:37.547+02:00'] using lang [painless]

**Steps to reproduce**:
I'm not quite sure if it's reproduceble as I don't get it often, but my query looks like:

    var now = DateTime.Now;
    var nowString = string.Format("{0:yyyy-MM-ddTHH:mm:ss.fffzzzz}", now);
    var myScript = $"ctx._source.LastModified='{nowString }'";

    var myUpdateRequest = new UpdateByQueryRequest(Indices.Index(myIndices))
    {
      Conflicts = Conflicts.Proceed,
      IgnoreUnavailable = true,
      Query = new IdsQuery
      {
        Values = new List<Id>(myIds.Select(id => new Id(id)))
      },
      Script = new InlineScript(myScript)
    };

    var result = await _client.UpdateByQueryAsync(myUpdateRequest );

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

    result.ApiCall.ServerError.Error.Reason:
    Failed to compile inline script [ctx._source.LastModified='2017-12-13T09:45:37.547+02:00'] using lang [painless]

**Describe the feature**:

**Comment by russcam** [comment]
@rm2k NEST 6.x is not compatible with Elasticsearch 5.x; please use the latest NEST 5.x version with Elasticsearch 5.6.3.

Are you executing many Painless scripts concurrently? Is there anything in the Elasticsearch logs? I suspect you may be [hitting the max number of compilations per minute](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/modules-scripting-using.html#prefer-params) since the script you're sending needs to be compiled each time.

Take a look at parameterizing the script and passing the `nowString` value as a parameter. The script only needs to be cached once in this case:

```c#
var now = DateTime.Now;
var nowString = string.Format("{0:yyyy-MM-ddTHH:mm:ss.fffzzzz}", now);
var myScript = "ctx._source.LastModified='params.now'";

var myUpdateRequest = new UpdateByQueryRequest(Indices.Index(myIndices))
{
    Conflicts = Conflicts.Proceed,
    IgnoreUnavailable = true,
    Query = new IdsQuery
    {
        Values = new List<Id>(myIds.Select(id => new Id(id)))
    },
    Script = new InlineScript(myScript)
    {
        Params = new Dictionary<string, object>
        {
            { "now", nowString }
        }
    }
};

var result = await _client.UpdateByQueryAsync(myUpdateRequest);
```

**Comment by rm2k** [comment]
@russcam yeah. I run the scripts for a couple of users requests, it might be that i'm hitting the max number. 

Unfortunately I only ever logged `ApiCall.ServerError.Error.Reason` in my code, and I haven't met the error again yet. I'm not sure how to check ES logs. 

In any case I'll give your your suggestion a shot.

**Comment by russcam** [comment]
@rm2k any progress?

**Comment by rm2k** [comment]
Hi @russcam I incorporated your suggestions, and now keeping a close eye on how things pan out. So I'm closing the issue in the meantime.
