### ISSUE TITLE
NEST 6.0 Beta: JsonProperty attribute not working?

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch-net#2972]
I'm performing a `BulkUpdateOperation` w/ `DocAsUpsert=true`.  The POCO looks something like this:
```
public class MyThing
{
   [JsonProperty("kumquat")]
   public string Foo { get; set; }
}
```
I've set the mapping to `"dynamic": "strict"` w/ the "kumquat" field mapped as "text".  When I go to perform the update, I get the following error from the ES 6.0 server:
`Type: strict_dynamic_mapping_exception Reason: \"mapping set to strict, dynamic introduction of [foo] within [my_index] is not allowed\"`

On the search side, these (ie. JsonProperty attributes) seem to work (ie. we map "_id" to "Id", etc.) but I think this may be the only one we actually use on the update side and previously had some indexes (including this index) as `"dynamic": "false"` so we may never have noticed.  Should this work or is there something I'm doing wrong?

**Comment by tdoman** [comment]
My bad, I had to switch to `[Text(Name = "kumquat")]` and it appears to work just fine now.

**Comment by russcam** [comment]
@tdoman if you simply want to name the field differently to the POCO, there's also `[Rename("kumquat")]`. Taking this approach, you can still use automapping and not have to specify the explicit type.

**Comment by tdoman** [comment]
Thanks @russcam, after I made that change last night, I realized I still didn't know what to do now for a non-text field to rename it, perfect!
