### ISSUE TITLE
Create a new backup repository using NEST 6.0?

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch-net#2974]
I posted this on stackoverflow thinking there might be some like positioned people w/ an answer but I'm thinking this may be the best place since I think it may also be a piece of functionality missing from the NEST library.  Here's the link and I'll include the entire question below as well: [Create a new backup repository for elasticsearch using NEST?](https://stackoverflow.com/questions/47874239/create-a-new-backup-repository-for-elasticsearch-using-nest)

For my ES backups, I use the Azure repository plugin. So far, I've just been using a scheduled task that uses **CURL** to issue my desired commands but I want to do this in a **WebJob**. Using the NEST library, I see that I can request a new `.Snapshot()` which is the second half of what I've been doing but I also want to periodically (every month) create a full backup. So, before I invoke the snapshot, I make sure the current month's repository is created something like so:
```
PUT _snapshot/es-2017-12
{
  "type": "azure",
  "settings": {
    "container": "elasticsearch-backups",
    "base_path": "60-2017-12"
  }
}
```
After that I do a snapshot to that location and the first time it's invoked in the month, I get a full backup and then snapshots every day during the month until the next month begins.  Is there a NEST-based approach to doing this?  If not, should there be?  Or do I just have to send a raw request? If raw, so far, I've never needed to make a raw request, could this particular request even be made via a `RawQuery()` (ie. I need to issue a `PUT`)? If so, can you provide an example?

**Comment by Mpdreamz** [comment]
You can call:

```csharp
client.CreateRepository(new CreateRepositoryRequest(_name)
{
	Repository = new AzureRepository()
	{
		Settings = new AzureRepositorySettings
		{
			Container = "foocontainer",
			BasePath = "foopath",
			Compress = true,
			ChunkSize = "64mb"
		}
	}
});
```

To create an azure repository.

**Comment by tdoman** [comment]
Fantastic, thanks Martijn!  I really appreciate your support.
