### ISSUE TITLE
6.0 beta 1, index a JObject

### ISSUE THREAD

**Issue by jchonc** [elastic/elasticsearch-net#2975]
**NEST/Elasticsearch.Net version**: 6.0 (beta1)

**Elasticsearch version**: 6.0.1

**Description of the problem including expected versus actual behavior**:
We have piece of code working in 5.5, but stopped working in 6.0 (beta1)

`
 dynamic doc = new JObject();
            doc.name = "jian";
            doc.age = "12";
            dynamic pet = new JObject();
            doc.pet = pet;
            pet.name = "oreo";
            pet.color = "black&white";
            var result = client.Index(new IndexRequest<object>(doc, indexName, "doc", Guid.NewGuid()));
`
It seems the refactor of JSON serializer affected it. 

However, the following code works via lowLevel
`PostData s = Newtonsoft.Json.JsonConvert.SerializeObject(doc);
            var result = client.LowLevel.Index<IndexResponse>(indexName, "doc", Guid.NewGuid().ToString(), s);`

**Steps to reproduce**:
 1.  Create a project using NEST 5.5, the above code should insert a doc into {indexName}
 2.  Update to 6.0, run the same code and check doc in ES, all attributes are empty [] now 
 
**Provide `ConnectionSettings` (if relevant)**:
N/A

**Provide `DebugInformation` (if relevant)**:
N/A

**Describe the feature**:

**Comment by Mpdreamz** [comment]
This is expected as per `6.x` the client no longer depends on NewtonSoft.Json so has no knowledge of `JObject`

You can either switch to `ExpandoObject`

```csharp
dynamic doc = new ExpandoObject();
doc.name = "jian";
doc.age = "12"; 
dynamic pet = new ExpandoObject();
doc.pet = pet; 
pet.name = "oreo";
pet.color = "black&white";
var result = client.Index(new IndexRequest<object>(doc, "temp", "doc", Guid.NewGuid()));
```

Or reference `Nest.JsonNetSerializer` and use the following:

```csharp
var connectionPool = new SingleNodeConnectionPool(new Uri("http://ipv4.fiddler:9200"));
var connectionSettings = new ConnectionSettings(connectionPool, 
        (b, s) => new JsonNetSerializer(b, s, () => new JsonSerializerSettings())
     )
    .EnableDebugMode();
var client = new ElasticClient(connectionSettings);

dynamic doc = new JObject();
doc.name = "jian";
doc.age = "12";
dynamic pet = new JObject();
doc.pet = pet;
pet.name = "oreo";
pet.color = "black&white";
var result = client.Index(new IndexRequest<object>(doc, "temp", "doc", Guid.NewGuid()));
Console.WriteLine(result.DebugInformation);          
```

There is however a bug in the `JsonNetSerializer` the way its published in `6.0.0-beta1` that prevents you to use it right now. 

The reason the low level client works is because you send it as `string`.

Thanks for opening this issue and trying out the beta 👍
