### ISSUE TITLE
NEST 2.4.6 BulkDescriptor.Update hangs on dynamic objects

### ISSUE THREAD

**Issue by SLavrynenko** [elastic/elasticsearch-net#2981]
**NEST/Elasticsearch.Net version**: 2.4.6

**Elasticsearch version**: 2.4.1

I need to do partial updates in a bulk, so have the following code:

```
var descriptor = new BulkDescriptor();

var str = "{  \"Location\": null,  \"Id\": \"1_1\",  \"ContactId\": 1,  \"ClientId\": 1}";                        
var partialObject = JsonConvert.DeserializeObject<dynamic>(str);

// This works fine
var response = client.Update<MyType, object>(DocumentPath<MyType>.Id("1_1").Index("Index1"),u => u.Doc(partialObject));

// This works fine also
descriptor.Update<MyType, dynamic>(
  op => op
    .Index("Index1")
    .Id("1_1")
    .Doc(new { Id = "1_1", ContactId = 1, ClientId = 1 })
    .DocAsUpsert());

// Here it takes forever to process (looks like it gets into infinitive loop) without any exception
descriptor.Update<MyType, dynamic>(op => op.Index("Index1").Id("1_1").Doc(partialObject).DocAsUpsert());

```

Some notes:
It looks that it happens because I've "Location": nul field on my dynamic. But why then it works fine with the Update method (not in a BulkDescriptor)

I need partial update to update all the fields on my object even if they are null. I can't use an exact type because I have a big type that is stored at Elastic index so I'm building dynamic object with those fields that I really need to update.

**Comment by SLavrynenko** [comment]
just verified that the same issue exists in 2.5.6 version of NEST

**Comment by russcam** [comment]
This looks to be the same issue as #2244 and #937 and is related to dynamic dispatch.

The solution is to cast the `dynamic` type to `object` i.e.

```c#
descriptor.Update<MyType, dynamic>(op => op.Index("Index1").Id("1_1").Doc((object)partialObject).DocAsUpsert());
```

**Comment by manX7710237872** [comment]
> **NEST/Elasticsearch.Net version**: 2.4.6
> 
> **Elasticsearch version**: 2.4.1
> 
> I need to do partial updates in a bulk, so have the following code:
> 
> ```
> var descriptor = new BulkDescriptor();
> 
> var str = "{  \"Location\": null,  \"Id\": \"1_1\",  \"ContactId\": 1,  \"ClientId\": 1}";                        
> var partialObject = JsonConvert.DeserializeObject<dynamic>(str);
> 
> // This works fine
> var response = client.Update<MyType, object>(DocumentPath<MyType>.Id("1_1").Index("Index1"),u => u.Doc(partialObject));
> 
> // This works fine also
> descriptor.Update<MyType, dynamic>(
>   op => op
>     .Index("Index1")
>     .Id("1_1")
>     .Doc(new { Id = "1_1", ContactId = 1, ClientId = 1 })
>     .DocAsUpsert());
> 
> // Here it takes forever to process (looks like it gets into infinitive loop) without any exception
> descriptor.Update<MyType, dynamic>(op => op.Index("Index1").Id("1_1").Doc(partialObject).DocAsUpsert());
> 
> ```
> 
> Some notes:
> It looks that it happens because I've "Location": nul field on my dynamic. But why then it works fine with the Update method (not in a BulkDescriptor)
> 
> I need partial update to update all the fields on my object even if they are null. I can't use an exact type because I have a big type that is stored at Elastic index so I'm building dynamic object with those fields that I really need to update.
www.2244.ńet/MSN/se-sv
