### ISSUE TITLE
BulkDescriptor.UpdateMany<T>  missing document

### ISSUE THREAD

**Issue by YoungL1107** [elastic/elasticsearch-net#2984]
**NEST/Elasticsearch.Net version **: 5.6.0

**Elasticsearch version**:  5.6.0

**Description of the problem including expected versus actual behavior**:
BulkDescriptor.UpdateMany  request missing doc.

**Steps to reproduce**:
 1. use ElasticClient.CreateIndex() method create index
 2. ElasticClient.Bulk(bd => bd.CreateMany )
 3. ElasticClient.Bulk(bd => bd.UpdateMany<T>)

                var bulkResult = client.Bulk(bulk => bulk
                    .Refresh(Refresh.True)
                    .UpdateMany(bulkSet, (bc, d) => bc.Id(ids[d]).Type(typeName))
                );

**Provide `DebugInformation` (if relevant)**:
Invalid NEST response built from a unsuccessful low level call on POST: /_bulk
# Invalid Bulk items:
# Audit trail of this API call:
 - [1] BadResponse: Node: http://web-datacenter.emapd.com:9200/ Took: 00:00:00.1120015
# ServerError: ServerError: 400Type: action_request_validation_exception Reason: "Validation Failed: 1: script or doc is missing;2: script or doc is missing;"
# OriginalException: System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Elasticsearch.Net.HttpConnection.Request[TReturn](RequestData requestData) in C:\Users\russ\source\elasticsearch-net-5.x\src\Elasticsearch.Net\Connection\HttpConnection.cs:line 163
# Request:
{"update":{"_index":"test_2017.12.22_15:49:38","_type":"test","_id":"ad60bd9b-1aa9-4710-94a4-63f5c11baf95"}}
{}
{"update":{"_index":"test_2017.12.22_15:49:38","_type":"test","_id":"d81cccf5-ee76-4b26-9698-7ca80453b53a"}}
{}

# Response:
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: script or doc is missing;2: script or doc is missing;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: script or doc is missing;2: script or doc is missing;"},"status":400}

**Comment by Mpdreamz** [comment]
Hi @YoungL1107 

Sorry for taking a while to respond. You need to explicitly call  `.Doc()` or `.Script()` on the update descriptor.

```csharp
.UpdateMany(bulkSet, (bc, d) => bc.Id(ids[d]).Type(typeName).Doc(d))
```

NEST can not assume how you want to update the document.

**Comment by YoungL1107** [comment]
thanks for your response. it works.
