### ISSUE TITLE
ES 6.0, 6.1 and NEST

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch-net#2994]
Hey guys, not to distract from the NEST 6.0 effort but I wanted to try to get a glimpse of the plan for NEST beyond 6.0.  I assume that your current work targets ES 6.0 and that breaking changes for ES 6.1 will be targeted separately, is this correct?  Under that assumption, we'll target ES 6.0.x for the near future.

**Comment by Mpdreamz** [comment]
Elasticsearch 6.1 and NEST 6.1 won't have breaking changes. When we release 6.0.0 GA it will be tested against 6.0.0 and 6.1.0 (which we do now too). 

NEST 6.1 will have focus on new features from Elasticsearch 6.1 (such as the very cool composite aggregation see: #2902).

so if you are planning an upgrade you should be able to jump to Elasticsearch 6.1.0 with NEST 6.0. 

Hope this clarifies things @tdoman 😄

**Comment by tdoman** [comment]
@Mpdreamz Yes, thank you, I should have been clearer but that's precisely what I wanted to know!  As such, we'll try out ES 6.1 w/ the current NEST 6.0 beta (v6.0.0-beta1) library from NuGet.

FWIW, I could have sworn I saw a 6.1 breaking changes doc but I can't find it now.  However, the one change I have seen that I had assumed would be breaking in ES 6.1 that we use in our code is nested sorting: [ES 6.1: Nested sorting examples](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/search-request-sort.html#_nested_sorting_examples).
Sounds like the old nested sorting method will continue to be supported for a time?  Namely: [ES 6.0: Nested sorting examples](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/search-request-sort.html#_nested_sorting_example).
