### ISSUE TITLE
Cannot serialize/deserialize document containing a JoinField without an ElasticClient/SourceSerializer on hand

### ISSUE THREAD

**Issue by badpp** [elastic/elasticsearch-net#2995]
**NEST/Elasticsearch.Net version**: 6.0.0-beta1

**Elasticsearch version**: 6.1.1

**Problem**:
In Elasticsearch.NET/NEST <= 5.x we never had issues to serialize/deserialize a document using a Newtonsoft directly. We have plenty of document POCOs enriched with ElasticSearch properties. Even we don't expose this POCOs to an API or presentation layer directly, we move this documents from one to another micro service in various locations (by Newtonsoft.JsonConvert.SerializeObject), additionally the documents are serialized to a long term storage for historical reasons. Most of the micro services don't have access to the data access layer.

Serializing a child or parent document by
```
var child = new SampleChild()
{
    MyJoinField = JoinField.Link<SampleChild>(Guid.NewGuid().ToString("N"))
};
var jsonString = Newtonsoft.Json.JsonConvert.SerializeObject(child);
```
will just produce
```"MyJoinField":{},```

Furthermore, in the business layer we are using various Json tools like diffs and merges and having the need to serialize and deserialize the documents at any time.

**Steps to reproduce**:
 1. Create parent / child class with a base class containing the JoinField.
 2. Creat a child document and serialize it.
 3. Check serialized string -> ```{}```
 4. Deserialize, of course the JoinField information is missing.

See sample source:
[JoinFieldDeserializeProblem.txt](https://github.com/elastic/elasticsearch-net/files/1592896/JoinFieldDeserializeProblem.txt)
 
Question:
Is there anyway around this? 
- creating our own Newtonsoft serializer settings and adding the necessary converters?
- defining a join field only by attribute?

**Comment by badpp** [comment]
Great, that's good news!

**Comment by Mpdreamz** [comment]
You should be able to add `new HandleNestTypesOnSourceJsonConverter(client.RequestResponseSerializer)` to your JsonConverter in the next release to have the NEST types that can appear on your source serialized by NEST routines.
