### ISSUE TITLE
Autocomplete using important terms from large text field

### ISSUE THREAD

**Issue by debzzone** [elastic/elasticsearch-net#2996]
I am a newbie with elasticsearch and NEST, and in my exploration phase. Currently I am ingesting some attachment types to search and highlight from its content field (analyzed text). Now I want to implement autocomplete suggestions so that if user types some phrase it suggests the top N best-suited completion matches for that phrase from the attachment contents. I looked into some edge ngrams examples but they are dealing with keyword fields like title, name etc. In my case these could be large text fields from which the phrase has to be searched and autocompleted. Any working example would be great, if not at least if some one can guide me towards the possible approaches.

One feature that seems to be close to my requirement is SignificantText. But unfortunately that is not available with NEST at this moment.

**Comment by zabihy** [comment]
I have the same issue

**Comment by fannairu** [comment]
Hi guys, do you have a solution now? I have the some issue. Should we have a word segmentation first and then insert all words to the elastic suggestions

**Comment by zabihy** [comment]
Follow this instruction steps:

**Comment by zabihy** [comment]
follow this instruction steps: [http://www.bilyachat.com/2015/07/search-like-google-with-elasticsearch.html](url)

You need to have a few changes to index mapping according on the basis of new ElasticSearch version: "fielddata":true for autocomplete field like this: [https://gist.github.com/jinkyou/ac92c0d9fc53860b703ac773af03b0da](url)

To do a suggestion, you need to query like this:
`POST: /YOUR_INDEX/_search`
`{
  "size": 0,
  "aggs": {
    "autocomplete": {
      "terms": {
        "field": "autocomplete",
        "order": {
          "_count": "desc"
        },
        "include": "c.*"
      }
    }
  },
  "query": {
    "prefix": {
      "autocomplete": {
        "value": "c"
      }
    }
  }
}`

**Comment by fannairu** [comment]
@zabihy thanks, just need to set "fielddata":true and add aggs to query.

**Comment by debzzone** [comment]
"fielddata":true has its own consequences. 
I am using the ingest-attachment plugin that extracts the text out of the attachments and populates the index. Also used some analyzers and mapped them. The search/suggest etc. works fine and will continue to make them more precise. But the part I am stuck with is completion for partially typed phrases. I agree that the phrases should best be domain specific. But to start with, what I am looking for is a way to scan the extracted texts and keep the most important keywords (ranked based on some scoring strategy) ready. I think significant text aggregation does exactly the same: https://www.elastic.co/guide/en/elasticsearch/reference/master/search-aggregations-bucket-significanttext-aggregation.html. But unfortunately it is not available with NEST(6.0.0.0). Will it be available in any future release or a CI build?

**Comment by russcam** [comment]
@debzzone Significant Text Aggregation was [added in NEST 6.1.0](https://github.com/elastic/elasticsearch-net/releases/tag/6.1.0)

For autocomplete on large text fields, it depends on what the expectation is for how autocompletion should work:
1. should it only work from the start of the text i.e. prefix
2. should it work from the start of any term within the text
3. should it work for any part of a term within the text 

For a large text field, you may want to take a look at building an analyzer that uses an [edge ngram token filter](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-edgengram-tokenfilter.html). Depending on how a tokenizer tokenizes the text into terms, this token filter would be able to index terms to handle the first and second scenarios above. To satisfy the third scenario, you would likely need to look at building an analyzer with an [ngram token filter.](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-ngram-tokenfilter.html).

Hope that helps 👍
