### ISSUE TITLE
Cannot serialize directly CreateIndexDescriptor when using a customer serializer

### ISSUE THREAD

**Issue by badpp** [elastic/elasticsearch-net#2998]
**NEST/Elasticsearch.Net version**: 6.0.0-beta1

**Elasticsearch version**: 6.1.1

**Problem**:
For all our indices we define the CreateIndexDescriptor. During development we serialize all descriptors to separate JSON files and store those files in our source repository. This is helping us a lot to track any breaking changes and preparing upgrade scripts for existing customer data.

We use a custom serializer derived from ConnectionSettingsAwareSerializerBase. Unfortunately, the resulting stream is just an empty object ```{}```.

Note: when using the default serializer the result is as expected (the same as in ElasticSearch.NET/NEST <= 5.x).

**Steps to reproduce**:
 1. Build a CreateIndexDescriptor.
 2. Serialize it using a client with a default SourceSerializer.
 3. Result: <json including settings and mapping
 4. Create a customer serializer based on ConnectionSettingsAwareSerializerBase.
 5. Build a CreateIndexDescriptor and serialize it using the SourceSerializer.
 6. Problem: result: ```{}```

See attached sample program:

[IndexDescriptorProblem.txt](https://github.com/elastic/elasticsearch-net/files/1593394/IndexDescriptorProblem.txt)

**Output from attached sample programm**:
```
Normal client:{
  "settings": {
    "index.number_of_replicas": 0,
    "index.number_of_shards": 1
  },
  "mappings": {
    "samplebase": {
      "properties": {
        "id": {
          "type": "keyword"
        },
        "myJoinField": {
          "type": "join",
          "relations": {
            "sampleparent": "samplechild"
          }
        },
        "docType": {
          "type": "keyword"
        }
      }
    }
  }
}
Custom client:{}
```

Question: 
- Is there a way to get it running with a custom serializer?

**Comment by Mpdreamz** [comment]
This is expected, only the built in serializer can serialize this as it needs all the internal converters you can feed it the `client.RequestResponseSerializer`.

**Comment by badpp** [comment]
OK, great, will do. Thanks for the advice.
