### ISSUE TITLE
How do I dynamically create a filter with multiple conditions?

### ISSUE THREAD

**Issue by carlosdulima** [elastic/elasticsearch-net#3004]
NEST/Elasticsearch.Net version 5.x or More

Elasticsearch version 6.x or More

How do I dynamically create a filter with multiple conditions?

The section below works, but I need it to be dynamically mounted, that is, each AND is concatenated.

Example:

`
var filters = new List<Func<QueryContainerDescriptor<MyObject>, QueryContainer>>();

                    filters.Add(f => f.Terms(t => t.Field("Field1").Terms("termo1"))
                        && f.Terms(t => t.Field("Field1").Terms("termo2"))
                        && f.Terms(t => t.Field("Field1").Terms("termo3"))
                    );
`

**Comment by Mpdreamz** [comment]
Hi @carlosdulima 

I am not sure what you are asking so I can not answer your question. 

Please make sure you have read the following two pieces of documentation:

https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/writing-queries.html
https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/bool-queries.html

Feel free to reopen (or better ask the general question over at discuss.elastic.co) if you are still having difficulties.
