### ISSUE TITLE
Pretty on request and connectionsettings results in pretty=true,true

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch-net#3005]
The following code ...
```
var response = _client.Snapshot(
	name,
	$"snapshot-{now.ToString("yyyy-MM-dd")}",
	x => x
		.Pretty()
		.WaitForCompletion(false)
		.IncludeGlobalState());
```
yields the following request ...
```
PUT <server>/_snapshot/es-2018-01/snapshot-2018-01-02?pretty=true,true&wait_for_completion=false
{
  "include_global_state": true
}
```
which yields the following error:
```
{"The remote server returned an error: (502) Bad Gateway."}
```
Removing the extra `true` and manually issuing the same request fixes the problem.  Not sure where the extra true comes from but I'm guessing the `include_global_state` part does that?

**Comment by Mpdreamz** [comment]
`?pretty=true,true` that looks like a bug, thanks for reporting will look into this tomorrow. 

For now just remove the `.Pretty()` from the `x` selector.

**Comment by tdoman** [comment]
It's not gonna be pretty!  ;)  Will do, thanks Martijn.

**Comment by Mpdreamz** [comment]
Fixed as of https://github.com/elastic/elasticsearch-net/pull/3016
