### ISSUE TITLE
NEST 6.0: ES 6.0 and 6.1 Nested Sort differences

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch-net#3006]
I have discovered one difference between ES 6.0 and ES 6.1 that I would assume is a breaking change WRT nested sort.
[ES 6.1: Nested sorting examples](https://www.elastic.co/guide/en/elasticsearch/reference/6.1/search-request-sort.html#_nested_sorting_examples).
[ES 6.0: Nested sorting examples](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/search-request-sort.html#_nested_sorting_example).
Will ES 6.1 continue to support the ES 6.0 style as a deprecated method?  I ask because in the NEST 6.0 Beta, the ES 6.0 style of nested sort is the only one supported.  Perhaps the NEST library is handling that difference under the covers for now?  @Mpdreamz indicated there shouldn't be any breaking changes between ES 6.0 and ES 6.1 and I'd love to use ES 6.1 w/ NEST 6.0 as we upgrade, please advise.

**Comment by Mpdreamz** [comment]
Hi @tdoman, the 6.x way of specifying will also work in 6.1 albeit deprecated it won't be removed till `Elasticsearch 7.x`

I think for now NEST will roll with the deprecated way for both 6.0 and 6.1.

**Comment by tdoman** [comment]
Sounds good, deprecated method it is!  Thanks Martijn!
