### ISSUE TITLE
NumberAttribute problem

### ISSUE THREAD

**Issue by giocaputo** [elastic/elasticsearch-net#3008]
**NEST/Elasticsearch.Net version**: 6.0.0-rc1
**Elasticsearch version**: 6.0.x

**Description of the problem including expected versus actual behavior**:
Using Nest attribute property :    [Number(NumberType.Byte)]
i have this error 
'NumberAttribute.NumberAttribute(NumberType)' is inaccessible due to its protection level	Archiproducts.Data.ElasticSearch

**Comment by codebrain** [comment]
Thanks @giocaputo - fixed in https://github.com/elastic/elasticsearch-net/pull/3013

**Comment by codebrain** [comment]
Will be fixed in next release of client.
