### ISSUE TITLE
UpdateIndexSettingsRequest does not work on adding well-known settings through Dictionary.Add() method

### ISSUE THREAD

**Issue by bittusarkar** [elastic/elasticsearch-net#3019]
**NEST/Elasticsearch.Net version**: 5.6.0

**Elasticsearch version**: 5.4.0

**Description of the problem including expected versus actual behavior**:
I'm trying to write a generic code for updating index setting where the setting name and value are provided as inputs. If I initialize an object of `IndexSettings` class and add a setting using the `Dictionary.Add()` method for a well-known setting, then Nest throws saying `"no settings to update"`.

**Steps to reproduce**:
```
var settings = new IndexSettings();
settings.Add("index.unassigned.node_left.delayed_timeout", "10m");
var request = new UpdateIndexSettingsRequest(Indices.AllIndices)
{
    IndexSettings = settings
};
client.UpdateIndexSettings(request);

```

I understand that using `settings.UnassignedNodeLeftDelayedTimeout = "10m";` works but when I do not know what the setting is beforehand, I cannot use this. I also understand that I can achieve this using the low level client but I would like to avoid that as much as possible.

My ask is to allow configuring any setting by adding to a dictionary irrespective of whether it is a well-known setting or not.

**Comment by hyankov** [comment]
This doesn't work for me.

`client.UpdateIndexSettings(new UpdateIndexSettingsRequest("some_index_name") { IndexSettings = new IndexSettings() { RefreshInterval = null } });`

generates PUT request with empty body:
`https://cluster/some_index_name/_settings?pretty=true`

This gets rejected with:
```
{
  "error" : {
    "root_cause" : [ {
      "type" : "action_request_validation_exception",
      "reason" : "Validation Failed: 1: no settings to update;"
    } ],
    "type" : "action_request_validation_exception",
    "reason" : "Validation Failed: 1: no settings to update;"
  },
  "status" : 400
}
```

What am I doing wrong?
