### ISSUE TITLE
NEST 1.9.2 incompatible with Json.NET 10.x

### ISSUE THREAD

**Issue by lakario** [elastic/elasticsearch-net#3020]
**NEST/Elasticsearch.Net version**:

1.9.2

**Elasticsearch version**:

1.x

**Description of the problem including expected versus actual behavior**:

When using NEST 1.9.2 with Elasticsearch 10.x, there is an incompatibility caused by a breaking constructor change on Newtonsoft Json.NET's DefaultContractResolver, which is used by NEST's ElasticContractResolver.

Specifically, the constructor to DefaultContractContractResolver previously accepted a boolean. This constructor no longer exists in Json.NET 10.x.

`MissingMethodException: Method not found: 'Void Newtonsoft.Json.Serialization.DefaultContractResolver..ctor(Boolean)'`

**Steps to reproduce**:
 1. Install NEST 1.9.2
 2. Install Json.Net >= 10.0.1
 3. Create a `new ElasticClient()`

**Comment by lakario** [comment]
Elasticsearch.Net.JsonNet has a hard constraint on Newtonsoft.Json <= 9.,0 which I think may be breaking the build. Is this constraint required? Can we move it forward to 10.x?

**Comment by russcam** [comment]
Hey @lakario, [NEST 1.9.2 nuget package](https://www.nuget.org/packages/NEST/1.9.2) supports only JSON.Net >= 9.0.0 && < 10.0.0, which it is compiled and tested against.

Support and development for NEST 1.x ceased a year ago, in line with the discontinuation of support of Elasticsearch 1.x and there are no plans to release a newer version. If possible, are you able to move to latest Elasticsearch 5.x or 6.x?

**Comment by lakario** [comment]
@russcam Understood. We are in the unfortunate position of having introduced a hard dependency on Json.NET 10 while retaining legacy code for ES 1.x for a few more releases as we deploy a new 5.x platform in the coming year.  So yes, we can upgrade, eventually.

The fix seems to have already been adopted in the 5.x code code, as I can see that the current version of `ElasticContractResolver` is still similar. Provided we don't identify any obvious issues with this patched DLL, we'll just reference it directly, for now.

Thank you.

**Comment by russcam** [comment]
Thank you for understanding @lakario. I had a look over the proposed change in #3021; one of the differences in `ElasticContractResolver` that is missing in the change but is in 5.x and therefore think it also should be included in your patched DLL, is the use of a Concurrent dictionary to cache resolved contracts:

https://github.com/elastic/elasticsearch-net/blob/5.6.0/src/Nest/CommonAbstractions/SerializationBehavior/ElasticContractResolver.cs#L38-L80

Without this change too, contracts will be resolved each time.

**Comment by lakario** [comment]
This is helpful @russcam, thank you. I will incorporate the referenced logic to ensure that we have similar operating performance.
