### ISSUE TITLE
NEST documentation page missing

### ISSUE THREAD

**Issue by Minx-SigEp** [elastic/elasticsearch-net#3029]
**NEST/Elasticsearch.Net version**: 2 and 5

**Description of the problem including expected versus actual behavior**:

The API for getting a document by ID has changed since version 1.0 but there is no documentation for this. This is a basic API, but it should still be documented.

**Steps to reproduce**:
 1. Navigate to https://www.elastic.co/guide/en/elasticsearch/client/net-api/1.x/get.html
 2. On the right side select 2.x or 5.x (current) or master from the **.NET API:** dropdown
 3. An alert will appear with the message "This page is not available in the docs for version:2.x"

After a little more digging I discovered that the whole "Core" area from 1.x is missing in all other version. 

https://www.elastic.co/guide/en/elasticsearch/client/net-api/1.x/core.html

**Comment by russcam** [comment]
The documentation underwent a massive overhaul from 1.x -> 2.x to generate documentation from tests, to ensure that the documentation does not drift from the source code implementation. The 1.x documentation was originally hosted outside of the elastic website documentation, but later incorporated into it.

I think it would be useful to have some documentaton for getting a document by ID in the documentation on Elastic. There's [an example on the github repository README](https://github.com/elastic/elasticsearch-net#getting-a-document) and [tests for it ](https://github.com/elastic/elasticsearch-net/blob/master/src/Tests/Document/Single/Get/GetApiTests.cs).

**Comment by Mpdreamz** [comment]
Adding our `API` tests back as documentation is already part of #2248. Thanks for reporting this @Minx-SigEp always keen to hear how we can improve documentation.
