### ISSUE TITLE
Customer Serializer - How to port

### ISSUE THREAD

**Issue by Minx-SigEp** [elastic/elasticsearch-net#3032]
**NEST/Elasticsearch.Net version**: NEST 6.0.0-rc1

**Description of the problem **:
We are in the process of upgrading to Nest 6.0.0-rc1 and I can not figure out how to migrate the below serializer. 

5.5 has the following logic which we were relying on
https://github.com/elastic/elasticsearch-net/blob/5.5/src/Nest/CommonAbstractions/SerializationBehavior/ElasticContractResolver.cs#L63-L73

6.0 (Master) does not 
https://github.com/elastic/elasticsearch-net/blob/master/src/Serializers/Nest.JsonNetSerializer/ConnectionSettingsAwareSerializerBase.Serializer.cs

```
    public class ClientFactory : IClientFactory
    {
        /// <summary>
        /// Creates a nest settings object.
        /// </summary>
        protected virtual IConnectionSettingsValues CreateSettings(
            IConnectionPool connectionPool)
        {
            var settings = new ConnectionSettings(connectionPool, (c) => new EnumHandlingJsonNetSerializer(c));
            
            // Additional Logic here but not important

            return settings;
        }

        /// <summary>
        /// StringEnumConverter for Enums and Nullable<T> where T is an Enum
        /// </summary>
        public class EnumHandlingJsonNetSerializer : JsonNetSerializer
        {
            public EnumHandlingJsonNetSerializer(IConnectionSettingsValues settings) : base(settings)
            {
            }

            protected override void ModifyJsonSerializerSettings(JsonSerializerSettings settings)
            {
                settings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
            }

            protected override IList<Func<Type, JsonConverter>> ContractConverters =>
                new List<Func<Type, JsonConverter>>
                {
                    type => IsEnumOrNullableEnum(type)
                        ? new Newtonsoft.Json.Converters.StringEnumConverter()
                        : null
                };

            private static bool IsEnumOrNullableEnum(Type type)
            {
                return type.IsEnum
                    || (type.IsGenericType
                        && type.GetGenericTypeDefinition() == typeof(Nullable<>)
                        && type.GetGenericArguments().First().IsEnum);
            }
        }
    }
```

**Comment by Mpdreamz** [comment]
Hi @Minx-SigEp 

You are right this is no longer available, but would still be super useful to add back. Will open a PR for this.

**Comment by Mpdreamz** [comment]
On second thought the existing infrastructure for passing a list of `JsonConverter` to `JsonNetSerializer` or  a ` ConnectionSettingsAwareSerializerBase` subclass should be sufficient even for something like the build in `StringEnumConverter`

```csharp
	public class MyEnumConverter : StringEnumConverter
	{
		public override bool CanConvert(Type objectType)
		{
			return base.CanConvert(objectType);
		}
	}

````

I hope this [and our documentation](https://www.elastic.co/guide/en/elasticsearch/client/net-api/master/custom-serialization.html#_jsonnetserializer) are sufficient to get you unblocked @Minx-SigEp feel free to reopen if its not.

**Comment by Minx-SigEp** [comment]
Just in case someone else needs this in the future. This is what the new version looks like in Nest 6.  

```cs
ConnectionSettings.SourceSerializerFactory serializerFactory = (b, c) =>
    new JsonNetSerializer(b, c, contractJsonConverters: new List<JsonConverter>()
    {
        new Newtonsoft.Json.Converters.StringEnumConverter()
    });

var settings = new ConnectionSettings(connectionPool, serializerFactory)
    .RequestTimeout(options.RequestTimeout);
```

Also discovered the StringEnumConverter already does the Nullable check. and there no reason to do it again 
https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Converters/StringEnumConverter.cs#L175-L182
