### ISSUE TITLE
NEST 5.6 ReindexOnServer WaitForCompletion(true) NullReferenceException after 1 minute

### ISSUE THREAD

**Issue by coelacanth16** [elastic/elasticsearch-net#3033]
**NEST/Elasticsearch.Net version**: 5.5 (but probably forward)

**Elasticsearch cluster version**: 5.1.1

**Description of the problem including expected versus actual behavior**:

I'm attempting to use ReindexOnServer like this:
```
var response = client.ReindexOnServer(selector => selector
    .Source(srcSel => srcSel
      .Index("source_index_name")
      .Type(type)
      .Query<object>(querySel => querySel
         .Terms(termsSel => termsSel
            .Field("fieldName")
            .Terms("term1", "term2", ...))))
   .Destination(destSel => destSel
      .Index("dest_write_alias_name"))
   .WaitForCompletion(true))
```
my source_index_name has some 70 million docs. When I run this job manually on the server using the console, it takes about 8 minutes and I can monitor the task. When I run this in Nest, after exactly **1 minute** every time, the response returns and is _InValid_. The _ServerError.Error.Reason_ is:

_System.NullReferenceException: Object reference not set to an instance of an object.
  at ElasticsearchReindex.Program.<Start>d_6.MoveNext<> in_ ...<my program name>

However, when I query the task from the console I can see its still running and it eventually finishes without error, as expected. The _ReindexOnServerAsync_ equivalent method has the same behavior. 

It seems like there is an internal timer somewhere that cannot be set, is defaulting to 1 minute. In most console calls, you can add a _wait_for_completion=true&timeout=_N_s_ URL parameter. Is it set to 1 minute? If it is, can I request a feature that allows setting the timeout?

**Steps to reproduce**:
 1. have a large index to reindex
 2. wait 1 minute
 3. failure

**Provide `ConnectionSettings` (if relevant)**: a sniffing connection

**Provide `DebugInformation` (if relevant)**: given

**Comment by russcam** [comment]
@coelacanth16 specifying `.WaitForCompletion(true)` tells Elasticsearch to keep the connection open until the reindex operation completes. For a large reindex operation, this could take some time, much longer than the default 1 minute request timeout applied to requests.

You can specify a larger request timeout for this particular request to mitigate this. However, I think the better approach here is to specify `.WaitForCompletion(false)` and use the [task id returned to monitor the status of the reindex operation.](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html#docs-reindex-task-api).

Do you have the stack trace for the exception thrown, and the audit trail information? I'd like to see that we provide enough information to indicate that the request has timed out.

**Comment by coelacanth16** [comment]
@russcam 
Turns out my issue was more about an unexpected response. Timeouts are not "ServerError"s but the exception is still stored in OriginalException. Sorry to waste your time - I think its safe to close this.

I still can't monitor tasks by task_id in Nest or otherwise. Nest does correctly create the request, per the spec, however I think the issue indicative of 5.1.1. Not worth looking into atm with an impending upgrade.
