### ISSUE TITLE
thread hang at ElasticClient.GetAlias(Func<GetAliasDescriptor, IGetAliasRequest> selector = null)

### ISSUE THREAD

**Issue by l1183479157** [elastic/elasticsearch-net#3066]
Im using NEST.net version is 6.0.0-alpha1,lately i found my application response slowly and most requst hang at ElasticClient.GetAlias(Func<GetAliasDescriptor, IGetAliasRequest> selector = null)，

        Child SP               IP Call Site
0000000010b9cac8 00000000779bc2ea [GCFrame: 0000000010b9cac8] 
0000000010b9cb98 00000000779bc2ea [HelperMethodFrame_1OBJ: 0000000010b9cb98] System.Threading.Monitor.ObjWait(Boolean, Int32, System.Object)
0000000010b9ccc0 000007fed98a0e6a System.Threading.ManualResetEventSlim.Wait(Int32, System.Threading.CancellationToken)
    PARAMETERS:
        this (0x0000000010b9cd70) = 0x000000044028b218
        millisecondsTimeout (<CLR reg>) = 0x00000000ffffffff
        cancellationToken = <no data>
    LOCALS:
        <CLR reg> = 0x0000000000000000
        <CLR reg> = 0x0000000000000000
        <CLR reg> = 0x00000000ffffffff
        <no data>
        <no data>
        <no data>
        <no data>
        <no data>
        <no data>
        0x0000000010b9cd00 = 0x000000044028b240
        <no data>
        0x0000000010b9cd0c = 0x0000000000000000
        <no data>

0000000010b9cd70 000007fed986570a System.Threading.Tasks.Task.SpinThenBlockingWait(Int32, System.Threading.CancellationToken)
    PARAMETERS:
        this (0x0000000010b9cde0) = 0x000000044028b158
        millisecondsTimeout = <no data>
        cancellationToken = <no data>
    LOCALS:
        <no data>
        <no data>
        <no data>
        0x0000000010b9cd98 = 0x000000044028b218
        <no data>

0000000010b9cde0 000007fed9865592 System.Threading.Tasks.Task.InternalWait(Int32, System.Threading.CancellationToken)
    PARAMETERS:
        this = <no data>
        millisecondsTimeout (0x0000000010b9ceb8) = 0x00000000ffffffff
        cancellationToken = <no data>
    LOCALS:
        <no data>
        0x0000000010b9ce84 = 0x0000000000000000
        <no data>
        <no data>
        <no data>

0000000010b9ceb0 000007fed98b0073 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    PARAMETERS:
        task (<CLR reg>) = 0x000000044028b158
    LOCALS:
        <no data>
        <no data>

0000000010b9cee0 000007fe7b1239d2 Elasticsearch.Net.HttpConnection.Request[[System.__Canon, System.Private.CoreLib]](Elasticsearch.Net.RequestData)
    PARAMETERS:
        this = <no data>
        requestData (<CLR reg>) = 0x0000000440289e10
    LOCALS:
        <no data>
        0x0000000010b9cf08 = 0x000000044028a5b0
        <no data>
        <no data>
        <no data>
        <no data>
        <no data>
        <no data>
        <no data>
        <no data>

0000000010b9cf50 000007fe7b12323e Elasticsearch.Net.RequestPipeline.CallElasticsearch[[System.__Canon, System.Private.CoreLib]](Elasticsearch.Net.RequestData)
    PARAMETERS:
        this (<CLR reg>) = 0x0000000440289d88
        requestData (0x0000000010b9cfd0) = 0x0000000440289e10
    LOCALS:
        0x0000000010b9cf88 = 0x000000044028a118
        0x0000000010b9cf80 = 0x0000000000000000
        <no data>
        <no data>

0000000010b9cfc0 000007fe7b121e35 Elasticsearch.Net.Transport`1[[System.__Canon, System.Private.CoreLib]].Request[[System.__Canon, System.Private.CoreLib]](Elasticsearch.Net.HttpMethod, System.String, Elasticsearch.Net.PostData`1, Elasticsearch.Net.IRequestParameters)
    PARAMETERS:
        this (0x0000000010b9d080) = 0x0000000440289bd0
        method = <no data>
        path = <no data>
        data = <no data>
        requestParameters = <no data>
    LOCALS:
        0x0000000010b9d028 = 0x0000000440289d88
        0x0000000010b9d020 = 0x0000000440289e10
        <no data>
        0x0000000010b9d018 = 0x000000044028a008
        <no data>
        0x0000000010b9d010 = 0x000000044028a030
        0x0000000010b9d008 = 0x0000000440287cc8
        0x0000000010b9d000 = 0x0000000000000000
        <no data>
        <no data>

0000000010b9d0d8 000007fed9ed410e [StubHelperFrame: 0000000010b9d0d8] 
0000000010b9d130 000007fe7b120b6f Elasticsearch.Net.ElasticLowLevelClient.IndicesGetAliasForAll[[System.__Canon, System.Private.CoreLib]](System.String, System.Func`2)
    PARAMETERS:
        this = <no data>
        name = <no data>
        requestParameters = <no data>

0000000010b9d1a0 000007fe7afae5a9 Nest.LowLevelDispatch.IndicesGetAliasDispatch[[System.__Canon, System.Private.CoreLib]](Nest.IRequest`1)
    PARAMETERS:
        this = <no data>
        p = <no data>
    LOCALS:
        <no data>
        <no data>

0000000010b9d240 000007fe7afad9fa Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]](System.__Canon, System.Func`3, System.Func`3,Elasticsearch.Net.ElasticsearchResponse`1>)
    PARAMETERS:
        this = <no data>
        request = <no data>
        responseGenerator = <no data>
        dispatch = <no data>

**Comment by russcam** [comment]
@l1183479157  could you please update to [NEST-6.0.0-rc1](https://www.nuget.org/packages/NEST/6.0.0-rc1) and see if the problem recurs? If it does, would you be able to supply

1. You connection settings configuration
2. A minimal, succinct reproducible example

**Comment by l1183479157** [comment]
@russcam  thanks
