### ISSUE TITLE
NEST 6.0: Documentation problem.

### ISSUE THREAD

**Issue by bergdahl** [elastic/elasticsearch-net#3077]
The example code for "Modifying settings using SerializerFactory" does not compile.

https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/modifying-default-serializer.html

**Comment by russcam** [comment]
Thanks @bergdahl. 

That documentation page is no longer applicable to 6.x and will be removed

**Comment by bergdahl** [comment]
We still need an example of how to configure the default serializer.

**Comment by russcam** [comment]
Take a look at https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html.
