### ISSUE TITLE
Index Request Selector is no longer optional

### ISSUE THREAD

**Issue by jonyadamit** [elastic/elasticsearch-net#3079]
**NEST/Elasticsearch.Net version**:
6.0
**Elasticsearch version**:
6.0
**Description of the problem including expected versus actual behavior**:
In previous versions we could just use `client.IndexAsync<SomeType>(obj)`, but now we are forced to supply the index request selector (`client.IndexAsync<SomeType>(obj, s => s.Index("someIndex")`).  

I suppose this was made so because of the one-type indices change, but if we used the new `DefaultMappingFor` methods, why are we forced to specify them again?  **This must be a bug, since in it's `Search` and `Delete` equivalents the selector is still optional.**

**Steps to reproduce**:
Use `Index` or `IndexAsync` methods with a single parameter.

**Comment by Mpdreamz** [comment]
Hi @jonyadamit this particalar overload has been renamed to `IndexDocumentAsync(doc)`. 

We always fought with parameter resolution in `C#` to support it on `Index()` and opted to remove this particular ugly cast:

https://github.com/elastic/elasticsearch-net/blob/5.x/src/Nest/Document/Single/Index/ElasticClient-Index.cs#L44-L45

in `6.x`.
