### ISSUE TITLE
how do I.fix

### ISSUE THREAD

**Issue by ghavaun** [elastic/elasticsearch-net#3083]
**NEST/Elasticsearch.Net version**:

**Elasticsearch version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Describe the feature**:

**Comment by russcam** [comment]
@ghavaun Can you edit the issue and add details about the problem you are having? Without any detail, it's impossible to know what you need to fix and therefore offer advice!

**Comment by ghavaun** [comment]
GraphQL API v4

**Comment by ghavaun** [comment]
#3083
NEST/Elasticsearch.Net version:

Elasticsearch version:

**Comment by ghavaun** [comment]
How do I fix the issue
