### ISSUE TITLE
IMultiGetResponse for Nest.Id type

### ISSUE THREAD

**Issue by giocaputo** [elastic/elasticsearch-net#3085]
**NEST/Elasticsearch.Net version**: 6.0.0

**Elasticsearch version**: 6.00

**Description of the problem including expected versus actual behavior**:

IMultiGetResponse should be have

MultiGetHit<T> Get<T>(Id id) where T : class;
IEnumerable<IMultiGetHit<T>> GetMany<T>(IEnumerable<Nest.Id> ids) where T : class;

**Comment by Mpdreamz** [comment]
Responses dont have access to `ConnectionSettings` needed to resolve `Id`. You will have to resolve this outside of `MultiGetHitResponse.GetMany()` sadly.
