### ISSUE TITLE
NEST 6.x - Missing documentation?

### ISSUE THREAD

**Issue by bergdahl** [elastic/elasticsearch-net#3092]
Is it just me or is there documentation pages missing for Index, Delete, and Update? 
At least I can't find them by browsing the menu.

In 1.x it was easy to find under the Core topic.

**Comment by russcam** [comment]
@bergdahl There is no Index, Delete and Update documentation currently for 2.x+; these would be welcome additions.

**Comment by Mpdreamz** [comment]
Closing as its covered by #2248
