### ISSUE TITLE
Geo-Shape - invalid serialization when used JsonNetSerializer.Default

### ISSUE THREAD

**Issue by stefando** [elastic/elasticsearch-net#3096]
**NEST/Elasticsearch.Net version**: 6.0.1

**Elasticsearch version**: 6.2.1

**Description of the problem including expected versus actual behavior**:

We are indexing the data containing geo-shape data.
When using ``` JsonNetSerializer``` these data are serialized incorrectly. 
(Default serializer works OK.)

```c#
var point = new PointGeoShape(new GeoCoordinate(lat, lon));
```
**With default serializer (expected):**
```json
{
    "geometry": {
        "type": "geometrycollection",
        "geometries": [
            {
                "coordinates": [
                    49.105995,
                    21.9926492
                ],
                "type": "point"
            },
            {
                "coordinates": [
                    49.1017987,
                    21.9909713
                ],
                "type": "point"
            }
        ]
    }
}
```

**With JsonNetSerializer (actual):**
```json
{
    "geometry": {
        "type": "geometrycollection",
        "geometries": [
            {
                "coordinates": {
                    "lat": 49.105995,
                    "lon": 21.9926492
                },
                "type": "point"
            },
            {
                "coordinates": {
                    "lat": 49.1017987,
                    "lon": 21.9909713
                },
                "type": "point"
            }
        ]
    }
}
```
which produces the following error:
```
json_parse_exception Reason: "Current token (FIELD_NAME) not numeric, can not use numeric value accessors
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@248dbc2c; line: 1, column: 462]
```

**Comment by GAnatoliy** [comment]
The same issue with *nest 6.0.1* and *Elasticsearch 6.1.3*

I try to index document with EnvelopeGeoShape and get above error.
In my case I have to hook serializer as described  [here](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html#_jsonnetserializer) since I have inherited classes and use custom json converters.
But this leads to error with geoshapes, so I can't move to nest 6

Would be nice to know if you have any plans regarding this issue.
Thanks.

**Comment by russcam** [comment]
Thanks for reporting @stefando.

@GAnatoliy the `IGeoShape` types were intended to be used as input types to geo shape queries. I can see the value of being able to specify them on documents though, so am looking at supporting them for this usage.
