### ISSUE TITLE
Type cannot be inferred from usage

### ISSUE THREAD

**Issue by nphmuller** [elastic/elasticsearch-net#3097]
**NEST/Elasticsearch.Net version**:
NEST 6.0.1

**Elasticsearch version**:
n/a

**Description of the problem including expected versus actual behavior**:
According to [this](https://www.elastic.co/blog/nest-elasticsearch-net-6-0-ga) blog post I should still be able to do this after upgrading to NEST 6.x:

`client.Index(new Company { Id = 1 })`

If I write this however, I get the following compile error
`The type arguments for method 'IElasticClient.Index<T>(IIndexRequest<T>, CancellationToken)' cannot be inferred from the usage. Try specifying the type arguments explicitly.`.

Here's a minimum sample which produces the compile error:
``` c#
public class MyClass
{
    public void MyMethod()
    {
        IElasticClient client = null;
        client.Index(new MyIndexedEntity());
    }
}

public class MyIndexedEntity { }
```

**Comment by Mpdreamz** [comment]
we had to change that to `client.IndexDocument<T>(T doc)`.

On the road now so pardon the short explanation will link to another ticket explaining it later.

**Comment by nphmuller** [comment]
Short answer is fine, it's clear. :)

Shall I leave this open to track if the blog post should be updated, or shall I close this issue?

**Comment by russcam** [comment]
@nphmuller yes please; we'll get the blog post updated 👍

**Comment by russcam** [comment]
I've now updated the blog post so am now closing this issue
