### ISSUE TITLE
Count the number of documents in a single index 

### ISSUE THREAD

**Issue by ophirmi** [elastic/elasticsearch-net#310]
Hi,

How do I count the number of documents in a single index (the cluster has many indices).

Thanks

**Comment by pvwalke** [comment]
A curl command could look something like this **curl -X GET "localhost:9200/indexname/_count?pretty"**

**Comment by pvwalke** [comment]
FYI  Curl command looks something like this 
**curl -X GET "clickhouse.falconide.com:9200/pepiposttest/_count?pretty"**
