### ISSUE TITLE
Question: mapping for autocomplete and text search

### ISSUE THREAD

**Issue by rdcm** [elastic/elasticsearch-net#3102]
1) At this moment  i trying to implement feature with autocomplete for 3 fields:

```
public class Assignment
{
	public string Title { get; set; }
	public string Theme { get; set; }
	public string TrainingKit { get; set; }
	...
}
```

In dsl api there is no opportunity to set multiple fields for completion, by this moment i have found only this quick solution. Can you suggest another solutions?

```
public async Task<IEnumerable<string>> Complete(string text)
{
	var sd1 = new SearchDescriptor<Assignment>().Suggest(
	    scd => scd.Completion(
		"completion1",
		csd => csd
		    .Field(x => x.Title)
		    .Prefix(text)));

	var sd2 = new SearchDescriptor<Assignment>().Suggest(
	    scd => scd.Completion(
		"completion2",
		csd => csd
		    .Field(x => x.Theme)
		    .Prefix(text)));

	var sd3 = new SearchDescriptor<Assignment>().Suggest(
	    scd => scd.Completion(
		"completion3",
		csd => csd
		    .Field(x => x.TrainingKit)
		    .Prefix(text)));

	var task1 = _elasticClient.SearchAsync<Assignment>(sd1);
	var task2 = _elasticClient.SearchAsync<Assignment>(sd2);
	var task3 = _elasticClient.SearchAsync<Assignment>(sd3);

	await Task.WhenAll(task1, task2, task3);

	var resp1 = task1.Result.Suggest.SelectMany(x => x.Value).SelectMany(x => x.Options).Select(x => x.Text).Distinct();
	var resp2 = task2.Result.Suggest.SelectMany(x => x.Value).SelectMany(x => x.Options).Select(x => x.Text).Distinct();
	var resp3 = task3.Result.Suggest.SelectMany(x => x.Value).SelectMany(x => x.Options).Select(x => x.Text).Distinct();

	return resp1.Concat(resp2).Concat(resp3);
}
```

2) On the other hand i need full-text search for this 3 fields.

Can i set several data types for each field?
For example, for `Title` `text` and `completion`.
At this moment all my attempts to set correct mapping for single field with this two types have failed.

**Comment by russcam** [comment]
Hey @rdcm ,

GitHub issues are reserved for bugs and feature requests. The best place to ask this question would be over at https://discuss.elastic.co/c/elasticsearch. Not only will it gain more attention there, the answers may help out other users in the future, and the forum will be an easier place for others to find similar questions that have been asked before.
