### ISSUE TITLE
NEST 6.X - Nested path/filter in sort

### ISSUE THREAD

**Issue by vicariouskp** [elastic/elasticsearch-net#3104]
**NEST/Elasticsearch.Net version:**
6.0

**Elasticsearch version:**
6.1.3

**Description of the problem including expected versus actual behavior:**
Hello, I'm trying to write in c# using Nest 6.0 version code provided here: [https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html)

```c#
POST /_search
{
   "query" : {
      "term" : { "product" : "chocolate" }
   },
   "sort" : [
       {
          "offer.price" : {
             "mode" :  "avg",
             "order" : "asc",
             "nested": {
                "path": "offer",
                "filter": {
                   "term" : { "offer.color" : "blue" }
                }
             }
          }
       }
    ]
}
```

How can write this nested object in c#? 
The only thing that I found in the library for the SortDescriptor<T> object is NestedPath() and NestedFilter(), unfortunatelly both of them are deprecated:

>#! Deprecation: [nested_path] has been deprecated in favor of the [nested] parameter
>#! Deprecation: [nested_filter] has been deprecated in favour for the [nested] parameter

**Comment by russcam** [comment]
Hey @vicariouskp,

GitHub issues are reserved for bugs and feature requests. The best place to ask this question would be over at https://discuss.elastic.co/c/elasticsearch. Not only will it gain more attention there, the answers may help out other users in the future, and the forum will be an easier place for others to find similar questions that have been asked before.

Thanks!
