### ISSUE TITLE
Nested_path and Nested_filter are deprecated

### ISSUE THREAD

**Issue by vicariouskp** [elastic/elasticsearch-net#3106]
**NEST/Elasticsearch.Net version:**
6.0

**Elasticsearch version:**
6.1.3

**Description of the problem including expected versus actual behavior:**
When using Elastic Search 6.1.3 & Nest 6.0 in SortDescriptor for NestedPath & NestedFilter we get the deprecations alerts

> #! Deprecation: [nested_path] has been deprecated in favor of the [nested] parameter
> #! Deprecation: [nested_filter] has been deprecated in favour for the [nested] parameter

**Steps to reproduce:**
Try to create SortDescriptor<T> object
It's not possible to do proper [nested] parameter using Nest 6.0

**Comment by russcam** [comment]
Thanks for reporting @vicariouskp. They are only deprecations, so the functionally, they continue to work as expected.

I've opened Issue #3178 and PR #3180 to address so am going to close this in favour of tracking on #3178 (I would have tracked it on this issue, but I opened a new one before seeing this 😢 )
