### ISSUE TITLE
"DataMember" attribute is not applied when deserializing searching query

### ISSUE THREAD

**Issue by QuanTran91** [elastic/elasticsearch-net#3107]
**NEST/Elasticsearch.Net version**: 6.0.1

**Elasticsearch version**: 6.0.1

**Description of the problem including expected versus actual behavior**:

I have a document model as below:

    [DataContract(Name = "source_entity")]
    public class SourceEntity
    {
        [DataMember(Name = "name")]
        public string Name { get; set; }
        
        [DataMember(Name = "display_name")]
        public string DisplayName { get; set; }
    }

And here is the code for inserting random source entities:

    public class AddEntitySample
    {
        private ElasticClient elasticClient;

        public AddEntitySample()
        {
            var node = new Uri("http://localhost:9200");
            var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
            var settings = new ConnectionSettings(pool);
            
            settings.DefaultMappingFor<SourceEntity>(t => t.IndexName("source_entity_fun"));
            settings.DisableDirectStreaming();
            settings.OnRequestCompleted((t) =>
            {
                var a = t.DebugInformation;
            });
            elasticClient = new ElasticClient(settings);
        }

        public void AddSampleData()
        {
            elasticClient.DeleteIndex(Indices.Index<SourceEntity>());
            var enumberation = Enumerable.Range(0, 1000).Select(index => new SourceEntity
            {
                Name = "Name " + index,
                DisplayName = "DisplayName" + index
            });        
            var response = elasticClient.BulkAsync(t => t.IndexMany(enumberation), 
                new System.Threading.CancellationToken()).Result;
        }        
    }

After insert some items in elastic db, I use this command "GET source_entity_fun/_mapping" (in Kibana dev console) to get the schemas of SourceEntity in elastic db.
And here is the json format of the document

    {
      "source_entity_test": {
        "mappings": {
          "sourceentity": {
            "properties": {
              "display_name": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "name": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              }
            }
          }
        }
      }
    }

When I make a simple query:

    var query = elasticClient.Search<SourceEntity>(t => t.Query(u => u.Terms(k => k.Field(h => h.DisplayName).Terms("23"))));
    
And here is the json query generated (using DebugInformation):

    {"query":{"terms":{"displayName":["23"]}}}

As the result, there are no documents returned.
I would expected is should be :

    {"query":{"terms":{"display_name":["23"]}}}
 (with underscore)

I tried to use [NEST.JsonNetSerializer](https://www.nuget.org/packages/NEST.JsonNetSerializer/) but it did not work.
Could you help me, please?
Thanks.

**Comment by russcam** [comment]
Hey @QuanTran91, if you use

```c#
[ElasticsearchType(Name = "source_entity")]
public class SourceEntity
{
    [PropertyName("name")]
    public string Name { get; set; }

    [PropertyName("display_name")]
    public string DisplayName { get; set; }
}
```
It will work as expected.

**Comment by QuanTran91** [comment]
Hi @russcam 
Actually, I have several ways to fix it. But what I'm mentioning here is the inconsistent implementation in entity serializing in Nest. Hope you guys think about it.

**Comment by russcam** [comment]
> inconsistent implementation in entity serializing in Nest

What is serialization inconsistent with? 

NEST has never supported `DataContract` and `DataMember` attributes as far as I can see; it has always had its own attributes to support entity and property naming.

One of the reasons for not using `DataContract` and `DataMember` attributes is that it creates a dependency on `System.Runtime.Serialization`, a dependency that is required only to support these attributes, and this would be forced on all NEST consumers. There are abstractions within the client for a consumer to add support for these attributes, or any other attributes, if they need to.

**Comment by QuanTran91** [comment]
If Nest does not support DataContract and DataMember, why does the property name of "DisplayName" is "display_name" not "displayName" in json format document as I expected. That's confusing me.

**Comment by russcam** [comment]
[By default, NEST camel cases property names](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/field-inference.html#camel-casing). This behaviour can be changed with `.DefaultFieldNameInferrer(Func<string,string>)` on `ConnectionSettings`.

**Comment by QuanTran91** [comment]
Hi @russcam , when I removed DataContract and DataMember from entity, the property names are showed in camel cases format as default (correct behavior). However, when I put DataContract and DataMember into it (with snake case style), it somehow affects to json format of document ("displayName" now turn to "display_name"). That is the issue I concern about.

**Comment by russcam** [comment]
Can you provide a reproducible example?

**Comment by QuanTran91** [comment]
I have already post at first, you can take a look at it:

    {
      "source_entity_test": {
        "mappings": {
          "sourceentity": {
            "properties": {
              "`**display_name**`": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "name": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              }
            }
          }
        }
      }
    }

**Comment by russcam** [comment]
Could you please provide a reproducible example that demonstrates how the mapping you have posted is generated from the `DataMember` attributed type

**Comment by QuanTran91** [comment]
Hi @russcam , I have updated my top post. Could you take a look at it? Thanks.

**Comment by russcam** [comment]
Thank you for the reproducible example @QuanTran91, this is a bug.
