### ISSUE TITLE
OutOfMemoryException with IndexManyAsync

### ISSUE THREAD

**Issue by stijnherreman** [elastic/elasticsearch-net#311]
I'm running into memory issues with IndexManyAsync. I can assume that the code itself works, I don't have any trouble when indexing few properties per document.

Environment is Windows 7 x64, 8 GB RAM, VS 2012 Development Server.

Before retrieving any data, the memory usage of the web server is 48 MB.
After retrieving all data from the database, the memory usage of the web server is 384 MB. A fresh instance of ES (java.exe) uses 152 MB.

I get to the IndexManyAsync call, and in a period of 13 seconds a few indices are created (visible in the ES process) and an OutOfMemoryException is thrown. At this point, the web server uses 865 MB and ES uses 710 MB. I still have over 3,5 GB available.

This looks like a rather low memory limit. Any idea how this can be avoided? Can I do additional debugging to provide information?

**Comment by Henr1k80** [comment]
@stijnherreman memory usage during indexing has been improved in this pull request
https://github.com/elastic/elasticsearch-net/pull/3579

**Comment by stijnherreman** [comment]
@Henr1k80 thanks! I'm no longer involved with that project so unfortunately I won't be able to test your changes.
