### ISSUE TITLE
Update by query

### ISSUE THREAD

**Issue by nguyenhero** [elastic/elasticsearch-net#3113]
Hello, I found a feauture [Update by query](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-update-by-query.html) .
How can i do it with nest ?

**Comment by russcam** [comment]
Hi @nguyenhero, 

GitHub is reserved for bug reports and feature requests.

The best place to ask a general question is at the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. 

To get you started, take a look at the [update by query integration tests](https://github.com/elastic/elasticsearch-net/blob/a8567d17404e3cf41f3db67735e99432c371d897/src/Tests/Document/Multiple/UpdateByQuery/UpdateByQueryApiTests.cs).  NEST APIs map 1-to-1 with Elasticsearch APIs and the fluent API structure mimics the structure of the JSON requests within Elasticsearch. If you're completely new to NEST, then I recommend starting on the [Getting Started section](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/nest-getting-started.html) in the documentation.

Thanks!
