### ISSUE TITLE
Add support for JSON.NET 11.0 for NEST 5/6 clients

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#3115]
Is there any timeline or plans for upgrading JSON.NET to 11.0 for the current clients?

**Comment by mscrivo** [comment]
I'd especially like it to be done for the 5.x clients.  There are way too many breaking changes for us to upgrade to 6 in the short-term, but nuget is telling us we can't upgrade to Json.NET 11 because ES.NET and NEST want a version < 11.

**Comment by chrisdrobison** [comment]
Would it be possible to just get rid of the next major version exclusion? Seems like a lot of libraries don't include that and everything continues to work just fine if the assembly binding redirects are setup.

**Comment by niemyjski** [comment]
Is there any updates on this? I'd be willing to submit a pr if needed.

**Comment by ejsmith** [comment]
JSON.NET has to be extremely good about not introducing breaking changes or else the entire world would break. It seems really silly to have an upper bound limit on the nuget dependency.

**Comment by Mpdreamz** [comment]
Working on this now PR's will follow shortly, sorry for the wait this JSON.NET release coincided with Elasticon and our Engineering get together in Lake Tahoe.

**Comment by mscrivo** [comment]
Thank you @Mpdreamz

**Comment by Mpdreamz** [comment]
Released `6.0.2` to bump the JSON.NET dependency to `11`. Working on `5.x` and `2.x` next.

**Comment by Mpdreamz** [comment]
Released [`5.6.1`](https://github.com/elastic/elasticsearch-net/releases/tag/5.6.1)

**Comment by Mpdreamz** [comment]
@ejsmith @chrisdrobison  the upper limit is gone from the `6.x` releases since your `JSON.NET` won't affect the serializing of `NEST` types anymore. We did have cases where a major upgrade of `JSON.NET` broke NEST throughout the years and to be fair to `JSON.NET` that's totally OK :)

**Comment by Mpdreamz** [comment]
And finally we released [`2.5.8`](https://github.com/elastic/elasticsearch-net/releases/tag/2.5.8) which will be our final `2.x` release as `Elasticsearch 2.x` itself is EOL since 2018-02-28

**Comment by chrisdrobison** [comment]
Out of curiosity, have you guys ever considered ILMerging the JSON.NET into
yours so that you guys can ensure whatever compatibility you want without
enforcing a dependency version?

**Comment by Mpdreamz** [comment]
That's what did for our 6.x releases:

https://www.elastic.co/blog/nest-elasticsearch-net-6-0-ga

Just ilmerging is not sufficient we also rewrite the merged codes namespace to `Nest.Json`

**Comment by niemyjski** [comment]
@Mpdreamz when is 5.x EOL and before that happens will you remove the upper bound on json.net?
