### ISSUE TITLE
Add support for ip_range range datatype

### ISSUE THREAD

**Issue by arledesma** [elastic/elasticsearch-net#3118]
It looks like an implementation of the `ip_range` range datatype that was introduced in 5.5 is needed.

- https://www.elastic.co/guide/en/elasticsearch/reference/5.5/range.html
- https://www.elastic.co/guide/en/elasticsearch/reference/5.5/release-notes-5.5.0.html#feature-5.5.0
- https://github.com/elastic/elasticsearch/pull/24433

**Comment by russcam** [comment]
Thanks for opening @arledesma, we'll look to get these in the next 5.x and 6.x releases 👍
