### ISSUE TITLE
Nest ConnectionSettings Dafault Serializer

### ISSUE THREAD

**Issue by giocaputo** [elastic/elasticsearch-net#3124]
**NEST/Elasticsearch.Net version**: 6.0.1

**Elasticsearch version**: 6.1.1

Specifing default serializer in connection setting
ConnectionSettings settings =
 new ConnectionSettings(connectionPool ,
 sourceSerializer: (builtin, ss) =>  JsonNetSerializer.Default(builtin, ss));

the behavior is diffent:
in NullValueHandling in JSonNetSerializer.default is setted  NullValueHandling.Include

why?

**Comment by russcam** [comment]
> in NullValueHandling in JSonNetSerializer.default is setted NullValueHandling.Include

@giocaputo `NullValueHandling.Include` is the default value within Newtonsoft.Json's [`JsonSerializer`](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/JsonSerializer.cs#L558-L574) and [JsonSerializerSettings](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/JsonSerializerSettings.cs#L43). If you're using `JsonNetSerializer`, you're free to configure it however you need to.

The default _internal_ serializer within NEST when **not** using the NEST.JsonNetSerializer package, uses [`NullValueHandling.Ignore`](https://github.com/elastic/elasticsearch-net/blob/2fb7cf14a9b1846d4ca8ae183e0dc9a64577ef73/src/Nest/CommonAbstractions/SerializationBehavior/InternalSerializer.cs#L124-L130)

**Comment by giocaputo** [comment]
Thanks @russcam , than how to resolve #3175 ?

**Comment by russcam** [comment]
Please ask the question in #3175 on the forum at https://discuss.elastic.co/c/elasticsearch; we try to keep Github for bugs and feature requests. Having the question and answer on Discuss will be beneficial to others who may have the same question in the future.
