### ISSUE TITLE
Create generic version of IGetTaskResponse

### ISSUE THREAD

**Issue by ejsmith** [elastic/elasticsearch-net#3131]
We often kick off tasks for things like snapshots and reindex and then sit in a loop getting the task status. The GetTaskAsync method returns a response that contains the response from the initial request once the task has completed. It would be really nice if we could do something like this:

```c#
var status = await _client.GetTaskAsync<IReindexOnServerResponse>(result.Task);
if (status.Completed)
  Console.WriteLine(status.Task.Response.Failures.Count);
```

Here is an example of what we currently have to do:
https://github.com/FoundatioFx/Foundatio.Repositories/blob/master/src/Foundatio.Repositories.Elasticsearch/Repositories/ElasticReindexer.cs#L126-L134

**Comment by russcam** [comment]
Are you thinking some kind of Observable implementation @ejsmith ?

**Comment by ejsmith** [comment]
I think it can just be as simple as it’s only populated and serialized if the task is completed. But I also think it would be really helpful to have a method that polls the task until it’s complete as well and then returns when the task is finished.

**Comment by russcam** [comment]
Hi @ejsmith This has been implemented in https://github.com/elastic/elasticsearch-net/pull/3966 for 7.2.0 onwards. Are you using 7.x or 6.x?
