### ISSUE TITLE
[Research] Change infer types to structs

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#3137]
Opening and closing this brain dump, changing inference type to struct.

100k itteration of:
`Inferrer.PropertyName(f)` where `f` == `Infer.Property<MyProject>(p => p.Person.Name)`

`Run` instantiates `PropertyName` for every iteration, `RunCreateOnce` resolves a 100k times on a single instance.

```
        Method |        Mean |     Error |    StdDev |      Gen 0 |    Allocated |
-------------- |------------:|----------:|----------:|-----------:|-------------:|
           Run | 1,103.16 ms | 87.815 ms | 22.810 ms | 62000.0000 | 192203.61 KB |
 RunCreateOnce |    11.80 ms |  5.660 ms |  1.470 ms |          - |      4.81 KB |
````

Changing propertyname to struct:

```
        Method |        Mean |    Error |    StdDev |      Gen 0 | Allocated |
-------------- |------------:|---------:|----------:|-----------:|----------:|
           Run | 1,104.50 ms | 61.76 ms | 16.042 ms | 64000.0000 | 193.87 MB |
 RunCreateOnce |    26.70 ms | 18.91 ms |  4.913 ms |  4000.0000 |  12.21 MB |
```

 Seems like  a clear cut choice to me :)

Not really a clean struct vs class case since it internally news up a pretty heavy expression visitor but in light of recent `Infer` and `IUrlParameter` changes I'm happy to keep these as `classes` and focus on our expression visitor instead.

cc @codebrain @russcam

**Comment by codebrain** [comment]
:+1:
