### ISSUE TITLE
Outdated Attribute Mapping Doc Page

### ISSUE THREAD

**Issue by bbeda** [elastic/elasticsearch-net#3138]
This page' example is outdated. 

https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/attribute-mapping.html

1. The [Object] attribute doesn't support Store=false
2. It uses ElasticsearchType attribute with two type names which is not supported in ES6x

**Comment by russcam** [comment]
@bbeda The documentation is generated from tests within the 6.x branch, so is up to date with 6.x source. With that said, this particular documentation page executes unit tests only.

> The [Object] attribute doesn't support Store=false

`ObjectAttribute` inherits from [`ElasticsearchCorePropertyAttributeBase`](https://github.com/elastic/elasticsearch-net/blob/83e2dba5f20e01e254c26638a6678a2a84114f07/src/Nest/Mapping/AttributeBased/ElasticsearchCorePropertyAttributeBase.cs#L16) which has a `Store` property.

> It uses ElasticsearchType attribute with two type names which is not supported in ES6x

You're correct, two document types within one index is not supported. Will update this now.

**Comment by russcam** [comment]
I've opened #3139 to address point 2

**Comment by bbeda** [comment]
@russcam  - I didn't investigate the 1st point. However, when I wanted to confirm that the usage of the two attributes by just copying the code snippet, when I ran it, it threw an exception for the Store property in the attribute, this is why I mentioned it.

**Comment by russcam** [comment]
No worries @bbeda, which version of NEST are you using?

**Comment by bbeda** [comment]
I am using Nest 6.0.2 with Elasticsearch 6.2.2. I just ran it again, this is the error:
`[1] BadResponse: Node: http://localhost:9200/ Took: 00:00:00.2702411
OriginalException: Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. ServerError: Type: mapper_parsing_exception Reason: "Failed to parse mapping [company]: Mapping definition for [employees] has unsupported parameters:  [store : false]" CausedBy: "Type: mapper_parsing_exception Reason: "Mapping definition for [employees] has unsupported parameters:  [store : false]""`

**Comment by russcam** [comment]
Ah gotcha! I've misunderstood the original issue, my apologies. 

I'll look to address; this might be tricky because of the inheritance structure and not breaking binary compatibility. At the very least, I can remove it from the documentation

**Comment by bbeda** [comment]
No problem @russcam . Yes, agreed
Thank you
