### ISSUE TITLE
How to search special word?

### ISSUE THREAD

**Issue by ZhiqiangTao** [elastic/elasticsearch-net#3142]
there are many many special word as below:
“” ， , ? ？★☆★$ & ¤ § | °゜ ¨ ± · × ÷ ˇ ˉ ˊ ˋ ˙ Γ Δ Θ Ξ Π Σ Υ Φ Ψ Ω

For example:
I have two sentences  as below:
**I'm a person.**
**I have a pen, but I don't know how to use it.**

Now, I want to search which contains the character “**,**”, the second sentence above should be matched;
If I want to search contains both "**,**" and "**.**", both above sentences should be mathched.

How to do that?
Thanks advanced!!

**Comment by russcam** [comment]
Hi @ZhiqiangTao , 

GitHub is reserved for bug reports and feature requests.

The best place to ask a general question like this is at the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch

Thanks!

As a start, the inclusion of punctuation and other special symbols can be controlled through the application of [analyzers](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/analysis.html) on the fields of interest.
