### ISSUE TITLE
Refactor datatype mappings

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#3145]
Relates #3138 

Within mappings, There are some options exposed in base types that are not valid for the inherited types e,g. `ObjectProperty` does not support `Store`, but inherits it from `CorePropertyBase`.

Revisit the inheritance structure to address supported options for each type.

**Comment by russcam** [comment]
Additional example

- `BinaryProperty` and `BooleanProperty` should not have `Similarity`

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Will be tackled within code-generator.
