### ISSUE TITLE
NEST Version Consult

### ISSUE THREAD

**Issue by caozhiyuan** [elastic/elasticsearch-net#3167]
hi, i'm a beginner . now i use 6.0.2 client and es server version is 2.2.2 , now i just use DeleteAsync  CreateAsync UpdateAsync and SearchAsync , it will be some Compatibility problem？
or it must use 2.5.7 client

**Comment by russcam** [comment]
Hey @caozhiyuan, please take a look at the [compatibility matrix in the readme](https://github.com/elastic/elasticsearch-net#compatibility-matrix); NEST 2.x (any version, recommend latest 2.x, which is [2.5.8](https://www.nuget.org/packages/NEST/2.5.8)) is compatible with Elasticsearch 2.2.2.
