### ISSUE TITLE
Nullvaluehandling  for dictionary property in partial update

### ISSUE THREAD

**Issue by giocaputo** [elastic/elasticsearch-net#3175]
**NEST/Elasticsearch.Net version**: 6.0.2

**Elasticsearch version**: 6.2.2 /6.1.2

I want use a partial update 
_client.Update<T, P>(docPath,  
f => f.Doc(partialDocument).Index(_indexName).DocAsUpsert().Routing(routing)
)

The partial document have a property dictionary that is not serialized when values are null.

How to handle the nullvaluehandling without change the global settings connnection?

The documentation in 
https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html
is not exhaustive.

Thanks

**Comment by russcam** [comment]
Hi @giocaputo, 

GitHub is reserved for bug reports and feature requests.

The best place to ask a general question like this is at the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch

Thanks 👍
