### ISSUE TITLE
Nested sort yields invalid JSON

### ISSUE THREAD

**Issue by californiah2oco2** [elastic/elasticsearch-net#3177]
Based on the https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/sort-usage.html

I created and added SortField into the SearchRequest, where it yields 
  
```json
  "sort": [
    {
      "Applications.Borrower.FirstName.raw": {
        "order": "desc",
        "nested_filter": {
          "nested": {
            "query": {
              "term": {
                "Applications.MyIndex": { "value": 0 }
              }
            },
            "path": "Applications"
          }
        },
        "nested_path": "Applications"
      }
    }
  ]
```

Which it did not work on elastic 6.2. Then I hand crafted the system following the instruction provided here https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html

```json
  "sort": [
    {
      "Applications.Borrower.FirstName.raw": {
        "order": "desc",
        "nested": {
                  "path": "Applications",
                  "filter": {
                     "match": {"Applications.MyIndex": 0}
                  }
               }
      } 
    }
  ]
```

Then it works. There might be an issue serializing SortField?

**Comment by russcam** [comment]
@californiah2oco2 Can you show how you are building the query within NEST?

**Comment by californiah2oco2** [comment]
Hi @russcam, I believe this is the same as https://github.com/elastic/elasticsearch-net/issues/3178.

Basically, the code is very simple for reproducing the scenario -

var searchRequest = new SearchRequest<T>("myIndex", "myType") {Query = new MatchAllQuery(), Sort = _sortFields }

_sortFields is what I have mentioned earlier. 

I debug.print() out the request at ".RequestCompleted" event and quickly realized the difference between the JSON which NEST produced vs  the instruction provided at https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-sort.html


Thanks

**Comment by russcam** [comment]
Can you show a full example of how you're building the search request, including `_sortFields`? Without a complete, succinct example, it takes much longer to get to the root of the issue 🙂 

It looks like you would like to use `nested` sort. This has been implemented in the 6.x branch, but has not yet been released to a 6.x version on nuget; it will be in the next 6.x version of nuget, which we're aiming to put out this week. In the meantime, `nested_filter` and `nested_path` do exist in 6.x and can be used to build sorting on nested fields, although not all nested sorting scenarios that are supported with `nested` sort are supported with `nested_filter` and `nested_path`. They are deprecated in favour of `nested` sort, but this deprecation is only advisory.

Looking at the query you have posted, it looks like this would be supported with `nested_filter` and `nested_path`, but it should be something like

```json
  "sort": [
    {
      "Applications.Borrower.FirstName.raw": {
        "order": "desc",
        "nested_filter": {
          "term": {
            "Applications.MyIndex": {
              "value": 0
            }
          }
        },
        "nested_path": "Applications"
      }
    }
  ]
```

`nested_filter` is operating in a nested scope, so the `term` query doesn't need to be within a `nested` query inside `nested_filter`.

I'm going to close this issue @californiah2oco2 as I don't think there's anything further actionable. Keep an eye out on nuget for the next 6.x release 👍
