### ISSUE TITLE
Add Significant Text Aggregation

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#3181]
[Introduced as an experimental feature in 6.0](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/search-aggregations-bucket-significanttext-aggregation.html).

I think the usecases would warrant implementing this. Thoughts @Mpdreamz, @codebrain ?

**Comment by codebrain** [comment]
Seems reasonable - I imagine it'd just fit with the existing aggregations pattern in NEST?

**Comment by Mpdreamz** [comment]
Agreed, quite a few aggs were experimental for most of 2.x and 5.x 😄
