### ISSUE TITLE
Aggregation result not serialized properly by client 

### ISSUE THREAD

**Issue by jyothi530** [elastic/elasticsearch-net#3182]
**NEST/Elasticsearch.Net version**:
6.0.2
**Elasticsearch version**:
6.2.3
**Description of the problem including expected versus actual behavior**:
Aggregation result with NEST client is empty. When debugged using fiddler the query passed Elasticsearch cluster is giving correct result but in the client result is empty.

**Provide `DebugInformation` (if relevant)**:
Client code
```
if (string.IsNullOrEmpty(searchTerm)) throw new System.ArgumentException(nameof(searchTerm));

            var searchResponse = await _elasticClient.SearchAsync<Transaction>(s =>
                                        s.Index("qbiot-transactions")
                                         .AllTypes()
                                         //.From(0)
                                         .Size(0)
                                         .Query(q => q.QueryString(t => t.Query(searchTerm)))
                                        .Aggregations(a => a
                                            .Terms("group_by_type", at => at
                                                .Field(t => t.Type)))
                                        //q => q.Match(m => m.Field(t => t.Type).Query(searchTerm))
                                        );

            var documents = searchResponse.Aggregations.Terms("group_by_type");

            return Ok(documents);
```
Response with client code
![image](https://user-images.githubusercontent.com/19412829/38106666-bd92125a-335d-11e8-8eef-7bce0c1d9380.png)
Query generated by NEST client to pass to elasticsearch cluster and response from cluster
![image](https://user-images.githubusercontent.com/19412829/38106724-ec2ceb4e-335d-11e8-9a9c-98b39dec6433.png)

Following is example index mapping
![image](https://user-images.githubusercontent.com/19412829/38106993-af251734-335e-11e8-9322-98eb68c4a2f4.png)

Below is elasticclient configuration
 ```
var elasticsearchSettings = Configuration.GetSection("Elasticsearch").Get<ElasticsearchSettings>();

            var connectionPool = new SingleNodeConnectionPool(new Uri(elasticsearchSettings.ConnectionString));

            var connectionSettings = new ConnectionSettings(connectionPool)
                                        .BasicAuthentication("elastic", "****")
                                        .DefaultFieldNameInferrer(s => s.ToLower());

            services.AddSingleton(new ElasticClient(connectionSettings));
```

From the above screenshot we can see that NEST client is not serializing aggregation results properly

**Comment by russcam** [comment]
@jyothi530 this looks like the same issue as #3093; can you confirm that you serializing the documents to JSON within return `Ok(documents);`?

**Comment by jyothi530** [comment]
@russcam I am not serializing explicitly. But it is serialized by .Net Core's by default internally using Newtonsoft.JSON

**Comment by russcam** [comment]
Thanks for confirming @jyothi530, this is the same issue. I'm going to close this in favour of tracking in one place on #3093.
