### ISSUE TITLE
IndicesStats not having shards information in Nest

### ISSUE THREAD

**Issue by intrakislay** [elastic/elasticsearch-net#3185]
https://github.com/elastic/elasticsearch-net/blob/5.x/src/Nest/Indices/Monitoring/IndicesStats/IndicesStats.cs
GET <IndexName>/_stats/store?level=shards
Query to Elastic search gives shards level information too but IndicesStats is having only two fields Primaries and Total.
It's not supporting 
Shards information there

**Comment by codebrain** [comment]
@intrakislay - which version of Elasticsearch are you running against? Thanks!

**Comment by intrakislay** [comment]
I am using ES 5.4

**Comment by codebrain** [comment]
Thanks.

Its related to this Java structure on the Elasticsearch server: https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/action/admin/indices/stats/ShardStats.java

Will work in `master` and backport to `5.x`

**Comment by codebrain** [comment]
Fixed as per https://github.com/elastic/elasticsearch-net/commit/b3af5b9b25f046d11e3660685d49271058f9366a
