### ISSUE TITLE
Json Serialization Exception on Decision Enum

### ISSUE THREAD

**Issue by thollowell** [elastic/elasticsearch-net#3210]
When calling the Elastic Search Client method:
           client.ClusterAllocationExplainAsync(ed => ed
                .ErrorTrace()
                .Human()
                .Index("my_index")
                .Primary(true));

I am getting a Json Serialization Exception trying to Deserialize the following json snip found in part of the response.

"node_allocation_decisions": [{
    "node_id": "_3APDoyWQUGJC2J_LbxQVw",
    "node_name": "node",
    "transport_address": "10.10.10.10:9300",
    "node_attributes": {
	    "ml.max_open_jobs": "10",
	    "rack_id": "2",
	    "ml.enabled": "true",
	    "machinetype": "warm"
    },
    "node_decision": "worse_balance",
    "weight_ranking": 4
	}
]

The NodeAllocationExplanation.NodeDecision property is of type Nullable<Decision>
The Decision enum values only include yes and no.
This is causing the json deserialization to fail.
Is there a way we can get the possible values added to the enum?
Is there a workaround we could use without having to manually interrogate the raw json? 

ES version 5.6.5
NEST package 5.5.0

Thanks in advance

**Comment by russcam** [comment]
Thanks for raising @thollowell - this will be fixed in the next 5.x release, which we're hoping to get out today.
