### ISSUE TITLE
InvalidOperationException when using a ClientCertificate with the ElasticLowLevelClient

### ISSUE THREAD

**Issue by jweber** [elastic/elasticsearch-net#3211]
**NEST/Elasticsearch.Net version**: 6.0.2

**Elasticsearch version**: 6.2.2

**Description of the problem including expected versus actual behavior**:
An `InvalidOperationException` is being thrown when I attempt to use a Client Certificate when building the ElasticLowLevelClient. The message I'm seeing says that `The ClientCertificateOptions property must be set to 'Manual' to use this property.`

I tried to work around it by providing a custom IConnection to the ConnectionConfiguration and  overriding the `Elasticsearch.Net.HttpConnection.CreateHttpClientHandler` method. I changing the line `handler.ClientCertificateOptions = ClientCertificateOption.Automatic;` to use `ClientCertificateOption.Manual`. This partially works, but only if I also call `DisablePing` on the ConectionConfiguration. Otherwise the Ping calls fail due to what I assume is another Client Certificate related issue.

**Steps to reproduce**:
 1. Create and use an ElasticLowLevelClient instance configured to use a ClientCertificate

```
var cfg = new ConnectionConfiguration().ClientCertificate("...");

var client = new ElasticLowLevelClient(cfg);
```

**Comment by jweber** [comment]
A few more bits of information. The initial issue was encountered running under a netcore2.0 app. 

I also tried it out under a net4.6 app. In net4.6 I didn't have to have a custom IConnection implementation but encountered similar problems where the Ping calls would fail. If I called `DisablePing()` then it would throw an error with the message `The request was aborted: Could not create SSL/TLS secure channel`

**Comment by jweber** [comment]
Please ignore the comments around `DisablePing()` - it turns out that the user associated with the certificate didn't have permission to make call `HEAD /`.

This does affect the high-level `ElasticClient` as well. I have to pass in the custom `IConnection` class in order to make it work with the client certificate.

**Comment by Mpdreamz** [comment]
Thanks for the updates @jweber just to confirm: your initial problem was on .NET Core?

Not sure if it matters but are you using self generated client certificates?

**Comment by jweber** [comment]
Yep, at this time the issue only appears when running on .NET Core 2 on Windows.

The certificate we're using is signed by an internal certificate authority.

**Comment by Mpdreamz** [comment]
We switched to `ClientCertificateOption.Manual` for CoreFX at some point during #3266 which is a somewhat unrelated but massive PR. Closing this as assumed fixed.
