### ISSUE TITLE
Scroll property in SearchRequest throws a System.InvalidCastException

### ISSUE THREAD

**Issue by HyruleWarrior** [elastic/elasticsearch-net#3220]
**NEST/Elasticsearch.Net version**: 5.6.0

**Elasticsearch version**: 5.6.0

**Description of the problem including expected versus actual behavior**: Scroll property in SearchRequest throws a System.InvalidCastException when trying to retrieve it. In GetQueryStringValue<TOut>() in FluentRequestParameters.cs, it is trying to explicitly cast the Scroll value (a string) into a Time object. Time only has implicit casts in it right now, so this throws an exception.

**Steps to reproduce**:
 1. Create a SearchRequest with the Scroll property set
 2. Try to read this property
 3. Observe that it throws an exception when trying to evaluate it

**Comment by russcam** [comment]
Thanks for opening @HyruleWarrior; this has been fixed and will be in the next release 👍
