### ISSUE TITLE
Assembly Name different from major version.

### ISSUE THREAD

**Issue by alkampfergit** [elastic/elasticsearch-net#3234]
Scenario: I have an application that uses ES, and I want to be able my final user to use the version of ES he like (major version).

Actually if I want to use ES 2.x, 5.x or 6.x I need to use the appropriate version of the NEST, but since the nuget package is the same, and assembly name is the same, I cannot use multiple version of NEST. 

It would be great if NEST 2.x generates assemblies named Nest2 in a package nuget nest2 and so on. This would give me the ability to reference multiple version of NEST and use the appropriate version depending on the version of the server.

Thanks.

**Comment by codebrain** [comment]
Hi @alkampfergit,

A few things here:

1) We do not guarantee binary compatibility between major versions, so the interfaces and classes between NEST 2, 5 and 6 are different. A key difference between NEST 5 and 6 for example is how we perform serialization. It is not going to be possible to write a piece of code to interact with NEST 2 and then simply swap to NEST 6. It may be possible in extremely simple situations, but it is not something we support or recommend.

2) Have you considered loading the assemblies into the GAC? That will allow you to have multiple different versions of the same named assembly.

3) You can create a custom assembly resolver to dynamically load in a different DLL: https://msdn.microsoft.com/en-us/library/system.appdomain.assemblyresolve

You will very likely have to support different implementation codebases/codepaths for each version of NEST / Elasticsearch you'd like to use and there are going to be quite significant featuresets available between each version.

Hope this helps.

**Comment by alkampfergit** [comment]
I do not want to write a piece of code that can interact with NEST2 and NEST6, I want to be able to write *different* pieces of code and choose the one I need.

Ex: I have a class called IDocumentQueryClient that performs search on ES for an entity called Document and I also have IDocumentIndexer that perform indexing of my class.

I have almost 250 unit test that verify indexing and all the queries supported by that interface. 

If I could reference Both NEST2 and NEST5 and NEST6 I can write different concrete implementation for those interface, then during bootstrap of the application, connect with ES with raw connection, parse the json and grab the number, then configure my IoC engine to use the appropriate class.

I do not like using the GAC or custom assembly resolver, because I'm very well aware that all major version are not binary compatible, thus it would be better to have different nuget packages and different assemblynames so I can reference all the version that my code support in the same codebase.

Thanks.

**Comment by russcam** [comment]
Moving to having different nuget packages for different versions of NEST (and Elasticsearch) is unlikely to happen at this stage.

I think your options are
- load multiple versions of the same assembly [using namespace alias qualifiers and `extern alias`](https://blogs.msdn.microsoft.com/abhinaba/2005/11/30/c-2-0-using-different-versions-of-the-same-dll-in-one-application/) with all the caveats that come with this approach
- fork elasticsearch-net and build differently named assembly versions of 2.x, 5.x and 6.x with different namespaces
- use something like Mono.Cecil to rewrite compiled assemblies, renaming namepaces and outputting an assemblies with different names. For example, we internalize and [rewrite the Newtonsoft.Json namespace to Nest.Json](https://github.com/elastic/elasticsearch-net/blob/6.x/build/scripts/Building.fsx#L95-L153) with Mono.Cecil.

**Comment by alkampfergit** [comment]
Understood. 

Is it something you are planning for the future? I think that there is little utility to have a single nuget package and a single assembly name when code is bound to a specific version of ES, but I can easily fork and republish with a different namespace internally.

Thanks.

**Comment by russcam** [comment]
It's not something we have planned for the future; such a change at this point would be really disruptive, particularly to downstream dependencies. It would also make the package upgrading scenario more complex.
