### ISSUE TITLE
Single response from array in top hits aggregation fails to deserialize

### ISSUE THREAD

**Issue by carasel** [elastic/elasticsearch-net#3235]
**NEST/Elasticsearch.Net version**: 5.5.0

**Elasticsearch version**: 5.6.8

**Description of the problem including expected versus actual behavior**:
I have a top hits aggregation, which returns a single nested object. 

    .Aggregations(a => a
                    .Nested("global", gb => gb
                        .Path("locations")
                        .Aggregations(a2 => a2
                            .Terms("locations", l => l
                                .Field("locations.name.keyword")
                                .Aggregations(a3 => a3
                                    .TopHits("locationHit", th => th
                                        .Size(1)
                                    )
                                )
                            )
                        )
                    )

I then try to retrieve the top hit:

            var globalLocations = searchResponse.Aggs.Nested("global").Terms("locations");

            foreach (var globalLocation in globalLocations.Buckets)
            {
                var locationResults = locationHit.Hits<Document>();
            }

This causes the following error:

Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1[MyObject+Location]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'hits[0]._source.locations.coordinates', line 1, position 589.

The json for `locationResults` is:  (locations isn't an array, though it is mapped as nested)
````
{{
  "_index": "documents",
  "_type": "document",
  "_id": "9cd79253703ad1b588d8bec827bc696230a4dac9",
  "_nested": {
    "field": "locations",
    "offset": 0
  },
  "_score": 1.0,
  "_source": {
    "locations": {
      "coordinates": {
        "lat": 37.63983154296875,
        "lon": -123.173828125
      },
      "sizeInKm": 84.83842089198464
    }
  }
}}
````

The Location class looks like this:
````
        public class Location
        {
            public string name { get; set; }
            [GeoPoint]
            public GeoLocation coordinates { get; set; }
            public double sizeInKm { get; set; }
        }
````
and it is nested within a Document:
````
        [ElasticsearchType(Name = "document")]
        public class Document
        {
            ....
            [Nested]
            public List<Location> locations { get; set; }
            ....
        }
````

**Comment by russcam** [comment]
@carasel would you be able to provide the complete JSON response to the request you're making (obfuscate any data that shouldn't be posted publicly)?

**Comment by codebrain** [comment]
Closing due to lack of response.
