### ISSUE TITLE
Could not create an instance of type Nest.IHttpInputAuthentication while executed GetWatch

### ISSUE THREAD

**Issue by gam4er** [elastic/elasticsearch-net#3237]
**NEST/Elasticsearch.Net version**: 6.1.0

**Elasticsearch version**: 5.6.3

It seems, that ElasticClient.GetWatch not work property
 

**Steps to reproduce**:
So, 
`
var node9 = new Uri("http://IP:9200");
IConnectionPool pool = new SniffingConnectionPool(new[] {node9 });
ConnectionSettings connectionSettings_watcher = new ConnectionSettings(pool);
connectionSettings_watcher.BasicAuthentication("USER", "PASS");
connectionSettings_watcher.RequestTimeout(TimeSpan.FromMinutes(10));
connectionSettings_watcher.PrettyJson(true);
 
//just simple call 
elasticClient_watcher.GetWatch("watcher_ID_that_actually_exists");
//cause an exception
`

![default](https://user-images.githubusercontent.com/3364155/39627808-b257d67c-4faf-11e8-914d-b85f08d48f53.png)

But it is an client issue: server send correct data to client. But that data cannot  be parsed into IGetWatchResponse

**Comment by gam4er** [comment]
![default](https://user-images.githubusercontent.com/3364155/39628795-d1b3eaa8-4fb2-11e8-882f-6099479944ae.png)
server answers correctly
it contains watch.actions.webhook.auth parameter, that seems cannot be parsed
![default](https://user-images.githubusercontent.com/3364155/39628903-2d9a505a-4fb3-11e8-8736-6cbb9f56550a.png)

**Comment by russcam** [comment]
Thanks for reporting @gam4er, this is a bug. I've opened  #3241 to address

**Comment by russcam** [comment]
@gam4er PR #3241  is now merged into 5.x and 6.x. Will be in the next releases on nuget 👍

**Comment by gam4er** [comment]
Tnx a lot, guys (-:
You are awesome

2018-05-31 11:37 GMT+03:00 Russ Cam <notifications@github.com>:

**Comment by russcam** [comment]
Thanks for the kind words @gam4er 😄 If you need the fix sooner than the next release, you can reference one of the CI canary packages on MyGet (**note:** _canary packages are not _supported_ like official releases to nuget, since they are prereleases_)

- [5.x](https://www.myget.org/gallery/elasticsearch-net-legacy)
- [6.x](https://www.myget.org/gallery/elasticsearch-net)

For Elasticsearch 5.6.3, you should be using the latest NEST 5.x package.
