### ISSUE TITLE
Issue creating a synonym token filter 

### ISSUE THREAD

**Issue by bpetersen1** [elastic/elasticsearch-net#3240]
I'm having a issue adding the synonym token filter. When adding it to the token filters i get a "object not set to an instance of an object"

` SynonymTokenFilter synonymFilter = new SynonymTokenFilter
            {
                Format = SynonymFormat.Solr,
                SynonymsPath = "synonym.txt",
                Tokenizer = "whitespace",
            };
            IndexSettings isettings = new IndexSettings();
isettings.NumberOfReplicas = 1;
            isettings.NumberOfShards = 2;
isettings.Analysis.TokenFilters.Add("mysynonym", synonymFilter); // it throws an Exception right here
`
I'm leaving out the rest of the code because everything works  well if i comment out the  line that throws the exception.

I really don't know what i'm doing wrong, i tried to follow other examples as well, but with no luck.

Could someone please shed some light on this.

**Comment by russcam** [comment]
[I answered your question on stackoverflow](https://stackoverflow.com/a/50241943/1831). 

We try to reserve GitHub for bug reports and feature requests. The best place to ask a general question is generally at the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch

Thanks!

**Comment by bpetersen1** [comment]
Sorry about that, and thanks a mill, will look into it

**Comment by russcam** [comment]
No worries 😄
