### ISSUE TITLE
DefaultMappingFor non generic accept IdProperty configuration

### ISSUE THREAD

**Issue by josuedallagnese** [elastic/elasticsearch-net#3244]
**NEST/Elasticsearch.Net** version: 6.x (current)

Hi!
In my application, I need to register the mappings in a non-generic way using DefaultMappingFor, because I have only the System.Type of the object.
In this case I do not have access to the existing IdProperty method in the Generic DefaultMappingFor method.

Is there an alternative way (disregarding the use of ElasticsearchTypeAttribute) to perform this registration?

**Comment by russcam** [comment]
The other way is if the property on the type is named `Id` (case-insensitive), then it will be used as the id for the document.

**Comment by russcam** [comment]
Would you be interested in opening a PR to support this @josuedallagnese ?

**Comment by josuedallagnese** [comment]
@russcam Yes! I will ...

**Comment by Mpdreamz** [comment]
I've opened: https://github.com/elastic/elasticsearch-net/pull/3346

To allow IdProperty to be specified when using the non generic `DefaultMappingFor()`
