### ISSUE TITLE
NEST 6 client.UpdateAsync documentation is missing from site

### ISSUE THREAD

**Issue by RevoluPowered** [elastic/elasticsearch-net#3246]
Can't find the documentation for Update or UpdateAsync on the website, can you please document code examples for it's usage please?

Nest 2.x.x documentation is not sufficient.

Tried using google, and also using the site search.

I'd like examples of how to use a partial document, or how to use a direct ID and a full POCO object to replace the existing entry by ID.

**Comment by RevoluPowered** [comment]
bump

**Comment by russcam** [comment]
@RevoluPowered The [integration tests for `Update` and `UpdateAsync`](https://github.com/elastic/elasticsearch-net/tree/master/src/Tests/Document/Single/Update) have a few different examples that may help. There's also [an answer on stackoverflow](https://stackoverflow.com/a/39029907/1831) that may also help.

Having documentation for CRUD operations is on the roadmap but it is a lower priority at the moment. If you'd like to help in getting this documentation together, I'd be more than happy to guide and review.

**Comment by RevoluPowered** [comment]
Thanks, I've got it working now with my own project.

I don't really have any free time to do the documentation, sorry.

**Comment by RevoluPowered** [comment]
For anyone else looking for this, 

Your type is the type you are trying to update.

The documentID is the GUID string of the document you want to get.

client.UpdateAsync<YourType>(DocumentPath<YourType>.Id(documentID string), descriptor => descriptor
.RetryOnConflict(3)
.Doc(datatoupdate))

Then the .Doc(datatoupdate) is where you supply your actual data.

You can attach things like .RetryOnConflict(3) but it's not necessary (if only running one node)

**Comment by Mpdreamz** [comment]
Thanks for the report @RevoluPowered since this covered by the 2nd bullet on this ticket I am closing this as a duplicate:

https://github.com/elastic/elasticsearch-net/issues/2248
