### ISSUE TITLE
RequestConfiguration should expose ThrowExceptions

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#3248]
From @ivan-sam on #3232:

Checked source code.
For branch 5.x I believe only **IRequestConfiguration.EnableHttpPipelining** property is affected, cause IRequestConfiguration does not contain ThrowExceptions property.

Fix may be very simple if public contracts should be preserved:
```
--- a/src/Elasticsearch.Net/ElasticLowLevelClient.cs
+++ b/src/Elasticsearch.Net/ElasticLowLevelClient.cs
@@ -46,7 +46,7 @@ namespace Elasticsearch.Net
 			if (!allow404 && contentType.IsNullOrEmpty()) return requestParams;
 
 			requestParams = requestParams ?? new TRequestParams();
-			if (requestParams.RequestConfiguration == null) requestParams.RequestConfiguration = new RequestConfiguration();
+			if (requestParams.RequestConfiguration == null) requestParams.RequestConfiguration = new RequestConfiguration { EnableHttpPipelining = Settings.HttpPipeliningEnabled };
 			if (allow404)
 				requestParams.RequestConfiguration.AllowedStatusCodes = new[] { 404 };
 			if (!contentType.IsNullOrEmpty() && requestParams.RequestConfiguration.ContentType.IsNullOrEmpty())

```

However, there's related issue in 5.x branch: methods 

- IElasticLowLevelClient.Get<T>
- IElasticLowLevelClient.Delete<T>
- IElasticLowLevelClient.XpackWatcherGetWatch<T>
- IElasticLowLevelClient.XpackWatcherDeleteWatch<T>

does not throw when IConnectionConfigurationValues.ThrowExceptions is set to true and http status code 404 is returned. Not sure whether a new issue should be created. There's a test to reproduce.

```
[Test]
public void GetDocumentThrowsOn404TestWhenConnectionConfiguredToThrow()
{
		var config = new ConnectionConfiguration()
				.ThrowExceptions();
		
		var client = new ElasticLowLevelClient(config);
		Assert.Throws<ElasticsearchClientException>(() => client.Get<byte[]>("non_existing_index", "test", "test"));
}
```

And here is a proposal to address the issue. In short, I changed api generation to **allow404: true** for HEAD methods from Allow404 group (IElasticLowLevelClient.<object>Exists methods) because there's no sense in throwing within methods that check the existence, and set **allow404: !Settings.ThrowExceptions** for other methods from Allow404 group in order to take into account this setting.
```
--- a/src/CodeGeneration/ApiGenerator/Views/ElasticLowLevelClient.Generated.cshtml
+++ b/src/CodeGeneration/ApiGenerator/Views/ElasticLowLevelClient.Generated.cshtml
@@ -59,7 +59,7 @@ namespace Elasticsearch.Net
 		{<text>		[Obsolete("Scheduled to be removed in 6.0, @method.ObsoleteMethodVersion removed this method from the rest specification")]
 </text>}
 		<text>public @Raw(method.ReturnType) @(method.FullName)@(Raw(method.ReturnTypeGeneric))(@Raw(method.Arguments))
-			where @method.CallTypeGeneric : class => this.@(requestMethod)@(Raw("<" + method.CallTypeGeneric +">"))(@method.HttpMethod, Url($"@(Raw(patchedUrl))"), @(method.FullName.Contains("Async") ? "cancellationToken, " : string.Empty)@(method.Parts.Any(pp=>pp.Name == "body") ? "body" : "null"), _params(requestParameters@(method.Allow404 ? ", allow404: true" :"")@(Raw(url.StartsWith("_cat") ? ", contentType: \"text/plain\", accept: \"text/plain\"" : ""))));
+			where @method.CallTypeGeneric : class => this.@(requestMethod)@(Raw("<" + method.CallTypeGeneric +">"))(@method.HttpMethod, Url($"@(Raw(patchedUrl))"), @(method.FullName.Contains("Async") ? "cancellationToken, " : string.Empty)@(method.Parts.Any(pp=>pp.Name == "body") ? "body" : "null"), _params(requestParameters@(method.Allow404 ? (method.HttpMethod == "HttpMethod.HEAD" ? ", allow404: true" : ", allow404: !Settings.ThrowExceptions") :"")@(Raw(url.StartsWith("_cat") ? ", contentType: \"text/plain\", accept: \"text/plain\"" : ""))));
 		</text>
 		}
 	}
```

**Comment by russcam** [comment]
I think `RequestConfiguration` should expose `ThrowExceptions`. I'm thinking that the implementation should mirror 6.x's, with `bool` as opposed to `bool?`, to make upgrading to 6.x from 5.x smoother.

> - IElasticLowLevelClient.Get<T>
> - IElasticLowLevelClient.Delete<T>
> - IElasticLowLevelClient.XpackWatcherGetWatch<T>
> - IElasticLowLevelClient.XpackWatcherDeleteWatch<T>
> 
> does not throw when IConnectionConfigurationValues.ThrowExceptions is set to true and http status code 404 is returned.

> And here is a proposal to address the issue. In short, I changed api generation to **allow404: true** for HEAD methods from Allow404 group (IElasticLowLevelClient.<object>Exists methods) because there's no sense in throwing within methods that check the existence, and set **allow404: !Settings.ThrowExceptions** for other methods from Allow404 group in order to take into account this setting.

Need to have a think about this change /cc @Mpdreamz @codebrain

**Comment by ivan-sam** [comment]
> I think RequestConfiguration should expose ThrowExceptions

In 5.5 `RequestConfiguration` contains `AllowedStatusCodes`. Then the logic should take into account both? I.e. having `RequestConfiguration.AllowedStatusCodes` contains 404 and RequestConfiguration.ThrowExceptions equals true would mean that exception should not be thrown on 404 status code?

**Comment by russcam** [comment]
`AllowedStatusCodes` should only be taken into account for `.IsValid` logic I believe, so _I think_ we should throw for e.g. a 404 on a GET request when `.ThrowExceptions()` is set to `true`.

**Comment by codebrain** [comment]
Closing as change implies port to `5.x`, which is no longer a maintained branch.

https://www.elastic.co/support/eol

`5.6.x` support became end of life on 2019-03-11
