### ISSUE TITLE
Backport of ranking evaluation API

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#3252]
https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-6.2.0.html

Rank Evaluation: Backport of ranking evaluation API - https://github.com/elastic/elasticsearch/pull/27844

**Comment by stevejgordon** [comment]
API is marked as experimental in https://github.com/elastic/elasticsearch/blob/master/rest-api-spec/src/main/resources/rest-api-spec/api/rank_eval.json

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Will be considered within code-gen.
