### ISSUE TITLE
Add WKT Support to Geo

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#3256]
https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-6.2.0.html

Two issues to consider:

- Add WKT Support to GeoBoundingBoxQueryBuilder - https://github.com/elastic/elasticsearch/pull/27692
- Add Well Known Text (WKT) Parsing Support to ShapeBuilders  - https://github.com/elastic/elasticsearch/pull/27417

**Comment by russcam** [comment]
Closing this as #3377 has been merged into 6.3, to go into 6.x
