### ISSUE TITLE
[6.2] Add version support for inner hits in field collapsing

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#3261]
https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-6.2.0.html

Aggregations: Add version support for inner hits in field collapsing - https://github.com/elastic/elasticsearch/pull/27833

**Comment by codebrain** [comment]
I believe this has already been implemented: https://github.com/elastic/elasticsearch-net/blob/e2223918fc95e08872ed15d35bbed16c609601f8/src/Nest/Search/Search/Hits/Hit.cs#L78

@russcam - thoughts?

**Comment by russcam** [comment]
Looks to be implemented. It would be worth extending the [Inner Hits Integration test](https://github.com/elastic/elasticsearch-net/blob/3bba963fde0dafa7f42b281c63eb06ab8b1111d5/src/Tests/Search/Request/InnerHitsUsageTests.cs#L213) to include it

**Comment by codebrain** [comment]
@russcam ` .\build.bat integrate 6.2.0 IntrusiveOperation QueryInnerHitsApi` currently fails...
