### ISSUE TITLE
Updated document ID's

### ISSUE THREAD

**Issue by gvijayakumar-16** [elastic/elasticsearch-net#3265]
Hi,

Can we have an option where we can get the ID's of the documents which got updated?

I am currently dealing with a scenario wherein I need the list of document ID's that got updated using UpdateByQueryAsync and I am making additional calls to retrieve them.

**Comment by russcam** [comment]
I think this may be better asked on https://github.com/elastic/elasticsearch/issues since NEST exposes what is returned from Elasticsearch.

**Comment by gvijayakumar-16** [comment]
Ok, thank you. Will follow up over there
