### ISSUE TITLE
StringEnum Attribute not working on array of enums

### ISSUE THREAD

**Issue by YairHalberstadt** [elastic/elasticsearch-net#3267]
**NEST/Elasticsearch.Net version**: 6.0.0

**Elasticsearch version**: 6.1.3

**Description of the problem including expected versus actual behavior**:
When I index an array of enums with the StringEnum attribute, an exception is thrown: "InvalidCastException: Unable to cast object of type 'MyEnum[]' to type 'System.Enum'."

**Steps to reproduce**:
Run this code:
```
	static class Program
	{
		enum MyEnum
		{
			A,
			B
		}

		class Data
		{
			[StringEnum] public MyEnum[] Enums { get; set; }
		}
		static void Main(string[] args)
		{
			var settings = new ConnectionSettings(new Uri("http://localhost:9200"))
				.DefaultIndex("data").BasicAuthentication("username", "password");
			var client = new ElasticClient(settings);

			client.IndexMany(new[] {new Data {Enums = new[] {MyEnum.A}}});
                }
        }
```

**Comment by YairHalberstadt** [comment]
Looking into the Source Code it looks like the fault is with the StringEnumConverter in JSON.net

I would suggest that a new jsonconverter be created to deal with it. Much of the (open source) code from https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Converters/StringEnumConverter.cs could be reused, with the addition of a case to deal with arrays.

The particular reason I used an array in the first place was because of Flags. I would suggest that whilst doing this it might be sensible to add in an option to convert flags to an array of strings.

**Comment by russcam** [comment]
The `StringEnumAttribute` is a public proxy for the internalized Json.NET `StringEnumConverterAttribute`, so works the same way. Applying the attribute to a POCO property of an array of enums will throw an exception because the attribute expects an enum. 

It can be used in the following ways however

```c#
[StringEnum]
enum MyEnum
{
	A,
	B
}

client.IndexMany(new[] 
{
	new Data 
	{
		Enums = new[] {MyEnum.A, MyEnum.B}
	}
});
```
sends the request

```json
POST http://localhost:9200/_bulk?pretty=true 
{"index":{"_index":"documents","_type":"data","_id":null}}
{"enums":["A","B"]}
```

Or, if wanting to use `FlagsAttribute`

```c#
class Data
{
	public MyEnum Enum {get; set; }
}

[StringEnum]
[Flags]
enum MyEnum
{
	A = 1,
	B = 2
}

client.IndexMany(new[] {
	new Data 
	{
		Enum = MyEnum.A | MyEnum.B
	}
});
```
which sends 

```json
POST http://localhost:9200/_bulk?pretty=true 
{"index":{"_index":"documents","_type":"data","_id":null}}
{"enum":"A, B"}
```

I think you're looking for the first option.

**Comment by YairHalberstadt** [comment]
Thanks
That worked for indexing data to elasticsearch, but when I try to search I now get this error:
"ArgumentException: Could not cast or convert from System.String to MyEnum[]."

CODE:
```
var searchResponse = client.Search<Data>(s => s
	.Query(q => q
		.Term(t => t
			.Field(fi => fi.Enum)
			.Value(MyEnum.A)
		)
	);
```

**Comment by YairHalberstadt** [comment]
The issue can be worked round by using a different class for indexing and searching, so Index with 
```
		class DataIndex
		{
			public MyEnum[] Enums { get; set; }
		}
```
and search with 
```
		class DataSearch
		{
			public MyEnum Enums { get; set; }
		}
```
But this is obviously extremely hacky and the bug really should be resolved

**Comment by YairHalberstadt** [comment]
Thanks, that worked

**Comment by russcam** [comment]
Glad it worked @YairHalberstadt. Can we close this issue?

**Comment by YairHalberstadt** [comment]
Yes, thank you for your help
