### ISSUE TITLE
Is attribute necessary?

### ISSUE THREAD

**Issue by SnailDev** [elastic/elasticsearch-net#3269]
**NEST/Elasticsearch.Net version**: 6.0.2

**Elasticsearch version**: v6.1.2

**Description of the problem including expected versus actual behavior**:
```C#
    [Serializable]
    [BsonIgnoreExtraElements]
    public class CouponLifeCycle : IEntity<string>
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string ID { get; set; }

        // [BsonElement("MallID")]
        // [Number(Name = "MallID")]
        public long MallID { get; set; }
    }
```
![image](https://user-images.githubusercontent.com/30819423/40776794-69fefcca-64fe-11e8-9c48-8b1e26657958.png)

if I use ***[Number(Name = "MallID")]*** both test and test1 value  normal ,  but when haven't use ***[Number(Name = "MallID")]***  test value normal and test1 value is unexpected，Is attribute necessary?

**Comment by russcam** [comment]
Hey @SnailDev, we like to reserve GitHub for feature requests and reporting bugs. The best place to ask a general question like this in the future is at the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Thanks! 

[NEST camel-cases property names by default](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/field-inference.html#camel-casing) to get the field name for Elasticsearch e.g. `mailId`. By using the attribute with a `Name` property, you explicitly tell NEST to use the value given in the `Name` property, in this case `MailID`.

If you can override NEST's property name behaviour by passing a `Func<string, string>` to [`DefaultFieldNameInferrer(...)`](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/configuration-options.html#_options_on_connectionsettings) e.g.

```c#
var settings = new ConnectionSettings(new Uri("http://localhost:9200"))
    .DefaultFieldNameInferrer(s => s);

var client = new ElasticClient(settings);
```

With this configuration, NEST will use whatever the name of the property on the POCO is, _unless_ explicitly overridden with an attribute (`NumberAttribute`, `PropertyNameAttribute`, etc.) or in a `DefaultMappingFor<TDocument>(...)` configuration for the given `TDocument` POCO type.

[Attribute mapping](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/attribute-mapping.html) and [fluent mapping](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/fluent-mapping.html) are used to explicitly control how properties on POCOs map to fields.

**Comment by SnailDev** [comment]
@russcam ok, I guess this is a bug so I ask this question here. may be i should learn elasticsearch & nest more.

Thanks!
