### ISSUE TITLE
TopHits aggregation is missing DocValueFields

### ISSUE THREAD

**Issue by jtreher** [elastic/elasticsearch-net#3274]
Currently, Nest only supports DocValueFields in `InnerHits`, however, this is also a valid argument for `TopHits` aggregations. However, I see that in Nest there is the option to specify FieldDataFields which DocValueFields will ultimately make use of if available. FieldDataFields is currently not listed as a supported per hit feature in the documentation. https://www.elastic.co/guide/en/elasticsearch/reference/6.2/search-aggregations-metrics-top-hits-aggregation.html

Should this be renamed or is there a reason for using FieldDataFields?

**Comment by russcam** [comment]
Thanks for opening @jtreher. This is a bug; I'll add DocValueFields and deprecate FieldDataFields
