### ISSUE TITLE
Support reindex

### ISSUE THREAD

**Issue by ThomasArdal** [elastic/elasticsearch-net#328]
Other clients for ElasticSearch supports reindexing entire index as described here: http://www.elasticsearch.org/blog/changing-mapping-with-zero-downtime/#_reindexing_your_data

It would be cool to support this flow in NEST as well.

**Comment by eamocanu** [comment]
I have a parent child index and calling reindex with object type throws a no documents exist in index exception: client.Reindex<object>(...) -> exception
I have to reindex each type one after another; the problem becomes that if index already exist cannot use reindex() to insert other documents into it -> exception is thrown again.

Has anyone else found this behaviour?

**Comment by benbenwilde** [comment]
In my opinion, the NEST implementation has too many requirements and assumptions.
1. You must create a new index during the reindex (can't just set it up yourself and then call re-index)
2. You must setup all the settings and mappings during the reindex (you can't use your method of choice for these things, and the fluent interface is not as easy as alternative methods)
3. The from-index must have documents

The current implementation may work for some, but for those who are looking for another way:
http://stackoverflow.com/a/34867857/2284031
