### ISSUE TITLE
VerbatimDictionaryKeysJsonConverter is not used by JsonNetSerializer

### ISSUE THREAD

**Issue by dejonghee** [elastic/elasticsearch-net#3280]
Both Elastic 5 and 6 contain a VerbatimDictionaryKeysJsonConverter which is a JSON converter for IDictionary that ignores the contract resolver.

When using the JsonNetSerializer source serializer, the VerbatimDictionaryKeysJsonConverter is not applied and the casing of dictionary keys changes.

Since the VerbatimDictionaryKeysJsonConverter class is internal, it can also not be added as JsonConverter to the JsonNetSerializer.

Is there a way to enforce the old behaviour in combination with the JsonNetSerializer?

**NEST/Elasticsearch.Net version**: 6.1

**Elasticsearch version**: 6.1

**Steps to reproduce**:
I wrote a console application with a repro of the problem, see: [https://github.com/EmanuelDejonghe/elastic-repro-serialization/blob/master/DictionarySerialization/Program.cs](https://github.com/EmanuelDejonghe/elastic-repro-serialization/blob/master/DictionarySerialization/Program.cs)

**Comment by russcam** [comment]
Thanks for opening @dejonghee. `VerbatimDictionaryKeysJsonConverter` is only applied to types that use the internal serialization. When using `Nest.JsonNetSerializer` package, the serialization/deserialization of `_source` documents (plus a few other places in the APIs where a user can provide a document) is the responsibility of the `JsonNetSerializer` which has the default configuration of Json.NET by default. If you'd like to have the same behaviour as the internal serializer, you could define a `NamingStrategy` that

1. Serializes Dictionary keys verbatim
2. Serializes field names using the `DefaultFieldNameInferrer` from `ConnectionSettings`

```c#
private static void Main()
{
    var defaultIndex = "documents";
	var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));

    var settings = new ConnectionSettings(
        pool, 
        new InMemoryConnection(), 
        (builtin, connSettings) => new JsonNetSerializer(builtin, connSettings, modifyContractResolver: resolver => resolver.NamingStrategy = new DictionaryKeysNamingStrategy(new Lazy<Func<string,string>>(() => connSettings.DefaultFieldNameInferrer))))
        .DefaultIndex(defaultIndex)
		.BasicAuthentication("elastic", "elastic")
        .DisableDirectStreaming()
        .PrettyJson()
        .OnRequestCompleted(callDetails =>
        {
            if (callDetails.RequestBodyInBytes != null)
            {
                Console.WriteLine(
                    $"{callDetails.HttpMethod} {callDetails.Uri} \n" +
                    $"{Encoding.UTF8.GetString(callDetails.RequestBodyInBytes)}");
            }
            else
            {
                Console.WriteLine($"{callDetails.HttpMethod} {callDetails.Uri}");
            }

            Console.WriteLine();

            if (callDetails.ResponseBodyInBytes != null)
            {
                Console.WriteLine($"Status: {callDetails.HttpStatusCode}\n" +
                         $"{Encoding.UTF8.GetString(callDetails.ResponseBodyInBytes)}\n" +
                         $"{new string('-', 30)}\n");
            }
            else
            {
                Console.WriteLine($"Status: {callDetails.HttpStatusCode}\n" +
                         $"{new string('-', 30)}\n");
            }
        });

    var client = new ElasticClient(settings);

    var record = new Record
    {
        Id = 1,
        Data = new Dictionary<string, string>
                {
                    {"Hello World", "Value 1"}
                }
    };
    
    client.IndexDocument(record);
}

public class DictionaryKeysNamingStrategy : NamingStrategy
{
    private Lazy<Func<string, string>> _inferrer;
    
    public DictionaryKeysNamingStrategy(Lazy<Func<string, string>> inferrer) => 
        _inferrer = inferrer;

    protected override string ResolvePropertyName(string name) => 
        _inferrer.Value(name);

    public override string GetDictionaryKey(string key) => key;
}

public class Record
{
    public int Id { get; set; }
    public IDictionary<string, string> Data { get; set; }
}
```

This makes the following request

```json
PUT http://localhost:9200/documents/record/1?pretty=true 
{
  "id": 1,
  "data": {
    "Hello World": "Value 1"
  }
}
```

An alternative would be to copy the source of `VerbatimDictionaryKeysJsonConverter` and apply it to any dictionaries that require it; it's not possible to use that internal type with Json.NET directly as the Json.NET assembly referenced by NEST is internalized within NEST and renamespaced, effectively making all of the types defined within different and incompatible with Json.NET.

**Comment by dejonghee** [comment]
@russcam Thanks for the clear answer!
Maybe it would be useful to add this to the 'breaking changes' documentation?
