### ISSUE TITLE
SocketsHttpHandler adoption for dotnet core 2.1

### ISSUE THREAD

**Issue by Elufimov** [elastic/elasticsearch-net#3296]
**Describe the feature**:
Hi! Right now we are in a migration process to dotnet core, and we are notensed a significant cpu penalty (up to two times) between nest under .net framework 4.6.2 and dotnet core. We managed to reduce it by creating a custom IConnection based on SocketsHttpHandler instead of HttpClientHandler.

**Comment by russcam** [comment]
Awesome @Elufimov! Would you be happy to share the implementation/contribute it to NEST?

**Comment by Elufimov** [comment]
We would be happy, but we have incomplete impl. Without ssl and proxy. We do not use these features in our environment. We can share what we have if it would be useful for you.

**Comment by russcam** [comment]
@Elufimov that would still be useful I think. Would you like to open a PR against the master branch with what you have, and contribute it to the project?

**Comment by Mpdreamz** [comment]
`HttpClientHandler` will use `SocketsHttpHandler` on .NET 2.1 and over. Closing this as stale.

The CurlHandler from older .NET core releases is not the most stable sadly.

Feel free to reopen if you feel there is still something actionable here @Elufimov
