### ISSUE TITLE
Indexing JObject causing all values in the document to be empty array

### ISSUE THREAD

**Issue by jhellemann** [elastic/elasticsearch-net#3298]
**NEST/Elasticsearch.Net version**: 6.1.0

**Elasticsearch version**: 6.2.1

**Description of the problem including expected versus actual behavior**:

In the process of upgrading NEST and ES from 5.x to 6.x we discovered that our current generic method for indexing .NET models, convert them into generic `JObjects`, caused all values to be set to empty array in Elasticsearch. 

*Expected (NEST/ES 5.x):*
```
{
  "_index": "member_search",
  "_type": "member",
  "_id": "123p123456",
  "_version": 1,
  "found": true,
  "_source": {
    "identity": {
      "centerId": 123,
      "id": 123456
    },
    "externalMemberId": "123456",
    "firstName": "Ola",
    "lastName": "Nordmann",
    "fullName": "Ola Nordmann",
    "hasProfilePicture": true,
    "email": null,
    "mobile": "+47 9000000",
    "address": {
      "address": "Park lane 1",
      "postalCode": "0001",
      "postalArea": "OSLO",
      "country": "NO"
    }
}
```

*Actual (NEST/ES 6.x):*
```
{
  "_index": "member_search",
  "_type": "member",
  "_id": "123p123456",
  "_version": 1,
  "found": true,
  "_source": {
    "identity": {
      "centerId": [],
      "id": []
    },
    "externalMemberId": [],
    "firstName": [],
    "lastName": [],
    "fullName": [],
    "hasProfilePicture": [],
    "email": [],
    "mobile": [],
    "address": {
      "address": [],
      "postalCode": [],
      "postalArea": [],
      "country": []
    }
}
```

**Steps to reproduce**:
 1. index a `JObject` document using either `_client.BulkAsync(request)` or `_client.IndexAsync(request)`
 2. Compare documents in ES/Kibana 5.x vs 6.x

**Comment by russcam** [comment]
Hey @jhellemann, this is a duplicate of #3228, #3186 and #2975. 

Given that it's come up a few times, I think we ought to take this opportunity to [call it out in the 6.x breaking changes](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/nest-breaking-changes.html) and [Custom Serializer documentation.](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html)

**Comment by jhellemann** [comment]
@russcam Thank you for really fast response :) I will look into docs and other issues. Guess the best solution for us will be to use our models for indexing.
