### ISSUE TITLE
Access to response headers

### ISSUE THREAD

**Issue by CasperSkydt** [elastic/elasticsearch-net#3300]
I have an issue where i need to access response headers. 
I have not found a solution, that makes access to these, unless i sniff them through fiddler/proxy.  

Currently you are able to access responsebody through: response.ApiCall.ResponseBodyInBytes...  would be nice to access the response headers the same way.

I am using version 5.x of the nest client.

**Comment by Mpdreamz** [comment]
Can you tell me a bit more about why you need access to the response headers?

The only way to currently get to them is to use your own `IConnection` implementation possibly by subclassing `HttpConnection` but it would be hard/impossible to pass it along to the final response.

Without a clear use-case, I'm not inclined to expose them.

**Comment by CasperSkydt** [comment]
We have akamai cdn in front of elasticsearch as a cachelayer, using akamai POST cache for better global response. 

Our service runs in AWS Lambda calling Elasticsearch through akamai cdn. Some weird shenanigans was happening between akamai and AWS Lambda, and the akamai PRAGMA response headers had the information that could help me debug the issue. 

But recently AWS Lambda was upgraded to .net core 2.1 and the issue has been solved by the new implementation of HttpClient on linux. 

Could still see use cases where the response headers could contain information for tracing across service boundaries.

**Comment by Mpdreamz** [comment]
Thanks so much for the use case @CasperSkydt ! That makes a lot of sense. 

In that case i think implementing your own `IConnection` or `HttpConnection` subclass probably will suffice.
