### ISSUE TITLE
Improvement suggestion for documentation

### ISSUE THREAD

**Issue by RevoluPowered** [elastic/elasticsearch-net#3307]
I recommend that the examples for aggregations be improved.

For example, this example gives you the commit activity breakdown via aggregation. (taken from nest documentation)
```csharp 
s => s
.Aggregations(aggs => aggs
    .Children<CommitActivity>("name_of_child_agg", child => child
        .Aggregations(childAggs => childAggs
            .Average("average_per_child", avg => avg.Field(p => p.ConfidenceFactor))
            .Max("max_per_child", avg => avg.Field(p => p.ConfidenceFactor))
            .Min("min_per_child", avg => avg.Field(p => p.ConfidenceFactor))
        )
    )
)
```
I believe this is too much for new users to take in, and I think the example could be simplified down so that the user can see everything, it makes more sense to provide them with all the information e.g.

I would make this a bit simpler by providing a simpler example, with proper names and type info. Also commenting to explain to the developer what that actually does is a good idea too.

Lowering the bar of complexity is better for the user of the system, because less can go wrong if something is simpler.

```csharp 
// Our apple data we store
public class Apple
{
    public float Calories {get;set;}
}

// Our aggregated result from the data
public class AppleSummary
{
    public float UserRating {get;set;}
    public float Calories {get;set;}
}

// do a search over the data, matching everything
_client.Search<Apple>( s=>s.MatchAll()
// aggregate some data
.Aggregations(aggs => aggs
    // Make a child aggregation
    .Children<AppleSummary>("AppleAggregation", child => child
        .Aggregations(childAggs => childAggs
             // calculate the average user rating of the apples.
            .Average("average_user_rating", avg => avg.Field(p => p.UserRating))
             // calculate the calories consumed in total, if all the apples are eaten.
            .Sum("calories", sum => sum.Field(p => p.Calories))
        )
    )
)
```

I only recommend this because elasitcsearch is amazing, but it's difficult to make full use of it without good examples by the original developers of the API.

This also means that if the developer has to explain themselves a bit, the API can become clearer to the implementer.

**Comment by RevoluPowered** [comment]
bump because of inactivity

**Comment by Mpdreamz** [comment]
Long overdue reply will be a short one: I agree the intro could be improved upon with a clearer lead in on what the code in is actually doing functionally.  😄 

https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/writing-aggregations.html

The source for this lives here: https://github.com/elastic/elasticsearch-net/blame/master/src/Tests/Aggregations/WritingAggregations.doc.cs

**Comment by Mpdreamz** [comment]
Added this as bullet item under #2248, thanks again for the callout @RevoluPowered suggestions like these are very much appreciated and keep us sharp!
