### ISSUE TITLE
Attempting to resurrect a dead node takes 21 seconds even after a ping failure

### ISSUE THREAD

**Issue by bittusarkar** [elastic/elasticsearch-net#3308]
**NEST/Elasticsearch.Net version**: 5.5.0

**Elasticsearch version**: 5.4.1

**Description of the problem including expected versus actual behavior**: Code containing the Nest client runs in Azure PaaS VMs and Elasticsearch nodes are hosted in IaaS VMs. The PaaS VMs can see the IaaS VMs through Azure virtual network peering. We use static connection pool to fire requests against two client nodes. If one node goes down, the request takes around 42 seconds to fail on the dead node before firing the request on the other alive node. After some time, Nest tries to resurrect the dead node and takes around 21 seconds before attempting the request on the alive node. This repeats again till the dead node comes up. As a result, every request on a resurrection attempt is significantly slow.

**Steps to reproduce**:
 Below is the simplified code I used to reproduce this issue:
```
IConnectionPool connectionPool = new StaticConnectionPool(new[] { new Uri("http://192.168.0.51:9200"), new Uri("http://192.168.0.52:9200") });
ConnectionSettings connectionSettings = new ConnectionSettings(connectionPool)
    .DisableDirectStreaming()
    .RequestTimeout(TimeSpan.FromSeconds(60));

ElasticClient elasticClient = new ElasticClient(connectionSettings);

while (true)
{
    ISearchResponse<object> queryResponse = elasticClient.Search<object>(sd => sd
        .Index(Indices.All)
        .Type(Types.All)
        .Query(q => q.MatchAll()));

    StringBuilder auditMessageStringBuilder = new StringBuilder();
    if (queryResponse.ApiCall?.AuditTrail != null)
    {
        foreach (Audit audit in queryResponse.ApiCall.AuditTrail)
        {
            auditMessageStringBuilder.AppendLine($"Started: [{audit.Started:o}], Took: [{audit.Ended - audit.Started}], Node: [{audit.Node?.Uri}], Event: [{audit.Event}], NodeAlive: [{audit.Node?.IsAlive}], Exception: [{audit.Exception?.Message}]");
        }
    }

    if (auditMessageStringBuilder.Length > 0)
    {
        Console.WriteLine(auditMessageStringBuilder.ToString());
    }
    
    Thread.Sleep(TimeSpan.FromSeconds(1));
}
```
When both nodes are alive, the following gets logged (all good):
```
Started: [2018-06-28T10:08:45.6792579Z], Took: [00:00:00.0897403], Node: [http://192.168.0.51:9200/], Event: [HealthyResponse], NodeAlive: [True], Exception: []

Started: [2018-06-28T10:08:46.7914112Z], Took: [00:00:00.0312770], Node: [http://192.168.0.52:9200/], Event: [HealthyResponse], NodeAlive: [True], Exception: []
```

When I shut down node `192.168.0.51`, the following gets logged (request fails on dead node and spends 42 seconds):
```
Started: [2018-06-28T10:09:18.2710668Z], Took: [00:00:42.0563033], Node: [http://192.168.0.51:9200/], Event: [BadRequest], NodeAlive: [False], Exception: []
Started: [2018-06-28T10:10:00.3273701Z], Took: [00:00:00.0309880], Node: [http://192.168.0.52:9200/], Event: [HealthyResponse], NodeAlive: [True], Exception: []
```

When Nest tries to resurrect the dead node, the following gets logged (resurrection attempt takes 21 seconds):
```
Started: [2018-06-28T10:11:00.3488695Z], Took: [00:00:00], Node: [http://192.168.0.51:9200/], Event: [Resurrection], NodeAlive: [False], Exception: []
Started: [2018-06-28T10:11:00.3488695Z], Took: [00:00:21.0201337], Node: [http://192.168.0.51:9200/], Event: [PingFailure], NodeAlive: [False], Exception: [An error occurred trying to read the response from the specified node.]
Started: [2018-06-28T10:11:21.3690032Z], Took: [00:00:00.0624720], Node: [http://192.168.0.52:9200/], Event: [HealthyResponse], NodeAlive: [True], Exception: []
```
On testing the same code in Nest 6.1.0, the failed resurrection attempt takes 2 seconds (log below):
```
Started: [2018-06-28T11:39:56.7062205Z], Took: [00:00:00], Node: [http://192.168.0.51:9200/], Event: [Resurrection], NodeAlive: [False], Exception: []
Started: [2018-06-28T11:39:56.7062205Z], Took: [00:00:02.0181905], Node: [http://192.168.0.51:9200/], Event: [PingFailure], NodeAlive: [False], Exception: [An error occurred trying to read the response from the specified node.]
Started: [2018-06-28T11:39:58.7244110Z], Took: [00:00:00.0462106], Node: [http://192.168.0.52:9200/], Event: [HealthyResponse], NodeAlive: [True], Exception: []
```
So, I believe a bug fix was taken for reducing the resurrection time. Unfortunately, we cannot move to the latest version of Nest just yet. If one can point me to the fix pull request/commit, I will try to backport it to the version we use.

Also, is there a way to minimize the 42 seconds spent on firing the request on a dead node? I came across [this issue](https://github.com/elastic/elasticsearch-net/issues/1475) and tried using `SetTcpKeepAlive()` on connection settings but that did not help.

**Comment by Mpdreamz** [comment]
Hey @bittusarkar sorry for the late reply.

This should be fixed with: https://github.com/elastic/elasticsearch-net/commit/9328a147bbdbb8824f93978d9a3a1836a1fe0d3a

Which was released after `5.5.0`, try updating the client to the latest `5.x` release.
