### ISSUE TITLE
deserialize Json Query

### ISSUE THREAD

**Issue by mazadard** [elastic/elasticsearch-net#3312]
Hi everybody, 

I builded a lot of query with the DSL Json language of elasticsearch, and now I want to make then interactive. To do that I think the best way is to deserialize them in a way that i can used them with the NEST client. 

Is that possible ? 

I am not very familiar with those concepts but I hope one you are ! ;) 

Robin, 
France.

**Comment by Mpdreamz** [comment]
Hey @mazadard 

please have a read through our documentation on writing queries:
https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/writing-queries.html

Your question is a bit too open-ended to close this with a definitive answer.
