### ISSUE TITLE
Add date format to DateHistogram source for Composite Aggregation

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#3317]
Relates: https://github.com/elastic/elasticsearch/pull/28310

Add ability to specify a date format for `DateHistogramCompositeAggregationSource`. Property should be XML commented to indicate that it only applies to 6.3.0+

**Comment by Mpdreamz** [comment]
Started on this locally, still need to write an integration tests for it before submitting a PR though.

**Comment by russcam** [comment]
Closing as #3367 has been merged into 6.3
