### ISSUE TITLE
Support 3rd dimension (Z value) to points for geo_point and points in geo_shapes

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#3318]
Relates: https://github.com/elastic/elasticsearch/pull/25738

Add support for indexing Z value (3rd dimension) points in geo_point and geo_shape. This value is returned on `_source` documents, and not used in queries

Mapping for [`geo_point`](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html#geo-point-params) and [`geo_shape`](https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-shape.html#geo-shape-mapping-options) should also support `ignore_z_value` parameter

**Comment by Mpdreamz** [comment]
`geo_point`  `ignore_z_value` is in #3364 

Adding a PR for `geo_shape` now.

**Comment by russcam** [comment]
Closing as added in #3364
