### ISSUE TITLE
Add support for `allow_partial_search_results` search request parameter

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#3321]
Relates: https://github.com/elastic/elasticsearch/pull/27906
Documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-uri-request.html#_parameters_3

Add support for `allow_partial_search_results` request parameter to return an overall failure if the request would produce partial results

**Comment by Mpdreamz** [comment]
This is part of the `6.3` branch after code generation.

**Comment by russcam** [comment]
Closing this as it's part in 6.3 codegen
