### ISSUE TITLE
Add acknowledge request parameter to Start Trial API

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#3324]
Relates: https://github.com/elastic/elasticsearch/pull/30135
Documentation: https://www.elastic.co/guide/en/elasticsearch/reference/current/start-trial.html

`acknowledge` request query string parameter is required in 6.3.0+. This should be picked up when upgrading the REST API specs.

**Comment by Mpdreamz** [comment]
This should be in the `6.3` branch now.

**Comment by russcam** [comment]
Closing as this now exists in 6.3 branch from codegen
