### ISSUE TITLE
Add Adaptive selection statistics to NodeStats

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#3329]
Relates: https://github.com/elastic/elasticsearch/pull/28721
Documentation: https://www.elastic.co/guide/en/elasticsearch/reference/6.3/cluster-nodes-stats.html#adaptive-selection-stats

Also, 

- Ingest statistics are missing; add these
- Look at rename of `breakers` to `breaker` for field data circuit breaker stats (may be wrong `JsonProperty` name in client, or renamed in ES source).

**Comment by Mpdreamz** [comment]
`breakers` is still the property name in the response, if you want to filter on it you need to specify `breaker` though in the URL which is correctly defined in `NodesStatsMetric`. No action needed.
