### ISSUE TITLE
lack of response on issue tracker

### ISSUE THREAD

**Issue by RevoluPowered** [elastic/elasticsearch-net#3332]
**NEST/Elasticsearch.Net version**:
Latest

**Elasticsearch version**:
Latest

**Description of the problem including expected versus actual behavior**:
Lack of response about basic issues on github

**Steps to reproduce**:
 1. submit ticket
 2. wait 20 days
 3. ticket still not answered

**Describe the feature**:
1. Response to issues.

**Comment by russcam** [comment]
Please exercise some patience; we have been working on [6.2.0](https://github.com/elastic/elasticsearch-net/releases/tag/6.2.0) and [5.6.3](https://github.com/elastic/elasticsearch-net/releases/tag/5.6.3) releases of the client, which contain a lot of changes. Opening a new issue to complain isn't helpful or constructive.

**Comment by RevoluPowered** [comment]
20 days is a lot of time to be waiting for a reply; I've shown patience. Perhaps forewarn people of this and give them a time-frame? 

So we can communicate more effectively.

**Comment by RevoluPowered** [comment]
Additionally, what do you mean you've been working on 6.2, 5.6.

Those were released 2 weeks ago, I don't really understand.

**Comment by Mpdreamz** [comment]
@RevoluPowered the issue you opened https://github.com/elastic/elasticsearch-net/issues/3307 is an open ended discussion. We really appreciate you raising the issue and would love to give it the attention it deserves.

Our docs are generated from our tests and so to actually include greater context needs some further contemplation. All of this results in the ticket being open longer as even a reply that lays out the current state with some suggestions on how to implement an improvement takes time. 

Asking for a quick 👍 or 👎 on the issue itself would also be appreciated, a gentle bump on the issue itself as you did at the same time as opening this issue would also be appreciated. Opening a very passive aggressive ticket not so much. 

If you must understand: we work on several different repositories and have other responsibilities too (training, helping support, etc) that we need to prioritize just like everyone else.

I am sincerely sorry you did not feel heard. I hope you can extend us the same level of empathy.

**Comment by RevoluPowered** [comment]
I'm fine with that mate, it was just literally didn't like raising something which wasn't actually acknowledged.

If you're quite stretched I can understand, we're the same, but it's not just myself which hasn't been listened to. Its the other 10 tickets which popped up after I posted my one. That was my concern. 

It was starting to look non-maintained; without any 'hey we're busy with stuff at the moment, but we will get back to you in x days'. That was the reality, but I didn't know that. I think communication is key here, if you're busy, I'm more than happy to wait a month for a reply; with notice, but again having that notification makes people less annoyed.

**Comment by RevoluPowered** [comment]
In hindsight you were right, next time I'll be more patient and do what you recommended. Sorry about that.
