### ISSUE TITLE
Add default value handling to value type attributes

### ISSUE THREAD

**Issue by Henr1k80** [elastic/elasticsearch-net#3336]
Like we discussed in this thread:
https://discuss.elastic.co/t/nest-avoid-storing-default-values-false-0-etc/140457
I would like the option for avoid serializing, sending, storing and indexing default values.
Could be something like the JsonNet syntax:
[Boolean(DefaultValueHandling = DefaultValueHandling.Ignore)]
public bool SeldomTrueAndOnlyFilteredOnTrueNeverFalseAndNeverSortedOn { get; set; }
and the default should of course be the current default so backwards compability is not broken.

I might be able to contribute this feature at a later time, but I do not have the time right now.

**Comment by Mpdreamz** [comment]
I'm not immediately keen to start supporting this. This should be serializer concern and the serializer is already injectable in NEST. 

Would another route be to project your document into another class or make the property a nullable `bool?` ?

Do appreciate opening an issue to discuss! 😄

**Comment by Mpdreamz** [comment]
cc @elastic/microsoft
