### ISSUE TITLE
max_result_window

### ISSUE THREAD

**Issue by shmera55** [elastic/elasticsearch-net#3337]
max_result_window option not available in C# 

Please help on the same & Thanks !!!

**Comment by Mpdreamz** [comment]
We only strongly type *some* known keys on `IndexSettings` 

`IndexSettings` is a dictionary though so you can set any value you like e.g

```csharp
var settings = new Nest.IndexSettings(new Dictionary<string, object>
{
	{ "any.setting", "can be set" },
	{ "doubles", 1.1 },
	{ "bools", false },
	{ "enums", IndexOptions.Offsets },
})
{
	NumberOfShards = 1,
	NumberOfReplicas = 2,
};
```
