### ISSUE TITLE
NEST BulkUpdateOperation doesn't expose "refresh"

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch-net#3339]
***NEST version***: 6.1
***ES version***: 6.1.1

I'm wanting to make changes where immediate searchability is not required by exposing the `refresh` option to my callers but I've discovered that `BulkUpdateOperation` does not expose it.  It seems to expose pretty much every other parameter that's documented so I'm not sure why it's missing.  At any rate, is there a way for me to set this in a `BulkUpdateOperation`?  I do see it in the `BulkDescriptor` that I use for staight "Index" operations.

**Comment by Mpdreamz** [comment]
The `refresh` option is not something you set on a per operation basis only per `_bulk` operation.  You either refresh affected shards of the bulk operations or you don't. 

This is reflected in NEST and thus only available on the `BulkDescriptor` that describes the whole request.

Hope that makes sense :smile:

**Comment by tdoman** [comment]
@Mpdreamz Yep, I see it now, thank you.
