### ISSUE TITLE
No assembly in Nuget Package 6.2.0 on .NetFramework 4.5

### ISSUE THREAD

**Issue by Hansi111** [elastic/elasticsearch-net#3348]
**NEST/Elasticsearch.Net version**: 6.2.0

**Elasticsearch version**: 6.3.0

**Description of the problem including expected versus actual behavior**:
"Could not install package 'Elasticsearch.Net 6.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

**Steps to reproduce**:
 1. Open Visual Studio
 2. Create a .Net Framework 4.5 project
 3. Try to install Elasticsearch.Net with Nuget

Elasticsearch.Net 6.1.0 works perfect, it´s just the latest Version that doesn´t work, so it´s probably just forgotten?

![grafik](https://user-images.githubusercontent.com/42027332/43572140-0b6ac384-963f-11e8-8dcd-612433317988.png)

**Comment by Mpdreamz** [comment]
Hey @Hansi111 thanks for reporting this. 

We purposefully removed `.NET 4.5` support (see #3334) but we left the `<dependencyGroup>` in our `.nuspec` files, this will be fixed when we release a new version.

**Comment by Hansi111** [comment]
Ah thanks :)
Now i have to convince my team to upgrade^^

**Comment by Mpdreamz** [comment]
`.NET 4.5` is EOL'd. Only `.NET 4.5.2` is still supported by MS but is also over 4 years old

see: https://en.wikipedia.org/wiki/.NET_Framework_version_history

Maybe these tidbits help make your case 😸
