### ISSUE TITLE
BulkDescriptor has methods that cannot be mocked (feature request)

### ISSUE THREAD

**Issue by SwintDC** [elastic/elasticsearch-net#3372]
**Describe the feature**:
The following classes have methods which cannot be mocked using the Moq library:
- BulkDescriptor
- BulkCreateDescriptor
- BulkIndexDescriptor
- BulkDeleteDescriptor
- BulkUpdateDescriptor

To be able to mock these methods, they must be included in a interface or abstract class (as an overridable method).

Is it possible to make them mockable? (A lot of developers would probably benefit from this improvement)

**Comment by Mpdreamz** [comment]
Hi @SwintDC, I am a firm believer you should only mock your service layer or code you own. If you need to mock something not under your control it probably needs to be abstracted as a service/provider interface that you do control. That makes mocking so much more targetted and powerful. 

For that reason, I am not going to make anything an interface in the client just for mocking purposes.
