### ISSUE TITLE
No Nest support for DynamicTemplate.MatchPattern (match_pattern property)

### ISSUE THREAD

**Issue by jacob-123** [elastic/elasticsearch-net#3373]
**NEST/Elasticsearch.Net version**:
5.6.2 (Not present @5.6.3 as well
**Elasticsearch version**:
5.6.4
**Description of the problem including expected versus actual behavior**:
JSON: 
"my_dynamic_mapping_string": {
	"match_pattern": "regex",
	"path_match": "foo[0-9]",
	"match_mapping_type": "string",
	  "fielddata": true,
	  "copy_to": "bar"
Expected Nest:
.DynamicTemplate("my_dynamic_mapping_string", dm => dm
	.MatchMappingType("string")
	.PathMatch("foo[0-9]")
	.MatchPattern("regex")
	.Mapping(m => ...)
	);
Actual Nest gets an error :
Error	18	'Nest.DynamicTemplateDescriptor<dynamic>' does not contain a definition for 'MatchPattern' and no extension method 'MatchPattern' accepting a first argument of type 'Nest.DynamicTemplateDescriptor<dynamic>' could be found (are you missing a using directive or an assembly reference?)	

**Steps to reproduce**:
1. Use Nest 5.6.x
 2. Create a dynamic Mapping using the above Dynamic Template :
    client.Map<dynamic>(x => x.Index(indexName).Type(typeName) 
           .DynamicTemplates(dt => 
              dt.DynamicTemplate("my_dynamic_mapping_string", dm => 
                    dm.MatchMappingType("string")
                          .PathMatch("foo[0-9]")
                          .MatchPattern("regex") 
                          .Mapping(m => ...))

**Provide `ConnectionSettings` (if relevant)**:
Not Relevant
**Provide `DebugInformation` (if relevant)**:
Not Relevant

**Comment by russcam** [comment]
Thanks @jacob-123, I've opened https://github.com/elastic/elasticsearch-net/pull/3374 to address
