### ISSUE TITLE
StringResponse.TryGetServerError parse error on 401 response

### ISSUE THREAD

**Issue by VitaliyMF** [elastic/elasticsearch-net#3378]
**NEST/Elasticsearch.Net version**: 6.2

**Elasticsearch version**: (any)

**Description of the problem including expected versus actual behavior**: when StringResponse is used and server returns 401 (requires HTTP auth) 'Invalid JSON string' exception is thrown because [ServerError class](https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Responses/ServerException/ServerError.cs) tries to parse response body as JSON. SkipDeserializationForStatusCodes doesn't help in this case because it is ignored for types listed in ResponseBuilder.SetSpecialTypes.

**Steps to reproduce**:

> var client = new ElasticLowLevelClient(new ConnectionConfiguration(new Uri(anyUrlThatRequiresHttpAuth)));
> var res = client.Search&lt;StringResponse&gt;("someIndex",PostData.String(anyQueryJson));
> // that's all, 'SerializationException: Invalid JSON string' is thrown
> 

In fact this issue can be reproduced for 'BytesResponse' too. 
Wrapping [StringResponse.TryGetServerError](https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Responses/Special/StringResponse.cs) code with try-catch might solve the issue.

**Comment by Mpdreamz** [comment]
Thanks for reporting @VitaliyMF, we'll look into this before the next release 👍

**Comment by russcam** [comment]
I've opened #3466 to address.
