### ISSUE TITLE
JArray passed in Terms clause is serialized incorrectly

### ISSUE THREAD

**Issue by ranjak** [elastic/elasticsearch-net#3388]
**NEST/Elasticsearch.Net version**: 6.2.0

**Elasticsearch version**: 6

**Description of the problem including expected versus actual behavior**:

When using a JArray as the value argument for a terms clause:
```
JToken value = new JArray("a", "b", "c", "d");
q => q.Terms(s => s.Field("myField").Terms(value));
```
The value is not serialized correctly in the query.

This is what I get, printing the query using `client.RequestResponseSerializer.Serialize()`:
```
"terms": {
    "myField": [ [], [], [], [] ]
}
```
Instead of the expected:
```
"terms": {
    "myField": [ "a", "b", "c", "d" ]
}
```

This results in the following ES error: `[terms] query does not support multiple fields` (code 400).

**Provide `ConnectionSettings` (if relevant)**: `new ConnectionSettings(connectionPool, JsonNetSerializer.Default)`

**Comment by russcam** [comment]
Relates: #3228, #3298, #3186

NEST does not know how to (de)serialize JSON.NET's `JArray` type, which requires special handling by an `IElasticsearchSerializer` implementation that uses Json.NET. You can [hook up the `JsonNetSerializer`](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html#_jsonnetserializer) from the [NEST.JsonNetSerializer nuget package](https://www.nuget.org/packages/NEST.JsonNetSerializer/) to achieve this.
