### ISSUE TITLE
Mapping Kibana on .Net NEST stack

### ISSUE THREAD

**Issue by weedkiller** [elastic/elasticsearch-net#3400]
In the documentation and help its not clear, on how to `integrate Kibana Visualization on an app with NEST stack`

We have an ASP MVC and or Core stack, and wondering how to serve up Kibana Visualization, apologies ahead of time after some searching i am posting here.

**Comment by Mpdreamz** [comment]
There is a feature being discussed on kibana to export visualizations to PNG: https://github.com/elastic/kibana/issues/21423 you could potentially proxy these in your MVC app if that feature lands.

Your best bet is to ask on the discuss.elastic.co site though.
