### ISSUE TITLE
Can't set refresh_interval to default value (null)

### ISSUE THREAD

**Issue by kpstolk** [elastic/elasticsearch-net#3402]
**NEST/Elasticsearch.Net version**:
6.3.0

**Elasticsearch version**:
6.4.0

**Description of the problem including expected versus actual behavior**:
`refresh_interval` setting cannot be changed to default (`null`) because `null` values are not sent.
I also don't see an option to just send `null`'s for a single request.

Expected: `refresh_interval` set to `null`
Actual: `refresh_interval` doesn't update to `null`

**Steps to reproduce**:
 1. Create Index using `CreateIndexAsync`
 2. Update Index settings to set `refresh_interval` to -1
```
UpdateIndexSettingsDescriptor GetUpdateDescriptor(Time refreshInterval)
{
   return new UpdateIndexSettingsDescriptor()
      .Index("my-index")
      .IndexSettings(s => s
         .RefreshInterval(refreshInterval)
      );
}

await _client.UpdateIndexSettingsAsync(GetUpdateDescriptor(-1));
```
 3. Reset `refresh_interval` to default by providing `null`
```
await _client.UpdateIndexSettingsAsync(GetUpdateDescriptor(null));
```
4. Retrieve settings of Index, `refresh_interval` is still -1, `GET my-index/_settings` returns:
```
{
  "my-index": {
    "settings": {
      "index": {
        "refresh_interval": "-1"
      }
    }
  }
}
```

**Provide `ConnectionSettings` (if relevant)**:
`new ConnectionSettings(node).DefaultTypeName("_doc")`

**Provide `DebugInformation` (if relevant)**:
N/A

**Comment by Mpdreamz** [comment]
This is indeed something we do not support now. We'll look at adding support for this in `6.4.0`.

**Comment by russcam** [comment]
I've opened #3465 to address.
