### ISSUE TITLE
Can't create a role with Kibana privileges?

### ISSUE THREAD

**Issue by kpstolk** [elastic/elasticsearch-net#3409]
**NEST/Elasticsearch.Net version**:
6.3.0

**Elasticsearch version**:
6.4.0

**Description of the problem including expected versus actual behavior**:
`PutRoleAsync` accepts a `PutRoleDescriptor` which allows to set Cluster and Indices privileges.
However there's no support for the Kibana privileges like available in Kibana UI under `Management` -> `Security` -> `Roles`?

![image](https://user-images.githubusercontent.com/538170/45689829-3627ea80-bb55-11e8-92ea-7c1fe657f5f6.png)

**Steps to reproduce**:
 1. Try to create a new role using PutRoleAsync
 2. Notice it's impossible to provide any Kibana privileges

**Provide `ConnectionSettings` (if relevant)**:
N/A

**Provide `DebugInformation` (if relevant)**:
N/A

**Describe the feature**:
If this is not a bug but a new feature: please allow to set Kibana privileges by extending the `PutRoleDescriptor` class.

**Comment by Mpdreamz** [comment]
I **think** kibana is mapped as application specific privileges which we do not support yet as part of the `PutRoleRequest`

https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-role.html

Thanks for bringing this to our attention

**Comment by russcam** [comment]
opened #3462 to address
