### ISSUE TITLE
Cross Cluster support in IndexName prevents the use of `::`

### ISSUE THREAD

**Issue by lakario** [elastic/elasticsearch-net#3411]
https://github.com/elastic/elasticsearch-net/blob/4fc89fbf9add070405d3c959f1bafa1dea2abdfd/src/Nest/CommonAbstractions/Infer/IndexName/IndexName.cs#L16

Is there a documented use case for the `Cluster` property on the `IndexName` type? I was experimenting with including "::" (i.e. "write::some-name") in the name of an alias (or index) and after producing an instance of `IndexName` from the implicit conversion operator on `string`, the index name used in the resulting API call was invalid due to the implementation of the `Parse()` method. 

https://github.com/elastic/elasticsearch-net/blob/4fc89fbf9add070405d3c959f1bafa1dea2abdfd/src/Nest/CommonAbstractions/Infer/IndexName/IndexName.cs#L47

```c#
private static IndexName Parse(string indexName)
{
	if (string.IsNullOrWhiteSpace(indexName)) return null;
	var tokens = indexName.Split(ClusterSeparator, 2, StringSplitOptions.RemoveEmptyEntries);
	return tokens.Length == 1
		? new IndexName(tokens[0])
		: new IndexName(tokens[1],tokens[0]);
}
```

I've verified that there's no limitation in the Elasticsearch API around using "::" in an index or alias name, so this logic in the .NET library seems like a defect.

**Comment by Mpdreamz** [comment]
This allows you to build [cross cluster search](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-cross-cluster-search.html) requests e.g `Index<Project>("cluster1")` will yield `cluster:projects` which is always send as a whole to `Elasticsearch`.

`NEST` should be more lenient in your use case though.

**Comment by russcam** [comment]
I've opened #3458 to address
