### ISSUE TITLE
Index Wildcard is being encoded to %2A - resulting in no results

### ISSUE THREAD

**Issue by voxon2** [elastic/elasticsearch-net#3412]
NEST 6.3.0
ElasticSearch "6.2.4",

I am attempting to specify a wildcard for index name and getting no results, from what appears to be because the asterik is being encoded to %2A

```
var client = new ElasticClient(settings);
         var results = client.Search<object>(_ => _
            .Index(Indices.Parse( "alias-xyz-*"))
            .Query(q => q
               .Bool(b => b
                  .Filter(f => f
                     .DateRange(dr => dr.Field("@timestamp").GreaterThan(lastTimestamp))
                  ))));
```
Debug Information:
Valid NEST response built from a successful low level call on POST: /alias-xyz-%2A/_doc/_search?typed_keys=true
# Audit trail of this API call:
 - [1] HealthyResponse: Node: https://XXXXXXX:9200/ Took: 00:00:00.2015063
# Request:
{"query":{"bool":{"filter":[{"range":{"@timestamp":{"gt":"2018-09-20T13:42:18.1636501-04:00"}}}]}}}
# Response:
{"took":35,"timed_out":false,"_shards":{"total":44,"successful":44,"skipped":0,"failed":0},"hits":{"total":0,"max_score":null,"hits":[]}}

When executing the same query through postman or the kibana dev tools, I get actual responses.

Is there a way to avoid the url encoding of the wildcard? I see this issue: https://stackoverflow.com/questions/44924008/elasticsearch-net-nest-use-a-wildcard-index-in-query but no resolution.

**Comment by Mpdreamz** [comment]
Sending `%2A` for `*` is totally valid and Elasticsearch accepts it. It would be breaking URL conventions if it didnt as the two should be equivalent. 

To proof it I've attached commit b8041fb to showcase this:

```request
POST http://127.0.0.1:9200/prefixed-%2A/doc/_search?pretty=true&error_trace=true&typed_keys=true HTTP/1.1
Accept: application/json
Content-Type: application/json
Content-Length: 2
Host: 127.0.0.1:9200

{}
```
response:
```json
HTTP/1.1 200 OK
content-type: application/json; charset=UTF-8
content-length: 1187

{
  "took" : 84,
  "timed_out" : false,
  "_shards" : {
    "total" : 4,
    "successful" : 4,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 2,
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "prefixed-1",
        "_type" : "doc",
        "_id" : "project-1",
        "_score" : 1.0,
        "_routing" : "project-1",
        "_source" : {
          "type" : "project",
          "join" : "project",
          "name" : "project-1",
          "state" : "BellyUp",
          "visibility" : "Public",
          "startedOn" : "0001-01-01T00:00:00",
          "lastActivity" : "0001-01-01T00:00:00",
          "numberOfContributors" : 0
        }
      },
      {
        "_index" : "prefixed-2",
        "_type" : "doc",
        "_id" : "project-2",
        "_score" : 1.0,
        "_routing" : "project-2",
        "_source" : {
          "type" : "project",
          "join" : "project",
          "name" : "project-2",
          "state" : "BellyUp",
          "visibility" : "Public",
          "startedOn" : "0001-01-01T00:00:00",
          "lastActivity" : "0001-01-01T00:00:00",
          "numberOfContributors" : 0
        }
      }
    ]
  }
}
```

How are you trying this in Kibana? 

If you write it as:

```
GET /alias-xyz-%2A/_doc/_search
{
...
}
```
Kibana will do a `match_all` ignoring the json make sure you do:

```
POST /alias-xyz-%2A/_doc/_search
{
...
}
```

With the exact same body. 

Hope this helps!
