### ISSUE TITLE
[doc]sample code problem in Debug information

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/elasticsearch-net#3413]
In https://www.elastic.co/guide/en/elasticsearch/client/net-api/6.x/debug-information.html with regards to below, `Should` is not found in version 6.3.1

`response.DebugInformation.Should().Contain("Valid NEST response");`

So I got it to work like this

`var info = searchResponse.DebugInformation.ToString();`

Am I doing something wrong or should we update the doc accordingly?

**Comment by russcam** [comment]
The documentation is correct; it simply provides an example of what can be done with the response `DebugInformation`. In this case, it's using an assertion extension method from a testing framework, but a user might write the debug information to the console, log it to a logging framework, or some other action that makes sense for their usage.

**Comment by russcam** [comment]
I think we could possibly hide the usage of the assertion framework from the docs, and provide an example of writing to the console

**Comment by TomonoriSoejima** [comment]
Looking at some Test code, are these what I need to import into the project?

```
using Tests.Core;
using Tests.Core.Client;
```

**Comment by russcam** [comment]
Yes, *but* to be clear, the docs are unit tests that are run to ensure that they don't drift as the source code changes. You'll find all the doc source code in the tests project, so it may be better to just clone the repository.

**Comment by russcam** [comment]
If you click edit on any docs page, there will be a link back to the original source file

**Comment by TomonoriSoejima** [comment]
Thanks.

In the meantime, I just got by using `using FluentAssertions;` in my tiny project.
I also cloned the repository and was able to add my test code.
Thanks for clarifying the doc!
