### ISSUE TITLE
Cannot use Xamarin.iOS NSUrlSessionHandler

### ISSUE THREAD

**Issue by Cheesebaron** [elastic/elasticsearch-net#3415]
**NEST/Elasticsearch.Net version**:
6.3.1

**Description of the problem including expected versus actual behavior**:
When using Elasticsearch.Net you cannot provide a NSUrlSessionHandler in the `CreateHttpClientHandler` method override. NSUrlSessionHandler in Xamarin.iOS is a HttpMessageHandler, rather than HttpClientHandler.

Since it cannot be used, Xamarin.iOS apps can only use the managed, less stable HttpClientHandler.

Would it be possible to make the return type `HttpMessageHandler` for `CreateHttpClientHandler` in `HttpConnection`?

**Comment by Mpdreamz** [comment]
Thanks for reporting this @Cheesebaron 👍 

We wont be able to change for 7.0 due to backwards compatibility issues. Is copying the sourcce for `HttpConnection` in the mean time a workable (albeit tedious) solution?

**Comment by Cheesebaron** [comment]
I think that could work. Not pretty at all though.

I don't see why this should affect any backwards compatibility? HttpClientHandler inherits from HttpMessageHandler, so changing the return type on `CreateHttpClientHandler` would not change anything.

**Comment by russcam** [comment]
I've added #3648 to address this in 7.0.0

**Comment by russcam** [comment]
This is now merged into 7.x in #3648
