### ISSUE TITLE
NEST: Change default serializer of LowLevelClient

### ISSUE THREAD

**Issue by Vm3ntos** [elastic/elasticsearch-net#3421]
**NEST/Elasticsearch.Net version**: 6.3.1

**Elasticsearch version**: 6.4.1

**Description of the problem including expected versus actual behavior**: I've changed default serializer of NEST and it works, but when I'm accessing LowLevelClient in NEST client instance it's using default serializer. There's no possibility to change serializer of LowLevelClient inside of NEST client...

**Comment by Mpdreamz** [comment]
Hey @Vm3ntos 

You can if you instantiate the low level client directly using `new ElasticLowLevelClient(....)`. With `6.x` we split the serializer in two in NEST. The internal once, and the source serializer you can override which is targetted only to user provided values (`_source`, fields, script values and others). 

@codebrain @russcam thoughts on making an option in the high level client to set the lowlevel serializer?

**Comment by codebrain** [comment]
> @codebrain @russcam thoughts on making an option in the high level client to set the lowlevel serializer?

Makes sense to allow this.

**Comment by russcam** [comment]
I'm trying to think of a use case for allowing this. 

Having the low level client exposed on the high level client use the same serializer as the one configured for the high level client makes a lot of sense when it comes to using the low level client to send a request, and deserializing to a high level response. Setting a different serializer for the low level client seems like it would be better served by instantiating a new instance of the low level client separately.
