### ISSUE TITLE
NEST: Default JsonNetSerializer does not camel case property names

### ISSUE THREAD

**Issue by FrodeRennemo** [elastic/elasticsearch-net#3422]
**NEST/Elasticsearch.Net version**: 6.1.0

**Elasticsearch version**: 6.0.1

**Description of the problem including expected versus actual behavior**:
When using the internal json serializer, the properties get camel cased names by default. I would expect the same behaviour when using the JsonNetSerializer while explicitly using the default option. Now the snake cased property names are not changed to camel case.

If this is a misunderstanding on my part I would appreciate any input on how to solve this matter!

**Steps to reproduce**:
 1. Instantiate connection settings: `new ConnectionSettings(pool, sourceSerializer: JsonNetSerializer.Default);`
 2. Try to serialize snake cased properties

**Describe the feature**:  Ship the default JsonNetSerializer with the same defaults as the internal one used in NEST.

**Comment by Mpdreamz** [comment]
Hi we explicitly do not do this. 

The `JsonNetSerializer` uses whatever defaults `Json.NET` has. You'll need to explicitly set [NamingStrategy = new SnakeCaseNamingStrategy()](https://www.newtonsoft.com/json/help/html/NamingStrategySnakeCase.htm)

```csharp
var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
var connectionSettings = new ConnectionSettings(pool, (builtin, settings) =>
	new JsonNetSerializer(builtin, settings,
		modifyContractResolver: c=> {
			c.NamingStrategy = new SnakeCaseNamingStrategy();
		}
	)
);


var client = new ElasticClient(connectionSettings);
```
