### ISSUE TITLE
Bulk operations not documented for current version of NEST

### ISSUE THREAD

**Issue by alexanderte** [elastic/elasticsearch-net#3451]
For some reason bulk operations seems to have been removed from the docs. It would be really helpful if this was documented – and preferably with example for common use cases.

**Comment by alexanderte** [comment]
An example using something like `MoreLINQ.Batch` and `ElasticClient.IndexManyAsync` could be helpful.

**Comment by russcam** [comment]
Thanks for opening @alexanderte. Indexing, including bulk indexing is something that we want to document. Hopefully we'll get a chance to document after 6.4.0 client is released. 

We would also be happy to accept a contribution for documentation, if it's something you'd be interested in?

**Comment by alexanderte** [comment]
That’s great. I found this and other operations intuitive once I got used to the fluent syntax. Unfortunately I don’t have time at the moment to contribute. Thanks for asking.

**Comment by codebrain** [comment]
Bulk indexing was covered in the following blog post:
https://www.elastic.co/blog/indexing-documents-with-the-nest-elasticsearch-net-client

Closing as documentation has been provided.

**Comment by russcam** [comment]
Also now [covered in the docs on elastic.co](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/indexing-documents.html#_multiple_documents_with_bulk)
