### ISSUE TITLE
DateAttribute can't mapping

### ISSUE THREAD

**Issue by 799839351** [elastic/elasticsearch-net#3456]
**NEST/Elasticsearch.Net version**:

**Elasticsearch version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Describe the feature**:
if I use DateAttribute  and set up format their will have an error
for example
 [ElasticsearchType(Name = "esmodel", IdProperty = "id")]
    public class ESModel
    {
        [Number(Name = "id")]
        public int Id { set; get; }
        [Text(Name = "name")]
        public string Name { set; get; }
        [Date(Name = "birthday",Format = "yyyy-MM-dd HH:mm:ss")]
        public DateTime? Birthday { set; get; }
    }
  ESModel es = new ESModel();
            es.Id = 1;
            es.Name = "22";
            es.Birthday =DateTime.Now;
 client.IndexDocument(es);

**Comment by bieladeka** [comment]
I would like to fix it

**Comment by 799839351** [comment]
The error message is probably +8:00 caused if you fixed  this very nice

**Comment by bieladeka** [comment]
Can you describe in witch part of code is this error ?

**Comment by russcam** [comment]
The format for the `DateAttribute` of `yyyy-MM-dd HH:mm:ss` won't match the serialized format of a `DateTime` instance. If you're indexing and deserializing dates with NEST, you don't need to use the `Format` property, as the default Elasticsearch configuration understands how to parse a date and time from the serialized form sent by NEST.

**Comment by 799839351** [comment]
If I don't use DateAttribute of yyyy-MM-dd HH:mm:ss  it will insert into es this data for example 
{"_index":"testindex","_type":"test","_id":"1","_version":1,"found":true,"_source":{"id":1,"name":"测试","birthday":"2018-10-22T21:15:06.8045419+08:00"}} ；  But this format is not what I want； how should  i do

**Comment by russcam** [comment]
To change the serialized format of `DateTime`/`DateTimeOffset` requires changing the component that is responsible for serializing them. One way to do this would be to reference `Nest.JsonNetSerializer` nuget package, and writing a custom `JsonConverter` to handle serialization, then hooking it up to `JsonNetSerializer`.

Why do you wish to change the serialized format? Perhaps there is a different approach to addressing the underlying problem that you wish to solve,

**Comment by bieladeka** [comment]
Yes,  I have trouble with build solution,  because part of json cannot be
serialized, that is error you talking about? If yes, then it clarify for me

**Comment by 799839351** [comment]
> To change the serialized format of `DateTime`/`DateTimeOffset` requires changing the component that is responsible for serializing them. One way to do this would be to reference `Nest.JsonNetSerializer` nuget package, and writing a custom `JsonConverter` to handle serialization, then hooking it up to `JsonNetSerializer`.
> 
> Why do you wish to change the serialized format? Perhaps there is a different approach to addressing the underlying problem that you wish to solve,

I just want to Insert data to es with default Serializer but there is an error occured ；I konw  the reason why occured  error ； but I can‘t change it 。if I change the POCO set DateTime to string  ,there will  haven't error;  May I send  my demo Code to your email?

**Comment by bieladeka** [comment]
Ok, send me your code please.

On 23 Oct 2018 1:53 p.m., "799839351" <notifications@github.com> wrote:

To change the serialized format of DateTime/DateTimeOffset requires
changing the component that is responsible for serializing them. One way to
do this would be to reference Nest.JsonNetSerializer nuget package, and
writing a custom JsonConverter to handle serialization, then hooking it up
to JsonNetSerializer.

Why do you wish to change the serialized format? Perhaps there is a
different approach to addressing the underlying problem that you wish to
solve,

I just want to Insert data to es with default Serializer but there is an
error occured ；I konw the reason why occured error ； but I can‘t change it
。if I change the POCO set DateTime to string ,there will haven't error; May
I send my demo Code to your email?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/elastic/elasticsearch-net/issues/3456#issuecomment-432215674>,
or mute the thread

**Comment by 799839351** [comment]
I am a Chinese  sending your mail is blocked.

**Comment by 799839351** [comment]
class Program
    {
        static void Main(string[] args)
        {
            var uris = new[]{new Uri("http://localhost:9200")};
            var connectionPool = new SniffingConnectionPool(uris);
            var settings = new ConnectionSettings(connectionPool);
            settings.DefaultIndex("testindex");
            var client=new ElasticClient(settings);

            IIndexState indexState = new IndexState()
            {
                Settings = new IndexSettings()
                {
                    NumberOfReplicas = 1,//副本数
                    NumberOfShards = 3//分片数
                }
            };
            client.CreateIndex("testindex", p => p.InitializeUsing(indexState).Mappings(ms => ms
           .Map<MyDemo>(q=> q.AutoMap())));

            MyDemo m = new MyDemo { Id = 1, Name = "测试", Birthday = DateTime.Now };
          
          var t=  client.IndexDocument(m);

            Console.WriteLine("Hello World!");

        }
    }
}

 [ElasticsearchType(Name = "test", IdProperty = "id")]
    public class MyDemo
    {
        [Number(Name = "id")]
        public int Id { set; get; }

        [Text(Name = "name")]
        public string Name { set; get; }
        [Date(Name = "birthday")]
        public DateTime? Birthday { set; get; }
    }

**Comment by russcam** [comment]
What's the error with the example?

**Comment by 799839351** [comment]
OriginalException: Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: PUT /couponproducts/couponproduct/993_7308. ServerError: Type: mapper_parsing_exception Reason: "failed to parse [indate]" CausedBy: "Type: illegal_argument_exception Reason: "Invalid format: "2018-10-22T09:47:40.6144748+08:00" is malformed at "T09:47:40.6144748+08:00""

**Comment by russcam** [comment]
@799839351 what does the mapping in the index look like? It sounds like the `indate` field may be mapped with a `format` that means that Elasticsearch does not know how to parse `DateTime` serialized by NEST. If you leave it with the defaults, it will work.

**Comment by 799839351** [comment]
Yes  finally  I removed the mapping and changed the datetime type to a string type.I am using the client created in singleton mode, and then using the deletebyquery method in the for loop to prompt me for version conflicts, but in the process I did not modify the data in es, or the data in es has not changed.

**Comment by russcam** [comment]
@799839351 is this issue now resolved? Can we close this?

**Comment by 799839351** [comment]
ok close the issue

**Comment by russcam** [comment]
is the issue resolved for you? Did you implement a custom `JsonConverter` to serialize `DateTime` in the format you have defined in the mapping?

**Comment by russcam** [comment]
Closing this issue as it appears to be resolved by the user. If that's not the case, feel free to reopen 👍
