### ISSUE TITLE
One Index vs. Multiple Indices

### ISSUE THREAD

**Issue by maryam-abdullah** [elastic/elasticsearch-net#3463]
Hello,

What is better to use, a single index or multiple ones?
Which of the two gives a better performance in terms of searching?

Knowing that if I stored data in multiple indices, I will search only in one of these indices (based on the request).

Thanks in advance.

**Comment by russcam** [comment]
Hi @maryam-abdullah , 

GitHub is reserved for bug reports and feature requests.

The best place to ask a general question is at the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. More folks view the forums than the GitHub issues list too, so it's likely to be seen, and hopefully answered, faster there.

Thanks!
