### ISSUE TITLE
Extracting the request content from Nest client

### ISSUE THREAD

**Issue by sztrzask** [elastic/elasticsearch-net#3464]
Hi. 

How can I extract the raw json request from the Nest client? The previous solution #1288 doesn't work anymore as the're is no Connection property on the search result.

I tried using `RequestResponseSerializer.SerializeToString` method, but if my query contains both aggregate and query it only serializes part of it.

**Comment by senthilkumarmohan** [comment]
Hi,

```
var elasicsearchSettings = getElasticSearchSettings();
var client = new ElasticClient(elasicsearchSettings);
var searchResult = client.Search<Foo>(s => s.MatchAll());
Logger.Log(searchResult.DebugInformation);
```
Please check 'DebugInformation'. That should give you the details you are looking for.

# Audit trail of this API call:
# OriginalException:
# Request:
# Response:

Thanks.

**Comment by russcam** [comment]
Hi @sztrzask , 

We reserve GitHub Issues for bug reports and feature requests.

In order for your question to get the attention it deserves, the best place to ask it would be the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Not only do more folks view the forums than the GitHub Issues list, and hence it is more likely to receive attention, but the forums are also geared towards being able to search previous questions and answers, making it a much more valuable archive for future question askers.

Thanks!

----

Take a look at https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/logging-with-on-request-completed.html.
