### ISSUE TITLE
How to get all documents for a field

### ISSUE THREAD

**Issue by 799839351** [elastic/elasticsearch-net#3480]
I want to query a field accurately and get all the qualified documents. How do I do that?

**Comment by russcam** [comment]
Hi @799839351 , 

We reserve GitHub Issues for bug reports and feature requests.

In order for your question to get the attention it deserves, the best place to ask it would be the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Not only do more folks view the forums than the GitHub Issues list, and hence it is more likely to receive attention, but the forums are also geared towards being able to search previous questions and answers, making it a much more valuable archive for future question askers.

Thanks!
