### ISSUE TITLE
Response DebugInformation property exposes login credentials

### ISSUE THREAD

**Issue by hermanussen** [elastic/elasticsearch-net#3485]
**NEST/Elasticsearch.Net version**: NEST 5.5.0 (and possibly others)

**Elasticsearch version**: 6.4.0 (and possibly others)

**Description of the problem including expected versus actual behavior**:
The DebugInformation property on the query result object shows useful information about the result of the query. This includes the full connection string to the ElasticSearch machine.

However, it may occur that this connection string contains username and password. It could be argued that it should not and authentication should be done in a different way. But nevertheless, the DebugInformation property should filter this out. Otherwise, logfiles or other places where the value is used could be contaminated with login data. This is a potential security issue.

**Steps to reproduce**:
 1. Run a NEST query
 2. Log the DebugInformation (string) property from the result object
 3. Observe the log message to find the connectionstring including username and password

**ConnectionSettings**:
https://[redacted_username]:[redacted_password]@[redacted_url]:[redacted_port]

**Comment by Mpdreamz** [comment]
Thank you for the report, I fully agree we need to address this. Will work on a PR now.

**Comment by hermanussen** [comment]
Excellent. Thank you!
