### ISSUE TITLE
BulkAll Return Response with document _id's 

### ISSUE THREAD

**Issue by andystroz** [elastic/elasticsearch-net#3487]
**NEST/Elasticsearch.Net version**: 6.3.1

**Elasticsearch version**: 6.3

**Describe the feature**:

I am using the BulkAll interface to index a group of documents. I would like Elastic to Create the _id field for these documents so I do not specify it in my request. I would like to know the _id of the documents indexed, like the response of the index API or the [standard bulk API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html). Could the response from Elastic be included in the [BulkAllResponse](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Document/Multiple/BulkAll/BulkAllResponse.cs)?

I am thinking that all that needs be done is modify that class to include a response. Then include the successful response from Elastic [here](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs#L152). When onNext is called in the subscriber the response for items included in that bulk update will be shown.

I could be completely off base with a solution / should I just write my own version of BulkAll with the functionality that I desire?

**Comment by russcam** [comment]
I think this would be a great addition to `BulkAllResponse`!

> I am thinking that all that needs be done is modify that class to include a response. Then include the successful response from Elastic here. When onNext is called in the subscriber the response for items included in that bulk update will be shown.

A cursory glance, that looks like that would be needed. The values would come from the `documentsWithResponse` that are valid (`.IsValid` is true) 

https://github.com/elastic/elasticsearch-net/blob/28f37744d388df46139b9fe92a8b3c20a18c4692/src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs#L137

Is this something you would be interested in contributing?

**Comment by russcam** [comment]
#3598 has been merged and will be in the next release (6.6.0), so am closing this.
