### ISSUE TITLE
Incorrect query after using DateTime.MinValue in the DateRange filter

### ISSUE THREAD

**Issue by IvanSorokin** [elastic/elasticsearch-net#3505]
**NEST/Elasticsearch.Net version**: 6.4.0

**Elasticsearch version**: 6.5.1

**Description of the problem including expected versus actual behavior**:
I am using filter for counting documents like this

```
private static Func<QueryContainerDescriptor<ISearchableNotification>, QueryContainer> IndexedDateFromFilter(SearchQuery query)
{
    if (query.IndexedDateFrom.HasValue)
        return filter => filter.DateRange(rf => rf.Field(nm => nm.IndexedDateTime)
                                                  .GreaterThanOrEquals(query.IndexedDateFrom));
     return null;
}
```

IndexedDateFrom's type is **[DateTime?]**. When **IndexedDateFrom** equals **DateTime.MinValue** everything crashes with exception

`org.elasticsearch.ElasticsearchParseException: failed to parse date field [] with format [strict_date_optional_time||epoch_millis]`

 because NEST translates C# code into this (part of the query I got from DebugInformation)
```
{
                "range": {
                  "indexedDateTime": {
                    "gte": ""
                  }
                }
}
```

If I use **DateTime.MinValue.AddDays(1)** instead of **DateTime.MinValue** everything works fine. It looks like a bug.

**Comment by Mpdreamz** [comment]
Opened https://github.com/elastic/elasticsearch-net/pull/3546 to fix this as best as we can in 6.5.

Need to open another PR to make `DateMath` anchor a `DateTime?` on `master` (`7.0`).
