### ISSUE TITLE
Ingest Pipeline processors if condition support

### ISSUE THREAD

**Issue by kpstolk** [elastic/elasticsearch-net#3506]
**NEST/Elasticsearch.Net version**:
6.3.1

**Elasticsearch version**:
6.5.0

**Description of the problem including expected versus actual behavior**:
All [processors](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/ingest-processors.html) have an `if` condition option, but this is not exposed in for example the `AppendProcessorDescriptor` (or any other `IProcessor`).

**Steps to reproduce**:
 1. Create pipeline:
```
await _service.PutPipelineAsync("my-pipeline", descriptor => descriptor
    .Description("My Pipeline")
    .Processors(processorsDescriptor => processorsDescriptor
        .Append<object>(appendDescriptor => appendDescriptor
            .Field("my_field")
            .Value("the_value")
        )
    )
);
```
 2. Note there's no option for `.If()` like there is for `.OnFailure()`

**Describe the feature**:
Expose a method to configure an `If` condition just like [OnFailure](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Ingest/Processor.cs#L12)

**Comment by russcam** [comment]
Opened #3528
