### ISSUE TITLE
CreateIndexAsync not using the indexname from request

### ISSUE THREAD

**Issue by nhancers** [elastic/elasticsearch-net#3513]
**NEST/Elasticsearch.Net version**:
6.3

**Elasticsearch version**:
6.3

**Description of the problem including expected versus actual behavior**:
CreateIndexAsync(IndexName index, Func<CreateIndexDescriptor, ICreateIndexRequest> selector = null, CancellationToken cancellationToken = default);

is not creating index for the indexname name passed. We are using document mapping while creating index. When we try to create index, it always refers to the default index mentioned in the connection settings and ignores the indexname passed as part of the request.
e.g. 

```
CreateIndexAsync("test",  c => c
                .Index<Document>()
                .Mappings(ms => ms
                    .Map<Document>(m => m
                        .RoutingField(r => r.Required())
                        .AutoMap<A>()
                        .AutoMap<B>()
                        .FieldNamesField(fnf => fnf.Enabled())
                        .Properties(props => props
                            .Join(j => j
                                .Name(p => p.map)
                                .Relations(r => r.Join<A, B>())))))) 
```

**Expected behavior:** Should create index with name "test"

**Actual behavior:** It looks for the default index name on connection settings and tries to create index with that name.

**Provide `ConnectionSettings` (if relevant)**:
```
var connectionPool = new SingleNodeConnectionPool(new Uri(<<host url>>));
            var serializerSettings = new JsonSerializerSettings();
            serializerSettings.Converters.Add(new HoldingsJsonConverter());

            var toReturn = new ConnectionSettings(
                connectionPool,
                sourceSerializer: (builtin, settings) => new JsonNetSerializer(builtin, settings, () => serializerSettings))
                    .DefaultMappingFor<Document>(m => m.TypeName("doc"))
                    .DefaultMappingFor<B>(m => m.TypeName("doc")
                    .DefaultMappingFor<A>(m => m.TypeName("doc")
                        .RelationName(Document.Schema_Name)).DefaultIndex("default-index");
```

**Provide `DebugInformation` (if relevant)**:

@Mpdreamz  @gmarz

**Comment by nhancers** [comment]
@Mpdreamz  @gmarz

**Comment by Mpdreamz** [comment]
`"test"` gets overwritten by `.Index<Document>()` in the fluent descriptor.
