### ISSUE TITLE
How to get response in object using SQL ElasticSearch, I am close but still not getting  exact syntax

### ISSUE THREAD

**Issue by nileshpore** [elastic/elasticsearch-net#3514]
I have uploaded users in elastic search, now I want to get particular user by username.
I want to use elastic using SQL to retrieve data. 

I have written following function, please let me know how can I get response in [User] c# object.
Any way to get it auto mapped to my required object?

Please help me with syntax.
================================================================

      public static User GetUserByUserName()
        {
            var client = new ElasticConnectionManager().GetClient("users");
            var query = "SELECT * FROM users where username = 'DummyStudent_6610'";

            var sqlRequest = new QuerySqlRequest();
            sqlRequest.Query = query;
            sqlRequest.Format = "json";

        
            var response = client.QuerySql(sqlRequest);
            //How to convert to User object?

            return;
        }

Stackoverflow Link for same question:
https://stackoverflow.com/questions/53746080/elastic-search-getting-response-in-object

**Comment by russcam** [comment]
Hi @nileshpore , 

We reserve GitHub Issues for bug reports and feature requests.

In order for your question to get the attention it deserves, the best place to ask it would be the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Not only do more folks view the forums than the GitHub Issues list, and hence it is more likely to receive attention, but the forums are also geared towards being able to search previous questions and answers, making it a much more valuable archive for future question askers.

Thanks!
