### ISSUE TITLE
Nest 6.4 with ElasticSearch 6.5 Aggregations no data;

### ISSUE THREAD

**Issue by zzandww** [elastic/elasticsearch-net#3515]
Nest 6.4 with ElasticSearch 6.5 Aggregations no data;
 .Aggregations(hg =>                    
                        hg.Terms("countries", td => td.Field("country.keyword")
.Aggregations(f => f.Cardinality("customercount", q => q.Field("customer.keyword"))).Size(999))
                    )

The data in the debugging information is correct. but .Aggregations Dictionary is empty.

Nest5.5 + ElasticSearch 5.6.3 is fine.

**Comment by russcam** [comment]
@zzandww I don't understand the issue; please can you add a small, concise, reproducible example that demonstrates the issue?

**Comment by zzandww** [comment]
@russcam thanks for you replay.
I've found out why.


when datetime is 0001/1/1 0:00:00
Nest 5.5  Generated dsl is : "arrivalDate":{"gte":null,"lte":null}

Nest 6.4 Generated dsl is "arrivalDate":{"gte":"","lte":""} ,can't find any data.

I solved this problem by setting the date to null.
