### ISSUE TITLE
No nodes were attempted error when using a RequestTimeout on ConnectionSettings

### ISSUE THREAD

**Issue by mcbainuk12** [elastic/elasticsearch-net#3516]
NEST v6.3.1 / Elasticsearch.Net v6.3.1:

Elasticsearch v6.3.2:

'No nodes were attempted, this can happen when a node predicate does not match any nodes' error when a RequestTimeout is added to the ConnectionSettings.

Steps to reproduce:
 1. Create ConnectionSettings like so 
new ConnectionSettings(new Uri("localhost:9205")).RequestTimeout(new TimeSpan(50000));
 2.  After succesful Elasticclient creation, issue a request such as "await client.CatHealthAsync(new CatHealthRequest())"
 3. You will then receive a "No nodes were attempted, this can happen when a node predicate does not match any nodes" exception. 
4. Remove the ".RequestTimeout(new TimeSpan(50000));" from the ConnectionSettings and repeat, everything will work fine.

Inspection of the collection pool of both requests looks identical.

**Comment by Mpdreamz** [comment]
@mcbainuk12 can you also paste the code you use to instantiate the client?

If you set `.DebugMode()` on `ConnectionSettings()` and catch the `No nodes were attempted...` exception that exception will have a `.DebugInformation` property. Are you able to capture that and give us the contents of that. That will hopefully help us uncover what is going on.

**Comment by mcbainuk12** [comment]
Hello, 

Thanks for the reply, here's the DebugInfo

# FailureReason: Unrecoverable/Unexpected NoNodesAttempted while attempting GET on _cat/health?pretty=true&error_trace=true on an empty node, likely a node predicate on ConnectionSettings not matching ANY nodes
 - [1] NoNodesAttempted: Took: -737040.09:58:24.8536398
# Inner Exception: No nodes were attempted, this can happen when a node predicate does not match any nodes
Elasticsearch.Net.ElasticsearchClientException: No nodes were attempted, this can happen when a node predicate does not match any nodes
# Exception:
Elasticsearch.Net.UnexpectedElasticsearchClientException: No nodes were attempted, this can happen when a node predicate does not match any nodes ---> Elasticsearch.Net.ElasticsearchClientException: No nodes were attempted, this can happen when a node predicate does not match any nodes
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.RequestPipeline.ThrowNoNodesAttempted(RequestData requestData, List`1 seenExceptions)

Hopefully that helps?

Currently upgrading from Elasticsearch1 to Elasticsearch6. Going well apart from this strange issue.

**Comment by Mpdreamz** [comment]
I can not quite reproduce this behaviour but `new TimeSpan(50000))` translates to `5ms` which might be too strict.

I get the following `DebugInformation` for the code you pasted.

```
Unsuccessful low level call on GET: /_cat/health?pretty=true&error_trace=true
# Audit trail of this API call:
 - [1] BadResponse: Node: http://localhost:9205/ Took: 00:00:00.0093912
 - [2] MaxTimeoutReached: 
```

What happens if you increase your timeout?
