### ISSUE TITLE
Support Custom Query Class for Elastic Plugin

### ISSUE THREAD

**Issue by agentschmitt** [elastic/elasticsearch-net#3517]
It would be nice, to have extension options for custom queries in NEST, to support elastic search plugins.
I want to include support for "IntraFind Elasticsearch Linguistic Plugin" to NEST.

The query type for this plugin is an extension of QueryStringQuery with some additional fields.
I extended QueryStringQuery and added this properties together with annotations to map json accordingly.

```
    public class IntrafindQueryString : QueryStringQuery
    {
        [PropertyName("search_type")]
        public string SearchType { get; set; }

        [PropertyName("expand_complete_query_with_thes")]
        public bool UseThesaurus { get; set; }

        [PropertyName("exact_boost")]
        public double ExactBoost { get; set; }
    }
```

But when the complete query is serialized the query name is serialized as "query_string" instead of "intrafind_query_string" because this is defined by JsonPropertyAttribute in IQueryContainer at property QueryString.

I tried to extend QueryContainer to add my own IntraFindQueryStringQuery Property.
But because InternalWrapInContainer in QueryBase is internal I can't write my custom Query into the correct filter property.

Could the method be change to protected? Or is there some better way to do this customization?

```
    public class IntrafindQueryContainer : QueryContainer
    {
        [PropertyName("intrafind_query_string")]
        public IntrafindQueryString IntrafindQueryString { get; set; }
    }
```

**Comment by Mpdreamz** [comment]
Hi @agentschmitt there is no way currently other then the `RawQuery`. 

Similarly we have a long open request for aggregations as well: https://github.com/elastic/elasticsearch-net/issues/1016. 

I think it would be fantastic if we offered a better story here but its not as straightforward as it might sound and might involve breaking changes making this a `7.x` only change. We'll look into this again before the next major version.

**Comment by nikiz0r** [comment]
Hey there,
I have a similar issue, but instead I was able to do what I understood OP tried to do by extending IScoreFunction and adding it into searchDescriptor phase as stated below.

```
_esClient.Search<Object>(s => s
    .Query(q => q
        .FunctionScore(fs => fs
            .Functions(new List<IScoreFunction>
            {
                new MyCustomPlugin(new MyCustomPluginFields(){
                    Foo = _foo,
                    Bar = _bar
                })
            })
        )
    )
);
```
Now, what I'm facing is that when I'm using NEST package from Nuget, it seems to not be able to serialize correctly my plugin statement by sending an empty Functions node to Elasticsearch, but then I've compiled NEST dlls locally and added them to my lab project, then the same code works, my query is generated with my plugin statement as it should.
That's an awkward behavior I've been trying to figure it out for a while but can't seem to understand what's going on. Any help would be highly appreciated.

**Comment by Mpdreamz** [comment]
@nikiz0r When we build a NuGet package we effectively shade our Newtonsoft.Json reference. Meaning we internalize the code and rewrite the types into a new namespace. 

This explains the difference in behaviour. You most likely have something like this:

```csharp
public class MyCustomPlugin : IScoreFunction
{
	public MyCustomPlugin(MyCustomPluginFields fields) => Plugin = fields;

	[JsonProperty("my-custom-plugin")]
	public MyCustomPluginFields Plugin { get; }
	public QueryContainer Filter { get; set ; }
	public double? Weight { get; set; }
}

public class MyCustomPluginFields
{
	public string Foo { get; set; }
	public string Bar { get; set; }
}
```

The following attribute `[JsonProperty("my-custom-plugin")]` will be the same `Newtonsoft.Json.JsonPropertyAttribute` type if you use a local compiled dll vs our production NuGet packages. 
If you reference the NuGet package the one we look for internally is `Nest.Json.JsonPropertyAttribute` which is shaded (internal and not accessible). 

So it won't be picked up any more. Luckily the fix is quite straight forward:

```csharp
public class MyCustomPlugin : IScoreFunction
{
	public MyCustomPlugin(MyCustomPluginFields fields) => Plugin = fields;

	[DataMember(Name = "my-custom-plugin")]
	public MyCustomPluginFields Plugin { get; }
	public QueryContainer Filter { get; set ; }
	public double? Weight { get; set; }
}

public class MyCustomPluginFields
{
	public string Foo { get; set; }
	public string Bar { get; set; }
}
```

By switching to the [`DataMemberAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.datamemberattribute?view=netframework-4.7.2) which is part of the BCL you can mark the property for inclusion again.

Given this example:

```csharp
var settings = new ConnectionSettings(new InMemoryConnection())
	.EnableDebugMode()
	.DefaultIndex("my-index");
var client = new ElasticClient(settings);
var response = client.Search<Object>(s => s
	.Query(q => q
		.FunctionScore(fs => fs
			.Functions(new List<IScoreFunction>
			{
				new MyCustomPlugin(new MyCustomPluginFields(){
					Foo = "elastic_foo",
					Bar = "elastic_bar" 
				})
				{
					Weight = 1
				}
			})
		)
	)
);
Console.WriteLine(response.DebugInformation);
````

I can see the following JSON being emitted.

```json
{
  "query": {
    "function_score": {
      "functions": [
        {
          "my-custom-plugin": {
            "foo": "elastic_foo",
            "bar": "elastic_bar"
          },
          "weight": 1.0
        }
      ]
    }
  }
}
```

Hope this helps!

**Comment by nikiz0r** [comment]
Hi @Mpdreamz,
I've applied what you mentioned and it works just as I needed.
Thank you very much.

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Please let us know if this issue is still a relevant priority for your usage?
