### ISSUE TITLE
Null Reference Error occurs sometime when retrieving data from elastic search when maximum RAM was utilized in server

### ISSUE THREAD

**Issue by karanjshah** [elastic/elasticsearch-net#3526]
**NEST/Elasticsearch.Net version**:

**Elasticsearch version**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Describe the feature**:

**Comment by Mpdreamz** [comment]
This sounds unfortunate but without a stacktrace or anything else we have far too little information to look into this. Closing this but feel free to update the ticket with more infomation and we'll reopen this.
