### ISSUE TITLE
Switching alias causing downtime of < 1 sec

### ISSUE THREAD

**Issue by nhancers** [elastic/elasticsearch-net#3527]
**NEST/Elasticsearch.Net version**: 6.3.*

**Elasticsearch version**:6.3

**Description of the problem including expected versus actual behavior**:
Changing alias from old to new index causing very little downtime probably < 1 sec.
We are repointing alias to the new index with documents loaded in it. While performing this action we keep on simulating users using jMeter. During the process of alias switching, we see a downtime of < 1 sec and request fails to get documents.

**Steps to reproduce**:
 1. Perform alias switching. Keep on running jmeter to simulate load of 10 concurrent users.
 2. Delete the old index after alias points to new index.
 
**Pointing alias to new index**:
`await _clientNest.AliasAsync(ba => ba
            .Remove(remove => remove.Alias(aliasName).Index("*")).Add(add => add.Alias(aliasName).Index("test_new")));`

_We are deleting index after alias repointing succeeds._

We also tried 
`await _clientNest.AliasAsync(ba => ba
            .Remove(remove => remove.Alias(aliasName).Index("test_old")).Add(add => add.Alias(aliasName).Index("test_new")));` but produces same behaviour.

@Mpdreamz @roncohen @colinsurprenant @ph

**Comment by Mpdreamz** [comment]
Switching aliases shouldn't cause downtime, mind reopening this issue on discuss.elastic.co for a wider audience? Also include the actual failures you get from the get operations. 

Thanks!
