### ISSUE TITLE
Custom JsonConverter not used by the BulkAsync method

### ISSUE THREAD

**Issue by dhjgodin** [elastic/elasticsearch-net#3538]
**NEST/Elasticsearch.Net version**: 6.4.0

**Elasticsearch version**: 5.6

**Description of the problem including expected versus actual behavior**:
When using a JsonConverter CanConvert is never called when using BulkUpdate

**Steps to reproduce**:
 1. Add a custom JsonConverter
```
var connectionSettings = new ConnectionSettings(
                pool,
                (builtin, settings) => new JsonNetSerializer(builtin, settings,
                    () =>
                    {
                        var jSettings = new JsonSerializerSettings();
                        jSettings.Converters.Add(new MyTypeJsonConverter());
                        return jSettings;
                    }));
```
 2. Add a break point or output log in the CanConvert method.

 3. Call `await client.BulkAsync(descriptor);`

The CanConvert method won't be hit, calling `await client.IndexAsync(` does however hit the method.

**Comment by russcam** [comment]
Thanks for reporting @dhjgodin, we'll need to investigate

**Comment by Mpdreamz** [comment]
I [have tried to reproduce this](https://github.com/elastic/elasticsearch-net/commit/a39ef5abfe0e7c4843e3301422edf06604fd5422) but was not able to see this behaviour. 


Mind sharing more information about your setup @dhjgodin

**Comment by dhjgodin** [comment]
Thank you for looking into this for me.  At first this made no sense to me as I can see your test shows that it works yet mine continued to fail.  Then I found we have a duplicate identically named factory for the client, the one the bulk method is using doesn't have the Converter.

Apologies for wasting your time.  Your test did however prove that it was a bug in our code and helped me isolate the issue so thank you for that.

**Comment by Mpdreamz** [comment]
Thanks for reporting back! Much appreciated.
