### ISSUE TITLE
NEST and auto-interval date bucket

### ISSUE THREAD

**Issue by mantasaudickas** [elastic/elasticsearch-net#3549]
Any idea when NEST 6.x will support auto-interval date?
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-autodatehistogram-aggregation.html

Maybe its already there but just looking in wrong place?

**Comment by russcam** [comment]
Thanks for opening @mantasaudickas. I've added to go into the next 6.x release https://github.com/elastic/elasticsearch-net/issues/3552

**Comment by russcam** [comment]
@mantasaudickas This is included in the [6.5.1 release on Nuget](https://www.nuget.org/packages/NEST/6.5.1)
