### ISSUE TITLE
There is no available option to configure keywords_pattern

### ISSUE THREAD

**Issue by IvanSorokin** [elastic/elasticsearch-net#3551]
**NEST/Elasticsearch.Net version**: 6.4.2

**Elasticsearch version**: 6.5.1

**Description of the problem including expected versus actual behavior**:

As stated in [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-keyword-marker-tokenfilter.html) I can specify ```keywords_pattern``` for Keyword marker. But there is no available option in the NEST ```KeywordMarkerTokenFilterDescriptor``` only ```Keywords``` and ```KeywordsPath```

**Comment by codebrain** [comment]
@IvanSorokin - thanks for raising. I have submitted a PR, once approved it should be available in `6.6.0`

**Comment by russcam** [comment]
Closing this as will be in the next release
