### ISSUE TITLE
GetManyAsync returns the changed values if they are similar to the time data

### ISSUE THREAD

**Issue by enot123** [elastic/elasticsearch-net#3554]
**NEST/Elasticsearch.Net version**:
6.0.2 - 6.4.2
**Elasticsearch version**:
elasticsearch-6.3.1
**Description of the problem including expected versus actual behavior**:
I have docs with fields like as 
```
{
        "created-at": "2009-11-15T14:12:12"
}
```
It is keyword type. When I use client.GetManyAsync<Dictionary<string, string>>() I recieve
```
{
        "created-at": "11/15/2009 14:12:12"
}
```
I expected 
```
{
        "created-at": "2009-11-15T14:12:12"
}
```
Method client.SearchAsync<Dictionary<string, string>> returns unchanged values
**Steps to reproduce**:
 1. Create index with mapping
```
"mappings": {
            "_doc": {
                "properties": {
                    "created-at": {
                        "type": "keyword"
                    }
                }
            }
```
2. Add doc with source like as
```
{
        "created-at": "2009-11-15T14:12:12"
}
```
 3. ```client.GetManyAsync<Dictionary<string, string>>()```

**Provide `ConnectionSettings` (if relevant)**:
```
new ConnectionSettings(new Uri("http://localhost:9200/"));
```
P.S it is work correctly if  use 
```
new ConnectionSettings( new SingleNodeConnectionPool(new Uri("http://localhost:9200/")), JsonNetSerializer.Default);
```

**Comment by russcam** [comment]
Thanks for reporting @enot123. I think I know why this might be happening, but will need to investigate further

**Comment by russcam** [comment]
Relates: https://github.com/JamesNK/Newtonsoft.Json/issues/862

**Comment by russcam** [comment]
I've opened #3611 to address

**Comment by russcam** [comment]
#3611 is merged so this will go into the next released. Closing this.
