### ISSUE TITLE
.NET client documentation improvements

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#3559]
- Fix all incorrectly defined `/// <inheritdoc />` statements
- Ensure XML documentation on *everything public*
- Potentially revisit language used in the ApiGenerator templates
- The documentation generator is skipping <inheritdoc /> declarations and failing to omit documentation - problem exists in XmlDocsVisitor.

**Comment by stevejgordon** [comment]
Will be applied during code-gen in v8.
