### ISSUE TITLE
Jsonproperty points to a property with Jsonignore when using Elasticsearch.Net

### ISSUE THREAD

**Issue by longmaster** [elastic/elasticsearch-net#3561]
NEST/Elasticsearch.Net version: 6.4.0

I am in a situation that i would like to return SocialNumber with the value of ParentId when using Elasticsearch.Net . Is that possible?

public class Parent
{
    [JsonProperty("SocialNumber")]
    public string ParentId { get; set; }

    [JsonIgnore]
    public string SocialNumber { get; set; }
}
It seems Nest does not understand how to serialize this case!

Thank you all!

**Comment by russcam** [comment]
Hi @longmaster, 

We reserve GitHub Issues for bug reports and feature requests.

In order for your question to get the attention it deserves, the best place to ask it would be the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Not only do more folks view the forums than the GitHub Issues list, and hence it is more likely to receive attention, but the forums are also geared towards being able to search previous questions and answers, making it a much more valuable archive for future question askers.

Thanks!
