### ISSUE TITLE
Investigate slow incremental builds of solution

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#3565]
Rebuilding in Rider takes too long, investigate whether this is due to our current SDK, something invalidating the incremental builds or other.

**Comment by russcam** [comment]
With the move over the Bullseye in #3636, should we close this?

**Comment by Mpdreamz** [comment]
Yes, not related to bullseye but the incremental builds seem better on a later sdk. Still not great but I did some investigation with structured msbuild logging and could not locate an offender.
