### ISSUE TITLE
Move build to BullsEye and Proc

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#3567]
FAKE has served us well over the years but several reasons cause us to want to move over:

* FAKE 5 is heavily split in modules and gets quite tiring to compose back together
* FSharp editors are lacking
   * Rider works but at some point it keeps jumping the cursor as I type (could be IdeaVIM interaction)
   * Ionide works but I am personally not fond of VS code. Ionide is also just slow enough to be annoying
   * there is a fsharp LSP which is fast! but does not work with fsx files 😢 
* Paket is the best package manager we don't use.
   * .NET core integration nowadays is there, we had to drop it since it was not ready at the time.
   * Now we only use paket for FAKE.
   * FAKE5 paket integration and intellisense generation is clever but given the state of the tooling we do not need clever.

Most of the big FAKE targets have been pushed to dedicated dotnet tools already.

https://github.com/adamralph/bullseye

Is a very minimalist target runner combined with https://github.com/nullean/proc will do most of what we need

It will give us a regular csharp project that will build and run just like the rest of our projects. I love love fsharp but the benefits of that outweigh my language preference.

**Comment by russcam** [comment]
I think we can close this now, @mpdreamz?

**Comment by russcam** [comment]
Closing this as this change has been made in 6.x and 7.x
