### ISSUE TITLE
Add article_case property to IElisionTokenFilter

### ISSUE THREAD

**Issue by cgbeutler** [elastic/elasticsearch-net#3570]
**Describe the feature**:
ElasticSearch allows for an elision filter to have a property called "article_case"
```
"french_elision": {
  "type": "elision",
  "articles_case": true,
  "articles": [
    "l", "m", "t", "qu", "n", "s", "j", "d", "c", "jusqu", "quoiqu", "lorsqu", "puisqu"
  ]
}
```

This property appears to be missing from the fluent definitions for Nest. It would be nice to have that added so one could truly recreate the default french filter as elastic search has it internally. This would probably involve adding `ArticleCase` to the `IElisionTokenFilter`.
Something like:

```
.Elision("french_elision", f => f
  .ArticlesCase(true)
  .Articles("l", "m", "t", "qu", "n", "s", "j", "d", "c", "jusqu", "quoiqu", "lorsqu", "puisqu"))
```

**Comment by russcam** [comment]
Thanks for opening @cgbeutler, this is missing. We'll add it into the next release.

In the meantime, you can add it by deriving from `ElisionTokenFilter` and add the property e.g.

```c#
public class MyElisionTokenFilter : ElisionTokenFilter 
{
    [PropertyName("articles_case")]
    public bool? ArticlesCase { get; set; }
}
```

and use this in your settings using `.UserDefined("french_elision", <instance of MyElisionTokenFilter>)`

**Comment by russcam** [comment]
Added https://github.com/elastic/elasticsearch-net/pull/3572 to address
