### ISSUE TITLE
Add Score property to Nest.TermVectorTerm class

### ISSUE THREAD

**Issue by volj1** [elastic/elasticsearch-net#3604]
**NEST/Elasticsearch.Net version**: 6.5.1

**Elasticsearch version**: 6.4.0

**Describe the feature**:
The **Nest.TermVectorTerm** class has no **Score** property to refiect corresponding data from ElasticSearch response.

See the "Terms filtering" example from the ElasticSearch docs:
[https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-termvectors.html#docs-termvectors-terms-filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-termvectors.html#docs-termvectors-terms-filtering
)

**Comment by russcam** [comment]
I've added #3606 to address

**Comment by russcam** [comment]
Closing this; will be in the next release, `6.6.0`.
