### ISSUE TITLE
Accessing ES 5.5 with NEST 6.x

### ISSUE THREAD

**Issue by mantasaudickas** [elastic/elasticsearch-net#3607]
Hi,

not sure if this is supported, but we used ElasticSearch server 5.5 with NEST Client 6.4.
It worked fine until we had to use some inline scripts.

With this version combination we are getting server error:
illegal_argument_exception: reason": "[script] unknown field [source], parser not found

Steps to reproduce:
1. create index:
```
PUT myindex/doc/1
{
  "my_field": 5
}
```

2. do search:
```
GET myindex/_search
{
  "script_fields": {
    "my_doubled_field": {
      "script": {
        "lang":   "expression",
        "inline": "doc['my_field'] * multiplier",
        "source": "doc['my_field'] * multiplier",
        "params": {
          "multiplier": 2
        }
      }
    }
  }
}
```
3. server responds with error:
```
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "[script] unknown field [source], parser not found"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "[script] unknown field [source], parser not found"
    },
    "status": 400
}
```

We did a short check, and found that between 5.5 and 5.6 documentation was changed:
https://www.elastic.co/guide/en/elasticsearch/reference/5.5/modules-scripting-using.html
(uses inline)
vs
https://www.elastic.co/guide/en/elasticsearch/reference/5.6/modules-scripting-using.html
(uses source).

Seems like client 6.x is sending both fields while server 5.5 does not recognize [source] field and is failing.

Can it be prevented somehow?

**Comment by russcam** [comment]
The 6.x client is not compatible with 5.x, [see the compatibility matrix](https://github.com/elastic/elasticsearch-net#compatibility-matrix). 

There are known breaking changes between Elasticsearch 5.x and 6.x that are reflected in changes in the client. The latest 5.x client should be used with Elasticsearch 5.x 👍
