### ISSUE TITLE
NEST client 6.x / Elastic Server 1.x

### ISSUE THREAD

**Issue by fahrigoktuna** [elastic/elasticsearch-net#3612]
Hi,

I need guidance/help regarding to migration of ElasticSearch 1.x to 6.x. Here is my question and what I need. I have to use NEST client on .Net Core version 6.x but I dont want to change elasticSearch version of server which 1.x. Is it possible to just migrate my .net core client to6.x and use 1.x as server side?

If not, what can you recommend to this migration since I have to upgrade my .net framework to .net core? How should I continue?

**Comment by russcam** [comment]
Hi @fahrigoktuna , 

We reserve GitHub Issues for bug reports and feature requests.

In order for your question to get the attention it deserves, the best place to ask it would be the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Not only do more folks view the forums than the GitHub Issues list, and hence it is more likely to receive attention, but the forums are also geared towards being able to search previous questions and answers, making it a much more valuable archive for future question askers.

Please open this question on the forum.

Thanks!
