### ISSUE TITLE
Possible socket starvation due to non-static HttpClient

### ISSUE THREAD

**Issue by ThomasVestergaard** [elastic/elasticsearch-net#3620]
I have a long running .NET core 2.2 application running in a container in AWS. It received a lot of requests and indexes stuff in elasticsearch via the Client.Index(...) method.

The container has rising memory usage and in the end, restarts because heartbeats from external services are not received.

After debugging this for days, I narrowed it down to the nest client, specifically the usage of HttpClient in HttpConnection.cs.

In HttpConnection.cs, the method GetClient(...) maintains a dictionary of HttpCliens which is reused. This is not as per Microsoft guidelines and is causing socket starvation. A few reads on the topic:

- https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client#create-and-initialize-httpclient
- https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

So I forked this repo, and did a simple test where I'm reusing a static HttpClient across all calls. This fixed the problem and the service is now completely stable.

What are your thoughts on this?

![AWS ECS memory usage](https://i.imgur.com/f6sjvwS.jpg)

**Comment by russcam** [comment]
Firstly, thanks for opening @ThomasVestergaard. 

Could you provide some more information about the .NET core application:

1. Runtime version
2. OS platform host - you mention container, so sounds like a Linux distro. Would you also be able to provide details about the container environment, version, etc. too?

The dictionary of HTTP clients should be caching `HttpClient` instances for the lifetime of the `HttpConnection`, which should be a singleton tied to a singleton `ConnectionSettings` and `ElasticClient`

https://github.com/elastic/elasticsearch-net/blob/01047d93faf31e2f31cca811999a8337ca368a93/src/Elasticsearch.Net/Connection/HttpConnection.cs#L130-L151

The key for the dictionary is determined from:

https://github.com/elastic/elasticsearch-net/blob/01047d93faf31e2f31cca811999a8337ca368a93/src/Elasticsearch.Net/Connection/HttpConnection.cs#L274-L286

A few initial thoughts come to mind:

1. Are you varying any of the components of `RequestData` with each request that would constitute multiple `HttpClient` instances to be created?
2. Are you using custom TCP Keep Alive values on `ConnectionSettings.EnableTcpKeepAlive(...)`?
3. Are you configuring a higher connection limit using `ConnectionSettings.ConnectionLimit(...)`? The default connection limit is set to the processor count when the underlying `HttpClientHandler` is `System.Net.Http.CurlHandler`, and 80 for all others. We have experienced `System.Net.Http.CurlHandler` not reusing TCP connections previously (#2784) so set a very conservative connection limit.

Any additional detail that you can provide will be super useful. If you have a repro that clearly replicates what you're seeing, that would be even more awesome!

**Comment by ThomasVestergaard** [comment]
Hi @russcam 
Thanks for the rapid reply on this.
I will try to make a repo where I replicate the issue where all of your questions are answered. Will get back to that later.
Meanwhile, it seems a HttpClientFactory has been introduced in .net core 2.1 which is addressing this exact issue. 
https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests

I will try to do a test with the HttpClientFactory as well.

**Comment by russcam** [comment]
Thank you! We have full intentions of moving over to `HttpClientFactory` where possible 😃

**Comment by StephaneBischoff** [comment]
I have the same issue it seems using ElasticClient within durable functions in Azure. I am getting SocketExceptions after a few successful requests. @ThomasVestergaard, please let me know the solution if you find one.

**Comment by ThomasVestergaard** [comment]
@russcam Sorry for the very late reply on this.
Today i experienced this with the fix from earlier:
![IMem spikes](https://i.imgur.com/9wi6vLa.jpg)
So maybe my issue is not tied to elasticsearch after all.
I think it might be best to close this issue until I get to the bottom of this. Right now I can't rule out anything.

**Comment by russcam** [comment]
@ThomasVestergaard Did you send an email reply saying to close this for now?

**Comment by ThomasVestergaard** [comment]
@russcam Sorry for the very late reply. Yes I did - It was a comment on this thread which I deleted again. I have been debugging this on and off for a while and I'm getting inconsistent results, so no conclusion yet. I think it's best to close this for now. I'll reopen if I get something concrete to look at.

**Comment by russcam** [comment]
Thanks @ThomasVestergaard. Feel free to reopen if you get to something concrete 👍

**Comment by roelandvh** [comment]
Just a thought: could this be connected to https://github.com/dotnet/corefx/pull/32793? Socket starvation and a memory leak could perhaps be related. More information: https://github.com/dotnet/corefx/issues/37044#issuecomment-500660152 and https://github.com/dotnet/corefx/issues/31262 .
