### ISSUE TITLE
Consistent naming of Timezone/TimeZone

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#3622]

**Comment by russcam** [comment]
Votes on `TimeZone` or `Timezone` ? Since it's two words, might vote is for `TimeZone` but I have no strong preference, other than for consistency 😃 

Thoughts @codebrain , @Mpdreamz ?

**Comment by ghuntley** [comment]
FYI - nodatime uses `TimeZone` - https://github.com/nodatime/nodatime/blob/master/src/NodaTime/TimeZones/CachedDateTimeZone.cs#L11

**Comment by codebrain** [comment]
++ for TimeZone (https://docs.microsoft.com/en-us/dotnet/api/system.timezone?view=netframework-4.7.2)

**Comment by russcam** [comment]
Going for `TimeZone`

**Comment by russcam** [comment]
This is now merged into 7.x in #3645.
