### ISSUE TITLE
Nested objects are not being returned 

### ISSUE THREAD

**Issue by dholakianivid** [elastic/elasticsearch-net#3630]
**NEST/Elasticsearch.Net version**:
6.0.2
**Elasticsearch version**:
6.0.2
**Description of the problem including expected versus actual behavior**:
When I am using Nest C# client to query elastic search the nested objects aren't returned back in the result set. I checked fiddler the field is not returned. If I use the same query in Kibana works fine.
**Steps to reproduce**:
simple query 
```
{
  "query": {
    "query_string": {
      "query": "TOYOTA"
    }
  }
}
```
```
{
"name":  "Toyota",
          "models": [
            {
              "name": "Camry",
              "trim": "LE",
              "noOfCylinders": 4
            },
            {
              "name": "Camry",
              "trim": "XLE",
              "noOfCylinders": 4
            },
           {
              "name": "SIENNA",
              "trim": "XLE",
              "noOfCylinders": 6
            }
          ]
}
```

**C# Classes**
```
[ElasticSearchType(Name="Company")]
public class Company
{
    public string Name { get; set; }
    [Nested]
    public Model[] Models { get; set; }
}
[ElasticSearchType(Name="Models")]
public class Model
{
    public string Name { get; set; }
    public string Trim { get; set; }
    public int NoOfCylinders { get; set; }
}
```
**Index Configuration**
```
"models": {
            "type": "nested",
            "include_in_parent": true,
            "noOfCylinders": {
              "division": {
                "type": "integer"
              },
              "name": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "trim": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              }
            }
          }
```

**Comment by russcam** [comment]
Hey @dholakianivid. can you please post a complete example that replicates the issue? I suspect the query being sent with NEST is likely not the same as the one being sent by Kibana.

**Comment by dholakianivid** [comment]
> Hey @dholakianivid. can you please post a complete example that replicates the issue? I suspect the query being sent with NEST is likely not the same as the one being sent by Kibana.
Hi,
 I will have to create a sample index and project for this thing.  I can't share our index data here.  
I know it's hard to replicate without example but as I mentioned I copied the query sent to elastic from fiddler and it works as expected.  But the response isn't the same, it doesn't have the nested objects included in the result set.  


Thanks,
Nivid Dholakia

**Comment by dholakianivid** [comment]
Sorry please disregard this issue. It was an issue with wildcard in index name. I didn't change it to the desired one. So it brought data from other index too.

**Comment by russcam** [comment]
Thanks for letting us know, @dholakianivid 👍
