### ISSUE TITLE
IElasticClient.GetAlias().IsValid throws NullReferenceException if Elasticsearch is not reachable

### ISSUE THREAD

**Issue by bittusarkar** [elastic/elasticsearch-net#3643]
**NEST/Elasticsearch.Net version**: 6.3.1

**Elasticsearch version**: 6.2.4

**Description of the problem including expected versus actual behavior**:
`IGetAliasResponse.IsValid` throws NullReferenceException if Elasticsearch is not reachable. It should just return `false`.

**Steps to reproduce**:
 1. Make sure Elasticsearch is not running.
 2. Invoke `IElasticClient.GetAlias(s => s.Name("any_name_will_do")).IsValid`.

`IsValid` property will throw a null ref exception. Definition of this property is as under in [this file](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Indices/AliasManagement/GetAlias/GetAliasResponse.cs):
`public override bool IsValid => Indices.Count > 0;`

`Indices` is `null` when Elasticsearch is not running and that results in this exception. Ideally, `IsValid` should never fail and its definition should be updated to as under:
`public override bool IsValid => Indices != null && Indices.Count > 0;`

**Comment by russcam** [comment]
Thanks for opening @bittusarkar. Your proposal looks reasonable to me. Would you be interested in opening a PR for this?

**Comment by bittusarkar** [comment]
Sure, I can send a PR for this.

**Comment by bittusarkar** [comment]
@russcam This does not reproduce anymore in 6.7.0. So I guess something got fixed.

**Comment by Mpdreamz** [comment]
Thanks for reporting back to us @bittusarkar, will close this.
