### ISSUE TITLE
JsonNet serializer not used for script params

### ISSUE THREAD

**Issue by sloncho** [elastic/elasticsearch-net#3652]
**NEST/Elasticsearch.Net version**: 6.6.0

**Elasticsearch version**: n/a

**Description of the problem including expected versus actual behavior**:

Script parameters are not serialized using the externally provided serializer (JsonNet). If elastic client is configured to use StringEnum serializer, this is not applied to objects passed as script update parameters.

Using [SourceConverter](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/CommonOptions/Scripting/ScriptBase.cs#L32) instead?

**Comment by russcam** [comment]
Thanks for opening @sloncho.

Not sure what we should do here; thoughts @Mpdreamz, @codebrain ?

**Comment by russcam** [comment]
We haven't discussed this yet @Alukim. 

For string enum values, enums can be attributed with `[StringEnum]` to serialize as strings

```c#
private static void Main()
{
    var defaultIndex = "example";
    var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));

    var settings = new ConnectionSettings(pool, JsonNetSerializer.Default)
        .DefaultIndex(defaultIndex)
	.DefaultTypeName("_doc");

    var client = new ElasticClient(settings);

	var indexResponse = client.Update<Document>(1, u => u
		.Script(s => s
			.Source("ctx._source.foo = params.foo")
			.Params(p => p
				.Add("foo", Foo.Bar)			
			)
		)
	);
}

public class Document 
{
	public Foo Foo { get;set; }
}

[StringEnum]
public enum Foo
{
	Bar,
	Baz
}
```

which emits

```json
POST http://localhost:9200/example/_doc/1/_update?pretty=true 
{
  "script": {
    "params": {
      "foo": "Bar"
    },
    "source": "ctx._source.foo = params.foo"
  }
}
```

**Comment by codebrain** [comment]
@Alukim - does the suggested solution help?

**Comment by codebrain** [comment]
Closing as no response has been received, a solution has been offered by @russcam above.
