### ISSUE TITLE
Support PrettyJson in serialized requests when Formatting.Indented specified

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#3654]
With the move to utf8json in #3493, the internal serializer does no indentation, even when `Formatting.Indented` is specified.

Indentation should be performed when `Formatting.Indented` is specified.

**Comment by codebrain** [comment]
Will mark parameter as `Obsolete` or through xmldocs to indicate that pretty printing functionality is not yet supported in the new serialiser in `7.x`

**Comment by russcam** [comment]
clarification: don't think we're proposing to mark as obsolete, only XML docs

**Comment by stevejgordon** [comment]
Can re-review with STJ implementation.
