### ISSUE TITLE
7.0.0 ElasticsearchTypeAttribute should continue to support Name property

### ISSUE THREAD

**Issue by nenadvicentic** [elastic/elasticsearch-net#3681]
**NEST/Elasticsearch.Net version**:
7.0.0-alpha1
**Elasticsearch version**:
7.0.0
**Description of the problem including expected versus actual behavior**:

**Actual**
Even though mapping types have been removed in Elasticsearch 7.x, option to set name of the class for serialization is still useful when using fluent/strongly-type interfaces.

1. When defining `Join` in index mapping:
```
_client.CreateIndexAsync(IndexName,
    index => index.Map<MyDocument>(
        tmd => tmd.AutoMap()
        .Properties(
            props => props.Join(
                j => j.Name(p => p.Relationship)
                .Relations(
                    r => r.Join<ParentType, ChildType>()
                    )
                )
            )
        )
    );
```

2. When linking instances of child types to parent types:
```
var parent = new ParentType { Id = 1 };
var parentDoc = new MyDocument
{
    Parent = parent,
    Relationship = JoinField.Root<ParentType>()
}

var childDoc = new MyDocument
{
    Child = new ChildType(),
    Relationship = JoinField.Link<ChildType>(new Id(parent.Id))
}
```
3. When using `JoinAttribute` on `JoinField` property:
```
public class MyDocument
{
    public ParentType Parent { get; set; }

    public ChildType Child { get; set; }

    [Join(typeof(ParentType), typeof(ChildType))]
    public JoinField Relationship { get; set; }
}
```

**Expected**
Therefore, possibility to override class name for serialization should still be supported. In the past `ElasticsearchTypeAttribute`'s `Name` property was used for this.

**Comment by Mpdreamz** [comment]
Thank you a ton for reporting  this @nenadvicentic 

`ElasticsearchTypeAttribute.RelationName` now controls this. 

Since this obscure I think it be best if we ship `.Name` and mark it obsolete instead, @codebrain @russcam thoughts?

**Comment by nenadvicentic** [comment]
@Mpdreamz thanks a lot for your feedback!

I think `RelationName` is pretty confusing for that purpose.

My impression was, since `ElasticsearchTypeAttribute.IdProperty` property is the name of property that servers as document ID, that `ElasticsearchTypeAttribute.RelationName` serves to mark `JoinField` for document join relationship.

In my above example with `MyDocument` it would be:

```
[ElasticsearchType(RelationName = "Relationship")]
public class MyDocument
{
    public ParentType Parent { get; set; }

    public ChildType Child { get; set; }

    public JoinField Relationship { get; set; }
}
```

**Comment by codebrain** [comment]
> Thank you a ton for reporting this @nenadvicentic
> 
> `ElasticsearchTypeAttribute.RelationName` now controls this.
> 
> Since this obscure I think it be best if we ship `.Name` and mark it obsolete instead, @codebrain @russcam thoughts?

Sounds good to me.

**Comment by russcam** [comment]
Agreed. I'll open a PR for this shortly

**Comment by russcam** [comment]
I've opened https://github.com/elastic/elasticsearch-net/pull/3702 to address

**Comment by russcam** [comment]
Closing this as #3702 has been merged. Will be in the next release
