### ISSUE TITLE
7.0.0 GetRequest with SourceExclude or SourceInclude error

### ISSUE THREAD

**Issue by dimmasik** [elastic/elasticsearch-net#3682]
**NEST/Elasticsearch.Net version**: 7.0.0

**Elasticsearch version**: 7.0

If you use GetRequest class and SourceExclude or SourceInclude fields it is translated into query
/{index_name}/_doc/{doc_id}?_source_include=...
/{index_name}/_doc/{doc_id}?_source_exclude=...

So error appears with text "# OriginalException: Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: GET /{index_name}/_doc/{doc_id}?_source_include=.... ServerError: Type: illegal_argument_exception Reason: "request [ /{index_name}/_doc/{doc_id}] contains unrecognized parameter: [_source_include] -> did you mean any of [_source_includes, _source_excludes]?""

Excpected: _source_includes and _source_excludes in result query instead of _source_include or _source_exclude. Need to add char "s" in the end of string.

**Comment by Mpdreamz** [comment]
I've opened https://github.com/elastic/elasticsearch/pull/41439 to address this in the source specs.

THis will be updated in the next release of the client @dimmasik thank you for reporting this :+1:

**Comment by russcam** [comment]
Opened https://github.com/elastic/elasticsearch-net/pull/3726 to address

**Comment by russcam** [comment]
Closing this as #3726 has been merged and will be in the next release
