### ISSUE TITLE
Add support for is_write_index

### ISSUE THREAD

**Issue by kpstolk** [elastic/elasticsearch-net#3686]
**Describe the feature**:

Allow setting of `is_write_index` for [Create Index](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-create-index.html#create-index-aliases) and [Index Aliases](https://www.elastic.co/guide/en/elasticsearch/reference/master/indices-aliases.html#aliases-write-index) API's which can be used by the Rollover API.

This seems currently not supported:
```
await client.CreateIndexAsync("my-index", s => s
    .Aliases(a => a
        .Alias("my-alias", d => d
            .IsWriteIndex() // <-- Method doesn't exist, only Filter() etc
        )
    )
);
```

Call via ES API:
```
PUT my-index
{
  "aliases": {
    "my-alias": {
      "is_write_index": true
    }
  }
}
```

**Comment by russcam** [comment]
Thanks for opening @kpstolk. Alias operations already had an ability to set `is_write_index`, but this was not exposed on aliases for the create index API. I have opened #3704 to address

**Comment by russcam** [comment]
Closing this as #3704 has been merged and will be in the next release
