### ISSUE TITLE
Bulk insert error

### ISSUE THREAD

**Issue by caopengfei** [elastic/elasticsearch-net#3687]
**NEST/Elasticsearch.Net version**:7.0.0-alpha1

**Elasticsearch version**:7.0.0

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1.
 2.
 3.
![TIM截图20190419093043](https://user-images.githubusercontent.com/10126284/56400457-9109f780-6286-11e9-948a-0652168f0bc5.png)

**Provide `ConnectionSettings` (if relevant)**:http://47.*.*.*:9200/

**Provide `DebugInformation` (if relevant)**:
![TIM截图20190419093358](https://user-images.githubusercontent.com/10126284/56400461-98c99c00-6286-11e9-9495-8db751b8123e.png)

**Describe the feature**:

**Comment by Mpdreamz** [comment]
Thank you for reporting this @caopengfei its hard to diagnose since `DebugInformation` throws a NRE which warrents investigation on its own. 

Might need you to run this again next week when we release another alpha

**Comment by russcam** [comment]
The exception message

> BulkAll halted after receiving failures that can not be retried from _bulk

indicates that the underlying issue is one of being unable to index some of the documents. Will need to investigate the NullReferenceException

**Comment by codebrain** [comment]
@caopengfei - would it be possible for you to try this again with the alpha2 release?

**Comment by caopengfei** [comment]
> @caopengfei - would it be possible for you to try this again with the alpha2 release?

The problem remains

**Comment by russcam** [comment]
@caopengfei I've opened #4077 to address the null reference exception in `BulkAll`.

Looking at the screenshot of the usage of `BulkAll`, it looks like there are a number of things that are not quite correct

1. the `BulkAll` call should not be called in a `while` loop where records are paginated from a database
2. if an exception is thrown during processing, the `CountdownEvent` is not signalled

You may want to change the implementation to encapsulate the pagination from the database inside a method that returns an `IEnumerable<T>`

```c#
public IEnumerable<Article> GetArticles(int num)
{
    using (DBUserContext db = new DBUserContext())
    {
        var data = db.Articles.Where(q => q /* your query */);
        while (data.Count > 0)
        {
            foreach(var d in data)
            {
                yield return d;
            }

            data = db.Articles.Where(q => q /* your query */);
        }
    }
}
```

Then pass this to `BulkAll`

```c#
int index = 1, num = 500;
var waitHandle2 = new CountdownEvent(1);

var bulkAll = client.BulkAll(GetArticles(500), b => b
    .MaxDegreesOfParallelism(8)
    // etc...
);

Exception ex = null;

bulkAll.Subscribe(new BulkAllObserver(
    onNext: b => Console.WriteLine("Some message"),
    onError: e => 
    { 
        ex = e; 
        waitHandle2.Signal();
    },
    onCompleted: () => waitHandle2.Signal()
));

waitHandle2.Wait();

if (ex != null)
    throw ex;
```
