### ISSUE TITLE
whether Nest5.2.0 and ElasticSearch.Net 5.2.0 can support elasticsearch6.7.1 query,filter,sort?

### ISSUE THREAD

**Issue by sunweiconfidence** [elastic/elasticsearch-net#3688]
Hi,

currently i use elasticsearch.net 5.2.0 and Nest5.2.0 to call elasticsearch5.2.0 to get the search result, now i prepare to upgrade elasticsearch to version 6.7.1, whether i can use current elasticsearch.net5.2.0 and Nest5.2.0 to call elasticsearch6.7.1? any potential issue for this? or no problem？ thanks

**Comment by sunweiconfidence** [comment]
correct it, i use elasticsearch.net 5.2.0 and Nest5.2.0 to call elasticsearch5.4.3 version's search index to get the search result

**Comment by Mpdreamz** [comment]
We don't support it but if you dont hit any of the [Elasticsearch 6.0 breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking-changes-6.0.html) you might get away with it. 

But again we don't support doing this.
