### ISSUE TITLE
NEST client fails within Parallel.ForEach loop, generates assembly loading error

### ISSUE THREAD

**Issue by BenLewies** [elastic/elasticsearch-net#3690]
**NEST/Elasticsearch.Net version**: Nest 6.6.0

**Elasticsearch version**: 6.51

**Description of the problem including expected versus actual behavior**:
Indexing with the NEST client inside a parallel foreach loop generates a "could not find file or assembly" error message during runtime, both for NetStandard2.0 and NetCoreApp2.1.

Given a list of class `Individual` objects, that we want to index to an index called "individuals", the following code produces the runtime exception:
`           
            Parallel.ForEach(individuals, individual =>
            {
                var indexResponse = _elasticClient.Index<Individual>(individual, i => i
                    .Id(individual.UniqueId));
            });
`

**Steps to reproduce**:
 1. Create NetStandard 2.0 class library and install NEST nuget package
 2. Index documents form within Parallel.Foreach loop 
 3. Invoke code during runtime from Azure Functions V2 (see update below)

**`DebugInformation`**:
> Elasticsearch.Net.UnexpectedElasticsearchClientException
>   HResult=0x80131500
>   Message=Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
>   Source=Elasticsearch.Net
>   StackTrace:
>    at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
>    at Elasticsearch.Net.ElasticLowLevelClient.DoRequest[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
>    at Elasticsearch.Net.ElasticLowLevelClient.IndexPut[TResponse](String index, String type, String id, PostData body, IndexRequestParameters requestParameters)
>    at Nest.LowLevelDispatch.IndexDispatch[TResponse,TDocument](IRequest`1 p, SerializableData`1 body)
>    at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 responseGenerator, Func`3 dispatch)
>    at Nest.ElasticClient.Nest.IHighLevelToLowLevelDispatcher.Dispatch[TRequest,TQueryString,TResponse](TRequest request, Func`3 dispatch)
>    at Nest.ElasticClient.Index[T](IIndexRequest`1 request)
>    at Nest.ElasticClient.Index[T](T document, Func`2 selector)
>    at Sanctions.ImportServices.Infrastructure.SanctionListElasticSearchIndexer.<>c.<IndexData>b__3_0(Individual individual) in ***CENSORED***
>    at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
> 
> Inner Exception 1:
> FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
> 
> Inner Exception 2:
> FileNotFoundException: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
> 

**UPDATE**
It seems that the same error is being generated when calling `BulkAll` synchronously, as per the following:
```
public static class ElasticSearchBulkUploader
    {
        public static void DoBulkUpload<TDocumentType>(this ElasticClient elasticClient, IEnumerable<TDocumentType> documents)
        where TDocumentType : class 
        {
            var waitHandle = new CountdownEvent(1);

            var bulkAll = elasticClient.BulkAll(documents, b => b
                .BackOffRetries(2)
                .BackOffTime("30s")
                .RefreshOnCompleted(true)
                .MaxDegreeOfParallelism(4)
                .Size(1000)
            );

            bulkAll.Subscribe(new BulkAllObserver(
                onNext: (b) => { Console.Write("."); },
                onError: (e) => { throw e; },
                onCompleted: () => waitHandle.Signal()
            ));

            waitHandle.Wait();
        }
}
```

This code, and the original code,is being invoked from Azure Functions V2.

**Comment by Mpdreamz** [comment]
Thanks for reporting this @BenLewies :+1:  do you see the same happening if you run locally?

Will look into this deeper tomorrow soonest.

**Comment by BenLewies** [comment]
Yes, this is running locally using the latest stable version of Azure Storage Emulator.

**Comment by russcam** [comment]
@BenLewies what dotnet version are you running i.e. what does the following output

```bat
dotnet --version
```

In Azure functions, what framework version and runtime is your code running under? I'm wondering if this may be related to https://github.com/dotnet/standard/issues/328

**Comment by BenLewies** [comment]
2.2.104

**Comment by BenLewies** [comment]
@Mpdreamz @russcam Were you able to reproduce this issue on your side?

**Comment by Mpdreamz** [comment]
@BenLewies not locally, we'll need to carve out time to replicate these conditions which is something we won't have in the next weeks

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Please let us know if this issue is still a relevant priority for your usage?
