### ISSUE TITLE
.Net Framework & Nest 7.0

### ISSUE THREAD

**Issue by GaryTurpin** [elastic/elasticsearch-net#3692]
I have noticed that the last couple versions of Nest.JsonNetSerializer only support .Net Standard.  Will Nest 7.0 and Nest.JsonNetSerializer 7.0 support .Net Framework once the projects go GA?

**Comment by Mpdreamz** [comment]
Hey @GaryTurpin 

What are your exact needs here? Referencing netstandard in `4.6.1` and up i supported allbeit a tad cluttered in the `4.6.x` range. The process of referencing netstandard libraries is much smoother in `4.7.2` and up. 

This is the reason why on `6.x` we still explicitly target `net461`in our nuget packages. 

We don't intend to drop support for net461 in `7.0` but are still evaluating which TFM's we want to support.

Our `master` is one TFM on purpose, we want to ensure our code is netstandard2.0 only (possibly netstandard3.0 only going towards 8.0). When we create our version specific branches we reevaluate our TFM choices which is what happened with 7.0 :smile: 

Given the rocky experience and known bugs referencing `netstandard2.0` libraries I do think its highly likely we'll reintroduce `net461` TFM in 7.0

**Comment by GaryTurpin** [comment]
@Mpdreamz supporting 4.6.1 and up is fine with us.  We are currently on 4.7.1 and have on our roadmap to change to .Net Standard.  I just wanted to see would have to put the ElasticSearch and Nest upgrades until after we support .Net Standard.  

Do you know if Nest.JsonNetSerializer will be reevaluated to see if it can support .Net Framework?  We haven't been able to move past 6.2.0 since it doesn't support .Net Framework.
