### ISSUE TITLE
Add Properties Currently Missing from ClusterHealthResponse.cs

### ISSUE THREAD

**Issue by SpencerLN** [elastic/elasticsearch-net#3698]
**Describe the feature**: The same data present when calling the _cluster/health API directly should be available when calling ClusterHealth() in NEST. The current behavior is that several properties are missing from ClusterHealthResponse.cs including:
- active_shards_percent_as_number
- delayed_unassigned_shards
- number_of_in_flight_fetch
- task_max_waiting_in_queue_millis

**Comment by SpencerLN** [comment]
#3699

**Comment by russcam** [comment]
#3699 has been merged, so this will be in the next 6.x release. Thanks again, @SpencerLN 👍
