### ISSUE TITLE
7.1.0 expected:'Number Token', actual:'"0"'

### ISSUE THREAD

**Issue by bluewalk** [elastic/elasticsearch-net#3703]
**NEST/Elasticsearch.Net version**: 7.1.0-ci20190429T050458

**Elasticsearch version**: 7.0.0

**Description of the problem including expected versus actual behavior**:
Request returns with an exception `JsonParsingException: expected:'Number Token', actual:'"0"', at offset:518` whilst the property has been marked with attribute Text.

**Steps to reproduce**:
 1. Logging via log4net elastic search module
 2. Retrieving the logs as: 
```csharp
var results = _client.Search<MyLog>(s =>
                s.Sort(ss => ss.Descending(p => p.TimeStamp))
                    .Size(150)
                    .From(from)
                    .Index("log-something")
                    .Query(
                        q => q.QueryString(qs => qs.Query($"*{query}*")))
            );
```
 3. "Enjoy" the exception

**Provide `DebugInformation` (if relevant)**:
The entry it's failing on is `"lineNumber": "0",`

Returned JSON for an item is
```json
{
    "timeStamp": "2019-04-29T05:50:49.0457231Z",
    "message": "Finished",
    "messageObject": {},
    "exception": {},
    "loggerName": "myproject",
    "domain": "myproject.exe",
    "identity": "",
    "level": "INFO",
    "className": "myproject.Lib.Regger",
    "fileName": null,
    "lineNumber": "0",
    "fullInfo": "myproject.Lib.Regger.Log(:0)",
    "methodName": "Log",
    "fix": "LocationInfo, UserName, Identity, Partial",
    "properties": {
        "log4net:Identity": "",
        "log4net:UserName": "username",
        "log4net:HostName": "somemachine",
        "@timestamp": "2019-04-29T05:50:49.0457231Z"
    },
    "userName": "username",
    "threadName": "3",
    "hostName": "somemachine"
}
```

It has been marked in the model as followed: 
```csharp
        [Text(Name = "lineNumber")]
        public long LineNumber { get; set; }
```
Yet the library tries to resolve it as an integer.

**Comment by bluewalk** [comment]
Seems the new serializer takes the property datatype for deserialization, as this was defined as `long` instead of `string` the deserializer failed.

Can be closed :)

**Comment by russcam** [comment]
@bluewalk The serializer is much stricter in 7.x, but the benefit is that it is much faster 😃

**Comment by kartheek91** [comment]
![image](https://user-images.githubusercontent.com/13515213/80284135-31b4b200-873a-11ea-9a1f-f48b58e3be6d.png)

Hi RussCam I'm unable to solve the above mentioned issue.Actually I kept mapping to strict

**Comment by russcam** [comment]
> How I need to check which field causing the issue?

@kartheek91 Have a look at [the documentation on capturing the response](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/logging.html). The error message provides the offset, so you should be able to ascertain which document is the culprit.

> I kept mapping to strict.

`strict` mapping only controls If new fields are detected in a document, throw an exception and  the reject the document, so that new fields must be explicitly added to the mapping. What you probably want is to set [`coerce` to `false`](https://www.elastic.co/guide/en/elasticsearch/reference/current/coerce.html), which is `true` by default.
