### ISSUE TITLE
Abstract object not mapped correctly in Nest 7.0.0-alpha1

### ISSUE THREAD

**Issue by andreasnauta** [elastic/elasticsearch-net#3705]
**NEST/Elasticsearch.Net version**: 7.0.0-alpha1

**Elasticsearch version**: 7.0.0

**Description of the problem including expected versus actual behavior**:
See [Question in Stackoverflow](https://stackoverflow.com/questions/55849350/abstract-object-not-mapped-correctly-in-elasticsearch-using-nest-7-0-0-alpha1)

**Steps to reproduce**:
 1. Clone repository https://github.com/andreasnauta/test-nest-7.0.0-alpha
 2. Insert ConnectionSettings
 3. Run InsertTest in 7.0.0

**Comment by russcam** [comment]
I appreciate you taking the time to open this @andreasnauta, and the tests repository, thanks! 

We'll need to have a discussion amongst the team as to whether we should look to support this in 7.x's internal serializer, as it is not something currently supported in 6.x out of the box, as you have found in the tests with 6.6.0. 

It is possible to support this with a discriminator field within the `actor` object. [Json.NET supports this notion with `TypeNameHandling`](https://www.newtonsoft.com/json/help/html/SerializeTypeNameHandling.htm), which [we have an example of doing in the docs.](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html#_serializing_type_information) You'll need to also reference the `Nest.JsonNetSerializer` nuget package ](https://www.nuget.org/packages/NEST.JsonNetSerializer)and [hook it up as the serializer to use for your documents as per the docs.](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html#_jsonnetserializer)

**Comment by russcam** [comment]
Upon discussion with the team, we've decided that we're not going to change how the client works to support this by default, since it's something that can be handled with custom serialization.

**Comment by andreasnauta** [comment]
Thank you for looking into this @russcam and thank you for the links :)
