### ISSUE TITLE
Calling ConnectionSettings.DefaultMappingFor throws ArgumentException when the Type has been previously added

### ISSUE THREAD

**Issue by ejsmith** [elastic/elasticsearch-net#3706]
**NEST/Elasticsearch.Net version**: 7.0.0-alpha1

**Elasticsearch version**: 7.0.0

**Description of the problem including expected versus actual behavior**:
When calling ConnectionSettings.DefaultMappingFor it will throw if the Type has already been added. It seems like it should just be replacing the mapping if it already exists and not throwing. Even if you want to not have it automatically overwrite the existing mapping, there is no way for the end user to know if it's already mapped or not.

```
 System.ArgumentException : An item with the same key has already been added. Key: Foundatio.Repositories.Elasticsearch.Tests.Repositories.Models.Employee
Stack Trace:
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Nest.ConnectionSettingsBase`1.DefaultMappingFor(Type documentType, Func`2 selector)
```

**Comment by ejsmith** [comment]
@russcam Any comments on this? Not really sure how I can even work around it.

**Comment by Mpdreamz** [comment]
Sorry for leaving this lingering we'll fix this in the next beta which should be out in the coming days. 

We'll add a third argument which toggles whether the call should be override existing values or not.

**Comment by russcam** [comment]
@ejsmith I've opened https://github.com/elastic/elasticsearch-net/pull/3807 to address. Following a team discussion last week, we came to the agreement that it would make more sense for the default mapping methods to use the dictionary indexers to set/override values for default mapping, as opposed to the `.Add` methods. What do you think?

**Comment by russcam** [comment]
Closing this as #3807 has been merged into 7.x
