### ISSUE TITLE
SequenceNumber and PrimaryTerm missing from IMultiGetHit and IHit

### ISSUE THREAD

**Issue by ejsmith** [elastic/elasticsearch-net#3708]
**NEST/Elasticsearch.Net version**: 7.0.0-alpha1

**Elasticsearch version**: 7.0.0

**Description of the problem including expected versus actual behavior**:
When using the `seq_no_primary_term` option on search requests it returns the `_seq_no` and `_primary_term`, but those fields are not present in the `IHit` models in the C# client.

**Comment by russcam** [comment]
Thanks for opening @ejsmith. I've opened https://github.com/elastic/elasticsearch-net/pull/3714 to address.

**Comment by ejsmith** [comment]
@russcam Is this in a CI build?

**Comment by russcam** [comment]
Closing this as #3714 is merged and will be in the next release
