### ISSUE TITLE
Mapping using Scalar with DateTimeOffset property is missing in the generated request

### ISSUE THREAD

**Issue by ejsmith** [elastic/elasticsearch-net#3709]
**NEST/Elasticsearch.Net version**: 7.0.0-alpha1

**Elasticsearch version**: 7.0.0

**Description of the problem including expected versus actual behavior**:
A `Scalar` mapping on a `DateTimeOffset` property like this:
```csharp
[Fact]
public async Task CanCreateScalarFieldIndex() {
    var response = await _client.CreateIndexAsync("test", i => i.Map<Employee>(m => m.Properties(p => p
        .Scalar(f => f.NextReview, f => f.Name(e => e.NextReview))
        .FieldAlias(a => a.Name(f2 => f2.NextReview).Path("next"))
    )));
    _logger.LogTraceRequest(response);
    Assert.True(response.IsValid);
}

public class Employee {
    public string Id { get; set; }
    public DateTimeOffset NextReview { get; set; }
}
```

Produces this request:
```
PUT /test
{"mappings":{"properties":{"nextReview":{"path":"next","type":"alias"}}}}
```

So it just ignored the `Scalar` mapping.

**Comment by ejsmith** [comment]
Looks like this is failing when trying to just map it as a Date field too:

```csharp
public async Task CanCreateDateFieldIndex() {
    var response = await _client.CreateIndexAsync("test", i => i.Map<Employee>(m => m.Properties(p => p
        .Date(f => f.Name(e => e.NextReview))
        .FieldAlias(a => a.Name(f2 => f2.NextReview).Path("next"))
    )));
    _logger.LogTraceRequest(response);
    Assert.True(response.IsValid);
}
```

**Comment by ejsmith** [comment]
I am guessing that there is just a problem with `DateTimeOffset` in general, but this was working in the ES5 client.

**Comment by ejsmith** [comment]
Actually, it looks like it doesn't have anything to do with DateTimeOffset. The FieldAlias is overwriting the mapping for the property instead of just adding an additional alias mapping.

**Comment by russcam** [comment]
Thanks for reporting @ejsmith. Taking a look at

**Comment by russcam** [comment]
[Looking at the docs](https://www.elastic.co/guide/en/elasticsearch/reference/7.0/alias.html), it looks like `Name` and `Path` should be the other way round in your example

```c#
private static void Main()
{
	var defaultIndex = "default_index";
	var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));

	var settings = new ConnectionSettings(pool, new InMemoryConnection())
		.DefaultIndex(defaultIndex)
		.DisableDirectStreaming()
		.PrettyJson()
		.OnRequestCompleted(callDetails =>
		{
			if (callDetails.RequestBodyInBytes != null)
			{
				Console.WriteLine(
					$"{callDetails.HttpMethod} {callDetails.Uri} \n" +
					$"{Encoding.UTF8.GetString(callDetails.RequestBodyInBytes)}");
			}
			else
			{
				Console.WriteLine($"{callDetails.HttpMethod} {callDetails.Uri}");
			}

			Console.WriteLine();

			if (callDetails.ResponseBodyInBytes != null)
			{
				Console.WriteLine($"Status: {callDetails.HttpStatusCode}\n" +
						 $"{Encoding.UTF8.GetString(callDetails.ResponseBodyInBytes)}\n" +
						 $"{new string('-', 30)}\n");
			}
			else
			{
				Console.WriteLine($"Status: {callDetails.HttpStatusCode}\n" +
						 $"{new string('-', 30)}\n");
			}
		});

	var client = new ElasticClient(settings);

	if (client.IndexExists(defaultIndex).Exists)
		client.DeleteIndex(defaultIndex);

	client.CreateIndex(defaultIndex, c => c
		.Map<Document>(mm => mm
			.AutoMap()
			.Properties(p => p
				.FieldAlias(fa => fa
					.Name("next")
					.Path(pa => pa.NextReview)
				)
			)
		)
	);
}

public class Document
{
	public DateTimeOffset NextReview { get; set; }
}
```

```json
PUT http://localhost:9200/default_index?pretty=true 
{"mappings":{"properties":{"nextReview":{"type":"date"},"next":{"path":"nextReview","type":"alias"}}}}
```

**Comment by ejsmith** [comment]
Hmm... you are right. It seems really strange to me that the `Name` can be a C# expression. I assumed that the alias name would only allow string and so I didn't realize that I had them backwards. Why would you use a C# expression to map the name of an alias?

**Comment by russcam** [comment]
I agree that it'd be more typical for an alias field to be defined with a string value, as opposed to mapping to property on a POCO `T`. The `Name` methods are inherited from the base type, [`PropertyDescriptorBase<TDescriptor, TInterface, T>`](https://github.com/elastic/elasticsearch-net/blob/bac97524847a435ef4e17eef4f73dd34468b8550/src/Nest/Mapping/Types/PropertyDescriptorBase.cs#L35-L39), so users can specify with a member expression for the given `T` or pass a `PropertyName`, which has implicit conversion from `string`.

I'm going to close this as I don't think it requires further action.
