### ISSUE TITLE
7.0.0-alpha1 NEST fails to parse buckets in TermsAggregate

### ISSUE THREAD

**Issue by 4nonym0us** [elastic/elasticsearch-net#3710]
**NEST/Elasticsearch.Net version**: 7.0.0-alpha1

**Elasticsearch version**: 7.0.0

**Description of the problem including expected versus actual behavior**:
NEST 7.0.0-alpha1 fails to parse\deserialize buckets of items, which are aggregated by terms.

Expected behavior: Aggregate buckets should be retrievable using `searchResponse.Aggregations.Terms(agg-name: string)`.

Actual behavior: The API call, mentioned above, returns list 

> (`IReadOnlyCollection<KeyedBucket<string>`), which contains only default (empty) objects.
![image](https://user-images.githubusercontent.com/2701409/56996084-30df5380-6bac-11e9-9a2b-46ff070a7427.png)

As you can see, actual response from the server has all the data, but NEST fails to read it correctly. Looks like that even aggregate dictionary (`searchResponse.Aggregations`) has invalid data.

**Steps to reproduce**:
 1. 
```csharp
var testAggregateName = "test_agg";
var searchResponse = client.Search<MyEntity>(s => s
	.Size(0)
	.Index(indexName)
	.Aggregations(q => q
		.Terms(testAggregateName, t => t
			.Field(f => f.Type)))
);

searchResponse.Aggregations.Terms(testAggregateName).Buckets.Dump();

var responseBody = Encoding.UTF8.GetString(searchResponse.ApiCall.ResponseBodyInBytes);;
JObject.Parse(responseBody)["aggregations"].ToString().Dump();

```
 2. BucketAggregate is empty:
> ![image](https://user-images.githubusercontent.com/2701409/56996337-de526700-6bac-11e9-9705-14689d097b11.png)

**Provide `DebugInformation` (if relevant)**:
```
# Request:
{"aggs":{"test_agg":{"terms":{"field":"Type"}}},"size":0}
# Response:
{
  "took" : 2,
  "timed_out" : false,
  "_shards" : {
    "total" : 3,
    "successful" : 3,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 10000,
      "relation" : "gte"
    },
    "max_score" : null,
    "hits" : [ ]
  },
  "aggregations" : {
    "lterms#test_agg" : {
      "doc_count_error_upper_bound" : 0,
      "sum_other_doc_count" : 0,
      "buckets" : [
        {
          "key" : 0,
          "doc_count" : 752550
        },
        {
          "key" : 1,
          "doc_count" : 128339
        },
        {
          "key" : 2,
          "doc_count" : 5826
        }
      ]
    }
  }
}
```

**Comment by russcam** [comment]
Thanks for opening @4nonym0us. Will need to look into

**Comment by russcam** [comment]
I can't replicate the issue

```c#
			var json = @"{
  ""took"" : 2,
  ""timed_out"" : false,
  ""_shards"" : {
    ""total"" : 3,
    ""successful"" : 3,
    ""skipped"" : 0,
    ""failed"" : 0
  },
  ""hits"" : {
    ""total"" : {
      ""value"" : 10000,
      ""relation"" : ""gte""
    },
    ""max_score"" : null,
    ""hits"" : [ ]
  },
  ""aggregations"" : {
    ""lterms#test_agg"" : {
      ""doc_count_error_upper_bound"" : 0,
      ""sum_other_doc_count"" : 0,
      ""buckets"" : [
        {
          ""key"" : 0,
          ""doc_count"" : 752550
        },
        {
          ""key"" : 1,
          ""doc_count"" : 128339
        },
        {
          ""key"" : 2,
          ""doc_count"" : 5826
        }
      ]
    }
  }
}";

			var bytes = Encoding.UTF8.GetBytes(json);

			var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
			var connectionSettings = new ConnectionSettings(pool, new InMemoryConnection(bytes));
			var client = new ElasticClient(connectionSettings);

			var searchResponse = client.Search<Project>(s => s
				.Size(0)
				.Index("issue")
				.Aggregations(q => q
					.Terms("test_agg", t => t
						.Field(f => f.Type)))
			);

			var buckets = searchResponse.Aggregations.Terms("test_agg").Buckets;
			buckets.Should().NotBeNull().And.HaveCount(3);
```

It may be that it's already fixed. I've pushed that test up to https://github.com/elastic/elasticsearch-net/tree/fix/3710

**Comment by 4nonym0us** [comment]
@russcam I can confirm that the issue is gone as my saved code snippet passes the test as well. I'm curios how the bug got silently fixed as I wasn't changing anything in the code and index settings (I wish all bugs could be resolved this way 😃)
Thanks for the reply and thanks for working on NEST – the API is pretty intuitive, flexible, allows to build complex queries easily. It's a pleasure to integrate ES using NEST.

**Comment by 4nonym0us** [comment]
Looks like I've made a mistake and was testing the GeoCentroid aggregate, which works fine.
My previous test case and your code snippet fails when i run that in linqpad. Are you also using 7.0.0-alpha1?
![image](https://user-images.githubusercontent.com/2701409/57124057-e0731c00-6d8c-11e9-83f2-511190ff359d.png)

**Comment by 4nonym0us** [comment]
@russcam 
Also, `buckets.Should().NotBeNull().And.HaveCount(3);` doesn't covers the scenario because the issue is that buckets are empty(default) and the assertion above check whenever buckets are present and not null (and this test succeeds).

**Comment by 4nonym0us** [comment]
@russcam looks like it's linqpad-related issue. For some reason `Dump()` linqpad's extension ignores KeyedBuckets in output. Have never encountered the issue yet, therefore wasn't aware it's possible at all.

**Comment by russcam** [comment]
> looks like it's linqpad-related issue.

That's a weird one, but confirm I see the same with LinqPad v5.36.03. Enumerating the buckets yields the expected values

**Comment by mccow002** [comment]
I know this is a closed issue, but I'm having the same problem, except the KeyedBuckets are actually empty.

The DebugInformation property is returning this:

``` JSON
{
	"aggregations": {
		"sterms#work_type_tag": {
			"doc_count_error_upper_bound": 0,
			"sum_other_doc_count": 0,
			"buckets": [
				{
					"key": "Value1",
					"doc_count": 36
				},
				{
					"key": "Value2",
					"doc_count": 36
				},
				{
					"key": "Value3",
					"doc_count": 30
				}
			]
		}
	}
}
```

But when I call `Console.WriteLine(JsonConvert.SerializeObject(rsp.Aggregations.Terms("work_type_tag").Buckets));`
I get this:  `[{},{},{}]`

Unlike the previous response, the bucket values are actually empty, even though the raw response isn't.

Any ideas?
