### ISSUE TITLE
build.bat fails with .Net Core 2.2.103

### ISSUE THREAD

**Issue by bittusarkar** [elastic/elasticsearch-net#3712]
**NEST/Elasticsearch.Net version**: master branch

**Elasticsearch version**: N/A

**Description of the problem including expected versus actual behavior**: Executing `build.bat` from master branch in Windows 10 with .NET Core 2.2.103 fails due to a known issue https://github.com/NuGet/Home/issues/7748. I verified that build does not fail with .Net Core 2.2.104. I can send a PR for changing the minor version if that's fine.

**Comment by russcam** [comment]
@bittusarkar Interesting. What's the error message when it fails?

**Comment by bittusarkar** [comment]
I don't have the error logs right now because I upgraded .Net Core as soon as I hit that error and found the Github issue that talked about it. The error message said `This repository indicated that all its packages are repository signed; however, this package is unsigned.` for a lot of packages. Interestingly, I just tried this on a different machine which did not have .Net Core installed ever before. I installed .Net Core 2.2.103, cloned this repository and executed `build.bat` and it worked! I'm not sure why it failed on the other machine.

**Comment by russcam** [comment]
Hmm, strange behaviour! I'm inclined to close this for now, and reopen if it's reported again. Sound OK?

**Comment by bittusarkar** [comment]
Sure, no problem.

**Comment by russcam** [comment]
Thanks @bittusarkar
