### ISSUE TITLE
ElasticSearch .NET CertificateValidations not working as expected in .net core 2.2 app

### ISSUE THREAD

**Issue by rezvanf** [elastic/elasticsearch-net#3716]
**NEST/Elasticsearch.Net version**: 6.0

**Elasticsearch version**:

Expected: Validate cert and log event
Actual: Does not validate cert and does not log event

I have an elasticsearch endpoint in my organization and it uses a test certificate issued by a test authority.

When I use the curl statement with the cert e.g.

curl http://org-elastic-endpoing --cacert "mycert.crt"
I get a 401 because I have not provided the username and password with basic authentication as expected but the ssl handshake as been establised

When I do a curl without the --cacert as expected I get "unable to get local issuer certicate" error as expected 

**Steps to reproduce**:
 1. Setup ConnectionConfiguration.ServerCertificateValidationCallback
var x509 = new X509Certificate2(mycert)
Use ConnectionConfiguration.ServerCertificationValidationCallback(CertificateValidation.AuthorityIsRoot(x509) or AuthorityPartOfChain(x509)
 
I have looked into the added the CertifcateValidations class to my project to debug I.e. https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Connection/CertificateValidations.cs

And I can the issue is related to the ChainStatus being PartialChain and therefore the method(s) returns false

I can there is this issue exists in .net core so thinking this could be the issue

https://github.com/dotnet/corefx/commit/9cc9e050df3b262d6e9d227d484c6cf0c4ccfbd2

**Comment by russcam** [comment]
Thanks for raising @rezvanf, we'll need to dig into this 👍

**Comment by stevejgordon** [comment]
Given the age of this issue and the version, I'm going to close this. We've had no further reports of certificate issues.
