### ISSUE TITLE
7.0.0-alpha1 UnexpectedElasticsearchClientException upon parsing empty geo_bounds aggregation

### ISSUE THREAD

**Issue by 4nonym0us** [elastic/elasticsearch-net#3717]
**NEST/Elasticsearch.Net version**: 7.0.0-alpha1

**Elasticsearch version**: 7.0.0

**Description of the problem including expected versus actual behavior**:
`UnexpectedElasticsearchClientException` (`"expected:'"', actual:'
', at offset:335"`) is thrown when search query returns empty GeoBounds Aggregation result (which always happens when number of hits is 0).

**Steps to reproduce**:
Complete linqpad snippet:
```csharp
void Main()
{
	var json = @"{
  ""took"" : 2,
  ""timed_out"" : false,
  ""_shards"" : {
    ""total"" : 3,
    ""successful"" : 3,
    ""skipped"" : 0,
    ""failed"" : 0
  },
  ""hits"" : {
    ""total"" : {
      ""value"" : 10000,
      ""relation"" : ""gte""
    },
    ""max_score"" : null,
    ""hits"" : [ ]
  },
  ""aggregations"" : {
    ""geo_bounds#viewport"" : { }
  }
}";

	var bytes = Encoding.UTF8.GetBytes(json);

	var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
	var connectionSettings = new ConnectionSettings(pool, new InMemoryConnection(bytes));
	var client = new ElasticClient(connectionSettings);

	var searchResponse = client.Search<TestEntity>(s => s
		.Size(0)
		.Index("issue")
		.Aggregations(q => q
			.GeoBounds("viewport", t => t
				.Field(f => f.TestProperty)))
	); // throws UnexpectedElasticsearchClientException
}

public class TestEntity {
	public string TestProperty { get; set; }
}
```

**Comment by russcam** [comment]
Thanks for opening @4nonym0us. I've opened #3722 to address

**Comment by 4nonym0us** [comment]
Thanks for such a fast response. It's a pleasure to see that Elastic actually cares and keeps so many client libraries up to date.
Feel free to close the issue w\e it's appropriate according to your guidelines.

**Comment by russcam** [comment]
Closing this as #3722 has been merged and will be in the next release
