### ISSUE TITLE
Cannot deserialize

### ISSUE THREAD

**Issue by WJdenghuo** [elastic/elasticsearch-net#3720]
**NEST/Elasticsearch.Net version**:nest 6.6.0

**Elasticsearch version**:
"version" : {
    "number" : "7.0.1",
    "build_flavor" : "default",
    "build_type" : "zip",
    "build_hash" : "e4efcb5",
    "build_date" : "2019-04-29T12:56:03.145736Z",
    "build_snapshot" : false,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.7.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"

**Description of the problem including expected versus actual behavior**:
mycode：
①no problem
       [HttpPost]
        [Route("value/index")]
        public IIndexResponse Index([FromBody]Log log)
        {
            return _client.IndexDocument(log);
        }
②
        [HttpPost]
        [Route("value/search")]
        public IReadOnlyCollection<Log> Search([FromQuery]string type)
        {
            return _client.Search<Log>(s => s
                .From(0)
                .Size(10)
                .Query(q => q.Match(m => m.Field(f => f.MachineName).Query(type)))).Documents;
        }
errormessage：
Elasticsearch.Net.UnexpectedElasticsearchClientException
  HResult=0x80131500
  Message=Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Int64' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly.
To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'hits.total.value', line 1, position 113.

**Comment by russcam** [comment]
NEST 6.x is not compatible with Elasticsearch 7.x. 

We're working on getting NEST 7.x to GA. In the meantime, you can use [7.0.0-alpha1 nuget package](https://www.nuget.org/packages/NEST/7.0.0-alpha1). If you come across issues with 7.0.0-alpha1, please open an issue. Thanks!

**Comment by fromeroc0200** [comment]
Great <a href="https://www.nuget.org/packages/NEST/7.0.0-alpha1" rel="nofollow">7.0.0-alpha1 nuget package</a> It's working with ElasticSearch 7.0.1

 public static Uri node;

        //Nest Functions
        public static ConnectionSettings settings;
        public static ElasticClient client;

        [WebMethod]
        public static ProcessResult<List<User>> LoginUser(string user, string password)
        {
            ProcessResult<List<User>> result = new ProcessResult<List<User>>();

            
            node = new Uri("http://localhost:9200");
            settings = new ConnectionSettings(node);
            client = new ElasticClient(settings);
            settings.DefaultIndex("users");
            settings.DefaultMappingFor<User>(d => d.IndexName("users"));

            var indexSettings = new IndexSettings();
            indexSettings.NumberOfReplicas = 0;
            indexSettings.NumberOfShards = 1;

            if (client.IndexExists("users").Exists)
            {
                var response = client.Search<dynamic>(c => c.Index("users"));
            }
            result.HasError = false;
            return result;
        }

I get Data
