### ISSUE TITLE
Index lifecycle management support

### ISSUE THREAD

**Issue by abrasat** [elastic/elasticsearch-net#3731]
Is the elasticsearch index lifecycle management ( [ILM](https://www.elastic.co/de/blog/implementing-hot-warm-cold-in-elasticsearch-with-index-lifecycle-management) ) feature supported by elasticsearch-net? If yes, are there any usage samples available?

**Comment by russcam** [comment]
@abrasat ILM has been implemented in 6.7.0 which will be going out very shortly.

> If yes, are there any usage samples available?

[There are integration tests for the ILM APIs](https://github.com/elastic/elasticsearch-net/blob/6.x/src/Tests/Tests/XPack/Ilm/IlmApiTests.cs), but no dedicated client documentation for them.

**Comment by abrasat** [comment]
Ok, thx. Just for my understanding, why are the ILM tests placed under \XPack ?

**Comment by russcam** [comment]
ILM is an Elastic Stack feature available under the basic license and above. This is in line with features that previously came under the name X-Pack, so ILM logically fits into this.
