### ISSUE TITLE
Sort string field problem

### ISSUE THREAD

**Issue by ruben44bac** [elastic/elasticsearch-net#3733]
I have a problem when use "sort" with a string field

this is my code

```
var sortClauses = new List<ISort>();

sortClauses.Add(new SortField { Field = "aBC", Order = SortOrder.Ascending });
```
but when I use decimal field I don´t have problems

```
var sortClauses = new List<ISort>();

sortClauses.Add(new SortField { Field = "precio", Order = SortOrder.Ascending });
```

 thanks for your help

**Comment by russcam** [comment]
Hi @ruben44bac , 

We reserve GitHub Issues for bug reports and feature requests.

In order for your question to get the attention it deserves, the best place to ask it would be the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Not only do more folks view the forums than the GitHub Issues list, and hence it is more likely to receive attention, but the forums are also geared towards being able to search previous questions and answers, making it a much more valuable archive for future question askers.

Thanks!
