### ISSUE TITLE
Stored Scripts are not serialized when requesting cluster state Metadata

### ISSUE THREAD

**Issue by cscorley** [elastic/elasticsearch-net#3746]
**NEST/Elasticsearch.Net version**:

6.5.0

**Elasticsearch version**:

6.2.4

**Describe the feature**:

Currently requesting the cluster state metadata (`client.ClusterState(s => s.Metric(ClusterStateMetric.Metadata))`) does not serialize the `stored_scripts` portion of the response. 

If I were to take a swing at implementing this, the sub field on the state response would provide something like a `Dictionary<Id, IStoredScript>`.  The (simplified) response json from the above request:

```json
{
    "metadata": {
        "stored_scripts": {
            "my-script-id": {
                "lang":"painless",
                "source":"return 1;",
                "options":{}
            },
            "my-other-script-id": {
                "lang":"painless",
                "source":"return 0;",
                "options":{}
            },
        }
    }
}

```

I also notice the response includes an `options` that isn't currently being serialized. I'm not sure what this is useful for since we don't utilize it, but it is missing (maybe intentionally?)

**Comment by codebrain** [comment]
Thanks for raising @cscorley - I have opened a PR to address this.

**Comment by cscorley** [comment]
Thank you for the quick help!

**Comment by codebrain** [comment]
Hi @cscorley - after speaking with some colleagues it is recommended that you don't rely on the cluster state metadata response - only that it is susceptible to breaking within minor versions. It is not versioned in the same manner as other endpoints.

Is there anyway you can use the script endpoints instead? https://www.elastic.co/guide/en/elasticsearch/reference/6.2/modules-scripting-using.html#modules-scripting-stored-scripts

**Comment by codebrain** [comment]
This is now available in the `6.8.0` client recently pushed to nuget https://www.nuget.org/packages/NEST/6.8.0

**Comment by cscorley** [comment]
Hi @codebrain, thanks again for your help.  Sorry for the late response, was out for a US holiday.

Indeed, we use the GET/PUT/DELETE _scripts for their respective operations.  The problem we're running into is getting an idea for what scripts are currently installed on the cluster, as there is no "ListScripts" option as far as I can tell.  I realize now that's what we should be asking for, but on the main Elasticsearch project itself!  We've been manually going through ClusterState to figure it out and parsing the response ourselves to get a list of scripts.

**Comment by codebrain** [comment]
Ah, yes, you are correct, there is no list scripts endpoint. This does seem like an oversight, let me open a ticket for you there.
