### ISSUE TITLE
Nest 7.0.0-alpha1 is not taking virtual directory name while executing queries

### ISSUE THREAD

**Issue by jaspreetchahal** [elastic/elasticsearch-net#3749]
I have elastic search hosted on IIS with url as "https://somedomain.com/VD1".
I am able to access above url in Postman and perform get put queries on it. Using Nest I am observing that queries get fired against "https://somedomain.com" instead of "https://somedomain.com/VD1".

I am trying to connect using below code
     EsNode    = new Uri("https://somedomain.com/VD1/");
     EsConfig  = new ConnectionSettings(EsNode);
     EsClient   = new ElasticClient(EsConfig);

 var resp = EsClient.CreateIndex("profile", c => c
                 .Map<SomeModel>(mp => mp )
                 .AutoMap())

error  shows uri as https://somedomain.com/profle

**Comment by russcam** [comment]
This was addressed in #3700 and is part of [NEST 7.0.0-alpha2](https://www.nuget.org/packages/NEST/7.0.0-alpha2). Would you be able to try with this and report back?

**Comment by jaspreetchahal** [comment]
Thanks @russcam , It is working in  7.0.0-alpha2.
