### ISSUE TITLE
7.0.0-alpha2 - Unable to get raw document JSON without deserializing

### ISSUE THREAD

**Issue by ejsmith** [elastic/elasticsearch-net#3751]
**NEST/Elasticsearch.Net version**: 7.0.0-alpha2

**Elasticsearch version**: 7.0.1

**Description of the problem including expected versus actual behavior**:
Trying to get the raw document JSON without deserializing. Pretty sure I'm doing it the right way. In the old client I just set the response type to `JObject`. Now I'm trying to use `StringResponse` and `BytesResponse` which looking at the code seems like it's supposed to do what I'm trying to do, but it's just returning `null`.

```csharp
[Fact]
public void CanGetRaw() {
    var client = GetClient();
    var index = CreateRandomIndex<MyType>(client);
    var response = client.IndexDocument(new MyType { Field4 = 12 });
    
    var doc = client.Get<BytesResponse>(response.Id, d => d.Index(index));
    Assert.NotNull(doc.Source.Body);
}
```

**Comment by russcam** [comment]
@ejsmith the high level client is intended to work with types that represent documents. In your example, the generic type parameter of `TDocument` is set to `BytesResponse`, which is intended to represent the _entire_ response and not just the document, so is not a correct usage of the high level API method.

In this case, if you're wanting to return just the bytes representation of the source, the low level client is what you'd want to use

```c#
var client = GetClient();
var lowLevelGetResponse = client.LowLevel.Get<BytesResponse>(index, response.Id.Id);

Assert.NotNull(lowLevelGetResponse.Body);
```
