### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by p4tooo** [elastic/elasticsearch-net#3753]
Hi,

In project I maintanent is used old Nest client verion 1.6.1.
It uses this code:
```
public Models.Order.ProductDto GetProductFromElastic(long ean)
        {
            const string documentType = "commerceproducts";
            var esQuery = new SearchDescriptor<CommerceProduct>();
            esQuery.Index("commerceprodukter_alias");
            esQuery.Type("commerceproducts");
            esQuery.From(0);
            esQuery.Sort(y => y.OnField("_score"));

            esQuery.Query(x => x.MatchAll());
            esQuery.Filter(f => f.And(new FilterDescriptor<CommerceProduct>().Terms("_type", new[] { documentType })));
            esQuery.Query(x => x.Filtered(ff => ff.Filter(f => f.Term("ean", ean))));

            var result = elasticClient.Search<CommerceProduct>(esQuery);
            return result.Hits.Any() ? OrderMapper.Map<Models.Order.ProductDto>(result.Hits.First().Source) : null;
        }
```

Is it possible, there is a memory leak? After few deys it raised to almost 2GB on local env.
In production enviroment to 17Gb.
I tried update to version 1.9.2, but it didn't help.
Also I tried to profile it with dotMemory, but I can not see nothing relevant.
How can I rewrite this query to newer version? 
There is not Filter method and OnField method on SortDescriptor in version 2.

Can you help me.

**Comment by Mpdreamz** [comment]
`Filter` is now `PostFilter` and `OnField` isnow `Field`. 

`1.x` is EOL end no longer supported, I am not aware of a memory leak but it would take a significant investigation to replicate which falls outside our EOL. 

`2.x` is not tested against `1.x` of Elasticsearch so you need to be sure you are not using removed parameters in the client. There might also be cases where a `1.x` response from Elasticsearch can not be parsed in `NEST 2.x` so thread carefully. You should be able to use the latest `NEST 2.x` though with the same caveats as the first `NEST 2.x`.

**Comment by russcam** [comment]
From memory, the `error` structure on Elasticsearch responses is quite different between 1.x and 2.x, resulting in JSON serialization exceptions at deserialization time.
