### ISSUE TITLE
AutoDateHistogramAggregation missing Buckets property

### ISSUE THREAD

**Issue by jonyadamit** [elastic/elasticsearch-net#3754]
**NEST/Elasticsearch.Net version**: 6.7.0

**Elasticsearch version**: 6.3.x (though irrelevant here)

**Description of the problem including expected versus actual behavior**:
Cannot specify buckets using `AutoDateHistogramAggregation`.
**Steps to reproduce**:
Try specifying number of buckets for `AutoDateHistogramAggregation`. 😄

**Comment by codebrain** [comment]
Thanks @jonyadamit - I have opened PR to address this.

**Comment by codebrain** [comment]
Merged and available in `6.8.0` - please check nuget.
