### ISSUE TITLE
Add additional details about using NEST with Elastic Cloud

### ISSUE THREAD

**Issue by joshjanoski** [elastic/elasticsearch-net#3756]
I found this Discuss forum post here: https://discuss.elastic.co/t/using-nest-net-client-with-elastic-cloud/144240 going over which Connection Pool setting to use with Elastic Cloud.

I think it would be beneficial to add a note with this information to the official documentation for the client here: https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/connection-pooling.html so that it is easy for Elastic Cloud users to find.

Please let me know if you have any questions regarding this request and thank you for considering it!

**Comment by codebrain** [comment]
Hi @joshjanoski, thanks for contributing, funnily enough we spoke about this exact topic last week!

We are going to be introducing explicit methods for connecting to Elastic Cloud and then introduce a connection pool named `CloudConnectionPool`, which will be a subclass of `SingleNodeConnectionPool`.

**Comment by russcam** [comment]
Closing this as [`CloudConnectionPool`](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/connection-pooling.html#cloud-connection-pool) has been implemented. I've opened #4030 to make this documentation more clear too.
