### ISSUE TITLE
[Question] How to mapping Nested Type?

### ISSUE THREAD

**Issue by phucphanJaneto** [elastic/elasticsearch-net#3769]
Hi,

How can I configure Nested Object as Property for my index?

Please see my object: 

![image](https://user-images.githubusercontent.com/37202364/58325238-50883580-7e53-11e9-8b42-1a78c5156291.png)

And here is my configuration for Elasticsearch:
![image](https://user-images.githubusercontent.com/37202364/58325272-6269d880-7e53-11e9-8436-87027cedf751.png)

And here is my code to create index:
![image](https://user-images.githubusercontent.com/37202364/58325295-71e92180-7e53-11e9-8009-b77bda3ea99b.png)

But I always get Response failed for create new index with Reason: 
![image](https://user-images.githubusercontent.com/37202364/58325346-9cd37580-7e53-11e9-8e11-1e513ae44553.png)

Do I have any error or missing in configuration?

**Comment by russcam** [comment]
Hi @phucphanJaneto , 

We reserve GitHub Issues for bug reports and feature requests.

In order for your question to get the attention it deserves, the best place to ask it would be the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Not only do more folks view the forums than the GitHub Issues list, and hence it is more likely to receive attention, but the forums are also geared towards being able to search previous questions and answers, making it a much more valuable archive for future question askers.

Feel free to add a comment to this issue with a link to the opened question on the forums.

Thanks!
