### ISSUE TITLE
7.0.0 Pre-release Myget Feed

### ISSUE THREAD

**Issue by williamdenton** [elastic/elasticsearch-net#3789]
Do you plan to start publishing pre-release builds to https://www.myget.org/gallery/elasticsearch-net for the v7 release?

I would like to start contributing to downstream projects like https://github.com/bcuff/elasticsearch-net-aws and this is much easier if a myget feed is available.

The changes made in https://github.com/elastic/elasticsearch-net/pull/3648/commits/32e2b5c02d1bd6f6b85216c095cb013c5ca3014a open up the option of using DelegatingHandlers so we can inject middleware on requests for metric and tracing (Aws XRay)

**Comment by russcam** [comment]
@williamdenton prelease builds are being pushed:

1. for successful CI builds to Appveyor: https://ci.appveyor.com/nuget/elasticsearch-net
2. for milestone prerelease builds to nuget: https://www.nuget.org/packages/NEST. For example [`7.0.0-alpha2`](https://www.nuget.org/packages/NEST/7.0.0-alpha2)

**Comment by williamdenton** [comment]
I'm blind. Thank you
