### ISSUE TITLE
Cannot deserialize the current JSON object after upgrading to the new verson with es7.1.0 and nest 6.7.0

### ISSUE THREAD

**Issue by WenRuonan** [elastic/elasticsearch-net#3791]
Below code is fine when I use the old verson for es and nest, but after upgrading, it meets below error.
code: 
var result = _client.Search<TeamProDTO>(s => s.Index(indexTeamRead).Query(q => q.MatchAll()));
error:
Elasticsearch.Net.UnexpectedElasticsearchClientException:“Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Int64' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly.
To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'hits.total.value', line 1, position 113.”

**Comment by russcam** [comment]
NEST 6.7.0 does not support Elasticsearch 7.x. For this, you will need to use a NEST 7.x version, the latest released is currently [NEST 7.0.0-alpha2](https://www.nuget.org/packages/NEST/7.0.0-alpha2), with a GA release as soon as it's ready.
