### ISSUE TITLE
Second level terms aggregation "ConsumerType" returns 0 matches. But I could get the results in Kibana. Please advise what i'm missing here.

### ISSUE THREAD

**Issue by rajarajan1985** [elastic/elasticsearch-net#3803]
My Code:
----------

   [ElasticsearchType(Name="abc-orders")]
    public class ebizOrders
    {
       public string buyflowsessionid { get; set; }
        public string buyfloworderid { get; set; }
        public string ordersubmissiontype { get; set; } 
        public string level1marketname { get; set; } 
        public int level1marketid { get; set; }
       public DateTime createdate { get; set; }
        public cls_Details details { get; set; } 
    }

    public class cls_Details
    {
        public cls_ConsumerInfo ConsumerInfo { get; set; }
    }

    public class cls_ConsumerInfo
    {
        public string ConsumerType { get; set; }
    }

var SearchResult = _connectionToEs.EsClient().Search<ebizOrders>(s => s
                .Index(searchIndex)
                .Type(searchDoc)
                .Query(q => q
                    .Bool(b => b
                        .Must(mu => mu
                            .QueryString(qr => qr
                                .Query(queryString)
                                .DefaultField("*")
                                .AnalyzeWildcard(true)
                                )
                             )
                         )
                      )
                .Aggregations(a => a
                     .DateRange("Order_Date_Ranges", date => date
                          .Field(p => p.createdate)
                          .Ranges(
                              r => r.From(fromDt).To(toDt),
                              r => r.From(fromDtPrev).To(toDtPrev),
                              r => r.From(fromDt1w).To(toDt1w),
                              r => r.From(fromDt2w).To(toDt2w)
                              )
                           .TimeZone("-04:00")
                           .Aggregations(childAggs => childAggs
                              .Terms("FullFillmentType", ff => ff.Field(p => p.ordersubmissiontype.Suffix("keyword"))
                                   .Size(5)
                                   .Aggregations(aa=>aa
                             .Terms("ConsumerType",ct=>ct.Field(p1=>p1.details.ConsumerInfo.ConsumerType.Suffix("Ctype"))
                                        .Size(5)
                                        .Aggregations(aa1 => aa1
                                            .Cardinality("UniqueOrders", uo => uo.Field(f => f.buyfloworderid.Suffix("key")))
                                            )
                                          )
                                    )
                                   )
                                 )
                         )
                     )
                );

*Json Format - This is the one I want to build in NEST.Net*
--------------------------------------------------------------------
{
  "aggs": {
    "2": {
      "date_range": {
        "field": "createdate",
        "ranges": [
          {
            "from": "now-3h-4h",
            "to": "now-4h"
          }
        ]
      },
      "aggs": {
        "5": {
          "terms": {
            "field": "ordersubmissiontype.keyword",
            "size": 5,
            "order": {
              "1": "desc"
            }
          },
          "aggs": {
            "1": {
              "cardinality": {
                "field": "buyfloworderid.keyword"
              }
            },
            "4": {
              "terms": {
                "field": "details.ConsumerInfo.ConsumerType.keyword",
                "size": 5,
                "order": {
                  "1": "desc"
                }
              },
              "aggs": {
                "1": {
                  "cardinality": {
                    "field": "buyfloworderid.keyword"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

**Comment by russcam** [comment]
Hi @rajarajan1985 , 

We reserve GitHub Issues for bug reports and feature requests.

In order for your question to get the attention it deserves, the best place to ask it would be the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Not only do more folks view the forums than the GitHub Issues list, and hence it is more likely to receive attention, but the forums are also geared towards being able to search previous questions and answers, making it a much more valuable archive for future question askers.

Feel free to add a link to the question on Discuss, once opened.

Thanks!
