### ISSUE TITLE
Treat cluster state as key value response in 7.0

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#3812]
See: https://github.com/elastic/elasticsearch/pull/38413

cluster state will be documented as `key/value` response

We should model this as such in 7.0 before we ship I reckon.

We can still ship objects to assist in the mapping but maybe not expose these directly on the response as properties that are part of the deserialization,

**Comment by codebrain** [comment]
Merged: https://github.com/elastic/elasticsearch-net/pull/3824
