### ISSUE TITLE
Huge changes to IElasticClient in NEST 7.0 beta 1, is that on purpose?

### ISSUE THREAD

**Issue by lummar** [elastic/elasticsearch-net#3816]
**NEST/Elasticsearch.Net version**:
7.0 beta 1
**Elasticsearch version**:
7.1.1
**Description of the problem including expected versus actual behavior**:
Bunches of Methods were removed from IElasticClient, e.g. Alias, IndexExists
**Steps to reproduce**:
 1. Install NEST 7.0 alpha 2 Nuget package, those methods were there.
 2. Install NEST 7.0 beta 1 Nuget package, those methods were gone.

**Provide `ConnectionSettings` (if relevant)**:
n/a
**Provide `DebugInformation` (if relevant)**:
n/a

**Comment by russcam** [comment]
@lummar I answered your question on https://github.com/elastic/elasticsearch-net/issues/3563#issuecomment-501564124

**Comment by russcam** [comment]
- `IndexExists` -> `Indices.Exists`
- `Alias` -> `Indices.BulkAlias`

**Comment by meriturva** [comment]
- `Client.Refresh(Nest.Indices.All);` -> `Client.Indices.Refresh(Nest.Indices.All);`

**Comment by lummar** [comment]
@russcam thank you very much
