### ISSUE TITLE
CreateIndex doesn't return index name

### ISSUE THREAD

**Issue by kpstolk** [elastic/elasticsearch-net#3823]
**NEST/Elasticsearch.Net version**:
6.8.0

**Elasticsearch version**:
6.8.0

**Describe the feature**:
Currently `CreateIndexAsync` returns an `ICreateIndexResponse` which includes the `ShardsAcknowledged` and `Acknowledged` properties but not the index name as returned in the json response:

```
{
  "acknowledged" : true,
  "shards_acknowledged" : true,
  "index" : "my-index-2019.06.17-000001"
}
```

This is useful when indices are created using Date Math patterns like `%3Cmy-index-%7Bnow%2Fd%7D-000001%3E` so the date doesn't has to be calculated again.

**Comment by codebrain** [comment]
PR merged, will be in next release.
