### ISSUE TITLE
Target missed in Nuget package

### ISSUE THREAD

**Issue by t00130** [elastic/elasticsearch-net#3832]
**Elasticsearch version**: 7.0.0-beta1

**Description of the problem including expected versus actual behavior**:
Nuspec file does not contain targetframework group for .NetFramework4.6.1:
`<group targetFramework=".NETFramework4.6.1" /> `
while v6.8.0 did. Is this framework supported in versión 7.0?

**Steps to reproduce**:
 1. Add Nuget package version 7.0.0-beta1 in VS 2017 in a project with target .Net Framework 4.6.1
 2. See errors because target is not included
 3.

**Comment by Mpdreamz** [comment]
Yes it will make a return with: 

#3831 

Appreciate you taking the time to report this!
