### ISSUE TITLE
Add support for dense_vector and sparse_vector field mappings

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#3836]
Relates: https://github.com/elastic/elasticsearch/pull/33022

Client should support [new field datatypes](https://github.com/mayya-sharipova/elasticsearch/blob/8383f59c97bbfe7d1e955fbdb5ba9af9cbd9e4bc/docs/reference/mapping/types.asciidoc)

* ~Rank Feature~ (see #3938)
* ~Rank Features~ (see #3938)
* Dense Vector - https://www.elastic.co/guide/en/elasticsearch/reference/7.x/dense-vector.html
* Sparse Vector - https://www.elastic.co/guide/en/elasticsearch/reference/7.x/sparse-vector.html

**Comment by russcam** [comment]
Both Sparse and Dense vector are marked as experimental, so I don't think should be implemented at this stage.

**Comment by russcam** [comment]
Split out `rank_feature`, `rank_features` and `rank_feature` query into https://github.com/elastic/elasticsearch-net/issues/3938

**Comment by PharaonHub** [comment]
Any progress milestones on dense vector mapping? Thanks.

**Comment by russcam** [comment]
Dense vector fields were marked as GA in 7.6.0 (https://github.com/elastic/elasticsearch/pull/49120) so we're good to add them to the high level client. We'll look to get them in the next release.

Sparse vector have been deprecated and will be removed so don't think we should implement these.

**Comment by Yeronimo** [comment]
Is there any new milestone or target version for the dense vector mapping in the NEST .Net client?

**Comment by nzeichner** [comment]
Joining @Yeronimo's question. Any update on this?

**Comment by stevejgordon** [comment]
Will review this as part of code-gen work.

**Comment by seschulz** [comment]
Is there any update on the support for the dense_vector type?  I see it still missing in 7.13.

**Comment by stevejgordon** [comment]
@seschulz and @Yeronimo - Apologies for the delay in getting to this item. This has now been merged and will be included in the next release (7.14.0).
