### ISSUE TITLE
Make ShouldSerializeX methods private

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#3855]
Make `ShouldSerialize(X)` methods private (e.g. on `BoolQuery`).

No longer need to be `public`

**Comment by russcam** [comment]
This is not so straightforward to do for bool query. 

Both concrete implementations of `IBoolQuery` are serialized as `IBoolQuery`, where the look up for `ShouldSerializeX` methods are on `IBoolQuery`, a public interface. These methods could be explicitly implemented on `BoolQuery` and `BoolQueryDescriptor` and not implicitly implemented. Not private, but less discoverable.

An alternative could be to implement a `QueryContainerCollection` type to use in places where `IEnumerable<QueryContainer>` is used.

**Comment by codebrain** [comment]
Closing as referenced PR was merged.
