### ISSUE TITLE
Check MemoryPool buffer size and implications on rent/return

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#3858]
* Check array pool rent/returns
* Check smaller buffer sizes
* Check buffer sizes across project
* Create an integration tests for very large request and response

**Comment by stevejgordon** [comment]
For the most part, these have been removed with the move to `System.Text.Json` in v8. We still have some use for interop with customer source serializers but it's limited. Further general work around profiling and performance will review that post v8.0 GA. I'm going to close this issue and track performance changes in a new issue at a later date.
