### ISSUE TITLE
Private property is not used for deserialization despite being decorated with a nest

### ISSUE THREAD

**Issue by StingyJack** [elastic/elasticsearch-net#3859]
**NEST/Elasticsearch.Net version**:
6.8

**Elasticsearch version**:
6.6

**Description of the problem including expected versus actual behavior**:
Deserialization to .net objects does not use private properties, even when they are marked with Nest properties. 

This is the workaround I had to put in place to be able to deserialize an `int[]` on an elasticsearch document into a string I could put into a column in an MSSQL table. 

``` cs

        //this is the value that gets saved/read from a SQL table.
        public string ProductIdsJson {get;set;}

       //this is the property I was trying to use as a convenience for development, rather than 
      //re-parsing the product id json value repeatedly
        [Nest.PropertyName("DontUseThis1")]
        [JsonIgnore]
        public List<int> ProductIds
        {
            get
            {
                if (string.IsNullOrWhiteSpace(ProductIdsJson))
                {
                    return new List<int>(); //this is what makes netwonsoft not want to fill out the property. The helper property below is how to get around that.
                }

                try
                {
                    var productIds = JsonConvert.DeserializeObject<List<int>>(ProductIdsJson);
                    return productIds;
                }
                catch (Exception e)
                {
                    throw new ArgumentException($"A list of ProductIds could not be generated from the json value '{ProductIdsJson}'", e);
                }
            }
            set
            {
                ProductIdsJson = JsonConvert.SerializeObject(value);
            }
        }

        // this is a helper property to map the es doc field
        [Number(NumberType.Integer, Name = "ProductIds")]
        [JsonProperty("ProductIds")]
        public List<int> ProductIdsSerializerHelper
        {
            get
            {
                if (ProductIds.Count == 0)
                {
                    return default(List<int>);
                }

                return ProductIds;
            }
            set
            {
                ProductIds = value;
            }
        }
```

To make newtonsoft.json v12 work to deserialize the json correctly, I can make the Helper property private, which is nice as it doesnt have to litter the property list for consumers of this class.

However Nest requires that the property be public to make this work, and that I add a property name attribute to the property already marked as [JsonIgnore] or it complains about something already named ProductId.  

Can Nest be updated to work in a way more consistent with the underlying json serializer? And also to not opt in other properties in a class when there are properties specifically marked for its serialization?

**Comment by russcam** [comment]
@StingyJack, I take it you're using the `Nest.JsonNetSerializer` nuget package?

**Comment by StingyJack** [comment]
I'm using whatever the NEST nuget package is defaulting to.

**Comment by russcam** [comment]
The default serializer in NEST is an internalized _version_ of Json.NET, which is essentially a different serializer, because all of the types are internalized and re-namespaced. This means that Json.NET attributes like ` [JsonIgnore]` don't work with it. 

You can replace

```c#
        [Nest.PropertyName("DontUseThis1")]
        [JsonIgnore]
        public List<int> ProductIds
```

with [NEST's ignore attribute](https://www.elastic.co/guide/en/elasticsearch/client/net-api/6.x/ignoring-properties.html)

```c#
        [Nest.Ignore]
        public List<int> ProductIds
```

for NEST to ignore this property.

If you were to [hook up NEST.JsonNetSerializer as the serializer](https://www.elastic.co/guide/en/elasticsearch/client/net-api/6.x/custom-serialization.html) to use for your POCOs, you can configure Json.NET to serialize them however you wish, including serializing private properties, implementing a custom `JsonConverter` for ProductIds.

**Comment by russcam** [comment]
Here's an example demonstrating the default serialization, with JsonNetSerializer

```c#
private static void Main()
{
	var pool = new SingleNodeConnectionPool(new Uri($"http://localhost:9200"));
	var settings = new ConnectionSettings(pool, new InMemoryConnection());
	var client = new ElasticClient(settings);

	Console.WriteLine(client.SourceSerializer.SerializeToString(new Document("yet another location")
	{
		Location = "location",
		AnotherLocation = "another location"
	}, SerializationFormatting.None));

	Document deserialized;
	var json = "{\"another_location\":\"location\",\"anotherLocation\":\"\another location\",\"yet_another_location\":\"yet another location\"}";

	using (var stream = client.ConnectionSettings.MemoryStreamFactory.Create(Encoding.UTF8.GetBytes(json)))
		deserialized = client.SourceSerializer.Deserialize<Document>(stream);
		
	Console.WriteLine(deserialized.ToString());

	settings = new ConnectionSettings(pool, new InMemoryConnection(), JsonNetSerializer.Default);
	client = new ElasticClient(settings);

	using (var stream = client.ConnectionSettings.MemoryStreamFactory.Create(Encoding.UTF8.GetBytes(json)))
		deserialized = client.SourceSerializer.Deserialize<Document>(stream);

	Console.WriteLine(deserialized.ToString());
}

public class Document
{
	public Document(string yetAnotherLocation)
	{
		YetAnotherLocation = yetAnotherLocation;
	}
	
	[PropertyName("another_location")]
	public string Location { get; set; }
	
	[Nest.Ignore]
	public string AnotherLocation { get; set; }
	
	[PropertyName("yet_another_location")]
	[JsonProperty("yet_another_location")]
	private string YetAnotherLocation { get; set;}

	public override string ToString()
	{
		return $"Location: {Location}. AnotherLocation: {AnotherLocation}. YetAnotherLocation {YetAnotherLocation}";
	}
}
```

yields

```
{"another_location":"location"}
Location: location. AnotherLocation: . YetAnotherLocation 
Location: location. AnotherLocation: . YetAnotherLocation yet another location
```

In the output, 

- the first line shows that `AnotherLocation` is not serialized because it is marked with `Net.IgnoreAttribute`.
- the second line shows that `YetAnotherLocation` is not deserialized by the default serializer
- the third line shows that when using `JsonNetSerializer` and marked with `JsonPropertyAttribute`, the Json.NET serializer will deserialize the property.

Hope this helps.
