### ISSUE TITLE
Could not load type "Nest.IBulkResponse" with 7.0.0-beta1 Nest client and Automapper in .Net Core 2.2

### ISSUE THREAD

**Issue by ArtVandelay101** [elastic/elasticsearch-net#3896]
NEST/Elasticsearch.Net version: 7.0.0-beta1
Elasticsearch version: 7.1.1

When I use the latest NEST client in combination with Automapper in .Net Core 2.2 I get

> Could not load type "Nest.IBulkResponse" from assembly "Nest, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d";

I don't get this error when I'm using 7.0.0-alpha1 (unfortunately tokenizer in custom analyzers seems to have issues with the alpha1)

**Comment by Mpdreamz** [comment]
I suspect one of your projects depends on `7.0.0` release. Can you verify all your projects are on `7.0.0` and not `7.0.0-beta1`

**Comment by ArtVandelay101** [comment]
Thank you, mate! A third party library was referencing the 6.8 version. Sorry for the false alarm, at least now its documented and if someone else has similar problems they might find your solution. :) Now, I'm using the 7.0 stable Version in my project and updated the third party library - everything works fine!

Cheers!
