### ISSUE TITLE
Anchored DateMath no longer serializes time zone information for local DateTime

### ISSUE THREAD

**Issue by jonyadamit** [elastic/elasticsearch-net#3899]
**NEST/Elasticsearch.Net version**:
7.0.0
**Elasticsearch version**:
7.2.0
**Description of the problem including expected versus actual behavior**:
Given the query
```
var result = client.Search<object>(s => s
                .Index("test")
                .Query(q => q
                    .DateRange(dr => dr
                        .GreaterThanOrEquals(DateTime.Now)
                        .Field("some_field"))));
```
Nest 6.8.0 generates the following query: (my local time is UTC + 3)
`{"query":{"range":{"some_field":{"gte":"2019-07-01T17:16:18.1266967+03:00"}}}}`

Nest 7.0.0 generates the following query:
`{"query":{"range":{"some_field":{"gte":"2019-07-01T17:16:18.1266967"}}}}`

As a workaround for now I guess I have to either manually convert dates to UTC or add the TimeZone property (either of which adds unnecessary complexity).

**Comment by russcam** [comment]
Thanks for opening @jonyadamit. This is a bug that has crept in with the move to Utf8Json. Will open a fix shortly.

In the meantime, the workaround would be to convert the `DateTime` instance to a date string in your application, and pass this string to `.GreaterThanOrEquals(...)`

**Comment by russcam** [comment]
I've opened https://github.com/elastic/elasticsearch-net/pull/3910 to address

**Comment by bkqc** [comment]
This is only a suggestion but wouldn't it be cleaner in the DateMath.ToMinThreeDecimalPlaces function to simply change the actual "" format to "yyyy-MM-ddTHH:mm:ss.fffffffK" or we we really need to keep the string shorter, get the timezone string in a second call to .ToString(" K").Substring(1) and concatenate instead of reimplementing the TZ logic?
