### ISSUE TITLE
Setting 'include_type_name' not included for IndexExistsDescriptor

### ISSUE THREAD

**Issue by ngbrown** [elastic/elasticsearch-net#3901]
**NEST/Elasticsearch.Net version**:
Both 6.8.0 and 7.0.0

**Elasticsearch version**:
6.8.1

**Description of the problem including expected versus actual behavior**:
In my .net application I check if indexes exist, and if not, then create them.  Against Elasticsearch 6.8.1, I am getting a deprecation warning:

> Elasticsearch reported depecation 299 Elasticsearch-6.8.1-1fad4e1 "[types removal] The parameter include_type_name should be explicitly specified in get indices requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', which means responses will omit the type name in mapping definitions." for request HEAD http://localhost:9200/datapump-index-status?pretty=true

**Steps to reproduce**:

From this code:

```cs
IExistsResponse indexExistsResponse = await this.elasticClient
    .IndexExistsAsync(indexName, null, cancellationToken)
    .ConfigureAwait(false);
```

**Workaround**

I added the following extension:
```cs
    public static class RequestParametersExtensions
    {
        public static void SetIncludeTypeName<TParameters>(IRequest<TParameters> request, bool? value)
            where TParameters : IRequestParameters, new()
        {
            request.RequestParameters.SetQueryString("include_type_name", value);
        }

        public static IndexExistsDescriptor IncludeTypeName(this IndexExistsDescriptor request, bool? value = true)
        {
            SetIncludeTypeName(request, value);
            return request;
        }
    }
```

and then modified the index exists call to add `s => s.IncludeTypeName(false)`:

```cs
IExistsResponse indexExistsResponse = await this.elasticClient
    .IndexExistsAsync(indexName, s => s.IncludeTypeName(false), cancellationToken)
    .ConfigureAwait(false);
```

While this client code is 6.8.0, the `IncludeTypeName` doesn't exist on `IndexExistsDescriptor` in 7.0.0 either.

**Feature Request**

The request is to add `IncludeTypeName` to the `IndexExistsDescriptor` like it is on some of the other Descriptors.

**Comment by russcam** [comment]
It looks like the REST API spec for 6.8 does not include `include_type_name` for index exists:

https://github.com/elastic/elasticsearch/blob/12632795cdeb57a9092da4a0508f58424c5d7fc6/rest-api-spec/src/main/resources/rest-api-spec/api/indices.exists.json

The parameters available in the .NET clients are generated from this REST API spec. I've opened https://github.com/elastic/elasticsearch/issues/43905 to discuss having this parameter added.

**Comment by russcam** [comment]
@ngbrown I'm going to close this as it will be addressed in a later release of Elasticsearch and fixed in the client by pulling in a newer version of the rest api spec. The workaround for now is to include the parameter as you have done.
