### ISSUE TITLE
NEST 7.0.0 The IndexManyExtensions.IndexMany<T> method doesn't work with ElasticSearch 6.x

### ISSUE THREAD

**Issue by volj1** [elastic/elasticsearch-net#3902]
**NEST/Elasticsearch.Net version**: 7.0.0

**Elasticsearch version**: 6.7.1

**Description of the problem including expected versus actual behavior**:
The IndexManyExtensions.IndexMany<T> method doesn't work with ElasticSearch 6.x. With ElasticSearch 7.2 this method works well.

**Steps to reproduce**:
```
static void Main(string[] args)
{
            var client = new ElasticClient(new Uri(connectionString));

            var data = new List<TestClass>
            {
                new TestClass {F1 = "aaa", F2 = "bbb"},
                new TestClass {F1 = "ccc", F2 = "ddd"},
                new TestClass {F1 = "eee", F2 = "fff"}
            };

            var res = client.IndexMany<TestClass>(data, "testindex");
}
    public class TestClass
    {
        public string F1 { get; set; }
        public string F2 { get; set; }
    }
```

**Provide `DebugInformation` (if relevant)**:
ServerError: Type: action_request_validation_exception Reason: "Validation Failed: 1: type is missing;2: type is missing;3: type is missing;"

# Request:
{"index":{"_id":null}}
{"f1":"aaa","f2":"bbb"}
{"index":{"_id":null}}
{"f1":"ccc","f2":"ddd"}
{"index":{"_id":null}}
{"f1":"eee","f2":"fff"}

**Comment by russcam** [comment]
> NEST/Elasticsearch.Net version: 7.0.0
> Elasticsearch version: 6.7.1

[NEST 7.x is not compatible with Elasticsearch 6.x](https://github.com/elastic/elasticsearch-net#compatibility-matrix); please use the latest NEST 6.x, which will also send `_type` information,
