### ISSUE TITLE
TypeMappingDescriptor<T> still supports setting AllField

### ISSUE THREAD

**Issue by sladeos** [elastic/elasticsearch-net#3905]
**NEST/Elasticsearch.Net version**:
7.0.0/7.0.0

**Elasticsearch version**:
7.2.0

**Description of the problem including expected versus actual behavior**:
TypeMappingDescriptor<T> still has the AllField method even though using it results in a 400 when creating an index. The method should maybe have been marked Obsolete in the 6.X version and removed in 7.X.
**Steps to reproduce**:
 1. Define a CreateIndexDescriptor and in the Map section set AllField to disabled
 2. Attempt to create the index.

```
            var testDescriptor = new CreateIndexDescriptor("test")
                .Map(m => m
                    .AllField(af => af.Enabled(false))
                    .AutoMap());
            var result = this.client.Indices.Create(testDescriptor);

```

**Provide `DebugInformation` (if relevant)**:
Root mapping definition has unsupported parameters:  [_all : {enabled=false}]

**Comment by russcam** [comment]
Thanks for reporting @sladeos; this should have been removed for 7.x 😢 

Will mark as `[Obsolete()]`.

**Comment by russcam** [comment]
I've opened https://github.com/elastic/elasticsearch-net/pull/3918 to address
