### ISSUE TITLE
Version 7.0.0 not working with os httphandlers

### ISSUE THREAD

**Issue by lukapor** [elastic/elasticsearch-net#3907]
If I am using 
  AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
with version 7.0.0 at least Indices api Exists doesnt work correctly. if I am using 7.0.0-beta1 everything is ok.

Here is code to reproduce
static void Main(string[] args)
{
    AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);
    var defaultIndex = "nonexist_index";
    var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9210"));

    var settings = new ConnectionSettings(pool)
        .DefaultIndex(defaultIndex)
        .DisableDirectStreaming()
        .PrettyJson();

    var client = new ElasticClient(settings);

    var response = client.Indices.Exists(defaultIndex);
    if (response.ApiCall.HttpStatusCode != (int)HttpStatusCode.NotFound)
       throw new Exception("Should be 404 status code.");
}

**Comment by russcam** [comment]
Thanks for opening @lukapor, we'll need to investigate.

**Comment by russcam** [comment]
I can replicate an issue. The HttpStatusCode is `null` in this scenario, and an exception has been thrown, which can be viewed on `response.OriginalException`

```
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: Error 87 calling WinHttpSendRequest, 'The parameter is incorrect'.
   at System.Net.Http.WinHttpException.ThrowExceptionUsingLastError(String nameOfCalledFunction)
   at System.Net.Http.WinHttpHandler.InternalSendRequestAsync(WinHttpRequestState state)
   at System.Net.Http.WinHttpHandler.StartRequest(WinHttpRequestState state)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData)
```

This occurs when making the request, and before a HTTP request is actually sent.

**Comment by russcam** [comment]
My initial suspicion here is that this relates to the introduction of `RequestDataContent` in https://github.com/elastic/elasticsearch-net/commit/a525ac8fa5bbac0f387cc14c2689d137d517b893, which is used instead of `StreamContent`.

/cc @Mpdreamz

**Comment by russcam** [comment]
opened #3925 to address

**Comment by russcam** [comment]
This will be fixed in the next release
