### ISSUE TITLE
Documentation: Mapping an Index name for a .NET type code samples

### ISSUE THREAD

**Issue by Trisped** [elastic/elasticsearch-net#3914]
**NEST/Elasticsearch.Net version**: 6.0

**Elasticsearch version**: 6.0

**Description of the problem including expected versus actual behavior**:
[Mapping an Index name for a .NET type](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/index-name-inference.html#index-name-type-mapping) needs some work.

The first code sample is the same as the second sample and does not exemplify MapDefaultTypeIndices as indicated by the line describing what should be in the example.

At the time of this writing, the current documentation was version 6.0
**Steps to reproduce**:
 1. Go to https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/index-name-inference.html#index-name-type-mapping
 2. Compare the first two code blocks.

**Comment by russcam** [comment]
@Trisped thanks for your reporting. Would you be interested in contributing a PR to rectify? I can go through what would need to be done.

**Comment by Trisped** [comment]
@russcam Not really.  I am not familiar with the process of making PRs on GitHub and do not have time to make the changes.
