### ISSUE TITLE
Intellisense Documentation Links

### ISSUE THREAD

**Issue by Trisped** [elastic/elasticsearch-net#3915]
**NEST/Elasticsearch.Net version**: 6.7.0

**Description of the problem including expected versus actual behavior**:
I have run into a few places in the intelisense documenation (C#) where the links are broken. For example, the DeleteIndexAsync method on Nest.ElasticClient states:

> The delete index API allows to delete an existing index.
> [http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-delete-index.html](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/indices-delete-index.html)
> 

The link will work if you replace http://www.elasticsearch.org with https://www.elastic.co. 
 Someone will need to make this change to all instances in the documentation.

**Comment by codebrain** [comment]
Addressed in https://github.com/elastic/elasticsearch/pull/44487

**Comment by russcam** [comment]
Removing v6.8.1,v7.2.0 and adding v7.4.0, as the upstream fix will be applied to v7.4.0

**Comment by Trisped** [comment]
@russcam Does this mean that the intelisense documenation will only be updated from version 7.4 forward?  Is it possible to get the older versions updated also?  I expect the older versions will be available for a long time so it will have a large impact.

**Comment by russcam** [comment]
@Trisped I've asked the question on the upstream change. Typically, a change would be backported to a previous major only if there were to be a new release e.g. a new 6.x version. This change probably would not warrant a release of Elasticsearch, but is useful for the client libraries. Another approach that could be proposed is reinstating the redirects from `http://www.elasticsearch.org` to `https://www.elastic.co`

**Comment by Trisped** [comment]
@russcam New releases are preferable, but I understand not doing it since it will be a lot of work to re-release each version.  The redirect would be a good work around as long as we are sure we did not miss any of the addresses changes.

**Comment by russcam** [comment]
I've opened https://github.com/elastic/elasticsearch-net/pull/4220 to address the final bits in the 7.x client.
