### ISSUE TITLE
JsonSerializerSettings not honored for Field Expressions

### ISSUE THREAD

**Issue by kpstolk** [elastic/elasticsearch-net#3926]
**NEST/Elasticsearch.Net version**:
7.0.1

**NEST.JsonNetSerializer version**:
7.0.1

**Elasticsearch version**:
7.2.0

**Description of the problem including expected versus actual behavior**:
Expected: be able to query on a field using an `Expression` lambda which should honor the `[JsonProperty]` attributes when configured using `JsonSerializerSettings` just like in NEST 6.8.0.

Actual: No query results are returned.

**Steps to reproduce**:
 1. `DELETE my-index`
 2. Index a document and query it using a date range filter:

```csharp
var pool = new SingleNodeConnectionPool(new Uri("https://localhost.fiddler:9200"));
var settings = new ConnectionSettings(pool, (serializer, connectionSettings)
        => new JsonNetSerializer(serializer, connectionSettings))
    .BasicAuthentication("elastic", "elastic");
var client = new ElasticClient(settings);
var doc = new DocumentModel { Timestamp = DateTime.UtcNow, DocumentName = "Doc 1" };

await client.IndexAsync(doc, descriptor => descriptor
    .Index("my-index")
    .Refresh(Refresh.True)
);

var countResponse = await client.CountAsync<DocumentModel>(descriptor => descriptor
    .Index("my-index")
);
long totalDocs = countResponse.Count; // totalDocs = 1

var searchResponse = await client.SearchAsync<DocumentModel>(descriptor => descriptor
    .Index("my-index")
    .Query(q => q
        .DateRange(range => range
            .Field(model => model.Timestamp)
            .GreaterThan("1970-01-01"))
    )
);
int count = searchResponse.Documents.Count; // count = 0
```
The poco model:

```csharp
public class DocumentModel
{
    [JsonProperty("@timestamp")]
    public DateTime Timestamp { get; set; }

    [JsonProperty("document_name")]
    public string DocumentName { get; set; }
}
```

 3. Notice that the date range filter uses the lowercased `Timestamp` property name, not `@timestamp` from the `[JsonProperty]` attribute:

```
POST https://localhost:9200/my-index/_search?typed_keys=true HTTP/1.1
Accept: application/json
Content-Type: application/json
User-Agent: elasticsearch-net/7.0.1 (Microsoft Windows 10.0.17134; .NET Framework 4.7.3416.0; Nest)
Authorization: Basic ZWxhc3RpYzplbGFzdGlj
Host: localhost:9200
Content-Length: 53

{"query":{"range":{"timestamp":{"gt":"1970-01-01"}}}}
```

**Comment by kpstolk** [comment]
Also the [documentation for 7.x](https://www.elastic.co/guide/en/elasticsearch/client/net-api/7.x/custom-serialization.html#_jsonnetserializer) seems not updated yet?
It still mentions Newtonsoft Json which is removed completely now?

**Comment by russcam** [comment]
@kpstolk You are correct, this needs to be updated

**Comment by russcam** [comment]
Opened https://github.com/elastic/elasticsearch-net/pull/3942 to address
