### ISSUE TITLE
Feature Request for DataFrame in Elasticsearch

### ISSUE THREAD

**Issue by Tak1za** [elastic/elasticsearch-net#3928]
**Describe the feature**:
With Elasticsearch 7.x, DataFrames were added into Elasticsearch X-Pack.
The current .NET Client does not support it.
It could be a valuable addition to the client.

DataFrames: https://www.elastic.co/guide/en/elasticsearch/reference/current/data-frame-apis.html

**Comment by russcam** [comment]
Thanks for opening @varungupta2015135. Dataframes APIs are beta in Elasticsearch 7.2.0, so will be implemented in a later client release

**Comment by codebrain** [comment]
Removing `7.2.0` label. If we do implement before being classified `stable` then it'll be in at least a few minor versions from now.

**Comment by codebrain** [comment]
DataFrames (now called Transform) is currently slated for stable release in `7.7.0`, so will be added to the client at this point.

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Please let us know if this issue is still a relevant priority for your usage? Will also be reviewed during code-gen work.
