### ISSUE TITLE
ConnectionSettings DefaultMappingFor doesn’t support base class mapping anymore

### ISSUE THREAD

**Issue by sladeos** [elastic/elasticsearch-net#3929]
**NEST/Elasticsearch.Net version**:
7.0.0/7.0.0
**Elasticsearch version**:
7.2.0

**Description of the problem including expected versus actual behavior**:
After upgrading to NEST 7 I noticed that properties which were ignored in 6.4.2 were no longer ignored. I'm not sure that the it was supposed to work in the first place though.
I've looking though the breaking changes for 7.0 but didn't see anything about this.

If you have a class Status:

```
public class Status
{
   public string Name { get; set; }
   public string Description { get; set; }
   public string Severity { get; set; }
}
```
and various sub classes for different objects:

```
public class OrderStatus : Status
{
}

public class EnquiryStatus : Status
{
}
```
in 6.4.2 (possibly higher version not tested) one could ignore all status implementations by just configuring the mapping for the base class:

```
var settings = new ConnectionSettings(pool, connection)
                    .DefaultMappingFor<StatusType>(s => s
                        .Ignore(i => i.Description)
                        .Ignore(i => i.Severity));
```
but now it seems one must define a mapping for each implementation.
Is there a way to make it work like it did before or must each implementation be defined?

**Comment by russcam** [comment]
Thanks for opening @sladeos, will need to dig into.

**Comment by russcam** [comment]
This is a change in how reflected properties are enumerated in 7.0.0 when building a serialization component for a given type.

In 6.x, the reflection of properties and building of a serialization component is part of the internalized Json.NET library. In 7.x, it is a modified version of what existed in Utf8Json, the serialization library that replaced the internalized Json.NET library. Json.NET jumps through many additional hoops when reflecting over properties which the Utf8Json implementation doesn't. The workaround for now is to map the derived types in addition.

@Mpdreamz @codebrain something to discuss.

**Comment by elangelo** [comment]
We are currently experiencing the same issue. We started on version 7.5 (which was working fine). We just upgraded from version 7.9.0 to 7.10.0 and the problem reoccurs.

**Comment by stevejgordon** [comment]
Closing due to complexity. Please let us know if this issue is still a relevant priority for your usage?
