### ISSUE TITLE
What is the NEST equivalent to `Newtonsoft.Json.JsonProperty`' s handling for setting null values ?

### ISSUE THREAD

**Issue by StingyJack** [elastic/elasticsearch-net#3930]
Specifically we are looking to have something like 
``` csharp
public class Document 
{
  public Guid DocId {get;set;}
   [JsonProperty(NullValueHandling = NullValueHandling.Include)]
   public DateTime? EffectiveDate {get;set;}
//  etc...
}
```
in order to be able to change the EffectiveDate on a document from some non-null value to a null value.  It seems that NEST is ignoring the request to set the value to null.  How can we set the value to null?

**Comment by russcam** [comment]
NEST does not support sending null values by default. There are a few reasons for this:

1. null values when indexing a document are superfluous. They will be persisted in the document store but they won't be indexed in the inverted index and can't be searched on.
2. a JSON formatter/converter may be generated for the POCO. The generated formatters are optimized for performance, so may not contain branching paths for null values or other features like indentation
3. There's no way when a POCO is used, to indicate that attributes apply under certain contexts only e.g. send null values when updating, but not when indexing.

this means that the following doesn't work, as you've found

```c#
var updateResponse = client.Update<Document, object>(3, u => u
	.Doc(new { EffectiveDate = (DateTime?)null })
);
```

which ends up sending

```json
POST http://localhost:9200/posts/_update/3?pretty=true 
{"doc":{}}
```

Having said this, I appreciate that updating a document to remove a field value is completely valid use case where sending a null value is useful. A few approaches

1. Index the document, without the field with the Index API. Indexing overwrites the existing document with the same ID. This does require you to have the values of all the other fields that you want to retain however.

2. Use the Update API with scripting, to remove the field from _source

```c#
var updateResponse = client.Update<Document, object>(3, u => u
	.Script(s => s
		.Source("ctx._source.remove('effectiveDate')")
	)
);
```

3. Use the low level Update API to send a JSON string with null value

```c#
var updateResponse = client.LowLevel.Update<UpdateResponse<Document>>(
	"index_name", 
	"doc_id", 
	"{\"doc\":{\"effectiveDate\":null}}"
);
```

4. Configure Json.NET as the serializer to use for your documents, [by referencing `NEST.JsonNetSerializer` nuget package and configuring it](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html#_jsonnetserializer), then using Json.NET serializer settings

```c#
var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
var settings = new ConnectionSettings(pool, JsonNetSerializer.Default);
var client = new ElasticClient(settings);

var updateResponse = client.Update<Document, object>(3, u => u
	.Doc(new { EffectiveDate = (DateTime?)null })
);
```
