### ISSUE TITLE
ToString() overrides that use DebuggerDisplay string value

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#3935]
I was just trying to output my log messages with what indices would be removed and found this scenario not very idomatic. 

`_logger.LogInformation("Removing {@Indexes} Indexes", indexes);` returned `Removing Nest.Indices Indexes`

I was going to do a PR for this but then saw there is a ton of `DebuggerDisplay` properties across the codebase. Is there any reason for not overriding ToString() here to provide nice logging/exporting data. Would be nice if `Indices.Parse` and ToString() worked together :).

**Comment by niemyjski** [comment]
I should point out that it's not easy to get the string representation because debugger display is also private, my log message now becomes:
```cs
_logger.LogInformation("Removing {@Indexes} Indexes", String.Join(",", indexes.ToType<IndexName[]>().Select(i => i.Name)));
```

 and it doesn't account for `_all`

**Comment by Mpdreamz** [comment]
Thanks @niemyjski opened https://github.com/elastic/elasticsearch-net/pull/4002 to adress this.

**Comment by codebrain** [comment]
Closing as referenced PR was merged.
