### ISSUE TITLE
NEST don't apply attribute mapping

### ISSUE THREAD

**Issue by dsonjohn** [elastic/elasticsearch-net#3956]
Hi,
I use nest 7.0.0 and asp.net core 2.2. i want to create indxe from poco class. in elasticsearch index create but without any mapping. create index method is :

`public async Task CreateIndex()`
`{`
   `try`
       `{`     
           `  var getIndexResponse =await ElasticClient.Indices.GetAsync("myindex");` 
              `if (getIndexResponse.Indices == null || !getIndexResponse.Indices.Any())`
                `{`
                     `var createIndexResponse = await ElasticClient.Indices.CreateAsync("myindex", c => c`
                                   ` .Map(p => p.AutoMap<MyModel>()));`                                    
                 `}`                              
         `}`                                        
       `catch (Exception)`     
            `{`
            `}`
 ` }`
            
and MyModel is like this:

`[ElasticsearchType(IdProperty = nameof(Id), RelationName = "MyModelMessage")]`
    `public class MyModel` 
    `{`    
        `[Number(NumberType.Long, Index = true, DocValues = false)]`
        `public long UserId { get; set; }`      
        `[Date(Index = true)]`
        `public DateTime CreatedAt { get; set; }`
        `[Text(Index = false)]`
        `public string ObjectName { get; set; }`
        `[Date(Index = true)]`
        `public DateTime UpdateAt { get; set; }`
      `}`

**Comment by russcam** [comment]
Hi @dsonjohn , 

We reserve GitHub Issues for bug reports and feature requests.

In order for your question to get the attention it deserves, the best place to ask it would be the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Not only do more folks view the forums than the GitHub Issues list, and hence it is more likely to receive attention, but the forums are also geared towards being able to search previous questions and answers, making it a much more valuable archive for future question askers.

Thanks!

**Comment by dsonjohn** [comment]
Ok thanks @russcam
