### ISSUE TITLE
Consider to downgrade system.buffer reference to 4.3 version

### ISSUE THREAD

**Issue by alkampfergit** [elastic/elasticsearch-net#3959]
**NEST/Elasticsearch.Net version 7.x**:

*When I reference version 7 of nuget package from a full framework solution, it has a reference to system.buffers 4.5 that is not available for full framework. This will copy lots of netstandard dll in my bin folder and break some of my code.*:

**Steps to reproduce**:
 1. Create a full framework console application
 2. Reference Nest 7.x nuget package
 3. Build solution
4. Your output folder contains 104 dll from .netstandard ....

![image](https://user-images.githubusercontent.com/358545/61381609-98539800-a8ab-11e9-8d55-cb0ee7b380cc.png)

**Comment by russcam** [comment]
> This will copy lots of netstandard dll in my bin folder and break some of my code.:

Can you elaborate on "breaks some of my code"? A small but complete reproducible example would help. Some additional detail about full framework version used would also help.

**Comment by alkampfergit** [comment]
I have no repro to share (project of a customer), but I have filed an issue on original System. Buffers https://github.com/dotnet/corefx/issues/37639 to have the library generates a full fw dll in the next version.
Look also to https://github.com/dotnet/corefx/issues/39362

**Comment by russcam** [comment]
Thanks for the additional info, @alkampfergit.

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Please let us know if this issue is still a relevant priority for your usage?
