### ISSUE TITLE
[NEST] Extend aggregations container with custom (non built-in) aggregations

### ISSUE THREAD

**Issue by 4nonym0us** [elastic/elasticsearch-net#3960]
This feature request is about creating an API to request custom aggregations using HighLevelClient. AFAIK (please, correct me if I'm wrong), the only way to write a query to request custom aggregation is to use LowLevelClient, which is a bad idea for complex and advanced queries.

The use case is simple – there are a lot of plugins, which cover features, unavailable in default elasticsearch configuration (i.e. https://github.com/opendatasoft/elasticsearch-aggregation-envelope) by implementing a custom aggregations. It would be pretty convenient if there were an option to extend pre-defined aggregations container with a custom aggregation (which probably should be inherited from AggregationBase and implement corresponding interfaces; it should also define all the necessary properties\attributes for mapping), which would translate into following:
```json
{
  "aggregations": {
    "<aggregation_name>": {
      "<aggregation_kind>": {
        "field": "<field_name>",
        "<another_option_name>": "<another_option_value>"
      }
    }
  }
}
```

**Comment by russcam** [comment]
This is hard to do in a generic fashion. There's not only serialization of the request to handle, but also deserialization of the response, which is fairly [manual for aggregations](https://github.com/elastic/elasticsearch-net/blob/5d85c87640d741e605f135466bca1dc6d6870b9f/src/Nest/Aggregations/AggregateFormatter.cs), unless `typed_keys` is specified in the request.

The hard part is exposing serialization internals in a fashion that allows a user to manipulate only a subset, without affecting other parts. Then, in doing this, serialization library specifics will likely be exposed in the public API, which we wouldn't want to do.

**Comment by 4nonym0us** [comment]
Thanks for linking AggregateFormatter. As far as I see, it heavily depends on JsonReader and I agree that there is no way to make the Formatter, in it's current state, extendable without making JsonReader accessible for everyone (which is definitely a bad idea).
I wonder if the Formatter, linked above, takes care of both "generic"- and "typed_keys"-aggregations? If it handles only "generic" responses, It would be possible just to make this feature request require a `typed_keys` option enabled (AFAIK, it's enabled by-default anyway).

**Comment by 4nonym0us** [comment]
Closing as duplicate of #1016

**Comment by russcam** [comment]
> If there is no decent way to do a generic aggregation handling, is there a way to convert SearchDescriptor<T> to PostData or other options to modify a NEST request before sending (to benefit from NEST query-building API and to be able to add non-NEST API as well)?

You can serialize a `SearchDescriptor<T>` to JSON with the `client.RequestResponseSerializer`, then modify that by parsing into a generic JSON structure like `JObject` of [`JsonDocument`](https://docs.microsoft.com/en-us/dotnet/api/system.text.json.jsondocument?view=netcore-3.0), which would allow you to leverage NEST for endpoints and properties it supports, and augment for those it doesn't.

**Comment by 4nonym0us** [comment]
That's exactly a feature I wanted NEST to have but, unluckily, I couldn't find a way to do such a conversion in documentation. Thanks a lot for the help!
