### ISSUE TITLE
Bitnami image does not work without DisablePing

### ISSUE THREAD

**Issue by draganjovanovic1** [elastic/elasticsearch-net#3970]
**NEST/Elasticsearch.Net version**:

`7.1`

**Elasticsearch version**:

`7.0.0`

**Description of the problem including expected versus actual behavior**:

The problem exists when Elasticsearch endpoint is not exposed on the host root path `/` but under `/elasticsearch` like on Bitnami ELK image.

Invoking any client method, like `client.Indices.Exists`, throws an exception `Failed to ping the specified node.. Call: Status code 200 from HEAD /`. Beside status code `200` response mime type is `text/html` which indicated that client tries to ping host without path included and gets Bitnami default landing page.

By debugging through ELK http logs assumption was confirmed. GET call was fired to `http://HOST` instead of `http://HOST/elasticsearch/` as configured. 

**Steps to reproduce**:
 1. Bootstrap Bitnami ELK image
 2. Instantiate client w/o calling `DisablePing` method
 3. Call `client.Indices.Exists` method for any index (existing or non-existing)

*** Workaround ***

Call `DisablePing` on the client instance before any Api Call.

**Comment by russcam** [comment]
Thanks for opening @draganjovanovic1, investigating

**Comment by russcam** [comment]
I've opened #3975 to address
