### ISSUE TITLE
Indices.Exists fails in FULL .NET framework, works in .NET Core

### ISSUE THREAD

**Issue by HakanL** [elastic/elasticsearch-net#3971]
**NEST/Elasticsearch.Net version**: 7.1.0 (master)

**Elasticsearch version**: 7.2.0

**Description of the problem including expected versus actual behavior**: Call to client.Indices.Exists(indexName) throws exception (if enabled in config settings) or sets IsValid = false when run on full .Net framework (tested on 4.7.1). It works correctly on .Net Core.

**Steps to reproduce**:
 1. Create new ElasticClient, connect to 7.2.0 node (only version tested)
 2. Use .NET Framework 4.7.1 (only version tested so far)
 3. Call client.Indices.Exists(indexName) with indexName either existing or not, doesn't matter
 4. Throws exception

The issue is that in full .Net framework, using HttpWebRequest, the mimeType in the response for the above API call will be set to "" (blank string). In .NET Core it's set to null. In the Transport Pipeline (https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Transport/Pipeline/ResponseBuilder.cs#L70) there is a check if mimeType is null which in the full .NET Framework will mark the request as unsuccessful.
I believe the correct way would be to use string.IsNullOrEmpty instead of the null check.

**Comment by russcam** [comment]
Closing this as #3972 is now merged into master and 7.x. Thanks for reporting and PR, @HakanL 👍
