### ISSUE TITLE
Expecting to have a collection of objects with sql query requests

### ISSUE THREAD

**Issue by Nastya-Scherbakova** [elastic/elasticsearch-net#4000]
**Describe the feature**: When working with query I want to have opportunity to expect an exact typed object or collection of objects.

Currently I'm doing this with the reflection: 
```
            var res = new List<T>();
            var q = new QuerySqlRequest()
            {
                Query = req,
                Format = "json"
            };
            var resp = await _elasticClient.Sql.QueryAsync(q);
            var type = typeof(T);
            for (int i = 0; i < resp.Rows.Count; i++)
            {
                var newObj = new T();
                for (int j = 0; j < resp.Columns.Count; j++)
                {
                    var defaultCol = resp.Columns.ElementAt(j).Name;
                    var column = defaultCol.Substring(0, 1).ToUpper()[0] + defaultCol.Substring(1);
                    if (type.GetProperties().Any(el => el.Name == column))
                    {
                        type.GetProperty(column).SetValue(newObj, resp.Rows.ElementAt(j).ElementAt(i));
                    }
                }
                res.Add(newObj);
            }
            return res as List<T>;
```

**Comment by codebrain** [comment]
Hi @Nastya-Scherbakova, thank you for raising this issue.

You are right in detailing that this API returns a collection of columns and rows (https://github.com/elastic/elasticsearch-net/blob/7.x/src/Nest/XPack/Sql/QuerySql/QuerySqlResponse.cs)

...this is as per the API endpoint: https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-rest-format.html#_json

Your approach to use reflection to set properties on a new instance seems reasonable.

We could consider implementing some kind of helper method in NEST to achieve the same outcome - although I suspect it may be tricky to cater for all cases.

Thoughts @Mpdreamz @russcam ?

**Comment by russcam** [comment]
Another option over using reflection would be to:

1. Use the translate SQL API to get the respective Elasticsearch query DSL for a SQL query, using the low level client
2. Execute the query using the low level client, returning the response as a high level `SearchResponse<T>`, where T is your document type.

For example

```c#
var client = new ElasticClient();

// use high level translate SQL request type
var request = new TranslateSqlRequest
{
	Query  = "SELECT title, score from posts where type = 'Question' order by score DESC LIMIT 10"
};

var sqlResponse = client.LowLevel.Sql.Translate<StringResponse>(PostData.Serializable(request));
var queryDsl = sqlResponse.Body;
var searchResponse = client.LowLevel.Search<SearchResponse<Question>>("posts", queryDsl);

foreach (var hit in searchResponse.Hits)
{
	var question = hit.Source;
	
	// returned as doc value field
	var score = hit.Fields.ValueOf<Question, int>(f => f.Score);
	
	Console.WriteLine($"{question.Title}: {score}");
}
```

which yields

```
Why is it faster to process a sorted array than an unsorted array?: 23057
How do I undo the most recent local commits in Git?: 19640
How do I delete a Git branch locally and remotely?: 15249
What is the difference between 'git pull' and 'git fetch'?: 11008
What is the correct JSON content type?: 9701
What does the "yield" keyword do?: 9246
What is the "-->" operator in C++?: 8305
How to undo 'git add' before commit?: 8144
How do I redirect to another webpage?: 7729
How to modify existing, unpushed commit messages?: 7673
```

Note, some fields may come from [source filtering, whilst others may be doc value fields in the translated SQL request](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/returned-fields.html).

**Comment by codebrain** [comment]
With the above, you would only need to translate the query once, and then re-use the translated version multiple times.

Interesting approach!

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Please let us know if this issue is still a relevant priority for your usage?
