### ISSUE TITLE
Ability to easily add a FieldAlias for the current property mapping

### ISSUE THREAD

**Issue by ejsmith** [elastic/elasticsearch-net#4034]
I would love to figure out how to easily create a FieldAlias for the current property that I'm mapping. Something like this:

```csharp
map.Properties(p => p
  .Keyword(f => f.Name(u => u.SomeProperty).Alias("some")));
```

instead of this:

```csharp
map.Properties(p => p
  .Keyword(f => f.Name(u => u.SomeProperty))
  .FieldAlias(a => a.Name("some").Path(f => f.SomeProperty));
```

I was trying to dig into the property descriptors to see if there was some way I could reach outside of the current mapping to add another mapping, but that doesn't appear to be possible. Thoughts?

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Please let us know if this issue is still a relevant priority for your usage?
