### ISSUE TITLE
BulkDescriptor serialization returns empty object: {}

### ISSUE THREAD

**Issue by mostmand** [elastic/elasticsearch-net#4045]
**NEST version**:
7.2.0

**Elasticsearch version**:
7.2.0

**Description of the problem**:
When I create a new BulkDescriptor and add some documents to it using Index method, then serialization of the bulk descriptor returns empty object. Note that I am trying to upgrade from Nest 6.4 to Nest 7.2 and I haven't experienced such problem in 6.4 release.

**Steps to reproduce**:
 ```csharp
var bulkDescriptor = new BulkDescriptor();
bulkDescriptor.Index<Dictionary<string, object>>(i => i
                            .Document(data)
                            .Index(index));
var jsonSerializer = new ElasticClient().RequestResponseSerializer;
var bytes = jsonSerializer.SerializeToBytes(bulkDescriptor);
```
The above code returns a byte[] of length 2 which only consists of "{}" while object data is a Dictionary<string, object> and contains 10 key value pairs.

**Comment by mostmand** [comment]
If anyone else is facing this issue this is a workaround:
```csharp
var postData = new SerializableData<IBulkRequest>(bulkDescriptor);
using (var stream = new 
{
    postData.Write(stream, new ConnectionSettings());
    var bytes = stream.GetBuffer().Take(Convert.ToInt32(stream.Length)).ToArray();
}
```

**Comment by russcam** [comment]
@mostmand It looks like you found the issue. In 7.x, the `BulkDescriptor` would need to be serialized as the interface `IBulkRequest`

```c#
var bulkDescriptor = new BulkDescriptor();
bulkDescriptor.Index<Dictionary<string, object>>(i => i
	.Document(new Dictionary<string, object> 
	{
		{ "foo", "bar" }
	})
	.Index("index"));

var jsonSerializer = new ElasticClient().RequestResponseSerializer;
var bytes = jsonSerializer.SerializeToBytes<IBulkRequest>(bulkDescriptor);
```

serializes to

```json
{"index":{"_id":null,"_index":"index"}}
{"foo":"bar"}
```

I _think_ this will be true for all requests, that they will need to be serialized as their interface.

**Comment by mostmand** [comment]
Thanks for your response.

**Comment by codebrain** [comment]
Closing as response appears to resolved the issue.
