### ISSUE TITLE
Double Deserializer uses current thread culture, throws Exeption

### ISSUE THREAD

**Issue by nenadvicentic** [elastic/elasticsearch-net#4057]
**NEST/Elasticsearch.Net version**: 7.2.1

**Elasticsearch version**: 6.8, 7.2

**Description of the problem including expected versus actual behavior**:

**The problem:**

When current thread culture has comma "," as a decimal separator instead of dot ".", exception is thrown for valid `longitude` values (ex: **16.27749494276941**):

> UnexpectedElasticsearchClientException: Specified argument was out of the range of valid values.
Parameter name: Invalid longitude '1.62774949427694E+15'. Valid values are between -180 and 180

**Expected:** 

Parse longitude/latitude values for `GeoCentroidAggregate` correctly.

**Stack trace**:

Inner Exception:
> ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
 Parameter name: Invalid longitude '1.62774949427694E+15'. Valid values are between -180 and 180

Stack Trace:

> Nest.GeoLocation..ctor(double latitude, double longitude)
> Nest.GeoLocationFormatter.Deserialize(ref JsonReader reader, IJsonFormatterResolver formatterResolver)
> Nest.AggregateFormatter.GetGeoCentroidAggregate(ref JsonReader reader, IJsonFormatterResolver formatterResolver, IReadOnlyDictionary<string, object> meta)
> Nest.AggregateFormatter.ReadAggregate(ref JsonReader reader, IJsonFormatterResolver formatterResolver)
> Nest.AggregateFormatter.GetSubAggregates(ref JsonReader reader, string name, IJsonFormatterResolver formatterResolver)
> Nest.AggregateFormatter.GetKeyedBucket(ref JsonReader reader, IJsonFormatterResolver formatterResolver)
> Nest.AggregateFormatter.ReadBucket(ref JsonReader reader, IJsonFormatterResolver formatterResolver)
> Nest.AggregateFormatter.GetMultiBucketAggregate(ref JsonReader reader, IJsonFormatterResolver formatterResolver, ref ArraySegment<byte> propertyName, IReadOnlyDictionary<string, object> meta)
> Nest.AggregateFormatter.ReadAggregate(ref JsonReader reader, IJsonFormatterResolver formatterResolver)
> Nest.AggregateDictionaryFormatter.ReadAggregate(ref JsonReader reader, IJsonFormatterResolver formatterResolver, string[] tokens, Dictionary<string, IAggregate> dictionary)
> Nest.AggregateDictionaryFormatter.Deserialize(ref JsonReader reader, IJsonFormatterResolver formatterResolver)
> Deserialize(object[] , ref JsonReader , IJsonFormatterResolver )
> Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize<T>(byte[] bytes, int offset, IJsonFormatterResolver resolver)
> Elasticsearch.Net.Utf8Json.JsonSerializer.DeserializeAsync<T>(Stream stream, IJsonFormatterResolver resolver)
> Elasticsearch.Net.ResponseBuilder.SetBodyAsync<TResponse>(ApiCallDetails details, RequestData requestData, Stream responseStream, string mimeType, CancellationToken cancellationToken)
> Elasticsearch.Net.ResponseBuilder.ToResponseAsync<TResponse>(RequestData requestData, Exception ex, Nullable<int> statusCode, IEnumerable<string> warnings, Stream responseStream, string mimeType, CancellationToken cancellationToken)
> Elasticsearch.Net.HttpConnection.RequestAsync<TResponse>(RequestData requestData, CancellationToken cancellationToken)
> Elasticsearch.Net.RequestPipeline.CallElasticsearchAsync<TResponse>(RequestData requestData, CancellationToken cancellationToken)
> Elasticsearch.Net.Transport<TConnectionSettings>.RequestAsync<TResponse>(HttpMethod method, string path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters)

**Comment by nenadvicentic** [comment]
I found the issue. It is in `StringToDoubleConveter.cs` file, at the line 640:

```c#
return double.Parse(laststr);
```

Instead, it should be:
```c#
return double.Parse(laststr, CultureInfo.InvariantCulture);
```

**Comment by russcam** [comment]
@nenadvicentic thanks for raising! Would you like to open.a PR for it?

**Comment by nenadvicentic** [comment]
@russcam I created PR. Signed CLA few mins ago.
