### ISSUE TITLE
[feature] Create an option to enable TrackTotalHits for all requests by default

### ISSUE THREAD

**Issue by IvanSorokin** [elastic/elasticsearch-net#4074]
**NEST/Elasticsearch.Net version**: 7.0.0

**Elasticsearch version**: 7.2.0

**Describe the feature**:

We are migrating from elasticsearch 6 and struggling with total hits count. In es7 you have to specify `.TrackTotalHits()` for each search request to get accurate result, otherwise maximal total is 10000. A lot of our logic require accurate total and we have tons of search calls. I didn't find a way to enable previous logic via connectionSettings or any other one line method. It's a lot of work to inject `.TrackTotalHits()` in each search request so I suggest having a feature for global total accurate setting is a really handy thing. Like an option for connection string, so you can have something like this:

```
connectionSettings.ThrowExceptions()
                  .DisablePing()
                  .TrackTotalHits();
```

**Comment by russcam** [comment]
I can see some value in having this, but it's probably not a high priority item to implement. Would you be interested in opening a PR for this? Branching from master would be best and would need to be implemented in a non-binary breaking way to port and include in 7.x.

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Please let us know if this issue is still a relevant priority for your usage?
