### ISSUE TITLE
How to generates the query based on the users input!

### ISSUE THREAD

**Issue by rameshkr1994** [elastic/elasticsearch-net#4084]
Dear All.

I having issue while writing the query with multiple search fields

How can we run elastic search query based on user input fields:values.

i have 8-fields and every time user searching 3 or 4,5,8 fields there is no any fixed search fields limit.

how can we achieve this kind of query in elastic search.

**Comment by russcam** [comment]
Hi @rameshkr1994, 

We reserve GitHub Issues for bug reports and feature requests.

In order for your question to get the attention it deserves, the best place to ask it would be the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Not only do more folks view the forums than the GitHub Issues list, and hence it is more likely to receive attention, but the forums are also geared towards being able to search previous questions and answers, making it a much more valuable archive for future question askers.

Thanks!
