### ISSUE TITLE
Completion suggesters Missing weights

### ISSUE THREAD

**Issue by mikkel-busch** [elastic/elasticsearch-net#4088]
**NEST/Elasticsearch.Net version**: 7.3.0
**Elasticsearch version**: 7.3.1
**Wanted behavior**
To send weighted completions suggestions like in:
```
PUT music/_doc/1?refresh
{
    "suggest" : [
        {
            "input": "Nevermind",
            "weight" : 10
        },
        {
            "input": "Nirvana",
            "weight" : 3
        }
    ]
}
```
From: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html#completion-suggester
**Actual**
The class CompletionField does not support individual weights.
And nothing in the [documentation](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/suggest-usage.html) suggest how to apply individual weights.

**Work around**
By adding
```csharp
  [Completion]
  public CompletionWorkAround[] Completion { get; set; }
  ...
  public class CompletionWorkAround
  {
    public string Input { get; set; }
    public int Weight { get; set; }
  }
```
Completion suggestions seems to be indexed correctly.
**Hope**
This feature will be supported directly by NEST

**Comment by russcam** [comment]
I think introducing your own type for this mapping is totally fine and the right thing to do; the `CompletionField` type is a convenient helper type for the most common use case of multiple inputs tied to the same weight.

**Comment by russcam** [comment]
I've added a discussion point for this to look at for the next major version.

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Will re-review during code-gen work though. Please let us know if this issue is still a relevant priority for your usage?
