### ISSUE TITLE
GeoSuggestContextDescriptor's Precision-method accepts array instead of singular value

### ISSUE THREAD

**Issue by billbogaiv** [elastic/elasticsearch-net#4089]
**NEST/Elasticsearch.Net version**: 6

**Elasticsearch version**: 6

**Description of the problem including expected versus actual behavior**:

When applying `Mapping` within `client.CreateIndex`, the `GeoLocation` `Completion`-descriptor takes a collection of `Precision`-values. However, ES only accepts a singular value. Even passing one-value to `.Precision("25mi")` results in the construction of an array. This eventually leads to an ES syntax-error when creating the index.

**Steps to reproduce**:

```csharp
public class PlaceSearchDocument
{
    [GeoPoint]
    public Location Location { get; set; }
}

client.CreateIndex("places", (CreateIndexDescriptor createDescriptor) =>
    createDescriptor.Mappings(mappingDescriptor =>
        mappingDescriptor.Map<PlaceSearchDocument>(map => map
            .AllField(af => af.Enabled(false))
            .AutoMap()
            .Properties(property => property
                .Completion(completion => completion.Name("LocationSuggest").Contexts(context => context
                    .GeoLocation(geolocation => geolocation
                        .Name("Location")
                        .Path("Location")
                        .Precision("25mi"))
                ))))));
```

**Provide `DebugInformation` (if relevant)**:

```json
PUT places
{
  "mappings": {
    "place": {
      "_all": {
        "enabled": false
      },
      "properties": {
        "Location": {
          "type": "geo_point"
        },
        "LocationSuggest": {
          "type": "completion",
          "contexts": [
            {
              "type": "geo",
              "name": "Location",
              "path": "Location",
              "precision": ["25mi"]
            }
          ]
        }
      }
    }
  }
}
```

**Expected value**

```json
PUT places
{
  "mappings": {
    "place": {
      "_all": {
        "enabled": false
      },
      "properties": {
        "Location": {
          "type": "geo_point"
        },
        "LocationSuggest": {
          "type": "completion",
          "contexts": [
            {
              "type": "geo",
              "name": "Location",
              "path": "Location",
              "precision": "25mi"
            }
          ]
        }
      }
    }
  }
}
```

Ref. https://github.com/elastic/elasticsearch-net/blob/c646b98c5e5278ad122cd686fa27c45cbb18b919/src/Nest/Search/Suggesters/ContextSuggester/GeoSuggestContext.cs#L35

**Comment by khalidabuhakmeh** [comment]
Well actually... It seems like the problem is in the type definition.

https://github.com/elastic/elasticsearch-net/blob/c646b98c5e5278ad122cd686fa27c45cbb18b919/src/Nest/Search/Suggesters/ContextSuggester/GeoSuggestContext.cs#L7-L15

That type probably shouldn't be `IEnumerable<string>`
