### ISSUE TITLE
GeoBoundingBox ... can't pass geohash parameter

### ISSUE THREAD

**Issue by patcout26** [elastic/elasticsearch-net#4092]
When create a filter for a GeoBoundingBox ... elasticsearch 7.3 accepts geohash but not the sdk (nest 7.3)
ex: new QueryContainerDescriptor<Obejct>().GeoBoundingBox(dr => dr.BoundingBox(bb => bb ..

Link that prove that elastic search accepts geohash parameter
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-geo-bounding-box-query.html

**Comment by russcam** [comment]
NEST represents the `"top_left"` and `"bottom_right"` values of the bounding box with the `GeoLocation` type, which doesn't support geohashes. 

Supporting geohashes in addition to the `{ "lat": _, "lon": _ }` might require re-modelling the `GeoLocation` type, introducing a new type, or introducing a `Union<string, GeoLocation>`. Not sure about the feasability of supporting this in 7.x without a breaking change, which is not something we'd want to do.

**Comment by stevejgordon** [comment]
Closing  as this will be reviewed during code-gen work for v8. Please let us know if this issue is still a relevant priority for your usage?
