### ISSUE TITLE
Double check our source link support

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#4095]
We support sourcelink for a long time now but I haven't double checked if we package this correctly  for a similar long while either.

Creating this ticket to remember to investigate our support for this feature is still good.

**Comment by phoeniks-sk** [comment]
Hello, I would say that it's probably not packaged or shipped correctly.

I don't know if I should post this here or create a separate issue, let me know if I need to change it please.

I've tried yesterday to load PDB for Nest and it failed on me.

The Symbol Load log looks like this:
> SYMSRV:  BYINDEX: 0x16B
>          <local_cache_path>*https://msdl.microsoft.com/download/symbols
>          Nest.pdb
>          3F54E208B90547C5BE259DA1B4429D7C1
> SYMSRV:  UNC: <local_cache_path>\Nest.pdb\3F54E208B90547C5BE259DA1B4429D7C1\Nest.pdb - path not found
> SYMSRV:  UNC: <local_cache_path>\Nest.pdb\3F54E208B90547C5BE259DA1B4429D7C1\Nest.pd_ - path not found
> SYMSRV:  UNC: <local_cache_path>\Nest.pdb\3F54E208B90547C5BE259DA1B4429D7C1\file.ptr - path not found
> SYMSRV:  HTTPGET: /download/symbols/Nest.pdb/3F54E208B90547C5BE259DA1B4429D7C1/Nest.pdb
> SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
> SYMSRV:  HTTPGET: /download/symbols/Nest.pdb/3F54E208B90547C5BE259DA1B4429D7C1/Nest.pd_
> SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
> SYMSRV:  HTTPGET: /download/symbols/Nest.pdb/3F54E208B90547C5BE259DA1B4429D7C1/file.ptr
> SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
> SYMSRV:  RESULT: 0x80190194
> https://msdl.microsoft.com/download/symbols: Symbols not found on symbol server.
> SYMSRV:  BYINDEX: 0x16C
>          <local_cache_path>*https://symbols.nuget.org/download/symbols
>          Nest.pdb
>          3F54E208B90547C5BE259DA1B4429D7Cffffffff
> SYMSRV:  UNC: <local_cache_path>\Nest.pdb\3F54E208B90547C5BE259DA1B4429D7Cffffffff\Nest.pdb - path not found
> SYMSRV:  UNC: <local_cache_path>\Nest.pdb\3F54E208B90547C5BE259DA1B4429D7Cffffffff\Nest.pd_ - path not found
> SYMSRV:  UNC: <local_cache_path>\Nest.pdb\3F54E208B90547C5BE259DA1B4429D7Cffffffff\file.ptr - path not found
> SYMSRV:  HTTPGET: /download/symbols/Nest.pdb/3F54E208B90547C5BE259DA1B4429D7Cffffffff/Nest.pdb
> SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
> SYMSRV:  HTTPGET: /download/symbols/Nest.pdb/3F54E208B90547C5BE259DA1B4429D7Cffffffff/Nest.pd_
> SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
> SYMSRV:  HTTPGET: /download/symbols/Nest.pdb/3F54E208B90547C5BE259DA1B4429D7Cffffffff/file.ptr
> SYMSRV:  HttpQueryInfo: 80190194 - HTTP_STATUS_NOT_FOUND
> SYMSRV:  RESULT: 0x80190194
> SYMSRV:  BYINDEX: 0x16D
>          <local_cache_path>*https://symbols.nuget.org/download/symbols
>          Nest.pdb
>          3F54E208B90547C5BE259DA1B4429D7C1
> SYMSRV:  UNC: <local_cache_path>\Nest.pdb\3F54E208B90547C5BE259DA1B4429D7C1\Nest.pdb - path not found
> SYMSRV:  UNC: <local_cache_path>\Nest.pdb\3F54E208B90547C5BE259DA1B4429D7C1\Nest.pd_ - path not found
> SYMSRV:  UNC: <local_cache_path>\Nest.pdb\3F54E208B90547C5BE259DA1B4429D7C1\file.ptr - path not found
> SYMSRV:  HTTPGET: /download/symbols/Nest.pdb/3F54E208B90547C5BE259DA1B4429D7C1/Nest.pdb
> SYMSRV:  HttpQueryInfo: 80190193 - HTTP_STATUS_FORBIDDEN
> SYMSRV:  RESULT: 0x80190193

Also, according to [this post](https://devblogs.microsoft.com/nuget/improved-package-debugging-experience-with-the-nuget-org-symbol-server/), there should be a _Download symbols_ link on NEST's nuget page on the right under _Download package_, but it's missing.

**Comment by russcam** [comment]
It looks like since SourceLink was originally implemented, some required pieces that are needed for it to work were lost in refactoring of build components and the move to newer SDK projects. I've reinstated these pieces and I've opened #4224 to address. I've checked the PR in both Visual Studio 2019 and JetBrains Rider, and both are functioning correctly.
