### ISSUE TITLE
geopoint attribute not working

### ISSUE THREAD

**Issue by thdotnet** [elastic/elasticsearch-net#4098]
Hi I'm trying to use GeoPoint type, but it's being mapped to string:

indexProperties.geolocation.type | string

Here's how I'm using in my code:

```
            [GeoPoint]
            public GeoLocation GeoLocation
            {
                get
                {
                    return new GeoLocation(double.Parse(latitudeDeg), double.Parse(longitudeDeg));
                }
            }

```

**Comment by russcam** [comment]
Can you show the code that you're using to map the geopoint property to a mapping in an index please?

**Comment by russcam** [comment]
@thdotnet do you have a complete but succinct example that you can share, that shows the issue?

**Comment by thdotnet** [comment]
As I am no longer using it, I'll close the issue.
