### ISSUE TITLE
Upgrade to NEST 7.0 serializer issues.

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#4116]
I upgraded to elasticsearch 7 from 5 and one area that bit me and caused me about a days worth of work was trying to figure out why my models were not being serialized correctly. I was under the impression that in 7.0 that all serializer settings configured were only for my models and that was it. This is where I went wrong...

I injected my applications serializer settings and configured it like this thinking it would use all my serializer settings:
```cs
var settings = new ConnectionSettings(connectionPool, 
                (serializer, values) => new JsonNetSerializer(serializer, values, () => _myAppsInjectedSerializerSettings));
```

After a day of messing around and creating smaller and smaller samples, I found that my injected serializer settings were modified by reference and affected my entire application (NOT Cool). I believe this is being done so NEST Attributes can be resolved (of which we don't use anywhere in our app and have no plans todo). So I was able to rework the following in one of our apps which got us up and working:

```cs
var settings = new ConnectionSettings(
                CreateConnectionPool() ?? new SingleNodeConnectionPool(new Uri(_config.ConnectionString)),
                (serializer, values) => new JsonNetSerializer(serializer, values, JsonSerializerSettingsFactory, ModifyContactResolver, ContractJsonConverters));
            
        private JsonSerializerSettings JsonSerializerSettingsFactory()
        {
            return new JsonSerializerSettings
            {
                DateParseHandling = _serializerSettings.DateParseHandling,
                DefaultValueHandling = _serializerSettings.DefaultValueHandling,
                MissingMemberHandling = _serializerSettings.MissingMemberHandling,
                NullValueHandling = _serializerSettings.NullValueHandling
            };
        }
        
        private void ModifyContactResolver(ConnectionSettingsAwareContractResolver resolver)
        {
            var strategy = ((DefaultContractResolver) _serializerSettings.ContractResolver).NamingStrategy;
            resolver.NamingStrategy = new CamelCaseNamingStrategy(strategy.ProcessDictionaryKeys, strategy.OverrideSpecifiedNames, strategy.ProcessExtensionDataNames);
        }

       private IEnumerable<JsonConverter> ContractJsonConverters => _serializerSettings.Converters;
```

One of my main concerns about this is that I don't like that I can't just use my existing serializer settings and there probably is a lot of properties that I'm not syncing.. I'd rather just inject my settings and know it's the same exact serializer settings. Which brings me to my blocking issue.

In Exceptionless, we have a [custom contract resolver](https://github.com/exceptionless/Exceptionless/blob/feature/elastic7/src/Exceptionless.Core/Serialization/LowerCaseUnderscorePropertyNamesContractResolver.cs) that depending on the type we use [one serializer or the other](https://github.com/exceptionless/Exceptionless/blob/feature/elastic7/src/Exceptionless.Core/Bootstrapper.cs#L289-L293) ([here is where we register the serializer](https://github.com/exceptionless/Exceptionless/blob/feature/elastic7/src/Exceptionless.Core/Bootstrapper.cs#L74-L84)). I don't even know how I'd modify the contract resolver in this case.  I could probably get 80% of the way there with a custom naming strategy but we do custom logic in `LowerCaseUnderscorePropertyNamesContractResolver.CreateProperty`.

Is there a good way to solve this?

**Comment by niemyjski** [comment]
cc @Mpdreamz @russcam :)

**Comment by niemyjski** [comment]
Is anyone looking at these issues?

**Comment by Mpdreamz** [comment]
Yes. You should know better then most that we take issues seriously. Hope you trust us we were otherwise engaged.

**Comment by russcam** [comment]
This looks like a manifestation of the recurrent problem that the client needs to make specific modifications to the serializer settings, including the `IContractResolver`, that could collide with your changes to the serializer settings needed for your application.

You may need to derive from `JsonNetSerializer` and override `CreateContractResolver()` to return an `IContractResolver` that derives from `ConnectionSettingsAwareContractResolver` which applies any settings that you need, or calls to the base implementation.

I would like to revisit this implementation for 8.x, to see if it's possible to make these components easier to use and modify.

**Comment by niemyjski** [comment]
Thanks for the follow up. I’ll start down that path. I get that you are looking at these and working on other things too. I’d figured I’d comment as I looked at the last page of github issues filed and barely any responses (I’m guilty of this too) knowing most of the people who posted are probably blocked, myself included.

**Comment by niemyjski** [comment]
So I just referenced a commit here and noticed it wasn't straight forward or how I'd expect/like to configure the serializer. Since the base constructor immediately creates a serializer any overriden methods that I'd implemented to create contracts / serializer settings threw null references and I was forced to create static func implementations to pass to the base constructer which didn't feel idiomatic.

**Comment by Mpdreamz** [comment]
>  I believe this is being done so NEST Attributes can be resolved (of which we don't use anywhere in our app and have no plans todo). So I was able to rework the following in one of our apps which got us up and working:

Thats correct: `Nest.JsonNetSerializer` exists to deal with bits from NET in your source documents such as 
- resolving configured propertynames (attributes/connectionsettings). 
- As well as handling NEST objects that could appear in your source and might need special care:

```csharp
typeof(JoinField),
typeof(QueryContainer),
typeof(CompletionField),
typeof(Attachment),
typeof(ILazyDocument),
typeof(LazyDocument),
typeof(GeoCoordinate),
typeof(GeoLocation)
```

If neither apply it could be more beneficial to create your own `IElasticsearchSerializer` based on `Json.Net` and return that from the `source serializer` factory method you pass to `ConnectionSettings`. That way we don't bleed into your existing contract resolvers.

**Comment by russcam** [comment]
I don't think there's anything further actionable on this ticket, are you happy for me to close it, @niemyjski?

**Comment by niemyjski** [comment]
I think this can be resolved but there definitely is some work that could take place to make this easier. I almost think my scenario should be the default and you should have to opt into serializer changes that allow you to use attributes. I should just need to inject my serializer settings and be done.

**Comment by russcam** [comment]
> I almost think my scenario should be the default and you should have to opt into serializer changes that allow you to use attributes.

I disagree; When using the `JsonNetSerializer`, I would expect the default to "just work" where I have used Nest attributes or types on my document POCOs. 

We have a discussion point for the next major version to look at making this better/easier/simpler to use, which I am keen to do for the client all round. Closing this.

**Comment by niemyjski** [comment]
Searching github code usages... I’m curious as to how many people use the attributes and have a package dependency...
