### ISSUE TITLE
Snake case naming strategy not applied in queries

### ISSUE THREAD

**Issue by rpawlaszek** [elastic/elasticsearch-net#4121]
**NEST/Elasticsearch.Net version**: 6.8.3

**Elasticsearch version**: 6.7.1

**Description of the problem including expected versus actual behavior**:
Match query over field is serialized in camelCase when SnakeCaseNamingStrategy specified (following: https://github.com/elastic/elasticsearch-net/issues/3422).
**Steps to reproduce**:
 1. Set up `docker-compose.yml`:

```
version: '3.7'
services:

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
        restart: always
        ports:
            - 9200:9200
        environment:
            - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
```

 2. Create a console app with `dotnet new console`
 3. Add packages to follow this csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elasticsearch.NET" Version="6.8.3" />
    <PackageReference Include="NEST" Version="6.8.3" />
    <PackageReference Include="NEST.JsonNetSerializer" Version="6.8.3" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
  </ItemGroup>

</Project>
```
 4. Prepare the `Program.cs` following:

```
    public class Person
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }

    class Program
    {
        static async Task Main(string[] args)
        {
            var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
            var connectionSettings = new ConnectionSettings(pool, (builtin, settings) =>
                new JsonNetSerializer(builtin, settings,
                    modifyContractResolver: c => c.NamingStrategy = new SnakeCaseNamingStrategy()
                )
            );
            connectionSettings.DefaultMappingFor<Person>(m => m.IndexName("person").TypeName("_doc"));
            connectionSettings.DisableDirectStreaming()
                    .OnRequestCompleted(details =>
                    {
                        Console.WriteLine(details.DebugInformation);
                    })
                    .PrettyJson();

            var client = new ElasticClient(connectionSettings);

            var person = new Person
            {
                Id = 1,
                FirstName = "John",
                LastName = "Smith"
            };

            Console.WriteLine("indexing");
            var indexResponse = await client.IndexDocumentAsync(person);
            Console.WriteLine($"indexing valid: {indexResponse.IsValid}");
            var response = await client.SearchAsync<Person>(s => s.From(0).Take(10).Query(q => q.Match(m => m.Query("John").Field(f => f.FirstName))));

            Console.WriteLine($"response: Count {response.Documents.Count}");

            await Task.Delay(2000);
        }
    }
```
 
 5. `docker-compose up`
 6. `dotnet restore|build|run` (after the ES is started)

**Provide `ConnectionSettings` (if relevant)**:
```
            var connectionSettings = new ConnectionSettings(pool, (builtin, settings) =>
                new JsonNetSerializer(builtin, settings,
                    modifyContractResolver: c => c.NamingStrategy = new SnakeCaseNamingStrategy()
                )
            );
            connectionSettings.DefaultMappingFor<Person>(m => m.IndexName("person").TypeName("_doc"));
            connectionSettings.DisableDirectStreaming()
                    .OnRequestCompleted(details =>
                    {
                        Console.WriteLine(details.DebugInformation);
                    })
                    .PrettyJson();
```
**Provide `DebugInformation` (if relevant)**:
1. Indexing (which is fine):
```
Successful low level call on PUT: /person/_doc/1?pretty=true
# Server indicated deprecations:
- 299 Elasticsearch-6.7.1-2f32220 "the default number of shards will change from [5] to [1] in 7.0.0; if you wish to continue using the default of [5] shards, you must manage this on the create index request or with an index template"
# Audit trail of this API call:
 - [1] HealthyResponse: Node: http://localhost:9200/ Took: 00:00:02.8506221
# Request:
{
  "id": 1,
  "first_name": "John",
  "last_name": "Smith"
}
# Response:
{
  "_index" : "person",
  "_type" : "_doc",
  "_id" : "1",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "_seq_no" : 0,
  "_primary_term" : 1
}
```
1. Search (which has a camelCase serialized field name):

```
Successful low level call on POST: /person/_doc/_search?pretty=true&typed_keys=true
# Audit trail of this API call:
 - [1] HealthyResponse: Node: http://localhost:9200/ Took: 00:00:00.4519862
# Request:
{
  "from": 0,
  "query": {
    "match": {
      "firstName": {
        "query": "John"
      }
    }
  },
  "size": 10
}
# Response:
{
  "took" : 119,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
```
Note that changing the query to: 

```
            var response = await client.SearchAsync<Person>(s => s.From(0).Take(10).Query(q => q.Match(m => m.Query("John").Field("first_name"))));
```
is a workaround to the issue. 

**Describe the feature**:
Serialize the type property names according to the specified `NamingStrategy` in field descriptors.

**Comment by russcam** [comment]
Thanks for opening @rpawlaszek.

There's a subtlety here. The `JsonNetSerializer` naming strategy is used to serialize your POCOs that are used to represent documents in Elasticsearch. The fields to target in queries are encapsulated in the `Field` type though, which is serialized by the internal request/response serializer, and not by the source serializer i.e. `JsonNetSerializer`. 

The casing for how fields are serialized can be changed globally with `DefaultFieldNameInferrer` on `ConnectionSettings`, [along with some other ways](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/field-inference.html#camel-casing):

```c#
var settings = new ConnectionSettings(pool)
	.DefaultFieldNameInferrer(s =>
	{
                // your casing implementation
		var sb = new StringBuilder(s.Length);
		for (int i = 0; i < s.Length; i++)
		{
			var c = s[i];

			if (Char.IsUpper(c))
			{
				if (i == 0)
				{
					sb.Append(char.ToLowerInvariant(c));
				}
				else if (char.IsUpper(s[i - 1]))
				{
					sb.Append(char.ToLowerInvariant(c));
				}
				else
				{
					sb.Append("_");
					sb.Append(char.ToLowerInvariant(c));
				}
			}
			else
			{
				sb.Append(c);
			}
		}

		return sb.ToString();
	});

var client = new ElasticClient(settings);
```

**Comment by rpawlaszek** [comment]
Thanks @russcam for the answer. This solution works. This obviously is not a bug, as the approach in the client provides the functionality requested. 

Could I ask you to explain (or point me to the documentation) why this distinction in serialization exists?

**Comment by russcam** [comment]
> Could I ask you to explain (or point me to the documentation) why this distinction in serialization exists?

The distinction exists because NEST is always responsible for serializing `Field` types. A `Field` type can be represented as

- a string
- a `PropertyInfo`
- a lambda expression

And NEST handles resolving all of these to a string (the first one is easy 😄 ) that indicates the field to target.

**Comment by rpawlaszek** [comment]
Ok, this I understand. I do not understand the decoupling. Does it mean that a ```Field``` as understood by ES can mean something else than the data properties on an index?

What would be an example of ```NamingStrategy``` and ```DefaultFieldNameInferrer``` being different but required by NEST?

**Comment by russcam** [comment]
`NamingStrategy` is a concept of a specific `IElasticsearchSerializer` implementation, `JsonNetSerializer`, based on Json.NET. `DefaultFieldNameInferrer` is the general seam to affect how `Field` are serialized by convention.

The current field inference/serialization implementation does not rely on the `IElasticsearchSerializer` configured. Looking at the commit in which `DefaultFieldNameInferrer` was introduced in 2013 (https://github.com/elastic/elasticsearch-net/commit/cadcaa986539b45faf1de58361a28a6bbc44bb22), I _think_ it was originally introduced to affect dictionary keys, in addition to type properties. At that time, I don't believe Json.NET exposed a way to affect how dictionary keys are serialized. 

Perhaps `DefaultFieldNameInferrer` could rely on `IElasticsearchSerializer` in the future to serialize `Field`, through an interface on the method.
