### ISSUE TITLE
7.0 Query serializer settings for trailing commas?

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#4128]
I'm using the latest version of (7.3.1) nest and I'm going to be digging into this but I figured I'd log it in case it's something simple but we are using nest to build up a query and we just got the following error: `json_parse_exception Reason: "Unexpected character (']' (code 93)): expected a value`

I'm tracking it down but it seems our sort query has a trailing `,` before the end of the sort array.

```json
  "sort": [
    {
      "test.long-000004": {
        "nested": {
          "filter": {
            "term": {
              "tester.userId": {
                "value": "5d9f919617d7af597fd8a451"
              }
            }
          },
          "path": "tester"
        },
        "order": "asc"
      }
    },
  ],
```

In our visitor we are setting the nodes content for sort to something like this:

```cs
new FieldSort
                        {
                            Field = node.Field,
                            Nested = new NestedSort
                            {
                                Path = path,
                                Filter = Query<TEST>.Term(f => f.UserId, userid)
                            },
                            Order = node.IsNodeOrGroupNegated() ? SortOrder.Descending : SortOrder.Ascending
                        }
```

**Comment by russcam** [comment]
Do you have a reproducible example @niemyjski? I had a brief look at the sort serialization and nothing jumps out. The following

```c#
private static void Main()
{
    var defaultIndex = "default_index";
    var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));

    var settings = new ConnectionSettings(pool, new InMemoryConnection())
        .DefaultIndex(defaultIndex)
        .DisableDirectStreaming()
        .OnRequestCompleted(callDetails =>
        {
            if (callDetails.RequestBodyInBytes != null)
            {
                Console.WriteLine(
                    $"{callDetails.HttpMethod} {callDetails.Uri} \n" +
                    $"{Encoding.UTF8.GetString(callDetails.RequestBodyInBytes)}");
            }
            else
            {
                Console.WriteLine($"{callDetails.HttpMethod} {callDetails.Uri}");
            }
        });

    var client = new ElasticClient(settings);

	client.Search<object>(new SearchRequest<object>
	{
		Sort = new List<ISort> 
		{
			new FieldSort
			{
				Field = "test.long-000004",
				Nested = new NestedSort
				{
					Path = "path",
					Filter = Query<TEST>.Term(f => f.UserId, "userid")
				},
				Order = SortOrder.Descending
			}
		}
	});	
}

public class TEST
{
	public string UserId {get;set;}
}
```

serializes to

```json
POST http://localhost:9200/default_index/_search?typed_keys=true 
{"sort":[{"test.long-000004":{"nested":{"filter":{"term":{"userId":{"value":"userid"}}},"path":"path"},"order":"desc"}}]}
```

**Comment by niemyjski** [comment]
I don't currently but will try to get something, there's a lot of moving parts and it's not in a public app.

**Comment by niemyjski** [comment]
![image](https://user-images.githubusercontent.com/1020579/66656562-df7bcb80-ec03-11e9-88e3-645baff2503a.png)

Looks like the issue could be that multiple sort fields are returned and one of them is empty. I'm guessing that this is stripped from the generated query or is outputted as empty leaving the extra comma

**Comment by niemyjski** [comment]
I do see this code: https://github.com/elastic/elasticsearch-net/blob/c646b98c5e5278ad122cd686fa27c45cbb18b919/src/Nest/CommonOptions/Sorting/SortFormatter.cs#L77 so I'd think it wouldn't be generated but maybe it generates the comma before the sort expression which returns?

**Comment by russcam** [comment]
Good catch @niemyjski 👍 The formatter should emit `null` here rather than returning; the insertion of a comma happens in the formatter iterating over the collection. 

I'll submit a PR for this. Ideally, the calling code should also guard against allowing sort fields with `null` as `SortKey`
