### ISSUE TITLE
Deserialization Null Values

### ISSUE THREAD

**Issue by kowalej-homex** [elastic/elasticsearch-net#4153]
**NEST/Elasticsearch.Net version**:
7.3.1

**Elasticsearch version**:
7.3.2

**Description of the problem including expected versus actual behavior**:
I have a document POCO model made up of properties that include basic primitive types and some of my own object types. The mappings  generated from this model within elasticsearch are as expected, and searching by these properties appears to generate the expected query and resulting documents. However the documents only seem to have the basic type properties set and my own object types are all null.

Example:

I am searching for Cases with the following POCO mapping:

```C#
public abstract class DocumentBase
{
        public dynamic Id { get; set; }
        public JoinField JoinField { get; set; }

        public const uint Version = 1;
}

public class Case : DocumentBase
{
        public string AccessInstructions { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public User Customer { get; set; }
        public string CaseNumber { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public DateTime? CreatedOn { get; set; }
}

public class User
{
        public Guid? Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public PhoneType? PhoneType { get; set; }
}
```

I am able to search, for example, using a filter specifying Customer.FirstName matches "Mike" and will see Cases come back where the customer's first name is indeed "Mike" (I can check against the CaseNumber properties, or see the resulting JSON has the "customer.firstName" prop set to Mike in all records), with other results filtered out. However, the only properties that will have values in the mapped POCO object will be things like Case.AccessInstructions , Case.CaseNumber, Case.CreatedOn... but Case.Customer will be null.
 

**Steps to reproduce**:
 1. Create mapping POCO as shown above.
 2. Seed elasticsearch with objects such as:
  {
    "addressLine1" : "123, Fake Str",
	"addressLine2": "15th floor",
	
	"customer.id": "53B9A209-3F39-4859-87C2-6AB1E6795C81"
	"customer.firstName": "Mike",
	"customer.lastName": "Snow",
	"customer.fullName": "Mike Snow",
	"customer.phone": "123-342-4323",
	"customer.phoneType": 2

	"caseNumber": "12314231",
    "city": "Chicago",
    "country": "US",
	"createdOn" : "2019-06-11T15:59:20.040Z"	
}
 3. See that the returned result even when searching for Customer.FirstName, will have a null customer object.

Maybe I'm expecting this deserialization to happen automatically, but something needs to be specifically configured? Any help is appreciated here.

**Comment by russcam** [comment]
The JSON object in your example is flattened. For example,

```json
{
"addressLine1" : "123, Fake Str",
"addressLine2": "15th floor",

"customer.id": "53B9A209-3F39-4859-87C2-6AB1E6795C81",
"customer.firstName": "Mike",
"customer.lastName": "Snow",
"customer.fullName": "Mike Snow",
"customer.phone": "123-342-4323",
"customer.phoneType": 2,

"caseNumber": "12314231",
"city": "Chicago",
"country": "US",
"createdOn" : "2019-06-11T15:59:20.040Z"
}
```

should be the following, for the client to be able to deserialize correctly.

```json
{
"addressLine1" : "123, Fake Str",
"addressLine2": "15th floor",
"customer": {
  "id": "53B9A209-3F39-4859-87C2-6AB1E6795C81",
  "firstName": "Mike",
  "lastName": "Snow",
  "fullName": "Mike Snow",
  "phone": "123-342-4323",
  "phoneType": 2,
},
"caseNumber": "12314231",
"city": "Chicago",
"country": "US",
"createdOn" : "2019-06-11T15:59:20.040Z"
}
```
