### ISSUE TITLE
Function Score Query Usage - Object Initializer syntax does not compile

### ISSUE THREAD

**Issue by aeslinger0** [elastic/elasticsearch-net#4159]
[The object initializer syntax in the docs](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/function-score-query-usage.html#_object_initializer_syntax_example_54) does not compile. There is no generic `Field<Project>` property. Either the generic property is missing, the documentation is incorrect, or it's just not apparent where `Field<obj>` is coming from.

**Comment by russcam** [comment]
If you click the "edit" button on any of the docs, it will link to the underlying asciidoc file from which it was generated:

![image](https://user-images.githubusercontent.com/208231/67168084-c2a17e00-f3e3-11e9-907c-91a773af3fb5.png)

This in turn will link back to the source code that generated the asciidoc:

![image](https://user-images.githubusercontent.com/208231/67168098-e6fd5a80-f3e3-11e9-9597-07759d7ab769.png)

`Field<T>()` is using a `static import`; the full name is `Nest.Infer.Field<T>()`:

https://github.com/elastic/elasticsearch-net/blob/b0a8d867cd75b6e617f40d759986ed623c4b21eb/src/Tests/Tests/QueryDsl/Compound/FunctionScore/FunctionScoreQueryUsageTests.cs#L8

This is called out in the [Field Inference documentation](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/field-inference.html#nest-infer), but I think it would be noisy to call it out everywhere it's used.
