### ISSUE TITLE
[tests] get task fails n seed 84799

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#4167]
> build.bat seed:84799 integrate 7.0.0 "writable" "gettask"

The random seeded data throws:

>[ 2019-10-21T17:13:26,386][DEBUG][o.e.a.b.TransportShardBulkAction] [writable-node-f5f9929200] [project-get-task][0] failed to execute bulk item (index) index {[project-get-task][_doc][Auer, Turner and Walter380664], source[n/a, actual length: [3.5kb], max length: 2kb]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [tags.added] of type [date] in document with id 'Auer, Turner and Walter380664'
	at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:280) ~[elasticsearch-7.0.0.jar:7.0.0]

Found in #4163 https://github.com/elastic/elasticsearch-net/pull/4163/checks?check_run_id=268611435

**Comment by Mpdreamz** [comment]
> [2019-10-21T18:25:38,374][INFO ][o.e.t.LoggingTaskListener] [writable-node-5294029200] 3203 finished with response BulkByScrollResponse[took=7.1s,timed_out=false,sliceId=null,updated=0,created=500,deleted=0,batches=1,versionConflicts=0,noops=0,retries=0,throttledUntil=0s,bulk_failures=[],search_failures=[]]
[2019-10-21T18:25:39,377][INFO ][o.e.c.m.MetaDataCreateIndexService] [writable-node-5294029200] [nest-fluentasync-660dc1bc] creating index, cause [api], templates [nest_tests], shards [2]/[0], mappings []
[2019-10-21T18:25:40,134][DEBUG][o.e.a.b.TransportShardBulkAction] [writable-node-5294029200] [project-get-task][0] failed to execute bulk item (index) index {[project-get-task][_doc][Klocko - Conroy188046], source[n/a, actual length: [3.9kb], max length: 2kb]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [tags.added] of type [date] in document with id 'Klocko - Conroy188046'

From 

> build.bat seed:17572 integrate 7.0.0 "writable" "gettask"

**Comment by codebrain** [comment]
> > build.bat seed:84799 integrate 7.0.0 "writable" "gettask"
> 
> The random seeded data throws:
> 
> > [ 2019-10-21T17:13:26,386][DEBUG][o.e.a.b.TransportShardBulkAction] [writable-node-f5f9929200] [project-get-task][0] failed to execute bulk item (index) index {[project-get-task][_doc][Auer, Turner and Walter380664], source[n/a, actual length: [3.5kb], max length: 2kb]}
> > org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [tags.added] of type [date] in document with id 'Auer, Turner and Walter380664'
> > at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:280) ~[elasticsearch-7.0.0.jar:7.0.0]
> 
> Found in #4163 https://github.com/elastic/elasticsearch-net/pull/4163/checks?check_run_id=268611435

Ran on my machine and the tests passed without error.

**Comment by codebrain** [comment]
> > [2019-10-21T18:25:38,374][INFO ][o.e.t.LoggingTaskListener] [writable-node-5294029200] 3203 finished with response BulkByScrollResponse[took=7.1s,timed_out=false,sliceId=null,updated=0,created=500,deleted=0,batches=1,versionConflicts=0,noops=0,retries=0,throttledUntil=0s,bulk_failures=[],search_failures=[]]
> > [2019-10-21T18:25:39,377][INFO ][o.e.c.m.MetaDataCreateIndexService] [writable-node-5294029200] [nest-fluentasync-660dc1bc] creating index, cause [api], templates [nest_tests], shards [2]/[0], mappings []
> > [2019-10-21T18:25:40,134][DEBUG][o.e.a.b.TransportShardBulkAction] [writable-node-5294029200] [project-get-task][0] failed to execute bulk item (index) index {[project-get-task][_doc][Klocko - Conroy188046], source[n/a, actual length: [3.9kb], max length: 2kb]}
> > org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [tags.added] of type [date] in document with id 'Klocko - Conroy188046'
> 
> From
> 
> > build.bat seed:17572 integrate 7.0.0 "writable" "gettask"

Ran on my machine and the tests passed without error.

**Comment by russcam** [comment]
For

>build.bat seed:84799 integrate 7.0.0 "writable" "gettask"
>
> The random seeded data throws:
>
>[ 2019-10-21T17:13:26,386][DEBUG][o.e.a.b.TransportShardBulkAction] [writable-node-f5f9929200] [project-get-task][0] failed to execute bulk item (index) index {[project-get-task][_doc][Auer, Turner and Walter380664], source[n/a, actual length: [3.5kb], max length: 2kb]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse field [tags.added] of type [date] in document with id 'Auer, Turner and Walter380664'
at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:280) ~[elasticsearch-7.0.0.jar:7.0.0]
>
>Found in #4163 https://github.com/elastic/elasticsearch-net/pull/4163/checks?check_run_id=268611435

The date format in question is

```
2019-10-20T21:40:40.5+00:00
```

Note the single fractional value. Nest uses the `DateTimeFormatter`'s `Serialize` method:

https://github.com/elastic/elasticsearch-net/blob/86bcc2c1d5a6df52e4a421c90ba99220b89e4aed/src/Elasticsearch.Net/Utf8Json/Formatters/DateTimeFormatter.cs#L97-L259

which pads nanoseconds, so this error is surprising. Need to dig into further

**Comment by russcam** [comment]
Closing this as #4175 is merged
