### ISSUE TITLE
ElasticLowLevelClient BulkAsync Memory leak!

### ISSUE THREAD

**Issue by xlievo** [elastic/elasticsearch-net#4180]
simple
var result = Elastic.BulkAsync<StringResponse>(PostData.MultiJson(arg2));

In AB test - n 10000 - c 1000
Will cause memory never to be freed
Are there any parameters that limit memory growth? Thank you!

**Comment by Mpdreamz** [comment]
We use a pooled memory buffer:

https://github.com/elastic/elasticsearch-net/pull/4172

Which is expected to grow and reused. That said in the linked ticket we are discussing introducing some more knobs to users. Closing this to keep conversation isolated on that ticket. Feel free to comment on the PR.
