### ISSUE TITLE
Does ReIndexOnServer support ingest pipelines

### ISSUE THREAD

**Issue by envitraux** [elastic/elasticsearch-net#4183]
ReIndex has an ability to use an pipeline. The NEST client does not seem to support it for ReIndexOnServer

POST _reindex
{
  "source": {
    "index": "source"
  },
  "dest": {
    "index": "dest",
    **"pipeline": "some_ingest_pipeline"**
  }
}

**Comment by russcam** [comment]
Closing this as it's been implemented in https://github.com/elastic/elasticsearch-net/commit/593d871c028d3edeb27336ac1197bea17cd09128 and will be in the next release.

**Comment by envitraux** [comment]
Thanks
