### ISSUE TITLE
BulkAll exception details not accesible

### ISSUE THREAD

**Issue by mortenbock** [elastic/elasticsearch-net#4185]
When using the BulkAll() method in Nest, and an error occurs, then an ElasticsearchClientException is thrown. But from there it is not possible to get the information about what the issue was.

Example:

If I make a BulkAll() with one document where the Id property is empty, then elasticsearch will return a response like this over http:

    {
    	"took": 0,
    	"errors": true,
    	"items": [{
    			"index": {
    				"_index": "myindexname",
    				"_type": "mydocument",
    				"_id": "",
    				"status": 400,
    				"error": {
    					"type": "illegal_argument_exception",
    					"reason": "if _id is specified it must not be empty"
    				}
    			}
    		}
    	]
    }

This results in an exception with the message "BulkAll halted after receiving failures that can not be retried from _bulk", but exploring that does not give me access to the "items" array, which could describe what the underlying problem is.

Further more, trying to read the `ElasticsearchClientException.DebugInformation` property throws a null ref exception.

Would it be possible to get some more details in the exception to be able to log what actually went wrong during the bulk request? The only way I was able to find the problem was by using Fiddler to see what was being returned from the server.

**Comment by andrx** [comment]
I guess your use case looks something like this:

	var client = VirtualClusterWith.Nodes(2)
		.ClientCalls(c =>
			c.SucceedAlways()
				.ReturnResponse(new
				{
					took = 0,
					errors = true,
					items = new[]
					{
						new
						{
							index = new
							{
								_index = "myindexname",
								_type = "mydocument",
								_id = "",
								status = 400,
								error = new { type = "illegal_argument_exception", reason = "if _id is specified it must not be empty" }
							}
						}
					}
				}))
		.StaticConnectionPool()
		.Settings(s => s.DisableDirectStreaming().DefaultIndex("default-index").SkipDeserializationForStatusCodes(401))
		.Client;


	var index = CreateIndexName();

	var size = 10;
	var pages = 10;
	var seenPages = 0;
	var numberOfDocuments = size * pages;
	var documents = CreateLazyStreamOfDocuments(numberOfDocuments);
	var requests = 0;

	Exception ex = null;
	var tokenSource = new CancellationTokenSource();
	var bulkResponses = new ConcurrentBag<BulkResponse>();
	var bulkAllResponses = new ConcurrentBag<BulkAllResponse>();
	var deadLetterQueue = new ConcurrentBag<SmallObject>();
	var observableBulk = client.BulkAll(documents, f => f
			.MaxDegreeOfParallelism(1)
			.BulkResponseCallback(r =>
			{
				bulkResponses.Add(r);
				Interlocked.Increment(ref requests);
			})
			//.ContinueAfterDroppedDocuments()
			.DroppedDocumentCallback((r, o) => deadLetterQueue.Add(o))
			.BackOffTime(TimeSpan.FromMilliseconds(1))
			.Size(size)
			.RefreshOnCompleted()
			.Index(index)
			.BufferToBulk((r, buffer) => r.IndexMany(buffer))
		, tokenSource.Token);

	try
	{
		observableBulk.Wait(TimeSpan.FromSeconds(30), b =>
		{
			bulkAllResponses.Add(b);
			Interlocked.Increment(ref seenPages);
		});
	}
	catch (Exception e)
	{
		ex = e;
	}
			
So when exception happens in this case, it just leaves the execution by throwing on the first failed item. `ElasticsearchClientException.Response.DebugInformation` is available. `bulkResponses` will contain BulkResponse with `Items` collection that you mentioned.

If you uncomment `ContinueAfterDroppedDocuments` line above then it will continue trying to finish with all other documents. You won't get exception unless ES returns http code different than 200. For bulks it returns 200 if coordinating node successfully parsed and executed the client request no matter what error happened with specific item. In this case you will see all responses in `bulkResponses` again with `Items` collection available. `deadLetterQueue` will contain those bad items that it couldn't process. And `bulkAllResponses` will have a bit more insight on which batch error happened and what was the problem.

**Comment by mortenbock** [comment]
@andrx Thank you for this. Using the `DroppedDocumentCallback` allowed me to log the actual document specific errors before the exception occurs.
