### ISSUE TITLE
What is the backward compatibility story of Elasticsearch.net?

### ISSUE THREAD

**Issue by virgilp** [elastic/elasticsearch-net#4193]
**NEST/Elasticsearch.Net version**:
7.0.0-alpha (but I suspect it applies to 7.4 just as well)
**Elasticsearch version**:
6.4.2
**Description of the problem including expected versus actual behavior**:
According to https://github.com/elastic/elasticsearch-net , 6.x clients are incompatible with 7.x servers and viceversa. I can verify this to be true, since e.g. the "PUT ROLE" api has different endpoints:
https://www.elastic.co/guide/en/elasticsearch/reference/7.4/security-api-put-role.html
https://www.elastic.co/guide/en/elasticsearch/reference/6.8/security-api-put-role.html

We have an enterprise software that is deployed on-premise, and this means that we can't use Elasticsearch.net version 7.4 in our software since it wouldn't work with our customers that have 6.x servers; and I can't use 6.8.3 either, since it wouldn't work with our customers that upgraded to newer 7.x servers. What do I do?

**Steps to reproduce**:
 1. try to use the Elasticsearch.net client to perform "PUT ROLE" operations.
 2. if you use Elasticsearch.net 7.x, it will work with 7.x servers but not with 6.x servers (actually I think 6.7 might work, but 6.4.2 does not).  
 3. if you use Elasticsearch.net 6.x, it will work with 6.x servers but it doesn't work with 7.x servers. 

I understand that Elastic needs the ability to evolve the library. But I'm surprised that it's not backwards compatible - not even one major version back. Enterprises don't move that fast, we can't expect all of them to immediately upgrade, this is sort of a dealbreaker for us.

**Comment by codebrain** [comment]
Hi @virgilp 

Hopefully the following blog article answers your questions:
https://www.elastic.co/fr/blog/nest-and-elasticsearch-net-upgrading-your-codebase

...but please reach out here again if you have any further questions.

**Comment by virgilp** [comment]
So the answer is that whatever compatibility we want to offer, we need to do it completely on our own...  not necessarily the answer I was hoping for, but no doubt, an answer. Thanks!

**Comment by codebrain** [comment]
Sadly, if you intend to use different major versions in parallel, this is the best option we have currently.
Closing this ticket as hopefully your original question was answered.

**Comment by chad-rotermund-CA** [comment]
Is the information in that blog post (https://www.elastic.co/blog/nest-and-elasticsearch-net-upgrading-your-codebase) still the recommended path forward?  Similar to the original poster, I have an application that must manage more than one cluster of varying ES versions from within the same runtime.  

Namespace-versioned clients sound like a perfect solution. (from a perspective)

However, I'm not seeing any packages in the following NuGet feed:
https://ci.appveyor.com/nuget/elasticsearch-net

Am I looking in the right place?

**Comment by russcam** [comment]
@chad-rotermund-CA yes, you're looking in the right place. Need to make sure that prerelease packages will be returned as all the CI packagaes are prerelease packages. Here's what I see in Rider for the appveyor CI source:

![image](https://user-images.githubusercontent.com/208231/84452645-b3847e80-ac99-11ea-8162-2987ed94cd0c.png)
