### ISSUE TITLE
NullReference from API

### ISSUE THREAD

**Issue by haf-afa** [elastic/elasticsearch-net#4194]
**NEST/Elasticsearch.Net version**: 7.4.0
**Elasticsearch version**: doesn't matter

**Description of the problem including expected versus actual behavior**:

I can get nullrefexn from the surface area of your API. After failing to use the fluent API https://github.com/elastic/elasticsearch-net-example/issues/32 - I tried to manually create a request.

```fsharp

let createIndex (client: ElasticClient) =
  let name = IndexName.op_Implicit "kubernetes-resources"
//  let createBuilder (x: CreateIndexDescriptor): ICreateIndexRequest =
//    x.Map<Honey>(fun x -> x.AutoMap().Properties(fun y -> y))
  let req = new CreateIndexRequest(name)
  req.Mappings.Properties.[PropertyName.op_Implicit "apiVersion"] <- TextProperty()
  req.Mappings.Properties.[PropertyName.op_Implicit "kind"] <- TextProperty()
  req.Mappings.Properties.[PropertyName.op_Implicit "name"] <- TextProperty()
  req.Mappings.Properties.[PropertyName.op_Implicit "ns"] <- TextProperty()
  client.Indices.CreateAsync(name, fun _ -> req :> ICreateIndexRequest)
    |> Async.AwaitTask
```

This fails with:

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Program.createIndex(ElasticClient client) in C:\dev\fou_v2\src\Services\prometheus-operator\analyse\Program.fs:line 117
   at Program.main@154-1.Invoke(PingResponse _arg1) in C:\dev\fou_v2\src\Services\prometheus-operator\analyse\Program.fs:line 156
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in E:\A\_work\130\s\src\fsharp\FSha
rp.Core\async.fs:line 416
```
where line 117 is this line

```fsharp
  req.Mappings.Properties.[PropertyName.op_Implicit "apiVersion"] <- TextProperty()
```

Also, there are no docs on how to create indicies; the api docs on your web site are outdated and the methods used there don't exist. Also, it's unclear how to create other than TextProperty properties and how the type `Properties` is used (since it has no functionality, but I'd expect it to have bunch of factory functions that create these property mappings).

**Comment by codebrain** [comment]
Hi @haf-afa 

There is an example of using the client from F# in this blog article: https://www.elastic.co/blog/realtime-address-search-with-australian-gnaf (full F# script is here: https://gist.github.com/codebrain/9356a8c6db1c887bbd34706a6e77a66b)

Scrolling down to the *Create the index and mappings* heading you should see an example in F#, I have copied here for reference too:

```
let createIndex (elasticClient:ElasticClient) =
   let properties = new Properties<Address>()
   properties.Add(PropertyName.op_Implicit "display", new SearchAsYouTypeProperty()) 1.
   properties.Add(PropertyName.op_Implicit "location", new GeoPointProperty()) 2.

   let mapping = new TypeMapping()
   mapping.Properties <- properties

   let settings = new IndexSettings()
   settings.NumberOfReplicas <- Nullable 0 3.
   settings.NumberOfShards <- Nullable 1 4.

   let createIndexRequest = new CreateIndexRequest(IndexName.op_Implicit elasticsearchIndex)
   createIndexRequest.Settings <- settings
   createIndexRequest.Mappings <- mapping

   logf "Creating index %s" elasticsearchIndex
   let indexResponse = elasticClient.Indices.Create(createIndexRequest)
   logf "Created index %O" indexResponse
```

Hopefully the blog article and above example helps guide you on the usage from F#.

I think, based on your other ticket https://github.com/elastic/elasticsearch-net/issues/4195, we can look to improve the usability and documentation for F# use cases.

**Comment by haf-afa** [comment]
Thank you for your help in creating the response. I ended up doing it with curl instead. This issue is about the API throwing a null reference exception for something that is valid C#/F#, so I consider that a bug. Make Mappings a factory function that sets a reference or a configurator-callback or simply don't expose a getter publicly if it can be null, to solve the bug.

As for the API design (which is separate from the bug above); if you want you can create a ticket about designing the API with F#, where I can assist you and be your sounding board; because the implicits and way that the discoverability works right now is horrible to use.

**Comment by russcam** [comment]
`req` needs to be assigned an instance of `ITypeMapping` for `Mappings`, which is `null` by default. 

An index creation request may not define mappings, so I would argue it's better to have a `null` default value rather than allocate a new instance of `ITypeMapping` that may not be used, and that would end up serializing to `{}`.

Closing this.
