### ISSUE TITLE
Custom property's attributes are not serialized to index mapping

### ISSUE THREAD

**Issue by phoeniks-sk** [elastic/elasticsearch-net#4217]
**NEST/Elasticsearch.Net version**: 7.4.0

**Elasticsearch version**: 7.4.0

**Description of the problem including expected versus actual behavior**:
Hi, while upgrading our codebase from 6.8 to 7.4, we discovered a change of behavior that I cannot attribute to any of the breaking changes. Is this maybe caused by the change of the JSON serializer?

I create an object property with a custom property, but only the `type` gets serialized and the rest of the properties is ignored. In 6.8 it would also serialize the value of `language`. I've tried to mark them as `DataContract`/`DataMember` with no success.

When checking the descriptor's private properties, I can see that everything seems correct, just the serialization somehow ignores the properties.

Help would be appreciated, thanks.

**Steps to reproduce**:
 1. Create a custom property, e.g.:
```c#
    public class SpecialKeywordProperty : IProperty
    {
        public SpecialKeywordProperty(string language)
        {
            Type = "special_keyword";
            Language = language;
        }

        public string Type { get; set; }

        public PropertyName Name { get; set; }

        public IDictionary<string, object> LocalMetadata { get; set; }

        [PropertyName("language")]
        public string Language { get; set; }
    }
```
 2. Create a property visitor that's going to apply the property (on all object properties for simplicity):
```c#
    public class MappingPropertyVisitor : NoopPropertyVisitor
    {
        public override void Visit(IObjectProperty type, PropertyInfo propertyInfo, ElasticsearchPropertyAttributeBase attribute)
        {
            type.Properties.Clear();
            type.Properties.Add("special_field", new SpecialKeywordProperty("en"));
        }
    }
```
 3. Create a document POCO:
```c#
    class Doc
    {
        [Object]
        public string Whatever { get; set; }
    }
```
 4. Create a `CreateIndexDescriptor` mapping the document:
```c#
    new CreateIndexDescriptor("test-index")
             .Map<Doc>(m => m
                 .AutoMap<Doc>(new MappingPropertyVisitor())
                 .Dynamic(DynamicMapping.Strict)
             );
```
 5. Create the index or just serialize the mapping, the property `Language` will not be serialized
```javascript
{
  "mappings": {
    "dynamic": "strict",
    "properties": {
      "whatever": {
        "properties": {
          "special_field": {
            "type": "special_keyword"
          }
        },
        "type": "object"
      }
    }
  }
}

```

**Comment by russcam** [comment]
@phoeniks-sk This is a known issue with the serializer in 7.x, and relates to https://github.com/elastic/elasticsearch-net/issues/3655. I am hoping that we can revisit this soon. For now, you would be able to send the request with the lowlevel client

**Comment by russcam** [comment]
I've just opened #4219 to address

**Comment by russcam** [comment]
#4219 is merged and will be in the next release. Closing this
