### ISSUE TITLE
DateTime.MinValue doesn't get parsed for dateRangeQuery

### ISSUE THREAD

**Issue by Anasbzr** [elastic/elasticsearch-net#4228]
**NEST/Elasticsearch.Net version**:
7.4.0
**Elasticsearch version**:
7.3.0
**Description of the problem including expected versus actual behavior**:
In the search descriptor `DateRange.GreaterThanOrEquals` does not parse `DateTime.MinValue`, instead it sends a request with an empty string which ES 7.4 throws an error `cannot parse empty date`
**Steps to reproduce**:
 1. Set DateTime.MinValue
 2. Create any search query

**Comment by Knight2601** [comment]
isnt that because ES runs internally on EPOCH dates? offsets from January 1, 1970 so 01/01/0001 is bs
add 1950 years to datetime.mindate and its fine 🗡

**Comment by russcam** [comment]
Thanks for reporting @Anasbzr. It looks like the JSON serialization library  does not handle `DateTime.MinValue`

```c#
var response = client.Search<Question>(s => s
	.Query(q => q
		.DateRange(d => d
			.GreaterThanOrEquals(DateTime.MinValue)
			.Field(f => f.CreationDate)
		)
	)
);
```

emits

```
POST http://localhost:9200/posts/_search
{}
```

but

```c#
var response = client.Search<Question>(s => s
	.Query(q => q
		.DateRange(d => d
			.GreaterThanOrEquals(DateTime.MinValue.AddTicks(1))
			.Field(f => f.CreationDate)
		)
	)
);
```

emits

```json
POST http://localhost:9200/posts/_search
{"query":{"range":{"creationDate":{"gte":"0001-01-01T00:00:00.0000001"}}}}
```

we'll look to address this in the next release.

**Comment by russcam** [comment]
> It looks like the JSON serialization library does not handle DateTime.MinValue

JSON serialization is fine, it's the implementation for `IsValid` on `DateMath`:

https://github.com/elastic/elasticsearch-net/blob/e514e5b7f4a7fb555357d3e71bd455237ec8b542/src/Nest/CommonOptions/DateMath/DateMath.cs#L86

I think for a `DateTime`, any `DateTime` should be valid

**Comment by russcam** [comment]
opened #4278 to address
