### ISSUE TITLE
Search results behaviour with boosts is different from 6.8 to 7.1

### ISSUE THREAD

**Issue by yannlairdc** [elastic/elasticsearch-net#4229]
**NEST/Elasticsearch.Net version**: 7.4.0

**Elasticsearch version**: 7.1

**Description of the problem including expected versus actual behavior**:
We are currently doing the ground work to migrate from ES 6.8 to latest (which is 7.1 on AWS server side). We have built a new set of environment to be able to assess the impact of that change and we are seeing search results differences that we cannot explain. Note: using the exact same code to build the index and do the search with the exact same query.

The problems is that the explanation gives us very different result, even though the total roughly come to similar points. The weirdest of those is the boost. When we give a boost of 15 for a particular field, it comes back in the explanation with a value of 15 in v6 (as expected) and 33 in v7! We have no idea what is triggering that changes.

Any chance to get an explanation on how the boost values aren't consistent anymore between query and explanation in v7?

**Expected result:** The boost factor that we send to 7.1 server is used and returned properly in explanations. Set to 15 in the query, expected to come back as 15 as well.

**Actual Result:** The boost factor is very different in v6 to v7. V6 return an expected 15 boost factor, equivalent to query, but V7 server returns 33, which seems wrong.

**Steps to reproduce**:
 1. Run the same query in a V6 and V7 server with a boost 
This is our .net wrapper for the search:

`public async Task<ISearchResponse<T>> SearchAsync<T>(SearchQueryParameters parameters)
            where T : class
        {
            return await _elasticClient.SearchAsync<T>(s => s
                .Index(parameters.IndexName)
                .Explain(parameters.ExplainResult)
                .From((parameters.Page - 1) * parameters.PageSize)
                .Take(parameters.PageSize)
                .Query(q => parameters.Filter && (parameters.Query || q.MatchAll())));
        }`

This is a simplified version of the REST query that get sent to the server, with a boost of 15
`GET /logodesigns2/_search
{ 
   "explain":true,
   "from":0,
   "track_total_hits": true,
   "query":{ 
      "bool":{ 
         "should":[ 
            { 
               "term":{ 
                  "isOwned":{ 
                     "value":true,
                     "boost":15.0
                  }
               }
            }
         ]
      }
   },
   "size":32
}`

 2. Compare the outcome of V6 and V7 and see the boost explanation very different from V6 to V7.

V6 explanation on the boost, still at 15 as requested:
`                  {
                  "value": 6.758246,
                  "description": "weight(isOwned:T in 2242) [PerFieldSimilarity], result of:",
                  "details": [
                    {
                      "value": 6.758246,
                      "description": "score(doc=2242,freq=1.0 = termFreq=1.0\n), product of:",
                      "details": [
                        {
                          "value": 15,
                          "description": "boost",
                          "details": []
                        }
                      ]
                    }
                  ]
                },`

V7 outcome of the boost which is now set to 33 for no apparent reason:
`                {
                  "value" : 6.391614,
                  "description" : "weight(isOwned:T in 18403) [PerFieldSimilarity], result of:",
                  "details" : [
                    {
                      "value" : 6.391614,
                      "description" : "score(freq=1.0), product of:",
                      "details" : [
                        {
                          "value" : 33.0,
                          "description" : "boost",
                          "details" : [ ]
                        }
                  ]
                },`

**Provide `ConnectionSettings` (if relevant)**:
NA

**Provide `DebugInformation` (if relevant)**:
NA

**Comment by Mpdreamz** [comment]
Hi @yannlairdc 

This is more a server issue then a client issue but as I was unaware of any scoring changes myself this peeked my interest too.

I asked around internally and there was a change in how BM25 is calculated in Lucene:

 https://issues.apache.org/jira/browse/LUCENE-8563

This change landed in Elasticsearch `7.x`.

Hope this helps.
