### ISSUE TITLE
packing tag 7.1.0 locally generates 7.0.0.nupkg file

### ISSUE THREAD

**Issue by s7h** [elastic/elasticsearch-net#4231]
**NEST/Elasticsearch.Net version**: 7.1.0

**Elasticsearch version**: 7.1.0

**Description of the problem including expected versus actual behavior**:
Packing the git [tag version 7.1.0](https://github.com/elastic/elasticsearch-net/releases/tag/7.1.0) locally is generating ~7.0.0.nupkg files for elasticsearch, NEST and Nest.JsonNetSerializer projects. 

**Steps to reproduce**:
 1. Clone git tag 7.1.0
 2. Perform these steps for all the three projects
   - dotnet restore
   - dotnet build -c Release
   - dotnet pack --no-build -c Release
 3. Nuget file generated from these steps are of version 7.0.0

**Comment by Mpdreamz** [comment]
we use our own build script and do not rely on `dotnet pack` yet. 

`build.bat|build.sh release 7.1.0 skipdocs` 

Should build the release.

**Comment by s7h** [comment]
I tried running this command but I'm not able to build the code. 

I have the required dotnet SDK version - v2.2.103  but still it gives the error.
Could you please let me know if I could be missing any required dependencies.


FYI: I am able to build and pack it throw `dotnet` CLI commands.


![ES](https://user-images.githubusercontent.com/12686019/69534962-d884fe80-0fa0-11ea-9e0b-b909fbf56e4d.PNG)

**Comment by s7h** [comment]
@Mpdreamz

**Comment by s7h** [comment]
@Mpdreamz  got it fixed.

**Comment by Mpdreamz** [comment]
I reckon it's the space in your path?

**Comment by s7h** [comment]
Hey! @Mpdreamz ... 
I am able to build the code on windows machine successfully now. 
But when I am trying to build it on CentOS/Linux platform, I am not able to generate the nuget packages.

What could be the issue for this error?
![ES3](https://user-images.githubusercontent.com/12686019/69615131-6d97fe00-105a-11ea-858b-03398885fea1.PNG)

**Comment by Mpdreamz** [comment]
Ahh, it seems that part is still windows specific.

I run linux but we all release from Windows for our releases.

The main known blccker there is: https://github.com/nullean/AssemblyDiffer/issues/2

This is another one

**Comment by Mpdreamz** [comment]
Opened https://github.com/elastic/elasticsearch-net/issues/4242 to track this. 

Let's use that open ticket to continue discussing this, thanks for pushing this @s7h :+1:
