### ISSUE TITLE
Nest Field no longer support member expressions

### ISSUE THREAD

**Issue by slayme89** [elastic/elasticsearch-net#4240]
**NEST/Elasticsearch.Net version**:
7.4
**Elasticsearch version**:
7.4
**Description of the problem including expected versus actual behavior**:
Hi there!

I have created a topic at the Elastic forums which explains this issue, it can be found here: [Nest Field no longer support MemberExpressions](https://discuss.elastic.co/t/nest-field-no-longer-support-memberexpressions/208656). I was redirected here.

*Expected:*
Fields to be able to take a member expression in the constructor, as this documentation states:
[Member expression only](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/field-inference.html#member-expressions-only)

*Actual:*
Throws an exception that tells the user the provided expression is not a lambda expression.

I think this commit have changed the behavior: [7x/field resolver performance #3668](https://github.com/elastic/elasticsearch-net/commit/0fb1149c1f84a5e501149c78b222b5ae7dec677c#diff-60957b99fed84039ef5daa9b1861db9f)

We have a "workaround" for this now where we convert the member expression into a lambda expression before passing it to the Field constructor, but I think either the documentation should be updated to match the actual behavior or the constructor should support member expressions.

**Steps to reproduce**:
 1. Create a MemberExpression.
 2. Create a new Field and pass the MemberExpression into the constructor.

**Comment by russcam** [comment]
opened https://github.com/elastic/elasticsearch-net/pull/4268 to address
