### ISSUE TITLE
Allow release target to work x-platform

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#4242]
Our release target should work x-platform. 

Right now all our build targets work cross platform except `release` which needs to be called from Windows

Blockers:

- [ ] `pack` relies on `nuget.exe`
- [ ] https://github.com/nullean/AssemblyDiffer/issues/2

**Comment by s7h** [comment]
@Mpdreamz , is there any ETA on this ?

**Comment by Mpdreamz** [comment]
@s7h no, moving assembly differ is a bit involved. 

Took the first steps here: https://github.com/nullean/AssemblyDiffer/pull/3

But we also need to update JustAssembly in a fork so that it does not call the windows registry in a static property. We are also investigating other assembly differs in the mean time.

**Comment by Mpdreamz** [comment]
All the upstream blockers have been resolved `./build.sh <version>` now works on our`7.x` and `master` branches.
