### ISSUE TITLE
Match boolean prefix query not implemented

### ISSUE THREAD

**Issue by jonyadamit** [elastic/elasticsearch-net#4247]
**Describe the feature**:  
Title sums this up.  Implementation for [the following feature](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/query-dsl-match-bool-prefix-query.html) is missing.  
As a workaround, one can use a `MultiMatch` query, specifying `bool_prefix` as the type.  
I'm not sure if there are drawbacks to using `multi_match` query with one field vs using `match_bool_prefix` query.

**Comment by russcam** [comment]
Thanks @jonyadamit, opened https://github.com/elastic/elasticsearch-net/pull/4256
