### ISSUE TITLE
It is impossible to create index mapping with dynamic templates using Fluent Mapping

### ISSUE THREAD

**Issue by genafox** [elastic/elasticsearch-net#4248]
**NEST/Elasticsearch.Net version 7.4.1**:

**Elasticsearch version 7.5**:

**It is impossible to create index mapping with dynamic templates using Fluent Mapping** (DynamicTemplateDescriptor with MatchMappingType and Generic mapping):

**Steps to reproduce**:
Try to create index using the following code:
```
var createIndexResponse = _client.Indices.Create("company_index", c => c
	.Map<Company>(m => m
		.RoutingField(r => r.Required())
		.Properties(ps => ps
			.Text(s => s
				.Name(n => n.Name)
			)
		)
		.DynamicTemplates(d => d
			.DynamicTemplate(
				"copy_to_all_long",
				dt => dt
					.PathMatch("package.data.custom.*")
					.MatchMappingType("long")
					.Mapping(m => m
						.Generic(g => g
							.Type("long")
							.CopyTo(x => x.Field("custom_all_field"))
						)
					)
			)
	)
);
```
This code will produce the following request to the Elasticsearch:
```
PUT company_index
{
  "mappings": {
    "dynamic_templates": [
      {
        "copy_to_all_long": {
          "mapping": null,
          "match_mapping_type": "long",
          "path_match": "package.data.custom.*"
        }
      }
    ],
    "properties": {
      "name": {
        "type": "keyword"
      }
    },
    "_routing": {
      "required": true
    }
  }
}
```
The "**mapping**" property within the "**copy_to_all_long**" dynamic template is **null**, which is not allowed by the Elasticsearch and as a result the index creation fails:
```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "template must have mapping set"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [_doc]: template must have mapping set",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "template must have mapping set"
    }
  },
  "status": 400
}
```

As far as I understand from the Elasticsearch documentation the "**mapping**" property of the "**copy_to_all_long**" dynamic template must be the following:
```
"mapping": {
	"type": "long",
	"copy_to": [
		"custom_all_field"
	]
}
```

**Note:** the same problem is reproduced with other automatically detectable data types ("boolean", "date", "double", "long").

**Comment by russcam** [comment]
Thanks for reporting @genafox. This looks like an issue that originates from `PropertyFormatter`'s `Serialize` method that uses the `type` string to determine which concrete `IProperty` implementation we're serializing

https://github.com/elastic/elasticsearch-net/blob/e837dd07ede5e747fccf5ecd5384d5fb65157cfb/src/Nest/Mapping/Types/PropertyFormatter.cs#L112-L217

We'll look to address this for the next release as it is trappy in the case where `IGenericProperty` is used with a `type` string that would match another property, as happens in this case.

For now, you can workaround this issue by using the `INumberProperty` instead of `IGenericProperty`

```c#
var createIndexResponse = client.Indices.Create("company_index", c => c
	.Map<Company>(m => m
			.RoutingField(r => r.Required())
			.Properties(ps => ps
				.Text(s => s
					.Name(n => n.Name)
				)
			)
			.DynamicTemplates(d => d
				.DynamicTemplate(
					"copy_to_all_long",
					dt => dt
						.PathMatch("package.data.custom.*")
						.MatchMappingType("long")
						.Mapping(m => m
							.Number(n => n
								.Type(NumberType.Long)
								.CopyTo(x => x.Field("custom_all_field"))
							)
						)
				)
			)
		)
	);

```

which serializes to

```json
{
    "mappings": {
        "dynamic_templates": [{
            "copy_to_all_long": {
                "mapping": {
                    "copy_to": ["custom_all_field"],
                    "type": "long"
                },
                "match_mapping_type": "long",
                "path_match": "package.data.custom.*"
            }
        }],
        "properties": {
            "name": {
                "type": "text"
            }
        },
        "_routing": {
            "required": true
        }
    }
}
```

**Comment by genafox** [comment]
Hi @russcam! Thanks for the explanation and for the suggested workaround!

**Comment by russcam** [comment]
Opened https://github.com/elastic/elasticsearch-net/pull/4262 to address
