### ISSUE TITLE
Missing support for search_as_you_type in dynamic templates

### ISSUE THREAD

**Issue by robertlyson** [elastic/elasticsearch-net#4249]
Hello 👋,

**NEST/Elasticsearch.Net version**: 7.4.1

**Elasticsearch version**: 7.3.0

**Description of the problem including expected versus actual behavior**:

When creating dynamic template with fluent syntax there is no way to add mapping for `search_as_you_type` field type.

**Steps to reproduce**:
```
var createIndexResponse = await client.Indices.CreateAsync("index", o => o
    .Map<Act>(m => m
        .AutoMap<Act>()
        .DynamicTemplates(d => d
            .DynamicTemplate("stringassearch", dt => dt
                .PathMatch("entity.*")
                .MatchMappingType("string")
                .Mapping(ma => ma.SearchAsYouType(s => s))))));
```

It won't compile right now. Issue [spotted](https://stackoverflow.com/questions/59194687/how-to-map-dynamically-the-properties-of-a-jobject-in-c-sharp-using-elasticsearc) in this SO question.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Describe the feature**:

**Comment by russcam** [comment]
Thanks @robertlyson, I've opened https://github.com/elastic/elasticsearch-net/pull/4259
