### ISSUE TITLE
Missing "Updateable" property on filter descriptor in NEST

### ISSUE THREAD

**Issue by johanandrel** [elastic/elasticsearch-net#4252]
**NEST/Elasticsearch.Net version 7.4.1**:

**Elasticsearch version 7.4.1**:

**Add Updateable property to filter definitions in NEST**:

I am using NEST to setup a synonym_graph filter, but I am not able to define the filter as updateable so I can reload it through the "_reload_search_analyzers" endpoint (for reloadig synonym files). 

Example:

...SynonymGraph("synonym_graph", sg => sg.SynonymsPath("synonym_en.txt"))

As this does not have a "Updateable" property I cannot reload the synonyms as recommended here: https://www.elastic.co/blog/boosting-the-power-of-elasticsearch-with-synonyms

**Comment by russcam** [comment]
Thanks @johanandrel, I've opened https://github.com/elastic/elasticsearch-net/pull/4257

**Comment by johanandrel** [comment]
> Thanks @johanandrel, I've opened #4257

Great, thank you! Any hints on when version 7.5 of NEST will released? This is the only missing piece for a client solution :)

**Comment by bendikiv** [comment]
This is something I'm interested in as well!

**Comment by russcam** [comment]
We're aiming to have a 7.5.0 release out early next week. There's a few items on the 7.5 meta ticket https://github.com/elastic/elasticsearch-net/issues/4232 to tackle, and some other issues raised that we'd like to address for this release.
