### ISSUE TITLE
19 digit convert double - character problem

### ISSUE THREAD

**Issue by shz701** [elastic/elasticsearch-net#4285]
**NEST/Elasticsearch.Net version**:
NEST 7.4
**Elasticsearch version**:
7.3
**Description of the problem including expected versus actual behavior**:
return json string:
`buckets":[{"key":3515753798950990007,"doc_count":3}]`
after Json Serializer key:3.51575379895099E+18
code in AggregateFormatter.GetKeyedBucket ReadDouble 

The code is on line 773 of "AggregateFormatter.cs"

**Comment by russcam** [comment]
Thanks for opening @shz701. Please could you provide a more complete example of what you're doing? It looks like your issue is related to floating point rounding from `3515753798950990007` to `3.51575379895099E+18` (`3515753798950990000`), but some more detail will help

**Comment by shz701** [comment]
yes ,thank you

**Comment by russcam** [comment]
Reopening as this is an issue.

@shz701, Please could you provide a more complete example of what you're doing? It looks like you might be running a terms aggregation on a `double` field?

**Comment by shz701** [comment]
I have an id field that's a 19-digit number
