### ISSUE TITLE
Improve generator to use new REST API Specification format

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#4292]
The current ApiGenerator project uses the old REST API JSON structure, and passes the new structure through a transformation process:

https://github.com/elastic/elasticsearch-net/blob/1fb218fc5fed94c0a18eea2b94d597a03455e42a/src/CodeGeneration/ApiGenerator/Generator/ApiEndpointFactory.cs#L126

This was implemented in `7.4.0` as a means of ensuring the client release was not impeded, but we ought to move the project to use the new format directly.

**Comment by stevejgordon** [comment]
No longer needed due to schema.json!
