### ISSUE TITLE
BulkOperationsCollection Allocation Improvements?

### ISSUE THREAD

**Issue by MaJaHa95** [elastic/elasticsearch-net#4298]
**Context:**

Currently, `BulkOperationsCollection<T>` is implemented using a `private IList<T>`, along with some locking. The summary tag explains this:

>  This class is used by \<see cref="IBulkRequest.Operations" /\> which needs thread safe adding \<see cref="ICollection{T}.Add" /\> as well as an equivalent of \<see cref="List{T}.AddRange"/\>. Because operations from Elasticsearch are executed in order none of the types in System.Collection.Concurrent can't be used for this. We need to preserve insert order and exposed indexed index because \<see cref="BulkResponse.Items"/\> is ordered and lines up with \<see cref="BulkRequest.Operations"/\> allowing one to zip the two together.

That's fairly concise and specific, but I'm a bit confused by it.

It's pretty trivial in the scheme of things, but I can't help but notice the limitation this propriety type imposes.

**Questions:** 

1. What exactly is it about `IBulkRequest.Operations` that makes this thread-safe adding necessary? It's a nice enough helper class in general, but isn't it true that by the time it gets to the request itself, it's going to be effectively read-only? I wouldn't expect someone to add to the collection after they've called `BulkAsync`.

Here's the formatter, showing that it's just looping over the contents.

https://github.com/elastic/elasticsearch-net/blob/c646b98c5e5278ad122cd686fa27c45cbb18b919/src/Nest/Document/Multiple/Bulk/BulkRequestFormatter.cs#L26

2. Pending that, would it be possible to change `IBulkRequest.Operations` to be an `IList<IBulkOperation>`? Existing implementations should remain in-tact, but I could use (and re-use) an `IBulkOperation[]`.
3. If that's not possible, would it be possible to at least expose the `List<T>(int capacity)` constructor, so that I can avoid some unnecessary list expansion?

**Comment by russcam** [comment]
Going back through the commit history, operations was changed to be backed by a `SynchronizedCollection<T>` in https://github.com/elastic/elasticsearch-net/commit/f365429e923010bc7c7c6752349fb47a88c315c2, in response to https://github.com/elastic/elasticsearch-net/issues/223. I think @Mpdreamz probably knows more, but from recollection of conversations we've had about this, I _believe_ the problem in the issue surfaced from collecting the set of bulk operations concurrently. Whether this should still hold true for the next major, I'm not sure, but there's a possibility that changing it in 7.x could break someone.

> If that's not possible, would it be possible to at least expose the List<T>(int capacity) constructor, so that I can avoid some unnecessary list expansion?

This seems like a reasonable constructor to add

**Comment by Mpdreamz** [comment]
@russcam is bang on with why this was introduced. It was back in 2013 when we only had the descriptor syntax and there was a requirement for the backing data types to be threadsafe. 

Opened https://github.com/elastic/elasticsearch-net/pull/4674 to address this. 


I think the capacity contructor would be another good addition that we can backport to `7.x` and `6.x` 👍
