### ISSUE TITLE
How to query against multiple indices and handle different subclasses (mappings)?

### ISSUE THREAD

**Issue by dsonjohn** [elastic/elasticsearch-net#4306]
Hi every one,
I’m playing around with ElasticSearch(7.4.0) in combination with NEST(7.3.1) in my C# project. My use case includes several indices with different document mapping which I query separately so far. Now I wanna implement a global search function which queries against all existing indices.
So my question: How do I accomplish that by using NEST?
Maybe for a better understanding, this is the query I wanna realize with NEST:
` 
          
        var queryContainers = new List<QueryContainer>();
           
            if (totalFilter.HasTextFilter())
            {
                queryContainers.Add(QueryContainerHelper.GetQueryStringQuery($"*{totalFilter.Search}*",null));
            }

            
            var accountQueryContainers = new List<QueryContainer>();

            if (!totalFilter.UserIds.IsNullOrEmpty())
            {
                accountQueryContainers.Add(new BoolQuery()
                {
                    Must = new List<QueryContainer>()
                    {
                        new BoolQuery()
                        {
                            Filter = new List<QueryContainer>()
                            {
                                QueryContainerHelper.GetTermsQuery(totalFilter.InstagrmUserIds.OfType<object>().ToList(),Infer.Field<User>(i=>i.UserId)),
                                QueryContainerHelper.GetTermQuery(UserEntityType.Customer,Infer.Field<User>(i=>i.UserEntityType))
                            }
                        }
                    }
                });
            }
            
            var shouldAccountQuery = new BoolQuery()
            {
                Should = accountQueryContainers

            };

            queryContainers.Add(shouldAccountQuery);

            var mustQuery = new BoolQuery()
            {
                Must = queryContainers
            };
            var searchResponse = await _elasticClient.SearchAsync<object>(s => s.Query(q => mustQuery));
            
        
`

**Comment by russcam** [comment]
With different document mappings in each index, the generic type `T` in the high level `Search<T>()` call needs to be a type to which all the differently shaped JSON documents from each index can be deserialized into. 

You can use `dynamic` or `Elasticsearch.Net.DynamicDictionary` for this. If you're more comfortable with Json.NET, you can [hook it up as the serializer to use for your documents](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html#_jsonnetserializer), then use `JObject`.
