### ISSUE TITLE
Problem with mapping from elastic to C# object [nulls in object when _source have data]

### ISSUE THREAD

**Issue by patsadow2** [elastic/elasticsearch-net#4307]
How is it possible that NEST C# cannot map it poperly to object when it's not empty in query _source ?

![image](https://user-images.githubusercontent.com/19226186/71767129-2b8b9300-2f09-11ea-951f-48a8cdc2fd25.png)

Is it problem that everything should be lower case ? geolocation and id have normal data

**Comment by Mpdreamz** [comment]
The default casing NEST emits and expects to read is `camelCase`. You can influence this on `ConnectionSettings().DefaultFieldNameInferrer()` as documented here: https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/configuration-options.html

e.g ``ConnectionSettings().DefaultFieldNameInferrer(s => s)` will emit and read property names verbatim.

Or map the names explicitly through attribute mapping: https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/attribute-mapping.html

Hope this helps!
