### ISSUE TITLE
Support int type for track_total_hits search parameter

### ISSUE THREAD

**Issue by robertlyson** [elastic/elasticsearch-net#4316]
Hi guys :wave: 

**NEST/Elasticsearch.Net version**: 7.5.1

**Elasticsearch version**: 7.5

**Description of the problem including expected versus actual behavior**:

Elasticsearch [docs ](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/search-request-body.html#request-body-search-track-total-hits) mention there is a way to specify integer value for `track_total_hits` search parameter

> It is also possible to set track_total_hits to an integer. For instance the following query will accurately track the total hit count that match the query up to 100 documents:

 but looks like NEST accepts only bool value for it thus the following code won't compile 

```
await client.SearchAsync<object>(s => s.TrackTotalHits(100));
```

Reported [here](https://stackoverflow.com/questions/59736849/change-elasticsearch-track-total-hits-in-nest).

**Comment by andrx** [comment]
Duplicates #4241

**Comment by robertlyson** [comment]
@andrx right, thanks :)
