### ISSUE TITLE
Allow extending NEST token filters

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#4326]
Relates: https://github.com/elastic/elasticsearch-net/issues/3655#issuecomment-512823453

Allow support for extending token filters

**Comment by russcam** [comment]
opened #4328 to address

**Comment by jtreher** [comment]
@russcam Thanks for making this fix. Is this definitely going to make the cut for 7.6? I looked at the 7.6 meta and couldn't quite tell where you were with progress or if there was a target date. 

This is the only blocking issue preventing us from upgrading to 7.x from 6.x.

**Comment by russcam** [comment]
@jtreher It's now merged into 7.x mainline, for the 7.6.0 release. _If_ you wanted to try it out sooner than the release, take a look at our CI package feed:

https://ci.appveyor.com/nuget/elasticsearch-net

and look for the latest `7.6.0-ci*` package
