### ISSUE TITLE
Refactor Metric aggregations

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#4332]
As part of #4331, it looks like not all `IMetricAggregation` implementations support scripting i.e. the `Script` property 

https://github.com/elastic/elasticsearch-net/blob/4adf18a05ee51abdfa16e3e336bcdc40b4e48052/src/Nest/Aggregations/Metric/MetricAggregation.cs#L17

Going through the aggregation builder types in Elasticsearch, whether an aggregation supports scripting, formatting, etc. is controlled by declaring the supported fields on the parser. For example, for `MinAggregationBuilder`

https://github.com/elastic/elasticsearch/blob/17358b5af7b34a2b9a15846ba672f5a04001fcd5/server/src/main/java/org/elasticsearch/search/aggregations/metrics/MinAggregationBuilder.java#L48

```java
public class MinAggregationBuilder extends ValuesSourceAggregationBuilder.LeafOnly<ValuesSource.Numeric, MinAggregationBuilder> {
    public static final String NAME = "min";

    private static final ObjectParser<MinAggregationBuilder, Void> PARSER;
    static {
        PARSER = new ObjectParser<>(AvgAggregationBuilder.NAME);
        ValuesSourceParserHelper.declareNumericFields(PARSER, true, true, false); <---
    }

   ...
```

where the `bool` values are `scriptable`, `formattable` and `timezoneAware`, respectively.

Only the `IMetricAggregation` that support scripting should allow a `Script` property to be set. Going through the 7.x Java source, this is the support found

| agg name                      | scriptable         | formattable        |
| ----------------------------- | ------------------ | ------------------ |
| avg                           | :heavy_check_mark: | :heavy_check_mark: |
| cardinality                   | :heavy_check_mark: |  |
| extended_stats                | :heavy_check_mark: | :heavy_check_mark: |
| geo_centroid                  | :heavy_check_mark: |  |
| max                           | :heavy_check_mark: | :heavy_check_mark: |
| median_absolute_derivation    | :heavy_check_mark: | :heavy_check_mark: |
| min                           | :heavy_check_mark: | :heavy_check_mark: |
| percentile_ranks              | :heavy_check_mark: | :heavy_check_mark: |
| percentiles                   | :heavy_check_mark: | :heavy_check_mark: |
| stats                         | :heavy_check_mark: | :heavy_check_mark: |
| sum                           | :heavy_check_mark: | :heavy_check_mark: |
| value_count                   | :heavy_check_mark: | :heavy_check_mark: |

(timezone aware is not a column because it doesn't look to apply to metric aggs)
(metric aggregations omitted from the list do not support either script or format)

### Possible implementation

Derive an `IScriptableMetricAggregation` from `IMetricAggregation`, and `IFormattableMetricAggregation` from `IScriptableMetricAggregation`

```csharp
	public interface IMetricAggregation : IAggregation
	{
		Field Field { get; set; }

		[DataMember(Name ="missing")]
		object Missing { get; set; }
	}

	public interface IScriptableMetricAggregation : IMetricAggregation 
	{
		[DataMember(Name ="script")]
		IScript Script { get; set; }
	}

	public interface IFormattableMetricAggregation : IScriptableMetricAggregation 
	{
		[DataMember(Name ="format")]
		stringFormat { get; set; }
	}
``` 

NOTE: `Missing` should also be changed to `object`

**Comment by stevejgordon** [comment]
Code-gen should catch this for v8.
