### ISSUE TITLE
Bulk operations won't "fail fast"

### ISSUE THREAD

**Issue by tmenier** [elastic/elasticsearch-net#4334]
**NEST/Elasticsearch.Net version**:
6.8

**Elasticsearch version**:
6.6.1

**Description of the problem including expected versus actual behavior**:

When I send a bulk request operation and have throttled retries (I've tried small numbers and 0), I would expect the request to return immediately (or move on to the next operation) after the last retry. Instead, it seemingly continues to retry until the `Timeout` is hit.

**Steps to reproduce**:

I've tried to reduce as much as possible and only include relevant details:

```c#
var cli = new ElasticClient(new ConnectionSettings(...)
    .DefaultTypeName("my_type")
    .MaximumRetries(0));

var req = new BulkRequest {
    Operations = new[] {
        new BulkDeleteOperation<T>(id) {
            Index = "my_bad_index",
            RetriesOnConflict = 0
        }
    },
    Timeout = TimeSpan.FromSeconds(30)
};

var resp = await cli.BulkAsync(req);
```

In this overly simplistic example, I've specified 0 retries at both the connection level and operation level, and sent a single `delete` operation against an index that does not exist. It correctly reports a "no such index" error, **yet the operation uses up all its allotted 30 seconds every time**.  I've tried 1, 2, and 3 retries with the same result. This is hitting a single-node cluster on my local dev box and I would expect it to fail very fast.

**Provide `ConnectionSettings` (if relevant)**:
(See above)

**Provide `DebugInformation` (if relevant)**:
```
Invalid NEST response built from a successful low level call on POST: /_bulk?timeout=30s
# Invalid Bulk items:
  operation[0]: delete returned 404 _index: my_bad_index _type: my_type _id: xxxx _version: 0 error: Type: index_not_found_exception Reason: "no such index"
# Audit trail of this API call:
 - [1] HealthyResponse: Node: http://localhost:9200/ Took: 00:00:30.0339497
# Request:
{"delete":{"_id":xxxx,"_index":"my_bad_index","retry_on_conflict":0,"_type":"my_type"}}

# Response:
{"took":30000,"errors":true,"items":[{"delete":{"_index":"my_bad_index","_type":"my_type","_id":"xxxx","status":404,"error":{"type":"index_not_found_exception","reason":"no such index","index_uuid":"_na_","index":"my_bad_index"}}}]}
```

**Comment by russcam** [comment]
I'm getting the same result when running the following in Linqpad

```c#
private static void Main()
{
	var main = MainAsync();	
	main.Wait();	
	main.Result.DebugInformation.Dump();
}

public static async Task<IBulkResponse> MainAsync()
{
	var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
	var cli = new ElasticClient(new ConnectionSettings(pool)
		.DefaultTypeName("my_type")
		.MaximumRetries(0));

	var req = new BulkRequest
	{
		Operations = new[] {
		new BulkDeleteOperation<object>("foo") {
			Index = "my_bad_index",
			RetriesOnConflict = 0
		}
	},
		Timeout = TimeSpan.FromSeconds(30)
	};

	return await cli.BulkAsync(req);
}
```

The following is dumped to output

```
Invalid NEST response built from a successful low level call on POST: /_bulk?timeout=30s
# Invalid Bulk items:
  operation[0]: delete returned 404 _index: my_bad_index _type: my_type _id: foo _version: 0 error: Type: index_not_found_exception Reason: "no such index"
# Audit trail of this API call:
 - [1] HealthyResponse: Node: http://localhost:9200/ Took: 00:00:00.0361687
# Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# Response:
<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
```

and the query takes 0.039 seconds

![image](https://user-images.githubusercontent.com/208231/73426607-85547100-4380-11ea-9b22-8dc900325e43.png)

Can you share more about .NET version (Framework/Core and number) and platform (Windows/macOS/Linux variant)? If you have a small gist that reproduces what you're seeing, that would be super helpful.

**Comment by tmenier** [comment]
Thanks for the reply. I'm on Windows 10/Framework 4.7.2, and I do indeed get the same result as you when I run that. Even if I exclude `MaximumRetries` and `RetriesOnConflict`, or set both an obnoxiously high number, it still fails very quickly.

I'll do some more investigating but I should have isolated it completely the first time like you did before posting this. Sorry to have wasted your time. It's definitely taking as long as whatever I set that `Timeout` to in my "real" code, but there's got to be something I missed. I'll report back, thanks again for the help.

**Comment by tmenier** [comment]
Well, I can't even repro this in the real code anymore. Just for a little background, I'm in the middle of refactoring a highly concurrent system that builds search indexes. At one point an integration test started failing with the above error, but it consistently ran for a full minute before failing. Of course 60 seconds is the default Elasticsearch timeout, and when I brought that number down the test run time followed suit. I've since fixed the bug at the heart of the problem and moved on.

My theory is that at the time not only did I have a bug (deleting an index that didn't exist), but I suspect I was also consistently creating a deadlock and ES was killing it at the point of the timeout. Does that sound likely?

I'm fine with closing this because my code is in a better place and I'm not really inclined to go back to that revision and try to prove the theory, unless you have your doubts and think it would be valuable for me to investigate further.

**Comment by russcam** [comment]
Thanks for reporting back. 

The request might be being queued in a thread pool on Elasticsearch when under high load. That could explain taking longer, however, I don't think it would explain receiving a response after 30 seconds- I would have expected to receive a client timeout after 30 seconds, with an exception like `OperationCancelledException` (wrapped in a client exception).

I'm happy to close for now if it's not possible to reproduce the issue. Feel free to reopen though if you can reproduce it again 👍
