### ISSUE TITLE
SourceMany unexpected behavior

### ISSUE THREAD

**Issue by Fylhtq42** [elastic/elasticsearch-net#4342]
**NEST/Elasticsearch.Net version**: 7.3.0

**Elasticsearch version**: 7.2

**Description of the problem including expected versus actual behavior**:
I used Nest.IElasticClient for search by SourceMany and found some 
strange behavior. Api of method looks like you can send ids and you will get IEnumerable<Document> back. But if you send ["id1","id1","id1"] and Index contains one document with id = "id1", you will get 9 documents back instead of 3 for example. Because if you send multi get request to elastic api with 3 same ids you will get 3 documents in response. And I found that you have some join operation after elastic api response in MultiGetResponse.SourceMany, it creates duplicates.

**Steps to reproduce**:
 1. Save one document to index with Id = "id1"
 2. Call elasticClient.SourceMany<Document>(ids, IndexName);
 Ids = ["id1","id1","id1"]
 3. You get 9 documents back.

**Comment by russcam** [comment]
This does look like a bug, which we will look to fix.

**Comment by Fylhtq42** [comment]
Thank you for answering my issue, @russcam.
