### ISSUE TITLE
Unable to initialize ConnectionConfiguration in certain conditions

### ISSUE THREAD

**Issue by mozerov** [elastic/elasticsearch-net#4387]
I got the same issue as described here
https://github.com/elastic/elasticsearch-net/issues/4189#issue-515430503

But I got it in NEST/Elasticsearch.Net 6..8.3. Is it possible to release a fix for this issue in 6.x since we are not ready yet to switch to 7.x.

https://github.com/elastic/elasticsearch-net/blob/6.x/src/Elasticsearch.Net/Domain/RuntimeInformation.cs#L19

Thanks in advance.

**Comment by russcam** [comment]
Thanks @mozerov. Yes, the issue should be backported to 6.x and a new release put out

**Comment by mozerov** [comment]
Hi @russcam, do you have any idea when this can be released?

**Comment by codebrain** [comment]
@mozerov - this is going to be released into `6.8.4` very shortly. I will close this issue as the related PR was merged: https://github.com/elastic/elasticsearch-net/pull/4390
