### ISSUE TITLE
Question: Multiple iteration of IEnumerable

### ISSUE THREAD

**Issue by LordMike** [elastic/elasticsearch-net#4388]
I was looking into making a logging of requests, and stumbled upon this.

https://github.com/elastic/elasticsearch-net/blob/60360565440eb9db8b7ebf8a4503d745f6345a12/src/Elasticsearch.Net/Transport/PostData.cs#L202-L205

In this, we can see that the IEnumerable is "opened" (`GetEnumerator`) multiple times. In this world of yield-enumerables, there is a significant risk that a user may provide a very costly method of iterating data. Perhaps the enumerable came from a database, and doing a `.HasAny()` followed by iterating it, could cause a query to happen twice.

I'd recommend that cases like these, get the enumerator from the IEnumerable, and then iterate it once to see if there's data. If there is, it can use that first result, along with any new results, to send to the target.

This way, you call `GetEnumerator` once, and don't risk performing two costly operations.

Sidenote: C# really should have used `IEnumerator` more .. alas..

**Comment by codebrain** [comment]
Thanks for raising @LordMike - it is true, some of these extension methods could have their logic inlined on some of the hot paths.

@Mpdreamz @russcam - how do you feel about moving towards in-lining some of the logic? Maybe something like the below?

```
case PostType.EnumerableOfObject:
	if (_enumerableOfObject == null) return;
	var initBuffer = true;
	foreach (var o in _enumerableOfObject)
	{
		if (initBuffer)
		{
			BufferIfNeeded(settings, ref buffer, ref stream);
			initBuffer = false;
		}
		settings.RequestResponseSerializer.Serialize(o, stream, SerializationFormatting.None);
		stream.Write(NewLineByteArray, 0, 1);
	}
	break;
```

 I think that a simple bool check on each iteration is better than the possibility of a re-iterating the `IEnumerable<>` twice, and likely more preferable than allocating into a `List<T>`...

**Comment by russcam** [comment]
I quite like the approach that @LordMike proposes. Something like

```c#
case PostType.EnumerableOfObject:
{
	if (_enumerableOfObject == null)
		return;

	using var enumerator = _enumerableOfObject.GetEnumerator();
	if (!enumerator.MoveNext())
		return;

	BufferIfNeeded(settings, ref buffer, ref stream);
	do
	{
		var o = enumerator.Current;
		settings.RequestResponseSerializer.Serialize(o, stream, SerializationFormatting.None);
		stream.Write(NewLineByteArray, 0, 1);
	} while (enumerator.MoveNext());
	break;
}
```

**Comment by LordMike** [comment]
I've found that @russcam's code example, is more readable and skips the if-evaluation on each iteration of the loop - so I'd personally go with that. :)
