### ISSUE TITLE
Unable to compile UWP App with .Net Native toolchain

### ISSUE THREAD

**Issue by dreeri** [elastic/elasticsearch-net#4389]
Thanks a lot for great work on the software! Really appreciating your efforts.

**Elasticsearch.Net version**: 7.0.0

**Elasticsearch version**: 7.5.1

**Description of the problem including expected versus actual behavior**:

Expected: I build my UWP application with "Compile with .NET Native Tool Chain" enabled and I am able to log to my Elasticsearch index.

Actual: No logging is happening unless "Compile with .NET Native Tool Chain" is disabled.

RtlGetVersion function seems to be the culprit as it is not supported on UWP:
https://github.com/elastic/elasticsearch-net/blob/master/src/Elasticsearch.Net/Api/NativeMethods.cs

We are logging over the Serilog.Sinks.Elasticsearch but the error seems to spring up on elasticsearch-net level. Should there be an alternative implementation for getting the version information in UWP projects? What do you think would be the optimal solution for using elasticsearch-net in UWP applications?

**Steps to reproduce**:
 1. Set a UWP project to compile with .NET Native Tool Chain toggled on
 2. Compile the project with elasticsearch-net references
 3. Try to log to elasticsearch

**Provide `DebugInformation`**:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning
MCG : warning MCG0007: Unresolved P/Invoke method 'ntdll!RtlGetVersion' for method 'System.Int32 Elasticsearch.Net.NativeMethods.Windows.RtlGetVersion(Elasticsearch.Net.NativeMethods.Windows.RTL_OSVERSIONINFOEX)'.
Calling this method would throw exception at runtime. Please make sure the P/Invoke either points to a Windows API allowed in UWP applications, or a native DLL that is part of the package. If for some reason your P/Invoke does not satisfy those requirements, please use
[DllImport(ExactSpelling=true) to indicate that you understand the implications of using non-UWP APIs.
```

**Similar issues and additional info**:
https://github.com/Azure/azure-libraries-for-net/issues/697
https://github.com/Azure/azure-cosmos-dotnet-v2/issues/625
https://github.com/serilog/serilog-sinks-elasticsearch

**Comment by russcam** [comment]
First of all, thank you for the detailed issue!

`RtlGetVersion` may be one problem. Wondering if we can put some guard around this. The value is used to get runtime information to include in the default User agent string, which I think we could lazily resolve as well, so it'll be called if needed.

A larger problem that I foresee though is that Utf8Json, the underlying serialization library forked and included in the client, makes heavy use of `Reflection.Emit` to generate IL, which as far as I understand, is not supported on UWP (https://github.com/dotnet/runtime/issues/26379). We don't have _immediate_ plans to change using Utf8Json. Longer term, we have discussed and are keen to utilize System.Text.Json, but this is would be in the next major version at the very earliest.

An approach that should work, would be to use the low level client with an `IElasticsearchSerializer` based on a JSON serialization library works in UWP e.g. JSON.NET. Granted, you won't have strongly typed requests and responses as these are tied to the internal serializer, but you would at least still have all of the APIs, their paths and parameters exposed on the client to use.

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Please let us know if this issue is still a relevant priority for your usage?
