### ISSUE TITLE
RankQueryQueryFormatter generates incorrect JSON

### ISSUE THREAD

**Issue by gkinsman** [elastic/elasticsearch-net#4392]
**NEST/Elasticsearch.Net version**:
NEST 7.5.1

**Elasticsearch version**:
7.6.0

**Description of the problem including expected versus actual behavior**:
If no function is selected, then the JSON formatter will still add a comma after the field name:
https://github.com/elastic/elasticsearch-net/blob/453a60862503e9ad7daa47ccb488277dad817d76/src/Nest/QueryDsl/Specialized/RankFeature/RankFeatureQuery.cs#L189-L206

**Steps to reproduce**:
1. Create an index with a rank_feature field
2. Add some docs to the index with field values
3. Query for a single field without a Function parameter.
4. Query generated will look like: `{"query":{"rank_feature":{"field":"field.prop",}}}` - note the extra comma.
```

**Comment by russcam** [comment]
Thanks @gkinsman, will address this in the next release.
