### ISSUE TITLE
For custom analyzer position_offset_gap renamed to position_increment_gap

### ISSUE THREAD

**Issue by AlexMihalev** [elastic/elasticsearch-net#4394]
**NEST/Elasticsearch.Net version**: 7.4.1

**Elasticsearch version**: 7.3.0

The position_increment_gap can't be specified in the case of the custom analyzer. Only **PositionOffsetGap** (see **ICustomAnalyzer.PositionOffsetGap**) is available but it looks like its **deprecated** and ignored by Elastic Search (see https://www.elastic.co/guide/en/elasticsearch/reference/7.5/analysis-custom-analyzer.html#)

Seems it has been renamed to position_increment_gap.

**Comment by codebrain** [comment]
Ported to `7.x` and `7.6`
