### ISSUE TITLE
Bug in distance_feature query

### ISSUE THREAD

**Issue by DavidRouyer** [elastic/elasticsearch-net#4487]
**NEST/Elasticsearch.Net version**: 7.6

**Elasticsearch version**: 7.6

**Description of the problem including expected versus actual behavior**:
I'm trying to use the `distance_feature` query, but it looks like the generated JSON is broken. I'm getting the following error: `Unexpected character ('}' (code 125)): was expecting double-quote to start field name\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@725045c0; line: 11, column: 7]`

**Steps to reproduce**:
 1. Use a query like
```csharp
            ElasticClient.SearchAsync<MyIndex>(
                s => s
                .Sort(so => so.Descending(SortSpecialField.Score))
                .From(skip)
                .Size(take)
                .Query(
                    q =>
                        q.Bool(b => b
                            .Should(s =>
                                s.DistanceFeature(f => f
                                    .Field(f => f.WorkshopAddress.Location)
                                    .Pivot(new Distance(200, DistanceUnit.Kilometers))
                                    .Origin(new GeoCoordinate(latitude, longitude)))))
                       ),
                cancellationToken);
```
 2. The generated JSON looks like:
```json
{
	"from":0,
	"query":{
		"bool":{
			"should":[
				{
					"distance_feature":{
						"field":"workshopAddress.location",
						"origin":[48.8697246,2.3061506],
						"pivot":"200km",
					}
				}
			]
		}
	},
	"size":20,
	"sort":[
		{
			"_score":{
				"order":"desc"
			}
		}
	]
}
```
instead of: (There is an extra comma)
```json
{
	"from":0,
	"query":{
		"bool":{
			"should":[
				{
					"distance_feature":{
						"field":"workshopAddress.location",
						"origin":[48.8697246,2.3061506],
						"pivot":"200km"
					}
				}
			]
		}
	},
	"size":20,
	"sort":[
		{
			"_score":{
				"order":"desc"
			}
		}
	]
}
```

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by russcam** [comment]
Thanks for reporting @DavidRouyer, I've opened https://github.com/elastic/elasticsearch-net/pull/4488 to address
