### ISSUE TITLE
Support for multifields via attributes

### ISSUE THREAD

**Issue by OndrejPiza** [elastic/elasticsearch-net#4501]
Hi,

is it possible to map multifields via attributes in POCO? 

Right now I cannot use fluent mapping. I have two independent services which communicates over rabbit. As I found out, I can directly map each specific object type by client fluent mapping but that would introduce dependency to second service because it would has to have knowledge of all services is using it or might in the future and also it has to have such POCO objects in its code.

Via attributes it looked like a decent level of decoupling. But I cannot create client on first service.

Is there way how to achieve that?

Thank you for any advice

**Comment by russcam** [comment]
The issue with attribute mapping is that C# Attributes are limited to properties that accept constant values, which makes it tricky to express all properties available on Elasticsearch field datatype mappings.

Looking at the problem from another angle, it sounds like [index templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html) and [dynamic templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html) may be an option here?

**Comment by russcam** [comment]
Thanks for opening @OndrejPiza. It is unlikely that multifields will be configurable through attributes. 

[Multifields can be configured through fluent mapping](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/multi-fields.html), or can be applied through convention using [index templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html) and [dynamic templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html).
