### ISSUE TITLE
ElasticClient.Indices.Refresh throwing a NullReferenceException

### ISSUE THREAD

**Issue by Friedenspanzer** [elastic/elasticsearch-net#4527]
**NEST/Elasticsearch.Net version**: 7.6.1

**Elasticsearch version**: 7.6.1

**Description of the problem including expected versus actual behavior**:

When calling the method ElasticClient.Indices.Refresh with a not existing index it is throwing a general NullReferenceException with a nondescript error message.

**Expected behavior**

I'd expect the following code (where `client` is a valid ElasticClient) to return an invalid result or at least run the exception handler.

```
try
{
    var result = client.Indices.Refresh("SomeIndex");
}
catch (ElasticsearchClientException ex) { }
```

**Comment by russcam** [comment]
@Friedenspanzer I can't replicate the null reference exception. Here's my simple example with NEST 7.6.1

```c#
private static void Main()
{
	var pool = new SingleNodeConnectionPool(new Uri($"http://localhost:9200"));
    var settings = new ConnectionSettings(pool);
    var client = new ElasticClient(settings);
	
	try
	{
		var result = client.Indices.Refresh("foo");
	}
	catch
	{
		Console.WriteLine("caught an exception");
	}
}
```

`"caught an exception"` is never written. Setting `.ThrowExceptions()` on `ConnectionSettings` still does not result in an error thrown.

Can you provide a minimum example that reproduces what you're seeing?

**Comment by Friedenspanzer** [comment]
So this is a bit embarrassing. When trying to to create a more elaborate example I noticed it actually stopped happening for me because it was dependent on a very small detail in my setup that made the error so obvious I didn't even think to double check.

This should not happen in nearly all circumstances and I'm horribly sorry for not checking before.

**Comment by russcam** [comment]
No worries, @Friedenspanzer, happens to all of us :)
