### ISSUE TITLE
change default Serializer

### ISSUE THREAD

**Issue by laosandegudai** [elastic/elasticsearch-net#4531]
**NEST/Elasticsearch.Net version**:6.7

**Elasticsearch version**:6.7.1

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 I want change  elasticsearch-net  default Serializer,  But i found  its a  func,

![image](https://user-images.githubusercontent.com/17979159/78003388-25238080-736b-11ea-896d-60c8df33cc73.png)
if  InternalSerializer  is internal, in func i dont change  it, so  i dont change seThisRequestResponseSerializer

**Comment by russcam** [comment]
@laosandegudai [serialization can be changed](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html) with

```c#
public class MySerializer: IElasticsearchSerializer
{
    public T Deserialize<T>(Stream stream) => throw new NotImplementedException();

    public object Deserialize(Type type, Stream stream) => throw new NotImplementedException();

    public Task<T> DeserializeAsync<T>(Stream stream, CancellationToken cancellationToken = default(CancellationToken)) =>
        throw new NotImplementedException();

    public Task<object> DeserializeAsync(Type type, Stream stream, CancellationToken cancellationToken = default(CancellationToken)) =>
        throw new NotImplementedException();

    public void Serialize<T>(T data, Stream stream, SerializationFormatting formatting = SerializationFormatting.Indented) =>
        throw new NotImplementedException();

    public Task SerializeAsync<T>(T data, Stream stream, SerializationFormatting formatting = SerializationFormatting.Indented,
        CancellationToken cancellationToken = default(CancellationToken)) =>
        throw new NotImplementedException();
}

var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
var connectionSettings = new ConnectionSettings(
    pool,
    sourceSerializer: (builtin, settings) => new MySerializer()); 
var client = new ElasticClient(connectionSettings);
```

The above changes the _source_ serializer, the serializer used to serialize and deserialize your documents and associated API properties.

The internal serializer cannot be changed; the internal serializer is the _request response serializer_, which the client uses to serialize and deserialize client requests and responses to Elasticsearch (excluding those items serialized by the _source_ serializer). As such, it is not possible to change this serializer as it could result in making changes that break client functionality.

**Comment by laosandegudai** [comment]
yes,I have done it in my work,but  I don't know what he means about SourceSerializerFactory in IConnectionConfigurationValues.

**Comment by russcam** [comment]
`SourceSerializerFactory` is a delegate that will be invoked to create a source serializer

https://github.com/elastic/elasticsearch-net/blob/1dc2e5039a12ffcc80c9bee79e59b327ffe129b8/src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs#L22-L26

**Comment by laosandegudai** [comment]
> `SourceSerializerFactory` is a delegate that will be invoked to create a source serializer
> 
> https://github.com/elastic/elasticsearch-net/blob/1dc2e5039a12ffcc80c9bee79e59b327ffe129b8/src/Nest/CommonAbstractions/ConnectionSettings/ConnectionSettingsBase.cs#L22-L26

` InternalSerializer internalSerializer = new InternalSerializer(this);
            _sourceSerializer = (sourceSerializerFactory?.Invoke(internalSerializer, this) ?? internalSerializer);
            base.UseThisRequestResponseSerializer = internalSerializer;`

yes,I don't change internalSerializer by  sourceSerializerFactory,because  internalSerializer is internal

**Comment by russcam** [comment]
You can't change `internalSerializer` as it's used by the client to serialize its own request and response types. In much older versions of the client where this was possible, users could end up changing the serializer in a way which breaks client functionality, hence the reason the internal serializer cannot be changed.

You can change the serializer that serializes your documents however, using `SourceSerializerFactory`

**Comment by laosandegudai** [comment]
Tank you very much.
