### ISSUE TITLE
[UpdateRequest] doc doesn't support values of type: START_ARRAY

### ISSUE THREAD

**Issue by SLavrynenko** [elastic/elasticsearch-net#4576]
**NEST/Elasticsearch.Net version**:
7.6.1

**Elasticsearch version**:
7.6.1

**Description of the problem including expected versus actual behavior**:
Here is the code that Im using for bulk update:

```
                    var client = GetElasticClient(settings.ElasticServerConnection, true);
                    var descriptor = new BulkDescriptor();

                    BulkResponse bulkResult = null;
                        foreach (var item in items)
                            descriptor.Update<ContactElastic, object>(
                                op => op
                                    .Index(settings.ElasticIndex)
                                    .Id(item.Id)
                                    .Doc((object)item.ExportModel)
                                    .RetriesOnConflict(settings.RetriesOnConflict)
                                    .DocAsUpsert());
                        bulkResult = client.Bulk(descriptor);
                    );

```
Here is what I see in a descriptor (image):

![VS_Debug](https://user-images.githubusercontent.com/16493827/78993754-19904080-7b47-11ea-9c93-fce35aaadc4c.jpg)

so you can see that I have a valid objects that are not empty. But at the end Ive got an error that you can see in the *DebugInformation* section and it looks like all my objects are empty?
We are moving from an earlier version of NEST and it was working fine there. Is it something related to a serializer? As all my objects are of a Newtonsoft.Json.Linq.JObject type.

**Provide `DebugInformation` (if relevant)**:
Invalid NEST response built from a unsuccessful (400) low level call on POST: /_bulk
# Invalid Bulk items:
# Audit trail of this API call:
 - [1] BadResponse: Node: xxxxxxxxxx/ Took: 00:00:01.1243509
# OriginalException: Elasticsearch.Net.ElasticsearchClientException: The remote server returned an error: (400) Bad Request.. Call: Status code 400 from: POST /_bulk. ServerError: Type: x_content_parse_exception Reason: "[1:29] [UpdateRequest] doc doesn't support values of type: START_ARRAY" ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at Elasticsearch.Net.HttpWebRequestConnection.Request[TResponse](RequestData requestData)
   --- End of inner exception stack trace ---
# Request:
{"update":{"_id":"9349_6751647","_index":"XXXXXXXX"}}
{"doc_as_upsert":true,"doc":[[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]]]}
{"update":{"_id":"9349_6752400","_index":"XXXXXXXX"}}
{"doc_as_upsert":true,"doc":[[[[[]],[[]]]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]],[[]]]}

**Comment by russcam** [comment]
> As all my objects are of a Newtonsoft.Json.Linq.JObject type.

You'll need to use the [`Nest.JsonNetSerializer` nuget package](https://www.nuget.org/packages/NEST.JsonNetSerializer) and hook up the [`JsonNetSerializer`](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html#_jsonnetserializer) as the serializer to use for your documents

```c#
var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));

var connectionSettings =
    new ConnectionSettings(pool, sourceSerializer: JsonNetSerializer.Default);

var client = new ElasticClient(connectionSettings);
```

Using this client with the bulk operations above should work as expected.

Essentially, the internal serializer has no understanding of how to serialize `JObject` types, which require specific serialization routines that are implemented in Json.NET.

**Comment by russcam** [comment]
I'm closing this issue as I think it resolves the issue. if you’re still in need of resolution @SLavrynenko, feel free to re-open and we'd be glad to help you out 👍
