### ISSUE TITLE
Error	CS1503	Argument 1: cannot convert from 'Person' to 'Nest.IIndexRequest<Person>'

### ISSUE THREAD

**Issue by kobosh** [elastic/elasticsearch-net#4577]
**NEST/Elasticsearch.Net version**: 7.6.1

**Elasticsearch version**: 7.6.2

**Description of the problem including expected versus actual behavior**:
I am following through with [this](https://www.elastic.co/guide/en/elasticsearch/client/net-api/1.x/nest-quick-start.html) in visual studio 2019 community. I get compile error when trying to construct settings as :   new ConnectionSettings( node ,defauktIndex:"myapp"): I comment out error portion and add defaultIndex to settings.  settings.DefaultIndex("myapp"); 

**Steps to reproduce**:
 1.create console app and add Nest  version 7.6.1 which automatically adds Elasticsearch.Net (7.6.1) 
 2.add Person poco entity  and try to index  new Person
 3. I get compile error as shown in title.

**Expected behavior**
Be able to index new person document into "myapp" index in elastic cluster;

 

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by russcam** [comment]
The documentation linked to is for NEST 1.x; [please use the documentation for NEST 7.x](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/nest-getting-started.html#_indexing_2), which uses the `IndexDocument()` method when only a document is passed
