### ISSUE TITLE
FieldStatistics.cs class has int values but can get from indexes long values

### ISSUE THREAD

**Issue by guille11gg** [elastic/elasticsearch-net#4578]
**NEST/Elasticsearch.Net version**: 7.6.1

**Elasticsearch version**: 6.8

**Description of the problem including expected versus actual behavior**:
This class is getting integers in all their properties: https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Document/Single/TermVectors/FieldStatistics.cs
Can be the case, when you do a termVectors query, those number are bigger than an integer (long).

**Steps to reproduce**:
 1. Query to termVectors: POST https://host/index/_mtermvectors 
 2. An exception is triggered: "Unhandled exception when processing list: efefdb47-0aaf-4244-9c96-7e971cba3c46. - Elasticsearch.Net.UnexpectedElasticsearchClientException: JSON integer 2320738168 is too large or small for an Int32. Path 'docs[0].term_vectors.abstractFull.field_statistics.sum_ttf'

**Expected behavior**
Be able to map all properties.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by russcam** [comment]
Thanks for opening @guille11gg.

Looking at [`FieldStatistics` in Elasticsearch source](https://github.com/elastic/elasticsearch/blob/4d58656065af81b1e333f17347c150b4309d299f/client/rest-high-level/src/main/java/org/elasticsearch/client/core/TermVectorsResponse.java#L249-L251), `SumOfDocumentFrequencies` and `SumOfTotalTermFrequencies` should be `long`.

Changing these to `long` in 7.x would technically be a breaking change. I see a couple of options:

1. Accept the breaking change in a minor version, as impact in doing so is likely low. For clarity, the semantic versioning of the library is bound to the versioning of Elasticsearch.
2. Introduce `SumOfDocumentFrequenciesLong` and `SumOfTotalTermFrequenciesLong` `long` type properties to deserialize to, with existing `int` properties returning these values.

**Comment by codebrain** [comment]
Technically a breaking change, but I suspect moving from `int` to `long` in this case should be of limited impact. My vote for 1.

**Comment by russcam** [comment]
I'm +1 on changing them to `long` too

**Comment by guille11gg** [comment]
Hi all,

Will the fix of this bug release in v.7.7.0?

What´s the date expected of that release?

thanks a lot.

**Comment by russcam** [comment]
hi @guille11gg, I'm looking at putting a new 7.x release out today

**Comment by russcam** [comment]
@guille11gg 7.6.2 is now released to nuget with this fix: https://www.nuget.org/packages/NEST/7.6.2
