### ISSUE TITLE
NEST swallows part of an aggregation value

### ISSUE THREAD

**Issue by mausch** [elastic/elasticsearch-net#4582]
**NEST/Elasticsearch.Net version**: 6.8.1

**Elasticsearch version**: 6.7

I have a filter aggregation where one of the values in the response is "ff3046ce-e547-46b6-8ffb-44832bd8c2ad c# .net".
When I read that response with NEST it says the value is " .net". That is, it swallows the first part of the value for some reason.

This seems to be related to https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Aggregations/AggregateDictionary.cs#L16-L34 which I see is used in the serializer https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Aggregations/AggregateDictionaryFormatter.cs#L31 to handle the `typed_keys` parameter, but regardless of what this is set to in the request, this serializer seems to behave the same?
Are there any workarounds? Can this serializer be overriden somehow?

Thanks

EDIT: I'm using NEST 6.x here but the code I'm linking to is still in master so i'm pretty sure this still happens in the latest versions of NEST.

**Comment by Mpdreamz** [comment]
Hey @mausch are you able capture the response with DebugInformation() on connectionsettings and share it with us.

Would help us to create a repro faster. Thanks!

**Comment by mausch** [comment]
Yep, here you go https://github.com/mausch/es-net-4582

**Comment by russcam** [comment]
Thanks @mausch, opened https://github.com/elastic/elasticsearch-net/pull/4656 to address

**Comment by Mpdreamz** [comment]
We just released a path to our `6.x` clients: 

https://github.com/elastic/elasticsearch-net/releases/tag/6.8.6

This should have the parser fix, thanks again for bringing this to our attention @mausch
