### ISSUE TITLE
Add max_children to nested sort

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#4595]
Relates: https://discuss.elastic.co/t/net-client-include-max-children-property-in-nested-sorting/161472

`NestedSort` is currently missing a `MaxChildren` property. This should be added.

**Comment by NataliyaV** [comment]
Thanks, really needed stuff!
Any info when there will be a new release containing it?

**Comment by russcam** [comment]
It's in NEST 6.8.6 if you're using 6.x. For 7.x, there should be a new package out very soon

**Comment by NataliyaV** [comment]
> It's in NEST 6.8.6 if you're using 6.x. For 7.x, there should be a new package out very soon

Maybe any details about the dates? Just considering if it's reasonable to write by ourselves.
Thank you.

**Comment by russcam** [comment]
@NataliyaV I'm looking at putting a new 7.x release out today

**Comment by russcam** [comment]
@NataliyaV 7.6.2 is now released to nuget: https://www.nuget.org/packages/NEST/7.6.2

**Comment by NataliyaV** [comment]
> @NataliyaV 7.6.2 is now released to nuget: https://www.nuget.org/packages/NEST/7.6.2

Thank you @russcam ! Awesome
