### ISSUE TITLE
Installation failed (Windows Server 2016). Can't connect to elasticsearch client. Elastic [7.5.0], Nest [7.5.1]

### ISSUE THREAD

**Issue by AlexanderAnatolich** [elastic/elasticsearch-net#4681]
Hello.
I encountered the problem of deploying "elasticsearch" on an Azure virtual machine running Windows Server 2016 Datacenter.
My API is written in .Net Core 3.1. When I try to connect to the "elasticsearch" client https://prnt.sc/qdflqr, I get the error https://prnt.sc/qdfjr4.
With this, the same configurations work successfully under Windows 10 both on the local machine and on the VirtualBox virtual machine (Windows 10).
I try to solve this problem more two days. Disabling the firewall does not solve this problem.
During installation, I did not set any passwords.
If I do this, then I get an installation error. It can be see from the logs that during the installation, attempts to connect to the "elasticsearch" client are unsuccessful.
I disabled security. But the result has not changed. https://prnt.sc/qdgmtb
[Log.txt](https://github.com/elastic/windows-installers/files/3987497/Log.txt)

**Comment by ygel** [comment]
I moved this issue here since it's more about NEST and connections than about install experience, thanks!

**Comment by russcam** [comment]
@AlexanderAnatolich please can you copy/paste code into the issue using ``` around a block of code, or highlighting and using the `<>` button. Looking at code or errors in images makes it hard to read and isn't searchable in future.

The node is configured with Basic security enabled, but the client is not configured with any credentials to use when connecting to the cluster, so a HTTP 401 response is returned

![image](https://user-images.githubusercontent.com/208231/82778785-bc054880-9e95-11ea-8461-ca31d8d5b3ae.png)

Credentials can be provided to the client using `.BasicAuthentication()` or `.ApiKeyAuthentication()` on `ConnectionSettings`.

This provides the anonymous user with superuser access:

![image](https://user-images.githubusercontent.com/208231/82778979-4baaf700-9e96-11ea-8cc2-23a1ddc3e5f3.png)

which I would **not recommend**, as it allows anyone to do anything in Elasticsearch. I would recommend creating a user or an API key for the client to use to connect to the cluster, using the built-in `elastic` superuser to set up any other users or API keys that you need to.
