### ISSUE TITLE
How to create roll over policy in elastic search from asp.net core application?

### ISSUE THREAD

**Issue by LalJohnGeon** [elastic/elasticsearch-net#4688]
**NEST/Elasticsearch.Net version**: 6.8.6

**Elasticsearch version**: 6.6.0

**Description of the problem including expected versus actual behavior**:
I want to create a rollover policy from asp.net core application. Is there any way to implement this

**Comment by russcam** [comment]
Hi @LalJohnGeon, Index Lifecycle Management (ILM) is supported in the 6.8.6 client. For example

```c#
var client = new ElasticClient(settings);

var putLifecycleResponse = client.PutLifecycle("policy_id", p => p
    .Policy(po => po
        .Phases(a => a
            .Cold(w => w
                .Actions(ac => ac
                    .Freeze(f => f)
                    .SetPriority(f => f.Priority(50))
                )
            )
            .Warm(w => w
                .MinimumAge("10d")
                .Actions(ac => ac
                    .ForceMerge(f => f.MaximumNumberOfSegments(1))
                )
            )
            .Delete(w => w
                .MinimumAge("30d")
                .Actions(ac => ac
                    .Delete(f => f)
                )
            )
        )
    )
);
```

which sends the following request

```json
PUT /_ilm/policy/policy_id
{
  "policy": {
    "phases": {
      "warm": {
        "min_age": "10d",
        "actions": {
          "forcemerge": {
            "max_num_segments": 1
          }
        }
      },
      "cold": {
        "actions": {
          "freeze": {},
          "set_priority": {
            "priority": 50
          }
        }
      },
      "delete": {
        "min_age": "30d",
        "actions": {
          "delete": {}
        }
      }
    }
  }
}
```


We reserve GitHub Issues for bug reports and feature requests. The best place to ask questions is the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Not only do more folks view the forums than the GitHub Issues list, and hence it is more likely to receive attention, but the forums are also geared towards being able to search previous questions and answers, making it a much more valuable archive for future question askers.

Thanks!

**Comment by brenthompson2** [comment]
How to do this in the 8.x client?
