### ISSUE TITLE
Nest DateHistogramCompositeAggregationSource does not have CalendarInterval and FixedInterval

### ISSUE THREAD

**Issue by mehdimadani** [elastic/elasticsearch-net#4695]
**Interval** is deprecated on version 7.2.0 and `DateHistogramCompositeAggregationSource` does not support **FixedInterval** and **CalendarInterval**. 

These properties already implemented in `DateHistogramAggregation` but not in `DateHistogramCompositeAggregationSource` class.

Using Interval generates warning on each response.

**Comment by russcam** [comment]
Thanks for opening @mehdimadani, will look to add
