### ISSUE TITLE
BulkAll

### ISSUE THREAD

**Issue by lcb1208** [elastic/elasticsearch-net#4698]
Today I occur this problem. When use BulkAll data,  BulkAllObservable.RefreshOnCompleted throw exception"Refreshing after all documents have indexed failed",I think it's so abstract description for error.why not return detail error message, like es server unauthorized...

**Comment by russcam** [comment]
`RefreshOnCompleted` throws an `ElasticsearchClientException`

https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs#L112

and 

https://github.com/elastic/elasticsearch-net/blob/f1ffbf260132eb83ea4e7950c1bcf19ef679ee6f/src/Nest/Document/Multiple/BulkAll/BulkAllObservable.cs#L227-L228

which has a `DebugInformation` property on it with details about the audit trail, etc.

https://github.com/elastic/elasticsearch-net/blob/f1ffbf260132eb83ea4e7950c1bcf19ef679ee6f/src/Elasticsearch.Net/Exceptions/ElasticsearchClientException.cs#L31

So it would be possible to see if an exception is an instance of `ElasticsearchClientException` and inspect/log these details, inspect the `IApiCallDetails` response property, etc. 

I _think_ `DebugInformation` is not built ahead of time and passed as the message as it's intended to be human readable and it's relative expensive to build.
