### ISSUE TITLE
Cat.Allocation field mismatch

### ISSUE THREAD

**Issue by dpaissan** [elastic/elasticsearch-net#4699]
**NEST/Elasticsearch.Net version**:7.7.0

**Elasticsearch version**:7.7.0

**Description of the problem including expected versus actual behavior**:
When Cat.Allocation is called, no information about the allocation is actually returned. I think that the mapping in [this file](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Cat/CatAllocation/CatAllocationRecord.cs) is wrong/outdated.
From what I receive from Elasticsearch, the name should be separed with a dot instead of camel case: e.g. "disk.avail" instead of "diskAvail".

**Steps to reproduce**:
 1.Just call client.Cat.Allocation() and inspect the response.

**Expected behavior**
I expect the API call to return the allocation information.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by russcam** [comment]
Thanks for opening @dpaissan, this does look like a bug. The available values should be (left column)

```
shards       | s              | number of shards on node
disk.indices | di,diskIndices | disk used by ES indices
disk.used    | du,diskUsed    | disk used (total, not just ES)
disk.avail   | da,diskAvail   | disk available
disk.total   | dt,diskTotal   | total capacity of all volumes
disk.percent | dp,diskPercent | percent disk used
host         | h              | host of node
ip           |                | ip of node
node         | n              | name of node
```

**Comment by russcam** [comment]
opened #4705 to address
