### ISSUE TITLE
Feature Add Lifecyle policy creation

### ISSUE THREAD

**Issue by DR9885** [elastic/elasticsearch-net#4701]
**Is your feature request related to a problem? Please describe.**
Elastic Client is unable to setup full lifecycle policy. 
REF: https://www.elastic.co/guide/en/elasticsearch/reference/master/set-up-lifecycle-policy.html

Problem 1) PutTemplate has no way to set "index.lifecycle.name" nor is it able to set "index.lifecycle.rollover_alias". 

Problem 2) Indices.Create has no way to set "aliases.$NAME.is_write_index".

**Describe the solution you'd like**
Solution for Problem 1)
```
            var template = client.Indices.PutTemplate(templateId, t => t
                .IndexPatterns(aliasId + "-*")
                .Settings(s => s
                    .Lifecycle(lc =>
                        lc.Name(policyId)
                            .RolloverAlias(aliasId)
                    )
                )
            );
```
Solution for Problem 2)
```
            var index = client.Indices.Create(aliasId + "-000001", c => c
                .Aliases(x =>
                    x.Alias(a => 
                        a.Name(aliasId)
                            .IsWriteIndex(true)
                    )
                )
            );
```

**Describe alternatives you've considered**
I'm considering one of three options:
1) forking, and doing it myself
2) using low level client or basic http call
3) manually managing creating lifecycles (but this is not scalable).

**Additional context**
As a positive note, creating the policy works, but needs the rest to work properly...

```
            var lifecycle = client.IndexLifecycleManagement.PutLifecycle(new PutLifecycleDescriptor(policyId)
                .Policy(p =>
                    p.Phases(ph =>
                        ph.Hot(h =>
                            h.Actions(a =>
                                a.Rollover(r =>
                                    r.MaximumSize(maxSize).MaximumAge(maxAge).MaximumDocuments(1)
                                )
                            )
                        ).Delete(d =>
                            d.Actions(a =>
                                a.Delete(dd => dd)
                            ).MinimumAge(maxAge)
                        )
                    )
                ));
```

**Comment by russcam** [comment]
@DR9885 What version of NEST are you using?

Any index setting such as `"index.lifecycle.name"` can be set with `.Setting()`. For example, with NEST 7.7.0

```c#
client.Indices.PutTemplate("template", t => t
	.IndexPatterns("pattern")
	.Settings(s => s
		.Setting("index.lifecycle.name", "name")
		.Setting("index.lifecycle.rollover_alias", "rollover_alias")
	)
);
```

It might be nice to provide strongly typed methods for these.

It's possible to set `is_write_index` when creating an alias from 6.7.0 onwards. For example, in 7.7.0

```c#
client.Indices.Create("foo", c => c
	.Aliases(a => a
		.Alias("bar", ad => ad
			.IsWriteIndex(true)
		)
	)
);
```

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Please let us know if this issue is still a relevant priority for your usage?
