### ISSUE TITLE
Overriding default IndexNameResolver

### ISSUE THREAD

**Issue by MaJaHa95** [elastic/elasticsearch-net#4704]
**Is your feature request related to a problem? Please describe.**
Not so much a problem, but I own a personal Elasticsearch cluster that hosts a personal project. I'd like to test some other projects on the same cluster (since I'm paying for it anyway, and nothing is super mission-critical), but I'd like to avoid naming collisions between two deployed applications.

SQL could handle this using namespaces, but Elasticsearch already exposes a comparable feature through index prefixes.

It would be nice if I could store a setting in my project, so that some deployments would utilize a constant index prefix.

E.g. if I set a prefix of "my-app-", then call:

```
await this._conn.IndexAsync(new IndexRequest<MySpecialType>("special-types", "1234")
{
    Document = ret
}).ConfigureAwait(false);
```

It would turn into a request to:

```
POST /my-app-special-types/1234
```

**Describe the solution you'd like**
1. Create an interface `IIndexNameResolver` exposing the same contract as the current `IndexNameResolver`
2. Make methods on `IndexNameResolver`, `virtual`
3. Allow custom overriding of that default implementation with a custom class implementing that interface

I would then implement something like:

```
public class PrefixedIndexNameResolver : IndexNameResolver
{
    private readonly string prefix;

    public PrefixedIndexNameResolver(IConnectionSettingsValues connectionSettings, string prefix)
        : base(connectionSettings)
    {
        this.prefix = prefix;
    }

    private string PrependPrefix(string indexName) => this.prefix + indexName;

    public string Resolve<T>() where T : class => PrependPrefix(base.Resolve<T>());

    public string Resolve(IndexName i) => PrependPrefix(base.Resolve(i));

    public string Resolve(Type type) => PrependPrefix(base.Resolve(type));
}
```

The use could be very similar to `SourceSerializerFactory`, if `ConnectionConfiguration<T>` added:

```
public delegate IIndexNameResolver IndexNameResolverFactory(IConnectionSettingsValues values);

public T UseIndexNameResolver(IndexNameResolverFactory factory);
```

**Describe alternatives you've considered**
I originally thought a simple `GlobalIndexPrefix` would make a nice argument to `IConnectionSettingsValues`, but looking at the source code, I think a much cleaner solution would be to avoid this special-case behavior, and simply allow a custom implementation.

**Additional context**
I recognize this use-case is niche, but I can imagine other cases where someone may want to implement a special `IndexNameResolver` that, say, did some default transformations given the full type name, or even stored some form of mapping in a configuration dictionary. Not saying that sounds like a good idea, but this would open a lot of options up.

Additionally, this would be another step toward a more .NET Core philosophy of dependency injection, by allowing core functionality to be swapped out using interfaces.

I do see `IConnectionSettingsValues` also exposes `Inferrer Inferrer { get; }`, maybe there's a way to set that directly? All I see is `ConnectionSettingsBase<TConnectionSettings>.DefaultIndex` and such, which would presumably pass into the creation of a default `Inferrer`.

It should also be noted: I have runtime-defined index mappings for some document types, so I can't depend on CLR mappings to handle this completely. But even otherwise, this would be much more foolproof.

**Comment by russcam** [comment]
This sounds like an interesting feature, if perhaps niche as you say. How many different POCOs do you have? I'm wondering if using `DefaultMappingFor<T>`, although repetitive, might suffice?

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Please let us know if this issue is still a relevant priority for your usage?
