### ISSUE TITLE
Support Highlight Fields array

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#4724]
Relates: https://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-body.html#explicit-field-order

Highlighted fields can be explicitly ordered using an array

```
GET /_search
{
    "highlight": {
        "fields": [
            { "title": {} },
            { "text": {} }
        ]
    }
}
```

The client should support this documented feature.

**Comment by stevejgordon** [comment]
Will also be v8 code-gen work.
