### ISSUE TITLE
Nest deserialization is very very very slow on v7.7

### ISSUE THREAD

**Issue by SkyChenSky** [elastic/elasticsearch-net#4734]
**NEST/Elasticsearch.Net version**: 7.7

**Elasticsearch version**: 7.7

**Description of the problem including expected versus actual behavior**:

I need 37 seconds to search for data with NEST.It surprised me.So I debug on NEST open source.
Finally, I find the function` ResponseBuilder.ToResponse<TResponse>()` on ResponseBuilder.cs is performance bottleneck.

**Steps to reproduce**:
 1..net code
```
            var node = new Uri("http://192.168.88.138:9200");
            var settings = new ConnectionSettings(node);
            var client = new ElasticClient(settings);

            var response = client.Search<test2>(a=>a.Index("test2"));
```

**Expected behavior**
Normal search performance

If it's my use problem, please give me some suggestions.

**Comment by Mpdreamz** [comment]
A couple of suggestions:

Try to time the second call, the first call suffers from building caches but that alone should not be anywhere near 37 seconds. 

What does `response.Took` indicate?

Can you set `.EnableDebugMode()` on `ConnectionSettings` and tell us what `response.DebugInformation` returns?  Note this will include response data so be mindful of you can share this.

**Comment by SkyChenSky** [comment]
Thank you very much for your immediate reply.
After receiving your suggestions，I try to second call and third call.It still very slow.
So I  set `.EnableDebugMode()` on `ConnectionSettings`  and debuger Information  as below:
```
Valid NEST response built from a successful (200) low level call on POST: /test2/_search?pretty=true&error_trace=true&typed_keys=true
# Audit trail of this API call:
 - [1] HealthyResponse: Node: http://192.168.88.138:9200/ Took: 00:01:12.6477597
# Request:
{}
# Response:
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 4,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "test2",
        "_type" : "_doc",
        "_id" : "ca29c3IBf1szuS2CHI_V",
        "_score" : 1.0,
        "_source" : {
          "name" : "苹果X/iphone x",
          "des" : "当天发货/24期分期Apple/苹果iPhone 11官方旗舰店国行苹果11全网通4G手机x官方xr iPhone se新品11pro xsmax"
        }
      },
      {
        "_index" : "test2",
        "_type" : "_doc",
        "_id" : "c629c3IBf1szuS2CJ4_0",
        "_score" : 1.0,
        "_source" : {
          "name" : "苹果X手机壳",
          "des" : "苹果X手机壳硅胶iPhonexsmax浮雕iPhonex全包防摔xr磨砂男女款软"
        }
      },
      {
        "_index" : "test2",
        "_type" : "_doc",
        "_id" : "da29c3IBf1szuS2CMI-D",
        "_score" : 1.0,
        "_source" : {
          "name" : "苹果6s手机壳",
          "des" : "苹果6s手机壳硅胶iPhone 6s浮雕iPhone 6x全包防摔xr磨砂男女款软"
        }
      },
      {
        "_index" : "test2",
        "_type" : "_doc",
        "_id" : "d629c3IBf1szuS2CO48v",
        "_score" : 1.0,
        "_source" : {
          "name" : "苹果笔记本",
          "des" : "苹果笔记本2020版macbook air mackoob pro"
        }
      }
    ]
  }
}

```

**Comment by sadaqatbukhari** [comment]
NEST/Elasticsearch.Net version: 7.6.1
I am also facing same problem.

Query on Postman took 300ms. But when I query using NEST client it is taking about 12 seconds for 10000 records.
I figure out this is problem with deserialization the response. If decrease the size to 100 then it is taking only 1 second.
Could you please suggest me what to do with this 10000 size of documents?

**Comment by SkyChenSky** [comment]
Today,I reboot my PC and use same code with nest. Response just need 1 second. Does the memory usage affect the deserialization performance?

```
Valid NEST response built from a successful (200) low level call on POST: /test2/_search?pretty=true&error_trace=true&typed_keys=true
# Audit trail of this API call:
 - [1] HealthyResponse: Node: http://192.168.88.138:9200/ Took: 00:00:00.9993916
# Request:
{}
# Response:
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 4,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "test2",
        "_type" : "_doc",
        "_id" : "ca29c3IBf1szuS2CHI_V",
        "_score" : 1.0,
        "_source" : {
          "name" : "苹果X/iphone x",
          "des" : "当天发货/24期分期Apple/苹果iPhone 11官方旗舰店国行苹果11全网通4G手机x官方xr iPhone se新品11pro xsmax"
        }
      },
      {
        "_index" : "test2",
        "_type" : "_doc",
        "_id" : "c629c3IBf1szuS2CJ4_0",
        "_score" : 1.0,
        "_source" : {
          "name" : "苹果X手机壳",
          "des" : "苹果X手机壳硅胶iPhonexsmax浮雕iPhonex全包防摔xr磨砂男女款软"
        }
      },
      {
        "_index" : "test2",
        "_type" : "_doc",
        "_id" : "da29c3IBf1szuS2CMI-D",
        "_score" : 1.0,
        "_source" : {
          "name" : "苹果6s手机壳",
          "des" : "苹果6s手机壳硅胶iPhone 6s浮雕iPhone 6x全包防摔xr磨砂男女款软"
        }
      },
      {
        "_index" : "test2",
        "_type" : "_doc",
        "_id" : "d629c3IBf1szuS2CO48v",
        "_score" : 1.0,
        "_source" : {
          "name" : "苹果笔记本",
          "des" : "苹果笔记本2020版macbook air mackoob pro"
        }
      }
    ]
  }
}

```

**Comment by russcam** [comment]
> Today,I reboot my PC and use same code with nest. Response just need 1 second. Does the memory usage affect the deserialization performance?

Which memory usage are you referring to? Elasticsearch? .NET runtime / application?

I think we need much more detail to be able to investigate this. Can you provide the following

1. Operating system, processor, RAM
2. .NET Framework/SDK used
3. Details about the Elasticsearch cluster you're running against (number of nodes, RAM per node, type of disks, to start)
4. A small but complete example of client usage where you're seeing slow responses would be hugely helpful. In lieu of this, [a dump](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-dump) taken when you see slow responses

**Comment by SkyChenSky** [comment]
In my environment，My PC is 4 core CPU 、16GB RAM and 512GB SSD.

Elasticsearch is run single node  on VMware centos 7 docker. The VM set 4GB RAM and 1 core CPU. 

The Elasticsearch just have 123KB data. I use postman send and response just 132ms.

The demo is run .Net Core Console Application v3.1.101 in my local pc windows ;

The demo code  as below:
```
var node = new Uri("http://192.168.88.138:9200");
            var settings = new ConnectionSettings(node);
            var client = new ElasticClient(settings);

            var response = client.Search<test2>(a=>a.Index("test2"));
```
The debug info  as below:
```
Valid NEST response built from a successful (200) low level call on POST: /test2/_search?pretty=true&error_trace=true&typed_keys=true
# Audit trail of this API call:
 - [1] HealthyResponse: Node: http://192.168.88.138:9200/ Took: 00:01:12.6477597
# Request:
{}
# Response:
{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 4,
      "relation" : "eq"
    },
    "max_score" : 1.0,
    "hits" : [
      {
        "_index" : "test2",
        "_type" : "_doc",
        "_id" : "ca29c3IBf1szuS2CHI_V",
        "_score" : 1.0,
        "_source" : {
          "name" : "苹果X/iphone x",
          "des" : "当天发货/24期分期Apple/苹果iPhone 11官方旗舰店国行苹果11全网通4G手机x官方xr iPhone se新品11pro xsmax"
        }
      },
........
```

Thank you for your reply. If you need anything else, please feel free to reply to me

**Comment by russcam** [comment]
I've added a benchmark using a a fixed bytes response, and the example data provided in 

https://github.com/elastic/elasticsearch-net/tree/issue-4734

This benchmark can be run from the solution root with

```sh
.build benchmark
```

and choose the number that corresponds to `GitHubIssue4734Benchmark`.

On my machine, the results are

```
BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18363
Intel Core i7-8850H CPU 2.60GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=3.0.100
  [Host]     : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), X64 RyuJIT
  Job-ZJHABG : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), X64 RyuJIT

Jit=RyuJit  Runtime=.NET Core 3.0  

|      Method |     Mean |   Error |   StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------ |---------:|--------:|---------:|------:|------:|------:|----------:|
| Deserialize | 253.6 ns | 8.31 ns | 23.44 ns |     - |     - |     - |      36 B |
```

With the mean time of 253ns to perform the client request, including serialization, and excluding any network.

My suspicion at this stage is that the response time you saw may be network related. Can you configure network tracing and capture http related traces for slow responses? You can use something like [`PerfView` to trace `System.Net` event sources](https://github.com/dotnet/corefx/blob/master/Documentation/debugging/windows-instructions.md#systemnet-namespaces)

**Comment by SkyChenSky** [comment]
Greate! Thank you for your reply.

At first time,  I ran into this problem. I thought it was a network problem.But I  test in multiple environments include postman、.Net `RestSharp` and `curl`.Fast except nest.

Now because I reboot my computer, I can't reproduce the scene and capture more information for you

Next, if I still have performance problems, I'll capture as much information as I can for you.

Thank you again for your reply.

**Comment by sadaqatbukhari** [comment]
Testing Environment Laptop is 4 core CPU, 16GB RAM and 512GB SSD.

Elasticsearch is running single node on windows server 2012 VM. This VM has 16GB RAM and 4 core CPU.

The Elasticsearch have 18 GB data. I am using NEST version: 7.6.1 for indexing and query
Same query with Postman is taking only 1221 ms but with NEST client it is taking about 10-13 seconds for 10000 size. 
When I decrease the page size query time is decreased for 3000 it is taking almost 5 seconds.

**Benchmarks of same query for REST Client and NEST Client.
Nest client took: 12384 ms
Nest client documents: 10000
Rest client took: 1966 ms**

I have build Elasticsearch repository in asp.net core 3.1.

**Settings of Client**

`  var settings = new ConnectionSettings(new Uri(url))
                .EnableDebugMode()
                
            .DefaultIndex(defaultIndex);
            var client = new ElasticClient(settings);
            services.AddSingleton<IElasticClient>(client);`

Get List Method

`  public List<T> GetList<T>(SearchDescriptor<T> descriptor, string index = null) where T : class, IElasticBaseModel
        {
            descriptor.From(0)
        .Take(scrollPageSize).Scroll("5m");

            index = index ?? _options.DefaultIndex;
            descriptor = descriptor.Index(index);
            var searchResponse = _client.Search<T>(descriptor);
            var results = new List<T>();

            while (true)
            {
                if (!searchResponse.IsValid || string.IsNullOrEmpty(searchResponse.ScrollId))
                    throw new Exception($"Search error: {searchResponse.ServerError.Error.Reason}");

                if (!searchResponse.Documents.Any())
                    break;

                results.AddRange(searchResponse.Documents);
                searchResponse = _client.Scroll<T>("5m", searchResponse.ScrollId);
            }

            _client.ClearScroll(new ClearScrollRequest(searchResponse.ScrollId));
            return results;
        }`

This query took 11.5 seconds.
Below is Debug Info from NEST client.

```
Valid NEST response built from a successful (200) low level call on POST: /position/_search?pretty=true&error_trace=true&typed_keys=true&scroll=5m
# Audit trail of this API call:
 - [1] HealthyResponse: Node: http://172.18.3.161:9200/ Took: 00:00:08.9185311
# Request:
{"from":0,"query":{"bool":{"filter":[{"bool":{"must":[{"geo_bounding_box":{"boost":1.1,"validation_method":"coerce","type":"indexed","location":{"bottom_right":{"lat":47.6125,"lon":39.575},"top_left":{"lat":64.8875,"lon":-17.075}}}}],"should":[{"bool":{"filter":[{"bool":{"should":[{"bool":{"must":[{"terms":{"machine":["6F1401","6G1519"]}},{"range":{"time":{"gte":"2019-09-01T00:00:00Z","lte":"2019-09-30T23:59:59.9999999Z"}}}]}}]}}]}}]}}]}},"size":10000}
# Response:
{
  "_scroll_id" : "DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAHY_0WVlFRQlpTazJSUjZKbjJ4OGplQlJ3UQ==",
  "took" : 2876,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 59128374,
      "relation" : "eq"
    },
    "max_score" : 0.0,
    "hits" : [
      {
        "_index" : "position",
        "_type" : "_doc",
        "_id" : "6H1561_1541153618.03",
        "_score" : 0.0,
        "_source" : {
          "id" : "6H1561_1541153618.03",
          "time" : "2018-11-02T10:13:38.0300000Z",
          "machine" : "6H1561",
          "orderid" : 56,
          "bunkerunloading" : false,
          "operatingmode" : 1,
          "depthguidanceon" : true,
          "engineon" : true,
          "istimelygap" : false,
          "identifier" : 6852,
          "location" : {
            "lat" : 50.613713333,
            "lon" : 4.014146667
          }
        }
      },

```

**Comment by sadaqatbukhari** [comment]
> Greate! Thank you for your reply.
> 
> At first time, I ran into this problem. I thought it was a network problem.But I test in multiple environments include postman、.Net `RestSharp` and `curl`.Fast except nest.
> 
> Now because I reboot my computer, I can't reproduce the scene and capture more information for you
> 
> Next, if I still have performance problems, I'll capture as much information as I can for you.
> 
> Thank you again for your reply.

Could you please help me with this NEST client desalinization issue. Please read above comments and let me know what is wrong with my settings.

**Comment by sadaqatbukhari** [comment]
> I've added a benchmark using a a fixed bytes response, and the example data provided in
> 
> https://github.com/elastic/elasticsearch-net/tree/issue-4734
> 
> This benchmark can be run from the solution root with
> 
> ```shell
> .build benchmark
> ```
> 
> and choose the number that corresponds to `GitHubIssue4734Benchmark`.
> 
> On my machine, the results are
> 
> ```
> BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18363
> Intel Core i7-8850H CPU 2.60GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
> .NET Core SDK=3.0.100
>   [Host]     : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), X64 RyuJIT
>   Job-ZJHABG : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), X64 RyuJIT
> 
> Jit=RyuJit  Runtime=.NET Core 3.0  
> 
> |      Method |     Mean |   Error |   StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
> |------------ |---------:|--------:|---------:|------:|------:|------:|----------:|
> | Deserialize | 253.6 ns | 8.31 ns | 23.44 ns |     - |     - |     - |      36 B |
> ```
> 
> With the mean time of 253ns to perform the client request, including serialization, and excluding any network.
> 
> My suspicion at this stage is that the response time you saw may be network related. Can you configure network tracing and capture http related traces for slow responses? You can use something like [`PerfView` to trace `System.Net` event sources](https://github.com/dotnet/corefx/blob/master/Documentation/debugging/windows-instructions.md#systemnet-namespaces)

Could you please help me in this performance issue. I am still facing performance issue. I don't know what is wrong with my settings. I even rebooted the PC but still same performance issue. Please let m know if you need more information. Please read my above comment.

**Comment by SkyChenSky** [comment]
> > I've added a benchmark using a a fixed bytes response, and the example data provided in
> > https://github.com/elastic/elasticsearch-net/tree/issue-4734
> > This benchmark can be run from the solution root with
> > ```shell
> > .build benchmark
> > ```
> > 
> > 
> > and choose the number that corresponds to `GitHubIssue4734Benchmark`.
> > On my machine, the results are
> > ```
> > BenchmarkDotNet=v0.12.0, OS=Windows 10.0.18363
> > Intel Core i7-8850H CPU 2.60GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
> > .NET Core SDK=3.0.100
> >   [Host]     : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), X64 RyuJIT
> >   Job-ZJHABG : .NET Core 3.0.0 (CoreCLR 4.700.19.46205, CoreFX 4.700.19.46214), X64 RyuJIT
> > 
> > Jit=RyuJit  Runtime=.NET Core 3.0  
> > 
> > |      Method |     Mean |   Error |   StdDev | Gen 0 | Gen 1 | Gen 2 | Allocated |
> > |------------ |---------:|--------:|---------:|------:|------:|------:|----------:|
> > | Deserialize | 253.6 ns | 8.31 ns | 23.44 ns |     - |     - |     - |      36 B |
> > ```
> > 
> > 
> > With the mean time of 253ns to perform the client request, including serialization, and excluding any network.
> > My suspicion at this stage is that the response time you saw may be network related. Can you configure network tracing and capture http related traces for slow responses? You can use something like [`PerfView` to trace `System.Net` event sources](https://github.com/dotnet/corefx/blob/master/Documentation/debugging/windows-instructions.md#systemnet-namespaces)
> 
> Could you please help me in this performance issue. I am still facing performance issue. I don't know what is wrong with my settings. I even rebooted the PC but still same performance issue. Please let m know if you need more information. Please read my above comment.

Hey guy!

I didn't solve the problem. I just reboot my PC and the problem has disappeared.
But I still think there's a problem with deserialization.

Some suggestions:

1. Dose response have long text?
2. Use other json sdk test deserialization. For example :fastjson
3. Custom  or replacement serialization.Use elaticsearch.net provided serialization  Interface 

Good Luck!
