### ISSUE TITLE
Queryable support for NEST client

### ISSUE THREAD

**Issue by cermakp** [elastic/elasticsearch-net#4786]
Hi, 

is there any plan to expose IQueryable interface for search requests, sth like

```
client.Search<IndexedEntity>.Query()
   .Where(entity => entity.Name.Contains("John") && entity.Age > 30)
   .OrderBy(entity => entity.Age); 
```

Our client needs to expose Queryable interface and without implementation of any custom queryProvider or expression visitor we are not able to achieve that. 

Is there any plan to implement IQueryable or at least provide some library doing the transformation between IQueryable and DSL using by NEST?

**Comment by russcam** [comment]
Hi @cermakp

There are no plans to implement a QueryProvider/IQueryable interface for the client. It's been asked a few times before:

- https://github.com/elastic/elasticsearch-net/issues/1197
- https://github.com/elastic/elasticsearch-net/issues/1581
- https://github.com/elastic/elasticsearch-net/issues/3845

I think the reasons for not doing so are outlined in those issues and this [stackoverflow answer](https://stackoverflow.com/a/36002317/1831), so I'm going to close this
