### ISSUE TITLE
NEST generates query for null values

### ISSUE THREAD

**Issue by SLavrynenko** [elastic/elasticsearch-net#4787]
**NEST/Elasticsearch.Net version**: 7.6.1

**Elasticsearch version**: 7.7.0

**Description of the problem including expected versus actual behavior**:
I have the following code:

```
                    response = client.Search<XXXXX>(
                        s => s.Query(q => q.Terms(t => t.Field(c => c.Id).Terms(Ids)))
                            .Index("Index1")
                            .Source(sfd => SourceSelector(sfd, searchFilter))
                            .Size(Ids.Count)
                            .ApplySorting(searchFilter)
                    );

```
There is a method SourceSelector(sfd, searchFilter) here that basically generates code for the source in the case if we need to select only certain fields, in the case when we need everything it returns null and in this case we have the following problem:

> System.ApplicationException: Invalid NEST response built from a unsuccessful (400) low level call on POST: /XXXXXX/_search?typed_keys=true@# Audit trail of this API call:@ - [1] BadResponse: Node: http://XXXXXXXX/ Took: 00:00:00.0156257@# OriginalException: Elasticsearch.Net.ElasticsearchClientException: The remote server returned an error: (400) Bad Request.. Call: Status code 400 from: POST /XXXXXX/_search?typed_keys=true. ServerError: Type: parsing_exception Reason: ""Unknown key for a VALUE_NULL in [_source]."" ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.@   at System.Net.HttpWebRequest.GetResponse()@   at Elasticsearch.Net.HttpWebRequestConnection.Request[TResponse](RequestData requestData)@   --- End of inner exception stack trace ---@# Request:@{""track_total_hits"":true,""from"":0,""query"":{""bool"":{""must"":[{""bool"":{""must"":[{""term"":{""CID"":{""value"":1111}}},{""term"":{""IsActive"":{""value"":1}}},{""terms"":{""ID"":[11,22]}},{""term"":{""DbId"":{""value"":14}}}]}}]}},""size"":20,""sort"":[{""AddedOn"":{""order"":""desc""}},{""ID"":{""order"":""desc""}}],**""_source"":null**}@# Response:@{""error"":{""root_cause"":[{""type"":""parsing_exception"",""reason"":""Unknown key for a VALUE_NULL in [_source]."",""line"":1,""col"":487}],""type"":""parsing_exception"",""reason"":""Unknown key for a VALUE_NULL in [_source]."",""line"":1,""col"":487},""status"":400}@ ---> Elasticsearch.Net.ElasticsearchClientException: The remote server returned an error: (400) Bad Request..

**Expected behavior**
in the case when source selector returns null the _source part of query should not be generated

We have just moved from NEST 2.5.8 and this code works there as expected (it doesnt generate code if source selector returns null)

**Comment by russcam** [comment]
Thanks for opening, @SLavrynenko.

I think the issue here is that the value returned from `Source(...)` is always wrapped in a `Union<bool, ISourceFilter>`

https://github.com/elastic/elasticsearch-net/blob/ae0516d03e70e595480a9c84f826880875110c05/src/Nest/Search/Search/SearchRequest.cs#L300-L301

 so even if the returned value happens to be `null`, because the union wrapper is not null, the serializer still attempts to serialize the union.

I'll open a PR to address.
