### ISSUE TITLE
.NET 3.5 compliance?

### ISSUE THREAD

**Issue by macrauder** [elastic/elasticsearch-net#48]
Hi,

is it possible to create a build profile that is creating NEST as a .Net 3.5 compliant DLL?
We need .Net 3.5 because we like to use NEST in a SharePoint environment and these is only 3.5 compliant.
A manuel change in the solution to .Net 3.5 wasn't succesfully.
Thx Thomas

**Comment by KamranShahid** [comment]
I also needed it for a 3.5 version. I have a .net 3.5 version of task Parallel library avaibale n codeplex which I have also used in my 3.5 version.Problem was use of dynamic feature of .net 4.0.
Is there any old repository of Nest for 3.5 where we can get the code and will try to compile it in 3.5?
