### ISSUE TITLE
Query with Terms provide no result until I use "keyword.myfieldname" instead of the lambda

### ISSUE THREAD

**Issue by NicolasReyDotNet** [elastic/elasticsearch-net#4820]
**NEST/Elasticsearch.Net version**: 7.8.0

**Elasticsearch version**: 7.6.1

**Description of the problem including expected versus actual behavior**:
Hi, I simply try to Index (it works) and Search documents using the Term query (always returns empty results)

**Steps to reproduce**:
 1. From Kibana I index a document (it works)
```
PUT product/_doc/b0264dad-6739-49ea-b691-e05a2883a724
{
  "name": "Name 2",
  "description": "Desc 1",
  "price": 11,
  "startSell": "2020-06-28T12:24:37.0070067+00:00",
  "endSell": "2020-07-19T12:24:37.0070161+00:00",
  "variants": [
    {
      "color": "Red",
      "size": 1
    },
    {
      "color": "Red",
      "size": 1
    },
    {
      "color": "Red",
      "size": 1
    },
    {
      "color": "Blue",
      "size": 1
    },
    {
      "color": "Yellow",
      "size": 1
    },
    {
      "color": "Yellow",
      "size": 2
    },
    {
      "color": "Yellow",
      "size": 3
    },
    {
      "color": "Purple",
      "size": 4
    }
  ]
}
```
 2. The search query returns no data 
![image](https://user-images.githubusercontent.com/37657851/86018828-245fc080-ba26-11ea-9123-243af35a8898.png)

 3. From Kibana, the intellisense tells me to use "keyword.nameoffield" 
```
POST product/_search
{
  "query": {
    "term": {
      "name.keyword": {
        "value": "Name 2",
        "boost": 1
      }
    }
  }
}

```
 4. If I do the same in the Nest library it works but why can't I use the lambda without using "keyword.xxx" ?
  
![image](https://user-images.githubusercontent.com/37657851/86019221-a3ed8f80-ba26-11ea-945b-40d352cd32e3.png)

**Expected behavior**
I would like to not have to provide "keyword.xxx" and use the supplied lambda from the Nest lib as povided

**Comment by russcam** [comment]
The `keyword` field exists in Elasticsearch's index, but is not part of your POCO that models the document (and if it is, it shouldn't be. The document should model the `_source`).

NEST contains the [`.Suffix(...)`](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/property-inference.html#_appending_suffixes_to_a_lambda_expression_body) extension method that allows you to use [`Multi Fields` with lambda expressions](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/multi-fields.html)

```c#
var result5 = await _productRepository.Get(q => q.Term(f => f.Name.Suffix("keyword"), "Name 2");
```

[Take a look at the documentation for more complex examples](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/field-inference.html#_complex_field_name_expressions).
