### ISSUE TITLE
Id field cannot be serialized correctly in inherited class

### ISSUE THREAD

**Issue by antonydenyer** [elastic/elasticsearch-net#483]
As per:
[http://stackoverflow.com/questions/19543707/automatic-id-generation-and-mapping-id-nest](http://stackoverflow.com/questions/19543707/automatic-id-generation-and-mapping-id-nest)
[https://gist.github.com/antonydenyer/9074159](https://gist.github.com/antonydenyer/9074159)

A class that is inherited can not serialize the id field correctly. However, the root goal was to have a model with an auto assigned id. That is a model that when indexing ignores the Id property but when de-serializing pulls it out. Perhaps something in the attribute on the model?

**Comment by nasreekar** [comment]
Any update or alternative for this issue? Using Hits may not work in all the scenario's.
