### ISSUE TITLE
Adding bulkhead protection to protect application

### ISSUE THREAD

**Issue by jtreher** [elastic/elasticsearch-net#4845]
Elasticsearch can configure max concurrent connections, but it is possible to starve an application while an ES cluster is sluggish or nearly unresponsive.

Introduce bulkhead and/or circuit breaker protection. 
ES already offers retries and timeouts, so it seems natural that additional resilience configurations might be desirable.

**Alternatives**
We were considering trying to tailor the concurrency settings, but this seems to be the inverse of what we want, to control the max operations from the application regardless of servers.

Introduce https://github.com/App-vNext/Polly to wrap some of the calls going to Elasticsearch to make use of its resilience strategies. Covering the breadth of calls on the high level client isn't practical and one could potentially "know too much" about the implementation details (pathological coupling) of the low level client in our wrapper. Finally, extend HttpConnection and override the Request<T> method to wrap the base Request with Polly. This seems like it might be the most straightforward approach.

**Additional context**
We had a period last quarter where our application was thread starved waiting on queries to complete. We normally handle thousands of requests per minute, but the cluster started to become barely responsive, causing all requests to reach the maximum timeout of 2s (most queries are ms, but we have a few large search queries that sometimes hit the 2s mark). This caused the application threadpool to become starved.

We were using default concurrency settings on the client. What we were thinking is that it might be better to introduce bulkhead isolation which would allow us to isolate how many concurrent operations are going out of that application node at any one time to ensure that we have some available resources for other operations when there is a problem. 

Circuit breaker would go a step further, stopping all calls to Elasticsearch for some specified amount of time, giving it a chance to recover.

**Comment by stevejgordon** [comment]
We have reviewed this and don't feel this is something we'll add.
