### ISSUE TITLE
I try to use bool query, I don't know why I can't find out the result.

### ISSUE THREAD

**Issue by wajika** [elastic/elasticsearch-net#4849]
![image](https://user-images.githubusercontent.com/17058349/87109610-b8881e00-c297-11ea-8bd6-1dbb375fdea4.png)
![image](https://user-images.githubusercontent.com/17058349/87109826-39471a00-c298-11ea-96e6-649665aac410.png)

![image](https://user-images.githubusercontent.com/17058349/87109966-862af080-c298-11ea-82d4-80ff74e05ebe.png)

![image](https://user-images.githubusercontent.com/17058349/87109232-afe31800-c296-11ea-9f4a-1205cdaa9247.png)

I only succeeded in term query

**Comment by wajika** [comment]
fuzzy search
![image](https://user-images.githubusercontent.com/17058349/87110847-8fb55800-c29a-11ea-991c-cbc01c30f069.png)

**Comment by wajika** [comment]
index mapping

```
{
  "mapping": {
    "properties": {
      "@timestamp": {
        "type": "date"
      },
      "@version": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "BrowserInfo": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "Category": {
        "type": "long"
      },
      "ClientIpAddress": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "CreateTime": {
        "type": "date"
      },
      "Exception": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "ExecutionDuration": {
        "type": "long"
      },
      "ExecutionTime": {
        "type": "date"
      },
      "Id": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "ImpersonatorTenantId": {
        "type": "long"
      },
      "JobInfoId": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "Message": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "MethodName": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "Parameters": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "ServiceName": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "SourceType": {
        "type": "text",
        "fields": {
          "keyword": {
            "type": "keyword",
            "ignore_above": 256
          }
        }
      },
      "TenantId": {
        "type": "long"
      }
    }
  }
}
```



Data content


```
{
  "_index": "abp_schedulerlogs_dev",
  "_type": "_doc",
  "_id": "rt1nPHMBbI5kNDBPzlBX",
  "_version": 1,
  "_score": null,
  "_source": {
    "Id": "08d814f9-736c-48a9-823c-72276c23bbad",
    "Category": 2,
    "@timestamp": "2020-07-11T05:45:02.686Z",
    "SourceType": "workingjob",
    "WorkNode": null,
    "StackTrace": null,
    "Message": "档案管理行历史数据同步开始,开始时间：2020-07-11  05-45-00",
    "JobInfoId": "08d814f9-736c-48a9-823c-72276c23bbad",
    "@version": "1",
    "CreateTime": "2020-07-11T05:45:00.061998+00:00"
  },
  "fields": {
    "@timestamp": [
      "2020-07-11T05:45:02.686Z"
    ],
    "CreateTime": [
      "2020-07-11T05:45:00.061Z"
    ]
  },
  "sort": [
    1594446302686
  ]
}
```


I later wrote another DSL statement, but the result returned is different from the expected.

GET abp_schedulerlogs_dev/_search
{
  "query": { 
    "bool": { 
      "must": [
        { "match": { "JobInfoId": "08d814f9-2469-4b66-8270-3bfdbdfafaf5" }}

      ],
      "filter": [ 
        { "term":  { "SourceType": "workingjob" }}
      ]
    }
  }
}



Return result

![image](https://user-images.githubusercontent.com/17058349/87218387-cbc4e780-c384-11ea-84e7-16c981ce000f.png)


var searchResponse = client.Search<JobElasticDto>(s => s
            .Index("abp_schedulerlogs_dev")
            .Query(q => q
                .Bool(b => b
                    .Must(m => m.Term(p => p.JobInfoId, "08d81529-64a9-49ba-856a-4b9ed9b56da6"))
                    .Filter(f => f.Term(p => p.SourceType, "workingjob"))
                )
            )
        );

But using NEST client returns 0



I have also written a lot of code, and the results obtained are also a bit strange.
https://paste.ubuntu.com/p/27t74c7mmk/

**Comment by russcam** [comment]
Hi @wajika, 

We reserve GitHub Issues for bug reports and feature requests.

The best place to ask future questions is the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Not only do more folks view the forums than the GitHub Issues list, and hence it is more likely for questions to receive attention, but the forums are also geared towards being able to search previous questions and answers, making it a much more valuable archive for future question askers.

The provided examples are incomplete, but I suspect the client is configured with the default serialization, which [will camel case field names](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/field-inference.html#camel-casing), but the mapping and the Kibana console example use Pascal case. If you change the client to use Pascal case by setting [`DefaultFieldNameInferrer` on `ConnectionSettings`](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/configuration-options.html#_options_on_connectionsettings)

```c#
var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
var settings = new ConnectionSettings(pool)
    .DefaultFieldNameInferrer(p => p); // <

var client = new ElasticClient(settings);
```
