### ISSUE TITLE
The type initializer for 'Elasticsearch.Net.DiagnosticsSerializerProxy' threw an exception.

### ISSUE THREAD

**Issue by ShirishPatel** [elastic/elasticsearch-net#4850]
**NEST/Elasticsearch.Net version**: NEST.7.8.1 + Elasticsearch.Net.7.8.1 Nuget Packages

**Elasticsearch version**: Elasticsearch v7.3.1

**Steps to reproduce**:
 1. VS 2013 + Windows 7 SP 3 + ASP.Net C#
 2. Code :-
var searchBoxUri = new Uri("http://localhost:9200");
var elasticSettings = new ConnectionSettings(searchBoxUri).DefaultIndex("companylistindex");
 3. Gives error on the last line above "The type initializer for 'Elasticsearch.Net.DiagnosticsSerializerProxy' threw an exception."

**Comment by russcam** [comment]
What version of .NET are you using e.g. .NET Core 3.1.100, .NET Framework 4.6.1, etc.? If you have a link to a small example project it will help. I suspect a problem in resolving System.Diagnostics.DiagnosticSource, but need more information to confirm.

**Comment by ShirishPatel** [comment]
.Net Framework 4.8

**Comment by ShirishPatel** [comment]
The same code works fine when published but does not work when debugged..

I have now degraded the Nuget packages from 7.8.1 to NEST.7.3.1 + Elasticsearch.Net.7.3.1 just to match the Elasticsearch v7.3.1 and now it is working fine..

**Comment by Mpdreamz** [comment]
Do you have a stracktrace available for the exception?

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Please let us know if this issue is still a relevant priority for your usage?
