### ISSUE TITLE
Security.Permissions Exceptions in Elastic.Net.ConnectionConfiguration in wcf dot net applications 

### ISSUE THREAD

**Issue by ajvenkatesh4228** [elastic/elasticsearch-net#4851]
Hi Folks,

Hope, anyone helps on this to get an answer for this : I am working in a wcf dot net applications - I am logging in elastic search, it works in my local windows 10 machine, when hosting the wcf application in windows server in IIS, when I tried to logging the logs in elastic search, my wcf dot net code gives following errors "The type initilaizer for elasticsearch.net.connectionconfigurations throws an exception", System.Security.Permissions.SecurityPermission at elasticsearch.net
Connectionconfiguration 1..ctor(Iconnectionpool connectionpool, Iconnection connection, Ielasticsearchserializer requestResponseSerializer) at serilog.sinks.elasticsearch.elasticsearchsinksstate..ctor(Elasticsearchsinkoptions options)
at serilog.sinks.elasticsearch.elasticsearchsinksstate..create(Elasticsearchsinkoptions options)
at serilog.sinks.elasticsearch.elasticsearchsinks..ctor(Elasticsearchsinkoptions options)

Pls help on this issue to resolve in my window server asap

**Comment by russcam** [comment]
Hi @ajvenkatesh4228 , 

We reserve GitHub Issues for bug reports and feature requests.

The best place to ask future questions is the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Not only do more folks view the forums than the GitHub Issues list, and hence questions are more likely to receive attention, but the forums are also geared towards being able to search previous questions and answers, making it a much more valuable archive for future question askers.

Given the presence of System.Security.Permissions.SecurityPermission in the message, and an exception in type initialization (`TypeInitializationException`?), this sounds like it _may_ be related to trust. Is the WCF application running with Full or Partial trust? Also, what version of .NET Framework is it running on?

**Comment by ajvenkatesh4228** [comment]
> Hi @ajvenkatesh4228 ,
> 
> We reserve GitHub Issues for bug reports and feature requests.
> 
> The best place to ask future questions is the Elastic Discourse forums at https://discuss.elastic.co/c/elasticsearch. Not only do more folks view the forums than the GitHub Issues list, and hence questions are more likely to receive attention, but the forums are also geared towards being able to search previous questions and answers, making it a much more valuable archive for future question askers.
> 
> Given the presence of System.Security.Permissions.SecurityPermission in the message, and an exception in type initialization (`TypeInitializationException`?), this sounds like it _may_ be related to trust. Is the WCF application running with Full or Partial trust? Also, what version of .NET Framework is it running on?

.Net framework - 4.7.1 and full trust in running wcf application

**Comment by russcam** [comment]
What version of NEST/Elasticsearch.NET are you using?

**Comment by ajvenkatesh4228** [comment]
Elasticsearch.net - version 7.0.0.0, runtime version - v4.0.30319

**Comment by russcam** [comment]
What's the nuget package version?

**Comment by ajvenkatesh4228** [comment]
Nuget package version - 7.0.0

**Comment by russcam** [comment]
@ajvenkatesh4228 can you update NEST and Elasticsearch.NET to the latest 7.x version and see if the problem persists? At time of writing the latest version is [7.8.1](https://www.nuget.org/packages/NEST/7.8.1).

**Comment by ajvenkatesh4228** [comment]
Ya I have tried to latest version, same error occurs, Note : local code
connecting to elastic search url works fine, even hosting in local IIS of
same windows server DLL also works fine, only this issue occurs in windows
server IIS hosted wcf connecting to elastic search url

**Comment by russcam** [comment]
Would you be able to create a github repository with the simplest WCF example that replicates the problem and instructions to replicate, and post the link here?

**Comment by russcam** [comment]
@ajvenkatesh4228 would you be able to create a github repository with the simplest WCF example that replicates the problem? Without having a clear reproduction, I think it's going to be tricky to investigate this.

**Comment by stevejgordon** [comment]
Closing due to age/inactivity. Please let us know if this issue is still a relevant priority for your usage?
