### ISSUE TITLE
How can I access script fields in queries ?

### ISSUE THREAD

**Issue by NicolasReyDotNet** [elastic/elasticsearch-net#4875]
**NEST/Elasticsearch.Net version**:
7.8.0

**Elasticsearch version**:
7.6.1 (Docker)

**Description of the problem including expected versus actual behavior**:
Hi, I simply would like to get access to a script field computed to get the arcDistance from a Geopoint mapped field and a supplied coordinates.

**Steps to reproduce**:
Here is the raw query generated by my NEST search (it works well)
```
GET offices/_search
{
  "size": 100,
  "_source": [
    "name", 
  ],
  "script_fields": {
    "mydistance": {
      "script": "doc['location'].arcDistance(48.858,  2.21)"
    }
  },
  "query": {
    "bool": {
      "must": [
			...
      ],
      "filter": {
        "geo_distance": {
          "distance": "5000m",
          "location": {
            "lat": 48.858,
            "lon": 2.21
          }
        }
      }
    }
  },
  "sort": [
    {
      "_geo_distance": {
        "location": {
          "lat": 48.858,
          "lon": 2.21
        },
        "order": "asc"
      }
    }
  ]
}
```

Results in (mydistance field does appear as expected)

```
"hits" : [
      {
        "_index" : "offices",
        "_type" : "_doc",
        "_id" : "off1",
        "_score" : null,
        "_source" : {
          "name" : "OFFICE 1"
        },
        "fields" : {
          "mydistance" : [
            265.0396545087881
          ]
        },
        "sort" : [
          265.0396545087881
        ]
		...
	}
]
```

My POCO used to index document
```
    public class Offices
    {
        public string Id{ get; set; }
        public string Name { get; set; }
        public GeoLocation Location { get; set; }
    }
```

**When the query is performed, the script field is returned (raw JSON), but how to declare this extra field so that it can be serialized into my POCO but ignored when I index a document (as it's computed by Elastic, not by me) ?**

**Expected behavior**
Get the way to serialize a script field in a POCO.

**Comment by NicolasReyDotNet** [comment]
I found this when enumerating the Hits :

```
var searchResponse = await _elasticClient.SearchAsync<T>(s => s.Index("myIndex").Query(query));

// Enumerate over response Hits with i
searchResponse.Hits.ElementAt(i).Fields["mydistance"].As<List<double>>().FirstOrDefault()
```

Is it the only way to get access to such field ?

**Comment by NicolasReyDotNet** [comment]
I also tried with method : 
```
Task<ISearchResponse<TDocument>> SearchAsync<TInferDocument, TDocument>(Func<SearchDescriptor<TInferDocument>, ISearchRequest> selector = null, CancellationToken ct = default)
            where TInferDocument : class
            where TDocument : class;
```
This way
```
            var searchResponse = await _elasticClient.SearchAsync<Offices, OfficesWithScriptFields>(
                s => s.Index("myIndex")
                .Size(size)
                .Source(source)
                .ScriptFields(scripts)
                .Query(query)
                .Sort(sort));
```

Using my pevious POCO as `TinferDocument `
```
    public class Offices
    {
        public string Id{ get; set; }
        public string Name { get; set; }
        public GeoLocation Location { get; set; }
    }
```
And a POCO supposed to get the script fields as `TDocument`

```
    public class OfficesWithScriptFields
    {
        public string Id{ get; set; }
        public string Name { get; set; }
        public GeoLocation Location { get; set; }
        // public object fields { get; set; } => property is null
        // public object Fields { get; set; } => property is null
        // public object myDistance{ get; set; } => property is null
        // public object mydistance{ get; set; } => property is null
    }
```

Raw json ouput : 
```
...
,
        "fields" : {
          "mydistance" : [
            265.0396545087881
          ]
        },
...
```

**How my TDocument POCO should be designed to have a chance getting my script fields (from Hits collection as I understood) ?**

**Comment by russcam** [comment]
Hi @NicolasReyDotNet,

`TDocument` maps to the `_source` returned for each search hit, which is the verbatim JSON that was sent to Elasticsearch. 

Script fields can be accessed on the response in a similar way to stored fields, with

```c#
var client = new ElasticClient();
	
var searchResponse = client.Search<Document>(s => s
	.Query(q => q.MatchAll())
);

foreach(var hit in searchResponse.Hits)
{
	var fields = hit.Fields;
	var myDistance = fields.Value<double>("mydistance");
}
```

or using the shorthand

```c#
var client = new ElasticClient();
	
var searchResponse = client.Search<Document>(s => s
	.Query(q => q.MatchAll())
);

foreach(var fields in searchResponse.Fields)
{
	var myDistance = fields.Value<double>("mydistance");
}
```

Take a look at the [Script fields docs](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/script-fields-usage.html) for more info.

**Comment by NicolasReyDotNet** [comment]
Thank you I did finally achieved something similar, it works as expected.
Thank you

**Comment by TanujChauhan07** [comment]
@NicolasReyDotNet 

I am stuck in Nest Query.

I need below json response in NEST Query, Please help me out 
Thanks in advance.
{
  "from": 0,
  "script_fields": {
    "distance": {
      "script": "doc['location'].distanceInKm(28.2487,77.0635)"
    }
  },
  "size": 100
}
