### ISSUE TITLE
S3 Repository Restore/Snapshot bytes per sec settings

### ISSUE THREAD

**Issue by jamesd24** [elastic/elasticsearch-net#4889]
**Is your feature request related to a problem? Please describe.**
The S3RepositorySettings are missing the max_restore_bytes_per_sec and max_snapshot_bytes_per_sec settings.
https://www.elastic.co/guide/en/elasticsearch/plugins/7.6/repository-s3-repository.html

**Describe the solution you'd like**
If the settings are relevant add them to the S3RepositorySettings class.

**Describe alternatives you've considered**
Is there an alternative way to specify these settings when creating the repository?

**Additional context**
I am trying to avoid using the low level client api.

**Comment by russcam** [comment]
Hi @jamesd24,

Thanks for opening. These properties need to be added to the `S3RepositorySettings`. As a workaround for now, you'd be able to use the low level client to send these

```c#
var client = new ElasticClient();

var response = client.LowLevel.Snapshot.CreateRepository<CreateRepositoryResponse>(
	"repository_name",
	PostData.Serializable(new
	{
		type = "s3",
		settings = new
		{
			bucket = "foobucket",
			max_restore_bytes_per_sec = "50mb",
			max_snapshot_bytes_per_sec = "50mb"
		}
	})
);

```

**Comment by jamesd24** [comment]
@russcam Thanks for the work around. I was trying to avoid using the low level client but, that looks like the only way for now.
