### ISSUE TITLE
Capturing Request JSON Without Disable Direct Streaming?

### ISSUE THREAD

**Issue by thollowell** [elastic/elasticsearch-net#4954]
in the NEST 6.x code we were able to 'capture' the requests without disabling direct streaming. We did this via the small extension method below and it seems to work well. We were able to use the captured JSON in postman to troubleshoot our queries. Now all we get is {} from the call. Is there a new way to do this without disabling direct streaming? Generally the IRequest passed is a SearchDescriptor<T>.

Thanks in advance.

Extension method we were using:

public static string GetRequestAsJson(this IRequest request, IElasticClient client)
{
     using (var stream = new MemoryStream(8192))
     {
          client.SourceSerializer.Serialize(request, stream);
          return Encoding.UTF8.GetString(stream.ToArray());
     }
}

**Comment by russcam** [comment]
A similar extension method can be used with 7.x; the serializer resolves type information differently however, such that the specific request interface must be used. For example

```c#
using Elasticsearch.Net;

public static class ExtensionMethods
{
	public static string GetRequestAsJson<TRequest>(this TRequest request, IElasticClient client)
		where TRequest : IRequest =>
		client.SourceSerializer.SerializeToString(request);
}
```

some examples

```c#
var client = new ElasticClient();

var request = new SearchRequest
{
	Query = new MatchAllQuery()
};

var json = request.GetRequestAsJson<ISearchRequest>(client); // <-- cast to ISearchRequest interface.

var putJobRequest = new PutJobDescriptor<object>("job_id")
	.Description("my ML job")
	.AnalysisConfig(a => a
		.BucketSpan("1m")
		.CategorizationFieldName("field1")
	)
	.ModelPlot(m => m
		.Enabled()
	);
	
var json = putJobRequest.GetRequestAsJson<IPutJobRequest>(client); // <-- cast to IPutJobRequest interface
```

**Comment by russcam** [comment]
Hope the information above helps @thollowell. I'm closing this issue.

**Comment by thollowell** [comment]
Indeed it did. 
Thanks Russ
