### ISSUE TITLE
NEST v.7.8.2 on framework 4.6.2 -> Method not found: 'Nest.DateHistogramAggregationDescriptor

### ISSUE THREAD

**Issue by meriturva** [elastic/elasticsearch-net#4955]
**NEST/Elasticsearch.Net version**:
7.8.2
**Elasticsearch version**:
7.8.1

**Description of the problem including expected versus actual behavior**:
After updating NEST to 7.8.2 we always have exception. With 7.8.1 no problem.

`{"message":"An error has occurred.","exceptionMessage":"Method not found: 'Nest.DateHistogramAggregationDescriptor`1<!0> Nest.DateHistogramAggregationDescriptor`1.CalendarInterval(Nest.DateInterval)'.","exceptionType":"System.MissingMethodException","stackTrace":"   at xxx.Statistics.Persistence.Repositories.PreparationStatisticsRepository.<>c__DisplayClass8_1.<GetPerformanceAsync>b__5(DateHistogramAggregationDescriptor`1 b)\r\n   at Nest.AggregationContainerDescriptor`1._SetInnerAggregation[TAggregator,TAggregatorInterface](String key, Func`2 selector, Action`2 assignToProperty)\r\n   at Nest.AggregationContainerDescriptor`1.DateHistogram(String name, Func`2 selector)\r\n   at xxx.Statistics.Persistence.Repositories.PreparationStatisticsRepository.<>c__DisplayClass8_0.<GetPerformanceAsync>b__4(AggregationContainerDescriptor`1 preparationPerformanceAgg)\r\n   at Nest.BucketAggregationDescriptorBase`3.<>c.<Aggregations>b__15_0(TBucketAggregationInterface a, Func`2 v)\r\n   at Nest.Fluent.Assign[TDescriptor,TInterface,TValue](TDescriptor self, TValue value, Action`2 assign)\r\n   at Nest.BucketAggregationDescriptorBase`3.Assign[TValue](TValue value, Action`2 assigner)\r\n   at Nest.BucketAggregationDescriptorBase`3.Aggregations(Func`2 selector)\r\n   at xxx.Statistics.Persistence.Repositories.PreparationStatisticsRepository.<>c__DisplayClass8_0.<GetPerformanceAsync>b__2(FilterAggregationDescriptor`1 queryFilter)\r\n   at Nest.AggregationContainerDescriptor`1._SetInnerAggregation[TAggregator,TAggregatorInterface](String key, Func`2 selector, Action`2 assignToProperty)\r\n   at Nest.AggregationContainerDescriptor`1.Filter(String name, Func`2 selector)\r\n   at xxx.Statistics.Persistence.Repositories.PreparationStatisticsRepository.<>c__DisplayClass8_0.<GetPerformanceAsync>b__1(AggregationContainerDescriptor`1 ag)\r\n   at Nest.SearchDescriptor`1.Aggregations(Func`2 aggregationsSelector)\r\n   at xxx.Statistics.Persistence.Repositories.PreparationStatisticsRepository.<>c__DisplayClass8_0.<GetPerformanceAsync>b__0(SearchDescriptor`1 sd)\r\n   at Nest.Extensions.InvokeOrDefault[T,TReturn](Func`2 func, T default)\r\n   at Nest.ElasticClient.<SearchAsync>d__248`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()\r\n   at xxx.Statistics.Persistence.Repositories.PreparationStatisticsRepository.<GetPerformanceAsync>d__8.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at mata.Server.WebApi.Controllers.PerformanceStatisticsController.<GetPerformanceAsync>d__3.MoveNext() in D:\\Projects\\git.loccioni.com\\mata\\mata.Server.WebApi\\Controllers\\PerformanceStatisticsController.cs:line 45\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__1`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__5.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.Tracers.HttpControllerTracer.<ExecuteAsyncCore>d__10.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()"}`

**Comment by russcam** [comment]
Hi @meriturva, this looks like a [breaking change that was introduced in 7.8.2](https://github.com/elastic/elasticsearch-net/releases/tag/7.8.2) for Date Histogram aggregation intervals. The fluent method taking a `DateInterval` was changed to accept `DateInterval?`:

https://github.com/elastic/elasticsearch-net/pull/4856/files#diff-5dbb3d46ddb501e1934cfd64fbd165b6R199.

We strive not to introduce breaking changes into the client within a major version lineage. In this case, we took the decision to make a breaking change because the mapping for intervals were such that the client API allowed passing parameters that would not be accepted by Elasticsearch.

**Comment by russcam** [comment]
Hope the information above helps in resolving this for you, @meriturva. I'm going to close this issue.

**Comment by meriturva** [comment]
I will try to fix it based on your comment next week.
Thanks.

I will report the results here.

**Comment by meriturva** [comment]
I finally updated version to NEST 7.9.0 and issue is not anymore present.

Thanks.
