### ISSUE TITLE
Am I doing something wrong, or am I expecting slow speeds with 1+ billion documents in an index?

### ISSUE THREAD

**Issue by mortenmoulder** [elastic/elasticsearch-net#4968]
**NEST/Elasticsearch.Net version**: 7.8.2/7.9.0 (just tried updating)

**Elasticsearch version**: 7.4.1

**Description of the problem including expected versus actual behavior**:
First time working with Elastic at work, and I noticed that getting results is quite slow. We do have 1+ billion (yes, with a B) documents in an index and we log 50+ million records per day. The things we log are simply Apache requests, which include stuff such as hostnames, which domain was requested, which file was requested, and so on.

I have a very simple query: **Get all documents on a given domain within a specified date range**

I've only tried 24, 48, and 72 hours, and each response time increases exponentially, it seems. I do realise looking through 50-150 million documents is a lot.

JSON equivalent of my query:

```
{
    "from": 0,
    "query": {
        "bool": {
            "filter": [
                {
                    "match_phrase": {
                        "servername": {
                            "query": "www.website.com"
                        }
                    }
                },
                {
                    "range": {
                        "@timestamp": {
                            "gte": "2020-08-18T12:43:39.419257"
                        }
                    }
                }
            ]
        }
    },
    "size": 1000,
    "sort": [
        {
            "@timestamp": {
                "order": "desc"
            }
        }
    ],
    "_source": {
        "includes": [
            "request",
            "@timestamp"
        ]
    }
}
```

This query is replicated by opening Kibana, adding the `servername` (with value) as a filter and changing the date range to 48 hours. It only returns `request` (which file was requested) and `@timestamp` (when it was added), because I changed the `_source` to only include those two.

My NEST query can be seen here:

```
SearchDescriptor<ApacheRequest> Query(SearchDescriptor<ApacheRequest> qc)
{
    var query = qc
        .Source(sr => sr
            .Includes(i => i.Fields(
                    f => f.Request,
                    f => f.Timestamp
                )
            )
        )
        .Query(q =>
            q.Bool(b =>
                b.Filter(
                    f => f.MatchPhrase(mp => mp
                        .Field(fi => fi.Servername)
                        .Query(domain)
                    ),
                    f => f.DateRange(r =>
                        r.Field(fi => fi.Timestamp).GreaterThanOrEquals(from)
                    )
                )
            )
        );

    return query;
}
```

and the search with an anonymous type, so we can reuse this code:

```
var searchResponse = await client.SearchAsync<T>(sd =>
{
    var f = Query;

    var sdResult = sd
        .From(0)
        .Take(1000)
        .Sort(s =>
            s.Descending("@timestamp") //all models have @timestamp so this is fine
        );

    sdResult = f(sdResult);

    //get JSON
    //var json = client.RequestResponseSerializer.SerializeToString(sdResult, SerializationFormatting.Indented);

    return sdResult.Scroll("2m");
});
```

I have tried with `.ScrollAll()` and various other methods, but this is by far the fastest one. 

The above code returns:
~25.000 documents for 24 hours in ~6 seconds
~45.000 documents for 48 hours in ~15 seconds

So my question is: Is this expected? Is 45.000 records in 15 seconds acceptable? Can my query be optimized? 

I have no idea where else to ask than here, so hopefully someone has an answer. Thanks.

**Comment by russcam** [comment]
Hi @mortenmoulder

A good first place to ask questions like this one is the discuss forums at https://discuss.elastic.co/c/elastic-stack/elasticsearch/6. More folks peruse the forums than this repository and there are large parts to this question which are more generally about Elasticsearch than the client, so it's likely you'd get some good responses and suggestions there.

It's difficult to know if this is expected as there are a number of factors to look at, _before_ looking at the client, I think:

1. Which version of Elasticsearch are you using?
2. How many nodes are you running and what's the configuration?
3. How many indices and shards are you searching across?
4. Does the cluster have monitoring on it, and if so, what do resources look like when performing the query?
5. What do cluster stats and node stats look like when performing the query?
6. What does the index mapping look like?

**Comment by mortenmoulder** [comment]
Hi @russcam and thanks for the reply.

After talking to our team, it appears that we're definitely not running enough nodes. In another cluster I can query 800.000 documents and create a date histogram in less than 2 seconds, so I've put the other department on the task to merge the clusters together (4 vs 32 nodes, where the one with 4 nodes has 10 times as many documents).

I'll close this one. Thanks!

**Comment by russcam** [comment]
No worries @mortenmoulder!

One thing that may help for your use case if you're often performing sorting by `@timestamp` frequently is to consider using [index sorting](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-index-sorting.html) on the `@timestamp` field - note that index sorting can decrease write performance in favour of optimizing query performance. [Take a look at the blog post on index sorting](https://www.elastic.co/blog/index-sorting-elasticsearch-6-0) for more details.
