### ISSUE TITLE
Getting Nodes-Stats from NEST 7.6.2 is not possible for Elastic 7.8.1

### ISSUE THREAD

**Issue by ratinhoo** [elastic/elasticsearch-net#4969]
**NEST/Elasticsearch.Net version**: 7.6.2

**Elasticsearch version**: 7.8.1

**Description of the problem including expected versus actual behavior**:
Getting the nodes stats from NEST does not work for NEST 7.6.2 and Elasticsearch 7.8.1. This seems to be a breaking change. Apparently a new role "remote_cluster_client" has been added in Elastic 7.7 and NEST 7.6.2 can not handle it.

**Steps to reproduce**:
 1. Call new ElasticClient(connectionSettings).Nodes.Stats(new NodesStatsRequest());
 2. An Exception is thrown: "Der angeforderte Wert "remote_cluster_client" konnte nicht gefunden werden." (remote_cluster_client not found)
 

**Expected behavior**
Since NEST 7.6.2 should be compatible to all 7.* Elasticsearch versions this should work.

**Comment by russcam** [comment]
This is an unfortunate consequence of mapping Elasticsearch enums returned as strings as enums in the client; if Elasticsearch introduces a new enum member in a new version e.g. 7.7.0, then clients prior to 7.7.0 will throw an exception when deserializing a response that contains that new enum member. This is what is happening and the best course of action is to update the client to the latest 7.x version.

We have discussed changing the mapping of enums to use strings, or to use types that wrap string values and have static readonly properties on them for comparisons. It would be awesome [if C# supported something like Rust's `non_exhaustive` attribute](https://doc.rust-lang.org/reference/attributes/type_system.html#the-non_exhaustive-attribute), but it doesn't as far as I am aware.
