### ISSUE TITLE
HTTP Header Propagation / Distributed Tracing / Service Mesh, OpenTelemetry

### ISSUE THREAD

**Issue by sunsided** [elastic/elasticsearch-net#4981]
**Is your feature request related to a problem? Please describe.**

In a distributed system of microservices, calls to Elasticsearch are not observable since NEST doesn't seem to allow for distributed tracing.

Using [OpenTelemetry in ASP.NET Core](https://github.com/open-telemetry/opentelemetry-dotnet) applications will automatically instruct ASP.NET Core to register incoming tracing headers (W3C's `traceparent`, Zipkin's `x-b3-traceid`, ...), as well as instruct `HttpClient` instances created through an `IHttpClientFactory` to send these tracing headers to the upstream service. Since NEST creates its own `HttpClient` instances, it doesn't receive the according middleware and thus is a dead end for distributed tracing.

**Describe the solution you'd like**

I'd like the NEST client to work with OpenTelemetry, use an injected `IHttpClientFactory` or at least provide some means of injecting HTTP headers into the outgoing call. Header propagation would be the most trivial step, but going for OpenTracing appears to be a safe bet.

**Describe alternatives you've considered**

I went through the source code to figure out extension points for the HTTP calls. It appears that internally, a custom `HttpClient` factory is used and that there is no way to sneak in an externally provided client. I noticed that Diagnostics Sources are available which would at least make it possible to provide a trace span _in_ the application, but upstream connections wouldn't see it. Concretely, Istio utilizes the Envoy proxy to inspect HTTP traffic, which in turn will make use of HTTP request headers for tracing - because of that, _sending_ these headers is important even though Elasticsearch itself may not care.

**Additional context**

Here's how a trace looks like in Jaeger; outgoing HTTP calls are visible, but the call going through NEST is missing.

![nest-invisible](https://user-images.githubusercontent.com/495335/91039022-13899080-e60c-11ea-9784-922ccbc3b6b6.png)

As far as headers go, [OpenTelemetry](https://opentelemetry.io/) is a standard framework for distributed tracing by means of [W3C Trace Context](https://www.w3.org/TR/trace-context/) (`traceparent` and `tracestate`) HTTP headers; services Meshes like Istio automatically [provide distributed tracing](https://istio.io/latest/docs/tasks/observability/distributed-tracing/) for incoming and outgoing HTTP calls by means of `x-b3-*` headers; Google uses `x-cloud-trace-context` etc.

**Comment by Mpdreamz** [comment]
Just dropping a short note 

I was going to reply that you can use:

```csharp
var settings = new ConnectionSettings()
	.GlobalHeaders(new NameValueCollection())
	.OnRequestDataCreated(requestData =>
	{
		// requestData.Headers ??= new NameValueCollection();
		requestData.Headers.Add("traceparent", ...);
	});
```

To inject headers dynamically before each request. However `Headers` has a private setter and is not guaranteed to have a value. You can cheat by creating a global headers collection through `GlobalHeaders`, this ensures `request.Headers` has a value assigned that you can dynamically add more headers to. 

You can also instrument the client with our own APM agent. That implementation is built on diagnostic listener and should allow you to built spans not just for HTTP requests but also serialization costs.
https://github.com/elastic/apm-agent-dotnet/pull/329#issuecomment-616718098 This should be able to be adapted for OpenTelemetry as well.  This won't solve generic outside listener solutions though. 

Thank you for raising this, we'll definitely create a cleaner story around attaching headers dynamically.

Most likely through something like:

```csharp
var settings = new ConnectionSettings()
	.GlobalHeaders(new NameValueCollection())
	.RequestHeaders(headers =>
	{
		headers.Add("traceparent", Activity.Current....);
	});
```

**Comment by sunsided** [comment]
Thank you! I'll give your suggestion a try in the meantime.

**Comment by stevejgordon** [comment]
Picking this up in another wider piece of work.
