### ISSUE TITLE
Searching fields with special character

### ISSUE THREAD

**Issue by ptrknow** [elastic/elasticsearch-net#4989]
In my database, there is a field name called "@timestamp" which starts with a special character "@". Is it possible to search this field 
using the NEST client?

In particular, I want to write something like below, which obviously didn't work:
```C#
var searchResponse = client.Search<Project>(s => s
  .Query(q => q
    .DateRange(r => r
      .Field(f => f.@timestamp // here
  ...
```

**Comment by mortenmoulder** [comment]
```
public class Project
{
    [Date(Name = "@timestamp")]
    public DateTime Timestamp { get; set; }
}
```

Add that property together with the attribute to your `Project` class. You can read more in the documentation about [mapping](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/attribute-mapping.html).

**Comment by russcam** [comment]
Hi @ptrknow

As @mortenmoulder proposes, one way is to use attribute mapping. Another way would be to define the default mapping for `Project` on `ConnectionSettings`

```c#
public class Project
{
    public DateTime Timestamp { get; set; }
}

var projectsIndex = "projects";
var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));

var settings = new ConnectionSettings(pool)
    .DefaultMappingFor<Project>(i => i
        .IndexName(projectsIndex)
        .PropertyName(p => p.Timestamp, "@timestamp")
    );

var client = new ElasticClient(settings);

var createIndexResponse = client.Indices.Create("projects", s => s
        .Map<Project>(m => m
            .AutoMap()
        )
    );

var searchResponse = client.Search<Project>(s => s
    .Query(q => q
        .DateRange(r => r
          .Field(f => f.Timestamp)
          .GreaterThan(DateMath.Now)
        )
    )
);
```

results in

```json
PUT http://localhost:9200/projects
{
  "mappings": {
    "properties": {
      "@timestamp": {
        "type": "date"
      }
    }
  }
}

POST http://localhost:9200/projects/_search
{
  "query": {
    "range": {
      "@timestamp": {
        "gt": "now"
      }
    }
  }
}
```

The `Field` type has implicit conversions from `string`, `PropertyInfo` and `Expression<Func<TDocument, TProperty>>` so you could do simply

```c#
var searchResponse = client.Search<Project>(s => s
    .Query(q => q
        .DateRange(r => r
          .Field("@timestamp")
          .GreaterThan(DateMath.Now)
        )
    )
);
```

**However**, you likely want the client to map the `@timestamp` returned in the `_source` document to a property on the `Project` type, in which case the client needs to be told about this either with attribute mapping or `DefaultMappingFor<T>`
