### ISSUE TITLE
Applying different serialization attributes to the same class in different scenarios?

### ISSUE THREAD

**Issue by winzig** [elastic/elasticsearch-net#4990]
**Is your feature request related to a problem? Please describe.**

We currently are building two ElasticSearch indices. One indexes our `User` object, and is used in some of our staff tools to help us search our users based on any property. 

The second indexes our `Message` object, and part of each `Message` is an `Author` property, of type `User`. The same class that is getting indexed completely in our users index described above.

When we index Users into the users index, we want all the properties indexed. 

When we index User associated with a Message, we only want to index a few of the User properties. 

**Describe the solution you'd like**

Looking for a way to specify two different ways of indexing the same class, depending on the ES index it's going into. So far I've only used `[Attributes]` to flag indexing, e.g. [Nest.Ignore]. This seems unusable for this specific scenario, however.

**Describe alternatives you've considered**

Currently I am working around this situation by creating a completely separate class, called `Author`, which takes in a `User` object and uses it to build an Author object that exposes only a few of the same properties (the ones we want to index). I'd like to avoid this hack if possible.

**Comment by Mpdreamz** [comment]
> Currently I am working around this situation by creating a completely separate class, called Author, which takes in a User object and uses it to build an Author object that exposes only a few of the same properties (the ones we want to index). I'd like to avoid this hack if possible.

I'll be honest, I think this is the most elegant and functional way to solve this and far from a hack. 
You have the need to model two different DTO's and this makes that very explicit. 


The only way to do what you want is to write a custom converter and annotating the `Author` property on `Message` with that converter that will take precedence over the default way to serialize.

If you use https://www.nuget.org/packages/NEST.JsonNetSerializer/ then you can follow Json.NET guidance around custom converters. If you use our default serializer you can do this through: https://github.com/neuecc/Utf8Json#jsonformatterattribute


That said this will cause information loss on write and on read your `User` instances will be anemic. You now have to deal with two types of Users, a complete one read from the user index and an anemic one that was set on `Message`. Modeling this explicit as two different types is more elegant IMO.

**Comment by russcam** [comment]
> If you use our default serializer you can do this through: https://github.com/neuecc/Utf8Json#jsonformatterattribute

Small note, we don't expose the ability to use JsonFormatters with the default serializer, so hooking up JsonNetSerializer is the easiest path.
