### ISSUE TITLE
Please help ，NEST SearchRequest is bug，see the  jpg

### ISSUE THREAD

**Issue by wjhmiss** [elastic/elasticsearch-net#4991]
![c0c717cf75492aa69347d55b0f6b60d](https://user-images.githubusercontent.com/6950490/91328135-109fc300-e7f9-11ea-9402-8b7292faa8ac.png)
please help me，This problem has been bothering me for days

**Comment by wjhmiss** [comment]
help me help me help me

**Comment by russcam** [comment]
Hi @wjhmiss, please can you edit the issue to include the source code - it'll help in investigating. Thanks!

**Comment by wjhmiss** [comment]
public async Task<string> test()
        {
            //第一种 In this case ，use SearchDescriptor，  output the result is right
            SearchDescriptor<RecordInputDTO> query = new SearchDescriptor<RecordInputDTO>();
            query.Aggregations(p => p.Nested("caseReason", n => n
              .Path(p => p.caseReason)
              .Aggregations(aa => aa
                  .Terms("caseReason", t => t
                      .Field("caseReason.text")
                  )
              )
            ));
            query.Index("cprecord");
            var response1 = await EsClient.SearchAsync<RecordInputDTO>(query);

            //第二种  this case ，use SearchRequest， output the result is error，nested Node is missing the peer aggs node. Please see the picture
            var request = new SearchRequest("cprecord") { Aggregations = new AggregationDictionary() };
            AggregationContainer aggcompanys = new AggregationContainer();
            aggcompanys.Nested = new NestedAggregation("caseReason")
            {
                Path = "caseReason",
                Aggregations = new TermsAggregation("caseReason")
                {
                    Field = "caseReason.text",
                }
            };
            request.Aggregations.Add("caseReason", aggcompanys);
            var response2 = await EsClient.SearchAsync<RecordInputDTO>(query);

            return "";
        }

        public class RecordInputDTO 
        {
            public string Id { get; set; }
            [Nested]
            public List<anyou> caseReason { get; set; }
        }
        public class anyou
        {
            [Keyword]
            public string value { get; set; }
            [Keyword]
            public string text { get; set; }

        }
![c0c717cf75492aa69347d55b0f6b60d](https://user-images.githubusercontent.com/6950490/91378573-5c7f5600-e853-11ea-9db4-930f76ccb4ff.png)

**Comment by russcam** [comment]
What version of NEST are you using?

**Comment by wjhmiss** [comment]
7.8.2

**Comment by wjhmiss** [comment]
I tried 7.9.0 ,Neither

**Comment by wjhmiss** [comment]
![1598498943(1)](https://user-images.githubusercontent.com/6950490/91380851-8b4bfb00-e858-11ea-8b44-93fe7c398543.png)
a moment ago，i tried 7.9.0，7.8.0，7.8.1  7.8.2 。 but  No effect

**Comment by russcam** [comment]
This works

```c#
var request = new SearchRequest("cprecord") { Aggregations = new AggregationDictionary() };
AggregationContainer aggcompanys = new NestedAggregation("caseReason")
{
	Path = "caseReason",
	Aggregations = new TermsAggregation("caseReason")
	{
		Field = "caseReason.text",
	}
};
request.Aggregations.Add("caseReason", aggcompanys);
var response2 = await client.SearchAsync<RecordInputDTO>(request);
```

which can be shortened to

```c#
var request = new SearchRequest("cprecord") 
{
	Aggregations = new NestedAggregation("caseReason")
	{
		Path = "caseReason",
		Aggregations = new TermsAggregation("caseReason")
		{
			Field = "caseReason.text",
		}
	}
};

var response2 = await client.SearchAsync<RecordInputDTO>(request);
```

Will need to investigate more why the original way posted doesn't work. 

Note that there's a bug in your example

```c#
var response2 = await EsClient.SearchAsync<RecordInputDTO>(query);
```

should be

```c#
var response2 = await EsClient.SearchAsync<RecordInputDTO>(request);
```

**Comment by wjhmiss** [comment]
tks you reply，i try it

**Comment by wjhmiss** [comment]
![1598500696(1)](https://user-images.githubusercontent.com/6950490/91382594-a3be1480-e85c-11ea-852c-32acc53dabcc.png)
Thank you very much. Finally, I come to China. If you travel to China, I will treat you to dinner
