### ISSUE TITLE
Elasticsearch.Net.UnexpectedElasticsearchClientException: expected:'{', actual:'19.0', at offset:740

### ISSUE THREAD

**Issue by nealsu** [elastic/elasticsearch-net#4992]
**NEST/Elasticsearch.Net version**: **7.7.1**

**Elasticsearch version**:**6.5.3**

**Description of the problem including expected versus actual behavior**:

The document format:
![image](https://user-images.githubusercontent.com/880872/91674124-725e8500-eb8b-11ea-89f8-2ca4a0429d6a.png)

The object format:
![image](https://user-images.githubusercontent.com/880872/91674145-8dc99000-eb8b-11ea-8ed1-a2cb8c9003a6.png)

The struct has an implicit double operator.
![image](https://user-images.githubusercontent.com/880872/91674325-5dcebc80-eb8c-11ea-8320-94db6b736a53.png)

**Result = Exception **
Elasticsearch.Net.UnexpectedElasticsearchClientException: expected:'{', actual:'19.0', at offset:740
---> Elasticsearch.Net.Utf8Json.JsonParsingException: expected:'{', actual:'19.0', at offset:740
   at Elasticsearch.Net.Utf8Json.JsonReader.ReadIsBeginObjectWithVerify()
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )

**Expected behavior**
Expected the mapper to able to identify the property can be treated as `Number` and set the double value to the `Struct` with implicit double operator.

Is there away to enforce this value conversion?

**Comment by Mpdreamz** [comment]
No not with the builtin `Utf8Json`. If you can not remodel you poco your best bet is to use Json.NET for the serialization

see: https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html#_jsonnetserializer
