### ISSUE TITLE
editorconfig braces rule not applying in Visual Studio

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elasticsearch-net#4998]
Not a product bug, but an observation during development. When editing C# files in Visual Studio the editor is defaulting to putting braces on the same line as class, method declarations.

This appears to be caused by the line:

```
csharp_new_line_before_open_brace = all:error
```

From what I can tell, this is an invalid value causing it not to apply at all. Changing it (as per the line below) fixes it for me.

```
csharp_new_line_before_open_brace = all
```

I can submit this in a small PR, if you agree this is appropriate?

cc @russcam / @Mpdreamz

**Comment by Mpdreamz** [comment]
👍 please fire away.

Formatting conventions do not accept `value:<severity>` 

https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-formatting-conventions?view=vs-2019

Only Language Conventions do: https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-language-conventions?view=vs-2019

There might be a couple of other mistakes in our `.editorconfig` like this

**Comment by stevejgordon** [comment]
PR submitted 😄
