### ISSUE TITLE
ExtendedStats with one document -> UnexpectedElasticsearchClientException

### ISSUE THREAD

**Issue by meriturva** [elastic/elasticsearch-net#5007]
**NEST/Elasticsearch.Net version**:
7.9.0
**Elasticsearch version**:
7.9.1

**Description of the problem including expected versus actual behavior**:
Using ExtendedStats on a numeric value on one document generates always an exception:

```
    "message": "An error has occurred.",
    "exceptionMessage": "expected:'Number Token', actual:'\"NaN\"', at offset:179002",
    "exceptionType": "Elasticsearch.Net.UnexpectedElasticsearchClientException",
```

ps: I really don't know if the issue was present before, actually we working usually with a lot of documents, so this is the first time we see only one document after filtering our index and the first time in years that we see this exception.

**Expected behavior**
No exception but an empty result.

**Comment by meriturva** [comment]
Actually now I'm just filtering my results based on document count calculated on a pre query.
My first question is related to the issue...is it confirmed? any news from nest team? @russcam for example.

Secondly, how to avoid a pre query to filter data? is it possible to calculate ExtendedStats based on document count > 1 on the same query?

**Comment by russcam** [comment]
Hi @meriturva, this _looks_ like a bug. 

`NaN` is a peculiarity in JSON, which might be supported in a number of ways. The server is sending it as a string `"NaN"`, but the internal client serializer will not accept a string, but would accept it as `NaN`. I think we'll need to address this in the client.

> ps: I really don't know if the issue was present before,

I've not seen Elasticsearch return `NaN` before. This may have come in with the addition of standard deviation and variance sampling to extended stats in https://github.com/elastic/elasticsearch/pull/49782

**Comment by meriturva** [comment]
In meanwhile, any workaround to avoid double query (to filter aggregation without documents)?
I don't found any way to enable aggregation based on document count resulting in parent aggregation, so I have now to execute a more one query just to check document presents.

**Comment by meriturva** [comment]
Hi @russcam I just would like to ask news about that issue or maybe a cool workaround to avoid double queries.
So thanks.

**Comment by meriturva** [comment]
Just to know @russcam ...is it fixed on 7.10 version?

**Comment by russcam** [comment]
Hi @meriturva

there's no change in NEST for this yet. There's been some discussion about whether Elasticsearch should be returning `NaN` at all, given the ambiguity of representing it in JSON. No conclusion has been reached yet though.

@Mpdreamz, @stevejgordon perhaps we can check for `"NaN"` in the offending fields? I _think_ it's the addition of the sampling fields in extended stats, but would need double checking.

**Comment by yBother2** [comment]
Just updated form 7.6 and encountered the very same problem.
This is a major problem for me as I have data as following:
` {
        "_index" : "datapoints-batches-1-a",
        "_type" : "_doc",
        "_id" : "e08a4fe9-6156-4646-a27b-a8153322d575-637329369540000000",
        "_score" : 1.0,
        "_ignored" : [
          "value"
        ],
        "_source" : {
          "id" : "e08a4fe9-6156-4646-a27b-a8153322d575-637329369540000000",
          "batchId" : "batches-1-A",
          "parameterId" : "e08a4fe9-6156-4646-a27b-a8153322d575",
          "timestamp" : "2020-08-13T17:35:54Z",
          "value" : "NaN"
        }
 }`

which I wrote an a custom converter for:
`                writer.WriteValue("NaN");`

**Comment by yBother2** [comment]
> 
> 
> Hi @meriturva
> 
> there's no change in NEST for this yet. There's been some discussion about whether Elasticsearch should be returning `NaN` at all, given the ambiguity of representing it in JSON. No conclusion has been reached yet though.
> 
With ES 7.6 "NaN" has been returned - at aleast when index is set to ignore malformed values.
Not returning already stored "NaN" values is **not acceptable**.

**Comment by meriturva** [comment]
same issue un 7.11.1
any news @russcam here?

**Comment by jmisaxobank** [comment]
I am experiencing the very same problem (in my case it's on 7.10.0), and can confirm that the NaN comes from the computed "sampling" fields, not from my documents.

```
    "extended_stats#my_extendedstats_agg" : {
      "count" : 1,
      "min" : -269.0,
      "max" : -269.0,
      "avg" : -269.0,
      "sum" : -269.0,
      "sum_of_squares" : 72361.0,
      "variance" : 0.0,
      "variance_population" : 0.0,
      "variance_sampling" : "NaN",
      "std_deviation" : 0.0,
      "std_deviation_population" : 0.0,
      "std_deviation_sampling" : "NaN",
      "std_deviation_bounds" : {
        "upper" : -269.0,
        "lower" : -269.0,
        "upper_population" : -269.0,
        "lower_population" : -269.0,
        "upper_sampling" : "NaN",
        "lower_sampling" : "NaN"
      }
    }
```

 I really just need to compute the standard deviation, don't even know what the "sampling" fields are used for.

**Comment by russcam** [comment]
I've opened https://github.com/elastic/elasticsearch-net/pull/5404 to address

**Comment by jmisaxobank** [comment]
Awesome, thanks!!!

**Comment by Vycka** [comment]
NEST/Elasticsearch.Net version:
7.12.1
Elasticsearch version:
7.10.1

Hello, FYI - same type of issue still exists, but from for me from different line of code in both master and and 7.13:
* https://github.com/elastic/elasticsearch-net/blob/3d0c0e2a183241ff3e9150054be308319dbd4d70/src/Nest/Aggregations/AggregateFormatter.cs#L461
* https://github.com/elastic/elasticsearch-net/blob/1e60c117a27c2ba2d678b586238c5acfa60680ee/src/Nest/Aggregations/AggregateFormatter.cs#L469
