### ISSUE TITLE
custom ITokenizer implementations Serialize is not expected

### ISSUE THREAD

**Issue by fate1009** [elastic/elasticsearch-net#5036]
custom ITokenizer implementations Serialize is not expected.
https://github.com/elastic/elasticsearch-net/pull/5035

CLA — Author of some commits did not sign a contributor agreement

**Comment by fate1009** [comment]
i have signed,but is not valid.

**Comment by Mpdreamz** [comment]
Closed via #5065 

Thanks again @fate1009
