### ISSUE TITLE
JSON parsing properties all caps 

### ISSUE THREAD

**Issue by jpspane** [elastic/elasticsearch-net#5043]
**NEST/Elasticsearch.Net version**:
7.9
**Elasticsearch version**:
7.9
**Description of the problem including expected versus actual behavior**:

Trying to upgrade from a 6.5 cluster. We have a few properties that are all caps in their name like COIN, ABCD, etc.. those do not seem to serialize into the C# class that was used as the template in the elastic client Search. If I switch to using Json.Default when creating the Elastic client then that parser picks up those values. Not sure what is going as there is no errors. Those properties are null. If I print out the raw json string response the values are in the response so this appears to be just parsing issue. Thanks for any advice in the matter.
**Steps to reproduce**:
 1.
 2.
 3.

**Expected behavior**
That the json response from elastic is serialized into the C# object just like it is doing under version 6.5 .

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by Mpdreamz** [comment]
The 7.0 client depends on UTF8Json wich is not lenient with property names. 

By using `JsonNetSerializer.Default` your are using `Json.NET` for your objects which can (and is) configured to lenient. 


https://github.com/JamesNK/Newtonsoft.Json/issues/815


We won't reintroduce this behaviour in the `UTF8Json`. 

Thanks for reporting!
