### ISSUE TITLE
DocCount is reported incorrectly by NEST library for nested aggregations

### ISSUE THREAD

**Issue by elkhiyarih** [elastic/elasticsearch-net#5047]
**Elasticsearch version**: 
7.6.0

**NEST  version**: 
7.6.1

**Elasticsearch.Net version**: 
7.5.1

**Description of the problem including expected versus actual behavior**:
The `DocCount` property of the `KeyedBucket` object overestimates the number of documents in the bucket likely including the count of all nested subdocuments. There seems to be no way in NEST to get the count of documents in the bucket without including nested documents 

**Steps to reproduce**:
 1. This behavior is observed when the `IncludeInParent` property is set to true for nested fields but may also occur if the property is set to false

**Expected behavior**
`DocCount` property in NEST should return the correct number of documents in the bucket similar to the `doc_count` property returned by the REST API

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by Mpdreamz** [comment]
Hey @elkhiyarih Did you mean to close this?

**Comment by elkhiyarih** [comment]
Yes, this issue can be closed. It turned out that NEST was not using the default index and was searching all indices on the server which explains the higher than expected count. By specifying the index name in the query, the issue was resolved.
