### ISSUE TITLE
Add 'version' mapping type 

### ISSUE THREAD

**Issue by fredeil** [elastic/elasticsearch-net#5050]
Add attribute mapping and Fluent mapping for the version type (see https://www.elastic.co/guide/en/elasticsearch/reference/master/version.html)

**Additional context**
See this issue https://github.com/elastic/elasticsearch/issues/48878, https://github.com/elastic/elasticsearch/pull/62692 and https://github.com/elastic/elasticsearch/pull/59786.

**Comment by stevejgordon** [comment]
Thanks for raising this @fredeil. This is also included in the items in #5096 and is in my list to pick up after the next piece of work with a view to getting it into the next release. I'll close this as we're tracking in the meta ticket.
