### ISSUE TITLE
_client.LowLevel.SearchAsync<>() api ignoring type and index name defined in SearchDescriptor<>() object

### ISSUE THREAD

**Issue by naveadkazi** [elastic/elasticsearch-net#5051]
**NEST/Elasticsearch.Net version**:5.6.5

**Elasticsearch version**:5.4.3

**Description of the problem including expected versus actual behavior**:

We are trying to fetch result from our index using the LowLevelClient. We are using the below `SearchAsync` API

```C#
          var searchDescriptor = new SearchDescriptor<MyType>()
                                                       .Type("mytype")
                                                       .Index("myindex")
                                                       .Query(....)
                                                       .Aggregation(ag => ag.Terms(... Aggregation(ag1 => ag1.Min(...TopHits(...)))));
            var memoryStream = new MemoryStream();
            _client.Serializer.Serialize(searchDescriptor, memoryStream);
            var response = await _client.LowLevel.SearchAsync<byte[]>(memoryStream.ToArray()).ConfigureAwait(false);
           //_client - instance of Nest.ElasticClient
           //Next Step - Deserialize the response
```
**Actual Behaviour -** The client is ignoring type and index name and calling POST `/_search` api
**Expected Behaviour -** The client should call POST `/myindex/mytype/_search` api

This is giving me results from another index(a combination of result from various index) and my deserialization is breaking.

**Steps to reproduce**:
 1. Call `_client.LowLevel.SearchAsync<>()` with index and type defined in SearchDescriptor object
 2. observe the ElasticsearchResponse.DebugInformstion property to check the API that is called.

**Expected behavior**
The client should call POST `/myindex/mytype/_search` api

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by naveadkazi** [comment]
Found a workaround

The `_client.LowLevel.SearchAsync<>()` method have overloaded method `_client.LowLevel.SearchAsync<T>(string indexName, string typeName, T t)`

Passing the index name and type name will narrow to search to that particular index.

But the question still remains, why it is not taking the index and type name from `SearchDescriptor` object?

**Comment by Mpdreamz** [comment]
When you target the low level client the `SearchDescriptor` only describes the the querystring parameters and body of the request.

The low level client has no knowledge of `SearchDescriptor<>()` and how it exposes the path parameters.

Thanks for reporting but I dont think this is actionable. The work around is the intended usage.
