### ISSUE TITLE
Custom JsonConverter is not honored when serializing script parameters.

### ISSUE THREAD

**Issue by prochnowc** [elastic/elasticsearch-net#5074]
**NEST/Elasticsearch.Net version**: 7.9.0

**Elasticsearch version**: 7.9.1

**Description of the problem including expected versus actual behavior**:

I have a custom JsonConverter registered to serialize Guid types using the shorter "N" format. To register custom
serializer I followed the guide at https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html.

So far my custom converter works fine for document types, but as soon as I start to add complex script parameters which have Guid's inside my custom converter is not used anymore. 

**Expected behavior**

Expected behavior is that a custom JsonConverter is used for document types and script parameters.

**Comment by russcam** [comment]
Relates: #4971 

Closing this issue to consolidate discussion on the existing issue. @prochnowc please feel free to upvote the existing issue and discuss there.
