### ISSUE TITLE
Unable to specify _id when indexing documents

### ISSUE THREAD

**Issue by ohmattyo** [elastic/elasticsearch-net#5122]
**NEST/Elasticsearch.Net version**: 7.10.0

**Elasticsearch version**: 7.10.0

**Description of the problem including expected versus actual behavior**:
It currently appears that we are unable to specify the field we would like to use as the "_id" field when indexing data, and because of this cannot prevent data duplication.

**Steps to reproduce**:
`[ElasticsearchType(IdProperty = nameof(RecID))]` or `[ElasticsearchType(IdProperty = "RecID")]`
`settings.DefaultMappingFor<SequenceLog>(m => m
    .IdProperty(p => p.RecID)
);`

**Expected behavior**
I would expect that my resulting data would use the value of my "RecID" in the "_id" field, but as you can see below, the "_id" field is null when being submitted.

**Provide `ConnectionSettings` (if relevant)**:
`
var settings = new ConnectionSettings(Utils.CreateElasticsearchConnectionSettings(log));
settings.DefaultMappingFor<SequenceLog>(m => m
    .IdProperty(p => p.RecID)
);
settings.EnableDebugMode();
var client = new ElasticClient(settings);
`

**Provide `DebugInformation` (if relevant)**:
Request:
{"index":{"_id":null}}
{"recID":22000001,"id":"22000001","orgID":10030,"compID":100010608,"timestampUTC":"2020-10-02T21:37:36Z","opID":"XXXXX","source":"Payment-GenerateNextInvoice()","detailMessage":"Begin GenerateNextInvoice()... | pIn = ","detailJson":"{\r\n\t\"paymentRecID\": XXX\r\n"}

Response:
{
  "took" : 126,
  "errors" : false,
  "items" : [
    {
      "index" : {
        "_index" : "sequence-log",
        "_type" : "_doc",
        "_id" : "d-nRAHYBepd6Fz1C5l_S",
        "_version" : 1,
        "result" : "created",
        "_shards" : {
          "total" : 2,
          "successful" : 1,
          "failed" : 0
        },
        "_seq_no" : 5000,
        "_primary_term" : 1,
        "status" : 201
      }
    }
  ]
}

**Comment by stevejgordon** [comment]
Hi @ohmattyo! I've taken an initial look at this an I'm unable to replicate. Are you able to provide more of the code you're using to index the document? Here's a .NET 5 sample I've used and I'm seeing the expected PUT request and when querying, the _Id is set correctly.

```c#
using Elasticsearch.Net;
using Nest;
using System;

var settings = new ConnectionSettings()
    .DefaultIndex("sequence_logs");
    //.DefaultMappingFor<SequenceLog>(m => m.IdProperty(p => p.RecID)); 

var client = new ElasticClient(settings);

await client.IndexDocumentAsync(new SequenceLog
{
    RecID = 22000001,
    OrgID = 10030,
    Source = "Payment-GenerateNextInvoice()"
});

var searchResponse = await client.LowLevel.GetAsync<DynamicResponse>("sequence_logs", "22000001");

if (searchResponse.Success)
    Console.WriteLine($"ID: {searchResponse.Get<string>("_id")}");

await client.LowLevel.Indices.DeleteAsync<VoidResponse>("sequence_logs");

[ElasticsearchType(IdProperty = nameof(RecID))]
internal class SequenceLog
{
    public int RecID { get; set; }
    public int OrgID { get; set; }
    public string Source { get; set; }
}
```

### PUT request:
_Note that the ID is sent in the path._
```
PUT http://localhost:9200/sequence_logs/_doc/22000001 HTTP/1.1
Host: localhost:9200
Accept: application/json
User-Agent: elasticsearch-net/7.10.0+fc84ad2c2f86ec60ac54f022cf431cf9f5236ca1 (Microsoft Windows 10.0.19042; .NET 5.0.0; Nest)
Content-Type: application/json
Content-Length: 73

{"recID":22000001,"orgID":10030,"source":"Payment-GenerateNextInvoice()"}
```

### PUT response:

```
HTTP/1.1 201 Created
Location: /sequence_logs/_doc/22000001
content-type: application/json; charset=UTF-8
content-length: 168

{"_index":"sequence_logs","_type":"_doc","_id":"22000001",
"_version":1,"result":"created","
_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1}
```

**Comment by ohmattyo** [comment]
Thanks for the example, that got us on the right track to finding the issue. The problem was that my class definition (that I did not yet provide, as we were able to find the issue when attempting to combine your example with my code for a more concise  example to post here) did not contain the getters and setters which made them fields instead of auto implemented properties.

**Comment by stevejgordon** [comment]
You're welcome @ohmattyo. I'm glad your up and running.
