### ISSUE TITLE
async call to elastic client search async method throws an error for system.diagnostics.diagnosticsource

### ISSUE THREAD

**Issue by zissop** [elastic/elasticsearch-net#5134]
**NEST/Elasticsearch.Net version**:
7.10
**Elasticsearch version**:
7.10

**Description of the problem including expected versus actual behavior**:
Any fix for the old problem with system.diagnostics.diagnosticsource? I mean ElastiSearch.Net references the old 4.0.3.1 version of the dll and produces problems / crashes on runtime. We talk about latest Nuget packages.

its the same porblem as here -> https://stackoverflow.com/questions/57503422/facing-issue-when-the-nest-dll-upgraded-for-elastic-search

I have a project without any dependency on System.Diagnostics.DiagnosticSource. This dependency is included only as part of the ElasticSearch / Nest library.

Only way to avoid this is to include the app.config (or web.config) with the below:
```
<dependentAssembly>
        <assemblyIdentity name="System.Diagnostics.DiagnosticSource" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
</dependentAssembly>
```

Using ILSpy it seems ElleasticSearch .Net somehow references the 4.0.3.1 version.

https://ibb.co/ckqx5Nd

**Comment by stevejgordon** [comment]
Hi @zissop. I'm going to try and carve some time to investigate this later this week. Elasticsearch.NET 7.10.0 explicitly references 4.5.1 of DiagnosticSource so not sure where the 4.0.31 reference is coming from at the moment.

**Comment by stevejgordon** [comment]
@zissop - I was able to see the same in ILSpy for 7.10.0 as in your screenshot.

In 7.10.1 (released this week) we updated our dependency to DiagnosticSource 5.0.0 and checking in ILSpy, that seems to resolve to the expected version. 

![image](https://user-images.githubusercontent.com/3669103/101638225-b7fdda00-3a25-11eb-9056-a6a1904a86d4.png)

I've build two small .NET 4.6.1 console apps which use the low-level client versions 7.10.0 and 7.10.1 to perform `SearchAsync<T>`. Both run without exceptions being thrown so I'm not entirely able to reproduce the runtime crash you experienced.

Could you please try using 7.10.1 initially to see if the updated dependency there improves the situation at all? If not, are you able to provide a small repro sample that I can investigate further? Thanks in advance.

**Comment by stevejgordon** [comment]
@zissop I wanted to follow up one more time to see if you're still experiencing this on the latest release or able to assist with a sample to reproduce it?

**Comment by dnauck** [comment]
Hello @stevejgordon ,

this issue is back. The `Elasticsearch.Net 7.11.1` NuGet package references `System.Diagnostics.DiagnosticSource (>= 5.0.0)` but required exactly 5.0.0.0. A manual bindingRedirect is required because System.Diagnostics.DiagnosticSource 5.0.1 exists and is resolved by Paket.

**Comment by stevejgordon** [comment]
@dnauck Thanks for letting us know. Would you mind opening a new issue please with the steps to reproduce it as simply as possible. We can then investigate further.
