### ISSUE TITLE
Unable to update Null as a value to a existing property in case of update

### ISSUE THREAD

**Issue by KillerAyce** [elastic/elasticsearch-net#5152]
**NEST/Elasticsearch.Net version**:  NEST 7.10

**Elasticsearch version**: 7.8.0

**Description of the problem including expected versus actual behavior**: I am trying to update Null values in a Nullable Datetime field but couldn't able to, Serializer seems to ignore Nulls.
**Things i have tried so far : **
1. inject a custom serializer which includes NULL getting an exception  :  "Could not load type 'Nest.CartesianPoint' from assembly 'Nest, Version=7.0.0.0";
2. Tried Null value attribute (I am using attribute mapping) turns out i am not able to set a NullValue for Nullable Date time. 
3. manually updated mapping in Elastic search using kibana and set a Min Value. No success either

**Steps to reproduce**:
 1. Create a partial model with some Nullable date fields.
 2. Insert values with date fields containing values.
 3. Try to update a null next time on those date fields which were set in Step 1.
4. Couldnt able to Set NullValue in attribute mapping for Nullable date field

**Expected behavior**
I want to update Null value in datefields

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by stevejgordon** [comment]
@KillerAyce I am investigating the `NullValue` property on the attribute as I believe I understand what's likely the problem there. Have you tried defining your mapping using the [Fluent syntax](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/fluent-mapping.html)?

Something like this...

```c#
var createIndexResponse = client.Indices.Create("null-sample", c => c
    .Map<Book>(m => m
        .Properties(ps => ps
            .Date(d => d.Name(n => n.PublishDate).NullValue(DateTime.MinValue))
        )
    )
);
```

So that I can understand the issue better, are you able to provide a small sample of your model and how you are indexing it with NEST?

**Comment by stevejgordon** [comment]
@KillerAyce Further to the above, [this comment](https://github.com/elastic/elasticsearch-net/issues/3930#issuecomment-509512750) further explains some of the options for updating with null values.

**Comment by KillerAyce** [comment]
> 
> 
> @KillerAyce Further to the above, [this comment](https://github.com/elastic/elasticsearch-net/issues/3930#issuecomment-509512750) further explains some of the options for updating with null values.

I was able to solve this problem by using CustomJsonNetSerializer.
I was not overriding the following method
`       protected override void ModifyContractResolver(ConnectionSettingsAwareContractResolver resolver) =>
            resolver.NamingStrategy = new CamelCaseNamingStrategy();`
Thanks

**Comment by stevejgordon** [comment]
Thanks @KillerAyce. I'm very pleased you got this working. Thanks for sharing your final solution. I'll close this now and open a new issue to review the NullValue attribute property for DateTime.
