### ISSUE TITLE
Nested attribute

### ISSUE THREAD

**Issue by NigelYu** [elastic/elasticsearch-net#5170]
I want to use the Nested attribute, but it does not take effect, what should I do
![image](https://user-images.githubusercontent.com/4321593/101763993-7ef36180-3b1a-11eb-92fe-2b1760c293a2.png)

![image](https://user-images.githubusercontent.com/4321593/101763451-c2999b80-3b19-11eb-943d-b2bc6d02be20.png)

**Comment by stevejgordon** [comment]
@NigelYu How have you configured your mapping with `AutoMap` which is required to get the attribute mappings to take effect?

```c#
var createIndexResponse = _client.Indices.Create("grades", c => c
    .Map<Grade>(m => m.AutoMap())
);
```

**Comment by NigelYu** [comment]
@stevejgordon Yes, I used it, but the same does not work, this is my code
```c#
Grade grade = new Grade
{
                Id = "1",
                GradeName = "一年级",
                Persons = new List<Person> {
                    new Person
                    {
                        Id = "zhangshan",
                        FullName = "张珊"
                    },
                    new Person
                    {
                        Id = "lisi",
                        FullName = "李四"
                    }
                }
            };
            var elasticClient = GetElasticClient("http://192.168.20.15:9200/");
            var createIndexResponse = elasticClient.Indices.Create("nigel", c => c
                    .Map<Grade>(m => m.AutoMap())
            );
            elasticClient.Index<Grade>(grade,p=>p.Index("nigel"));
```
![image](https://user-images.githubusercontent.com/4321593/101847177-97509400-3b8d-11eb-8cc5-06cc1a652cce.png)

**Comment by stevejgordon** [comment]
I have a suspicion that the `Store = true` property is not valid for the mapping. Can you try removing that. When I repro locally, that causes the create index request to fail. Without it, it is mapped as nested.

**Comment by NigelYu** [comment]
Yes, I tried it, he works normally, thanks

**Comment by stevejgordon** [comment]
That's good to here @NigelYu. Thanks for raising this as it highlights an issue with the attribute accepting that property. I'll open an issue to review that further.
