### ISSUE TITLE
IdsQuery without Values returns all results

### ISSUE THREAD

**Issue by TheFireCookie** [elastic/elasticsearch-net#5171]
Hello guys,

**NEST/Elasticsearch.Net version**: 7.10.0

**Elasticsearch version**: 7.9.3

**Description of the problem including expected versus actual behavior**:
1) Create a new IdsQuery
2) Don't put any ids in the Values field of the IdsQuery
3) Do a search and expect to have no results as there is no id provided (it work like that in ElasticSearch with a REST call)

**Expected behavior**
The IdsQuery is still serialized and apply against Elasticsearch, so no results comes up.

Matthias.

**Comment by russcam** [comment]
The query will be treated as conditionless without IDs, resulting in it not forming part of the serialized query. [The query can be marked `.Verbatim()` to serialize exactly as is.](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/verbatim-and-strict-query-usage.html).

**Comment by TheFireCookie** [comment]
Ah I'll try that right now! The workaround I had was to add a new guid to simatre the behavior mais it's a crappy workaround 😂

**Comment by TheFireCookie** [comment]
Ok it work with IsVerbatim, sorry I didn't saw this in the code & in the documentation. Have a nice day!
