### ISSUE TITLE
Different exception message in .Net Framework compared to dotnet core

### ISSUE THREAD

**Issue by mostmand** [elastic/elasticsearch-net#5173]
**NEST/Elasticsearch.Net version**: 7.10.1

**Elasticsearch version**: 7.4.0

**Description of the problem including expected versus actual behavior**:
When a search request has syntax error, nest returns a response with status set to BadResponse and an OriginalException containing an informative message about the syntax error. When I use a project targeted for .Net framework 4.7 the error message is different compared to when a project is targeted for dotnet core 3.1.

For example when I use an erroneous query like this:
```json
{"query":{"match":
```
Dotnet core exception message which  I think is the expected behavior:
`Request failed to execute. Call: Status code 400 from: POST /sample/_search. ServerError: Type: parsing_exception Reason: "Expected [START_OBJECT] but found [VALUE_STRING]"`

.Net Framework exception message which is incomplete and uninformative:
`The remote server returned an error: (400) Bad Request.. Call: Status code 400 from: POST /sample/_search`

**Steps to reproduce**:

  **Suppose that http://localhost:9200 is URI of a running elasticsearch node that has an index called 'my-index'**
 1. Create a project that references Nest nuget package version 7.10.1 and consists of a class Program which is implemented like this:
```csharp
using Elasticsearch.Net;
using Nest;
using System;
using System.Threading.Tasks;

namespace NestBug
{
    class Program
    {
        static async Task Main(string[] args)
        {
            IElasticClient client = CreateElasticClient("http://localhost:9200");
            var response = await client.LowLevel.SearchAsync<BytesResponse>("my-index", CreateInvalidSearchRequestBody());
            Console.WriteLine(response.OriginalException.Message);
        }

        private static PostData CreateInvalidSearchRequestBody()
        {
            return "\"query\":{\"match\":";
        }

        private static IElasticClient CreateElasticClient(string initialUri)
        {
            var uri = new Uri(initialUri);
            var connectionSettings = new ConnectionSettings(uri);
            return new ElasticClient(connectionSettings);
        }
    }
}

```
 2. Use target framework net47 for the project.
 3. Run the program. You'll get this message printed:
`The remote server returned an error: (400) Bad Request.. Call: Status code 400 from: POST /sample/_search`
4. Use target framework netcoreapp3.1
5. Run the program. You'll get this message printed:
`Request failed to execute. Call: Status code 400 from: POST /sample/_search. ServerError: Type: parsing_exception Reason: "Expected [START_OBJECT] but found [VALUE_STRING]"`

**Expected behavior**
Both messages of stage 3 and 5 to be equal and be informative enough for the user to understand the error like the one in stage 5.

**Comment by mostmand** [comment]
I cloned the source code and tried to debug the problem. It seems that different IConnection implementations in netstandard and net461 is the reason why different exception messages are created.

**Comment by mostmand** [comment]
Is there any progress?

**Comment by stevejgordon** [comment]
Hi @mostmand! My apologies. This issue slipped past me! My initial thought is that is likely due to differences in how the frameworks report exceptions. I'll dig into our code to see if we do anything extra that may account for this where our transport layer does diverge based on the target framework.

**Comment by stevejgordon** [comment]
Are you still able to reproduce this when using v7.12.1 @mostmand? While I don't think we intentionally changed anything, I'm seeing a more complete error running from a .NET Framework 4.7.2 console app:

```
The remote server returned an error: (400) Bad Request.. Call: Status code 400 from: POST /my-index/_search. ServerError: Type: parsing_exception Reason: "Expected [START_OBJECT] but found [VALUE_STRING]"
```

The first part of our exception string (before "Call:") is dependent on the exception returned by the framework and will vary. The incorrect double period character bugs me and I'll fix that up. 

I'd like to understand how is this impacting your use of the library?

**Comment by stevejgordon** [comment]
@mostmand Did you have a chance to test this on v7.12 of the client?

**Comment by mostmand** [comment]
I tested it on NEST 7.12.1 and Elasticsearch server 7.11.1. The difference is still there. My use case is that a user writes a query and I'm going to show the results of the search query. When the user's query has syntax error, it would be helpful to give him/her a comprehensible error message. As a workaround if I reference the netstandard 2.0 DLL of NEST manually, it works correctly even if I target .NET Framework 4.7 but it's kind of hacky because updating the DLL manually could cause some problems.

**Comment by stevejgordon** [comment]
@mostmand I've taken a fresh look at this and I don't think we'll make any changes in this area. The difference is due to the underlying runtime differences. `HttpWebRequest` is used on .NET Framework and this throws the exception when the request fails. This is returned as the original exception which is valid. For .NET Core/5/6, `HttpClient` is used which doesn't throw in the same way, so our own failure exception is returned for the failed request. These are ultimately platform differences that consuming code needs to handle.
