### ISSUE TITLE
Nested mapping attribute and descriptor incorrectly accept "Store" property

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elasticsearch-net#5174]
**NEST/Elasticsearch.Net version**: 7.10.1

**Elasticsearch version**: 7.10.0

**Description of the problem including expected versus actual behavior**:
When using attribute mappings to define a Nested type, the attribute accepts a Store property. Elasticsearch returns an error when attempting such a mapping. We should evaluate removing this property given that it is not supported and also check that it's removed from the fluent mapping also. This is 

This relates to the discussion in #5170

**Steps to reproduce**:
 1. Create a type which includes a Nested attribute for one of the properties. 
 2. Include `Store = true` in the attribute
 3. Elasticsearch will return an error - "Mapping definition for [field] has unsupported parameters: [store : true]"

**Expected behavior**
NEST should not offer the store property for nested field mappings.

**Comment by russcam** [comment]
Related: https://github.com/elastic/elasticsearch-net/issues/3145

**Comment by stevejgordon** [comment]
Thanks @russcam 👍

**Comment by stevejgordon** [comment]
Attribute mappings are no longer supported for v8.
