### ISSUE TITLE
Issues and PRs marked 7.9.1 should be included in 7.10.0 release notes

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#5175]
There are some issues and PRs that are marked for a 7.9.1 release, but a 7.9.1 release never went out:

https://github.com/elastic/elasticsearch-net/pulls?q=label%3Av7.9.1+

All these issues and PRs should be updated to be tagged with 7.10.0, and included in the 7.10.0 release notes.

**Comment by stevejgordon** [comment]
Thanks @russcam. Those are updated.
