### ISSUE TITLE
[TESTS] TransformApiTests throwing JsonParsingException

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#5185]
It looks like some of the TransformApiTests are failing on CI due to a JsonParsingException:

https://github.com/elastic/elasticsearch-net/pull/5177/checks?check_run_id=1561871433

- Tests.XPack.Transform.TransformApiTests.StopTransformResponse
- Tests.XPack.Transform.TransformApiWithSettingsTests.ReturnsExpectedResponse
- Tests.XPack.Transform.TransformApiTests.DeleteTransformResponse
- Tests.XPack.Transform.TransformApiWithSettingsTests.ReturnsExpectedStatusCode

```
Elastic.Transport.UnexpectedTransportException : expected:'Number Token', actual:'"2014-12-29T00:00:00.000Z"', at offset:79
---- Nest.Utf8Json.JsonParsingException : expected:'Number Token', actual:'"2014-12-29T00:00:00.000Z"', at offset:79`
```

**Comment by stevejgordon** [comment]
I believe @Mpdreamz has some commits which address these failures in his WIP transport PR.

**Comment by Mpdreamz** [comment]
#5046 has some fixes for timeouts, not for this parsing issue.

**Comment by stevejgordon** [comment]
Confirmed these occur on the new 7.11 branch so will fix as part of getting that prepared.
