### ISSUE TITLE
Cannot preview SearchResponse<JObject> in debugging (only on 7.10.1)

### ISSUE THREAD

**Issue by prcdpr** [elastic/elasticsearch-net#5276]
**NEST/Elasticsearch.Net version**:

7.10.1 (7.10.0 works alright)

**Elasticsearch version**:

does not matter

**.NET Runtime version**:

5.0

**Description of the problem including expected versus actual behavior**:

It's not possible to preview SearchResponse<JObject> properties when debugging following code:

```csharp
var response = await elasticClient.SearchAsync<JObject>(s => s);
; // Set breakpoint here.
```

Expected (7.10.0):
![image](https://user-images.githubusercontent.com/43776797/104914636-bcf06a80-598f-11eb-80b9-2333461357db.png)

Actual:
![image](https://user-images.githubusercontent.com/43776797/104914311-3cca0500-598f-11eb-814a-d9a37d18c8ec.png)

VS2019 has the same problem:
![image](https://user-images.githubusercontent.com/43776797/104915081-67688d80-5990-11eb-8228-496d4ed593de.png)

(notice missing expand button)

**Comment by stevejgordon** [comment]
Hi @prcdpr. I can't seem to reproduce this locally using...

```csharp
const string userName = "elastic";
const string password = "hidden";

var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));
var settings = new ConnectionSettings(pool, sourceSerializer: JsonNetSerializer.Default)
    .BasicAuthentication(userName, password)
    .DefaultIndex("stackoverflow")
    .EnableDebugMode(r => { });

var client = new ElasticClient(settings);
var response = await client.SearchAsync<JObject>(s => s);
var thing = response.Documents.Count;

Console.WriteLine("done");
```
Are you able to access the documents and if an exception is thrown, provide the stack trace? If not already, could you try [enabling debug mode](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/debug-mode.html) to collect the value from DebugInformation as well?

If the contents cannot be shared publically, feel free to drop them to us at: microsoft @ elastic.co (without spaces) and ping me here so I can check for it.

**Comment by stevejgordon** [comment]
@prcdpr I'm just following up to see if we can assist you further on this issue?

**Comment by prcdpr** [comment]
I'll try to prepare a repro for this in following days, if it won't be possible then we'll close this issue.

**Comment by stevejgordon** [comment]
@prcdpr I'll close for now but we can reopen if you identify this in a repro. Thanks!
