### ISSUE TITLE
Add metric for time spent on Deserialization

### ISSUE THREAD

**Issue by kimipsen** [elastic/elasticsearch-net#5281]
At times, it would be really nice to have a built-in metric for time spent on the deserialization process in general.

My use case is when looking at requests in general and the time spent on each part in our application, it is hard to distinguish between the actual call to ElasticSearch and the time it takes to deserialize our objects (are they too big, do we deserialize fewer to reduce time spent etc). 

For the time being I've settled on a simple timer surrounding the entire request, and then subtract the time spent on the request, which is found in the `Took` property.

**Comment by Mpdreamz** [comment]
We have these metrics as part of our `DiagnosticSource` support:

Here's an example of our APM agent using it to create more detailed spans of the client internals

https://github.com/elastic/apm-agent-dotnet/pull/329#issuecomment-616718098

![image](https://user-images.githubusercontent.com/245275/105334586-58275100-5bd7-11eb-9961-618cc524e96b.png)


See our docs here how to listen manually: https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/diagnostic-source.html

Hope this helps!
