### ISSUE TITLE
Performance issue with large request

### ISSUE THREAD

**Issue by trongvodang** [elastic/elasticsearch-net#5283]
**NEST/Elasticsearch.Net version**:
7.1.0. i also try 7.10.1
**Elasticsearch version**:
7.1.1
**Description of the problem including expected versus actual behavior**:
We have built one API with .net and NEST. We had some issues with performance. So I have added timers that I log to check what is taking most of the time when we do a search
**Steps to reproduce**:
```c#
private readonly ElasticClient elasticSearchClient;
        public ElasticSearchService(IHttpClientFactory httpClientFactory)
        {
            var settings = new ConnectionSettings(new Uri(appSettings.ElasticSearch.Host)).DefaultIndex(appSettings.ElasticSearch.PlaceIndexName);
            elasticSearchClient = new ElasticClient(settings);
        }
        private async Task<IList<Place>> SearchTextSuggestElasticAsync()
        {
            var time1 = DateTime.Now;
            ISearchResponse<Place> searchResponse = // some query;
            var requestTime = (DateTime.Now - time1).TotalMilliseconds;
            if ((requestTime - searchResponse.Took) > 300)
            {
                log.Warn($"the difference : {(requestTime - searchResponse.Took)} End request in {requestTime} took: {searchResponse.Took}");

            }
            var data = searchResponse.Documents.ToList();
            return data;
        }
```
It's fine with a single request,  but when I make about 100 request/s, `requestTime` with much larger than `took` from ElasticSearch
I try to use HttpClient factory to do same number of request, it does not happen. So it does not network issue
In above code, a lot of log was written
the difference : 364.1491 End request in 529.1491 took :165
the difference : 351.0123 End request in 531.0123 took :180
the difference : 605.7492 End request in 747.7492 took :142
the difference : 587.7566 End request in 776.7566 took :189
the difference : 389.3551 End request in 492.3551 took :103
**Expected behavior**

**Comment by Mpdreamz** [comment]
Quick comment on this before diving in further:

* what os are you using?
* Is `ElasticClient` or `ElasticsearchService` registered as a singleton or reused for each invocation of `SearchTextSuggestElasticAsync` ?

**Comment by trongvodang** [comment]
I an using ubuntu 18.04, i also try on win 10 pro deploy on local machine
with iis.
Using .net core 3.1
ElasticClient and ElasticSearchService register as signleton
Thanks

Vào Th 5, 21 thg 1, 2021 lúc 17:33 Martijn Laarman <notifications@github.com>
đã viết:

**Comment by stevejgordon** [comment]
Thanks @trongvodang - I'll see if I can reproduce this. A further questions...

- How many docs are you getting back from your search?
- Are you using the default `SocketsHttpHandler` in 3.1. So not disabled as specified in [this doc](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=net-5.0).
- How are you load testing this? 
- How long are you testing at 100/s?

**Comment by trongvodang** [comment]
- I got 20 documents for each call
- No, i did not disabled it
- I am using jmeter to call my api, 50 threads, run in few minutes and i
got a lot of log above.


Vào Th 5, 21 thg 1, 2021 lúc 18:34 Steve Gordon <notifications@github.com>
đã viết:

**Comment by stevejgordon** [comment]
@trongvodang I've performed some initial investigation into this. I am able to reproduce a slow down as the number of RPS increases, however, I am also able to see a similar result using the IHttpClientFactory directly. I also compared to using a singleton HttpClient instance. Since you did not measure "slow" requests when using IHttpClientFactory, while I did, are you able to provide an example of how you tested that to see if it may account for the difference.
 
At 10rps all three perform about the same with 0.01% - 0.02% of requests being > 300ms slower than the search time. The mean search request time is also similar - 118ms for HttpClient, 159ms for HttpClientFactory and 180ms using our client. This seems about right since I didn't fully implement the deserialisation for the tests with HttpClient and HttpClientFactory.

At 100rps there's a little more spread but all exhibit many more slower requests. 30% were > 300ms slower than the search time with HttpClient and the mean request time is 310ms. With HttpClientFactory 56% were > 300ms slower than the search time and mean time is 382ms. With our client, 80% were > 300ms slower than the search time and the mean time was 650ms. 

This doesn't seem to be a connection issue as in all cases, the number of open HTTP1.1 connections is equivalent, sitting at around 44 connections while under the 100rps load. I did measure some thread pool queuing initially which improved overtime as the thread count increased.

I'll continue to investigate this further next week to see if I can find any more information and identify a particular improvement that might be required.

**Comment by trongvodang** [comment]
Here we call ES by httpclient factory. 
When drive same traffic as we call ES by your library, no log was written, 
``` c#
/// <summary>
        /// IHttpClientFactory
        /// </summary>
        private readonly IHttpClientFactory httpClientFactory;

        /// <summary>
        /// Elastic search
        /// </summary>
        /// <param name="appSettings"></param>
        public ElasticSearchService(IHttpClientFactory httpClientFactory)
        {
            this.httpClientFactory = httpClientFactory;
        }

/// <summary>
        /// Get result from elastic search
        /// </summary>
        /// <param name="autoSuggest"></param>
        /// <returns></returns>
        private async Task<IList<Place>> SearchTextSuggestElasticAsync2(AutoSuggestSearch autoSuggest)
        {
            var time1 = DateTime.Now;
            IList<Place> rs;
            var text = Utils.Removed(autoSuggest.Text);
            var callingText = // json string  of query, same as we call by NEST & ElasticSearch.net;
            var url = @"host/_search?typed_keys=true";
            var data = new StringContent(callingText, Encoding.UTF8, "application/json");
            var httpclient = httpClientFactory.CreateClient("elasticsearch");
            var response = await httpclient.PostAsync(url, data);
            ElasticResponseSearch result;
            if (response.IsSuccessStatusCode)
            {
                string resultstring = await response.Content.ReadAsStringAsync();
                result = JsonConvert.DeserializeObject<ElasticResponseSearch>(resultstring);
                var temp = result.Hits.Hits;
                rs = temp.Select(m => m.Source).ToList();
            }
            else
            {
                throw new Exception("error when searching");
            }
            var requestTime = (DateTime.Now - time1).TotalMilliseconds;
            if ((requestTime - result.Took) > 300)
            {
                log.Warn("the difference : " + (requestTime - result.Took) + " End request in " + requestTime + " took :" + result.Took);

            }
            return rs;
        }
````

**Comment by stevejgordon** [comment]
Thanks again @trongvodang. May I also confirm that you are running your tests against the application built in release mode? I've observed that in my tests with Debug mode, the throughput is significantly decreased.

**Comment by trongvodang** [comment]
I deployed with release mode.
You mean you do not get slow down as the number of RPS increasing when
deploy with release mode?

Vào Th 2, 25 thg 1, 2021 lúc 18:57 Steve Gordon <notifications@github.com>
đã viết:

**Comment by stevejgordon** [comment]
In my initial tests, it performs well even at 200rps and higher (when built in release mode). This is tested on my local dev machine sending requests to an Elastic Cloud instance of Elasticsearch. For 50 connections, 100rps, and 2,000 total requests all were successful and the mean response time for my measurement was 19ms.

You can see and try my sample at: https://github.com/stevejgordon/ElasticsearchClientPerfTesting. Perhaps you can test how this performs for you?

When you run in production, how is your application hosted?

**Comment by stevejgordon** [comment]
Note that the sample used .NET 5.0 for some additional performance counters I wanted to see, but I have also tested against `netcoreapp3.1` with good results.

**Comment by trongvodang** [comment]
Can you share your repo?

Vào Th 2, 25 thg 1, 2021 lúc 19:47 Steve Gordon <notifications@github.com>
đã viết:

**Comment by stevejgordon** [comment]
@trongvodang It's linked in my previous comment - https://github.com/stevejgordon/ElasticsearchClientPerfTesting

**Comment by trongvodang** [comment]
Thanks, i will give it a try when i comeback to company

Vào Th 2, 25 thg 1, 2021 lúc 19:50 Steve Gordon <notifications@github.com>
đã viết:

**Comment by trongvodang** [comment]
I think I got a key point.
The problem will happen when I make a complex query. 
The performance is great when I use a simple query like you. `s=>s.Size(20)`
Both codes also have low `took`. 
I think slow performance will happen with generation of query code, not httpclient or webrequest. 
My query code:
```c#
searchResponse = await elasticSearchClient.SearchAsync<Place>(s => s
                    .Query(qu => qu.Bool(boo => boo
                                        .Must(mu => mu.DisMax(di => di.TieBreaker(0).Queries(que => que
                                          .QueryString(m => m
                                              .Query($"{text}").DefaultOperator(Operator.And)
                                              .Fields(fi => fi.Field("name_address_suggest")
                                              .Field("address_acronym_suggest"))
                                              .Analyzer("standard_analyzer_extract_words").Escape()), que => que
                                          .QueryString(m => m
                                              .Query($"{text}").DefaultOperator(Operator.And)
                                              .Fields(fi => fi.Field("name_suggest"))
                                              .Analyzer("standard_analyzer_extract_words").Escape()))))
                                        .Should(mu => mu.DisMax(di => di.TieBreaker(0.1).Boost(4)
                                            .Queries(que => que
                                              .QueryString(m => m
                                                  .Query($"\"{text}\"").DefaultOperator(Operator.And)
                                                  .Fields(fi => fi.Field("name_address_suggest")
                                                  .Field("address_acronym_suggest")).PhraseSlop(10)
                                                  .Analyzer("standard_analyzer").Boost(1).Escape()), que => que
                                              .QueryString(m => m
                                                  .Query($"\"{text}\"").DefaultOperator(Operator.And)
                                                  .Fields(fi => fi.Field("name_suggest")).PhraseSlop(10)
                                                  .Analyzer("standard_analyzer").Boost(2).Escape()))))
                      .Filter(filters))).From(0).Size(CommonConstants.LimitQuery))
````

**Comment by stevejgordon** [comment]
Thanks for the update @trongvodang. When you tested with IHttpClientFactory, were you simply adding `HttpContent` with a string based payload? There will be some overhead to evaluate that query and then to produce the serialised request. It's something I'd like to review and optimise where possible in the next major release, with some small steps along the way in upcoming releases. 

It sounds like your delay is larger than I'd like though. I'll see if I can attempt to reproduce this and profile it on my end. Are you able to share your `Place` type so I can get as close to your situation as possible? How complex are your filters? Do you have an example of the input text here too? How many tokens do you tend to have in there?

Something which may be worth trying is looking at using the object initializer syntax to avoid the various descriptors which need to be evaluated here. Is that perhaps something you could test?

**Comment by trongvodang** [comment]
> were you simply adding HttpContent with a string based payload

yes.

> Are you able to share your Place type

Here is one of my `place`

``` json
{
                    "address": "38, Chi Lăng, Phường Hải Châu II, Quận Hải Châu, Thành Phố Đà Nẵng, Việt Nam",
                    "end_date": "2099-11-29T10:00:00.000Z",
                    "geometry": {
                        "coordinates": [
                            108.216338,
                            16.069428
                        ],
                        "type": "Point"
                    },
                    "id": "5c9845e8814a9df9d67e5eeb",
                    "is_deleted": false,
                    "location": [
                        108.216338,
                        16.069428
                    ],
                    "name": "Sân vận động Chi Lăng",
                    "name_address": "Sân vận động Chi Lăng 38, Chi Lăng, Phường Hải Châu II, Quận Hải Châu, Thành Phố Đà Nẵng, Việt Nam",
                    "object_id": "5b98cd2b2b5c0949ecdcfbfb",
                    "photos": null,
                    "start_date": "2000-11-24T10:00:00.000Z",
                    "types": [
                        "stadium"
                    ]
                }
            }
```
>How complex are your filters? Do you have an example of the input text here too?

I added filters in below code. text is `nguyen van linh`
>How many tokens do you tend to have in there?

I don't know much about it, the index has about 8m records
>Something which may be worth trying is looking at using the object initializer syntax to avoid the various descriptors which need to be evaluated here. Is that perhaps something you could test?

I tested it, and the same problems were happen
```c#
var searchRequest = new SearchRequest<Place>
                {
                    Query = new BoolQuery()
                    {
                        Must = new QueryContainer[]
                        {
                            new DisMaxQuery
                            {
                                TieBreaker=0,
                                Queries= new QueryContainer[]
                                {
                                    new QueryStringQuery()
                                    {
                                        Query = text,
                                        DefaultOperator = Operator.And,
                                        Fields = new Field("name_address_suggest").And("address_acronym_suggest"),
                                        Analyzer = "standard_analyzer_extract_words",
                                        Escape = true
                                    },
                                    new QueryStringQuery()
                                    {
                                        Query = text,
                                        DefaultOperator = Operator.And,
                                        Fields = new Field("name_suggest"),
                                        Analyzer = "standard_analyzer_extract_words",
                                        Escape = true
                                    }
                                }
                            }
                        },
                        Should = new QueryContainer[]
                        {
                            new DisMaxQuery
                            {
                                TieBreaker=0,
                                Queries= new QueryContainer[]
                                {
                                    new QueryStringQuery()
                                    {
                                        Query = $"\"{text}\"",
                                        DefaultOperator = Operator.And,
                                        Fields = new Field("name_address_suggest").And("address_acronym_suggest"),
                                        PhraseSlop=10,
                                        Analyzer = "standard_analyzer",
                                        Boost=1,
                                        Escape = true
                                    },
                                    new QueryStringQuery()
                                    {
                                        Query = $"\"{text}\"",
                                        DefaultOperator = Operator.And,
                                        Fields = new Field("name_suggest"),
                                        Analyzer = "standard_analyzer",
                                        Boost=1,
                                        PhraseSlop=10,
                                        Escape = true
                                    }
                                }
                            }
                        },
                        Filter = new QueryContainer[]
                        {
                                new TermQuery
                                {
                                    Field= new Field("is_deleted"),
                                    Value = false
                                }
                        }
                    },
                    From = 0,
                    Size = 10
                };
```

**Comment by stevejgordon** [comment]
Thanks again @trongvodang. I'll spend some time investigating things with a closer replication of your query.

**Comment by stevejgordon** [comment]
@trongvodang Actually, to replicate fully, are you able to share your mapping for this index also please?

**Comment by trongvodang** [comment]
@stevejgordon here you are
`{"mappings":{"properties":{"address":{"type":"text","store":true,"term_vector":"yes","eager_global_ordinals":true,"similarity":"defaultSimilarity","copy_to":["address_suggest","address_acronym","address_acronym_suggest","house_number"],"analyzer":"standard_analyzer","fielddata":true},"address_acronym":{"type":"text","similarity":"defaultSimilarity","analyzer":"acronym_analyzer","search_analyzer":"standard_analyzer"},"address_acronym_suggest":{"type":"text","similarity":"defaultSimilarity","analyzer":"acronym_suggestion_analyzer","search_analyzer":"standard_analyzer"},"address_suggest":{"type":"text","term_vector":"yes","eager_global_ordinals":true,"similarity":"defaultSimilarity","analyzer":"standard_suggestion_analyzer","search_analyzer":"standard_analyzer","fielddata":true},"end_date":{"type":"date","store":true},"geometry":{"properties":{"coordinates":{"type":"float"},"type":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}},"house_number":{"type":"text","store":true,"similarity":"defaultSimilarity","analyzer":"house_number_analyzer"},"id":{"type":"keyword","index":false,"store":true},"is_deleted":{"type":"boolean","store":true},"location":{"type":"geo_point"},"location_geoshape":{"properties":{"coordinates":{"type":"float"},"type":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}},"name":{"type":"text","store":true,"term_vector":"yes","eager_global_ordinals":true,"similarity":"defaultSimilarity","copy_to":["name_suggest"],"analyzer":"standard_analyzer","fielddata":true},"name_address":{"type":"text","similarity":"defaultSimilarity","copy_to":["name_address_suggest"],"analyzer":"standard_analyzer"},"name_address_suggest":{"type":"text","term_vector":"yes","eager_global_ordinals":true,"similarity":"defaultSimilarity","analyzer":"standard_suggestion_analyzer","search_analyzer":"standard_analyzer","fielddata":true},"name_suggest":{"type":"text","term_vector":"yes","eager_global_ordinals":true,"similarity":"defaultSimilarity","analyzer":"standard_suggestion_analyzer","search_analyzer":"standard_analyzer","fielddata":true},"object_id":{"type":"keyword","index":false,"store":true},"photos":{"properties":{"name":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},"url":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}}}},"start_date":{"type":"date","store":true},"tags":{"type":"keyword","store":true},"types":{"type":"keyword","store":true}}}}`

**Comment by stevejgordon** [comment]
Thanks @trongvodang. I've performed an initial test this morning with a modified sample, using your query and an index more closely matching your own. In release mode, I'm afraid I'm still unable to replicate the delay you're seeing.

```
{"slowCount":14,"totalRequests":2000,"averageRequestTime":25}
```

25ms mean request time seems pretty reasonable. I'm going to do some profiling on the query generation but right now, I'm unable to isolate an issue to go after.

**Comment by trongvodang** [comment]
How are you load testing this? what tool? can you share config of tool?

**Comment by stevejgordon** [comment]
I'm using [bombardier](https://github.com/codesenberg/bombardier) for the testing.

```
E:\> bombardier -c 50 -r 100 -n 2000 https://localhost:5001
Bombarding https://localhost:5001 with 2000 request(s) using 50 connection(s)
 2000 / 2000 [=========================================================================================================================================================================================================] 100.00% 16/s 1m59s
Done!
```

I've also going to repeat this on Linux as well later this morning as I've been testing on Windows currently.

**Comment by stevejgordon** [comment]
I'm getting similar results on Ubuntu as well...

```
{"slowCount":0,"totalRequests":2000,"averageRequestTime":21}
```

**Comment by stevejgordon** [comment]
@trongvodang If I push up my changes to my repro repository, do you want to give it a go on your system and see if you produce different results?

**Comment by trongvodang** [comment]
> @trongvodang If I push up my changes to my repro repository, do you want to give it a go on your system and see if you produce different results?

yes please

**Comment by trongvodang** [comment]
hi @stevejgordon with http client factory, please use `Newtonsoft.Json` instead of `System.Text.Json`
```c#
var resultstring = await response.Content.ReadAsStringAsync();
var searchResponse = JsonConvert.DeserializeObject<SearchResponse>(resultstring);
```

**Comment by stevejgordon** [comment]
@trongvodang With 100 concurrent connections I still get good results (tested on Windows):

```
{"slowCount":15,"totalRequests":2000,"averageRequestTime":31}
```

Note that the connection should be https when running the sample on port 5001:

```
bombardier -c 100 -r 100 -n 2000 https://localhost:5001
```

I've pushed a repro onto [this branch](https://github.com/stevejgordon/ElasticsearchClientPerfTesting/tree/5283).

I've not updated to `Newtonsoft.JSON" as I've only been testing the direct client usage since that is producing reasonable results. Feel free to tweak accordingly.

**Comment by trongvodang** [comment]
Thanks @stevejgordon 
I try to create a new index with 1 document, it fast as your result. But with 8.000.000 records in an index, it slow ( it still ok with HTTP client factory)
`{"slowCount":926,"totalRequests":2128,"averageRequestTime":1660}`
I only change es URL. 
I don't know why this happens.

**Comment by stevejgordon** [comment]
@trongvodang I'm failing to think of any reason a larger number of documents in the index would change anything client side. I'd expect the query to take longer on the server due to the very large index. On the client, as long as only 20 hits are returned, there's no extra overhead on the request or response. If I provide instructions, are you able to run my perf sample on .NET 5 as we can use the new HTTP counters to make sure there's nothing unusual happening. I'll also see if the sample can be updated to record other TCP stats in a useful manor.

Internally our code uses some of the IHttpClientFactory code and we use Utf8Json serialiser which should be more performant. If you want you can follow [this documentation](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html#_jsonnetserializer) to enable Newtonsoft JSON in our and re-run your tests both against a small and large index.

**Comment by trongvodang** [comment]
Yes, .net 5 is fine
I also read utf8json is fatester than newtonsoft json, but in my case, utf8json is slower, i only change small code to deserialize using newtonsoft instead utf8json 😂

**Comment by stevejgordon** [comment]
I'd expect JSON performance to be equivalent regardless though. Are you able to use a tool such as Fiddler to capture a few requests and responses through each to compare if they differ in any way?

**Comment by stevejgordon** [comment]
@trongvodang - I've pushed up to the 5283 branch of the perf testing tool a couple of changes. I've made it run on .NET 5 so it'll require the .NET 5 SDK. I've also expanded on how to run dotnet counter to collect HTTP stats from the process. That should provide a good indication of any major differences in the TCP connections being opened.

**Comment by trongvodang** [comment]
I only delete this code in your branch `.Field("address")` because that field not index. and change ES URL of course
Here is my result: `{"slowCount":1112,"totalRequests":2579,"averageRequestTime":1699}`
this counter that I run after run `bombardier -c 100 -r 200 -n 2000 https://domain`
```[System.Net.Http]
    Current Http 1.1 Connections                                   0
    Current Http 2.0 Connections                                   0
    Current Requests                                             100
    HTTP 1.1 Requests Queue Duration (ms)                          0
    HTTP 2.0 Requests Queue Duration (ms)                          0
    Requests Failed                                                0
    Requests Failed Rate (Count / 1 sec)                           0
    Requests Started                                           3,689
    Requests Started Rate (Count / 1 sec)                          0
[System.Runtime]
    % Time in GC since last GC (%)                                 0
    Allocation Rate (B / 1 sec)                               32,624
    CPU Usage (%)                                                  0
    Exception Count (Count / 1 sec)                                0
    GC Fragmentation (%)                                           0.063
    GC Heap Size (MB)                                             91
    Gen 0 GC Count (Count / 1 sec)                                 0
    Gen 0 Size (B)                                                96
    Gen 1 GC Count (Count / 1 sec)                                 0
    Gen 1 Size (B)                                         3,185,160
    Gen 2 GC Count (Count / 1 sec)                                 0
    Gen 2 Size (B)                                         6,434,664
    IL Bytes Jitted (B)                                      593,657
    LOH Size (B)                                          17,980,000
    Monitor Lock Contention Count (Count / 1 sec)                  0
    Number of Active Timers                                        2
    Number of Assemblies Loaded                                  124
    Number of Methods Jitted                                   7,390
    POH (Pinned Object Heap) Size (B)                        262,288
    ThreadPool Completed Work Item Count (Count / 1 sec)           0
    ThreadPool Queue Length                                        0
    ThreadPool Thread Count                                        3
    Working Set (MB)                                             292```

**Comment by trongvodang** [comment]
If it not help much, i will create index on cloud and test with you, can
you give me your email, i will email cloudid and pass

Vào Th 4, 3 thg 2, 2021 lúc 21:34 Steve Gordon <notifications@github.com>
đã viết:

**Comment by stevejgordon** [comment]
@trongvodang The numbers are a little confusing. I'm not sure why it's not showing any connections. I was hoping to confirm whether two many connection handshakes might be causing the delay. Do you have a support plan with us? We'd have to go through support to investigate your data. I'll see if there's more we can collect here but you may also need to review a Fiddler and/or Wireshark to see if there's anything in the request/response/TCP layers which help explain the delay. I'll also see if I can reproduce with a larger doc count using my own Cloud instance.

**Comment by trongvodang** [comment]
Sorry, i dont know much about this tool. Here is result when I running bombardier (the previous result is `after` run it)
```[System.Net.Http]
    Current Http 1.1 Connections                                  50
    Current Http 2.0 Connections                                   0
    Current Requests                                             198
    HTTP 1.1 Requests Queue Duration (ms)                        346.061
    HTTP 2.0 Requests Queue Duration (ms)                          0
    Requests Failed                                                0
    Requests Failed Rate (Count / 1 sec)                           0
    Requests Started                                           7,536
    Requests Started Rate (Count / 1 sec)                         58
[System.Runtime]
    % Time in GC since last GC (%)                                 0
    Allocation Rate (B / 1 sec)                            4,649,240
    CPU Usage (%)                                                  3
    Exception Count (Count / 1 sec)                              274
    GC Fragmentation (%)                                          19.277
    GC Heap Size (MB)                                            161
    Gen 0 GC Count (Count / 1 sec)                                 0
    Gen 0 Size (B)                                         2,663,464
    Gen 1 GC Count (Count / 1 sec)                                 0
    Gen 1 Size (B)                                         5,825,072
    Gen 2 GC Count (Count / 1 sec)                                 0
    Gen 2 Size (B)                                         6,434,664
    IL Bytes Jitted (B)                                      610,757
    LOH Size (B)                                          17,980,000
    Monitor Lock Contention Count (Count / 1 sec)                  2
    Number of Active Timers                                      100
    Number of Assemblies Loaded                                  124
    Number of Methods Jitted                                   7,521
    POH (Pinned Object Heap) Size (B)                        262,288
    ThreadPool Completed Work Item Count (Count / 1 sec)         849
    ThreadPool Queue Length                                        0
    ThreadPool Thread Count                                        4
    Working Set (MB)                                             282

**Comment by stevejgordon** [comment]
@trongvodang Those counters look as I'd expect, no unusually high volume of connections. Thanks for running that. Please kill that cloud instance as I wouldn't want those credentials to be misused. As part of our ongoing work for the next major release we will be focusing on performance and doing lots of profiling.
