### ISSUE TITLE
Please return application privileges in client.Security.GetRole()

### ISSUE THREAD

**Issue by wolframhaussig** [elastic/elasticsearch-net#5401]
**Is your feature request related to a problem? Please describe.**
I am implementing a tool to make managing our users, roles and role mappings easier(like adding change dates, desciptions and so on as metadata) and I am using the NEST library for that. While the PutRoleRequest supports adding Application privileges the GetRoleResponse does not return them.

**Describe the solution you'd like**
I would like to have NEST return the application privileges(e.g. Kibana Spaces).

**Describe alternatives you've considered**
Of course I could the Lowlevel client to read the roles but this could mean that I have to update my logic for each ElasticSearch API change.

**Additional context**
NEST version: 7.11.1

**Comment by stevejgordon** [comment]
Thanks for reporting this gap @wolframhaussig. I should be able to get this into the next release.

**Comment by stevejgordon** [comment]
PR is merged for 7.12.0 release.
