### ISSUE TITLE
Ids query with Guids produces null values in the query

### ISSUE THREAD

**Issue by mendoncaftw** [elastic/elasticsearch-net#5430]
**NEST/Elasticsearch.Net version**: 7.10.0

**Elasticsearch version**: 7.10.2 on Elastic Cloud

**Description of the problem including expected versus actual behavior**:
Ids query with Guids is producing null values in the query.

**Steps to reproduce**:
```
public async Task<IEnumerable<ElasticObject>> SearchAsync(IEnumerable<Guid> ids)
{
    var idsQuery = new QueryContainerDescriptor<ElasticObject>();

    if (ids != null && ids.Any())
    {
        idsQuery.Ids(c => c.Values(new List<Id> { new Id(Guid.NewGuid().ToString()), new Id(Guid.NewGuid()) }));
    }

    var result = await _client.SearchAsync<ElasticObject>(s =>
        s.Query(q => idsQuery));

    return result.Documents;
}
```

This code throws the following exception:
Elasticsearch.Net.ElasticsearchClientException: 'Request failed to execute. Call: Status code 400 from: POST /redacted/_search?typed_keys=true. ServerError: Type: parsing_exception Reason: "[1:67] [ids] failed to parse field [values]" CausedBy: "Type: x_content_parse_exception Reason: "[1:67] [ids] failed to parse field [values]" CausedBy: "Type: illegal_state_exception Reason: "Can't get text on a VALUE_NULL at 1:67

With the debug information showing the request and response:
\# Request:
{"query":{"ids":{"values":["819d143f-0eee-4de4-9f07-fcd1dee3fe76",null]}}}
\# Response:
{"error":{"root_cause":[{"type":"parsing_exception","reason":"[1:67] [ids] failed to parse field [values]","line":1,"col":67}],"type":"parsing_exception","reason":"[1:67] [ids] failed to parse field [values]","line":1,"col":67,"caused_by":{"type":"x_content_parse_exception","reason":"[1:67] [ids] failed to parse field [values]","caused_by":{"type":"illegal_state_exception","reason":"Can't get text on a VALUE_NULL at 1:67"}}},"status":400}

**Expected behavior**

It should produce a values array with two Guids. I passed an Id Guid and another as Guid.ToString() just to show what happens. If it was just 1 Guid it produces values: [null]

[Ids inference](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/ids-inference.html) points out that Guid is supported.

**Comment by stevejgordon** [comment]
Hi @mendoncaftw. Thanks for raising this issue. The `Id` ctor doesn't include an overload that accepts a `Guid` so it's matching the `object`-based overload which expects to be able to infer the Id from the `object` which is expected to contain an `Id` property. `Id` supports an implicit conversion from `Guid` though, so in your example, you should be able to use:

```c#
idsQuery.Ids(c => c.Values(new List<Id> { Guid.NewGuid().ToString(), Guid.NewGuid() }));
```

This implicitly converts from `string` or `Guid`.

I agree this is slightly unclear in the documentation so I will look at improving that. It feels like we should be able to support a constructor which accepts a `Guid` to round-off the `Id` type.

**Comment by mendoncaftw** [comment]
Hi @stevejgordon thanks for the quick reply. 

I checked that indeed it's the object overload being called for the Guid. The nest [documentation](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/ids-inference.html) mentioned that an Id could be infered from a Guid so I thought it would work.

Thanks for the help!
