### ISSUE TITLE
Support for Stempel Analysis plugin

### ISSUE THREAD

**Issue by osikstrom** [elastic/elasticsearch-net#5439]
**Is your feature request related to a problem? Please describe.**
I am trying to use the "Stempel Analysis plugin" in elastic search through NEST/Elasticsearch.Net.
https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-stempel.html
But having issues regarding index creation.

Here is a snippet from the "DebugInformation" when running (_client.Indices.CreateAsync):
```
Invalid NEST response built from a unsuccessful (400) low level call on PUT: /test-index_polish_v1
# Audit trail of this API call:
 - [1] BadResponse: Node: http://localhost:****/ Took: 00:00:00.3797671
# OriginalException: Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: PUT /test-index_polish_v1. ServerError: Type: illegal_argument_exception Reason: "Invalid stemmer class specified: Polish" CausedBy: "Type: class_not_found_exception Reason: "org.tartarus.snowball.ext.PolishStemmer""
```

Indeed PolishStemmer is missing from org.tartarus.snowball.ext, is there anyway around this or will there be any support for this?

**Describe alternatives you've considered**
Here is a snippet from the index definition:
```
  "settings": {
    "analysis": {
      "analyzer": {
        "standard": {
          "filter": [
            "lowercase",
            "ascii_folding_filter"
          ],
          "tokenizer": "standard",
          "type": "custom"
        },
        ...
      "filter": {
        "language_stop_filter": {
          "stopwords": [
            "_polish_"
          ],
          "type": "stop"
        },
        "language_stemmer_filter": {
          "language": "polish",
          "type": "stemmer"
        },
```
  
I have also tried to create an index with english as a stemmer to bypass issues regarding polish stemmer (as in this example:  https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-polish-stop.html)
```
  "settings": {
    "analysis": {
      "analyzer": {
        "analyzer_with_stop": {
          "filter": [
            "lowercase",
            "polish_stop"
          ],
          "tokenizer": "standard",
          "type": "custom"
        },
        ...
        "filter": {
          "polish_stop": {
            "stopwords": [
              "_polish_"
            ],
            "type": "stop"
          },
          "language_stemmer_filter": {
            "language": "english",
            "type": "stemmer"
          },
```

In this case the index can then be created but no success in the query.

Example of text:
_Kauderwelsch Trener wymowy Niemiecki - słowo w słowo_

Search word: _słowo_

**Describe the solution you'd like**
Support for Stempel Analysis plugin.

**Comment by stevejgordon** [comment]
Hi @osikstrom. Having reviewed this, I don't think this is a .NET client issue, but an error in the usage. I'm not an expert in this area, but the [docs do not list Polish](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-stemmer-tokenfilter.html#analysis-stemmer-tokenfilter-language-parm) for the Language Stemmer Filter. The docs for the plug-in state:

> The plugin provides the polish analyzer and the polish_stem and polish_stop token filters, which are not configurable.

There is an example of [using the stop filter in the documentation](https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-polish-stop.html) also.

I'd suggest you begin by proving your use-case using Dev Tools in Kibana or CURL commands to create a valid index configuration. You can then review applying that configuration using NEST. If you continue to have exceptions, your question may be best placed for the [discussion forum](https://discuss.elastic.co/c/elastic-stack/elasticsearch).

If you feel this is actually an issue specifically when using NEST (i.e. does not occur when you send the same configuration via Kibana), can you please provide C# code I can use to reproduce the full issue?

**Comment by osikstrom** [comment]
Hi @stevejgordon! Thank you so much for taking the time to answer this.

I've been reading in the discussion forum <https://discuss.elastic.co/> and been using the Dev Tools through Kibana combined with elasticsearch.net. It is indeed just as you are describing. Not an issue in elasticsearch.net. It was surely a usage error.

I will describe some information regarding this to allow other with similar issues find this and maybe get some knowledge regarding this.
I will also close this issue.

Polish is not used as a language, but it is however possible to use an analyser which you get when installing the plugin as described.

You can then use the plugin to analyze on field level.

Here is an example of usage with mappings (no analyzer must be customized in settings section, just the plugin installed):
```
{
  "mappings": {
    "properties": {
      "title": {
        "fields": {
          "polish": {
            "type": "text",
            "analyzer": "polish" <= Polish plugin specific
          }
        },
        "type": "text"
      }
    }
  }
}
```

A few steps to for testing through Kibana:
_1. Add index with polish analyzer for field:_
```
PUT /my_index
{
  "mappings": {
    "properties": {
      "title": {
        "fields": {
          "polish": {
            "type": "text",
            "analyzer": "polish"
          }
        },
        "type": "text"
      }
    }
  }
}
```
In case you get: "Failed to parse mapping [_doc]: analyzer [polish] has not been configured in mappings" ensure that the plugin is installed correctly.

_2. Add a document:_
```
POST my_index/_doc/1
{
  "title": "Bardzo kocham zółwie"
}
```
_3. Ensure that the document exists:_
```
GET my_index/_doc/1
```
_4. Try the search with query: zółwie_
```
GET my_index/_search
{
  "query": {
    "multi_match": {
      "type":     "most_fields",
      "query":    "zółwie",
      "fields": [ "title", "title.polish" ]
    }
  }
}
```
