### ISSUE TITLE
Make sure integrate `latest-7` works on `7.11`

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#5484]
It's unlikely we do another 7.11 release but its one of the active integration branches.

Currently the `integrate latest 7` is broken (9 test failures)

https://github.com/elastic/elasticsearch-net/runs/2201937450

It would be good to turn this green so we are notified if `make assemble` turns red.

**Comment by stevejgordon** [comment]
Resolved in #5504
