### ISSUE TITLE
Not_analyzed has no effect

### ISSUE THREAD

**Issue by TowardsDeath** [elastic/elasticsearch-net#55]
I'm trying to tell ElasticSearch to stop analyzing a certain property, to prevent values with a dash from being split. I tried the options I could find, but none of them work. Have I stumbled upon a bug in NEST or am I doing something wrong? Let me tell you what I've tried so far.
### Mapping with ElasticProperty

The NEST docs tell me I can use the ElasticProperty attribute with a FieldIndexOption.

``` C#
[ElasticType( Name = "product" )]
public class ElasticSearchProduct
{
    [ElasticProperty( OmitNorms = true, Index = FieldIndexOption.not_analyzed )]
    public string Format { get; set; }
}
```

When the `Index` method has been called, I can see the product has been correctly indexed and the mapping is created in ElasticSearch. However, when I perform a faceted search, the value is still split. (The facet value "E-book" becomes two: "E" and "Book".)
### Manually call the mapper method

I found issue #19 that told me to persist the mapping, so I did:

``` C#
this.ElasticSearch.Map<ElasticSearchProduct>( "products" );
```

It creates a mapping, but the value is still split.
### Explicit type mapping

Then I tried to perform an explicit type mapping, as mentioned in issue #19.

``` C#
var notAnalyzedProperty = new TypeMappingProperty
{
    Type = "string",
    Index = "not_analyzed"
};
var newMapping = new TypeMapping( "product" );
newMapping.Properties.Add( "format", notAnalyzedProperty );
this.ElasticSearch.Map( newMapping, index );
```

That doesn't prevent the value from being split either.
### I'm running this with:
- the latest NEST package from NuGet: 0.9.1.0
- the latest ElasticSearch 0.19.7, with default configuration.
- search queries that use an index alias and a routing value, a construct that I've found on the [ElasticSearch Google group](https://groups.google.com/forum/?fromgroups#!searchin/elasticsearch/data$20flow/elasticsearch/49q-_AgQCp8/MRol0t9asEcJ). That should have nothing to do with this issue, but perhaps it's good to know to determine the cause.

If you need me further to debug this or provide any more information, just let me know.

**Comment by emwalker** [comment]
I've run into this problem as well.

**Comment by rajatg64** [comment]
same problem here. anyone got the solution?

**Comment by russcam** [comment]
@rajatg64 it'd be best to open a new issue and describe what the problem you're seeing is.
