### ISSUE TITLE
this words is not work: ISort sort = new ScriptSort() { Order = Nest.SortOrder.Ascending, Script = new InlineScript("doc['name'].value.length()"),Type= "number" };  

### ISSUE THREAD

**Issue by wjhmiss** [elastic/elasticsearch-net#5528]
![image](https://user-images.githubusercontent.com/6950490/113708668-1a38c400-9714-11eb-9cc7-8c4b82fb5b58.png)
![image](https://user-images.githubusercontent.com/6950490/113708681-1efd7800-9714-11eb-8e2a-6ad1ca3e40a4.png)

please help me,

**Comment by stevejgordon** [comment]
@wjhmiss This is the repo for the .NET Client. Your question seems specific to querying Elasticsearch? This is best raised as a question in the [discussion forums for Elasticsearch](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6).
