### ISSUE TITLE
NullReferenceException when disposing of ConnectionSettings - backport fix to 6.x

### ISSUE THREAD

**Issue by bdchris** [elastic/elasticsearch-net#5529]
**NEST/Elasticsearch.Net version**:  6.8.7

**Elasticsearch version**:  6.8.10

**Description of the problem including expected versus actual behavior**:
Requesting backport of fix from 7.x for this issue.
Same issue as reported in https://github.com/elastic/elasticsearch-net/issues/4818

Fix is simple (add nullability check on the `_cleanupTimer?.Dispose()` below.

```
src\Elasticsearch.Net\Connection\HandlerTracking\RequestDataHttpClientFactory.cs
		protected virtual void StopCleanupTimer()
		{
			lock (_cleanupTimerLock)
			{
				_cleanupTimer.Dispose();
				_cleanupTimer = null;
			}
		}
```

**Steps to reproduce**:
See https://github.com/elastic/elasticsearch-net/issues/4818

**Expected behavior**

**Provide `ConnectionSettings` (if relevant)**: N/A

**Provide `DebugInformation` (if relevant)**:  N/A

**Comment by stevejgordon** [comment]
Thanks for raising this and providing the PR to fix it @bdchris. I've merged that in and it'll appear in the next patch release.
