### ISSUE TITLE
RuntimeField's Script is an IStoredScript. How do I pass it a param?

### ISSUE THREAD

**Issue by dharmaturtle** [elastic/elasticsearch-net#5537]
Given the following doc:

```json
POST my-index/_doc
{
  "@timestamp": "2017-02-03T19:27:20.606Z"
}
```

This script successfully runs. Note that it takes a `params`:

```json
GET my-index/_search
{
  "fields": [
    "day_of_week"
  ],
  "runtime_mappings": {
    "day_of_week": {
      "type": "keyword",
      "script": {
        "source": "emit(doc['@timestamp'].value.dayOfWeekEnum.getDisplayName(TextStyle.FULL, Locale.ROOT) + params.foo )",
        "params": {
          "foo": " is a good day."
        }
      }
    }
  }
}
```

In attempting to convert the above to NEST v7.12.0, I noticed that [`RuntimeField`'s `Script` property is of type `IStoredScript`](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Mapping/RuntimeFields/RuntimeField.cs#L39). I believe this is incorrect, as [`IStoredScript` does not accept any `params`](https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Modules/Scripting/IStoredScript.cs).

If instead I am incorrect, please let me know how to fix the following `SearchRequest` so that it can take a `params`:

```csharp
var sr = new SearchRequest() {
  RuntimeFields = new RuntimeFields
  (
    new Dictionary<Field, IRuntimeField>
    {{
      new Field("RevisionId"),
      new RuntimeField() {
        Format = "keyword",
        Script = new PainlessScript("this doesn't take a params"),
        Type = FieldType.Long
      }
    }}
  ),
  Query = new IdsQuery {
    Values = new List<Id> { exampleId },
  }
};
```

Thanks!

**Comment by stevejgordon** [comment]
Hi @dharmaturtle. Apologies for the delayed response. I was out on some vacation time. Thanks for reporting this. Indeed I can see the issue with the current design. IIRC, params may not have been supported early on, but they certainly are now. This is certainly something we should address and while we generally avoid breaking changes in minor releases, I think it's something we can review for inclusion 7.13.0. I'll assess this and look to make changes to fully support params.

**Comment by stevejgordon** [comment]
The change is now merged and although breaking, we've agreed the impact is small enough that we'll ship this as part of 7.13.0.

**Comment by stevejgordon** [comment]
@dharmaturtle 7.13.0 just shipped and includes this change.
