### ISSUE TITLE
Ping Failure Error when HTTPS is enabled

### ISSUE THREAD

**Issue by ahmetf** [elastic/elasticsearch-net#5553]
**NEST/Elasticsearch.Net version**: 7.5.1

**Elasticsearch version**: 7.5.1

**Description of the problem including expected versus actual behavior**:
xpack Security is enabled,  http ssl is enabled and ssl certifiace is created on the server which is non-prod environment. If you use SniffingConnectionPool and DisablePing() is active, it's working. But if DisablePing() is not active (Ping is active also) the application receives "The operation has timed out" exception. Upper exception is "Failed to ping the specified node.. Call: Status code unknown from: HEAD /"
If http ssl is disabled, whether DisablePing() is active or not, it's working.

**Steps to reproduce**:
 1. Use below elasticsearch.yml and connection pool settings:
elasticsearch.yml:

     bootstrap.memory_lock: false
     cluster.name: elasticsearch751-demo
     http.port: 9200
     network.host: 0
     node.data: true
     node.ingest: true
     node.master: true
     node.max_local_storage_nodes: 1
     node.name: DEMO1
     path.data: E:\Elasticsearch\data
     path.logs: E:\Elasticsearch\logs
     transport.tcp.port: 9300
     xpack.license.self_generated.type: basic
     xpack.security.enabled: true
     xpack.security.http.ssl.enabled: true
     xpack.security.http.ssl.keystore.path: elastic-certificates.p12
     xpack.security.http.ssl.verification_mode: none
     xpack.security.transport.ssl.enabled: true
     xpack.security.transport.ssl.verification_mode: certificate
     xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
     xpack.security.transport.ssl.truststore.path: elastic-certificates.p12
     discovery.seed_hosts: []
     discovery.type: single-node

NEST Connection configuration:
`            SniffingConnectionPool connectionPool = null;

            var uri = new UriBuilder(IpAddress) { Port = Port };
            var uri2 = new UriBuilder(IpAddress2) { Port = Port2 };
            var uri3 = new UriBuilder(IpAddress3) { Port = Port3 };
            var uri4 = new UriBuilder(IpAddress4) { Port = Port4 };
            var uri5 = new UriBuilder(IpAddress5) { Port = Port5 };

            var uri6 = new UriBuilder(IpAddress6) { Port = Port6 };
            var uri7 = new UriBuilder(IpAddress7) { Port = Port7 };
            var uri8 = new UriBuilder(IpAddress8) { Port = Port8 };
            var uri9 = new UriBuilder(IpAddress9) { Port = Port9 };
            var uri10 = new UriBuilder(IpAddress10) { Port = Port10 };

            connectionPool = new SniffingConnectionPool(new[] { uri.Uri, uri2.Uri, uri3.Uri, uri4.Uri, uri5.Uri, uri6.Uri, uri7.Uri, uri8.Uri, uri9.Uri, uri10.Uri });

            var settings = new ConnectionSettings(connectionPool);

            settings
                .UserAgent("Mozilla/5.0 (Windows NT 10.0; …) Gecko/20100101 Firefox/71.0")
                .DefaultIndex(IndexName)
                .SniffOnConnectionFault(false)
                .RequestTimeout(TimeSpan.FromSeconds(ElasticSearchTimeout))
                .DeadTimeout(TimeSpan.FromSeconds(ElasticSearchDeadTimeout))
                .MaximumRetries(ElasticSearchTryCount)
                .SniffOnStartup(false)
                .DisableDirectStreaming()
                .SniffLifeSpan(TimeSpan.FromMinutes(1));

            if (!string.IsNullOrEmpty(Username) && !string.IsNullOrEmpty(Password))
            {
                settings.BasicAuthentication(Username, Password);
            }

            settings.ServerCertificateValidationCallback((sender, cert, chain, errors) => true);

            Client = new ElasticClient(settings);`

 
**Expected behavior**
When https is enabled and Ping is active (No DisablePing() config in ConnectionSettings), it should be working. 

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

        "DebugInformation": "Unsuccessful () low level call on POST: /ESINDEX/_delete_by_query\r\n# Audit trail of this API call:\r\n - [1] PingFailure: Node: https://x.x.x.x:9200/ Exception: PipelineException Took: 00:00:15.1863616\r\n# OriginalException: Elasticsearch.Net.ElasticsearchClientException: Failed to ping the specified node.. Call: Status code unknown from: HEAD / ---> Elasticsearch.Net.PipelineException: Failed to ping the specified node. ---> Elasticsearch.Net.PipelineException: An error occurred trying to read the response from the specified node. ---> System.Net.WebException: The operation has timed out\r\n   at System.Net.HttpWebRequest.GetResponse()\r\n   at Elasticsearch.Net.HttpWebRequestConnection.Request[TResponse](RequestData requestData)\r\n   --- End of inner exception stack trace ---\r\n   at Elasticsearch.Net.RequestPipeline.Ping(Node node)\r\n   --- End of inner exception stack trace ---\r\n   at Elasticsearch.Net.RequestPipeline.Ping(Node node)\r\n   at Elasticsearch.Net.Transport`1.Ping(IRequestPipeline pipeline, Node node)\r\n   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)\r\n   --- End of inner exception stack trace ---\r\n# Audit exception in step 1 PingFailure:\r\nElasticsearch.Net.PipelineException: An error occurred trying to read the response from the specified node. ---> System.Net.WebException: The operation has timed out\r\n   at System.Net.HttpWebRequest.GetResponse()\r\n   at Elasticsearch.Net.HttpWebRequestConnection.Request[TResponse](RequestData requestData)\r\n   --- End of inner exception stack trace ---\r\n   at Elasticsearch.Net.RequestPipeline.Ping(Node node)\r\n# Request:\r\n<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>\r\n# Response:\r\n\r\n",

**Comment by stevejgordon** [comment]
Hi, @ahmetf. Thanks for reporting this issue. As a starting point, can you please try updating to the latest client 7.12.1 which is backwards-compatible with server 7.5.1 as let me know if you still experience this error?

**Comment by stevejgordon** [comment]
@ahmetf One further thought on reviewing the debug info. How are you hosting/running your Elasticsearch instances? I don't think this is likely as you're able to get this working in some configuration, but are you using Docker? The reason I ask is that this will present issues with pinging and sniffing. 

I'm also curious why your cluster config includes: `discovery.type: single-node`

**Comment by ahmetf** [comment]
Hi @stevejgordon, 

After updating client to 7.12.1, there is no error. We are going to update client version. Thanks for you help.
