### ISSUE TITLE
Xamarin.Forms Android Release Build FileNotFoundException

### ISSUE THREAD

**Issue by Chtau** [elastic/elasticsearch-net#5575]
**NEST/Elasticsearch.Net version**:7.12.1

**Elasticsearch version**:7.12.0

**Description of the problem including expected versus actual behavior**:
ElasticClient/ElasticLowLevelClient throws an error when used in Xamarin.Forms (Android) with the `Release` option. The same Project works just fine with `Debug`. 

Inner exception:
System.TypeInitializationException: The type initializer for 'Elasticsearch.Net.MetaDataHeader' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Elasticsearch.Net.RuntimeVersionInfo' threw an exception. ---> System.IO.FileNotFoundException: mscorlib.dll
  at System.Diagnostics.FileVersionInfo.GetVersionInfo (System.String fileName) [0x0000d] in <e3680798dcba445e9260ec362d9456ad>:0 
  at Elasticsearch.Net.RuntimeVersionInfo.GetNetCoreVersion () [0x0004d] in <a90124c0ee2045c9887a8344acf445ee>:0 

**Steps to reproduce**:
 1. Create a new Xamarin.Forms Project
     It can be reproduced with older Xamarin.Forms Version and also with the newest Nuget 5.0.0.2012
 2. Add NEST or Elasticsearch.Net
 3. Create Client
     `var settings = new ConnectionSettings(new Uri("http://127.0.0.1:9201"));`
     `settings.ApiKeyAuthentication("xxxxxxxxxxxxxxx", "xxxxxxxxxxxxxxxxxx");`
     `settings.DefaultIndex("monitor-default");`
     `var client = new ElasticLowLevelClient(settings);`
     `var result = client.Index<StringResponse>($"monitor-{DateTime.UtcNow:yyyy.MM.dd}", "test");`

**Expected behavior**
Should work in Release as it works in Debug

**Comment by stevejgordon** [comment]
Thanks for reporting this @Chtau. I'll take a look at our exception handling around the runtime detection.

**Comment by stevejgordon** [comment]
I'll add some more exception handling around that code path. The code where you've observed the exception is part of a feature added in 7.11.0 which detects the client and runtime version through reflection. Unless you need the newest features, you could use 7.10.1 or earlier, before that change was introduced until we get a release out that better handles the Xamarin case.

**Comment by stevejgordon** [comment]
@Chtau The extra exception handling will go out in the next release. While I couldn't get it to reproduce, the code path from the call stack gets the location of the assembly containing the object type (mscorlib.dll) and attempts to access the `GetVersionInfo`. Were you able to get this working by using the previous version of the client?

**Comment by Chtau** [comment]
@stevejgordon I tried 7.10.x Versions but they are incompatible with the rest of our tool chain. So i have to wait for the next release to confirm the fix.
