### ISSUE TITLE
Does not support Chinese search by default?

### ISSUE THREAD

**Issue by zhuyangping** [elastic/elasticsearch-net#5653]
Does not support Chinese search by default? What configuration is required?（ nest 7.12.0）
![image](https://user-images.githubusercontent.com/38641795/116498089-82299700-a8db-11eb-9d85-ab46e767c53e.png)

**Comment by stevejgordon** [comment]
Hi @zhuyangping. There should be no extra configuration needed to use Chinese characters in searches via NEST. Can you please provide some more context about your issue? What are you expecting to happen and what is the actual result? 

If you believe the request is wrong, can you please enable [debug mode](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/debug-mode.html) so you can capture the debug information which would also be helpful?

I created a basic repro which seems to function as expected:

```c#
var result = c.SearchAsync<TestData>(x => x.Index("test")
	.Query(q => q.ConstantScore(c =>
		c.Filter(qq => qq
			.Term(t => t.Name, "史蒂夫")))));
```

And the request body was:

```
{"query":{"constant_score":{"filter":{"term":{"name":{"value":"史蒂夫"}}}}}}
```

**Comment by zhuyangping** [comment]
OK
