### ISSUE TITLE
Basic Authentication not working

### ISSUE THREAD

**Issue by denisecastagna** [elastic/elasticsearch-net#5687]
Hello everybody, I'm trying to implement a connection to Elastic (7) on AWS but I don't understand how to do it using basic authentication credential instead of IAM. 

This is my code, but when I try to do a search I have got the error "Elasticsearch.Net.UnexpectedElasticsearchClientException: Unable to retrieve credentials required to sign the request. ---> System.Exception: Unable to retrieve credentials required to sign the request. ---> Amazon.Runtime.AmazonServiceException: Unable to get IAM security credentials from EC2 Instance Metadata Service." 

`
var httpConnection = new AwsHttpConnection(Amazon.RegionEndpoint.EUWest3.ToString());
var pool = new SingleNodeConnectionPool(host);
settings = new ConnectionSettings(pool, httpConnection).BasicAuthentication(_user, _password).ServerCertificateValidationCallback(
							delegate (
								object sender,
								System.Security.Cryptography.X509Certificates.X509Certificate certificate,
								System.Security.Cryptography.X509Certificates.X509Chain chain,
								System.Net.Security.SslPolicyErrors sslPolicyErrors
							)
							{
								return true; // Always accept
							});
`

NEST v. 7.12.1
Elasticsearch.Net.Aws 7.1.0
ElasticSearch v. 7

Can anyone help me?

**Comment by stevejgordon** [comment]
Hi @denisecastagna. I'm going to close this as it doesn't look like it relates to a supported feature of this library. Please let me know if you have further information and we can review re-opening.
