### ISSUE TITLE
Can IElasticClient use Singleton Mode?

### ISSUE THREAD

**Issue by zhuyangping** [elastic/elasticsearch-net#5690]
Singleton mode can be used to query, but cannot be used to create.

Query Index Code:

public async Task<IReadOnlyCollection<GeneratorPriceVO>> GetGeneratorPriceList(DateTime startDate, DateTime endDate, string scenario)
  {
      var query = await Client.SearchAsync<GeneratorPriceVO>(x => x.Index(IndexNameGeneratorPrice)
          .Query(q => q
          .ConstantScore(c => c
          .Filter(qq => qq //Elasticsearch会自动缓存经常使用的Filter查询
          .DateRange(r => r.Field(t => t.Date).GreaterThanOrEquals(DateMath.FromString(startDate.ToString("yyyy-MM-dd")))) && qq
          .DateRange(r => r.Field(t => t.Date).LessThan(DateMath.FromString(endDate.AddDays(1).ToString("yyyy-MM-dd")))) && qq
          .Term(t => t.Scenario.Suffix("keyword"), scenario))))
          .Size(ElasticsearchConfigOptions.MaxSize)
      );
      return query.Documents;
  }
    
Create Index Code:

public async Task CreateClearRecord(ClearRecordDTO clearRecordDTO)
{
    await Client.IndexAsync(clearRecordDTO, x => x.Index(IndexNameClearRecord));
}

Singleton Mode Code:

public class ElasticsearchProvider : IElasticsearchProvider
    {
        protected static IElasticClient instance;

        protected static object locker = new object();

        protected static Uri[] Uris;

        public static IElasticClient Singleton
        {
            get
            {
                if (instance == null)
                {
                    lock (locker)
                    {
                        if (instance == null) //防止线程重入
                        {
                            if (Uris.Length == 1)
                            {
                                ConnectionSettings connectionSettings = new ConnectionSettings(Uris[0]);
                                instance = new ElasticClient(connectionSettings);
                            }
                            else
                            {
                                StaticConnectionPool pool = new StaticConnectionPool(Uris);
                                ConnectionSettings settings = new ConnectionSettings(pool);
                                instance = new ElasticClient(settings);
                            }
                        }
                    }
                }
                return instance;
            }
        }

        /// <summary>
        /// 获取客户端
        /// </summary>
        /// <param name="uris"></param>
        /// <returns></returns>
        public IElasticClient GetClient(Uri[] uris)
        {
            Uris = uris;
            return Singleton;
        }
    }

**Comment by stevejgordon** [comment]
Hi @zhuyangping. Indeed, the client is intended to be used as a single instance per application, managed however it best suits your situation. For example, it can be registered in a DI container as a singleton instance. Locking around a singleton instance is another valid approach if you need to provide the Uris at runtime, otherwise, a static readonly field could be another way to go.

Using a single instance ensures that we maintain the underlying HttpClient instances and connections, reusing them where possible to reduce lots of short-lived connections.

When you stated:
> Singleton mode can be used to query, but cannot be used to create.

Can you please expand on this? Are you experiencing issues? There is no difference between indexing or searching via a singleton client.

**Comment by zhuyangping** [comment]
Yes, it works well.

**Comment by zhuyangping** [comment]
Yes, it works well.
