### ISSUE TITLE
Elasticsearch has enabled x-pack security, how to assign minimum permissions

### ISSUE THREAD

**Issue by hyt05** [elastic/elasticsearch-net#5692]
NEST version:  7.10.0
elasticsearch version：7.5.1

My elasticsearch has enabled x-pack authentication, how to use the minimum permission configuration，

This is my permission configuration
![image](https://user-images.githubusercontent.com/48778924/118422114-2d688780-b6f5-11eb-8c45-902f1cccc3ed.png)

**Comment by stevejgordon** [comment]
Hi @hyt05,

It looks like you've configured a role with your required permissions. You can assign a user to that role and when you configure the NEST client, provide the basic authentication credentials you wish to connect with.

```c#
var client =
    new ElasticClient(
        new ConnectionSettings(new Uri("http://localhost:9200"))
            .BasicAuthentication("username", "password"));
```

It's also possible to configure ApiKey authentication in a similar way.

Does that answer your question?

**Comment by hyt05** [comment]
> 嗨@ hyt05，
> 
> 您似乎已使用所需的权限配置了角色。您可以将用户分配给该角色，并且在配置NEST客户端时，提供您希望与之连接的基本身份验证凭据。
> 
> ```cs
> var  client  = 
>     new  ElasticClient（
>         新的 ConnectionSettings（新的 Uri（“ http：// localhost：9200 ”）
>             。）BasicAuthentication（“ username ”，“ password ”））；
> ```
> 
> 也可以通过类似的方式配置ApiKey身份验证。
> 
> 这是否回答你的问题？

Thank you for your answer. My problem is that I don’t know how to grant users the minimum permissions or the recommended permissions. I found that only administrator permissions can write logs. The permissions shown in the figure cannot be written to logs successfully.

**Comment by stevejgordon** [comment]
@hyt05 You're question would be best asked on our [discussion forums](https://discuss.elastic.co/c/elastic-stack/elasticsearch/6). This repository is specific to the .NET client and not the best fit for general Elasticsearch configuration questions.

**Comment by hyt05** [comment]
@stevejgordon Ok thanks
