### ISSUE TITLE
Can't index json string into elastic search using Nest 7.13.0

### ISSUE THREAD

**Issue by LilanSilva** [elastic/elasticsearch-net#5721]
**NEST/Elasticsearch.Net version**: 7.13.0

**Elasticsearch version**: v7.13.1

**Description of the problem including expected versus actual behavior**:
I need to index dynamic json object into elastic search. I create the model with dynamic property
```
public class BookElasticSearch
{
    public string Id { get; set; }
    public string ApplicationId { get; set; }
    public dynamic Metadata { get; set; }
}
```

Then deserialize json string and create BookElasticSearch object with it. Then Serialize that object and get string and index that json string
```
var basonDoc = JsonConvert.DeserializeObject(@"{
   ""emp-name"":""Kasun kalhara"",
   ""emp-age"":30,
   ""emp-position"":""Associate Developer""
}");
var tt = new BookElasticSearch
{
    Id = Guid.NewGuid().ToString(),
    Metadata = basonDoc
};
var pp = JsonConvert.SerializeObject(tt);
var indexResponse = await elasticClient.IndexAsync(pp, document => document.Index("book-index"));
```

**Steps to reproduce**:
 1. get Json string  
```
{
   "Id":"39f9af93-f315-40e7-bb42-8eebbd08bacb",
   "ApplicationId": "application-34y7af93-f315-40e7-bb42-8eebbd08bvdr",
   "Metadata":{
      "emp-name":"Kasun kalhara",
      "emp-age":30,
      "emp-position":"Associate Developer"
   }
}
```
 2. Index json string using "IndexAsync" method
 await elasticClient.IndexAsync(pp, document => document.Index("book-index"));

**Expected behavior**
Json string should index in elastic search 

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**: 
# FailureReason: BadResponse while attempting POST on https://2c7809f98d7b4f78aca7ff6c819858dc.eastus.azure.elastic-cloud.com:9243/book-index/_doc
# Audit trail of this API call:
 - [1] BadResponse: Node: https://2c7809f98d7b4f78aca7ff6c819858dc.eastus.azure.elastic-cloud.com:9243/ Took: 00:00:01.7856567
# OriginalException: Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: POST /book-index/_doc. ServerError: Type: mapper_parsing_exception Reason: "failed to parse" CausedBy: "Type: not_x_content_exception Reason: "not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes""
# Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# Response:
<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# Exception:
Elasticsearch.Net.ElasticsearchClientException: Request failed to execute. Call: Status code 400 from: POST /book-index/_doc. ServerError: Type: mapper_parsing_exception Reason: "failed to parse" CausedBy: "Type: not_x_content_exception Reason: "not_x_content_exception: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes""

**Comment by LilanSilva** [comment]
This option also not working 
```
var tt = new List<string>(){
  JsonConvert.SerializeObject(new BookElasticSearch
  {
      Id = Guid.NewGuid().ToString(),
      ApplicationId = "dsfsdfsdfsfs",
      Metadata = basonDoc
  })
};

var test = await elasticClient.BulkAsync(b => b
            .Index("book-index")
            .IndexMany<string>(tt)
        );
```

**Comment by LilanSilva** [comment]
Thanks, Steve, I will try the first option. I already tried 2nd option and it not work. index item without JSON string value (only indexing  C# property values. lost dynamic property value)
I will try Json.NET serializer option as well.

**Comment by LilanSilva** [comment]
1st option also not working. it doesn't return any error but not index on the elastic search side. Do you have any working code sample?

**Comment by stevejgordon** [comment]
@LilanSilva If the request fails, you should see that on the response.

The following code works for me:

```c#
var client = new ElasticClient();

var basonDoc = JsonConvert.DeserializeObject(@"{
   ""emp-name"":""Kasun kalhara"",
   ""emp-age"":30,
   ""emp-position"":""Associate Developer""
}");

var tt = new BookElasticSearch
{
    Id = Guid.NewGuid().ToString(),
    Metadata = basonDoc
};

var pp = JsonConvert.SerializeObject(tt);
var response = client.LowLevel.Index<StringResponse>("your-index-name", PostData.String(pp));
```

The response `HttpStatusCode` should be 201 and the `AuditTrail` on the response should include a `HealthyResponse` event. Because this is the low-level client and we specified `StringResponse`, the `Body` of the response should be a string containing the JSON response from the server. 

If there are any failures, those locations should indicate what failed.

**Comment by LilanSilva** [comment]
Thanks for your support. it is working :) 

```
var pp = JsonConvert.SerializeObject(bookList);
var response = await elasticClient.LowLevel.BulkAsync<StringResponse>("book-index", PostData.String(pp));
```
I tried the bulk index option and it gives me an error (Have you any idea ? do I manualy constrcut json with a new line)
`{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The bulk request must be terminated by a newline [\\n]"}],"type":"illegal_argument_exception","reason":"The bulk request must be terminated by a newline [\\n]"},"status":400}`

**Comment by stevejgordon** [comment]
@LilanSilva - The Bulk API expects an NDJSON formatted body so you will need to ensure you send data in that format. The high-level client would handle this for you, but in the low-level, you will need to handle this yourself. Since you are using a string you could perhaps use a `TextWriter`. Be aware that formatting large bulk requests as strings may lead to large memory allocations.

**Comment by LilanSilva** [comment]
Thanks for suggestions
