### ISSUE TITLE
Mechanism to set file system snapshot repository in ReadOnly mode

### ISSUE THREAD

**Issue by AmitDilipDol** [elastic/elasticsearch-net#5753]
**NEST/Elasticsearch.Net version**: **7.x**
**Elasticsearch version**: **7.12**
**Description of the problem including expected versus actual behavior**:
Our application is using file system snapshot repository to take snapshot of index data. The location needs to be backup by third party backup solution. As Elasticsearch recommends to set repository in ReadOnly mode before backing up location. Our application is planning to set  that repository in ReadOnly mode; but there is no way to set snapshot repository in ReadOnly mode using NEST API. No 'ReadOnly' in 'FileSystemRepositorySettings' like there is in 'S3RepositorySettings'
Wanted to know way to set snapshot repository in backup mode before taking backup by third party solution

**Comment by stevejgordon** [comment]
Hi @AmitDilipDol. It looks like this option may be missing so I'll investigate adding this ASAP.

**Comment by stevejgordon** [comment]
A fix for this has been merged and will be available in the next release.

**Comment by AmitDilipDol** [comment]
Thanks @stevejgordon for quick fix. Any timelines on next release.
