### ISSUE TITLE
POST for CountAsync() instead of GET

### ISSUE THREAD

**Issue by ChristianHaase** [elastic/elasticsearch-net#5756]
**NEST/Elasticsearch.Net version**: v6.8.8

**Elasticsearch version**: v6.8

**Description of the problem including expected versus actual behavior**:
I'm trying to get the total count from ElasticSearch based on a query. The query should be sent in the request body of a GET request according to the [official documentation](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-count.html) from ElasticSearch, but is sent as a POST request from NEST/ElasticSearch.Net, hence the status code from ElasticSearch is a 403.

**Steps to reproduce**:
 1. Create a method to call `IElasticClient.CountAsync<T>()`
 2. Provide the count with a `.Query`
 3. Try to return `response.Count`

**Expected behavior**
I expect to retrieve the total count matching the query trough a GET request

**Provide `ConnectionSettings` (if relevant)**: Basic auth (username/password)

**Comment by stevejgordon** [comment]
Hi @ChristianHaase. The count API supports both GET and POST and we default to POST in such situations. The fact you are receiving a 403 here suggests a permissions issue. I would recommend checking that the credentials you are using have access to the index/indices specified in the URL.

You can also test this outside of the .NET Client using the same credentials where I would expect the same forbidden result to be returned.

**Comment by ChristianHaase** [comment]
Hi @stevejgordon. Ah yes, I see. I should've just read further down the documentation. My apologies. Thank you for the fast reponse!
