### ISSUE TITLE
NEST times out after a fixed number of Indices.ExistsAsync calls

### ISSUE THREAD

**Issue by dzendras** [elastic/elasticsearch-net#5775]
**NEST/Elasticsearch.Net version**: 7.13.1 (.NET 4.8)

**Elasticsearch version**: 7.13.2

**Description of the problem including expected versus actual behavior**:
Given the code below, the NEST client times out on DeleteIndexAsync command after the 79th loop:

```
Elasticsearch.Net.ElasticsearchClientException
  HResult=0x80131500
  Message=Maximum timeout reached while retrying request. Call: Status code unknown from: DELETE /some-index
  Source=Elasticsearch.Net
  StackTrace:
   at Elasticsearch.Net.Transport`1.HandleElasticsearchClientException(RequestData data, Exception clientException, IElasticsearchResponse response)
   at Elasticsearch.Net.Transport`1.FinalizeResponse[TResponse](RequestData requestData, IRequestPipeline pipeline, List`1 seenExceptions, TResponse response)
   at Elasticsearch.Net.Transport`1.<RequestAsync>d__15`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at TestNest.Program.<Main>d__1.MoveNext() in C:\Users\dzendras\Downloads\TestNestUpgradeTo7-master\Program.cs:line 40

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
WebException: The request was aborted: The request was canceled.
```

It's always 80th loop when the time out occurs (why?). When the exception is thrown, then Elasticsearch claims that the index is gone, which suggests that the server got the delete request, processed it successfully, yet the client timed out.
What's very interesting is that removing the call to ExistsAsync "fixes" the issue and the loop succeeds after 150 iterations.
Alternatively, you can remove Create and Delete calls and keep Exists only and it will time out at 81 iteration. It seems that ExistsAsync is somehow problematic, but I have no clue what I could be doing wrong.

**Steps to reproduce**:

```
var connectionSetting = new ConnectionSettings(new SingleNodeConnectionPool(new Uri("http://localhost:9200")));
connectionSetting.DisableDirectStreaming();
connectionSetting.ThrowExceptions();
var client = new ElasticClient(connectionSetting);
const string indexName = "some-index";
for (int i = 0; i < 150; i++)
{
    Console.WriteLine($"Iteration {i+1}");
    await client.Indices.CreateAsync(indexName);
    await client.Indices.ExistsAsync(indexName);
    try
    {
        await client.Indices.DeleteAsync(indexName);
    }
    catch (Exception e)
    {
        Console.WriteLine("Boo! " + e.Message);
    }
}
```

 1. Run the code above against a single-node dockerized localhost instance (https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html)
 2. You'll get Iteration 80, followed by "Boo!"
 3. Any subsequent iterations are going to fail on delete.
 4. Comment out ExistsAsync and re-run to see that 150 iterations succeeded.

**Expected behavior**
The loop succeeds with 150 iterations. The same scenario works with NEST 6.8.8.

**Comment by dzendras** [comment]
I would like to point out that it works in 7.12.1, breaks totally on 7.13 due to https://github.com/elastic/elasticsearch-net/issues/5730.

**Comment by stevejgordon** [comment]
Thanks for raising this @dzendras. I think I can see the issue with that last change that is causing this. I'm going to pick this up next week and validate my theory.

**Comment by stevejgordon** [comment]
Thanks again @dzendras for reporting this and apologies for the regression in the behaviour. I have fixed the offending code to ensure we properly release connections after completing a HEAD request such as `Indicies.ExistsAsync`. I have built release 7.13.2 which includes the fix.

**Comment by dzendras** [comment]
No worries! Thanks! I can confirm that 7.13.2 does not display the issue.
