### ISSUE TITLE
ISearchResponse.Total throws a null reference exception when TrackTotalHits is set to false

### ISSUE THREAD

**Issue by meywd** [elastic/elasticsearch-net#5892]
**NEST/Elasticsearch.Net version**:
7.12.1
**Elasticsearch version**:
7.6.1
**Description of the problem including expected versus actual behavior**:

Doing a query with TrackTotalHits set as false will return a hits object with no total property
```
 "hits" : {
    "max_score" : null,
    "hits" : [ ]
  },
```
the issue is that when trying to access `ISearchResponse.Total` we get a null reference exception from the getter, instead of simply returning null, which is caused by this code `public long Total => HitsMetadata?.Total.Value ?? -1;` in the Nest Client within `SearchResponse<TDocument>`

**Steps to reproduce**:
 1. Query with TrackTotalHits set to false
 2. Access ISearchResponse.Total
 3. Get exception

**Expected behavior**

Should get a null returned instead of an exception being thrown.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

Object reference not set to an instance of an object.
   at Nest.SearchResponse`1.get_Total()

**Comment by stevejgordon** [comment]
Thanks for raising this @meywd. I'll take a look at fixing this.

**Comment by stevejgordon** [comment]
@meywd I've fixed this issue which will go out in the next release. Thanks again for raising it.

**Comment by meywd** [comment]
Thank you
