### ISSUE TITLE
Update basic dependencies for version 5.x

### ISSUE THREAD

**Issue by wojteksbt** [elastic/elasticsearch-net#5925]
Hi, 

I know 5.x version is no longer maintained but there are the teams (including mine) which are forced to use it due to Elasticsearch version. Unfortunately in latest 5.6.6 version, there are dependency constraints defined which are more and more painful.

Therefore I'd like to kindly ask you if could you release a maintenance update with common libraries version updated? For my particular case the problem is Newtonsoft.Json < 13.0.0.

**Comment by stevejgordon** [comment]
Hi @wojteksbt. I appreciate the situation and I've been there myself with older libraries in the past. Unfortunately, ES5 and the corresponding client are no longer supported and this is not something we will address. The best option is to upgrade to ES6+ (ideally ES7) to return to a supported version.

**Comment by wojteksbt** [comment]
Ok, I understand. ES is our let's say external dependency but we'll try to force update. Thanks for your response @stevejgordon!
