### ISSUE TITLE
AggregationBase bitwise AND operator with two nulls results in invalid AggregationCombinator

### ISSUE THREAD

**Issue by Krusen** [elastic/elasticsearch-net#5929]
**NEST/Elasticsearch.Net version**: 7.13.2

**.NET runtime version**: .NET 5.0

**Description of the problem including expected versus actual behavior**:
Combining `null` values of `AggregationBase` using bitwise AND (`&&`) results in an "invalid" `AggregationCombinator` with an empty `Aggregations` list,  which then fails to cast/convert to both `AggregationContainer` and `AggregationDictionary`. 

The use case where this came up was when dynamically building a list of aggregations, starting out with `AggregationBase null` and then conditionally adding new aggregations which would be `null`/empty if not relevant in the current situation.

**Steps to reproduce**:

```csharp
AggregationBase agg1 = null;
AggregationBase agg2 = null;
AggregationBase agg3 = agg1 && agg2;
	
// Fails with ArgumentNullException: Value cannot be null. (Parameter 'key') 
// https://github.com/elastic/elasticsearch-net/blob/7.13.2/src/Nest/Aggregations/AggregationContainer.cs#L474
var aggContainer = (AggregationContainer) agg3; 

// Fails with ArgumentException: AggregationCombinator .Name is not set! 
// https://github.com/elastic/elasticsearch-net/blob/7.13.2/src/Nest/Aggregations/AggregationContainer.cs#L54
var aggDictionary = (AggregationDictionary) agg3; 
```

Combining two nulls results in the "invalid" `AggregationCombinator` which then cannot be fixed.

**Expected behavior**
I would expect that the casts to both `AggregationContainer` and `AggregationDictionary` would work and result in "empty" versions of those, which I suppose for `AggregationContainer` would be `null` and for `AggregationDictionary` would be an empty dictionary.

**Comment by stevejgordon** [comment]
Hi @Krusen. I'm having a hard time reproducing the exceptions you're seeing with the code above. In each case, the code executes for me without an exception.

When `AggregationCombinator` is constructed with left and right both being null (a result of the operator), they are skipped in the switch statement and the Aggregations property is an empty list. Therefore L474 in AggregationContainer.cs should not be executed. 

In both cases, they produce an empty `AggregationDictionary`.

**Comment by Krusen** [comment]
@stevejgordon Damnit, sorry. I was simplifying the reproduction example too much. It happens only when combining 3 or more aggregations, i.e. after the first `null && null` => `AggregationCombinator` and when that is then AND'ed with something else (doesn't have to be null).

```csharp
AggregationBase agg1 = null;
AggregationBase agg2 = null;
AggregationBase agg3 = null; // or any valid aggregation, e.g. new TermsAggregation("terms") { Field = "field" }
AggregationBase agg4 = agg1 && agg2 && agg3;

// Fails with ArgumentNullException: Value cannot be null. (Parameter 'key') 
// https://github.com/elastic/elasticsearch-net/blob/7.13.2/src/Nest/Aggregations/AggregationContainer.cs#L474
var aggContainer = (AggregationContainer)agg4;

// Fails with ArgumentException: AggregationCombinator .Name is not set! 
// https://github.com/elastic/elasticsearch-net/blob/7.13.2/src/Nest/Aggregations/AggregationContainer.cs#L54
var aggDictionary = (AggregationDictionary)agg4;
```

**Comment by stevejgordon** [comment]
No worries @Krusen. I can reproduce this now and see the cause. I'll need to investigate further to see if the fix is as simple as it first appears and safe for more common scenarios.
