### ISSUE TITLE
Unconfigured field _index_preview in server logs

### ISSUE THREAD

**Issue by MartinDemberger** [elastic/elasticsearch-net#5944]
**NEST/Elasticsearch.Net version**: NEST 7.14.1

**Elasticsearch version**: 7.14.0

**.NET runtime version**: net5.0

**Operating system version**: Windows 10

**Description of the problem including expected versus actual behavior**:
I have a multi field index with a prefixed textfield. In the server logs I see the following message very often:
```
[WARN ][o.e.i.s.IndexShard       ] no index mapper found for field: [descriptions.prefix._index_prefix] returning default postings format
```

I don't see any way to solve this warning.

**Steps to reproduce**:
Execute the following test

```csharp
[Fact]
public async Task TestRaw()
{
    var indexName = $"{ Guid.NewGuid()}";
    var connectionPool = new SingleNodeConnectionPool(new Uri("http://localhost:9200"));

    var connectionSettings = new ConnectionSettings(connectionPool)
        .DefaultMappingFor<ElasticTestIndexEntry>(m => m
            .IndexName(indexName)
        )
        .EnableDebugMode()
        .ThrowExceptions()
        //.DisableDirectStreaming()
        ;

    var client = new ElasticClient(connectionSettings);

    try
    {
        await client.Indices.CreateAsync(indexName, c => c
            .Map<ElasticTestIndexEntry>(m => m
                .AutoMap()
                .Properties(p => p
                    .Text(t => t
                        .Name(n => n.Descriptions)
                        .Fields(f => f
                            .Text(tt => tt
                                .Name("prefix")
                                .IndexPrefixes(pp => pp)
                            )
                        )
                    )
                )
            )
        );

        var bulkEntry = new BulkDescriptor();
        bulkEntry.Refresh(Refresh.WaitFor);
        bulkEntry.Index<ElasticTestIndexEntry>(i => i.Document(new ElasticTestIndexEntry() 
        {
            Descriptions = new List<string>()
            { 
                "abc def",
            },
        }));
        var bulkResponse = await client.BulkAsync(bulkEntry);
        bulkResponse.ItemsWithErrors.Should().BeEmpty();
    }
    finally
    {
        await client.Indices.DeleteAsync(indexName);
    }
}

public class ElasticTestIndexEntry
{
    public List<string> Descriptions { get; set; }
}
```

Then you have the warning in the server logs.

**Expected behavior**
The nest configuration configures the index correct so that no warning is in the log.

**Comment by stevejgordon** [comment]
Hi @MartinDemberger. At a first glance, the generated mapping looks okay to me. I'm awaiting some input from colleagues to see if there's something specific about this case we need to be aware of.

**Comment by stevejgordon** [comment]
Sorry for the delay @MartinDemberger. I've had some feedback that suggests you shouldn't need the sub-field in your mapping. The `index_prefixes` option enables a silent optimisation on a regular text field. The client can use the plain field `descriptions` and the text field will automatically decide when to use the special prefix index it creates, only if presented with a prefix query on that field. With your mapping it would index the full text twice - once in `descriptions` and again in `descriptions.prefix`.

So this should be sufficient during creation.
```c#
await client.Indices.CreateAsync(indexName, c => c
            .Map<ElasticTestIndexEntry>(m => m
                .AutoMap()
                .Properties(p => p
                    .Text(t => t
                        .Name(n => n.Descriptions)
			.IndexPrefixes(pp => pp)
                    )
                )
            )
        );
```

**Comment by MartinDemberger** [comment]
No problem. This isn't a issue that's urgent so there is no hurry.

Thanks for the answer but I can't use this. In my live index there is a more complex definition. And the sub-field has another indexer than the main field which provides a alternate way to search. I only removed it for this reproduction.

**Comment by stevejgordon** [comment]
Ah, I see. In that case, it may be best to raise this within the [Elasticsearch repo](https://github.com/elastic/elasticsearch). The client is emitting the mapping as I'd expect based on the code. This seems to be more around the expected usage which may benefit from input from the engineers over there?

**Comment by stevejgordon** [comment]
@MartinDemberger I wanted to check in before closing this out to see if there's anything further I can help with here and if this has answered your question?

**Comment by stevejgordon** [comment]
Closing as I believe this has been answered.
