### ISSUE TITLE
"The client noticed that the server is not a supported distribution of Elasticsearch." after upgrading NEST from 7.13.0 to 7.14.1

### ISSUE THREAD

**Issue by skovalyova** [elastic/elasticsearch-net#5950]
**NEST/Elasticsearch.Net version**: 7.14.1

**Elasticsearch version**: 7.9.1. Instance is deployed in AWS and uses basic authentication type.

**.NET runtime version**: .NET5

**OS version**: Windows 10 Pro, 21H1

**Issue:**
After upgrading NEST from 7.13.0 to 7.14.1, any NEST request to Elasticsearch finishes with the exception: The client noticed that the server is not a supported distribution of Elasticsearch.

Related post in AWS blog:
https://aws.amazon.com/ru/blogs/opensource/keeping-clients-of-opensearch-and-elasticsearch-compatible-with-open-source/

**Comment by stevejgordon** [comment]
Hi @skovalyova. Is this a self-managed cluster (on VMs or similar) or is this running in AWS's managed "Amazon Elasticsearch Service"?

**Comment by skovalyova** [comment]
@stevejgordon thanks for quick response. We do use OSS distribution (OpenDistro).

Also, we've found a related post in AWS blog:
https://aws.amazon.com/ru/blogs/opensource/keeping-clients-of-opensearch-and-elasticsearch-compatible-with-open-source/

**Comment by stevejgordon** [comment]
You're welcome @skovalyova. Since you're on `7.9.1` of the server, you should be fine sticking on `7.13.2` as most of the new features in the client add support for new APIs which won't be present in your version. I close this issue on that basis.
