### ISSUE TITLE
Missing runtime_mappings support for async search requests

### ISSUE THREAD

**Issue by ejsmith** [elastic/elasticsearch-net#5988]
**NEST/Elasticsearch.Net version**: 7.14.1

**Elasticsearch version**: 7.14.1

**.NET runtime version**: 5.0

**Description of the problem including expected versus actual behavior**:
Support for defining runtime mappings is missing from `IAsyncSearchSubmitRequest` and `AsyncSearchSubmitDescriptor`

When I did a diff between `ISearchRequest` and `IAsyncSearchSubmitRequest` I found that they were the same except `ISearchRequest` had these additional fields:

```
IRuntimeFields RuntimeFields
ISlicedScroll Slice
IPointInTime PointInTime
Fields Fields
```

I know async search doesn't support snapshot and maybe some other things so not sure if any of these are missing on purpose, but generally it seems that async search is supposed to be pretty much the same as a regular search.

https://www.elastic.co/guide/en/elasticsearch/reference/current/async-search.html

**Comment by stevejgordon** [comment]
Thanks, @ejsmith for highlighting this gap. Indeed those should be present. I've created a PR for this which I hope to sneak into the next release.

**Comment by ejsmith** [comment]
Thank you!! Is that due to come out soon? I'm currently blocked by this.

Code generation will definitely help make sure that these things aren't missed. I took a look at your 8.0 plan and it looks really good!

**Comment by ejsmith** [comment]
@stevejgordon I also just noticed that `AsyncSearch` is missing these fields compared to `ISearchResponse`:

```cs
long Total { get; }
string PointInTimeId { get; }
```

I'm not sure if `PointInTimeId` is supposed to be there, but I definitely need the `Total` field.

**Comment by ejsmith** [comment]
Bit of a side discussion, but it sure would be nice if models like these shared some sort of interface in common since they are super similar.

**Comment by ejsmith** [comment]
Ahh I just noticed that I can get `Total` from `HitsMetadata`

**Comment by stevejgordon** [comment]
> Ahh I just noticed that I can get Total from HitsMetadata
Was just going to mention that, but we should have the shortcut property there as well. `PointInTimeId` would be needed too as it may represent a newer ID for the PIT if that was used on the search. Will get a PR in now.

> Bit of a side discussion, but it sure would be nice if models like these shared some sort of interface in common since they are super similar.
I think there are historical reasons it's been problematic to do so but I can see why it would be useful. I'll flag that as something I can look at once code-gen is in place as that may dictate some of the design.

**Comment by stevejgordon** [comment]
@ejsmith - The `7.15.0` release is now available https://github.com/elastic/elasticsearch-net/releases/tag/7.15.0

**Comment by ejsmith** [comment]
Thanks @stevejgordon!
