### ISSUE TITLE
Invalid NEST response ... when ping the server

### ISSUE THREAD

**Issue by dkezri** [elastic/elasticsearch-net#6019]
Hi!

**Im getting following exception when I want to ping the elasticsserver on AWS  using basicauthentication**:

"Error": "The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product. Call: Status code unknown from: GET /?pretty=true"

**NEST/Elasticsearch.Net version**: 
7.15.0

** .Net version:  **
  5.0

** The code

```c#
var url = Environment.GetEnvironmentVariable("ELASTICSEARCH_URL");
var username = Environment.GetEnvironmentVariable("ELASTICSEARCH_USERNAME");
var password = Environment.GetEnvironmentVariable("ELASTICSEARCH_PASSWORD");

var settings = new ConnectionSettings(new Uri(url))
	.BasicAuthentication(username, password)
	.ThrowExceptions(alwaysThrow: true)
	.PrettyJson()
	.RequestTimeout(TimeSpan.FromSeconds(300));

var client = new ElasticClient(settings);
```

I will appreciate any help !

**Comment by dkezri** [comment]
Hi @stevedodson 

I had the wrong URL address.   It works fine now. Thanks for your response.

**Comment by stevejgordon** [comment]
Good the hear that @dkezri. I'll close this.
