### ISSUE TITLE
Search method returns the "The client noticed that the server is not a supported distribution of Elasticsearch." error.

### ISSUE THREAD

**Issue by VijayKaravadra** [elastic/elasticsearch-net#6036]
**NEST/Elasticsearch.Net version**:
7.15.1
**Elasticsearch version**:
7.10.2
**.NET runtime version**:
.NET 5
**Operating system version**:
Windows 10
**Description of the problem including expected versus actual behavior**:
NEST library Search method returns the "The client noticed that the server is not a supported distribution of Elasticsearch." error.

**Steps to reproduce**:
 1. Create a simple search request.
 2. Invoke Search method of the NEST library
 3. Observe the response.

**Expected behavior**
The search method should return a proper response.

**Actual behavior**
The search method returns the "The client noticed that the server is not a supported distribution of Elasticsearch." error.

**Note**
The search method works fine with NEST library version 7.9 or lower with the same ElasticSearch server version.

**Comment by stevejgordon** [comment]
Closing due to lack of response.
