### ISSUE TITLE
Issuess Serializing enum/Collection<IpAddress>/Collection<MacAddress> to index

### ISSUE THREAD

**Issue by cklogs** [elastic/elasticsearch-net#6053]
NEST/Elasticsearch.Net version: 7.14.1

Elasticsearch version: 7.14.0

Description of the problem including expected versus actual behavior:

Some data types fail to serialize correctly even if serializers are provided for those specific data types.

My document has some types that don't have explicit NEST types, including:

1. Enum
2. Guid
3. ICollection of IPAddress
4. ICollection of PhysicalAddress

### GUID

When it comes to the Guid class members, they appear _just work_ without any special configuration.

### ENUM

I immediately get stuck when trying to serialize enums to camel case values. 
 
This is my enum definition:
```
public enum Status {
    Normal = 0,
    Warning = 1,
    Critical = 2
}
```

I have tried using this annotation

```
[StringEnum]
public enum Status {
    Normal = 0,
    Warning = 1,
    Critical = 2
}
```

As well as:
```
[StringEnum]
public enum Status {
   [EnumMember(Value = "normal")]
    Normal = 0,
   [EnumMember(Value = "warning")]
    Warning = 1,
   [EnumMember(Value = "critical")]
    Critical = 2
}
```

But the only thing that appears to work is this:

```
// In my document class
	[Keyword]
	[JsonConverter(typeof(StringEnumConverter))]
	public Status Status { get; set; }

	[Text]
	public string StatusSearchableProperty {
		get {
			return Status.ToString();
		}
	}

// In my DI config
var pool = new SingleNodeConnectionPool(new Uri(elasticSearchUrl));
	var settings = new ConnectionSettings(pool, sourceSerializer: JsonNetSerializer.Default)
		.BasicAuthentication(elasticSearchUsername, elasticSearchPassword)
		.DefaultMappingFor<AssetSearchDo>(documentMapping => documentMapping
			.IndexName(elasticSearchAssetIndexName)
			.IdProperty(document => document.Id)
		);
	builder
		.Register<IElasticClient>(c => new ElasticClient(settings))
		**.SingleInstance();**
```

Then I indeed see values:

![image](https://user-images.githubusercontent.com/10749074/141731348-75636d44-a4d3-42f7-bc1f-f6e3e5996fe0.png)

Without the second getter property, the enum field is never indexed. I'm a little baffled.

### `Collection<IPAddress>` / `Collection<PhysicalAddress>`

Secondly, when I try to index the IPAddress/PhysicalAddress collections with some custom Newtonsoft Json converters, they fail to index.

In my DI config:
![image](https://user-images.githubusercontent.com/10749074/141731652-ce2d0277-9f00-41ca-89d5-097006d5a7ba.png)

In my document class:
![image](https://user-images.githubusercontent.com/10749074/141731721-4d44cb61-4fb3-4f53-a2ac-2f07823c8c77.png)

Is there a proper way to go about providing custom serializers for these types? I did not see any obvious direction from the documentation around custom serialization. We would prefer not to store the IPAddress/PhysicalAddress collections as collections of strings.

Any help with the two issues above would be greatly appreciated.

**Comment by stevejgordon** [comment]
Hi, @cklogs. Firstly, my apologies for not responding to this sooner. It got missed in my review of issues. You're code generally looks like it's on the right track. I'm not entirely sure why it's not working as expected as I tested locally and it seems to be for me (see code below which works).

You're adding the Json.NET serializer which gives you control to apply any of the Json.NET concepts to control the serialization of your source objects. Adding a custom convert as you've done for PhysicalAddress allows you to write out the JSON precisely if the default Json.NET serialization + attributes don't provide enough control. The `EnumMember` attributes should also be respected by the `JsonNetSerializer`.

You mention the collections are failing to index. What exactly happens there?

```c#
public class Program
{
    private static void Main()
    {
        var pool = new SingleNodeConnectionPool(new Uri("https://localhost:9600"));
        var settings = new ConnectionSettings(pool, (b, s) => new JsonNetSerializer(b, s, contractJsonConverters: new JsonConverter[]
        {
            new PhysicalAddressConverter()
        })).DefaultIndex("test");

        var client = new ElasticClient(settings);

        var result = client.IndexDocument(new ExampleType
        {
            Addressess = new List<PhysicalAddress> { new PhysicalAddress { AddressLine1 = "LINE1"} },
            Status = Status.Warning
        });
    }
}

public class PhysicalAddress
{
	public string AddressLine1 { get; set; }
}

public class PhysicalAddressConverter : JsonConverter<PhysicalAddress>
{
    public override PhysicalAddress ReadJson(JsonReader reader, Type objectType, PhysicalAddress existingValue, bool hasExistingValue, JsonSerializer serializer) => throw new NotImplementedException();
    public override void WriteJson(JsonWriter writer, PhysicalAddress value, JsonSerializer serializer)
    {
        writer.WriteStartObject();
        writer.WritePropertyName("custom-property");
        writer.WriteValue(value.AddressLine1);
        writer.WriteEndObject();
    }
}

public class ExampleType
{
    [JsonConverter(typeof(StringEnumConverter))]
    public Status Status { get; set; }

    public ICollection<PhysicalAddress> Addressess { get; set; }
}

public enum Status
{
    [EnumMember(Value = "normal")]
    Normal,
    [EnumMember(Value = "warning")]
    Warning,
    [EnumMember(Value = "critical")]
    Critical
}
```

The above serialises the document as (captured on the wire using Fiddler):
```
{"status":"warning","addressess":[{"custom-property":"LINE1"}]}
```

**Comment by stevejgordon** [comment]
I'm just following up @cklogs to see if you can provide more detail about this issue as per the comment above?

**Comment by stevejgordon** [comment]
I'm going to close this issue to avoid it becoming stale. Please comment if you have further information so we can assist and re-open if necessary.
