### ISSUE TITLE
DateOnly in .net 6 causes indexing error, add support for it

### ISSUE THREAD

**Issue by CPlusPlus17** [elastic/elasticsearch-net#6058]
**Is your feature request related to a problem? Please describe.**
Trying to index an object with DateOnly wil cause the following error:

> Failed to index document 618252e5fd34fc54f4d94ac3: Type: mapper_parsing_exception Reason: "failed to parse field [dueAt.dayOfWeek] of type [integer] in document with id '618252e5fd34fc54f4d94ac3'. Preview of field's value: 'Friday'" CausedBy: "Type: number_format_exception Reason: "For input
> string: "Friday"""

**Describe the solution you'd like**
Proper support for DateOnly, aka a working serializer and deserializer.

**Describe alternatives you've considered**
Some custom serializer, but don't know how to implement this.

**Additional context**

Settings:

```
var settings = new ConnectionSettings(pool, (builtin, settings) => new JsonNetSerializer(builtin, settings,
            contractJsonConverters: new JsonConverter[] {new StringEnumConverter()})).EnableDebugMode();
```

StringEnumConverter seems to break support for DateOnly.

**Comment by naefp** [comment]
vote

**Comment by stevejgordon** [comment]
Hi @CPlusPlus17. Thanks for raising this. These new types do need some attention and are not considered supported in the current serialiser implementation. As we don't provide a `net6.0` specific target for this library introducing support needs some consideration.

For `8.0`, the good news is that we are moving to `System.Text.Json` for serialisation which should ensure that new Microsoft types are supported by the serialiser out of the box. We also plan to ship `net6.0` targets of the package.

I'll review how achievable a custom converter for these types will be and provide a workaround code sample once this it's thoroughly tested. Unfortunately even `Newtonsoft.Json` has yet to add support for these types. If you can, I'd recommend sticking to the `DateTime` type for properties involved in serialisation if at all possible until this work is completed.

**Comment by stevejgordon** [comment]
We won't be making significant changes to the internal serializer used for source serialization (by default) in the 7x timeframe. We have moved to `System.Text.Json` for v8, although that also doesn't fully support these new types yet either. While these types have value, it's best to avoid them until more serializers support them out of the box.

**Comment by niemyjski** [comment]
@Mpdreamz @stevejgordon Hope all is well. I'm running into this now. If you don't support .NET 6 as a target doesn't matter. You target .NET Standard 2.0 and 2.1 which are officially compatible with .NET 6 and .NET 6 is LTS. Effort needs to be put in to support this on current supported version of NEST client for all consumers. Are there any work arounds we can use that have been reported as I'm not familiar with Utf8Json at a code level?

**Comment by niemyjski** [comment]
@Mpdreamz @stevejgordon Hope all is well. I get that you don't support .NET Core x as an output but do target .NET Standard 2.0 and 2.1.  It doesn't really make sense to target a specific version of .NET with those two targets. However, considering many apps have started to use the new types and .NET 6 is LTS seems like this is something that should be given some priority and supported by NEST or at least a work around.

Also worth noting that current STJ doesn't yet support these types until .NET 7. But our models specify STJ contract serializers.  https://github.com/dotnet/runtime/issues/53539

**Comment by niemyjski** [comment]
Also, I'd like to add for us to upgrade to NEST 8.0 is a massive undertaking due to the massive number of breaking changes.

**Comment by niemyjski** [comment]
Looks like it's supported by json.net in https://github.com/JamesNK/Newtonsoft.Json/pull/2679 latest beta on nuget. I'd rather not have to bring in newtonsoft and use the defaults for a green field project...

**Comment by stevejgordon** [comment]
@niemyjski Adding a specific `NET6.0` target for 7.x is not going to a priority while we work on v8. I did take a spike on that a while back and ran into some issues, although I need to revisit what those issues where. Given that, as you note, even STJ doesn't yet support these new `DateOnly` and `TimeOnly` types, our general advice is to avoid them on source types. For 8.x we'll likely be able to support those with the STJ library. One the benefits of the move to STJ as the default source serializer is that custom converters work OOB and provide more standard ways to control advanced serialization.

Thanks for linking to the Newtonsoft PR. Good to see support coming there soon. Once supported there, a workaround would be to use our NewtonsoftJson package to gain support that way. You could also add in a custom `ISerializer` as a current workaround with a serializer that supports these types. Implementing `ISerializer` is the intended way for consumers to "extend" the client to support any behaviour for source serialization that is required.

**Comment by sjd2021** [comment]
@stevejgordon  STJ does support DateOnly and TimeOnly. Newtonsoft was only updated to support them after the STJ version was merged in a few months ago.

**Comment by stevejgordon** [comment]
@sjd2021 It's been added for .NET 7.0 which is not yet released and supported until November. Our new client targets STJ so consumers will be able to leverage those types by default in that release.
