### ISSUE TITLE
Include missing properties on mapping field types

### ISSUE THREAD

**Issue by fredeil** [elastic/elasticsearch-net#6067]
Hey again @stevejgordon and rest of the maintainers,

I'm missing the `ignore_malformed` property on the [IP field type](https://www.elastic.co/guide/en/elasticsearch/reference/current/ip.html) in C#. I'm sure there are more types missing other properties too.

To be more specific I'm trying to set this using the IP Attribute mapping https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Mapping/Types/Specialized/Ip/IpAttribute.cs.

Today we have to maintain a JSON version of the mapping and a C# version of the index mapping because of these limitations.

**Comment by stevejgordon** [comment]
Apologies for the delay @fredeil. I'll take a look at this as it's likely an oversight. It's one of the reasons for moving to code-generating these properties from a schema for v8.

**Comment by stevejgordon** [comment]
@fredeil I have added a fix for this which we'll include in the next release.
