### ISSUE TITLE
used a stress test to insert data, partial data lost

### ISSUE THREAD

**Issue by WangJunZzz** [elastic/elasticsearch-net#6073]
**NEST/Elasticsearch.Net version**:  7.15.0

**Elasticsearch version**:  7.15.0

**.NET runtime version**: 6.0

**Operating system version**: Windows10

**Description of the problem including expected versus actual behavior**:
I used a stress test to insert data, partial data Data is lost

insert code 
```csharp
        public IElasticClient GetElasticClient()
        {
            var pool = new SingleNodeConnectionPool(new Uri(_configuration.GetValue<string>("EsConnectionStrings:Url")));
            var connectionSettings =
                new ConnectionSettings(pool);
            connectionSettings.EnableHttpCompression();
            connectionSettings.BasicAuthentication(_configuration.GetValue<string>("EsConnectionStrings:UserName"),
                _configuration.GetValue<string>("EsConnectionStrings:Password"));

            return new ElasticClient(connectionSettings);
        }

 var Client = _elasticsearchProvider.GetElasticClient();

 await Client.IndexAsync(dto, e => e.Index(IndexName));
```

**Steps to reproduce**:
 1. has a web api insert data
 2. use k6 stress test
![image](https://user-images.githubusercontent.com/25657426/145750713-d5694bba-b35e-4eb9-aee8-138f6edc3b75.png)
3. but i insert 467

**Comment by stevejgordon** [comment]
@WangJunZzz The first job here is to understand if a request has failed or simply not been sent. My suspicion is that all requests will have been sent by the client, but one may have failed on the server. I'd expect a client-side exception if something failed within the client itself.

You should inspect the `IndexResponse` from the call to learn more about the outcome.

```c#
var response = await Client.IndexAsync(dto, e => e.Index(IndexName));
```

On that response, you can check whether the request `IsValid`. It's possible one of the requests could fail, especially if the server starts throttling them. You can then check the `response.ApiCall.HttpStatusCode` property and `response.ServerError` for more details if the request failed. The `response.ApiCall.AuditTrail` will provide further details that may be useful.

**Comment by WangJunZzz** [comment]
thanks  IsValid  is false , i used polly solve.
