### ISSUE TITLE
README not up to date for the section "Compatibility Clarifications"

### ISSUE THREAD

**Issue by gillg** [elastic/elasticsearch-net#6076]
Hello,

This is not a software bug, but more a documentation "bug" in the README.
It's writen in section "Compatibility Clarifications"
> I have a 7.0 server, what client should I use?
> Always use the latest minor version of the client within that major version, so in this instance, at time of writing, this is version 7.14.0. The reason being is that 7.14.x will contain many bug fixes not present in the 7.0.0 version of the client.

That's make sense, but since the version 7.14 you introduced the pre-flight check, so it's not possible anymore to use a client up to date with a cluster in a previous version.
As I understand (correct me if I'm wrong), this check is primarly a counter mesure against a open search or any potential ES fork to prevent using this official client lib with a non standard ElasticSearch server. But in the case where you are using an official ES (7.10.2 in my case) you can't use the latest client library.
Is there a client constructor option to prevent flight check ? Is it another "hard" limitation or breaking change in v7.15 which make it incompatible with older servers ? What are options to stay up to date ?

**Comment by stevejgordon** [comment]
Hi @gillg. The latest client should be compatible with the version you mention when using the default distribution of Elasticsearch. With the 7.11 release of Elasticsearch, we no longer release oss-only distributions, as stated in the [FAQ on license change](https://www.elastic.co/pricing/faq/licensing). The client can be pinned to a version <7.14 if connecting to a cluster running the OSS distribution. The recommendation is to upgrade to the latest default distribution of Elasticsearch, which is free to use under [Elastic License v2](https://www.elastic.co/licensing/elastic-license) at which point the compatibility section applies.

If you are receiving an error with the latest client and the non-OSS distribution, this may be a bug. Can you please confirm the distribution you are using?

Thanks for highlighting this confusion in the README. We'll review that and see if we can clarify that section.

**Comment by stevejgordon** [comment]
We'll revisit the docs further as part of `8.0.0` work, but for now, I have included a note in the compatibility documentation to further clarify OSS distribution support.
