### ISSUE TITLE
The client noticed that the server is not a supported distribution of Elasticsearch (NEST 7.16 to Elasticsearch 7.9.0)

### ISSUE THREAD

**Issue by Schoof-T** [elastic/elasticsearch-net#6077]
**NEST/Elasticsearch.Net version**: 7.16.0

**Elasticsearch version**: 7.9.0

**.NET runtime version**: 4.7.2

**Operating system version**:  Windows 10 / Server 2019

**Description of the problem including expected versus actual behavior**:
I was previously using NEST/Elasticsearch.NET 7.9.0, but we are looking to upgrade to 7.16.2 for the LOG4J vurnability.
Looking at your official documentation I noticed the following:

> I have a 7.0 server, what client should I use?
> 
> Always use the latest minor version of the client within that major version, so in this instance, at time of writing, this is version 7.14.0. The reason being is that 7.14.x will contain many bug fixes not present in the 7.0.0 version of the client.
> 
> Client methods which call endpoints added to Elasticsearch since 7.0.0 will fail due to those endpoints not existing on the server.

So I upgraded my NEST/ElasticSearch to the latest minor version (7.16). Now when I try to connect to our Elastic Cluster I get the exception "The client noticed that the server is not a supported distribution of Elasticsearch".

I would expect this to just work, according to your official documentation?

**Steps to reproduce**:
 1. Have ElasticSearch 7.9.0
 2. Have NEST/ElasticSearch 7.16.0
 3. Try to connect to ElasticSearch 7.9.0

**Expected behavior**
I expected to be able to connect to the ElasticSearch cluster.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by stevejgordon** [comment]
Hi @Schoof-T. This error suggests that you may be using the OSS distribution. Could you please confirm? With the 7.11 release of Elasticsearch, we no longer release oss-only distributions, as stated in the [FAQ on license change](https://www.elastic.co/pricing/faq/licensing). The recommendation is to upgrade to the latest default distribution of Elasticsearch, which is free to use under [Elastic License v2](https://www.elastic.co/licensing/elastic-license). Otherwise, you can pin the client version to <7.14.

**Comment by Schoof-T** [comment]
Thanks for the reply @stevejgordon. How do I check what version I am running?
This is the result from GET / in kibana
`{
  "name" : "ELASTIC-DEV-01",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "bVVfDpMQSais2rH2ubwyDw",
  "version" : {
    "number" : "7.9.0",
    "build_flavor" : "unknown",
    "build_type" : "unknown",
    "build_hash" : "a479a2a7fce0389512d6a9361301708b92dff667",
    "build_date" : "2020-08-11T21:36:48.204330Z",
    "build_snapshot" : false,
    "lucene_version" : "8.6.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
`

**Comment by stevejgordon** [comment]
@Schoof-T I'd expect to see `"build_flavor": "default"` or `"build_flavor": "oss"` in that response. The fact that this is returning "unknown" explains the failure. How is your server installed and deployed?

**Comment by Schoof-T** [comment]
> @Schoof-T I'd expect to see `"build_flavor": "default"` or `"build_flavor": "oss"` in that response. The fact that this is returning "unknown" explains the failure. How is your server installed and deployed?

We used the Elastic Search MSI (Beta): https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.0.msi, and just followed the installer.

**Comment by stevejgordon** [comment]
Thanks for providing that information @Schoof-T. Unfortunately, this may be a bug in the MSI installer causing the `build_flavor` to be `unknown` and therefore causing the product check to fail. The MSI is considered beta and will no longer be produced after 7.16.2.  In your case, I think you'll need to first upgrade the nodes to the latest release of Elasticsearch using the [zip package](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/zip-windows.html). Hopefully, that will resolve the unknown `build_flavor` that is reported. The `7.9.0` client should continue to be compatible with this newer server version. Once the server is upgraded and reporting a known `build_flavor` you can then update to the latest client. Note that I haven't tested this myself and I'd advise testing your scenario in a non-production environment first to ensure that it works as expected.

**Comment by brysbroughton** [comment]
Is ElasticSearch.Net affected by the Log4j vulnerability? I see the thread is about version conflicts but originally the issue was motivated by log4j remediation.

**Comment by stevejgordon** [comment]
@brysbroughton The .NET client libraries are not affected by log4j so there's no risk with those in that regard. The Elasticsearch server is built on Java and does need the latest patches to fully mitigate any vulnerabilities by picking up the latest fixes for log4j.

**Comment by Schoof-T** [comment]
> Thanks for providing that information @Schoof-T. Unfortunately, this may be a bug in the MSI installer causing the `build_flavor` to be `unknown` and therefore causing the product check to fail. The MSI is considered beta and will no longer be produced after 7.16.2. In your case, I think you'll need to first upgrade the nodes to the latest release of Elasticsearch using the [zip package](https://www.elastic.co/guide/en/elasticsearch/reference/7.16/zip-windows.html). Hopefully, that will resolve the unknown `build_flavor` that is reported. The `7.9.0` client should continue to be compatible with this newer server version. Once the server is upgraded and reporting a known `build_flavor` you can then update to the latest client. Note that I haven't tested this myself and I'd advise testing your scenario in a non-production environment first to ensure that it works as expected.

I will test again after upgrading to 7.16.2 using the ZIP file. Thanks for the advice.

**Comment by stevejgordon** [comment]
@Schoof-T You're most welcome! I'll close this issue for now since the client is behaving correctly. We can re-open if anything fails after the upgrade.
