### ISSUE TITLE
with_positions_payloads enum value is missing in src/Nest/Mapping/TermVectorOption.cs

### ISSUE THREAD

**Issue by vkras** [elastic/elasticsearch-net#6078]
**NEST/Elasticsearch.Net version**:
7.14.1 (latest)

**Elasticsearch version**:
7.16.3 (latest)

**.NET runtime version**:
.Net.core 3.1

**Operating system version**:
Windows 10

**Description of the problem including expected versus actual behavior**:
One of the 7 enum values is missing. It causes a crash on deserialization of the response for a template or index definition:
var response = _elasticClient.Indices.GetTemplate(name);
FailureReason: Unrecoverable/Unexpected BadResponse while attempting GET on https://192.168.xx.xx:9200/_template/dev
System.ArgumentException: Requested value 'with_positions_payloads' was not found.

**Steps to reproduce**:
 1. Create a template or index with one of the fields set to 
                "field": {
                    "analyzer": "whitespace_apostrophe_delimited",
                    "term_vector": "with_positions_payloads",
                    "type": "text"
                },
 2. Try to get mapping via Indices.GetTemplate(name)

**Expected behavior**
No exceptions, response is correctly processed

**Comment by stevejgordon** [comment]
Apologies for the delay @vkras. I'll take a look at this.

**Comment by stevejgordon** [comment]
@vkras This is now added and will be available in the next release.

**Comment by vkras** [comment]
Thank you!
