### ISSUE TITLE
Nest.IndicesStats should contain shard_stats reported by GET /index/_stats

### ISSUE THREAD

**Issue by vkras** [elastic/elasticsearch-net#6079]
**Is your feature request related to a problem? Please describe.**
GET /index/_stats returns shard_stats with total_count property for indices. But C# method ElasticClient.Indices.Stats(index) returns Nest.IndicesStats class where the shard_stats is not mapped. 

**Describe the solution you'd like**
Map shard_stats API returns to C# object.

**Describe alternatives you've considered**
I have to made a second call to get this information from index settings (it's not ideal).

**Comment by stevejgordon** [comment]
Apologies for the delay @vkras. I'll take a look at this.

**Comment by stevejgordon** [comment]
Added in 7.15, so re-labelling this as a feature we will add.

**Comment by stevejgordon** [comment]
@vkras I've added this for the next release. Thanks for raising it.
