### ISSUE TITLE
make ElasticClient IDisposable

### ISSUE THREAD

**Issue by dliulabs** [elastic/elasticsearch-net#6081]
Currently the ElasticClient is created, it is not possible to get rid of it. I would love to be able to do something like:

`using (var settings) {
  settings.GlobalHeaders(new NameValueCollection 
    { 
        { "Authorization", $"Bearer {token}" } 
    };
  var client = new ElasticClient(settings);
  var results = client.DoSomething();
  // return results;
}`

The problem with the ElasticClient is very static, it would be helpful in a MVC API Controller, we can switch "security context" of the connection.

**Comment by stevejgordon** [comment]
Hi, @dliulabs. The client is designed to be registered/used as a singleton for the life of an application. This is because it maintains open connections to the nodes of the cluster as well as some state about failures of nodes. Re-establishing this per-request would add overhead to each use that could impact performance. It could also cause socket exhaustion if created/disposed frequently.

While strictly speaking it could be `IDisposable`, the only IDisposable resources it holds on to are mainly the TCP connections to the servers, such that connections are reused.

In your sample code above, the client instance would go out of scope after the method ends and likely be collected during the next garbage collection. At that point, connections would be closed. IDisposable isn't strictly needed to produce the same result.

It's not clear why you cannot reuse the client between MVC controllers/actions? Are you connecting to different clusters?

**Comment by dliulabs** [comment]
Hi @stevejgordon Thank you so much for the detailed reply. Yes, I agree with you that in normal "single user" case, it makes sense to use a singleton instance of ElasticClient, however, in a "multi-tenancy" backend microservice/API, the connection needs to change to connect to use another user's account according to incoming user's roles. For example a lot of Elastic admin APIs (e.g. /xpack/security/user & /xpack/security/role APIs) can only be consumed using 'elastic' user rights, and some API needs to be done using a non-root (non-elastic) user and all the indices read/write operations will need to be done by yet another different users in different roles. This is very similar to how Entity Framework DbContext is used. In EF case,  each incoming Http call will have different DbContext and as soon as the Http ends, a different DbContext needs to be created (using different db user) to connect to the backend databases. In Elasticsearch case, an Index is just like a "SQL table", its data belongs to different "tenant/user" and using the same ElasticClient instance is not feasible. It is necessary to disposed of the existing ElasticClient to erase credential in memory and the re-create a new instance of ElasticClient. We can use the same instance of ElasticClient (so that we keep the same singleton instance of HttpClient), but we need to have ability to swap out "Basic Authentication settings" or swap out "Global Authorization. Headers".

**Comment by stevejgordon** [comment]
@dliulabs Thanks for the detailed use case. This is a more complex scenario, but I believe you can still support it using a singleton client. We support adding request configuration (per-request) to the `RequestParameters` which accepts basic and API key auth credentials. Using that, you could control the auth header for each request. You'd still benefit from the pooled HTTP connections etc. Does that sound like it could work in your case?

**Comment by dliulabs** [comment]
I see a little bit of info about per request config, but not able to find any documentation on how to inject an authentication into it, can you correct the following code? I am getting `error CS1061: 'RequestConfigurationDescriptor' does not contain a definition for 'Authentication' and no accessible extension method 'Authentication' accepting a first argument of type 'RequestConfigurationDescriptor' could be found (are you missing a using directive or an assembly reference?)`

`using Nest;
using Elasticsearch.Net;
using Elastic.Transport;

var blank_settings = new ConnectionSettings (new Uri (ELASTIC_URI))
    .PrettyJson(true);
var blank_client = new ElasticClient(blank_settings);

var r = await blank_client.Cat.IndicesAsync(
    c => c
    .AllIndices()
    .RequestConfiguration(r => r.Authentication(new BasicAuthentication(ELASTIC_USER, ELASTIC_PASS))) // <---- Exception here
);`

**Comment by stevejgordon** [comment]
@dliulabs The code in my comment above should work on your API call. It's not `r  => r.Authentication` but `r => r.BasicAuthentication("username", "password")`

**Comment by dliulabs** [comment]
Hi @stevejgordon,

Okay, I tweak a little of my code and was lucky to have found the right syntax. This one works:
```
using Nest;
using Elasticsearch.Net;
using Elastic.Transport;

var blank_settings = new ConnectionSettings (new Uri (ELASTIC_URI))
    .PrettyJson(true);
var blank_client = new ElasticClient(blank_settings);

var r = await blank_client.Cat.IndicesAsync(
    c => c
    .AllIndices()
    .RequestConfiguration(r => r.BasicAuthentication(ELASTIC_USER, ELASTIC_PASS))
);
```

So if this per-call  configuration does not keep anything in the ElasticClient. You are right, we can use a Singleton ElasticClient and just supply needed credentials at per-request basis. 

Thank you for all your help.
