### ISSUE TITLE
Include version in GetPipeline response

### ISSUE THREAD

**Issue by mpwoz** [elastic/elasticsearch-net#6082]
**Is your feature request related to a problem? Please describe.**
GetPipeline doesn't include pipeline version

**Describe the solution you'd like**
The ES ingest/get_pipeline API includes a `version` field in the response: https://www.elastic.co/guide/en/elasticsearch/reference/current/get-pipeline-api.html
This is needed for making concurrency-safe updates to an existing pipeline (e.g. adding a processor)

The Nest client does not include this field in the response. https://github.com/elastic/elasticsearch-net/blob/master/src/Nest/Ingest/GetPipeline/GetPipelineResponse.cs

**Describe alternatives you've considered**
Right now, I'm considering falling back to the low-level REST Api, but would prefer to use the high level nest API as it already includes everything I need (except version) https://github.com/elastic/elasticsearch-net#falling-back-to-elasticsearchnet

**Additional context**

**Comment by stevejgordon** [comment]
Thanks for catching and raising this @mpwoz. I've fixed this in #6085 which will go out in the next release.
