### ISSUE TITLE
Implement composable (V2) templates in High Level Client

### ISSUE THREAD

**Issue by vkras** [elastic/elasticsearch-net#6083]
**Is your feature request related to a problem? Please describe.**
From what I can see, only legacy (deprecated) templates are implemented in the latest version of NEST.

**Describe the solution you'd like**
I want new component templates and index templates (AKA Templates V2, composable templates) added to NEST.

**Describe alternatives you've considered**
Low Level client but it requires manual mapping for results

**Additional context**
Old V1 templates are deprecated and throw warning below:
"Legacy index templates are deprecated in favor of composable templates."

**Comment by stevejgordon** [comment]
Hi, @vkras. Component template APIs were added in 7.16.0. Index Template (v2) APIs were indeed missing. I've added these in #6101 and will release them in 7.17.0.

**Comment by vkras** [comment]
Thank you, it was fast.
