### ISSUE TITLE
SumAggregation does not return the correct value

### ISSUE THREAD

**Issue by hoppities** [elastic/elasticsearch-net#6121]
**NEST/Elasticsearch.Net version**: 5.6.16

**Elasticsearch version**: 5.6.6

**Description of the problem including expected versus actual behavior**:

When creating a `SumAggregation`, the value that is returned does not match what is in the index. We noticed that the value `213413252351.34` is returned correctly when just selecting the column value. However, if that value is included in a `SumAggregation`, the value is incorrect.

REQUEST
```
{
	"aggs": {
		"groupedAggregation": {
			"aggs": {
				"var_1": {
					"sum": {
						"field": "invoiceTotal"
					}
				},
				"var_2": {
					"sum": {
						"field": "invoiceBalanceDue"
					}
				},
				"groupedAggregationSubRecords": {
					"top_hits": {
						"size": 10000,
						"_source": {
							"includes": ["invoiceTotal", "invoiceBalanceDue"]
						}
					}
				}
			}
		}
	},
	"from": 0,
	"size": 0
}
```
RESPONSE
```
{
	"took": 3,
	"timed_out": false,
	"_shards": {
		"total": 1,
		"successful": 1,
		"skipped": 0,
		"failed": 0
	},
	"hits": {
		"total": 1,
		"max_score": 0.0,
		"hits": []
	},
	"aggregations": {
		"groupedAggregation": {
			"doc_count_error_upper_bound": 0,
			"sum_other_doc_count": 0,
			"buckets": [{
					"key": "test",
					"doc_count": 1,
					"var_0": {
						"value": 1
					},
					"var_1": {
						"value": 2.13413249024E11
					},
					"groupedAggregationSubRecords": {
						"hits": {
							"total": 1,
							"max_score": 1.4E-45,
							"hits": [{
									"_source": {
										"invoiceBalanceDue": 2.1341325235134E11,,
										"invoiceTotal": 2.1341325235134E11
									}
								}
							]
						}
					},
					"var_2": {
						"value": 2.13413249024E11
					}
				}
			]
		}
	}
}
```

**Steps to reproduce**:
 1. Load the decimal value `213413252351.34` into an index
 2. `new SumAggregation("Some_Placeholder", "yourValueColumnName");`
 3. Make the request against your index cluster and see the above results.

EDIT:
Making the above request directly against the index rather than using the Nest library returns the following:
```
{
	"took": 1,
	"timed_out": false,
	"_shards": {
		"total": 1,
		"successful": 1,
		"skipped": 0,
		"failed": 0
	},
	"hits": {
		"total": 1,
		"max_score": 0.0,
		"hits": []
	},
	"aggregations": {
		"groupedAggregation": {
			"doc_count_error_upper_bound": 0,
			"sum_other_doc_count": 0,
			"buckets": [{
					"key": "test",
					"doc_count": 1,
					"var_0": {
						"value": 1
					},
					"var_1": {
						"value": 2.13413249024E11
					},
					"groupedAggregationSubRecords": {
						"hits": {
							"total": 1,
							"max_score": 1.4E-45,
							"hits": [{
									"_source": {
										"invoiceBalanceDue": 2.1341325235134E11,
										"invoiceTotal": 2.1341325235134E11
									}
								}
							]
						}
					},
					"var_2": {
						"value": 2.13413249024E11
					}
				}
			]
		}
	}
}
```

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by stevejgordon** [comment]
Hi, @hoppities. Elasticsearch `5.x` and the `5.x` clients are out of support but I can summarise what I think is happening here. I believe the issue stems from the precision of the value being stored. Without an explicit mapping, your value is likely being stored as a `float` value and losing some of the precision, ending up as `213413249024` which is the value returned by the sum aggregation. I suspect that if you explicitly map your fields as a `double`, then the extra precision will retain the value you expect here. You may also be able to store it more efficiently with a `scaled_float` but again, precision may be lost. As far as I can see, the responses above are correct based on these precision differences. I'll close this issue on that basis. While this version is out of support, you may be able to get a deeper explanation from the [community forum](https://discuss.elastic.co/).
