### ISSUE TITLE
Nested Query Doesn't Work 

### ISSUE THREAD

**Issue by hesamdarbandi** [elastic/elasticsearch-net#6141]
as you can see on code below :

public class ReceiveMoneyVoucher
    {
        public Guid Id { get; set; }
        [Nested]
        public List<ReceiveMoneyVoucherItem> VoucherItems { get; set; } = new List<ReceiveMoneyVoucherItem>();
   }

I've defined nested mapping which can see the result below:

"voucherItems": {
          "type": "nested",
          "properties": {

But nested query Doesn't return the expected result as can see below :

  var res = await ElasticClient.SearchAsync<ReceiveMoneyVoucher>(s => s
               .Index(IndexName)
            //.From(searchParam.PageNumber - 1)
            //.Size(searchParam.PageSize)
            //.Query(searchQuery));
            .Query(q => q.Nested(n => n.Path("voucherItems").Query(nq => nq.Match(t => t.Field("voucherItems.description").Query("hesam hesam"))))));

**Comment by stevejgordon** [comment]
@hesamdarbandi I need a more complete issue in order to investigate this, please. What version of Elasticsearch and the client are you using? The code above looks incomplete (missing generics on lists for example) but in principle that query looks like it should work. You state it doesn't return the expected response. What response are you receiving and what are you expecting? 

Assuming the following mapping and initial data:

```
PUT repro-6141
{
  "mappings": {
    "properties": {
      "voucherItems": {
        "type": "nested" 
      }
    }
  }
}

PUT repro-6141/_doc/1
{
  "id" : "73f9e18d-0487-40a4-bf5b-0e380e152d79",
  "voucherItems" : [
    {
      "description" : "hesam hesam"
    }
  ]
}

GET repro-6141/_search
{
  "query": {
    "nested": {
      "path": "voucherItems",
      "query": {
        "bool": {
          "must": [
            { "match": { "voucherItems.description": "hesam hesam" }}
          ]
        }
      }
    }
  }
}
```

And the following C# code (.NET 6):

```c#
using Nest;

var client = new ElasticClient("CLOUDID", 
    new Elasticsearch.Net.BasicAuthenticationCredentials("elastic", "PASSWORD"));

var res = await client.SearchAsync<ReceiveMoneyVoucher>(s => s
    .Index("repro-6141")
    .Query(q => q.Nested(n => n.Path("voucherItems").Query(nq => nq.Match(t => t.Field("voucherItems.description").Query("hesam hesam"))))));

Console.ReadKey();

public class ReceiveMoneyVoucher
{
    public Guid Id { get; set; }

    [Nested]
    public List<VoucherItem> VoucherItems { get; set; } = new List<VoucherItem>();
}

public class VoucherItem
{
    public string Description { get; set; }
}
```

When I execute the query I receive a single hit as I'd expect.

I'll need complete reproduction steps (and possibly more details about your mapping and data) for your scenario in order to assist further. Thanks!

**Comment by hesamdarbandi** [comment]
I Appreciate For Your Consideration And Response, I've used nest client version 7.16.0 and dotnet 5.0


I have Parent Object That Called ReceiveMoneyVoucher that have nested List in it that called VoucherItems,So
I create mapping for parent and specify nested for  VoucherItems in it.
 My nested array data looks like below

new List<VoucherItem> VoucherItems = new List<VoucherItem>
{
   new VoucherItem { Description = 'apple' },
   new VoucherItem { Description = 'orange' }
}


query is 

var res = await client.SearchAsync<ReceiveMoneyVoucher>(s => s
    .Index("receivemoneyvouchers")
    .Query(q => q.Nested(n => n.Path("voucherItems").Query(nq => nq.Match(t =>   t.Field("voucherItems.description").Query("apple"))))));


so I expect The Response as below

List of ReceiveMoneyVoucher
[
    Id = "73f9e18d-0487-40a4-bf5b-0e380e152d79"
    VoucherItems = [
          {
                 Description = 'apple' 
          }
    ]
]

but It has return null

**Comment by hesamdarbandi** [comment]
I've created an index for the parent 

```xml

ElasticClient.Indices.Create("receivemoneyvouchers", m => m.Map<T>(x => x.AutoMap()));

ElasticClient.IndexAsync(receiveMoneyVoucher, m => m.Index("receivemoneyvouchers"));

  ```

**Comment by stevejgordon** [comment]
@hesamdarbandi What property is `null` in your case? If you index the document in code (as above), then you may need to wait for up to 1 second for it to appear in subsequent search results. I've attempted to reproduce based on your information above and cannot. Here is the code I'm using:

```c#
using Elasticsearch.Net;
using Nest;

var cloudPool = new CloudConnectionPool("CLOUDID", new BasicAuthenticationCredentials("elastic", "PASSWORD"));
var client = new ElasticClient(new ConnectionSettings(cloudPool).EnableDebugMode());

var cleanup = await client.Indices.DeleteAsync("receivemoneyvouchers");

var createResponse = await client.Indices.CreateAsync("receivemoneyvouchers", m => m.Map<ReceiveMoneyVoucher>(x => x.AutoMap()));

var receiveMoneyVoucher = new ReceiveMoneyVoucher();
var indexResponse = await client.IndexAsync(receiveMoneyVoucher, m => m.Index("receivemoneyvouchers"));

await Task.Delay(1000); // need to wait for the new document to be available for searching - could force a refresh here too

var searchResponse = await client.SearchAsync<ReceiveMoneyVoucher>(s => s
    .Index("receivemoneyvouchers")
    .Query(q => q.Nested(n => n.Path("voucherItems").Query(nq => nq.Match(t => t.Field("voucherItems.description").Query("apple"))))));

Console.WriteLine(searchResponse.DebugInformation);

Console.ReadKey();

public class ReceiveMoneyVoucher
{
    public Guid Id { get; set; } = Guid.NewGuid();

    [Nested]
    public List<VoucherItem> VoucherItems { get; set; } =
        new List<VoucherItem>
        {
           new VoucherItem { Description = "apple" },
           new VoucherItem { Description = "orange" }
        };
}

public class VoucherItem
{
    public string Description { get; set; }
}
```

Response (as expected)
```
{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 0.6931471,
    "hits" : [
      {
        "_index" : "receivemoneyvouchers",
        "_type" : "_doc",
        "_id" : "78550039-2151-487e-87cd-3083ac1f5436",
        "_score" : 0.6931471,
        "_source" : {
          "id" : "78550039-2151-487e-87cd-3083ac1f5436",
          "voucherItems" : [
            {
              "description" : "apple"
            },
            {
              "description" : "orange"
            }
          ]
        }
      }
    ]
  }
}
```

If you still experience issues, could you identify anything different you're doing in your code? Also, please [enable ](https://www.elastic.co/guide/en/elasticsearch/client/net-api/7.17/debug-mode.html) `DebugMode` as shown in the same above and collect the `DebugInformation` on your responses which may provide further clues.

**Comment by hesamdarbandi** [comment]
Thanks a lot @stevejgordon 

Could you Checkout this Please
 here is expecting a respond  Based on your query

```xml


{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 0.6931471,
    "hits" : [
      {
        "_index" : "receivemoneyvouchers",
        "_type" : "_doc",
        "_id" : "78550039-2151-487e-87cd-3083ac1f5436",
        "_score" : 0.6931471,
        "_source" : {
          "id" : "78550039-2151-487e-87cd-3083ac1f5436",
          "voucherItems" : [
            {
              "description" : "apple"
            }
          ]
        }
      }
    ]
  }
}


```

**Comment by stevejgordon** [comment]
@hesamdarbandi I'm not sure what you're asking exactly but will make an assumption is about the inclusion of "orange" in the array of `voucherItems` in the `_source` object? If so, the `_source` field will include any and all voucher items from the original document. No filtering is applied and it's purely the original JSON document that was indexed. In this case, the document had two voucher items, so both are part of the source document. A nested query allows you to query inside a nested object, but the result is the original root document(s) that match the query clauses.
