### ISSUE TITLE
Not able to access to Nest.Indices.Names

### ISSUE THREAD

**Issue by dliulabs** [elastic/elasticsearch-net#6145]
**NEST/Elasticsearch.Net version**: 7.17.0

**Elasticsearch version**: 

**.NET runtime version**: 7.17.0

**Operating system version**:

**Description of the problem including expected versus actual behavior**:
I am doing a GetRole:

var getRoleResponse = client.Security.GetRole("a_role");

After that, trying to list the names in the indices, but there does not appear an accessor to get to the list of names.

KeyValuePair<string, Nest.XPackRole> role = getRoleResponse.Roles.ElementAt(0);

IndicesPrivileges index = (IndicesPrivileges) role.Value.Indices.ElementAt(0);

var a_name  = index.Names[0];

**Steps to reproduce**:

Console.WriteLine(index.Names);  // failed

Newtonsoft.Json.JsonConvert.SerializeObject(getRoleResponse.Roles); // failed to show Names
 

**Expected behavior**

There should be a way to access to the results at the High Level Client

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by stevejgordon** [comment]
Hi, @dliulabs,

`Roles` on the response is a dictionary. so you can first access the specific role by its name. Each role then has an array of index permission entries. You could use LINQ to access all `Indices` from all of the entries. Once you have the `Indices` you can iterate over them and extract the individual names. In this case, `Indices` is a special union type so it's a little complicated to work with. The easiest option, for now, is to use its `Match` method to handle the union cases. See the example below which adds the values to a list.

This does highlight a usability issue on this response that I'll flag and look to improve in v8 if possible. 

```c#
var role = getRoleResponse.Roles["a_role"]; // Access the role by name

var indices = role.Indices.Select(i => i.Names);

var indexNames = new List<string>();
foreach(var index in indices)
{
	var names = index.Match(all => new[] { "_all" }, many => many.Indices.Select(index => index.Name).ToArray());
	indexNames.AddRange(names);
}
```

**Comment by dliulabs** [comment]
@stevejgordon,

Thank you, yes, this helps.

If we have an accessor function such as this:

`public static IEnumerable<string[]> IndexNames(this IReadOnlyCollection<Nest.IIndicesPrivileges> p)
 => p
    .Select(i => i.Names)
    .Select( index => index
    .Match(
            all => new[] { "_all" }, 
            many => many.Indices.Select(index => index.Name).ToArray()
        )
    );`
    
  then it is possible to do something like this:
  
  `role.Indices.IndexNames()`
