### ISSUE TITLE
NEST 8 nuget package ?

### ISSUE THREAD

**Issue by agonzalezm** [elastic/elasticsearch-net#6146]
Elastic 8 was released few weeks ago and documentation is up for NEST 8, but there is no nuget package for NEST 8, last version is 7.17. When is nuget NEST 8 going to be available?

**Comment by stevejgordon** [comment]
Hi @agonzalezm. We are working on a new client that is being released under a new package name. At this time, it's an early alpha with limited API support. We will be releasing more alphas ASAP. In the meantime, you can continue to use the 7.17.x client against a v8 server. Please see this [short guide](https://www.elastic.co/guide/en/elasticsearch/client/net-api/7.17/connecting-to-elasticsearch-v8.html) that covers the steps required to configure the client using the new CA fingerprint information. Please let me know if that helps you get started.

**Comment by stevejgordon** [comment]
Closing as answered.

**Comment by agonzalezm** [comment]
the new 8.x client is not compatible with NEST? it requires migration of lot of code and retesting of all code, why it breaks everything? is NEST support for how long before we need to migrate to new client?

**Comment by LordMike** [comment]
I would start here: #7624

**Comment by flobernd** [comment]
@agonzalezm This is correct, the upgrade from NEST -> v8 contains breaking changes. You can read more about the reasons for this here:

https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/migration-guide.html

NEST compatibility mode can be used to connect to Elasticsearch 8.* servers, but you won't be able to use the new features. There is no day X at which NEST suddenly stops working, but I would recommend to prepare for an update anyways.

My personal recommendation: Use NEST and the v8 client side-by-side in your project and start migrating the code that is supported by the v8 client. Some features are not implemented yet, but for these you can fall back to NEST for now.
