### ISSUE TITLE
Support copy_from parameter in SetProcessor

### ISSUE THREAD

**Issue by mpwoz** [elastic/elasticsearch-net#6147]
**Is your feature request related to a problem? Please describe.**
Set processors (in ingest pipelines) are more efficient than scripts if you want to just copy one field's value to another. However, to do this you need the `copy_from` parameter which Nest currently does not support in its SetProcessor as of 7.17

- Official docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/set-processor.html
- Nest SetProcessor https://github.com/elastic/elasticsearch-net/blob/7.17/src/Nest/Ingest/Processors/SetProcessor.cs

**Describe the solution you'd like**
Nest would add the `CopyFrom` property to `SetProcessor`

**Describe alternatives you've considered**
We're currently using scripts to accomplish the same thing. However, for a simple copy from one field to another a Set processor would be more efficient and not require error-prone Painless language scripts embedded in our code.

Thank you for taking a look! Please let me know if I can provide any additional details.

**Comment by stevejgordon** [comment]
Thanks for raising this @mpwoz. Will look to get this added and into the next patch release.

**Comment by stevejgordon** [comment]
@mpwoz I have merged a PR that adds this missing property and this will ship in the next release `7.17.2`.

**Comment by stevejgordon** [comment]
@mpwoz 7.17.2 has shipped with this fix.
