### ISSUE TITLE
Invalid NEST response built from a unsuccessful 

### ISSUE THREAD

**Issue by shuangbaojun** [elastic/elasticsearch-net#6148]
**The sample code is as follows:**

           var settings = new ConnectionSettings(new Uri("https://xx.xx.xxx.xxx:9200"))
                                .BasicAuthentication("elastic", "0fjaNokbmHSeS4kXeFV")
                                .DefaultIndex("people")
                                .RequestTimeout(TimeSpan.FromSeconds(300));

            var client = new ElasticClient(settings);

            var person = new Person
            {
                Id = 1,
                FirstName = "Martijn",
                LastName = "Laarman"
            };

            var indexResponse = client.IndexDocument(person);

            if (!indexResponse.IsValid)
            {
                var debugInfo = indexResponse.DebugInformation;
                var error = indexResponse.OriginalException;
            }

**environment：**
1、ElasticSearch 8.0.1
2、NEST 7.17.0
3、NET 6.0

**ps：**
Entering the account number and password through https://xx.xx.xxx.xxx:9200 can be accessed, but it cannot be accessed through the .net client, and the package error is as follows

**The stack information is as follows:**

Invalid NEST response built from a unsuccessful () low level call on PUT: /people/_doc/1
# Audit trail of this API call:
 - [1] ProductCheckOnStartup: Took: 00:00:00.6003806
 - [2] ProductCheckFailure: Node: https://xx.xx.xxx.xxx:9200/ Took: 00:00:00.5720633
# OriginalException: Elasticsearch.Net.ElasticsearchClientException: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product. Call: Status code unknown from: GET /
 ---> Elasticsearch.Net.PipelineException: The client is unable to verify that the server is Elasticsearch due to an unsuccessful product check call. Some functionality may not be compatible if the server is running an unsupported product.
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch, RemoteCertificateChainErrors
   at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
   at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Elasticsearch.Net.HttpConnection.Request[TResponse](RequestData requestData)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.RequestPipeline.ThrowIfTransientProductCheckFailure()
   at Elasticsearch.Net.RequestPipeline.Ping(Node node)
   at Elasticsearch.Net.Transport`1.Ping(IRequestPipeline pipeline, Node node)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
# Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# Response:
<Response stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>

**Comment by Sen-Gupta** [comment]
We are facing the exact issue! NEST Client 17.7.0 and Elastic    "number" : "7.13.2"!

Shall we upgrade our Elastic?

**Comment by Sen-Gupta** [comment]
We updated the Elastic 8 and still no luck!

**Comment by stevejgordon** [comment]
@shuangbaojun and @Sen-Gupta - The most likely cause when communicating with Elasticsearch 8.0 is that the server now starts with security enabled and HTTPS using a self-signed certificate in use by default. I have just added a [short guide](https://www.elastic.co/guide/en/elasticsearch/client/net-api/7.17/connecting-to-elasticsearch-v8.html) that covers the steps required to configure the client using the new CA fingerprint information. Please let me know if that helps you get started.

**Comment by shuangbaojun** [comment]
@stevejgordon  hi，Thanks for the answer, as you said above, is there a demo for this?

**Comment by stevejgordon** [comment]
@shuangbaojun A demo for retrieving the CA fingerprint? The client doc links to an [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/8.1/configuring-stack-security.html#_connect_clients_to_elasticsearch_5) page which provides the command you can issue to retrieve the fingerprint.

**Comment by stevejgordon** [comment]
Closing this as answered and addressed with the documentation update.

**Comment by sergiufilip** [comment]
Hi, 
I am literally pulling my hair with a similar issue, and I don't seem to be able to fix it nor work around it. I'll keep it short:
Single node ES **v.7.16.2** | NEST 7.17 | plain http://, no TLS | also using the low-level client, in the same process - no problem.

NEST fails with this error above, I turned on  _EnableDegbugMode()_ and turns out that nest is always trying to connect to **localhost.** . _No connection could be made because the target machine actively refused it 127.0.0.1:9200_

Please help.

@stevejgordon big thank you; lots of hope for the future of this library since you joined the team and **kudos !** - your content on Pluralsight is top-notch sir.

**Comment by BacClunky** [comment]
> @shuangbaojun and @Sen-Gupta - The most likely cause when communicating with Elasticsearch 8.0 is that the server now starts with security enabled and HTTPS using a self-signed certificate in use by default. I have just added a [short guide](https://www.elastic.co/guide/en/elasticsearch/client/net-api/7.17/connecting-to-elasticsearch-v8.html) that covers the steps required to configure the client using the new CA fingerprint information. Please let me know if that helps you get started.

Hi @stevejgordon ,

I followed your steps but I still did not make it work. (Error message: Invalid NEST response built from a unsuccessful () low level call on PUT: /platforms/_doc/1)

            var pool = new SingleNodeConnectionPool(new Uri("https://localhost:9200"));

            var settings = new ConnectionSettings(pool)
                .DefaultIndex(defaultIndex)
                .CertificateFingerprint("94:75:CE:4F:EB:05:32:83:40:B8:18:BB:79:01:7B:E0:F0:B6:C3:01:57:DB:4D:F5:D8:B8:A6:BA:BD:6D:C5:C4")
                .BasicAuthentication("elastic", "8kLqbRV00677W75Dm6anDbP0")
                .EnableApiVersioningHeader();

            AddDefaultMapping(settings);

            var client = new ElasticClient(settings);

            services.AddSingleton<IElasticClient>(client);

And I can browse Elastic normally
![image](https://user-images.githubusercontent.com/3404299/183919229-7a1e3291-8e3f-4fff-acfd-9e3ce1107fd2.png)

Is there anything I missed?

Thank you,

**Comment by stevejgordon** [comment]
Hi @BacClunky. You need to pass in the `CertificateFingerprint` value for your server instance. You can retrieve that from your server. This [part of the v8 client guide](https://www.elastic.co/guide/en/elasticsearch/client/net-api/8.4/connecting.html#single-node) provides some details for that.

**Comment by swapnaram-bandaru** [comment]
I have exact same error using Single Node, got Certificate Fingerprint from server , connecting via the basic authentication username , password and certificate fingerprint. However no issues browsing to the endpoint (certificate is valid)

**Comment by ajaythakor** [comment]
@flobernd Can you tell me the solution? What should I do to resolve the issue?

**Comment by ajaythakor** [comment]
I appreciate the quick response.

**Comment by flobernd** [comment]
@ajaythakor I see that you are using a `localhost` url. In this case it's probably easiest to simply not use SSL (use `http` instead of `https`).

**Comment by ajaythakor** [comment]
@flobernd I have installed the elasticsearch in docker, and it has generated the https URL by default.
If there is a way to change it I can change and retry.

**Comment by flobernd** [comment]
@ajaythakor I'm sorry but I can not answer this question as I'm not using the Elasticsearch docker container. Your question is not related to the client, but rather about general usage of the Elasticsearch server. 

Could you please ask this question in the [elasticsearch (server)](https://github.com/elastic/elasticsearch) repository - or even better, contact the support? I'm sure there are as well plenty sources available that show how to either copy the certificate from the docker container to your local machine and add it to the trust store or how to disable SSL (not recommended for production usage of course).
