### ISSUE TITLE
Cannot add Pipeline in the ReindexOnServer method

### ISSUE THREAD

**Issue by kplazinski** [elastic/elasticsearch-net#6151]
**NEST/Elasticsearch.Net version**: 7.16.0

**Elasticsearch version**: 7.16.3

**Description of the problem including expected versus actual behavior**:
When using the `ReindexOnServer()` method there is no way to add `Pipeline`, because it ends with error:
`unknown field [Pipeline] did you mean [pipeline]?`. 

Probably it's because there is no `[DataMember]` attribute on the `Pipeline` property in the `IReindexDestination`

**Steps to reproduce**:
 1. Create ReindexOnServer request
 2. Add any pipeline to the destination's descriptor

**Comment by stevejgordon** [comment]
Thanks for raising this @kplazinski. I suspect you are correct. I'll get this fixed and into the next patch release.

**Comment by stevejgordon** [comment]
@kplazinski 7.17.2 has shipped with this fix.
