### ISSUE TITLE
Deprecated `Size` on Reindex request

### ISSUE THREAD

**Issue by plachor** [elastic/elasticsearch-net#6152]
**NEST/Elasticsearch.Net version**: 7.17

**Description of the problem including expected versus actual behavior**:
I wish to control how many documents will be reindexed in single batch in conjunction with `requests_per_second`. According to docs I should use `size`. However Nest API claims `size` is depreciated and that I should use `max_docs` instead ([**link to code**](https://github.com/elastic/elasticsearch-net/blob/7.17/src/Nest/Document/Multiple/ReindexOnServer/ReindexOnServerRequest.cs#L48))

In documentation however description of `max_docs` is confusing ([**link to documentation**](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/docs-reindex.html#docs-reindex-api-request-body)):
> **max_docs**
> (Optional, integer) The maximum number of documents to reindex. If [conflicts](https://www.elastic.co/guide/en/elasticsearch/reference/8.1/docs-reindex.html#conflicts) is equal to proceed, reindex could attempt to reindex more documents from the source than max_docs until it has successfully indexed max_docs documents into the target, or it has gone through every document in the source query.

Again for `size` docs state:
> **size**
> {Optional, integer) The number of documents to index per batch. Use when indexing from remote to ensure that the batches fit within the on-heap buffer, which defaults to a maximum size of 100 MB. 

Is that `Obsolete` valid in that case ?

**Comment by stevejgordon** [comment]
Hi @plachor.

The `Size` deprecation refers to a historic field on the top-level request body which is no longer recommended for use. I believe the confusion here is that a `size` field exists inside the `source` object. For controlling the size of the reindex batches, that is the correct setting to use.

`MaximumDocuments` is a distinct option on the request body to control the total number of successful documents (non-conflicting) that should be reindexed. If set to 1 for example, only a single document would be reindexed from the source to the destination. This field used to be named `Size`.

Does that help clarify things? If not, you may want to consider posting a query on the [community forum](https://discuss.elastic.co/) for more general advice on settings to use for reindex requests.

**Comment by plachor** [comment]
Hi @stevejgordon, thnx for response. 

So when I use `IElasticClient.ReindexOnServerAsync` with `ReindexOnServerDescriptor` callback there is a method `Size` marked with this obsolete. 

 ```csharp
elasticClient.ReindexOnServerAsync(z => z
    .Source(x => x
        .Index(..)
        .Query<object>(q => q.Raw(query)))
        .RequestsPerSecond(..)
        .Size(..)   // <-- this one is depreciated 
    .Destination(x => x.Index(..))
    .WaitForCompletion(false));
 ```
 
 Is that method setting actually size of batch?

**Comment by stevejgordon** [comment]
@plachor No, that method is obsolete and is the old name for `MaximumDocuments`. To set the batch size, use the `Size` property on the source. Your indentation is slightly off:

```c#
client.ReindexOnServerAsync(z => z
.Source(x => x
   .Index("b")
   .Query<object>(q => q.Raw(""))
   .Size(1)) // <-- this one sets the batch size
.RequestsPerSecond(10)
//.Size(1)   // <-- this one is depreciated (old name for MaximumDocument)
.Destination(x => x.Index("a"))
.WaitForCompletion(false));
```

**Comment by plachor** [comment]
Thanks for clarification and help.
