### ISSUE TITLE
Only one of dozens of log indexes won’t rollover: “source alias does not exist”

### ISSUE THREAD

**Issue by tdoman** [elastic/elasticsearch-net#6155]
I put all the details in Elastic community discussion group but I think that if I'm gonna get an answer, I need to log it here:
https://discuss.elastic.co/t/only-one-of-dozens-of-log-indexes-wont-rollover-source-alias-does-not-exist/299673

**Comment by stevejgordon** [comment]
@tdoman I think the forums are the best place for this initially, as this doesn't immediately sound like a bug. I've responded there and will close this for now. We can reopen if we can trace the problem to being specific to the client.
