### ISSUE TITLE
API for adding documents to index with optional Id

### ISSUE THREAD

**Issue by stivx0** [elastic/elasticsearch-net#6160]
**Is your feature request related to a problem? Please describe.**
I am trying to add document to index using method like СreateAsync, CreateDocumentAsync and etc, but all of them require Id as a mandatory parameter for query.
However Elasticsearch API has a way to index document using autogenerated ID (https://www.elastic.co/guide/en/elasticsearch/reference/7.11/docs-index_.html).

I don't need my own ID because data is just logs and I would not like to implement mechanisms to avoid ID duplication when hundreds of clients will add data to index simultaneously.

**Describe the solution you'd like**
I would like to have overloaded methods which will allow me to not specify Id. It should use Elastic API **"POST /\<target\>/_doc/"**
ElasticClient.Create
ElasticClient.CreateAsync
ElasticClient.CreateDocument
ElasticClient.CreateDocumentAsync
ElasticClient.Index
ElasticClient.IndexAsync

**Describe alternatives you've considered**
I have found a workaround using ElasticLowLevelClient, but it not convenient and looks like hack.

**Comment by stevejgordon** [comment]
Hi, @stivx0.

The `Create*` methods map one-to-one with the create API on the server which explicitly requires an ID to be provided. Generally, you want to use the `Index*` methods which do not require an ID in the path.

If you've configured your client with a default index or a mapping for a type, you can use `IndexDocumentAsync`.

```c#
var client = new ElasticClient(new ConnectionSettings().DefaultMappingFor<Music>(m => m.IndexName("music")));
var doc = new Music { Name = "TEST" };
var indexResponse = await client.IndexDocumentAsync(doc);
```

If you prefer to provide the index name on the request directly you can use `IndexAsync`

```c#
var client = new ElasticClient();
var doc = new Music { Name = "TEST" };
var indexResponse = client.IndexAsync(doc, i => i.Index("music"));
```

Does that help?

**Comment by stivx0** [comment]
Thanks a lot, that works!
I have seen PUT in description "**PUT** request to the index API, read more about this API online" and unfortunatelly even have not tried to test it.
