### ISSUE TITLE
Bulk-Update with partial document sets wrong $type

### ISSUE THREAD

**Issue by neox2811** [elastic/elasticsearch-net#6164]
NEST/Elasticsearch.Net version: 7.17.0

Elasticsearch version: 8.0.1

.NET runtime version: 6.0.201

Operating system version: Ubuntu 18.04.

**Description of the problem including expected versus actual behavior**:
I want to (partial) update multiple existing documents but the $type of my document gets changed with the update operation. 

I want to add items to the List, without loading the whole doument from the index.

My Main-Object
```
public class MyClass
{
    public Guid Id { get; set; }
    public int Prop1 { get; set; }
    public string Prop2 { get; set; }
    public List<MyClassList> List { get; set; } = new();
}
```

My Sub-Object
```
public class MyClassList
{
    public Guid Id { get; set; }
    public int Prop1 { get; set; }
    public string Prop2 { get; set; }
}
```

C# Update Code
```
var des = new BulkDescriptor();
foreach (var item in itemList)
{
    des.Update<MyClass, object>(a => a
         .Index("myindex)
         .Id(item.Id)
          .Doc(new { List = new List<MyClassList> { item } })
          );
}
var bulkres = await client.BulkAsync(des);
```

Generated Elasticsearch Request
```
POST /_bulk
{"update":{"_id":"7b1c99bc-f6c6-42fa-9d29-e2739fd84186","_index":"myindex"}}
{"doc":{"$type":"<>f__AnonymousType1`1[[System.Collections.Generic.List`1[[MyClassList]], System.Private.CoreLib]]","list":{"$type":"System.Collections.Generic.List`1[[MyClassList]], System.Private.CoreLib","$values":[{"$type":"MyClassList","id":45,"prop1":7,"prop2":"t"}]}}}
```

Expected Request - without changing the $type Field (works, when I send it via query console, the main document is not changes, only the new item is added to the list)
```
POST /_bulk
{"update":{"_id":"57be0116-4c88-44c2-b14f-cb3f7f7d9e76","_index":"myindex"}}
{"doc":{"list":{"$type":"System.Collections.Generic.List`1[[MyClassList]], System.Private.CoreLib","$values":[{"$type":"MyClassList","id":45,"prop1":7,"prop2":"t"}]}}}
```

**Comment by stevejgordon** [comment]
@neox2811 It looks like you're using custom serialization with a contract resolver that is adding the type name to the serialized document. In your case, this is causing the type information for your anonymous object to be included in the serialised payload for the update. Is that the case? If so, you will need to handle that in your JSON serialisation or perhaps consider looking at whether you can achieve your desired result using an update by script.

**Comment by neox2811** [comment]
Yes, I was using a custom serializer. Thanks for the reply. In the meantime I removed the custom serializer I used mostly for covariant searches. Without the serializer partial updates are working as expected. 

Now I have to perform a typed search query (search<MyDocument>) for every index I want to search and merge the results together after mapping. Is there any better solution to search different indices in one search query and map the results in the dotnet objects?

**Comment by stevejgordon** [comment]
@neox2811 I'm glad to read that you got it working for the updates. It would be best to take specific questions over to the [forums](https://discuss.elastic.co/tag/language-clients) please as more people can assist with answering and also the community can benefit better from past questions and answers. We try to reserve the issues here to bugs and feature requests.

**Comment by stevejgordon** [comment]
Closing based on the previous comment.
