### ISSUE TITLE
Update stale examples in the documentation

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#621]
To avoid further confusion as seen here:

https://github.com/elasticsearch/elasticsearch-net/issues/611

and couple of other issues.

Look into the [scribble project](https://github.com/shiftkey/scribble) that @shiftkey started which can scan the source code (i.e tests) for snippets while generating docs. Last I looked at it was a bit too powershell oriented and my powershell-fu is lacking.

**Comment by Mpdreamz** [comment]
We are working on combining roslyn based literate programming, unit and integration testing all in a single for our `2.0` architecture.

This will solve the stale code in documentation because all the code in the documentation will be actual code :)

**Comment by tkirill** [comment]
> We are working on combining roslyn based literate programming, unit and integration testing all in a single project for our 2.0 architecture.

@Mpdreamz Could you give a link to this combination in code of NEST?  I can't find anything like this in docs directory in branch "2.0".  It is interesting especially literate programming with Roslyn but I can't find it in Google.

**Comment by Mpdreamz** [comment]
For now much of it lives here:

https://github.com/elastic/elasticsearch-net/tree/spike/literate-tests/src/Tests/Nest.Tests.Literate

With the actual tooling going over our tests generating documentation from the markdown comments here:

https://github.com/elastic/elasticsearch-net/tree/spike/literate-tests/src/CodeGeneration/Nest.Litterateur

We spiked the whole feedback loop and will move on this sooner then later (and blog about it of course :))
