### ISSUE TITLE
Multiple NEST clients in a solution throws ReflectionTypeLoadException exception

### ISSUE THREAD

**Issue by tavisca-dhruvpanchal** [elastic/elasticsearch-net#6256]
**NEST/Elasticsearch.Net version**: 7.17.0

**Elasticsearch version**: 7.17.1

**.NET runtime version**: >.NET core 3.1

**Operating system version**: Windows 10 Enterprise 64bit, OS build 19043.1586

**Description of the problem including expected versus actual behavior**:
We have a project which is currently using Elasticsearch 2.3.3 (NEST 5.5.0, ElasticSearch.NET 5.5.0)
We want to upgrade to Elasticsearch 7.17.1 with backward compatibility with Elasticsearch 2.3.3. 

So, in a solution, we created two different projects, one is for ES2.3.3 and another for ES7.17.1. Both are using NEST 5.5.5 and NEST 7.17.0 respectively.

The project builds successfully, but at runtime, it throws following exception.

ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Nest.JsonNetSerializer' from assembly 'Nest, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'.
Could not load type 'Nest.IBulkResponse' from assembly 'Nest, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'.
Could not load type 'Nest.ICountResponse' from assembly 'Nest, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'.
Could not load type 'Nest.IDeleteResponse' from assembly 'Nest, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'.
Could not load type 'Nest.IClusterHealthResponse' from assembly 'Nest, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'.
Could not load type 'Nest.IIndexResponse' from assembly 'Nest, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'.
Could not load type 'Nest.IPutMappingResponse' from assembly 'Nest, Version=7.0.0.0, Culture=neutral, PublicKeyToken=96c599bbe3e70f5d'

**Steps to reproduce**:
 1. Create a solution with two projects, one reference to NEST 5.5.0 and another to NEST 7.17.0
 2. Add at least one class in both projects which use at least one NEST library class, i.e., NEST.JsonNetSerializer
 3. Refer both these projects to one executable project, such as console application and initialize both classes of it. (Refering both projects in one project, and initializing the classes, is necessary to reproduce the error)
 4. Build and run the solution, it will throw the ReflectionTypeLoadException.

**Expected behavior**
As, both the projects are not dependent on each other, and using different NEST clients, It should run the project.

**Comment by stevejgordon** [comment]
Hi, @tavisca-dhruvpanchal. Although each of your libraries uses a different NEST version, when you reference those libraries in a common console app, such exceptions are to be expected. Your console application has transitive dependencies on two different versions of the same library and it cannot resolve both.

To achieve your goal, you can [follow this historic blog](https://www.elastic.co/blog/nest-and-elasticsearch-net-upgrading-your-codebase) on migrating which includes details of how to use our versioned packages to support migration. Note, that this is recommended as a relatively short term solution in support of a full server upgrade.

We stopped publishing packages to AppVeyor around 7.6, so you may need to use our newer feed `https://f.feedz.io/elastic/all/nuget/index.json` instead.

**Comment by tavisca-dhruvpanchal** [comment]
@stevejgordon I have tried this approach. This will work as the short term solution. Thank you.
