### ISSUE TITLE
Version 6.x: Wrong JsonProperty name on AnalyzeToken. Expecting position_length when it should be positionLength

### ISSUE THREAD

**Issue by Ferran54** [elastic/elasticsearch-net#6258]
**NEST/Elasticsearch.Net version**: 6.8.10
**Elasticsearch version**: 6.8

**Description of the problem including expected versus actual behavior**:
JsonProperty name is wrong
https://github.com/elastic/elasticsearch-net/blob/0aaf7c76fe24df9ca1d23df6c99256af005fecc8/src/Nest/Indices/Analyze/AnalyzeToken.cs#L14

![analyzerresponse](https://user-images.githubusercontent.com/25817096/162190198-db4988dd-e82b-495a-9510-7f98b434cd82.PNG)

The Eastic api is returning **positionLength** and NEst is expecting **position_length** so, NEst can't serialize the response properly and always return that null

**Steps to reproduce**:
 1.  call AnalyzeAsync on NEST 
 2. observe results are always returning PositionLength = null

**Expected behavior**
PositionLenght should be the same that is returned by the Elastic Analyzer api

**Comment by stevejgordon** [comment]
Thanks for raising this and the PR to fix it @Ferran54. I have merged the PR and this morning I released `6.8.11` which includes your contribution.
