### ISSUE TITLE
ValueAggregate should have GetDate() or ValueAsDate

### ISSUE THREAD

**Issue by DR9885** [elastic/elasticsearch-net#6266]
**Is your feature request related to a problem? Please describe.**
ValueAggregate doesn't have option to read date

``` 
	public class ValueAggregate : MetricAggregateBase
	{
		public double? Value { get; set; }

		public string ValueAsString { get; set; }
	}
```

**Describe the solution you'd like**
``` 
public static class ElasticExtensions
{
    private static readonly CultureInfo Culture = CultureInfo.InvariantCulture;
    private const string DateFormat = "yyyy-MM-ddTHH:mm:ss.fffZ";
    public static DateTime GetDate(this ValueAggregate agg)
    {
        var str = agg.ValueAsString;
        var date = str == null? DateTime.MinValue: DateTime.ParseExact(str, DateFormat, Culture);
        return date;
    }
}
```
or this:
```
	public class ValueAggregate : MetricAggregateBase
	{
		public double? Value { get; set; }

		public string ValueAsString { get; set; }

		public DateTime? ValueAsDate { get; set; }
	}
```

**Describe alternatives you've considered**
Using this extension for now

**Additional context**
Would also be nice to include other formats: decimal, int, long, etc...

**Comment by DR9885** [comment]
@stevejgordon, currently we Aggregate MAX DateTime, to figure out what is the latest update to all models. then I check to see if there are any newer changes we need to update in elastic.

**Comment by stevejgordon** [comment]
Thanks for providing that use case @DR9885. Thanks for raising the suggestion, but I don't think this is common enough that it warrants inclusion in the client. Adding such methods will likely be more confusing for the majority cases where the data is generally numeric. The response type exposes the values sent by the server and I think it's best left as an application concern how to parse and use those for the application specific requirement. On that basis, I'll close this issue.
