### ISSUE TITLE
NEST client is failing to Index documents larger than 700MB

### ISSUE THREAD

**Issue by EVINDX** [elastic/elasticsearch-net#6406]
**NEST/Elasticsearch.Net version**: 7.14.1

**Elasticsearch version**: 7.14.1

**.NET runtime version**: 4.8

**Operating system version**: Windows Server 2016

**Description of the problem including expected versus actual behavior**:
NEST client is failing to Index documents larger than 700MB with System.ArgumentOutOfRangeException exception

**Expected behavior**
Should successfully index 1GB document as Lucene Index/Elasticsearch shard is capable of Indexing till 2GB per document

**Stack trace**:
System.ArgumentOutOfRangeException: Too many characters. The resulting number of bytes is larger than what can be returned as an int.|
Parameter name: charCount|
   at System.Text.UTF8Encoding.GetMaxByteCount(Int32 charCount)|
   at Elasticsearch.Net.Utf8Json.JsonWriter.WriteString(String value)|
   at Elasticsearch.Net.Utf8Json.Formatters.NullableStringArrayFormatter.Serialize(JsonWriter& writer, String[] value, IJsonFormatterResolver formatterResolver)|
   at Serialize(Byte[][] , Object[] , JsonWriter& , <object name here> , IJsonFormatterResolver )|
   at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Serialize(JsonWriter& writer, T value, IJsonFormatterResolver formatterResolver)|
   --- End of inner exception stack trace ---|

**Observation**:
While serializing the input document represented by POCO using Utf8Json, a call(System.Text.UTF8Encoding.GetMaxByteCount) is made to calculate the max number of bytes that will be produced after encoding the characters
where the estimate representing that max count roughly assumes the value of input length times 3 (as code points from the basic multilingual plane will be encoded to 1-3 bytes) and is finally made to throw an ArgumentOutOfRangeException exception if the value is larger than 0x7fffffff(2GB) thus the overall call will fail if we are focusing on anything larger than 2GB/3(~680MB).(https://github.com/microsoft/referencesource/blob/master/mscorlib/system/text/utf8encoding.cs). Is there any way to deal with documents larger than 680MB with the Elasticsearch .NET client?

**Comment by stevejgordon** [comment]
Hi, @EVINDX. This is unfortunately a limitation in the encoding API the serialization path relies on, which is limited to returning a max size of int.MaxValue as the length. Please see #5172 which also details the same limitation. There are some links there for guidance on splitting large data into multiple documents. 

For 7.x, I don't think there's anything we can practically do to enable this scenario. A potential workaround you could attempt is to implement and [register your own source serializer](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html) where you can fully control how the data is serialized. For v8 we're moving to depend on `System.Text.Json` which may avoid this limitation, although I've yet to test that capability.

**Comment by EVINDX** [comment]
Hi, @stevejgordon. Thank you for the clarification, we will explore these options and take favorable action accordingly.
