### ISSUE TITLE
Memory leak with BulkAll

### ISSUE THREAD

**Issue by NicolaiJee** [elastic/elasticsearch-net#6443]
**NEST/Elasticsearch.Net version**: 7.17.2

**Elasticsearch version**: Elastic Cloud newest version

**.NET runtime version**: .net core 6

**Operating system version**: Azure

**Description of the problem including expected versus actual behavior**:
I have a service that updates 3.8 million addresses on a regular basis.

My code looks like this:
` int totalRows = 0;
                var addresses = (await _dataContext.Addresses.AsNoTracking().Where(m => m.Updated >= since).ToListAsync(cancellationToken)).Select(m => new ElasticAddressModel(m));
                performContext.WriteLine($"Found {addresses.Count()} addresses");

                var requests = 0;
                var tokenSource = new CancellationTokenSource();
                var bulkResponses = new ConcurrentBag<BulkResponse>();
                var bulkAllResponses = new ConcurrentBag<BulkAllResponse>();
                var deadLetterQueue = new ConcurrentBag<ElasticAddressModel>();
                var numberOfAdresses = addresses.Count();
                if (numberOfAdresses > 0)
                {
                    var bulkAllObservable = _elasticClient.BulkAll(addresses, b => b
                    .MaxDegreeOfParallelism(1)
                    .BulkResponseCallback(r =>
                    {
                        bulkResponses.Add(r);
                        Interlocked.Increment(ref requests);
                    })
                    .ContinueAfterDroppedDocuments()
                    .DroppedDocumentCallback((r, o) => deadLetterQueue.Add(o))
                    .BackOffTime(TimeSpan.FromMilliseconds(1))
                    .Size(1000)
                    .RefreshOnCompleted()
                    .Index(AddressesIndexName)
                    .BufferToBulk((r, buffer) => r.IndexMany(buffer))
                , tokenSource.Token)

                    .Wait(TimeSpan.FromMinutes(15), next =>
                    {
                        totalRows = totalRows + next.Items.Count;
                        performContext.WriteLine(ConsoleTextColor.Green, $"{totalRows} of {numberOfAdresses}");
                    });
                }`
When I deploy the service to Azure I can see that memory keeps going up until the APP crashes with an Out of memory Exception.
I can also see the same thing on my development machine, it just has more memory so I doesn't crash.

The out of memory exception looks like this:
`Elasticsearch.Net.UnexpectedElasticsearchClientException: Exception of type 'System.OutOfMemoryException' was thrown. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown. at Nest.NestFormatterResolver.InnerResolver.GetFormatter[T]() at Nest.NestFormatterResolver.GetFormatter[T]() at Nest.BulkResponseItemFormatter.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver) at Elasticsearch.Net.Utf8Json.Formatters.CollectionFormatterBase`4.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver) at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver ) at Elasticsearch.Net.Utf8Json.Resolvers.DynamicMethodAnonymousFormatter`1.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver) at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver) at Elasticsearch.Net.Utf8Json.JsonSerializer.DeserializeAsync[T](Stream stream, IJsonFormatterResolver resolver) at Elasticsearch.Net.ResponseBuilder.SetBodyAsync[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType, CancellationToken cancellationToken) at Elasticsearch.Net.ResponseBuilder.ToResponseAsync[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String productName, String mimeType, CancellationToken cancellationToken) at Elasticsearch.Net.HttpConnection.RequestAsync[TResponse](RequestData requestData, CancellationToken cancellationToken) at Elasticsearch.Net.RequestPipeline.CallElasticsearchAsync[TResponse](RequestData requestData, CancellationToken cancellationToken) at Elasticsearch.Net.Transport`1.RequestAsync[TResponse](HttpMethod method, String path, CancellationToken cancellationToken, PostData data, IRequestParameters requestParameters) --- End of inner exception stack trace --- at Nest.BlockingSubscribeExtensions.WaitOnObservable[TObservable,TObserve,TObserver](TObservable observable, TimeSpan maximumRunTime, Func`3 factory) at Nest.BlockingSubscribeExtensions.Wait[T](BulkAllObservable`1 observable, TimeSpan maximumRunTime, Action`1 onNext) at API.Helpers.ElasticSearchHelper.FullSync(DateTime since, PerformContext performContext, CancellationToken cancellationToken) in D:\a\1\s\src\API\Helpers\ElasticSearchHelper.cs:line 55`

Line 55 is this one:
 var bulkAllObservable = _elasticClient.BulkAll(addresses, b => b

**Comment by stevejgordon** [comment]
Hi, @NicolaiJee,

My first observation is that it appears you are pulling back 3.8 records from the database using EF in one single query. That's going to put a lot of objects into memory very quickly. After that, you have a transformation which will take each record and produce another object, once we start enumerating your data inside the bulk helper. Pulling so many records back in one hit is likely not helping the memory situation.

I'd recommend starting by capturing a heap dump during the crash and reviewing the allocated objects to identify which types are consuming the most memory. I'd then suggest checking their retention paths as well to see what's holding a reference to them. You may also want to profile the app during the bulk upload and take a few snapshots before it throws the OOM exception.

I'd also recommend reconsidering pulling all 3.8m records back in one go. Can you refactor this to bring back smaller sets of records at a time? That would likely relieve the memory pressure and allow the GC to hopefully keep up.

**Comment by NicolaiJee** [comment]
Hi @stevejgordon 

I found out that I sometimes got the Out of memory exception from the 3.8 mill records.
So i rewrote it and memory consumption looks much better and I can see that GC does it business.
Thanks :)

My rewritten code that may help someone else is just pagination.
Not elegant but it works.
`var query = _dataContext.Addresses.AsNoTracking().Where(m => m.Updated >= since);
                var numberOfAdresses = await query.CountAsync(cancellationToken);
                performContext.WriteLine($"Found {numberOfAdresses} addresses");

                var requests = 0;
                int totalRows = 0; 
                var tokenSource = new CancellationTokenSource();
                var bulkResponses = new ConcurrentBag<BulkResponse>();
                var bulkAllResponses = new ConcurrentBag<BulkAllResponse>();
                var deadLetterQueue = new ConcurrentBag<ElasticAddressModel>();
                if (numberOfAdresses > 0)
                {
                    //implement paging of results to prevent out of memory problems
                    var pageSize = 50000;
                    var pageCount = (double)numberOfAdresses / 50000;
                    pageCount = (int)Math.Ceiling(pageCount);

                    for (int page = 1; page <= pageCount; page++)
                    {
                        var skip = (page - 1) * pageSize;
                        performContext.WriteLine($"Page {page} of {pageCount}");
                        var addresses = (await query.Skip(skip).Take(pageSize).ToListAsync(cancellationToken)).Select(m => new ElasticAddressModel(m));

                        var bulkAllObservable = _elasticClient.BulkAll(addresses, b => b
                        .MaxDegreeOfParallelism(1)
                        //.BulkResponseCallback(r =>
                        //{
                        //    bulkResponses.Add(r);
                        //    Interlocked.Increment(ref requests);
                        //})
                        .ContinueAfterDroppedDocuments()
                        //.DroppedDocumentCallback((r, o) => deadLetterQueue.Add(o))
                        .BackOffTime(TimeSpan.FromMilliseconds(1))
                        .Size(10000)
                        .RefreshOnCompleted()
                        .Index(AddressesIndexName)
                        .BufferToBulk((r, buffer) => r.IndexMany(buffer))
                    , tokenSource.Token)

                        .Wait(TimeSpan.FromMinutes(15), next =>
                        {
                            totalRows = totalRows + next.Items.Count;
                            performContext.WriteLine(ConsoleTextColor.Green, $"{totalRows} of {numberOfAdresses}");
                        });
                    }
                }`
