### ISSUE TITLE
Feasibility to upsert the documents using Bulk operation

### ISSUE THREAD

**Issue by balukantu** [elastic/elasticsearch-net#6509]
Hi Team,

Is there a way to insert a document if the document doesn't exist or else update the document in Elasticsearch using BulkAll?

How can we handle not duplicating the records if we do the import twice?

**Comment by stevejgordon** [comment]
Hi @balukantu,

The best place to raise these questions is our community discuss forum where more people can contribute to an answer. We reserve issues for bugs and feature requests. There is an [existing question](https://discuss.elastic.co/t/please-explain-how-to-perform-a-bulk-update-with-partials-using-updatemany/183873) there which may help in your case.
