### ISSUE TITLE
MultiGetAsync<TDocument> returns 400 statuscode - unexpected token [START_OBJECT]

### ISSUE THREAD

**Issue by DanielFruerlund** [elastic/elasticsearch-net#6531]
Hi Team,

**NEST/Elasticsearch.Net version**: Elastic.Clients.Elasticsearch 8.0.0-beta.1

**Elasticsearch version**: 8.2.3

# Description of the problem:
When invoking the MultiGetAsync<TDocument> a status 400 is returned from the api.

Passing in a MultiGetRequestDescriptor or a MultiGetRequest with an array of ids, results in a request body that looks as follows: 
{"ids":{}}. 
My method call:
![image](https://user-images.githubusercontent.com/42201511/178938298-f5da07ba-a121-4424-8b55-91e435126452.png)

This is also the case when specifying each document to return. Here the request body created is: {"docs":{"_id":""}} and my method call: 
![image](https://user-images.githubusercontent.com/42201511/178938395-41d8c991-dba3-418d-9fc9-07fb5087a2b1.png)

According to the documentation both "docs" and "ids" should be an array. 

**docscumentation of mget**: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-get.html:

# Debug information: 
Elastic.Transport.TransportException: Request failed to execute. Call: Status code 400 from: POST /_mget?pretty=true&error_trace=true. ServerError: Type: parsing_exception Reason: "unexpected token [START_OBJECT], expected [FIELD_NAME] or [START_ARRAY]"

**Request:**
{"ids":{}}

**Response:**
{
  "error" : {
    "root_cause" : [
      {
        "type" : "parsing_exception",
        "reason" : "unexpected token [START_OBJECT], expected [FIELD_NAME] or [START_ARRAY]",
  },
  "status" : 400
}

**Comment by stevejgordon** [comment]
Thanks again @DanielFruerlund. The fixes to the code-generator and client are now merged and will be in beta 2. You can grab them sooner from our CI builds if you want to test further.

**CI Build Feed:** https://f.feedz.io/elastic/all/nuget/index.json
**Version:** 8.1.0-ci20220714T135329
