### ISSUE TITLE
Index Mappings: Geopoint Property Descriptor Script is missing

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#6555]
**NEST/Elasticsearch.Net version**: 7.17.4

**Elasticsearch version**: 7.17.4

**.NET runtime version**: .NET 6

**Operating system version**: macos

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
 1. Nest is missing GeoPoint Script support https://www.elastic.co/guide/en/elasticsearch/reference/current/geo-point.html#geo-point-params

**Expected behavior**

This should work
`.GeoPoint(g => g.Name(m => "geo").Script("BLAH"))`

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by stevejgordon** [comment]
This is now merged and will be released as part of `7.17.5`.
