### ISSUE TITLE
Adding max_analyzed_offset option for highlighting

### ISSUE THREAD

**Issue by catmanjan** [elastic/elasticsearch-net#6609]
**NEST/Elasticsearch.Net version**: 7.7.14

**Elasticsearch version**: 7.6.1

**.NET runtime version**: 6.0

**Operating system version**: Azure Web App

**Description of the problem including expected versus actual behavior**:
Same issue logged here https://github.com/elastic/elasticsearch-py/issues/1719

I have the following code:

```
var request = new SearchRequest<ElasticDocument>()
{
    Query = new BoolQuery()
    {
        Must = must,
        Should = should,
        MinimumShouldMatch = 1
    },
    Sort = sorts,
    From = from,
    Size = size,
    Highlight = new Highlight()
    {
        NumberOfFragments = 1,
        Order = HighlighterOrder.Score,
        Fields = new Dictionary<Field, IHighlightField>()
        {
            [Infer.Field<ElasticDocument>(f => f.Body)] = new HighlightField()
        },
        PreTags = new[] { "<b>" },
        PostTags = new[] { "</b>" },
        NoMatchSize = 100,
        MaxAnalyzedOffset = 1000000
    },
};
```

Which triggers the error:

```
"Request failed to execute. Call: Status code 400 from: POST /document/_search?typed_keys=true. ServerError: Type: x_content_parse_exception Reason: \"[1:45] [highlight] unknown field [max_analyzed_offset]\""
```

**Expected behavior**
Highlighting works with no error for long documents

**Comment by stevejgordon** [comment]
Hi @catmanjan. The `max_analyzed_offset` options was not [added](https://github.com/elastic/elasticsearch/pull/67325) until Elasticsearch 7.12 and is not supported on the version you are using. This error from the server is therefore accurate and expected. To support using this feature, you would need to upgrade your cluster. I'll close this issue on that basis as this appears not to be a fault with the client.
