### ISSUE TITLE
ES fails to read TEMP folder path containing special character

### ISSUE THREAD

**Issue by EVINDX** [elastic/elasticsearch-net#6645]
**NEST/Elasticsearch.Net version**: 7.14.1.0
**Elasticsearch version**: 7.14
**.NET runtime version**: 4.7.03190
**Operating system version**: Windows Server 2019

**Description of the problem including expected versus actual behavior**:

ElasticSearch fails to read TEMP folder path containing special character. 
The below error message is logged to denote this issue -

**ERROR: Temporary directory [E:\TestTemp\Temp\elasticsearch] does not exist or is not accessible**

The actual TEMP folder path contains a special character (!) - "E:\\!TestTemp\Temp\elasticsearch".
Due to this the Elasticsearch JVM fails to start.
 
**Steps to reproduce**:
 1.
 2.
 3.

**Expected behavior**
ElasticSearch should be able to handle folder path containing special characters.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by stevejgordon** [comment]
Hi @EVINDX.

This doesn't appear to be a .NET client issue so I am closing this issue. For general community support you can get help from our [discuss forum](https://discuss.elastic.co/). If you believe this is a bug for Elasticsearch, the correct repository is [here](https://github.com/elastic/elasticsearch).
