### ISSUE TITLE
Failed to serialize anonymous type: Nest.BulkIndexDescriptor

### ISSUE THREAD

**Issue by mbooh** [elastic/elasticsearch-net#6646]
**NEST/Elasticsearch.Net version**: 7.17.4

**Elasticsearch version**: 8.2.2

**.NET runtime version**: NET 6.0

**Operating system version**: Win Server 2019 Standard

**Description of the problem including expected versus actual behavior**:
Using 7.17.4 on Win Server 2019 we can not use IndexMany()

var bulkResponse = Client.Bulk(b => b
                .Index(Client.GetIndexName(targetIndex, indexBaseName))
                .IndexMany(documents));

That gives us an exception:
Failed to serialize anonymous type: Nest.BulkIndexDescriptor`1[Klaranatet.Elastic.Models.IDocumentModel].

If we change to version 7.17.2 it works just fine on the server and 7.17.4 also works fine on my Win 10 developing machine.

**Comment by stevejgordon** [comment]
Hi, @mbooh.

Apologies for the delay. I have been on leave. In the mean time, did you get any further with this? It's curious why this would behave differently on Server 2019 and Win 10. Are you using the same data for the documents? To assist further, are you able to please capture the debug information and share it as it will include the request/response details and the full stack trace. https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/debug-mode.html 

The easiest logging option would be the OnRequestCompleted callback. https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/logging-with-on-request-completed.html 

```c#
var pool = new SingleNodeConnectionPool(new Uri("http://localhost:9200")); 
var settings = new ConnectionSettings(pool, sourceSerializer: JsonNetSerializer.Default) 
   .EnableDebugMode() 
   .OnRequestCompleted(apiCallDetails => {  
      // apiCallDetails.ToString() holds all the useful debug information 
      // Log it from here. 
}); 
```

var client = new ElasticClient(settings);

**Comment by stevejgordon** [comment]
Hi, @mbooh. Are you able to provide further information to move this forward?

**Comment by stevejgordon** [comment]
Closing as stale.

**Comment by martindu911** [comment]
I've met the same problem. It turns out you need to specify the index name with client.IndexMany(documents, indexName).
