### ISSUE TITLE
BulkAsync failed but response.Success is true and HttpStatusCode is 200

### ISSUE THREAD

**Issue by jincaijiang** [elastic/elasticsearch-net#6649]
**NEST/Elasticsearch.Net version**: 7.6.1

**Elasticsearch version**: 7.17

**.NET runtime version**: net6.0

**Operating system version**: Windows 10

**Description of the problem including expected versus actual behavior**:
BulkAsync failed to upsert a document with a large number of fields and no message was written to the nodes. response.body says {"status":400,"error":{"type":"illegal_argument_exception","reason":"Limit of total fields [1000] in index [test_inventory] has been exceeded"}, but response.Success=true and response.HttpStatusCode=200
**Steps to reproduce**:
 1.open lowlevel connection with SniffingConnectionPool(nodes) where nodes containing 3 elements
 2.upsert a message using lowelLevelClient.BulkAsync<Elasticsearch.Net.StringResponse>(postData) |> Async.AwaitTask
 3.check the response.Success is true, HttpStatusCode is 200, but no message was written in the cluster, response.body contains a message of status 400

**Expected behavior**
response.Success should be false and HttpStatusCode should be 400 so I can test the failed upsertion (instead of scanning the response for status 400)
**Provide `ConnectionSettings` (if relevant)**:
Not relevant
**Provide `DebugInformation` (if relevant)**:
Successful (200) low level call on POST: /_bulk
# Audit trail of this API call:
 - [1] SniffOnStartup: Took: 00:00:01.3520906
 - [2] SniffSuccess: Node: https://elastic.azure.portal.net:9200/ Took: 00:00:01.0105424
 - [3] PingSuccess: Node: https://10.33.56.217:9200/ Took: 00:00:00.6812748
 - [4] HealthyResponse: Node: https://10.33.56.217:9200/ Took: 00:00:00.9033282
# Request:
{"index":{"_index":"test_inventory","_id":"FC001_SS1:A1.A","retry_on_conflict":5}}
{"fcid":"FC001","location":"SS1:A1.A","inventory":[{"inventoryBlockId":"503760a573bb432ab928a7f16f5b89db","creationDate":"2019-01-29T19:15:44+00:00","thorSku":"AA0AA1","totalUnitQty":12,"expirationDate":"2029-01-01T23:59:59-08:00","reservedQty":{},"poNumber":null,"poNbr":null,"wipBucket":null,"originalOwner":"JET","currentOwner":"JET","version":1415},{"inventoryBlockId":"88dc59725ccd4bd9b673e04217e9f598","creationDate":"2019-06-25T23:12:49+00:00","thorSku":"AA0AA2","totalUnitQty":22,"expirationDate":null,"reservedQty":{"11538516A":6,"11608036A":3,"11608037A":1,"11608038A":1,"11608039A":3,"11608039B":3,"11608042A":1,"11608043A":1,"11885320A":6,"11909128A":6,"11909129A":6,"11909130A":6,"11909131A":6,"11986222A":6,"11986223A":6,"12723243A":1,"12723245A":1,"12723246A":1,"12723247A":1,"12723248A":1,"12723249A":1,"12723250A":1,"12723251A":1,"12723252A":1,"12723253A":1,"12723254A":1,"12723255A":1,"12723256A":1,"12723257A":1,"12723258A":1,"12723259A":1,"12723260A":1,"12723261A":1,"12723262A":1,"12723263A":1,"12723264A":1,"12723265A":1,"12723266A":1,"12723267A":1,"12723268A":1,"12723269A":1,"12723270A":1,"12723271A":1,"12723272A":1,"12723273A":1,"12723274A":1,"12723275A":1,"12723276A":1,"12723277A":1,"12723278A":1,"12723279A":1,"12723280A":1,"12723281A":1,"12723282A":1,"12723283A":1,"12723284A":1,"12723285A":1,"12723286A":1,"12723287A":1,"12723288A":1,"12723289A":1,"12723290A":1,"12723291A":1,"12723292A":1,"12723293A":1,"12723294A":1,"12723295A":1,"12723296A":1,"12723297A":1,"12723298A":1,"12723299A":1,"12723300A":1,"12723301A":1,"12723302A":1,"12723303A":1,"12723304A":1,"12723305A":1,"12723306A":1,"12723307A":1,"12723308A":1,"12723309A":1,"12723310A":1,"12723311A":1,"12723312A":1,"12723313A":1,"12723314A":1,"12723315A":1,"12723316A":1,"12723317A":1,"12723318A":1,"12723319A":1,"12723320A":1,"12723321A":1,"12723322A":1,"12723323A":1,"12723324A":1,"12723325A":1,"12723326A":1,"12723327A":1,"12723328A":1,"12723329A":1,"12723330A":1,"12723331A":1,"12723332A":1,"12723333A":1,"12723334A":1,"12723335A":1,"12723336A":1,"12723337A":1,"12723338A":1,"12723339A":1,"12723340A":1,"12723341A":1,"12723342A":1,"12723343A":1,"12723344A":1,"12723345A":1,"12723346A":1,"12723347A":1,"12723348A":1,"12723349A":1,"12723350A":1,"12723351A":1,"12723352A":1,"12723353A":1,"12723354A":1,"12723355A":1,"12723356A":1,"12723357A":1,"12723358A":1,"12723359A":1,"12723360A":1,"12723361A":1,"12723362A":1,"12723363A":1,"12723364A":1,"12723365A":1,"12723366A":1,"12723367A":1,"12723368A":1,"12723369A":1,"12723370A":1,"12723371A":1,"12723372A":1,"12723373A":1,"12723374A":1,"12723375A":1,"12723376A":1,"12723377A":1,"12723378A":1,"12723379A":1,"12723380A":1,"12723381A":1,"12723382A":1,"12723383A":1,"12723384A":1,"12723385A":1,"12723386A":1,"12723387A":1,"12723388A":1,"12723389A":1,"12723390A":1,"12723391A":1,"12723392A":1,"12723393A":1,"12723394A":1,"12723395A":1,"12723396A":1,"12723397A":1,"12723398A":1,"12723399A":1,"12723400A":1,"12723401A":1,"12723402A":1,"12723403A":1,"12723404A":1,"12723405A":1,"12723406A":1,"12723407A":1,"12723408A":1,"12723409A":1,"12723410A":1,"12723411A":1,"12723412A":1,"12723413A":1,"12723414A":1,"12723415A":1,"12723416A":1,"12723417A":1,"12723418A":1,"12723419A":1,"12723420A":1,"12723421A":1,"12723422A":1,"12723423A":1,"12723424A":1,"12723425A":1,"12723426A":1,"12723427A":1,"12723428A":1,"12723429A":1,"12723430A":1,"12723431A":1,"12723432A":1,"12723433A":1,"12723434A":1,"12723435A":1,"12723436A":1,"12723437A":1,"12723438A":1,"12723439A":1,"12723440A":1,"12723441A":1,"12723442A":1,"12723443A":1,"12723444A":1,"12723445A":1,"12723446A":1,"12723447A":1,"12723448A":1,"12723449A":1,"12723450A":1,"12723451A":1,"12723452A":1,"12723453A":1,"12723454A":1,"12723455A":1,"12723456A":1,"12723457A":1,"12723458A":1,"12723459A":1,"12723460A":1,"12723461A":1,"12723462A":1,"12723463A":1,"12723464A":1,"12723465A":1,"12723466A":1,"12723467A":1,"12723468A":1,"12723469A":1,"12723470A":1,"12723471A":1,"12723472A":1,"12723473A":1,"12723474A":1,"12723475A":1,"12723476A":1,"12723477A":1,"12723478A":1,"12723479A":1,"12723480A":1,"12723481A":1,"12723482A":1,"12723483A":1,"12723484A":1,"12723485A":1,"12723486A":1,"12723487A":1,"12723488A":1,"12723489A":1,"12723490A":1,"12723491A":1,"12723492A":1,"12723493A":1,"12723494A":1,"12723495A":1,"12723496A":1,"12723497A":1,"12723498A":1,"12723499A":1,"12723500A":1,"12723501A":1,"12723502A":1,"12723503A":1,"12723504A":1,"12723505A":1,"12723506A":1,"12723507A":1,"12723508A":1,"12723509A":1,"12723510A":1,"12723511A":1,"12723512A":1,"12723513A":1,"12723514A":1,"12723515A":1,"12723516A":1,"12723517A":1,"12723518A":1,"12723519A":1,"12723520A":1,"12723521A":1,"12723522A":1,"12723523A":1,"12723524A":1,"12723525A":1,"12723526A":1,"12723527A":1,"12723528A":1,"12723529A":1,"12723530A":1,"12723531A":1,"12723532A":1,"12723533A":1,"12723534A":1,"12723535A":1,"12723536A":1,"12723537A":1,"12723538A":1,"12723539A":1,"12723540A":1,"12723541A":1,"12723542A":1,"12723543A":1,"12723544A":1,"12723545A":1,"12723546A":1,"12723547A":1,"12723548A":1,"12723549A":1,"12723550A":1,"12723551A":1,"12723552A":1,"12723553A":1,"12723554A":1,"12723555A":1,"12723556A":1,"12723557A":1,"12723558A":1,"12723559A":1,"12723560A":1,"12723561A":1,"12723562A":1,"12723563A":1,"12723564A":1,"12723565A":1,"12723566A":1,"12723567A":1,"12723568A":1,"12723569A":1,"12723570A":1,"12723571A":1,"12723572A":1,"12723573A":1,"12723574A":1,"12723575A":1,"12723576A":1,"12723577A":1,"12723578A":1,"12723579A":1,"12723580A":1,"12723581A":1,"12723582A":1,"12723583A":1,"12723584A":1,"12723585A":1,"12723586A":1,"12723587A":1,"12723588A":1,"12723589A":1,"12723590A":1,"12723591A":1,"12723592A":1,"12723593A":1,"12723594A":1,"12723595A":1,"12723596A":1,"12723597A":1,"12723598A":1,"12723599A":1,"12723600A":1,"12723601A":1,"12723602A":1,"12723603A":1,"12723604A":1,"12723605A":1,"12723606A":1,"12723607A":1,"12723608A":1,"12723609A":1,"12723610A":1,"12723611A":1,"12723612A":1,"12723613A":1,"12723614A":1,"12723615A":1,"12723616A":1,"12723617A":1,"12723618A":1,"12723619A":1,"12723620A":1,"12723621A":1,"12723622A":1,"12723623A":1,"12723624A":1,"12723625A":1,"12723626A":1,"12723627A":1,"12723628A":1,"12723629A":1,"12723630A":1,"12723631A":1,"12723632A":1,"12723633A":1,"12723634A":1,"12723635A":1,"12723636A":1,"12723637A":1,"12723638A":1,"12723639A":1,"12723640A":1,"12723641A":1,"12723642A":1,"12723643A":1,"12723644A":1,"12723645A":1,"12723646A":1,"12723647A":1,"12723649A":1,"12723650A":1,"12723651A":1,"12723652A":1,"12723653A":1,"12723654A":1,"12723655A":1,"12723656A":1,"12723657A":1,"12723658A":1,"12723659A":1,"12723660A":1,"12723661A":1,"12723662A":1,"12723663A":1,"12723664A":1,"12723665A":1,"12723666A":1,"12723667A":1,"12723668A":1,"12723669A":1,"12723670A":1,"12723671A":1,"12723672A":1,"12723673A":1,"12723674A":1,"12723675A":1,"12723676A":1,"12723677A":1,"12723678A":1,"12723679A":1,"12723680A":1,"12723681A":1,"12723682A":1,"12723683A":1,"12723684A":1,"12723685A":1,"12723686A":1,"12723687A":1,"12723688A":1,"12723689A":1,"12723690A":1,"12723691A":1,"12723692A":1,"12723693A":1,"12723694A":1,"12723695A":1,"12723696A":1,"12723697A":1,"12723698A":1,"12723699A":1,"12723700A":1,"12723701A":1,"12723702A":1,"12723703A":1,"12723704A":1,"12723705A":1,"12723706A":1,"12723707A":1,"12723708A":1,"12723709A":1,"12723710A":1,"12723711A":1,"12723712A":1,"12723713A":1,"12723714A":1,"12723715A":1,"12723716A":1,"12723717A":1,"12723718A":1,"12723719A":1,"12723720A":1,"12723721A":1,"12723722A":1,"12723723A":1,"12723724A":1,"12723725A":1,"12723726A":1,"12723727A":1,"12723728A":1,"12723729A":1,"12723730A":1,"12723731A":1,"12723732A":1,"12723733A":1,"12723734A":1,"12723735A":1,"12723736A":1,"12723737A":1,"12723738A":1,"12723739A":1,"12723740A":1,"12723741A":1,"12723742A":1,"12723743A":1,"12723744A":1,"12723745A":1,"12723746A":1,"12723747A":1,"12723748A":1,"12723749A":1,"12723750A":1,"12723751A":1,"12723752A":1,"12723753A":1,"12723754A":1,"12723755A":1,"12723756A":1,"12723757A":1,"12723758A":1,"12723759A":1,"12723760A":1,"12723761A":1,"12723762A":1,"12723763A":1,"12723764A":1,"12723765A":1,"12723766A":1,"12723767A":1,"12723768A":1,"12723769A":1,"12723770A":1,"12723771A":1,"12723772A":1,"12723773A":1,"12723774A":1,"12723775A":1,"12723776A":1,"12723777A":1,"12723778A":1,"12723779A":1,"12723780A":1,"12723781A":1,"12723782A":1,"12723783A":1,"12723784A":1,"12723785A":1,"12723786A":1,"12723787A":1,"12723788A":1,"12723789A":1,"12723790A":1,"12723791A":1,"12723792A":1,"12723793A":1,"12723794A":1,"12723795A":1,"12723796A":1,"12723797A":1,"12723798A":1,"12723799A":1,"12723800A":1,"12723801A":1,"12723802A":1,"12723803A":1,"12723804A":1,"12723805A":1,"12723806A":1,"12723807A":1,"12723808A":1,"12723809A":1,"12723810A":1,"12723811A":1,"12723812A":1,"12723813A":1,"12723814A":1,"12723815A":1,"12723816A":1,"12723817A":1,"12723818A":1,"12723819A":1,"12723820A":1,"12723821A":1,"12723822A":1,"12723823A":1,"12723824A":1,"12723825A":1,"12723826A":1,"12723827A":1,"12723828A":1,"12723829A":1,"12723830A":1,"12723831A":1,"12723832A":1,"12723833A":1,"12723834A":1,"12723835A":1,"12723836A":1,"12723837A":1,"12723838A":1,"12723839A":1,"12723840A":1,"12723841A":1,"12723842A":1,"12723843A":1,"12723844A":1,"12723845A":1,"12723846A":1,"12723847A":1,"12723848A":1,"12723849A":1,"12723850A":1,"12723851A":1,"12723852A":1,"12723853A":1,"12723854A":1,"12723855A":1,"12723856A":1,"12723857A":1,"12723858A":1,"12723859A":1,"12723860A":1,"12723861A":1,"12723862A":1,"12723863A":1,"12723864A":1,"12723865A":1,"12723866A":1,"12723867A":1,"12723868A":1,"12723869A":1,"12723870A":1,"12723871A":1,"12723872A":1,"12723873A":1,"12723874A":1,"12723875A":1,"12723876A":1,"12723877A":1,"12723878A":1,"12723879A":1,"12723880A":1,"12723881A":1,"12723882A":1,"12723883A":1,"12723884A":1,"12723885A":1,"12723886A":1,"12723887A":1,"12723888A":1,"12723889A":1,"12723890A":1,"12723891A":1,"12723892A":1,"12723893A":1,"12723894A":1,"12723895A":1,"12723896A":1,"12723897A":1,"12723898A":1,"12723899A":1,"12723900A":1,"12723901A":1,"12723902A":1,"12723903A":1,"12723904A":1,"12723905A":1,"12723906A":1,"12723907A":1,"12723908A":1,"12723909A":1,"12723910A":1,"12723911A":1,"12723912A":1,"12723913A":1,"12723914A":1,"12723915A":1,"12723916A":1,"12723917A":1,"12723918A":1,"12723919A":1,"12723920A":1,"12723921A":1,"12723922A":1,"12723923A":1,"12723924A":1,"12723925A":1,"12723926A":1,"12723927A":1,"12723928A":1,"12723929A":1,"12723930A":1,"12723931A":1,"12723932A":1,"12723933A":1,"12723934A":1,"12723935A":1,"12723936A":1,"12723937A":1,"12723938A":1,"12723939A":1,"12723940A":1,"12723941A":1,"12723942A":1,"12723943A":1,"12723944A":1,"12723945A":1,"12723946A":1,"12723947A":1,"12723948A":1,"12723949A":1,"12723950A":1,"12723951A":1,"12723952A":1,"12723953A":1,"12723954A":1,"12723955A":1,"12723956A":1,"12723957A":1,"12723958A":1,"12723959A":1,"12723960A":1,"12723961A":1,"12723962A":1,"12723963A":1,"12723964A":1,"12723965A":1,"12723966A":1,"12723967A":1,"12723968A":1,"12723969A":1,"12723970A":1,"12723971A":1,"12723972A":1,"12723973A":1,"12723974A":1,"12723975A":1,"12723976A":1,"12723977A":1,"12723978A":1,"12723979A":1,"12723980A":1,"12723981A":1,"12723982A":1,"12723983A":1,"12723984A":1,"12723985A":1,"12723986A":1,"12723987A":1,"12723988A":1,"12723989A":1,"12723990A":1,"12723991A":1,"12723992A":1,"12723993A":1,"12723994A":1,"12723995A":1,"12723996A":1,"12723997A":1,"12723998A":1,"12723999A":1,"12724000A":1,"12724001A":1,"12724002A":1,"12724003A":1,"12724004A":1,"12724005A":1,"12724006A":1,"12724007A":1,"12724008A":1,"12724009A":1,"12724010A":1,"12724011A":1,"12724012A":1,"12724013A":1,"12724014A":1,"12724015A":1,"12724016A":1,"12724017A":1,"12724018A":1,"12724019A":1,"12724020A":1,"12724021A":1,"12724022A":1,"12724023A":1,"12724024A":1,"12724025A":1,"12724026A":1,"12724027A":1,"12724028A":1,"12724029A":1,"12724030A":1,"12724031A":1,"12724033A":1,"12724034A":1,"12724035A":1,"12724036A":1,"12724037A":1,"12724038A":1,"12724039A":1,"12724040A":1,"12724041A":1,"12724042A":1,"12724043A":1,"12724044A":1,"12724045A":1,"12724046A":1,"12724047A":1,"12724048A":1,"12724049A":1,"12724050A":1,"12724051A":1,"12724052A":1,"12724053A":1,"12724054A":1,"12724055A":1,"12724056A":1,"12724057A":1,"12724058A":1,"12724059A":1,"12724060A":1,"12724061A":1,"12724062A":1,"12724063A":1,"12724064A":1,"12724065A":1,"12724066A":1,"12724067A":1,"12724068A":1,"12724069A":1,"12724070A":1,"12724071A":1,"12724072A":1,"12724073A":1,"12724074A":1,"12724075A":1,"12724076A":1,"12724077A":1,"12724078A":1,"12724079A":1,"12724080A":1,"12724081A":1,"12724082A":1,"12724083A":1,"12724084A":1,"12724085A":1,"12724086A":1,"12724087A":1,"12724088A":1,"12724089A":1,"12724090A":1,"12724091A":1,"12724092A":1,"12724093A":1,"12724094A":1,"12724095A":1,"12724096A":1,"12724097A":1,"12724098A":1,"12724099A":1,"12724100A":1,"12724101A":1,"12724102A":1,"12724103A":1,"12724104A":1,"12724105A":1,"12724106A":1,"12724107A":1,"12724108A":1,"12724109A":1,"12724110A":1,"12724111A":1,"12724112A":1,"12724113A":1,"12724114A":1,"12724115A":1,"12724116A":1,"12724117A":1,"12724118A":1,"12724119A":1,"12724120A":1,"12724121A":1,"12724122A":1,"12724123A":1,"12724124A":1,"12724125A":1,"12724126A":1,"12724127A":1,"12724128A":1,"12724129A":1,"12724130A":1,"12724131A":1,"12724132A":1,"12724133A":1,"12724134A":1,"12724135A":1,"12724136A":1,"12724137A":1,"12724138A":1,"12724139A":1,"12724140A":1,"12724141A":1,"12724142A":1,"12724143A":1,"12724144A":1,"12724145A":1,"12724146A":1,"12724147A":1,"12724148A":1,"12724149A":1,"12724150A":1,"12724151A":1,"12724152A":1,"12724153A":1,"12724154A":1,"12724155A":1,"12724156A":1,"12724157A":1,"12724158A":1,"12724159A":1,"12724160A":1,"12724161A":1,"12724162A":1,"12724163A":1,"12724164A":1,"12724165A":1,"12724166A":1,"12724167A":1,"12724168A":1,"12724169A":1,"12724170A":1,"12724171A":1,"12724172A":1,"12724173A":1,"12724174A":1,"12724175A":1,"12724176A":1,"12724177A":1,"12724178A":1,"12724179A":1,"12724180A":1,"12724181A":1,"12724182A":1,"12724183A":1,"12724184A":1,"12724185A":1,"12724186A":1,"12724187A":1,"12724188A":1,"12724189A":1,"12724190A":1,"12724191A":1,"12724192A":1,"12724193A":1,"12724194A":1,"12724195A":1,"12724196A":1,"12724197A":1,"12724198A":1,"12724199A":1,"12724200A":1,"12724201A":1,"12724202A":1,"12724203A":1,"12724204A":1,"12724205A":1,"12724206A":1,"12724207A":1,"12724208A":1,"12724209A":1,"12724210A":1,"12724211A":1,"12724212A":1,"12724213A":1,"12724214A":1,"12724215A":1,"12724216A":1,"12724217A":1,"12724218A":1,"12724219A":1,"12724220A":1,"12724221A":1,"12724222A":1,"12724223A":1,"12724224A":1,"12724225A":1,"12724226A":1,"12724227A":1,"12724228A":1,"12724229A":1,"12724230A":1,"12724231A":1,"12724232A":1,"12724233A":1,"12724234A":1,"12724235A":1,"12724236A":1,"12724237A":1,"12724238A":1,"12724239A":1,"12724240A":1,"12724241A":1,"12724242A":1,"12724243A":1,"12724244A":1,"12724245A":1,"12724246A":1,"12724247A":1,"12724248A":1,"12724249A":1,"12724250A":1,"12724251A":1,"12724252A":1,"12724253A":1,"12724254A":1,"12724255A":1,"12724256A":1,"12724257A":1,"12724258A":1,"12724259A":1,"12724260A":1,"12724261A":1,"12724262A":1,"12724263A":1,"12724264A":1,"12724265A":1,"12724266A":1,"12724267A":1,"12724268A":1,"12724269A":1,"12724270A":1,"12724271A":1,"12724272A":1,"12724273A":1,"12724274A":1,"12724275A":1,"12724276A":1,"12724277A":1,"12724278A":1,"12724279A":1,"12724280A":1,"12724281A":1,"12724282A":1,"12724283A":1,"12724284A":1,"12724285A":1,"12724286A":1,"12724287A":1,"12724288A":1,"12724289A":1,"12724290A":1,"12724291A":1,"12724292A":1,"12724293A":1,"12724294A":1,"12724295A":1,"12724296A":1,"12724297A":1,"12724298A":1,"12724299A":1,"12724300A":1,"12724301A":1,"12724302A":1,"12724303A":1,"12724305A":1,"12724306A":1,"12724307A":1,"12724308A":1,"12724309A":1,"12724310A":1,"12724311A":1,"12724312A":1,"12724313A":1,"12724314A":1,"12724315A":1,"12724316A":1,"12724317A":1,"12724318A":1,"12724319A":1,"12724320A":1,"12724321A":1,"12724322A":1,"12724323A":1,"12724324A":1,"12724325A":1,"12724326A":1,"12724327A":1,"12724328A":1,"12724329A":1,"12724330A":1,"12724331A":1,"12724332A":1,"12724333A":1,"12724334A":1,"12724335A":1,"12724336A":1,"12724337A":1,"12724338A":1,"12724339A":1,"12724340A":1,"12724341A":1,"12724342A":1,"12724343A":1,"12724344A":1,"12724345A":1,"12724346A":1,"12724347A":1,"12724348A":1,"12724349A":1,"12724350A":1,"12724351A":1,"12724352A":1,"12724353A":1,"12724354A":1,"12724355A":1,"12724356A":1,"12724357A":1,"12724358A":1,"12724359A":1,"12724360A":1,"12724361A":1,"12724362A":1,"12724363A":1,"12724364A":1,"12724365A":1,"12724366A":1,"12724367A":1,"12724368A":1,"12724369A":1,"12724370A":1,"12724371A":1,"12724372A":1,"12724373A":1,"12724374A":1,"12724375A":1,"12724376A":1,"12724377A":1,"12724378A":1,"12724379A":1,"12724380A":1,"12724381A":1,"12724382A":1,"12724383A":1,"12724384A":1,"12724385A":1,"12724386A":1,"12724387A":1,"12724388A":1,"12724389A":1,"12724390A":1,"12724391A":1,"12724392A":1,"12724393A":1,"12724394A":1,"12724395A":1,"12724396A":1,"12724397A":1,"12724398A":1,"12724399A":1,"12724400A":1,"12724401A":1,"12724402A":1,"12724403A":1,"12724404A":1,"12724405A":1,"12724406A":1,"12724407A":1,"12724408A":1,"12724409A":1,"12724410A":1,"12724411A":1,"12724412A":1,"12724413A":1,"12724414A":1,"12724415A":1,"12724416A":1,"12724417A":1,"12724418A":1,"12724419A":1,"12724420A":1,"12724421A":1,"12724422A":1,"12724423A":1,"12724424A":1,"12724425A":1,"12724426A":1,"12724427A":1,"12724428A":1,"12724429A":1,"12724430A":1,"12724431A":1,"12724432A":1,"12724433A":1,"12724434A":1,"12724435A":1,"12724436A":1,"12724437A":1,"12724438A":1,"12724439A":1,"12724440A":1,"12724441A":1,"12724442A":1,"12724443A":1,"12724444A":1,"12724445A":1,"12724446A":1,"12724447A":1,"12724448A":1,"12724449A":1,"12724450A":1,"12724451A":1,"12724452A":1,"12724453A":1,"12724454A":1,"12724455A":1,"12724456A":1,"12724458A":1,"12724459A":1,"12724460A":1,"12724461A":1,"12724462A":1,"12724463A":1,"12724464A":1,"12724465A":1,"12724466A":1,"12724467A":1,"12724468A":1,"12724469A":1,"12724470A":1,"12724471A":1,"12724472A":1,"12724473A":1,"12724474A":1,"12724475A":1,"12724476A":1,"12724477A":1,"12724478A":1,"12786540A":6,"12786540B":6,"12786540C":6,"12786540D":6,"12786540E":5,"12786540F":6,"12786540G":6,"12786540H":5,"12786540I":6,"12786540J":6,"12786540K":6,"12786540L":6,"12786540M":6,"12786540N":6,"12786540O":6,"12786540P":6,"12786540Q":6,"12786541A":6,"12786541B":6,"12786541C":6,"12786541D":5,"12786541E":6,"12786541F":6,"12786541G":6,"12786541H":6,"12786541I":6,"12786541J":5,"12786541K":6,"12786541L":6,"12786541M":6,"12786541N":6,"12786541O":6,"12786541P":6,"12786541Q":6,"12786542A":1,"12786543A":1,"12786545A":1,"12786546A":1,"12786547A":1,"12786548A":1,"12786578A":1,"12786579A":1,"12786580A":1,"12786581A":1,"12786583A":1,"12786846A":1},"poNumber":null,"poNbr":null,"wipBucket":null,"originalOwner":"JET","currentOwner":"JET","version":1422},{"inventoryBlockId":"2d8152c0e11340a38154eb607c8e7375","creationDate":"2019-10-22T14:40:59+00:00","thorSku":"AA0BL2","totalUnitQty":89,"expirationDate":"2022-06-06T23:59:59-07:00","reservedQty":{"11453535A":52,"11453535B":48},"poNumber":null,"poNbr":null,"wipBucket":null,"originalOwner":"JET","currentOwner":"JET","version":1390},{"inventoryBlockId":"b2d8f56e26194d978283501a1ed5c986","creationDate":"2019-09-06T21:48:08+00:00","thorSku":"AA0BZ2","totalUnitQty":9,"expirationDate":null,"reservedQty":{},"poNumber":null,"poNbr":null,"wipBucket":null,"originalOwner":"JET","currentOwner":"JET","version":1423},{"inventoryBlockId":"7460e05042d44e3597340dc880202c92","creationDate":"2019-09-06T21:50:21+00:00","thorSku":"AA0BZ3","totalUnitQty":1,"expirationDate":"2024-05-05T23:59:59-07:00","reservedQty":{},"poNumber":null,"poNbr":null,"wipBucket":null,"originalOwner":"JET","currentOwner":"JET","version":82},{"inventoryBlockId":"ef8bdbfec9424a75aafdca48b3114d2c","creationDate":"2018-10-23T20:22:15+00:00","thorSku":"AA0HX2","totalUnitQty":100000000,"expirationDate":null,"reservedQty":{"4597862A":2},"poNumber":null,"poNbr":null,"wipBucket":null,"originalOwner":"JET","currentOwner":"JET","version":5},{"inventoryBlockId":null,"creationDate":"2015-01-08T00:40:58+00:00","thorSku":"AA0RJ5","totalUnitQty":6,"expirationDate":"2015-11-19T08:00:00+00:00","reservedQty":{},"poNumber":null,"poNbr":null,"wipBucket":null,"originalOwner":"JET","currentOwner":"JET","version":45},{"inventoryBlockId":"d20b956c0e46483585d6ad72a7bc0a2d","creationDate":"2018-10-23T20:22:27+00:00","thorSku":"AA0SC2","totalUnitQty":100000000,"expirationDate":null,"reservedQty":{"4602509A":2},"poNumber":null,"poNbr":null,"wipBucket":null,"originalOwner":"JET","currentOwner":"JET","version":6},{"inventoryBlockId":"60dbd3cb40584d178b59e647a43a2790","creationDate":"2018-06-25T14:55:53+00:00","thorSku":"AA0WW1","totalUnitQty":3000,"expirationDate":null,"reservedQty":{},"poNumber":null,"poNbr":null,"wipBucket":null,"originalOwner":"JET","currentOwner":"JET","version":2},{"inventoryBlockId":"dd198aa7bb9045f9be4b002cab0645fe","creationDate":"2018-10-30T20:16:27+00:00","thorSku":"AA1AH7","totalUnitQty":3000010,"expirationDate":null,"reservedQty":{},"poNumber":null,"poNbr":null,"wipBucket":null,"originalOwner":"JET","currentOwner":"JET","version":1416},{"inventoryBlockId":"24d9320216754d169e7bacead9f0252b","creationDate":"2018-06-22T14:59:25+00:00","thorSku":"AA1SU7","totalUnitQty":6,"expirationDate":"2022-06-07T23:59:59-07:00","reservedQty":{},"poNumber":null,"poNbr":null,"wipBucket":null,"originalOwner":"JET","currentOwner":"JET","version":23},{"inventoryBlockId":"220d2cc0a52b4250a4cd57d173af856f","creationDate":"2015-03-20T23:27:44+00:00","thorSku":"AA2KP5","totalUnitQty":6,"expirationDate":null,"reservedQty":{"12787388A":5,"12872706A":1},"poNumber":null,"poNbr":null,"wipBucket":null,"originalOwner":"JET","currentOwner":"JET","version":1394},{"inventoryBlockId":"281e7f475a934e67ac018a930083f0fd","creationDate":"2020-02-13T20:46:01+00:00","thorSku":"AA5SR6","totalUnitQty":100000,"expirationDate":null,"reservedQty":{},"poNumber":null,"poNbr":null,"wipBucket":null,"originalOwner":"JET","currentOwner":"JET","version":49},{"inventoryBlockId":"2a784eea26df49bba912e8977ebc8e69","creationDate":"2019-01-11T16:20:32+00:00","thorSku":"AA6KX3","totalUnitQty":500,"expirationDate":null,"reservedQty":{},"poNumber":null,"poNbr":null,"wipBucket":null,"originalOwner":"JET","currentOwner":"JET","version":10},{"inventoryBlockId":"a4a78cdb9771428299204f248df5ea06","creationDate":"2019-01-11T16:24:17+00:00","thorSku":"AA6KX4","totalUnitQty":22,"expirationDate":null,"reservedQty":{},"poNumber":null,"poNbr":null,"wipBucket":null,"originalOwner":"JET","currentOwner":"JET","version":1430},{"inventoryBlockId":"3b27336e85d048c9aa2149d787c6bc22","creationDate":"2019-07-22T14:22:54+00:00","thorSku":"AA6LM4","totalUnitQty":200,"expirationDate":null,"reservedQty":{"10965487C":6},"poNumber":9084,"poNbr":null,"wipBucket":null,"originalOwner":"MOOSEJAW","currentOwner":"MOOSEJAW","version":1429},{"inventoryBlockId":"7a64fbc7719448fcacc405aacd5577b0","creationDate":"2019-08-29T16:53:33+00:00","thorSku":"AA7AK2","totalUnitQty":200,"expirationDate":null,"reservedQty":{},"poNumber":null,"poNbr":null,"wipBucket":null,"originalOwner":"JET","currentOwner":"JET","version":1427},{"inventoryBlockId":"0f5d2562909042598692164fd2810b65","creationDate":"2019-08-14T21:06:47+00:00","thorSku":"AA7AK7","totalUnitQty":200,"expirationDate":"2026-02-10T23:59:59-08:00","reservedQty":{"10039870A":1,"10039870B":1},"poNumber":null,"poNbr":null,"wipBucket":null,"originalOwner":"JET","currentOwner":"JET","version":1425}]}

# Response:
{"took":44,"errors":true,"items":[{"index":{"_index":"test_inventory","_type":"_doc","_id":"FC001_SS1:A1.A","status":400,"error":{"type":"illegal_argument_exception","reason":"Limit of total fields [1000] in index [test_inventory] has been exceeded"}}}]}

**Comment by stevejgordon** [comment]
Hi @jincaijiang.

I appreciate the confusion here and there is some debate of the best status code the server should return here. The server returns a 200 OK because the request was received and processed. In this case, some operations had errors which can be identified by checking the `Errors` property on the top-level response. The response also overrides the `IsValid` shortcut property and will return `false` if any of the bulk operations experienced errors. You can access the `ItemsWithErrors` on the response to enumerate any failed operations.

Does that help explain the situation and address you requirements?

**Comment by stevejgordon** [comment]
Closing as answered.
