### ISSUE TITLE
"An item with the same key has already been added" for Indices.Get(...) method

### ISSUE THREAD

**Issue by skarpecki** [elastic/elasticsearch-net#6650]
**NEST/Elasticsearch.Net version**:
7.12.1 
**Elasticsearch version**:
7.x 
**.NET runtime version**:
.NET Framework 4.8
**Operating system version**:
Windows 10
**Description of the problem including expected versus actual behavior**:
One of our clients reported following exception:
```
Elasticsearch.Net.UnexpectedElasticsearchClientException: An item with the same key has already been added. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Nest.DynamicTemplatesFormatter.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Nest.ReadAsFormatter`2.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Deserialize(Object[] , JsonReader& , IJsonFormatterResolver )
   at Nest.ResolvableDictionaryResponseFormatter`3.Deserialize(JsonReader& reader, IJsonFormatterResolver formatterResolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Byte[] bytes, Int32 offset, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.Utf8Json.JsonSerializer.Deserialize[T](Stream stream, IJsonFormatterResolver resolver)
   at Elasticsearch.Net.DiagnosticsSerializerProxy.Deserialize[T](Stream stream)
   at Elasticsearch.Net.ResponseBuilder.SetBody[TResponse](ApiCallDetails details, RequestData requestData, Stream responseStream, String mimeType)
   at Elasticsearch.Net.ResponseBuilder.ToResponse[TResponse](RequestData requestData, Exception ex, Nullable`1 statusCode, IEnumerable`1 warnings, Stream responseStream, String mimeType)
   at Elasticsearch.Net.HttpWebRequestConnection.Request[TResponse](RequestData requestData)
   at Elasticsearch.Net.RequestPipeline.CallElasticsearch[TResponse](RequestData requestData)
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   --- End of inner exception stack trace ---
   at Elasticsearch.Net.Transport`1.Request[TResponse](HttpMethod method, String path, PostData data, IRequestParameters requestParameters)
   at Data.Elasticsearch.SynchronizeElasticsearch.CountObjects(xxxxx)
```

The CountObjects method has following body:

```
public int CountObjects(string connectionString)
{
    try
    {
        var uri = new Uri(connectionString);
        ConnectionSettings setting = new ConnectionSettings(uri)
            .PingTimeout(TimeSpan.FromSeconds(Timeouts.ElasticsearchTimeout))
            .RequestTimeout(TimeSpan.FromSeconds(Timeouts.ElasticsearchTimeout));

        var client = new ElasticClient(setting);

        var result = client.Indices.Get(new GetIndexRequest(Indices.All));
        var indexes = result.Indices.Keys;
        return indexes.Count()
    }
    catch (Exception ex)
    {
        return -1;
    }
}
```

The problem is - we have no idea why we get the error that item with same key has already been added, when all we do is actually getting the list of indices and just counting them. Does Indicies.Get() method inserts any new data?

**Expected behavior**
No error
**Provide `ConnectionSettings` (if relevant)**:
In snippet
**Provide `DebugInformation` (if relevant)**:

**Comment by stevejgordon** [comment]
Hi, @skarpecki.

Apologies for the delay. I have been on extended leave.

This is unexpected and it appears that something the client expects to be unique in the response and therefore deserialisable to a dictionary is not in your case. Based on the stack trace it appears to be an index with dynamic templates defined in the mappings. To investigate this further I'd need to see the response from the server. Are you able to enable debug mode to capture that and share it please? 

As it may contain sensitive information about your indices you can email the debug info. Please send it to us at: `microsoft @ elastic.co` (without spaces) and ping me here so I can check for it.

**Comment by stevejgordon** [comment]
Hi, @skarpecki. Are you able to provide further information to move this forward?

**Comment by skarpecki** [comment]
I am afraid we need to close the issue, as user who reported it haven't answered us since a month. We forwarded your question, but it seems that he ignored it..

**Comment by stevejgordon** [comment]
No problem @skarpecki. Ping us if you get more information to reproduce this.

**Comment by skarpecki** [comment]
Dear team, I finally got the response: 
![image](https://user-images.githubusercontent.com/58214669/205592649-e39fb9af-623f-4eb1-a9b6-e0bd8b20e380.png)

**Comment by stevejgordon** [comment]
@skarpecki, Can you please provide this as text so we can parse through it more easily?

**Comment by skarpecki** [comment]
@stevejgordon 

`{
  "mappings": {
    "_doc": {
      "properties": {
        "buyUnitld": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "buyUnitTypeName": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "capacityLocal": {
          "type": "long"
        },
        "capacityNet": {
          "type": "long"
        },
        "channelld": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "channelName": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "code": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "comercial UnitName": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "date": {
          "type": "date"
        },
        "id": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "mediaTypeName": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "name": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "order": {
          "type": "long"
        },
        "programName": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "quotas": {
          "properties": {
            "amount": {
              "type": "float"
            },
            "duration": {
              "type": "long"
            },
            "duration TypeName": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "name": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "quantity": {
              "type": "long"
            },
            "quotald": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            },
            "quotaName": {
              "type": "text",
              "fields": {
                "keyword": {
                  "type": "keyword",
                  "ignore_above": 256
                }
              }
            }
          }
        },
        "segmentld": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "table": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        },
        "unitTypeName": {
          "type": "text",
          "fields": {
            "keyword": {
              "type": "keyword",
              "ignore_above": 256
            }
          }
        }
      }
    }
  }
}`

**Comment by stevejgordon** [comment]
@skarpecki That JSON does not correspond to a complete response from the server for the C# request you previously included.

```c#
var result = client.Indices.Get(new GetIndexRequest(Indices.All));
```

Without the full response, I'll be unable to assist here.

**Comment by skarpecki** [comment]
Ok, working on it

**Comment by samuelchmiel** [comment]
Hi! I'm working with skrapecki on this problem. Unfortunately, the client will not send us an entire response from the production server. 

We managed to cause such an exception in a test environment. I think it's because dynamic templates can contain multiple template names with the same name.

Steps to reproduce the bug:

`PUT _template/newtemplate 

{ 
  "index_patterns": [ 
    "newindex-*" 
  ], 
  "mappings": { 
    "dynamic_templates": [ 
      { 
        "firstTemplate": { 
          "path_match": "myobject.abc.*", 
          "match_mapping_type": "double", 
          "mapping": { 
            "type": "long" 
          } 
        } 
      }, 
      { 
        "firstTemplate": { 
          "path_match": "myobject.def.*", 
          "match_mapping_type": "double", 
          "mapping": { 
            "type": "long" 
          } 
        } 
      } 
    ] 
  } 
} 
`
`PUT newindex-1`

Response of GET /_all

{ 
    "newindex-1": { 
        "aliases": {}, 
        "mappings": { 
            "dynamic_templates": [ 
                { 
                    "newtemplate": { 
                        "path_match": "myobject.abc.*", 
                        "match_mapping_type": "double", 
                        "mapping": { 
                            "type": "long" 
                        } 
                    } 
                }, 
                { 
                    "newtemplate": { 
                        "path_match": "myobject.def.*", 
                        "match_mapping_type": "double", 
                        "mapping": { 
                            "type": "long" 
                        } 
                    } 
                } 
            ] 
        }, 

        "settings": { 
            "index": { 
                "routing": { 
                    "allocation": { 
                        "include": { 
                            "_tier_preference": "data_content" 
                        } 
                    } 
                }, 
                "number_of_shards": "1", 
                "provided_name": "newindex-1", 
                "creation_date": "1673529001857", 
                "number_of_replicas": "1", 
                "uuid": "eoXH0NWBQYCHvug7375-1g", 
                "version": { 
                    "created": "7100199"
                } 
            } 
        } 
    } 
}

**Comment by stevejgordon** [comment]
Thanks, @samuelchmiel. That's really helpful. I'll need to review this further to see what our options are to handle this.

**Comment by samuelchmiel** [comment]
Hi @stevejgordon, do you have any updates on this issue?

**Comment by stevejgordon** [comment]
@samuelchmiel I'm afraid I didn't get time to work on this around other priorities, so this hasn't progressed. I am no longer maintaining this library so won't be picking this up personally.

**Comment by flobernd** [comment]
@samuelchmiel Hi there, I'm the new maintainer of the library, but NEST currently has low priority for me as well. I'm happy to accept PRs, but besides from that, it might take a good while until I habe time to check this issue.
