### ISSUE TITLE
Script mapping parameters missing from some types

### ISSUE THREAD

**Issue by marcin-dardzinski** [elastic/elasticsearch-net#6651]
**NEST/Elasticsearch.Net version**: 7.16.4

**Elasticsearch version**: 7.16.4

**.NET runtime version**: .NET 6.0

**Operating system version**: Linux

**Description of the problem including expected versus actual behavior**:
Some mapping data types (e.g. [keyword](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/keyword.html#keyword-params), [number](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/number.html#number-params) allow setting script as value source. 
Currently NEST only allows this for `GeoShape` / `GeoPoint` which was requested in #6555. 

**Expected behavior**
I can set up scripts in mappings for all the types that support it.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by stevejgordon** [comment]
Thanks for raising this gap in the client @marcin-dardzinski. I'll review this further and look at adding this missing property for the other mapping types.
