### ISSUE TITLE
Update System.Diagnostics.DiagnosticSource to version 6.0.0.0?

### ISSUE THREAD

**Issue by ucu2009** [elastic/elasticsearch-net#6653]
**Is your feature request related to a problem? Please describe.**
Recently we have updated our projects libraries. In those libraries we had System.Diagnostics.DiagnosticSource. We updated that to 6.0.0.0.
After that, we have an error when we try to run a Hangfire job that indexes our data.
We tried to remove the System.Diagnostics.DiagnosticSource package altogether from the project(we are not using the library anywhere else) and leave the dependency from elastic search, we still have the problem.
In Elasticsearch.Net Nuget the dependency for System.Diagnostics.DiagnosticSource is  >= 5.0.0.0 but it seams is restricted to 5.0.0.0.

We are using Elasticsearch.Net.7.17.4.

Bellow is the error message.
![image](https://user-images.githubusercontent.com/31214811/189161735-016ee4c3-c1d1-4459-ba14-e1d44911f93f.png)

Our security policy will not allowed us the have a release with packages that are not up to date.

**Describe the solution you'd like**
Update Elasticsearch.Net. dependency to System.Diagnostics.DiagnosticSource to version 6.0.0.0

**Comment by stevejgordon** [comment]
Hi, @ucu2009.

As a general practice we don't update dependencies in this way as it forces all consumers to use a newer version which may conflict with other packages they use. We depend on the version required providing the features we need and upgrade only for new features or security vulnerabilities. As you noticed it's a greater or equal dependency that we have so you should be able to force the use of a newer version to 6.0.0. 

Are you on .NET (core) or legacy .NET Framework? The latter from my experience exhibits more issues with package resolution. Are any other packages you depend on perhaps pinning to 5.0.0?

I was able to get this working on .NET 6.0 with the following in my project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NEST" Version="7.17.4" />
    <PackageReference Include="System.Diagnostics.DiagnosticSource" Version="6.0.0" />
  </ItemGroup>

</Project>
```

To assist further, can you provide a simplified reproduction I can look at?

**Comment by stevejgordon** [comment]
Hi, @ucu2009. Are you able to provide further information to move this forward?

**Comment by ucu2009** [comment]
@Hi @stevejgordon,

After a long try, for us at least. the problem was solved. We had to change the way we load the dependencies on the project.

Thanks.

**Comment by stevejgordon** [comment]
Thanks for feeding back, @ucu2009. Glad you were able to resolve it.
