### ISSUE TITLE
Aliases are not been created for newly generated indices

### ISSUE THREAD

**Issue by sooraj23** [elastic/elasticsearch-net#6740]
**NEST version**: 7.8.2

**Elasticsearch version**: 7.8.0

**.NET runtime version**: 3.1.30

**Operating system version**: Windows 10

**Description of the problem including expected versus actual behavior**:
while trying to create aliases using the below given code, aliases are not being created intermittently for newly generated indices. Kindly provide the details if we have a solution for this.

`private ElasticClient Client { get; }`
`string indexFullName = $"{indexInfo.SiteName}_{indexInfo.IndexType}_{indexInfo.IndexSuffix}";`
`string alias = $"{indexInfo.SiteName}_{indexInfo.IndexType}_all";`
`PutAliasResponse pResult = await Client.Indices.PutAliasAsync(Indices.Parse(indexFullName), new Name(alias), ct: token);`

**Expected behavior**
Aliases should be created for newly created indices

**Comment by sooraj23** [comment]
> @sooraj23 You'll need to review the response to understand if the server is rejecting it for some reason. If `IsValid` is false, you can inspect the `ServerError` to understand the cause. Does that help you progress?

**Comment by stevejgordon** [comment]
@sooraj23 At this stage we don't have enough information to support you on this. If the server is returning a valid response, then it would suggest it accepted and processed the put alias request. If that's the case, this is unlikely to be a client bug. We'd need a way to reproduce what you are experiencing. How are you checking whether the alias was created? Is there anything common about the aliases that cannot be created?

Can you [capture the responses](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/debug-information.html) for your put alias requests? If you can hold onto that until you have an alias you believe was not created, we could double-check what the server sends for the put response. If it's returning a created response, but they are not available on the server, then possibly there's a misconfiguration somewhere or a serverside bug.

**Comment by stevejgordon** [comment]
Closing as stale.
