### ISSUE TITLE
 how can i get request param detail at BulkAllObserver OnNext callback

### ISSUE THREAD

**Issue by Honestor** [elastic/elasticsearch-net#6777]
at BulkAllObserver OnNext callback, how can i get request param detail,now i just get the Id and other not important imformation. i want to get the request param.

**Comment by stevejgordon** [comment]
Hi, @Honestor.

It's recommended that questions be raised in the [Discuss community forum](https://discuss.elastic.co/), as we reserve the issues for bug reports and feature requests. The `BullkAll` helper is an IObservable of `BulkAllResponse`, and as a result, it doesn't expose the request level information. From the `BulkAllResponse`, you can access the per operation status, error and result. Could you please describe your use case/scenario for accessing the request information? If you need finer control over bulk requests, you may need to manually invoke the [Bulk endpoint](https://www.elastic.co/guide/en/elasticsearch/client/net-api/7.17/indexing-documents.html#_multiple_documents_with_bulk), at which point you can manage each response. Of course, you also need to consider batching, retries, error handling etc.

**Comment by stevejgordon** [comment]
Closing as answered.
