### ISSUE TITLE
elastic cloud authentication - API key: Illegal base64 character 2d

### ISSUE THREAD

**Issue by gioccher** [elastic/elasticsearch-net#6823]
**Elastic.Clients.Elasticsearch version**:
8.0 rc1
**Elasticsearch version**:

**.NET runtime version**:
4.7.2
**Operating system version**:
windows 

**Description of the problem including expected versus actual behavior**:
I'm trying to get started with app search, but I'm already stuck with the authentication. The error message "API key: Illegal base64 character 2d" seems to indicate elastic is not expecting a dash in the apikey (at least, %2d is dash when urlencoding), but the api keys generated from the App Search credentials page all contain a dash. Is this a bug in the library or am I being particularly dense and not using the "right" api key?
![image](https://user-images.githubusercontent.com/921538/197897178-891c78e5-5cdf-4727-ac95-3b5428684f25.png)
![image](https://user-images.githubusercontent.com/921538/197897150-d60c2f5d-adc1-49b3-b5a1-f6d33acbd8a7.png)

**Comment by stevejgordon** [comment]
Hi, @gioccher.

We do not currently ship an Enterprise Search or App Search client for .NET. Elastic.Clients.Elasticsearch is intended for use directly with an Elasticsearch cluster or [Elastic Cloud Elasticsearch](https://www.elastic.co/cloud/) deployment and is not supported for use with App Search.
