### ISSUE TITLE
Add field_multi_value_leniency to SQL APIs

### ISSUE THREAD

**Issue by Szanik** [elastic/elasticsearch-net#6866]
**Is your feature request related to a problem? Please describe.**
There is no way to specify [field_multi_value_leniency](https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-search-api.html#sql-search-api-request-body) for SQL APIs

**Describe the solution you'd like**
A Method where you can put the field_multi_value_leniency to true .

**Describe alternatives you've considered**
A Method to add other optional fields to the request body, defined in the api.

**Comment by stevejgordon** [comment]
Thanks for highlighting this gap, @Szanik. We'll take a look at adding support for this in a future 7.x release.
