### ISSUE TITLE
NEST 1.0 - What is the new .MapFromAttributes()?

### ISSUE THREAD

**Issue by rianjs** [elastic/elasticsearch-net#690]
I have some POCOs that're decorated with attributes. Inside they look like this:

``` csharp
[Serializable]
[ElasticType(DisableAllField = true, IdProperty = ElasticsearchFields.FullUncPath)]
public class ShareDriveDocument
{
    [ElasticProperty(Name = ElasticsearchFields.Id, Type = FieldType.string_type, Store = true, Index = FieldIndexOption.not_analyzed)]
    public string Id { get; internal set; }

    [ElasticProperty(Name = ElasticsearchFields.FullUncPath, Type = FieldType.string_type, Store = true, Index = FieldIndexOption.not_analyzed)]
    public string FullUncPath { get; internal set; }

    [ElasticProperty(Name = ElasticsearchFields.FileName, Type = FieldType.string_type, Store = true, Index = FieldIndexOption.not_analyzed)]
    public string FileName { get; internal set; }

    [ElasticProperty(Name = ElasticsearchFields.ParentDirectory, Type = FieldType.string_type, Store = true, Index = FieldIndexOption.not_analyzed)]
    public string ParentDirectory { get; internal set; }

    [ElasticProperty(Name = ElasticsearchFields.DateCreated, Type = FieldType.date_type, Store = true, DateFormat = ElasticsearchDateFormats.NoMillis)]
    public DateTime DateCreated { get; internal set; }

    [ElasticProperty(Name = ElasticsearchFields.DateModified, Type = FieldType.date_type, Store = true, DateFormat = ElasticsearchDateFormats.NoMillis)]
    public DateTime DateModified { get; internal set; }

    [ElasticProperty(Name = ElasticsearchFields.SemanticFulltext, Type = FieldType.string_type, Store = true, IndexAnalyzer = "english")]
    public string SemanticFulltext { get; internal set; }

    [ElasticProperty(Name = ElasticsearchFields.ExactFulltext, Type = FieldType.string_type, Store = true, IndexAnalyzer = "not_analyzed")]
    public string ExactFulltext { get; internal set; }

    [ElasticProperty(Name = ElasticsearchFields.OriginalSize, Type = FieldType.long_type, Store = true)]
    public long OriginalFileSize { get; internal set; }

    [ElasticProperty(Name = ElasticsearchFields.TextSize, Type = FieldType.long_type, Store = true)]
    public long TextContentSize { get; internal set; }

    public ShareDriveDocument(IndexingJob indexingJob, string fulltext)
    {
        var fileInfo = new FileInfo(indexingJob.PathName);

        FullUncPath = indexingJob.PathName;
        FileName = Path.GetFileName(indexingJob.PathName);
        ParentDirectory = Path.GetDirectoryName(indexingJob.PathName);
        DateModified = fileInfo.LastWriteTimeUtc;
        DateCreated = fileInfo.CreationTimeUtc;
        SemanticFulltext = fulltext;
        ExactFulltext = fulltext;
        OriginalFileSize = fileInfo.Length;
        TextContentSize = fulltext.Length;
    }
    //...
}
```

Once upon a time, I could do this:

``` csharp
var client = new ElasticClient(connectionSettings);
//...
client.MapFromAttributes<ElasticsearchDocument>(TEST_INDEX, type);
```

But I can't anymore. `client.Map<ShareDriveDocument>(m => m.MapFromAttributes());` triggers a runtime error. I suspect this is because m.MapFromAttributes() is a 0.12.\* thing.

How do I accomplish this in 1.0?

**Comment by nasreekar** [comment]
@rianjs Hi rianjs.. Im trying to elastic property for my class variables and then use automap or map option for mapping. But when i use elastic property, it is throwing an error saying 

> "The type of namespace Elasticproperty could not be found(are you missing a using directive or assembly reference")

![image](https://cloud.githubusercontent.com/assets/13792317/15038093/79dfe124-12d3-11e6-83ce-4894da1ea42f.png)

 can you please help me with this... TIA

**Comment by russcam** [comment]
@nasreekar Take a look at the [NEST 2.x documentation](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/index.html), specifically the [documentation on Automapping](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/auto-map.html) and on [breaking changes between 1.x and 2.x.](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/breaking-changes.html)

**Comment by nasreekar** [comment]
@russcam  Hi Russ, As per the documentation they say class AttachmentMapping is removed. In that case how can I re-write the below  variable property? Can you please help me with this?
```
[String(Type = FieldType.Attachment, TermVector = TermVectorOption.WithPositionsOffsetsPayloads, Store = true, Index = FieldIndexOption.Analyzed)]
public Attachment File { get; set; }
```

**Comment by russcam** [comment]
@nasreekar You should use the fluent mapping in order to set an attachment type. [The tests have an example of the mapping that should help](https://github.com/elastic/elasticsearch-net/blob/2.x/src/Tests/Mapping/Types/Specialized/Attachment/AttachmentMappingTests.cs#L71). 

There is an `AttachmentAttribute` but since all of its properties are *not* primitive types, there is no way to set values for those properties in an attribute.

**Comment by nasreekar** [comment]
@russcam Thanks Russ. Does this work without using the ### AttachmentAttribute?

**Comment by nasreekar** [comment]
@russcam Thanks Russ. Does this work without using the AttachmentAttribute? Because Im trying to index the content of files in a folder(.pdf's,.docs etc). 

```
 class Attachment
    {
        public string Id { get; set; }

        public string Name { get; set; }

        [String(TermVector = TermVectorOption.WithOffsets)]
        public string Content { get; set; }
    }
```

and indexing is done using the below code:

```
 settings = new ConnectionSettings(pool)
             .DefaultIndex(defaultIndex)
             .MapDefaultTypeNames(m => m.Add(typeof(Attachment), "docs"));
```

And then for reading the content 

 ```
foreach (string file in Directory.GetFiles(path))
            {
                Attachment document = new Attachment
                {
                    Id = counter.ToString(),
                    Name = Path.GetFileNameWithoutExtension(file),
                    Content = Convert.ToBase64String(File.ReadAllBytes(file)),
                };
                counter++;
            }
```

I dont have any problem while indexing the documents and searching them with their Id's but the problem is with the content. It is displayed in ToBase64String Format and how can I search in the content of documents.

**Comment by russcam** [comment]
`Attachment` needs to be mapped as an `attachment` type [using fluent mapping](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/auto-map.html#auto-mapping-with-overrides) and the [mapper-attachments plugin](https://www.elastic.co/guide/en/elasticsearch/plugins/master/mapper-attachments.html) needs to be installed. The plugin uses [Apache Tika](http://tika.apache.org/) to allow searching on document fields mapped with `attachment` type.

If `Attachment` is not mapped as `attachment` type then it will be mapped as an `object` type by NEST in which case you will *not* be able to search across the document indexed as a Base64 string.

**Comment by nasreekar** [comment]
@russcam I installed the mapper attachments plugin. I think i am missing the "mapping it as an Attachment part."

**Comment by nasreekar** [comment]
@russcam  Hi Russ. Can you help me in mapping the 

> Attachment

 as an 

> attachment

as Im trying the attachment part for the first time and dont know how to proceed. In few of the SO answers, they created another class which will refer to Attachment class. I didnt understand why they are doing like that. Any help is appreciated. Thanks in advance

**Comment by nasreekar** [comment]
@russcam  I have used something like this.

```
 configvalue1 = ConfigurationManager.AppSettings["url"];
            var pool = new SingleNodeConnectionPool(new Uri(configvalue1));
            var defaultIndex = "reader";

var descriptor = new CreateIndexDescriptor(defaultIndex)
                .Mappings(ms => ms
                .Map<Attachment>(m => m
                .Properties(ps => ps
                        .String(s => s
                            .Name(e => e.Id)
                        )
                        .String(s => s
                            .Name(e => e.Name)
                        )
                        .Attachment(s => s
                            .Name(e => e.Content)
                        ))));
```
How do i pass this descriptor to settings so that client takes these mappings while creating.

previously i used this 

```
settings = new ConnectionSettings(pool)
             .DefaultIndex(defaultIndex)
             .MapDefaultTypeNames(m => m.Add(typeof(Attachment), "docs"));

and then 
 client = new ElasticClient(settings);
client.createIndex(defaultIndex);
```

But now how to continue after descriptor creation.

**Comment by nasreekar** [comment]
@russcam  Hi Russ, I tried to map the Attachment as an attachment type but still i couldnt search in the content. Can you please have a look at the code and tell where did i go wrong.

```
settings = new ConnectionSettings(pool);
 client = new ElasticClient(settings);
if (!client.IndexExists(defaultIndex).Exists)
            {
                client.CreateIndex(defaultIndex,c=>c
                    .Mappings(ms=>ms
                    .Map<Document>(m=>m
                    .Properties(ps=>ps
                        .Number(n=>n
                            .Name(e=>e.Id)
                        )
                        .String(s => s
                            .Name(e => e.Title)
                        )
                        .Attachment(s => s
                            .Name(e => e.File)
                            
                    )))));
            }
```

**Attachment class**

```
 class Attachment
    {
        [String(Name = "name")]
        public string Name { get; set; } //name of the document

        [String(Name = "content")]
        public string Content { get; set; } //content of the document

        [String(Name = "content_type")]
        public string ContentType { get; set; } //pdf or doc or etc
    }
```

**Document Class**

```
class Document
    {
        public int Id { get; set; }
        public string Title { get; set; } 
        public Attachment File { get; set; } 
    }
```
**Main Program**

            ```
List<Document> list = new List<Document>();
            string path = @"D:\ES\Documents";

            foreach (string file in Directory.GetFiles(path))
            {
                Attachment attach = new Attachment
                {
                    Name = Path.GetFileNameWithoutExtension(file),
                    Content = Convert.ToBase64String(File.ReadAllBytes(file)),
                    ContentType = Path.GetExtension(file)
                };

                var doc = new Document()
                {
                    Id = counter,
                    Title = "First Try",
                    File = attach
                };

                list.Add(doc);

                counter++;
            }

            client.IndexMany(list, "filesreader", "docs");
```

**Comment by russcam** [comment]
@nasreekar what version of NEST are you using and what version of Elasticsearch are you running against?

**Comment by nasreekar** [comment]
@russcam 
![image](https://cloud.githubusercontent.com/assets/13792317/15063078/8616164c-1379-11e6-9311-fcbf57da4ef2.png)

**Comment by russcam** [comment]
What version of Elasticsearch are you running against?

**Comment by nasreekar** [comment]
@russcam 2.3.1
![image](https://cloud.githubusercontent.com/assets/13792317/15063311/afff760e-137b-11e6-9338-ae1f4c40aee7.png)

**Comment by russcam** [comment]
@nasreekar I've opened #2085 to better handle attachments.
