### ISSUE TITLE
[FEATURE] Support cumulative_sum aggregations

### ISSUE THREAD

**Issue by hughbe** [elastic/elasticsearch-net#7049]
I’m trying to migrate a library from 7.x to 8.x. However, I cannot find support the `cumulative_sum` aggregation in the new version of the library.

Will support for this aggregation be added?

**Comment by stevejgordon** [comment]
Hi, @hughbe.

This is not currently available in the 8.0.0 as documented in our [supported aggregations](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/release-notes-8.0.0.html#_supported_aggregations) in our release notes. We will (re)introduce this (and other) aggregation types in future client releases. Thanks for raising your need for this type, as it helps prioritise that work.
