### ISSUE TITLE
Floating-point types are not always serialized with a decimal point

### ISSUE THREAD

**Issue by Alkaersig** [elastic/elasticsearch-net#7051]
**Elastic.Clients.Elasticsearch version**:
8.0.2

**Elasticsearch version**:
8.5.0

**.NET runtime version**:
6.0

**Operating system version**:
Windows 11

**Description of the problem including expected versus actual behavior**:
Ran into another problem while migrating one of our smaller projects to v8. Trying to index a range of documents i got an error that [float] could not be converted to [long]. Inspecting the request, it turns out that whenever a floating-point value does not have a decimal part, it is serialized as an int (without a decimal point/radix). 

I guess this problem was introduced by the new Serializer in the v8 client. This was fixed some years ago back in v7:
https://github.com/elastic/elasticsearch-net/issues/3657

**Steps to reproduce**:
1: Create a simple document
```
public class FloatDocument
{
  public decimal Amount { get; set; }
}
```

2: Insert a range of documents with a mix of integers and decimal numbers:
```
var data = new List<FloatDocument>();
data.Add(new FloatDocument() { Amount = 11 });
data.Add(new FloatDocument() { Amount = 1.15M });
data.Add(new FloatDocument() { Amount = 3.76M });

await esClient.IndexManyAsync<FloatDocument>(data, "index");
```

3: Returns an error: mapper [amount] cannot be changed from type [float] to [long]" since it serializes to:
```
[{
  Amount: 11
},
{
  Amount: 1.15
},
{
  Amount: 3.76
}]
```

**Expected behavior**
Floating-point types should always be serialized as floating-point types (serialized with a decimal point).

**Comment by stevejgordon** [comment]
Thanks for raising this, @Alkaersig. I certainly see the problem this can introduce. We'll need to consider introducing custom converters to work around the choices made in `System.Text.Json` for such numbers. A workaround, for now, is to explicitly map fields in advance for the expected number type.

**Comment by Alkaersig** [comment]
Hi @stevejgordon 

Thanks for coming back on this. I already attempted the workaround, mapping our decimals to float using a template that creates the mapping when the index is created, but when trying to index a decimal that has no decimal value (like 10 (10.0)) , we still get the error (a [long] cannot be mapped to a [float]).

So i guess there is more to this, since i would expect it to map just fine to a float, even though ES parses it as a long (well at least if the long-value is not bigger than the max value of a float).

**Comment by Alkaersig** [comment]
Hi @stevejgordon 

Just a little Christmas update. 

We actually got it working now after updating from RC2 to 8.0.2 and mapping the field to float manually using index_templates. So the workaround do work after all. 

So the issue only arises using auto-field-mapping when a long-value is encountered before a float (thus the field is mapped as long) which obviously does not support float-values :)

**Comment by stevejgordon** [comment]
Thanks for the update, @Alkaersig. That's good to know. It would also be possible to define your own custom `System.Text.Json` converter to assign to your properties to control their serialization.
