### ISSUE TITLE
[FEATURE] Support bucket_sort aggregations

### ISSUE THREAD

**Issue by vladimir-ilnytskyi** [elastic/elasticsearch-net#7055]
We really want to use newer version because of serializer speed AND really depend on this agg.
When is estimated release?

**Elastic.Clients.Elasticsearch version**: 8.0.1

**Elasticsearch version**: 8.5.x

**.NET runtime version**: .net6

**Operating system version**: not applicable

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:
no query language for bucket_sort, found in source code this:
case “avg_bucket”:
throw new Exception(“The aggregate in response is not yet supported.“);
case “bucket_script”:
throw new Exception(“The aggregate in response is not yet supported.“);
case “bucket_count_ks_test”:
throw new Exception(“The aggregate in response is not yet supported.“);
case “bucket_correlation”:
throw new Exception(“The aggregate in response is not yet supported.“);
case “bucket_selector”:
throw new Exception(“The aggregate in response is not yet supported.“);
case “bucket_sort”:
throw new Exception(“The aggregate in response is not yet supported.“);

**Expected behavior**
support added

**Comment by stevejgordon** [comment]
Hi, @vladimir-ilnytskyi.

This is not currently available in the 8.0.0 as documented in our [supported aggregations](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/release-notes-8.0.0.html#_supported_aggregations) in our release notes. We will (re)introduce this (and other) aggregation types in future client releases. Thanks for raising your need for this type, as it helps prioritise that work.

**Comment by vladimir-ilnytskyi** [comment]
Hello!

Thanks for the reply!
Any rough estimations on when this is planned to be implemented in beta?

**Comment by stevejgordon** [comment]
@vladimir-ilnytskyi I can't provide any timeframes at the moment.
