### ISSUE TITLE
7.10.0 .Net Filtering in a nested sort does not get applied

### ISSUE THREAD

**Issue by PoisonousMushroom** [elastic/elasticsearch-net#7056]
**NEST/Elasticsearch.Net version**: 7.10.0

**Elasticsearch version**: 8.4.3

**.NET runtime version**: 6.0

**Operating system version**: Windows 10

**Description of the problem including expected versus actual behavior**:
When using Nested Filter within a sort it is expected that the filter get's applied over the values being sorted on so that only the ones respecting the condition are sorted on. Instead, the nesting is applied, but not the filter

**Steps to reproduce**:
Specific case is sorting entities based on an array of descriptors that are localized

 `sortQuery = s => s
                                .Field(f => f
                                    .Field(sortPath)
                                    .Order(order)
                                    .Nested(n => n
                                        .Path(nestedPath)
                                        .Filter(fi => fi.Term(t => t.Name($"{nestedPath}.languageCode.keyword").Value(acceptLanguages)))
                                        )
                                    );`

**Expected behavior**
Expected to get generated code 

` "sort": [
        {
            "variations.genres.genreTranslations.displayName.keyword_lowercase": {
                "nested": {
                    "path": "variations.genres.genreTranslations",
                   "filter": {
                      "term": {
                        "variations.genres.genreTranslations.languageCode.keyword": "en-US"
                      }
                    }
                },
                "order": "desc"
            }
        }
    ]` 

Received instead

` "sort": [
        {
            "variations.genres.genreTranslations.displayName.keyword_lowercase": {
                "nested": {
                    "path": "variations.genres.genreTranslations"
                },
                "order": "desc"
            }
        }
    ]`

**Comment by stevejgordon** [comment]
Hi, @PoisonousMushroom,

Your example specifies a `Name` for the filter query, but I think you meant to specify the `Field`. As a result, the incomplete filter is not serialised. I think you want:

```c#
.Sort(s => s.Field(f => f.Field("a_field").Order(SortOrder.Descending).Nested(n => n.Path(nestedPath).Filter(fi => fi.Term(t => t.Field($"{nestedPath}.languageCode.keyword").Value("en-US"))))))
```

Does that answer your question?

**Comment by PoisonousMushroom** [comment]
@stevejgordon  Oh my! That was indeed it! Thank you for the help. I was staring at the code for so long, I overlooked that completely
