### ISSUE TITLE
README's release notes and migration guidance points to 404

### ISSUE THREAD

**Issue by PsychoBoy11** [elastic/elasticsearch-net#7129]
Hello, I found that this repository's README.md ([here](https://github.com/elastic/elasticsearch-net#elasticsearch-8x-clusters)) mentions [release notes and migration guidance](https://elasticsearch-net_7008.docs-preview.app.elstc.co/guide/en/elasticsearch/client/net-api/current/release-notes-8.0.0.html) which points to 404 page.

**Comment by stevejgordon** [comment]
Thanks for raising this, @PsychoBoy11.
