### ISSUE TITLE
[FEATURE] Support Tasks endpoints

### ISSUE THREAD

**Issue by RolfDeVries** [elastic/elasticsearch-net#7166]
**Elastic.Clients.Elasticsearch version**:
8.x

**Elasticsearch version**:
8

**.NET runtime version**:
netcore 6

**Operating system version**:
Windows

**Description of the problem including expected versus actual behavior**:
I know the new Elastic.Clients.Elasticsearch is not feature complete yet.
But i would very much like to have the Tasks API in a future version
Also the range and daterange queries seem to be missing.

**Steps to reproduce**:
 1.
 2.
 3.

**Expected behavior**
Please add requested features in a future verion

**Comment by stevejgordon** [comment]
Thanks for raising this @RolfDeVries. We currently don't generate experimental (beta) APIs, but we can review options for supporting these in the client.
