### ISSUE TITLE
Serialization options (IgnoreCycles)

### ISSUE THREAD

**Issue by KoalaBear84** [elastic/elasticsearch-net#7237]
**Is your feature request related to a problem? Please describe.**
Cannot serialize objects with cyclic references.

**Describe the solution you'd like**
An option to add/set IgnoreCycles.

**Describe alternatives you've considered**
Serialize it myself, but then it will not respect the elasticSearch default naming conventions etc.

**Additional context**
https://discuss.elastic.co/t/elastic-clients-elasticsearch-8-x-custom-serialization/324435

```A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 64. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles. Path: $.ModifiedFields.Old.Languages.Parent.Parent.Parent.Parent.Parent.Parent.etc```

**Comment by stevejgordon** [comment]
@KoalaBear84, thanks for raising this. I will close it as it's covered in #7238 and something we are looking to support.
