### ISSUE TITLE
[FEATURE] Index Lifecycle Management

### ISSUE THREAD

**Issue by seruss** [elastic/elasticsearch-net#7242]
Please add in v8 client API features that were previously in v7 in Elasticsearch.Net.Specification.IndexLifecycleManagementApi namespace.

https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-management.html

**Comment by stevejgordon** [comment]
@seruss Thanks for raising this to highlight your need for this area of the API. Are there any specific endpoints which would be most useful for your use case(s)?

**Comment by seruss** [comment]
@stevejgordon yes, the most important for me is PUT on /_ilm/policy/{policy_id}

**Comment by stevejgordon** [comment]
Blocked until the [spec](https://github.com/elastic/elasticsearch-specification/blob/main/specification/ilm/_types/Phase.ts#L45) is updated to represent the possible externally tagged actions.
