### ISSUE TITLE
Documentation is a huge issue

### ISSUE THREAD

**Issue by jacob-winkler** [elastic/elasticsearch-net#7243]
**Is your feature request related to a problem? Please describe.**
Trying to use an API client for an expansive toolset like Elasticsearch without in depth documentation is highly painful.

**Describe the solution you'd like**
With the understanding that there's almost no documentation of the individual methods and features for the new client, it should be made clear that a lot of the documentation from the NEST days is still applicable. Better yet, reuse the NEST documentation where applicable, update the method names that have changed but are functionally equivalent, and slap an `8.x` label on it.

**Describe alternatives you've considered**
There aren't a lot of alternatives to missing documentation other than trial and error. And that is an oh so tedious process.

**Comment by jacob-winkler** [comment]
Documentation on fluent syntax would be nice, as that seems to have changed considerably.

**Comment by stevejgordon** [comment]
Hi, @jacob-winkler. I wholly agree the documentation is essential, and I'm keen to flesh that out and improve on what we've provided historically. The focus has been on delivering the initial version of the new client, ironing out kinks and planning the roadmap for missing features. Behind the scenes, I've been building a prioritised list of the missing documentation, which will probably become a roadmap issue at some point.

**Comment by jacob-winkler** [comment]
I find it odd that this wasn’t part of the initial release. I’ve been auditing my team’s code base as we seek alternatives to the deprecated NEST library, and unfortunately it’s very difficult to recommend using the new 8.x .NET client at this point without documentation to accompany the library. This is a make or break issue and is probably going to be the single deterrence from choosing this library as our solution, potentially meaning a move to something like OpenSearch instead.

**Comment by stevejgordon** [comment]
I'm sorry to hear it's put you off @jacob-winkler. Hard choices must be made all the time, and we chose to release an initial feature-limited, early version of the new client for those keen to get their hands on it. As discussed in the release notes, we don't consider this migration ready for many scenarios but are working hard to close the gaps in the core areas. Documentation is an important part of that and something I'm passionate about. You've mentioned the fluent syntax documentation. Are there other key topics you were looking for? I'd like to prioritise spending time in those areas we have evidence are most challenging and unclear.

If you missed it, you could use the 7.17 client in compatibility mode with the v8 server until this client and its documentation are more feature complete.

**Comment by stefanobranco** [comment]
@stevejgordon Is there even a little more info about timeframes for these things? I understand hard choices must be made sometimes. I also understand the constraints of these choices are often times not set by those have to who make them, so I'm not trying to blame anyone. At the same time, it's a source of incredible frustration for us that while Elastic is now on 8.6, we're still stuck on either a legacy client in compatibility mode, or a feature incomplete and sparsely documented client with, at least from the outside, not that much activity. While I'm happy to hear these things are on your radar, it seems like we should be a little beyond roadmaps and priority lists at this point.

Once again, I'm not trying to pin this on you or anyone, and I appreciate the work you do, but it's hard not feel (at least for us) like this client, and by extensions Elastics .NET customers and users, do not get the attention they deserve.

**Comment by meriturva** [comment]
@stefanobranco you are right and your words are entirely accurate. I'm working right now on our code and the lack of documentation and feature is blocking our porting to 8.x version.

**Comment by svenhartmann** [comment]
@stevejgordon It would be nice to have some examples for mocking a response inside tests with the new 8.x client. With NEST i was able to mock a response like in the examples below in my tests using moq:

Example for simulate a server error, e.g. Unauthorized Access
```csharp
Mock<ISearchResponse<ProductResponse>> searchResponseMock = new();
searchResponseMock.SetupGet(x => x.ServerError).Returns(new ServerError(new Error(), 401));
this.elasticClientMock.Setup(x =>
    x.SearchAsync<ProductResponse>(It.IsAny<SearchDescriptor<ProductResponse>>(),
        It.IsAny<CancellationToken>())).ReturnsAsync(searchResponseMock.Object);
```


Example for mocking a response to test my handler to create the correct response based on the returned data of elastic:

```csharp
var productResponse = new ProductResponse
{
    Id = "123",
    Description = "Yolo Product 133",
};

Mock<ISearchResponse<ProductResponse>> searchResponseMock = new();
searchResponseMock.Setup(x => x.Documents).Returns(new List<ProductResponse>() { productResponse });

this.elasticClientMock.Setup(x =>
    x.SearchAsync<ProductResponse>(It.IsAny<SearchDescriptor<ProductResponse>>(),
        It.IsAny<CancellationToken>())).ReturnsAsync(searchResponseMock.Object);
```

Both examples worked fine and i could also verify if a property was called or not. For example if i set the `Documents` property to an empty list i was able to check verify my code did the early return based on the hits of zero.
```csharp
searchResponseMock.Verify(x => x.Took, Times.AtLeastOnce);
searchResponseMock.Verify(x => x.Hits, Times.AtLeastOnce);
searchResponseMock.Verify(x => x.Documents, Times.Never);
```

Currently i have absolute no idea how to create a `SearchResponse` with the Property `ElasticsearchServerError`. 

For a `SearchResponse` containing documents it could be working to serialize and deserialize a json payload, correct?

**Comment by b93rn** [comment]
I'm extremely disappointed in the way you handled this transition to a new client ass well. 
I could see the point if there was yet no documentation if the client stayed almost the same and if it worked fine. But now we have neither of these things.

I'm basically forced to use the 8.* client, since i need the KnnQuery feature.

**Comment by svenhartmann** [comment]
> I'm extremely disappointed in the way you handled this transition to a new client ass well. I could see the point if there was yet no documentation if the client stayed almost the same and if it worked fine. But now we have neither of these things.
> 
> I'm basically forced to use the 8.* client, since i need the KnnQuery feature.

You can easly use the "normal documentation" with the raw JSON Queries and adapt those to the .NET Client. I don´t see the problem here. Did a lot of migrations the last week from NEST to the 8.x client and mostly never missed documentation.

**Comment by b93rn** [comment]
> > I'm extremely disappointed in the way you handled this transition to a new client ass well. I could see the point if there was yet no documentation if the client stayed almost the same and if it worked fine. But now we have neither of these things.
> > I'm basically forced to use the 8.* client, since i need the KnnQuery feature.
> 
> You can easly use the "normal documentation" with the raw JSON Queries and adapt those to the .NET Client. I don´t see the problem here. Did a lot of migrations the last week from NEST to the 8.x client and mostly never missed documentation.

I'm working here with a fully typed search service that i am trying to migrate to the new client. I don't wanna be rude to you, but what's the point of using a typed client with raw JSON queries? With that strategy i rather call the the API myself.

**Comment by sethmlarson** [comment]
@b93rn Also wanted to note that I read @svenhartmann's comment to mean adapting the REST API documentation JSON/parameters into .NET code, not using raw JSON directly. @svenhartmann you can confirm if this is what you meant. The new .NET client very closely mirrors the actual Elasticsearch API, so this process should be much easier compared to trying to do the same for past clients. Hope this helps!

**Comment by svenhartmann** [comment]
> @b93rn Also wanted to note that I read @svenhartmann's comment to mean adapting the REST API documentation JSON/parameters into .NET code, not using raw JSON directly. @svenhartmann you can confirm if this is what you meant.
> 
> The new .NET client very closely mirrors the actual Elasticsearch API, so this process should be easier compared to trying to do the same for past clients. Hope this helps!

Correct. It is more or less a no brainer in my opinion to adapt a json query from the documentation examples to the new .NET 8.x client (if the feature is implemented yet).

And yes, i saw some API changes but those are also no brainers; example:

```csharp
- var minValue = searchResponse.Aggregations.Min("blaMin")?.Value,
- var maxValue = searchResponse.Aggregations.Min("blaMax")?.Value,
+ var minValue = searchResponse.Aggregations?.GetMin("blaMin")?.Value,
+ var maxValue = searchResponse.Aggregations?.GetMax("blaMax")?.Value,
```

**Comment by b93rn** [comment]
I'am not really sure what you guys mean. Can you give a small example of this style?

**Comment by stevejgordon** [comment]
We've opened a new meta issue to track planned/missing documentation. As such, we will close this issue.
