### ISSUE TITLE
Nest.SuffixExtensions.Suffix type annoyance

### ISSUE THREAD

**Issue by catmanjan** [elastic/elasticsearch-net#7284]
Its annoying when using the Suffix feature for fields that the type is not presevered, e.g. 

`Infer.Field<ElasticDocument>(f => f.Title)`

is type Field

`Infer.Field<ElasticDocument>(f => f.Title).Suffix("raw")`

is type object

**Comment by stevejgordon** [comment]
@catmanjan The suffix extension is intended for use inside the expression, evaluated by NEST. As such, your code should be...

```c#
Infer.Field<ElasticDocument>(f => f.Title.Suffix("raw"));
```
