### ISSUE TITLE
Execute raw query / filter

### ISSUE THREAD

**Issue by abeninski** [elastic/elasticsearch-net#7285]
**Is your feature request related to a problem? Please describe.**
I want to be able to execute range queries and I noticed this issues https://github.com/elastic/elasticsearch-net/issues/7050 so I tried to find how to execute raw query but, I don't see a way to do it in v8.

**Describe the solution you'd like**
Can you please add the ability to add raw query / filter like it used to be in previous version so we can easily go around problems like that?

**Describe alternatives you've considered**
The only alternative so far is to fork the repository.

**Comment by meriturva** [comment]
I think we have to use `Transport`:

https://github.com/elastic/elasticsearch-net/blob/4ff277ebca2c731c8450f1d537fe175fe12d9edc/src/Elastic.Clients.Elasticsearch/Client/ElasticsearchClient.cs#L83

**Comment by stevejgordon** [comment]
@abeninski Thanks for your feedback. I have a PR in to implement this fallback option.

**Comment by stevejgordon** [comment]
@meriturva It's best to ask questions on [discuss.elastic.co](https://discuss.elastic.co/) and not an unrelated issue, as they may be missed. You are correct; there is no specific low-level client, and using Transport directly is the correct option if you want to send raw JSON requests and responses to a cluster.
