### ISSUE TITLE
Any way to use minimum_should_match in NEST Match queries?

### ISSUE THREAD

**Issue by Aaronaught** [elastic/elasticsearch-net#741]
According to the [ElasticSearch documentation](http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/query-dsl-match-query.html), `minimum_should_match` is supported on all `match` queries, but does not appear to be supported in NEST.

It seems like I should be able to write something like:

``` c#
return query.Match(match => match
    .OnField("_all")
    .Query(keywords)
    .MinimumShouldMatch("2<80%")
);
```

But of course I cannot... the last line isn't in the API for `MatchQueryDescriptor<T>`.

Shouldn't it be part of that API? Is there some other way to add `minimum_should_match` to the query?

(P.S. I know it's supported by the NEST API in Boolean and Query String clauses, but that doesn't help me here.)

**Comment by jbejar** [comment]
I believe this should be added for the Simple Query String as well: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html

**Comment by vikingland2018** [comment]
Damn, I've been struggling with this for a day why isn't this on the issue list? MinimumShouldMatch is clearly still not working.

**Comment by russcam** [comment]
@vikingland2018 `MinimumShouldMatch` is implemented on the following queries in NEST 5.x and 6.x:

- match queries
- multi match queries
- simple query string queries
- query string queries
- bool queries
- more like this queries
- common terms queries

What issue are you having with it?
