### ISSUE TITLE
[FEATURE] Support missing DecayFunctions in `FunctionScore`

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elasticsearch-net#7428]
Due to certain complexities with the `DecayFunction` union in the specification, the code generator is currently skipping these on the `FunctionScore` container type, which prevents the use of `gauss`, `exp` and `linear` functions. We need to solve this in the code generator so that these functions can be reintroduced in the 8.x client.

_Please update by adding a thumbs-up reaction to this comment if this is a blocker for you. This helps us prioritise the work on new features._

**Comment by oscarlofwenhamn** [comment]
Is there any way to, for example, inject manually written JSON into FunctionScore to make use of the decay functions, or is the realistic solution simply to use the 7.17.x client (as recommended in the project README), in the case where decay functions are required?

**Comment by JanToreKyrdalen** [comment]
Is this still not adressed?

**Comment by flobernd** [comment]
@JanToreKyrdalen The code generator is currently being reworked to address this and other issues. A rough estimation for completion is end of Q1 2024.

**Comment by luisvsilva** [comment]
Any update on this?

**Comment by eCorke** [comment]
So, how's it going? It's been a year and three months from the original post, and 6 moths since Q1 2024 rough estimates. Any good news?

**Comment by flobernd** [comment]
This is currently blocked until we decided about: https://github.com/elastic/elasticsearch-specification/issues/2545

**Comment by flobernd** [comment]
Implemented in 8.14.4
