### ISSUE TITLE
[FEATURE] Add client overloads accepting descriptors

### ISSUE THREAD

**Issue by b93rn** [elastic/elasticsearch-net#7475]
**Elastic.Clients.Elasticsearch version**:
8.08

Why do i need an Action<SearchRequestDescriptor<T>> like shown below?

public virtual Task<SearchResponse<TDocument>> SearchAsync<TDocument>(Action<SearchRequestDescriptor<TDocument>> configureRequest, CancellationToken cancellationToken = default);

Request: 
Add overload <SearchRequestDescriptor<T>  as the NEST client had.

**Comment by svenhartmann** [comment]
I also missed this but the migration from a NEST  `SearchDescriptor` to a 8.x `SearchRequest` with Object initializer syntax can be done in a short amount of time. 

Maybe this helps you to get your work done without having the feature yet.

**Comment by b93rn** [comment]
> I also missed this but the migration from a NEST `SearchDescriptor` to a 8.x `SearchRequest` with Object initializer syntax can be done in a short amount of time.
> 
> Maybe this helps you to get your work done without having the feature yet.

This comment might push me in the right direction. My thoughts were that SearchReqeustDescriptor is the equivalent of SearchDescriptor in NEST?
