### ISSUE TITLE
Add QueryDescriptor params actions and ICollection overload methods in 8.* client

### ISSUE THREAD

**Issue by b93rn** [elastic/elasticsearch-net#7603]
**Is your feature request related to a problem? Please describe.**
Since operators are yet not supported #7594, i currently rely on overload methods that have:
`ICollection<Query>?` or `params Action<QueryDescriptor<TDocument>>[] configure`

QueryDescriptor does no have these. E.g: QueryDescriptor.Bool.

**Describe the solution you'd like**
Add: 

-  `public QueryDescriptor<TDocument> Bool(params Action<BoolQueryDescriptor<TDocument>> configure);`
-  `public QueryDescriptor<TDocument> Bool(ICollection<BoolQuery> boolQuery);`

**Comment by stevejgordon** [comment]
@b93rn The `Query` type is a "container" for a single query, so these overloads don't make sense here. We've added operator support for object initializer syntax, which will release in 8.1. Fluent support for operators is more complex and will be reviewed for inclusion in a future release. You can still construct a bool query using the fluent syntax, but you must set the "Should", "Must", etc. queries you require.
