### ISSUE TITLE
[FEATURE] Support AND operator for `SearchAggregation`

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elasticsearch-net#7616]
Consider porting the NEST operator implementation from `AggregationBase`.

To help us prioritise features, please add a thumbs-up to this issue if this is something you rely on to migrate to 8.x.

**Comment by flobernd** [comment]
This feature is no longer possible to implement with the new code design. Previously, the aggregation name was part of the individual aggregation variant. This is no longer the case, which means that a simple binary operator is not sufficient to express the tuple of [aggname1, aggvar] x [aggname2, aggvar2].
