### ISSUE TITLE
Latest Elastic Search Client 8.1.0 not compatible with Elastic.Transport. version greater than 0.4.3 

### ISSUE THREAD

**Issue by NeenaDadwal** [elastic/elasticsearch-net#7650]
I am working with Latest Elastic Search Client.
I found out an issue that , I am not able to search or delete or update data when i am using following versions together - 
Elastic.Clients.Elasticsearch - 8.1.0
Elastic.Transport - version greater than 0.4.3. 

I get the error as shown in the image attached. The piece of code that I am using is :

` var node = new Uri(ElasticApi);
            var settings = new ElasticsearchClientSettings(node).SkipDeserializationForStatusCodes(406).EnableDebugMode().PrettyJson();
            var client = new ElasticsearchClient(settings);
            var query = new QueryDescriptor();
            var expiredDate = DateTime.Now.AddDays(-60);
            var result = client.Indices.Get(IndexName);
            var response = client.DeleteByQuery<LogFile>(IndexName, d => d
                            .Query(q => q
                               .Range(r => r.DateRange(dr => dr.Field(p => p.StartTime).Lte(expiredDate))
                                )
                            ));
            if (!response.IsValidResponse)
            {
                Console.WriteLine("Elasticsearch response error. " + response.DebugInformation);
                Console.ReadKey();
            }`

![image](https://user-images.githubusercontent.com/35590716/231491605-4314ad07-b41c-45e8-87ca-587187dcbfed.png)

It worked fine with the following versions: 

Elastic.Clients.Elasticsearch - 8.1.0
Elastic.Transport -  0.4.3. 

Please let me know if any further information is needed. 

Thanks and Regards
Neena Dadhwal

**Comment by stevejgordon** [comment]
@NeenaDadwal, The latest client, has a transitive dependency on `Elastic.Transport` 0.4.8. It looks like you are running on .NET Framework. Please confirm which .NET framework version you are running. Which Elasticsearch server version is this? The server is rejecting the versioning header. The client only supports v8 servers.

**Comment by NeenaDadwal** [comment]
Following is the version for elastic search - 
{
  "name" : "7969f5329d11",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "7-Lk5qKQS8ahtVFv0CrH1A",
  "version" : {
    "number" : "7.5.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "e9ccaed468e2fac2275a3761849cbee64b39519f",
    "build_date" : "2019-11-26T01:06:52.518245Z",
    "build_snapshot" : false,
    "lucene_version" : "8.3.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

I am using **.Net Framework 4.8**

**Comment by stevejgordon** [comment]
Thanks for providing those details @NeenaDadwal. Based on that, you are running Elasticsearch 7.5. The v8 client is not backwards compatible with that version, and we do not support such usage. You should switch to the latest 7.17.x NEST client available on [NuGet](https://www.nuget.org/packages/NEST), which is compatible with the v7 Elasticsearch server versions. You can find [documentation for the v7](https://www.elastic.co/guide/en/elasticsearch/client/net-api/7.17/introduction.html) client on our website. I hope that helps you get started. If you have general questions, you can also post them on our [community forums](https://discuss.elastic.co/). Based on this information, I will close this issue.
