### ISSUE TITLE
The class ClusterGetSettingsResponse doesn't contain the Defaults property.

### ISSUE THREAD

**Issue by yansklyarenko** [elastic/elasticsearch-net#7666]
**NEST/Elasticsearch.Net version**: 7.17.5

**Elasticsearch version**: 7.17

**.NET runtime version**: net6.0

**Operating system version**: Windows 10

**Description of the problem including expected versus actual behavior**:
The class `ClusterGetSettingsResponse` doesn't contain the `Defaults` property. 

If I run a cluster get-settings request in the API console (`GET /_cluster/settings?include_defaults&flat_settings`), I get the JSON back which contains the `defaults` element. However, if I run the same call with the .NET API (`client.Cluster.GetSettingsAsync`), I only get the instance of `ClusterGetSettingsResponse` where the `Defaults` property is absent.

I can see that the newer version of the API (8.x), which is a different NuGet package, contains the class `GetClusterSettingsResponse` with the `Defaults` property. Is it possible to backport this functionality to 7.17.x version?

**Comment by stevejgordon** [comment]
Hi, @yansklyarenko.

Thanks for raising this. We can certainly review porting this back. The v8 code is generated, so we'll need to review any complexities over serialization logic etc. In the mean time, you can look to drop to the low-level client as a workaround if this is a blocker.

**Comment by yansklyarenko** [comment]
Low-level client! Right!
Thanks for the hint, @stevejgordon! Now this feature request has become even lower priority. :)
