### ISSUE TITLE
Nest is not aware of new private setting `index.history.uuid`

### ISSUE THREAD

**Issue by plachor** [elastic/elasticsearch-net#7675]
**NEST/Elasticsearch.Net version**:
v7.17.5

**Elasticsearch version**:
v7.9.*

**.NET runtime version**:
.NET7

**Operating system version**:
-

**Description of the problem including expected versus actual behavior**:
Seems that in v7.9 of Elasticsearch there was a new setting being introduced `index.history.uuid` check for details: https://github.com/elastic/elasticsearch/pull/56930/files. Elastic search treats this setting as private one.

It looks like current version of Nest is not aware of this new private setting and does not trim it when cloning index based on existing index settings, check: https://github.com/elastic/elasticsearch-net/blob/7.17.5/src/Nest/Indices/IndexManagement/CreateIndex/CreateIndexRequest.cs#L15.

**Steps to reproduce**:
I have not reproduced exact moment those settings were added to my indices but I believe this was caused by DevOps team that was migrating our data from AWS Elasticsearch service to self-hosted native instance. I assume here they have used some native Elistsearch client for Python to do so and most probably that client introduced new settings on new cluster.

Will you patch latest Nest with exclusions for this new private setting ?

**Comment by stevejgordon** [comment]
Thanks for raising this, @plachor. We should look to update our list of private settings from https://github.com/original-brownbear/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/common/settings/IndexScopedSettings.java#L217
