### ISSUE TITLE
`SqlRowConverter` does not implement `JsonConverter`

### ISSUE THREAD

**Issue by felix-stnr** [elastic/elasticsearch-net#7715]
**Elastic.Clients.Elasticsearch version**: 8.1.1

**Elasticsearch version**: 8.7.0

**.NET runtime version**: .NET 7.0.23

**Operating system version**: Windows 11

**Description of the problem including expected versus actual behavior**:
The `SqlRowConverter`, which is located within the `SqlRow` class (see [here](https://github.com/elastic/elasticsearch-net/blob/main/src/Elastic.Clients.Elasticsearch/Types/Sql/SqlRow.cs)) overrides the method `Write` from the `JsonConverter` base class. However, this method is not implemented yet and hence always throws a `NotImplementedException`. Thus, serializing the response will always lead to an exception. To fix this bug the `Write` method should be correctly overwritten/implemented.

Maybe this issue is related to #7713.

**Comment by stevejgordon** [comment]
Hi, @felix-stnr. Why are you serializing the response? The response types are only expected to be deserialized from the JSON sent by the server. We don't guarantee that they will be serializable unless used on requests.

**Comment by felix-stnr** [comment]
Hi there. The main reason why I wanted to serialize the response is that I want to forward it to another client, which relies on a specific JSON format. Since the `SqlRow` derives from the `JsonConverter` class, I expected the serialization to work out of the box. After always running into the same exception, I took a look at the code of the `SqlRow` and saw that this functionality was not implemented. But I guess implementing the serialization in the Elasticsearch .NET client directly would not align with the concept you just mentioned. Therefore, I am not sure anymore if this is actually an issue or just expected behavior.
Moreover, it turned out that handling the serialization in my own code is rather easy.
