### ISSUE TITLE
[FEATURE] Support ML Infer endpoint

### ISSUE THREAD

**Issue by virtualaidev** [elastic/elasticsearch-net#7717]
**Is your feature request related to a problem? Please describe.**
We're using ML for vector search, currently the below sample request does not have equivalent when implementing it .NET.

```
POST /_ml/trained_models/sentence-transformers__all-minilm-l12-v2/_infer
{
  "docs": {
    "text_field": "similar movies of resident evil"
  }
}
```

**Describe the solution you'd like**
```
var response = _client.MachineLearning.Infer(
  "sentence-transformers__all-minilm-l12-v2",
  new InferRequest <Document> {
    Docs = new List <Document> {
      new Document {
        TextField = "similar movies of resident evil"
      }
    }
  }
);
```

If we could have something like the above that would be a great help in using ML in .NET.

**Comment by flobernd** [comment]
I'm currently working on the code generator with the ultimate goal to bring back all missing endpoints and additionally support all new endpoints of 8.x.

As these code generator changes will allow me to pretty much generate all missing functionality in one go when it is done, I'm now closing all related feature request issues to clean up the issue tracker a little bit.
