### ISSUE TITLE
Sort by multiple fields

### ISSUE THREAD

**Issue by erik-kallen** [elastic/elasticsearch-net#7728]
**Is your feature request related to a problem? Please describe.**

It appears that there is no way to sort a query by multiple fields, which should be possible according to https://www.elastic.co/guide/en/elasticsearch/reference/current/sort-search-results.html.

**Describe the solution you'd like**
```
var response = _elasticsearchClient.Search<MyModelType>(r => r
    .Index("my-index)
    .Query(query)
    .Sort(s => s
        .Field(u => u.Field1)
        .Field(u => u.Field2)
    )
);
```

Currently this only sorts by `field2`, as the last configuration will overwrite the previous one instead of adding to it.

**Describe alternatives you've considered**
Could also be a separate method for multiple fields

**Comment by stevejgordon** [comment]
Hi @erik-kallen. There is an overload of sort accepting a `params Action<SortOptionsDescriptor<TDocument>>[]`, which you need to use here. In your current code, you're reconfiguring the same `SortOptionsDescriptor`, so only the final call applies to the final object. 

Your code should be:

```c#
var response = client.Search<MyModelType>(r => r
	.Index("my-index")
	.Query(query)
	.Sort(
		s => s.Field(u => u.Field1),
		s => s.Field(u => u.Field2)
	)
);
```

**Comment by erik-kallen** [comment]
Ah, thank you!
