### ISSUE TITLE
Error when serializing and deserializing ElasticsearchClientException

### ISSUE THREAD

**Issue by meninobirno** [elastic/elasticsearch-net#7744]
**Environment**
**NEST**: 7.17.5
**Elastic**:7.19.9
**dotnet**:6.0

When I serialize the ElasticsearchClientException using  NewtonsoftJson in version 13.0.3, I get the following error:

**Member 'HelpUrl' was not found**

Searching a little, I found that CustomExceptions need to have the attribute **[Serializable]**. To reproduce, you can use the following code:

`try
{
    var exceptionJson = JsonConvert.SerializeObject(new ElasticsearchClientException("test"));
    var exceptionDeserialized = JsonConvert.DeserializeObject<Exception>(exceptionJson);
}
catch (Exception ex)
{
    Console.WriteLine(ex);
}`

**Comment by stevejgordon** [comment]
Hi, @meninobirno.

Our custom exceptions have not been designed to be serializable. Exception serialization is primarily intended to support remoting, and support for remoting was dropped in .NET Core 1.0. The .NET team is taking this further and deprecating related types and attributes in .NET 7 and 8.

Therefore, I don't think this is a change we would now consider introducing. In your situation, you can grab any data you want (exception message), and add it to your own type, which you can control for serialization if required. Please let us know if there's a scenario we're missing where that is not practical.
