### ISSUE TITLE
The `DynamicTemplates` property of `BulkIndexOperation<T>` is of type `Dictionary<string, string>` when I would have expected (perhaps?) `ICollection<IDictionary<string, DynamicTemplate>>`

### ISSUE THREAD

**Issue by QuintinWillison** [elastic/elasticsearch-net#7748]
**Elastic.Clients.Elasticsearch version**: 8.1.1

**Elasticsearch version**: 8.7.1 (Cloud)

**.NET runtime version**: 7.0

**Operating system version**: Windows 11 Business

**Description of the problem including expected versus actual behavior**:
I'm trying to work out from your .NET APIs alone how to replace previous `Keyword` and `Date` attributes from a NEST v7 implementation, now that we've swapped in v8 .NET Client.
I found [your examples in Java](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/indexing-bulk.html), but of course the features they use aren't in .NET yet.
Is it possible to use [dynamic templates](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html) in the current state of the v8 .NET client for a bulk index operation, please?
I notice there is a lot of auto-generated code which looks like it may not actually be usable, but I may be wrong.
Lack of API docs for .NET is very frustrating.

**Steps to reproduce**:
```csharp
// create a number of these:
var operation = new BulkIndexOperation<TDocument>(document, indexName)
{
    DynamicTemplates = // WHAT CAN I INJECT HERE?
};

// add them all to a BulkOperationsCollection
// set that on BulkRequest's Operations property
// and then client.BulkAsync
```

**Expected behavior**
Some documentation or example for how I can specify `dynamic_templates` for a `BulkIndexOperation` in .NET v8 client, please.

**Provide `ConnectionSettings` (if relevant)**:
```csharp
var elasticCloudId = secrets.GetValue("ElasticCloudId");
var elasticApiKey = secrets.GetValue("ElasticApiKey");
client = new(elasticCloudId, new ApiKey(elasticApiKey));
```
(it just works, and does bulk index using those `BulkIndexOperation` instances I'm creating, if I don't include that `DynamicTemplates` property ... it's just that I need to configure those!)

**Provide `DebugInformation` (if relevant)**:
None available as I can't even work out how to compile something!

**Comment by flobernd** [comment]
Hi, sorry for the lack of documentation. The specification mentions the following for the `dynamic_templates` field:

```ts
/**
   * A map from the full name of fields to the name of dynamic templates.
   * Defaults to an empty map.
   * If a name matches a dynamic template, then that template will be applied regardless of other match predicates defined in the template.
   * If a field is already defined in the mapping, then this parameter won’t be used.
   */
```

Does that answer your question?

**Comment by QuintinWillison** [comment]
Thanks for responding but I'm a million miles out of context by this point, so I can't tell you if this would have answered the question, nor do I have time to check now. We ended up not using Elastic at all, so I'm happy to close this issue as no longer needed or able to report in more detail.
