### ISSUE TITLE
ElasticsearchClient RequestResponseSerializer deserialization not setting value of wildcard query

### ISSUE THREAD

**Issue by Leandore** [elastic/elasticsearch-net#7750]
**Elastic.Clients.Elasticsearch version**: 8.1.1

**Elasticsearch version**: 8.7.0

**.NET runtime version**: .Net 7

**Operating system version**: Windows 10

**Description of the problem including expected versus actual behavior**:
When deserializing a wild card search query using the `RequestResponseSerializer.Deserialize` method on `ElasticsearchClient`, the value of query is not being (although the name of the filter is). The expected outcome, to my understanding, is that the `WildcardQuery` value property should contain the provided search query.

**Steps to reproduce**:
 1. Create any wildcard query
 2. Serialize request to MemoryStream
 3. Create a search request using `client.RequestResponseSerializer.Deserialize`
 4. Inspect the SearchRequest.Query.Filter.Value
 5. The value of the filter here is null
![image](https://github.com/elastic/elasticsearch-net/assets/8113597/6f45d8b8-83f1-4e79-a416-ec6d7765ca75)

Please see working example of issue https://github.com/Leandore/ElasticSearch8/blob/deserialize-issue-investigation/ESClientExample/Program.cs#L61

**Expected behavior**
When providing a wildcard filter query, the value of the search query should be set according to the input.

Please see helper method to demonstrate missing value
https://github.com/Leandore/ElasticSearch8/blob/deserialize-issue-investigation/ESClientExample/Program.cs#L26-L37

**Comment by Leandore** [comment]
Bump. I am happy to add more detail or make clarifications.

**Comment by flobernd** [comment]
Elasticsearch has very special behavior in some places. The .NET client currently does not support so called "shortcut properties". As an alternative, you can set the value like this:

```csharp
wildcard = new
{
    "displayName" =
    {
        "value" = "*"
    }
}
```

**Comment by flobernd** [comment]
That being said, what you are doing is generally unsupported. We do not guarantee that request classes can be **de**serialized. They are meant to be serialized only in most cases.

I would recommend to initialize the query using the API:

```csharp
var q = new WildcardQuery("displayName")
{
	Value = "*"
};
```

**Comment by flobernd** [comment]
Closing this for now as manual deserialization of requests is generally not supported.
