### ISSUE TITLE
Ping fails due to NullReferenceException after upgrading

### ISSUE THREAD

**Issue by VMelnalksnis** [elastic/elasticsearch-net#7752]
**Elastic.Clients.Elasticsearch version**: 8.1.1

**Elasticsearch version**: 8.6.1

**.NET runtime version**: 6.0

**Operating system version**: Windows 10 22H2

**Description of the problem including expected versus actual behavior**:
After upgrading to the new client, `Ping` method fails either with previous or minimal configuration.
While debugging I tracked it down to this line in `HttpTransportClient` method `public override TResponse Request<TResponse>(RequestData requestData)`:
```csharp
mimeType = responseMessage.Content.Headers.ContentType.ToString();
```
The exception is thrown because the response content does not have any headers.

**Steps to reproduce**:
 1. Create new `ElasticsearchClient` with the settings below
 2. Call `ElasticsearchClient.Ping()`
 3. See `UnexpectedTransportException` with inner `NullReferenceException`

**Expected behavior**
Ping succeeds.

**Provide `ConnectionSettings` (if relevant)**:
```csharp
new ElasticsearchClientSettings(Uri)
    .Authentication(new BasicAuthentication(userName, password));
```

**Comment by stevejgordon** [comment]
This has recently been fixed in https://github.com/elastic/elastic-transport-net/pull/78, and we will need to update to the latest patch to pick up this fix.

**Comment by VMelnalksnis** [comment]
Thanks, I was using the sync version to check the connection on creation instead of first use, but I'll check if it's possible to convert it to async.
