### ISSUE TITLE
Make it possible to get the serializer options used to serialize documents

### ISSUE THREAD

**Issue by erik-kallen** [elastic/elasticsearch-net#7754]
**Is your feature request related to a problem? Please describe.**
Sometimes we need to for example find the elastic field name that corresponds to a property. There are solutions to do this, but the nicest, non-duplicated way would be to ask the serializer that would actually be used for serializing the requests.

Also, if serializing requests (eg. for logs), the serializer needs to be set up correctly.

**Describe the solution you'd like**
There is an internal property `SystemTextJsonSerializer.Options`. Making this property public would solve the problem.

**Describe alternatives you've considered**
For example hacking around it by assuming that it uses a camel case naming strategy. Or private reflection. I don't like either of these alternatives particularly well.

**Comment by stevejgordon** [comment]
@erik-kallen I'm not keen on exposing the options as we found it caused some confusion for consumers about its use. We provide various levels of hooks to control source serialization, as documented here.

For your example, accessing options is insufficient as that only shows how the serializer is configured, which uses camel casing by default. However, control over property naming is also controllable via attributes as well.

For your case, I think calling our inferrer is likely a better way to achieve your goal.

```c#
Expression<Func<Person, object?>> expression = p => p.Age;
var name = client.Infer.PropertyName(new PropertyName(expression));
```
