### ISSUE TITLE
Join Field

### ISSUE THREAD

**Issue by emorin** [elastic/elasticsearch-net#7756]
The examples for join don't seem to work anymore for the 8.x version.  I can find .Join on properties, but there is no .Relationship.

Is this not ported over from 7.x?

**Comment by coding-bunny** [comment]
Would like to see this feature ported to V8 as well, because there's indeed no support for this right now.
And is actually one of the blocking reasons why we cannot upgrade our code to the new 8.x client.

**Comment by flobernd** [comment]
The `Relations` field is available again in 8.13.x.
