### ISSUE TITLE
Query by Date Range

### ISSUE THREAD

**Issue by jairo20088** [elastic/elasticsearch-net#7758]
We are switching  to elastic 8 and we currently have version 8.0.10. We were trying to add a filter for date range in our query and realize there is not date range query anywhere.  Base on what I figured out, date range query does not exist in this and that's how I figure is not there yet. Is there away to know when that functionality will be available ?
![Screenshot 2023-06-20 075912](https://github.com/elastic/elasticsearch-net/assets/47305335/f1917bf9-8e72-4d5b-aefe-ec08cc9ed9f8)

**Comment by stevejgordon** [comment]
@jairo20088 We added support for range queries in [8.1.0](https://github.com/elastic/elasticsearch-net/releases/tag/8.1.0), so I suggest using the latest release of the client to get this feature.
