### ISSUE TITLE
Support Altitude/Z in ES 8

### ISSUE THREAD

**Issue by EngineerCoding** [elastic/elasticsearch-net#7780]
**Is your feature request related to a problem? Please describe.**
In the ES 7 NEST Client we could create a GeoCoordinate including a Z/altitude. This currently is not possible in the ES8 client natively.

**Describe the solution you'd like**
Support for altitude/Z in the geo objects, for example in the `LatLonGeoLocation`.

**Describe alternatives you've considered**
I am considering to write something up to make my code compatible, but I am not sure if that is possible at the time of writing this issue. Will update this issue if I have found something.

**Comment by flobernd** [comment]
Hi, 

just to clarify: Are you talking about the ability to store an optional `altitude` (which is not indexed) like mentioned in the description of the `ignore_z_value` parameter?

https://www.elastic.co/guide/en/elasticsearch/reference/8.8/geo-point.html

If I understood you correctly, you used the NEST client to hand-craft a payload that included this value and now with the v8 client there currently is no way to achieve the same, right?

**Comment by EngineerCoding** [comment]
Hi, yes I am talking about that particular feature. However, with the NEST client we had a GeoCoordinate object which took an optional z value, which is now missing. The LatLonCoordinate object (or how it actually is called with the current client) does not allow for this optional argument.

**Comment by flobernd** [comment]
@EngineerCoding I'm currently checking, if the `LatLonGeoLocation` should have a nullable `z` field and I'll update you with the outcome of my research when I'm done.

For the time being, you could use the

```csharp
public static GeoLocation Coordinates(double[] coordinates)
```

factory method to create a `GeoLocation` union from an array. This overload accepts an optional `z` coordinate as the third element in the array.

Order of elements:  `[lon, lat, alt/z]`

**Comment by flobernd** [comment]
I confirmed that `LatLonGeoLocation` is not supposed to support a nullable `z` field. Closing this issue for now.
