### ISSUE TITLE
SearchRequestDescriptor ambiguity of Sort implementation

### ISSUE THREAD

**Issue by brokolica** [elastic/elasticsearch-net#7842]
**Elastic.Clients.Elasticsearch version**: 8.1.1

**Elasticsearch version**: 8.8.0

**.NET runtime version**: 7.0.203

**Operating system version**: Windows 11 Pro

**Description of the problem including expected versus actual behavior**:
There are two implementations of `Sort` method for `SearchRequestDescriptor` that cause ambiguous invocation error:
```
public SearchRequestDescriptor<TDocument> Sort(Action<SortOptionsDescriptor<TDocument>> configure) { .. }
public SearchRequestDescriptor<TDocument> Sort(params Action<SortOptionsDescriptor<TDocument>>[] configure) { .. }
```
An invocation of `Sort` with just one sorting `Action` is not possible. I think there should be the only implementation with `params`.

**Comment by flobernd** [comment]
I have to check this in detail. For now you could work around this issue by explicitly using the `params` overload:

```csharp
.Sort(new Action<SortOptionsDescriptor<TDocument>>[] { x => x... })
```

**Comment by flobernd** [comment]
@brokolica Could you please give a little bit more context to this issue? I was not able to reproduce any kind of "ambiguous invocation error" using `net7` or `net462`. For me, the compiler correctly uses the single item overload if I only pass one sort descriptor.

For explaination: 
We generate both variants for performance reason. When passing just a single item, we will avoid the implicit array allocation caused by using `params []` in this case.

**Comment by piotrek-k** [comment]
I've might come across the same problem
![image](https://github.com/elastic/elasticsearch-net/assets/5506878/fb443559-a828-4300-8269-a7ec50f6f1ed)

> Ambiguous invocation:   Elastic.Clients.Elasticsearch.SearchRequestDescriptor<DashboardApp.Services.ElasticSearch.Mappings.ConversationHistoryElasticMapping> Sort(params System.Action<Elastic.Clients.Elasticsearch.SortOptionsDescriptor<DashboardApp.Services.ElasticSearch.Mappings.ConversationHistoryElasticMapping>>[]) (in class SearchRequestDescriptor<ConversationHistoryElasticMapping>)   Elastic.Clients.Elasticsearch.SearchRequestDescriptor<DashboardApp.Services.ElasticSearch.Mappings.ConversationHistoryElasticMapping> Sort(System.Action<Elastic.Clients.Elasticsearch.SortOptionsDescriptor<DashboardApp.Services.ElasticSearch.Mappings.ConversationHistoryElasticMapping>>) (in class SearchRequestDescriptor<ConversationHistoryElasticMapping>) match
