### ISSUE TITLE
DistanceFeature is missing in the 8.x library

### ISSUE THREAD

**Issue by lyubomirhristovv** [elastic/elasticsearch-net#7860]
**Is your feature request related to a problem? Please describe.**
`DistanceFeature` seems to be missing in the new 8.x library, it was present in NEST.
And it is also in version 8.8 documentation, so there are no signs that this feature is getting retired.
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-distance-feature-query.html

**Describe the solution you'd like**
In NEST it was possible to access it through a `BoolQueryDescriptor`.
Ex: `descriptor.Should(s => s.DistanceFeature(dist => dist.Field(fld => fld.DateModified)...`
I see `GeoDistance` is a method in `QueryDescriptor<TDocument>`, so `DistanceFeature` could also be there.

**Describe alternatives you've considered**
Didn't find any workarounds for the moment.

**Additional context**
Checked the version 8.0 release notes -> missing features and it is not present there, so I'm not sure what are the plans for this feature.

**Comment by PeLe01** [comment]
Are there plans to include this in the near future? It's pretty useful in some scenarios for increasing accuracy.

**Comment by joshuaapple** [comment]
Upvote

**Comment by flobernd** [comment]
DistanceFeatureQuery is available in 8.14.4.
