### ISSUE TITLE
[FEATURE] Add Support for SimpleQueryStringQuery "flags" parameter in 8.x client

### ISSUE THREAD

**Issue by gise88** [elastic/elasticsearch-net#7863]
I'd like to request support for the [SimpleQueryString `flags`](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html#simple-query-string-top-level-params) parameter in v8.x. We're planning to upgrade to the ES 8 but some part of our project relies on this feature and it seems to be missing in this new client.

As part of the migration process, I'm performing a gap analysis and I noticed some other features are missing like [Filter aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-filter-aggregation.html) or JoinField (https://github.com/elastic/elasticsearch-net/issues/7756), and other that might come next days. 

Because of this need, I would also really love to contribute to this repo but after watching [this talk](https://www.youtube.com/watch?v=2AtNjxnwxZk) from @stevejgordon I fear the "converter" from [elasticsearch-specification](https://github.com/elastic/elasticsearch-specification) to [generated code](https://github.com/elastic/elasticsearch-net/tree/main/src/Elastic.Clients.Elasticsearch/_Generated) is still a private repository.. Could you please advise me on how to proceed with this request?
 
 Thank you in advance,
 Gianluca

**Comment by flobernd** [comment]
Hi @gise88!

Unfortunately you are right about the code generator aka "converter". The code generator repositories are highly coupled to our internal workflow, so opening them up would be a non-trivial task.

Some features can be implemented as handcrafted extensions (where it makes sense) as the generated files are mostly `partial`.

The `flags` field seems to be in the specification. I'll have to check why it's not generated.

**Comment by gise88** [comment]
Hey @flobernd! Thank you very much for the answer! 

Yep, I saw `SimpleQueryStringQuery` class is partial but that means I'll need to fork this library (since partials can only live in the same assembly) and create my own Nuget and maintain it, which of course is something we would like to avoid.

What if I [sing the CLA](https://www.elastic.co/contributor-agreement)? Can you then share the code generator to me? 😀

**Comment by flobernd** [comment]
> What if I [sing the CLA](https://www.elastic.co/contributor-agreement)? Can you then share the code generator to me? 😀

The CLA must be signed in order to contribute to our open source repositories, but signing it does not grant you access to any private repository. Unfortunately we can not make any exceptions here.

> Yep, I saw SimpleQueryStringQuery class is partial but that means I'll need to fork this library (since partials can only live in the same assembly) and create my own Nuget and maintain it, which of course is something we would like to avoid.

In this particular case it does not make sense to manually extend the class. I just checked and the generator is aware of the `flags`, but currently has no support for generation of `[Flags]` enums.

**Comment by gise88** [comment]
> The CLA must be signed in order to contribute to our open source repositories, but signing it does not grant you access to any private repository. Unfortunately we can not make any exceptions here.

I can say "unfortunately" as well but yeah, I fully understand .. and I had to try! 😄 

> In this particular case it does not make sense to manually extend the class. I just checked and the generator is aware of the flags, but currently has no support for generation of [Flags] enums.

I see! Even if I've already a workaround creating our own `SimpleQueryStringQuery` wrapper on top of the `RawJsonQuery`, can you give me an ETA for this implementation? I just need to discuss internally on how to proceed..

**Comment by flobernd** [comment]
> can you give me an ETA for this implementation?

I'm currently working on the code generator anyways, which means you could be lucky, but I won't promise anything 🙂 I will take a more detailed look next week in order to estimate and prioritize. Will come back to you afterwards!
