### ISSUE TITLE
PercentilesAggregation is missing in the 8.x client

### ISSUE THREAD

**Issue by gise88** [elastic/elasticsearch-net#7879]
**Is your feature request related to a problem? Please describe.**
Percentiles metrics aggregation  is missing in new client v8.*
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-aggregation.html

**Comment by gise88** [comment]
@flobernd Any news about this? Could you please provide an ETA? We're migrating old code, and this particular issue is causing a significant troubles! 😕

**Comment by flobernd** [comment]
This aggregation got reintroduced in #7923. Will be included in the next release.

**Comment by gise88** [comment]
@flobernd Hey once again, we're having some issues with this PercentilesAggregation.. We used like in the screenshot but the `SearchAsync` throwes that `tdigest_percentiles is not supported`. Should we write the query in some other ways? 

![image](https://github.com/elastic/elasticsearch-net/assets/6855163/155d8eab-e4a1-4842-ac66-8f7da370072c)
