### ISSUE TITLE
HTMLStrip processor

### ISSUE THREAD

**Issue by rmalca** [elastic/elasticsearch-net#7881]
**Is your feature request related to a problem? Please describe.**
Hello, I would like to request that the HTMLStrip processor be added to the ProcessorsDescriptor or some way that an undefined processor can be added in the PutPipeline method.

**Additional context**
Reference: https://www.elastic.co/guide/en/elasticsearch/reference/current/htmlstrip-processor.html

![image](https://github.com/elastic/elasticsearch-net/assets/3759745/9e3d2e3a-f06a-4f66-a831-58f1a84ff8f2)

**Comment by flobernd** [comment]
Thanks for reporting! 

It seems like this particular processor (as well as some other ones) are currently not part of the specification:
https://github.com/elastic/elasticsearch-specification/blob/main/specification/ingest/_types/Processors.ts

**Comment by flobernd** [comment]
I've created an issue in the specification repository:
https://github.com/elastic/elasticsearch-specification/issues/2231

I'll close this one for now.

**Comment by bytefish** [comment]
@flobernd Is there any way to currently add the Html Strip Processor using the C# API?

**Comment by flobernd** [comment]
@bytefish No, not yet. I'll take care of adding a few of the missing processors in the next weeks. The issue is already open for way too long :/

**Comment by bytefish** [comment]
@flobernd Great! Thanks for the news and confirming it’s not possible. I'll keep an eye on this issue. 🧐

**Comment by flobernd** [comment]
@ChristianGottinger Yes, I just pushed the required [specification changes](https://github.com/elastic/elasticsearch-specification/pull/2835). As soon as the PR is approved, I can then regenerate the client to include the new processors.

cc @bytefish @rmalca

**Comment by flobernd** [comment]
The `HtmlStripProcessor` is now available in version [8.15.5](https://github.com/elastic/elasticsearch-net/releases/tag/8.15.5).
