### ISSUE TITLE
404 is considered Invalid

### ISSUE THREAD

**Issue by rickdgray-dc** [elastic/elasticsearch-net#7887]
**NEST/Elasticsearch.Net version**:

7.15.2

**Elasticsearch version**:

7.15.2

**.NET runtime version**:

6

**Operating system version**:

Win 11 Build: 22621.2134

**Description of the problem including expected versus actual behavior**:

When an item is not found, the response is `Invalid NEST response built from a successful (404)`.

I have spent quite a long time trying to figure out why the response is invalid. With `DisableDirectStreaming()` enabled, I seem to get a very normal response, but it is unable to deserialize.

```
{
  "_index" : "inventory",
  "_type" : "_doc",
  "_id" : "1234",
  "found" : false
}
```

**Steps to reproduce**:
 1. Initialize `ElasticClient()`.
 2. Run `GetAsync` on an ID that is known not to exist.
 3. Inspect response.

**Expected behavior**

I expect the 404 to return a valid NEST response and successfully deserialize.

**Provide `ConnectionSettings` (if relevant)**:

```
var settings = new ConnectionSettings(new Uri("localhost"))
    .DisableDirectStreaming()
    .EnableDebugMode();

var client = new ElasticClient(settings);
```

**Provide `DebugInformation` (if relevant)**:

```
Invalid NEST response built from a successful (404) low level call on GET: /inventory/_doc/1234?pretty=true&error_trace=true
# Server indicated deprecations:
- 299 Elasticsearch-7.15.2-93d5a7f6192e8a1a12e154a2b81bf6fa7309da0c "Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.15/security-minimal-setup.html to enable security."
# Audit trail of this API call:
 - [1] ProductCheckOnStartup: Took: 00:00:00.4482201
 - [2] ProductCheckSuccess: Node: https://elasticsearch.drive.local/ Took: 00:00:00.4151422
 - [3] HealthyResponse: Node: https://elasticsearch.drive.local/ Took: 00:00:00.0173877
# Request:
<Request stream not captured or already read to completion by serializer. Set DisableDirectStreaming() on ConnectionSettings to force it to be set on the response.>
# Response:
{
  "_index" : "inventory",
  "_type" : "_doc",
  "_id" : "1234",
  "found" : false
}

# TCP states:
  Established: 314
  TimeWait: 120
  CloseWait: 6

# ThreadPool statistics:
  Worker: 
    Busy: 1
    Free: 32766
    Min: 20
    Max: 32767
  IOCP: 
    Busy: 0
    Free: 1000
    Min: 20
    Max: 1000
```

**Comment by flobernd** [comment]
Hey @rickdgray-dc, sorry for not working on this. I just took over the role as the maintainer of the .NET client around the time when you opened the issue and it must have slipped under my radar. Besides that, NEST has currently the lowest priority in general.

Tomorrow I'll release version 8.13.0 which might be worth trying for you - depending on the size of your project and the migration effort.
