### ISSUE TITLE
Update index settings API is missing

### ISSUE THREAD

**Issue by TheFireCookie** [elastic/elasticsearch-net#7895]
**Elastic.Clients.Elasticsearch version**:
8.9.2

**Elasticsearch version**:
8.9.0

**.NET runtime version**:
7.0.10

**Operating system version**:
Windows 11

**Description of the problem including expected versus actual behavior**:
The update settings API of the Index endpoint seems to be missing ( this one : https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-update-settings.html )

**Steps to reproduce**:
Use the client and try to find the update settings methods
![image](https://github.com/elastic/elasticsearch-net/assets/10741012/eda03e50-a959-46e0-a290-b8a83b4163af)

**Comment by flobernd** [comment]
There are a few unsupported endpoints related to indices at the moment (see #7890). I definitely plan to implement them at some point.

**Comment by flobernd** [comment]
FYI: I'm closing this issue as all of the missing endpoints will be reimplemented anyways as soon as I've finished my work on the code generator.
