### ISSUE TITLE
Decoration of requests

### ISSUE THREAD

**Issue by kmcclellan** [elastic/elasticsearch-net#7896]
**Is your feature request related to a problem? Please describe.**
Elasticsearch requests have accompanying "descriptor" types (e.g. [`SearchRequestDescriptor<TDocument>`](https://github.com/elastic/elasticsearch-net/blob/c99615728965df04f494489468e395001fc2e233/src/Elastic.Clients.Elasticsearch/Api/SearchRequest.cs#L38)) to incrementally configure requests in a fluent API style. However, unlike other fluent builders, they don't expose their state, so there's no way to know what has already been specified for the request. This leaves me unable to "decorate" requests: checking what has been set and altering it if necessary (e.g. "if no sort is specified, sort by timestamp").

The situation is somewhat better if you decline the fluent syntax in favor of `SearchRequest` and friends. However, even these types occasionally let you set state that is then no longer publicly accessible (e.g. the [indicies on an `OpenPointInTimeRequest`](https://github.com/elastic/elasticsearch-net/blob/c99615728965df04f494489468e395001fc2e233/src/Elastic.Clients.Elasticsearch/_Generated/Api/OpenPointInTimeRequest.g.cs#L65)).

Aside from decoration, this also becomes a pain point when trying to mock responses to requests with inscrutable state. 

**Describe the solution you'd like**
Any state specified on a request model should be accessible in order to support decoration and other use cases.

**Describe alternatives you've considered**
It's possible to create custom POCOs that resemble ES request types for decoration/testing, but the mapping becomes tedious.

**Additional context**
Honestly not a fan of the two worlds between descriptors/requests. It makes things more cluttered when there are already too many types/signatures. Though most APIs have overloads for both, there are still times when I need a request and all I have is a descriptor or vice versa, and the types do not share an ancestor as they did in the NEST client (once again, the lack of accessible state means I can't even convert them manually).

Rant over. Still a fan of the v8 client. Please keep supporting/improving!

**Comment by flobernd** [comment]
Hi @kmcclellan,

> Though most APIs have overloads for both, there are still times when I need a request and all I have is a descriptor or vice versa, and the types do not share an ancestor as they did in the NEST client

The descriptor design is inherited from NEST but we dropped the common interface with the request. In part, it was a design decision to get rid of the bloat of interfaces that didn't add much value. It was also a technical decision at the time when STJ didn't support polymorphic deserialization directly. It would have forced us to have custom converters which again required more work to generate and extra code in the assembly. That second item would potentially be solved with the new attributes today, but we'd have to bump the minimum version of STJ we pull in.

> However, unlike other fluent builders, they don't expose their state, so there's no way to know what has already been specified for the request.

Descriptors are subtly different to a builder which would hold the state as methods are called. They represent a fluent way to define requests, but the implementation detail is hidden. In our case, execution of the `configure` actions is deferred until the last possible minute. This allows users to prepare default descriptor instances and reuse them in various ways. Individual properties can be tweaked multiple times without causing extra allocations.

> It's possible to create custom POCOs that resemble ES request types for decoration/testing, but the mapping becomes tedious.

This is usually our suggestion for usecases like yours. However, we are fully aware this has some drawbacks - like the rather big maintenance overhead.

---

Some of the descriptors implement the `IBuildableDescriptor` interface that provides a method to convert descriptors to their corresponding request classes. I will consider supporting this interface for all descriptor types to provide a way to check internal state for cases where performance/allocations are not a major concern.

We will as well discuss about make all properties of the request objects settable.

**Comment by kmcclellan** [comment]
> They represent a fluent way to define requests, but the implementation detail is hidden. In our case, execution of the configure actions is deferred until the last possible minute.

I understand the desire to encapsulate the serialization implementation. I think this could be preserved while granting access to partially configured request state. In the case of descriptor members which take delegates, it would make sense to provide this as an argument when they are invoked.

```csharp

var search = new SearchRequestDescriptor<MyDocument>();

search.Sort(
    sorts =>
    {
        sorts.Add(new SortOptionsDescriptor<MyDocument>().Field(x => x.MyField));
    });

// This code doesn't have to know about the previous code.
search.Sort(
    sorts =>
    {
        if (sorts.Count == 0)
        {
            sorts.Add(new SortOptionsDescriptor().Field("@timestamp"));
        }
    });
```

> This allows users to prepare default descriptor instances and reuse them in various ways. Individual properties can be tweaked multiple times without causing extra allocations.

I'm not sure if this is as useful as you think. For one, I'm rarely able to reuse descriptor instances. This would mean executing the exact same request multiple times, whereas usually there are slight differences based on one or more runtime arguments. For two, it's hard to "tweak" properties without knowing what their current state is (e.g. "sort by timestamp if no sort is specified").

I realize these are not simple changes and would likely require an architectural paradigm shift. As things stand, I don't find descriptors very useable.

**Comment by flobernd** [comment]
> I understand the desire to encapsulate the serialization implementation. I think this could be preserved while granting access to partially configured request state. In the case of descriptor members which take delegates, it would make sense to provide this as an argument when they are invoked.

It's not only about serialization, but as well about the descriptor implementation itself. The example code you've shown looks like a mix of descriptor and initializer style. I personally don't see the advantage over the plain initializer style here (assuming the request objects expose all of their state).

> I'm not sure if this is as useful as you think. For one, I'm rarely able to reuse descriptor instances. This would mean executing the exact same request multiple times, whereas usually there are slight differences based on one or more runtime arguments. 

There are some good cases where it's possible to reuse a descriptor. For instance, you could prepare a complete query and execute it on different `.Index()`. In this regard, the current descriptor implementation is as powerful as using plain request objects. The second call to a method always overrides the corresponding property.

> For two, it's hard to "tweak" properties without knowing what their current state is (e.g. "sort by timestamp if no sort is specified").

I agree with that statement, but in these cases you can pass the plain request objects around or implement your own POCO wrappers. It's just not the intended usecase for these descriptors.

That being said, I will definitely think about some possible improvements (a few non breaking ones are mentioned in my previous comment).

**Comment by flobernd** [comment]
I created an evaluation task for possible improvements on my internal TODO list. Closing this issue for now.
