### ISSUE TITLE
Missing public accessors on MultiSearch Response

### ISSUE THREAD

**Issue by Alkaersig** [elastic/elasticsearch-net#7930]
**Elastic.Clients.Elasticsearch version**:
8.9.2

**Elasticsearch version**:
8.9.0

**.NET runtime version**:
6.0

**Description of the problem including expected versus actual behavior**:
When using the MultiSearch API there seems to be missing public accessors for the response. The "responses" property on MultisearchResponse<T> is a union of MultisearchItem<TDocument> and ErrorResponseBase which are stored in internal fields named Item1 and Item2.

**Steps to reproduce**:
 1. Make a MultiSearch Query
 2. Inspect the Responses property on the response.

**Expected behavior**
Results of type T should be publicly available (should be a property that exposes the results of "MultiSearchResponseItems".Select(x => x.Item1))

**Provide `DebugInformation` (if relevant)**:
The results of the query/queries are non-public.
![image](https://github.com/elastic/elasticsearch-net/assets/12032054/7ac7629d-0f45-4c32-8bd9-1459b62f99bb)

**Comment by flobernd** [comment]
Hi @Alkaersig,

it's possible to access the union members like this:

```csharp
var responses = result
    .Responses.Select(resp => resp.Match(first => first, second => (MultiSearchItem<Person>?)null));
```

The above example returns the `first` variant for all valid responses and maps to `null` for all error cases. This is nothing that I would recommend running in production as it simply ignores all error responses, but it simply shows a way how to access the individual variants.

**Comment by Alkaersig** [comment]
Thanks @flobernd

It seems that it will do the job, although it's not a very intuitive way of getting the data compared to exposing a DictionaryList, Tuble or wrapping object (the old client just had a GetResponses<T> method for getting the results).

**Comment by flobernd** [comment]
I think the new way is inspired by functional programming languages. Personally I like that approach as it provides a type-safe way to to match the desired variant without causing extra allocations.

I'll make sure to add documentation of the Union type so that the `Match()` method is more present to everybody.

For a custom `GetResponses()` method, I would suggest to implement a simple extension method like this:

```csharp
return result.Responses
    .Select(resp => resp.Match(first => first, second => (MultiSearchItem<Person>?)null))
    .Where(x => x is not null);
```
