### ISSUE TITLE
Please add a property to set expected similarity to KnnQueryDescriptor.

### ISSUE THREAD

**Issue by mikkel-busch** [elastic/elasticsearch-net#7952]
**Is your feature request related to a problem? Please describe.**

The class [KnnQueryDescriptor ](https://github.com/elastic/elasticsearch-net/blob/59d6cf878c54fbf92a635863ec796160429e5531/src/Elastic.Clients.Elasticsearch/_Generated/Types/KnnQuery.g.cs#L75)

Does not seem to have a similarity property to set expected similarity.

The [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/knn-search.html#_search_knn_with_expected_similarity) states that such a parameter should exist for KNN search.

**Describe the solution you'd like**
I would like the property to be added.

**Describe alternatives you've considered**
Currently the filtering can be done client side, but this add some unnecessary overhead.

**Comment by flobernd** [comment]
Hi @mikkel-busch! 

This is a specification issue which just got fixed: https://github.com/elastic/elasticsearch-specification/pull/2261.

The fix will be included in the next release.

**Comment by mikkel-busch** [comment]
Sounds good. Thank you for the fast reply.
