### ISSUE TITLE
Properties of derived class are not serialized

### ISSUE THREAD

**Issue by tiptobi** [elastic/elasticsearch-net#7967]
**Elastic.Clients.Elasticsearch version**:  8.10.0

**Elasticsearch version**: 8.6.2

**.NET runtime version**: 6.0

**Operating system version**: 

**Description of the problem including expected versus actual behavior**:
When using the .NET client to create or update a document where the model is a derived class, the properties that are in the derived class are not serialized / they don't appear in the request. This was working perfectly fine on the NEST v7 client.

**Steps to reproduce**:
 1. Having the following model classes 
```
public abstract class BaseEntity
{
    public string GeneralProperty { get; set; }
}

public class ConcreteEntity : BaseEntity
{
    public string DerivedProperty { get; set; };
}
```

And the following logic to index a document:
```
public async Task IndexAsync<T>(T entity) where T : BaseEntity
{
    var index = GetIndexByEntity(entity);

    await _client.IndexAsync(entity, descriptor => descriptor.Index(index));
}
```

2. Call the index function like: 
```
var entity = new ConcreteEntity { GeneralProperty = "general", DerivedProperty = "derived" };
await IndexAsync(entity);
```

3. The generated HTTP request body of the V8 client then is:
```
{
    "generalProperty": "general"
}
```

**Expected behavior**
The generated request should include the properties from the base class AND the derived class:
```
{
    "generalProperty": "general",
    "derivedProperty": "derived"
}
```

**Note**: The same behaviour can be observed on all writing client functions like IndexAsync(), UpdateAsync() and BulkAsync().

**Comment by flobernd** [comment]
@tiptobi I can not confirm this issue. Your basic example resulted in the following response from `IndexAsync`:

```
# Request:
{"derivedProperty":"derived","generalProperty":"general"}
# Response:
{"_index":"index","_id":"E1x1KIsBfOpqVA4G7Vni","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":1,"_primary_term":1}
```

Are you maybe using a different code in production? 

The generic approach works fine for me:

```csharp
public async Task IndexAsync<T>(T entity) where T : BaseEntity
{
    await _client.IndexAsync(entity, ...); // => IndexAsync<ConcreteEntity>(...)
}
```

But using a generic polymorphic approach does **not**:

```csharp
public async Task IndexAsync(BaseEntity entity)
{
    await _client.IndexAsync(entity, ...); // => IndexAsync<BaseEntity>(...)
}
```

```
# Request:
{"generalProperty":"gen"}
# Response:
{"_index":"index","_id":"FFx4KIsBfOpqVA4GdVnq","_version":1,"result":"created","_shards":{"total":1,"successful":1,"failed":0},"_seq_no":2,"_primary_term":1}
```

**Comment by tiptobi** [comment]
@flobernd Thank you for your answer, this brought me closer to the problem and I made some more tests. 
You're right, having the following method:

```
public async Task IndexAsync<T>(T entity) where T : BaseEntity
{
    await _client.IndexAsync(entity, ...); // => IndexAsync<ConcreteEntity>(...)
}
```

This one works and generates the correct request:
```
var entity = new ConcreteEntity { GeneralProperty = "general", DerivedProperty = "derived" };
await IndexAsync(entity);
```

But what isn't working is the following:
```
BaseEntity entity = new ConcreteEntity { GeneralProperty = "general", DerivedProperty = "derived" };
await IndexAsync(entity);
```

I'm now not sure if this is maybe expected behaviour? But it was probably different in the V7 client as this was working fine with the V7 client for us?

**Comment by flobernd** [comment]
@tiptobi I'm not super familiar with NEST (v7 client), but I can imagine this is a change in behavior introduced by switching from `Utf8Json` to `System.Text.Json`. Do you maybe have some insights @stevejgordon ?

**Comment by stevejgordon** [comment]
@flobernd That's correct. We default to using STJ for source serialization, which until .NET didn't natively support polymorphic serialization without a custom converter on the type. Since .NET 7, this is now supported, and this [Microsoft doc](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-7-0) details the steps. The behaviour isn't something our library can directly influence. It is also possible to [customise the source serialization](https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/source-serialization.html) in several ways.

**Comment by flobernd** [comment]
Thanks for confirming @stevejgordon! Hoping that answers your open questions for now @tiptobi . Feel free to reach out again, if you have further problems.
