### ISSUE TITLE
missing_order option missing for CompositeAggregationSource

### ISSUE THREAD

**Issue by rbaudrillard** [elastic/elasticsearch-net#7971]
I am currently working to replace our seach engine with elastic search and I got a business rule that could work in plain JSON but the option is missing in the NEST 7.17.5 library : there doesn't appear to be a way to set the missing_order option for composite aggregations. I would like to do something like:

List<ICompositeAggregationSource> sources = new List<ICompositeAggregationSource>();

sources.Add(new TermsCompositeAggregationSource(sourceName)
{
    Field = field,
    Order = sorter.IsAscending() ? SortOrder.Ascending : SortOrder.Descending,
    MissingBucket = true,
    **MissingOrder = "last"**
});

I naively tried to extend the interface / class, but it didn't worked and I didn't find another workaround, is there any with this version ? 
I cannot upgrade to the new client version because composite aggregation are not fully supported yet

**Comment by flobernd** [comment]
Hi there,

NEST is deprecated and we won't implement any new features there. As a workaround, you could use the low level client and build the JSON request yourself:

https://www.elastic.co/guide/en/elasticsearch/client/net-api/7.17/transports.html

I'm closing down this issue for now as it's a feature request for NEST, but feel free to reach out again if you have any other specific questions.
