### ISSUE TITLE
The client.Indices.GetAsync() call fails with the JSON parsing exception if certain settings are present

### ISSUE THREAD

**Issue by yansklyarenko** [elastic/elasticsearch-net#7972]
**Elastic.Clients.Elasticsearch version**: 8.10

**Elasticsearch version**: 8.2.2

**.NET runtime version**: 7.0

**Operating system version**: Windows 10

**Steps to reproduce**:
Create an index with the following call:

```
var createResponse = await client.Indices.CreateAsync("my-test-index", d => d
                       .Settings(s => s
                                   .Analysis(a => a
                                       .TokenFilters(tf => tf
                                         .WordDelimiterGraph("test_filter", sel => sel.SplitOnNumerics(false)
                                       )))), default).ConfigureAwait(false);
```

This works just fine. The index is created with the following settings:

```
{
  "my-test-index" : {
    "settings" : {
      "index" : {
        "routing" : {
          "allocation" : {
            "include" : {
              "_tier_preference" : "data_content"
            }
          }
        },
        "number_of_shards" : "1",
        "provided_name" : "my-test-index",
        "creation_date" : "1698047329433",
        "analysis" : {
          "filter" : {
            "test_filter" : {
              "type" : "word_delimiter_graph",
              "split_on_numerics" : "false"
            }
          }
        },
        "number_of_replicas" : "1",
        "uuid" : "2wzv2HGIS729KaxIaODsHw",
        "version" : {
          "created" : "8020299"
        }
      }
    }
  }
}
```

However, if you try to get the index with the following call:

```
var getResponse = await client.Indices.GetAsync("my-test-index", default).ConfigureAwait(false);
```

It fails with the following exception:

```
# FailureReason: Unrecoverable/Unexpected BadResponse while attempting GET on https://localhost:9292/my-test-index?pretty=true&error_trace=true
 - [1] BadResponse: Node: https://localhost:9292/ Exception: JsonException Took: 00:00:00.0795701
# Audit exception in step 1 BadResponse:
System.Text.Json.JsonException: The JSON value could not be converted to System.Nullable`1[System.Boolean]. Path: $.split_on_numerics | LineNumber: 2 | BytePositionInLine: 43.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'String' as a boolean.
   at System.Text.Json.Utf8JsonReader.GetBoolean()
   at System.Text.Json.Serialization.Converters.BooleanConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.NullableConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at Elastic.Clients.Elasticsearch.Analysis.TokenFilterInterfaceConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options) in /_/src/Elastic.Clients.Elasticsearch/_Generated/Types/Analysis/TokenFilters.g.cs:line 252

```

**Some mode details**
As far as I can see, it doesn't like the fact that `split_on_numerics` is of a string type, not bool, and it fails when it tries to deserialize it to bool. The exception stack trace mentions the `Read` method of the `TokenFilterInterfaceConverter` class. It tries to deserialize the `word_delimiter_graph` part like this:
```
JsonSerializer.Deserialize<WordDelimiterGraphTokenFilter>(ref reader, options);
```
It looks like the `WordDelimiterGraphTokenFilter` doesn't set the proper convertor on each required `bool?` property. For example, the mentioned `split_on_numerics` property is defined like this:
```
[JsonInclude]
[JsonPropertyName("split_on_numerics")]
public bool? SplitOnNumerics { get; set; }
```
While another `bool?` property `preserve_original` is defined like this:
```
[JsonInclude]
[JsonPropertyName("preserve_original")]
[JsonConverter(typeof(StringifiedBoolConverter))]
public bool? PreserveOriginal { get; set; }
```

**An assumption for the fix**
It looks like the fix here is to decorate all `bool?` properties with `StringifiedBoolConverter` attribute. I've checked the sample above, replacing the `split_on_numerics` with `preserve_original`, and it was able to return the index response just fine.

**Comment by flobernd** [comment]
Hi there, unfortunately there are a lot of places where the Elasticsearch server might send a `string` instead of the actual primitive type.

There is a high level proposal to fix all of these places at once:
https://github.com/elastic/elasticsearch-specification/issues/2238

Until that's implemented, I have to manually mark each of these fields as "stringified" in the specification.

**Comment by yansklyarenko** [comment]
Thanks for your answer, @flobernd. Yep, I've seen that proposal and I understand that is not a trivial change.
For this particular bug, is it possible to cover only the `IndexState` class and its counterparts (`IndexSettings`, `TypeMapping`, etc.)?

In the meantime, is there a workaround you can suggest? If I issue a low-level request and get `StringResponse` back, I'm still not able to deserialize its `Body` to `IndexState`. Is there a better approach than manually parsing the raw JSON for now? Thanks for your time, I really appreciate it.

**Comment by yansklyarenko** [comment]
@flobernd Perhaps, it would be easier to add those [Stringified convertors](https://github.com/elastic/elasticsearch-net/blob/b1416abe89771402f889928b870ec2b5d63dbf45/src/Elastic.Clients.Elasticsearch/Serialization/Stringified.cs) to the [list of converters for DefaultRequestResponseSerializer](https://github.com/elastic/elasticsearch-net/blob/main/src/Elastic.Clients.Elasticsearch/Serialization/DefaultRequestResponseSerializer.cs#L28)?
Do you think it is a _dirtier_ fix than the one you mentioned above (manually add attributes on demand)?

**Comment by flobernd** [comment]
@yansklyarenko Yes, this was something I'm considering as well. There might be a minor performance hit, but I know that e.g. the Go client does it the same way and always accepts strings for numbers and bools.

I got something else to finish first, but no worries, I'll try to fix these stringify problems in a timely manner (either by adding the attributes or by registering the converters in the default converter list).

**Comment by yansklyarenko** [comment]
Thanks a lot, @flobernd!
Just FYI, I've tried registering the converters in the default converter list locally, and it fixes the problem in my case. All the tests have also passed locally.

**Comment by yansklyarenko** [comment]
@flobernd Florian, I have tried the new client v8.11.0, and it resolves this issue! Thank you a lot for a quick fix!
Feel free to close this thread unless you want to keep it open for some other reason. :)
