### ISSUE TITLE
Whether Chinese queries are not supported

### ISSUE THREAD

**Issue by qiandi** [elastic/elasticsearch-net#7973]
**Elastic.Clients.Elasticsearch version**:8.10

**Elasticsearch version**:8.10

**.NET runtime version**:aspnetcore 3.1

**Operating system version**:linux

Chinese characters are converted to Unicode。
I wanted to query Chinese "新年快乐", but through the logs, it became "\u65B0\u5E74\u5FEB\u4E50"
![QQ截图20231027150258](https://github.com/elastic/elasticsearch-net/assets/11673386/0fbf6ff3-aa32-4fa7-a6e0-7c25ecc03631)
![QQ截图20231027150339](https://github.com/elastic/elasticsearch-net/assets/11673386/e685526a-886c-4c64-a5c0-2aba6704f40d)

**Comment by flobernd** [comment]
Hi! This behavior is defined in the JSON standard. The ES server should be able to handle this correctly.
