### ISSUE TITLE
Non generic type Fields can not be used with type argument

### ISSUE THREAD

**Issue by a2741890** [elastic/elasticsearch-net#7985]
**NEST/Elasticsearch.Net version**: 7.16.0

**Elasticsearch version**: 7.16.0

**.NET runtime version**: .NET 6.0

**Operating system version**: Windows 10

I tried to use the example from the [page](https://www.elastic.co/guide/en/elasticsearch/client/net-api/7.16/sort-usage.html) (Object Initializer syntax example) But there was an error saying "Non generic type Fields can not be used with type argument" for the usage "Field = _Field<Project>_(p => p.Tags.First().Added)"

Seems like the **Field** is not accepting generic type...
 Very confused

![image](https://github.com/elastic/elasticsearch-net/assets/44138757/c7251339-f226-446c-a051-f21a42744a43)

**Comment by a2741890** [comment]
Ok I think I found the correct syntax. According to the [test ](https://github.com/elastic/elasticsearch-net/blob/c75fea62e7d05abf98304092ef43904beb7476a8/tests/Tests/Search/Search/SortUsageTests.cs#L41), you have to use Elasticsearch Net package and call the static method **Infer** in order to use generic **Field**.  
e.q.
`Field = Infer.Field<Project>(f => f.LocationPoint),`
So I assume the document mentioned above is wrong?

**Comment by flobernd** [comment]
Hi @a2741890 , yes I assume it's outdated 🙂

**Comment by a2741890** [comment]
> Hi @a2741890 , yes I assume it's outdated 🙂 

🫡
