### ISSUE TITLE
Script pipeline processor is missing 

### ISSUE THREAD

**Issue by f1nzer** [elastic/elasticsearch-net#7996]
**Elastic.Clients.Elasticsearch version**: 8.11.0

It looks like the script processor is not generated:
https://github.com/elastic/elasticsearch-net/tree/main/src/Elastic.Clients.Elasticsearch/_Generated/Types/Ingest

Docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/script-processor.html

**Comment by flobernd** [comment]
Hi @f1nzer, Thanks for reporting! There are currently a bunch of processors missing from the specification. The issue is tracked in the specification repository: https://github.com/elastic/elasticsearch-specification/issues/2231
