### ISSUE TITLE
MultiBucketAggregate is missing

### ISSUE THREAD

**Issue by gpetrou** [elastic/elasticsearch-net#7999]
**Elastic.Clients.Elasticsearch version**: 8.11.0

**Elasticsearch version**: 8.2.2

**.NET runtime version**: net8.0

**Operating system version**: Windows 11

**Description of the problem including expected versus actual behavior**:
`MultiBucketAggregate` exists in NEST, but is missing in the new library. Is this replaced by something else? Or are you planning to bring it back? Is yes, are you planning to do that soon? If not, are there any guidelines on how to submit a PR for it?

**Steps to reproduce**:

**Expected behavior**

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by flobernd** [comment]
Hi @gpetrou ! Not all aggregations and aggregates are currently implemented in the v8.* client. The plan is to implement all missing  types and endpoints (including this aggregation) until end of Q1 2024 if everything goes fine. Most parts of the client are auto-generated from our elastic-specification, but the code generator is closed source for internal reasons which means you won't be able to create a PR.

**Comment by flobernd** [comment]
Hi @matteocalisti! Thanks for the kind way of asking. Currently it's looking good that at least a big chunk of missing endpoints and features can be released around the end of Q1/2024 (+/-). My plan is to create an alpha/beta version first which will be publically available for testing. I expect it to take some additional time to get rid of some smaller bugs and rough edges, but that will definitely be an incremental process with a lot more frequent releases and not - like this time - a "all or nothing" situation.

**Comment by flobernd** [comment]
@gpetrou I had the time to check what the `MultiBucketAggregate` in NEST is about. This is just a base class used for aggregates that return multiple buckets. In the v8 client, you can still access the `Buckets` property on the returned aggregates directly (check `AdjacencyMatrixAggregate` for example).
