### ISSUE TITLE
SingleBucketAggregate is missing

### ISSUE THREAD

**Issue by gpetrou** [elastic/elasticsearch-net#8000]
**Elastic.Clients.Elasticsearch version**: 8.11.0

**Elasticsearch version**: 8.2.2

**.NET runtime version**: net8.0

**Operating system version**: Windows 11

**Description of the problem including expected versus actual behavior**:
`SingleBucketAggregate` exists in NEST, but is missing in the new library. Is this replaced by something else? Or are you planning to bring it back? Is yes, are you planning to do that soon? If not, are there any guidelines on how to submit a PR for it?

**Steps to reproduce**:

**Expected behavior**

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by flobernd** [comment]
Hi @gpetrou ! Not all aggregations and aggregates are currently implemented in the v8.* client. The plan is to implement all missing  types and endpoints (including this aggregation) until end of Q1 2024 if everything goes fine. Most parts of the client are auto-generated from our elastic-specification, but the code generator is closed source for internal reasons which means you won't be able to create a PR.
