### ISSUE TITLE
Missing Support for term range queries

### ISSUE THREAD

**Issue by lukapor** [elastic/elasticsearch-net#8004]
Only number and date range queries are supported by version 8.

**Comment by flobernd** [comment]
I'm currently in the prgoress of implementing all missing endpoints and related features. This particular feature (term range queries) should be available afterwards as well.

**Comment by CasperWSchmidt** [comment]
@flobernd Any ETA on this? We're currently migrating from NEST because it's not working on .Net 8 and need the `TermRangeQuery`

**Comment by CasperWSchmidt** [comment]
@flobernd We're on a very tight schedule for upgrading to .Net 8, so we've chosen not to have support for term range queries for now and add it later. The end of Q1 sounds reasonable enough to just wait for it to come :)

**Comment by CasperWSchmidt** [comment]
@flobernd any news on this?

**Comment by flobernd** [comment]
Hi @CasperWSchmidt, as you've probably noticed, I was able to release the 8.13.x client in time. Afterwards I already started focusing on the bugs, but the list is long 🙂 

It seems like this specific issue is related to the specification and not - like I originally thought - to the code generator. The `TermsRangeQuery` is not modelled there. I'm going to re-open issue until I come up with a fix.

**Comment by flobernd** [comment]
Related to https://github.com/elastic/elasticsearch-specification/issues/2545

**Comment by flobernd** [comment]
Currently blocked until https://github.com/elastic/elasticsearch-specification/issues/2545 is merged.

**Comment by deMD** [comment]
Do you have any ETA? We have a pretty tight schedule to support the new Client if we want to avoid rework later, so it would be great if we can decide asap what direction to go.

**Comment by flobernd** [comment]
Unfortunately, I cannot give you a definite ETA. The work will be done as transparent as possible. Supporting this feature requires work on two major components: the specification and the code-generator.

The work on the specification is mostly done (see the linked PR), but we have to make sure these changes are compatible with all the other code-generators (for other languages) as well. Merging is blocked until this testing is finished.

The related work on the .NET code-generator has partially started in parallel, but requires the specification PR to be merged to proceed.

I expect the task to be fully completed within the next month at the latest.

**Comment by flobernd** [comment]
Implemented in 8.14.4
