### ISSUE TITLE
AggregationContainer is missing

### ISSUE THREAD

**Issue by gpetrou** [elastic/elasticsearch-net#8005]
**Elastic.Clients.Elasticsearch version**: 8.11.0

**Elasticsearch version**: 8.2.2

**.NET runtime version**: net8.0

**Operating system version**: Windows 11

**Description of the problem including expected versus actual behavior**:
`AggregationContainer` exists in NEST, but is missing in the new library. Is this replaced by something else? Or are you planning to bring it back? Is yes, are you planning to do that soon?

**Steps to reproduce**:

**Expected behavior**

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by flobernd** [comment]
Hi @gpetrou!

The `AggregationContainer` class is not available, but the v8.x client still provides functionality to perform aggregations (not all types are currently supported, but the most important ones are).

Could you please explain what you are trying to achieve? I should be able to provide you with an example code snippet.
