### ISSUE TITLE
Deprecation of old nugets and transfer of downloads

### ISSUE THREAD

**Issue by thompson-tomo** [elastic/elasticsearch-net#8020]
**Is your feature request related to a problem? Please describe.**
I logged an issue for ElasticSearch.Net thinking it was still under development but and was not aware it had been replaced by Elastic.Clients.Elasticsearch. 

**Describe the solution you'd like**
I would like the ElasticSearch.Net package to be deprecated on nuget and the downloads transferred to Elastic.Clients.Elasticsearch. Same goes for the NEST.* packages.

**Describe alternatives you've considered**
Allow the confusion to remain on nuget

**Additional context**
This will mean that [Elastic.Clients.Elasticsearch](https://www.nuget.org/packages/Elastic.Clients.Elasticsearch) will go from being on the second page of packages with 1,110,140 downloads to being the top result with 280+million downloads and Elatic.APM second.

https://learn.microsoft.com/en-us/nuget/nuget-org/deprecate-packages

**Comment by flobernd** [comment]
NEST and `ElasticSearch.Net` is not end of life yet. Some customers are even using NEST and the new v8.* client side-by-side while migrating.
