### ISSUE TITLE
Add FilterPath to SearchRequestDescriptor

### ISSUE THREAD

**Issue by majbo** [elastic/elasticsearch-net#8022]
I'm migrating from NEST to Elasticsearch .NET Client and noticed that FilterPath can't be configured for a search request.

Please add an option to configure FilterPath similar to the one existing in NEST.

Nuget Version: Elastic.Clients.Elasticsearch 8.11.0

**Comment by flobernd** [comment]
Hi there! `PlainRequest` actually contains a `FilterPath` property, but its use is disabled as for the reason stated in the documentation:

```c#
/// <summary>
///     A comma-separated list of filters used to reduce the response.
///     <para>
///         Use of response filtering can result in a response from Elasticsearch
///         that cannot be correctly deserialized to the respective response type for the request.
///         In such situations, use the low level client to issue the request and handle response deserialization.
///     </para>
/// </summary>
[JsonIgnore]
public string[] FilterPath
{
    get => Q<string[]>("filter_path");
    set => Q("filter_path", value);
}
```
