### ISSUE TITLE
Indicies.Get call fails to deserialize ICollections properly in the IndexRequest

### ISSUE THREAD

**Issue by baveryt** [elastic/elasticsearch-net#8034]
**Elastic.Clients.Elasticsearch version**: 8.11

**Elasticsearch version**: 8.8

**.NET runtime version**: 8.0

**Operating system version**: Osx

**Description of the problem including expected versus actual behavior**:
When making calls to Indicies.Get and setting the Features or ExpandWildcards on the GetIndexRequest object the ICollections are not getting parsed properly for the underlying API call.  Looking at the stack trace you'll see something like: Invalid Elasticsearch response built from a unsuccessful (400) low level call on GET: /%2A?features=System.Collections.ObjectModel.Collection%601%5BElastic.Clients.Elasticsearch.IndexManagement.Feature%5D\n 

**Steps to reproduce**:
 1. Make a call to the Indicies.Get setting either the features or expandwildcards option

**Expected behavior**
For the features it should expand out the collections properly [aliases] in this case.

**Comment by flobernd** [comment]
Hey @baveryt, could you please include the JSON payloads for the request (and response, if possible)? They should be included in the exception after calling `DisableDirectStreaming()` on your `ElasticSearchSettings` instance.

**Comment by flobernd** [comment]
Thanks for the additional details! It indeed seems like building the query argument fails for some cases when the argument is a collection.
