### ISSUE TITLE
[Request feedback] Looking for feedback about the UX experience

### ISSUE THREAD

**Issue by flobernd** [elastic/elasticsearch-net#8039]
The engineering team here at Elastic is looking for developers to participate in research and feedback sessions to learn more about how you use our .NET v8 client and what improvements we can make to their design and your workflow. If you're interested in sharing your insights into developer experience and language client design, please fill out this ~short form~ (ended). Depending on the number of responses we get, we may either contact you for a 1:1 conversation or a focus group with other developers who use the same client. Thank you in advance - your feedback is crucial to improving the user experience for all Elasticsearch developers!

**Comment by gpetrou** [comment]
Currently, there are too many bugs that require too many workarounds if possible and missing functionality compared to NEST. Incomplete documentation is also an issue. Personally, I am eagerly awaiting the new generator implementation I have read about in other issues. Hopefully, this will significantly improve the developer experience.

**Comment by flobernd** [comment]
Hi @gpetrou, thanks for your feedback. It would be nice if you could as well enter this in the provided form (if you did not already do that).

Just to be completely transparent here:

With the first set of generator changes, we are aiming for full support of all endpoints and server features (e.g. the currently missing aggregations). Initially there will be no major UX/quality of life improvements. 

However, this feedback request has been opened for this very purpose. After we have collected the major issues, we will fully focus on improving the developer experience when using this library.

Regarding NEST features: Simplifying the client and removing some features of NEST in the process was a conscious decision of the previous maintainers (which I fully support). This step, and also the use of code generation, is necessary to make the maintenance effort bearable for a single person.

This does not mean that no NEST features will be re-implemented in the v8 client, but a large part will probably not be able to be migrated at this stage. I would be interested to hear the exact names of the NEST features that are important to you.

**Comment by stefannikolei** [comment]
ATM keeping up to date with the package is a real PITA. Nearly each Patch Version has Breaking Changes..

**Comment by flobernd** [comment]
@stefannikolei 8.13 was shipped with breaking changes which were unavoidable. More about the reasons here:

- https://github.com/elastic/elasticsearch-net/issues/8091#issuecomment-2059059297
- https://github.com/elastic/elasticsearch-net/issues/8091#issuecomment-2059155570

The patch releases 8.13.x fixed some unintentional breaking changes, but should otherwise not have affected the public API.

Could you please elaborate which breaking changes you've encountered in the latest patch releases? Just trying to figure out if there were more unintentional changes.

**Comment by stefannikolei** [comment]
For example with v8.13.9 we had breaking changes.

We had to change from

`qd.Terms(t => t.Field($"id"))`

to `qd.Terms(t => t.Field($new Field("id")))`
