### ISSUE TITLE
Dll verion

### ISSUE THREAD

**Issue by MalkaGit** [elastic/elasticsearch-net#8043]
Hello,

my package,config look like:
<?xml version="1.0" encoding="utf-8"?>
<packages>
  **<package id="Elastic.Clients.Elasticsearch" version="8.0.5" targetFramework="net461" />**
  <package id="Elastic.Transport" version="0.4.6" targetFramework="net461" />
  <package id="log4net" version="2.0.15" targetFramework="net461" />
  <package id="Microsoft.Bcl.AsyncInterfaces" version="6.0.0" targetFramework="net461" />
  <package id="Microsoft.CSharp" version="4.7.0" targetFramework="net461" />
  <package id="System.Buffers" version="4.5.1" targetFramework="net461" />
  <package id="System.Diagnostics.DiagnosticSource" version="5.0.1" targetFramework="net461" />
  <package id="System.Memory" version="4.5.4" targetFramework="net461" />
  <package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net461" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="6.0.0" targetFramework="net461" />
  <package id="System.Text.Encodings.Web" version="6.0.0" targetFramework="net461" />
  <package id="System.Text.Json" version="6.0.0" targetFramework="net461" />
  **<package id="System.Threading.Tasks.Extensions" version="4.5.4" targetFramework="net461" />**
  <package id="System.ValueTuple" version="4.5.0" targetFramework="net461" />
</packages>

I need to write data to Elastic (probably with bulks)
I created wrapper dll that use the Elastic.Clients.ElasticSearch.
It works fine with project1.
when i try to use it from froject2 i get error loading System.Threading.Tasks.Extensions"
(it seems that my old legacy project is using older veersion of Syste,Threading.Tasks.Extentions .

what would you recommand ?
is there older version of the package that i can use or other package ?

*i tried chainging the assembly binding, but it did not work

**Comment by flobernd** [comment]
Hi @MalkaGit,

This sounds like a general issue of your project dependencies and nothing specific to the Elasticsearch client.

Unfortunately it's impossible for me to help you without basic information like .NET (Framework) version, Client version (7, 8?), etc. In this specific case, please as well well provide a minimal project example that allows me to reproduce the issue.

**Comment by MalkaGit** [comment]
Thank you for your reply.
We will try using nest .

**Comment by flobernd** [comment]
Alright! Closing this issue for now. Feel free to open a new one, if you still encounter issues.
