### ISSUE TITLE
Remove netcoreapp3.1 and net5.0 from TargetFrameworks and add net8.0

### ISSUE THREAD

**Issue by gpetrou** [elastic/elasticsearch-net#8050]
**Is your feature request related to a problem? Please describe.**
Currently, I see in the csproj files `<TargetFrameworks>netstandard2.0;net461;netstandard2.1;netcoreapp3.1;net5.0;net6.0</TargetFrameworks>`

**Describe the solution you'd like**
Remove `netcoreapp3.1` and `net5.0` and add `net8.0`.

**Describe alternatives you've considered**

**Additional context**

**Comment by flobernd** [comment]
Thanks for hinting this. Removing the "end of support" targets is probably a good idea. `net461` should be replaced by `net462` as well. I have to check if we introduce any breaking change  that way, but in theory `netstandard2.0` and `netstandard2.1` should still ensure compatibility with `netcoreapp3.1` and `net5` projects.
