### ISSUE TITLE
Unable to setup default similarity or more similarities with different name.

### ISSUE THREAD

**Issue by petr-horny-bsshop** [elastic/elasticsearch-net#8067]
It is not possible to create similarity with custom name, eg. "default". The names are hardcoded. For the same reason it is not possible to create two similarities of same type with different settings.

In NEST you can for example create BM25 similarity named "default":
```csharp
var client = new ElasticClient(nodeUri);

await client.Indices.CreateAsync("my_index2", index =>
    index.Settings(settings =>
        settings.Similarity(similarity =>
            similarity.BM25("default", _ => new BM25Similarity())
        )
    )
);
```

In Elasticsearch-net client you cannot specify name:
```csharp
var client = new ElasticsearchClient(nodeUri);

await client.Indices.CreateAsync("my_index1", index =>
    index.Settings(settings =>
        settings.Similarity(similarity =>
            similarity.Bm25(_ => { })
        )
    )
);
```

The NEST version creates this:
![image](https://github.com/elastic/elasticsearch-net/assets/102522083/f2cfc896-92b5-4c20-88fa-055ba9c22c65)

The Elasticsearch-net creates this:
![image](https://github.com/elastic/elasticsearch-net/assets/102522083/c321479d-e805-4fcf-8659-a4c47a3079b0)

You cannot create "default" similarity.
You cannot create more similarites of same type with different name and settings.

**Comment by flobernd** [comment]
Hi @petr-horny-bsshop, thanks for reporting!

Version 8.13.0 will be released on April 3rd. This version is the first one based on a completely revisited code generator. For the cost of some breaking changes, a lot of the previously unsupported features and endpoints will be available.

I just tested your case in the 8.13 code-base and I can confirm, that the following will be supported again:

```csharp
await client.Indices.CreateAsync("my_index1", index =>
	index.Settings(settings => settings
		.Similarity(similarities => similarities
			.Bm25("sim1", _ => { })
			.Bm25("sim2", _ => { })
		)
	)
);
```

and creates the correct request:

```json
{"settings":{"similarity":{"sim1":{"type":"BM25"},"sim2":{"type":"BM25"}}}}
```

**Comment by petr-horny-bsshop** [comment]
Hi @flobernd, that's great news.
