### ISSUE TITLE
How to do BulkUpdates on a property in version 8.x?

### ISSUE THREAD

**Issue by PatriQ94** [elastic/elasticsearch-net#8070]
Include="Elastic.Clients.Elasticsearch" Version="8.12.0"

**Is your feature request related to a problem? Please describe.**
I have 10 million documents in the database. The model looks something like this
```csharp
public class Partner
{
    public Guid Id { get; set; }
    public string Name { get; set; }
    public bool ScreeningRequired { get; set; }
}
```
with a single query, I'd like to bulk update `all` documents and set this bool property ScreeningRequired to true. How to do that? There's no way to find any documentation and no examples on how to do bulk updates.

**Describe the solution you'd like**
A simple-intuitive query, to either bulk update all documents by some property and even better an extension to define by which `ids` to update the said property.

**Describe alternatives you've considered**
Tried also integrating old NEST libraries but its impossible to maintain two libraries and same indexes at the same time.

**Additional context**
Nothing else.

**Comment by flobernd** [comment]
Hi @PatriQ94, 

I think [UpdateByQuery](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docs-update-by-query.html) could be used for that (potentially in combination with script usage).

In case this does not work for you, it might be a good idea to ask that question in the [Elastic Community Forums](https://discuss.elastic.co/) as it's rather related to general ES functionality and not so much related to the client itself. These people might know a better solution for your problem 🙂
