### ISSUE TITLE
Missing implicit operator for range queries

### ISSUE THREAD

**Issue by gpetrou** [elastic/elasticsearch-net#8080]
**Elastic.Clients.Elasticsearch version**: 8.13.1

**Elasticsearch version**: 8.12.0

**.NET runtime version**: 8.0

**Operating system version**:

**Description of the problem including expected versus actual behavior**:
`public static implicit operator Query(NumberRangeQuery numberRangeQuery)` and
`public static implicit operator Query(DateRangeQuery dateRangeQuery)`
are missing from the respective classes.

**Steps to reproduce**:
 1. Try to convert a `NumberRangeQuery` or  `DateRangeQuery` to `Query`.

**Expected behavior**

**Comment by flobernd** [comment]
Hi @gpetrou,

thanks for reporting!

The new generator follows the specification more closely. `NumberRangeQuery` and `DateRangeQuery` are not actually variants of `Query`. The corresponding variant is `RangeQuery` (which is an union of the former types).

It seems like even for `RangeQuery`, no conversion operator is currently being generated which is definitely a bug. I'll as well check what I can do to improve usability of `NumberRangeQuery` and `DateRangeQuery`.

For now, the only way to wrap these types in `Query` is:

```csharp
var query = Query.Range(new RangeQuery(numberRangeQuery));
```
