### ISSUE TITLE
Elastic.Transport.UnexpectedTransportException with Ingest.GetPipelineAsync

### ISSUE THREAD

**Issue by gpetrou** [elastic/elasticsearch-net#8083]
**Elastic.Clients.Elasticsearch version**: 8.13.1

**Elasticsearch version**: 8.11

**.NET runtime version**: 8.0

**Operating system version**:

**Description of the problem including expected versus actual behavior**:
When trying to use `elasticsearchClient.Ingest.GetPipelineAsync(r => r.Id("pipeline_test"));` there is an exception.
This used to work in 8.12.1.

```
 'The converter 'Elastic.Clients.Elasticsearch.Ingest.ProcessorConverter' read too much or not enough. Path: $.pipeline_test.processors[0] | LineNumber: 10 | BytePositionInLine: 7.'
```

**Steps to reproduce**:
 1.
 2.
 3.

**Expected behavior**

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by flobernd** [comment]
Hi @gpetrou,

could you please show me how you configured your `pipeline_test`. Especially the used processors would be nice to know.

Thank you!

**Comment by gpetrou** [comment]
I just used:

`PUT: /_ingest/pipeline/pipeline_test`

```
{
  "description": "description_test1",
  "processors": [
    {
      "geoip": {
        "field": "location_1",
        "ignore_missing": true
      }
    },
    {
      "user_agent": {
        "field": "user_agent_1",
        "ignore_missing": true
      }
    }
  ]
}
```

**Comment by flobernd** [comment]
Thanks! I was able to reproduce the issue. A fix will be released soon, together with the Fields improvements.
