### ISSUE TITLE
Multifield mapping

### ISSUE THREAD

**Issue by s-leonard** [elastic/elasticsearch-net#810]
Is there any way to apply multifield mappings using attributes or any intension to add this in the future?

Im currently mapping multifields like so: 
_searchClient.CreateIndex("indexname", c => c
	.NumberOfReplicas(1)
	.NumberOfShards(1)
	.AddMapping<ItemType>(m => m
		.MapFromAttributes()
		.Properties(props => props
			.MultiField(mf => mf.Name(t => t.Brand).Fields(fs => fs
				.String(s => s.Name(t => t.Brand).Index(FieldIndexOption.analyzed))
				.String(s => s.Name(t => t.Brand.Suffix("raw")).Index(FieldIndexOption.not_analyzed))))

This approach gets a bit messy when you have lots of multifield properties to map.
Adding multiple attributes might be a nicer approach like below:

[ElasticMultiFieldProperty1(Index = FieldIndexOption.analyzed)]
[ElasticMultiFieldProperty2(OmitNorms = true, Index = FieldIndexOption.not_analyzed, Suffix="raw")]
public string Brand { get; set; }
        
or is there another way i havent seen so apply multifield mappings?

thanks

**Comment by jayhilden** [comment]
@gmarz should this story be marked as complete and part of release 1.1?

**Comment by gmarz** [comment]
@jayhilden actually this was never implemented.  See the comments in #827 as to why.

**Comment by jayhilden** [comment]
Thank you for the update @gmarz.

**Comment by Mpdreamz** [comment]
closing this because both me and @gmarz are not a fan of exposing too much via attributes.
