### ISSUE TITLE
MultisearchBody does not support being written to JSON

### ISSUE THREAD

**Issue by insulationman** [elastic/elasticsearch-net#8106]
**Elastic.Clients.Elasticsearch version**:
8.13

**Elasticsearch version**:

**.NET runtime version**:
8.0

**Operating system version**:

**Description of the problem including expected versus actual behavior**:
The client throws an error when trying to execute a MultiSearch request with the following error message:
`Elastic.Transport.UnexpectedTransportException: 'MultisearchBody' is a readonly type, used only on responses and does not support being written to JSON.`

**Steps to reproduce**:
 1. Instantiate a MultiSearchRequest
 2. Instantiate a SearchRequestItem with valid parameters for MultiSearchHeader and MultiSearchBody.
 3. Append the SearchRequestItem to the Searches property of the request.
 4. Using the request as the input parameter, start a MultiSearch using client.MultiSearchAsync

**Expected behavior**
The client should perform a multisearch after the Request is Serialized.

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by flobernd** [comment]
Hi @insulationman,

thanks for reporting! This is fixed in 8.13.5.
