### ISSUE TITLE
406 Content-Type header [application/vnd.elasticsearch+json;compatible-with=8] is not supported

### ISSUE THREAD

**Issue by langhaoabcd** [elastic/elasticsearch-net#8112]
``` 
//Elastic.Clients.Elasticsearch: 8.13.5
var nameValueCollection = new NameValueCollection
{
    { "Content-Type", "application/json" }
};
var settings = new ElasticsearchClientSettings(new Uri(ES_URL))
                 .GlobalHeaders(nameValueCollection)
                .Authentication(new BasicAuthentication(ES_NAME, ES_PWD))
                .EnableDebugMode();
var elasticsearchClient = new ElasticsearchClient(settings);

var idsQuery = new IdsQuery();
idsQuery.Values = new Ids(new[] { "46016822" });
var response = await elasticsearchClient.DeleteByQueryAsync(new DeleteByQueryRequest("test_saas_index")
{
    Query = idsQuery
});
```

Invalid Elasticsearch response built from a unsuccessful (406) low level call on POST: /test_saas_index/_delete_by_query?pretty=true&error_trace=true
 Exception: Request failed to execute. Call: Status code 406 from: POST /test_saas_index/_delete_by_query?pretty=true&error_trace=true. ServerError: Type:  Reason: "Content-Type header [application/vnd.elasticsearch+json;compatible-with=8] is not supported"

### Audit trail of this API call:
 - [1] BadResponse: Node: http://localhost:9200/ Took: 00:00:01.1987679
###  Request:
{
  "query": {
    "ids": {
      "values": [
        "46016822"
      ]
    }
  }
}
###  Response:
{
  "error" : "Content-Type header [application/vnd.elasticsearch+json;compatible-with=8] is not supported",
  "status" : 406
}

###  TCP states:
  Established: 87
  TimeWait: 14
  CloseWait: 19

###  ThreadPool statistics:
  Worker: 
    Busy: 0
    Free: 32767
    Min: 8
    Max: 32767
  IOCP: 
    Busy: 0
    Free: 1000
    Min: 8
    Max: 1000

**Comment by flobernd** [comment]
Hi @langhaoabcd, what is the server version you are trying to connect to?

**Comment by langhaoabcd** [comment]
@flobernd Its Elasticsearch Clusters Version 7.4.0

**Comment by flobernd** [comment]
Hi @langhaoabcd,

using the 8.x client on a 7.x cluster is not supported. Please check the version compatibility matrix on the README. You have to upgrade your cluster to 8.x or use NEST 7.17.

Some requests without a body might work, but the majority won't.
