### ISSUE TITLE
Add missing fields back to TaskStatus

### ISSUE THREAD

**Issue by RolfDeVries** [elastic/elasticsearch-net#8113]
**Elastic.Clients.Elasticsearch version**:
8.13.5

**Elasticsearch version**:
N/A

**.NET runtime version**:
.Net 8.0

**Operating system version**:
N/A

**Description of the problem including expected versus actual behavior**:
I'm upgrading from NEST 7.latest to the new Elastic.Clients.Elasticsearch version.
And I'm missing some features that are not yet supported

**Steps to reproduce**:
 1. Call the Tasks.GetAsync api: 
 
                var task = await client.Tasks.GetAsync(taskId.FullyQualifiedId);
                var deletedCount = task.Task.Status.Deleted;

**Expected behavior**
In the NEST 7 version, the properties Deleted, Inserted, Updates etc.. existed
In the Elastic.Client.Elasticsearch 8 these fields are missing, please add those

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by flobernd** [comment]
Hi @RolfDeVries,

the documentation of `Task.Status` mentions:

> Task status information can vary wildly from task to task

It was decided to change the type of `Status` to `object` as it's impossible to correctly model this type (without knowing the kind of the task beforehand).

As a workaround you can do something like this:

```csharp
var result = client.Tasks.Get(...);
var jsonStatus = (JsonElement)result.Task.Status!;
var status = JsonSerializer.Deserialize<TaskStatus>(jsonStatus);
```

while using the old NEST datatype:

```csharp
	public class TaskStatus
	{
		[DataMember(Name = "batches")]
		public long Batches { get; internal set; }

		[DataMember(Name = "created")]
		public long Created { get; internal set; }

		[DataMember(Name = "deleted")]
		public long Deleted { get; internal set; }

		[DataMember(Name = "noops")]
		public long Noops { get; internal set; }

		[DataMember(Name = "requests_per_second")]
		public float RequestsPerSecond { get; internal set; }

		[DataMember(Name = "retries")]
		public TaskRetries Retries { get; internal set; }

		[DataMember(Name = "throttled_millis")]
		public long ThrottledMilliseconds { get; internal set; }

		[DataMember(Name = "throttled_until_millis")]
		public long ThrottledUntilMilliseconds { get; internal set; }

		[DataMember(Name = "total")]
		public long Total { get; internal set; }

		[DataMember(Name = "updated")]
		public long Updated { get; internal set; }

		[DataMember(Name = "version_conflicts")]
		public long VersionConflicts { get; internal set; }
	}
```

Note, that this migth yield incorrect results, depending on the kind of the task.

**Comment by RolfDeVries** [comment]
Thanks, I was expecting such an answer:-)
The workaround will do for now.
