### ISSUE TITLE
No response class implementation for Get index settings

### ISSUE THREAD

**Issue by RolfDeVries** [elastic/elasticsearch-net#8115]
**Elastic.Clients.Elasticsearch version**:
8.13.5

**Elasticsearch version**:
N/A

**.NET runtime version**:
.Net 8.0

**Operating system version**:
N/A

**Description of the problem including expected versus actual behavior**:
I'm upgrading from NEST 7.latest to the new Elastic.Clients.Elasticsearch version.
And I'm missing some features that are not yet supported

**Steps to reproduce**:
 1. Create code to call the Get index settings API 

var result = await Client.Indices.GetSettingsAsync(s => s
    .Indices(indexName)
    .Name("index.analysis.filter." + filterName + ".*")
);

 2. Trying to parse the response to get a specific setting: 
 
var indexState = result?.Indices?[indexName];

**Expected behavior**
In the NEST 7 version, this was easily done
In the Elastic.Client.Elasticsearch 8 it seams that all .net properties are protected and not accesable
Please make sure that this code is backwards compatible with minor effort

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by apr-un** [comment]
I get similar problem in Elastic.Clients.Elasticsearch version: 8.13.12 running on .net 8

```
var indexName = "myindex"; // this index exists
var response = await _elasticClient.Indices.GetSettingsAsync(Indices.Index(indexName), indexName);
if (response.IsValidResponse)
{
  // no known way to get settings from index :(  but I see in debug that Backing Dictionary contains all settings  
  // response.BackingDictionary["myindex"].Settings.Index; // sealed/inaccessible, 
}
```

**Expected result:** response contain function/property to get current IndexSettings

**Comment by apr-un** [comment]
@flobernd any info on this? The same problem still exists on 8.14.2

**Comment by flobernd** [comment]
@apr-un I will update the issue if there is any progress.

**Comment by gtoth93** [comment]
In case someone is struggling with this, here is a low level client request that gets a specific index setting:
```csharp
var indexName = "index-name";
var key = "index.mapping.total_fields.limit";
var settingsResponse = await Client.Transport.RequestAsync<BytesResponse>(
    HttpMethod.GET,
    $"/{indexName}/_settings/{key}",                    // Request path
    null,                                                                  // Request body
    new GetIndicesSettingsRequestParameters(), // Query params
    cancellationToken);

using var stream = new MemoryStream(settingsResponse.Body);
var responseBody = Client.RequestResponseSerializer.Deserialize<Dictionary<IndexName, IndexState>>(stream);
```
To deserialize the response, I used the client's RequestResponseSerializer, which only accepts a stream as a parameter, so I wrapped the response body in a MemoryStream. Maybe there is a more efficient way, but at least it works.
