### ISSUE TITLE
Provide support for filter_path for all apis

### ISSUE THREAD

**Issue by RolfDeVries** [elastic/elasticsearch-net#8116]
**Elastic.Clients.Elasticsearch version**:
8.13.5

**Elasticsearch version**:
N/A

**.NET runtime version**:
.Net 8.0

**Operating system version**:
N/A

**Description of the problem including expected versus actual behavior**:
I'm upgrading from NEST 7.latest to the new Elastic.Clients.Elasticsearch version.
And I'm missing some features that are not yet supported

**Steps to reproduce**:
 1. Create code to call a random api, any api will do:

        var response = await client.Cluster.StatsAsync(s => s
            .FilterPath(filterPath)
        );

**Expected behavior**
In the NEST 7 version, the FilterPath option was very easy to use
In the Elastic.Client.Elasticsearch 8 there is no support for this, please add it back for performance reasons

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by flobernd** [comment]
Hi @RolfDeVries,

thanks for reporting. It seems that the `FilterPath` setting currently is only available for the request classes (e.g. `StatsRequest`), but not the corresponding descriptors (`StatsRequestDescriptor`). I'll fix that in one of the next patch releases.

**Comment by RolfDeVries** [comment]
Thank you very much!

**Comment by RolfDeVries** [comment]
Hi,

Any update on this? This is a blocking issue for migration from 7 to 8 on my projects.

Gr Rolf

**Comment by flobernd** [comment]
Hi @RolfDeVries, sorry for the delay. There was a lot of higher priority things to do which caused this issue to drop of my radar. I just created a PR and will publish a new patch release in the next hours 🙂
