### ISSUE TITLE
ExtendedBounds missing from DateHistogramAggregationDescriptor<TDocument>

### ISSUE THREAD

**Issue by matteocalisti** [elastic/elasticsearch-net#8122]
**Elastic.Clients.Elasticsearch version**: 8.13.5

**Elasticsearch version**: 8.13.0

**.NET runtime version**: 6.0

**Operating system version**: Windows 10

**Description of the problem including expected versus actual behavior**:
`ExtendedBounds` method is not yet present in `DateHistogramAggregationDescriptor`.

**Steps to reproduce**:

**Expected behavior**

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

Is there a workaround to use `extended_bounds` while we wait for the implementation on the client?
Thanks!

**Comment by flobernd** [comment]
Hi @matteocalisti, there currently is no workaround, but I'll have a look at this right away in the beginning of next week!
