### ISSUE TITLE
Unable to perform knn query [knn] unknown field [k

### ISSUE THREAD

**Issue by alkampfergit** [elastic/elasticsearch-net#8124]
**Elastic.Clients.Elasticsearch version**:

**Elasticsearch version**:
8.13.0
**.NET runtime version**:
.NET 8
**Operating system version**:
Windows 11
**Description of the problem including expected versus actual behavior**:
I've created a knn query with the following syntax

```
        var knnOuterQuery = new QueryDescriptor<object>().Knn(knn => knn
            .Filter(query)
            .Field("vector")
            .NumCandidates(limit * 2)
            .QueryVector(coll));
```

Then I got an error:  ServerError: Type: x_content_parse_exception Reason: "[9:7] [knn] unknown field [k]"

Looking for generated query it contains a k value that it is not supported: this is the request where you can see a k : 0 that is not correct. If I remove that parameter and try to execute the query everything seems to work just fine.

```
{
  "from": 0,
  "query": {
    "knn": {
      "field": "vector",
      "filter": {
        "match_all": {}
      },
      "k": 0,
      "num_candidates": 10,
      "query_vector": [
        -0.0546875,
        -0.53125,
        0.453125,
        -0.484375
      ]
    }
  },
  "size": 5
}
```

Indeed the driver has that parameter in the request, but seems not to be understood by the server. I'm constructing the query from a QueryDescriptor<object>() object.

![image](https://github.com/elastic/elasticsearch-net/assets/358545/d746125b-1a7c-4670-9d80-340215bb1bd7)

Am I doing something wrong or the driver indeed add a wrong "k" argument to the query?

**Comment by pquentin** [comment]
Hello! This is a known issue in the Elasticsearch specification that will be fixed in the next version of the .NET client: https://github.com/elastic/elasticsearch-specification/pull/2490. Sorry about that.

**Comment by alkampfergit** [comment]
Is an older version of the driver that works with it? Actually this is pretty a blocking issue in a project of mine because we are planning to use Elastic as vector search.....

**Comment by flobernd** [comment]
As @pquentin said, it's already fixed in the specification. The fix will propagate to the .NET client in the next few days. There is no older version of the 8.* client that correctly supports KNN queries. Hope you don't mind waiting a couple of days 🙂 I'll try to do a patch release already today, but can't promise anything.

**Comment by flobernd** [comment]
Fixed in 8.13.6

**Comment by alkampfergit** [comment]
Confirmed! All test are green now on my project.

Thanks again!!!

**Comment by flobernd** [comment]
@alkampfergit Happy to help you out 🙂 As well thanks to @l-trotta for fixing this issue upstream in the specification.
