### ISSUE TITLE
Elasticsearch client is missing Synonyms Set configuration in Analysis.SynonymGraphTokenFilter

### ISSUE THREAD

**Issue by avaudo** [elastic/elasticsearch-net#8125]
### Elasticsearch Version

8.13.1

### Java Version

_bundled_

### OS Version

windows 11

### Problem Description

The Elastic.Clients.Elasticsearch library for .Net (8.13.5 or earlier) is completely missing the ability to create a SynonymGraphTokenFilter using a synonyms set.  It only allows for a list of synonym words or a synonyms path, not a synonyms set that was created through the Synonyms API.  This is almost an identical issue that somebody reported here, but for Java.

https://github.com/elastic/elasticsearch-java/issues/781

### Steps to Reproduce

There is absolutely no way to create a filter like below using the elastic client library (8.13.5 or earlier) .

  "filter": {
    "synonyms_filter": {
      "type": "synonym_graph",
      "synonyms_set": "my-synonym-set",
      "updateable": true
    }
  }

**Comment by flobernd** [comment]
@avaudo Hi! Thanks for reporting. This is a specification issue which means it is fixed on a central place for all (most) language clients. @l-trotta already took care of this after it was reported for the Java client. It will be fixed for .NET in one of the next patch releases as well.

**Comment by flobernd** [comment]
@avaudo Yes
