### ISSUE TITLE
Dictionary exception in BucketsPathConverter

### ISSUE THREAD

**Issue by gpetrou** [elastic/elasticsearch-net#8126]
**Elastic.Clients.Elasticsearch version**: 8.13.5

**Elasticsearch version**: 8.11

**.NET runtime version**: 8.0

**Operating system version**:

**Description of the problem including expected versus actual behavior**:
Check https://github.com/elastic/elasticsearch-net/blob/00c8b422cc55b3fb8b4ea1f1bd223974e8c0be93/src/Elastic.Clients.Elasticsearch/_Generated/Types/Aggregations/BucketsPath.g.cs#L120.
It tries to use multiple empty keys and this will eventually lead to Dictionary exceptions when attempting to use the buckets path functionality.
This makes it impossible to use BucketSelectorAggregation.

**Steps to reproduce**:
 1.
 2.
 3.

**Expected behavior**

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by flobernd** [comment]
Hi @gpetrou, thanks again for reporting.

This looks like a bad one. I'll look at it later today.

**Comment by flobernd** [comment]
It seems like I have to hand-craft the converter for this type as it's an union of `string | string[] | Dictionary<string, string>` and/or potentially improve the `MultiItemUnionConverter<TUnion, TEnum>` type to be able to handle these unions that contain multiple different datatypes.

**Comment by gpetrou** [comment]
@flobernd any updates on this?

**Comment by flobernd** [comment]
Fixed in 8.13.10
