### ISSUE TITLE
Missing && operator between aggregations

### ISSUE THREAD

**Issue by gpetrou** [elastic/elasticsearch-net#8133]
**Elastic.Clients.Elasticsearch version**: 8.13.5

**Elasticsearch version**: 8.11

**.NET runtime version**: 8.0

**Operating system version**:

**Description of the problem including expected versus actual behavior**:
It looks like in 8.13.x versions we cannot use && operator between aggregations. Has this been replaced by something else? If yes, what is that? If no, are you planning to add this back?

**Steps to reproduce**:
 1.
 2.
 3.

**Expected behavior**

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by flobernd** [comment]
I hope you understand, that I can not bring this functionality back for technical reasons. I will make sure to document that in the release notes of 8.13.0.

**Comment by gpetrou** [comment]
I see. OK. Thanks.

**Comment by a-witkowski** [comment]
@flobernd, can you show me how to initialize Aggregation with aggregations in the latest 8.13.* client?

How "translate" this query in C#:
```
{
    "from": 0,
    "size": 100,
      "collapse": {
        "field": "uniqueId"
    },
    "query": {
        "match": {
            "Content": "test word"
        }
    },
    "aggregations": {
        "my-terms aggs": {
            "terms": {
                "field": "seqId",
                "size": 100
            },
          	"aggregations": {
        		"my-cardinality-agg": {
          			"cardinality": {
            			"field": "uniqueId"
          			}
       			}
      		}
        }
    }
}
```

- [ ] i must set and use "my-terms aggs" and "my-cardinality-agg" in code
- [ ] uniqueId and seqId are different fields
- [ ] search is performed on aliases that may contain duplicates

I tried

```
Aggregation.Terms(new TermsAggregation
{
  Field = Infer.Field("seqId"),
  Size = 100
}).Aggregations = new Dictionary<string, Aggregation>
{
  {
    "my-cardinality-agg",
    new CardinalityAggregation { Field = "uniqueId" }
  }
}
```
but how to set up name "my-terms aggs" in TermsAggregation in that case?
