### ISSUE TITLE
Missing Public Constructor on Type  Elastic.Clients.Elasticsearch.Fields

### ISSUE THREAD

**Issue by DavidHoechtlJH** [elastic/elasticsearch-net#8152]
**Elastic.Clients.Elasticsearch version 8.13.7

**Elasticsearch version 8.12.2

**.NET runtime version .net 8

**Operating system version windows 11

I want to declare a instance of MulitMatchQuery with multiple Fields. The property of MulitMatchQuery.Fields is of Type Fields, which i cannot initialize.

Missing public constructor

**Steps to reproduce**:
 1. Install nuget Elastic.Clients.Elasticsearch 8.13.7
 2. Try initialize a Fields instance

**Comment by DavidHoechtlJH** [comment]
I see, it inherits from IEnumerable<Field> so i can pass that instead of a fieldsinstance. I think this is very confusing tho, is this as expected ?

**Comment by flobernd** [comment]
@DavidHoechtlJH Yes, take a look at the different implicit conversion operators of this class. You can even use lambda expressions to initialize the Fields.

I think it's good practice to have matching static methods for each implicit operator like "Fields.FromStrings(...)" etc. I'll try to add these in one of the next releases.
