### ISSUE TITLE
Latest MINOR package version does not support .Net 6 anymore.

### ISSUE THREAD

**Issue by deMD** [elastic/elasticsearch-net#8179]
**Elastic.Clients.Elasticsearch version**: 8.13.11

**.NET runtime version**: .Net 6

**Description of the problem including expected versus actual behavior**:
When deploying a Function App to Azure, we get an error and the app does not start.

```
Error configuring services in an external startup class. Elastic.Transport: Could not load file or assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
```

**Steps to reproduce**:
 1. Create a .Net 6 In Process Function App
 2. Reference the Elasticsearch Client
 3. Deploy on Azure

**Expected behavior**
A reference to at least a version of Elastic.Transport that supports .Net 6 (0.4.17) when that is the Target Framework

**Comment by flobernd** [comment]
Hi @deMD,

this looks like something specific to the weird Azure functions runtime.

Elastic.Transport targets net6 - just like the ES client does. However, all new versions are pulling in System.Text.Json 8. This shouldn't be a problem as it is just a regular NuGet package (and as well has a dedicated net6 target).

I know from my past experience, that the Azure Functions SDK might remove packages during the pack/deployment step. There was a trick to prevent it from removing specific packages, but I sadly can't remember what was required for that. Maybe you can do some research in that direction.
