### ISSUE TITLE
Elastic.Transport.UnexpectedTransportException with Indices.GetAsync

### ISSUE THREAD

**Issue by feherbbj** [elastic/elasticsearch-net#8180]
**Elastic.Clients.Elasticsearch version**: 8.12.0

**Elasticsearch version**: 8.12.2

**.NET runtime version**: 8.0

**Operating system version**:

**Description of the problem including expected versus actual behavior**:
Try to use await client.Indices.GetAsync(....) and it throws 
Elastic.Transport.UnexpectedTransportException : The JSON value could not be converted to System.Collections.Generic.ICollection`1[System.String]. Path: $.relations.entry | LineNumber: 0 | BytePositionInLine: 

I have an index with a relation:
  "mappings": {
    "properties": {
     .......
      "parentChild": {
        "type": "join",
        "relations": {
          "entry": "term"
        }
      },
    .........

**Expected behavior**
Previously this does not throw any exception and based on the official web site, it is a valid relation still

**Comment by flobernd** [comment]
Hi @feherbbj,

just to clarify. Are you really using `Elastic.Clients.Elasticsearch` 8.12.0?

**Comment by feherbbj** [comment]
Yes, i started the migration in this march from 7.x and since there are parallel issue and our caode base is large. I still on 8.12.0. If the issue is fixed in later versions, i might consider upgrading.

**Comment by flobernd** [comment]
Thanks for the response. Yes, this looks like it is the same bug as in #7871 which meanwhile was fixed.

**Comment by feherbbj** [comment]
Thanks for the info
