### ISSUE TITLE
Indices.ExistsAsync throw exception due to ICU field

### ISSUE THREAD

**Issue by feherbbj** [elastic/elasticsearch-net#8181]
**Elastic.Clients.Elasticsearch version**: 8.12.

**Elasticsearch version**: 8.12.2

**.NET runtime version**: 8.0

**Description of the problem including expected versus actual behavior**:
I have an ES instance with ICU plugin installed, when i call Indices.ExistsAsync(...) it throws exception because it cannot deserialize a property with field icu_collation_keyword to 'Mapping.IProperty'

**Expected behavior**
This used to work in 7.x

**Comment by flobernd** [comment]
Hi @feherbbj,

could you please send me the response JSON payload so that I can reproduce the issue?

**Comment by feherbbj** [comment]
index is like:
{
   ...,
   "mappings": {
      "properties": {
         "itemname": {
            "type": "text",
            "fields": {
               ...
               "icu": { "type": "icu_collation_keyword" }
            }
         }
      }
   }
}
The repsonse is for await client.Indices.GetAsync(Indices.All):
Elastic.Transport.UnexpectedTransportException : Encountered an unsupported variant tag 'icu_collation_keyword' on 'Mapping.IProperty', which could not be deserialized.
  ----> System.Text.Json.JsonException : Encountered an unsupported variant tag 'icu_collation_keyword' on 'Mapping.IProperty', which could not be deserialized.
   at Elastic.Transport.DefaultHttpTransport`1.ThrowUnexpectedTransportException[TResponse](Exception killerException, List`1 seenExceptions, RequestData requestData, TResponse response, RequestPipeline pipeline)
   at Elastic.Transport.DefaultHttpTransport`1.RequestCoreAsync[TResponse](Boolean isAsync, HttpMethod method, String path, PostData data, RequestParameters requestParameters, OpenTelemetryData openTelemetryData, CancellationToken cancellationToken)

**Comment by flobernd** [comment]
@feherbbj Could you please double check this as well in 8.13.x when you are ready to migrate? This should already be fixed as well.

**Comment by feherbbj** [comment]
i can confirm, this issue is fixed
