### ISSUE TITLE
Queries are no longer derive from SearchQuery 

### ISSUE THREAD

**Issue by feherbbj** [elastic/elasticsearch-net#8182]
**Elastic.Clients.Elasticsearch version**: 8.13.x or 8.14

**Elasticsearch version**: 8.12.2

**.NET runtime version**: 8.0

**Description of the problem including expected versus actual behavior**:
Queries are no longer derive from SearchQuery ( I Mean TermsQuery, WildcardQuery...etc). Is there a reason for that? This way operators (&& or ||) cannot be applied. In earlier versions 8.12.0 or before they did derive from SearchQuery

**Expected behavior**
All query must derive from SearchQuery

**Comment by flobernd** [comment]
Hi @feherbbj,

this is a change that was introduced with the new code generator. It was required to be able to generically support similar constructs in our specification.

The container class `Query` still supports the use of the `&&` and `||` operators.

The change is documented in the release notes of 8.13.0:
https://github.com/elastic/elasticsearch-net/releases/tag/8.13.0

**Comment by feherbbj** [comment]
Hi @flobernd ,

Thank you for the answer. I did not notice this breaking change, but even with your response I don't really understands the reason behind it.
It really seems like with every version, there is a step back for the C# API, since the latest 7.16 NEST nuget package. Loosing the mix usage of QueryDescriptor and Query objects, loosing built-in formatters (eg Stack object is deserialized inversed order compare to the original input) and this change could also trigger a lot of extra code. I know this is the situation now and users need to accept it, but the old NEST API was more comfortable to use

**Comment by flobernd** [comment]
Hi @feherbbj, thanks for the feedback. Maybe this blog post gives you some more insights about the reasons: https://www.elastic.co/search-labs/blog/net-client-evolution

It's basically just one person (me) maintaining the .NET client these days and we had to reduce scope to keep up with the workload. Now that version 8.13.x is released and finally most of the ES server APIs are supported, I can focus on bringing back some of the convenience features (but note, that bringing back NEST features is case by case decision and not everything will make it into the new client).

**Comment by feherbbj** [comment]
Thanks for the info! Well that explains a lot. That's rough. Wishing you lots of perseverance then
