### ISSUE TITLE
DefaultMappingFor IndexName is not respected in searches

### ISSUE THREAD

**Issue by Genide** [elastic/elasticsearch-net#8184]
**Elastic.Clients.Elasticsearch version**: 8.13.12

**Elasticsearch version**: 8.5.3

**.NET runtime version**: DOTNET 8

**Operating system version**: Windows 10 64 bit

**Description of the problem including expected versus actual behavior**:
Setting a default index name for a given type no longer works. This behavior is what I expected in Elastic.Clients.Elasticsearch version 8.13.11.

**Steps to reproduce**:
 1. Create an `ElasticsearchClient` with client settings that include a default mapping for index names.
 ``` csharp
    var connectionSettings = new ElasticsearchClientSettings(options.Value.CloudId, new ApiKey(options.Value.ApiKey))
        .DefaultMappingFor<Branch>(m => m.IndexName("branches"))
        .EnableDebugMode();

    return new ElasticsearchClient(connectionSettings);
```
 2. Use the `ElasticsearchClient` to search for an object with the mapped index name.
 ``` csharp
        var result = await _client.SearchAsync<Branch>(s => s
            .Query(q => q
                .Term(t => t.Field(f => f.FinancialInstitutionId.Suffix("keyword")).Value(fiid))));
        return result.Documents;
```
 3. See results being returned from all indexes. This is a snippet from `result.DebugInformation`. Notice how the URL path **does not** include the index name.
 > Valid Elasticsearch response built from a successful (200) low level call on POST: /_search?pretty=true&error_trace=true

**Expected behavior**
I expected the following message in `result.DebugInformation`. 
> Valid Elasticsearch response built from a successful (200) low level call on POST: /branches/_search?pretty=true&error_trace=true

**Provide `ConnectionSettings` (if relevant)**: NA

**Provide `DebugInformation` (if relevant)**:  
``` json
Valid Elasticsearch response built from a successful (200) low level call on POST: /_search?pretty=true&error_trace=true

# Audit trail of this API call:
 - [1] HealthyResponse: Node:  OMITTING NODE NAME Took: 00:00:04.9044904
# Request:
{
  "query": {
    "term": {
      "fiid.keyword": {
        "value": "SANDBOX"
      }
    }
  }
}
# Response:
{
  "took" : 4805,
  "timed_out" : false,
  "_shards" : {
    "total" : 57,
    "successful" : 57,
    "skipped" : 46,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 8250,
      "relation" : "eq"
    },
    "max_score" : 11.089042,
    "hits" : [
      {
        "_index" : "branches",
        "_id" : "Rzv3AokBFOgoV9vSRWhT",
        "_score" : 11.089042,
        "_source" : {
          "fiid" : "SANDBOX",
          "branchId" : 0,
          "lat" : 29.8,
          "lon" : -95.4,
          "location" : {
            "lat" : 29.8,
            "lon" : -95.4
          }
        }
      },
      {
        "_index" : "branches_dev",
        "_id" : "Rzv3AokBFOgoV9vSRWhT",
        "_score" : 11.089042,
        "_source" : {
          "fiid" : "SANDBOX",
          "branchId" : 0,
          "lat" : 29.8,
          "lon" : -95.4,
          "location" : {
            "lat" : 29.8,
            "lon" : -95.4
          }
        }
      },
      {
        "_index" : "financial_institutions_dev",
        "_id" : "SANDBOX",
        "_score" : 8.753898,
        "_source" : {
          "fiid" : "SANDBOX",
          "name" : "Dummy Financial"
        }
      },
      {
        "_index" : "financial_institutions",
        "_id" : "SANDBOX",
        "_score" : 8.753687,
        "_source" : {
          "fiid" : "SANDBOX",
          "name" : "Dummy Financial"
        }
      },
    // Omitting the remainder for brevity
    ]
  }
}

# TCP states:
  Established: 301
  TimeWait: 179
  SynSent: 1
  CloseWait: 3

# ThreadPool statistics:
  Worker: 
    Busy: 1
    Free: 32766
    Min: 8
    Max: 32767
  IOCP: 
    Busy: 0
    Free: 1000
    Min: 1
    Max: 1000
```

**Comment by Genide** [comment]
Then is the use of `TConnectionSettings DefaultMappingFor<TDocument>` and `ClrTypeMappingDescriptor<TDocument> IndexName` obsolete?

**Comment by flobernd** [comment]
@Genide No, it's still working - just not for optional `Indices` pararameter 🙂 It works for all other cases like e.g. `Get` or most index management APIs, etc.
