### ISSUE TITLE
Lacks the ability to put aggregations into aggregations

### ISSUE THREAD

**Issue by a-witkowski** [elastic/elasticsearch-net#8198]
**Elastic.Clients.Elasticsearch version**: 8.13.12

**Elasticsearch version**: 8.12.1

**.NET runtime version**: 8.0.5

**Operating system version**: Windows 10 22H2

**Description of the problem including expected versus actual behavior**:
In the old NEST library, it was possible to put aggregations into aggregations with the aggregation name specified
```
new SearchRequest("indeces", Types.All)
{
    Query = query,
    Collapse = new FieldCollapse()
    {
        Field = uniqueIdFieldName
    },
    Aggregations = new AggregationDictionary()
    {
        {
            "my-terms aggs",
            new AggregationContainer()
            {
                Terms = new TermsAggregation()
                {
                    Field = Infer.Field(seqIdFieldName)
                },
                Aggregations = new AggregationDictionary()
                {
                    {
                        "my-cardinality-agg",
                        new AggregationContainer()
                        {
                            Cardinality = new CardinalityAggregation(idFieldName)
                        }
                    }
                }
            }
        }
    },
    From = 0,
    Size = 100
};
```
The new version does not include AggregationDictionary and also any other possibility to achieve the same.

**Expected behavior**
After transformation the output query should look like:
```
{
    "from": 0,
    "size": 100,
      "collapse": {
        "field": "uniqueId"
    },
    "query": {
        "match": {
            "Content": "test word"
        }
    },
    "aggregations": {
        "my-terms aggs": {
            "terms": {
                "field": "seqId",
                "size": 100
            },
          	"aggregations": {
        		"my-cardinality-agg": {
          			"cardinality": {
            			"field": "uniqueId"
          			}
       			}
      		}
        }
    }
}
```

Also I tried:
```
Aggregation.Terms(new TermsAggregation
{
  Field = Infer.Field("seqId"),
  Size = 100
}).Aggregations = new Dictionary<string, Aggregation>
{
  {
    "my-cardinality-agg",
    new CardinalityAggregation { Field = "uniqueId" }
  }
}
```
but how to set up name "my-terms aggs" in TermsAggregation in that case?

**Comment by flobernd** [comment]
Hi @a-witkowski, this is still possible. An example can be found in the release notes of 8.13.0:

https://github.com/elastic/elasticsearch-net/releases/tag/8.13.0

Please feel free to open a new issue, if that does not solve your problem 🙂

**Comment by flobernd** [comment]
```csharp
new SearchRequest("indeces", Types.All)
{
	Query = query,
	Collapse = new FieldCollapse()
	{
		Field = uniqueIdFieldName
	},
	Aggregations = new Dictionary<string, Aggregation>
	{
		{
			"my-terms aggs",
			Aggregation.Terms(new TermsAggregation
			{
				Field = Infer.Field(seqIdFieldName)
			}).Aggregations = new Dictionary<string, Aggregation>
			{
				{
					"my-cardinality-agg",
					new AggregationContainer()
					{
						Cardinality = new CardinalityAggregation(idFieldName)
					}
				}
			}
		}
	},
	From = 0,
	Size = 100
};
```

**Comment by a-witkowski** [comment]
> ```cs
> new SearchRequest("indeces", Types.All)
> {
> 	Query = query,
> 	Collapse = new FieldCollapse()
> 	{
> 		Field = uniqueIdFieldName
> 	},
> 	Aggregations = new Dictionary<string, Aggregation>
> 	{
> 		{
> 			"my-terms aggs", // <- top level aggregation name
> 			Aggregation.Terms(new TermsAggregation // <- top level aggregation
> 			{
> 				Field = Infer.Field(seqIdFieldName)
> 			}).Aggregations = new Dictionary<string, Aggregation>
> 			{
> 				{
> 					"my-cardinality-agg", // <- sub aggregation name
> 					Aggregation.Cardinality(new CardinalityAggregation(idFieldName)) // <- sub aggregation
> 				}
> 			}
> 		}
> 	},
> 	From = 0,
> 	Size = 100
> };
> ```

@flobernd, thank you for quick response but

The best overloaded Add method 'Dictionary<string, Aggregation>.Add(string, Aggregation)' for the collection initializer has some invalid arguments: 
cannot convert from 'System.Collections.Generic.IDictionary<string, Elastic.Clients.Elasticsearch.Aggregations.Aggregation>' to 'Elastic.Clients.Elasticsearch.Aggregations.Aggregation'

What I missed?

**Comment by flobernd** [comment]
@a-witkowski Ah, I see. Could you try this:

```csharp
var myTerms = Aggregation.Terms(new TermsAggregation // <- top level aggregation
{
	Field = Infer.Field("seqIdFieldName")
});

myTerms.Aggregations = new Dictionary<string, Aggregation>
{
	{
		"my-cardinality-agg", // <- sub aggregation name
		Aggregation.Cardinality(new CardinalityAggregation()) // <- sub aggregation
	}
};

new SearchRequest("indeces")
{
	Aggregations = new Dictionary<string, Aggregation>
	{
		{
			"my-terms aggs", // <- top level aggregation name
			myTerms
		}
	},
	From = 0,
	Size = 100
};
```

**Comment by a-witkowski** [comment]
@flobernd, thank you so much. Now it works perfectly!
