### ISSUE TITLE
Missing properties in aggregation API

### ISSUE THREAD

**Issue by petr-horny-bsshop** [elastic/elasticsearch-net#8216]
**Elastic.Clients.Elasticsearch version**: 8.13.x

**.NET runtime version**: 8.0

**Description of the problem including expected versus actual behavior**:
Since version 8.13.0, the aggregation classes are missing properties for sub-aggregations. Property `Aggregation` and property for meta data `Meta` is missing. In previous versions 8.12.x it was ok.

In version 8.12.x you could do:
```csharp
var nestedAggregation = new NestedAggregation("nested");
nestedAggregation.Path = "children";
nestedAggregation.Aggregations = new AggregationDictionary();    // this is missing in 8.13.x
nestedAggregation.Aggregations["max"] = new MaxAggregation("max", "age");  // this is missing in 8.13.x
nestedAggregation.Meta = new Dictionary<string, object> { { "mykey", "myvalue" } };  // this is missing in 8.13.x

var termsAggregation = new TermsAggregation("terms");
termsAggregation.Field = "color";
termsAggregation.Aggregations = new AggregationDictionary();  // this is missing in 8.13.x
termsAggregation.Aggregations["max"] = new MaxAggregation("max", "price");  // this is missing in 8.13.x
termsAggregation.Meta = new Dictionary<string, object> { { "mykey", "myvalue" } };  // this is missing in 8.13.x
```

This reduced API makes it completely impossible to use sub-aggregations. 

Consider unsealing the classes so we can inherit them and add missing members. This would give us the oportunity to create a temporary workaround in many cases.

**Comment by flobernd** [comment]
Hi @petr-horny-bsshop,

please check the release notes for 8.13 for a migration guide:

https://github.com/elastic/elasticsearch-net/releases/tag/8.13.0

Unfortunately we had to do a breaking change here. On the positive side, the client finally supports most endpoints and types now 🙂

**Comment by flobernd** [comment]
For explanation: The sub-aggregations and meta properties are still available. For technical reasons we had to keep the data-structure more closely to the request JSON. Here, the sub-aggregations are part of the aggregation container and not the actual aggregation variants.

**Comment by petr-horny-bsshop** [comment]
Hi @flobernd, 

Thank you, I missed that.
