### ISSUE TITLE
Intervals query is missing the option to set Field

### ISSUE THREAD

**Issue by asal-hesehus** [elastic/elasticsearch-net#8226]
**Elastic.Clients.Elasticsearch version**: 8.14.0

**Elasticsearch version**:8.12.0

**.NET runtime version**: .Net core 7.0

**Operating system version**: Windows 11

**Description of the problem including expected versus actual behavior**:
In version 8.12 of the client there was a Field method that allowed setting the toplevel field in ther intervals query:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-intervals-query.html

The code that compiled in version 8.12:
            queryDescriptor => queryDescriptor.Intervals(intervalsQueryDescriptor => intervalsQueryDescriptor
                .AllOf(intervalsAllOfDescriptor => intervalsAllOfDescriptor
                    .Intervals(intervalsDescriptor => intervalsDescriptor
                        .Match(intervalsMatchDescriptor => intervalsMatchDescriptor
                            .Query($"phrase to match")
                            .MaxGaps(0).
                            Ordered(false))))
                .Field(x => x.SearchText));

The Field method does not exist in version 8.14

**Expected behavior**
There is a way to set the top level field.

**Comment by flobernd** [comment]
Hi @asal-hesehus, thanks for reporting. This seems to be a bug in the new code generator.

**Comment by flobernd** [comment]
Fixed in 8.14.1.

**Comment by asal-hesehus** [comment]
Thanks for the fast fix.
