### ISSUE TITLE
Adding document to Elastic with Client.IndexAsync doesn't await result;  also ambigious function parameters

### ISSUE THREAD

**Issue by apr-un** [elastic/elasticsearch-net#8243]
**Elastic.Clients.Elasticsearch version**: 8.14.2

**Elasticsearch version**: 8.9

**.NET runtime version**: .net 8

**Operating system version**: alpine linux container

**Description of the problem including expected versus actual behavior**:
1. Cannot add document to index
2. Recomended way from documentation https://www.elastic.co/guide/en/elasticsearch/client/net-api/master/source-serialization.html to add document to index is not possible to use due to ambigious parameter types: IndexAsync(TDocument, IndexName, CancellationToken) and IndexAsync(TDocument, Id?, CancellationToken)

**Steps to reproduce**:
Try to execute code - indexResponse is never returned:

```
string indexName = "my-main";
DocumentDto document = new DocumentDto();
document.Id = "cb0e355f-5fb6-b6db-b14d-364bdaf6d6b2"; // some guid
document.Title ="Some title";
document.Description = "Some description";

//var indexResponse = await _elasticClient.IndexAsync(document, indexName); //cannot be compiled due to error "call is ambigious between IndexName and Id?"

IndexRequest<DocumentDto> indexRequest = new IndexRequest<DocumentDto>(document, indexName, document.Id);
var indexResponse = await _elasticClient.IndexAsync(indexRequest); //not awaited, goes somewhere :/ 
if (!indexResponse.IsValidResponse ) // code never gets there
{
    _logger.LogError(string.Format("Error while adding document to index {0}", indexResponse.Result.ToString()));
}

```

**Expected behavior**
Document is added to index or some error is returned. IndexResponse is awaited

**Provide `ConnectionSettings` (if relevant)**:
DefaultIndex is set to prefix "my-*"

**Provide `DebugInformation` (if relevant)**:
nothing is returned

**Comment by flobernd** [comment]
Hi @apr-un 

I can't reproduce the main issue. The same code works perfectly fine on my side. Do you maybe have a network issue? Could you please run `client.InfoAsync()` to check if that's the case?

For the other problem, please try this:

```csharp
var indexResponse = await _elasticClient.IndexAsync(document, index: indexName);
```

or

```csharp
var indexResponse = await _elasticClient.IndexAsync(document, (IndexName)indexName);
```

**Comment by apr-un** [comment]
Thanks for fast reply :)
Methods You mentioned works - thanks 🥇 

Code with IndexRequest started to work after I tested Your methods :o 

client.InfoAsync() looks like doesn't await or like IndexAsync it just behaves weird during debug - I'm adding documents in loop, so it looks like it goes outside of my AddDocument function, then returns in random moments, but in console log it looks ok, so You're probably right about network issues...

I find that `var indexResponse = await _elasticClient.IndexAsync(document)` also works, but it is creating new document every time - it doesnt take Id from POCO model.

**Comment by flobernd** [comment]
I just tested `IndexAsync` and it seems to work as intended for me:

```csharp
await client.IndexAsync(new Person { Id = 1290 });
```

```
Successful (201) low level call on PUT: /idx/_doc/1290?pretty=true&error_trace=true // <- inferred ID in the url

# Request:
{
  "id": 1290, // <- ID in the document
  "data": "NOTHING"
}
```

The second call successfully updates the document:

```
# Response:
{
  "_index" : "idx",
  "_id" : "1290",
  "_version" : 2,
  "result" : "updated",
```

Is your `id` property named correctly?

This is my test POCO type:

```csharp
public class Person
{
	public int Id { get; set; }
```

**Comment by apr-un** [comment]
I think that everything is fine in my definition:
```
   public class DocumentDto
   {
       [JsonPropertyName("id")]
       public string Id { get; set; }
```
and in client settings:
```
var settings = new ElasticsearchClientSettings(_elasticSearchUri)
    .DefaultMappingFor<DocumentDto>(a => a.IdProperty(nameof(DocumentDto.Id).ToLowerInvariant()))
```
I used JsonPropertyName before and it works correctly (In 7.x client I marked my dto with `[ElasticType(IdProperty = nameof(Id))]` but I belive it's not supported anymore? )

**Comment by flobernd** [comment]
Could you please try this instead:

```csharp
.DefaultMappingFor<DocumentDto>(x => x.IdProperty(p => p.Id))
```

As an alternative, try to remove the `ToLowerInvariant` as you are specifying the CLR type property and not the lower-case JSON representation.

In the NEST attribute you as well used `nameof(Id)` and not `nameof(Id).ToLowerInvariant()` 😅

**Comment by apr-un** [comment]
You're right, IdProperty shouldn't be lowercased :( 
Your code works fine - I just need to change default index to be exactly named, not wildcard.

To be honest I'm"experimenting" with everything due to lack of complete more complex examples for .net client 8.x ;)
Thank You for support 👍

**Comment by flobernd** [comment]
@apr-un Thanks for updating the post regarding the initial issue!

Happy to help! Don't hesitate to open a new issues if you have further questions.
