### ISSUE TITLE
upsert operation and refresh set to 3s 

### ISSUE THREAD

**Issue by Blqck666** [elastic/elasticsearch-net#8253]
**Elastic.Clients.Elasticsearch version**: 8.14.2

**Elasticsearch version**:8.11.1

**.NET runtime version**:net8.0

**Operating system version**:windows

**Description of the problem including expected versus actual behavior**:

i'm doing upsert like this 
public async Task AddOrUpdate(Car car, CancellationToken cancellationToken)
    {
        await _client.IndexAsync(user, i => i
                .Index(latestIndexName)
                .Id(car.Id),
            cancellationToken);
    }
and i set refresh interval to be 3s , and i DisableIdInference
now any event that came before the refresh is done for the same car id will create a duplicate of it instead of update 
**Steps to reproduce**:
 1.set refresh to 3s
 2.disableIdinference
 3.call this method for the same car multiple times within 3s interval

**Expected behavior**
i'm not sure how this should be handled , setting refresh manually just after indexasync will make the service more slow.
**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by flobernd** [comment]
Hello @Blqck666, this does not sound like a client related issue. If I understood correctly, you are looking for advice of how to make your cluster more efficient in case of frequent upserts.

Please post your question in the community forums instead: https://discuss.elastic.co/c/elastic-stack/elasticsearch/6
