### ISSUE TITLE
Support OpentTelemetry Metrics 

### ISSUE THREAD

**Issue by Alirexaa** [elastic/elasticsearch-net#8265]
**Is your feature request related to a problem? Please describe.**
Colleccting Stats from nodes, indices and cluster for monitoring is not easy. 

**Describe the solution you'd like**
I think its good to support such metrics as OTel Spec.
This client support tricing via using `ActivityResource` so it can easly works with OpentTelemetry in .NET, i think we should use same approach to add elastic search metrics to our applications. 

**Describe alternatives you've considered**

**Additional context**

**Comment by flobernd** [comment]
Hi @Alirexaa, could you please elaborate which statistics would be useful to you or what the usecase is?
