### ISSUE TITLE
MachineLearning.GetTrainedModelsStats throws a deserialization exception part 2

### ISSUE THREAD

**Issue by svalbuena** [elastic/elasticsearch-net#8281]
**Elastic.Clients.Elasticsearch version**: 8.14.6

**Elasticsearch version**: 8.14.3

**.NET runtime version**: 8.0

**Operating system version**: Windows

**Description of the problem including expected versus actual behavior**:
I'm using the `MachineLearning.GetTrainedModelsStatsAsync` call to get the stats of a trained model, this request always results in a JSON deserialization error. In a previous [issue](https://github.com/elastic/elasticsearch-net/issues/8271) I fixed one of the errors but there are a couple more left.
In https://github.com/elastic/elasticsearch-specification/issues/2762 I describe the root cause and address it in https://github.com/elastic/elasticsearch-specification/pull/2763.

This time, I've downloaded the .net client project, done the equivalent tweaks I'm doing in the spec project, and tested the request to verify there are no other errors left.

**Comment by flobernd** [comment]
Hi @svalbuena, thanks again for creating the spec PR! The fix will be included tomorrow in the 8.15.0 release.
