### ISSUE TITLE
Any example of doing Join with .Net Client?

### ISSUE THREAD

**Issue by draxtor** [elastic/elasticsearch-net#8311]
Hello, 
none of the examples of Join with .NET are working with ElasticSearch.Net. I tried with 8.12 and 8.15.2
Git Copilot suggested that for 8.15.2 this should work:
```
.Join(j => j
    .Name(n => n.JoinField)
    .Relations(r => r
        .Join<Parent, Child>()
    )
)
```
But it doesn't it says that my parent class do not have property called Name.

So if anyone has example, link to documentation it would be nice

Thanks

**Comment by flobernd** [comment]
Hi @draxtor,

I assume you try to create the mapping for a join field using the Elasticsearch v8 client?

The following example should get you started:

```csharp
var response = await client.Indices.PutMappingAsync<Test>(m => m
    .Properties(p => p
        .Join(j => j.MyJoinField, j => j
            .Relations(x => x
                .Add("question", "answer") // Currently it's not possible to specify the relations by using a lambda expression
            )
        )
    )
);
```

Please let me know, if that solves your issue.

**Comment by draxtor** [comment]
Thanks @flobernd the error is gone.
Currently child classes have not been indexed I am inspecting it now

Parent is: 
`item.JoinField = JoinField.Root<Instruction>(); `

Child:
`task.JoinField = JoinField.Link<InstructionTask>(item.InstructionId)`

And join setup is:
`.Join(j => j.JoinField, objConfig => objConfig.Relations(r => r.Add("instruction", "instructiontask")))`

I use the same method and index for both parent and child:
```
await Client.IndexAsync(item, index, id: item.InstructionId);
await Client.IndexAsync(task, index, id: $"T{count}");
```
I fake children so each instruction should have one child.

I put another run because  I was not sure if there are any dependencies between class names and strings in relations (it was task before when it was not working). I'll post here what happened.

**Comment by draxtor** [comment]
I am getting exception when indexing child objects.

> Exception: Request failed to execute. Call: Status code 400 from: PUT /search-joinedinstructions/_doc/T1. ServerError: Type: document_parsing_exception Reason: "[1:210] failed to parse: [routing] is missing for join field [joinField]"

I saw that NEST was automatically set the routing value to parentId value. It looks now it is not the case.
Anyone knows how can I set it with ElasticSearchClient?

**Comment by flobernd** [comment]
Hi @draxtor,

```csharp
var parent = new Person { Id = 1337 };
var child = new Person { Id = 1338 };

await client.IndexAsync(child, index: "person", c => c.Routing(Routing.From(parent)));
```

**Comment by draxtor** [comment]
Nice, I'll try it.
I managed to have everything working in the console. so at least mapping is good. I'll try this thing with Routing
Thanks a lot, really

**Comment by draxtor** [comment]
@flobernd  unfortunately  I am getting the same error.

> [routing] is missing for join field [joinField]

Here is my code:
`await Client.IndexAsync(task, index: index, c => c.Routing(Routing.From(item.InstructionId.ToString())));`
I only replaced object with id since I am not having Id property.
I am creating a parent like this:
`await Client.IndexAsync(item, index, id: item.InstructionId.ToString());`

**Comment by flobernd** [comment]
@draxtor, The basic concepts from this [documentation](https://www.elastic.co/guide/en/elasticsearch/client/net-api/6.x/parent-child-relationships.html) are still valid.

I think you have to use `.Routing()` for the parent as well.

Here is a working example:

```csharp
public abstract class MyDocument
{
	public int Id { get; set; }
	public required JoinField MyJoinField { get; set; }
}

public class MyParent : MyDocument
{
	public required string ParentProperty { get; set; }
}

public class MyChild : MyDocument
{
	public required string ChildProperty { get; set; }
}
```

```csharp
var response = await client.Indices.CreateAsync<MyDocument>(m => m
	.Index("jointest")
	.Mappings(m => m
		.Properties(p => p
			.Join(j => j.MyJoinField, j => j
				.Relations(x => x
						.Add(client.Infer.RelationName(typeof(MyParent)), client.Infer.RelationName(typeof(MyChild)))
				)
			)
		)
	)
);

var parent = new MyParent
{
	Id = 1,
	MyJoinField = JoinField.Root<MyParent>(),
	ParentProperty = "parent test"
};

var indexParent = await client.IndexAsync(parent, index: "jointest", i => i.Routing(1)); // Routing.From(parent)

var child = new MyChild
{
	Id = 2,
	MyJoinField = JoinField.Link<MyChild>(1), // JoinField.Link<MyChild, MyParent>(parent)
	ChildProperty = "child test"
};

var indexChild = await client.IndexAsync<MyDocument>(child, index: "jointest", i => i.Routing(1)); // Infer.Route(child)
```

The commented out code shows an automatic way of inferring the route for types that have an `Id` property.

**Comment by draxtor** [comment]
@flobernd First thank you a lot you were more than helpful.
Next, here are the results.  I had to put the Id property to the Parent class.
Only then it worked.
I thought at first, it was because of Base Class missing (your example had that) but no, it works without base class. It works also if I create index by parent class only but with Id in parent.

```
 (item).JoinField = JoinField.Root<Instruction>();
 var response = await Client.IndexAsync(item, index: index, i => i.Routing(item.Id));

 var task = new InstructionTask
 {
     JoinField = JoinField.Link<InstructionTask, Instruction>(item),
      ....
 };
 
 var responseTask = await Client
     .IndexAsync(task, index: index, c => c.Routing(Routing.From(item)));
```


Mapping was Parent only but everything works:
```
 var response = await Client.Indices.CreateAsync<Instruction>(index, c => c
     .Mappings(map => map
         .Properties(p => p
             .Text(i => i.InstructionUid)
             .LongNumber(i => i.Id)
             .Text(i => i.InstructionStatusId)
             .Text(i => i.InstructionStatus)
           ....
```

Thanks again
