### ISSUE TITLE
Global Aggregations in elastic search client version 8.13

### ISSUE THREAD

**Issue by Bhavyagc02** [elastic/elasticsearch-net#8321]
**Elasticsearch.Net version - 8.0**:

**Elasticsearch version - 8.13**: - upgraded from version 8.11 to 8.13

**.NET runtime version - 8.0**:

**Operating system version - win11**:

**Description of the problem including expected versus actual behavior**:
Have upgraded elastic version from 8.11 to 8.13, post upgrading we are facing issues with aggregation mainly. below is the code snippet of aggregation. Can somebody help how to achieve the same in latest version because earlier sub aggregation were supported not in the latest version.

**Below is the code snippet**:

```csharp
public GlobalAggregation GetAggregations(SearchDefinition searchDef, Query? multiFieldTermQuery, string? searchFieldConfigName, string globalAggregationName)
  {
      //// create a base query.
      Query qry;
      var aggList = new AggregationDictionary();
      searchDef.FieldFilters.ForEach(f =>
      {
          if (f.IncludeAggregation)
          {
              //// create an aggregation with filter query.
              aggList.Add(new FiltersAggregation(f.FieldName!) { Filters = new Buckets<Query>(this.GetFilterAggregation(searchDef, f.FieldName!, qry)), 
                  Aggregations = new TermsAggregation($"{f.FieldName}") { Field = new Field(f.FieldName! + ".keyword"!), MinDocCount = 0, Size = 10000 } });
          }
      });
      var globalAggregation = new GlobalAggregation(globalAggregationName) { Aggregations = aggList };
      return globalAggregation;
  }
```

**Expected behavior**
Achieve Global aggregation with the combination of filters and Term aggregation.

**Comment by flobernd** [comment]
@Bhavyagc02 There have been a few breaking changes regarding to aggregations in 8.13. These are documented in the [release notes](https://github.com/elastic/elasticsearch-net/releases/tag/8.13.0).

**Comment by Bhavyagc02** [comment]
@flobernd  Yes please, I need help with sub aggregations with filter aggregation, earlier **Aggregations** were supported in Filter aggregation class now it is removed, in our case term aggregation is required to find the bucket count based on the filters selected.

`new FiltersAggregation() { Filters = new Buckets<Query>(), 
                ###   Aggregations = new TermsAggregation() { Field = new Field(f.FieldName! + ".keyword"!), MinDocCount = 0, Size = 10000 } }.`

Please find the above code from version 8.11, How can I achieve sub aggregations inside Filter Aggregation, which is now not possible in 8.13 ?


Please let me know if you need further details.

**Comment by flobernd** [comment]
Hi @Bhavyagc02, as explained in the changelog, this is still possible, but the structure changed a bit:

```csharp
await client.SearchAsync<Person>(x => x
    .Aggregations(aggs => aggs
        .Add("filtersagg", agg => agg
            .Filters(f => f
                .Filters(new Buckets<Query>([Query.MatchAll(new MatchAllQuery())]))
            )
            .Aggregations(subs => subs
                .Add("subagg1", agg => agg
                    .Terms(t => t
                        .Field("test")
                        // ...
                    )
                )
            )
        )
    )
);
```

The same is possible with the object initializer syntax:

```csharp
var aggs = new Dictionary<string, Aggregation>();
var filters = Aggregation.Filters(new FiltersAggregation { });
filters.Aggregations = new Dictionary<string, Aggregation>();
filters.Aggregations.Add("subagg1", Aggregation.Terms(new TermsAggregation{ }));
aggs.Add("filtersagg", filters);
```

**Comment by flobernd** [comment]
Hi @Bhavyagc02 , did that answer your question?
