### ISSUE TITLE
IntervalQuery support in .Net Client v8

### ISSUE THREAD

**Issue by jstutson-rel** [elastic/elasticsearch-net#8401]
**Elastic.Clients.Elasticsearch version**: 8.15.10

**Elasticsearch version**: 8.11

**.NET runtime version**: net472

**Operating system version**: irrelevant

The Elastic .net client v8 (8.15.10) appears to be lacking IntervalsQuery functionality.  When I attempt to use the Object Initializer syntax for Elastic.Clients.Elasticsearch.QueryDsl.IntervalsQuery, I am only greeted with the internal constructor for IntervalsQuery with no public constructor available.  I am not sure if this is because it is still a work in progress or actually an accidental omission during code generation.  

```internal IntervalsQuery(string variantName, object variant)```
Other query classes seem to have a second generated class that exposes the public constructors.  Intervals lacks this.

If not implemented yet, when will this be ready?  This is absolutely vital for our active development and a major unforeseen impediment.

**Comment by flobernd** [comment]
Hi @jstutson-rel,

similar to how you use the static `Query.Intervals(...)` factory method, you have to use it for the `IntervalsQuery` itself:

```csharp
var query = Query.Intervals(IntervalsQuery.AllOf(new IntervalsAllOf
{
    // ...
}));
```

Please let me know, if that solves your issue.

**Comment by jstutson-rel** [comment]
Hi @flobernd at first glance I think this is clear now, thank you v much!
