### ISSUE TITLE
Cannot set RequestParameters anymore

### ISSUE THREAD

**Issue by gpetrou** [elastic/elasticsearch-net#8415]
**Elastic.Clients.Elasticsearch version**: 8.16.0

**Elasticsearch version**: 8.12.2

**.NET runtime version**: 8.0

**Operating system version**:

**Description of the problem including expected versus actual behavior**:
In previous versions, we were able to pass `RequestParameters` in ElasticsearchClient.Transport.RequestAsync<StringResponse> method.
It seems that we cannot do that anymore. According to the [release notes](https://github.com/elastic/elasticsearch-net/releases/tag/8.16.0) there were some changes to the Transport library, but once again, it is unclear what to do about them.

**Steps to reproduce**:

```
UpdateDocumentRequestParameters : RequestParameters
{
    public Refresh Refresh
    {
        get => Q<Refresh>("refresh");
        init => Q("refresh", value);
    }
}
```

```
UpdateDocumentRequestParameters updateDocumentRequestParameters = new()
{
    Refresh = refresh
};

StringResponse response = await _elasticsearchClient.Transport.RequestAsync<StringResponse>(
    Elastic.Transport.HttpMethod.POST,
    $"{indexName}/_update/{id}",
    PostData.String(postData),
    updateDocumentRequestParameters,
    cancellationToken).ConfigureAwait(false);
```

How are we supposed to convert such code?

**Expected behavior**

**Provide `ConnectionSettings` (if relevant)**:

**Provide `DebugInformation` (if relevant)**:

**Comment by flobernd** [comment]
Hi @gpetrou,

```csharp
UpdateDocumentRequestParameters updateDocumentRequestParameters = new()
{
    Refresh = refresh
};

var pathAndQuery = updateDocumentRequestParameters.CreatePathWithQueryStrings($"{indexName}/_update/{id}",
    _elasticsearchClient.ElasticsearchClientSettings);
var endpointPath = new EndpointPath(Elastic.Transport.HttpMethod.POST, pathAndQuery);

var response = await client.Transport
    .RequestAsync<StringResponse>(
        endpointPath,
        PostData.String(""),
        null,
        null,
        default)
    .ConfigureAwait(false);
```
