### ISSUE TITLE
`TermQueryConverter` is failing to deserialize string value

### ISSUE THREAD

**Issue by MikeAlhayek** [elastic/elasticsearch-net#8432]
**Elastic.Clients.Elasticsearch version**: 
8.16.3

**Elasticsearch version**: 
8.6.1

**.NET runtime version**: 
.net9

**Description of the problem including expected versus actual behavior**:

I am trying to deserialize the following query:

```json
{
  "query": {
    "term": { "Content.ContentItem.ContentType": "BlogPost" }
  },
  "size": 3
}
```

This query string is being deserialized using the `SourceSerializer` like this:

```csharp
using var stream = new MemoryStream(Encoding.UTF8.GetBytes(query));
var request = _client.SourceSerializer.Deserialize<SearchRequest>(stream);
```

However, the code above fails to deserialize the value of the `term` query when it is provided as a string.

The following query works as expected:

```json
{
  "query": {
    "term": { "Content.ContentItem.ContentType": { "value": "BlogPost" } }
  },
  "size": 3
}
```

**Steps to reproduce**:
 1. Try to deserialize the query listed above using the code.

**Expected behavior**
I expect that the value will be deserialize from a string or from an object.

**Comment by MikeAlhayek** [comment]
@flobernd thank you for your quick response. 

> this is not considered a bug as we do not guarantee that all types are round-trip serializable.
Understood. Since there is a built in serializer, it would be nice to support "shortcut".

> PS: Please use the RequestResponseSerializer instead of the SourceSerializer 🙂

Done. With the same result (but I think you expected that too).

> PS2: The Elastic.Transport namespace provides some useful extensions to e.g. directly deserialize from a string. This saves you the MemoryStream and Encoding.GetBytes overhead.

Does the `Elastic.Transport` support "shortcut"?

**Comment by MikeAlhayek** [comment]
I ended up using Transport and directly query the server from string. 

Thanks for your help.

**Comment by flobernd** [comment]
> Done. With the same result (but I think you expected that too).

Yes, this functionality will only be available when the new serialization logic is released (early next year).

> I ended up using Transport and directly query the server from string.

This is a good workaround, especially for your use-case that involves raw string queries!
