### ISSUE TITLE
Sorting on strings, AddSortField, not_analyzed?

### ISSUE THREAD

**Issue by ghost** [elastic/elasticsearch-net#85]
I am really having a difficult time figuring out the mapping to make sorting work via NEST. From looking around, I am pretty sure I need to use a multi-field with a non-analyzed field. I've tried setting AddSortField to true on the property, then I tried creating a new property and setting it to not_analyzed and IncludeInAll to false, but each time I get the following error using something like Sort(i => i.OnField(deal => deal.Name).Ascending()).

Response:
<code>
{"error":"SearchPhaseExecutionException[Failed to execute phase [query], total failure; shardFailures {[sg4nK11YTK-ydWoktljh7g][deals][1]: RemoteTransportException[[Alcmena][inet[/10.191.252.186:9300]][search/phase/query]]; nested: QueryPhaseExecutionException[[deals][1]: query[filtered(ConstantScore(NotDeleted(cache(salesSplit.memberIds:[3088 TO 3088]) cache(salesPlanner.id:[3088 TO 3088]) cache(<ommited by me, lots of ints>)))->cache(_type:deals)],from[0],size[10],sort[<custom:\"dealName\": org.elasticsearch.index.field.data.strings.StringFieldDataType$1@38add9c9>]: Query Failed [Failed to execute main query]]; nested: IOException[Can't sort on string types with more than one value per doc, or more than one token per field]; }
</code>

Request:
<code>
{
  "from": 0,
  "size": 10,
  "sort": {
    "dealName": {
      "order": "asc"
    }
  },
  "query": {
    "bool": {
      "must": [
        {
          "constant_score": {
            "filter": {
              "or": {
                "filters": [
                  {
                    "term": {
                      "salesSplit.memberIds": "3088"
                    }
                  },
                  {
                    "term": {
                      "salesPlanner.id": "3088"
                    }
                  },
                  {
                    "terms": {
                      "harborTeamId": [
                        "2",
                       <bunch more>
                      ]
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  }
}
</code>

Model:
<code>
[ElasticProperty(AddSortField = true)]
public string Name { get; set; }

[ElasticProperty(Index = FieldIndexOption.not_analyzed, IncludeInAll = false)]
</code>

**Comment by JedatKinports** [comment]
This worked for me: `.Sort(sortDescriptor => sortDescriptor.Descending(product => product.TopProduct.Suffix("keyword")))`
