### ISSUE TITLE
Ability to display the query that is being executed in a log message / output window..

### ISSUE THREAD

**Issue by niemyjski** [elastic/elasticsearch-net#864]
It's difficult to track down what specific query is being run and you can't call ToString() or look at the output window / log to see what query is being executed by the client.. This would really help us nubs :).

**Comment by taschmidt** [comment]
Was the EnableTrace method removed?  If so, what should we use in its place?

**Comment by taschmidt** [comment]
Ok, I saw this now ([link](http://frustrateddev.com/logging-requests-from-nest-to-elasticsearch/)) but it's not exactly convenient, especially since I do use `ThrowExceptions()`.  Seems like there could be a more convenient way.
