### ISSUE TITLE
Document how to hook Log4Net, NLog, Serilog into NEST/Elasticsearch.NET

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#865]
https://github.com/elasticsearch/elasticsearch-net/issues/864

**Comment by yosz** [comment]
It's simple when you know how to do this ;) http://frustrateddev.com/logging-requests-from-nest-to-elasticsearch/

**Comment by romansp** [comment]
I published simple logging implementation from NEST/Elasticsearch.net to MiniProfiler at https://github.com/romansp/MiniProfiler.Elasticsearch. However it has an issue with logging of async api calls, will try to fix this bit later.

If I got some spare time I will PR into this repo some documentation notes for Log4Net, NLog integration hooks.

**Comment by Mpdreamz** [comment]
w00t @romansp sounds awesome! 

One thing that I noticed scanning the code quickly

https://github.com/romansp/MiniProfiler.Elasticsearch/blob/aadd5c1200def381de77cd9eed6f03613b508bd6/src/MiniProfiler.Elasticsearch/MiniProfilerElasticsearch.cs#L19

Is it possible to add all the metric requests as individual timings? That way you can see your call resulted in a ping/sniff or both and you can see all the retries more finegrained?

**Comment by romansp** [comment]
@Mpdreamz Yep, adding as individual timings is definitely possible, going to do it and extend output with RequestType. Looking forward for any other suggestions. 

Can you provide some info regarding [(S|De)serializationTime](https://github.com/elastic/elasticsearch-net/blob/682bc5293379b1c94b2e94d832fe3c7c5022e9b5/src/Elasticsearch.Net/Domain/Response/CallMetrics.cs#L9) from CallMetrics? Do they worth output?

**Comment by lakario** [comment]
@romansp I would say that those values are well-worth outputting. Personally, I've had some application performance issues which could be attributed to overly-ambitious object sizes. Seeing Serialization/Deserialization times would be very informative.

**Comment by Mpdreamz** [comment]
closing this in favor of new tracking issue: #2248
