### ISSUE TITLE
Can we get some search functionality for the documentation?

### ISSUE THREAD

**Issue by codymullins** [elastic/elasticsearch-net#966]
I am a beginner to Elastic Search in general, and have played around with Lucene for probably 3-4 weeks now. Trying to build NEST into my application, some sort of search functionality in the documentation/website would be great.

I also wouldn't mind helping to integrate the search functionality if some guidance could be given!

**Comment by Mpdreamz** [comment]
We'll most likely output our documentation into elasticsearch's documentation format soon which will come with baked in search :+1:
