### ISSUE TITLE
SuggestOption - Payload - How To Index Data In The Payload

### ISSUE THREAD

**Issue by mickdelaney** [elastic/elasticsearch-net#984]
Hi,

I want to index the id of a entity that i'm using the completion suggester with. 
the name will be the text & then a payload object would contain its id to use when selected.

as shown here: http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/search-suggesters-completion.html

is that available in NEST at the moment?

regards

**Comment by Minx-SigEp** [comment]
Follow up question. Should SuggestField.Input be a string or an IEnumerable like @mickdelaney has. If it is suppose to be a string then how do you handle multiple inputs for the same output.

**Comment by gmarz** [comment]
@Minx-SigEp it should be an IEnumerable, but would be a breaking change.  We have this issue open https://github.com/elasticsearch/elasticsearch-net/issues/1220 to address it in 2.0.

For now, you can just implement your own suggest object.

**Comment by bgiromini** [comment]
@mickdelaney Here is how I indexed the completion suggestions:

[http://stackoverflow.com/a/21887982/593214](http://stackoverflow.com/a/21887982/593214)
